### ISSUE TITLE
PolyLine Gradient

### ISSUE THREAD

**Issue by mojocakes** [react-native-maps/react-native-maps#1088]
Is it possible to use a gradient as a PolyLine stroke?

I know the gradient line could be achieved using an SVG placed on top of the map, but I'm not sure how I'd line up the map point coordinates with points of the SVG, and then compensate for any zooming/scrolling of the map.

Does anybody have an idea of how this could be achieved?

**Comment by chinloong91** [comment]
you can do it by setting the span style (natively)
example on ios using google maps.

```
-(void)setFillColor:(UIColor *)fillColor
{
  UIColor *color = [UIColor colorWithRed:52.0f/255.0f green:73.0f/255.0f blue:94.0f/255.0f alpha:1.0f];

  UIColor *toColor = [UIColor colorWithRed:255.0f/255.0f green:66.0f/255.0f blue:60.0f/255.0f alpha:1.0f];
  GMSStrokeStyle *style = [GMSStrokeStyle gradientFromColor:color toColor:toColor];

  _fillColor = color;
  _polyline.spans = @[[GMSStyleSpan spanWithStyle:style]];
}
```
gives you 

<img width="113" alt="screen shot 2017-04-17 at 1 19 35 pm" src="https://cloud.githubusercontent.com/assets/9411705/25079616/8c336fc2-2370-11e7-8fd0-182ad324b012.png">

Note: The colors from above snippet should be passed around from js bridge. And the span will overrides the stroke color.

**Comment by IjzerenHein** [comment]
I've done some work on it but never gotten around to finish it:
https://github.com/IjzerenHein/react-native-maps/tree/feature-gradientpolyline3

**Comment by IjzerenHein** [comment]
Just added the PR for this on iOS/MapKit: #1911
