### ISSUE TITLE
Overlapping markers being pressed will trigger onSelect multiple times

### ISSUE THREAD

**Issue by MarsWang42** [react-native-maps/react-native-maps#1353]
Each press will trigger multiple markers select event. Tried `event.stopPropagation` and `event.preventDefault` but does not work. Any clue?

![k0zbp6aang](https://cloud.githubusercontent.com/assets/14301745/26279593/a689263a-3d6c-11e7-8684-1e2ca7c414d8.gif)

**Comment by Marswang92** [comment]
Any clue how to solve it? Very annoying. I'm using `react-native-maps` on `0.15.2` and `react native` `0.44.0`.

**Comment by carlo-** [comment]
This happens because the method `_handleTap` in the objc class AIRMapMarker calls `[marker.map selectAnnotation:marker animated:NO]`, which triggers `showCalloutView` again (sometimes on a different marker if they are too close, I'm guessing that's just how MKMapView works).  The call to `selectAnnotation ` should be removed in my opinion.

**Comment by Marswang92** [comment]
@carlo- thanks! I'm not really a swift guy, shall we also get some other ppl's attention or prolly make a PR on it?

**Comment by carlo-** [comment]
@Marswang92 yes! Although I'm not sure what are all of the side effects that could appear by removing that line, I only know that it fixes this problem in my situation.

**Comment by Marswang92** [comment]
@yonahforst Hey man I noticed your issue https://github.com/airbnb/react-native-maps/issues/436 and added that line `[marker.map selectAnnotation:marker animated:NO]`. Any reason for that? Cuz it seems like to be the cause of my issue, thanks for any help!

**Comment by yonahforst** [comment]
Hey @Marswang92, I added it because `onSelect` wasn't being called when tapping on a marker's subview. 

I just tested it again in RN 0.44, and I'm experiencing something similar to you guys. What's weird is that the callout jumps to a nearby marker, but the `onPress` event of that second marker is _not_ fired.

**Comment by zolrath** [comment]
This is currently biting me as well. This didn't happen a few versions ago but while using the new version of expo tapping on markers that are close to each other is an exercise in frustration.

Focus jumps back and forth between the markers that are in close proximity, making it quite hard to get the callout you want.

**Comment by xiaoTuiMao** [comment]
+1

**Comment by esutton** [comment]
[Off-topic] How can you allow individual selection of densely packed or over-lapping markers?  

Is this called clustering?  Are there solutions to implement  in react-native-maps ?

![mapsmania](https://user-images.githubusercontent.com/6115047/28969468-509b11ac-78ea-11e7-8e44-6da943f31184.png)

**Comment by jarnell** [comment]
Did anyone figure out a solution or workaround to this yet?

**Comment by jeffreychuc** [comment]
Seeing this issue with this package list
```
    "haversine": "^1.1.0",
    "native-base": "^2.3.5",
    "react": "^16.2.0",
    "react-native": "^0.51.0",
    "react-native-animatable": "^1.2.4",
    "react-native-auth0": "^1.2.1",
    "react-native-dismiss-keyboard": "^1.0.0",
    "react-native-maps": "^0.18.3",
    "react-native-sensitive-info": "^5.1.0",
    "react-native-sentry": "^0.31.0",
    "react-native-sliding-up-panel": "^1.1.12",
    "react-native-triangle": "0.0.9",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "rn-sliding-up-panel": "^1.1.7",
    "shortid": "^2.2.8"
```

**Comment by lumenlunae** [comment]
Would this be fixed by setting AIRMapMarker.m:189 to
`tapGestureRecognizer.cancelsTouchesInView = YES;`
?
It's currently NO so the map marker touches propagate.

**Comment by ratkus91** [comment]
Does anyone have any idea how to fix this?

**Comment by Andre-JierongLuo** [comment]
any updates on this issue?

**Comment by switch13** [comment]
Any news?

**Comment by filmhomage** [comment]
Same issue. Any updates or news?

**Comment by dragonza** [comment]
Any update on this issue? I also encounter this problem. Switching to google map solved the problem but my client declined to use it. :(

**Comment by NoahFiner** [comment]
Any updates?

**Comment by gunnarrb** [comment]
Hi guys, is there an update on this issue?

**Comment by cjsh** [comment]
> clustering
Have you solved this problem?

**Comment by andrewtelkamp** [comment]
Not trying to add another 'Any updates' comment, but any updates?

**Comment by RyanTG** [comment]
Have you tried: `pointerEvents="auto”`

In the Marker? That fixed it for me.

**Comment by esutton** [comment]
@RyanTG  Sadly `pointerEvents="auto”` did not change double-popups on iOS.

Thanks for the tip.  It was worth a try.

I tried various combinations of setting top marker to "auto" and nested to "none" and visa versa.
````
    const pinList = this.state.showPins ? (
      this.state.markers.list.map(marker => (
        <MapView.Marker
          pointerEvents="auto"
          ref={(ref) => {
            this._markerRefs[marker.label] = ref;
          }}
          key={marker.key}
          coordinate={marker.coordinate}
          pinColor={marker.color}
          tracksViewChanges={false}
          onPress={() => this.onMarkerPress(marker)}
          onSelect={() => this.onMarkerSelect(marker)}
          onCalloutPress={this.onCalloutPress}
        >

          <MapView.Callout
            pointerEvents="none"
            style={{ flex: -1, position: 'absolute', width: 250 }}
            tooltip={false}
          >
            <MapCalloutGps
              pointerEvents="none"
              {...this.props}
              marker={marker}
              onCalloutClose={() => {
                console.log('dbg: onCalloutClose');
                // this.onCalloutClose(marker);
              }}

              themeStyle={themeStyle}
              unitType={this.props.state.unitDepthType}
            />
          </MapView.Callout>
        </MapView.Marker>
      ))
    ) : null;
````

**Comment by jordymeow** [comment]
In my case, `pointerEvents="auto”` worked but it's not as snappy without it, there is maybe half a second (or actually, almost a second) between the press and the display of the label. Would be really awesome to see this fixed rather than looking for workarounds.

**Comment by devdane** [comment]
Has there been any progress on this bug? It's iOS-specific. @jordymeow the solution that worked for you did not work for me!

**Comment by JoostSlijkoort** [comment]
@jordymeow's solution works for me, but indeed makes it all less snappy; it takes some time for the callout to appear.

**Comment by 18clans** [comment]
@jordymeow `pointerEvents="auto"` does not work for me.  This disables any interaction on my map.

**Comment by 18clans** [comment]
@jordymeow This works great for me!

**Comment by rodionovich221** [comment]
> Have you tried: `pointerEvents="auto”`
> 
> In the Marker? That fixed it for me.

This works for me as well!

**Comment by switz** [comment]
Hmm that `pointerEvents="auto"` flag didn't fix it for me. Would really love to see a fix for this.

**Comment by DChiuch** [comment]
`pointerEvents="auto"` also doesn't work for me. Would love to see a fix for this.

**Comment by gmonte** [comment]
> @jordymeow's solution works for me, but indeed makes it all less snappy; it takes some time for the callout to appear.

Feb 21 and I'm facing the same behavior.

Please don't close this issue. Up.

**Comment by MoOx** [comment]
This issue is still a problem and should be reopened.

**Comment by MoOx** [comment]
`pointerEvents="auto"` seems to make you unable to rely on `onPress` which are now randomly called... Not a solid workaround.

If you don't use `onSelect` prop, you should definitely remove what is added in this PR: https://github.com/react-native-maps/react-native-maps/pull/1079
Using [patch-package](https://www.npmjs.com/package/patch-package) make this easy!

I ended up with this in 

`patches/react-native-maps+0.26.1.patch`

```diff
diff --git a/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.m b/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.m
index d90f89c..6f36b28 100644
--- a/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.m
+++ b/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.m
@@ -259,7 +259,10 @@ - (void)_handleTap:(UITapGestureRecognizer *)recognizer {
     if (marker.onPress) marker.onPress(event);
     if (marker.map.onMarkerPress) marker.map.onMarkerPress(event);
     
-    [marker.map selectAnnotation:marker animated:NO];
+    // https://github.com/react-native-maps/react-native-maps/issues/1353#issuecomment-306323721
+    // disable as we don't use onSelect
+    // this is to prevent the double callout bug
+    // [marker.map selectAnnotation:marker animated:NO];
 }
 
 - (void)hideCalloutView
```

**Comment by holyris** [comment]
Still facing this issue, version 0.31.1

**Comment by jadonhansen** [comment]
Not really a solution for the problem but a viable workaround: 

I am displaying multiple pins/markers for a user who has the same location, so naturally the markers will render on top of each other.

I offset the coordinate of each marker by a small amount each time, this will result in the pins being closely grouped but further enough away (once zoomed-in) for each to be tapped on and only activate its' relevant callout.


Render:
```
			<MapView
				// mapview props here
			>
				{ filteredPosts &&
					filteredPosts.map((post: SearchResult, i: number) => {
						return (
							<Marker
								key={i}
								coordinate={calculateCoordinateOffset(post.approximateLocation, filteredPosts, i)}
								description={post.item.category}
								title="Tap to view task"
								onPress={logMarkerPress}
								onCalloutPress={(event: CalloutPressEvent) => showModal(event)}
							/>
						);
					})
				}
			</MapView>
```

calculateCoordinateOffset function:
```
	const calculateCoordinateOffset = (approximateLocation: UserLocation, filteredPosts: SearchResult[], i: number): LatLng => {
		if (i == 0) return { latitude: approximateLocation.latitude, longitude: approximateLocation.longitude };

		const previous = filteredPosts[i - 1];

		if (approximateLocation.latitude == previous.approximateLocation.latitude &&
			approximateLocation.longitude == previous.approximateLocation.longitude) {

			return { latitude: approximateLocation.latitude + 0.001 * i, longitude: approximateLocation.longitude + 0.001 * i };
		}

		return { latitude: approximateLocation.latitude, longitude: approximateLocation.longitude };
	};
```

The above function has an edge case where some markers could still be rendered on top of each other. Working on it

**Comment by JackFord18** [comment]
Any update on this? @jordymeow 's solution works but has a noticeable delay as mentioned. @MoOx 's solution did not work for me.

**Comment by rokamon1997** [comment]
Still having this issue in 2023... Setting the pointerEvents to auto did not work in my case. Anyone knows of another workaround?

**Comment by jonathonor** [comment]
Still experiencing this issue... pointerEvents="auto" did not work.

**Comment by tpaksu** [comment]
I want to ask a different question.. Any updates?

**Comment by JaRoMasterDev** [comment]
I am still experiencing this issue on iOS with react-native-maps@1.22.6 and Expo SDK 53.0.0-preview.11. Are there any updates?

**Comment by CostasCF** [comment]
any updates on this?
