### ISSUE TITLE
Support for UWP

### ISSUE THREAD

**Issue by Noitidart** [react-native-maps/react-native-maps#1456]
The docs on react-native windows says that their `MapView` was deprecated in favor of this module here - https://github.com/Microsoft/react-native-windows/blob/master/docs/CoreParityStatus.md

![](http://i.imgur.com/yGg1wIZ.png)

The readme here does not mention UWP (universal windows platform). Is this something that needs to be updated? Does react-native-maps support UWP?

**Comment by christopherdro** [comment]
This project currently only supports iOS and Android.

**Comment by Noitidart** [comment]
Thanks @christopherdro for the reply. Are their plans to support MapView in the future? Or should we report to the UWP team that they need to come up with their own solution?

**Comment by christopherdro** [comment]
I doubt there will be any support for windows from this library.

**Comment by Noitidart** [comment]
Thanks sir I will share this info and see if they can help out.

**Comment by matthargett** [comment]
May I inquire as to why? Are you implying you wouldn't take a PR to that adds support for other RN platforms?

**Comment by christopherdro** [comment]
@matthargett Of course not! Sorry, what I meant was that I wouldn't expect the internal team to provide windows support anytime soon. 

I'll reopen this ticket and label it appropriately to continue tracking support for UWP.

**Comment by npmun** [comment]
Is there an alternative way to display simple map component on UWP app at the moment?

**Comment by Ash-faq** [comment]
is this issue solved?

**Comment by Ash-faq** [comment]
Need Support for UWP

**Comment by emad-ir** [comment]
Any updates on this issue? Does react-native-maps support UWP projects?

**Comment by capc0** [comment]
request to re-open.
