### ISSUE TITLE
Modify polyline without rendering the entire map

### ISSUE THREAD

**Issue by salbatoress** [react-native-maps/react-native-maps#1494]
Is there any way to modify a polyline without rerender the all map?

**Comment by PawanWagh** [comment]
same issue here.
After fetching latest polylines from google directions, rendering causes whole map UI unresponsive.

**Comment by bramus** [comment]
> After fetching latest polylines from google directions, rendering causes whole map UI unresponsive.

Be sure to take a peek at https://github.com/bramus/react-native-maps-directions, a library that handles directions/routing for you. Perhaps that will solve your issue?
