### ISSUE TITLE
Cant drag map on ios apple maps when using markers with image/custom view

### ISSUE THREAD

**Issue by alexbuicescu** [react-native-maps/react-native-maps#1539]
If I use a marker with image or a custom view, then i can not drag the map if clicking on the marker. This becomes a bigger problem if there are many markers on the map, and there isn't much space left to drag the map. 

I created a sample repo to demonstrate the problem.
https://github.com/alexbuicescu/react-native-maps-example

**Comment by mtt87** [comment]
+1 here
Unfortunately it's a problem you don't notice it until you have 10+ marker on the map 😢

**Comment by delvedor** [comment]
Same problem here, under Android everything works well.

React Native: `v0.47.1`
Maps: `v0.16.0`

**Comment by mtt87** [comment]
I confirm this only affects iOS not Android

**Comment by delvedor** [comment]
I made some test, and the issue starts after 045ec7eee5f90d06b00f1eb624453d6a7d02df92.
But you will note it only after this one dd1b8aa9499769dda008cbba464ea9b7a5c21369, because the above commit will cause compilation errors.

cc @Benjamin-Dobell @foyarash @christopherdro
https://github.com/airbnb/react-native-maps/pull/1360 https://github.com/airbnb/react-native-maps/pull/1485

**Comment by compojoom** [comment]
@delvedor - I doubt that the issue starts with the commits you mention. I Have this behavior for a year now. Initially I switched to google maps - there we don't have the issue, but we have another bug - high CPU usage, so it's a no go on iOS :(... 

Is this something we can fix? You don't need to have 100 markers for this. Even if you have one custom marker and you won't be able to drag the map when the drag initiates on the marker view. So I guess that nearly everyone is affected by this, just very few are noticing this.

**Comment by hkxicor** [comment]
Same problem
any solutions ?

**Comment by mtt87** [comment]
For some unknown reason it works now fine for me.

`react-native-maps: 0.15.3` `react-native:0.46.4`

**Comment by compojoom** [comment]
@mtt87 - okay strange. I'm on 0.16.3 with rn 0.47.2 and I experience this. And as I said above -we always had this...

**Comment by mtt87** [comment]
@compojoom yeah it's really strange, I can't tell why it works now and it's been a month I think already.
I haven't done any change to the code regarding maps. 

Anyway I will soon try https://github.com/mapbox/react-native-mapbox-gl as I've heard it's much more stable and working as expected.

**Comment by vemundeldegard** [comment]
Having this issue as well. Very frustrating. Need to find a workaround for iOS because markers can't be used, it makes it so userunfriendly..

**Comment by ruankranz** [comment]
Also having this issue on `react-native: 0.58.6` and `react-native-maps: 0.22.1`
