### ISSUE TITLE
Proposal: Use library to allow interactive Android callouts

### ISSUE THREAD

**Issue by hubConnect** [react-native-maps/react-native-maps#1556]
There are many issues that have been posted by users confused that their callouts have interactive elements on iOS, but not on Android. We'd like to integrate a library [InteractiveInfoWindowAndroid](https://github.com/Appolica/InteractiveInfoWindowAndroid) to allow this and would like to know if there is interest and that it would be mergeable.

**Comment by cinder92** [comment]
@hubConnect i think with `Custom Callout` you can do it.

**Comment by mickadoua** [comment]
same issue, i can't clic on callout's button 
here is my code 

```
<MapView.Callout tooltip style={[styles.customCalloutContainer]}>
    <CustomCallout  refMarker={this.marker} title={this.props.starPlaces[key].name} tags={this.props.starPlaces[key].tags} />
</MapView.Callout>
```

```
export default class CustomCallout extends React.Component {
    render() {
        return (
            <View style={globalStyle.shadow}>
                        <TouchableOpacity style={styles.starButton} onPress={() => {
                            console.log('starButton')
                        }}  >
                            <Icon
                                size={30}
                                type="font-awesome"
                                name="star"
                                color={Colors.star} 
                            />
                        </TouchableOpacity>
...
```

**Comment by jorgutdev** [comment]
I will try to fork this repo to disable the Touchable Opacity around the MapView.Callout, AirBnb engineers talked about this in [this issue](https://github.com/airbnb/react-native-maps/issues/1280)

**Comment by tonygriv** [comment]
Any news about this?

**Comment by AndersenTobias** [comment]
Are callouts supposed to allow interaction on iOS already? Because I have something like the following, but the event handler isn't called:
```
<View>
    <View onTouchStart={() => console.log('Clicked!')}><Text>Test</Text></View>
</View>
```

**Comment by warash** [comment]
any news on that? i am also waiting for this option to have onTouchStart working on markers on Android

**Comment by pawan8525** [comment]
i implemented cluster on react-native-map in mobile app but my requirement is like below , i dont know it is possible in react-native-map or not. Please help me team
Thank you for your kind cooperation.
First part show cluster that i implemented very well.
![image](https://user-images.githubusercontent.com/38987561/44912389-980be600-ad47-11e8-9cdb-8e0bd64294d9.png)


second part when press on cluster icon it show hidden marker that is almost on same location that i don't know how to implement please see image

![image](https://user-images.githubusercontent.com/38987561/44912415-ac4fe300-ad47-11e8-952c-5382c6d7be0f.png)


Please if any plugin in react-native that help me. Thank you in advance

**Comment by swapanil** [comment]
> There are many issues that have been posted by users confused that their callouts have interactive elements on iOS, but not on Android. We'd like to integrate a library [InteractiveInfoWindowAndroid](https://github.com/Appolica/InteractiveInfoWindowAndroid) to allow this and would like to know if there is interest and that it would be mergeable.

Have you integrated that library?

**Comment by swapanil** [comment]
> There are many issues that have been posted by users confused that their callouts have interactive elements on iOS, but not on Android. We'd like to integrate a library [InteractiveInfoWindowAndroid](https://github.com/Appolica/InteractiveInfoWindowAndroid) to allow this and would like to know if there is interest and that it would be mergeable.

@hubConnect  Have you integrated that library?

**Comment by Atom1er** [comment]
Any news on that?

**Comment by alperenkarip** [comment]
Any news about this?
