### ISSUE TITLE
how detect onRegionChangeComplete is user action or animation?

### ISSUE THREAD

**Issue by kdong007** [react-native-maps/react-native-maps#1620]
After I call `fitToCoordinates` on map, `onRegionChangeComplete` is also triggered. Then how does `onRegionChangeComplete` know if the change event is from user action or auto animation?

**Comment by heysailor** [comment]
It'd be nice, sure. As a workaround, I set an `animation` variable `true` before firing a method like `fitToCoordinates`, and set it back to `false` after the duration of the animation using `setTimeout`.

Then in `onRegionChangeComplete` I can check if the change was due to an animation or from user input.

**Comment by MoOx** [comment]
I have to admit it can be pretty annoying... I would expect that onRegionChangeComplete is only called on user interaction.
I think now that we have a flag with onMapReady, onRegionChange(Complete) should not be triggered until the map is ready.

**Comment by IjzerenHein** [comment]
On Android, this is possible with the new Google Maps `onCameraMoveStartedListeners` API. Some work has been done in PR #1710 to support this, but it still needs to be added the `onRegionChange` API and propagated to JS. And obviously, iOS support needs to be added for this as well.

**Comment by Jun711** [comment]
I think when 'adding new markers to the map' action is done, it fires onRegionChangeComplete too. Is that right?

**Comment by outaTiME** [comment]
So? any update? 
im dealing with this issue on iOS the onRegionChangeComplete method fires intermittently but on Android fires according each region update.

Any way to achieve that? thanks !!!

**Comment by z4qx** [comment]
Same problem for me. Please can you provide a real solution like another callback ?

**Comment by harrisrobin** [comment]
Mapbox provides a [bool](https://github.com/react-native-mapbox-gl/maps/blob/c675b0566480656b84880be5418639bcb382e463/example/src/examples/ShowRegionDidChange.js#L122) in the event object, but would be nice to have something similar here!

**Comment by yairopro** [comment]
Any news about this issue ?
Any workaround to distinct user action from animation ?

**Comment by yairopro** [comment]
🐸

**Comment by yairopro** [comment]
🐼

**Comment by yairopro** [comment]
🐸

**Comment by aliwaqar981** [comment]
Anyone found solution for this?

**Comment by yairopro** [comment]
@aliwaqar981 

```jacascript
function onRegionChangeComplete(region, {isGesture}){
  if (isGesture){
    // ...
  }
}
```
