### ISSUE TITLE
MapView onPress() is fired when I hit marker ! (iosMaps only)

### ISSUE THREAD

**Issue by leadeg** [react-native-maps/react-native-maps#1689]
Hello, I put onPress method both marker and map view. On android, marker onPress work fine, it dont fires mapView 's onPress(), but IOS do.. Logically, MapView's onPress should not be fired when I hit just marker(I am 100% sure that I am not hitting Map, I zoomed into marker 500% and only hit marker). How can I handle it ? Any idea? Is it an issue ?

**Comment by kelset** [comment]
Can you show the code that "fires" that onpress? Maybe the whole component?

**Comment by emregurler** [comment]
Here is my code: 
 ```
<View style={Style.container} onLayout={this.navigationParams.markers ? this.fitMarkers : null}>
                <MapView
                    ref={(map: any) => this.map = map}
                    style={Style.container}
                    onPress={() => { this.onMapPress() }}
                    onLongPress={() => this.onLongPress()}
                    rotateEnabled={false}
                    pitchEnabled={false}
                    toolbarEnabled={false}
                    initialRegion={this.navigationParams.markers ? null : turkeyRegion}
                >
                    {
                        // Eğer navigationdan gelen noktalar kümesi varsa onu çizdir
                        this.navigationParams.markers &&
                        map(this.navigationParams.markers, (marker: GeoMarker, index: number) => {
                            return (
                                <Marker key={index} coordinate={marker.coordinate}
                                    onPress={() => { this.onMarkerPress(index) }}>
                                </Marker>
                            )
                        })
                    }
                </MapView>
    .
    .
```
Does onMapPress() work properly in your case ?  I think GoogleMap can understand that are you pressed map or only marker, but ios Maps can not

**Comment by bzm97** [comment]
Hi, got the same issue. It appears you could use `MapView`'s `onMarkerPress` callback to handle marker taps correctly on iOS, not `Marker`'s `onPress`.

Use identifier `<Marker identifier={index.toString()}>` to distinct markers within callback:
```javascript
  onMarkerPress = (event: any) => {
    const index = parseInt(event.nativeEvent.id, 10);
    if (isNan(index)) {
      return;
    }
    ...
```

**Comment by alvelig** [comment]
#114

**Comment by bluenex** [comment]
@bzm97 I don't think that is what @emregurler wants. The problem is all `MapView.onPress()`, `Marker.onPress()` and also `MapView.onMarkerPress()` are triggered when pressing on a Marker. This is not logical as pressing on Marker shouldn't trigger MapView's press.

**Comment by danbockapps** [comment]
My workaround for this is to create a boolean class variable called userJustPressedMarker, initialized to false. In the marker's onPress function, if `Platform.OS === 'ios'` I set it to true. In the MapView's onPress function, I wrap all the code inside `if (!this.userJustPressedMarker) { /* do stuff */ }` and at the end I set it to false.

**Comment by andrewtelkamp** [comment]
@danbockapps is that actually working? How are you ensuring your sequence of events? Like how are you sure your markerPress event handler is firing/setting state prior to the MapView's onPress?

**Comment by danbockapps** [comment]
@andrewtelkamp Yes, it's working. I'm using a class variable, not a state variable, so I don't have to worry about state getting set.

I guess react-native-maps doesn't promise to always call the marker's onPress function before the MapView's onPress function, but that does seem to be the order it always calls them in.

**Comment by sbichenko** [comment]
You can use `event.nativeEvent.action === 'marker-press'` to check whether a marker was pressed or not.

**Comment by alexpanov** [comment]
> You can use `event.nativeEvent.action === 'marker-press'` in the `onPress` handler to check whether a marker was pressed or not.

Genius!

**Comment by EhsanSarshar** [comment]
you can check by marker identifier

```
<Marker onPress={handleMarker} identifier="23af23" />
handleMarker = (e) => {
   let id = e.nativeEvent.id
}
```

**Comment by EhsanSarshar** [comment]
<Marker onPress={handleMarker}  identifier="234af"/>

handleMarker = (e) => {
   // stop onPress event from propagating to mapView
    e.stopPropagation();
    // determine which marker pressed
    let id = e.nativeEvent.id
}

**Comment by EhsanSarshar** [comment]
<Marker onPress={handleMarker}  identifier="234af"/>

```
handleMarker = (e) => {
   // stop onPress event from propagating to mapView
    e.stopPropagation();
    // determine which marker pressed
    let id = e.nativeEvent.id
}
```

**Comment by richardbumm** [comment]
This is called bubbling. It's common in touch applications and needs to be handled with propagation events.

Read this: https://javascript.info/bubbling-and-capturing

**Comment by FeMaffezzolli** [comment]
> You can use `event.nativeEvent.action === 'marker-press'` in the `onPress` handler to check whether a marker was pressed or not.

That's it. Thank you!
