### ISSUE TITLE
Rotation Prop not working on Animated Marker

### ISSUE THREAD

**Issue by juergengunz** [react-native-maps/react-native-maps#1701]
The rotation property on Marker.Animated is not working properly an throws a warning to use the rotate style property. On the normal Marker it is working and even animating.

**Comment by vk2142** [comment]
I'm having the same problem, did you find solution?

**Comment by alvelig** [comment]
@vk2142 could you please provide a minimum reproducible example and fill this issue according to the new template please, and so we can review it.

**Comment by ramsestom** [comment]
If you take the code example for animated markers provided in the readme page and add a rotation property:

```
import Mapview, { AnimatedRegion, Marker } from 'react-native-maps';

getInitialState() {
  return {
    coordinate: new AnimatedRegion({
      latitude: LATITUDE,
      longitude: LONGITUDE,
    }),
  };
}

componentWillReceiveProps(nextProps) {
  const duration = 500

  if (this.props.coordinate !== nextProps.coordinate) {
    if (Platform.OS === 'android') {
      if (this.marker) {
        this.marker._component.animateMarkerToCoordinate(
          nextProps.coordinate,
          duration
        );
      }
    } else {
      this.state.coordinate.timing({
        ...nextProps.coordinate,
        duration
      }).start();
    }
  }
}

render() {
  return (
    <MapView initialRegion={...}>
      <MapView.Marker.Animated
        ref={marker => { this.marker = marker }}
        coordinate={this.state.coordinate}
        rotation = {45}
      />
    </MapView>
  );
}
```

Here is the error message you obtain:

> You are setting the style `{ rotation: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { rotation: ... } }`
> YellowBox.js:82
> 

tested on android with react 16.2.0, react-native 0.53.3 and react-native-maps 0.20.1

**Comment by TitanKing** [comment]
@ramsestom This is actually incorrect, the rotation will not animate if you do this, it is preferred to not re-render the markers in the first place even if you are satisfied with a jerky rotation. I will investigate if perhaps react-natives native animation library can be used.

**Comment by TitanKing** [comment]
@ramsestom Actually, my bad, it does work.

**Comment by CrisHemswerthThor** [comment]
I am also getting through it and it is really frustrating. In my case it is shown in IOS but not on android.
Is there any update on this issue?

**Comment by ribamarsantos** [comment]
Using: 
react-native-maps: 0.24.2
react-native": 0.59.10

props rotation is working for both Android and iOS.(But I got the warning to use nested in a style object).
When I do that it just works for Android and not iOS.

**Comment by rosnaib11** [comment]
Whats the alternative for this?

**Comment by rosnaib11** [comment]
Nvm `style transform` works fine

```
<Marker.Animated
  title="Pickup"
  coordinate={moving_coordinates}
  identifier={asset_details && asset_details.AssetID}
  ref={ref => {
    this.markerRef = ref;
  }}
  style={{
    transform: [{rotate: `${50}deg`}]
  }}
  tracksViewChanges={false}
  icon={require("../../assets/images/assets/cars/car_top_view_2d.png")}
>

</Marker.Animated> 
```

**Comment by doylemark** [comment]
I found the above solution doesn't work properly as if you pan the Marker out of view by ~800km, the transform style is unloaded
