### ISSUE TITLE
Compass does not show up on map

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-native-maps/react-native-maps#1735]
I've got my map fully rendered and usable but the compass never shows up. Here is an example of my map:
```
<MapView
  customMapStyle={darkBlueMap}
  moveOnMarkerPress={false}
  provider={PROVIDER_GOOGLE}
  ref={ref => this.mapView = ref}
  showsCompass={true}
  style={styles.mapView}>
  {...}
</MapView>
```
Here is what my map looks like:
<img width="400" alt="screen shot 2017-10-25 at 2 01 11 pm" src="https://user-images.githubusercontent.com/11371200/32020412-54c8e7a2-b98d-11e7-959d-607159025130.png">

I've added my own re-center button to the bottom but the compass doesn't show up anywhere. Anyone have any idea on why?

react-native: 0.44.3
react-native-maps: 0.16.2

**Comment by alvelig** [comment]
Compass is hidden when pointing to the north.

**Comment by RyanMitchellWilson** [comment]
That should be documented then. In your docs it says if `showCompass` is set to true it will show. Does not mention that it does not show when pointing north.

**Comment by alvelig** [comment]
We need to document this. @RyanMitchellWilson could you help with it? 

We need to test: 

- [ ] iOS Apple Maps 
- [ ] iOS Google Maps
- [ ] Android Google Maps

**Comment by RyanMitchellWilson** [comment]
I wish I could but I'm currently on a really tight deadline at work till mid-january. I might be able to help out after that.

**Comment by remeryAGS** [comment]
I disagree with the sentiment here. If `showComapss` is set to true, the compass should be shown. The current behavior could be more accurately described as `showCompassOnRotate` or something similar.

Incidentally, I came here looking for a way to always show the compass even when facing north.

**Comment by angelos3lex** [comment]
@remeryAGS have you found a solution to always show the compass?

**Comment by remeryAGS** [comment]
@angelos3lex Unfortunately no. I gave up and moved on to other issues.

**Comment by craigcosmo** [comment]
agree with @remeryAGS , I think showsCompass={true} should always show compass regardless where you pointing.

**Comment by Donclion911** [comment]
replace mapview with this ClusteredMapView this component.

**Comment by Balasnest** [comment]
When I set `showCompass` to true, its not showing. Even when its disable, top left corner is not allowing to touch when a marker in the viewport. I guess its just hidden the image, but not removed entire view.

<img width="1145" alt="Screenshot 2019-08-28 at 4 18 22 PM" src="https://user-images.githubusercontent.com/6050520/63849900-a3244100-c9b0-11e9-9166-18309c654e0f.png">

**Comment by askpatrickw** [comment]
A great graph would be issues the bot closes which have >2 comments vs. issued closed by a PR.

**Comment by vigneshkumaran-github** [comment]
same issue I need to move the compass....

**Comment by Mik1337** [comment]
is there a workaround to this ?
