### ISSUE TITLE
onPressOut event as a counter to onPress and onPanDrag

### ISSUE THREAD

**Issue by JPTeasdale** [react-native-maps/react-native-maps#1770]
Would be cool to know when the user releases the touch.

**Comment by alvelig** [comment]
Can you please describe a business case for that?

**Comment by JPTeasdale** [comment]
If you wanted to implement snapback, where you press and drag, but then let go and it pulls back to where you started.

**Comment by imjaad9090** [comment]
You are right ,,i am looking for an event like onPanDragEnd but no success :/

**Comment by matikups** [comment]
Actually it can be very cool for dragging the map to any location, and when it taps out, it loads business from around that location.

**Comment by olivergeorge** [comment]
My use case for this was knowing the user had finished drawing a polygon so I could "end" drawing mode and re-enable zooming/moving map.

**Comment by prashantvv** [comment]
Well as I working on it ri8 now I figure out that onRegionChangeComplete() is called at the end of every onPanDrag(). You can use this instead of onPanDragEnd()

**Comment by eightyfive** [comment]
```js

  const [dragging, setDragging] = useState(false);
  const [position, setPosition] = useState({ lat: null, lng: null });

  // "onPanDragEnd"
  const onRegionChangeComplete = ({ latitude, longitude }) => {
    if (dragging) {
      setPosition({ lat: latitude, lng: longitude });
      setDragging(false);
    }
  };

  const onPanDrag = ev => {
    setDragging(true);
  };
```

**Comment by olivergeorge** [comment]
Thanks @eightyfive - I'll need to work through details to understand what you are suggesting but it sounds hopeful.

**Comment by bargald** [comment]
onRegionChangeComplete is not called after onPanDrag, it is called if a region is changed. 

In my case I use onPanDrag to draw on the map and I set scrollEnabled to false so I still need an onPanDragEnd callback.

**Comment by wolfzer44** [comment]
My solution for it:

```javascript 
function useDebounce(callback, delay) {
    const debouncedFn = useCallback(
      debounce((...args) => callback(...args), delay),
      [delay] 
    );
    return debouncedFn;
  }

 const onPanDragEnd = useDebounce((e: MapEvent) => alert('finished'), 200);
 const handleDraw = (e: MapEvent) => {
    onPanDragEnd(e);
}`
