### ISSUE TITLE
Custom Callout is not rendering centered above my Custom Marker when Marker isn't full in viewport.

### ISSUE THREAD

**Issue by mafiusu** [react-native-maps/react-native-maps#1810]
Hello there I have a Custom Marker and styled it like a rectangle. I expect that the Callout is always showing centered above my Custom Marker. BUT if the Custom Marker is not in full in viewport the Callout aligns left or right above my Custom Marker. 

Problem is on iOS.
```
          <Marker coordinate={{latitude: LAT, longitude: LONG}}>
            <View style={styles.customMarker}>
              <Text style={styles.customTextMarker}>Some Text</Text>
            </View>
            <View style={styles.customMarkerTriangle}/>
            <Callout tooltip={true}>
              <View >
                <Image style={styles.calloutImage} source={require('./assets/300x300.png')}/>
              </View>
            </Callout>
          </Marker>
```

### Is this a bug report?

Yes (View-Bug)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.51.0
react: 16.0.0
react-native-maps: 0.19.0 or "git+ssh://git@github.com/react-community/react-native-maps.git"

### Steps to Reproduce

1.
Fork https://github.com/react-community/react-native-maps.git or download (zip)

2. 
Getting the example running using [this instruction](https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md) from the doc

3.
Example App is running, then click on **Custom Callouts** and move the map, so that the left Marker aligns on the left edge from the Device-Screen. (see screenshots below)

![simulator screen shot - iphone 6 - 2018-02-26 at 17 32 58](https://user-images.githubusercontent.com/33623047/36682358-2452184c-1b1b-11e8-905d-71b86a620f6d.png)

Then click on the Marker and you will see the problem with the custom callout not aligning centered above the Marker.

![simulator screen shot - iphone 6 - 2018-02-26 at 17 34 27](https://user-images.githubusercontent.com/33623047/36682416-55755290-1b1b-11e8-9a9f-e123e05dd009.png)

### Expected Behavior

Callouts renders centered above the Markers like in Android. 

### Actual Behavior

Callouts (Custom Callouts) are not aligning centered above the Marker IF the Marker is nearly on the edge of the screen.

(See the screenshots above)

**Comment by alvelig** [comment]
@mafiusu Could you please fork https://github.com/alvelig/react-native-maps-example and reproduce the problem.

**Comment by mafiusu** [comment]
@alvelig I tried it but the bug I described above is sill there. I will show you an example of the specific bug in the images below.

<img width="193" alt="bildschirmfoto 2017-12-21 um 10 33 18" src="https://user-images.githubusercontent.com/33623047/34249654-c409564a-e63a-11e7-96a5-52814b6de9da.png">

<img width="296" alt="bildschirmfoto 2017-12-21 um 10 33 26" src="https://user-images.githubusercontent.com/33623047/34249655-c430c400-e63a-11e7-96ed-53f598eb0c41.png">

Expected Results: The Callout has to be centered above the custom Marker even it is not full in viewport.

**Comment by alvelig** [comment]
I meant this: 
>    * Issues without reproducible demos have a very low priority.
>    * The person fixing the bug would have to do that anyway. Please be respectful of their time.

**Comment by rborn** [comment]
@mafiusu please update the issue with the code to reproduce the problem and following the template. Once it's done ping me and  I'll reopen it. Thank you.

**Comment by mafiusu** [comment]
@rborn my start post is updated with the issue template. Hope it's looking good.

**Comment by mafiusu** [comment]
In `SMCalloutView.m` you can find the following code

```
    // we prefer to sit centered directly above our anchor
    CGFloat calloutX = roundf(anchorX - self.frameWidth / 2);

    // but not if it's going to get too close to the edge of our constraints
    if (calloutX < constrainedRect.origin.x)
        calloutX = constrainedRect.origin.x;

    if (calloutX > constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth)
        calloutX = constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth;

    // what's the farthest to the left and right that we could point to, given our background image constraints?
    CGFloat minPointX = calloutX + self.backgroundView.anchorMargin;
    CGFloat maxPointX = calloutX + self.frameWidth - self.backgroundView.anchorMargin;

    // we may need to scoot over to the left or right to point at the correct spot
    CGFloat adjustX = 0;
    if (anchorX < minPointX) adjustX = anchorX - minPointX;
    if (anchorX > maxPointX) adjustX = anchorX - maxPointX;

    // add the callout to the given layer (or view if possible, to receive touch events)
    if (view)
        [view addSubview:self];
    else
        [layer addSublayer:self.layer];

    CGPoint calloutOrigin = {
            .x = calloutX + adjustX,
            .y = bestDirection == SMCalloutArrowDirectionDown ? (anchorY - self.calloutHeight) : anchorY
    };

    self.frameOrigin = calloutOrigin;

    // now set the *actual* anchor point for our layer so that our "popup" animation starts from this point.
    CGPoint anchorPoint = [layer convertPoint:CGPointMake(anchorX, anchorY) toLayer:self.layer];

    // pass on the anchor point to our background view so it knows where to draw the arrow
    self.backgroundView.arrowPoint = anchorPoint;

    // adjust it to unit coordinates for the actual layer.anchorPoint property
    anchorPoint.x /= self.frameWidth;
    anchorPoint.y /= self.frameHeight;
    self.layer.anchorPoint = anchorPoint;

    // setting the anchor point moves the view a bit, so we need to reset
    self.frameOrigin = calloutOrigin;
```

Do you think this has been to do with my problem? If yes, what can I do, to remove this behavior. I don't have the knowledge about Swift/ObjectiveC.

**Comment by mafiusu** [comment]
Solved this issue 🎉🎉

in SMCalloutView.m I commented out the following code

```
    // but not if it's going to get too close to the edge of our constraints
    //if (calloutX < constrainedRect.origin.x)
    //    calloutX = constrainedRect.origin.x;

    //if (calloutX > constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth)
    //    calloutX = constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth;
```

I will let this issue open for anyone faces to this problem.

**Comment by jeffreymendez1993** [comment]
Experiencing this as well. Tried to animate to center pos before the callout is opened and no luck.

**Comment by mafiusu** [comment]
You should comment this lines like in my post above. This will solve the issue.

https://github.com/react-community/react-native-maps/issues/1810#issuecomment-372681667

**Comment by GarimaMathur07** [comment]
I am facing the same issue and i have commented out the lines like in post above but it does not resolve. I am using the custom callouts and when marker close to edge of screen then its callout aligns left and right with padding but not in centered.

**Comment by kingofdevs** [comment]
Any update for these issues?

**Comment by kingofdevs** [comment]
Solved this issue 🎉🎉 🎉🎉 🎉🎉
 
 // but not if it's going to get too close to the edge of our constraints
    //if (calloutX < constrainedRect.origin.x)
    //    calloutX = constrainedRect.origin.x;

    //if (calloutX > constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth)
    //    calloutX = constrainedRect.origin.x+constrainedRect.size.width-self.frameWidth;
