### ISSUE TITLE
flicker when changing the polygon

### ISSUE THREAD

**Issue by khomyakov42** [react-native-maps/react-native-maps#1818]
I use the polygon size 5 times the viewing area
I use expo-sdk@23.0.0 and react-native-maps@0.17.1

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/866005/33191412-be339f8c-d104-11e7-9900-dd3e50b1a80f.gif)

```javascript
import React from 'react';
import {View, StyleSheet} from 'react-native';
import {MapView} from 'expo';


const styles = StyleSheet.create({
   container: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'flex-end',
      alignItems: 'center',
      backgroundColor: 'red'
   },
   map: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
   },
});


export default class App extends React.Component {
   state = {
      region: {
         latitude: 37.78825,
         longitude: -122.4324,
         latitudeDelta: 0.0922,
         longitudeDelta: 0.0421,
      }
   };

   handleRegionChange(region) {
      this.setState({region});
   }

   renderPolygon() {
      const region = this.state.region;
      const padding = 5;
      const minLat = region.latitude - region.latitudeDelta / 2 * padding;
      const maxLat = region.latitude + region.latitudeDelta / 2 * padding;
      const minLng = region.longitude - region.longitudeDelta / 2 * padding;
      const maxLng = region.longitude + region.longitudeDelta / 2 * padding;

      const coordinates = [
         [minLat, minLng],
         [maxLat, minLng],
         [maxLat, maxLng],
         [minLat, maxLng]
      ].map(([lat, lng]) => ({latitude: lat, longitude: lng}));

      return <MapView.Polygon
         coordinates={coordinates}
         fillColor={"rgba(51,136,255,0.5)"}
      />
   }

   render() {
      return (
         <View style={styles.container}>
            <MapView
               region={this.state.region}
               onRegionChange={this.handleRegionChange.bind(this)}
               style={styles.map}
            >
               {this.renderPolygon()}
            </MapView>
         </View>
      );
   }
}
```

**Comment by khomyakov42** [comment]
is there any information? maybe I could somehow help

**Comment by oliverdolgener** [comment]
I'm struggling with the same problems. Especially when using the polygon with many holes. Have you found a solution for your problems?

**Comment by khomyakov42** [comment]
No =(

**Comment by oliverdolgener** [comment]
After testing this I figured out that it is an Android specific thing. On iOS the polygon is being updated without the flickering. Maybe someone could take a look on the Android implementation of the Polygon? That would be awesome as my app is highly based around the polygon feature.

**Comment by oliverdolgener** [comment]
When you compare both implementations you see that the Android one might be much slower pretty because each coordinate of the polygon and its holes is being read from a map data structure like this:

AirMapPolygon.java, line 39:
new LatLng(coordinate.getDouble("latitude"), coordinate.getDouble("longitude")));


On the iOS side its just a simple Array read like that:

AIRGoogleMapPolygon.m, line 29:
[path addCoordinate:coordinates[i].coordinate];


Maybe there might be some improvements on that line of code.

**Comment by oliverdolgener** [comment]
Please anyone, it works so well on iOS. It would be awesome if Android could be improved.

**Comment by oliverdolgener** [comment]
@alvelig Sorry to mention you directly but I've seen you fixed some issues regarding flickering of markers. Maybe you could take a look at this one here as well? It would be highly appreciated :)

**Comment by alvelig** [comment]
@oliverdolgener are you using the master branch or expo version?

**Comment by oliverdolgener** [comment]
@alvelig the expo version. Has this already been fixed on the master?

**Comment by alvelig** [comment]
I don't know. You can try.
We here don't support `expo`, but `react-native init` version.

**Comment by oliverdolgener** [comment]
@alvelig I can eject and try again with the master branch. I'll let you know. Thank for the heads-up.

**Comment by alvelig** [comment]
@oliverdolgener please don't eject. Build a separate project just to reproduce the problem, target `react-native-maps` package to master branch in `package.json` and share it on github. That's the best way to reproduce it.

**Comment by oliverdolgener** [comment]
@alvelig Did you have the time to check out my repo? It's a really annoying issue that blocks my app from being released soon.

**Comment by alvelig** [comment]
Hey @oliverdolgener! First of all thank you for making a reproducible repo, this will definitely help to nail down the issue. Sorry, I've been busy lately. But next week should be easier to find time to have a look at it. 
https://workhardanywhere.com/wp-content/uploads/2017/02/keep_calm-1.jpg

**Comment by oliverdolgener** [comment]
@alvelig Any news on this one?

**Comment by oliverdolgener** [comment]
Hey @alvelig are you still working on this issue? Please let me know if you need anything to further progress!

**Comment by oliverdolgener** [comment]
Can't anyone else help us? @christopherdro @rborn @Titozzz please it's driving me crazy. I can't seem to find the problem... :(

**Comment by techieyann** [comment]
Just bumping because I'm encountering the same thing on Android. I'm worried this might be another issue with Google's implementation, which would be ironic if it isn't occuring on iOS.

There's a [bug thread](https://issuetracker.google.com/issues/35823299) from 2013 which eventually solved a flicker problem with circles in 2016, but people are still reporting flickering with polygons on the thread.

**Comment by mbrehme** [comment]
Having the same issue. My polygon is flickering when setting the camera on mapview.

**Comment by andrey-shostik** [comment]
Have the same Issue

**Comment by oliverdolgener** [comment]
It certainly seems to be a problem with the native Google Maps Android SDK. We've created an issue and it seems to be fixed on the next major release. So there's hope! :)

https://issuetracker.google.com/issues/35829280

**Comment by oliverdolgener** [comment]
Response from the Google Maps Team:

> Marked as fixed.
> Dear developers,
>
> The Maps SDK for Android has recently received a major overhaul, now available in Beta, which made many bugs and feature requests inapplicable or obsolete.
>
> We believe that the issue or feature request reported here has been fixed or is inapplicable with this new release, and therefore closed this report.
>
> You can give this new release of the SDK a try by following the steps in our migration guide [https://goo.gle/v3-migration-guide].
>
> This is a beta release, and we rely on your feedback in the new component of our Issue Tracker [https://goo.gle/gmp-android-sdk-beta-issues] to help us exit beta as quickly as possible with a healthy, happy, bug-free SDK. 
>
> The full announcement for this new release is available on our blog at https://cloud.google.com/blog/products/maps-platform/whats-next-for-google-maps-platform.
>
> Thank you,
>
> The Google Maps Platform team

**Comment by oliverdolgener** [comment]
I already tried to enable Google Maps SDK 3.0.0 Beta for Android but I wasn't able to get it running. Maybe someone else could help me with that?

**Comment by inferusvv** [comment]
I have the same issue with `Marker` component. I have server-side clustering and here is what is happening when some markers disappears and new appears:

![2019-11-04 14 48 59](https://user-images.githubusercontent.com/3227120/68118932-59a52480-ff12-11e9-9cdf-f8a8ad437c58.gif)
