### ISSUE TITLE
showsMyLocationButton not showing up on Android

### ISSUE THREAD

**Issue by R1ckye** [react-native-maps/react-native-maps#2010]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

    react-native: 0.52.0
    react: 16.2.0
    react-native-maps: 0.19.0 

    GoogleMaps, but it works on iOS, Android-only issue

    Devices:
        Huawei Mate 9 running Android 7.0
        OnePlus One running Android 5.1.1 (Cyanogen - Factory OS on this phone)

### Steps to Reproduce

1. Create a MapView, with no options specified

### Expected Behavior

showsMyLocationButton to show up

### Actual Behavior

showsMyLocationButton not showing up

### Reproducible Demo

See https://github.com/react-community/react-native-maps/issues/2003, it has a demo, but it should be reproducible all the time

### Other info

I did some digging, on the OnePlus with Android 5 when I call `navigator.geolocation.getCurrentPosition` (separately) it throws
"Location request timed out" and on the Huawei it never returns. It also never asks for permissions to use my location. I also added every possible location permission one by one to the AndroidManifest, didn't help.

Could it be related to this? https://github.com/facebook/react-native/issues/7495

**Comment by rborn** [comment]
@alvelig I get a variation of this on a Samsung S6 too - I have two maps in the app, on the first one  I can see to button, on the second one I cannot make it work no matter what I try.
I also had to use the RN `navigator.geolocation.getCurrentPosition` to show the user's current location otherwise it would show up after 10' of waiting or so, no matter what permissions I put in AndroidManifest.xml

**Comment by alvelig** [comment]
I've reviewed this bug last month, and unfortunately have not found any solution, looks like it is initialized when rerendered, for example when rotating device...

**Comment by R1ckye** [comment]
Do you know any workaround to this?

**Comment by Shhzdmrz** [comment]
just try to repaint the map with padding or margin of 1.

**Comment by kartik0709** [comment]
You can do something like this.

componentDidMount(){
        setTimeout(()=>this.setState({flex: 1}),100);
}

Then in your mapview, you can put the style referring to the state
<MapView style={{flex: this.state.flex}} />

**Comment by Vetalyo** [comment]
I have same issue on iOS, using apple map provider.
showsMyLocationButton={true} is not showing up the button.

**Comment by MarkOSullivan94** [comment]
Has this be fixed? If so please close the issue. 

Otherwise it'd be great if someone could post a link to a repo with an example for anyone wanting to help out with this issue.

**Comment by darkmantle** [comment]
@MarkOSullivan94 It happens in every case.

**Comment by yodaheis** [comment]
I passed a function as props to MapView component that causes it to rerender once it is ready, for example - 
onMapReady={() => this.setState({ bottomPadding: 0 })}

This is a workaround.

**Comment by darkmantle** [comment]
@yodaheis Not for me - still get the same issue.

Have moved to another library until this is fixed.

**Comment by ntelkedzhiev** [comment]
Same here...

**Comment by prayuditb** [comment]
@darkmantle what library do you use?

**Comment by darkmantle** [comment]
@prayuditb https://github.com/mapbox/react-native-mapbox-gl

But it's not that much better, I've actually moved back to this library.

I did some testing and it works fine on a brand new RN 0.54.4 project, but that is no help to me as I have a pre-existing 0.54.4 project. No errors or any reason why the button is not showing up, but this is a huge problem.

**Comment by 2DKot** [comment]
> onMapReady={() => this.setState({ bottomPadding: 0 })}

Doesn't work for me. But it works with margin. Thank you!
```js
_onMapReady = () => this.setState({marginBottom: 0})

.........

<MapView
    style={{flex: 1, marginBottom: this.state.marginBottom}}
    onMapReady={this._onMapReady}
```

**Comment by Gytree** [comment]
the @2DKot  solution works for me. **react-native: 0.55.2**

**Comment by gamertense** [comment]
I followed the solution suggested by @2DKot, it's now working!
Tested on a React Native app which was created by `expo init` command.

**Comment by darkmantle** [comment]
Still not working on RN 0.54 which I'm using. Also 0.55+ isn't officially supported, so upgrading being the answer would be beyond ridiculous.

**Comment by darkmantle** [comment]
Updated to RN 0.55.4 and still getting no location button. I also cannot seem to overlay icons properly - in Android I get no top icon but the bottom sheet shows on click, in iOS its the other way around with the close icon showing but the bottom sheet not.

**Comment by lfernandoo** [comment]
How can I do that?  this.state.marginBottom's initial value should be 1.
I am new to React Native

**Comment by gamertense** [comment]
> How can I do that? this.state.marginBottom's initial value should be 1.
> I am new to React Native

Inside the constructor, add `this.state = { marginBottom : 1 }`
In case you don't understand what I'm talking about or want to see some sample code, please read [React docs](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class).

**Comment by lfernandoo** [comment]
> > How can I do that? this.state.marginBottom's initial value should be 1.
> > I am new to React Native
> 
> Inside the constructor, add `this.state = { marginBottom : 1 }`
> In case you don't understand what I'm talking about or want to see some sample code, please read [React docs](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class).

Thank you @gamertense

**Comment by MrFoxPro** [comment]
So, on emulator works solution with changing margin, bottom or flex, but on real device for me works only this: 
```
  _onMapReady() {
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
      .then(granted => {
        this.setState({ paddingTop: 0 });
      });
  }
   <View style={{ width: "100%", height: "100%", paddingTop: this.state.paddingTop }}>
        <MapView
          style={{ flex: 1 }}
          showsUserLocation={true}
          showsMyLocationButton={true}
          onMapReady={this._onMapReady}
        >
        </MapView>
   </View>
```

**Comment by rborn** [comment]
@PurnimaNaik can you confirm it works with the styling [absoluteFillObject](https://github.com/react-community/react-native-maps#my-map-is-blank)

**Comment by Mojo90** [comment]
> I am using the flex box style property `justifyContent:'center' ` on the mapView to solve this problem. Works on both android and iOS.
> 
> ```
>   mapContainer: {
>     justifyContent: 'center',
>     position: 'absolute',
>     height: Dimensions.get("window").height,
>     width: Dimensions.get("window").width
>   }
> ```

This does not work for me, tried to following:
```
<Mapbox.MapView
         styleURL={Mapbox.StyleURL.Street}
         zoomLevel={15}
         centerCoordinate={[11.256, 43.770]}
         style={{
           justifyContent: 'center',
           position: 'absolute',
           height: Dimensions.get("window").height,
           width: Dimensions.get("window").width
          }}
         showUserLocation={true}
         showsMyLocationButton={true}>
       </Mapbox.MapView>
```

**Comment by giacomocerquone** [comment]
SDK 32 in expo same problem. Tried all the solution above and they doesn't work...

**Comment by gtatyous** [comment]
Any solution for this yet? All of the above does not work on simulator or an actual device!

**Comment by giacomocerquone** [comment]
@gtatyous You just make a callout with a button in it and you can tie it with an onPress method to get your current position through the expo api and then move the camera manually. But I'm sorry I can't give you an example, I've not much free time in these days

Anyway **I should make a correction to my statement**, the button is showed only when you put the application in background and then you open it again (without closing it from the "task manager").
This behaviour smells like a js lib problem, this means that it **could** be fixed fast enough without touching native code.

**Comment by spencore** [comment]
For me, I notice the button will become visible when I focus on a react-native-elements Input. I have an Input in my header used as a search box and when I tap in it as if I am going to search for something, I notice the "go to current location" button becomes visible.  For now I am calling it a "feature" ...but it obviously isn't right. ;)

**Comment by anshumanburman** [comment]
@spencore i am facing the same issue did you get any solution for this??

**Comment by spencore** [comment]
Not the solution you and I want (to make it show up by default on it's own). But I just noticed that I was able to get it to show up when I tapped on my search bar on the same screen. Not sure if that means it shows up if focus is off the map or what.

**Comment by anastely** [comment]
@2DKot not working for me :/ 
Any Update Guys?

**Comment by HarshitMadhav** [comment]
@anastely  try the @2DKot  solution above, it is still working I have tried and tested it myself.

**Comment by anastely** [comment]
@Harshitmadhav It's work fine But when I rotate screen * Landscape * the map it will be in the middle don't take the whole screen.

**Comment by HarshitMadhav** [comment]
@anastely have you tried giving map style flex:1?

**Comment by anastely** [comment]
@HarshitMadhav  Yup, check here 
https://imgur.com/37HF6H5

**Comment by golaod** [comment]
Showing any button or location still doesn't work. I tried to put state styles both on parent View and MapView elements. Those styles were margin top/bottom, padding top/bottom and all combinations. flex:1 was set to both of them. I also added a button to change margin/padding values on click to see if rerendering will help. I followed suggestion to try with input field and with rotating the phone, but map simply doesn't show buttons or user location. I am more than sure app can read the location, because when I print navigator.geolocation.getCurrentLocation(result) I see where I am right now and when I move, it updates. It looks like just...any icons are not displayed.

**Comment by crespoxx** [comment]
I tried @2DKot solution but it doesn't work for me. After few hours trying everything, I came up with a similar solution:

`
constructor(props){
   super(props);
   this.state= {
   mapMargin:1
   }
}

setMargin = () => {
    this.setState({mapMargin:0})
  }

<MapView style={{marginBottom: this.state.mapMargin}}
          region={{ //Put your coords here }}
          showsUserLocation
          provider="google"
          showsMyLocationButton
          onMapReady={this.setMargin}
          >
</MapView>
` 
I tried this in 3 differents Android devices and it worked. It should look something like this:
![Map](https://user-images.githubusercontent.com/32083272/58140100-c13d1100-7c0b-11e9-82a4-c4194feb377c.png)

**Comment by pianoman730** [comment]
@crespoxx I've been dealing with this for a while now and I tried what you did with no luck (glad you got it to work though!). I set up react native maps with `react-native link react-native-maps` which worked out of the box for me with android. But the `showsMyLocationButton` is not working. Here's my code. I don't think it's very different from the solutions given here...Any ideas?
```
import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';

class Map extends Component {
  constructor(props) {
    super(props);
    this.state = { mapMargin: 1 };
  }

  setMargin = () => {
    this.setState({ mapMargin: 0 });
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          style={{ ...styles.map, marginBottom: this.state.mapMargin }}
          onMapReady={this.setMargin}
          provider="google"
          showsMyLocationButton
          initialRegion={{
            latitude: 49.7370,
            longitude: -111.8338,
            latitudeDelta: 0.001,
            longitudeDelta: 0.04,
          }}
        />
      </View>
    );
  }
}

const styles = {
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  }
};

export default Map;
```

**Comment by crespoxx** [comment]
@pianoman730 have you tried putting "showsUserLocation" inside of the MapView component?

**Comment by pianoman730** [comment]
@crespoxx I did try to put in `showsUserLocation` but that doesn't even work. It would be really nice (@ react-native-maps devs) to have a functioning example of very common use cases. I've been working with this library on and off for almost 2 years now and it seems to be the same issues every time.

**Comment by oussama9** [comment]
Any update about this issue ?

**Comment by StebanDev** [comment]
@crespoxx 's solution just worked for me, using an expo project.

**Comment by oussama9** [comment]
thank you very much Esteban !!  i've created my own button.

**Comment by darkmantle** [comment]
Seems to work for me now!

**Comment by virgilcui** [comment]
> @crespoxx I did try to put in `showsUserLocation` but that doesn't even work. It would be really nice (@ react-native-maps devs) to have a functioning example of very common use cases. I've been working with this library on and off for almost 2 years now and it seems to be the same issues every time.

with @crespoxx's solution, it works for me. Make sure you grant the location permission first, it doesn't show otherwise.

**Comment by oliversieto** [comment]
with @crespoxx's solution, it works for me, but I did some changes. I try some like this:

`constructor(props){
     super(props);
     this.state= {
      mapMargin:1 
     }
  }

setMargin = () => {
    this.setState({mapMargin: 15});
}

render() {
    return (
        <MapView
          style={ {flex : 1, marginTop: this.state.mapMargin} }
          provider="google"
          region={this.state.region}
          showsUserLocation={true}
          showsMyLocationButton={true}
          showsCompass={true}
          onMapReady={this.setMargin}
        >
        </MapView>
    );
  }
`

**Comment by juliobguedes** [comment]
Any news about this issue? I'm facing this problem when using Android, while iOS works fine. My MapView component is:
```javascript
                    <MapView
                      provider={PROVIDER_GOOGLE}
                      style={styles.mapStyles}
                      customMapStyle={mapStyle}
                      minZoomLevel={12}
                      maxZoomLevel={17}
                      followsUserLocation
                      showsUserLocation
                      showsMyLocationButton
                      showsCompass
                      initialRegion={{
                          ...center,
                          latitudeDelta: 0,
                          longitudeDelta: 0,
                      }}
                    >
```

**Comment by davychhouk** [comment]
@juliobguedes Here is how I do it:
`style={[styles.map, { marginBottom: this.state.mapMargin }]}`

I'm following @crespoxx's solution with <MapView> style as above and it works now.

**Comment by juliobguedes** [comment]
@davychhouk I've tried many different ways since I asked, but it was faster to code my own ShowMyLocation button, but thanks for replying. Can anyone else test this to close the issue?

**Comment by EtainLove** [comment]
@crespoxx solution works for me. thanks.
initially setting marginBottom 1 and setting marginBottom 0 in the OnMapReady.

**Comment by jamesdmurphy51** [comment]
Doesnt work for me :(

**Comment by jamesdmurphy51** [comment]
Works for me :)

**Comment by anastely** [comment]
@jamesdmurphy51 which solution works with you?

**Comment by anastely** [comment]
@richardbumm I do it, but when I click to this button the Map it's doing some Shaking..

my code
  ```
currentLocationBtn = async () => {
    Geolocation.getCurrentPosition(position => {
      const region = {
        latitude: position.coords.latitude,
        longitude: position.coords.longitude,
        latitudeDelta: 0.012,
        longitudeDelta: 0.01,
      };
      this.map.animateToRegion(region, 500);
    });
  };


 <MapView
          style={styles.map}
          loadingEnabled={true}
          loadingIndicatorColor="#666666"
          loadingBackgroundColor="#eeeeee"
          initialRegion={this.state.initialRegion}
          region={this.state.mapData}
          showsMyLocationButton={true}
          ref={map => (this.map = map)}
          onRegionChangeComplete={this.handleRegionChange}>

// My own button
<TouchableOpacity
          onPress={this.currentLocationBtn}
          style={{
            alignSelf: 'flex-start',
            width: 50,
            height: 50,
            marginHorizontal: 10,
            backgroundColor: 'red',
            justifyContent: 'center',
            alignItems: 'center',
          }}>
          <Text>+</Text>
        </TouchableOpacity>
```

**Comment by pedrocarlos-ti** [comment]
Thanks @crespoxx , works fine here. It's not the perfect way but works.

**Comment by saadi-ninjasCode** [comment]
@crespoxx , that solution work for me before. But now it's not working on same code. After updating SDK, I am not able to see the button on map screen.

**Comment by adrianloh128** [comment]
in my case, it is not marginButton but width.. I am on expo

**Comment by mathritter** [comment]
Some of the features that doesn't work here
showsMyLocationButton
followsUserLocation

**Comment by irfanzainudin** [comment]
Maybe the issue is related to showsUserLocation? From the docs, it says "You need to add NSLocationWhenInUseUsageDescription key in Info.plist to enable geolocation, otherwise it is going to fail silently!"

I'm having this issue right now and I haven't add the key into Info.plist. Plus, I haven't seen anyone suggesting this, so is it a possibility?

**Comment by Bonjamin** [comment]
> So, on emulator works solution with changing margin, bottom or flex, but on real device for me works only this:
> 
> ```
>   _onMapReady() {
>     PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
>       .then(granted => {
>         this.setState({ paddingTop: 0 });
>       });
>   }
>    <View style={{ width: "100%", height: "100%", paddingTop: this.state.paddingTop }}>
>         <MapView
>           style={{ flex: 1 }}
>           showsUserLocation={true}
>           showsMyLocationButton={true}
>           onMapReady={this._onMapReady}
>         >
>         </MapView>
>    </View>
> ```

If MyLocationButton is not shown. You try `this.setState({ paddingTop: 1 });`

**Comment by borbhuiyagulsan** [comment]
I have tried above mentioned all solutions but still I am unable to find a proper solution. I am using latest version of expo & I am trying to solve this from past 23 days. I would really appreciate everyone's help.
Please see the code 

`   const [mapMargin, setMapMargin] = useState(1)
    const setMargin = () => {
        setMapMargin(0)
    }`

`
            <View style={styles.container}>


            <MapView
                //mapPadding={{ top: 1, right: 1, bottom: 1, left: 0 }}

                style={{ ...styles.mapView, marginBottom: mapMargin }}
                provider={PROVIDER_GOOGLE}
                showsCompass={true}
                showsMyLocationButton={true}
                showsUserLocation={true}
                mapType={"standard"}
                zoomEnabled={true}
                initialRegion={location}
                rotateEnabled={true}
                onMapReady={setMargin}
                loadingEnabled={true}
                loadingIndicatorColor="#666666"
                loadingBackgroundColor="#eeeeee"
            >
            </MapView>`

`  

     container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        //width: '100%'
    },`

`  mapView: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        flex: 1
        //justifyContent: 'center'
    },`

**Comment by borbhuiyagulsan** [comment]
I have tried @JakeHadley code & it worked but I have made few modifications.
Instead of `marginBottom` , I have just used `margin` & it really worked for me. I am sharing my codes below for your reference.

`  const [mapMargin, setMapMargin] = useState(1)
    const setMargin = () => {
        setMapMargin(0)
    }`


`
<MapView
                style={{ ...styles.mapView, margin: mapMargin }}
                provider={PROVIDER_GOOGLE}
                showsCompass={true}
                showsMyLocationButton={true}
                showsUserLocation={true}
                mapType={"standard"}
                zoomEnabled={true}
                initialRegion={location}
                rotateEnabled={true}
                onMapReady={setMargin}
                loadingEnabled={true}
                loadingIndicatorColor="#666666"
                loadingBackgroundColor="#eeeeee"
            >
            </MapView>`

> @crespoxx I've been dealing with this for a while now and I tried what you did with no luck (glad you got it to work though!). I set up react native maps with `react-native link react-native-maps` which worked out of the box for me with android. But the `showsMyLocationButton` is not working. Here's my code. I don't think it's very different from the solutions given here...Any ideas?
> 
> ```
> import React, { Component } from 'react';
> import { View, StyleSheet } from 'react-native';
> import MapView from 'react-native-maps';
> 
> class Map extends Component {
>   constructor(props) {
>     super(props);
>     this.state = { mapMargin: 1 };
>   }
> 
>   setMargin = () => {
>     this.setState({ mapMargin: 0 });
>   }
> 
>   render() {
>     return (
>       <View style={styles.container}>
>         <MapView
>           style={{ ...styles.map, marginBottom: this.state.mapMargin }}
>           onMapReady={this.setMargin}
>           provider="google"
>           showsMyLocationButton
>           initialRegion={{
>             latitude: 49.7370,
>             longitude: -111.8338,
>             latitudeDelta: 0.001,
>             longitudeDelta: 0.04,
>           }}
>         />
>       </View>
>     );
>   }
> }
> 
> const styles = {
>   container: {
>     ...StyleSheet.absoluteFillObject,
>     justifyContent: 'flex-end',
>     alignItems: 'center',
>   },
>   map: {
>     ...StyleSheet.absoluteFillObject,
>   }
> };
> 
> export default Map;
> ```

**Comment by maxcct** [comment]
This issue needs an actual fix please

**Comment by Goldziher** [comment]
Verified that this bug is still in place.. :(

Adjusting the style of the map does force a re-render which causes the button to appear - but not always.

**Comment by Sarvarr** [comment]
Same here...

**Comment by GrEg00z** [comment]
> This issue needs an actual fix please

The workaround given by @2DKot still works with RN 0.63.4 & react-native-maps 0.27.1

**Comment by IPWright83** [comment]
I'm having real trouble getting the workaround to do anything - just wanted to see if anyone can see what I'm doing wrong?

I can see the re-render happening, but I still don't get any sort of a button?

```
const MapScreen = () => {
    // We need to keep region in state, otherwise anything that
    // triggers this component to re-render will reset the region
    const [region, setRegion] = useState({
        latitude: 53.945,
        longitude: -1.0539,
        latitudeDelta: 0.015,
        longitudeDelta: 0.0121,
    });

    const [margin, setMargin] = useState(10);
    const styles = getStyles(margin);

    return (
        <MapView
            style={styles.map}
            provider={PROVIDER_GOOGLE}
            region={region}
            showsMyLocationButton={true}
            onRegionChangeComplete={setRegion}
            onMapReady={() => {
                setTimeout(() => {
                    setMargin(0);
                }, 1000);
            }}
        />
    );
};

const getStyles = (margin) => ({
    map: {
        justifyContent: 'center',
        ...StyleSheet.absoluteFillObject,
        flex: 1,
        margin,
    },
});
```

**Comment by maazkhansw5145** [comment]
My work around.
import React, { useState, useEffect } from "react";
import MapView, { Marker } from "react-native-maps";
import { StyleSheet, Text, View, Dimensions, Pressable } from "react-native";
import CurrentLocation from "../Constants/CurrentLocation";
import Loading from "./Special/Loading";
import { MaterialIcons } from "@expo/vector-icons";

export default function MapViewComponent() {
  const [coordinates, setCoordinates] = useState(null);

  useEffect(() => {
    let loc = CurrentLocation();
    loc.then((l) => setCoordinates(l.coords));
  }, []);
  if (!coordinates) {
    return <Loading />;
  }

  const myLocation = () => {
    console.log("HIT");
    let loc = CurrentLocation();
    loc.then((l) => setCoordinates(l.coords));
  }
  console.log(coordinates);

  return (
    <View style={styles.container}>
      <MapView
        style={styles.map}
        region={{
          latitude: coordinates.latitude,
          longitude: coordinates.longitude,
          latitudeDelta: 0.005,
          longitudeDelta: 0.005,
        }}
        mapType="hybrid"
      >
        <Marker
          draggable
          coordinate={{
            latitude: coordinates.latitude,
            longitude: coordinates.longitude,
          }}
          onDragEnd={(e) => setCoordinates(e.nativeEvent.coordinate)}
          title={"Hold, then drag to your exact location"}
        />
      </MapView>
      <Pressable style={[styles.overlay,styles.myLocation]} onPress={myLocation}>
        <MaterialIcons
          name="my-location"
          size={24}
          color="rgb(123, 104, 238)"
        />
      </Pressable>
      <Pressable style={[styles.overlay,styles.done]}>
      <MaterialIcons name="check" size={24} color="rgb(123, 104, 238)" />
      </Pressable>
      <View style={[styles.overlay,styles.text]}>
      <Text >Hold the location icon, drag it to your exact location and press the done button.</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  overlay:{
    position: "absolute",
    backgroundColor: "white",
    padding: 15,
    borderRadius: 20,
  },
  myLocation: {
    top: 10,
    right: 10,
  },
  done:{
    bottom: 10,
    right: 10,
  },
  text:{
    bottom:7,
    left: 10,width:Dimensions.get("window").width - 100
  }
});

**Comment by navarrofracisco** [comment]
Can this issue be reopned? What is the point of using  library for maps if basic functionality like centering location is not working?

**Comment by rickyanwar** [comment]
same for me using 
 "expo": "~45.0.0",
 "react-native": "0.68.2",
 "react-native-maps": "0.30.2",

showsMyLocationButton not showing anything

this my sample code

     ```
  <MapView
                showsUserLocation={true}
                provider={PROVIDER_GOOGLE}
                initialRegion={region}
                showsMyLocationButton={true}
                showsScale={true}
            >
```
![a](https://user-images.githubusercontent.com/36995966/173881752-805e2904-daaf-48d1-a163-9694514a8815.jpg)

**Comment by quannq-comartek** [comment]
Need to fix this issue please

**Comment by quannq-comartek** [comment]
Any update? Nothing work for me

**Comment by r2510** [comment]
I tried almost everything on internet still showsUserLocation and followsUserLocation are not working on Android emulator. Please can someone tell me what was the final solution to show current location on android emulator.

const OrdersScreen = () => {
    const bottomSheetRef = useRef(null);
    const snapPoints = useMemo(() => ["12%", "90%"], [])//performance

    const { width, height } = useWindowDimensions();


    const [isMapReady, setMapReady] = useState(false);
    const [marginBottom, setMarginBottom] = useState(0);

    const mapRef = useRef(null);

    const handleMapReady = useCallback(() => {
        setMapReady(true);
        setMarginBottom(0);
    }, [mapRef, setMapReady]);

    // useEffect(() => {
    //     setTimeout(() => setMarginBottom(1), 100);
    // }, [])

    useEffect(() => {
        const requestLocationPermission = async () => {
            try {
                const granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                    {
                        title: 'Location permission is required for this app',
                        message: 'This app needs location permission to show your current location on the map.',
                        buttonNeutral: 'Ask Me Later',
                        buttonNegative: 'Cancel',
                        buttonPositive: 'OK',
                    },
                );
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    setMapReady(true);
                    console.log('Location permission granted');
                } else {
                    console.log('Location permission denied');
                }
            } catch (err) {
                console.warn(err);
            }
        };
        requestLocationPermission();
    }, []);

    return (
        <GestureHandlerRootView style={{ backgroundColor: 'lightblue', flex: 1 }}>
            <MapView
                style={isMapReady ? [styles.mapStyle, { marginBottom: marginBottom }] : {}}
                ref={mapRef}
                provider={PROVIDER_GOOGLE}
                onMapReady={handleMapReady}
                showsUserLocation={true}
                // showsMyLocationButton={true}
                followsUserLocation={true}
            />
            <BottomSheet ref={bottomSheetRef} snapPoints={snapPoints} >
                <View style={{ alignItems: 'center', marginBottom: 30 }}>
                    <Text style={{ fontSize: 20, fontWeight: '700', letterSpacing: 0.5, paddingBottom: 5 }}>You're Online</Text>
                    <Text style={{ letterSpacing: 0.5, color: 'grey' }}>Available Orders: {orders.length}</Text>

                </View>
                <FlatList
                    data={orders}
                    renderItem={({ item }) => <OrderItem order={item} />}
                />
            </BottomSheet>
        </GestureHandlerRootView>
    );
}

**Comment by r2510** [comment]
Use  expo-location to get current location on android

import * as Location from 'expo-location';

const [driverLocation, setDriverLocation] = useState(null);
const { width, height } = useWindowDimensions();

useEffect(() => {
        (async () => {

            let { status } = await Location.requestForegroundPermissionsAsync();
            if (status !== 'granted') {
                console.log('Permission to access location was denied');
                return;
            }

            let location = await Location.getCurrentPositionAsync({});
            setDriverLocation({
                latitude: location.coords.latitude,
                longitude: location.coords.longitude
            });
        })();
 }, []);

<MapView
                style={{ height: height, width: width }}
                showsUserLocation={true}
                followsUserLocation={true}
                initialRegion={{
                    latitude: driverLocation.latitude,
                    longitude: driverLocation.longitude,
                    latitudeDelta: 0.07,//zoom level
                    longitudeDelta: 0.07//zoom level
                }}
/>

**Comment by dev-externlabs** [comment]
In my case it was permission issue

**Comment by digitalbore** [comment]
Got the same problem. Margin is not helping me.

**Comment by jasimkhan-ariprodesign** [comment]
> Got the same problem. Margin is not helping me.

did you find any solution?
