### ISSUE TITLE
Markers are not moving onPress in iOS

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-native-maps/react-native-maps#2024]
Hi, currently I'm facing the issue in iOS. I have used google maps in iOS. The issue is like screen view is not moving when  another marker is pressed even if I set the property of MapView  `moveOnMarkerPress={true}` . 
Is any solution there?

**Comment by ltchurch88t** [comment]
moveOnMarkerPress is an android only functionality, however, you could create your own work around through setState. If you handled onPress you could update the current region to move the map to the specified coordinates the Marker is set at. If you need some code to give you and idea feel free to let me know otherwise it is always good to try it out yourself first. Look at onRegionChange and how it interacts with the region rendered

**Comment by ShaikhKabeer** [comment]
Hey @ltchurch88t , it will be good if you share the code for it.

**Comment by ShaikhKabeer** [comment]
Below is the Map component I'm using. Here I'm passing multiple lat long coordinates. Now please refer this one and tell what I do for doing marker moving functionality in iOS too.

import React from 'react';
import { StyleSheet,Text,View }  from 'react-native';
import MapView,{PROVIDER_GOOGLE} from 'react-native-maps';

export default class ReactMap extends React.Component {
    constructor(props){
        super(props);
        this.mapRef = null;

    }
    componentDidUpdate(){
        this.mapRef.fitToCoordinates(this.props.LatLongCoordinates,{ edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: true });
    }
    render() {
        return (
            <MapView
			 maxZoomLevel={14}
           //minZoomLevel={3}
            zoomEnabled={true}
            moveOnMarkerPress={true}
            provider={PROVIDER_GOOGLE}
            style={styles.map}
            ref={(ref) => {this.mapRef= ref}}
            onLayout={() => this.mapRef.fitToCoordinates(this.props.LatLongCoordinates,{ edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: true })}>
            {this.props.LatLongCoordinates.map((marker,i) =>   (
                <MapView.Marker key={i}
                zIndex={i}
                coordinate={marker}
                title={((marker.latitude).toString()+' , '+(marker.longitude).toString())}
                >
                <View style={styles.radius}>
                <View style={styles.markerStyle}/>
                </View>
               </MapView.Marker>
            ))}
            </MapView> 
           
        );
    }
 
}

const styles=StyleSheet.create({
    container:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0,
        justifyContent:'flex-end',
        alignItems:'center' 
    },
    map:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0,
       borderColor:'black',
       borderWidth:0.5
    },
    radius:{
        height:15,
        width:15,
        backgroundColor:'#81BD26',
        overflow:'hidden',
        borderRadius:50/2,
        borderWidth:1,
        alignItems:'center',
        justifyContent:'center'
    },
    markerStyle:{
        height:10,
        width:10,
        backgroundColor:'#81BD26',
        alignItems:'center',
        justifyContent:'center'
    }
});

**Comment by ShaikhKabeer** [comment]
Hey @ltchurch88t , any solution to this ?

**Comment by ltchurch88t** [comment]
@ShaikhKabeer is it absolutely essential to use the marker itself as the navigation tool or could you attribute the functionality elsewhere? For example on a carousel slider or button press in a separate view? The issue with iOS is the register of the marker press itself not mapping the component. Let me know as soon as you can and I will try and post code accordingly

**Comment by ShaikhKabeer** [comment]
Hey @ltchurch88t , as mentioned in the code above, I'm passing the no of Lat-Long objects and fitting those using fitToCordinates( ). So those markers are now fitting in the MapView. I'm showing Lat Long cordinate object for that particular marker. So when  I'm pressing particular marker for checking its cordinates then it is moving screen. So this behaviour is expected in both iOS and android but in iOS this particular marker is not moving the screen.

**Comment by eelmoni** [comment]
Hey guys! I'm a little late but maybe this helps, I'm gonna share you my code:

```
       <MapView
          ref={this.mapViewRef}
          moveOnMarkerPress
          tracksViewChanges={false}
          provider={PROVIDER_GOOGLE}
          style={styles.mapView}
          initialRegion={region}
          onRegionChangeComplete={this.onRegionChange}
          onMarkerPress={this.onMarkerPress}
        >
```
  
```
onMarkerPress = (event: Event) => {
    const { id, coordinate } = event.nativeEvent;
    const { region } = this.state;
    const newRegion = { ...region };

    newRegion.latitude = coordinate.latitude;
    newRegion.longitude = coordinate.longitude;

    this.setState(
      {
        region: newRegion,
      },
      this.goToPositionSelected,
    );
  };
```

The idea is after set the region in the state, call `animateToRegion` of the `MapView` ref:

```
  goToPositionSelected = () => {
    if (isAndroid) return;

    const { region } = this.state;

    this.mapView.animateToRegion(region);
  };
```

**Comment by vidoree** [comment]
Based on eelmoni's solution(thanks a lot! 🙂) I created a hook to handle this. When I used Region, MapView always jumped back to the original zoom and pitch. If you allow zoom or pitch, a better solution is to use Camera instead of Region. There is an `animateCamera` function(which accepts Camera Partial as a parameter), with this you won't need state anymore.

Here is the solution: 
```
export function useCameraFocus(): [
  React.RefObject<MapView>,
  (event: MapEvent) => void
] {
  const mapViewRef = useRef<MapView>(null)

    function onMarkerPress(event: MapEvent) {
    if (!mapViewRef.current || Platform.OS === 'android') {
      return
    }

    const { coordinate } = event.nativeEvent

    mapViewRef.current.animateCamera(
      {
        center: {
          latitude: coordinate.latitude,
          longitude: coordinate.longitude,
        },
      },
      { duration: 200 }
    )
  }

  return [mapViewRef, onMarkerPress]
}
```

Just use it in Map component:
```
  ... 
  const [mapViewRef, onMarkerPress] = useCameraFocus()

  return (
    <MapView
      ref={mapViewRef}
      provider={PROVIDER_GOOGLE}
      scrollEnabled={true}
      zoomEnabled={true}
      rotateEnabled={true}
      zoomTapEnabled={true}
      initialCamera={initialCamera}
      onMarkerPress={onMarkerPress}
    >
  ...
```
