### ISSUE TITLE
compass icon fires onPress - android

### ISSUE THREAD

**Issue by mtiziano** [react-native-maps/react-native-maps#2031]
### Is this a bug report?

Yes

### Environment

> Environment:
>   OS: Windows 10
>   Node: 8.1.2
>   Yarn: 0.27.5
>   npm: 5.3.0
>   Watchman: Not Found
>   Xcode: N/A
>   Android Studio: Version  3.0.0.0 AI-171.4443003
> 
> Packages: (wanted => installed)
>   react: 16.0.0 => 16.0.0
>   react-native: 0.51.0 => 0.51.0
> 
>   Target Platform: Android (7.1.1)

### Report

![compass](https://user-images.githubusercontent.com/6752432/36305792-64bed6e4-1315-11e8-9255-ae2fd816bf0c.png)

by changing map direction with two fingers, compass icon appears top-left to reset map direction to North.

When i press the compass icon, it fires onPress event of an external TouchableOpacity that has nothing related

**Comment by ArthurAttout** [comment]
Exact same issue here, touching the compass fires a navigation event, which quits the current screen

**Comment by lucasfronza** [comment]
Same as @numez. Touching compass fires onPress of a TouchableOpacity that is outsite MapView. It happens even if compass is not showing (map facing north). It doesn't happen with `showCompass={false}`. 
"react": "16.5.1",
"react-native": "0.57.1",
"react-native-maps": "0.21.0",

**Comment by richardbumm** [comment]
Is this still an issue?

**Comment by richardbumm** [comment]
This has been open for a long time with no update.  Any attempt to fix it coming?

**Comment by richardbumm** [comment]
@rborn Can you push this into a priority? Open for almost a year and no feedback. Broken feature.

**Comment by rborn** [comment]
@richardbumm I don't set priorities, I don't even publish to npm, I just help with sorting issues 😞
This is a community repo and issues are solved when somebody from it fixes something and participate back.
