### ISSUE TITLE
Custom markers doesn't always update on android

### ISSUE THREAD

**Issue by vvusts** [react-native-maps/react-native-maps#2048]
RN - 0.52
RN Maps - 0.20.1
IOS - work perfect
Android - is problem

I render a lot of markers and use clustering (react-native-maps-super-cluster) but this is related to map.
Markers use custom images like: **marker.png** and **selectedMarker.png**
I have list of buttons bellow map. When button is pressed it` .animateToRegion()` where some marker is.
Selecting button update state variable like `selectedMarkerId`.
In function that render marker I check this variable and based on that set different marker image.
Problem is that on android this image replace doesn't work. And then I move map so marker is not visible and back it again and then image is updated.
I tried with setting key to be `Math.random()` but this make marker flicker as I move map and change selections.
Does anybody have problem like this and is there solution?

**Comment by vuphuctho** [comment]
Same issue with you but in my case I don't call `animateToRegion` but update region by changing state. using `Math.random()` for updating key values work for me, no more flickering happens.

**Comment by vvusts** [comment]
Where exactly you set math.random?
On marker key? On marker image?
I set id of location from database for marker key so for me that is not random. I set on custom image but then I get flickering.

**Comment by bramus** [comment]
Could it be that this is a duplicate of https://github.com/react-community/react-native-maps/issues/1288 ?

**Comment by vvusts** [comment]
No, markers are moving fine it’s image for marker that is not update.

For example: you have two markers in a view region and two buttons one should update image one one and second on another. 
Click on button update once. 
But when you click on second button marker image is not changed. 
But if you move map so that marker is not visible and back agin it update marker image. 
And this is only on android.

**Comment by bramus** [comment]
Ah, thanks for the clarification … I get it now :)

**Comment by vuphuctho** [comment]
@vvusts I updated marker key, based on [this explanation.](https://github.com/react-community/react-native-maps/issues/1611#issuecomment-334619684)

**Comment by Khsed4** [comment]
@vvusts I'm stuck the same issue , have u found the solution ? if yes kindly post it here

**Comment by khuongdv** [comment]
@vuphuctho I tried that way but in real devices the issue still occurs @@

**Comment by abhideepmallick** [comment]
Working solution https://github.com/react-native-community/react-native-maps/issues/2734#issuecomment-515428771
