### ISSUE TITLE
UrlTile sometimes failes to load tiles

### ISSUE THREAD

**Issue by mellet** [react-native-maps/react-native-maps#2093]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, but using Expo.

### Environment

Expo SDK v25, running build of react-native-maps v0.19.0

### Steps to Reproduce

*NB! This bug is sporadic, does not occur on every run of the app. If everything seems fine try again until the tiles don't load.*

1. [Scan QR code or run simulator](https://snack.expo.io/SJKHosLKz)
2. Zoom all the way out and pan to the right as if your circling the earth on the map
3. Observe tiles that don't load

### Expected Behavior

All tiles for the UrlTile should load.

### Actual Behavior

On some runs tiles don't load.  
It seems like it is hitting the cache and thinks the tile is present.  

Example after my second run:
![Screenshot](https://i.imgur.com/LoT4wyy.png)

### Reproducible Demo

https://snack.expo.io/SJKHosLKz

I only testet on 2 actual iPhones with the Expo client.  
I'm getting the same bug in my standalone build of my app with Expo.

**Comment by mellet** [comment]
### Some more debugging

[Here](https://i.imgur.com/R2IKCp2.png) is another screenshot of tiles failing to load.
This time I had Charles Proxy running so I could see the network requests going out.

### Failing requests
![FailedRequests](https://i.imgur.com/8WhSEgl.png)

The response code was `404 Not Found`.  
I tried hitting the [tile](https://b.tile.openstreetmap.org/3/4/6.png) manually from the browser and the request seems fine.

Maybe add some retry functionality if the requests fails?

**Comment by sogasg** [comment]
Or at least UrlTile could have an attribute where we could provide a function to be called if the response did not have status code 200 (perhaps there also could be an attribute with success status codes or something?).
