### ISSUE TITLE
Animating polyline of google maps - (Any way to animate google maps tracked path)

### ISSUE THREAD

**Issue by vigneshwarrao** [react-native-maps/react-native-maps#2119]
## Environment
Environment:
 OS: macOS High Sierra 10.13.3
 Node: 8.9.1
 Yarn: Not Found
 npm: 5.5.1
 Watchman: 4.9.0
 Xcode: Xcode 9.2 Build version 9C40b
 Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
 react: 16.2.0 => 16.2.0
 react-native: 0.51.0 => 0.51.0

## Steps to Reproduce
Actually we tried with geo location and react-native-maps. If we have starting and ending point(latitude-longitude) then it should animate from starting to end point. Please find the following image examples.
##Eg 1:
https://i.stack.imgur.com/vCpWc.gif

##Eg 2:
![ios-img](https://user-images.githubusercontent.com/10556489/37778286-8c8abd18-2e0f-11e8-907c-4881287a8fea.gif)

## Expected Behavior
The polyline should animate from starting point to destination point.

## Actual Behavior
There is nothing happening at present. The polyline is just mapping from starting point to destination with markers but not animating

**Comment by Kirill23** [comment]
the only way I see is to slowly load array of coordinates on map ready. Let's say your loop will be adding 5 coordinates per second into array of coordinates that you used inside polyline then that will be your speed of animation.

**Comment by Usman175** [comment]
@vigneshwarrao can i see the code . ?

**Comment by vigneshwarrao** [comment]
Sorry usman, I don't have the code at present. Thank you for contacting me.

**Comment by EricPKerr** [comment]
@vigneshwarrao any way you can share code?  Thanks

**Comment by marcoschicote** [comment]
+1

**Comment by markmssd** [comment]
Have you guys tried that library: https://github.com/shameemz/react-native-maps-animated-polyline, works pretty well
