### ISSUE TITLE
iOS google maps change urlTemplate on button press

### ISSUE THREAD

**Issue by OsvaldasSk** [react-native-maps/react-native-maps#2200]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.2
react: 16.3.1
react-native-maps: 0.21.0
iOS GoogleMaps

### Steps to Reproduce

The problem: We have a floor picker and on floor select we change urlTemplate for UrlTiles component. On android everything works fine, but on iOS google maps tiles are not rerendered and old urlTemplate is used.

1. Create MapView with UrlTile and set urlTemplate to empty string. 
2. Change urlTemplate on button press to for e.g. http://c.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg 

### Expected Behavior

Tiles from new urlTemplate should be rendered.

### Actual Behavior

**iOS google maps** after button press and urlTemplate changed to different url, still initial urlTemplate is used -> new tiles from new urlTemplate is not rendered.
**Android** - works fine, urlTemplate can be changed on button press.

### Reproducible Demo

Snack url https://snack.expo.io/r1bIYXQnf

Code used from https://github.com/react-community/react-native-maps/blob/master/example/examples/CustomTiles.js

only change I have made is that urlTemplate is stored and retrieved from state. Initial urlTemplate is empty string and changed to http://c.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg on TouchableOpacity press

**Comment by gilliM** [comment]
Any news in this issue ?
