### ISSUE TITLE
zoomControlEnabled doesn't shows zooming UI

### ISSUE THREAD

**Issue by MortezaAghili** [react-native-maps/react-native-maps#2214]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.52.2
    react: 16.2.0
	react-native-maps: ^0.21.0
### Steps to Reproduce

1. Install react-native-maps library & setup for using that in our app  
2. Add props to give user, map zooming ability

### Expected Behavior

After adding Props to my MapView, I expect see a ZoomControl buttons on my displayed map screen. 

### Actual Behavior

But there is no UI for Zoom Control buttons on my map.  

<img width="370" alt="screen shot 2018-04-24 at 5 16 54 pm" src="https://user-images.githubusercontent.com/6826680/39187770-62eb3706-47e3-11e8-8c49-fea0678dbf80.png">
<img width="479" alt="screen shot 2018-04-24 at 5 17 07 pm" src="https://user-images.githubusercontent.com/6826680/39187771-63412508-47e3-11e8-979a-881ab9fc5b17.png">

**Comment by chist3r** [comment]
Seems like you are using iOS device. According to the documentation `zoomControlEnabled` works only on Android

**Comment by code-by** [comment]
in my case there also no zoom buttons on Android
```
react-native: 0.50.4
react-native-maps: 0.21.0
```
`zoomControlEnabled` is explicitly set to `true`, but according to docs it is `true` by default

**Comment by aliozinan** [comment]
Exactly same problem here with :

"react-native": "^0.56.1",
"react-native-maps": "^0.22.0"

Confirmed on both Android 23 Genymotion emulator and a real device.

**Comment by WandersonAlves** [comment]
Here too:

"react-native": "0.56.0",
"react-native-maps": "0.22.0" (i recently upgraded from 0.21.0 to see if bug persists)

My info

```
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 343.38 MB / 15.56 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.8.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        System Images: android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Render code:

```javascript
render () {
    const markers = this.props.clientDataWallet || [];
    return (
      <View style={_styleWallet.container}>
        <MapView
          userLocationAnnotationTitle={'Map'}
          showsScale
          showsCompass
          showsPointsOfInterest
          showsBuildings
          showsMyLocationButton
          showsUserLocation
          followsUserLocation
          style={_styleMap.map}
          loadingEnabled
          zoomEnabled
          zoomControlEnabled
          showsTraffic={false}
          region={this.state.region}>
          {markers.map(client => (
            <MapView.Marker
              tracksViewChanges={false}
              pinColor={client.colorPin}
              key={client.CODCLI}
              coordinate={client.LATLNG}
              title={client.CLIENTE}
              description={client.CLIENTE}
            />
          ))}
        </MapView>
      </View>
    );
  }
```

zoomControlEnabled, showTraffic and showsMyLocationButton props seem not to work.

Map been rendered:

![image](https://user-images.githubusercontent.com/9141449/50787239-a38e9100-1294-11e9-8d14-7b35d8f8705f.png)

**Comment by altenorjr** [comment]
Is this project abandoned?

**Comment by kriscarle** [comment]
There is a workaround for this, see https://github.com/react-native-community/react-native-maps/issues/3026#issuecomment-581098944

**Comment by idumachika** [comment]
F

**Comment by ilies-space** [comment]
Just , delete style for mapView,( height and weight ) .
save then rewrite the style . 
that solved my issue

**Comment by ilies-space** [comment]
change height and weight in style of the Mapview from % to dp`

**Comment by MiguelNiblock** [comment]
Issue should be open

**Comment by robba86** [comment]
Yes it should

**Comment by sajeduardo** [comment]
Waiting for solutions

**Comment by hoseinfo** [comment]
any update?
