### ISSUE TITLE
Polyline's prop strokeColors not working

### ISSUE THREAD

**Issue by guidoprinc** [react-native-maps/react-native-maps#2246]
### Is this a bug report?

Yes

I want to draw the trace of a trip of a car and changing the line's color each time i receive a new coordinate.
I was trying to use `Polyline` prop `strokeColors` but it doesn't work. I check the code and i couldn't found where this prop is used. A month ago, this props worked for me.
The colors's array would gradients from the blue color to the lightblue.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

   react: 16.0.0-alpha.12,
   react-native: 0.48.2,
  react-native-maps: 0.17.0

  I'm using Google Maps

### Steps to Reproduce

Just add the prop `strokeColors` to `Polyline` class with an array of coordinates and colors with same length.

### Expected Behavior

I would expect different colors for each pair of coordinates.

### Actual Behavior

Black line, no colors.

![screen shot 2018-05-10 at 12 39 02 pm](https://user-images.githubusercontent.com/28304582/39879165-7a1af848-5450-11e8-91f1-6857f6ee2d40.png)

**Comment by guidoprinc** [comment]
Currently i'm fixing this by mapping each color and adding a `Polyline` for each color and set a pair of coordinates and `strokeColor` to that color to get each line.

**Comment by chrisid** [comment]
I'm having the same issue

**Comment by frankfaustino** [comment]
Any word about this? I know the requirements for `strokeColors` array is it has to be the same length as the coordinates but I'm getting a black line instead.

**Comment by sjt145** [comment]
Hello, Even I am facing the same issue, if anyone have found the solution then please provide it...

**Comment by IsmailAlam786** [comment]
i am also facing this issue on android

Gradient Polylines (iOS MapKit only)
