### ISSUE TITLE
How to draw route between to points or Adding polyline on the maps?

### ISSUE THREAD

**Issue by ghost** [react-native-maps/react-native-maps#2261]
Please help me! Thanks you!

# Example
![map](https://user-images.githubusercontent.com/1733426/40097966-abfa7446-590b-11e8-97c6-ba41453442a1.jpg)

**Comment by luoerming** [comment]
@rborn Why is this issue closed? I did not see the solution.

**Comment by rborn** [comment]
@luoerming you didn't care to respect the issue template.
