### ISSUE TITLE
Allow an ability to disable fontScaling for map city labels

### ISSUE THREAD

**Issue by terrysahaidak** [react-native-maps/react-native-maps#2265]
### Is this a bug report?

The missing feature which is causing a bug for us.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, I've read the instruction.

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.6.0
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

### Steps to Reproduce

1. Increase the dynamic font value in the accessibility settings.
2. Open any app using the react-native-maps and you'll see the bigger city labels.

### Expected Behavior

We need an ability to control font scaling and enable it when we want to.
![image](https://user-images.githubusercontent.com/7809008/40166215-b08badc0-59c6-11e8-8e02-ef6e77483ea8.png)

### Actual Behavior

The map non-custom stuff like map city labels we can't change has increased font size, but we need an ability to disable it.

### Reproducible Demo

1. Increase the dynamic font value in the accessibility settings (first image).
2. Open any app using the react-native-maps and you'll see the bigger city labels (second image).

![image](https://user-images.githubusercontent.com/7809008/40166141-8183fd66-59c6-11e8-872e-4f6a683f0645.png)
![image](https://user-images.githubusercontent.com/7809008/40166158-91f4d8d2-59c6-11e8-950a-b33b9280e4d3.png)

**Comment by derrickbeining** [comment]
Same issue here!

**Comment by hellheim** [comment]
Same issue here. Any updates on this?

**Comment by Gokhanzorgul** [comment]
Same issue here!

**Comment by andrewTaylor2** [comment]
Having the same issue. +1

**Comment by kaonashi164** [comment]
Same issue +1

**Comment by terrysahaidak** [comment]
Still exists.

**Comment by ThanhNghia944** [comment]
Still exists.

**Comment by YeshanJay** [comment]
I'm facing the same problem. Can we reopen this issue?

**Comment by arundevkv** [comment]
Facing same issue. Please reopen

**Comment by codal-mpawar** [comment]
Please reopen we are still facing same issue.
