### ISSUE TITLE
SOLVED: "AirMaps" not found.

### ISSUE THREAD

**Issue by gabrielbuzziv** [react-native-maps/react-native-maps#2276]
For those that still getting the AirMaps not found error, the solution is simple.

You're probably getting this error cause you're usign an unsupported version of react native for this package.

I was using react-native 0.55.4, then i just downgraded to 0.54.4 and this worked like a charm.
I upgraded react too from 16.3.1. to 16.3.2.

then i just setted and installed the pods and runned the `react-native run-ios` again.

in case you get the react native version mismatch just run `watchman-del-all`

**Comment by diablourbano** [comment]
for those getting here, I already did this and didn't solve the issue, which is happening exclusively on android, please check GH #2301 

I need some help on that thanks :)
