### ISSUE TITLE
fitToCoordinates not working with edgePadding

### ISSUE THREAD

**Issue by sinhpn92** [react-native-maps/react-native-maps#2292]
I have an issue when **setPadding** to move **Google logo** to other position in the **MapView** by use method **fitToCoordinates** in **onLayout** callback. But, It's not working. 

I have found the cause of this issue in the native method:
https://imgur.com/AKOIQXE

<img width="967" alt="screen shot 2018-05-31 at 11 01 53 am" src="https://user-images.githubusercontent.com/9253441/40761266-0eae2f46-64c5-11e8-98a7-ce79ef57077a.png">

Could you please review and fix soon?

**Comment by GeekRishabh** [comment]
Getting the same issue. Please update if it is fixed.

**Comment by mightym** [comment]
Confirming this issue. Passing `edgePadding` to `fitToCoordinates` on Android doesn't have any effect.

**Comment by KasparasGud** [comment]
Same problem, `edgePadding` only works on iOS

**Comment by kenobi91** [comment]
It works for Android but for some reason it calculates paddings in raw pixel units. You can use PixelRatio.getPixelSizeForLayoutSize to convert units to raw pixels. For example if you want to have padding that is size half of height you can use it like this:

edgePadding = {
   ...
  bottom: (Platform.OS === 'android') ? PixelRatio.getPixelSizeForLayoutSize(height / 2) : (height / 2)
};

**Comment by rborn** [comment]
@kenobi91 could you open an issue that shows exactly the problem  (repro and solution) and link it here? 🤗

**Comment by kenobi91** [comment]
Ofc i will do it later np. :)
