### ISSUE TITLE
Can't animate custom markers

### ISSUE THREAD

**Issue by iremlopsum** [react-native-maps/react-native-maps#2309]
Hey guys, firstly let me explain what I'm trying to achieve. I have built custom markers, nothing fancy, just an svg. Now when I render the markers I want them to have an intro animation, but none if my `Animated` stuff works. Not sure if I'm doing something wrong or is this something that isn't supported?

### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native": "0.55.4",
"react-native-maps": "^0.21.0",
Android

### Steps to Reproduce

My current code for custom marker:

```
import React, { PureComponent } from 'react';
import { View, Animated } from 'react-native'
import { Marker } from 'react-native-maps';
import SVG from 'components/svg/SVG'

const BUSINESS_COLORS = {
  market: '#EC6D52',
  farm: '#763DAB',
  restaurant: '#C45D72',
  UrbanFarm: '#4B85DD',
  store: '#65A077',
}

class CustomMarker extends PureComponent {
  constructor(props) {
    super(props);
    this.spinValue = new Animated.Value(0);
  }
  componentDidMount() {
    this._animateThisIn()
  }
  _animateThisIn = () => {
    setTimeout(() => {
      Animated.spring(this.spinValue, {
        toValue: 1,
        bounciness: 15,
        useNativeDriver: true
      }).start()
    }, 5000)
  }
  render() {
    const { businessType, location } = this.props;
    const { shouldRender } = this.state;
    const iconColor = BUSINESS_COLORS[businessType.toLowerCase()];

    const spin = this.spinValue.interpolate({
      inputRange: [0, 1],
      outputRange: ['45deg', '360deg']
    })


    return (
      <Marker coordinate={{ ...location }}>
        <Animated.View style={{ width: 29, height: 36, transform: [{ rotate: spin }] }}>
          <SVG icon="Marker" width="29" height="36" fill={iconColor} />
        </Animated.View>
      </Marker>
    );

  }
}

export default CustomMarker;
```

### Expected Behavior

I would expect the `Animated` API to work as expected

### Actual Behavior

Not of the animations happen when using `Animated`

Any ideas?

**Comment by jpramassini** [comment]
Not a solution unfortunately, but I can add my experience here. On iOS, an Animated.View component wrapped in a standard View nested in the Marker is working. It does not, however, render anything on Android. Callouts still work and all other behavior is as expected, but there's nothing rendered.

**Comment by Michael-Antczak** [comment]
I think this is because Android can only render bitmaps as a marker so no marker animations on Android. It is fine on iOS. In my custom marker I detect the platform and if on Android then I render a static View, if on iOS then I run the animation.

**Comment by jpramassini** [comment]
That's the solution that I've resorted to as well. Thanks for the bitmap explanation, I hadn't considered that aspect.

**Comment by micchyboy237** [comment]
I believe this is a serious issue. Any fix on this?

**Comment by mhamzawey** [comment]
Is there any way to solve this issue?

**Comment by jeffhc** [comment]
Same issue. It may be that the Marker.Animated has animated support, but the enclosed custom marker contents (eg, Views, Images, etc.) are not animated.
