### ISSUE TITLE
Size of marker images (when defined as marker props)

### ISSUE THREAD

**Issue by rahamin1** [react-native-maps/react-native-maps#2340]
### Is this a bug report?
Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
No. I am using Expo and followed the instructions [there](https://docs.expo.io/versions/latest/sdk/map-view).

### Environment
- "react": "16.3.1",
- "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
 (documentation [here](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4, using react-native-maps 0.21.0)
-  Target Platform: Android 7.1.0/Galaxy S6/Genymotion

### Steps to Reproduce
- Because of the problem discussed in #1870, and until it is solved, there is a need to use marker's images as props (and not as children Images within a marker's View)
- I am rendering the same image twice:
  (1) As a Marker's prop Image
  (2) Outside of a Marker
- The size of (2) is three times the size of (1). I expected them to be of identical size.

### Expected Behavior
Have the images of (1) and (2) displayed with identical size.

### Actual Behavior
The size of (2) is three times the size of (1).

### Notes:
- #1422 talks about the same problem is closed, but I don't see how it explains what I am experiencing
- #1870, which is still open, discusses this problem, but talks mainly about the problem of not rendering marker images that are defined as marker's children, in android 7.1 and higher android versions

### Reproducible Demo
```
import React, { Component } from 'react';
import { View, Text, Image, Platform } from 'react-native';
import { MapView } from 'expo';

const centerOffset = { x: 0, y: 0 };
const anchor = { x: 0.125, y: 0.1 };
const cityCoordinates = { latitude: 40, longitude: 40 };
const imageName = require("../images/flag.png");

class CityMarker extends Component {

  constructor(props) {
    super(props);
    this.renderCallout = this.renderCallout.bind(this);
  }

  render() {

    // https://github.com/react-community/react-native-maps/issues/1870
    if (Platform.OS === 'android' && Platform.Version >= 24) {
      return (
        <MapView.Marker
          coordinate={cityCoordinates}
          centerOffset={centerOffset}
          anchor={anchor}
          calloutAnchor={{ x: 0, y: 0 }}
          image={imageName}
          >
          {this.renderCallout()}
        </MapView.Marker>
      );
    } else {
      return (
        <MapView.Marker
          coordinate={cityCoordinates}
          centerOffset={centerOffset}
          anchor={anchor}
          calloutAnchor={{ x: 0, y: 0 }}
          >
          <Image
            source={imageName}
          />
          {this.renderCallout()}
        </MapView.Marker>
      );
    }
  }

  renderCallout() {
    return (
      <MapView.Callout tooltip={true}>
        <View>
          <Text>
            callout text
          </Text>
        </View>
      </MapView.Callout>
    );
  }
}

export default CityMarker;
```

**Comment by HighSoftWare96** [comment]
Is there any workaround on this problem?

**Comment by IAmMarcellus** [comment]
@rahamin1 Were you able to find a solution to this problem? I'm having the same issue

**Comment by rahamin1** [comment]
No, just adjusted to it...
