### ISSUE TITLE
KML Markers from example not showing 

### ISSUE THREAD

**Issue by pncosta** [react-native-maps/react-native-maps#2360]
#### Is this a bug report?
YES

#### Have you read the Installation Instructions?
YES

#### Environment
 "react": "^16.3.0-alpha.1",
 "react-native": "^0.54"

Build the example [AirMapsExplorer](https://github.com/react-community/react-native-maps/tree/master/example), selected GoogleMaps mode and clicked "Load Map with KML".

Tried to do my own app as well with the same results.

Tried on both IOS and Android simulators.

#### Expected Behavior

Multiple Markers loaded from the KML file to show up on the map

#### Actual Behavior

No markers from the KML are shown.
Only The "Test" marker from the example is shown ( [added](https://github.com/react-community/react-native-maps/blob/master/example/examples/MapKml.js#L49)  as <Marker> not loaded from the KML)

**Comment by mohsinriaz17** [comment]
any update on this ? same issue

**Comment by mschinis** [comment]
having issues rendering kml files also. tried both the example as well as my own implementation and none of the two render any points

**Comment by yasir-lateef** [comment]
As far as I understand, the example contains a link to a pastebin, which is returned as text while a KML file should be loaded with a proper MIME type i.e the server should respond with status 200 and `Content-Type: application/vnd.google-earth.kml+xml` in order for Google Maps to properly parse it as KML file.

**Comment by Nagavikas96** [comment]
Any update on this, I can run load example project with the pastebin, but unable to load my own kml file, My project got stopped due to this, can any one please help me on this....

**Comment by Luccasoli** [comment]
Same with me :(, im using:
"react-native-maps": "0.27.1"
"react-native": "~0.63.3"

**Comment by zabojad** [comment]
> As far as I understand, the example contains a link to a pastebin, which is returned as text while a KML file should be loaded with a proper MIME type i.e the server should respond with status 200 and Content-Type: application/vnd.google-earth.kml+xml in order for Google Maps to properly parse it as KML file.

It seems it's not the reason why this is happening. I load my kml files from a server that sets correctly the `Content-Type` header to `application/vnd.google-earth.kml+xml`

**Comment by zabojad** [comment]
hmmm. I've managed to render my kml data by editing the AIRGoogleMap.m file as per https://developers.google.com/maps/documentation/ios-sdk/utility/kml#maps_ios_kml-objective-c

It works but the almost entire [`setKmlSrc`](https://github.com/react-native-maps/react-native-maps/blob/3338a960c62cc3c364286433ab98e5cf59435ebf/lib/ios/AirGoogleMaps/AIRGoogleMap.m#L835) method is rewritten...

**Comment by chunghn** [comment]
Encountering this issue on `1.4.0`.
