### ISSUE TITLE
mapPadding for polyline/markers

### ISSUE THREAD

**Issue by Billy-** [react-native-maps/react-native-maps#2361]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.4
    react: 16.3.2
    react-native-maps: 0.19.0

  Target Platforms: iOS 10+, Android 7.1.1

### Steps to Reproduce

1. Create a `MapView` and plot some markers and/or polylines
2. Set `region` and/or `initialRegion` to be a region that exactly wraps the positions of the `MapView`s children
3. Set `mapPadding` prop to whatever your heart desires
4. Observe that the google logo and directions toolbar (if enabled in Android) are positioned properly in respect to the `mapPadding` prop, and that the `MapView`s children are not - they will be hard up against the side of the `MapView`.

### Expected Behavior

`mapPadding` prop should affect the google logo and toolbar and markers/polylines/etc. at all times

### Actual Behavior

`mapPadding` prop affects only the google logo and toolbar but _not_ any markers/polylines/etc. that are added to the `MapView` as children
`animateToRegion` and `fitToElements` both honor the `mapPadding` prop and apply it to the google logo and toolbar _and_ any markers/polylines etc. that are added to the `MapView` as children

(Write what happened. Add screenshots!)

### Reproducible Demo

Could someone please explain how to get react-native-maps running in expo/snack as I've never used it before and can't work it out.. Then I can add a demo here! :smile: 

### Is this a bug report?
No, a question.

I'm trying to add padding around the polylines and markers I have displayed on a map (and I have set `initialRegion` to contain the points in those polylines and markers). I expected `mapPadding` to do this but it only seems to affect the google logo and toolbar buttons etc., but not any components I have added to the `MapView`.
I have asked this on stackoverflow and got no response at all: https://stackoverflow.com/questions/51140328/react-native-maps-mappadding-for-polyline-region

Is there any way to achieve what I am trying to do?

**Comment by rborn** [comment]
@Billy- you could try to detect mix/max latitude/longitude for all the  polylines points and set the region delata a little bigger

**Comment by Billy-** [comment]
I have just implemented using `animateToRegion` on my map - and this seems to take into account the `mapPadding` that I passed as a prop. Given this, I would stipulate that this is inconsistent behaviour and perhaps this issue could become a bug report?

**Comment by Billy-** [comment]
> you could try to detect mix/max latitude/longitude for all the polylines points and set the region delata a little bigger

Thought of this, and this is what I am doing for now (`deltas * 1.25`). Problem is, the amount of space this will produce varies greatly depending on a) where in the world the region corresponds to, and b) how large the region is. So unforuntately this is really a terrible solution. What I want to be able to do is say "I want `x` points of space - which corresponds to on screen pixels/units

**Comment by Billy-** [comment]
`fitToElements` also takes `mapPadding` into account. I'm definitely thinking it's a bug that the map doesn't take it into account in the first instance. Would anyone agree with that?

**Comment by Billy-** [comment]
ping @rborn

**Comment by rborn** [comment]
@Billy- you could create a bug report with the behaviour and how you think it should be. 
I'm not sure how soon will be solved though as this is a fully community project so everyone participates how and when they can.

**Comment by Billy-** [comment]
@rborn Can we re-tag this issue to be a bug report rather than a question? I can update the original post.

To clarify;

Current behaviour:
`mapPadding` prop affects only the google logo and toolbar and _not_ any markers/polylines/etc. that are added to the `MapView` as children
`animateToRegion` and `fitToElements` both honor the `mapPadding` prop and apply it to the google logo and toolbar _and_ any markers/polylines etc. that are added to the `MapView` as children

Expected behaviour:
`mapPadding` prop should affect the google logo and toolbar _and_ markers/polylines/etc. at all times

**Comment by rborn** [comment]
Please update the issue following the template and I'll do it

**Comment by rborn** [comment]
@Billy- thanks

expo/snack uses a version of the module published on npm and not the git one. 
maybe by editing the package.json in https://snack.expo.io/ will allow you to use this version? (not sure)

**Comment by Billy-** [comment]
Couldn't get it to work - added to the dependencies but get an error about `Unable to resolve module`: https://snack.expo.io/SJ83fIQ7X

**Comment by micchyboy237** [comment]
any update on this guys? seems to be a bug especially in Android

**Comment by Hannah-Alto** [comment]
Same, waiting for updates, a bunch of inconsistencies in Android
