### ISSUE TITLE
Marker moves on map without coordinates changing

### ISSUE THREAD

**Issue by katima-g33k** [react-native-maps/react-native-maps#2403]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.53.3
    react: 16.2.0
    react-native-maps: 0.20.1

### Steps to Reproduce

1. Load map with a marker and user position
2. Zoom out slightly on map
3. Wait, marker will jump from one place to other across the map

(I added my code below in the demo section)

### Expected Behavior

Map should display correctly with current user position and marker and the marker should stay at the same location.

### Actual Behavior

Map loads correctly with marker and user position, but after some time (time varies at each try), the marker starts changing positions on map displaying at an overall of about 3-4 locations within about 500m from each other. For the exemple I had added `console.warns` on my view `render`method on every event of `MapView`and `Marker`. None of which where triggered during the marker's jump through space.

![react-native-marker-bug](https://user-images.githubusercontent.com/7608273/43416032-2aef5238-9405-11e8-930b-52c45eb65310.gif)

### Reproducible Demo

```javascript
// In exemple the marker coordinates that are used are:
// latitude 45.3826204,
// longitude -71.9265674,

import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { Dimensions, View } from 'react-native';
import MapView from 'react-native-maps';

import geolocationAPI from '../dependencies/app/geolocationAPI';

const DEFAULT_CENTER = {
  latitude: 45.3811879,
  longitude: -71.922789,
};

export default class Map extends Component {
  static propTypes = {
    center: PropTypes.shape({
      latitude: PropTypes.number,
      longitude: PropTypes.number,
    }),
    markers: PropTypes.arrayOf(PropTypes.shape({
      coordinates: PropTypes.shape({
        latitude: PropTypes.number,
        longitude: PropTypes.number,
      }),
      radius: PropTypes.number,
    })),
    style: PropTypes.shape(),
  }

  static defaultProps = {
    center: {
      latitude: 0,
      longitude: 0,
    },
    markers: [],
    style: {},
  }

  setMapRef = (map) => {
    this.map = map;
  }

  getCenter = () => {
    if (this.props.center.latitude === 0 && this.props.center.longitude === 0) {
      if (this.props.markers.length === 1) {
        // If no center and only one marker return marker as center
        return this.props.markers[0].coordinates;
      }

      // If no center return default center
      return DEFAULT_CENTER;
    }

    return this.props.center;
  };

  fitBounds = async () => {
    const currentPosition = (await geolocationAPI.getCurrentPosition()).coords;
    const coordinates = [
      ...this.props.markers.map(marker => marker.coordinates),
      currentPosition,
    ];
    const bottomPadding = this.props.style.height ? Math.round(this.props.style.height / 3) : 5;
    const edgePadding = { top: 50, right: 15, bottom: bottomPadding, left: 15 };
    this.map.fitToCoordinates(coordinates, { animated: false, edgePadding });
  }

  renderMarkers = () => this.props.markers.map(marker => (
    <MapView.Marker
      coordinate={marker.coordinates}
      key={`marker-${marker.coordinates.latitude}`}
      image={marker.image}
      pinColor={marker.color}
      title={marker.title}
    />
  ))

  render() {
    const height = Dimensions.get('window').height / 3;

    return (
      <View>
        <MapView
          followsUserLocation
          initialRegion={{
            ...this.getCenter(),
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
          onMapReady={this.fitBounds}
          showsUserLocation
          style={[{ height }, this.props.style]}
          ref={this.setMapRef}
        >
          {this.renderMarkers()}
        </MapView>
      </View>
    );
  }
}
```

**Comment by vjeranc** [comment]
Do you have more than one map instantiated inside your app?

**Comment by katima-g33k** [comment]
@vjeranc I have 3 views that can each instantiate my MapView. But there should not be more than one active instance at a time.

**Comment by vjeranc** [comment]
Are you sure that those views are not mounted? gmaps library on android has a bug (really old one and I do not know if they fixed it) where multiple instances of a map view can cause marker jumps.

I'm asking because if this is not the case then I'll have to check if my workaround works.

https://stackoverflow.com/questions/37743929/two-mapviews-in-one-android-activity-jumping-flickering-markers

Here you can see the gif.

Something similar happens in #984

**Comment by dilekamadushan** [comment]
> Do you have more than one map instantiated in your app?

I ran into the same issue of late, this discussion helped me to sort out the issue. Thank you very much. Two  parallel MapView instances had caused the issue :)

**Comment by royken** [comment]
Hello,
Has anyone found a solution for this issue ?

**Comment by bearer-syntaxerror** [comment]
I'm seeing the same issue. 
We recently updated from React Native v57.8 to React Native v59.9 and enabled 64 bit. 
It does not appear to repro in our React Native v57.8 builds.

**Comment by chris-topher19** [comment]
experiencing the same issue

**Comment by misterchlee7** [comment]
I've commented on this on a separate open issue (https://github.com/react-native-community/react-native-maps/issues/3098#issuecomment-567710731)

I was having the same issue but on Android only. In my case we did have times where two maps would be instantiated at the same time. I also had a console.log on my marker render method to indeed confirm that even though the markers were visually teleporting, it was not actually re-rendering.

I've tried `trackViewChanges={ false }` and also generating each marker with a different zIndex to no success.

However, enabling `liteMode` on MapView fixed my flickering / teleporting markers issues and no other change other than that was made.

- on react-native@0.59.10 & react-native-maps@0.24.2

**Comment by Diyaa-Gubarah** [comment]
for me i have 3 tab each one return MapView (I have file called CustomMap.js) So in my CustomMap.js I did this.

```
import {useIsFocused} from '@react-navigation/native';
.
.
export default CustomMap= ()=> {
  const isFocused = useIsFocused();
.
.
return (
    isFocused && (<MapView ......./>))
 }
```
