### ISSUE TITLE
Loading KML file doesn't work

### ISSUE THREAD

**Issue by SuperBesse** [react-native-maps/react-native-maps#2438]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES (and maps works perfectly on my project and on example project)

### Environment

    react-native: 0.54.0
    react: 6.0.0-beta.5
	react-native-maps: 0.21.0 or "git+ssh://git@github.com/react-community/react-native-maps.git"

### Steps to Reproduce

build example project on ios simulator.
Click on button `Load Map with KML`

### Expected Behavior

A map appears with data from KML.

### Actual Behavior

Crash of native part
<img width="532" alt="capture d ecran 2018-08-19 a 11 05 35" src="https://user-images.githubusercontent.com/10027577/44307321-8b2ee000-a3a0-11e8-97aa-5cb9d3cbe99e.png">

And when i look at in  `AirMap.m`, i don't find the selector `setKmlSrc`.

**Comment by yasir-lateef** [comment]
Hi @SuperBesse,

I just noticed that this exception is raised if you try to use KML file with Apple Maps. If you set `provider={PROVIDER_GOOGLE}` for your Map component, this exception should go away.

PS: Don't forget to `import { PROVIDER_GOOGLE } from 'react-native-maps'`

Cheers! Hope this helps.
