### ISSUE TITLE
Overlapping Polygons Not Respecting Z-Index for onPress

### ISSUE THREAD

**Issue by jameskirkpatrick23** [react-native-maps/react-native-maps#2463]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

  "react-native": "0.52.2",
  "react": "16.2.0",
  "react-native-maps": "^0.21.0",

### Steps to Reproduce
1. Create a polygon on your map, complete with an onPress Event.
***
<Polygon
          id="WORK"
          ref={(polygon) => this.polygons[0] = polygon}
          coordinates={coords}
          zIndex={2}
          onPress={this.onPolygonPress}
        />
***
2. Create a second polygon on your map that completely surrounds the first polygon
***
<Polygon
          id="SURROUNDING WORK BOUNDARY"
          ref={(polygon) => this.polygons[1] = polygon}
          coordinates={coords}
          zIndex={1}
          onPress={this.onPolygonPress}
        />

![screen shot 2018-08-27 at 12 43 12 pm](https://user-images.githubusercontent.com/14095551/44672595-e98a3d00-a9f6-11e8-9b55-94cccbdd2f5c.png)

***
3. Try to press the inner zone, and see that occasionally your outer zone fires its onPress callback instead
***

### Expected Behavior

Expected the polygon with the highest zIndex (WORK) to be the one that gets its onPress called, rather than the lower zIndexed encapsulating zone (SURROUNDING WORK BOUNDARY)

### Actual Behavior

Mentioned above. About half the time it calls the higher zIndexed one, and the other half if calls the lower zIndexed one... Not really sure how else to describe it.

### Reproducible Demo

```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import MapView, { MAP_TYPES, Polygon, ProviderPropType, Polyline, Marker, Overlay } from 'react-native-maps';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      currentRegion: {}
    }
  }

  onRegionChange = (currentRegion) => {
    this.setState({ currentRegion });
  }

  render() {
    let innerPolygonCoords = [
      {latitude: 39.945664269783, longitude: -74.9784275516868},
      {latitude: 39.9460395481404, longitude: -74.9788198247552},
      {latitude: 39.9463371989628, longitude: -74.9777724221349},
      {latitude: 39.9454247074537, longitude: -74.9762298166752},
      {latitude: 39.945023207334, longitude: -74.9767531827092},
      {latitude: 39.944949435929, longitude: -74.9768386781216},
      {latitude: 39.9450879821606, longitude: -74.9771551787853},
      {latitude: 39.9453774117874, longitude: -74.9778341129422},
    ];

    let outerPolygonCoords = [
      {latitude: 39.9461053501609, longitude: -74.9832649156451},
      {latitude: 39.9476904914243, longitude: -74.973856061697},
      {latitude: 39.9434387754156, longitude: -74.9728462100029},
      {latitude: 39.9408512708827, longitude: -74.9806665256619}
    ];

    return (
      <View style={styles.container}>
        <MapView
            provider={'google'}
            ref={ref => this.map = ref}
            showsUserLocation
            showsPointsOfInterest
            showsScale
            showsCompass
            loadingEnabled
            onRegionChange={this.onRegionChange}
            showsMyLocationButton
            mapPadding={{top: 10, right: 10, bottom: 10, left: 10}}
          >
          <Polygon
            ref={(polygon) => this.polygons[0] = polygon}
            coordinates={innerPolygonCoords}
            tappable={true}
            zIndex={2}
            onPress={(e) => {console.warn('I pressed the inner zone')}}
          />
          <Polygon
            ref={(polygon) => this.polygons[1] = polygon}
            coordinates={outerPolygonCoords}
            tappable={true}
            zIndex={1}
            onPress={(e) => {console.warn('I pressed the outer zone')}}
          />
          </MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
});
```

**Comment by danTheWizard** [comment]
I am having the same issue with overlapping polyline. Any chance you found a solution?

**Comment by verochan** [comment]
Hi @jameskirkpatrick23 , did you solve this problem? Thanks.

**Comment by jameskirkpatrick23** [comment]
> Hi @jameskirkpatrick23 , did you solve this problem? Thanks.

@vincentvella I'm not sure if this is still an issue. Can you check?

**Comment by verochan** [comment]
I'm still experiencing this issue just on iOS, on Android it always worked ok. Any solution to this? :(

**Comment by jameskirkpatrick23** [comment]
@verochan I don't believe we ever found a solution to this issue on iOS. I think we created a separate component to handle the selection (a dropdown of the available polygons), thereby circumnavigating the issue.

**Comment by verochan** [comment]
@jameskirkpatrick23 So sad... Thanks for your feedback 👍
