### ISSUE TITLE
fitToElements not accounting for circle

### ISSUE THREAD

**Issue by jrdn91** [react-native-maps/react-native-maps#2465]
### Is this a bug report?

Possibly, maybe just a caveat of the `fitToElements` method

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
react-native: 0.55.2
react: 16.3.1
expo: 27.0.1
Target Platform iOS (using google maps)

### Steps to Reproduce

Add markers and circles with radiuses into the map view then call `fitToElements` on the mapview ref

### Expected Behavior

I expected the mapview to fit to all the elements that were in the mapview

![img_004a94eba9dc-1](https://user-images.githubusercontent.com/1076459/44735720-39cad300-aabb-11e8-8eb9-11fdf9c14446.jpg)

### Actual Behavior

it seems to only calculate the markers and not also the circle

![img_9d6e05a4c8b9-1](https://user-images.githubusercontent.com/1076459/44735725-3df6f080-aabb-11e8-8396-3ef4d57b9581.jpg)

### Reproducible Demo

https://snack.expo.io/@jordanr/fittoelements-issue

**Comment by rborn** [comment]
@Jordan4jc expo uses an older version of the module, can you please test with the git one?

**Comment by JanErikFoss** [comment]
My map isn't account for the circle either.
Latest version, 0.24.2

**Comment by fendorio** [comment]
Seeing this also

**Comment by JanErikFoss** [comment]
Anyone know more about this?
I currently have to fix it by approximating top left and bottom right of circle, then fitting to those points.
It's not really a solution that works well with multiple circles and markers.

**Comment by luca-saggese** [comment]
> Anyone know more about this?
> I currently have to work around the issue by approximating top left and bottom right of circle, then fitting to those points.
> It's not really a solution that works well with multiple circles and markers.

can you please share the code? i'm trying to fit only one circle
