### ISSUE TITLE
Could not find method implementation() for arguments [project ':react-native-maps', build_5yzom2lyrek7xvyvgp2oo4gzp$_run_closure1$_closure3$_closure4@1d634cfe] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by lastpeony** [react-native-maps/react-native-maps#2466]
When i react-native run-android i get this error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\xcrix\Desktop\projects\The Art Hunter\arthunterclient\android\build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'arthunterclient'.
> Could not find method implementation() for arguments [project ':react-native-maps', build_5yzom2lyrek7xvyvgp2oo4gzp$_run_closure1$_closure3$_closure4@1d634cfe] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Android/build.gradle:

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        repositories {
            jcenter()
             google()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.1.0'  
    implementation(project(':react-native-maps')){
           exclude group: 'com.google.android.gms', module: 'play-services-base'
           exclude group: 'com.google.android.gms', module: 'play-services-maps'
       }
       implementation 'com.google.android.gms:play-services-base:10.0.1'
       implementation 'com.google.android.gms:play-services-maps:10.0.1'
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
    
    allprojects {
        repositories {
            mavenLocal()
            jcenter()
            google()
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
            
        }
    }

Android/gradle.properties

    android.enableAapt2=false
    android.useDeprecatedNdk=true
Android/settings.gradle

    rootProject.name = 'arthunterclient'
    
    include ':app'
    include ':react-native-maps'
    project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

Android/app/build.gradle

    apply plugin: "com.android.application"
    
    import com.android.build.OutputFile
    
   
    
    project.ext.react = [
        entryFile: "index.js"
    ]
    
    apply from: "../../node_modules/react-native/react.gradle"
    
    /**
     * Set this to true to create two separate APKs instead of one:
     *   - An APK that only works on ARM devices
     *   - An APK that only works on x86 devices
     * The advantage is the size of the APK is reduced by about 4MB.
     * Upload all the APKs to the Play Store and people will download
     * the correct one based on the CPU architecture of their device.
     */
    def enableSeparateBuildPerCPUArchitecture = false
    
    /**
     * Run Proguard to shrink the Java bytecode in release builds.
     */
    def enableProguardInReleaseBuilds = false
    
    android {
        compileSdkVersion 26
        buildToolsVersion "26.0.1"
    
        defaultConfig {
            applicationId "com.arthunterclient"
            minSdkVersion 16
            targetSdkVersion 22
            versionCode 1
            versionName "1.0"
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }
        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  // If true, also generate a universal APK
                include "armeabi-v7a", "x86"
            }
        }
        buildTypes {
            release {
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
        }
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
    }
    
    dependencies {
      implementation fileTree(dir: "libs", include: ["*.jar"])
      implementation "com.android.support:appcompat-v7:23.0.1"
      implementation "com.facebook.react:react-native:+"
      implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
      }
      implementation 'com.google.android.gms:play-services-base:10.0.1'
      implementation 'com.google.android.gms:play-services-maps:10.0.1'
    }
    
    // Run this once to be able to run the application with BUCK
    // puts all compile dependencies into folder libs for BUCK to use
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
    }
Android/gradle/wrapper/gradle-wrapper.properties:

    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

I spent more than 5 hours to solve this problem.tried everything on internet but still same...

**Comment by rborn** [comment]
Update gradle in `_PROJECT_PATH_/android/gradle/wrapper/gradle-wrapper.properties`  to
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

**Comment by taviroquai** [comment]
I run into this problem.

@lastpeony What was the solution?

**Comment by sachithkadamba** [comment]
Hi, Any workaround for this issue?

**Comment by bouchja1** [comment]
Same issue here. Did you find the solution?
