### ISSUE TITLE
Callout(annotation) is jumped to nearest marker when using custom markers in same location(lat lon).

### ISSUE THREAD

**Issue by 777uday** [react-native-maps/react-native-maps#2492]
Is this a bug report?
Yes

Have you read the Installation Instructions?
Yes

Environment
"react": "16.3.1",
 "react-native": "0.55.4",
"react-native-maps": "0.18.3"

Steps to Reproduce
Note: this issue is faced in iOS only. Working perfectly in Android.
Add more than 2 markers at same location, and tap on it. Or add more than 2 markers very near to each other, then zoom out until both the markers are nearby and tap on marker.

Expected Behavior
Tapping on a Marker should only trigger the popup of the selected marker.

Actual Behavior
When i am clicking on the marker, callout of marker1 is bubbled ,closes on its own and then reopen callout of marker2.

Reproducible Demo
(Write your steps here:)

import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';

class MapHome extends Component {
render() {
return (

<MapView
style={styles.map}
initialRegion={{
latitude: 33.831105,
longitude: -117.130453,
latitudeDelta: 0.0922,
longitudeDelta: 0.0421,
}}
>
{this.state.records.map(marker => (
                        <MapView.Marker
                            coordinate={{ latitude: marker.location_lat, longitude: marker.location_lon }}
                            title={'title'}
                            zIndex={3}
                            identifier={'identifier'}
                            key = {marker.id}
                            description={'description'}
                            image={marker.imageURL}
                            onCalloutPress={() => this.action(marker)}
                        </MapView.Marker>
                    )) : null
                    }

);
}
}

const styles = StyleSheet.create({
container: {
...StyleSheet.absoluteFillObject,
justifyContent: 'flex-end',
alignItems: 'center',
},
map: {
position: 'absolute',
top: 0,
left: 0,
right: 0,
bottom: 0,
},
});

export default MapHome;

![ezgif com-gif-maker](https://user-images.githubusercontent.com/28705704/45610047-2ab2c180-ba78-11e8-9bdf-71749fe0d76c.gif)

**Comment by KarlosQ** [comment]
My solution is edit AIRMapMarker.m (in node_modules/react-native-maps/lib/ios/AirMap/AIRMapMarker.m) and comment part of _handleTap function:

        - (void)_handleTap:(UITapGestureRecognizer *)recognizer {
            AIRMapMarker *marker = self;
            if (!marker) return;
            
            if (marker.selected) {
                CGPoint touchPoint = [recognizer locationInView:marker.map.calloutView];
                if ([marker.map.calloutView hitTest:touchPoint withEvent:nil]) {
                    
                    // the callout got clicked, not the marker
                    id event = @{
                                @"action": @"callout-press",
                                };
                    
                    if (marker.onCalloutPress) marker.onCalloutPress(event);
                    if (marker.calloutView && marker.calloutView.onPress) marker.calloutView.onPress(event);
                    if (marker.map.onCalloutPress) marker.map.onCalloutPress(event);
                    return;
                }
            }
            
            // the actual marker got clicked
            /*id event = @{
                        @"action": @"marker-press",
                        @"id": marker.identifier ?: @"unknown",
                        @"coordinate": @{
                                @"latitude": @(marker.coordinate.latitude),
                                @"longitude": @(marker.coordinate.longitude)
                                }
                        };
            
            if (marker.onPress) marker.onPress(event);
            if (marker.map.onMarkerPress) marker.map.onMarkerPress(event);
            
            [marker.map selectAnnotation:marker animated:NO];*/
        }

**Comment by dragonza** [comment]
I encountered similar issue. Is there any other approach than fixing the file in node_modules which I am not a good idea?

**Comment by iamswain25** [comment]
Also happened to android device on expo dev.

**Comment by pesaorus** [comment]
Same problem on react-native-maps 0.24.2

**Comment by cokron** [comment]
I have the same issue. iOS only.

Interestingly, the `onPress(…)` event is only fired for the marker I have really clicked on. But the `onSelect(…)` event is fired for _both the marker I clicked on to open the callout + the neighbouring marker_.

I did some research and it seems that the error was introduced here (as mentioned by leonardogutierrezh in a comment to the PR):
https://github.com/react-native-community/react-native-maps/pull/1079

There is a strange workaround here: https://github.com/react-native-community/react-native-maps/issues/1353 (set `pointerEvents="auto"`, which worked for me, but makes appearance of callout slow.).

This issue is a duplicate of https://github.com/react-native-community/react-native-maps/issues/3047 and has been asked here as well: https://stackoverflow.com/questions/52293052/jumping-markers-jumping-to-next-or-nearest-marker-in-react-native-maps?rq=1.

**Comment by 18clans** [comment]
Having the same issue.  Decided to use Google Maps on iOS but ran into some performance issue.  Please update once this is fixed.

**Comment by Barney4242** [comment]
Any update on this issue?

**Comment by javi242** [comment]
I am having the same issue. Not fixed yed? Any help would be great. Thanks.

**Comment by facingmonday** [comment]
As far as I can tell after a whole lot of searching, there is no fix for this. I had to switch to the google map provider.

**Comment by ericampagna** [comment]
Please reopen, This is still a bug.

**Comment by tomh4** [comment]
Even now, still a bug
putting `pointerEvents="auto"` inside the Marker helps, but makes the callout slower so only a workaround, not a solution

**Comment by daveybell26** [comment]
This is still an open issue.
