### ISSUE TITLE
onPress function not being called as child of Callout

### ISSUE THREAD

**Issue by nathmack** [react-native-maps/react-native-maps#2508]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yep

### Environment

"react": "^16.5.0",
"react-native": "^0.57.1",
"react-native-maps": "^0.19.0",

simulator: iPhone 7 - 12.0

### Steps to Reproduce

Add a child with an `onPress` callback inside a `MapView.Callout` component

### Expected Behavior

The onPress callback should be called

### Actual Behavior

It does not get called

### Reproducible Demo

![image](https://user-images.githubusercontent.com/15811469/45948339-e9538080-c03a-11e8-9c4b-64966ba5c399.png)

```
<MapView.Callout>
  <TouchableOpacity onPress={() => { console.log('this does not get called 😞') }}>
    <Text style={{ padding: 10, backgroundColor: 'white' }}>
      Click me!
    </Text>
  </TouchableOpacity>
</MapView.Callout>
```

**Comment by nathmack** [comment]
Ok I have some additional information. For some reason this bug seems to be connected to the `provider` prop being set on the `MapView` component

I have done some testing below:

![image](https://user-images.githubusercontent.com/15811469/45950152-f45ddf00-c041-11e8-8387-878dd0d41cc6.png)
With no `provider` prop set each `TouchableOpacity` can be clicked and will log correctly
![image](https://user-images.githubusercontent.com/15811469/45950198-21aa8d00-c042-11e8-992d-13208b0129ce.png)

Once I set the provider prop I can no longer get a click

Have a look what happens when I apply some styles to the marker:
provider not set:
![image](https://user-images.githubusercontent.com/15811469/45950448-215ec180-c043-11e8-8ef6-5eea741afe7b.png)

provider set:
![image](https://user-images.githubusercontent.com/15811469/45950460-33d8fb00-c043-11e8-85f4-08346708a64c.png)

Notice that the marker's background color is actually in front of the marker and it's callout
![image](https://user-images.githubusercontent.com/15811469/45950475-4d7a4280-c043-11e8-8e97-54f859c6a546.png)

Not really sure what to make of that at the moment, but at least we know it has something to do with `provider`.

**Comment by rborn** [comment]
@nathmack what provider? does it behave the same for `PROVIDER_GOOGLE` and `PROVIDER_DEFAULT`

**Comment by rborn** [comment]
@nathmack looking again, I think you might want to use this instead of a touchable: https://github.com/react-community/react-native-maps/blob/master/docs/callout.md#events

**Comment by nathmack** [comment]
The issue occurs when using `PROVIDER_GOOGLE`, I have not tested with `PROVIDER_DEFAULT` but I assume that would have the same behaviour as not defining a provider at all,  as it's value is `null`
```
export const PROVIDER_DEFAULT = null;
export const PROVIDER_GOOGLE = 'google';
```

I can verify that when I get a chance though.

**Comment by nathmack** [comment]
In my actual use case I need two options in the callout, so I can't just add an `onPress` to the callout, I need an `onPress` on each of the options in the children

**Comment by HighSoftWare96** [comment]
I need that too... Is there a workaround for this?

**Comment by stdavis** [comment]
I'm experiencing the same issue and setting the provider to `null` had no effect. Is there someone that could point me in the right direction on how to fix this bug? I'd be happy to attempt a PR.

**Comment by motyl1338** [comment]
up, if someone can help I will be grateful.

**Comment by cinder92** [comment]
any update in this?

**Comment by richard4s** [comment]
You could use this instead https://stackoverflow.com/a/41161292/9104897

**Comment by brownieboy** [comment]
It works for on iOS with Apple Maps.  But on Android, the onPress for the Callout itself seems to take precedence over any elements that you've set up with onPress within that Callout.

And if I've set on onPress on the Callout, then nothing at all happens!

**Comment by ossraju** [comment]
hello @nathmack I used Flatlist in the Callout it works for me on iOS and i am facing issue on Android i am able to display the Flatlist but I could not able to execute the onpress function on the Listitems.
```javascript
{ data.map((Url,index) => {
              const a = {
                latitude: Url.latitude,
                longitude: Url.longitude
              }
             return <MapView.Marker style={{zIndex: 5}}
                identifier={Url.items[0].target}
                key={Url.items[0]._id}
                coordinate={a}
                image={this.returnPin(Url.items[0].pin_icon)}>
              
            <MapView.Callout style={{flex:1}} tooltip>
            <FlatList
             data={[Url.items]}
            renderItem={({item}) => 
              item.map((eachitem,index) =><TouchableOpacity onPress={()=>this.onPressItem(eachitem)}>
                  <View style={{width: 300, padding: 5,marginBottom:2, justifyContent: 'center', alignContent: 'center', alignItems: 'center', backgroundColor: '#' + eachitem.color[1].substring(2), borderRadius: 10}}>
                  <Text style={{color: 'white', fontWeight: 'bold', textAlign: 'center'}}>{eachitem.titres[0]}</Text>
                  <Text style={{color: 'white', textAlign: 'center'}}>{eachitem.titres[1]}</Text>
                 </View>
                 </TouchableOpacity>
                 )
                }/>

            
            </MapView.Callout >

              </MapView.Marker>

             }) }
```

**Comment by TheChanDI** [comment]
Is this issuse solved??? Did anyone find the solution for child  of callout not taking onPress function??

**Comment by amsimoes** [comment]
@ossraju I'm having the same issue... Were you able to fix it?

**Comment by spyshower** [comment]
Same here (android)

**Comment by ossraju** [comment]
@amsimoes , sorry for late reply.
No, android i can't  but on iOS its working like charm

**Comment by amsimoes** [comment]
@ossraju no problem! I've found my problem was that I was styling some components with zIndex (just trying things out) and then forgot about it.
Once I removed zIndex it started working as intended (on Android, iOs was working fine).

**Comment by nathmack** [comment]
I never did get this working. Although I have not touched that project in many months now. I should really give it another go!

**Comment by nehresma** [comment]
I also landed here after experiencing this same issue and trying to track it down.

**Comment by sardok** [comment]
Same issue for me on iOS.

**Comment by robertvorthman** [comment]
Same problem on iOS with Google Maps provider.

**Comment by cristian9804** [comment]
I have the same problem with ios

**Comment by tolypash** [comment]
Hey guys I solved the problem by wrapping my button with <MapView.CalloutSubview> and having onPress event attached to that. Example:

```
<MapView.Callout>
<MapView.CalloutSubview style={{ marginLeft: 'auto', marginRight: 'auto' }} onPress={() => { this.props.navigation.navigate('Tables') }}>
                                    <Button
                                        shadowless
                                        color="orange"
                                        style={{ alignSelf: 'center' }}
                                    >
                                        View Tables
                                    </Button>
                                </MapView.CalloutSubview>
<MapView.Callout>
```

**Comment by kot-ezhva** [comment]
@tolypash It's iOS solution only

**Comment by kot-ezhva** [comment]
My very dirty solution:

1. Made custom callout with fixed dimensions and add onPress to Callout component.
```
<Marker>
// Your stuff

<Callout tooltip onPress={this.onCalloutPress}>
    <View style={style.callout}>
        <View style={style.action}>
            { getIcon('running', 20, 'rgb(70, 70, 70)') }
         </View>
         <View style={style.action}>
             { getIcon('comment-dots', 20, 'rgb(70, 70, 70)') }
          </View>
      </View>
</Callout>
</Marker>
```
```
callout: {
    width: 130,
    flexDirection: 'row',
    justifyContent: 'space-between',
},
action: {
    width: 40,
    height: 40,
},
```

2. See and detect point object into nativeEvent and handle taps!
```
onCalloutPress = e => {
    const { point } = e.nativeEvent;
    const { onPressRun, onPressMessage } = this.props;

    this.marker.hideCallout();

    if (point.x < 65) { // 65 it's center of Callout
        onPressRun();
    } else {
        onPressMessage();
    }
};
```
😸

**Comment by beakshy** [comment]
bump, has anyone had any luck resolving this?

**Comment by jnuno98** [comment]
nope, still having the problem both in IOS and android

I just want to have a button to open another page but it just doesn't work. And the developers don't fix it in 3 years

**Comment by el-lsan** [comment]
Can we maybe reopen this ?
It is still happening...

**Comment by kmkrtich** [comment]
I still have same issue

**Comment by Haseeba393** [comment]
> Hey guys I solved the problem by wrapping my button with <MapView.CalloutSubview> and having onPress event attached to that. Example:
> 
> ```
> <MapView.Callout>
>   <MapView.CalloutSubview style={{ marginLeft: 'auto', marginRight: 'auto' }} onPress={() => { this.props.navigation.navigate('Tables') }}>
>     <Button
>         shadowless
>         color="orange"
>         style={{ alignSelf: 'center' }}
>      >
>        View Tables
>      </Button>
>   </MapView.CalloutSubview>
> <MapView.Callout>
> ```

Thanks...Its Working for me.

**Comment by AlejandroFNadal** [comment]
This problem is still happening on 2022 :-(

**Comment by nikacer** [comment]
Recién me topo con un desarrollo y sigo viendo que se presenta el problema sobre Android no es posible manejar elementos internos en el callout, en mi version actual CalloutSubview al parece no existe

**Comment by muhammadqazi** [comment]
use CalloutSubview

<Callout style={styles.calloutWidth}>
     <CalloutSubview
           style={styles.phoneContainer}
          onPress={() => {
       console.log('onPress Clicked')
      }}>


    <Icon
         name="directions-car"
         type="material"
         color={APP_THEME.APP_ORANGE}
         size={30}
          underlayColor="clear"
     />


       </CalloutSubview>
</Callout>

**Comment by muhammadqazi** [comment]
Use CalloutSubview 

```
<Callout style={styles.calloutWidth}>
<CalloutSubview
style={styles.phoneContainer}
onPress={() => {
console.log('onPress Clicked')
}}>
<Icon
name="directions-car"
type="material"
color={APP_THEME.APP_ORANGE}
size={30}
underlayColor="clear"
/>
</CalloutSubview>
</Callout>

```

**Comment by djnewage** [comment]
problem still happening in 2024

**Comment by djnewage** [comment]
found an answer
https://stackoverflow.com/questions/57233394/react-native-maps-callout-press-not-triggering-on-ios
