### ISSUE TITLE
showsMyLocationButton doesn't looks good on Android

### ISSUE THREAD

**Issue by fariasmark** [react-native-maps/react-native-maps#2512]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

    react-native: 0.54.0
    react: ^16.3.0-alpha.1
    react-native-maps: 0.21.0

### Steps to Reproduce

Just follow the instructions in docs, install with CocoaPods and add this on the Mapview:

```
<MapView
        showsUserLocation
        provider='google'
        showsMyLocationButton
        initialRegion={{
          latitude: -34.40032,
          longitude: -72.560092,
          latitudeDelta: 0.00522,
          longitudeDelta: 0.00522 * ASPECT_RATIO,
        }}
      >
</MapView>
```

### Expected Behavior

The button 'showsMyLocationButton' should look like the button that appears on the Google Maps App

### Actual Behavior

The button 'showsMyLocationButton' that appears on Android isn't the same that iOS

**Comment by mohsinriaz17** [comment]
showsUserLocation work on android,
showsMyLocationButton works on IOS but never appears on android

 <View style={{...StyleSheet.absoluteFillObject,
    flex: 1,
    width: '100%',
    alignItems:'center'}}>
        <MapView
          style={{ ...StyleSheet.absoluteFillObject }}
          provider={MapView.PROVIDER_GOOGLE}
          showsMyLocationButton={true}
          showsUserLocation={true}
          initialRegion={this.state.initialRegion}
        >
        </MapView>
</View>

**Comment by abegehr** [comment]
Is there a way to add a custom showMyLocationButton?

**Comment by rborn** [comment]
@abegehr yes, just add a button on top of the map and on click navigate to the user's current position.

**Comment by abegehr** [comment]
@rborn thanks! I found this as well: #1874

**Comment by crobinson42** [comment]
I'm having the same issue with the `showMyLocationButton` Android button showing up - it appears to be related to layout/styles because I have gotten to appear when playing with different View container and MapView component `styles` -  the button will show up on Android in some styles that I add but not in all cases. This just a bug with Android.
