### ISSUE TITLE
MapView with the Animated API is lagging too much in android

### ISSUE THREAD

**Issue by bbeckk** [react-native-maps/react-native-maps#2534]
**Is this a bug report?**
May be

**Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?**
Yes

**Environment**
"react": "16.3.1",
"react-native": "0.55.4",
 "react-native-maps": "^0.21.0",
 Target Platform: Android devices (eg: Samsung J7 Prime)

**Steps to Reproduce**
1. take the example file named AnimatedViews and test in android devices
2. You can see the lagging issue here in the video: https://youtu.be/EhdbT51R9bo 

**Expected Behavior**
I just want the map to behave as shown in the react-native-map doc 
https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966

**Actual Behavior**
It is lagging too much in android. See the video [here](https://youtu.be/EhdbT51R9bo ).
The performance is very slow in android devices.

**Reproducible Demo**
take the example file named AnimatedViews and test in android devices
- I've tested it in signed apk as well.
- I've asked a question in stackoverflow as well with sample codes
https://stackoverflow.com/questions/52644974/react-native-map-mapview-with-the-animated-api-is-lagging-too-much-in-android

**Comment by pavilion** [comment]
Performance gets better with @owinter86's answer on SO, but Animation from left to right still broken

**Comment by owinter86** [comment]
Hey @pavilion I also found that adding the `tracksViewChanges` to the marker component allows you to use children without the performance issue, cpu usage will not spike and you wont need to transfer to an icon prop. Not sure if that helps with the animation issue.

**Comment by pavilion** [comment]
@owinter86 that certainly helps with the performance image! Will investigate about the animation issue.

**Comment by pavilion** [comment]
@bbeckk @owinter86 I fixed it, left a PR https://github.com/react-native-community/react-native-maps/pull/2978
