### ISSUE TITLE
Android fitToCoordinates issue

### ISSUE THREAD

**Issue by kenobi91** [react-native-maps/react-native-maps#2543]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
 react-native: 0.54.0
 react: 16.3.0-alpha.1
 react-native-maps: 0.21.0

Target Platform: iOS - 11.2 Simulator/iPhone 6, Android 6.0.1 - Nexus5 and Android 8.1 - Huawei P20
iOS maps - GoogleMaps

### Steps to Reproduce

Issue is with fitToCoordinates method on Android platform. For example if i want to fit some coordinates with edgePadding it works on iOS but not on Android. Let's say i want to fit coordinates but i want bottom padding to be half of screen. I can write something like this:

let { height } = Dimensions.get('window');

let edgePadding = {
    top:   0,
    bottom: (height / 2),
    right: 0,
    left: 0
 };

let options = {
  edgePadding,
  animated: true
};

this.map.fitToCoordinates(coordinates, options);

### Expected Behavior

Map animates to provided coordinates and adds padding that is equal to half of screen height.

### Actual Behavior

On iOS this works as expected, but on Android it doesn't. As if android expects for padding to match actual pixel size of screen rather than dp unitis used with react-native.

### Reproducible Demo

n/a

### Workaround

If edge padding on android is provided as actual pixel number it works as expected, for example Nexus 5 have resolution of 1920 * 1080. To get actual pixel count for react-native dp unit we can use PixelRatio.getPixelSizeForLayoutSize(). So i made helper function for that:

const generateEdgePadding = (edgePadding) => {

  if(Platform.OS === 'ios'){
    return edgePadding;
  }

  return {
    top:    PixelRatio.getPixelSizeForLayoutSize(edgePadding.top),
    right:  PixelRatio.getPixelSizeForLayoutSize(edgePadding.right),
    left:   PixelRatio.getPixelSizeForLayoutSize(edgePadding.left),
    bottom: PixelRatio.getPixelSizeForLayoutSize(edgePadding.bottom)
  };
};

I hope this helps :)

**Comment by ProteanDev** [comment]
The edge padding workaround doesn't solve the issue for. Is there any other workaround for this? I've been trying to wrap my head around now for days, please help.

**Comment by superyarik** [comment]
Also face this issue on google pixel phone(android 9). Trick with PixelRatio is not working. iOS and galaxy s7 fitToCoordinates correct, but pixel ignore paddings. liteMode is true

looks like now we need to process coordinates and add paddings there, but there is be dependency on zoom level and another things...

![image](https://user-images.githubusercontent.com/1265590/52236289-78b94c00-28d7-11e9-9c9f-64c399cfcd2d.png)

![image](https://user-images.githubusercontent.com/1265590/52236429-dfd70080-28d7-11e9-8fad-18b43591f1fc.png)

**Comment by andyesp** [comment]
I'm also having this issue on Android, iOS works ok. When fitToCoordinates is called, it doesn't modify the map zoom.

**Comment by diegorodriguesvieira** [comment]
Same here, someone has any workaround?

**Comment by jkaravakis** [comment]
@diegorodriguesvieira  and @andyesp I have the same issue where fitToCoordinates on Android does nothing when called. I discovered that changing my MapView's region prop to initialRegion solves that issue. Let me know if this is the case for you as well. I believe this is a separate issue from the edgePadding issue which @kenobi91 developed a workaround for.

Unfortunately switching to initialRegion creates a new problem for me as my current location button no longer works due to initialRegion not updating. Any suggestions on a workaround for this?
