### ISSUE TITLE
Android marker touch area size is much bigger than the marker size

### ISSUE THREAD

**Issue by teepeevee** [react-native-maps/react-native-maps#2552]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.54 (with example app) and 0.57.1 (with our own app)
    react: 16.3.2 (with example app) and 16.5.0 (with our own app)
	react-native-maps: 0.22.0
Target Platform: Android 23-28

### Steps to Reproduce

1.  Open AirMapsExplorer or your own app with Android emulator or phone
2. Select StaticMap
3. Click/Tap the sea above the red marker

### Expected Behavior

The marker should not be selected as you tapped outside the marker.

### Actual Behavior

Marker gets selected and shows a callout when I click the sea about same place where calllout shows "description" text (clicked area marked with red circle):
![screenshot](https://user-images.githubusercontent.com/42848481/47015493-cd349200-d155-11e8-8130-9a27241862cf.png)

Similarly if I click outside the marker on the left/right/bottom side of the marker, the same callout shows.

Same code in iOS emulator and phone doesn't select the marker when tapped outside the marker. Android should work same way as only clicking the marker should select it.

Similarly in our own react-native-maps app we can reproduce this with Android using our own custom markers, but not with iOS. Also the touch area seems to be bigger, if the customer marker size is bigger than the default marker.

### Reproducible Demo

Build and run example app in Android emulator or phone:
https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md

**Comment by JensKolb** [comment]
I agree, the clickable area is way too large. In the [google maps api for javascript](https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerShape) there's an option to specify the shape and size of the clickable marker area. I think the react-native-map should also expose this option or at least let us set the radius of it.

**Comment by reyalpsirc** [comment]
Any news about this?

**Comment by reyalpsirc** [comment]
This seems to be a problem on the Google SDK for Android as reported on https://issuetracker.google.com/issues/35823783

**Comment by fozzarelo** [comment]
I ended up here trying to make the marker are bigger. I agree that this should be configurable. Even within my app, I can see the case for different area sizes.

**Comment by jbrodriguez-bytelion** [comment]
We're having the same issue and it happens only on Android

**Comment by betoharres** [comment]
I'm also having this problem.
@reyalpsirc posted an issue from 2013, so I think this issue is nowhere near to be fixed.

**Comment by reyalpsirc** [comment]
@betoharres The thing is that since the issue is on Google's side, react-native-maps can't do anything about it and so, even if this is open, the actual issue that needs to be fixed is the one from 2013 on Google's side. It's very possible that if it ever gets fixed there, it will also be fixed here automatically (as long as the maps library is updated on that time)

**Comment by betoharres** [comment]
@reyalpsirc you're totally right, I don't know why I requested that; might be a bug in my head :)

**Comment by GoktuqCan** [comment]
Hi, I've created a library based on the solution I'm using on my current project. I hope you'd find it useful:
[https://github.com/GoktuqCan/react-native-maps-touchables](https://github.com/GoktuqCan/react-native-maps-touchables)
