### ISSUE TITLE
[iOS + AppleMaps] showsPointsOfInterest, showsMyLocationButton, onPoiClick, etc. not working

### ISSUE THREAD

**Issue by arnaudambro** [react-native-maps/react-native-maps#2619]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, + all the solutions proposed in github for the problems liaised with showsMyLocationButton or onPoiClick (#1812, #1315, #209, #1033, #2010).
All the solutions are proposing 

- either to re-render the map after a timeout, and doing that by changing a style parameter (sometimes `padding`, sometimes `margin`, sometimes `flex` or `width`), which works with `provider='google'` but doesn't with AppleMaps for me

- either to create our own button, which could be a solution for the `showMyLocationButton` issue, but not for the POIs issue.

### Environment

    react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
    expo: 31.0.2
    react: 16.5.0
    react-native-maps: 0.22.1
    target: iOS + AppleMaps

### Steps to Reproduce / Expected Behavior / Actual Behavior

Any value (`true` or `false`) given to `showsPointsOfInterest` is always showing POI.
Any value (`true` or `false`) given to `showsMyLocationButton ` is never showing the location button.
Any value (`true` or `false`) given to `showsCompass ` is never showing the compass.
The method `onPoiClick` is never triggered.

### Reproducible Demo

```
const mapContainerStyles = StyleSheet.flatten({
  flex: 1,
  position: 'absolute',
  width: '100%',
  height: '100%',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  resizeMode: 'cover',
});
```
```
<View style={mapContainerStyles} >
  <MapView
    style={{ flex: 1 }}
    ref={map => this.map = map}
    initialRegion={{
      latitude,
      longitude,
      latitudeDelta,
      longitudeDelta
    }}
    showsUserLocation={true}
    showsPointsOfInterest={true}
    showsMyLocationButton={true}
    showsCompass={true}
    onPoiClick={(e) => console.log(e)}
  />
</View>
```

**Comment by danielzzz** [comment]
the same on android ^0.22.1

**Comment by radeno** [comment]
@arnaudambro on iOS maps (MapKit) "show my location button" was never implemented, only google maps on ios. So documentation is incorrect. https://github.com/react-native-community/react-native-maps/issues/1263#issuecomment-300966800

Implementation should be trivial. Based on this stackoverflow example https://stackoverflow.com/a/38009270/802949 but who knows.
