### ISSUE TITLE
Custom Markers disappear in Snapshots

### ISSUE THREAD

**Issue by softmastx** [react-native-maps/react-native-maps#2621]
PLEASE DON'T DELETE THIS TEMPLATE UNTIL YOU HAVE READ THE FIRST SECTION.

  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  PLEASE NOTE THAT ISSUES WITHOUT THE TEMPLATE IN PLACE WILL BE CLOSED RIGHT FROM THE START.

  Thanks for helping us help you!
-->

### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

    "react": "16.4.1",
    "react-native": "0.55.0",
    "react-native-maps": "^0.22.1"

 

     iOS - 11.4 Simulator/iPhone 8 Plus Using Apple Map.

 ### Steps to Reproduce

(Write your steps here:)

```
1.  {this.state.markers.map((marker,key) => (
          <Marker
            key={key}
            coordinate={marker.latlng}
            title={marker.title }
            description={marker.description}
            onCalloutPress={()=> this.onMarkerCalloutPress(key)}> 
           {marker.type == "label" ? 
          <View style ={{flex:1,backgroundColor:"rgba(0,0,0,1.0)",borderRadius:0,padding:2,justifyContent: 'center',
    alignItems: 'center'}}>
          <Text style={{flex:1,backgroundColor:"rgba(0,0,0,1.0)",color:"white",fontSize:12,justifyContent: 'center',
    alignItems: 'center'}}> {marker.title}</Text>
          </View>
   : null } </Marker>

2 const snapshot = this.map.takeSnapshot({
         
          format: 'png',   // image formats: 'png', 'jpg' (default: 'png')
          quality: 1.0,    // image quality: 0..1 (only relevant for jpg, default: 1)
          result: 'file'   // result types: 'file', 'base64' (default: 'file')
        });
        snapshot.then((uri) => {
          
          console.log(uri);
        });
```
### Expected Behavior

get an image with all markers.

(Write what you thought would happen.)

### Actual Behavior

only default marker on the image!

Screenshot

On simulator
<a href="https://ibb.co/3r1r89H"><img src="https://i.ibb.co/NVxVkdz/Screen-Shot-2561-12-10-at-15-40-19.png" alt="Screen-Shot-2561-12-10-at-15-40-19" border="0"></a>

Generated image
<a href="https://ibb.co/RHcmgcV"><img src="https://i.ibb.co/WKfwHfY/snapshot-1544431191-79071998596191406250.jpg" alt="snapshot-1544431191-79071998596191406250" border="0"></a>

**Comment by brightsider** [comment]
Any solution?

**Comment by SasankhM** [comment]
Also facing this issue please fix, no custom markers and user location marker are being shown

**Comment by SasankhM** [comment]
Especially user location marker - seems to be something people missed out on
