### ISSUE TITLE
Cannot take snapshot - Undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.takeSnapshot')

### ISSUE THREAD

**Issue by mayteio** [react-native-maps/react-native-maps#2623]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
   
    Android device OR Virtual Device in Android Studio. 
    - Pixel 2, Samsung Galaxy S9
    react-native: 31.0.0
    react: 16.5.0
    react-native-maps: 0.22.1

### Steps to Reproduce

1. Install as per instructions
2. Try to take a snapshot per [instructions](https://github.com/react-native-community/react-native-maps#take-snapshot-of-map)

```
takeSnapshot = () => {
    this.map
      .takeSnapshot({
        width: 1000,
        height: 1000
      })
      .then(res => console.log(res));
  };
```

### Expected Behavior

The function should return a blob or base64 file of map snapshot

### Actual Behavior

Error is displayed `Undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.takeSnapshot')`

![screenshot 2018-12-11 11 34 04](https://user-images.githubusercontent.com/43975092/49770487-b024d580-fd38-11e8-9bf5-bef4ea930df7.png)

### Reproducible Demo

Simple reproducible demo code available here: https://snack.expo.io/@mayteio/airmapmodule-issue
Unfortunately, snack doesn't have react-native-maps as a possible dependancy. 

I have also pushed to a repository here: https://github.com/mayteio/react-native-airmapmodule-issue

**Comment by mayconmesquita** [comment]
same problem here... any solutions?

**Comment by mayteio** [comment]
I ended up using Google's Static Maps to reproduce my map as an image. Not ideal (and this bug should be fixed) but it means I can cache the result and not hit google APIs often.

**Comment by mayconmesquita** [comment]
@mayteio Thanks for the suggestion. I will try Google's Static Maps while Snapshot is broken.

**Comment by mayconmesquita** [comment]
And yes, this bug need to be fixed ASAP.

**Comment by jbrodriguez** [comment]
This is still an issue as of today

**Comment by jbrodriguez** [comment]
I do have to add that another workaround is to use https://github.com/gre/react-native-view-shot, it does the job.

**Comment by charan0017** [comment]
> I do have to add that another workaround is to use https://github.com/gre/react-native-view-shot, it does the job.

Thanks man, it helped me too to solve the snapshot issue in react-native-maps
