### ISSUE TITLE
iOS: Invariant Violation: requireNativeComponent: "AirMap" was not found in the UIManager

### ISSUE THREAD

**Issue by janhesters** [react-native-maps/react-native-maps#2625]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: "0.57.5"
react: 16.6.1
react-native-maps: "git+https://git@github.com/react-native-community/react-native-maps.git"

### Steps to Reproduce

The bug appears on iOS:

1. Create a new RN project: `react-native init rnmapsbug`
2. Install react-native-maps directly from git: `npm install --save git+https://git@github.com/react-native-community/react-native-maps.git`
3. Link it: `react-native link react-native-maps`
4. Import it and use it:

```js
// in App.js
import MapView from "react-native-maps";

// in your component class
<MapView
  style={{ ...StyleSheet.absoluteFillObject }}
  initialRegion={{
    latitude: 37.78825,
    latitudeDelta: 0.0922,
    longitude: -122.4324,
    longitudeDelta: 0.0421
  }}
/>
```

5. Run your app. The error will pop up: `Invariant Violation: requireNativeComponent: "AirMap" was not found in the UIManager`

Follow my guide above. I followed the installation instructions for manual installations on iOS (because I mustn't use CocoaPods in my project) and combined them with the fixes in [this issue](https://github.com/react-native-community/react-native-maps/issues/2495), because I also had the same bug, when I just ran `npm install --save react-native-maps`.

### Expected Behavior

Maps should show on iOS.

### Actual Behavior

The app crashes (see below).

![simulator screen shot - iphone xs - 2018-12-13 at 13 04 57](https://user-images.githubusercontent.com/31096420/49937650-bb623780-fed7-11e8-85d1-09169d8113ab.png)

### Reproducible Demo

See steps to reproduce. You will end up with a demo in 3 minutes.

**Comment by cerberusv2px** [comment]
Yes i got the same error.

**Comment by salmazov** [comment]
Yes! I have the same problem

**Comment by LiTze06** [comment]
Any solution yet?

**Comment by mmatheusmmiguel** [comment]
Hello guys,
I solved this problem following this steps:
<img width="913" alt="30664105-33feb650-9e12-11e7-9d7d-962e767b48cd" src="https://user-images.githubusercontent.com/28689692/50385169-5fee3180-06af-11e9-8b76-4d8fffa4d8c7.png">

**Comment by ranjanpoudel1234** [comment]
@mmatheusmmiguel you saved my day. Excellent answer, thank you. After juggling for a whole day with pod files, running into ton of issues with use_frameworks! etc, at the end, your solution worked the best. :)

**Comment by conor909** [comment]
@mmatheusmmiguel thank you for the clear and simple steps! Finally!

**Comment by DevQuayle** [comment]
I have the same problem, but above solution does'n work for me. Maybe someone have other solution this problem. 

This my configuration:
`"react-native-maps": "0.25.0"`

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 342.55 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1```

**Comment by cyprienotto** [comment]
@janhesters All is in the
[linking natives librairies in the react native docs ](https://facebook.github.io/react-native/docs/linking-libraries-ios#content)

**Comment by coranmelia** [comment]
for iOS, what worked for me was I did `cd ios` and then `pod install`, it showed new dependency react-native-maps is installed and my map showed up.

**Comment by luisgurmendez** [comment]
@coranmelia Thanks for your comment :D! it fixed by issues I can see the map now , but it outputs this error when starting the app on ios
```
$ react-native run-ios
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-maps (to unlink run: "react-native unlink react-native-maps")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```
