### ISSUE TITLE
Android: Invariant Violation: requireNativeComponent "AIRMap" was not found in the UIManager

### ISSUE THREAD

**Issue by ksweetie** [react-native-maps/react-native-maps#2637]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.57.7
    react: 16.6.1
    "react-native-maps": "https://github.com/react-native-community/react-native-maps.git"

### Steps to Reproduce

I'm not getting this error when I run the project with `react-native run-android`. However, I'm trying to add a React Native app to an Android app in Android Studio as a library, and I'm getting the error in that project.

### Expected Behavior

There shouldn't be an error.

### Actual Behavior

![Image of Error](https://i.imgur.com/KoqtZrE.png)

### Reproducible Demo

I followed [this tutorial](https://medium.com/codeexplorers/connecting-the-dots-between-react-native-and-unity-3d-using-gradle-67f93b92c254), which worked, but when I add react-native-maps, I get this error.

There have been several issues about this error. I've read every comment and tried every possible solution without success. There's also a relatively new issue for iOS. I assume they're related, but I figured I would open an issue for Android.

**Comment by dyxizm** [comment]
Have the same error, IOS works fine also
"react-native": "0.57.4",
"react-native-maps": "^0.22.1",

**Comment by dyxizm** [comment]
> Have the same error, IOS works fine also
> "react-native": "0.57.4",
> "react-native-maps": "^0.22.1",

Installed google services solved the problem

**Comment by bouchja1** [comment]
> > Have the same error, IOS works fine also
> > "react-native": "0.57.4",
> > "react-native-maps": "^0.22.1",
> 
> Installed google services solved the problem

Which google services? Please, could you describe it more detaily?

**Comment by dyxizm** [comment]
> > > Have the same error, IOS works fine also
> > > "react-native": "0.57.4",
> > > "react-native-maps": "^0.22.1",
> > 
> > 
> > Installed google services solved the problem
> 
> Which google services? Please, could you describe it more detaily?

I Installed google services in android studio
![2019-01-15 18 39 27](https://user-images.githubusercontent.com/7794354/51191775-2f886480-18f6-11e9-8ddf-4b7e4d3c5cc4.png)

**Comment by kardoqadir** [comment]
I have the same problem and @dyxizm  answer is not working, It is ok in IOS.

Please anyone knows the solution?

**Comment by bouchja1** [comment]
> I have the same problem and @dyxizm answer is not working, It is ok in IOS.
> 
> Please anyone knows the solution?

The solution above (by @dyxizm) did not help me either. I have solved this by not using an Android simulator and I bought an Android testing device.

**Comment by umerbaig** [comment]
I've the same problem and @dyxizm answer is not working

**Comment by RafaelFronteira** [comment]
Hey guys
I followed this [tutorial ](https://dev.to/droidmakk/react-native-maps-done-right-for-android-d3o) and it worked for me 😀

Can you guys test too? 😉

**Comment by ndungujan23** [comment]
Thanks a lot @RafaelFronteira.. I've been stuck the whole day on android. It worked for me 😉

**Comment by Nagibaba** [comment]
From Android Studio
`Tools -> SDK Manager -> Android SDK -> SDK tools TAB -> check Google Play Services`
You are good to go!

**Comment by KesavSundarM** [comment]
Please check your MainApplication.java file whether the following lines are available.

`import com.airbnb.android.react.maps.MapsPackage;`

The following inside **_getPackages()_**

`new MapsPackage()`

**Comment by zeroidentidad** [comment]
see https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md

**Comment by pclevy** [comment]
> 
> 
> Please check your MainApplication.java file whether the following lines are available.
> 
> `import com.airbnb.android.react.maps.MapsPackage;`
> 
> The following inside **_getPackages()_**
> 
> `new MapsPackage()`

package com.navigation;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

What to do?
