### ISSUE TITLE
`initialRegion` doesn't work when `onMapReady` and `onLayout` are defined

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-maps/react-native-maps#2657]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
* Last Expo Snack version (it's using react-native-maps@0.22.1)
* Bug only present in iOS

### Steps to Reproduce
* Open https://snack.expo.io/HyJsmRPGN
* Check that I'm setting an initialRegion with latitudeDelta: 1 (very much zoom in). You gonna see that the map has a wrong zoom
* Comment line 23 (`onMapReady={() => {}}`) or 24 (`onLayout={() => {}}`). You gonna see that the map is gonna have the proper zoom

After commenting any of those functions, you gonna see that the zoom is gonna be properly set.
It's only happening on iOS

### Expected Behavior
* Zoom (latitudeDelta) should be correct

### Actual Behavior
* Zoom (latitudeDelta) is wrong

<img width="1139" alt="screen shot 2019-01-12 at 17 59 57" src="https://user-images.githubusercontent.com/1837969/51078473-1f714a80-1694-11e9-9ab0-6a83a022945a.png">
<img width="1185" alt="screen shot 2019-01-12 at 18 00 08" src="https://user-images.githubusercontent.com/1837969/51078474-2009e100-1694-11e9-9745-2ec7285deaad.png">
<img width="1162" alt="screen shot 2019-01-12 at 18 00 17" src="https://user-images.githubusercontent.com/1837969/51078475-2009e100-1694-11e9-8ae2-21f8fc7c2627.png">
<img width="1180" alt="screen shot 2019-01-12 at 18 00 26" src="https://user-images.githubusercontent.com/1837969/51078476-2009e100-1694-11e9-8908-7216fc169d3e.png">

### Reproducible Demo
https://snack.expo.io/HyJsmRPGN

**Comment by circuit-monkey** [comment]
I'm having same problem as well

**Comment by danrivett** [comment]
Ran into this issue today too 😞

**Comment by kimobrian** [comment]
Experiencing this similar issue. The map is totally zoomed out. When I comment out `onLayout`, it zooms in ok. The `onLayout` event is not documented anywhere though from the `MapView` reference.

**Comment by selven** [comment]
Just wanted to mention that this is still an issue

**Comment by iamir4g** [comment]
i have same isuue :(
