### ISSUE TITLE
Custom Markers cause extreme lag and slow down on android

### ISSUE THREAD

**Issue by alexcittadini** [react-native-maps/react-native-maps#2658]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
"expo": "^32.0.0",
"react": "16.5.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

Expo SDK32 utilises
"react-native-maps": 0.22.1
"react-native-svg": 8.0.10

### Steps to Reproduce
This has only been an issue since updating Expo SDK from 30 to SDK 32. In that time expo updated rn maps from 0.21.0 to 0.22.1.  My main page is a full screen mapview with about 10-100 custom markers. If the map initialises with more than 10 markers the entire app runs extremely slow on android (only appears to effect android).

### Behavior
In previous versions my app functioned well on android and iOS. After updating expo and rn maps even navigating away from the map will cause delays of 5-10 seconds to register a click. Spinner animations become clunky and the map becomes almost unusable as complex gestures aren't registered. Below is an example of a circle marker (I use more complex markers but even this will result in the same slow down). To compare, changing the SVG image to a png in the image prop fixes the lag problem but would be unusable in all but the most basic use cases. 

### Reproducible Demo
The following marker causes extreme lag on android. In fact any child in the Marker component cases lag.
```
<MapView.Marker
          coordinate={{latitude: marker.latLng.lat, longitude: marker.latLng.lng}}
          key={marker.id + moment().unix()}
          anchor={{x: 0.5, y: 0.5}}
           onPress={()=> this.props.showModal({marker}, 'markerModal')}
          >
            <Svg height={20} width={20}>
              <Svg.Circle
                cx="10"
                cy="10"
                r={2}
                fill={this.markerType(marker)}
              />
            </Svg>
          </MapView.Marker>
```

The following in an example of what works without lag but in some use cases I need to show custom text and direction arrows so this isn't enough 
```
        <MapView.Marker
          coordinate={{latitude: marker.latLng.lat, longitude: marker.latLng.lng}}
          key={marker.id + moment().unix()}
          anchor={{x: 0.5, y: 0.5}}
          onPress={()=> this.props.showModal({marker}, 'markerModal')}
          image={require('../../assets/icons/circle.png')}
          />
```

**Comment by efkan** [comment]
I've encountered the same issue.

The same application use less CPU with React-Native-Maps v0.21.0 than v0.22.1. 

Also 26 custom markers are shown faster on v0.21.0.

The following image shows CPU usage when the app with `react-native-maps` `v0.22.1` running on emulator:
![new rn map-cpu usage](https://user-images.githubusercontent.com/6974198/51118710-1615e880-1822-11e9-826d-20c2e757ca67.png)

The following image shows CPU usage when the app with `react-native-maps` `v0.22.1` running on emulator:
![old version of rn maps with modified drawee-cpu usage](https://user-images.githubusercontent.com/6974198/51118892-7b69d980-1822-11e9-9cad-82d9f646f608.png)

My laptops cpu-fan never stops when running` v0.22.1` and **this may cause faster phone battery draining**.

This is a big issue.

**Comment by HerbertLim** [comment]
This happens to me, too. Very serious.

**Comment by skidr0w** [comment]
I am too encountering this behaviour since Upgrading from Expo SDK 30 to 32. It seems like setting prop `tracksViewChanges={false}` on the `MapView.Marker` component fixes the performance issues.

**Comment by HerbertLim** [comment]
> I am too encountering this behaviour since Upgrading from Expo SDK 30 to 32. It seems like setting prop `tracksViewChanges={false}` on the `MapView.Marker` component fixes the performance issues.

I tried that. However, markers are located in at wrong places. That is, if there are 100 markers on the map, and if I move map to the left, all the markers have to move correspondingly. However, if `tracksViewChange` is false, markers does not move as map moves.

iOS works well without specifying `tracksViewChange`.

**Comment by HerbertLim** [comment]
I resolved this issue by turning on and off `tracksViewChanges` as @skidr0w said. #1031 was helpful to me. 

Now my customMarker class looks like this:
```
state = {
  tracksViewChanges: false,
}

componentDidUpdate(prevProps) {
    if (prevProps.coordinate !== this.props.coordinate // set true only when props changed
        || prevProps.value !== this.props.value 
        || prevProps.level !== this.props.level) {
        this.setState({tracksViewChanges: true})
    } else if (this.state.tracksViewChanges) {
       // set to false immediately after rendering with tracksViewChanges is true
        this.setState({tracksViewChanges: false})
    }
}

render() {
  return (
    <MapView.Marker
        coordinate={coordinate}
        style={{ zIndex: isFocused ? FOCUSED_MARKER_ZINDEX : zIndex }}
        onPress={onPressMarker}
        tracksViewChanges={this.state.tracksViewChanges}
    >
      ...
   </MapView.Marker>
}
```
Now google map at android response very very fast. 
I am using Svg to draw marker at Android and View to draw one at iOS.

**Comment by alexcittadini** [comment]
That worked for me HerbertLim. It feels a little jittery at times but makes the map usable at least. Hope they fix this because I'm starting to loose track of all the big patch code have too many patches in my code from previous bugs

**Comment by alexcittadini** [comment]
I don't know how I closed this but I think the issue still remains. This is just a patch that can be used until the underlying code is fixed

**Comment by Deprofets** [comment]
Use Marker.Animated instead

**Comment by mattyleggy** [comment]
> 
> 
> Use Marker.Animated instead

`Marker.Animated` doesn't appear to fix the issue

**Comment by Deprofets** [comment]
> > Use Marker.Animated instead
> 
> `Marker.Animated` doesn't appear to fix the issue

Apologies for the vague response, what worked for me was building a pure component using `Marker.Animated` and setting `tracksViewChanges` to false, I was then able to drag the map around with 12 markers without extreme lag. Another thing that improved performance a bit was using `MapView.Animated` instead of `MapView` and placing the markers once the map was ready.

**Comment by CesarDenis** [comment]
@Deprofets, can you make an example of your component? 

Tks

**Comment by davorbuha** [comment]
any news?

**Comment by duytq94** [comment]
I have the same problem, if you use custom markers, the map will very lag.
Set ``tracksViewChanges={false}`` will resolve the lag, but will cause the markers not working properly.
This is really a big problem, please help.
Thanks!

**Comment by wodka** [comment]
I do not remember where I copied it from - but this is working quite well for us:

```javascript
import React, {PureComponent} from "react"
import {MapView} from "expo"
import isEqual from "lodash.isequal"
import PropTypes from "prop-types"


export default class MapMarker extends PureComponent {
    state = {
        tracksViewChanges: true,
    }
    componentWillReceiveProps(nextProps) {
        if (!isEqual(this.props, nextProps)) {
            this.setState(() => ({
                tracksViewChanges: true,
            }))
        }
    }
    componentDidUpdate() {
        if (this.state.tracksViewChanges) {
            this.setState(() => ({
                tracksViewChanges: false,
            }))
        }
    }

    render() {
        return (
            <MapView.Marker
                tracksViewChanges={this.state.tracksViewChanges}
                {...this.props}
            >{this.props.children}</MapView.Marker>
        )
    }
}

MapMarker.defaultProps = {
    children: null,
};

MapMarker.propTypes = {
    children: PropTypes.any,
};
```

Then just use this MapMarker within your maps

**Comment by duytq94** [comment]
Thanks very much, @wodka 
This solution doesn't resolve the lag completely but makes the map much better.
Hope someone can fix this issue completely.

**Comment by luisfuertes** [comment]
@skidr0w and @wodka save me. It works

**Comment by psuslick** [comment]
> Then just use this MapMarker within your maps

Can you provide further explanation with how this was used within an example?

**Comment by RageOfJustice** [comment]
Hello! I use maps for tracking user positions with custom markers.
I have been inspired by @wodka 's and @HerbertLim solutions and decided to check some theory:
this is my Marker before changes:
![image](https://user-images.githubusercontent.com/18666217/58839171-902bfa00-8669-11e9-8d18-42dbfe29006e.png)
and result is:
![image](https://user-images.githubusercontent.com/18666217/58839217-b2257c80-8669-11e9-9e05-b59745e0afaa.png)
then ive tried to add _tracksViewChanges={false}_ prop and result:
![image](https://user-images.githubusercontent.com/18666217/58839288-f1ec6400-8669-11e9-885e-e4e947c76b01.png)
Seems like my component <MapMarker/> didnt rendered (Wrapped Image with styled-components). But why <UserImage/> did appear? The difference is the prop _imageUrl_ which to re-renders it component.
So I decided to add this prop for <MapMarker/> just for test:
![image](https://user-images.githubusercontent.com/18666217/58839066-36c3cb00-8669-11e9-84e9-a217c97f283c.png)
And it works! Even when coordinates changes - its working as before any changes.
But as for me, this a workaround and it stinks.

**Comment by brownieboy** [comment]
Adding the custom MapMarker class didn't make any noticeable Android performance improvements for me, sadly.  Plus I had issues with marker icons not appearing correctly.

**Comment by Balasnest** [comment]
Custom Marker is lagging very slow and its looks like CPU usage is growing steadily (i can feel the heat in phone). I tried with `tracksViewChanges={false}` once did update is done. But still can see lag, Zoom in/out are pretty hang and dead slow after using for a while.

**Comment by RWOverdijk** [comment]
@Balasnest This is a persistent issue. I'm curious if there's a way to provide native markers, those work well in my other app. I think large sums of markers simply won't work well with react-native-maps.

**Comment by oshtman** [comment]
Experiencing the same issue. We have around 100-200 custom markers at a given time (rendered with custom jsx), but the issue starts to be apparent already at around 10-20 markers

**Comment by Balasnest** [comment]
@RWOverdijk `key={marker.id + moment().unix()}` This creates new marker everytime instead of re-render. I think we should use `key={marker.id}` this as a key.

**Comment by RWOverdijk** [comment]
@balasnest You can use the `icon` prop. I have no idea what youre trying with the key there but I know its wrong.

**Comment by GH974** [comment]
Hi, i have similar issue, and i juste add five marker on maps, and the cpu goes up to 200%

**Comment by RWOverdijk** [comment]
@GH974 This needs a thorough fix and will take time to figure out. I have attempted to fix it but found it hard to figure out a good way to handle this. The approach I think should be taken is the one mapbox takes, too. Markers are to be handled natively instead of repositioning over the bridge.

Like I mentioned before, use the `icon` prop on your marker. This will do just that, but it's not a custom view and expects an image. The cpu will not spike though, and that's more important than having fancy custom views for markers 😄

Either that or use `tracksViewChanges={false}` and be smart about when you enable it (initially, or when markers have changed).

**Comment by HerbertLim** [comment]
In my case, as far as I maintain number of markers within 300, usually lower than 200, there is no performance issue both in Android and iOS. It is likely that rendering performance of Android 8 is poorest.

I use Expo and there were no problem until latest version of SDK v35, where react-native-maps version ranged from 0.22.1 to 0.25.

Let me show you my component rendering a marker. When region is changed, my app gets new marker via API and renders again. While getting response from API, `isLoading` props become `true`. I used `getDerivedStateFromProps()` method to decrease number of rendering each time region is changed. Hope this helps.

```
export default class MarkerWithView extends Component {
  state = {
    tracksViewChanges: false,
  }

  static getDerivedStateFromProps(props, state) {
    if (props.isLoading) {
      return {
        tracksViewChanges: true
      }
    } else {
      return null;
    }
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (nextProps.isLoading) {
      return false;
    } else {
      return true;
    }
  }

  componentDidUpdate(prevProps) {
    if (!this.props.isLoading && this.state.tracksViewChanges) {
      if (isIos) {
        setTimeout(() => {
          this.setState({tracksViewChanges: false})
        }, 300)
      } else {
        this.setState({tracksViewChanges: false})
      }
    }
  }

  render() {
    ...
    return (
      <MapView.Marker
        tracksViewChanges={this.state.tracksViewChanges}
      >
        <View style={[styles.markerContainer]}>
        ...
        </View>
      </MapView.Marker>
    )
  }
}
```

**Comment by GH974** [comment]
@RWOverdijk thanks it works if i add in icon props.

**Comment by bashirpour** [comment]
https://stackoverflow.com/questions/59716959/react-native-maps-custom-markers-cause-extreme-lag-and-slow-down-on-android/59716960

**Comment by xseignard** [comment]
> @Balasnest You can use the `icon` prop. I have no idea what youre trying with the key there but I know its wrong.

I have some custom markers defined as below:
```jsx
import React, { useEffect, useRef, memo, useCallback } from 'react'
import { Animated } from 'react-native'
import { Marker } from 'react-native-maps'
import { Icon } from 'native-base'

const AnimatedIcon = Animated.createAnimatedComponent(Icon)
const scaleDuration = 200

export default memo(({ style, selected, ...markerProps }) => {
  const scale = useRef(new Animated.Value(1)).current

  const scaleTo = useCallback(
    value => {
      Animated.timing(scale, {
        toValue: value,
        duration: scaleDuration,
        useNativeDriver: true,
      }).start()
    },
    [scale]
  )

  useEffect(() => {
    scaleTo(selected ? 1.2 : 1)
  }, [scaleTo, selected])

  const transformStyle = { transform: [{ scale }] }

  return (
    <Marker.Animated
      {...markerProps}
      // don't track changes to increase perfs
      tracksViewChandges={false}
      tracksInfoWindowChanges={false}
    >
      <AnimatedIcon
        type="MaterialCommunityIcons"
        name="map-marker-circle"
        fontSize={30}
        style={[style, transformStyle]}
      />
    </Marker.Animated>
  )
})
```

And using `index` as the marker `key` seems improve perfs on android. It may be just a feeling, bit it seems too be the case.

Any idea why ? You seem to say it won't improve perfs ?

**Comment by shanelarson** [comment]
> I resolved this issue by turning on and off `tracksViewChanges` as @skidr0w said. #1031 was helpful to me.
> 
> Now my customMarker class looks like this:
> 
> ```
> state = {
>   tracksViewChanges: false,
> }
> 
> componentDidUpdate(prevProps) {
>     if (prevProps.coordinate !== this.props.coordinate // set true only when props changed
>         || prevProps.value !== this.props.value 
>         || prevProps.level !== this.props.level) {
>         this.setState({tracksViewChanges: true})
>     } else if (this.state.tracksViewChanges) {
>        // set to false immediately after rendering with tracksViewChanges is true
>         this.setState({tracksViewChanges: false})
>     }
> }
> 
> render() {
>   return (
>     <MapView.Marker
>         coordinate={coordinate}
>         style={{ zIndex: isFocused ? FOCUSED_MARKER_ZINDEX : zIndex }}
>         onPress={onPressMarker}
>         tracksViewChanges={this.state.tracksViewChanges}
>     >
>       ...
>    </MapView.Marker>
> }
> ```
> 
> Now google map at android response very very fast.
> I am using Svg to draw marker at Android and View to draw one at iOS.

@HerbertLim Is this still relevant with the latest version?

> I resolved this issue by turning on and off `tracksViewChanges` as @skidr0w said. #1031 was helpful to me.
> 
> Now my customMarker class looks like this:
> 
> ```
> state = {
>   tracksViewChanges: false,
> }
> 
> componentDidUpdate(prevProps) {
>     if (prevProps.coordinate !== this.props.coordinate // set true only when props changed
>         || prevProps.value !== this.props.value 
>         || prevProps.level !== this.props.level) {
>         this.setState({tracksViewChanges: true})
>     } else if (this.state.tracksViewChanges) {
>        // set to false immediately after rendering with tracksViewChanges is true
>         this.setState({tracksViewChanges: false})
>     }
> }
> 
> render() {
>   return (
>     <MapView.Marker
>         coordinate={coordinate}
>         style={{ zIndex: isFocused ? FOCUSED_MARKER_ZINDEX : zIndex }}
>         onPress={onPressMarker}
>         tracksViewChanges={this.state.tracksViewChanges}
>     >
>       ...
>    </MapView.Marker>
> }
> ```
> 
> Now google map at android response very very fast.
> I am using Svg to draw marker at Android and View to draw one at iOS.

@HerbertLim Is this still relevant with the latest version?

**Comment by HerbertLim** [comment]
@shanelarson , I have not tested recently but I thought this issue still remains especially in Android 8. Thank you for your testing. At which Android did you test?

**Comment by shanelarson** [comment]
@HerbertLim Thank you for the quick response. I tested on Android 9.

**Comment by davx1992** [comment]
Hello All,
want to share my experience on same problem. I also had problem, that there is lot of markers on the map, IOS map becomes very laggy and slow. When I set      tracksViewChanges={false} it doesn't help. Only when I set marker image under image prop on marker it was working smooth.

I created PureComponent, and this is how my marker looked like when it was laggy: 
```js 
 <Marker
          coordinate={coordinate}
          identifier={marker.id}
          tracksViewChanges={false}
          anchor={{ x: 0.5, y: 1 }}
          icon={markerIcon}
          >
                {Platform.OS === "ios" && (
                    <View
                        key={marker.id}
                        style={styles.markerWrapper}
                    >
                        <MarkerSVGIcon />
                    </View>
                )}
</Marker>
```
Icon prop was for Android, as for some reason it was not working for IOS,  and View was for IOS.
With such setup it was not working well, and I have tried different approaches mentioned in this issue, however nothing helped.
Then I tried to add one view prop for IOS:     shouldRasterizeIOS={true}
As per Docs this prop is requesting to convert view to Bitmap before rendering.
After this, my map started working very well, without lags. So final Marker code which is working without lags is:

```js
<Marker
                coordinate={coordinate}
                identifier={marker.id}
                tracksViewChanges={false}
                anchor={{ x: 0.5, y: 1 }}
                icon={markerIcon}
            >
                {Platform.OS === "ios" && (
                    <View
                        key={marker.id}
                        shouldRasterizeIOS={true}
                        style={styles.markerWrapper}
                    >
                        <MarkerSVGIcon />
                    </View>
                )}
            </Marker>
```

This will be useful for people who need to put extra info in their marker body. Hope it will help anyone.

**Comment by lucianoacsilva** [comment]
Hello,

I have a similar issue here:

# Bug report



## Summary


I implement lots of markers with images from a server inside them. However, when the user moves the map, it lags a lot both the map and the aplication.
## Environment info



React Native with Expo 37.0.0

`react-native info` output:

```bash
# paste it here
```

Library version: 'https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz'

## Steps to reproduce



1. Open the map;
2. 

Describe what you expected to happen:

The map and the app should flow considerably fast.

## Reproducible sample code




1. Create custom marker:

`
function VisibleMarkers({ visibleAlerts, setAlert }) {
    return visibleAlerts.map((alert: AlertData, index: number) =>
        <AlertMarker
            key={index}
            alertInfo={alert}
            onClick={setAlert}
        />);
}
`
2. Insert it inside a **MapView** component:

`
<View style={styles.container}>
            <MapView
                style={styles.mapStyle}
                initialRegion={currentRegion}
                onRegionChange={setCurrentRegion}
                showsUserLocation
                followsUserLocation
                showsMyLocationButton
                showsCompass
            >
                <VisibleMarkers
                    visibleAlerts={visibleAlerts}
                    setAlert={(alert) => {
                        
                        navigation.navigate('AlertOpenedScreen', {
                            alert: alert,
                            timeline: true,
                        })
                    }}
                />
            </MapView>
            <MapLegend alertTypes={possibleAlertTypes} />
        </View>
`

**Comment by Ajmal0197** [comment]
Working solution for iOS and Android:
https://dev.to/ajmal_hasan/react-native-map-optimisation-59na

**Comment by foloinfo** [comment]
I strongly agree with setting `tracksViewChanges={false}` after the markers have been rendered.

This may be a bit off topic, but I would also suggest setting `showsIndoors={false}` on MapView as **it makes the map very slow** if you zoom in enough. Some low-end devices will even crash.

**Comment by kkx64** [comment]
Is there any solution for needing constantly animating markers, like a car tracking app?
