### ISSUE TITLE
edgePadding does not change when fitToCoordinates called

### ISSUE THREAD

**Issue by jfluence** [react-native-maps/react-native-maps#2660]
**Is this a bug report?**
Yes

**Have you read the Installation Instructions?**
Yes

**Environment**
react-native 0.55.4
react 16.3.1
react-native-maps: 0.22.1

Target Platform: iOS - 11.4 Simulator/iPhone X, 11.4.1  Device/Iphone 6  ,  Nexus6- Android 7.1.1  GoogleMaps for all devices

**Steps to Reproduce**
Simply call the fitToCoordinate function and supply edge padding.  Map animates to new coordinates, but ignores the edge padding completely.  Behavior is the same for both IOS and Android

`
let edgePadding = {
bottom: 300,
right: 0,
left: 0,
top: 0};
this.map.fitToCoordinates([coordinates], {edgePadding, animated:true});`

**Expected Behavior**
Padding should change to its new value during the camera change.

**Actual Behavior**
Map animates to new location, but padding does not change.

**Reproducible Demo**
None

**Note**
Issue 2292 and 2629 do not exhibit the exact same behavior as this issue seems to be platform agnostic.

**Comment by jfluence** [comment]
This is still broken on release 0.23.0

**Comment by avet-m** [comment]
@jfluence try to call fitToCoordinates method with timeout
1. On map initialize call fitToCoordinates in onMapReady [event](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#events)
2. If you need update position call fitToCoordinates in componendDidUpdate lifecycle 

```
            setTimeout(() => this.mapRef.current._component.fitToCoordinates(markers, {
                edgePadding: EDGE_PADDING,
                animated: true,
            }), 1000);
```

**Comment by jfluence** [comment]
I actually need to call the function when a drawer is opened/closed.  
I did try the componentDidUpdate life cycle but no luck.

**Comment by ribbit-rota** [comment]
I know this is an old issue, but was this ever resolved? I'm currently facing the same issue with `fitToSuppliedMarkers` as it seems to be ignoring the `edgePadding` option entirely.

**Comment by diegorodriguesvieira** [comment]
@jfluence @ribbit-rota 
https://github.com/react-native-community/react-native-maps/issues/3308
