### ISSUE TITLE
Marker do not pass click event on android

### ISSUE THREAD

**Issue by matan335** [react-native-maps/react-native-maps#2664]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.51.0
    react: 16.0.0
	react-native-maps: 0.19.0 or "git+ssh://git@github.com/react-community/react-native-maps.git"

### Expected Behavior

Marker pass click event to TouchableOpacity child component

### Actual Behavior

On ios the Marker is passing the press event but on android no event has been fired only the marker's onPress ebent is fired on clicking TouchableOpacity child component inside marker and as a result nothing happend when I press the TouchableOpacity inorder to display an image from gallery placed on a marker

**Comment by matan335** [comment]
Can someone help? this is a really big problem for me

**Comment by mohmdalfaha** [comment]
I am facing the same issue, any updates or did you solve it?

**Comment by mohmdalfaha** [comment]
Well, I fixed this by just not using TouchableOpacity and instead, I used onPress prop provided for the Marker itself. Hope this helps you or anyone facing the same issue on android particularly.
