### ISSUE TITLE
Double tap zoom does not work with Apple Maps on iOS.

### ISSUE THREAD

**Issue by Sakarisson** [react-native-maps/react-native-maps#2670]
## NOTE
I have not verified whether or not double tap zoom works on iOS using Google as a provider. As far as I know it may be an underlying issue that affects both providers. 

### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

```
    react: 16.6.3
    react-native: 0.57.8
    react-native-maps: 0.23.0
```

Target platform:

iOS, AppleMaps

Tested platforms:

Google Pixel 2, iPhone 6, iPhone 8, iPhone X.

### Steps to Reproduce

*(steps 3-5 are optional and are intended to illustrate the fact that this feature works on Android and not on iOS)*

1. Clone reproducible demo to your local environment.
2. `cd` into it and install dependencies (`yarn`)
3. Add your own Google Maps API key in `android/app/src/main/res/values.strings.xml`.
4. Open the application in an Android phone or an Android emulator (I used Google Pixel 2). 
5. Attempt to zoom using the one following method: 
5.1. Double tap the screen, but do not lift your finger from the glass after the second tap.
5.2. With your finger still resting on the screen, slide up or down to respectively zoom in or out of the map.
6. Now open the application in an iPhone or a simulator (I tried iPhone 6 physical and iPhone 6, 8 and X simulators). 
7. Attempt to zoom using the one finger method described in step 5. 

### Expected Behavior

The expected behavior would be for the iPhones to be able to zoom in or out using the one finger method. This method does work if you do it directly on Apple Maps.

It seems to work for the Android phones I have tested but not for the iPhones.

### Actual Behavior

Unfortunately it does not seem like the double tap zoom method works on any iPhones.

### Reproducible Demo

https://github.com/Sakarisson/react-native-maps-double-tap-zoom-repro

**Comment by RyanTG** [comment]
I can verify that it works in iOS with provider google. But it does not if you use provider apple maps. But this gesture is supported in apple maps, so I agree that I would expect this to work in RNM using apple maps.

**Comment by christopherdro** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why. Thanks!

**Comment by Sakarisson** [comment]
Indeed, the issue seems to have been fixed at some point between my report and now :)
