### ISSUE TITLE
Animated Marker not working in React Native 0.58

### ISSUE THREAD

**Issue by SystemBlad** [react-native-maps/react-native-maps#2681]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.58.1
    react: 16.6.3
	react-native-maps: 0.23.0 

  Target Platform: Android
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"

### Steps to Reproduce

1 Execute the react-native-maps example project.
2 Choose the option "Animated Marker Position"
3 The next error is shown:

01-30 10:04:39.570 17317 17661 E ReactNativeJS: This error is located at:
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in AIRMapMarker (at MapMarker.js:316)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in MapMarker (at createAnimatedComponent.js:153)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in AnimatedComponent (at AnimatedMarkers.js:62)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in AIRMap (at MapView.js:885)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in MapView (at AnimatedMarkers.js:52)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in RCTView (at View.js:45)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in View (at AnimatedMarkers.js:51)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in AnimatedMarkers (at App.js:116)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in RCTView (at View.js:45)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in View (at App.js:115)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in App (at renderApplication.js:34)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in RCTView (at View.js:45)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in View (at AppContainer.js:98)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in RCTView (at View.js:45)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in View (at AppContainer.js:115)
01-30 10:04:39.570 17317 17661 E ReactNativeJS:     in AppContainer (at renderApplication.js:33)

### Expected Behavior

A marker muts be animated

I think a native method was changed in new android SDK.

### Actual Behavior

The application Crashed

### Reproducible Demo

Check the project in the following link. You need to set the API key.
https://drive.google.com/open?id=1xbmhW3cnZhTqYN6CxNBb8g3n7Vp6-IQL

**Comment by nwaughachukwuma** [comment]
I have same issue, see image below
![image](https://user-images.githubusercontent.com/20521315/52569041-92472000-2e10-11e9-9b40-043151518384.png)

**Comment by nwaughachukwuma** [comment]
@SystemBlad I resolved it by adding values for latitudeDelta & longitudeDelta in 
`coordinate: new AnimatedRegion({/*values here*/})` definition. Hope this helps you

**Comment by SystemBlad** [comment]
@nwaughachukwuma Thanks, you are right just I set "0" for that properties and is working:

            coordinate: new AnimatedRegion({
                latitude: LATITUDE,
                longitude: LONGITUDE,
                latitudeDelta: 0,
                longitudeDelta: 0,
            }),
The example project must be updated.

However, after fix that the warning reported in issue #2671 is  shown.

**Comment by saif1002** [comment]
thank you guys, your info on helped me to fix 

> I have same issue, see image below
> ![image](https://user-images.githubusercontent.com/20521315/52569041-92472000-2e10-11e9-9b40-043151518384.png)

Thank You

**Comment by HemantRMali** [comment]
@nwaughachukwuma , Awesome, It Works.

this.state = {
        coordinate: new AnimatedRegion({
            latitude: LATITUDE,
            longitude: LONGITUDE,
            latitudeDelta: 0,  // -> **added this**
            longitudeDelta: 0, // ->  **added this**
        }),
    };

**Comment by anastely** [comment]
Hello all, can I achieve this in RN-maps?

[Marker](https://i.stack.imgur.com/vNrh1.gif)

**Comment by nwaughachukwuma** [comment]
Hi @anastely please rephrase your question or add little more detail for clarity
