### ISSUE TITLE
MapPadding on Android not working

### ISSUE THREAD

**Issue by LukePenkava** [react-native-maps/react-native-maps#2688]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-maps": "^0.23.0",

### Steps to Reproduce
Here is whole component, bare bones MapView setup with not much happening. MapPadding is not working and the Google logo is not showing up. This issue is only Android, everything works fine on iOS

```
import React from 'react';
import { Text, View, StyleSheet, Image, Dimensions } from 'react-native';
import MapView, { PROVIDER_GOOGLE, Marker } from 'react-native-maps';

const screen = Dimensions.get('window');
const ASPECT_RATIO = screen.width / screen.height;
const LATITUDE_DELTA = 0.03; 
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

class Map extends React.Component {
    render() {
        return (
            <View style={styles.container}>
                <MapView
                    provider={PROVIDER_GOOGLE}
                    style={styles.map}                    
                    mapPadding={{
                        top: 0,
                        right: 0,
                        bottom: 800,
                        left: 0
                    }}
                    initialRegion={{
                        latitude: 44.3148,
                        longitude: 85.6024,
                        latitudeDelta: LATITUDE_DELTA,
                        longitudeDelta: LONGITUDE_DELTA,
                    }}
                >
                    <Marker
                        coordinate={{ latitude: 44.3148, longitude: 85.6024 }}
                        tracksViewChanges={false}>                      
                    </Marker>
                </MapView>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        flex: 1
    },
})

export default Map;



```

**Comment by kelvinoshea** [comment]
having the same issue - android not working but iOS is abiding by mapPadding

**Comment by LukePenkava** [comment]
The map padding seems to be working fine on Android now, but the Google Logo is still not showing up. It basically disappears as soon as bottom padding is applied. Any help with that would be appreciated.

**Comment by padvlad** [comment]
@LukePenkava Did you change anything to make it work? I am using the latest version (0.24.2) and setting top padding does not work on Android. On iOS it works just fine.

**Comment by LukePenkava** [comment]
@padvlad Hi, i have mapPadding setup like this now:

```
const screen = Dimensions.get('window');
const ASPECT_RATIO = screen.width / screen.height;
const mapPaddingBottom = screen.height * 0.55;
const mapPaddingTop = screen.height * 0.1;

setMapPadding = () => {
        const iosEdgePadding = { top: mapPaddingTop * 0.5, right: 0, bottom: mapPaddingBottom * 0.95, left: 0 };
        const androidEdgePadding = { top: PixelRatio.getPixelSizeForLayoutSize(screen.height * 0), right: 0, bottom: PixelRatio.getPixelSizeForLayoutSize(screen.height * 0.17), left: 0 };
        const edgePadding = (Platform.OS === 'android') ? androidEdgePadding : iosEdgePadding;
        return edgePadding;
    }

<MapView
                    provider={PROVIDER_GOOGLE}
                    style={styles.map}
                    customMapStyle={MapStyle}
                    region={this.state.region}
                    mapPadding={this.setMapPadding()}
                >
```

Hope that helps a bit.

**Comment by padvlad** [comment]
Thanks for the quick response @LukePenkava. I have tried all approaches I could think of trying to get this to work but had no luck on the Android side.
My plan was actually to use the top padding to get a map pin centered correctly with the callout visible, which worked correctly on iOS but could not reproduce the results on Android. I actually winded up using a `LATITUDE_DELTA` when generating the `region` like you did in the first code snippet, but this doesn't seem to be an elegant solution.

I also played around with the left and bottom padding to see if the Google logo is moved correctly, but is seems to be cropped instead. This is how it looks like when setting `mapPadding={{ left: 20, bottom: 15 }}` on Android:
<img width="110" alt="Screen Shot 2019-04-25 at 10 09 50 AM" src="https://user-images.githubusercontent.com/8676848/56716729-b3e35280-6743-11e9-80b1-d53f57c01e6e.png">

**Comment by LukePenkava** [comment]
I am still having issue with this. Can we please get some solution how to use mappading on Android and get the Google logo without disappearing ( happens with bottom padding ). This seems as realy important feature, which is currently broken. I was not able to figure out anything in a month.

**Comment by SirKadogan** [comment]
LukePenkava's solution solved it for me

**Comment by tudormarze** [comment]
> Edit:
> I have solved the disappearing Google logo issue by updating the style with onMapReady
> 
> ```
> style={[styles.map, { width: this.state.width }]}
> onMapReady={() => this.setState({ width: this.state.width - 1 })}
> ```
> 
> i am setting width in state to screen.width. Otherwise you get map size issues or errors when its 0.

@LukePenkava thanks for the fix! I think it's better to have the initial width `screen.width - 1` and then rerender in `onMapReady` with `screen.width`. (the -1 is slightly visible on my screen)

**Comment by artemrsx** [comment]
any updates ?

**Comment by brmk** [comment]
Still not working.

As a workaround, it is possible to scale up the width and height of the map to the amount of the padding and recenter using negative margins
