### ISSUE TITLE
Fill color for Circle is not working in IOS, when we move to map screen 

### ISSUE THREAD

**Issue by gauravleo27** [react-native-maps/react-native-maps#2698]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

<Circle
                  key={marker.id}
                  center={{
                    latitude: marker.latitude,
                    longitude: marker.longitude,
                  }}
                  radius={marker.radius || 400}
                  fillColor={marker.fillColor}
                  strokeColor={marker.strokeColor || "rgba(255,0,0,1)"}
                  zIndex={marker.zIndex || 2}
                  strokeWidth={1}
                  miterLimit={0}
                />

**Comment by theharness** [comment]
When using a circle component in iOS, like this: 
`
<Circle
  center={this.state.circleCenter}
  radius={1000}
  strokeColor={'rgba(100,100,100,.5)'}
  fillColor={'rgba(100,100,100,.5)'}
/>
`

The stroke color and fill color are completely ignored. I also observed the same with the <Polygon/> component.

**Comment by khalid283** [comment]
@theharness 

Got same problem in iOS. Have you found any solution?

**Comment by RadekD** [comment]
@gauravleo27 @theharness  @khalid283 
I have found a solution. It seems that `Circle` nativeProps are not updated after received new props. 
And I am started doing `this.circle.setNativeProps({ fillColor: "rgba(255, 255, 255, 0.3)" });` after changing position of the circle. 

I think lib/components/MapCircle.js should have 
`componentDidUpdate(props) {
    this.setNativeProps(props)
 }` but not sure about Android, not tested it yet. 




```
onRegionChange = (region: Region) => {
        this.setState({
            marker: {
                latitude: region.latitude,
                longitude: region.longitude,
            }
        }, () => {
            this.circle.setNativeProps({ fillColor: "rgba(255, 255, 255, 0.3)" });
        });
}

<Circle ref={ref => { this.circle = ref; }} center={this.state.marker} radius={this.state.distance * 1000} />
```

**Comment by khalid283** [comment]
@RadekD This worked great in iOS. But I am still facing issue in setting marker custom image.

**Comment by jonong** [comment]
Are there any updates on this issue? I don't think we should need to call `setNativeProps(props)` every time we need to set/update props.

**Comment by mohshbool** [comment]
This is currently working on iOS 12.2 (RN 0.60.3) but it's wasting performance ... is there another workaround?

**Comment by Off2Race** [comment]
For me, Circle components won't respect the specified fillColor and strokeColor at all unless JS debugging is on. If I turn off the debugging, the circle will draw but without the desired color. If I turn the debugging back on, all is fine.

I recently updated from react-native-maps 0.22.0 to 0.25.0. I never noticed this issue on the previous version but I can reproduce the problem easily on the latest.

**Comment by mohshbool** [comment]
@Off2Race I'll try doing that but why does it happen in the first place?

**Comment by Off2Race** [comment]
Hi, @mohshbool — Unfortunately, I don't know what the root cause is. I'm just passing along what I learned.

**Comment by mtumiati** [comment]
I had the same issue and I tried with this workaround in MapCircle.js
```javascript
class MapCircle extends React.Component {
  setNativeProps(props) {
    this.circle.setNativeProps(props);
  }

  render() {
    const AIRMapCircle = this.getAirComponent();

// Set native props at every render if iOS
    if (this.circle && Platform.OS == 'ios') {
      this.circle.setNativeProps(this.props);
    }

    return (
      <AIRMapCircle
        {...this.props}
        ref={ref => {
          this.circle = ref;
        }}
      />
    );
  }
}
```

**Comment by mtumiati** [comment]
unfortunately the workaround is not working in Release version

**Comment by kyoyadmoon** [comment]
I have the same issue when using Circle component after upgrade react-native-maps to 0.25
I downgrade react-native-maps version to 0.24.2 and it works fine.

**Comment by mtumiati** [comment]
this is the same issue reported in #2867, still not solved.

**Comment by sam17896** [comment]
for ios 12.4 the stroke color is working fine. but for ios 13.1.2 stroke color seems to be ignored

**Comment by JaydenMajor** [comment]
I ran into this issue also and have the workaround using setNativeProps but i also noticed when using the zIndex prop on IOS that it will have issues. Even though i believe react native maps iOS doesn’t use this and it android only, for me it seemed to have an effect. Does anyone else has the same result?

**Comment by gusilveiramp** [comment]
Same problem here

**Comment by sneha1404** [comment]
I am using react-native-maps v0.27.1, react-native v0.61.5 and still facing this issue. The above workarounds also do not seem to work. Did anyone else find any solution for this?

**Comment by AbhiShrek** [comment]
> @gauravleo27 @theharness @khalid283
> I have found a solution. It seems that `Circle` nativeProps are not updated after received new props.
> And I am started doing `this.circle.setNativeProps({ fillColor: "rgba(255, 255, 255, 0.3)" });` after changing position of the circle.
> 
> I think lib/components/MapCircle.js should have
> `componentDidUpdate(props) { this.setNativeProps(props) }` but not sure about Android, not tested it yet.
> 
> ```
> onRegionChange = (region: Region) => {
>         this.setState({
>             marker: {
>                 latitude: region.latitude,
>                 longitude: region.longitude,
>             }
>         }, () => {
>             this.circle.setNativeProps({ fillColor: "rgba(255, 255, 255, 0.3)" });
>         });
> }
> 
> <Circle ref={ref => { this.circle = ref; }} center={this.state.marker} radius={this.state.distance * 1000} />
> ```


If you have mentioned the fillColor etc in the <Circle > instance, simply calling setNativeProps() with empty params in onRegionChange() also worked :
`this.circle.setNativeProps({  });`

**Comment by dkoprowski** [comment]
This happens always when I have at least two circles.

Workaround with setNativeProps works well for now. My workaround code with hooks. (I thought that maybe `useLayoutEffect` will works without timeout but nope - so you can use normal `useEffect`)

```jsx
  useLayoutEffect(() => {
    if (IS_IOS) {
      setTimeout(() => {
        if (circleRef.current) {
          circleRef.current.setNativeProps({
            fillColor: theme.colors.tealishGreen25,
            strokeColor: theme.colors.tealishGreen40,
          })
        }
      }, 0)
    }
  }, [])

  return (
    <Circle
      center={originLatLng}
      radius={originRange}
      fillColor={theme.colors.tealishGreen25}
      strokeColor={theme.colors.tealishGreen40}
      ref={circleRef}
    />
  )
```

**Comment by rakeshpetit** [comment]
I solved this by using the onLayout method of Circle component as none of the other solutions rendered the Circle immediately on iOS as soon as the component was mounted.

`
const circleRef = useRef(null)

<Circle
          ref={circleRef}
          onLayout={() => (circleRef.current.setNativeProps({
            strokeColor: colors.mapBorder,
            fillColor: colors.mapCircle,
          }))}
          center={center}
          radius={radius}
          strokeColor={'black'}
          fillColor={'blue'}
        />`

**Comment by SaijiroPL** [comment]
> circleRef

hi, rakeshpetit
Thanks for posting.
I used your code and got an error on "circleRef.current.setNativeProps".
Can you explain me about this?
Thanks

**Comment by teamzz111** [comment]
Issue not resolved yet.

**Comment by Off2Race** [comment]
Still not working

**Comment by robbertdejong88** [comment]
still waiting for a solution.
hope they will fix this soon

**Comment by oknelvapi** [comment]
Unfortunately, I have the same difficulties.  Moreover, I also get a few warnings: 
```
Warning: Failed prop type: The prop 'center' is marked as required in 'MapCircle', but its value is 'undefined'.
Warning: Failed prop type: The prop 'radius' is marked as required in 'MapCircle', but its value is 'undefined'
```
Currently, I'm using a crutch that was described by @dkoprowski. It works.

**Comment by tgreco** [comment]
Please fix!

**Comment by nindidooo** [comment]
Still having this issue in 2021. Anyone got a fix?

**Comment by gamingumar** [comment]
facing this issue with customMapStyle
