### ISSUE TITLE
UrlTile support for async function for urlTemplate

### ISSUE THREAD

**Issue by dflourusso** [react-native-maps/react-native-maps#2717]
### Is this a bug report?

No, it is a feature request

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

expo: 32.0.0
react: 16.5.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz

### Steps to Reproduce

```javascript
<MapView.UrlTile urlTemplate={async (z, x, y) => `file://some-path/${z}/${x}/${y}.png`}/>
```

### Expected Behavior

Should wait the tile to be generated before load. With this implementation i can generate the tiles offline on demand.

```javascript
<MapView.UrlTile urlTemplate={async (z, x, y) => {
  const file =  `file://some-path/${z}/${x}/${y}.png`
  const { exists } = await FileSystem.getInfoAsync(file)
  if(!exists) {
    // Call a function to generate the tile image
    await myFnToCreateTile(z, x, y)
  }
  return file
}/>
```

### Actual Behavior

Only with url template as string, i need to generate all tiles for all zoom levels i want before load the map.

**Comment by jacobltobin** [comment]
this would be The Best

**Comment by EKazachenko** [comment]
Hey @dflourusso ! Could you please provide a solution of your problem ? OFC if u found it :)

**Comment by EgorKazachenko** [comment]
Hi @dflourusso ! Did u find any solution ?

**Comment by dflourusso** [comment]
No solution yet
