### ISSUE TITLE
[IOS] callout not showing

### ISSUE THREAD

**Issue by vhoen** [react-native-maps/react-native-maps#2725]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react@16.6.3
react-native@0.58.6
react-native-maps@0.23.0

Issue occurs only on iOS.
Target Platform: iOS - 12.1 Simulator/iPhone X 

### Steps to Reproduce
1. Display two `<Marker />` on a `<MapView />`, one of them with a `<Callout />`, the other one without it.
1. First click on `<Marker />` without `<Callout />`
1. Then click on `<Marker />` with `<Callout />`

### Expected Behavior
When clicking on `<Marker />` with `<Callout />`,  `<Callout />` should be displayed.

### Actual Behavior
`<Callout />` is not displayed.

### Reproducible Demo
Here is an demo that reproduce the issue : https://github.com/vhoen/bugiosmapcallout

NB: Issue can be fixed app side by adding an empty callout with tooltip enabled instead : 
```
<Marker
  coordinate={{
    latitude: 37.787614,
    longitude: -122.431123,
  }}
>
  <Callout tooltip />
</Marker>
```

This is more a temporary solution but I thought it should be mentionned.

**Comment by christopherdro** [comment]
@vhoen There is 2 open PR's from one contributor that might help resolve this issue. Looks like one is more recent than the other. 
https://github.com/react-native-community/react-native-maps/pull/2581
https://github.com/react-native-community/react-native-maps/pull/2538

Any chance you can help test the changes and see if it resolves the issue you're coming across?

**Comment by vhoen** [comment]
@christopherdro 
I tested #2581, it does not fix the issue.

According to comments in #2581 it replaces #2538, so I did not test #2538.

**Comment by yelkamel** [comment]
Hi I got the same issue and PRs doesn't fix the problem...

**Comment by spyshower** [comment]
Any update/fix on this?
