### ISSUE TITLE
LocalTiles causes onMapReady not to be called correctly

### ISSUE THREAD

**Issue by DanielBoening** [react-native-maps/react-native-maps#2731]
### Is this a bug report?
YES
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES
### Environment

    react-native: 0.57.0
    react: 16.4.1
    react-native-maps: 0.23.0

### Expected Behavior

I load a local map with LocalTile which works fine. I expect onMapReady to be called.

### Actual Behavior
onMapReady is not called. This happens only with LocalTiles.
Also, the map is repeated horizontal, I don't expect this either.

**Comment by fernando-clvm** [comment]
I experienced the same issue in iOS 12.2, but it works properly for me in iOS 13.2.2

**Comment by christopherdro** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why. Thanks!
