### ISSUE TITLE
UrlTile on Google maps for iOS - urlTemplate prop cannot be changed after it is initialized

### ISSUE THREAD

**Issue by sebqq** [react-native-maps/react-native-maps#2733]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native": "0.58.6",
"react-native-maps": "0.23.0"

### Steps to Reproduce

Please follow on this one... I will enclose as much info as I can...

On android, everything works fine and urlTile urlTemplate prop is changed (in case of urlTemplate is changed) properly. But urlTemplate prop of UrlTile on ios (Google Maps SDK) cannot be changed from its initial value. In my application, I have some offline tiles stored in bundle (default offline tiles, which are pre-packed to the app). Then users have option to download more detailed offline tiles which I store to Document directory on both iOS and Android.

Now at runtime and as location is changing I'm calculating if the user is located at specific state, which tiles he downloaded in the past. If so, the url template is changed from (on iOS specific)

`"file://" + RNFS.MainBundlePath + "/assets/tiles/{z}/{x}/{y}.png"`

to 

`"file://" + RNFS.DocumentDirectoryPath + "/maps/" + countryCode + "/{z}/{x}/{y}.png"`

this functionality is wrapped in class getter like so:

```
get offlineTilesPath() {
    const { isDownloaded, countryCode } = this.state;
    if (isDownloaded) {
      // this statement is TRUE at runtime so this path should be used for UrlTile!
      // Even console.log() inside render() method returns this string.
      return OFFLINE_TEMPLATE_PREFIX + countryCode + "/{z}/{x}/{y}.png";
    }
    // fallback to default tiles
    // this string is returned on intial Map region set and when no country is found which offline tiles are available
    return "file://" + RNFS.DocumentDirectoryPath + "/maps/" + countryCode + "/{z}/{x}/{y}.png";
  }
```

My UrlTile code fragment looks like:

```
<UrlTile
     urlTemplate={this.offlineTilesPath}
     zIndex={-1}
     maximumZ={18}
     tileSize={256}
 />
```

I found in xCode console that UrlTile is still using path, which was set at first render of map! In my case it is `"file://" + RNFS.MainBundlePath + "/assets/tiles/{z}/{x}/{y}.png"`, so in the end the map is blank because tiles for specific zoom level aren't available in MainBundlePath because they are stored in DocumentDir!

I'm also enclosing ios console output and as you can see, wrong path is used!

```
2019-03-12 14:11:06.142523+0100 eccNativeApp[87090:4813503] Task <AF57E66E-B9D9-4F83-B5CF-1DBAFD6B6F3E>.<56> load failed with error Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSErrorFailingURLStringKey=file:///Users/trebunak/Library/Developer/CoreSimulator/Devices/XXXYYY/data/Containers/Bundle/Application/XXXXXYYYYY/eccNativeApp.app/assets/tiles/9/285/190.png, NSErrorFailingURLKey=file:///Users/trebunak/Library/Developer/CoreSimulator/Devices/XXXYYY/data/Containers/Bundle/Application/XXXYYY/eccNativeApp.app/assets/tiles/9/285/190.png, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <AF57E66E-B9D9-4F83-B5CF-1DBAFD6B6F3E>.<56>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <AF57E66E-B9D9-4F83-B5CF-1DBAFD6B6F3E>.<56>, NSUnderlyingError=0x6000008ac750 {Error Domain=kCFErrorDomainCFNetwork Code=-1100 "(null)"}} [-1100]
``` 

So it definitely looks like the urlTemplate cannot be changed after it is initialized... I tried to find, if there isn't any `shouldComponentUpdate() return false;` in react-native-maps UrlTile component source code but I didn't find anything.

I prepared [simplified Snack](https://snack.expo.io/@sebinq/react-native-maps-urltile-urltemplate-path-cannot-be-changed!) where you can try to change Tiles provider. The change of tile provider string is not going to work on iOS but it is clearly working on Android... 

I'm not able to use LocalTile on iOS because when I try i keep getting redbox which is related to unsolved issue #2088 with message:

```
Invariant Violation: requireNativeComponent: "AIRGoogleMapLocalTile" was not found in the UIManager.

This error is located at:
  in AIRGoogleMapLocalTile (at MapLocalTile.js:46)
  in MapLocalTile (at MapView.js:154)
  ...
```

### Reproducible Demo

[simplified Snack](https://snack.expo.io/@sebinq/react-native-maps-urltile-urltemplate-path-cannot-be-changed!)

## EDIT
If we can make it work to let urlTemplate change for UrlTile-s then #2088 can be closed in favour of this hack, because the functionality of LocalTile-s can be achieved with UrlTile-s

**Comment by sinodko** [comment]
I'm not objective C developer but if somebody can guide me how to expose native AIRGoogleMapUrlTile's `setUrlTemplate` method to the react-native I think we can make it work.

**Comment by sinodko** [comment]
Or maybe even easier solution could be just let urlTemplate change whenever urlTemplate prop is chaged :D same as with Android Google Maps

**Comment by sinodko** [comment]
I've found an ugly hack. I can force UrlTile to use new urlTemplate by setting different `key` prop to the `<UrlTile key={this.state.key} />` component, whenever tile provider is changed. This way will UrlTile use new urlTemplate but I think this is not best practice as (I think that) map is generating new UrlTile component whenever the map is changed. Am I right? Can there by any memory leaks? Please follow.

**Comment by rohitkum28** [comment]
> I've found an ugly hack. I can force UrlTile to use new urlTemplate by setting different `key` prop to the `<UrlTile key={this.state.key} />` component, whenever tile provider is changed. This way will UrlTile use new urlTemplate but I think this is not best practice as (I think that) map is generating new UrlTile component whenever the map is changed. Am I right? Can there by any memory leaks? Please follow.

@sebqq  Did you find any better solution for this?

**Comment by IlyaUpyackovich** [comment]
Hey guys, I have the same issue. I wonder why that "AIRGoogleMapLocalTile does not exist" bug is not fixed yet. It's like very crucial functionality. Or there is a workaround I don't know about? Did I miss something?

**Comment by devWaleed** [comment]
Bump

**Comment by Khubaib69** [comment]
> I've found an ugly hack. I can force UrlTile to use new urlTemplate by setting different `key` prop to the `<UrlTile key={this.state.key} />` component, whenever tile provider is changed. This way will UrlTile use new urlTemplate but I think this is not best practice as (I think that) map is generating new UrlTile component whenever the map is changed. Am I right? Can there by any memory leaks? Please follow.

Hello I am facing this same issue when UrlTile's key property is changed it refreshes the component and new image is placed on map. but I want a smooth transition like apple weather app. Did you find any solution for this?
