### ISSUE TITLE
Rendering a Marker with a custom view in react native maps not working in android but works in iOS devices

### ISSUE THREAD

**Issue by akhilsanker** [react-native-maps/react-native-maps#2734]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-maps": "^0.16.3",

### Steps to Reproduce

Added custom marker not showing in android devices.

### Expected Behavior

To show the custom marker in android devices as like in iOS devices.

### Actual Behavior

Uses different custom marker to show the nearby restaurant. But the markers are not shown in android devices and it works fine in iOS devices. 

### Reproducible Demo

        <MapView.Marker 
	     coordinate={item.coordinates}
	     style={{zIndex: 55, position:"relative"}}
	     tracksViewChanges={this.state.tracksViewChanges}
        >
	        <Animated.View  >
		       <View >
			   <Image source={require('../../assets/map-marker-2-gray.png')} style={{width: 30, height: 30}} />
		       </View>			
	       </Animated.View>
        </MapView.Marker>

**Comment by danielgindi** [comment]
You are working with a VERY old version of react-native-maps. It did not work back then.

**Comment by akhilsanker** [comment]
Hi @danielgindi ,

Thanks for your response.
I have used "react-native-maps": "^0.23.0". But when we move the over the map, the draggable marker is not responding correctly. Unable to zoom and drag to other positions. But it works fine in "react-native-maps": "^0.16.3", expect the custom marker.

Thanks

**Comment by CyxouD** [comment]
Expo: `27.0.0`,  react-native-maps: `0.23.0` Issue still exists

**Comment by yorickreum** [comment]
Facing similar issue. Everything works fine on iOS. And it's fine on Android until I click/press on the marker, then it suddenly changes for the normal Google Maps PIN.

**Comment by PurnimaNaik** [comment]
This is a know issue. The following was added in the official docs 3 years ago-

`Issue: Since android needs to render its marker views as a bitmap, the animations APIs may not be compatible with the Marker views. Not sure if this can be worked around yet or not.`

You can find it here-https://github.com/react-native-community/react-native-maps, under the '_Using the MapView with the Animated API_' section.

It is the `Animated.View` that causes the problem on android. Ditch it for a `View` component if you can. Then it will work the same on android and iOS.

**Comment by abhideepmallick** [comment]
This is a complete hack fix, but it works. You can test the below layout inside a `MapView.Marker`:

```
<ImageBackground
    style={{ ...Styles }}
    source={...ImageFile}
    onLoad={() => this.forceUpdate()}
>
    <Text style={{ width: 0, height: 0 }}>{Math.random()}</Text>
</ImageBackground>
```
