### ISSUE TITLE
Multiple <UrlTile />'s Order Not Working

### ISSUE THREAD

**Issue by systemlevel** [react-native-maps/react-native-maps#2750]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-maps": "^0.23.0",

### Steps to Reproduce

(Write your steps here:)

1. 

```
              <MapView
                showsUserLocation={true}
                showsMyLocationButton={true}
                style={styles.map}
                region={{
                  latitude: 39.957278,
                  longitude: -83.002115,
                  latitudeDelta: 0.015,
                  longitudeDelta: 0.0121,
                }}
              >

                /* . FIRST UrlTile shows beneath SECOND
                <UrlTile
                    urlTemplate={'https://dist.com/map/test/Mapnik/{z}/{x}/{y}.png'}
                    maximumZ={18}
                    shouldReplaceMapContent={true}
                />

                /* . SECOND UrlTile shows above FIRST
                <UrlTile
                  /**
                   * The url template of the tile server. The patterns {x} {y} {z} will be replaced at runtime
                   * For example, http://c.tile.openstreetmap.org/{z}/{x}/{y}.png
                   */
                    urlTemplate={'https://mapserver.com/arcgis/rest/services/LandCover/MapServer/tile/{z}/{y}/{x}?token=' + this.context.state.tokenNeoTreks}
                    maximumZ={19}
                />

              </MapView>
```

2. 

NOW REVERSE ORDER

```
              <MapView
                showsUserLocation={true}
                showsMyLocationButton={true}
                style={styles.map}
                region={{
                  latitude: 39.957278,
                  longitude: -83.002115,
                  latitudeDelta: 0.015,
                  longitudeDelta: 0.0121,
                }}
              >

                /* . SECOND UrlTile shows above FIRST
                <UrlTile
                  /**
                   * The url template of the tile server. The patterns {x} {y} {z} will be replaced at runtime
                   * For example, http://c.tile.openstreetmap.org/{z}/{x}/{y}.png
                   */
                    urlTemplate={'https://mapserver.com/arcgis/rest/services/LandCover/MapServer/tile/{z}/{y}/{x}?token=' + this.context.state.tokenNeoTreks}
                    maximumZ={19}
                />

                /* . FIRST UrlTile shows beneath SECOND
                <UrlTile
                    urlTemplate={'https://dist.com/map/test/Mapnik/{z}/{x}/{y}.png'}
                    maximumZ={18}
                    shouldReplaceMapContent={true}
                />

              </MapView>

```

I get the same result either say.  I've tried Z-Index on iOS but it doesn't effect anything.

### Expected Behavior

The UrlTiles should be able to be ordered visually depending on the order of UrlTile or atleast have some sort of mechanism to determine the order of display for more than one UrlTile applied to the map.

### Actual Behavior

You'll notice in the video that the layer containing the red dot data points always moves behind the other UrlTile layer and hides it.  It doesn't matter which order I place the <UrlTile /> the result is the same:

**Comment by systemlevel** [comment]
I resolved this issue by going with the fix as described here:  https://github.com/react-native-community/react-native-maps/issues/1181#issuecomment-343874160

Add a key to the layer:

key={Date.now()}

**Comment by rborn** [comment]
@systemlevel did you add a `zIndex` to your UrlTiles?

**Comment by systemlevel** [comment]
@rborn yeah that’s a great point. I attempted the zindex parameter. It didn’t work for me. The zindex had no effect on my UrlTile layers.

Have you had success with `zIndex`?  If so do you have a code snippet that demonstrates how you got yours to work? 

 Thanks so much.
