### ISSUE TITLE
Overlay:  bounds prop set wrong position of an image

### ISSUE THREAD

**Issue by gangstaJS** [react-native-maps/react-native-maps#2776]
I have trouble with an image overlay.

### Is this a bug report?

BUG

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

```
{
 "react-native": "0.59.2",
 "react-native-maps": "0.23.0",
 "react": "16.8.3",
}

```

Simulator/iPhone 8 (AppleMaps)

### Steps to Reproduce

Bounds example:

```javascript
 const bounds = [
  [field.SouthLat, field.WestLon], 
  [field.NorthLat, field.EastLon]
 ]
```

Output: 
```
[
  [-30.173081337,149.6555078531],
  [-30.1882609123,149.664137526]
]
```

### Expected Behavior

**There is the result in browser (leaflet.js)** (for the same bounds)
![browser result](https://api.monosnap.com/rpc/file/download?id=rXcUXqsz1kKhRFqCwZrHUrfJ3JvxfK)

### Actual Behavior

**There is the result on iPhone 8 emulator:**
![browser result](https://api.monosnap.com/rpc/file/download?id=avT77rR8m7e6yYOHF25CXJZhkMyeN9)

### Reproducible Demo

Code:

```
...
<Overlay bounds={[[field.SouthLat, field.WestLon], [field.NorthLat, field.EastLon]]}
                                     image={{uri}}/>
...
```

**Comment by rborn** [comment]
@gangstaJS why sorry?  Update the issue and I'll re-open it.
Ping me once you did it.

**Comment by gangstaJS** [comment]
@rborn ping :)

**Comment by rborn** [comment]
@gangstaJS can you try to use a big  `zIndex` for your overlay?

**Comment by gangstaJS** [comment]
@radeno I have found the issue, it is the `fitToCoordinates`. When I removed it the image fully was rendered. but this does not solve my problem cuz I need `fitToCoordinates`

![example](https://api.monosnap.com/rpc/file/download?id=weX8zt7NBtHYLhjwOCPa2wmOW1Sry2)

Result:
![example](https://api.monosnap.com/rpc/file/download?id=nQP5XQXeyoktQ1VpydzEwKpw56D9R1)

**Comment by rborn** [comment]
@gangstaJS try to execute `fit` after a delay , maybe the map still needs to execute stuff (out of curiosity)

**Comment by gangstaJS** [comment]
@rborn I have tried setTimeout 2sec it did not help. I can use `region`  prop for fit to a center of overlay but in this case, I do not have cool animation :(

**Comment by gangstaJS** [comment]
@radeno Look at this wired behavior https://monosnap.com/file/HyCiFNe4JeDHsEYXcZFg9UKtWLi51W

```javascript

fit = () => {
    if(this.props.shape) {
      const c = center(this.props.shape);

      const [longitude, latitude] = c.geometry.coordinates;

      this.setState({longitude, latitude}) // set regin to MapView
    }

    setTimeout(() => {
      this.props.shape && this.map.fitToCoordinates(this.props.shape.features[0].geometry.coordinates[0].map(c => ({
        latitude: c[1],
        longitude: c[0]
      })), {animated: false});
    }, 2000)
  };

```

**Comment by gangstaJS** [comment]
@rborn and one more wired thing, when zoom the image overlay is cutting https://monosnap.com/file/MYrKy5ffX7LtqLJxqbVFyOuaa3AQLP

**Comment by gangstaJS** [comment]
Looks like the problem from the above video in the Polygon, when I commented it all zooming fine

Example: https://monosnap.com/file/WVKnHcihFdYWPHhHTUIoxxh4a3vpyK

```javascript

<MapView
        ref={(ref) => {
          this.map = ref;
        }}
        provider={null}
        style={styles.map}
        mapType="satellite"
        region={{
          latitude: this.state.latitude,
          longitude: this.state.longitude,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA,

        }}
        onPress={e => this.onPress(e)}
        zoomControlEnabled={true}
      >
        {this.props.shape ? <Polygon zindex={2} strokeWidth={3} strokeColor="rgb(51, 136, 255)"
                                     coordinates={this.props.shape.features[0].geometry.coordinates[0].map(c => ({
                                       latitude: c[1],
                                       longitude: c[0]
                                     }))}/> : null}
        {field ? <Overlay
          zindex={9}
          bounds={[[field.NorthLat, field.WestLon], [field.SouthLat, field.EastLon]]}
          image={'https://storage.googleapis.com/flurosat-au/processed-v1/fc57b8a0f8ea48181bcc07d3b4994c57/20180523T001111/20180523T001111_T55JGG_S2A_ccci_singleDate.png'}
        /> : null}

      </MapView>
```

**Comment by radeno** [comment]
@gangstaJS is your overlay image with enough resolution? iPhone simulator uses retina with 2x or 3x (depends on iPhone) bigger density than in browser. Just brainstorming about blurry image when upscaling.
Anyway incomplete rendering of image is weird. Can you test it with Google maps? Just for curiosity if it is same result.

**Comment by gangstaJS** [comment]
@radeno Hey man the google maps really work perfectly 
https://monosnap.com/file/mF96gyMYYbShBIeIKtmpLkZMSflGqW

**Comment by radeno** [comment]
@gangstaJS ok thanks for info. If i am right, Google maps uses bitmap tiles, and Apple uses vectors on iOS. So need to check where is real issue. Harder part :)

**Comment by gangstaJS** [comment]
@radeno How the satellite tiles can be vectors?

**Comment by radeno** [comment]
@gangstaJS ah i see, you used satellite tiles. My bad. Can you test it with different map type layers? Road, satellite. It could help isolate real issue.
