### ISSUE TITLE
Dashed Polyline is not working on Android

### ISSUE THREAD

**Issue by Eyesonly88** [react-native-maps/react-native-maps#2779]
### Is this a bug report?

Yes. It only happens on Android. iOS works fine.

#### Android (broken ⚠️ )

![Screen Shot 2019-04-01 at 11 10 48 AM](https://user-images.githubusercontent.com/767013/55295893-fa100380-546e-11e9-9211-fc0ed856b02f.png)

#### iOS (✅ )

![Screen Shot 2019-04-01 at 11 11 12 AM](https://user-images.githubusercontent.com/767013/55295903-085e1f80-546f-11e9-869b-4e0d0b4c09d4.png)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 36.21 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        API Levels: 21, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-log-ios: 1.0.1
```

### Steps to Reproduce

Create a simple polyline with `lineDashPattern=[15,15]` on Android.

See this snack: https://snack.expo.io/@mido/react-native-maps-android-dash-line-broken

### Expected Behavior

Dashed polyline renders correctly on Android.

### Actual Behavior

Dashed polyline renders as a straight line, not dashed.

### Reproducible Demo

https://snack.expo.io/@mido/react-native-maps-android-dash-line-broken

**Comment by Arjun-sna** [comment]
The current version doesn't support Dashed Polyline for Android.
It is included in upcoming release 6c225af
Also please check #2805
