### ISSUE TITLE
Incompatibility with react-navigation v3

### ISSUE THREAD

**Issue by compojoom** [react-native-maps/react-native-maps#2780]
I have posted this in the react-navigation (https://github.com/react-navigation/react-navigation/issues/5594) and react-native-gesture-handler (https://github.com/kmagiera/react-native-gesture-handler/issues/465) repositories since it seems that the error is more at their end. However the issue still concerns this repository so I'm posting here with the hope that someone with knowledge of rn-maps will have a better idea what is going on and has ideas for a workaround/fix.

Here is a gif of the issue:
![2019-02-14 23 05 41](https://user-images.githubusercontent.com/693770/52821330-c8093480-30ae-11e9-9679-21b440bc210f.gif)

React-navigation in version 3 users react-native-gesture-handler under the hood and it seems that something in the marker dragging prevents rn-gesture-handler from finding out that there is no gesture taking place.

Here is the repository with only gesture handler and react-native-maps
https://github.com/compojoom/rnMapsNavigationBug/tree/gesture_hangler

When you drag the marker and afterwards try to press any button it won't work until you drag the map.

For those who don't want to test the repository - here is a snack with the issue: https://snack.expo.io/@eriveltonelias/maps-react-navigation

I know that it looks more like the issue is in the rn-gesture-handler corner, but react-navigation and react-native-maps are one of the most popular rn-packages and it is stupid that users would be stuck with such an issue.

### Is this a bug report?
yes

### Environment
iOS. Issue doesn't happen on Android

### Steps to Reproduce
View provided repository
https://github.com/compojoom/rnMapsNavigationBug/tree/gesture_hangler

**Comment by buraksak35** [comment]
Some issue on IOS, working good on Android

**Comment by IAmMarcellus** [comment]
@compojoom were you able to find a workaround for this?

I'm trying to keep track of when the user moves the map so that I can show a "search this area" button. I'm trying to use `onMoveShouldSetResponder` to change the state on touch, which means I'm using react native's default gesture responder instead of React-Native-Gesture-Handler, but that works fine on Android when disabling gestures in React Navigation, but the event doesn't fire on iOS.

People had similar problems, as discussed in https://github.com/react-native-community/react-native-maps/issues/1038, and they were able to use other responder events in React Native's default gesture responder, but not `onMoveShouldSetResponder`. Because using the default responder works on android when disabling gestures in React Navigation but not on Android, I think the issue may be related to https://github.com/kmagiera/react-native-gesture-handler/issues/255 since he didn't test on Android, but because RNGH isn't working with react-native maps, nor is the default responder, I can't seem to find an efficient workaround.

**Comment by compojoom** [comment]
The last release about the memory fix was talking about gestures, so I decided to see if it will solve the problem, but it doesn't. I've updated the repository to 0.24.2 and the problem remains. 

Since it is working after moving the map I thought that if I move the map with animateToCamera or to Region it could work, but it didn't. Problem remains.

The only workaround that I have right now is to use react-navigation v2 - which doesn't rely on rn-gesture-handler... But react-navigation v2 has it's own set of issues...

**Comment by mbrehme** [comment]
I have exactly the same problem. Did you somehow solved this issue with an current version of navigation?

**Comment by yamaka** [comment]
parche only hide map onEnDrag event in IOS with setState like this:
changePositionMarker = e => {
        if (Platform.OS == 'ios') {
            this.setState(
                {
                    latLong: e.nativeEvent.coordinate,
                    showHideMap: false,
                },
                () => {
                    this.setState({
                        showHideMap: true,
                    });
                }
            );
        } else {
            this.setState({
                latLong: e.nativeEvent.coordinate,
            });
        }
    };

**Comment by barinascode** [comment]
Creo que encontre la solucion, es la misma solucion de @yamaka pero implementada en un componente funcional

`import React, {useState,useEffect} from 'react';
import {StyleSheet,View, Text, TouchableOpacity} from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
import { mapStyle } from '../styles/mapStyle';
import defaultMapOptions from '../config/mapOptions'


function RegisterMarketScreenStep2(props) {

	const CompanyInfoSchema = {
		company_name : 'SIB C.A.',
		address : 'Barinas',
		company_email : 'info@sib.com',
		primary_phone : '330 7364527',
		secondary_phone : '330 8746302'
	}

const [ CompanyInfo ] = useState(CompanyInfoSchema)

	const [Origin , setOrigin] = useState({
		          	latitude: 18.388725,
				  	longitude: -66.130101,
				})
				
	const [ZoomMap , setZoomMap] = useState({
					latitudeDelta: -0.001,
					longitudeDelta: 0.0180,
			  })

	const [ForceRefresh , setForceRefresh ] = useState( Math.floor(Math.random() * 100) ) 

	useEffect(() => { 
		setForceRefresh(Math.floor(Math.random() * 100))
	  },[Origin]);



    return <View style={styles.container}>
			

			<View style={styles.captionContainer}>
              	<View style={{flex : 1,flexDirection:'row'}}>
                  	<View style={{ flex: 1, flexDirection: 'row', alignItems: 'center',padding:10,justifyContent:'center'}}>
						<TouchableOpacity>
							<Text style={{color:'white'}}>Drag and drop ther marker and set your bussiness location</Text>
						</TouchableOpacity>
                  	</View>
              	</View>
              </View>

            <MapView
			  key={ForceRefresh}
              style={styles.map}
              provider={PROVIDER_GOOGLE}
              region={{
                ...Origin,
                latitudeDelta: ZoomMap.latitudeDelta,
                longitudeDelta: ZoomMap.longitudeDelta,
              }}
              defaultOptions={defaultMapOptions}
              customMapStyle={mapStyle}
              showsCompass={false}
              zoomEnabled={true}
              zoomControlEnabled={true}
              toolbarEnabled={false}
              >

            <MapView.Marker
				coordinate={{...Origin}}
				title={"You are here"}
				image={require('../assets/pin.png')}
				draggable
        		onDragEnd={(e) =>setOrigin(e.nativeEvent.coordinate)}

			>
            </MapView.Marker>
            </MapView>
            

			


            <View style={styles.buttonContainer}>
            	<View style={{flex : 1,flexDirection:'row'}}>
                  
					<TouchableOpacity 
						style={{ flex: 1, flexDirection: 'row', alignItems: 'center',padding:10,justifyContent:'center'}}
						onPress={ () => this.props.navigation.goBack() }
					>
						<Text style={{color:'white'}}>Back</Text>
					</TouchableOpacity>

					<TouchableOpacity style={{ flex: 1, flexDirection: 'row', alignItems: 'center',padding:10,justifyContent:'center'}}>
						<Text style={{color:'white'}}
						onPress={ () => props.navigation.navigate('MarketConfirm', {company : {...CompanyInfo}, origin : Origin }) }>Next</Text>
					</TouchableOpacity>
            	</View>
            </View>

        </View> 
}

export default RegisterMarketScreenStep2

const styles = StyleSheet.create({
  map: {
    height : '100%',
    flex: 1,
    zIndex: 2,
    backgroundColor: '#FFFFFF'
  },
  container: {
    flex: 1,
  },
  captionContainer: {
    flex : 1,
    position : 'absolute',
    top : 0,
    zIndex : 4,
    backgroundColor: '#6812c0',
    padding: 10,
    width : '100%',
    shadowRadius: 10,
    shadowOpacity: 0.25
  },
  buttonContainer: {
    flex : 1,
    position : 'absolute',
    bottom : 0,
    zIndex : 4,
    backgroundColor: '#6812c0',
    padding: 10,
    width : '100%',
    shadowRadius: 10,
    shadowOpacity: 0.25
  },

  button: {
    flex : 1,
	backgroundColor: '#6812c0',
	zIndex : 3,
    justifyContent : 'center',
    marginTop : 3,
    color:'white',
    textAlign : 'center',
    borderRadius: 5,
    padding: 10,
    shadowColor: '#6812c0',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    width : '100%',

    shadowRadius: 10,
    shadowOpacity: 0.25
  },
  caption : {
    textAlign:'center',color:'yellow',flex : 1, fontSize : 24
  }
});`

**Comment by sergey-ovdienko** [comment]
We also had this issue.

Our solution was to use `Touchable*` components provided by `react-native-gesture-handler` package instead of `react-native` ones:

```js
import { TouchableOpacity } from 'react-native-gesture-handler';
```

They continue to work after map marker dragging.

**Comment by zhigang1992** [comment]
> import { TouchableOpacity } from 'react-native-gesture-handler';

This isn't really a viable option for us, since our map is on the home scree.

We would need to swap out every since Touchable in our App to fix this issue.

**Comment by nimrodbens** [comment]
> We also had this issue.
> 
> Our solution was to use `Touchable*` components provided by `react-native-gesture-handler` package instead of `react-native` ones:
> 
> ```js
> import { TouchableOpacity } from 'react-native-gesture-handler';
> ```
> 
> They continue to work after map marker dragging.

there are other components in my project which i did not build and they get locked up because of that as well.. so it doesn't solve it completely. i noticed that if i tap on the map after the long press function then the issue resolves. i tried to look up how to simulate a tap in react native but couldn't find any way. (it's my first app in react native)

**Comment by nimrodbens** [comment]
anything new here? it literally renders my app useless..

**Comment by avlonder** [comment]
Still no other solution but swapping react-native's TouchableOpacity for react-native-gesture-handler's TouchableOpacity?
The latter comes with its own set of issues (flexbox, absolute positioning, touch sounds).

**Comment by zhigang1992** [comment]
@avlonder I don't think so, we eventually revert back to Apple Map for our app.

**Comment by FayyazAliKhan1** [comment]
@mertlena the issue is the TouchableOpacity which is not clickable is positioned above mapview 
Rest TouchableOpacity are working
