### ISSUE TITLE
Explicit control is needed for requesting background location

### ISSUE THREAD

**Issue by adambutler** [react-native-maps/react-native-maps#2793]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.58.6
react: 16.6.3
react-native-maps: 0.23.0

Target Platform: iOS 12.2 / iPhone 7 
Maps: GoogleMaps

### Steps to Reproduce / Behavior /  Reproducible Demo

This issue relates more to App Store Connect rules and compatibility with another project.

I hope you'll agree after reading the description below that a reproducible demo wouldn't be helpful given that the issue lies in a lack of functionality rather than something that is implemented already but isn't working.

### Description

There is a widely used library called [react-native-permissions](https://github.com/yonahforst/react-native-permissions). Within the README it specifies:

> If you need to submit your application to the AppStore, you need to add to your Info.plist all *UsageDescription keys with a string value explaining to the user how the app uses this data. **Even if you don't use them.**

See direct link [here](https://github.com/yonahforst/react-native-permissions#app-store-submission-disclaimer)

Unfortunately, this causes a conflict with a behaviour in react-native-maps.

This project implicitly utilises the presence of the `NSLocationAlwaysUsageDescription` key in `Info.plist` without exposing any way of explicitly stating if the desired permission request should request in-app or background geolocation.

If the `NSLocationAlwaysUsageDescription` key is present, I can not prevent react-native-maps from requesting background geolocation, even if I do not wish to use it.

However, if I remove `NSLocationAlwaysUsageDescription` from `Info.plist` I will get the notice when submitting the build to Apple:

>  Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. 

I would propose that a new option is exposed to allow an implementer of react-native-maps to decide explicitly if the request is made for background geolocation or not.

**Comment by rborn** [comment]
@adambutler - maybe you can add your thoughts and help push this one forward? https://github.com/react-native-community/react-native-maps/pull/1184

**Comment by alexdaley** [comment]
I also have this issue - I cannot prevent react-native-maps from requesting background geolocation if I set NSLocationAlwaysUsageDescription, and the Apple build review requires me to.

**Comment by brsaylor2** [comment]
Just in case it is helpful: I had a similar issue that turned out to be caused not by react-native-maps, but by `navigator.geolocation.getCurrentPosition()`. (Same thing with needing to have `NSLocationAlwaysUsageDescription` due to using react-native-permissions).

I was able to prevent the "always" permission prompt by adding the following line:

```
navigator.geolocation.setRNConfiguration({ skipPermissionRequests: true });
```

and requesting permission explicitly using react-native-permissions.

**Comment by svegan** [comment]
Still getting permission request on ios if `showsUserLocation` prop is provided, even in case `setRNConfiguration({ skipPermissionRequests: true })` was set.

**Comment by wesvance** [comment]
@svegan make sure you're <MapView/> doesn't have showsUserLocation set to true, or any other property that might use the location such as followsUserLocation. Once I set those to false when permissions were not enabled, I no longer got the permissions dialog popup.

**Comment by svegan** [comment]
@wesvance but I need that property. But thank you anyway, you have given me obvious idea how to solve that, to check permission before map component mounts and depending on result either pass that prop to mounting map or not.

**Comment by wesvance** [comment]
@svegan thats one way, but you can also just set followsUserLocation, showsUserLocation, etc. to... false until you have permission, then update those values to true once you get permission to use their location.

So I have this.setState({haveLocationPermission: false}) at the start of my app - then I check if I have the location permissions - if I do, then I this.setState({haveLocationPermission: true}).

Similarly

```javascript
const {haveLocationPermission} = this.state;
<MapView
   followsUserLocation={haveLocationPermission}
   ...
/>
```

**Comment by svegan** [comment]
@wesvance also an option. Thanks!
