### ISSUE TITLE
How to avoid rendering Google/MapKit under OSM Tile?

### ISSUE THREAD

**Issue by andrey-shostik** [react-native-maps/react-native-maps#2796]
### Is this a bug report?

Not sure

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.59.2
    react: 16.8.3
	react-native-maps: 0.23.0
### Steps to Reproduce

Just open map with OSM Tile and move to any other coordinates, You will see Google/MapKit map under OSM
My map code:

```
<Map
  style={styles.map}
  showsCompass={false}
  initialRegion={INITIAL_REGION}
  showsUserLocation
  ref={this.onMapRef}
  onRegionChangeComplete={this.onRegionChangeComplete}
  onPress={this.onMapPress}
  mapType={IS_IOS ? 'standard' : 'none'}
>
  <Map.UrlTile urlTemplate={this.state.urlTemplate} />
</Map>
```

### Expected Behavior

Google/MapKit shouldn't render or be visible under OSM Tile

### Reproducible Demo
Pls watch the reproducing https://drive.google.com/file/d/1PmDN-DmD2Zc1Knkh1QNJryjUuq0ZJ5rz/view

**Comment by RyanTG** [comment]
You're telling it to show the google map right here: `mapType={IS_IOS ? 'standard' : 'none'}`

`mapType={'none'}` to hide it.

**Comment by systemlevel** [comment]
> You're telling it to show the google map right here: `mapType={IS_IOS ? 'standard' : 'none'}`
> 
> `mapType={'none'}` to hide it.

I can't get this to work for iOS.  Is this only available for Android?  mapType={'none'} not available on iOS?

**Comment by hariDasu** [comment]
@systemlevel you have to set up google maps to replace apple maps as the default for rn-maps, then you can set it to `none`

**Comment by hariDasu** [comment]
alternatively, i got it to work with:

```


import MapView, {
  MAP_TYPES,
  PROVIDER_DEFAULT,
  PROVIDER_GOOGLE,
} from "react-native-maps";


<MapView
     provider={PROVIDER_DEFAULT}
     mapType={MAP_TYPES.NONE}
     //{...otherProps}
/>
```

using the constant` NONE` from the `MAP_TYPES` imported from `react-native-maps`

**Comment by thiphariel** [comment]
To hide the default tiles on MapKit, you have to use the `shouldReplaceMapContent`property to `true`

**Comment by maartenvandillen** [comment]
@thiphariel that sounds like a perfect solution, but I don't see that property in the Typescript types:
````
  export interface MapUrlTileProps extends ViewProperties {
    urlTemplate: string;
    maximumZ?: number;
    zIndex?: number;
    tileSize?: number;
  }
````

**Comment by maartenvandillen** [comment]
@thiphariel that sounds like a perfect solution, but I don't see that property in the Typescript types:
````
  export interface MapUrlTileProps extends ViewProperties {
    urlTemplate: string;
    maximumZ?: number;
    zIndex?: number;
    tileSize?: number;
  }
````

**Comment by CarlQLange** [comment]
It's not on the types, but it does appear to partially fix the issue. However, place labels are still displayed 'underneath', even with both of `mapType='none'` and `shouldReplaceMapContent={'true'}`:

![Screenshot 2020-04-13 at 09 08 44](https://user-images.githubusercontent.com/859820/79104395-69991e00-7d66-11ea-86cd-eedd416e426a.png)

with the code:

```
                        <MapView style={styles.mapStyle} mapType="none">
                            <UrlTile
                                shouldReplaceMapContent
                                urlTemplate={"..."}
                                maximumZ={15}
                            />
                        </MapView>
```

(In my case, my tiles only cover Ireland)

**Comment by Vahradrim** [comment]
> It's not on the types, but it does appear to partially fix the issue. However, place labels are still displayed 'underneath', even with both of `mapType='none'` and `shouldReplaceMapContent={'true'}`:
> 
> ![Screenshot 2020-04-13 at 09 08 44](https://user-images.githubusercontent.com/859820/79104395-69991e00-7d66-11ea-86cd-eedd416e426a.png)
> 
> with the code:
> 
> ```
>                         <MapView style={styles.mapStyle} mapType="none">
>                             <UrlTile
>                                 shouldReplaceMapContent
>                                 urlTemplate={"..."}
>                                 maximumZ={15}
>                             />
>                         </MapView>
> ```
> 
> (In my case, my tiles only cover Ireland)

You should try with shouldReplaceMapContent={true} (not shouldReplaceMapContent={'true'}) otherwise you are assigning a string, not a boolean
