### ISSUE TITLE
Zooming in and out leads to grey tiles with open street map provider

### ISSUE THREAD

**Issue by loustak** [react-native-maps/react-native-maps#2806]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.57.1
react: 16.5.0
react-native-maps: 0.23.0

### Steps to Reproduce

When using another tiles provider with `UrlTile` tiles display correctly. But, when zooming in or out they disappear (become grey) and then re-appear. I tried with two differents tiles server, both from open street map.

To reproduce this issue just use the following code:
``` javascript
import React from 'react'
import MapView, { UrlTile } from 'react-native-maps'

export default class HomeScreen extends React.Component {

  render() {
    return (
      <MapView 
        style = {{ flex: 1 }}
        provider = { "google" }
        mapType = { "none" }
        initialRegion={{
          latitude: 48.862725,
          longitude: 2.287592,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }} 
      >
        <UrlTile urlTemplate = { "https://b.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png" } />
      </MapView>
    );
  }
}
```

### Expected Behavior

I excepted it to works the same as the google map or apple tiles. Like, when you zoom in or zoom out the outdated tiles keep visible until the new one are displayed making no grey are.

### Actual Behavior

Look how the map hide old tiles when zooming in or out instead of keeping them like google maps or apple maps do.

![image](https://media.giphy.com/media/H63OKmsK8HDUjk1LBc/giphy.gif)

### Reproducible Demo

Here is the link to reproduce the problem: https://snack.expo.io/@alexis-luangpraseuth/cmVhY3

(you can zoom in on the emulator with a double tap)

**Comment by johanleroch** [comment]
I have the exact same issue on Android only.

**Comment by johanleroch** [comment]
I have the same issue on both devices.
When setting provider to null, I got the same result on Android but I can see the google map in foreground on iOS (which is not the case when provider="google").
It's a weird behavior.

**Comment by cklinx** [comment]
Same Here.

**Comment by matmedev** [comment]
Hi @lucassardois, I've got the same issue, did you manage to make it any better since then?

**Comment by SabaliauskasLinas** [comment]
Same with WMSTile :(
