### ISSUE TITLE
App crashes on Android 6.0.1 on Samsung S7 when run in release version but works on dev version

### ISSUE THREAD

**Issue by Merikw** [react-native-maps/react-native-maps#2807]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
react-native: 0.59.4
react: 16.6.3
react-native-maps: 0.24.0

Samsung Galaxy S7
Android 6.0.1

### Steps to Reproduce

1. Create react native app.
2. Put a map view inside of a view.
3. Generate a release APK.
4. Run it on a Samsung S7 device with Android 6.0.1

### Expected Behavior
Working like it would work on develop mode (works).

### Actual Behavior
Crashes immediatly when run on the screen

with this:
![afbeelding](https://user-images.githubusercontent.com/17431378/56034683-535a1b80-5d28-11e9-811d-2fcf80e5f4f5.png)

or with an out of memory error:
![error 2](https://user-images.githubusercontent.com/17431378/56076709-63c7d000-5dd4-11e9-9332-ba65bc9ba2f2.png)

### Reproducible Demo

/

**Comment by jramalho** [comment]
Same, PlayStore gives me some memcpy and tgkills backtrace on why the app restarted.

**Comment by christopherdro** [comment]
Fwiw, I just tested a signed APK with a Galaxy S7 running Android 8.0 and didn't come across this issue.
I'll try to get my hands on a device running Android 6 to test further.

**Comment by Merikw** [comment]
> 
> 
> Fwiw, I just tested a signed APK with a Galaxy S7 running Android 8.0 and didn't come across this issue.
> I'll try to get my hands on a device running Android 6 to test further.

Tried it on an Galaxy S7 as well with Android 7.0 and din't get the error either.

**Comment by theohdv** [comment]
I think this is related to last RN versions (58 & 59). They added two CPU architecture type (64 bit cpu).

Looks similar: https://github.com/facebook/react-native/issues/24261

**Comment by radeno** [comment]
@Merikw could you test it on RN 0.59.10? it should be fixed by new JSC

**Comment by abbassiddiqui99** [comment]
reopen this issue facing the same problem with my s5.

**Comment by faz919** [comment]
Seems to still be an issue. Device model is Galaxy J7 Prime
