### ISSUE TITLE
Duration on iOS marker animation not working as expected

### ISSUE THREAD

**Issue by theharness** [react-native-maps/react-native-maps#2816]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.59.1
react: 16.8.2
react-native-maps: 0.24.1

### Steps to Reproduce
```
import Mapview, { AnimatedRegion, Marker } from 'react-native-maps';

getInitialState() {

    return {
    coordinate: new AnimatedRegion({
      latitude: LATITUDE,
      longitude: LONGITUDE,
    }),
  };
}

componentWillReceiveProps(nextProps) {
  const duration = 5000

  if (this.props.coordinate !== nextProps.coordinate) {
    if (Platform.OS === 'android') {
      if (this.marker) {
        this.marker._component.animateMarkerToCoordinate(
          nextProps.coordinate,
          duration
        );
      }
    } else {
      this.state.coordinate.timing({
        ...nextProps.coordinate,
        duration
      }).start();
    }
  }
}

render() {
  return (
    <MapView initialRegion={...}>
      <MapView.Marker.Animated
        ref={marker => { this.marker = marker }}
        coordinate={this.state.coordinate}
      />
    </MapView>
  );
}
```

### Expected Behavior

The animation of the marker should take however long the duration variable is set (in ms).

### Actual Behavior

The animation of the marker does not change from the default value (500ms)

**Comment by gaithoben** [comment]
Any solution to this?

**Comment by victorbatischev** [comment]
I confirm that the code in the example do not works as expected on both platforms: ios and android.

**Comment by gaithoben** [comment]
@victorbatischev can i see your code?

**Comment by victorbatischev** [comment]
> @victorbatischev can i see your code?

Yes, of course. That is it.

`animate() {

    var coordinate = new AnimatedRegion({ // добавим машину исходной точке
      latitude: LATITUDE,
      longitude: LONGITUDE,
      latitudeDelta: 0,
      longitudeDelta: 0,
    });

    var tempMarkers = this.state.markers;

    tempMarkers.push(coordinate);

    console.log(LATITUDE);
    console.log(this.state.markers);

    this.setState({ markers: tempMarkers });

    var newCoordinate;

    for (var i = 0; i < tempMarkers.length; i++) { // передвинем каждую машину

      newCoordinate = {
        latitude: LATITUDE + 
          (Math.random() - 0.5) * (LATITUDE_DELTA),
        longitude: LONGITUDE + 
          (Math.random() - 0.5) * (LONGITUDE_DELTA),
        latitudeDelta: 0,
        longitudeDelta: 0,
      };

      tempMarkers[i].timing(newCoordinate, 5000).start();
    }
  }

{ this.state.markers.map((marker, i) => (
              <Marker.Animated
                ref={component => this.cars[i] = component} key={i}
                coordinate={ this.state.markers[i] }
                flat={true} tracksViewChanges={false}
                // title={marker.title}
                // description={marker.description}
                style={{ width: 25, height: 43 }}>
                <Image source={require('./assets/images/driver_logo.png')}
                  style={{ width: 25, height: 43 }} />
              </Marker.Animated>
            ))}`

**Comment by nicolas-amabile** [comment]
I'm having a similar issue. Initially, I wasn’t using `AnimatedRegion` and I assigned the `coordinate={{ latitude, longitude }}`. That was working fine but without the smooth animation. 
I switched to `AnimatedRegion` but I'm still not able to make the Marker move. `.timing().start` doesn't seem to do anything.

```
const MyMapView = ({ location }) => {
  const markerRef = useRef(null);
  const initialLocation = useRef(location);
  
  useEffect(() => {
    if (Platform.os === 'android') {
      markerRef.current._component.animateMarkerToCoordinate(location, ANIMATION_DURATION);
    } else {
      const timingConfig = { ...location, duration: ANIMATION_DURATION };
      initialLocation.current.timing(timingConfig).start();
    }
  }, [location]);

  return (
    ...
    <MapView ...>
      <Marker.Animated
        ref={markerRef}
        coordinate={initialLocation.current}
      />
    </MapView>
    ...
  );
}
```

Any ideas?

**Comment by owaisnizam** [comment]
Can anyone confirm the resolution for this please 
@gaithoben @victorbatischev

**Comment by owaisnizam** [comment]
Just an update here that i resolved my problem. 
It was not because of an issue in library but my markerComponent was getting re-rendered due to prop updates from map component
I wrapped my marker component in useMemo and changed its dependencies from that prop and it works.
