### ISSUE TITLE
IllegalStateException The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by cihati** [react-native-maps/react-native-maps#2831]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.59.4
react-native-maps: 0.24.0
react: 16.8.3

### Steps to Reproduce

I have read the bug template carefully, but I know of the existence of this bug only in the wild and I have not been able to reproduce it locally. I've gone through all of the similar bug reports and PRs (@shanereid 's https://github.com/react-native-community/react-native-maps/pull/2545 , https://github.com/react-native-community/react-native-maps/issues/2564 , etc), but could not find a solution. Here's how we use `Marker`s:

```
              <Marker
                key={hit.id.toString()}
                coordinate={location}
                tracksViewChanges={false}
                style={markerStyle}
                onPress={onPress}
              >
                <CustomMarker
                  hit={hit}
                  inFocus={inFocus}
                  index={index}
                  price={price}
                />
              </Marker>
```

Here's the stack trace from Sentry:

![image](https://user-images.githubusercontent.com/461998/56737503-7215d480-6762-11e9-915f-6cb8f5fc9de6.png)

I am sorry to not be able to provide a reproducible bug report. Please let me know what I can log to Sentry, so that I can provide more information.

### Expected Behavior

No such errors

### Actual Behavior

Error exists!

**Comment by aravi365** [comment]
Facing the same issue when i tried to display a view inside<MapView>
