### ISSUE TITLE
iOS Marker icon dont behave like Android Marker icon

### ISSUE THREAD

**Issue by jramalho** [react-native-maps/react-native-maps#2834]
### Is this a bug report?
Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes.

### Environment
react-native: 0.59.5
react: 16.8.6
react-native: 0.24.2
Target Platform: All iPhones and Android devices (tested on iPhone: 5c, 6 and XS Android: Moto Z, Moto Z2, Moto e2) 
Map provider: Google maps

### Steps to Reproduce

1. Use Mapview
2. Use Marker inside MapView
3. Use the icon Prop on an image of your assets

### Expected Behavior
The icons should have the same size.

(Write what you thought would happen.)

### Actual Behavior
The icons don't have the same size, to make the icons behave with the same size you need to do something like:

```javascript
ios: PixelRatio.getPixelSizeForLayoutSize(50) / PixelRatio.get(),
        android: PixelRatio.getPixelSizeForLayoutSize(40),
```

**Comment by jramalho** [comment]
SO icon prop don't follow the react-native lifecycle too.
changing the Uri of an icon render the default marker icon, the red pin.
already tried to redraw, and force update().

**Comment by jramalho** [comment]
force update works btw, but it re-render the Marker. performance-wise is bad. but we need to do what we need to do haha

**Comment by vasydragan** [comment]
sane problem here but since issue is opened since may it looks like nobody cares :)
