### ISSUE TITLE
onCalloutPress event not fired for Google maps on iOS

### ISSUE THREAD

**Issue by mark-friedman** [react-native-maps/react-native-maps#2841]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

  Please specify the react, react-native, react-native-maps versions, eg:

    react-native: 0.57.1
    react: 16.5.0
    react-native-maps: 0.22.1

  Target Platform: eg: iOS - 12.1 Simulator/iPhone X

  ***If your target is iOS , please specify if you are using AppleMaps or GoogleMaps

    GoogleMaps

### Steps to Reproduce

(Write your steps here:)

1. Create app with a Google map,  a Marker and an onCalloutPress event handler
2. Click on the Marker
3. Click on the Callout

### Expected Behavior

(Write what you thought would happen.)

That the onCalloutPress event handler would be triggered

### Actual Behavior

(Write what happened. Add screenshots!)

The onCalloutPress event handler as not triggered

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

https://snack.expo.io/@thunkmark/oncalloutpress-test

Make sure you are previewing on iOS.
Click on the marker and then the callout and notice that nothing is logged to the console when you click the callout.

**Comment by jramalho** [comment]
Try the Callout component inside a Marker instead.

**Comment by mark-friedman** [comment]
@jadnco Thanks for the workaround, but for various reasons that's not practical for us.

**Comment by firofame** [comment]
@mark-friedman did you find a fix?

**Comment by mark-friedman** [comment]
@firofame Unfortunately, no.

**Comment by richardbumm** [comment]
Any reason you aren't just using onPress?  This is my onPress function in a callout with a nested custom callout element:
` <Callout
                    onPress={() => this.onCalloutSelected(breweryId)} //Nav to details screen will go here
                >
                    <MapCallout {...brewery} />
                </Callout>
                </Marker>`

**Comment by mark-friedman** [comment]
@richardbumm I am using the `title` and `description` props of the Marker rather than an explicit Callout element.

**Comment by lauyilouis** [comment]
same here

**Comment by firofame** [comment]
Me too

**Comment by vorasudh** [comment]
Any news on this issue?

**Comment by itsam** [comment]
That's still an issue... any updates on this?

**Comment by itsam** [comment]
Using a callout it's quite easy after all, but still this should be considered a bug!

**Comment by mark-friedman** [comment]
I don't quite understand closing the bug just because no one has done anything about it.

**Comment by mark-friedman** [comment]
As before, I don't quite understand closing the bug just because no one has done anything about it.

**Comment by jagthedrummer** [comment]
Still broken despite what stale-bot may think.

**Comment by jagthedrummer** [comment]
And still broken a year later.
