### ISSUE TITLE
componentWillUpdate is deprecated warning in MapView.js

### ISSUE THREAD

**Issue by thekrol01** [react-native-maps/react-native-maps#2843]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

 AppleMaps

### Steps to Reproduce

1. Installed the latest MapView release according to the installation instruction.
2. Build with Xcode 10.2 on physical device iPhone 5.
3. When I want to view the map the following deprecated warning appears:
componentWillUpdate is deprecated etc. with a link to :
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
4. MapView works as expected. 

1. 2. 3.

As expected. 

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jramalho** [comment]
ComponentWillUpdate is a legacy method and will be excluded from React in React 17 (by the docs https://reactjs.org/docs/react-component.html?utm_source=caibaojian.com#unsafe_componentwillupdate), just need to change the logic there to getSnapshotBeforeUpdate and the new region on componentDidUpdate i think.

**Comment by rborn** [comment]
@jramalho fancy a PR ? 🤗

**Comment by Taym95** [comment]
I would like to give this a try!
