### ISSUE TITLE
Polygon holes not working when js debugger off

### ISSUE THREAD

**Issue by ifatihyildirim** [react-native-maps/react-native-maps#2845]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.59.4
react: 16.8.3
react-native-maps: 0.24.2
react-native-maps-super-cluster: 1.5.0

### Steps to Reproduce

1. Use Mapview, ClusteredMapView, Marker and Polygon with holes
2. Use Marker and Polygon inside ClusteredMapView
3. Fetch phone current location
4. Cover the whole world with polygon and draw a holes to phone location

### Expected Behavior

When the debugger is off, the hole must be a hole in a place I want. 

### Actual Behavior

When the debugger is off, it doesn't draw a hole in the polygon. but the hole is only drawning when the debugger is on.

error gif: https://streamable.com/jtf4w

### Reproducible Demo

```
import React, { PureComponent } from 'react';
import { InteractionManager } from 'react-native';
import ClusteredMapView from 'react-native-maps-super-cluster';
import { Polygon } from 'react-native-maps';
import isEqual from 'lodash/isEqual';

import { coverageBorders } from '../../../../library/map';

class Map extends PureComponent {
  constructor(props) {
    super(props);

    this.initialRegion = {
      latitude: props.location.coords.latitude,
      longitude: props.location.coords.longitude,
      latitudeDelta: 0.03,
      longitudeDelta: 0.03,
    };
    this.map = null;
    this.state = {
      data: [],
      currentCoordinates: [
        props.location.coords.longitude,
        props.location.coords.latitude,
      ],
      interactionsComplete: false,
      mapHoles: [],
    };
  }

  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.fetchMoods();

      setTimeout(() => {
        this.setState({ interactionsComplete: true }, () => this.getMapHoles());
      });
    });
  }

  static getDerivedStateFromProps(props, state) {
    const { latitude, longitude } = props.location.coords;

    if (!isEqual(state.currentCoordinates, [longitude, latitude])) {
      return {
        currentCoordinates: [longitude, latitude],
      };
    }

    return null;
  }

  getMapHoles() {
    const coordinates = this.state.currentCoordinates;
    const radius = this.calculateRadius();

    this.setState(prevState => ({ ...prevState, mapHoles: coverageBorders(coordinates, radius) }));
  }


  fetchMoods() { }

  renderMarker = () => { }

  renderCluster = () => { }

  calculateRadius() {
    let radius = this.props.userRadius;

    if (this.props.units === 'miles') {
      radius *= 1.609;
    }
    radius *= 1000;

    return radius;
  }

  render() {
    const { interactionsComplete, mapHoles, data } = this.state;

    if (!interactionsComplete) {
      return null;
    }

    return (
      <ClusteredMapView
        style={{ flex: 1 }}
        data={data}
        initialRegion={this.initialRegion}
        ref={r => (this.map = r)}
        renderMarker={this.renderMarker}
        renderCluster={this.renderCluster}
        showsUserLocation
        showsMyLocationButton={false}
        showsCompass={false}
        moveOnMarkerPress={false}
      >
        <Polygon
          coordinates={[
            { latitude: -89, longitude: -179.99999999 },
            { latitude: 0, longitude: -179.99999999 },
            { latitude: 89, longitude: -179.99999999 },
            { latitude: 89, longitude: 0 },
            { latitude: 89, longitude: 179.99999999 },
            { latitude: 0, longitude: 179.99999999 },
            { latitude: -89, longitude: 179.99999999 },
            { latitude: -89, longitude: 0 },
            { latitude: -89, longitude: -179.99999999 },
          ]}
          key={Date.now()}
          zIndex={100}
          holes={[mapHoles]}
          strokeColor="rgba(0, 0, 0, 0.2)"
          fillColor="rgba(0, 0, 0, 0.4)"
        />
      </ClusteredMapView>
    );
  }
}

```

**Comment by randomBrainstormer** [comment]
I'm having the same issue

**Comment by Off2Race** [comment]
I ran into a similar issue where Circle components won't render with the specified fillColor and strokeColor unless JS debugging is on. If I turn off the debugging, the circle will draw but without the desired color. If I turn the debugging back on, all is fine. 

I realize this is a different problem than this issue but I wanted to mention it in case there's some correlation.

**Comment by randomBrainstormer** [comment]
Issue still present in react-native: 0.60.5 with react-native-maps: 0.25.0

**Comment by randomBrainstormer** [comment]
Is funny, I tried to look in the code for any conditionals indicating if the debugger is ON/OFF, but there seems to be none. I also tried to log/alert the value of `holes` key in the `AIRMapPolygon` component and the component does indeed receive the `holes` parameter, both in the JS and native code and both with the debugger on and off. Not sure why it is simply not rendering the holes when the debugger is off even though the param has a value.

**Comment by rborn** [comment]
This might be a difference between JSCore and V8 (when debugging the code runs actually in chrome which is has the V8 engine )

**Comment by bargald** [comment]
it seems like the problem is with zIndex, I got it to work on RN 0.59.2 and latest react-native-maps without debugger.

**Comment by randomBrainstormer** [comment]
@bargald can you provide more details on this quick fix?

**Comment by bargald** [comment]
> @bargald can you provide more details on this quick fix?

sure.
first of all, I didn't use the example code given by the Author, so I still don't know if that fixes his problem.

I wrote my own code, and showed a polygon with holes on the map. At first I had the same setup as the Author, with zIndex=100 given to the polygon and the error was duplicated, after removing the zIndex property I can see the holes both in release and debug mode.

**Comment by randomBrainstormer** [comment]
@bargald alright! thank you mate! I thought you were removing zIndex from the `<AIRPolygon>` components  🤣 

In my case I didn't have the `zIndex` prop, but I did have `lineDashPattern`, when I removed this prop the holes showed in both, when debugger is on and also when off, in iOS and also Android.

**Comment by bargald** [comment]
@randomBrainstormer awesome, glad it helped
