### ISSUE TITLE
Expose a bearing prop for GoogleMaps <Overlay /> component

### ISSUE THREAD

**Issue by evanAtFetchly** [react-native-maps/react-native-maps#2850]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
"react": "16.8.3",
"react-native": "0.59.3",
"react-native-maps": "^0.24.2",
```
Target: iOS using GoogleMaps

### Steps to Reproduce
Compare the react-native-maps `<Overlay />` API with the Google Maps iOS SDK `GMSGroundOverlay` [API](https://developers.google.com/maps/documentation/ios-sdk/overlays)

### Expected Behavior
Passing a `bearing` prop to the `<Overlay />` component would adjust the bearing of the overlay image on the map. Allowing support for images that are not oriented exactly North/South.

### Actual Behavior
The `<Overlay />` component does not have a `bearing` prop.

### Reproducible Demo
N/A

**Comment by wellmonge** [comment]
I'm up to help @evanAtFetchly
