### ISSUE TITLE
Polygon styling props ignored for Google Maps on iOS

### ISSUE THREAD

**Issue by benjamin-sweney** [react-native-maps/react-native-maps#2867]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: >= 0.51.0
react: >= 16.0.0
react-native-maps: 0.24.0

### Steps to Reproduce

1. Download repository
2. Launch example project for iOS 
3. Switch "Use GoolgeMaps?" to on
4. Go to "Update native props"

### Expected Behavior

The shapes would respect the props (fillColor, strokeWidth, strokeColor etc.) of polygons, circles etc. 

### Actual Behavior

The circle has a black stroke and no fill and the polygon has a blue fill and no stroke. 

### Reproducible Demo

The example project in the repository can be used.

<img width="500" alt="Screen Shot 2019-05-20 at 6 34 44 PM" src="https://user-images.githubusercontent.com/32251097/58000803-f96e2200-7b2d-11e9-8d0b-865dda9959be.png">

**Comment by benjamin-halter** [comment]
Note that using `setNatvieProps` on a timeout on mount eg. `setTimeout(() => ref.setNativeProps(this.props), 1000)` will result in the correct behaviour.

**Comment by rborn** [comment]
Not sure but this might be an outdated example?
I'm doing this and it works fine:

~~~
<Polygon
                style={styles.polygon}
                coordinates={this.props.coordinates}
                holes={this.props.holes}
                strokeColor={strokeColor}
                fillColor={fillColor}
/>

Maybe I don't get the issue?
~~~

**Comment by benjamin-halter** [comment]
@rborn strange... Would it be possible for you to check the example project and get that working? I have the exact same issue in my project as I've shown above. Works fine for everything except GoogleMaps on iOS.

**Comment by rborn** [comment]
@benjamin-halter I created a brand new project and all seems to work fine which makes me thing is an issue with the examples or maybe your settings?

https://github.com/rborn/rn_maps_polygons_test

![Screenshot 2019-05-21 at 11 27 25](https://user-images.githubusercontent.com/406409/58085376-e8202680-7bbc-11e9-8c80-744dad37a343.png)

**Comment by benjamin-halter** [comment]
@rborn thanks for that example! I can confirm this works - I noticed that you used pods to install, I however followed the manual instructions - I will try install with pods and report back the results

**Comment by benjamin-halter** [comment]
I can confirm that installing using CocoaPods removes the issue - may be worth updating documentation/looking into this further. 

Thanks!

**Comment by rborn** [comment]
@benjamin-halter the docs already say how to use pods, but maybe if you feel is not explained enough you can always come with a PR to improve that and I'll happily merge it 🤗

**Comment by benjamin-halter** [comment]
@rborn more than happy with how the docs explain how to use pods, was more referring to highlighting the slight differences as a result of manually installing vs using pods

**Comment by unmec** [comment]
Just run into this, glad to know that manual installation is the cause.

The project was created with ```react-native init``` and ```react-native-maps``` was added with ```react-native link```. The Polygon styling props are lost when enable Google Maps with manual installation process described [here](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md).

Maybe for now we should add a few lines in documentation to let people know about this issue with current manual installation process.

**Comment by jonong** [comment]
Is the only way to use Cocoapods? I'm facing an issue when installing with Cocoapods, where I get errors like `<React/UIView+React.h>` cannot be found. Manual installation works, but I encounter the above issue.

**Comment by EskelCz** [comment]
@benjamin-halter Can you please reopen this? It's still an issue for people who want manual installation.

**Comment by benjamin-halter** [comment]
Reopening as requested by @EskelCz. I would recommend following the Cocoapods route if applicable but agree this is an issue for those that require manual installation.

**Comment by EskelCz** [comment]
Ok I have figured out the workaround, the ref was supposed to be on the overlay shape, not the map. :) and the correct props set to it.

**Comment by aidanw** [comment]
I am using RN 0.60 so only pods install is available.

I still don't see my styles.

I find the pods install instructions a bit unclear. My podfile is here https://github.com/fo-am/iCrapAppPro/blob/master/ios/Podfile I have attempted to merge in the maps things, tho there are differences between the podfile distributed with react native and the one in the installation instructions. 

Have I missed a crucial step?

**Comment by JayHuang** [comment]
for anyone else who may be experiencing this problem and not able to resolve it: downgrading to v0.24.2 worked for us (on RN 0.60.3). We upgraded to react-native-maps 0.25.0 while upgrading to RN 0.60.3, and started having this issue. After much struggling with the problem, we just reverted `react-native-maps` back to v0.24.2 and everything is back to normal and working with RN 0.60.3

**Comment by EskelCz** [comment]
@JayHuang that's strange, because I'm seeing the issue on version 0.24.0, react-native 0.59.3

**Comment by Return-1** [comment]
Same issue here.

Using RN 0.60 so only pods install is available.

**Comment by Dkokkonas** [comment]
I am also facing this but not always . Some times the styles are being applied correctly . I can not find any pattern or scenario to reproduce. 
Using RN:0.60.3 and react-native-maps:0.25

**Comment by kpl39** [comment]
This is what worked for me. 

```
constructor(props) {
  super(props);
  this.circle = React.createRef();
}

<Circle
  ref={this.circle}
/>

<MapView
  onMapReady={() => this.circle.current.setNativeProps({ fillColor: "rgba(r,g,b,a)" })}
/>
```

I'd recommend using the `onMapReady` event over `setTimeout` in `componentDidMount`. Still not ideal though...

**Comment by dcosmin2003** [comment]
I'm also facing this issue. 
Using cocoapods, RN 0.60.3 and react-native-maps@0.25.0.
I have the issue on a Polygon, even if the fillColor is set to green, from time to time it shows purple.

**Comment by Return-1** [comment]
this still remains an issue

**Comment by kyoyadmoon** [comment]
I have the same issue when using Circle component after upgrade react-native-maps to 0.25
I downgrade react-native-maps version to 0.24.2 and it works fine.

**Comment by HerbertLim** [comment]
Suddenly, this issue happened to me.
I am aware of this issue while I upgrade from Expo SDK v33 to v35, where react-native-maps version changes from 0.24.2 to 0.25.0, and react-native version stays at 0.59.
This didn't happen when my app was Expo v33 for months, but this happens when I tried to upgrade from v33 to v35 yesterday. Strangely, this issue remains although I downgrade to Expo SDK v33.

Anyway, I was able to solve this issue by using setNativeProps, recommended by @kpl39. Thanks.

```
constructor(super) {
  this.circle = null; 
}

onMapReady = () => {
  this.circle && this.circle.setNativeProps({ 
    fillColor: 'rgba(0,0,0,0.12)',
    strokeColor: 'rgba(0,0,0,0.3)',
  })
}

render() {
  return (
    <MapView
      ...
     onMapReady={this.onMapReady}
    />
      <MapView.Circle
        center={region}
        radius={distance}
        fillColor={fillColor}
        strokeWidth={0.5}
        strokeColor={strokeColor}
        ref={ref => this.circle = ref}
      />
    </MapView>
  )
}
```

**Comment by sam17896** [comment]
> I have the issue on a Polygon, even if the fillColor is set to green, from time to time it shows purple (the default color).

Same here, but it seems to take correct color once i navigate back to the screen. Not sure how to fix it. Any idea?

**Comment by kerembalcan** [comment]
I had the same issue with Geojson component which uses Polygon as a child component. The styling props wasn't applied for IOS. I also tried given solutions but had a lot of issues with setting the ref and native props onMapReady call.

I solved my issue by having colors in the initial state as **null** and setting them later in the **componentDidMount**.  You can see the example below.

```
import {Geojson} from "react-native-maps";

...

constructor(props) {
  super(props);

  this.state = {
    fillColor: null,
    strokeColor: null,
  };
}

_setColors() {
  this.setState({
    fillColor: 'rgba(60, 165, 255, 0.2)',
    strokeColor: 'rgba(60, 165, 255, 1)'
  })
}

componentDidMount() {
  setTimeout(() => this._setColors(), 10)
}

render() {
  const {geojson} = this.props;
  const {strokeColor, fillColor} = this.state;

  return <Geojson
    geojson={geojson}
    strokeColor={strokeColor}
    strokeWidth={3}
    fillColor={fillColor} />
}

```

**Comment by verochan** [comment]
I'm experiencing the related problem with fillColor, strokeColor and strokeWidth on the project I'm working on with react-native-maps version 0.26.1 , as a temporal fix I applied this solution: https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087

Although, on the project, we have one specific case where it's not working 100% perfect (sometimes it shows the correct styles, sometimes it doesn't), but as temporal fix, we can cope with it... 

Does anybody know if this bug related with Google Maps is already being addressed and an official solution will arrive soon? If I'm not mistaken, this is happening since July 2019 (v0.25.0) :confused:

**Comment by BrianCodeItUp** [comment]
@kerembalcan I tried your solution. But i have to setTimeout for 1 second to make it work.

**Comment by ddarren** [comment]
I opened a #3658 to correct the issue in GeoJson specifically where the stroke color, stroke width, fill color, and marker color properties were not getting preserved. Alternatively, here's a [patch](https://gist.github.com/ddarren/2f2989bf9035308d88cd15d81f8a6d9d) for 0.27.1

**Comment by tgreco** [comment]
This issue still exists on the master branch? I am experiencing it on iOS.

**Comment by jeremyeaton89** [comment]
Adding weight to the fact that this issue is still present on iOS with version 0.28.0 (at least for me!)
