### ISSUE TITLE
Panning around Map and Dragging Pointer Issue

### ISSUE THREAD

**Issue by tyjing** [react-native-maps/react-native-maps#2868]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

```
react-native: 0.55.4
react: 16.3.1
react-native-maps: 0.24.2
Target Platform: iOS - 12.2 Simulator/iPhone Xs, Android 7.0
Using GoogleMaps on both Platform
```

### Steps to Reproduce

Rendered a map with one marker, to see the result for panning around the map and dragging the marker.

1. Dragging marker
2. Panning/Moving around the map

### Expected Behavior

Dragging marker and panning around the map should be smooth and without lagging

### Actual Behavior
![ezgif com-optimize](https://user-images.githubusercontent.com/30327028/58008049-21ee2000-7b1e-11e9-8104-e0b501782fd2.gif)

### Reproducible Demo

Below is my coding look like:
```
<MapView 
   provider={PROVIDER_GOOGLE}
   style={styles.map}
   region={this.state.mapRegion}
   onRegionChange={this.onRegionChange.bind(this)}>
     <MapView.Marker
        draggable
        tracksViewChanges={false}
        coordinate={{
          latitude: (this.state.lastLat) || -36.82339,
          longitude: (this.state.lastLong) || -73.03569,
        }}
        onDragEnd={(e) => {
          console.log(e.nativeEvent.coordinate) 
          this.setState({
            lastLat: e.nativeEvent.coordinate.latitude,
            lastLong: e.nativeEvent.coordinate.longitude,
          })
     }} />
</MapView>
```

**Comment by rborn** [comment]
@tyjing are you in development/debugging mode? Try to see if in release mode it happens the same

**Comment by tyjing** [comment]
@rborn I think it's still the same as I have also archived the app to iOS App Store. 
The lagging issue is still appearing
