### ISSUE TITLE
loadingBackgroundColor has no effect

### ISSUE THREAD

**Issue by Baloche** [react-native-maps/react-native-maps#2870]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
"react": "16.5.0",
"expo": "^32.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz", (0.57.1)
"react-native-maps": "expo/react-native-maps#v0.22.1-exp.0",

Tested on Android

### Steps to Reproduce

1. Use the component MapView with a custom `loadingBackgroundColor`
2. Run the app
3. Drag the view in order to see loading tiles

```jsx
<MapView
    style={{ flex: 1 }}
    loadingBackgroundColor="black"
/>
```

### Expected Behavior

The loading tiles take the color of the specified `loadingBackgroundColor`

### Actual Behavior

The prop `loadingBackgroundColor` seems to have no effect :  the tiles remain light gray when loading.

<img alt="Screenshot 2019-04-16 at 16 10 52" width="536" src="https://user-images.githubusercontent.com/4584879/56212718-42304800-6063-11e9-9f3e-a73632ba676c.png">

### Reproducible Demo

Below is my actual code 

```jsx
<MapView
      loadingEnabled
      showsUserLocation
      loadingBackgroundColor="black"
      loadingIndicatorColor="black"
      provider={null}
      style={{ flex: 1 }}
      initialRegion={initialRegion}
      mapType={Platform.OS == 'android' ? 'none' : 'standard'}
    >
      <MapView.UrlTile urlTemplate="https://tiles.basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}@4x.png" maximumZ={19} />
    </MapView>
```

but it is reproducible with this minimal example :
```jsx
<MapView
      loadingEnabled
      loadingBackgroundColor="black"
      style={{ flex: 1 }}
/>
```

Duplicates of the issue [2814](https://github.com/react-native-community/react-native-maps/issues/2814) (closed because of "NO ISSUE TEMPLATE")

**Comment by rborn** [comment]
My understanding is that `loadingBackgroundColor` is for loading indicator and not for the tiles.
I am not sure we can customize the  initial tiles though.

**Comment by Baloche** [comment]
There is also a `loadingIndicatorColor`. Isn't this property supposed to have the effect you describe ?
Each time I change those two props, I can't see any effect on the UI. I don't know what the indicator is supposed to be. Maybe it isn't yet implemented on Android ?

So if I want to hide those bright flashes when the user moves the map, there is nothing I can do to change the loading background color of the tiles to black ?

**Comment by BojDom** [comment]
Any update ?

**Comment by Smirow** [comment]
Still an issue here. @Baloche did you manage to get it work ?

**Comment by Baloche** [comment]
Nope :/

**Comment by taduyde** [comment]
The same issue.

**Comment by Baloche** [comment]
I think this issue should not be closed

**Comment by Shedav** [comment]
the same issue

**Comment by rodly** [comment]
Any word on this? I don't think any of the loading props work anymore.

**Comment by Baloche** [comment]
This issue still exists

**Comment by zholmes1** [comment]
Make sure you use the prop `loadingEnabled={true}` for these loading props to have an effect.

**Comment by kkx64** [comment]
> Make sure you use the prop `loadingEnabled={true}` for these loading props to have an effect.

This isn't the expected behavior, we have a dark map in our app and it flashbangs users every time it loads in with that white background

**Comment by ayan-shukla** [comment]
> This isn't the expected behavior, we have a dark map in our app and it flashbangs users every time it loads in with that white background

Same behaviour in our app, the map is dark and it flashes white for split seconds while using google maps on IOS. Any remedy here ?

**Comment by simondaigre** [comment]
`loadingEnabled={false}` seems to fix the issue.
