### ISSUE TITLE
Image rotation and overlay on google map

### ISSUE THREAD

**Issue by vikash326** [react-native-maps/react-native-maps#2892]
# Question

How to rotate image and overlay on google map?

I am trying to overlay image on map and its done but image are not exact to coordinate .

I provided top left coordinate and bottom right coordinate

how to set rotation angle of image ?

**Comment by ArnoldoJr** [comment]
Same, image is always set along the parallels. When i provide the leftTopCorner and bottomRIghtCorner coordinates the image gets stretched/shrunk so that it is displayed along the parallels.

**Comment by unjust** [comment]
I definitely need this too, is there a way or a workaround?

**Comment by Msegun** [comment]
Has the rotation feature for overlays been implemented ? 
If not can anyone suggest any workaround?

**Comment by RANAROYG** [comment]
I'm trying to rotate the image, but couldn't able to do so. If possible can anyone give me the hint, how to implement it?
