### ISSUE TITLE
Ability to change 'showsScale' unit ('mi' to 'km')?

### ISSUE THREAD

**Issue by Simek** [react-native-maps/react-native-maps#2894]
# Question

Is it possible to change units of scale component (`mi` to `km`) on Apple Maps (`showsScale` enabled)?

![IMG_6063](https://user-images.githubusercontent.com/719641/58690256-646af480-8389-11e9-9ad0-009392ddfa35.PNG)

**Comment by rborn** [comment]
I think this depends on the systems settings.

**Comment by Simek** [comment]
@rborn I am not so sure about that. On the same device Apple Maps displays `m` and `km` and im my RN app it is `yr` and `mi`.

Apple Maps
![IMG_6388](https://user-images.githubusercontent.com/719641/69864936-4df21700-12a0-11ea-90ee-2e6166f5bef3.jpg)

My RN app
![IMG_6387 2](https://user-images.githubusercontent.com/719641/69864937-4e8aad80-12a0-11ea-8d9c-ce2283662d50.jpg)
