### ISSUE TITLE
Is it possible to remove the small outer circle that appears when using google maps on IOS ?=

### ISSUE THREAD

**Issue by BasilJohn** [react-native-maps/react-native-maps#2896]
# Feature Request
Can we make the user location icon to look similar to how it looks on google maps
I see an additional circle apart from the accuracy circle. 

## Why it is needed'

I opened the google maps app on IOS device and i do not see that additional circle.
Is is possible to provide similar feature or let us know if there is any way to achieve this ?

This is how it looks on the app using react native maps.
Will it be feasible to remove the pointed circle? 
<img width="447" alt="Screenshot 2019-06-04 at 1 25 47 PM" src="https://user-images.githubusercontent.com/9947986/58861841-ee3df900-86cc-11e9-8250-2c611f5e6d72.png">

**Comment by exp8589ert** [comment]
@BasilJohn,

Set "showsUserLocation={false}" prop of MapView to false. Then add a Marker and with Image and coordinate props. There you use custom image.
![Response](https://user-images.githubusercontent.com/18294817/152602452-f2ea28ef-ce59-49e6-9d8c-61df1e53e3f6.PNG)
