### ISSUE TITLE
OSRMRoadManager::getRoad: request failed. working till android oreo, but shows straight line in android pie

### ISSUE THREAD

**Issue by utsab-bbc** [react-native-maps/react-native-maps#2904]
# Bug

It was working fine in android oreo, and still is. but it doesnot work in android pie and i get this error
OSRMRoadManager::getRoad: request failed.

It draws a straight line from point a to point b

The server is working fine, i am getting responses.

![image](https://user-images.githubusercontent.com/35037970/59182837-7cf9bc80-8b8a-11e9-934d-ad08f6f9cf35.png)

**Comment by rborn** [comment]
try to add this is your AndroidManifest.xml

```
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```

**Comment by utsab-bbc** [comment]
i actually did, but it didn't work. Still having the same problem.
