### ISSUE TITLE
zIndex not working for multiple Polylines

### ISSUE THREAD

**Issue by mikedpid** [react-native-maps/react-native-maps#2910]
# Question

Hello, i have multiple polylines on my map. Chances of those polylines overlapping eachother is pretty high, thats why i want to display 'current polyline' on top of the others. I tried with polyline's zIndex prop and with the style attribute as well but it does not work.
It works perfectly on android, but iOS does not take count of the zIndex it seems

```javascript
<MapView.Polyline 
    key={index}
    coordinates={... }
    strokeColor={...}
    strokeWidth={5}
    zIndex={ (50-index) } // this alone works on Android
    style={{ zIndex: (50-index) }} // none of those two work on iOS
    />
```

**Comment by mikedpid** [comment]
Edit: as a quick fix, i did a .reverse() on the array holding the polyline coords to adjust their zIndex that way

**Comment by rborn** [comment]
@mikedpid can we close this then?

**Comment by mikedpid** [comment]
@rborn was hoping to find another fix

**Comment by smallsaucepan** [comment]
Similar question here. Would like to use zIndex with a `<Circle />`. zIndex is marked as Android only in react-native-maps docs, and as expected, does not work.

However, zIndex is supported by Google Maps iOS SDK - https://developers.google.com/maps/documentation/ios-sdk/releases#version_140_-_july_2013

Is that property not being passed through because it used to not be supported on iOS?

**Comment by shuzootani** [comment]
Has anyone found a solution to this issue?

**Comment by usmanhashmi2123** [comment]
A fix that works for me
const setroutesfunc = (routeList , selectedt, selectedRouteIndex) => {
    if(selectedRouteIndex==-1)
    {
      selectedRouteIndex = routeList?.findIndex(item => item.position === selectedt?.position);
      selectedt = routeList[selectedRouteIndex];
    }
    if (selectedRouteIndex !== -1) {
        const routeswithoutSelectedroute = routeList.filter(route => route.position !== selectedt?.position);
        routeswithoutSelectedroute.push(selectedt);
        setRoutes(routeswithoutSelectedroute);
        
        
    }
    else setRoutes(routeList);
};
<MapView
          style={{ flex: 1 }}
          ref={mapRef}
        >
          {origin.latitude!=0.00 && <Marker key={0}
                coordinate={origin}
                pinColor={colors.btnGreen}
                title={"Start"}
                description={mapData.current.start_LatLng}
                draggable={true} 
                isPreselected={false}
                onDragEnd={(e) => getAddress(e.nativeEvent.coordinate, true)}
                />}
          {destination.latitude!=0.00 &&<Marker key={1}
                coordinate={destination}
                pinColor={"red"}
                title={"End"}
                description={mapData.current.end_LatLng}
                draggable={true}
                isPreselected={false} 
                onDragEnd={(e) => getAddress(e.nativeEvent.coordinate, false)}/>}
          {routes?.map((polyline, index) => (
                <Polyline
                key={polyline.position}
                coordinates={polyline.coordinates}
                strokeColor={(selectedRoute?.position===polyline.position)?'#FF0000':'#808080'}
                lineCap="round"
                strokeWidth={4}
                tappable={true}
                zIndex={(selectedRoute?.position===polyline.position)?2.00:0.00}
                onPress={() => { updateMapDataforRoute(polyline), setroutesfunc(routes, polyline, index);}}
                />
            ))}
        </MapView>
        
        I moved the polyline which i want on top  to the end of  array
