### ISSUE TITLE
Custom callout moves to next marker

### ISSUE THREAD

**Issue by Wangor** [react-native-maps/react-native-maps#2922]
![mapissue](https://user-images.githubusercontent.com/1412395/59825597-bffb2300-9334-11e9-866f-fb8f9e22d387.gif)

### Is this a bug report?

Seems to be yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

react-native: 0.59.5
"react-native-maps": "^0.24.2",

### Steps to Reproduce

Created a react native map and used custom callouts. The callouts appear correctly when clicking on a marker... If I move the map and get near to another marker the callout from the previous one is shown

1. 2. 3.

### Expected Behavior

The callout stays over the original marker (or maybe closes)

### Actual Behavior

The callout moves to the next marker

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Wangor** [comment]
Does someone have an idea or a working example? Occures on both, Android and IOS...

**Comment by Wangor** [comment]
Does anyone has an idea? It still occurs

**Comment by bharatchavan-pro** [comment]
@Wangor  got the solution?
