### ISSUE TITLE
Proposal: animateToX functions  should return a promise after the animation is finished

### ISSUE THREAD

**Issue by nabati** [react-native-maps/react-native-maps#2925]
# Feature Request

This it basically a duplicate of https://github.com/react-native-community/react-native-maps/issues/2600, I just didn't want to have it drown out in the comments section. 

Opening this issue to confirm that it's in the right direction of the library before post a PR. 

## Why it is needed

Currently, there's no way to know when the animations have actually finished when updating the camera. 

## Possible implementation

I've checked both the Android code for Google Maps and the iOS code for Apple Maps, and they both seem to provide callbacks for when the animations have finished, so this should not be terribly difficult. 

Android Google Maps animateCamera provides setting a callback, 
https://github.com/react-native-community/react-native-maps/blob/091c237d259e53e84e6be5deea3f3f077aca2e27/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L741
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#animateCamera(com.google.android.gms.maps.CameraUpdate)

iOS Apple Maps animateWithDuration that we are using provides setting a completion block;https://github.com/react-native-community/react-native-maps/blob/091c237d259e53e84e6be5deea3f3f077aca2e27/lib/ios/AirMaps/AIRMapManager.m#L281-L284
https://developer.apple.com/documentation/uikit/uiview/1622515-animatewithduration

iOS Google Maps implementation uses CATransaction and we could use `setCompletionBlock` for the intended behaviour.
https://github.com/react-native-community/react-native-maps/blob/091c237d259e53e84e6be5deea3f3f077aca2e27/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m#L199-L204
https://developer.apple.com/documentation/quartzcore/catransaction/1448281-setcompletionblock

Perhaps the proposed API would be similar to the Animated API where the Promise is resolved with with `finished: bool`. 

Let me know if this would be a desirable fix, if so, I could have a stab at it. 

For our use case, we would only need Google Maps on Android and Apple Maps on iOS, let me know if it's fine to leave out Google Maps on iOS.

**Comment by ezranbayantemur** [comment]
+ 1

**Comment by iamdanil** [comment]
+1
