### ISSUE TITLE
Overlay image quality issues

### ISSUE THREAD

**Issue by rbsmidt** [react-native-maps/react-native-maps#2928]
** EDIT rewrite in issue template **

# Bug

I'm experimenting with using Image Overlay to add a custom image of a building on the map. However it seems the image is downsized and compressed in-app. I've tried with both assets bundled in the build and assets from an external URL, but result seems the same. I've also tried different dimensions of the image - but it doesn't seem to have an effect. See screenshot for example:

<img width="325" alt="Screenshot 2019-06-25 at 21 00 02" src="https://user-images.githubusercontent.com/5921601/60125546-4a57e280-978c-11e9-9231-84272b8caa74.png">
Screen from app (image overlay)

Image original is 2840 × 3003 and a zoom to actual zoom shows much greater detail on the original image. I've tried with and image of 7741 × 8191, but with same result.

So - am i missing an important detail on using image overlay in order to obtain image quality? I've tried replicating the example code from ImageOverlayWithURL and even though it pixelates when zooming in, the images used are 256x256 and seems to have better quality than my tests.
As a follow up - am i using the wrong tool here? Are there a better suited component to achieve this? I've looked through docs and examples and it seems overlay is the one - but maybe i've missed something?

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
      Memory: 108.64 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 21.60s. - ~/.yarn/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

Library version: 0.24.2

## Steps To Reproduce

1) Add react native to clean project
2) Add overlay image using below code snippets
3) Run in simulator

```const { width, height } = Dimensions.get('window')

const ASPECT_RATIO = width / height

const LATITUDE = 55.669540
const LONGITUDE = 12.562031
const LATITUDE_DELTA = 0.01
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO

// const OVERLAY_TOP_LEFT_COORDINATE = [55.671319, 12.559694]
const OVERLAY_TOP_LEFT_COORDINATE = [55.670564, 12.561036]
// const OVERLAY_BOTTOM_RIGHT_COORDINATE = [55.668548, 12.564339]
const OVERLAY_BOTTOM_RIGHT_COORDINATE = [55.668695, 12.564202]

const IMAGE_URL = '<external-image-url>' // Should be remote image with consistent aspect ratio
```
[...]
```  
state = {
    region: {
      latitude: LATITUDE,
      longitude: LONGITUDE,
      latitudeDelta: LATITUDE_DELTA,
      longitudeDelta: LONGITUDE_DELTA,
    },
    overlay: {
      bounds: [
        OVERLAY_TOP_LEFT_COORDINATE,
        OVERLAY_BOTTOM_RIGHT_COORDINATE,
      ],
      image: IMAGE_URL,
    },
    imageFetched: false,
  }
```
[...]
```    return (
      <View style={styles.flex}>
        <MapView animateCamera={ camera } style={styles.map} initialRegion={ this.state.region } >

          { brandMarker }

          {
            this.state.imageFetched
            ? <Overlay pointerEvents="none" style={styles.overlay} bounds={this.state.overlay.bounds} image={this.state.overlay.image} zindex={2} />
              : null
          }

        </MapView>
      </View>
    )
```

**Comment by rborn** [comment]
Please update the issue following a suitable template or I'll close it.

**Comment by rbsmidt** [comment]
@rborn All right, i've edited my original post to match the bug template. Wasn't originally sure if i'm reporting a bug or i'm doing something wrong in the process of adding the overlay.
Hope the issue is better described now, if not let me know, and i'll give another try!

**Comment by rborn** [comment]
did you try to name your image `@2x` `@3x` ?

**Comment by rbsmidt** [comment]
@rborn It definitely gets me somewhere adding `@2x` and `@3x` and experiencing with resolution of the images. However i get some wierd artifacts in parts of the image (see screenshot). Looks like only part of the image is finished loading. Any suggestions what could cause this behaviour?

<img width="321" alt="Screenshot 2019-06-28 at 11 53 28" src="https://user-images.githubusercontent.com/5921601/60334363-a2186880-999b-11e9-8c25-3605578f80cf.png">

**Comment by rborn** [comment]
nope :(

**Comment by EgorKazachenko** [comment]
Hi @rbsmidt ! I've the same issue :( Did u find any solution ?

**Comment by rbsmidt** [comment]
@EgorKazachenko i ended up using MapBox instead. That worked out great though, and setup is somewhat similar to native maps.
