### ISSUE TITLE
Use Google Maps API-Key dinamically, instead of hard coded on XML file

### ISSUE THREAD

**Issue by rafaelfndev** [react-native-maps/react-native-maps#2938]
# Feature Request

Add option to use API-Key dinamically, instead of hard coded on XML file.

## Why it is needed

Sometimes we need to change "Google Map API-Key" dinamically.

## Possible implementation

The app is the same for many clients, but each client have different features enabled on the app based on purchased on panel, one of them is the feature to use map. If client pay to use features based on map, one "Google Map API-Key" is generated to this client, so if this client are using map on app, the backend send your on "Google Map API-Key" dinamically to render map on app.

### Code sample

I know that probably is not simple to implement, but the idea to use is something simple like this:

```javascript
<MapView
    region={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    }}
    apiKey='AIzaSy....................._qYJeP1Uyzj2vB'
/>
```

**Comment by nabati** [comment]
As far as I am aware, there are no native APIs to allow setting the API-key programmatically, so this seems unlikely to be implemented.

**Comment by Eesssn** [comment]
@nabati how to implement API_KEY in expo and react-native v 0.60.
there is no android directory and manifest to set.

**Comment by pke** [comment]
@Eesssn they probably generate the manifest during build. The Google API key has to be packaged resource, that's why you can't set it programmatically.
