### ISSUE TITLE
Marker doesn't animate on Release/Production Mode. It works well on Development Mode

### ISSUE THREAD

**Issue by Yingi** [react-native-maps/react-native-maps#2953]
I realised that I am unable to animate marker to coordinate in production mode. It works perfectly during development. 

For some reasons the screen even hangs when the function is called to animate marker. Any help is urgently needed.

Here is the piece of code that I used to animate marker

`animate(loc) {
        const { coordinate} = this.state;
        const newCoordinate = {
          latitude: loc[0],
          longitude: loc[1],
        };

        const region = {
            ...newCoordinate,
                  latitudeDelta: LATITUDE_DELTA,
                  longitudeDelta: LONGITUDE_DELTA        
                };

     const duration = 1500  
this.marker._component.animateMarkerToCoordinate(newCoordinate, duration);
}`

**Comment by rborn** [comment]
@Yingi please update the issue with the template or I'll close it.
