### ISSUE TITLE
TypeError undefined is not an object (evaluating 'this.map.setNativeProps')

### ISSUE THREAD

**Issue by Jense5** [react-native-maps/react-native-maps#2958]
# Bug

We see this bug showing up in Sentry, but haven't been able to reproduce it ourselves. It's only occuring in a small percentage of our userbase, but occured about 275 times. It looks like the map ref isn't checked before calling methods in `_onMapReady`, so I think these refs should be checked before we use them? This issue only occurs on Android.

Stacktrace on Sentry: https://sentry.io/share/issue/c6af900e656a4c2f91f027ff3075fef4/

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 99.61 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
```

Library version: 0.24.2

## Steps To Reproduce

Unable to reproduce by following specific steps, but I guess it happens when `_onMapReady` is called before the `this.map` is set.

## Reproducible sample code

Unable to reproduce by following specific steps.

**Comment by NguyenPhuong1907** [comment]
I have encountered the same error in IOS and ANDROID,

**Comment by Sanan4li** [comment]
Same Error. Any solution ?

**Comment by CVRamana** [comment]
same error in iOS and android ,
any solution??

**Comment by lucasluca** [comment]
I dont know yet, but maybe is something related to use animateToRegion before onMapReady is called

**Comment by lucasluca** [comment]
i just removed initialRegion and Region from my map props and i Use map reference to make animateToRegion when onMapReady callback is called, this seems to resolve this issue.

**Comment by Anuj-logiciel** [comment]
Any Solutions please?

**Comment by TrejGun** [comment]
same here

**Comment by ketanbhardwaj** [comment]
@Jense5 Same error still exists after more than year of opening this ticket. Do we have any solution to this?

**Comment by ketanbhardwaj** [comment]
Please check the screenshot

![Simulator Screen Shot - iPhone 11 - 2020-10-08 at 03 05 22](https://user-images.githubusercontent.com/2696831/95390530-25509a00-0913-11eb-82b9-92003282948d.png)

**Comment by morph3ux** [comment]
same here

**Comment by arryanggaputra** [comment]
I solved this by manually install this package. Open your `Podfile`, below `use_react_native` add this line. And run `pod install`

```
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

```

**Comment by akkravikumar** [comment]
> I solved this by manually install this package. Open your `Podfile`, below `use_react_native` add this line. And run `pod install`
> 
> ```
>   rn_path = '../node_modules/react-native'
>   rn_maps_path = '../node_modules/react-native-maps'
> 
>   # react-native-maps dependencies
>   pod 'react-native-maps', path: rn_maps_path
>   pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
>   pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
>   pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
> ```

this line is not required -> **pod 'react-native-maps'**


  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'`

**Comment by KritR** [comment]
If anyone's facing this during development, for me it was enough to run the npx pod-install and rebuild via yarn run ios. It appears the native components weren't linked for my build at the time.

**Comment by TrejGun** [comment]
ping

**Comment by salmank888** [comment]
any solution

**Comment by salah-ghanim** [comment]
@TrejGun @salmank888 this doesn't seem to be an issue with the latest version of the SDK / react native. please make sure your project is configured properly. if so please provide exact details of the bug.

**Comment by javiercr** [comment]
We're experiencing the same issue, Android only and running the latest react-native (`v0.63.4`) and `v0.26.1` of react-native-maps (but according to the changelog, there hasn't been any change related to this in the latest (`v0.27.1`).

In our case we're just drawing a map with a circle on it:

```jsx
<MapView
  zoomEnabled={true}
  maxZoomLevel={15}
  rotateEnabled={false}
  scrollEnabled={true}
  pitchEnabled={false}
  toolbarEnabled={false}
  provider="google"
  region={{
    latitude,
    longitude,
    latitudeDelta: 0.02,
    longitudeDelta: 0.02,
  }}
>
  <MapView.Circle
    center={{
      latitude,
      longitude,
    }}
    radius={500}
    strokeColor={Colors.orange}
    fillColor={Colors.orangeTransparent}
  />
</MapView>
```

So we're not doing anything with the map ref, it must be the library itself which is trying to set the region before the map is actually ready 🤔 .

**Comment by javiercr** [comment]
Apparently our problem with react-native-maps was caused by another JS crash. The app would crash for something else, and it seems that would cause react-native-maps to not finish rendering the map properly, leading to this error, and for some reason the final error we ended up seeing in our bugtracker was the react-native-maps one, not the other one.

After solving the other problem (not related to react-native-maps), everything works fine.

**Comment by salah-ghanim** [comment]
thanks for clarifying @javiercr this issue will be closed for now.

**Comment by archanashokeeniitg** [comment]
Still, this bug is prevalent even after an year.
Error:  TypeError: undefined is not an object (evaluating 'this.map.setNativeProps')
<img width="318" alt="Screen Shot 2021-03-10 at 5 46 53 PM" src="https://user-images.githubusercontent.com/66199202/110723471-f2b01380-81c8-11eb-81f5-0af2919fa8c2.png">


I'm just trying to pull a basic map.
Code : 
` <MapView
        style={{height: 100, width: 100}}
        provider={PROVIDER_GOOGLE}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />` 
all versions are up to the requirements. what is the solution?

**Comment by javiercr** [comment]
@archanashokeeniitg noticed that in that screenshot the title says "Log 5 of 6", so you may have other errors that are causing the map to not be rendered. This exactly what was happening to us. Make sure to fix the other 5 errors / warnings and perhaps that will fix the one regarding react-native-maps.

**Comment by enesbildiren95** [comment]
@archanashokeeniitg Remove "provider={PROVIDER_GOOGLE}" and run. I think, problem is 'provider' prop.

**Comment by meliodev** [comment]
> @archanashokeeniitg Remove "provider={PROVIDER_GOOGLE}" and run. I think, problem is 'provider' prop.

If you remove provider, you will use apple map instead of google maps.

**Comment by ziggear** [comment]
> pod 'react-native-maps', path: rn_maps_path

Same problem, it works for me.

**Comment by nghiadqdev** [comment]
> @archanashokeeniitg Remove "provider={PROVIDER_GOOGLE}" and run. I think, problem is 'provider' prop.

it fixes this problem but my boss still wants to use a map of google
