### ISSUE TITLE
Fresh react-native project (0.60.0) fails to build with react-native-maps and tipsi-stripe installed (DexArchiveBuilderException: Failed to process C:\....gradle\caches...\classes.jar)

### ISSUE THREAD

**Issue by dancherb** [react-native-maps/react-native-maps#2961]
# Bug

A fresh React-Native project at 0.60.0 with react-native-maps on the latest version (0.25.0) and tipsi-stripe (https://github.com/tipsi/tipsi-stripe) on the latest version (7.5.0) fails to build with the following error. A fresh project with either package on its own seems to work fine.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\cherb\.gradle\caches\transforms-2\files-2.1\8e9a36921623b25c921be84cb9af8f17\jars\classes.jar
```

There's quite a lot of warnings and errors on the way - full log here:
https://pastebin.com/Q7TY6UWm

## Environment info

React native info output:

```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 707.21 MB / 7.82 GB
  Binaries:
    Node: 10.15.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\Users\cherb\AppData\Roaming\npm\watchman.EXE
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
```

Library version: 7.5.0

## Steps To Reproduce

1. `react-native init BugDemo --version react-native@0.60.0`
2. `cd BugDemo && npm install --save tipsi-stripe react-native-maps`
3. Add `maven { url "https://jitpack.io" }` to the root build.gradle in `allprojects { repositories { ...` (for tipsi-stripe)
4. `npm i && react-native run-android`

Describe what you expected to happen:

1. The project builds smoothly and I have an amazing day

## Reproducible sample code

On the way.

**Comment by steubs** [comment]
Exact same issue here. I just migrated to androidX

**Comment by mikebouwmans** [comment]
Same issue for me upgrading to react 0.60.4

**Comment by steubs** [comment]
@mikebouwmans I fixed the maps error with this here: https://github.com/react-native-mapbox-gl/maps/issues/163

Still haven't fixed the tipsi issue, haven't had a chance to get around to it yet, but I imagine the solution is something similar.

**Comment by dancherb** [comment]
> 
> 
> @mikebouwmans I fixed the maps error with this here: [react-native-mapbox-gl/maps#163 (comment)](https://github.com/react-native-mapbox-gl/maps/issues/163#issuecomment-511542096)
> 
> Still haven't fixed the tipsi issue, haven't had a chance to get around to it yet, but I imagine the solution is something similar.

Both maps and tipsi stripe seem to work fine independently, only breaking in combination - is this the issue you're referring to?

**Comment by steubs** [comment]
Sorry that comment very wasn't clear. I was just referring to the fact that I was able to fix the issue for react-native-maps, but I haven't had the chance to work on the tipsi-stripe issue yet, so I don't know if that fixes that particular issue. And from what I remember (it's been a few weeks) the issues that affect both those dependencies looked related not migrating to androidX correctly. 

Are you able to get react-native-maps or tipsi-stripe to work independently? Or is the combination what's breaking for you?

**Comment by steubs** [comment]
Ah for me neither worked independently. 

I'll be trying to integrate tipsi again into my app this weekend so I'll update if I run into the issue or if it works for me.

**Comment by jezzdk** [comment]
@steubs Did it work?

**Comment by stevenheffner** [comment]
@jezzdk This worked for me

https://github.com/tipsi/tipsi-stripe/issues/504#issuecomment-518992108
