### ISSUE TITLE
how to move cars smoothly with socket? i have attached gif file please look (Question and help)

### ISSUE THREAD

**Issue by aliwaqassi** [react-native-maps/react-native-maps#2970]
# Question
i want to make like this please help any one

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/19648354/61513348-4418f700-aa16-11e9-8d93-abee8179b597.gif)

**Comment by pavilion** [comment]
This is not an issue, so please post it on SO, not here

**Comment by aliwaqassi** [comment]
@pavilion dear i know that is not bug, when i was add this i get started with question and help, so i need help

**Comment by pavilion** [comment]
@aliwaqassi if you need help post it on StackOverflow, issues are meant to be bugs, new features, etc... please close this and open it on StackOverflow.
