### ISSUE TITLE
Show user beam

### ISSUE THREAD

**Issue by lyudad** [react-native-maps/react-native-maps#2976]
# Question
In google maps user location shown as blue dot with beam. I can find how repeat same behavior.  Sometimes location dot have direction arrow, but it appear time to time
This is what I need to have V
<img width="580" alt="Снимок экрана 2019-07-24 в 12 29 01" src="https://user-images.githubusercontent.com/25103090/61782400-a6a33600-ae0e-11e9-8f53-b1e2f15f27c9.png">

**Comment by ignitebhdeveloper** [comment]
i guess you can custom marker by creating png with a beam and use marker rotation.

**Comment by CrisHemswerthThor** [comment]
I am also getting through it and it is really frustrating. In my case it is shown in IOS but not on android.
Is there any update on this issue?
