### ISSUE TITLE
I can't sync gradle on Android after upgraded to react-native 0.60

### ISSUE THREAD

**Issue by fouad1994** [react-native-maps/react-native-maps#2979]
I am getting these errors
![WhatsApp Image 2019-07-25 at 12 23 25 AM](https://user-images.githubusercontent.com/35866405/61830337-91acbe00-ae73-11e9-82bf-570da2215d35.jpeg)

This image has one line but the error is multi line like before one
![WhatsApp Image 2019-07-25 at 12 23 24 AM](https://user-images.githubusercontent.com/35866405/61830338-91acbe00-ae73-11e9-8a42-763f5fe496d3.jpeg)

I hope to get somehelp

**Comment by funkyfourier** [comment]
Have you tried running `npx jetify`? If I recall correctly that did the trick.
