### ISSUE TITLE
<WMSTile> - accommodate tile servers that require authentication

### ISSUE THREAD

**Issue by 100phel** [react-native-maps/react-native-maps#2987]
# Feature Request
Enhance `<WMSTile>` so that it can accept the `headers` property.

## Why it is needed
  Right now we can only supply a `urlTemplate` property to `<WMSTile>`. The tile server I'm using requires authentication header to be sent with the GET request.

## Possible implementation
  We could pass a `headers` property to `<WMSTile`> along with urlTemplate.

### Code sample
  ```javascript
<WMSTile
    urlTemplate="https://geoserver-url.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:LC08_L1TP_148023_20190104_20190130_01_T1_Clarity_compressed&styles=&bbox={minX},{minY},{maxX},{maxY}&width={width}&height={height}&srs=EPSG:4326&format=image/png&transparent=true"
    headers={[
        {
            Authorization: 'encoded key'
        }
    ]}
/>
```

**Comment by 100phel** [comment]
> @100phel can you please update the issue following the feature request template?

Done.

**Comment by 100phel** [comment]
Any update on this?

**Comment by gghnisan** [comment]
+

**Comment by gghnisan** [comment]
I fixed the react-native-maps library and added headers.
It works like this: 
```
<MapUrlTile 
        urlTemplate={'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png'}
        headers={
            {
                Authorization: 'Basic xxxxxtokenxxxxx'
            }
        } 
/>
```
**npm install @gghnisan/react-native-maps
npm link @gghnisan/react-native-maps**


I changed the following files:
1. com.airbnb.android.react.maps.AirMapUrlTile
2. com.airbnb.android.react.maps.AirMapUrlTileManager
3. lib.components.MapUrlTile.js
4. index.d.ts

**Comment by 100phel** [comment]
What about iOS?

**Comment by gghnisan** [comment]
I have never worked with ios, unfortunately.

**Comment by AMAISGOD** [comment]
Hi
we need it on iOs Please, guide us
thank you

**Comment by sahil16r** [comment]
Does anyone have another solution for integrating WMS Layers with Authentication headers?

**Comment by gghnisan** [comment]
@sahil16r  it is not in the repository.

look in npm:

`          //connection.addRequestProperty("Authorization", "Basic xxxxxxxxxxxxxxx-token");
          for (Map.Entry<String, Object> entry : requestProperties.toHashMap().entrySet()) {
            connection.addRequestProperty(entry.getKey(), (String) entry.getValue());
          }`

**Comment by sahil16r** [comment]
@gghnisan thank you 👍

**Comment by rokamon1997** [comment]
@gghnisan 

Hello, I did a fork similar to your fix for the latest version of react-native-maps (v1.7.1) but when I check on backend no authorization header seems to be included in the request.

Is there any additional step you have to do after changing the .java files (ex. like build something)? I'm using expo and I have been testing with both ExpoGo app and with a built .apk on my device.

**Comment by gghnisan** [comment]
Hello.

I'm not sure about Expo. Read the difference between Expo and React Native here:

https://stackoverflow.com/questions/39170622/what-is-the-difference-between-expo-and-react-native

In the new version of react-native-maps, they refactored the code, possibly moved part of the code to other files or classes. 
I see that they removed this file: AirMapUrlTile.
Most likely they moved this code here: MapTileProvider.java.  
Method: byte[] fetchTile(int x, int y, int zoom) {...}
Look here:
https://github.com/react-native-maps/react-native-maps/blob/673e9d21212442af9795cc21a17bf477623c458b/android/src/main/java/com/rnmaps/maps/MapTileProvider.java#L347

Here
https://github.com/react-native-maps/react-native-maps/blob/673e9d21212442af9795cc21a17bf477623c458b/android/src/main/java/com/rnmaps/maps/MapTileProvider.java#L347
add this code:

```java
//connection.addRequestProperty("Authorization", "Basic xxxxxxxxxxxxxxx-token");
for (Map.Entry<String, Object> entry : requestProperties.toHashMap().entrySet()) {
       connection.addRequestProperty(entry.getKey(), (String) entry.getValue());
}```

Here 
https://github.com/react-native-maps/react-native-maps/blob/master/android/src/main/java/com/rnmaps/maps/MapUrlTileManager.java
add this code:

```java
@ReactProp(name = "headers")
  public void setRequestProperties(AirMapUrlTile view, ReadableMap headers) {
    view.setRequestProperties(headers);
  }
```

Make sure you add the changes to the correct class in the correct place. Your best bet is to run the Intellij idea in the debugger and set a breakpoint at the point where the JavaScript request comes in. Run the map and you will see where the breakpoint is. For java debugging in react-native-maps you can use Android Studio or Intellij idea.
