### ISSUE TITLE
Marker Clustering

### ISSUE THREAD

**Issue by Return-1** [react-native-maps/react-native-maps#2992]
# Feature Request

Currently marker clustering only seems to be handled by third party libraries who handle clustering on the javascript level.

## Why it is needed

Driving forces to suggest adding clustering to this project are

a) **Performance:** Multiple markers ( not too many either, nearing 100 ) cause significant performance issues as is. The available options for clustering that work on the javascript level aren't very performant
b) **Native feel:** The above being the only option and having a lack of animations makes it very painfully clear that the application is far from native.
c) **Stability:** Resorting to a third party library for clustering does introduce some uncertainty.

## Possible implementation & code sample

I am unfamiliar with the specifics of this implementation but i imagine in terms of the API provided, a `<Clusterer>` component wrapping the markers would be the best approach. Even at its most basic form it would be immensly useful.

**Comment by StefKors** [comment]
yes! this would be amazing

**Comment by Return-1** [comment]
This might be my biased opinion but i spoke with a few other developers about the map solutions they use on React Native. Im willing to put this to a poll to highlight the importance of this because clustering seems to be the number one reason they dont use react-native-maps and will instead move to things like mapbox.

I think had my clients not specifically requested google maps i would have opted for that as well - though i have no personal experience with it -

**Comment by StefKors** [comment]
it also just seems like a logical feature to have in a maps package. Is there anyway I could help to get this feature built?

**Comment by Return-1** [comment]
> see: https://github.com/novalabio/react-native-maps-super-cluster

we're aware this exists. however this is not a native implementation of clustering which leaves out a lot. aside from the performance suffering significantly, things such as animations are missing making everything feel very.. web

**Comment by ming436534** [comment]
I have implemented that in native ways in both android and ios, but I don't have enough time to refine it so I may not submit a merge request. You guys can check out my repo. Just call addClusterItems and removeClusterItem to add and remove markers.

doc: https://github.com/ming436534/react-native-maps/blob/marker_clustering/docs/mapview.md

https://github.com/ming436534/react-native-maps/tree/marker_clustering

**Comment by lamyuho** [comment]
@ming436534 may I know how to enable `GOOGLE_MAPS_UTILS in ios` please many thank

**Comment by ming436534** [comment]
First, following the [doc](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md) to install react-native-maps with google map and Google-Maps-iOS-Utils. And then if error occurs, add these macros to preprocessing macro in xcode.
HAVE_GOOGLE_MAPS=1
HAVE_GOOGLE_MAPS_UTILS=1

**Comment by TZK-** [comment]
Any news about that request ? Anything planed ?

**Comment by Return-1** [comment]
not on our side. we're migrating to MapBox as this package has proven to be very problematic in more than one ways for us especially on iOS

**Comment by StefKors** [comment]
I had significant performance improvements by setting `shouldComponentUpdate` to false on map markers and the mapview. Doing this has made it unnessesairy to use mapclusters even when having +450 markers. It seems like every prop is rerenderd when doing anything with the map.

**Comment by itsam** [comment]
> I had significant performance improvements by setting `shouldComponentUpdate` to false on map markers and the mapview. Doing this has made it unnessesairy to use mapclusters even when having +450 markers. It seems like every prop is rerenderd when doing anything with the map.

Can you please share how you set shouldComponentUpdate () {return false} for each marker?
Thank you in advance

**Comment by StefKors** [comment]
Yes, @itsam that's correct, I had a custom marker wrapper for the map marker. Also have a look at the `tracksViewChanges` prop it might be helpful also.

**Comment by markymc** [comment]
@ming436534 Thank you very much for sharing your fork. I'm very interested in using it. I'm sorry to trouble you, but I was wondering if you might be able to share a little info/example code snippets of how to make use of `addClusterItems`? I'm having trouble working it out. Thanks in advance! 🙇 In return, perhaps I could assist with turning it into a PR?

**Comment by markymc** [comment]
As an update in case it's useful for anyone else, I had trouble getting `require()`'d image assets working for the icon property of the objects I was passing to `addClusterItems()`. I just learned that I could use `Image.resolveAssetSource(require('asset_path')).uri` that seems to work nicely.

Thanks again for sharing your clustering work, @ming436534! I may be making some changes to make it more configurable, so I'll let you know if/when that happens in case you want to make use of it. :)

**Comment by rborn** [comment]
Adding part of the conversation with @hussainahmad to be able to clean the maintainer's issue 
![Screenshot 2020-09-30 at 15 01 35](https://user-images.githubusercontent.com/406409/94688502-fdb76b80-032d-11eb-9df2-d1ae6d52fa55.png)

**Comment by danieldanielecki** [comment]
bump, we've to use https://github.com/venits/react-native-map-clustering in order to achieve the functionality
