### ISSUE TITLE
Zoom very large when call fitToCoordinates - how to manipulate it

### ISSUE THREAD

**Issue by komal1212** [react-native-maps/react-native-maps#2996]
# Question

**Comment by rborn** [comment]
empty issue, closing

**Comment by komal1212** [comment]
why closing this issue

**Comment by rborn** [comment]
is empty, please add more details and I'll re-open it

**Comment by komal1212** [comment]
openSearchModal() {
    RNGooglePlaces.openAutocompleteModal()
    .then((place) => {
     
      const marker = {
        latitude: place.location.latitude,
        longitude: place.location.longitude,
       // latitudeDelta:5,longitudeDelta:5,     
       };
      const region = Object.assign(

        {}, marker, { latitudeDelta:0.8, longitudeDelta: 0.5},

      );
     
      const address ={
        address:place.address
      }
      
      this.setState({place:place,marker,region,address})
     
      this.map.fitToCoordinates([{latitude:place.location.latitude, longitude:place.location.longitude,
       
      }], {
     
        edgePadding: DEFAULT_PADDING,
        animated: true,
      });
    })
  
   }


This is my code in this edgepadding is: const DEFAULT_PADDING = { top: 40, right: 40, bottom: 40, left: 40 };

**Comment by richardbumm** [comment]
Can you include a screenshot? A delta of 0.8 is actually pretty large.

**Comment by komal1212** [comment]
![Screenshot_1565097654](https://user-images.githubusercontent.com/52229170/62543642-eee53e00-b87b-11e9-81fb-f6bf70579576.png)
 this is screenshot of map which show location of searchbar.but map large to much .and i want to increase map zoom level and also circle radius on slider value change

**Comment by richardbumm** [comment]
So reduce your delta.  I really have no idea what's being asked here
