### ISSUE TITLE
Change position of Markers

### ISSUE THREAD

**Issue by Dr1992** [react-native-maps/react-native-maps#3004]
# Question

I would like to know if it's possible to change position of marker moving map and not dragging the marker point because that way is the most common that we can see in the apps.

For example: Uber, iFood.

**Comment by smallsaucepan** [comment]
You want the map to remain still and have the marker move automatically, like the cars moving in the Uber app? Would updating the `coordinate` prop on the Marker meet your needs?

**Comment by anastely** [comment]
can I achieve [this](https://drive.google.com/file/d/1-lOslN5-cwKfcxTrBXeVOj6-NqxSJ-_P/view) with RN-maps?

**Comment by djpetenice** [comment]
I'm looking for the same functionality. I have a map that gets your current location and shows a marker - when I then pan the map I want the marker to centre to the current region. I've been playing around with onPanDrag and OnRegionChangeComplete but I can't really get this to work.

Anyone have a solution for this?
