### ISSUE TITLE
Android "elevation" style property doesnt work on map Callout

### ISSUE THREAD

**Issue by udielenberg** [react-native-maps/react-native-maps#3006]
# Bug
Adding `shadow` style property onto a `View` inside `Callout` component doesnt work.
![Screen Shot 2019-08-06 at 12 31 30](https://user-images.githubusercontent.com/39482108/62528881-423c9980-b846-11e9-83bf-d38e0eafd3d9.png)

## Environment info
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.75 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3 
    react-native: 0.60.3 => 0.60.3
    **"react-native-maps": "~0.25.0",**

## Steps To Reproduce

1. Create a `Callout` component with a View container
2. Add styles 
```
const styles = {
   ...
   elevation: 2
}
```
...

Describe what you expected to happen:
Expecting a shadow around the `Callout`

## Reproducible sample code
```
return (
    // @ts-ignore
    <Callout alphaHitTest tooltip>
      <View style={styles}>
        <View>
          <View>{children}</View>
        </View>
      </View>
    </Callout>
```

**Comment by antonioreyna** [comment]
i am trying to add a shadow to the callout but it gets cut, were you able to fix this?

**Comment by juandiegombr** [comment]
I have the same problem on Android with the elevation property. Every element in the Callout component doesn't respond to 'elevation'.

@antonioreyna To avoid the shadow from being cut, I have added a padding to the callout wrapper.

```
<Callout tooltip style={{ padding: 4 }}>
    <CustomCalloutWithShadow/>
</Callout>
```

**Comment by Martin2912** [comment]
Hi, I have the same problem. I am trying to add a shaddow to my callouts on mapView (on an Android device) and it doesn't work. If someone has a solution it would be great :)

**Comment by Eden-Eliel** [comment]
Same here, i would love if someone have a solution  or some kind of a workaround

**Comment by manishsainju** [comment]
+1

**Comment by hugorezende** [comment]
+1

**Comment by Kjagd** [comment]
Also seems to have a similar issue with elevation on a custom Marker
