### ISSUE TITLE
Event to listen for when showsMyLocationButton button is pressed

### ISSUE THREAD

**Issue by smallsaucepan** [react-native-maps/react-native-maps#3009]
# Question

Hi everyone. I'd like to be able to run some code when the show my location button / center on user's location button is pressed. An onRegionChangeComplete is fired, though there's nothing to indicate whether this was initiated specifically by the show my location button.

Have experimented with onPress, however the default control displayed by showsMyLocationButton seems to swallow that.

I suspect this isn't possible, and I will have to roll my own location button: https://issuetracker.google.com/issues/35822333

Thought it worth asking in case others have the same problem and are looking in to it.

**Comment by ehsanbigzad** [comment]
Hi @smallsaucepan could you find any solution?
