### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_AIRGoogleMapWMSTile for x86_64 Architecture

### ISSUE THREAD

**Issue by deepankarsandy** [react-native-maps/react-native-maps#3010]
# Bug
### error
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AIRGoogleMapWMSTile", referenced from:
      objc-class-ref in AIRGoogleMap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`Undefined symbol: _OBJC_CLASS_$_AIRGoogleMapWMSTile`

I upgraded to RN 0.60.4 and react-native-maps 0.25 from From RN 0.59.5 and react-native-maps 0.24.2 and this is when the issue is happening. If I go back to old versions it's working fine.

## NOTE:
When I removed arm64 & arm64e from valid architectures in xcode it's successfully building but it's useless since all devices are now x64 based.

## my podfile
`target 'project_name' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GoogleMaps'
end`

## Environment info
React native info output:
```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.41 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.25

## Steps To Reproduce
install and use on RN 0.59.5 and maps 0.24.2 and then upgrade to RN 0.60 and maps 0.25 this is happening

**Comment by smallsaucepan** [comment]
I faced a very similar issue (AIRWeakMapReference and AIRWeakTimerReference though) after upgrading from 0.23.0 to 0.24.0. I had forgotten to `cd ios/` and run `pod install`. Doing so updated a couple of pods, pulling in the references mentioned.

Going from 0.24.0 to 0.25.0 produced a different error message. This time is was the one referenced in #2080. Running `pod update` instead fixed that problem. Hope that's of some help.

**Comment by computerjazz** [comment]
Adding `AIRGoogleMapWMSTile.m` to Build Phases -> Compile Sources fixed this for me.
