### ISSUE TITLE
[Android] app has stopped. ReactInstanceManager.detachViewFromInstance()

### ISSUE THREAD

**Issue by elrion018** [react-native-maps/react-native-maps#3012]
Have you read the Installation Instructions?
Yes

Environment
react-native-cli: 2.0.1
react-native: 0.60.4

Steps to Reproduce
Install react native maps
I used MapView Component in my code and open my app with react-native run-android

Hello. I am developing some apps with react-native-maps. But there are some errors.

I used MapView Component in my code and opened my app to test.
On opening a page where MapView Component was used, app was crashed and closed.

There is no problem when MapView Component was removed. I think, when MapView component was used, this error appear.

that is my code:
```
import React, { Component } from 'react';
import { StyleSheet, Text, TextInput, View, TouchableOpacity, FlatList} from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

export default class RouteSearch extends Component {
    render() {
        const { navigation } = this.props;
        return (
            
            <View style={styles.container}>
                <View style={styles.upper}>
                    <TextInput
                        style={styles.txtInput_1}
                        placeholder='something'
                    
                    />
                    <TextInput
                        style={styles.txtInput_2}
                        placeholder='something'

                    />
                </View>
                <View style={styles.lower}>
                <MapView
                    
                    style={{flex:1}}
                    initialRegion={{
                    latitude: 37.78825,
                    longitude: -122.4324,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                    }}
                />

                </View>


            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff'
    },
    upper: {
        flex:1,
        justifyContent: 'center',
    },
    lower: {
        flex:1
    },
    txtInput_1: {
        height: 60,
        borderWidth: 3,
        borderColor: '#DDDDDD',
        marginBottom: 20
    },
    txtInput_2: {
        height: 60,
        borderWidth: 3,
        borderColor: '#DDDDDD',
    }
})
```

this is adb logcat:
![image](https://user-images.githubusercontent.com/41279460/62824104-34836d00-bbd4-11e9-88e4-ccd8e44d15ab.png)

especially, ReactInstanceManager.detachViewFromInstance() appear when app is crashed.
I think this logcat error sentence is key to solve my trouble. 

Please help me~~~~~~~~~

**Comment by aggounix** [comment]
I have exactly the same problem
I have a component with mapview in it, when opening it with Expo client it works well but when I build it and installed it on android the app crashed
these are my dependencies:


    "expo": "^33.0.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-maps": "~0.24.0",

**Comment by AlastairTaft** [comment]
I'm trying to get to the bottom of this too. Around the same time our production app started crashing when a map was loaded. We figured out we weren't using a google maps api key, so have now deployed a new release with an android google maps api key set and that has resolved it but I'm still unable to track down the exact cause.

**Comment by aggounix** [comment]
This answer helped me, I hope it help
[](https://stackoverflow.com/questions/44671778/published-app-on-play-store-cant-communicate-with-google-maps-api-and-facebook)
