### ISSUE TITLE
Marker jumping when used react native Image component (android)

### ISSUE THREAD

**Issue by artemautomatic** [react-native-maps/react-native-maps#3013]
This bug appears only on android. react-native-maps: 0.24.2.

when I render the marker images like below, it seems unstable or jumping on the map.

```
<MapView.Marker>
       <Image source={your_custom_image}/>
</MapView.Marker>
```

however, it looks fine when you directly put your custom marker image to the prop like below:

```
<MapView.Marker
       image={your_custom_image}
/>
```
The thing is that when you do the second option, it is unable to give styles on the image such as width or height.

**Comment by JensKolb** [comment]
I have the same problem, I am also using the first option, but with an Icon component. 
The markers are randomly jumping around; the parents render function is not triggered. 
Setting "tracksViewChanges" to false on the markers makes no difference.

**Comment by artemautomatic** [comment]
@JensKolb  do you find any solution yet?

**Comment by JensKolb** [comment]
@artemautomatic I found a workaround: I noticed that the problem only occured when there was another map mounted. That map was in one of our react navigation home views which is always mounted, so I listened to willFocus and willBlur to figure if it was actually visible and if not, I didn't render it. This completely fixed the issue with the only downside, that the map takes half a second lobger to load.

**Comment by artemautomatic** [comment]
@JensKolb thanks a lot! i will try it

**Comment by chris-topher19** [comment]
@artemautomatic does the above mentioned solution worked for you?

**Comment by zadorozhny** [comment]
@chris-topher19 yes, it worked

**Comment by JoeLeung32** [comment]
The problem still in 0.26.1, once <Marker tracksViewChanges={true}>, whatever other icon had set {false}, they will jumping together.

**Comment by rraina91** [comment]
Thanks @JensKolb! This approach fixed my jumpy/jittery custom image problem as well.

For anyone else who wants to try it, the code I used is akin to this to take focus based on navigation being provided to my component, and then I just use the focused property in the render section to drive rendering of the Map conditionally as normal. 

```
class SomeScreen extends React.Component {
...
  constructor(props) {
    if (props != null && props.navigation != null) {
      this.didFocusListener = props.navigation.addListener('focus', () => {
        this.setState({ focused: true })
      });

      this.didBlurListener = props.navigation.addListener('blur', () => {
        this.setState({ focused: false })
      });
    }
  }
...
}
```

I'm thinking of at some point moving my component that controls this to function based and leveraging the following to get to the same point, so if yours is a FBC, maybe consider useIsFocused functionality.

**Comment by itsnuwan** [comment]
This issue still exists even in latest `react-native-maps@0.27.1`. Still have to do above workaround to get rid of it.

**Comment by f4z3k4s** [comment]
I'd advise against rendering the `<MapView />` conditionally because it has serious performance overhead.  In my case, it totally broke `'@react-navigation/material-top-tabs'`'s `MaterialTopTabNavigator`. The issue is caused by the `Image` inside `Marker`, if the `MapView` is still rendered on a not-in-focus map, like the following:

`Not-In-Focus-Currently.tsx`
```tsx
<MapView>
  <Marker
    key="marker"
    identifier="marker"
    coordinate={coordinate}
  >
    <Image
      source={LocationIcon}
      style={{ width: 40, height: 40 }}
    />
  </Marker>
</MapView>
```

so what I'd recommend is to conditionally display the marker based on `isFocused`, like:

`Not-In-Focus-Currently.tsx`
```tsx
const isFocused = useIsFocused();

return (
  <MapView>
    {isFocused && <Marker
      key="marker"
      identifier="marker"
      coordinate={coordinate}
    >
      <Image
        source={LocationIcon}
        style={{ width: 40, height: 40 }}
      />
    </Marker>}
  </MapView>
);
```

**Comment by Diyaa-Gubarah** [comment]
for me i have 3 tab each one return MapView (I have file called CustomMap.js) So in my CustomMap.js I did this.

`
import {useIsFocused} from '@react-navigation/native';
.
.
.
export default MapView = ()=> {
  const isFocused = useIsFocused();
....
return (
    isFocused && (MapView))
    
    }`

**Comment by iway1** [comment]
Strongly recommend not conditionally rendering map views because each mounting of a map view will trigger a map load which will go against your google api limit (which is 28k map loads per month)
