### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS AIRGoogleMapManager.m -[AIRGoogleMapManager didChangeActiveBuilding:] line 658

### ISSUE THREAD

**Issue by yuheidapperapps** [react-native-maps/react-native-maps#3014]
# Bug

I found this in crashlytics, I haven’t reproduce this issue by myself. However, after review the code for AIRGoogleMapManager I think this happens when there are multiple map instances,
`self.map = map;` in view method will overwrite the previous one. If the latest map is being removed from memory and the previous map's indoor delegate methods being called, then the app will crash with EXC_BAD_ACCESS.

This crash will gone if we change property map from assign to weak. However, self.map will become nil and the onIndoorBuildingFocused and onIndoorLevelActivated won’t be called

Library version: 0.24.2

**Comment by saransh-malik** [comment]
Do we have any resolution for this? I got this crash too.

**Comment by zerazeru** [comment]
This bug still exists. I see it on crashlytics and can reproduce it as well.

* You need two MapViews, render both of them, then remove one
* On the remaining MapView tap on a building, then try to move the map and it will crash

A sad workaround is to set `showsIndoors={false}` on the MapViews.

Anyway the issue should be reopened.
