### ISSUE TITLE
Is it possible to use remote image be a marker ?

### ISSUE THREAD

**Issue by tsaohucn** [react-native-maps/react-native-maps#3024]
# Question

I want to use remote image to be a marker, for example , user's avatar, from document, image prop of marker only for local image, so I tried to use image component inside marker component like below, but it seems not work . It only show view block .
![Screenshot_20190819-020243](https://user-images.githubusercontent.com/6713879/63228440-96bc1d80-c225-11e9-9d8f-795eb298a810.png)

```
    <View style={styles.container}>
      <MapView
        style={{ flex: 1 }}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      >
        <Marker
          coordinate={coordinate}
        >
          <View style={{ backgroundColor: "red", padding: 10, borderRadius: 10 }}>
            <Image
              style={{width: 100, height: 100}}
              source={{ uri: 'https://facebook.github.io/react-native/img/tiny_logo.png' }}
            />
          </View>
        </Marker>
      </MapView>
    </View>
```

**Comment by artemautomatic** [comment]
I have the same problem on android. BTW, my marker also jumps on the map, do you have this problem? @tsaohucn 

```
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
"react-native-maps": "^0.24.2",
```

**Comment by tsaohucn** [comment]
@artemautomatic, yes, my problem is also on android, I didn't try it on IOS .

**Comment by christopherdro** [comment]
Can you try the `icon` or `image` prop on <Marker /> instead of passing in a child Image component?
