### ISSUE TITLE
fillColor behaving weird on 0.25.0

### ISSUE THREAD

**Issue by cipriancaba** [react-native-maps/react-native-maps#3025]
# Bug

https://www.dropbox.com/s/1zogfngv3b1yfze/Screenshot%202019-08-19%2011.35.18.png?dl=0
The `0.08` transparency level should be much lower than the one visible in the screenshot. I have tracked this to the `AIRGoogleMapPolygon.m` and the color being passed there is `UIExtendedSRGBColorSpace 0.176471 0.341176 0.980392 0.0784314` which looks fine, so I am not sure if this is an underlying GoogleMaps issue rather than this library?
The real problem is that this happens most of the times, but there are cases when this actually works as expected. 

I only noticed this issue after the 0.25 release of the react-native-maps and the update to 0.60.4 react-native

React native info output:

```bash
react-native info
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 2.18 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 24.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react-native: 0.60.4 => 0.60.4
```

Library version: 0.25.0

## Steps To Reproduce

1. Create a polygon with an alpha channel `rgba(45,87,250,0.08)`
2. See the alpha channel not being properly respected
...

Describe what you expected to happen:

1. Alpha channel being respected when drawing

## Reproducible sample code

```
<Polygon
  key={s.id}
  coordinates={s.coordinates}
  fillColor="rgba(45,87,250,0.08)"
  strokeColor="rgba(45,87,250,0.39)"
/>
```

**Comment by cipriancaba** [comment]
For anyone looking for a quick fix, reverting to `0.24.2` fixes the issue (It also has a dependency on GoogleMaps pod version 2.5.0)

**Comment by tan101digital** [comment]
@cipriancaba Anyway to fix this other than reverting to `0.24.2`? I don't mind modifying native code.

**Comment by cipriancaba** [comment]
Haven't found a solution.. Not sure where the GoogleMaps repo is.. most likely problem is in there..

**Comment by tan101digital** [comment]
I think I found a temporary workaround. Use `setNativeProps` in `onLayout`:

```jsx
            <Polygon
              ref={ref => (this.polygon = ref)}
              onLayout={() => this.polygon.setNativeProps({
                fillColor: 'rgba(0,0,0,0.4)'
              })}
              holes={[focusingPolygon]}
              strokeColor={Colors.PRUSSIAN_BLUE}
              strokeWidth={0}
              fillColor='rgba(0,0,0,0.4)'
              accessibilityIgnoresInvertColors={false}
              coordinates={OVERLAY_POLYGON}
            />
```

**Comment by kitsanapong** [comment]
I have a problem that some times **fillColor** does not work. And this is a workaround. Set **fillColor** to some random color and then use **setNativeProps** to set your desired color.

```js
            <Polygon
              ref={ref => (this.polygon = ref)}
              onLayout={() => this.polygon.setNativeProps({
                fillColor: 'red'
              })}
              fillColor='#FFFFFF00'
            /> 
```

**Comment by sergiovonborries** [comment]
@kitsanapong works perfectly thanks!
Anyone have an idea how to solve this situation?
I have an array of polygons, how can I apply a unique ref for each polygon:

`{bunchOfStuff.map((stuff, index) => (
		<Polygon 
                        ref={ref => (this.polygon = ref)}
                        onLayout={() => this.polygon.setNativeProps({
                               fillColor: 'rgba(170, 191, 174, 0.5)'
                        })}
		      coordinates={stuff.geopoints.map(geopoint => {
				return {
					latitude: Number(geopoint.latitude),
					longitude: Number(geopoint.longitude)
				};
			})}
			fillColor= 'red'
		/>
	))}`

**Comment by cipriancaba** [comment]
You can use:
```
const polygonRefs = React.useRef({})

polygons.map(poly => (
            <Polygon
              ref={ref => {
                polygonRefs.current[String(poly.id)] = ref
              }}
              key={serviceArea.id}
              onLayout={() =>
                polygonRefs.current[String(poly.id)].setNativeProps({
                  fillColor: 'rgba(45,87,250,0.08)',
                })
              }
              coordinates={serviceArea.coordinates}
              fillColor="rgba(45,87,250,0.07)"
              strokeColor="rgba(45,87,250,0.39)"
            />
          ))}

```

**Comment by jstheoriginal** [comment]
fwiw, we're using the manual way to integrate google maps via our own Podfile, and we kept it at 2.5.0 instead of 3.1.0 for 0.25.0 and it doesn't have these issues. As soon as I tried to move up to 3.1.0, it does have the issues. so it looks like it's an issue on the native side vs. js side.

**Comment by patlux** [comment]
With a custom component:

```typescript
import React from 'react';
import { Polygon } from 'react-native-maps';

function CustomPolygon({ onLayout, ...props }) {
  const ref = React.useRef();

  function onLayoutPolygon() {
    if (ref.current) {
      ref.current.setNativeProps({ fillColor: props.fillColor });
    }
  }

  return <Polygon ref={ref} onLayout={onLayoutPolygon} {...props} />;
}

export default CustomPolygon;
```

**Usage**

```jsx
<CustomPolygon fillColor="#ff0000" />
```

**Comment by sam17896** [comment]
> With a custom component:
> 
> ```ts
> import React from 'react';
> import { Polygon } from 'react-native-maps';
> 
> function CustomPolygon({ onLayout, ...props }) {
>   const ref = React.useRef();
> 
>   function onLayoutPolygon() {
>     if (ref.current) {
>       ref.current.setNativeProps({ fillColor: props.fillColor });
>     }
>     // call onLayout() from the props if you need it
>   }
> 
>   return <Polygon ref={ref} onLayout={onLayoutPolygon} {...props} />;
> }
> 
> export default CustomPolygon;
> ```
> 
> **Usage**
> 
> ```js-jsx
> <CustomPolygon fillColor="#ff0000" />
> ```

This is not working on some instance, the polygon seems to be filled with translucent blue color, after refreshing once or twice it filling the original color.

**Comment by verochan** [comment]
I'm experiencing the same problem on the project I'm working on with react-native-maps version 0.26.1 , as a temporal fix I applied this solution: https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087

Although, on the project, we have one specific case where it's not working 100% perfect (sometimes it shows the correct styles, sometimes it doesn't), but as temporal fix, we can cope with it... 

Does anybody know if this bug related with Google Maps is already being addressed and an official solution will arrive soon? If I'm not mistaken, this is happening since July 2019 (v0.25.0) :confused:

**Comment by jstheoriginal** [comment]
An update on version 0.27.0 that sets native props when onLayout occurs:

It still has issues if a prop changes (like fill colour, for example), but the polygon itself doesn't change size/shape, which doesn't trigger an `onLayout` call, leaving the colour incorrect.

So for the time being, using a useEffect to setNativeProps when the colour prop changes is still required, but you no longer need to trigger this for size/shape changes due to `onLayout` firing.

**Comment by felixvdh** [comment]
Here is the workaround from before with @jstheoriginal's suggestion applied.

```js
function CustomPolygon(props) {
  const ref = React.useRef()

  React.useEffect(() => {
    if (ref.current /* Maybe check for google maps on iOS as well */) {
      ref.current.setNativeProps({
        fillColor: props.fillColor,
        strokeColor: props.strokeColor
      })
    }
  }, [props.fillColor, props.strokeColor])

  return <Polygon ref = { ref } { ...props } />
}
```

**Comment by therealgilles** [comment]
None of the solutions presented here work in my case. I am using:

  - react-native-google-maps (0.27.1):
    - Google-Maps-iOS-Utils (= 2.1.0)
    - GoogleMaps (= 3.5.0)

**Comment by slavikdenis** [comment]
Run into the same problem

**Comment by prvaghela** [comment]
Is this issue resolved in the latest version?

**Comment by edi** [comment]
Well .. I'm having the same translucent blue polygon issue. It sometimes uses the correct colors, sometimes it doesn't. Using the latest 0.27.1 version.

Please advise.

**Comment by tgreco** [comment]
Still an issue.

**Comment by jeremyeaton89** [comment]
Still an issue for me for iOS on 0.28.0

**Comment by edi** [comment]
Same issuevon my end ..

**Comment by verochan** [comment]
> Here is the workaround from before with @jstheoriginal's suggestion applied.
> 
> ```js
> function CustomPolygon(props) {
>   const ref = React.useRef()
> 
>   React.useEffect(() => {
>     if (ref.current /* Maybe check for google maps on iOS as well */) {
>       ref.current.setNativeProps({
>         fillColor: props.fillColor,
>         strokeColor: props.strokeColor
>       })
>     }
>   }, [props.fillColor, props.strokeColor])
> 
>   return <Polygon ref = { ref } { ...props } />
> }
> ```

After some time, I'm rechecking this issue on the project I'm working on, and after reviewing #3025, #3057, #2867 and #3658, I only managed to make it work adding a setTimeout to the `setNativeProps` call, independently of using functional components with useEffect hook or class components with the `onLayout` call. It's not ideal, but until the final solution is implemented, it serves as a working patch 😕

**Comment by edi** [comment]
Wonderhing how this is still a problem after 3 years ..

**Comment by alexandreerick** [comment]
Having the same problem for IOS on 0.29.3

**Comment by GustavoChiochetta** [comment]
I'm having the same problem with version 0.30.1 when the polygon intersect with itself

**Comment by peterkeith2010** [comment]
same problem with 0.31.0

**Comment by therealgilles** [comment]
Can this issue please be re-open?

**Comment by edi** [comment]
Guess this is just dead and wont be fixed :)

**Comment by therealgilles** [comment]
Oh my bad, I think this is been tracked in https://github.com/react-native-maps/react-native-maps/issues/3057.
