### ISSUE TITLE
Map buttons not show on first load, and show when switch screens?

### ISSUE THREAD

**Issue by dodevski** [react-native-maps/react-native-maps#3026]
Map buttons (like` showsMyLocationButton`, `zoomControls` etc...) not show on the map first load, and show when switch app screens?

![Screenshot_gif](https://media.giphy.com/media/MBsNUbbIscOAq3Yut6/giphy.gif)

Map component

```
<MapView
	ref={ref => (this.mapView = ref)}
	provider={PROVIDER_GOOGLE}
	style={styles.map}
	mapType="terrain"
	showsUserLocation={true}
	zoomControlEnabled={true}
/>
```

Any ideas?

**Comment by mertbekci** [comment]
I have that same problem 

 "react-native": "0.60.4"
 "react-native-maps": "^0.25.0"

**Comment by itsam** [comment]
Same for me... in my case since I am using react-native-navigation even the "switch screen" does not help.

**Comment by kaplona** [comment]
Same here. It seems to be something with map container or map response to layout changes.
"react-native": "0.60.4"
"react-native-maps": "0.25.0"

We show marker information in a card which appears on the bottom of a map on marker click. On first load there are no map buttons, but they appear when a user clicks on a marker and map layout changes to give way to an information card.

Minimal working example:
```javascript
class Test extends React.Component {
  constructor(props) {
    super(props);
    this.state = { isOpen: true };
  }
  
  componentDidMount() {
    setTimeout(() => this.setState({ isOpen: false }), 100);
  }
  
  render() {
    return (
      <View style={{ flex: 1 }}>
        <MapView
          provider={PROVIDER_GOOGLE}
          showsUserLocation={true}
          showsMyLocationButton={true}
          style={{ flex: 1 }}
          zoomEnabled={true}
          zoomControlEnabled={true}
        />
        
        {this.state.isOpen && <View style={{ height: 1 }} />}
      </View>
    );
  }
}
```

**Comment by kriscarle** [comment]
After a bit of searching I found this issue is explained here thanks to @psam44 https://github.com/react-native-community/react-native-maps/issues/1033#issuecomment-284531196 

I also managed to apply the workaround without needing to modify the react-native-map code by using a ref and calling `this.map.map.setNativeProps`  Like they said, this is far from a perfect fix,  just forces it to redraw instead of needing to switch screens.

Here is an example:

```js
import React from 'react'
import { StyleSheet } from 'react-native'
import MapView  from 'react-native-maps'
import * as Permissions from 'expo-permissions'

export default class MyMap extends React.Component {
  componentDidMount () {
    this._getLocationPermissionAsync()
  }

  // I needed this in Expo for the user location to show
  _getLocationPermissionAsync = async () => {
    const { status } = await Permissions.askAsync(Permissions.LOCATION)
    if (status !== 'granted') {
      // display an error
    }
  }

  render () {
    return (
      <MapView
        ref={(el) => { this.map = el }}
        showsUserLocation
        showsMyLocationButton
        zoomControlEnabled
        style={styles.mapStyle}
        onMapReady={() => {
          this.map.map.setNativeProps({ style: {...styles.mapStyle, marginLeft: 0} })
        }}
      >
        {...}
      </MapView>
    )
  }
}

const styles = StyleSheet.create({
  mapStyle: {
    flex: 1,
    marginLeft: 1
  }
})
```

**Comment by kiullikki** [comment]
The following helped me:

import React, {
  memo,
  useCallback,
  useState,
  useRef,
} from 'react';
import {
  createStyles,
} from 'react-native';
import MapView, { PROVIDER_GOOGLE, Marker } from 'react-native-maps';

function Tab() {

  const [isMapReady, setMapReady] = useState(false);

  const mapRef = useRef<MapView>(null);

  const handleMapReady = useCallback(() => {
    setMapReady(true);
  }, [mapRef, setMapReady]);

  return (
      <MapView
        ref={mapRef}
        provider={PROVIDER_GOOGLE}
        style={isMapReady ? styles.map : {}}
        showsUserLocation={true}
        showsMyLocationButton={true}
        onMapReady={handleMapReady}
      >
        {...}
      </MapView>
  );
}

export const MapTab = memo(Tab);

const styles = createStyles({
  main: {
    position: 'relative',
  },
  map: {
    width: '100%',
    height: '100%',
  },
});

**Comment by oriana4r** [comment]
Thanks @kiullikki, your solution worked for me. But, do you have any idea why do we have to implement the map component in this way?

**Comment by MiguelNiblock** [comment]
https://github.com/react-native-maps/react-native-maps/issues/3026#issuecomment-641192209

That solution worked for me, but it's not REALLY a solution. It's a slippery work-around, which could confuse someone who doesn't know this is a bug.

Basically, the map currently doesn't show the zoom controls and MyLocation button on load. It only shows them if the map style is changed after the MapView loads (i.e. onMapReady)

**Comment by llRizvanll** [comment]
This Controls worked for me, please try yourself.

`const [isMapReady, setMapReady] = useState(false);`
  `const _map = useRef(null);`
  `const _handleMapReady = useCallback(() => {`
    `setMapReady(true);`
  `}, [_map, setMapReady]);`
`<MapView`
    `      ref={_map}`
  `        style={isMapReady ? styles.mapcontainer : {}}`
`          onMapReady={_handleMapReady}/>`
`

**Comment by wenkey-everest** [comment]
Add this to avoid to break Maps on iOS for the versions below `0.30.0`.
`  style={
          Platform.OS === 'android'
            ? isMapReady
              ? styles.map
              : {}
            : styles.map
        }`
