### ISSUE TITLE
Google map on iOS works slow with markers

### ISSUE THREAD

**Issue by NemanjaManot** [react-native-maps/react-native-maps#3034]
# Bug

I found similar bug report, but for my case I didn't find solution.
On iPhones (on some more laggy then others) maps works really slow when a couple of markers are rendered. Custom or default no differences.
On android works well.

With markers: RAM around 380 MB
Without markers: RAM around 300 MB

## Environment info

 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 61.37 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.1
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.6 
      react-native: ^0.58.0 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1

react-native-maps": "0.25.0"

## Steps To Reproduce

1. Use Mapview
2. Use Marker inside MapView

Describe what you expected to happen:

1. To work fluid with markers, like on android

## Reproducible sample code

I am using` tracksViewChanges={ false }` on Marker.

```
<MapView.Marker
  tracksViewChanges={ false }
  style={ { opacity } }
  key={ key }
  coordinate={ coordinates }
  rotation={ rotation }
  anchor={ anchor }
  zIndex={ zIndex }
  onPress={ this.onPress }
  image={ this.renderIcon() }
/>
```

**Comment by mlop113** [comment]
Could you show  ` this.renderIcon() `?

**Comment by papigers** [comment]
I'm also having issues, I've confirmed this only happens with custom children inside the marker (no default marker icon), but still - only for google maps on ios, using the same custom marker on apple maps doesn't affect the performance at all.
I'm going to investigate further, remove sub-elements from the marker and check if I find something problematic.
