### ISSUE TITLE
Unable to resolve "./lib/components/MapWMSTile.js" from "node_modules\react-native-maps\index.js"

### ISSUE THREAD

**Issue by afulsamet** [react-native-maps/react-native-maps#3038]
# Question
Hello, I'm using `^0.24.2` version of `react-native-maps` with expo. I don't get this error in `latest` version of `react-native-maps`, but it still doesn't work. So `MapView` does not appear on the screen. I get this error when i use the version compatible(`^0.24.2`) with expo.

![chrome_qwa6Ug0fnq](https://user-images.githubusercontent.com/27636298/63688873-2c9d0d00-c811-11e9-8d28-04b32d7e6f6d.png)

Here is my code
```javascript
import { Text, View } from 'react-native';
import MapView from 'react-native-maps';

export default class App extends React.Component {
render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center'  }}>
        <MapView style={{ flex: 1 }} />
      </View>
    );
  }
}
```

**Comment by hashmatmuqbil** [comment]
Run
 rm -rf node_modules
npm install

**Comment by aSrivastaava** [comment]
> Run
> rm -rf node_modules
> npm install

tried but still the same error.

**Comment by afulsamet** [comment]
if `MapView` does not appear on screen, i solve this problem with this code

```javascript
<MapView
    initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    }}
    style={{  // required style for map appearance
        position: "absolute", 
        top: 0, 
        bottom: 0, 
        right: 0, 
        left: 0
    }}
/>
```
I can display map with this code, but i still can not solve error i get in `^0.24.2` version.
@hashmatmuqbil I also tried, but still failed.

**Comment by safwan-moha** [comment]
same problem

**Comment by okcompewter** [comment]
Same problem

**Comment by basemkhirat** [comment]
Still doesn't work. any updates?

**Comment by HerveH44** [comment]
I solved it, by bumping the react-native-maps version to 0.25.0.

The file MapWMSTile.js has been added in the version 0.25.0. I don't know why the expo engine fetches the version 0.24.2 because it's expecting the new version.

**Comment by maximesahagian** [comment]
I have the same issue, don't you have an error when starting the project @HerveH44 ?

`Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-maps - expected version range: ~0.24.0 - actual version installed: ^0.25.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]`

But when I install the package through expo, the error `Unable to resolve "./lib/components/MapWMSTile.js" from "node_modules/react-native-maps/index.js"` appears..

**Comment by nayana-c** [comment]
I am also facing the same issue. Any solution for this?

**Comment by kangaree** [comment]
Hey, try closing the packager and then running

`expo start -c`

"Your JavaScript transform cache is empty, rebuilding (this may take a minute)."

I have "^0.24.2" now and it works!
