### ISSUE TITLE
No bundle or url present after installing react-native-maps

### ISSUE THREAD

**Issue by tudorpintea** [react-native-maps/react-native-maps#3041]
# Bug

 I recently installed react-native-maps with CocoaPods for iOS and, after correcting some build errors, no i get "No bundle or url present"
 I tried clear cache, reinstall node modules, a lot of fixes from the internet and they aren't working.

## Environment info
  info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 481.42 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.60.3
    "react-native-maps": "^0.25.0",

React native info output:

```bash
 // paste it here
```

Library version: 0.25.0

## Steps To Reproduce

1. install react-native-maps
2.copy-paste code from install instructions in AppDelegate.m and Podfile
3.get API key
4.react-native run-ios
...

Describe what you expected to happen:

1. 
2.

## Reproducible sample code

<img width="1440" alt="Screenshot 2019-08-27 at 11 19 50" src="https://user-images.githubusercontent.com/49131718/63753917-a76f3200-c8bc-11e9-81d3-b9a3d4309255.png">

### Podfile
<img width="1440" alt="Screenshot 2019-08-27 at 11 26 43" src="https://user-images.githubusercontent.com/49131718/63754474-a094ef00-c8bd-11e9-9127-7bc5a977d0dd.png">

###Simulator
![Simulator Screen Shot - iPhone X - 2019-08-27 at 11 29 50](https://user-images.githubusercontent.com/49131718/63754720-05504980-c8be-11e9-8b15-9edd6b795de9.png)

**Comment by objectiveSee** [comment]
Getting the same error when using the Examples/ app on iOS

**Comment by jmhuret** [comment]
I encountered this issue recently. The solution for me was to remove the #ifdef debug condition in my appDelegate.m file... which actually has nothing to do with react-native-maps. 

So, instead of:
```
#ifdef DEBUG
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#endif
```

I now just have:
```
NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
```

**Comment by rborn** [comment]
@jmhuret what you did was to always load the bundle in debug mode (from metro builder on your computer). If you try to build for release your app won't work anymore.
