### ISSUE TITLE
How to animate or highlight route?

### ISSUE THREAD

**Issue by ebellumat** [react-native-maps/react-native-maps#3044]
First, thanks for the amazing project.

I Want to animate the created route, drawing then or just highlight, like Uber did, and if possible, round the corners of the path in iOS.

How to achieve this? I read the docs several times.

![ezgif-4-71e72656ca04](https://user-images.githubusercontent.com/26942680/63866150-2df14580-c989-11e9-8255-3dccc51f60a8.gif)

**Comment by richardbumm** [comment]
Does Uber use React Native Maps?

**Comment by ebellumat** [comment]
Probably not.

**Comment by richardbumm** [comment]
Uber is a tech company with internal engineering teams implementing custom code and libraries for their application.  I'm pretty sure this is an Uber Labs creation, not something you can just enable with this library

**Comment by ebellumat** [comment]
No problem. I Will implement this feature and i will open a pull request. I hope maintainers of this lib accept.
