### ISSUE TITLE
Zoom levels not consistent between iOS and Android

### ISSUE THREAD

**Issue by bargald** [react-native-maps/react-native-maps#3049]
# Bug

Same zoom level numbers appears to be different between iOS and Android.

I stored local tiles for zoom level 15 from my map provider.
when setting zoom level 15 on android they appear correctly, on iOS I don't see them, except if I set zoom level 14.

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 102.42 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.11.1 - ~/.nvm/versions/node/v12.9.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2

```

Library version: react-native-maps from master branch

## Steps To Reproduce

1. Store local tiles for a specific zoom level.
2.  set the zoomLevel property on MapView to that zoom level.
3. the tiles till not appear, but appear on Android.

## Reproducible sample code
```
<MapView
          minZoomLevel={ 15 }
          maxZoomLevel={ 16 }
...
```

**Comment by siyb** [comment]
Same issue here:
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 337.29 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

react-native-maps version 0.26.1

**Comment by heysoftwaredave** [comment]
Same issue here. Should we have different zoom levels on "Camera" for IOS and Android even though both are referencing Google Maps?
