### ISSUE TITLE
Unable to render MapView component (this._onMapReady.bind undefined)

### ISSUE THREAD

**Issue by meienberger** [react-native-maps/react-native-maps#3052]
# Bug

I'm trying to integrate react-native-maps inside my new project but after following install instructions I always get the following error when I use the <MapView /> component.

`Undefined is not an object (evaluating '_this._onMapReady.bind')`

react-native-maps was the first library I linked with this project and it was working before. Now after developing my app and adding other libraries I have this error. Maybe I used react-native link to link my fonts and it messed up something with rn-maps. I tried removing the pod and reinstalling from scratch with no luck.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 70.01 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 15, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: 0.25.0

## Steps To Reproduce

1. yarn add react-native-maps -E
2. cd ios
3. pod install

Describe what you expected to happen:

1. No error

**Comment by rborn** [comment]
you didn't link, the module doesn't support yet auto-linking I think
