### ISSUE TITLE
Marker - onDragEnd unable to click outside map

### ISSUE THREAD

**Issue by imbudhiraja** [react-native-maps/react-native-maps#3053]
# Bug

I have create a map with drag-able markers, but when i try to drag a marker to a position, after successfully drag. I not able able to perform outside clicks until i don't move MapView a bit.

## Environment info
React-Native - v60.5
React-Native-Maps - 0.25.0

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 29.79 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-Q | Android TV Intel x86 Atom, android-Q | Intel x86 Atom, android-Q | Google APIs Intel x86 Atom, android-Q | Google APIs Intel x86 Atom_64, android-Q | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-swift-cli: 2.3.0
```

Library version: 0.25.0

## Steps To Reproduce
1. Drag a marker to any specific location.
2. Try to click outside the map view. You will not be able to click outside the map until you don't move `MapVIew` a bit.
...

Describe what you expected to happen:

1. After onDragEnd outside should be able to perform.

## Reproducible sample code
```
 import React from 'react';
import { TextInput, Text, ScrollView, Button } from 'react-native';
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

class Location extends React.Component {
  mapRef = React.createRef();
  markerRef = React.createRef();

  constructor(props) {
    super(props);
    const initialRegion = {
      latitude: 30.7333,
      latitudeDelta: 0.05,
      longitude: 76.7794,
      longitudeDelta: 0.021,
    };

    this.state = {
      initialRegion,
      marker: {
        latitude: 30.7333,
        longitude: 76.7794,
      },
      region: initialRegion,
    };
  }

  onDragEnd=(e) => {
    this.setState({ marker: e.nativeEvent.coordinate });
  }

  render() {
    const {
      marker, initialRegion, region,
    } = this.state;

    return (
      <ScrollView>
        <TextInput />
        <Text>
          {'Long Press & Drag the pointer to select exact location'}
        </Text>
        <MapView
          ref={this.mapRef}
          provider={PROVIDER_GOOGLE}
          style={{ flex: 1 }}
          initialRegion={initialRegion}
          region={region}
        >
          <Marker.Animated
            draggable
            ref={this.markerRef}
            coordinate={marker}
            onDragEnd={this.onDragEnd}
          />
        </MapView>
        <Button
          block
          smallrounded
          onPress={() => this.onSubmit('Photo')}
        >
          <Text upperCase>NEXT</Text>
        </Button>
      </ScrollView>
    );
  }
}

export default Location;
```

**Comment by matiasgitl** [comment]
@imbudhiraja Did you find any solution? I'm with the same problem here

**Comment by alexborton** [comment]
Looks like i might have duplicated this too, but with further symptoms. #3078

**Comment by matiasgitl** [comment]
As I needed it fast I finally "solved" it changing the implementation by [this](https://designplox.com/blog/keep-marker-in-center-and-move-map-around-it) (that is better too)

**Comment by alexborton** [comment]
@matiasgitl this does actually look like an enhancement for my use case too.. good find! 👍 

Issue/issues remain open however ;)

**Comment by GH974** [comment]
Hi, anyone anything to suggest for this bug ?

**Comment by verochan** [comment]
Hi, I'm experiencing this bug, any suggestion to solve this?

**Comment by GH974** [comment]
+1

**Comment by verochan** [comment]
Almost 3 months have passed and still no solution to this bug? 😢

**Comment by GH974** [comment]
@verochan yes, no solution for moment Too bad

**Comment by isllyend** [comment]
It's so terrible (:

**Comment by isllyend** [comment]
help help to solve this  it‘s so terrible

**Comment by BenCrooksWeBill** [comment]
Even me :( +1

**Comment by ddedic** [comment]
+1

**Comment by tomthornton** [comment]
+1

**Comment by tomthornton** [comment]
@matiasgitl could you post another link to the "fix" you had for this? The link you provided is broken. Thanks!

**Comment by richvillije** [comment]
+1

**Comment by gabrielbrickle** [comment]
Any updates on this?

**Comment by gramberg** [comment]
@gabrielbrickle Have a look at this issue: https://github.com/react-native-community/react-native-maps/issues/2780

Maybe [this comment](https://github.com/react-native-community/react-native-maps/issues/2780#issuecomment-562629150) will help you as well.

**Comment by azhararmar** [comment]
Although not a good solution, a quick work-around is to re-render the map `onDragEnd` event. Here is what can be done.


```
{true === this.state.displayMapView &&
    <View style={{flex: 1}}>
        <MapView
            provider={PROVIDER_GOOGLE}
            style={{width: SCREEN_WIDTH, height: moderateScale(350)}}
            initialRegion={{
                latitude: this.state.latitude,
                longitude: this.state.longitude,
                latitudeDelta: 0.015,
                longitudeDelta: 0.0121
            }}
        >
            <MapView.Marker
                draggable
                coordinate={{latitude: this.state.latitude, longitude: this.state.longitude}}
                onDragEnd={(e) => {
                    const coords = e.nativeEvent.coordinate;
                    this.setState({
                        latitude: coords.latitude,
                        longitude: coords.longitude,
                        displayMapView: false
                    }, () => {
                        this.setState({
                            displayMapView: true
                        });
                    });
                }}
            />
        </MapView>
    </View>
}
```

On completing the onDragEnd event, it will retain the co-ordinates however it will refresh the map, I tried this and it works, I wish we have a solution soon on this.

**Comment by naaficodes** [comment]
Use this TouchableOpacity instead from react-native package

import { TouchableOpacity } from 'react-native-gesture-handler';

They work after map marker dragging.

**Comment by naaficodes** [comment]
Use this TouchableOpacity instead from react-native package

`import { TouchableOpacity } from 'react-native-gesture-handler';`

They work after map marker dragging.

**Comment by getterhiss** [comment]
@naaficodes Thank you!! This worked for me 🙏🙏🙏🙏

**Comment by tgreco** [comment]
+1 still no solution.

**Comment by verochan** [comment]
> Use this TouchableOpacity instead from react-native package
> 
> `import { TouchableOpacity } from 'react-native-gesture-handler';`
> 
> They work after map marker dragging.

I've been suffering this bug too on react-native-maps library, after reviewing almost a year later this issue and 3078, the quoted solution works on the project I'm working on 🎉  Just be careful with the styles applied to the affected buttons: On my case, the styles were broken and I had to create a View wrapper surrounding the TouchableOpacity components to manage properly opacity and some flex position properties.

Either way, I hope it gets fixed for the react-native TouchableOpacity component.

**Comment by Jarrettgohh** [comment]
This seems to not be an issue when using Apple maps.
