### ISSUE TITLE
Local tile doesn't work

### ISSUE THREAD

**Issue by eniniz** [react-native-maps/react-native-maps#3055]
# Question

I'm trying to use open street map offline, therefore I downloaded the needed tile (using JTileDownloader) then I used LocalTile, here is the render part of my map : 
`   render() { 

    var pathTemplate = "./tiles/h2/{z}/{x}/{y}.png";
    return (
      <View style={{ flex: 1, flexDirection: "column" }}>
        <View style={{ flex: 2 }}>
          <MapView
            mapType="none"
            initialRegion={this.state.initialRegion}
            style={{
              flex: 1,
              left: 0,
              right: 0,
              bottom: 0,
              top: 0,
              position: "absolute"
            }}
            region={this.state.region}
          >
            <MapView.Marker coordinate={this.state.markerPosition}>
              <View style={styles.raduis}>
                <View style={styles.marker} />
              </View>
            </MapView.Marker>
            <LocalTile pathTemplate={pathTemplate} tileSize={512} />
          </MapView>
        </View>
      </View>
    );
  }`

here is the hierarchy of tiles : 
+tiles
+--h2
+----12
+------....(the png tiles images)
+----13
+----14
+----15
+----16
+----17
+----18
the Map.js file (which renders the map) and the tiles folder are located in the same place

when I run this code, I got not error however the map doesn't appears.
could anyone help please :)

**Comment by bargald** [comment]
You can use a url tile and pass it a file local file url like this:
 `file://${RNFS.DocumentDirectoryPath}/tiles/{z}-{x}-{y}.png`

**Comment by NortacYWang** [comment]
hello, I have the same problem: 
I have uploaded the tiles folder to android emulator Download : 
![image](https://user-images.githubusercontent.com/96532687/216143494-527dd71c-47c4-450c-8598-f3db109424ea.png)

2 in my code: 
```
    <MapView
        style={styles.map}
        mapType={Platform.OS == 'android' ? 'none' : 'standard'}
      >
        <LocalTile
           // The path template of the locally stored tiles. The patterns {x} {y} {z} will be replaced at runtime
           // For example, /storage/emulated/0/mytiles/{z}/{x}/{y}.png
          pathTemplate={`${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`}
          
           // The size of provided local tiles (usually 256 or 512).
          tileSize={256}
          zIndex={10}
        />

      // I also tried the urlTiles
    {/* <UrlTile
          urlTemplate={
            // 'https://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
            `file://${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`
            // 'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg'
          }
          zIndex={10}
        /> */}

...
```

but the map shows nothing, can anyone help me ?

Thank you

**Comment by aroshanzamir** [comment]
> hello, I have the same problem: I have uploaded the tiles folder to android emulator Download : ![image](https://user-images.githubusercontent.com/96532687/216143494-527dd71c-47c4-450c-8598-f3db109424ea.png)
> 
> 2 in my code:
> 
> ```
>     <MapView
>         style={styles.map}
>         mapType={Platform.OS == 'android' ? 'none' : 'standard'}
>       >
>         <LocalTile
>            // The path template of the locally stored tiles. The patterns {x} {y} {z} will be replaced at runtime
>            // For example, /storage/emulated/0/mytiles/{z}/{x}/{y}.png
>           pathTemplate={`${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`}
>           
>            // The size of provided local tiles (usually 256 or 512).
>           tileSize={256}
>           zIndex={10}
>         />
> 
>       // I also tried the urlTiles
>     {/* <UrlTile
>           urlTemplate={
>             // 'https://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
>             `file://${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`
>             // 'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg'
>           }
>           zIndex={10}
>         /> */}
> 
> ...
> ```
> 
> but the map shows nothing, can anyone help me ?
> 
> Thank you

did you find any solution?

**Comment by NortacYWang** [comment]
> > hello, I have the same problem: I have uploaded the tiles folder to android emulator Download : ![image](https://user-images.githubusercontent.com/96532687/216143494-527dd71c-47c4-450c-8598-f3db109424ea.png)
> > 2 in my code:
> > ```
> >     <MapView
> >         style={styles.map}
> >         mapType={Platform.OS == 'android' ? 'none' : 'standard'}
> >       >
> >         <LocalTile
> >            // The path template of the locally stored tiles. The patterns {x} {y} {z} will be replaced at runtime
> >            // For example, /storage/emulated/0/mytiles/{z}/{x}/{y}.png
> >           pathTemplate={`${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`}
> >           
> >            // The size of provided local tiles (usually 256 or 512).
> >           tileSize={256}
> >           zIndex={10}
> >         />
> > 
> >       // I also tried the urlTiles
> >     {/* <UrlTile
> >           urlTemplate={
> >             // 'https://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
> >             `file://${RNFS.DownloadDirectoryPath}/555/{z}/{x}/{y}.png`
> >             // 'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg'
> >           }
> >           zIndex={10}
> >         /> */}
> > 
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but the map shows nothing, can anyone help me ?
> > Thank you
> 
> did you find any solution?

Hello, I tried it on the real device and it worked, if using emulator, try to disable the debug mode. Hope it help
