### ISSUE TITLE
react-native-maps issue

### ISSUE THREAD

**Issue by LongSeoJun** [react-native-maps/react-native-maps#3056]
i am using react-native-cli :2.0.1 and react-native:0.60.5
i installed react-native-maps ..
but app don't working..

**Comment by Asinox** [comment]
Please add more info about your issues.

Thanks!

**Comment by LongSeoJun** [comment]
Thank you!
first when i install react-native-maps then ...
![image](https://user-images.githubusercontent.com/52457934/64499649-84954280-d2ec-11e9-8987-81787181c5d5.png)
second..run-android
![image](https://user-images.githubusercontent.com/52457934/64499736-e81f7000-d2ec-11e9-869f-d7a26d9253db.png)

![image](https://user-images.githubusercontent.com/52457934/64499828-3896cd80-d2ed-11e9-86e1-8a3e0296cfa5.png)
…]()
and 
i insert my api_key 

![image](https://user-images.githubusercontent.com/52457934/64500173-b7d8d100-d2ee-11e9-88f2-fab7be6a444b.png)

but 
![image](https://user-images.githubusercontent.com/52457934/64500061-4567f100-d2ee-11e9-85aa-631876f2419f.png)

**Comment by Asinox** [comment]
After inserting your API KEY, just run again 

> react-native run-android

**Comment by LongSeoJun** [comment]
I tried again and again.

**Comment by Asinox** [comment]
Re-check that your API KEY is correct.

**Comment by LongSeoJun** [comment]
my api key is correct and when i try run-android then 
![image](https://user-images.githubusercontent.com/52457934/64500530-2702f500-d2f0-11e9-8b49-42d1a5aa318e.png)

**Comment by Asinox** [comment]
Try this: 

> react-native unlink react-native-map

and then go inside ios folder and try:

> pod install

**Comment by LongSeoJun** [comment]
Sorry ! i only need android app

**Comment by Asinox** [comment]
Well, just `react-native unlink react-native-map`

**Comment by LongSeoJun** [comment]
then i can not use map...Whether i  use any package, i can present(show) the map?.do you have any method?

**Comment by Asinox** [comment]
Try a new installation with this:
`npm install react-native-maps --save-exact`

**Comment by LongSeoJun** [comment]
i already try it

**Comment by LongSeoJun** [comment]
so i created new react-native app version 0.59.10...
then no error or warning but run-android  then 
![image](https://user-images.githubusercontent.com/52457934/64501250-2c157380-d2f3-11e9-81ba-ca47c50a40c9.png)
do not show map ...(blank map pages)

**Comment by Asinox** [comment]
Check this https://github.com/react-native-community/react-native-maps/issues/118

**Comment by LongSeoJun** [comment]
do you have ever use this samples(https://github.com/react-native-community/react-native-maps)

**Comment by rborn** [comment]
This is an API key issue, be sure is the correct one and is unrestricted

**Comment by LongSeoJun** [comment]
thank you ..but i already used reistricted api key..but same....

**Comment by RajeshKumDev** [comment]
I had the same issue, in my project. And when I see in Android studio log I got following error:

> E/Google Maps Android API: Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
E/Google Maps Android API: In the Google Developer Console (https://console.developers.google.com)
Ensure that the "Google Maps Android API v2" is enabled.
Ensure that the following Android Key exists:
API Key: <Your API KEY>
Android Application (<cert_fingerprint>;<package_name>): <your keystore sha1 hash>;<app-package-name>

After switching to correct keystore it starts working.

here is my main build-gradle file settings for build tools and google lib version:

> ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "11.8.0"
        androidMapsUtilsVersion = "0.5+"
    }

Unfortunately the latest versions of google maps is not working for me, so I used **11.8.0**

**Comment by ericrprates** [comment]
You need to enable Maps Static API and Maps SDK for Android on Google Developer Console - Libraries

I hope this helps you!

**Comment by sharmad1205** [comment]
Having Same issue Blank Maps Page with Google logo on left bottom.
Checked API key i.e correct
When Updated React-native from 0.5.9 to 0.6.1

**Comment by TimMun** [comment]
For others running into the same problem: Just because the google logo shows up does **not** necessarily mean it must be API key issue. 

In my case, I upgraded the react-native-maps package (along with RN 0.61), and somewhere the behavior must have changed. I used to be able to set the `region` with a latitudeDelta and longitudeDelta with 180 and 360 before. Now doing that with 0.26.1 causes a blank map.

Try creating a new project and add just a MapView and some known-good props; and if that works for you, you can troubleshoot backwards from there. You can also copy-paste the [api key from the example](https://github.com/react-native-community/react-native-maps/blob/master/example/android/app/src/main/AndroidManifest.xml#L26) into your project to determine if it's an api key issue (at least right now, it's unrestricted).

Also, when you make any changes to AndroidManifest.xml, you have to clean build.
```
cd android
./gradlew clean
```
