### ISSUE TITLE
Localize map

### ISSUE THREAD

**Issue by infin1t3** [react-native-maps/react-native-maps#3058]
# Question

- Before submitting it, please ensure that this was not already asked in another issue, or on StackOverflow. Ideally, you should always refer to StackOverflow first.
The only related question I found on StackOverflow was this:
https://stackoverflow.com/questions/53995302/how-to-create-local-language-support-on-google-maps-using-react-native-maps

There a couple threads and blog posts on the web, but most of them are either outdated or simply state "Change your phone language"

I have a business requirement to translate map to french. 
Changing my phone language is not an option unfortunately.
Is there a way to localize?

**Comment by rborn** [comment]
Would have been better to follow the template instead of put a "disclaimer" there (please update it or I'll close the issue)

Besides this:  did you try to change your phone language to french and see how is the map behaving?

**Comment by infin1t3** [comment]
@rborn Thank you for pointing that out, and sorry for not doing it in the first place. Description updated. 
As for the problem, unfortunately just the map needs to be in French, regardless of the phone language.

**Comment by infin1t3** [comment]
Well it is possible for embedding Google Maps on the web
https://stackoverflow.com/questions/22503945/set-language-for-google-maps-iframe
So I think the same should be possible on Mobile too.
