### ISSUE TITLE
animateCamera doesnt always zoom

### ISSUE THREAD

**Issue by Return-1** [react-native-maps/react-native-maps#3060]
# Bug

Zooming with animateCamera only works randomly sometimes. It is unclear when but many times, even though the camera is positioned to the right location, the zooming doesnt take place.

## Environment info

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 37.04 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

Nothing complicated, try the following on any android device

`this.map.animateCamera({
            center: coordinates,
            heading: 0,
            pitch: 0,
            zoom: 16,
        }, { duration: 450 })`

Sidenote: Seems to almost always work when zoomed out a lot but never works when zoomed in a lot. A lot is not exactly a measurable quantity but its hard to put exact numbers on this, reproduction is very easy so this rough description should suffice.

**Comment by higoramp** [comment]
I had the same problem with the Apple Maps.
Seems like the IOS mapKit uses the attribute altitude and Google Maps uses zoom

https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#types

Hope it helps

**Comment by lucaslarios** [comment]
> I had the same problem with the Apple Maps. Seems like the IOS mapKit uses the attribute altitude and Google Maps uses zoom
> 
> https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#types
> 
> Hope it helps



Thanks!'
