### ISSUE TITLE
Polyline in mapview error

### ISSUE THREAD

**Issue by nvkgismt** [react-native-maps/react-native-maps#3061]
Hello
I am using mapview 0.25.0 with RN 0.60.5
My app stopped abruptly when I used Component Polyline, I tried with Component Marker, Polygon all worked. app's code

import MapView, { PROVIDER_GOOGLE, Polyline, Polygon }  from 'react-native-maps'; // remove PROVIDER_GOOGLE import if not using Google Maps

const App = () => {
  return (
    <Fragment>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <View style={styles.container}>
          <MapView
            provider={PROVIDER_GOOGLE} // remove if not using Google Maps
            style={styles.map}
            region={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0121,
            }}
          >
            <Polyline
              coordinates={[
                { latitude: 37.8025259, longitude: -122.4351431 },
                { latitude: 37.7896386, longitude: -122.421646 },
                { latitude: 37.7665248, longitude: -122.4161628 },
                { latitude: 37.7734153, longitude: -122.4577787 },
                { latitude: 37.7948605, longitude: -122.4596065 },
                { latitude: 37.8025259, longitude: -122.4351431 }
              ]}
               strokeColor="#000" 
                strokeWidth={6}
            />
          </MapView>
        </View>

      </SafeAreaView>
    </Fragment>
  );
};

Help me.

**Comment by vuhoangp** [comment]
Same error
