### ISSUE TITLE
animateCamera / animateRegion puts chosen location in the corner of the screen

### ISSUE THREAD

**Issue by kuzkokov** [react-native-maps/react-native-maps#3063]
# Bug

Hey, guys. Recently I have created a PR -- #3045 , and now I am using my own fork in the project since I need the heading.
The thing is, this version with all latest PRs merged over 0.25.0 version is buggy. I am using `animateCamera` and `animateRegion` to animate to the user location. And on this latest version, these methods put the user location in the top left corner of the screen.
Here is the video:
https://drive.google.com/file/d/0B-9cMKJkePFuZE1GZ0VmTFJ2T2lHQlB3bW5lcTFkdU0zR1dR/view

It happens only on iOS. If I cmd+R my emulator, everything starts working fine, but if I close the app and run it again, the same bug appears. The same with a real device (on the video).

If I apply my PR over pure 0.25.0 everything works fine as well. So I suppose the bug is somewhere in between my PR and version 0.25.0 tag.

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 348.28 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: the very latest

**Comment by ingvardm** [comment]
using initialRegion prop solved the issue for me
