### ISSUE TITLE
onTouchCancel triggered just after onTouchStart, and onTouchEnd not triggered

### ISSUE THREAD

**Issue by PabloGiraudCarrier** [react-native-maps/react-native-maps#3065]
# Bug

I'm using the Touch events from the lib to hide some components when the map is moving. I use onTouchStart and onTouchEnd but the event onTouchCancel is triggered just after the onTouchStart , and onTouchEnd isn't triggered.

## Environment info

React native info output:

```bash

  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 2.20 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 27, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 0.25.0

## Steps To Reproduce

1. react-native run-ios
2. move the map with one finger
3. release the map

Describe what you expected to happen:

1. The event onTouchStart should be triggered when moving the map (it works)
2. The event onTouchEnd should be triggered when we release the map (not working)

## Reproducible sample code

```
export const Map = (props) => {
   return {
     <MapView
       style={{flex: 1}}
       onTouchEnd={() => console.log("TOUCH END}/>
   }
}
```

**Comment by liangyue2019** [comment]
onTouchStart={(e) => e.preventDefault()}

**Comment by jonasmedeiros** [comment]
@PabloGiraudCarrier did you have a fix for that ?
