### ISSUE TITLE
how to change direction arrow style

### ISSUE THREAD

**Issue by daheeahn** [react-native-maps/react-native-maps#3068]
# Question

Currently the direction is indicated by a blue triangle arrow, is there a way to beam the direction like the google maps app?

<current>

![스크린샷 2019-09-18 오후 6 17 34](https://user-images.githubusercontent.com/38369729/65138109-65fa1e80-da45-11e9-8905-1da595fe7ac1.png)

<I want (like google maps app)>
![스크린샷 2019-09-18 오후 6 17 48](https://user-images.githubusercontent.com/38369729/65138193-87f3a100-da45-11e9-81d9-2aaae5f9064a.png)

**Comment by IvanRavinskiy** [comment]
+1
