### ISSUE TITLE
React native maps not working with react native v0.60.5

### ISSUE THREAD

**Issue by johnJD47** [react-native-maps/react-native-maps#3069]
App repeatedly closes 
when remote js debugging enabled 
 "react-native": "0.60.5",
 "react-native-maps": "0.25.0",

**Comment by ABulnes** [comment]
Same here

**Comment by alubeck** [comment]
Same here...even not working with the latest commit from master 🤔 
https://github.com/react-native-community/react-native-maps/issues/3081

**Comment by virgule-xyz** [comment]
Probably a duplicate or same issue than https://github.com/react-native-community/react-native-maps/issues/3081

**Comment by AdityaTodkar** [comment]
react-native-maps is not working on react-native version 0.60.5 and react-native-maps version 0.25.0 I am getting this error 
```
React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-maps (to unlink run: "react-native unlink react-native-maps")
```
```
> Task :app:packageDebug FAILED
```

**Comment by alubeck** [comment]
I've got it working with the newer commit from master and manual linking, see here: https://github.com/react-native-community/react-native-maps/issues/3081

**Comment by RWOverdijk** [comment]
It does work on react-native 0.61.0-rc3 by the way.

**Comment by anastely** [comment]
I have react native 0.61.2 and it's not working!

**Comment by MatheusLima7** [comment]
i have react native v 0.61.5 and it's not working
