### ISSUE TITLE
MapView blocks the Touches and Handlers in the Screen

### ISSUE THREAD

**Issue by RamParthiban** [react-native-maps/react-native-maps#3071]
# Bug
I updated the latest RN version 0.60.5 and RN maps to 0.25. The App renders MapView on a route. The Screen gets stuck except the Map. The Map doesn't render the Region I specified, Renders the entire Map and no Markers are getting rendered.

## Environment info

React native info output:

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 2.47 GB / 11.92 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Users\XXX\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045

React Native Maps Library version: 0.25.0
React Native: 0.60.5
React Navigation: 4.0.0

## Reproducible sample code
```
const Map = () => {
  const coords = {
    latitude: 40.730610,
    longitude: -73.935242,
  }
  const [region, setRegion] = React.useState({
    latitude: 40.730610,
    longitude: -73.935242,
    latitudeDelta: LATITUDE_DELTA,
    longitudeDelta: LONGITUDE_DELTA,
  });
  const updateRegion = newRegion = setRegion(newRegion);

  return (
    <MapView
      provider={PROVIDER_GOOGLE}
      region={region}
      onRegionChange={updateRegion}
    >
      <Marker coordinate={coords} title="Test" />
    </MapView>
  );
}
```

**Comment by alexborton** [comment]
Could be related to my issue #3078
