### ISSUE TITLE
Advice for positioning 731 images all over the map at precise coordinates.

### ISSUE THREAD

**Issue by fromsujay** [react-native-maps/react-native-maps#3072]
Hello, 

I am a beginner and I request you to be patient with me. 

How do I position 731 images all over the map at predefined coordinates ? 

Development environment : expo: 33.0.0, react-native-maps: 0.24.2

What have I tried ? 
1. Geojson : Since <Geojson/> component of react-native-maps doesn't render images. This method didn't work. 
2. Rendering 731 <Overlay/> components. I converted KML file into Geojson and used it as the input dataset. By mapping through the whole Geojson at once, I tried to render 731 Overlay components on the map. Being a resource heavy operation, the app crashed systematically. 
3. Capturing the center of the screen using onRegionChangeComplete function, I tried to select only images within a precise radius i.e. roughly 4 images and render these images using the <Overlay/> component. The different operations take place asynchronously and the app crashes systematically. 

I have implemented this functionality on our website an I want to do the same in our mobile application using React Native : https://www.darkskymap.com/nightSkyBrightness

On our website I have used the KML layer directly to render the images on the map using the following library : @react-google-maps/api v1.6.0.

Unfortunately, I haven't found any library that can directly render a KML file onto react-native-maps. I am lost and would really appreciate help.

**Comment by kylebarron** [comment]
The link you point to shows images that form an overlay, with no images overlapping. This is exactly what a custom tile layer is for:
https://github.com/react-native-community/react-native-maps#using-a-custom-tile-overlay
