### ISSUE TITLE
Cannot call ref for methods on < MapView /> when using Function Components + Hooks

### ISSUE THREAD

**Issue by mvuk** [react-native-maps/react-native-maps#3073]
# Question

I found this StackOverflow post with similar information on how this could be figured out and resolved, however I tried with both the **useRef** and **createRef** hooks and neither was able to capture a reference to the map in the way I can actually call a method on it.

https://stackoverflow.com/questions/41048546/how-can-i-attach-to-a-stateless-components-ref-in-react

One example:

```
import React, { createRef }, from "react"

<ommitted>

const ServiceMap = ({service, driver}) => {

let mapRef = createRef();

return (
<MapView
ref={mapref}
>

</MapView>
)

}

```

No matter what when I use the patterns and proposed solutions I get the following value from my "mapRef":

```
Object {
  "current": null,
}
```

Then when I try to call one of the methods on it, I am told that it is undefined. When I look up all of the documentation about how to use Refs, then I am never shown with this format, however this is the consistent way I am building my entire application with hooks. I would want to stay consistent with this approach.

When I read this article: https://www.robinwieruch.de/react-function-component I find that **"React Function Components cannot have refs. However, if you need to pass a ref to a Function Component -- because you have to measure the size of a function component's DOM node, for example, or like in this case to focus an input field from the outside -- you can forward the ref:"**

So then let me try to forward the ref, ok. Hold on, I cannot because I did not create the component and I cannot modify the "<MapView>" component itself, I am importing it from this library! 

Is there a solution here? Does this mean it is impossible to call methods on the components if I am using this approach? To clarify I can display the map, markers, etc. all just fine.

**Comment by nfasarakis** [comment]
Hey @mvuk. 

So in <MapView> you attach the ref as **mapref**, but you've defined it as **mapRef** further above. Fix the typo where you attach the ref in MapView and you're good to go.  It should work. 

Now, it's true that functional components cannot have refs, in the sense that you can't attach a ref to them. This is not what you're doing here. You're attaching a ref to <MapView> which is not a functional component, it's a class component. So you shouldn't worry about that. 

As for createRef() vs useRef(), you should generally prefer useRef() in functional components since you probably want to maintain the reference across updates.

**Comment by dragma** [comment]
Same thing here. I can't have acces to any method in my `MapView`'s ref.
Code is almost the same, the "major" difference here is that I use `useRef`.

Code example :
```js
import React, { useRef } from 'react';
import MapView from 'react-native-maps';

const MyComp = () => {
    const mapRef = useRef(null);
    return (
      <MapView ref={mapRef} onMapReady={() => console.log(mapRef)}>[...myMarkers...]</MapView>
    ); 
}
```

I am using expo v35, and react-native-maps v0.25.0

**Comment by nfasarakis** [comment]
@dragma How are you trying to access the methods? Can you show us what you’re trying to do and what error you’re getting?

FYI,  make sure you’re accessing the methods through the .current property, i.e as `mapRef.current.methodName`

**Comment by dragma** [comment]
I am trying to access the method by the `mapRef` variable. 
The output I get with this code
```javascript
import React, { useRef } from 'react';
import MapView from 'react-native-maps';

const MyComp = () => {
    const mapRef = useRef(null);
    return (
    <MapView 
        ref={mapRef} 
        onMapReady={() => {
            console.log('==> REF CURRENT OBJECT KEYS');
            console.log(Object.keys(mapRef.current));
            console.log('==> TYPE OF EACH METHODS');
            console.log('mapRef.current.getCamera => ', typeof mapRef.current.getCamera);
            console.log('mapRef.current.animateCamera => ', typeof mapRef.current.animateCamera);
            console.log('mapRef.current.setCamera => ', typeof mapRef.current.setCamera);
            console.log('mapRef.current.animateToRegion => ', typeof mapRef.current.animateToRegion);
            console.log('mapRef.current.animateToNavigation => ', typeof mapRef.current.animateToNavigation);
            console.log('mapRef.current.animateToCoordinate => ', typeof mapRef.current.animateToCoordinate);
            console.log('mapRef.current.animateToBearing => ', typeof mapRef.current.animateToBearing);
            console.log('mapRef.current.animateToViewingAngle => ', typeof mapRef.current.animateToViewingAngle);
            console.log('mapRef.current.getMapBoundaries => ', typeof mapRef.current.getMapBoundaries);
            console.log('mapRef.current.setMapBoundaries => ', typeof mapRef.current.setMapBoundaries);
            console.log('mapRef.current.setIndoorActiveLevelIndex => ', typeof mapRef.current.setIndoorActiveLevelIndex);
            console.log('mapRef.current.fitToElements => ', typeof mapRef.current.fitToElements);
            console.log('mapRef.current.fitToSuppliedMarkers => ', typeof mapRef.current.fitToSuppliedMarkers);
            console.log('mapRef.current.fitToCoordinates => ', typeof mapRef.current.fitToCoordinates);
            console.log('mapRef.current.pointForCoordinate => ', typeof mapRef.current.pointForCoordinate);
            console.log('mapRef.current.coordinateForPoint => ', typeof mapRef.current.coordinateForPoint);
            console.log('mapRef.current.getMarkersFrames => ', typeof mapRef.current.getMarkersFrames);
            console.log('==> TEST GET CAMERA');
            mapRef.current.getCamera();
        }} />
    ); 
}
```
is this one
```
==> REF CURRENT OBJECT KEYS
Array [
  "props",
  "context",
  "refs",
  "updater",
  "state",
  "_onMapReady",
  "_onMarkerPress",
  "_onChange",
  "_onLayout",
  "_reactInternalFiber",
  "_reactInternalInstance",
  "__reactInternalMemoizedMergedChildContext",
  "map",
  "__reactInternalSnapshotBeforeUpdate",
]
==> TYPE OF EACH METHODS
mapRef.current.getCamera =>  function
mapRef.current.animateCamera =>  function
mapRef.current.setCamera =>  function
mapRef.current.animateToRegion =>  function
mapRef.current.animateToNavigation =>  function
mapRef.current.animateToCoordinate =>  function
mapRef.current.animateToBearing =>  function
mapRef.current.animateToViewingAngle =>  function
mapRef.current.getMapBoundaries =>  function
mapRef.current.setMapBoundaries =>  function
mapRef.current.setIndoorActiveLevelIndex =>  function
mapRef.current.fitToElements =>  function
mapRef.current.fitToSuppliedMarkers =>  function
mapRef.current.fitToCoordinates =>  function
mapRef.current.pointForCoordinate =>  function
mapRef.current.coordinateForPoint =>  function
mapRef.current.getMarkersFrames =>  function
==> TEST GET CAMERA

TypeError: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getCamera')
- node_modules/react-native-maps/lib/components/MapView.js:630:40 in getCamera
* src/views/HomeScreen/components/Map.js:149:12 in onMapReady
- node_modules/react-native-maps/lib/components/MapView.js:586:18 in <unknown>
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13857:16 in callCallback
- ... 22 more stack frames from framework internals

```
Any clue ?

**Comment by dragma** [comment]
I must say that i get this error only on android.

react-native-maps: v0.25
expo: SDK35

**Comment by Saifadin** [comment]
@dragma that error is related to #3099

**Comment by stevematdavies** [comment]
I have a similar problem trying to get callouts to work with useRef hooks. There seems to be either ridiculously involved examples or nothing explaining how this works, the getCallout() always throws an error as not defined when using hooks. There is no clear example on how to do this.

**Comment by davx1992** [comment]
Hello All,
having same issue. Cant access methods animateToRegion when add reference with useRef().
Does anybody has working example with hooks?

**Comment by Dingyj3178** [comment]
> Hello All,
> having same issue. Cant access methods animateToRegion when add reference with useRef().
> Does anybody has working example with hooks?

Please try ref.current
```
const mapRef = useRef(null);
mapRef.current.animateToRegion
```

**Comment by andywu0408** [comment]
> > Hello All,
> > having same issue. Cant access methods animateToRegion when add reference with useRef().
> > Does anybody has working example with hooks?
> 
> Please try ref.current
> 
> ```
> const mapRef = useRef(null);
> mapRef.current.animateToRegion
> ```

I'm doing this with a functional component that is a wrapper to my MapView. However, I'm still having the warning that "Function components cannot be given refs". Can anyone help a react beginner out please?

**Comment by betoharres** [comment]
the problem for me is that `onMapReady` does not send the map ref as an argument, so we cannot set the ref outside the render. Setting refs on render are not recommended by the React docs:
```
Unless you’re doing lazy initialization, avoid setting refs during rendering — this can lead to surprising behavior. Instead, typically you want to modify refs in event handlers and effects```
source: https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

Not sure how hard would be to fix that

**Comment by maartenvandillen** [comment]
For me this is working partially.

I have a component `<MapView ref={map} />` and a `const map = useRef(null);` declaration in a `FunctionComponent`. From within a `useEffect` effect callback I can call `map.current.fitToCoordinates()` for instance, which is working great. But from within an `onChangeText` handler of a `<TextInput/>` in the same component, the `map.current` reference is null. 

Does anyone have any idea how to fix this?

**Comment by MoOx** [comment]
Something is definitely wrong with what is exposed explicitly in the JS side (at least on iOS).

If you log you `ref.current`, you won't see most methods.
Same problem if you do some defensing programming like I were doing

```js
if (mapRef.current && mapRef.current.animateToRegion) {
  mapRef.current.animateToRegion( ... )
}
```

This code just never call the method because the test doesn't pass. That said, if you change your code to 

```js
if (mapRef.current) {
  mapRef.current.animateToRegion( ... )
}
```

It works (with a risk of failure, but it works).

**Comment by betoharres** [comment]
@MoOx 
I fixed this by passing `this` into `onMapReady` cb into this module using patch-package
```
--- a/node_modules/react-native-maps/lib/components/MapView.js
+++ b/node_modules/react-native-maps/lib/components/MapView.js
@@ -596,7 +596,7 @@ class MapView extends React.Component {
     this._updateStyle(this.props);
     this.setState({ isReady: true }, () => {
       if (onMapReady) {
-        onMapReady();
+        onMapReady(this);
       }
     });
   }
```

**Comment by betoharres** [comment]
you can read further details about this here: https://github.com/react-native-maps/react-native-maps/pull/1369#discussion_r429042230

**Comment by PrinzessBard** [comment]
mapRef.current.routeBetween

**Comment by PrinzessBard** [comment]
mapRef.current.routeBetween

У меня выдается что это undefined, хотя я все делал по инструкции.

**Comment by PrinzessBard** [comment]
TypeError: mapRef.current.routeBetween is not a function (it is undefined), js engine: hermes

I get an undefined message, even though I did everything according to the instructions.
Does this method still exist?
