### ISSUE TITLE
Readjustable Nodes for Polygon

### ISSUE THREAD

**Issue by senakvkc** [react-native-maps/react-native-maps#3077]
# Question

Hey there,
I'm pretty new with React Native and all the stuff it provides. Firstly thanks for all the efforts put into this. 

Currently, I'm working with Polygon components and what I have in my mind is to select an area on the map, as I can do it now, but also I want to be able to click the nodes of the polygon and readjust them. I wonder if it's possible, or it's not a feature yet.

Thanks in advance.

**Comment by nes123** [comment]
+1
