### ISSUE TITLE
Unable to interact with screen after pin place

### ISSUE THREAD

**Issue by alexborton** [react-native-maps/react-native-maps#3078]
# Bug

I have a map on a screen with a couple of other elements, all of which respond to touch. I am interacting with the map in a few ways - one is `onLongPress`. 

When i handle `onLongPress`, i drop/update the pin location. After this, i am unable to interact with the rest of the screen (other than the map itself) _until_ i move the map again. 

## Environment info

expo: `v33.0.0`
react-native-maps: `^0.24.2`
react-navigation: `^3.11.0` (could be relevant...)

## Steps To Reproduce

1. open/navigate to screen.
2. long-press map to place pin/update region
3. try to tap outside of map (buttons)
4. move map (scroll/pan/anything)
5. try to tap outside map (buttons)

Describe what you expected to happen:

The buttons should be available after placing/updating pin location

## Reproducible sample code

```
import React, { useState } from 'react'
import PropTypes from 'prop-types'
import { get } from 'lodash'
import { View, TouchableOpacity } from 'react-native'
import MapView from 'react-native-maps'

const styles = {
  map: {
    flex: 1,
    marginBottom: 20,
  },
}

const ReportManualLocationForm = () => {
  const [droppedPin, setDropperPin] = useState({
    coordinate: null,
  })
 
  const handleMovePin = e => {
    const { coordinate } = e.nativeEvent
    setDropperPin({
      coordinate: {
        lat: coordinate.latitude,
        lng: coordinate.longitude,
      },
    })
  }

  const handleSubmit = () => {
    console.warn('do something...') 
  }

  const getLocation = () => {
    const droppedPinLocation = get(droppedPin, 'coordinate')

    if (droppedPinLocation) {
      return {
        lat: droppedPinLocation.lat,
        lng: droppedPinLocation.lng,
      }
    }

    return false
  }

  return (
    <>
      <MapView
        style={styles.map}
        region={{
          latitude: getLocation() ? getLocation().lat : 51.5074,
          longitude: getLocation() ? getLocation().lng : -0.1277,
          latitudeDelta: getLocation() ? 0.005 : 0.5,
          longitudeDelta: getLocation() ? 0.005 : 0.5,
        }}
        provider="google"
        rotateEnabled={false}
        pitchEnabled={false}
        onLongPress={handleMovePin}
      >
        {getLocation() ? (
          <MapView.Marker
            coordinate={{
              latitude: getLocation().lat,
              longitude: getLocation().lng,
            }}
            draggable
            onDragEnd={handleMovePin}
            tracksViewChanges={false}
          />
        ) : null}
      </MapView>
      <TouchableOpacity onPress={handleSubmit}>
        SUBMIT
      </TouchableOpacity>
    </>
  )
}

ReportManualLocationForm.propTypes = {
  navigation: PropTypes.object.isRequired,
}

export default ReportManualLocationForm
```

I have ripped out some of the additional hooks that i am running for simplicity. `getLocation` will return an object with coordinates based on either a search result or the manual input as seen in the example. I don't imagine with would make any difference.

**Comment by getterhiss** [comment]
@alexborton - I found a fix that worked for me _(wasn't able to click buttons after marker onDragEnd event)._ 

Try importing TouchableOpacity from `react-native-gesture-handler` instead of `react-native` package for your buttons. Reference - https://github.com/react-native-maps/react-native-maps/issues/3053#issuecomment-771475443

**Comment by verochan** [comment]
The following fix worked for me too:

https://github.com/react-native-maps/react-native-maps/issues/3053#issuecomment-869498626
