### ISSUE TITLE
TapZoom stop work

### ISSUE THREAD

**Issue by NeRo8** [react-native-maps/react-native-maps#3079]
# Question

Hello. I have a zoom problem. When I make a zoom with a touch, the function onRegionChangeComplete changes the region, it wants to draw a region on the map, but since I zoom, the map just freezes.
```
<MapView
  region={this.state.region}
  onRegionChangeComplete={(newRegion) => this.setState({region: newRegion})}
>

```

**Comment by andrewtelkamp** [comment]
Do you have a reason for explicitly controlling the region? Sounds like `initialRegion` would be a better solution.
