### ISSUE TITLE
Add disabling scroll gestures during zoom

### ISSUE THREAD

**Issue by AleksandrZhukov** [react-native-maps/react-native-maps#3080]
# Feature Request

Some time ago Google added a feature for disabling scroll while zooming the map.
Here is a release notes https://developers.google.com/maps/documentation/android-sdk/releases#february_6_2019. 
Will be very nice to add this flag to react-native-maps.

**Comment by ankit5174** [comment]
Is there any solution or hack which we can do to achieve the above? @AleksandrZhukov

**Comment by littleJmer** [comment]
@ankit5174 
Did you find how to do it?

**Comment by EvgeniyPavlichenkov** [comment]
@ankit5174 
@littleJmer 
@AleksandrZhukov 

I found the solution. I use 0.24.2

For iOS:

- Open `node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMap.m`
- Find the `didPrepareMap` method
- Change like this:
`if (_didCallOnMapReady) return;`
` _didCallOnMapReady = true;`
`if (self.onMapReady) self.onMapReady(@{});`
`self.settings.allowScrollGesturesDuringRotateOrZoom = false;` // <--- Add this line
- Restart your app from Xcode

For Android:

- Open `node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java`
- Find the `onMapReady` method
- Change like this:
`this.map = map;`
`this.map.setInfoWindowAdapter(this);`
`this.map.setOnMarkerDragListener(this);`
`this.map.setOnPoiClickListener(this);`
`this.map.setOnIndoorStateChangeListener(this);`
`this.map.getUiSettings().setScrollGesturesEnabledDuringRotateOrZoom(false);` // <--- Add this line
- Restart your app with `npx react-native run-android`


Then you can use `patch-package` to create the patch and use it for `postinstall` script.

Let me know if it helps :)
