### ISSUE TITLE
is it possible to to restrict the map bounds?

### ISSUE THREAD

**Issue by sincraianul** [react-native-maps/react-native-maps#3085]
### Is this a bug report?

No.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

Using Expo SDK35, react-native-maps 0.25.0.

### Steps to Reproduce

I know it's possible to do it with the [JavaScript API](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/control-bounds-restriction), but I didn't see any info related to this in the docs.

**Comment by elodieirdor** [comment]
Did you find a way of doing it ?

**Comment by Mohammed-Yasin-Mulla** [comment]
@sincraianul Did you find an answer to this question, would be grateful if you could share it 🙂

**Comment by irg1008** [comment]
🗿
