### ISSUE TITLE
How to set background color on mapview overflow

### ISSUE THREAD

**Issue by kkemple** [react-native-maps/react-native-maps#3086]
# Question

I've checked the web and come up empty handed. Is there a way to change the background color of the mapview when you pass the edge of the map?

<img width="263" alt="Screen Shot 2019-09-24 at 9 50 06 AM" src="https://user-images.githubusercontent.com/3629876/65519771-86e2c980-deb4-11e9-955c-8b7a9ad84d49.png">

Notice the grey at the top.

I'm fitting map to all elements on load with `mapView.fitToElements()`. Then the map pans around swiping cards. Because the map can be so zoomed out to accommodate markers across the globe the map doesn't cover the whole screen but I can't find a way to change that default grey color, ideally I would set it to the water color of the custom map.

Let me know if any of this is unclear or you need more explanation and thanks so much for this awesome library! I'm always impressed by it.

**Comment by cormander** [comment]
What UI framework are you using? In NativeBase this is known as a transparent header:

https://docs.nativebase.io/Components.html#header-transparent-headref

**Comment by kkemple** [comment]
They grey is not there all the time, only when the map is moved to a position where the marker is near the top.

<img width="267" alt="Screen Shot 2019-09-26 at 2 31 04 PM" src="https://user-images.githubusercontent.com/3629876/65883263-aec6a700-e364-11e9-8ef7-cd24f899ff54.png">

As you can see in this screenshot it's fully covering the screen. I need to set a background color on the native map view.

**Comment by rborn** [comment]
I tried to look into the native code how to set this and I'm not sure it's exposed in any way. 
But I'm not good on native so I might be wrong :(

**Comment by kkemple** [comment]
Thanks for looking into it. For now I'm not showing all pins and keeping the zoom level low enough to prevent the bleeding background. I'll dig deeper as well.

**Comment by afzal-ali27** [comment]
Hi any update on this? I want to change background color of MapView in React Native

**Comment by Inayat567** [comment]
> # Question
> I've checked the web and come up empty handed. Is there a way to change the background color of the mapview when you pass the edge of the map?
> 
> <img alt="Screen Shot 2019-09-24 at 9 50 06 AM" width="263" src="https://user-images.githubusercontent.com/3629876/65519771-86e2c980-deb4-11e9-955c-8b7a9ad84d49.png">
> 
> Notice the grey at the top.
> 
> I'm fitting map to all elements on load with `mapView.fitToElements()`. Then the map pans around swiping cards. Because the map can be so zoomed out to accommodate markers across the globe the map doesn't cover the whole screen but I can't find a way to change that default grey color, ideally I would set it to the water color of the custom map.
> 
> Let me know if any of this is unclear or you need more explanation and thanks so much for this awesome library! I'm always impressed by it.

just use this mapCustomStyle to change default light mode of mapView to dark mode:


const mapCustomStyle  = [
  {
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#242f3e"
      }
    ]
  },
  {
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#746855"
      }
    ]
  },
  {
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "color": "#242f3e"
      }
    ]
  },
  {
    "featureType": "administrative.locality",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#d59563"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#d59563"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#263c3f"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#6b9a76"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#38414e"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#212a37"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9ca5b3"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#746855"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#1f2835"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#f3d19c"
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#2f3948"
      }
    ]
  },
  {
    "featureType": "transit.station",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#d59563"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#17263c"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#515c6d"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "color": "#17263c"
      }
    ]
  }
]


and Finally in mapView 


use customMapStyle= {mapCustomStyle}


Thanks to https://mapstyle.withgoogle.com/ site I have generated above code from this side

**Comment by JoshMcCullough** [comment]
I'm also looking for an answer here and I don't think the previous comment is what I need. I'm looking to change the white area around the map to some other color: 

![Image](https://github.com/user-attachments/assets/9c4fc0b1-c508-4449-8ac5-959d9d588c19)

**Comment by Inayat567** [comment]
> I'm also looking for an answer here and I don't think the previous comment is what I need. I'm looking to change the white area around the map to some other color:
> 
> ![Image](https://github.com/user-attachments/assets/9c4fc0b1-c508-4449-8ac5-959d9d588c19)

You can use the above map style configuration and apply whichever color you want to apply to the background.

**Comment by JoshMcCullough** [comment]
Since I'm overlaying a custom GeoJSON, the map style doesn't seem to work. I set up a [custom map style / map](https://console.cloud.google.com/google/maps-apis/studio/styles), and set the water and base to a different background color, but my map still shows as white. 

Here's my map:

```react
        <MapView
          style={styles.map}
          region={country.region}
          scrollEnabled={false}
          zoomEnabled={false}
          pitchEnabled={false}
          rotateEnabled={false}
          mapType={isReady ? "none" : "standard"}
          loadingBackgroundColor={getCurrentColorScheme().background}
          userInterfaceStyle={getCurrentColorSchemeName()}
          onMapReady={() => setIsReady(true)}
        >
          <Geojson geojson={geojson} />
        </MapView>
```

And my `styles`:

```react
const styles = StyleSheet.create({
  map: {
    width: Dimensions.get("window").width,
    height: "30%",
    backgroundColor: getCurrentColorScheme().background, // E.g. not white.
  },
});
```

And the [GeoJSON](https://github.com/user-attachments/files/23435339/US.json) I'm using.

**Comment by Nelson-Christensen** [comment]
I've found that it works well to circumvent the issue with the white strip at the top by using the `mapPadding` prop combined with a negative marginTop.
For example for my use case I wanted it outside of the safe area, so I used:
```tsx
<MapView
  style={{
    marginTop: -insets.top
  }}
  mapPadding={{ top: insets.top, right: 0, bottom: 0, left: 0 }}
>
```
