### ISSUE TITLE
 Could not resolve all dependencies for configuration

### ISSUE THREAD

**Issue by mjy12** [react-native-maps/react-native-maps#3089]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-maps'.
      > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompileCopy'.
         > Could not find androidx.appcompat:appcompat:1.0.2.
           Required by:
               myapp:react-native-maps:unspecified > com.facebook.react:react-native:0.61.1

**Comment by cormander** [comment]
This is resolved by https://github.com/react-native-community/react-native-maps/pull/3020 which isn't in a release yet.

My workaround is using [patch-package](https://www.npmjs.com/package/patch-package) with the following patch file: https://github.com/OurVoiceUSA/HelloVoter/blob/14857376632ab5dcb165e34e40f2b7ceb8906e3c/mobile/patches/react-native-maps%2B0.25.0.patch

Hope that helps.
