### ISSUE TITLE
Reaching coordinate values

### ISSUE THREAD

**Issue by senakvkc** [react-native-maps/react-native-maps#3091]
# I can't reach the coordinate values 

So I'm trying to create a function to delete all the coordinates of previously selected places. Basically the main purpose for that function is to erase the polygons I've created.

`console.log(this.props.coordinates);`

I'm trying to print out the coordinates with this line but it's returning me an "undefined" message. Am I doing something wrong?

Thanks in advance.

**Comment by NguyenPhuong1907** [comment]
Hi @senakvkc 
When created places and you have a marker, if you don't save marker here to **ref** ( **ref={marker => this.markerRef = marker}**). You will can't delete marker or show coordinate of marker.
So. What you need to do now is save places you created
