### ISSUE TITLE
Support for Apple Maps logo insets

### ISSUE THREAD

**Issue by Jazqa** [react-native-maps/react-native-maps#3092]
# Bug

iOS 13 adds a new Apple Maps logo to the bottom left corner of the map (equivalent of the Google logo in Google Maps). While `legalLabelInsets` makes moving the Legal disclaimer possible, there's no equivalent for moving the new Apple Maps logo (or the Google Maps logo for that matter)

## Steps To Reproduce

1. Update XCode
2. Build

Describe what you expected to happen:

1. A new prop should be added for setting the insets for the Apple Maps logo (if possible, moving the Google Maps logo with the same prop would be a plus)

**Comment by toshe** [comment]
https://forums.developer.apple.com/thread/119080 

It seems that the view responsible for the Apple Maps logo `MKAppleLogoImageView` cannot be moved. 

Here are the newest guidelines from Apple regarding this:
https://developer.apple.com/design/human-interface-guidelines/maps/overview/introduction/

**Comment by vvscode** [comment]
@toshe @ssztemberg  I use `0.27.1` but map padding doesn't affect maps logo

Simulator is on iPhone 8/ 13.7

**Comment by toshe** [comment]
Have you tried compiling with the Patch directly (downgrading)? Maybe something happened in the newer versions of iOS. @creat-or does the Apple Maps logo appear on iOS 14?
