### ISSUE TITLE
Flickering of markers & markers keeps on changing position

### ISSUE THREAD

**Issue by christopher-18** [react-native-maps/react-native-maps#3098]
Will the new release of react-native-maps, fixes the marker flickering and markers changing their position intermittently ?

**Comment by YeshanJay** [comment]
@chris-topher19 
Try setting `tracksViewChanges` to `false` in the `<Marker />` component.

**Comment by darran-kelinske-fivestars** [comment]
tracksViewChanges didn't fix the custom marker flicker for me on iOS

**Comment by jqtruong** [comment]
`tracksViewChanges={false}` definitely seems to work on Android.

**Comment by Matt-Tee** [comment]
tracksViewChanges={false} definitely didn't work for me on Android

**Comment by 18bhavna** [comment]
@jqtruong `trackViewChanges={false}` didn't worked for me. Markers are still changing the position.

**Comment by danfercf1** [comment]
trackViewChanges={false} It is works for me for:
react-native-maps@0.26.1

**Comment by misterchlee7** [comment]
I've had issues where markers would flicker/teleport all over the map on Android - Google Maps only. I've tried `trackViewChanges={ false }` and also generating each marker on the map with a different zIndex with no luck.

However, setting `liteMode` props as true on MapView fixed the issue on Android.

on react-native-maps@0.24.2

**Comment by chris-topher19** [comment]
I tried using liteMode  to true in android, and flickering of markers is gone. But when on touching the markers, the action specified on it is not working.

**Comment by shyamalVixplor** [comment]
> `trackViewChanges={false}` It is works for me for:
> react-native-maps@0.26.1

Thank you.It works like a charm :)

**Comment by lyseiha** [comment]
Any update on this issues?

**Comment by GeronimoKTT** [comment]
> 
> 
> > `trackViewChanges={false}` It is works for me for:
> > react-native-maps@0.26.1
> 
> Thank you.It works like a charm :)

**Also worked for me in react-native-maps@0.27.1**

**Comment by codeapp17** [comment]
@YeshanJay markers not showing after trackviewchange={false}

**Comment by codeapp17** [comment]
@misterchlee7 but after litemode={true}, user not able to move map or zoom map

**Comment by ilyabreev** [comment]
As mentioned above `liteMode` is not an option because we loose ability to zoom, move and custom markers actions.

`tracksViewChanges` just hides custom markers. So this is also not an option.

Still an issue for me when map displayed full screen.

**Comment by sapirshloush** [comment]
Any update on this issues? all the suggestion here are not helpful.
Does anyone know how to solve this problem?

**Comment by spacesuitdiver** [comment]
I feel like a zIndex is in needed. Also what are the drawbacks of using `tracksViewChanges`. It's not entirely clear what that prop even does.

**Comment by barnu5** [comment]
In the goal of a zoomable map with custom markers, the suggested solutions are not effective.

**Comment by barnu5** [comment]
Might fix your issueIf two markers overlap and are flickering, give them unique zindex:

```
[a,b,c].map((item, i) => <Marker zIndex={i} /> .....
```

**Comment by ninobc** [comment]
For anyone seeing their markers flicker upon selection (if you change its style when selecting it), make sure you don't have two markers overlapped at the same exact position. I had this weird flickering issue and spent an hour trying to figure out what was going on, turns out I duplicated my dummy data and had two markers overlapped in every position 😂

**Comment by williamswebworks** [comment]
Did we come up with a firm solution on this issue? I have custom markers on my maps and they keep flickering and moving location

**Comment by sgrishanin** [comment]
I have this issue as well. It seems to me that the marker flickers only if there's an image - if I render it with a styled View inside it works just fine. Manually passing <Image/> component as a child doesn't help though. Might be helpful to narrow down the issue.

**Comment by zac18992** [comment]
My marker images are also flickering all over the place at certain zoom levels, at least on Android. None of the suggested solutions solve the issue.

**Comment by LevMartens** [comment]
My markers were flickering too. What fixed it for me was taking my markers out of a React.Fragment component:
`<MapView>
         // Before
         <React.Fragment>
          {this.props.lineMarkersHandler}
        </React.Fragment> 

        // After
        {this.props.lineMarkersHandler}
</MapView>`

**Comment by LevMartens** [comment]
My markers were flickering too. What fixed it for me was taking my markers out of a React.Fragment component:
`<MapView>

// Before
<React.Fragment>
{this.props.lineMarkersHandler}
</React.Fragment>

// After
{this.props.lineMarkersHandler}

</MapView>`

**Comment by LevMartens** [comment]
My markers were flickering too. What fixed it for me was taking my markers out of a React.Fragment component:


`// Before
<React.Fragment>
{this.props.lineMarkersHandler}
</React.Fragment>

// After
{this.props.lineMarkersHandler}`

**Comment by LevMartens** [comment]
My markers were flickering too. What fixed it for me was taking my markers out of a React.Fragment component:

```
<MapView>

    // Before
    <React.Fragment key={1}>
          {this.props.lineMarkers}
     </React.Fragment> 

     // After
      {this.props.lineMarkers}

</MapView>
```

**Comment by charlie4284** [comment]
Hey guys, if it's still relavant, some of you may be facing this issue due to rerendering of the markers.
My use case was that I had to render a set of markers on a viewing position and then load a new set of positions when the maps view changes.
This meant that my array would be reassigned from a new state and would trigger the whole array to be re-rendered on the map, causing the markers to flicker.
In order to solve that, I used a react `useRef` to to have a set of current markers that are being displayed, and used another `forceUpdate` state to trigger re-render.
Please see the code below, it would probably help! However, due to copying of arrays and frequent splicing, it's quite expensive and is not recommended unless it's absolutely necessary!

```
const currentMarkersRef = useRef([]);

useEffect(() => {
    const newMarkerIDs = new Set(incomingMarkers.map(marker => marker.id));
    const existingMarkerIDs = new Set(
      currentMarkersRef.current.map(marker => marker.id),
    );

    let removedCount = 0;
    const currentMarkersClone = [
      ...currentMarkersRef.current.map(marker => marker.id),
    ];
   // FILTER EXISTING MARKERS
    currentMarkersClone.forEach((markerId, prevIndex) => {
      if (!newSpotIDs.has(markerId)) {
        currentMarkersRef.current.splice(prevIndex - removedCount, 1);
        removedCount++;
      }
    }, []);
  // ADD NEW MARKERS
    incomingMarkers.forEach(marker => {
      if (existingSpotIDs.has(marker.id)) {
      } else {
        currentMarkersRef.current.push(spot);
      }
    });
    setForceRender(true);
  }, [incomingMarkers]);
  ```

**Comment by FrSenpai** [comment]
Still an issue on expo 48.0.15 && react-native 0.71.7 (with rn maps 1.3.2)

**Comment by PauloGrachetelli** [comment]
same here, after updating RN to 0.72.4

**Comment by MuhammadShahidRaza** [comment]
Any update on that issue?

**Comment by SathishSaminathan** [comment]
Still facing flickering issue @salah-ghanim

**Comment by PauloGrachetelli** [comment]
> Still facing flickering issue @salah-ghanim
> 
>  WhatsApp.Video.2024-01-09.at.7.23.18.PM.mp4

try to remove this rows

  implementation 'com.google.android.gms:play-services-base:17.2.0'
  implementation 'com.google.android.gms:play-services-maps:+'

**Comment by SathishSaminathan** [comment]
> > Still facing flickering issue @salah-ghanim
> > WhatsApp.Video.2024-01-09.at.7.23.18.PM.mp4
> 
> try to remove this rows
> 
> implementation 'com.google.android.gms:play-services-base:17.2.0' implementation 'com.google.android.gms:play-services-maps:+'
> 
> from android/build.gradle

<img width="715" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/30047638/30ea2982-37c8-44fc-9892-104b27e63160">


<img width="724" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/30047638/db417b14-e869-4eaa-abef-1a1da3043d4f">


I didn't add these lines @PauloGrachetelli

**Comment by NirmalsinhGlasier** [comment]
Still facing this issue on zoom-in /zoom-out

**Comment by andrecrimb** [comment]
Same issue...

**Comment by PauloGrachetelli** [comment]
Try to use 1.8.0 version

**Comment by andrecrimb** [comment]
I'm on 1.11.3 and the issue persists.

**Comment by mattlewer** [comment]
> I'm on 1.11.3 and the issue persists.

> version 1.8.0 solves the issue

Which one to believe 👁️ 👁️

**Comment by kyrylo-ice** [comment]
> Might fix your issue: If two markers overlap and are flickering, give them unique zindex:
> 
> ```
> [a,b,c].map((item, i) => <Marker zIndex={i} /> .....
> ```

thank you SO MUCH

**Comment by Akshay340-mob** [comment]
updating to the latest version(1.15.6) and adding googleRenderer='LEGACY' resolved my issue.

**Comment by ssommelet21** [comment]
> updating to the latest version(1.15.6) and adding googleRenderer='LEGACY' resolved my issue.

How it is possible ?
If you read : https://developers.google.com/maps/documentation/android-sdk/release-notes

"**Because we will be decommissioning the legacy map renderer, the MapsInitializer.Renderer.LEGACY value for the [MapsInitializer.initialize()](https://developers.google.com/android/reference/com/google/android/gms/maps/MapsInitializer) method in the Maps SDK for Android is deprecated as of Maps SDK for Android v19.0.0.**"

the Release 19.0.0, was at June 25, 2024 
Could you please, try to update Google Maps (with Play Store) ?

**Comment by rushant11** [comment]
> @chris-topher19 Try setting `tracksViewChanges` to `false` in the `<Marker />` component.

but if you are using a custom marker with animation, then the animation will not work after doing `tracksViewChanges` to `false`.

**Comment by x64Bits** [comment]
Setting `zIndex` to my marker fixes the flickering, I'm just rendering a marker on my map and it kept flickering but this fixed it

**Comment by x64Bits** [comment]
Setting zIndex to my marker fixes the flickering, I'm just rendering a marker on my map and it kept flickering but this fixed it, thanks! 🙌🏼

> Might fix your issue: If two markers overlap and are flickering, give them unique zindex:
> 
> ```
> [a,b,c].map((item, i) => <Marker zIndex={i} /> .....
> ```

**Comment by hiThilinaW** [comment]
> @chris-topher19 Try setting `tracksViewChanges` to `false` in the `<Marker />` component.

Thank you boss
