### ISSUE TITLE
How to get onPress event of multiple touchable components that are placed inside the view of custom Marker or Callout?

### ISSUE THREAD

**Issue by TopsMayur** [react-native-maps/react-native-maps#3121]
# Question
I am trying to place 2 touchable components inside the custom view of a Marker and Callout. I am not able to get the onPress events of the 2 individual touchable components. I get the onPress of the marker and callout but I cannot get the onPress of the individual touchable component.

Is there a way I can get the onPress event of each touchable component placed inside the custom view?

I use  react-native-maps v0.24.2, react-native v0.59.9

**Comment by vanhungoz** [comment]
> https://github.com/react-native-community/react-native-maps/blob/master/docs/callout.md#calloutsubview--component-api
 you can check it

**Comment by vanhungoz** [comment]
only supported on ios

**Comment by pushkarva** [comment]
can anyone please help me out here? I have the same problem. I want a onPress event inside my custom marker on Android for now. Is there any way i can get that??

**Comment by dzpt** [comment]
I think this is the must-have feature, that's ridiculous when you can fire only one event on `Callout`.
