### ISSUE TITLE
Draw an Arc from center of some coordinates of some radius

### ISSUE THREAD

**Issue by sam17896** [react-native-maps/react-native-maps#3143]
# Question

How can i use `MapView.Circle` to draw an arc rather than full circle from a certain point of some radius.

The desire result: 
![image](https://user-images.githubusercontent.com/24951758/67156787-9b43a600-f33c-11e9-8f83-eb6ab3124e17.png)

related stackoverflow question :
https://stackoverflow.com/questions/58470250/how-to-resize-shapes-drawn-on-map-based-on-zoom-value-with-react-native-maps

**Comment by ekifox** [comment]
Upd...

**Comment by longomidexinc** [comment]
+1

**Comment by byyoungjin** [comment]
+1
