### ISSUE TITLE
Fill color doesn't work on Polygon with self-intersection point on Android

### ISSUE THREAD

**Issue by bargald** [react-native-maps/react-native-maps#3148]
# Bug

Fill color doesn't work on Polygon with self-intersection point on Android but works on iOS.

![Android - white polygon in the middle, not fiiled](https://user-images.githubusercontent.com/22773345/67304473-8c0b5680-f4fc-11e9-8f06-da48af653668.jpg)

![ios - green polygon](https://user-images.githubusercontent.com/22773345/67304539-a7766180-f4fc-11e9-87e2-ac6748e02f6a.jpg)

## Environment info

RN - 0.59.2
React-native-maps - latest master branch.

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 166.13 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.11.1 - ~/.nvm/versions/node/v12.9.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2
```

Library version: v0.26.1

## Steps To Reproduce

1. create a Map.Polygon component, pass a polygon with a self-intersection for coordinates. and any fill color.
2. run on device or emulator.

Describe what you expected to happen:

1. the polygon should render on the map with given fill color on Android as well as on iOS.

## Reproducible sample code
self intersecting polygon example:

```
[
    {
        "lat" : 33.9920610414009,
        "lng" : -118.468874004874
    },
    {
        "lat" : 33.9904867909688,
        "lng" : -118.469174517609
    },
    {
        "lat" : 33.9905245430615,
        "lng" : -118.466747649747
    },
    {
        "lat" : 33.9922346978782,
        "lng" : -118.467057268791
    },
    {
        "lat" : 33.9919477869478,
        "lng" : -118.466592840017
    },
    {
        "lat" : 33.9920610414009,
        "lng" : -118.468874004874
    }
]

```

**Comment by mattias-persson** [comment]
Likely related to #3146?

**Comment by Mubashirkhan** [comment]
any update on this issue. Still reproducible on android with the latest version "0.29.3"
