### ISSUE TITLE
Callout jumps when marker is clicked - Android

### ISSUE THREAD

**Issue by abhinavpadala** [react-native-maps/react-native-maps#3150]
# Bug
Each Callout shows the names of things. When a marker is clicked, the callout of that marker jumps to the nearest marker. I am facing this issue on an Android device.

## Environment info
  React Native Environment Info:
      npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
 
    "react-native-maps": "^0.24.2"

The issue is similar to this issue - https://github.com/react-native-community/react-native-maps/issues/3047

Many people mentioned that they are facing this issue only on IOS but not on Android. Is there a workaround to fix this? :)

**Comment by ryanjorgensen** [comment]
I did find that the `pointerEvents="auto"` suggestion mentioned in #3047 fixed it for me.

**Comment by abhinavpadala** [comment]
I tried this:
<Marker pointerEvents="auto">
...
</Marker>
It is not working in my case.

**Comment by abhinavpadala** [comment]
I tried this:
`<Marker pointerEvents="auto" >
   ....
  </Marker>`

It is not working in my case.
