### ISSUE TITLE
Pan map (scroll) by pixel programmatically

### ISSUE THREAD

**Issue by Annihil** [react-native-maps/react-native-maps#3152]
# Question

Hi, I would like to know how could I achieve something similar to the JS Web SDK
```javascript
map.panBy(0, -90);
```
In this case, it would move the map south by 90px.

Or like the [Android Java SDK](https://developers.google.com/maps/documentation/android-sdk/views#panning_scrolling)
```java
CameraUpdateFactory.scrollBy(float, float)
```

Or like the [iOS Swift SDK](https://developers.google.com/maps/documentation/ios-sdk/views#updating_the_camera_view)
```swift
// Move the camera 100 points down, and 200 points to the right.
let downwards = GMSCameraUpdate.scrollBy(x: 100, y: 200)
mapView.animate(with: downwards)
```

**Comment by rborn** [comment]
You might wanna try to use `coordinateForPoint` to convert the point you want to scroll to to coordinates and then move the map.

**Comment by Annihil** [comment]
I tried and it's not reliable across platforms alas ...

**Comment by ZaidSA** [comment]
Any better solution on this? @Annihil @rborn
