### ISSUE TITLE
React native maps 0.26.1 error polyline?

### ISSUE THREAD

**Issue by nvkgismt** [react-native-maps/react-native-maps#3157]
# Bug

## Environment info

"react": "16.8.6",
   "react-native": "0.60.5",

React native info output:

```bash
 // paste it here
```

Library version: 0.26.1

## Steps To Reproduce

 <Polyline
        key= '1'
        coordinates={props.coordinates}
        strokeColor="blue"
        fillColor="blue"
        strokeWidth={1}
    />

Describe what you expected to happen:
The software cannot run

**Comment by mattias-persson** [comment]
@nvkgismt You have to provide more details than this. "The software cannot run" is not enough. Also provide steps to reproduce and the follow the rest of the issue tracker if you want anyone to take a look at this.
