### ISSUE TITLE
fillColor ignored in device ios for MapView.Circle

### ISSUE THREAD

**Issue by sam17896** [react-native-maps/react-native-maps#3173]
# Bug
fillColor property seemed to be ignored while running map on actual device. It is working fine on latest version of ios in simulator but when working with the actual physical device the colors doesn't fill up in the circles. Below are the screenshot

![image](https://user-images.githubusercontent.com/24951758/68151267-2c349700-ff63-11e9-869d-285d0164f4f8.png)
![image](https://user-images.githubusercontent.com/24951758/68151285-348cd200-ff63-11e9-99ea-b6a4c0c0ea16.png)

## Environment info

React native info output:
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 358.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version:0.26.1

## Steps To Reproduce
1. Add the code below
```

<MapView.Circle
                key = { (location.latitude + index + location.longitude).toString() }
                center = { center }
                radius = { x.radius }
                strokeWidth = { 1 }
                strokeColor = { x.color }
                fillColor = { x.color }
              />)
```

Describe what you expected to happen:

1. fillColor and strokeColor should work as it is working on simulator

**Comment by bubble-hook** [comment]
i got same issue 
  ><

**Comment by rborn** [comment]
Try this maybe? https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-538345230

**Comment by crocodile** [comment]
Same issue. Using react-native-maps 0.26.1

**Comment by sam17896** [comment]
> Try this maybe? [#3025 (comment)](https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-538345230)

Tried this commit, fix the issue on temporary basis but on some instance and on some devices this approach still doesn't work.

**Comment by gusilveiramp** [comment]
Same here...

**Comment by doraeminemon** [comment]
Still occuring on iOS simulator ( iPhone 8 Plus )

**Comment by oscarcornejo** [comment]
Same problem!
Any solution? 🙄

**Comment by Nishant-goibibo** [comment]
Same problem!
Any solution?

**Comment by rejjer** [comment]
This solutions: [fix in render for Polygon](https://github.com/react-native-maps/react-native-maps/issues/3025#issuecomment-522968087) and [fix in library for Polygon](https://github.com/react-native-maps/react-native-maps/pull/3309/files) is works.

**Comment by safwanAzman** [comment]
Same problem!
Any solution?

**Comment by GuillermOsuna** [comment]
Same problem! 😣
Any solution?

**Comment by GuillermOsuna** [comment]
Hi, I resolved this issue making an setInterval per Circle, something like this:

`const interval = setInterval(() => {
            this.circle.setNativeProps({
                fillColor: this.props.fillColor,
                strokeColor: this.props.strokeColor,
            })
            clearInterval(interval)
        }, 10)
 `
 If you have to create a lot of Circles you can create an component to render Circles
 
 `
 import React, { Component } from 'react'
import { Circle } from 'react-native-maps'
interface Props {
    center: {
        latitude: number,
        longitude: number
    }
    radius: number
    fillColor: string
    strokeColor: string
    strokeWidth: number
    onPress?: Function
}
class CircleComponent extends Component<Props> {
    circle: any
    state = {

    }
    componentDidMount() {
        const interval = setInterval(() => {
            this.circle.setNativeProps({
                fillColor: this.props.fillColor,
                strokeColor: this.props.strokeColor,
            })
            clearInterval(interval)
        }, 10)
    }
    onPress() {
        if (this.props.onPress) {
            this.props.onPress()
        }
    }
    render() {
        this.onPress = this.onPress.bind(this)
        return (
            <Circle
                ref={ref => { this.circle = ref; }}
                center={this.props.center}
                radius={this.props.radius}
                fillColor={this.props.fillColor}
                strokeColor={this.props.strokeColor}
                strokeWidth={this.props.strokeWidth}
                onPress={this.onPress}
            />
        )
    }
}

export default CircleComponent
 `
 
 then import this component on the map:
 
 `
 render() {
        return (
            <View style={styles.containerFullWidth}>
                    <MapView
                        provider={PROVIDER_GOOGLE}
                        style={styles.mapStyle}
                        zoomEnabled={true}
                        moveOnMarkerPress={true}
                        region={{
                            latitude: this.state.mapLat,
                            longitude: this.state.mapLng,
                            latitudeDelta: 0.0600,
                            longitudeDelta: 0.0600

                        }}
                        mapType="standard"
                        onMapReady={() => {
                            this.circles()
                        }}
                    >
                        {
                            this.state.circles.map((item, index) => {
                                const color = item.color
                                return (
                                    <CircleGeofence
                                        key={index}
                                        center={{
                                            latitude: item.latitude,
                                            longitude: item.longitude
                                        }}
                                        radius={geofence.radius}
                                        fillColor={color}
                                        strokeColor={geofence.color}
                                        strokeWidth={3}
                                    />
                                )
                            })
                        }
                    </MapView>
            </View>
        )
    }
 `
 
 I hope it helps you!
