### ISSUE TITLE
edgePadding does not work when using fitToSuppliedMarkers in iOS

### ISSUE THREAD

**Issue by mmacartney10** [react-native-maps/react-native-maps#3182]
# Bug

```
    const mapOptions = {
      animated: true,
      edgePadding: {
        top: 100,
        right: 100,
        bottom: 800,
        left: 100
      },
    };

    _mapView.fitToSuppliedMarkers(markerIDs, mapOptions);
```
Above is my code. It correctly fits to show the list of markers. What I want to do i make it so that it fits the markers in the top half of the screen. I thought that edgePadding would solve this issue but it doesn't seem to change anything.

## Environment info
    "react-native": "0.61.2",
    "react-native-maps": "git+https://git@github.com/react-native-community/react-native-maps.git"

**Comment by shiftrtech** [comment]
Same to me, @mmacartney10 did you find a solution?

**Comment by shiftrtech** [comment]
I wrap the `_mapView.fitToSuppliedMarkers(markerIDs, mapOptions);` on `setTimeOut`, still the issue

**Comment by mhluska** [comment]
Why are these issues being closed? I am still experiencing this with the latest version.

**Comment by habiiev** [comment]
I have this issue on android only, on iOS it works as I expected, any idea how we can fix it?

**Comment by AizenSousuke** [comment]
I'm having this issue too..
