### ISSUE TITLE
iOS 13 Apple Maps Polyline Flicker on Coordinate Updates

### ISSUE THREAD

**Issue by ryansommers** [react-native-maps/react-native-maps#3184]
# Bug
In iOS 13, when an Apple Map (haven't tested Google) updates Polyline coordinates, the polylines flash. This doesn't happen in iOS 12. 

Video link showing flash: https://www.dropbox.com/s/5ugessg5na0gjhw/ios%2013%20polyline%20flash.mp4?dl=0

The video shows updating the user location with updated polyline coordinates every 1 second.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 54.32 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5199772
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.26.1

## Steps To Reproduce

1. Update map with new Polyline coordinates.
...

Describe what you expected to happen:

1. The polylines shouldn't flash on update.

**Comment by sam17896** [comment]
+1

**Comment by meikoudras** [comment]
Same issue here:

https://drive.google.com/file/d/1_NskJ4AN9xFVfiH632yRsE8bISKImJVQ/view

With iOS version 13.2.3

**Comment by pedrolopes10** [comment]
Same thing happened to me but this is not related with react native:

https://stackoverflow.com/questions/58674817/ios-13-2-removing-overlay-from-mapkit-causing-map-to-flicker#

I've also open a ticket to apple support one week ago but still no response.

**Comment by melihmucuk** [comment]
+1
