### ISSUE TITLE
kmlSrc ignored on iOS (with provider="google"), works awesome on Android

### ISSUE THREAD

**Issue by ikatun** [react-native-maps/react-native-maps#3190]
# Bug

When running kmlSrc example (https://github.com/react-native-community/react-native-maps/blob/master/example/examples/MapKml.js), the KML layer appears only on Android, it appears to be ignored on iOS.

## Environment info
React native info output:

```bash
Ivos-MacBook-Pro:GoogleMapsTest ikatun$ npx react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
      Memory: 85.89 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
```

Library version: 0.26.1 (and also 0.25.0 which comes with latest Expo)

## Steps To Reproduce

1. Create a new react native project
2. Add react-native-maps to the project
3. Create appropriate google API key
4. Render this component: `https://github.com/react-native-community/react-native-maps/blob/master/example/examples/MapKml.js` while setting provider to "google"
...

Describe what you expected to happen:

1. Expected to see info from KML layer on both Android and iOS (not only Android)

## Reproducible sample code

https://github.com/ikatun/kml-not-working-ios-reproducible-demo

Just clone, `npm install`, `pod install` and `npm run ios`, it already contains my test google api key, please don't abuse it :)

**Comment by CarlosJJR** [comment]
Facing the same issue

**Comment by chaitanyatejam** [comment]
kml source not working in ios

**Comment by ikatun** [comment]
No need to close this, I'm sure it's still not working.

**Comment by DaniShalash** [comment]
Same think here. On Android it works, but not on iOS

**Comment by zabojad** [comment]
Still having the same problem on iOS...

**Comment by zabojad** [comment]
[I've fixed it by rewriting the ](https://github.com/react-native-maps/react-native-maps/issues/2360)
