### ISSUE TITLE
Ios memory leak

### ISSUE THREAD

**Issue by mirhat** [react-native-maps/react-native-maps#3192]
# Bug

Every time I enter screen with MapView memory increases by 30 Mb and when I leave that screen memory stays the same.
When you zoom in or out on map memory also increases.

## Environment info

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 549.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 0.26.1

I am also using
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3", 

## Steps To Reproduce

1. Open screen with MapsView
2. Leave screen with MapsView
...

Describe what you expected to happen:

1. Memory returns to normal

## Reproducible sample code

```
<MapView
      provider={PROVIDER_GOOGLE}
      zoomEnabled
      zoomControlEnabled
      ref={(ref) => {
        mapRef = ref
      }}
      initialRegion={{
        latitude: props.lat,
        longitude: props.long,
        latitudeDelta: 0.006766,
        longitudeDelta: 0.005757,
      }}
    >
      <Marker
        coordinate={{
          latitude: props.lat,
          longitude: props.long,
        }}
      >
        <Icon type="Entypo" name="location-pin" style={{ fontSize: 30, color: 'red' }} />
      </Marker>
    </MapView>
```

**Comment by mirhat** [comment]
I have solved it by using this [comment](https://github.com/react-native-community/react-native-maps/issues/2284#issuecomment-396436171) but it is workaround

**Comment by firofame** [comment]
after going through a zillion solutions what worked for me is this [link](https://github.com/software-mansion/react-native-screens#usage-with-react-navigation-without-expo)

**Comment by reyalpsirc** [comment]
@mirhat That only solved the problem in debug mode. We have a released App which has Out Of Memory crashes due to this (tested with Activity Monitor from Instruments and noticed the spike in memory only in the release builds even with the workaround)

**Comment by reyalpsirc** [comment]
I added my solution to the link provided by @mirhat
