### ISSUE TITLE
Custom map zooming 

### ISSUE THREAD

**Issue by MoeMamdouh** [react-native-maps/react-native-maps#3200]
# Question
How to make zoom in and zoom out only from and to the center of the map?

**Comment by karimkhamwani** [comment]
+1 much needed

**Comment by richardbumm** [comment]
Zooming is handled via the delta properties of the region object:
`region: {
            latitude: 37.7859839,
            longitude: -122.4283955,
            latitudeDelta: 0.08,
            longitudeDelta: 0.08
        },`

**Comment by rajanshahsa** [comment]
I am using delta for Zooming. However, on a different location(Ahmedabad, Mumbai, London, New York, Durban etc) with the same delta value, my zooming is different. Can you please help me out in this?

**Comment by deepak-jha-kgp** [comment]
Did you find a solution? @MoeMamdouh  @karimkhamwani

**Comment by MoeMamdouh** [comment]
@deepak-jha-kgp  not yet, i think its an important feature and should added in the library
