### ISSUE TITLE
Question: PNG Overlay on iOS

### ISSUE THREAD

**Issue by the-habu** [react-native-maps/react-native-maps#3201]
# Question

I can't seem to get overlays (https://github.com/react-native-community/react-native-maps/blob/master/docs/overlay.md) in PNG format to show up on iOS. The reason I am using PNG is for transparency, as the overlay image is a custom grid.

Is this a bug, missing feature, incompatibility or am I doing something wrong?

I am using;
RN: 0.59.10
RN-Maps: 0.26.1 (provider google)

Thank you for answering!

**Comment by bargald** [comment]
it works for me with PNG's, did you try adding zIndex and checking that the boundary is correct?

**Comment by geekazoid-at** [comment]
Sorry, took me a long time to get back to image overlays. Yes, I tried zIndex and checking boundary. It works perfectly well on Android though.

In my app TraceForce (in stores) I have a Paintball Field (Paintballfabrik in Germany) with 2 overlays (1 jpg, 1 png with transparencies).
Android: Both work
iOS: Only JPG one works
