### ISSUE TITLE
Animated multiple markers IOS  (HELP)

### ISSUE THREAD

**Issue by aliwaqassi** [react-native-maps/react-native-maps#3203]
# Question

here is my code

``` 
{
typeof this.props.markers != 'undefined' && this.props.markers.map((data, index) => {
    return (<MapView.Marker.Animated ref={(ref) => {
        this.car_moves[data.id] = ref;
    }} coordinate={{
        latitude: data.address_latitude,
        latitudeDelta: 0,
        longitude: data.address_longitude,
        longitudeDelta: 0
    }} flat key={data.id}>
        <Animated.Image source={{ uri: 'car3d' }} style={{ width: 40, height: 40, transform: [{ rotate: data.heading + 'deg' }] }} />
    </MapView.Marker.Animated>)
})
}
```
this is working in andorid fine
```
const { driverWayCordAnim } = this.state;
if (Platform.OS === 'android') {
            if (this.car_moves) {
                this.car_moves[onTheWayObject.driver_id]._component.animateMarkerToCoordinate(JSON.parse(onTheWayObject.driver_location), 5000);
            }
        } else {
            driverWayCordAnim.timing(mylngLnganim,5000).start();
        }
```
here is for ios i want help i need to move specific marker like android code has , but i am confused in ios
```
const { driverWayCordAnim } = this.state;
driverWayCordAnim.timing(mylngLnganim,5000).start();

i want like this driverWayCordAnim[1].timing(mylngLnganim,5000).start();
```

**Note** my markers are dynamic so i need dynamic index in Ios

Thanks in advance

**Comment by tattivitorino** [comment]
@aliwaqassi have you managed to make it work on android? i have this error: [https://github.com/react-native-community/react-native-maps/issues/2195](url) with the animateMarkerToCoordinate

**Comment by aliwaqassi** [comment]
@tattivitorino  dear i am talking about IOS marker animation ```driverWayCordAnim[1].timing(mylngLnganim,5000).start();```

like i have 2 markers and i want to move specific one marker how can i do this in ios with `driverWayCordAnim[1].timing(mylngLnganim,5000).start();`
