### ISSUE TITLE
Custom Marker on IOS with some Images is very lag and low performance, trackViewChanges not working

### ISSUE THREAD

**Issue by mlop113** [react-native-maps/react-native-maps#3207]
# Bug

## Environment info

React native info output:

```bash
System:
      OS: macOS 10.15
      CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
      Memory: 91.70 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.0 => 16.8.0 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-maps: 0.24.2
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1
```

Library version: 0.24.2

## Steps To Reproduce

1. Scroll map is Lag and CPU is over 100% on IOS simulator, and more in REAL DEVICE, It is only with IOS, on Android is good
2.
...

Describe what you expected to happen:

1. Could have some ideas to improve that on IOS
2.

## Reproducible sample code

```
<MapView.Animated
          ref={mapView}
          provider={PROVIDER_GOOGLE}
          style={[StyleSheet.absoluteFill]}
          initialRegion={region}
          onRegionChangeComplete={handleRegionChangeCompleted}
          zoomEnabled={true}
          showsUserLocation={true}
         // customMapStyle={googleMapStyle}
        >
          {!isEmpty(currentAddress) && (
            <DiscoverMapMarker
              place={currentAddress}
              type="addressMap"
              identifier="addressMap"
            />
          )}

          {addressesVisible && (
            <DiscoverMarker
              duplicateAddressMultiJoyner={duplicateAddressMultiJoyner}
              type="addressMap"
              events={events}
              data={addresses}
              onMarkerPress={handleMarkerPress}
            />
          )}

          {stateHangout && isHangout.length > 0 && (
            <DiscoverMarker
              type="hangout"
              data={stateHangout}
              onMarkerPress={handleMarkerPress}
            />
          )}

          {eventsVisible && (
            <DiscoverMarker
              type="eventsMap"
              data={events}
              onMarkerPress={handleMarkerPress}
            />
          )}
        </MapView.Animated>
```

![Screen-Recording-2019-12-03-at-14 49 12](https://user-images.githubusercontent.com/22517602/70030692-50c07500-15dc-11ea-912b-8a70adf1f984.gif)

**Comment by sagomezza** [comment]
I'm experiencing this issue too on simulator and real iPhone devices. I'm using Expo version 35.

**Comment by felippepuhle** [comment]
Same here, from 60fps to 5fps on simulator, sounds horrible!

Anything I can help to identify what's causing it?

**Comment by mlop113** [comment]
I have looked for issues in the past but they seem to be closed with no solution or no interaction for a long time.

**Comment by mlop113** [comment]
Hope any senior helps me !

**Comment by HoangTrongKhanh** [comment]
any solution?

**Comment by ezranbayantemur** [comment]
any update?

**Comment by artmare** [comment]
The same issue. Did anyone fix that? Please help!

**Comment by felippepuhle** [comment]
@artmare 
If the marker is a simple image you can use `<Marker icon={require('./path/to/file.png')} />`

**Comment by artmare** [comment]
@felippepuhle Hi! No, my marker is custom with Callout inside. And I use react-native-map-clustering but my count of markers may be more than 300. Android works very well.

**Comment by WeZinc** [comment]
same problem here...

**Comment by georgecirilo** [comment]
Hello, this problem still persists. Any possible solutions? I wonder how this huge performance drop is still ignored to the date..

**Comment by georgecirilo** [comment]
Hello, I have the same issue. I got some improvement by setting tracksViewChanges={false} as suggested in the issue below. Still, performance drops significantly when rendering markers.


https://github.com/react-native-community/react-native-maps/issues/3034

**Comment by vitto-moz** [comment]
I was able to achieve better performance with the `image` prop
```
    <Marker
        image={require('./marker-icon.png')}>
```
however, there is significant drawback: you have to tweak the size of the image itself to have the needed one rendered on the map, so in my case it's 45px and the quality of the image becomes very poor...

**Comment by vitto-moz** [comment]
to resolve the issue with image quality, I've mentioned above - add different images sizes, as described in the [react-native docs](https://reactnative.dev/docs/images)

└── img
    ├── check.png
    ├── check@2x.png
    └── check@3x.png
