### ISSUE TITLE
onRegionChangeComplete returns a different value every render without the user trigger any change

### ISSUE THREAD

**Issue by slauzinho** [react-native-maps/react-native-maps#3212]
# Bug

When you provide an initial region to be rendered the `onRegionChangeComplete` triggers on every re-render with a different region (off by a few points on longitude). For instance, if you set a marker on that position you will notice the marker will always be different.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 283.95 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/n/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/n/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2
      System Images: android-16 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.26.1

## Steps To Reproduce

1. Initialize a new project
2. use some random initialRegion like:
```javascript
const INITIAL_REGION = {
  longitudeDelta: 0.05,
  latitude: 37.7631052842748,
  longitude: -122.40641713142395,
  latitudeDelta: 0,
};
```
3- do:
```javascript
 <MapView
    style={{ ...StyleSheet.absoluteFill }}
    initialRegion={INITIAL_REGION}
    onRegionChangeComplete={console.log}
 />
```

1. Expect console.log input to be the same as INITIAL_REGION but it isn't

**Comment by federicomiralles** [comment]
@slauzinho I think I'm facing this same issue on iOS. Calculating the radius (based on the zoom level) when the user opens the map (without doing anything else) changes while **onRegionChange** and **onRegionChangeComplete** callbacks are called:
```
DID MOUNT RADIUS = 150 // INITIAL REGION
ON REGION CHANGE RADIUS = 27
ON REGION CHANGE RADIUS = 882
ON REGION CHANGE RADIUS = 882
ON REGION CHANGE RADIUS = 150
ON REGION CHANGE COMPLETED RADIUS = 144
```
The radius value obtained is on km. I was expecting that radius calculated on onRegionChangeComplete was going to be the same as the initial region and the same as the latest onRegionChange call, that is, **150**. But for some unknown reason when onRegionChangeComplete is called the calculation reduces to 144 km.

Were you able to sort out this?

Thanks in advance.

Cheers,

Federico

**Comment by slauzinho** [comment]
Unfortunately, I couldn't come out with any viable solution, so I end up ignoring the first value from onRegionChangeComplete

**Comment by federicomiralles** [comment]
@slauzinho I can confirm that using the following line works. It's a workaround because the problem is still there but the map view gets fixed without the user noticing it:
```
onMapReady={() => {
          Platform.OS === 'ios' && mapRef.current.animateToRegion(region, 0.1);
}}
 ```
Looks like even though the issue was closed loooooooooooooong time ago, the bug is still present (or it's a regression) on the current version of react-native-maps (0.27.0 at the time of this writing).

In any case I hope this helps you (or any other dev who reaches this bug report)!

Cheers,

Federico
