### ISSUE TITLE
LocalTile doesn't render all tile images

### ISSUE THREAD

**Issue by Diwei-Chen** [react-native-maps/react-native-maps#3216]
# Bug

As shown in the screenshots below, on zoom level 14, the last column is missing 3 tile images. However, when checking the tile images in the simulator's file directory, the image are all there. After reload the map, the missing images come up, but the images in some other area are missing.
![Screen Shot 2019-12-10 at 3 19 15 pm](https://user-images.githubusercontent.com/26317142/70494877-18331500-1b61-11ea-905e-352b683e4567.png)
![Screen Shot 2019-12-10 at 3 19 21 pm](https://user-images.githubusercontent.com/26317142/70494878-18331500-1b61-11ea-93bb-5c43cb901670.png)
![Screen Shot 2019-12-10 at 3 19 27 pm](https://user-images.githubusercontent.com/26317142/70494880-18331500-1b61-11ea-9fc2-11fed3af28f3.png)
![Screen Shot 2019-12-10 at 3 19 35 pm](https://user-images.githubusercontent.com/26317142/70494881-18cbab80-1b61-11ea-830f-538e4d1dc36e.png)

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 21.27 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

Library version: 0.26.1

## Steps To Reproduce

1. Download a set of tile images between zoom level 1 and 15.
2. Render the tile images in the map by using `LocalTile`.
...

Describe what you expected to happen:

All local tile images should be rendered properly.

**Comment by juliuscalvium** [comment]
Did you find a solution to this? 
I'm having the same issue. I tried bumping up to `react-native-maps 0.27.1` but the same issue persists.

**Comment by cedced19** [comment]
I have exactly the same issue with `^0.27.1` too !
