### ISSUE TITLE
Display GeoJSON Points as points, not markers

### ISSUE THREAD

**Issue by tapioko** [react-native-maps/react-native-maps#3221]
# Feature Request

IMHO GeoJSON points should be displayed as points. Currently they are displayed as generic markers.

I could circumvent this by handling points as circles, but then I would have to update the circle radius (which is in meters) based on zoom level to keep the point size constant, and I don't want to do that.

### Code sample

There would be no changes to this example code to generate a GeoJSON point:
https://github.com/react-native-community/react-native-maps/blob/master/docs/geojson.md

**Comment by Covicake** [comment]
Any updates on this? I also need to customize geojson's markers :(

**Comment by datngotan-aavn** [comment]
Any updates on this? I also need to show points instead of markers. Do you guys have any solution for this?
