### ISSUE TITLE
MBtitles in new version

### ISSUE THREAD

**Issue by atihungdx** [react-native-maps/react-native-maps#3222]
# Feature Request
I See MBtitles in version 0.21.0 but when I config it not run! Please add it in new version! Many thanks

**Comment by secretgh** [comment]
Hey @atihungdx I am wanting this feature as well, take a look at this PR for a possible solution https://github.com/react-native-community/react-native-maps/pull/2388, Although not merged it has some decent code that implements mbtiles. I am currently attempting to create a local merge with the forked branch to implement my own mbtiles.

**Comment by mzu** [comment]
Any updates on this? It would be useful to be able to fetch mbtiles and allow `<MapView>` to handle them. As far as I understand, it is already possible to use x/y/z tiles locally for offline maps via `<MapView.UrlTile/>` . I am using expo and unzipping archived tiles after the transfer to the app is not supported (I would have to eject). Which means currently the only way to use offline tiles is by transferring them one by one.

I am still new to this so maybe there is an alternative way to make offline maps work (I would want to use my own generated tiles)?

**Comment by UnclePetros** [comment]
Hello, I'm also having problem with MbTile.
It seems to be missing. Is it so?

When I try to run this piece of code:

```
var path = `${RNFS.ExternalDirectoryPath}/map2.mbtiles`;

	return (
		<MapView
			style={Css.mapContainer}
			loadingEnabled={true}
			mapType='none'
			region={{
				latitude: 43.388784,
				longitude: 11.437064,
				latitudeDelta: 0,
				longitudeDelta: 0,
			}}
			minZoomLevel={12}
			maxZoomLevel={18}
		>
			<MapView.MbTile
				pathTemplate={path}
				tileSize={256}
			/>
		</MapView>
	)

```
I always receive this error:

![MbTile Error](https://i.ibb.co/g9PxyCT/error-Mb-Tile.png)

LocalTile with XYZ tile, insted, works fine.

Thank you in advance.
UnclePetros
