### ISSUE TITLE
AIRMapCalloutSubview is not supported on android

### ISSUE THREAD

**Issue by jeffwji** [react-native-maps/react-native-maps#3223]
# Question
I followed this example: https://github.com/react-native-community/react-native-maps/blob/master/example/examples/Callouts.js to add a custom callout to my App. It was all running good in iOS, but in Android it reported: "AIRMapCalloutSubview is not supported on android". I tried google, but nobody answered this problem. I'm hoping it is make scenes to ask in here. The screen shot is below.

![Screenshot_20191214_002952_host exp exponent](https://user-images.githubusercontent.com/5223763/70844064-9a456700-1e09-11ea-9d51-f8e90e4b1b1e.jpg)

And my code piece is:

    class MyCallout extends React.Component {
      constructor(props) {
        super(props)
      }
    
      render() {
        return(
          <Callout alphaHitTest tooltip
            style={{width:220, height:100}}
            onPress={e => {
              if ( e.nativeEvent.action === 'marker-inside-overlay-press' || e.nativeEvent.action === 'callout-inside-press' ) {
                return;
              }
            }}
          >
            <CustomCallout>
              <Text>Add to list</Text>
              <CalloutSubview onPress={() => {
                  this.props.addRemoveOpt(this.props.location)
                }}>
                <Button>
                  <Label>Add</Label>
                </Button>
              </CalloutSubview>
            </CustomCallout>
          </Callout>
        )
    ...
    }

**Comment by DanLeCornu** [comment]
Also have the same issue

**Comment by ekrokowski** [comment]
https://github.com/react-native-community/react-native-maps/blob/master/docs/callout.md

> Note: Supported on iOS only.

**Comment by foxcreation** [comment]
Having the same issue. Though documentation specifies it only applies to iOS the example in root-markup does show a working version on Android.
https://camo.githubusercontent.com/d76fd1619d2318f5eabaea0b90d23998cf8de781/687474703a2f2f692e67697068792e636f6d2f785437375964553048587279766f527161512e676966
