### ISSUE TITLE
Indoor map and level picker not showing on Android

### ISSUE THREAD

**Issue by AnujUTS** [react-native-maps/react-native-maps#3225]
# Bug?

Level picker for indoor maps not showing on Android but works fine on iOS. Android indoor terminal map without levels:
![workingwithnolevelpicker](https://user-images.githubusercontent.com/26514728/71060947-041f9100-21bb-11ea-9e1d-28c6c0b7174a.png)
Levels show up when using the Google Maps app

Occasionally on Android, the indoor building itself (an airport terminal) does not appear at all - same location as previous picture:
![notshowingindoor](https://user-images.githubusercontent.com/26514728/71063970-0b966880-21c2-11ea-91e7-f489c4ce4002.png)

This is a pure react native app.

## Environment info

info 
  React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
      Memory: 1.57 GB / 7.67 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.17.0 - /usr/bin/node
      npm: 6.13.0 - /usr/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

Library version: "~0.25.0"

## Steps To Reproduce

1. Use a MapView component inside a react-native app and try to select level picker for an indoor map when using an android device
...

Describe what you expected to happen:

1. Level picker should show up when indoor map is shown

## Reproducible sample code

`<MapView
                    showsIndoorLevelPicker={true}
                    provider={PROVIDER_GOOGLE}
                    style={{ flex: 1 }}
                    initialRegion={{
                        latitude: this.state.userLocation.latitude,
                        longitude: this.state.userLocation.longitude,
                        latitudeDelta: 0.0042,
                        longitudeDelta: 0.0042
                    }}
                >`

## Additional notes

- I have tested this on a Xiaomi mi-mix 2 and Oneplus 7 pro
- The goal is to be able to navigate a user from point A to B when indoors (regardless of level of building)

**Comment by r-saba** [comment]
Have you figured it out? I'm having the exact issue with level picker not working in android.

**Comment by AnujUTS** [comment]
No I'm afraid not, I've been looking at other indoor map providers instead. Please let me know if you happen to find a solution though

**Comment by TheGreatMarkus** [comment]
I've seen possible solutions that essential trigger a rerender by changing the size of the map, but none of the implementations have worked for me. :(

**Comment by r-saba** [comment]
@TheGreatMarkus Has made his own indoor level picker using the setIndoorActiveLevelIndex method to change levels when specific buttons are clicked. [Method can be found here](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#methods). This way we can turn off the default level picker and make a custom one which will display on both ios and android.
