### ISSUE TITLE
When custom Marker removed, half of map is not responsive

### ISSUE THREAD

**Issue by davx1992** [react-native-maps/react-native-maps#3236]
# Bug
Hi, I have found very strange bug. When I am adding custom marker (Marker with custom image and child view), when this marker is removed, half of the map is not responsive - you cant drag, zoom, e.t.c. on top side of the map.
Checked on both platforms. On Android it works, but on IOS facing this issue.

## Environment info
I am using Expo SDK 36
react-native-maps : "0.26.1"

Library version: "0.26.1"

## Steps To Reproduce
Use this snack on real device.
https://snack.expo.io/@davx1992/authentic-cereal

1. Click move to user location.
2. Then hold finger on point where you want to add marker (Long press) and remove finger.
3. Marker added, then move finger around screen and remove finger again, marker will be removed.
4. Try to drag map on top side of the screen, it will be not responsive, and try the same on bottom side of the map.

Describe what you expected to happen:

1. Map is responsive and draggable even after marker is removed.

## Reproducible sample code
https://snack.expo.io/@davx1992/authentic-cereal

**Comment by jonasmedeiros** [comment]
@davx1992 when I change marker position having same problem, also using long press, did you find way to fix it ?

**Comment by davx1992** [comment]
@jonasmedeiros to be honest I do not remember anymore how I solved the issue, but for sure I had to change logic how I am creating those markers. 
What issue are you facing? What is your marker code?
