### ISSUE TITLE
Is it possible to disable marker events?

### ISSUE THREAD

**Issue by switchtrue** [react-native-maps/react-native-maps#3239]
# Question

Is it possible to entirely disable touch events on certain markers? I have a map where I'm rendering two types of markers and geojson. The larger regular style red pins are touchable and handle onPress but the smaller custom orange dot markers should do nothing at all.

However, because they are often clumped together tapping what you think is a red marker actually centers the map onto a nearby orange one.

I'd like to be able to disable all touch events on the small orange ones so that tapping the red ones is easier.

![rnm_markers](https://user-images.githubusercontent.com/1535972/71774946-39561c80-2fcc-11ea-9c42-d3ea9d3f1111.png)

**Comment by kriscarle** [comment]
It doesn't look like it... You could try increasing the style zIndex value of the red markers to see if that helps.  If you don't need interaction you may want to look at the `Circle` component? 

If you have a lot of data you may want to consider using a tile overlay and rendering it using a service like Mapbox https://docs.mapbox.com/api/maps/#static-tiles or for an open-source option https://mapnik.org/ That will give you a lot more control over the design.

**Comment by marospekarik** [comment]
Unfortunately, event.stopPropagation() nor event.preventDefault() works to stop the default marker event on android.

rn-maps version: 0.26.1

**Comment by jfontanel** [comment]
We still can't do this with new versions ?
