### ISSUE TITLE
initialRegion doesn't work on AppleMaps but work on GoogleMaps

### ISSUE THREAD

**Issue by timgarciaa** [react-native-maps/react-native-maps#3243]
If i use google maps, initialRegion work fine but when I use appleMaps it doesn't start on the initial region I provided.

Here's a sample code.

`        <MapView style={styles.map}

          provider={(this.props.selectedMap.selectedMap === 'AppleMaps') ? MapView.PROVIDER_DEFAULT : MapView.PROVIDER_GOOGLE}
          loadingIndicatorColor={"#ffbbbb"}
          loadingBackgroundColor={"#ffbbbb"}
          initialRegion={region}
          onRegionChangeComplete={this.onRegionChange}
          rotateEnabled={false}
          loadingEnabled={true}
          minZoomLevel={6}
          maxZoomLevel={19}
          ref={ref => (this.mapView = ref)}
          onMapReady={this.goToInitialRegion.bind(this)}
        >`

**Comment by isma4102** [comment]
could you fix it?, same here.

**Comment by Staarks** [comment]
> could you fix it?, same here.

I removed initialRegion and use region only. Then in onMapReady, put there the action to move to initialRegion.
