### ISSUE TITLE
cropping snapshot or setting width and height

### ISSUE THREAD

**Issue by vrinch** [react-native-maps/react-native-maps#3246]
Hi, I am trying to work with the takeSnapshot method, but the set width and height props do not have any effect on the snapshot. Can someone kindly let me know if I am doing it wrong. 
I would also like to know if its possible to crop the snapshot to just the region and location?
Below is the code and image sample, showing it did not assign the width and height.

              takeSnapshot() {
                const { location: { longitude, latitude, }, result } = this.state;

                const snapshot = this.mapViewSnap.takeSnapshot({
                  width: 100,      // optional, when omitted the view-width is used
                  height: 100,     // optional, when omitted the view-height is used
                  region: {
                    latitude,
                    longitude,
                    latitudeDelta: LATITUDEDELTA,
                    longitudeDelta: LONGITUDEDELTA,
                  },
                  // iOS only, optional region to render
                  format: 'jpg',   // image formats: 'png', 'jpg' (default: 'png')
                  quality: 0.8,    // image quality: 0..1 (only relevant for jpg, default: 1)
                  result: 'file'   // result types: 'file', 'base64' (default: 'file')
                });
                snapshot.then((uri) => {
                  Firebase.shared.updateImage({
                    image: uri
                  }).then(() => {
                    console.log('sucesso');
                  }).catch((e) => {
                    console.log(e);
                  });
                });
            }

![image](https://user-images.githubusercontent.com/51086859/72211637-0bdb0880-34cf-11ea-9297-8d6403712757.png)

**Comment by nihp** [comment]
@vrinch How did you added that direction in this map.

**Comment by vrinch** [comment]
@nihp I used react-native-maps-directions

**Comment by preethypt** [comment]
Okay

**Comment by riordanpawley** [comment]
> I would also like to know if its possible to crop the snapshot to just the region and location?
Try  this.mapViewSnap.fitToCoordinates

**Comment by vrinch** [comment]
@riordanpawley can you explain to me how I can achieve this using the method you’re proposing?

**Comment by riordanpawley** [comment]
> @riordanpawley can you explain to me how I can achieve this using the method you’re proposing?

Yeah, my imperfect method is:
`  mapRef.current &&
      mapRef.current.fitToCoordinates(
        filteredCoordinates.map(({ location }) => location),
        { edgePadding: DEFAULT_PADDING, animated: true }
      );

      await timeout(500);
      const mapSnapshot =
        mapRef.current &&
        (await mapRef.current.takeSnapshot({
          format: 'jpg',
          quality: 0.7,
          result: 'file',
        }));`

This code zooms my map so that it just fits in all of the coords i provide it with.
