### ISSUE TITLE
MapView from 'react-native-maps' performance issues

### ISSUE THREAD

**Issue by BallySharma** [react-native-maps/react-native-maps#3247]
# Bug
I have about 800/1000+ markers on map due to this huge data rendering nothing is working properly as header buttons click, refresh,...etc.

Please suggest we how can we resolve this issues?...

## Environment info
React native info output:
"react-native": "0.60.5",
"react": "16.8.6",
"react-native-maps": "^0.25.0",
"react-native-maps-directions": "^1.7.0",

## Steps To Reproduce
1> Fetching geo points from Api and rendering on mapView
2> After rendered successfully header buttons onClick taking lots of time to perform action
3> Facing when getting a large amount of data from Api as 800/1000 points of array 

Describe what you expected to happen:
1> In case of large amount of data header buttons click should be work smoothly
2> Large data should be render smoothly on map

## Reproducible sample code
<MapView
                        initialRegion={this.state.region}
                        style={StyleSheet.absoluteFill}
                        ref={c => this.mapView = c}
                        pitchEnabled={true}
                        showsCompass={true}
                        liteMode={false}
                        showsBuildings={true}
                        showsTraffic={true}
                        showsIndoors={true}
                        loadingEnabled={true}
                        showsUserLocation={true}
                        followUserLocation={true}
                        showsMyLocationButton={true}
                        zoomEnabled={true}
                        minZoomLevel={5}
                        mapType={this.state.mapViewTitle}
                    >
 {this.state.coordinates.map((coordinate, index) =>
                            <MapView.Marker
                                key={`coordinate_${index}`}
                                coordinate={coordinate}
                                tracksViewChanges={this.state.tracksViewChanges}
                            //pinColor={'blue'}
                            >
                                {(coordinate.vehicle_color == 1 && !this.state.checkPoints) ? (<Animatable.View
                                    animation="pulse"
                                    easing="ease-in-out"
                                    iterationCount="infinite"
                                    style={{
                                        width: 50,
                                        height: 50,
                                        justifyContent: 'center',
                                        alignItems: 'center',
                                    }}><Image
                                        source={require('../../images/truck3.png')}
                                        style={{
                                            width: 40,
                                            height: 45,
                                            resizeMode: 'contain',
                                        }}
                                    /></Animatable.View>) : null}
                                {(coordinate.vehicle_color == 2 && !this.state.checkPoints) ? (<Animatable.View
                                    animation="pulse"
                                    easing="ease-in-out"
                                    iterationCount="infinite"
                                    style={{
                                        width: 50,
                                        height: 50,
                                        justifyContent: 'center',
                                        alignItems: 'center',
                                    }}><Image
                                        source={require('../../images/truck5.png')}
                                        style={{
                                            width: 40,
                                            height: 45,
                                            resizeMode: 'contain',
                                        }}
                                    /></Animatable.View>) : null}
                                {(coordinate.vehicle_color == 3 && !this.state.checkPoints) ? (<Animatable.View
                                    animation="pulse"
                                    easing="ease-in-out"
                                    iterationCount="infinite"
                                    style={{
                                        width: 50,
                                        height: 50,
                                        justifyContent: 'center',
                                        alignItems: 'center',
                                    }}><Image
                                        source={require('../../images/truck1.png')}
                                        style={{
                                            width: 40,
                                            height: 45,
                                            resizeMode: 'contain',
                                        }}
                                    /></Animatable.View>) : null}
                                {(coordinate.vehicle_color == 4 && !this.state.checkPoints) ? (<Animatable.View
                                    animation="pulse"
                                    easing="ease-in-out"
                                    iterationCount="infinite"
                                    style={{
                                        width: 50,
                                        height: 50,
                                        justifyContent: 'center',
                                        alignItems: 'center',
                                    }}><Image
                                        source={require('../../images/truck2.png')}
                                        style={{
                                            width: 40,
                                            height: 45,
                                            resizeMode: 'contain',
                                        }}
                                    /></Animatable.View>) : null}
                                {(coordinate.vehicle_color == 5 && !this.state.checkPoints) ? (<Animatable.View
                                    animation="pulse"
                                    easing="ease-in-out"
                                    iterationCount="infinite"
                                    style={{
                                        width: 50,
                                        height: 50,
                                        justifyContent: 'center',
                                        alignItems: 'center',
                                    }}><Image
                                        source={require('../../images/truck4.png')}
                                        style={{
                                            width: 40,
                                            height: 45,
                                            resizeMode: 'contain',
                                        }}
                                    /></Animatable.View>) : null}

                                <MapView.Callout
                                    style={{ margin: 5 }}
                                    onPress={() => this._callHere(coordinate.driverphone)}
                                >
                                    <View style={styles.mainViewStyle}>
                                        <CardView
                                            cardElevation={2}
                                            cardMaxElevation={2}
                                            cornerRadius={5}
                                            style={styles.cardViewStyle}
                                        >
                                            <View style={styles.viewStyle}>
                                                <Text style={styles.txtStyle}>{coordinate.title}</Text>
                                                <Text style={styles.txtStyle1}>{'Last updated:  ' + coordinate.lastupdated}</Text>
                                                <Text style={styles.txtStyle1}>{'Distance:  ' + coordinate.distance + ' km'}</Text>
                                                <Text style={styles.txtStyle1}>{'Location:  ' + coordinate.locTxt}</Text>
                                                <Text style={styles.txtCallStyle}>{'Click to call driver:  ' + coordinate.driverphone}</Text>
                                            </View>
                                        </CardView>
                                    </View>

                                </MapView.Callout>
                            </MapView.Marker>
                        )}
                    </MapView>

Please suggest we how can we handle large amount of data on mapView?...

Regards,
Bally Sharma

**Comment by richardbumm** [comment]
Aside from 800 markers being even usable by a user (I have no idea what you are doing, but something tells me you should take another look at usability), I suggest marker clustering to solve your problem.

Something like this: https://www.npmjs.com/package/react-native-map-clustering

**Comment by cranesandcaff** [comment]
We have a use case of rendering up to 800 markers and additional 800-1600 lines 😓

**Comment by askpatrickw** [comment]
@BallySharma, this isn't a fix, but something I've observed. When I load a lot (thousands) of Markers, the app in the simulator on my MacBook Air will crash, but when I install the app on my iPhone 11 Max Pro it works fine. That might not be your issue, but I thought I'd share in case it helps.
