### ISSUE TITLE
map not showing current location of user in huawei honor device

### ISSUE THREAD

**Issue by BallySharma** [react-native-maps/react-native-maps#3256]
# Bug

huawei honor device map not showing current location
showsUserLocation={true}: Not showing...
followUserLocation={true}: Not showing...
showsMyLocationButton={true}: Not showing...

## Environment info

"react": "16.8.6",
"react-native": "0.60.5",
"react-native-maps": "^0.25.0",

## Steps To Reproduce
1. install app from PlayStore on huawei honor device
2. Click on map icon and current location not found 
3. showing different region 
...

Describe what you expected to happen:
1. Google map should be show user current location

## Reproducible sample code
<MapView
                        //initialRegion={this.state.region}
                        region={this.state.region}
                        style={StyleSheet.absoluteFill}
                        ref={c => this.mapView = c}
                        provider={PROVIDER_GOOGLE}
                        pitchEnabled={true}
                        showsCompass={true}
                        //liteMode={false}
                        showsBuildings={true}
                        showsTraffic={true}
                        showsIndoors={true}
                        loadingEnabled={true}
                        showsUserLocation={true}
                        followUserLocation={true}
                        showsMyLocationButton={true}
                        zoomEnabled={true}
                        minZoomLevel={5}
                        //cacheEnabled={false}
                        mapType={this.state.mapViewTitle}
                    >

Please suggest we how can we show user current location on huawei honor device...

**Comment by hannojg** [comment]
Did you ask for location permission?
```javascript
        <MapView
          onMapReady={(): void => {
            PermissionsAndroid.request(
              PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
            );
          }}
```

**Comment by mramirez1390** [comment]
Tengo entendido que el mapa no esta funcionando en los nuevos dispositivos de Huawei, por los problemas de google con China.
