### ISSUE TITLE
Current location coords

### ISSUE THREAD

**Issue by armin23615** [react-native-maps/react-native-maps#3262]
# Question
How to retrieve current location coordinates?

**Comment by kriscarle** [comment]
I think you are looking for `onUserLocationChange` see https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#events

Though you may want to get it directly from the device so you have more options, for example with Expo you can use https://docs.expo.io/versions/v36.0.0/sdk/location/

**Comment by armin23615** [comment]
Also this package works quite well: [(https://github.com/Agontuk/react-native-geolocation-service)](url)
