### ISSUE TITLE
React Native map crashes only with apk

### ISSUE THREAD

**Issue by BSThisarasinghe** [react-native-maps/react-native-maps#3263]
# Bug

I am developing a react native app with several screens. It has a screen that loads react native map. It's working perfectly on debug when I run react-native run-android. But when I create the signed apk and install it on a device other screens work fine, but when I navigate to the screen with map, the app crashes. This happened only with apk. So, I can't find a reason as well. This is how I implemented map.

**/app/build.gradle/**

    `dependencies { 
        implementation project(':react-native-linear-gradient')
       implementation project(':react-native-orientation')
       implementation project(':@react-native-community_geolocation')
       implementation(project(':react-native-maps')){        
            exclude group: 'com.google.android.gms', module: 'play-services-base'        
            exclude group: 'com.google.android.gms', module: 'play-services-maps'    
       }
      implementation 'com.google.android.gms:play-services-base:12.0.0'
      implementation 'com.google.android.gms:play-services-maps:12.0.0'
      implementation fileTree(dir: "libs", include: ["*.jar"])
      implementation "com.facebook.react:react-native:+"  // From node_modules
     implementation project(':react-native-vector-icons')
        if (enableHermes) {
           def hermesPath = "../../node_modules/hermes-engine/android/";
           debugImplementation files(hermesPath + "hermes-debug.aar")
          releaseImplementation files(hermesPath + "hermes-release.aar")
     } else {
          implementation jscFlavor
     }
    }`

**android/build.gradle**
       `buildscript {
          ext {
            buildToolsVersion = "28.0.3"
            minSdkVersion = 16
            compileSdkVersion = 28
            targetSdkVersion = 28
            supportLibVersion = "28.0.0"
        }
        repositories {
            google()
            jcenter()
         }
          dependencies {
            classpath("com.android.tools.build:gradle:3.4.2")
          }
      }`

**Code**

    `<View>
          <MapView
              style={{ height: 500 }}
              initialRegion={{
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}
              provider={PROVIDER_GOOGLE}
              showsUserLocation={true}
              toolbarEnabled={true}
              loadingEnabled={true}
              mapType="standard"
            />
          </View>`

I have added internet permission and API key to manifest XML file. I checked this on android only. But the map crashes only in release.
Is there anyone who faced the same situation? How did you solve it?

**Comment by ameinabdi** [comment]
also faced this issue too did you got any solution ? @BSThisarasinghe

**Comment by egemenhalici1** [comment]
+1

**Comment by sharada3** [comment]
I had the same issue. Fixed it by adding the googleMaps-api-key under android in app.json
      "config": {
        "googleMaps": { "apiKey": <YourAPI Key> }   
     }
More detailed explanation was found here: https://medium.com/nycdev/create-a-react-native-app-with-google-map-using-expo-io-68041252023d

**Comment by KitTheProgrammer** [comment]
I solved this problem by change `def enableSeparateBuildPerCPUArchitecture = false`  on `true` in `app\build.gradle`.
I used `cd android && .\gradlew clean && .\gradlew assembleRelease` and then tried to install all apks in `android\app\build\outputs\apk\release`. Two of them worked as should.
