### ISSUE TITLE
Add "dissipating" option for heatmap

### ISSUE THREAD

**Issue by ytl6547** [react-native-maps/react-native-maps#3270]
# Feature Request

When zooming a heat map the gradient gets to thin (diluted) to be visible. Can we have the "dissipating" option to keep a heatmap static while zooming? Will really appreciate it if possible!

**Comment by kapilkarda** [comment]
is their any update on this ticket, I am looking for same.? 
@ytl6547 @rborn have you achieved something similar ?

**Comment by thanhluantl2304** [comment]
Any update on this?
