### ISSUE TITLE
Polygon onPress areas have padding that extend beyond the polygon bounds

### ISSUE THREAD

**Issue by mattcoker** [react-native-maps/react-native-maps#3280]
# Bug

The Polygon press event has "consistently inconsistent" behavior, in that the area outside of the polygon border still triggers the onPress event for the nearby polygon. If two polygons are very close to each other, then clicking the same spot in succession  will cause the onPress behavior to toggle between the nearby polygons that have "overlapping tap targets". This behavior has only been directly seen on Google Maps, and is consistent between iOS and Android.

I have noticed that the "onPress padding" is not coordinate-based, but seemingly pixel-based. The approximate pixel padding to the onPress area seems to be the same regardless of whether I am viewing the polygon border from a very high or a very low zoom level.

I've read numerous other issues, some going back to 2016 and 2017 that seem to indicate vaguely similar behavior, but it seemed like this was distinct enough to warrant a new issue.

## Environment info

React native info output:
```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 44.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```
Library version: 0.26.1

## Steps To Reproduce

1. Setup an RN Native app, per the provided instructions for Google Maps (bug happens on both OS's).
2. Render a map with multiple polygons, and an onPress handler.
3. Clicking areas outside of the polygon but still close to the border will still trigger an onPress event
4. If two polygons are adjacent or even just very close, clicking the exact same coordinate multiple times near the shared border will alternate between which polygon receives the press event.
...

Describe what you expected to happen:

1. Only pressing within the bounds of a polygon will trigger an `onPress` event within that polygon

## Reproducible sample code

```javascript
import React, { useRef } from 'react';
import { StyleSheet } from 'react-native';
import MapView, { Polygon, PROVIDER_GOOGLE } from 'react-native-maps';

import { RegionPolygonGenerator } from '../../components';
import useMap from '../../hooks/useMap';

import customMapStyle from './map-theme';

const bugJSON = {
  "data": [{
    "coordinates": [
      {"longitude": -3.9990234375, "latitude": 52.48947038534306},
      {"longitude": -1.9445800781249998, "latitude": 52.48947038534306},
      {"longitude": -1.9445800781249998, "latitude": 53.23234504341257},
      {"longitude": -3.9990234375, "latitude": 53.23234504341257},
      {"longitude": -3.9990234375, "latitude": 52.48947038534306}
    ]
  }, {
    "coordinates": [
      {"longitude": -0.9445800781249998, "latitude": 52.48947038534306},
      {"longitude": 0.9445800781249998, "latitude": 52.48947038534306},
      {"longitude": 0.9445800781249998, "latitude": 53.23234504341257},
      {"longitude": -0.9445800781249998, "latitude": 53.23234504341257},
      {"longitude": -0.9445800781249998, "latitude": 52.48947038534306}
    ]
  }, {
    "coordinates": [
      {"longitude": -3.9990234375, "latitude": 51.48947038534306},
      {"longitude": -1.9445800781249998, "latitude": 51.48947038534306},
      {"longitude": -1.9445800781249998, "latitude": 52.23234504341257},
      {"longitude": -3.9990234375, "latitude": 52.23234504341257},
      {"longitude": -3.9990234375, "latitude": 51.48947038534306}
    ]
  }, {
    "coordinates": [
      {"longitude": -1.9445800781249998, "latitude": 51.48947038534306},
      {"longitude": 0.1098632813, "latitude": 51.48947038534306},
      {"longitude": 0.1098632813, "latitude": 52.23234504341257},
      {"longitude": -1.9445800781249998, "latitude": 52.23234504341257},
      {"longitude": -1.9445800781249998, "latitude": 51.48947038534306}
    ]
  }]
};

const RegionMap = () => {
  const mapRef = useRef(null);
  const { selectedRegionId, setSelectedRegionId } = useMap();

  const getColorByIndex = (index) =>
    selectedRegionId === index
      ? 'rgba(255,0,0,.5)'
      : 'rgba(0,0,0,.5)';

  const onMapPress = ({ nativeEvent }) => {
    if (nativeEvent.action !== 'polygon-press') setSelectedRegionId(null);
  };

  const onPolygonPress = (index) => {
    setSelectedRegionId(selectedRegionId === index ? null : index);
  }

  return (
    <MapView
      ref={mapRef}
      style={styles.map}
      provider={PROVIDER_GOOGLE}
      customMapStyle={customMapStyle}
      loadingEnabled={true}
      pitchEnabled={false}
      rotateEnabled={false}
      onPress={onMapPress}
    >
      {bugJSON.data.map(({ coordinates }, index) => (
        <Polygon
          key={`polygon-${index}`}
          coordinates={coordinates}
          strokeWidth={3}
          strokeColor={getColorByIndex(index)}
          fillColor={getColorByIndex(index)}
          onPress={() => onPolygonPress(index)}
          tappable
          geodesic
        />
      ))}
    </MapView>
  );
}

const styles = StyleSheet.create({
  map: { ...StyleSheet.absoluteFillObject },
});

export default RegionMap;
```

## Video Reproduction
![iOS Emulator with Google Maps](https://user-images.githubusercontent.com/2382745/74096025-fa315480-4abe-11ea-835b-e0d23622138b.gif)

- Edit to fix uploaded gif, previous version was only 5 seconds.

**Comment by mattcoker** [comment]
Has anyone been able to replicate this, or have any documentation why this would be the case? I understand that, with touch targets being larger to accommodate the size of a finger, some "fuzziness" to the tappable area could be desirable. However, the alternating overlap behavior seems very much like bug to me.

As far as attempts to resolve this, I've tried manually controlling the z-index of the "active" polygon, thinking this would move the tappable area above the surrounding polygon tappable areas. Unfortunately, this did not change anything.

My use-case will have up to 200 polygons rendered on the map at a time, so switching to `onMapPress` and then looping through polygons to see if the point exists within them (with something like [point-in-polygon](https://github.com/substack/point-in-polygon) or [robust-point-in-polygon](https://github.com/mikolalysenko/robust-point-in-polygon) is certainly less than desirable).

**Comment by ryam4u** [comment]
same issue

**Comment by mattcoker** [comment]
@ryam4u if it helps (although this really shouldn't be necessary) I've had good success with the `onMapPress` solution that I mentioned in my last comment.

Essentially I have an onMapPress event that will run a `point-in-polygon` check on each polygon rendered until it finds one where it matches. Not sure when anyone will be able to take a look at this issue 😞

**Comment by ryam4u** [comment]
@mattcoker yes, thanks, this method has worked well for me
