### ISSUE TITLE
onResponderRelease and onTouchEnd is not getting triggered in iOS

### ISSUE THREAD

**Issue by arunpugahz** [react-native-maps/react-native-maps#3283]
# Bug
 Trying to implement freehand sketch on Map, for that I need to listen to onResponderRelease or onTouchEnd to frame a polygon. 
onResponderStart/onTouchStart is triggered properly but when I release the touch the screen onResponderRelease/onTouchEnd is not getting triggered.

![IMG_9342660E927A-1](https://user-images.githubusercontent.com/53349433/74137332-9bcaba00-4c15-11ea-9b53-14fcad34efd0.jpeg)

Library version: 0.26.1
Describe what you expected to happen:

1. onResponderStart={e => { console.log('onResponderStart Mapview') }} -> **working**
2. onResponderRelease={e => { console.log('onResponderRelease Mapview ') }} -> **Not working**

**Comment by Cplantijn** [comment]
Hopefully this gets fixed soon. I have attempted to place the responders on a parent view but the release callbacks still don't fire. Is the MapView consuming this callback and not propagating?

**Comment by hiepnguyen1195** [comment]
I got same issue when can not detect `onResponderRelease` of View component when I display MapView in it.

**Comment by hiepnguyen1195** [comment]
I got same issue. Can not detect `onResponderRelease` of View component when I display MapView in it.

**Comment by alexeyvax** [comment]
@arunpugahz I guess it's not react-native-maps bug.
I faced the same issue and seems like a found fix.

There is my code:
```
<MapView
  ...
  onStartShouldSetResponder={() => true}
  onResponderRelease={() => myCallback()}
  ...
></MapView>
```
and `myCallback()` called when you release the touch the screen

https://reactnative.dev/docs/view#onstartshouldsetresponder

**Comment by arunpugahz** [comment]
@alexeyvax Tried the same, Still not working

**Comment by tharakanwn2014** [comment]
@arunpugahz did you able to fix it?

**Comment by kickbk** [comment]
Experiencing the same issue with `onTouchEnd` which isn't firing on iOS.

**Comment by arunpugahz** [comment]
@tharakanwn2014 nope. Tried different solutions but didn't work.

**Comment by tharakanwn2014** [comment]
@arunpugahz  I used a timeout to manually stop the touchstart after some seconds.

**Comment by nkulic** [comment]
Same issue

**Comment by hlspablo** [comment]
@christopherdro hi chris, there is some workaround about it?
