### ISSUE TITLE
showMyLocationButton setting not taking effect unless map is explicitly resized

### ISSUE THREAD

**Issue by jakegriesmaier** [react-native-maps/react-native-maps#3288]
# Bug

## Environment info
* Expo 3.13.1
* Running on an Android Device

React native info output:
```bash
 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 2.39 GB / 7.72 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

Library version: 0.26.1

## Steps To Reproduce

1. Create a `MapView` with `showsMyLocationButton` prop set to `true`
2. Run the application and view the map
3. You will notice that the MyLocationButton is not visible in the top right corner
4. If the map width is changed, after expo refreshes the MyLocationButton will be visible (does not 
    matter what the size is changed to/from, updating the size makes the icon appear)

Describe what you expected to happen:

1. Expected the MyLocationButton to be visible from the start, without having to adjust the map size

## Reproducible sample code
```javascript
import React, { useEffect, useState } from 'react';
import {
  StyleSheet,
  View,
  Dimensions
} from 'react-native';
import MapView, { Marker } from 'react-native-maps';

export default function HomeScreen() {

  return (
    <View style={styles.container}>
      <MapView style={styles.mapStyle}
        initialRegion={{
        latitude: 37,
        longitude: -122,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0412,
      }}
      showsUserLocation = {true}
      showsMyLocationButton={true}
      showsCompass={true}>
      </MapView>
  </View>
  );
}

HomeScreen.navigationOptions = {
  header: null,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapStyle: {
       width: Dimensions.get('window').width, 
       //^This line is changed to the commented line below.
       // After Expo refreshes, the button becomes visible
       // width: Dimensions.get('window').width / 2,
       height: Dimensions.get('window').height,
  },
});
```

**Comment by jmbredal** [comment]
I can confirm this as an issue. I solve this by resizing the map on map ready.

**Comment by askpatrickw** [comment]
> I can confirm this as an issue. I solve this by resizing the map on map ready.

@jmbredal do you have an example of this you can share?

**Comment by MinaroShikuchi** [comment]
#2010

**Comment by vincicat** [comment]
> > I can confirm this as an issue. I solve this by resizing the map on map ready.
> 
> @jmbredal do you have an example of this you can share?

similar to this [so](https://stackoverflow.com/questions/55738286/how-to-fix-show-location-button-in-android-react-native-map), except the state holds the height (a real number),  not a margin 

note: the reason for using the height is to make the re-rendering less "visible" to the user

```jsx
const height = Dimensions.get('window').height
const [mapHeight, setMapHeight] = useState(height - 1)

<MapView
  //...
  style={{
    height: mapHeight,             // using state in styling
    ...StyleSheet.absoluteFillObject,
  }}
  onMapReady(()=>{
    // do your stuff
    // set the height before end of the callback
   setMapHeight(height); //set to '100%' should work for non-TS code
  })
/>
```
