### ISSUE TITLE
Allow access to native map marker icon so Markers can have pin and children

### ISSUE THREAD

**Issue by jcb121** [react-native-maps/react-native-maps#3298]
# Feature Request

Currently if you give the Marker component children, it will replace the native marker and you will have to source your own marker icon. I would like to add a append to my map marker, not replace the entire marker.

## Why it is needed

I have a map with multiple points and I would like the user to be able to see the name of these points without selecting a marker.

## Possible implementation

Export the default marker from the marker file.

### Code sample

`import Marker, { MarkerIcon } from 'react- native-maps/marker'
\<Marker>
    <MarkerIcon color="green"/>
    <Text>I am the name</Text>
</Marker>`

**Comment by aliwaqassi** [comment]
Use marker's ```title```  and  ```description```  props
