### ISSUE TITLE
iOS map onRegionChange and onRegionChangeCompleted events will be ignored if `animateCamera` is called multiple times

### ISSUE THREAD

**Issue by zupaox** [react-native-maps/react-native-maps#3303]
# Bug

iOS with Apple Map only.

We use an `ignoreRegionChanges` flag to stop emitting the `onChange` event during the animating a camera:

![image](https://user-images.githubusercontent.com/46878464/75220313-1a108a00-57da-11ea-88ec-2d17ee92087f.png)

If the `animateCamera` method is called again before the first animation completed, it is possible that the `originalIgnore` value for second call to be `YES`, which is the `ignoreRegionChanges` value for the first call. That means after the second animation block completed, the `ignoreRegionChanges` will be set to `YES` and that would prevent all future `onChange` events from emitting.

This can be fixed in the js code by making sure that we don't call `animateCamera` before the previous animation completed. It is not very obvious though, so it is probably worth to fix.

A potential fix is to use a counter, whenever the `animateCamera` is executed, we increase the counter and when animation completed we decrease it. But there might be other options there.

## Environment info

React native info output:

```bash

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.08 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6
```

Library version: ^0.26.1

## Steps To Reproduce

1. adding some log in the `onRegionChange` and `onRegionChangeCompleted` callback
2. executing the `animateCamera` twice and make sure the gap between the two calls is less than the first call's animated duration. For example:
```
this.map.animateCamera({ center }, 100);
setTimeout(()=>{
  this.map.animateCamera({center}, 100);
}, 50);
```
3. after the two animation, all future `onRegionChange` and `onRegionChangeCompleted` events will not be available in iOS.
...

Describe what you expected to happen:

1. the `onRegionChange` and `onRegionChangeCompleted` events should be continue reporting after the animation finished.

**Comment by kalzoo** [comment]
Great writeup! Just encountered this as well. I just wrap `animateCamera` to throttle calls, but it would be "nice" if that weren't necessary.

**Comment by Appkidd** [comment]
Thank you. Likely just saved me hours of troubleshooting.

**Comment by arunpugahz** [comment]
Yep, Facing the same issue.

**Comment by MaRaSu** [comment]
Just ran into this same bug. I would vote for fixing it in the library code, it's pretty serious bug on the core functionality which is very easy to run into if you have e.g. implemented your own location update & marker functionality that uses animateCamera to center to the map for user's location while also listening to onRegionChange events to track & persist map region.

**Comment by yonahforst** [comment]
Ran into this bug as well. It took me a while to figure out why my `onRegionChangeCompleted` updates had stopped

**Comment by yonahforst** [comment]
I managed to work around it with this code
```js
  const isAnimating = useRef()

  useEffect(() => {
    if (!location) return

    if (!isAnimating.current) {
      isAnimating.current = true
      mapRef.current.animateCamera({
        center: location.coords,
        heading: location.coords.heading,     
      }, { duration: 500 })
      setTimeout(() =>  isAnimating.current = false, 500)
    }
}, [ location ])

```

**Comment by i-mighty** [comment]
@yonahforst ,
Full logic for this please.

**Comment by vyxxr** [comment]
I'm facing the same issue

**Comment by audrew** [comment]
Maybe this is not the right topic, but I can't get dynamic values for animateCamera.. 

``` ref={(current) => map.current = current}
                onLayout={() => {
                    map.current.animateCamera({
                        center: { latitude: location?.coords?.latitude, longitude: location?.coords?.longitude },
                        zoom: zoomLevel, // was 7
                        heading: 50,
                        pitch: pitchLevel,
                        altitude: 5,
                    })
                }}
```
The camera just does not change even pitch and zoom values change in the state..
