### ISSUE TITLE
'NSLocationWhenInUseUsageDescription' is needed even no location is in use

### ISSUE THREAD

**Issue by FlashLim** [react-native-maps/react-native-maps#3305]
# Question

While I try to submit app to App Store and I got a message from them : 

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

I understand I need to declare ``NSLocationWhenInUseUsageDescription `` in info.plist while using the location. However, I did not use any location, but still Apple is detecting this. 

Any workaround?

Current code on map:

`
      <MapView
        ref={(ref) => {
          mapRef = ref;
        }}
        initialRegion={{
          latitude: 0,
          longitude: 0,
          latitudeDelta: 80,
          longitudeDelta: 80,
        }}
        style={{ flex: 1 }}
        customMapStyle={mapJson}
        provider={PROVIDER_GOOGLE}
        onRegionChangeComplete={onRegionChangeComplete}
`

OS: iOS
Map: Google Map
Version: 
react-native-maps v0.26.1
react-native v0.61.5
react 16.9.0

**Comment by diegorodriguesvieira** [comment]
@FlashLim are you using expo?

**Comment by FlashLim** [comment]
I am not using expo.

> @FlashLim are you using expo?

**Comment by diegorodriguesvieira** [comment]
In your Info.plist file you need to add the NSLocationWhenInUseUsageDescription key with a description

**Comment by FlashLim** [comment]
> In your Info.plist file you need to add the NSLocationWhenInUseUsageDescription key with a description

I know the Apple is requesting, but why do we need to add this key in the info.plist?

If the underlying reason is because of react native is doing multiple layer of parsing data, end up it is very hard to hide the permission. 

Then, I understand. But what should I write in the description?

**Comment by diegorodriguesvieira** [comment]
A message that tells the user why the app is requesting access to the user’s location information.

See:
https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationusagedescription

**Comment by enocholumide** [comment]
@diegorodriguesvieira I use react-native-maps in my project too, and I usually get NSLocationWhenInUseUsageDescription warning from Apple. 

For the map component, I always provide the map center with coordinates fetched from the server, and I NEVER request/use the user's location. 

For me, it is difficult to put this NSLocationWhenInUseUsageDescription in the Info.plist file because I never use this information.

In this situation, what do I have to do, any work around?

**Comment by diegorodriguesvieira** [comment]
@enocholumide are you using google maps or apple maps in iOs?

**Comment by enocholumide** [comment]
@diegorodriguesvieira I use the Apple Maps for iOS.

**Comment by diegorodriguesvieira** [comment]
I don't know the rules to use the apple maps bro, but my suggestion is to add this description to avoid issues with apple store process

**Comment by LuongTruong** [comment]
Hello @diegorodriguesvieira and @enocholumide : I am using the Google Map and face the same issue. 

I use Map just for some marker, there is no user location access. Can you please give me some example for purpose string in this case? I am really appreciated.

**Comment by edanedison** [comment]
Is there any update on this? I can confirm it is still an issue. It's not ideal to just add the 'NSLocationWhenInUseUsageDescription' when the user location isn't even required, because it means the user gets a big permissions popup come up as they start up the app, telling them they need to give away their location, when that isn't the case at all. In our app, we simply want to show a map of a point of interest, not  a marker for the user location. I've looked into the code but can't seem to find out what the issue is.

**Comment by edanedison** [comment]
I've just managed to temporarily resolve this. Not a proper solution but I don't know C programming, but in AIRMap.m, on line 348, I took out the block that requests user location access from the api and replaced with.

```
- (void)setShowsUserLocation:(BOOL)showsUserLocation
{
    showsUserLocation = showsUserLocation;
}
```

Created a fork and used this. I've just submitted to app store and didn't receive the usual plist warning. Map still functions ok.
There must be something dodgy with the original logic as it's returning true even when the prop is set to false in the app. Sorry for the hacky comment / solution but just thought i'd share in case this is helpful to someone else, or perhaps someone can fix the logic and create a PR.

**Comment by brtdv** [comment]
For what it's worth, I was having this same issue, my app asked the user for location permission while I did not really need it. When submitting, I got the same ITMS-90683 message that told me I need to set a NSLocationWhenInUseUsageDescription.

I was able to avoid the "Allow app to use location data" window after explicitly setting the `<MapView showsUserLocation={false} />`

**Comment by mwegener-com** [comment]
Still facing the same issue.
 @brtdv your solution is not working for me.

**Comment by matejpolak** [comment]
I'm facing the same issue, any solution to that other then forking and fixing this ourselves?
