### ISSUE TITLE
onPress method doesn't get triggered on Polyline and Polygon components

### ISSUE THREAD

**Issue by michaloslav** [react-native-maps/react-native-maps#3314]
# Bug
Pretty much what the title says. onPress works on Marker but not on Polyline and Polygon

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 1.31 GB / 15.60 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.26.1

## Steps To Reproduce

1. See the code below
2. Try tapping on the Marker and then on the Polygon - the Marker's method gets triggered, the Polygon's doesn't

Describe what you expected to happen:

1. I expect the Polygon's and Polyline's onPress to get triggered when I tap on them

## Reproducible sample code
```js
import React from "react"
import MapView, { Marker, Polygon} from "react-native-maps";

export default function App()  {
  return (
      <MapView style={{ flex: 1 }}>
       <Marker
          coordinate={{ longitude: 0, latitude: 0}}
          onPress={() => console.log('This gets logged')}
        />
        <Polygon
          coordinates={[
            { longitude: 5, latitude: 5 },
            { longitude: 15, latitude: 5 },
            { longitude: 15, latitude: 15 },
            { longitude: 5, latitude: 15 },
          ]}
          fillColor="red"
          onPress={() => console.log('This doesn\'t get logged')}
        />
      </MapView>
  );
}
```

I also put it on Snack:
https://snack.expo.io/ryQVY7h4U

**Comment by mattcoker** [comment]
@michaloslav You need to add the `tappable` prop to the Polygon in order for the `onPress` function to be triggered. See the props documentation on the Polygon component [here](https://github.com/react-native-community/react-native-maps/blob/master/docs/polygon.md).

>Tappable: Boolean to allow a polygon to be tappable and use the onPress function.
