### ISSUE TITLE
Feature Request: <Marker /> isPreselected on Google Maps

### ISSUE THREAD

**Issue by puremana** [react-native-maps/react-native-maps#3317]
# Feature Request

Currently the Marker `isPreselected` prop only works on iOS Apple Maps. I would love support for Google Maps on both iOS and Android

## Why it is needed

In my app I only have one marker showing, and it makes sense to me to have the title and description of the marker visible without having to tap it.

## Possible implementation

When the marker component is mounted, instead of ignoring the prop, check if the prop is true and if so, run the select method? I haven't looked at the underlining code.

**Comment by dpyeates** [comment]
+1
