### ISSUE TITLE
Hand Drawing Polyline on map gets lagged - react native

### ISSUE THREAD

**Issue by AFMW** [react-native-maps/react-native-maps#3333]
# Bug
I'm hand drawing a Polyline but it's really slow, is it a way to improve it?
When the finger moves slow over the map the Polyline really gets rendered in a laggy way.
I'm using the exact code from the PolylineCreator example [https://github.com/react-native-community/react-native-maps/blob/master/example/examples/PolylineCreator.js](url)

## Environment info
*"react-native": "0.59.10",*
*"react-native-map-clustering": "^3.1.2",*
*"react-native-maps": "^0.25.0".*

## Steps To Reproduce

1. slide the finger over the map for trigger the onPanDrag event
2. move the finger slowly around the map for rendering the polyline.

Describe what you expected to happen:

1. The Polyline must not take all that time for being render until the position where the finger is.

## Reproducible sample code

`constructor(args) {
      this.state={
        regionLocal: {latitude: 37.78825,
                      longitude: -122.4324,
                      latitudeDelta: 0.1022,
                      longitudeDelta: 0.0521
                  },
        polylines: [],               
        editing: null
      }
    }`

    onPanDrag(e) {
      const { editing } = this.state;
      if (!editing) {
        this.setState({
          editing: {
            id: id++,
            coordinates: [e.nativeEvent.coordinate],
          },
        });
      } else {
        this.setState({
          editing: {
            ...editing,
            coordinates: [...editing.coordinates, e.nativeEvent.coordinate],
          },
        });
      }
    }`

    render() {
      return (
          <MapView  mapRef={ref => this.map = ref}
              style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0
              }} 
              initialRegion={this.state.regionLocal}
              showsUserLocation={true}
              showsPointsOfInterest={true}
              showsBuildings={true}
              showsMyLocationButton={false}
              loadingEnabled={true}
              clusterColor={"#140c98"}
              spiderLineColor={"#140c98"}
              radius={30}
              moveOnMarkerPress={false}
              maxZoom={13}
              scrollEnabled={false}
              onPanDrag={(e)=>{this.onPanDrag(e)}}
              >
                  {this.state.polylines.map(polyline => (
                      <Polyline
                        key={polyline.id}
                        coordinates={polyline.coordinates}
                        strokeColor="#000"
                        fillColor="rgba(255,0,0,0.5)"
                        strokeWidth={1}
                      />
                    ))}
                    {this.state.editing && (
                      <Polyline
                        key="editingPolyline"
                        coordinates={this.state.editing.coordinates}
                        strokeColor="#F00"
                        fillColor="rgba(255,0,0,0.5)"
                        strokeWidth={1}
                      />
                    )}
      </MapView>
      )}

Also Here's an example of the way I want it to work:

![image description](https://thumbs.gfycat.com/RemoteDisloyalCardinal-small.gif)

**Comment by vicky462** [comment]
+1
Any solution ??

**Comment by Biplovkumar** [comment]
Any update ?

**Comment by tavidian** [comment]
updates??

**Comment by wolfzer44** [comment]
I fixed it, hiding the markers. So when the onPanDrag start I set my state as my state editing as true and it hides the markers, when the user finishes drawing I set editing false and show the polygon with the markers. Sorry about my broke English.

**Comment by bhirave** [comment]
@wolfzer44 would you mind to share your fix ? i am running into same issue

**Comment by linhlie** [comment]
can you give me soucre code. pls

**Comment by msadhikari** [comment]
Any solution ??

**Comment by dev-event** [comment]
@msadhikari , @linhlie , @bhirave , @wolfzer44 , @tavidian , @Biplovkumar , @vicky462 , @AFMW For React Native, you can use
using PanResponder to track x y and convert to latitude and longitude. You can view it here: https://github.com/dev-event/react-native-maps-draw

**Comment by calz10** [comment]
hi all, did you find any solution for this with cluster?

**Comment by osama294** [comment]
I see this issue is very very old but I used the code posted @AFMW in one of my projects, the trick was to skip some co-ordinates periodically being added to the array being used to draw the polyline. 
I am using Functional Components instead of Class components so I modified the pan gesture to this :

`  const onPanDrag = (e) => {
  console.log(index++)
  if(!isActiveDraw && (index % 10 == 0)){
  setEditing([...editing, e.nativeEvent.coordinate])
  }
  }`
I hope it might someone else.

**Comment by shavez9119** [comment]
> I see this issue is very very old but I used the code posted @AFMW in one of my projects, the trick was to skip some co-ordinates periodically being added to the array being used to draw the polyline. I am using Functional Components instead of Class components so I modified the pan gesture to this :
> 
> ` const onPanDrag = (e) => { console.log(index++) if(!isActiveDraw && (index % 10 == 0)){ setEditing([...editing, e.nativeEvent.coordinate]) } }` I hope it might someone else.

can you pls send me the source code???

**Comment by osama294** [comment]
> 

@shavez9119 , it is on a public repository on my Git Profile
[ReactNativeMaps](https://github.com/osama294/ReactNativeMaps)

**Comment by waqaramjad** [comment]
Anu update on this issue, @osama294 I tried your solution but seems it's not working well ?

**Comment by shavezagicent** [comment]
> > 
> 
> @shavez9119 , it is on a public repository on my Git Profile [ReactNativeMaps](https://github.com/osama294/ReactNativeMaps)

Thanks @osama294 I'll look at your code. Maybe that will help me a lot.

**Comment by osama294** [comment]
> 

Please share the exact issue you are facing.

**Comment by shavezagicent** [comment]
> > 
> 
> @shavez9119 , it is on a public repository on my Git Profile [ReactNativeMaps](https://github.com/osama294/ReactNativeMaps)

@osama294 After running the git project you provide us above (git repo link) It is asking for login credentials ...please give me the details of login or tell me another way to access the project's Home Screen

**Comment by waqaramjad** [comment]
> @waqaramjad
> 
> Please share the exact issue you are facing.


the issue is that onPandrag, polylines work slowly

**Comment by osama294** [comment]
@shavezagicent 
Email: dev_account@maps.com
Password: 12345678
