### ISSUE TITLE
Setting minZoomLevel prop breaks initialRegion on iOS / Apple Maps

### ISSUE THREAD

**Issue by vonkanehoffen** [react-native-maps/react-native-maps#3338]
# Bug

It appears minZoomLevel causes initialRegion to zoom in way too far and to a different point on the map. 

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 472.12 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.27.0
Also tested with 0.26.1

## Steps To Reproduce

As tested in my repo [here](https://github.com/vonkanehoffen/planning-alerts/blob/52a35370c738a00fdbbb4081f768bcd29eec6f98/frontend-mobile/src/screens/test/MapViewRefs.js)

When 
```
const initialRegion = {
  latitude: 53.44377497031008,
  latitudeDelta: 0.05861431339441481,
  longitude: -2.262476727574612,
  longitudeDelta: 0.062443106335308585
};
```

This works fine:
```js
<MapView
  initialRegion={initialRegion}
  style={styles.map}
  ref={el => (map = el)}
/>
```

Add `minZoomLevel` like this, and it does not:
```js
<MapView
  initialRegion={initialRegion}
  minZoomLevel={12}
  style={styles.map}
  ref={el => (map = el)}
/>
```
...the map shows with maximum zoom and on a slightly different point on the map, like it's not respected the deltas (which should be within that level).

Describe what you expected to happen:

1. Initial Region should show the actual region it describes 

## Reproducible sample code

See above :-)
Thanks!

See these other tickets for anyone going through the same steps & Googling as me ;-)

https://github.com/react-native-community/react-native-maps/issues/1677
https://github.com/react-native-community/react-native-maps/issues/1338
https://github.com/react-native-community/react-native-maps/issues/209

**Comment by vonkanehoffen** [comment]
This is still an issue on 0.27.1 for me. Anyone any ideas? I don't even know where to start 😭

**Comment by mblarsen** [comment]
Experiencing this as well 0.27.1 on iOS (expo client) Apple Maps.

**Comment by Daavidaviid** [comment]
Same thing here

**Comment by mblarsen** [comment]
Ping!

**Comment by mblarsen** [comment]
Ping! :thinking:

**Comment by olliem36** [comment]
This is happening to me too, had multiple users report their initial location was set to some random place in Scotland...

After 2 hours of trying numerous solutions, hacks, workarounds, it turns out removing `minZoomLevel` resolved the issue.

I'm now looking for a workaround for `minZoomLevel` as I ned to cap how far the user can zoom out.

**Comment by olliem36** [comment]
Workaournd for min zoom level if it helps anyone!:

```
 <MapView
      onMapReady={() => {
        setMinZoomLevel(12)
      }}
      minZoomLevel={minZoomLevel} 
/>
```
