### ISSUE TITLE
0.27.0 breaks markers with tracksViewChanges={false} on Google Maps

### ISSUE THREAD

**Issue by vonkanehoffen** [react-native-maps/react-native-maps#3339]
# Bug

Custom map markers with `tracksViewChanges={false}` disappear following version update from 0.26.1 on Google maps (Android). They remain visible on Apple Maps (iOS). They show when `tracksViewChanges={true}` but this has documented performance issues so it's not a practical fix.

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 28.41 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.27.0

## Steps To Reproduce

1. Try viewing a Google Map on an Android device with a custom marker
2. Note how it's invisible :-(
...

Describe what you expected to happen:

1. For them to display!

## Reproducible sample code

https://github.com/vonkanehoffen/planning-alerts/blob/d46ba282f1c31e5f3daee17aeaf0daf278b879af/frontend-mobile/src/screens/home/user-location-map.component.js#L150

Aware this is quite a complex repo - I'll get a basic one together for testing when I can. 
Thought I'd make this ticket in the meantime to see if anyone else is experiencing the problem?
Thanks!

**Comment by kneza23** [comment]
I can confirm that this happens inn my code also after upgrade

**Comment by arcodergh** [comment]
Same happening here

**Comment by christopherdro** [comment]
I think the issue might be coming from this PR. I'll try and take a closer look later today.
https://github.com/react-native-community/react-native-maps/pull/3035/

**Comment by christopherdro** [comment]
I'm not noticing custom markers not showing up but I do see some issues with how styles are applied, specifically shadows with the PR I linked above.  

I think I will revert those changes either way but could one of you try setting the source in package.json to the following branch and see if it resolves the issue? `react-native-community/react-native-maps#revert`

**Comment by arcodergh** [comment]
In my case, I remove the parameter tracksViewChanges and the markers are rendered normally and now I can render images within the callout in Android that was not possible in previous versions. I know this can impact the performance but for now as a workaround I'm reducing the number of markers displayed in one view.

**Comment by christopherdro** [comment]
@arcodergh 
Could you try putting back that parameter and adding `tracksInfoWindowChanges` and setting that to false as well?

**Comment by arcodergh** [comment]
I tried all the possibilities for those parameters and it seems like markers are rendered in two cases: if 
tracksViewChanges is not present or if tracksViewChanges={true}, the other parameter doesn't seem to have any effect on marker rendering

**Comment by christopherdro** [comment]
@vonkanehoffen @kneza23 Could you take a look at my comments above and try the branch I specified above to see if it resolves your issue. 

It's likely that I will revert that commit and release a patch version until we can resolve the issues at hand.;

**Comment by draperunner** [comment]
@christopherdro I have the same issue with custom markers using `tracksViewChanges={false}` disappearing on Android with v0.27.0. I have tested your branch (`npm i -S react-native-community/react-native-maps#revert`) and can confirm that it fixes the issue.

**Comment by christopherdro** [comment]
Just published 0.27.1 that should address the issue for now. I'm going to leave this ticket open for now as we revisit the original PR that introduced the issue.

**Comment by JoaoLSA** [comment]
Same problem here. Fixed it by removing tracksViewChanges={false} but when I reload the application multiple times it becomes slow

**Comment by JoaoLSA** [comment]
Upgrading to 0.27.1 didn't fix it for me

**Comment by draperunner** [comment]
@JoaoLSA did you try v0.27.1 that was published 2 hours ago?

**Comment by JoaoLSA** [comment]
@draperunner Yes, it worked. Thanks

**Comment by vonkanehoffen** [comment]
Sorry just seen this. I should set my notifications up properly ;-) Can confirm 0.27.1 fixes this for me too. Thanks so much. You guys are the best! :-D

**Comment by adamMebarki** [comment]
Hello, thanks for your work it helps us a lot.

Same problem here, while I used the version 0.27.1. Maybe it is because of my implementation of markers.
I use react-native-maps with react-native-snap-carousel, and both can interact between them with a selected marker.
When I select a card in the carousel, the corresponding marker is selected and when I select a marker, the carousel shows the corresponding card. The selected marker has a different colour.

When trackViewChanges is false, the selected marker is not updated (first video), and if I remove trackViewChanges, markers on the same coordinates are flickering (second video).

On Android, I don't see any impact.

| tracksViewChanges = false | without tracksViewChanges |
| ------ | ------ |
| ![tracksViewChanges_false](https://user-images.githubusercontent.com/13995591/77745710-0bf19b80-701c-11ea-93b3-f7859ae13875.gif) | ![without_tracksViewChanges](https://user-images.githubusercontent.com/13995591/77745739-1a3fb780-701c-11ea-8f48-f200f92f05bb.gif) |

**Comment by RobTS** [comment]
@draperunner I still experience this problem on iOS for one out of five to ten initial renders with a custom image, and it won't show up upon property change, either. When I set tracksViewChanges to true, it does not happen, when I remove the custom image, the render works consistently as well.

My setup is pretty basic, I have a react navigation tab navigator and hide the map when the tab is not in focus.

**Comment by dl-husky73** [comment]
Hi, I am having a similar problem.  My SVG custom markers worked fine until I upgraded RNM to 27.1 last weekend and now they have just color shadings instead of art.  I am on latest Android, RN 62 but seems continuation of this issue.  Wondering if anyone else had style problems?

**Comment by valeriik** [comment]
I have the same issue on 0.27.1 on Android (RN 0.61.2). Markers absolutely disappeared.

**Comment by DentVega** [comment]
I have the same problem in 0.27.1 on Android (RN 0.63.4). Markers blink when changing region.

**Comment by serbanstef** [comment]
In my case a workaround was to add a state update to the Marker's onLayout prop to re-render its parent:

tracksViewChanges={Platform.OS === 'android' ? false : true}
onLayout={() => setSomeState(null)}

**Comment by ingowonner** [comment]
We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem.
Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't not fully work for us so we adopted his idea and tried a little different approach:

We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!

For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.

```tsx
const markerRef = useRef<Marker>(null);

const doRedraw = () => {
  markerRef.current?.redraw();
};

<Marker
      ref={markerRef}
      coordinate={coordinate}
      tracksInfoWindowChanges={false}
      tracksViewChanges={false}
      onPress={() => onSelectPartner(partner)}>
      <Image
        source={selected ? icons['pinSelected'] : icons['pin']}
        fadeDuration={0}
        onLoadEnd={doRedraw}
        style={{
          width: 40,
          height: 40,
          resizeMode: 'contain',
        }}
      />
</Marker>
```

**Comment by pedrohcdo** [comment]
> We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem.
> Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't fully work for us so we adopted his idea and tried a little different approach:
> 
> We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!
> 
> For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.
> 
> ```tsx
> const markerRef = useRef<Marker>(null);
> 
> const doRedraw = () => {
>   markerRef.current?.redraw();
> };
> 
> <Marker
>       ref={markerRef}
>       coordinate={coordinate}
>       tracksInfoWindowChanges={false}
>       tracksViewChanges={false}
>       onPress={() => onSelectPartner(partner)}>
>       <Image
>         source={selected ? icons['pinSelected'] : icons['pin']}
>         fadeDuration={0}
>         onLoadEnd={doRedraw}
>         style={{
>           width: 40,
>           height: 40,
>           resizeMode: 'contain',
>         }}
>       />
> </Marker>
> ```

I love u man

**Comment by wordisthebird** [comment]
> We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem. Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't fully work for us so we adopted his idea and tried a little different approach:
> 
> We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!
> 
> For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.
> 
> ```tsx
> const markerRef = useRef<Marker>(null);
> 
> const doRedraw = () => {
>   markerRef.current?.redraw();
> };
> 
> <Marker
>       ref={markerRef}
>       coordinate={coordinate}
>       tracksInfoWindowChanges={false}
>       tracksViewChanges={false}
>       onPress={() => onSelectPartner(partner)}>
>       <Image
>         source={selected ? icons['pinSelected'] : icons['pin']}
>         fadeDuration={0}
>         onLoadEnd={doRedraw}
>         style={{
>           width: 40,
>           height: 40,
>           resizeMode: 'contain',
>         }}
>       />
> </Marker>
> ```

Brilliant! thank you!

**Comment by zell180** [comment]
> We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem. Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't fully work for us so we adopted his idea and tried a little different approach:
> 
> We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!
> 
> For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.
> 
> ```tsx
> const markerRef = useRef<Marker>(null);
> 
> const doRedraw = () => {
>   markerRef.current?.redraw();
> };
> 
> <Marker
>       ref={markerRef}
>       coordinate={coordinate}
>       tracksInfoWindowChanges={false}
>       tracksViewChanges={false}
>       onPress={() => onSelectPartner(partner)}>
>       <Image
>         source={selected ? icons['pinSelected'] : icons['pin']}
>         fadeDuration={0}
>         onLoadEnd={doRedraw}
>         style={{
>           width: 40,
>           height: 40,
>           resizeMode: 'contain',
>         }}
>       />
> </Marker>
> ```

GENIO!!! THANK YOU!

**Comment by AkibShaih** [comment]
Wroked for me. Thank you!

**Comment by AkibShaih** [comment]
> > We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem. Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't fully work for us so we adopted his idea and tried a little different approach:
> > We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!
> > For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.
> > ```tsx
> > const markerRef = useRef<Marker>(null);
> > 
> > const doRedraw = () => {
> >   markerRef.current?.redraw();
> > };
> > 
> > <Marker
> >       ref={markerRef}
> >       coordinate={coordinate}
> >       tracksInfoWindowChanges={false}
> >       tracksViewChanges={false}
> >       onPress={() => onSelectPartner(partner)}>
> >       <Image
> >         source={selected ? icons['pinSelected'] : icons['pin']}
> >         fadeDuration={0}
> >         onLoadEnd={doRedraw}
> >         style={{
> >           width: 40,
> >           height: 40,
> >           resizeMode: 'contain',
> >         }}
> >       />
> > </Marker>
> > ```
> 
> GENIO!!! THANK YOU!




> > We had the same issue where all Markers had disappeared on Android phones. For performance reasons we had to set `tracksViewChanges={false}`, but this disables any drawing of images on Android. Since we want to also change the image if the Marker is selected this is a real problem. Like @serbanstef suggested we need to somehow re-render the Markers manually. His solution didn't fully work for us so we adopted his idea and tried a little different approach:
> > We tried to make use of the `redraw` method (https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) and found a working solution!
> > For Android `fadeDuration={0}` is important because if the source of the Image changes Android starts a fade animation with a default duration of 300ms. If we don't zero this the redraw will run to early and a semi-transparent image is shown.
> > ```tsx
> > const markerRef = useRef<Marker>(null);
> > 
> > const doRedraw = () => {
> >   markerRef.current?.redraw();
> > };
> > 
> > <Marker
> >       ref={markerRef}
> >       coordinate={coordinate}
> >       tracksInfoWindowChanges={false}
> >       tracksViewChanges={false}
> >       onPress={() => onSelectPartner(partner)}>
> >       <Image
> >         source={selected ? icons['pinSelected'] : icons['pin']}
> >         fadeDuration={0}
> >         onLoadEnd={doRedraw}
> >         style={{
> >           width: 40,
> >           height: 40,
> >           resizeMode: 'contain',
> >         }}
> >       />
> > </Marker>
> > ```
> 
> GENIO!!! THANK YOU!

THANKS MAN! You saved me

**Comment by melyux** [comment]
Any way to do this when you're not using an Image? Just a view with some text in it. No `onLoadEnd` on those to hook onto.
