### ISSUE TITLE
Using `mapPadding` prop on Android makes Google logo invisible or partially hidden.

### ISSUE THREAD

**Issue by dkoprowski** [react-native-maps/react-native-maps#3340]
# Bug
Using `<MapView>` with `mapPadding` prop on Android makes Google logo hidden or event completely invisible. 

In my opinion it's a bug and I don't know if it needs separate issue or it can be handled here.

This is what happens when `mapPadding` is ```{
  top: 20,
  right: 30,
  bottom: 15,
  left: 15
}```
![image](https://user-images.githubusercontent.com/2902306/76778181-ac88c580-67a9-11ea-922a-3d1e3e9367d4.png)

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 536.47 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.26.1

## Steps To Reproduce

1. Add `<MapView > ... </MapView>` component
2. Setup `mapPadding` prop to object ```{
  top: 20,
  right: 30,
  bottom: 15,
  left: 15
}```
3. Setup `provider={PROVIDER_GOOGLE}`

Describe what you expected to happen:

1. Google logo should be moved 15/15 like on the iPhone

## Reproducible sample code

```
        <MapView
          provider={PROVIDER_GOOGLE}
          style={{
            width: '100%',
            height: '100%'
          }}
          mapPadding={{
            top: 20,
            right: 30,
            bottom: 15,
            left: 15
          }}
        />
```

**Comment by toshe** [comment]
See this: https://github.com/react-native-community/react-native-maps/issues/2108 

Basically add this as a prop:
        
`onMapReady={() => { if (Platform.OS==='android') this.setState({ width: this.state.width - 1 })}}`

**Comment by ecoeats** [comment]
I'm getting no movement at all on Android. Google logo stays in the same place the entire time, but on iOS mapPadding does the job nicely.
