### ISSUE TITLE
Invariant violation: View config not found for name AIRMapHeatmap.

### ISSUE THREAD

**Issue by Nitingadhiya** [react-native-maps/react-native-maps#3346]
![Simulator Screen Shot - iPhone X - 2020-03-18 at 09 53 36](https://user-images.githubusercontent.com/7464953/76926756-2aacaf80-6903-11ea-83d3-409bd9387927.png)
# Bug

When using Default_provider for display map, Android Works fine but in iOS application occur issue. because of we are using HeatMap functionality.
if we are using google map provider it's working fine but App store rejected our application. apple store said you have use third party map library. for more information please see screenshot

## Environment info

React native info output:

"react": "16.9.0",
 "react-native": "0.61.5",
 "react-native-maps": "^0.27.0",

## Steps To Reproduce
<MapView
              provider={PROVIDER_DEFAULT}
              style={{flex: 1}}
              maxZoomLevel={11}
              onRegionChange={this.onRegionChange}
              region={{
                latitude,
                longitude,
                latitudeDelta,
                longitudeDelta,
              }}>
<MapView.Heatmap
                        points={filterHeatMap[key]}
                        opacity={1}
                        radius={Platform.OS === 'ios' ? 50 : 15}
                        maxIntensity={100}
                        gradient={{
                          colors: this.keyColor(key),
                          startPoints: [0, 0.25, 0.5, 0.75, 1],
                          colorMapSize: 500,
                        }}
                        heatmapMode={'POINTS_DENSITY'}
                        key={`${key}_${index}`}
                      />
</MapView>

**Comment by Utzel-Butzel** [comment]
The issue might be because `<Heatmap />` only works with Google Maps
#3097

**Comment by Nitingadhiya** [comment]
yes, That's Right. 
but for iOS, when implement Heatmap with Google maps and then upload build to Apple stores. 
they have rejected my application, because of i'm using Google maps.

Apple stores Error: Regarding 4.0, we continue to find that your app's location feature is not integrated with the built-in mapping functionality, which limits users to a third-party maps app.
