### ISSUE TITLE
[Bounty 50$] Bearing Arrow is not working on Android

### ISSUE THREAD

**Issue by creat-or** [react-native-maps/react-native-maps#3350]
# Bug

Reissue https://github.com/react-native-community/react-native-maps/issues/1069.
"The little arrow on the blue dot that is supposed to show you which way you are pointing your phone is wildly inaccurate. It does move every now and then, but not in any direction that makes sense and seems to jump around. The actual location is perfect."

On the same phone on the Google Maps Application, the direction is displayed correctly. So the information should be there and accurate. 

Here is a GIF to demonstrate the behavior, please note that I did not move my phone during the screencapture:
<img src="https://thumbs.gfycat.com/WatchfulFirstBedbug-small.gif" width="250">

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 158.12 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v13.7.0/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.27.0

## Steps To Reproduce

1. Add `MapView` with `showsUserLocation={true}` (or checkout the sample code below)
2. Accept the permission
3. Zoom to your location
4. Watch the icon for a few seconds.
5. The icon will not represent any useful direction and jump around

Describe what you expected to happen:

1. The icon shows the correct location and updates responsively as I move around

## Reproducible sample code
When trying, just make sure to fill your API_KEY in AndroidManifest.xml.
https://github.com/creat-or/MinimalMapsProject

**Comment by rborn** [comment]
@creat-or try to add     
~~~
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
~~~
 in AndroidManifest.xml 

The module by itself only uses ACCESS_COARSE_LOCATION

**Comment by creat-or** [comment]
Oh yes, thank you! I forgot to add it in the minimal example and did it now.
Unfortunately the bug is still there.

**Comment by MasterAssailant** [comment]
I am facing the same issue as well. Dunno if it's useful but just to note that this feature works fine on the iOS version but is not working on the Android version.

**Comment by toshe** [comment]
+1 here, also with react-native-maps 0.27.1. Issue is only on Android; on iOS version it works as it should.

**Comment by sihan010** [comment]
+1 here, can confirm the issue still exists 29th July 2020

**Comment by toshe** [comment]
I would like to post a bounty for this issue since it's impacting our users a lot. Who is the main maintainer of the repo? Can you please add it to bounty source?

**Comment by creat-or** [comment]
Nice, thank you for offering a bounty @toshe!

**Comment by badaz** [comment]
I'm facing the same situation, has anyone found a workaround?

RN 0.68.1
react-native-maps 0.31.1

**Comment by jgoldm** [comment]
I experienced the same issue so I ended up disabling showsUserLocation. Instead, I have a blue dot as a marker at the user's location and update the location every 30 seconds. And I created my own re-center button. I think there should just be an option to disable the bearing arrow.
