### ISSUE TITLE
Can't install with google maps iOS utils 3.x

### ISSUE THREAD

**Issue by Queeniie** [react-native-maps/react-native-maps#3354]
# Question

I want to install react-native-maps but I'm using `use_frameworks` in my Podfile (and I can't get rid of it). Google Maps iOS utils has now a branch 3.x which allows the use of `use_frameworks` but `react-native-maps` dependency asks for the version 2.1.0.
Is it possible to change that so I can use the module directly?
Thanks.

**Comment by rborn** [comment]
What you can try is to go to node_modules/react-native-maps in your project and change the podspec files yourself and then run in  the  ios  folder `pod install`

If all works fine maybe make a PR too 😅

**Comment by Queeniie** [comment]
Unfortunately, even if I changed the dependency needed, I still get this error:
```
target has transitive dependencies that include statically linked binaries: (xx/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, xx/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and xx/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)
```
So though Google Maps iOS utils allows the use of `use_frameworks` , `react-native-maps` doesn't.

**Comment by Queeniie** [comment]
I found a workaround just after posting the last comment with this: #1923 
```
pre_install do |installer|
# workaround for CocoaPods/CocoaPods#3289
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end`
```
The pods then install fine with no error but now I have either `AirMapCoordinate.h not found` or `RCTConvert+AirMap.h not found`. I did add AirMaps and AirGoogleMaps inside my project.

**Comment by pedrohcdo** [comment]
Some

> I found a workaround just after posting the last comment with this: #1923
> 
> ```
> pre_install do |installer|
> # workaround for CocoaPods/CocoaPods#3289
> Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end`
> ```
> 
> The pods then install fine with no error but now I have either `AirMapCoordinate.h not found` or `RCTConvert+AirMap.h not found`. I did add AirMaps and AirGoogleMaps inside my project.

This causes others bugs FUuu!

**Comment by Queeniie** [comment]
Yeah, I've been on this since then and I can't seem to find any solution ... I've tried everything, I've tried to set the `header search paths` to every folder I know that contain the headers I need but no luck. If anyone has the start of a solution for this, I'll take everything to be honest.

**Comment by pedrohcdo** [comment]
> Yeah, I've been on this since then and I can't seem to find any solution ... I've tried everything, I've tried to set the `header search paths` to every folder I know that contain the headers I need but no luck. If anyone has the start of a solution for this, I'll take everything to be honest.

I tried about 10 ways and it didn't work in any way. So I decided to go back to everything, update by update that I had done, edit line by line and finally it worked. I will describe what I did at the end.

1) Clear all (build, npm, ..)
  a) In project folder run:
    `rm -rf ./node_modules`
  b) Enter in ios folder and run: 
    `rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`
   obs: This step i found in -> https://gist.github.com/mbinna/4202236#gistcomment-1814665
  c) In XCode clear build

2) Deintegrate your pod, I heard that the command "use_frameworks!" you can make fun of the premises, in ios folder run:
  `pod deintegrate`

3) Now reset your machine, this step was very important for me (maybe XCode updates can make fun of open projects), restart your machine.

4) In your pod filde, do not use `use_frameworks!` , this can make fun of many libs, I am not aware of the reason but I switched to `use_frameworks! :linkage =>: static`
  In my case what started to hinder me was the onesignal libs, maps, places and text input mask .. The lib text input mask needed `use_frameworks!` but `use_frameworks!` bugged maps, places!  so I used the step described above `use_frameworks! :linkage =>: static` and resolved!
  Again, Remove all 'use_frameworks!' and use only 'use_frameworks! :linkage =>:static' (I put it inside the target of my project only).

5) I use the onesignal frame and with that I had these problems too: 
  `"'sharedApplication' is unavailable: not available on iOS (App Extension)"`
If you have this problem too then add this code in your pod (i added outside of project target): 
Obs: (Remember to put 'No' and not 'NO', as in the code below. And this step only works accurately if you perform step 2 before)

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
    end
  end
end
```

  The method it was only useful when used with line command 'react-native run-ios', by xcode it still throws the error, if you want to run through XCode, when the error appears in XCode double click on the project containing the error in the error window and it will be forwarded to all pods, select all, click in in build settings and set
'require only App-Extension-Safe Api' to 'No' for all. Unfortunately I still need to do this whenever I need to run 'pod install' and test the app directly through XCode.

6) I followed several tutorials that sent edit header path, framework path, add in linked libraries. I just undid everything, left the project as it was without these meaningless edits and did these steps above.

7) If necessary use:

`pre_install do |installer|
# workaround for CocoaPods/CocoaPods#3289
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end``

8) In project folder run:
  `npm install`

9) In ios folder inside your project folder run:
  `pod install`

10) Prepare a coffee, and try to build it again .. Good luck.

**Comment by Queeniie** [comment]
Thanks for your answer. I tried what you said but no luck. I have a few questions:
- Did you keep the AirMaps and AirGoogleMaps folders in your iOS targets ?
- Did you add the AirMaps library in the library folder?
- Did you keep all of that in your Podfile ?
```
pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils', '~> 3.0.2'
```

**Comment by pedrohcdo** [comment]
> Thanks for your answer. I tried what you said but no luck. I have a few questions:
> 
> * Did you keep the AirMaps and AirGoogleMaps folders in your iOS targets ?
> * Did you add the AirMaps library in the library folder?
> * Did you keep all of that in your Podfile ?
> 
> ```
> pod 'react-native-maps', path: rn_maps_path
>   pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
>   pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
>   pod 'Google-Maps-iOS-Utils', '~> 3.0.2'
> ```

Look my pod file: 
Obs:(I didn't use google maps, I ended up using the native one.)

`platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'gorjeta_app' do
  # Pods for gorjeta_app
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  
  pod 'react-native-safe-area', :path => '../node_modules/react-native-safe-area'

  pod 'RNTextSize', :path => '../node_modules/react-native-text-size/ios/RNTextSize.podspec'

  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'


  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  target 'gorjeta_appTests' do
    inherit! :search_paths
    # Pods for testing
    
    
  end
  
  use_frameworks! :linkage => :static
  use_native_modules!
  
  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.11.2', '< 3.0'
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-places'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    else
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'gorjeta_app-tvOS' do
  # Pods for gorjeta_app-tvOS

  target 'gorjeta_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
`

**Comment by Queeniie** [comment]
God thank you!!!!!!
It finally works!
I indeed had to use the native maps for iOS, instead of the google maps provider, but at this point, I'll be happy with anything. 
Thanks a lot for the time you took to help :)

**Comment by pedrohcdo** [comment]
:D !! Any time!

**Comment by stianjensen** [comment]
If someone else stumbles upon this closed issue, this comment worked for me: https://github.com/react-native-maps/react-native-maps/issues/3656#issuecomment-749570974
