### ISSUE TITLE
Fit map to geojson path

### ISSUE THREAD

**Issue by gcoro** [react-native-maps/react-native-maps#3361]
# Question

Hi, I need to fit the view to a path in the map, which was drawn using the `Geojson` component. 
When I call `this.map.fitToElements(true)`, it does not fit to the path. 
If I have any markers on the map, it correctly fits to them, but not to the path. 
Is there any way I can achieve this?

**Comment by rborn** [comment]
@gcoro It seems that It only checks for the markers https://github.com/react-native-community/react-native-maps/blob/703e0c7e0891e4b4248e8f99f2188c3b059caca7/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L834

**Comment by war2k10** [comment]
Hi, I also need to fit the view of a "MultiPolygon" using the Geojson component. Is there any plan to support this?

**Comment by gcoro** [comment]
@war2k10 if it can be useful for you to know, in the end I achieved the same result by calculating the bounding box of the polygon and then calling `this.map.fitToCoordinates` with the coordinates of the box extremes

**Comment by war2k10** [comment]
@gcoro Thanks for the solution.
