### ISSUE TITLE
CalloutSubview Support for Android

### ISSUE THREAD

**Issue by BeckyWu220** [react-native-maps/react-native-maps#3363]
# Feature Request

iOS has the CalloutSubview supported to allow subviews inside the bubble. It is very common 
 and practical to handle, for example, button clicking, in a bubble when a spot is highlighted on the map. 

![google-maps-bubble-freebie_thumb](https://user-images.githubusercontent.com/16603120/77802545-52ed8a00-7038-11ea-999e-b9496afc63d4.jpg)

## Why it is needed

It would be nice to have it in Android, so the maps behaves the same in both iOS and Android.

**Comment by githuboftigran** [comment]
Facing the same issue

**Comment by foxcreation** [comment]
Agreeing with the need for CalloutSubView on Android. Currently, the usage results in 'Invariant Violation: requireNativeComponent: "AIRMapCalloutSubview" was not found in UIManager', while the examples do imply the ability of using the Subview on Android as well...

Image of documentation: https://camo.githubusercontent.com/d76fd1619d2318f5eabaea0b90d23998cf8de781/687474703a2f2f692e67697068792e636f6d2f785437375964553048587279766f527161512e676966

**Comment by Pignatar0md** [comment]
Same issue

**Comment by 25matt12** [comment]
Same here

**Comment by tarokins** [comment]
Would like to have this added

**Comment by dyegooviedo** [comment]
Facing the same issue here

**Comment by EmreAbi** [comment]
same issue here

**Comment by AhmedSarhan** [comment]
same issue please solve it

**Comment by FelipeGCastro** [comment]
Same issue here

**Comment by abdelkebir7Y** [comment]
same issue

**Comment by demiters** [comment]
Bump? Is there some technical reason that blocks this?
