### ISSUE TITLE
Markers flicker on state update

### ISSUE THREAD

**Issue by nikhilkumar6** [react-native-maps/react-native-maps#3381]
# Question

We've multiple coordinates that we need to display on the map using markers. The marker clicked by the user has to be marked as active and have some operations performed for some other functionality.

When I update the state in onPress method of the marker all the markers flickers, probably due to re-render. I've added the unique key as well but it doesn't seem to work. 

I've an array named **markers** which is used to render the markers on the map.

```
return markers.map(marker => (
      <Marker
        tracksViewChanges={false}
        tracksInfoWindowChanges={false}
        animationEnabled={false}
        identifier={marker.id}
        key={marker.id}
        coordinate={{
          latitude: marker.location.latitude,
          longitude: marker.location.longitude,
        }}
        onPress={() => {
          setActiveMarker(marker.id);  // State update using hook
        }}>
       {if(activeMarker === marker.id)
        (<Icon
          width={22}
          height={32}
          source={require('../../assets/images/marker.png')})
        else
         (<Icon
          width={22}
          height={32}
          source={require('../../assets/images/activeMarker.png')})
         }
      </Marker>
));
```

I went through the previous issues but all of those mentioned that it's already fixed but I'm still experiencing the same issue.

The react-native-map version: 0.27.1

**Comment by faisalansari97** [comment]
Did you find any solution for this?

**Comment by cicconewk** [comment]
> Did you find any solution for this?

I had the same problem and I found out that the custom marker was the cause, i don't know why though. It stopped flickering when I used an image with the icon prop.

**Comment by rraina91** [comment]
I'm hitting something similar. I haven't tried to fix it, but I saw this other bug with a workaround that looks very promising. Just wanted to link it here in case you guys didn't see it and for future searchers.

#3013

**Comment by Diyaa-Gubarah** [comment]
for me i have 3 tab each one return MapView (I have file called CustomMap.js) So in my CustomMap.js I did this.

```
import {useIsFocused} from '@react-navigation/native';
.
.
export default CustomMap= ()=> {
  const isFocused = useIsFocused();
.
.
return (
    isFocused && (<MapView ......./>))
 }
```
