### ISSUE TITLE
Custom markers not always showing up on iOS with Google Maps (when using tracksViewChanges={false})

### ISSUE THREAD

**Issue by RobTS** [react-native-maps/react-native-maps#3384]
# Bug

When a marker with a custom image is placed on the Map and the tracksViewChanges-property is set to false (quasi mandatory for normal CPU load), it is not rendered consistently on iOS. Subjectively, there is a 1/10 chance of it not appearing. I created this basic sample project to showcase the issue (offering easy refresh ability): https://github.com/RobTS/react-native-maps-render-issue

(Edit: Maps key disabled due to Google writing me emails about it, feel free to use your own)

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 2.14 GB / 64.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

React Native 0.62.2
React Native Maps 0.27.1

## Steps To Reproduce

1. Start the sample application in release mode
2. Hit refresh button, see whether the marker still appears.
3. On one in 10 attempts, the marker won't show although it should, showcasing the bug.

## Reproducible sample code

https://github.com/RobTS/react-native-maps-render-issue

(Edit: Maps key disabled due to Google writing me emails about it, feel free to use your own)

**Comment by RobTS** [comment]
I did a little initial digging (the things mentioned probably aren't new to the maintainers):

* tracksViewChanges  seems to [always be instantiated as true](https://github.com/react-native-community/react-native-maps/blob/master/lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m)
* [The iOS documentation on markers mentions tracksViewChanges specifically when it comes to custom icons](https://developers.google.com/maps/documentation/ios-sdk/marker?hl=de#use_the_markers_icon_property)
* It contained this gem: `When an animation is running or the contents are being loaded asynchronously, you should keep the property set to YES until the actions are complete.`

As a little test, I created a branch where I set `tracksViewChanges` to true until three seconds after ref is being called, and it seems to fix the issue while having little CPU overhead ([see MR in sample project](https://github.com/RobTS/react-native-maps-render-issue/pull/1/files)). So it seems like `tracksViewChanges` is sometimes toggled prematurely, before the icon is loaded?

I am not a great iOS developer, so I am unsure whether I will be able to contribute a fix, but I might give it a try.

**Comment by lesmo** [comment]
I'm having this problem too. That note you found helped me come up with an idea for a quick and dirty fix.

As a workaround, I did something like this:

```jsx
const MyComponent = ({ coordinate }) => {
  const [mapReady, setMapReady] = useState(false);

  return (
    <MapView
      provider="google"
      onMapReady={() => setTimeout(() => setMapReady(true), 100)}>
      <Marker
        image={markerImage}
        tracksViewChanges={!mapReady}
        coordinate={coordinate} />
    </MapView>
  );
};
```

I tried using `setImmediate` instead of a `setTimeout`, but that "increased" the success rate (it didn't make it appear 100% of the time). Using a small timeout seems to work.

**Comment by ottor-o** [comment]
This issue does still exist. If I use the image prop to show markers from image assets, sometimes the markers don't get rendered at all or only some of them do. This only happens on iOS. If I set tracksViewChanges={true}, this fixes the issue but performance suffers a lot.
