### ISSUE TITLE
Yesterday update of ANDROID DEBUG EXPO CLIENT gives 25px top margin to AppContainer. APK build does not have such probem.

### ISSUE THREAD

**Issue by ExpoNfinity** [react-native-maps/react-native-maps#3387]
# Bug

Expo SDK 36
Android 7 Phone

`react-native info` output:

not using react-native CLI. The issue is not related to react-native library. The issue is related only to EXPO DEBUG ANDROID CLIENT

Library version: x.x.x

## Steps To Reproduce

1. Removed and installed expo sdk android client on 13th apr (still actual on 14th april too)
2. started debug on android with "expo start" -> run on android

Describe what you expected to happen:

1. noticed unwished new margin at top
2. tried to build apk, checked - no margin at top

## Reproducible sample code

render(){
return < AppContainer / >
}

EXPO SDK 36, latest android debug client

Guys, it's second time when someone published update that causes debug to not match the production. This should not happen, otherwise debug is useless.

**Comment by rborn** [comment]
Please check if the expo change you did uses the same version of this module or not. 
It might be an expo issue ?

**Comment by ExpoNfinity** [comment]
All i did is uninstalled Expo application from the phone and did Run android device/emulator from GUI, so Expo application was installed again, i don't think it could cause any change, but:
- I didn't update expo for month or two
- I didn't check on any other phone
I you are not experiencing this issue, i will try these and give an update

**Comment by rborn** [comment]
This module is used by expo so I'm not sure what changed what :| would be interesting to find out

**Comment by ExpoNfinity** [comment]
Today i've upgraded EXPO SDK to 37 (with just 1 manual fix needed to be applied it so far looks like the fastest upgrade comparing to few previous versions), but problem hasn't gone

Direct link to screenshot file: https://i.imgur.com/DAqG7X1.png

**Comment by ExpoNfinity** [comment]
Checked on other devices and found same. So far ended up with changing 'screen' to 'none' for headerMode in createStackNavigator

const AppNavigator = createStackNavigator({
    Main: {screen: Main},
}, {
headerMode: 'none' 
}

related info: https://stackoverflow.com/questions/45170712/margin-top-for-header-bar-in-react-native-navigation

I guess, Constants.statusBarHeight from 'expo-constants' isn't calculated properly anymore, pls check and/or give your comment where i was wrong
