### ISSUE TITLE
MapView backgroundColor is white. Transparent tiles (labels) do not appear transparent

### ISSUE THREAD

**Issue by Vahradrim** [react-native-maps/react-native-maps#3391]
# Bug

Transparent tiles do not appear transparent. The backgroundColor of MapView is white, it's blocking when needed to display transparent tiles over elements.

## Environment info

> System:
>     OS: Windows 10 10.0.18362
>     CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
>     Memory: 3.50 GB / 7.95 GB
>   Binaries:
>     Node: 12.16.1 - H:\Programs\NodeJS\node.EXE
>     npm: 6.13.4 - H:\Programs\NodeJS\npm.CMD
>   npmPackages:
>     react: ~16.9.0 => 16.9.0
>     react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
>     react-native-maps: 0.26.1

## Steps To Reproduce

Use a MapView component with a custom provider : 
Example : http://c.tile.stamen.com/terrain-labels/{z}/{x}/{y}.jpg

Describe what you expected to happen:
The tile and the MapView should appear transparent (expect the labels in the provider example).

## Reproducible sample code
        

> import MapView, { PROVIDER_DEFAULT, MAP_TYPES } from "react-native-maps";
>...
>         <MapView
>           provider={PROVIDER_DEFAULT}
>           mapType={Platform.OS == "android" ? MAP_TYPES.NONE : "standard"}
>           style={{ height: "100%", width: "100%" }}
>         >
>           <MapView.UrlTile
>             urlTemplate={"http://c.tile.stamen.com/terrain-labels/{z}/{x}/{y}.jpg"}
>             shouldReplaceMapContent={true}
>           />
>         </MapView>

The following tile is transparent (except the labels) but the MapView component has a white backgroundColor that covers the underlying elements : 
![12665](https://user-images.githubusercontent.com/32706466/79297684-e3d3ba80-7eac-11ea-9609-a5b53ada89b7.png)

By forcing the opacity of the MapView component (opacity={0.3}), we can see the underlying elements : (but the labels are 0.3 transparents too of course)
![Forcing opacity of MapView component](https://user-images.githubusercontent.com/32706466/79297975-bd624f00-7ead-11ea-90b4-a7de85b333af.png)

By putting an opacity to 0.8, the underlying map is almost covered by the MapView white background : 
![With opacity of MapView component to 0 8](https://user-images.githubusercontent.com/32706466/79298025-dec33b00-7ead-11ea-82b4-1f7719b2ed76.png)

No need to provide an image for the opacity 1, you get the idea.
Is it possible to fix that or letting the possibility to change the backgroundColor just like 'loadingBackgroundColor'

**Comment by taduyde** [comment]
The same issue

**Comment by nes123** [comment]
+1

**Comment by guilhermeJB** [comment]
+1
