### ISSUE TITLE
pinColor not true for IOS devices

### ISSUE THREAD

**Issue by thanhluantl2304** [react-native-maps/react-native-maps#3393]
# Bug

I set marker's pinColor = '#b5faff' but it shown '#45878c' in ios devices.
On Android, it worked fine.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/37209046/79333327-89883780-7f48-11ea-8bf6-2105f173a9f1.png)

**Comment by ChrisDesigns** [comment]
This still seems to be an issue this can be seen in this [example snack](https://snack.expo.io/@clenart4/react-native-maps-ios-pincolor-issue). It is the result of using PROVIDER_GOOGLE. I'm guessing the problem starts somewhere in AirGoogleMaps when passing these values.
