### ISSUE TITLE
redraw() function cannot be called for Marker

### ISSUE THREAD

**Issue by MIPB** [react-native-maps/react-native-maps#3403]
# Bug

Hello, I have been working with React Native Maps for a while and noticed that the function redraw() for the markers cannot be called.  **IMPORTANT**: I am also using react native clustering but it only affects the MapView, the Markers are untouched in theory.  

My objective was to redraw the marker to change its color, but I noticed the only functions callable for a Marker are the showCallout, hideCallout, redrawCallout and animateMarkerToCoordinate. This is a picture of the functions callable as stated on the official docs:

![image](https://user-images.githubusercontent.com/47779064/80134215-b5d23280-859e-11ea-8673-1e8be9a8a39c.png)

As you can see, there is another function redraw().

## Environment info
`react-native info` output:

```
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 8.51 GB / 15.92 GB
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 24, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 30.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version of RN Maps: 0.26.1

## Steps To Reproduce

In my app, the user can vote in a certain location yes or no. If Yes > No the color should be red. No > Yes should be green. Equal should be blue.

I use a function in my marker to determine the "pinColor". It is very simple, it compares my yes / no data from my database. **Initially it works correctly**

The problem comes when the user votes ---> **the marker has to be re-rendered, changed of color.** For that I tried using the redraw() function without success.

I attach a simplified code for this. I want to stress that the part of shouldComponentUpdate is working correctly and the changes in my redux state are being taken into account:

Also, I checked the functions hideCallout and showCallout and they work correctly. So there shouldn't be a problem with my ref. 

## Reproducible sample code

// Function to redraw specific marker
```
  shouldComponentUpdate(nextProps, nextState) {
    if (nextProps.data != this.props.data && nextState.cardInfo.id) {
      console.log(this.markers[nextState.cardInfo.id]);
      this.markers[nextState.cardInfo.id].redraw();
      return true;
    }
    return true;
  }
```

// MapView and Marker

          <MapView
            mapRef={ref => (this.myMapRef = ref)}
           //
            tracksViewChanges={true}
            initialRegion={this.state.region}
            onPress={this.unsetCard}>
            {this.props.data.map(marker => (
              <Marker
                key={marker.id}
                ref={ref => {
                  this.markers[marker.id] = ref;
                }}
                coordinate={marker.l.coords}
                pinColor={this.markerColor(marker.j)}
                onPress={() => {
                  this.setCard(marker.id);
                }}>
                <Callout
                  onPress={() => {
                    if (!this.state.showCard) {
                      this.setCard(marker.id);
                    }
                  }}>
                  <CustomCallout title={marker.t} />
                </Callout>
              </Marker>
            ))}
          </MapView>
`

**Comment by douira** [comment]
I have the same problem. Can we have an update on this? Using `tracksViewChanges` for rare updates is inefficient.

**Comment by hyunjinjeong** [comment]
I experienced the same problem and I think it's just the library's type declaration problem in `v0.26.1`. The `redraw()` method of Marker is not declared in `index.d.ts`.

This was fixed in this [PR](https://github.com/react-native-community/react-native-maps/pull/3261). However, it was applied from `v0.27.0`, I guess.
 
As a workaround, you can add a type in `index.d.ts` on your own:

![redraw_type](https://user-images.githubusercontent.com/11304601/88763542-462b9f00-d1ae-11ea-8a1e-49f3d2c57678.png)

Then you'll be able to use `redraw()`.

**Comment by ogntech** [comment]
Got "Type error: Cannot read property 'apply' of undefined" when trying to redraw.

**Comment by amhinson** [comment]
> Got "Type error: Cannot read property 'apply' of undefined" when trying to redraw.

I also got this error. It seems to be due to `AirMapMarkerManager.m` not containing a `redraw` method.

https://github.com/react-native-maps/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapMarkerManager.m
