### ISSUE TITLE
MapView Marker onDeselect event not responding when i create markers using list

### ISSUE THREAD

**Issue by javiersubiabre** [react-native-maps/react-native-maps#3409]
# Bug
What i need to accomplish is to set the state with the active marker being pressed. But when i press the MapView (and the marker deselects) i want to update the state with markerActive: null and i cant find a way to get the event onDeselect properly :/

Here is how my code looks like:

```
<MapView
          pitchEnabled = { false }
          rotateEnabled = { false }
          zoomEnabled = { false }
          scrollEnabled = { false }
          region = { this.state.region }
          style = {{ flex: 2 }}
          provider = 'google'
          showsUserLocation = { true }
          followsUserLocation = { true }
          mapType = 'satellite'>

          {this.state.markers.map((marker, index) => {
            if (marker) {
              const coords = {
                latitude: marker.latitude,
                longitude: marker.longitude,
              };

              return (
                <MapView.Marker
                  key={index}
                  coordinate={coords}
                  style={styles.marker}
                  onPress={this.onMarkerPress.bind(this, marker)}
                  onDeselect={console.log("deselected")}
                 >
                  {ImageForMarker}
                 </MapView.Marker>
              );
            }
          })}
        </MapView>
```

"deselected" is printed a lot of times (like in an infinite loop)

  
```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 48.39 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

```

Library version: "react-native-maps": "0.26.1"

## Steps To Reproduce

1. create MapView with a list of markers
2. try to get the onDeselect event correctly and update state activeMarker to null
...

Describe what you expected to happen:

1. press a marker, state activeMarker is equal to that marker
2. press on the MapView, marker goes unselected and update state activeMarker to null

**Comment by javiersubiabre** [comment]
I have created a Snack here: https://snack.expo.io/@javiersubiabre/mapview-test-on-touchableopacity-nonaction-when-longpress-on-map

And i have 2 problems (Iphone 5SE)
1.- Sometimes, when i longPress the map or a marker(coin) i cant press the big coin to randomize all coins, and i have to make an extra tap on the map in order to “unlock” the big Coin. This is happening on an iPhone 5SE, NOT on androids i think, and NOT on the Snack Preview (which leads this to be more complex to debug)

2.- The remaining issue of the title: ¿How to get the marker onDeselect event?

Would you please help me

**Comment by javiersubiabre** [comment]
I isolated the problem, and is happening only when i use

import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

to create the starting point of the app, snack is updated and you can test the bug testing on your iPhone devices (not an emulator) you just have to longPress the map or a marker and then the TouchableOpacity button won't be able to trigger unless you tap some were in the map again

**Comment by rborn** [comment]
I'll ping somebody from react-navigation, no promise they'll respond though :)

**Comment by javiersubiabre** [comment]
> I'll ping somebody from react-navigation, no promise they'll respond though :)

Thank you so much @rborn

**Comment by rborn** [comment]
Did so, let's see 

I suspect a conflict between the map and react-native-reanimated. 
But I'm not sure :)

**Comment by javiersubiabre** [comment]
Problem Solved, it was the style position:'absolute' of the TouchableOpacity :) thanks !! (i still have toe problem trying to get the onDeselect event though.
