### ISSUE TITLE
Default map style briefly flashes when using a customMapStyle

### ISSUE THREAD

**Issue by pdugan20** [react-native-maps/react-native-maps#3416]
# Bug

I'm using a customMapStyle for a MapView in iOS for a dark mode theme. Whenever the map loads for the first time, there's a brief flash (flicker) of the default Google Maps style before the theme takes over.

## Environment info
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 559.97 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:

    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0
.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

```
Library version: 0.27.1

## Steps To Reproduce

1. Pass a customMapStyle into a MapView component
2. Render the MapView component

Describe what you expected to happen:
1. The MapView loads the customMapStyle without first loading the default Google Maps style

## Reproducible sample code
```
<MapView
    ref={(ref) => {
        this.mapView = ref;
    }}
    customMapStyle={mapStyle}
    provider={PROVIDER_GOOGLE}
    style={{
        height: '100%',
        zIndex: 1,
        overflow: 'hidden',
    }}
    mapType={mapType}
    initialRegion={region}
    showsUserLocation
    loadingEnabled
    showsMyLocationButton={false}
    showsPointsOfInterest={false}
    showsCompass
    onMapReady={this.onMapReady}
    mapPadding={mapPadding}
/>
```

Where you pass in any of the styles from: https://mapstyle.withgoogle.com/

Here's what it looks like in practice (note the brief flicker/flash):

![j1116](https://user-images.githubusercontent.com/1837100/80893101-37535000-8c84-11ea-9366-442f69b77cae.gif)
![tQLwR](https://user-images.githubusercontent.com/1837100/80893105-3a4e4080-8c84-11ea-831b-acdfbc9a0292.gif)

**Comment by pdugan20** [comment]
Any update on this? Is there any additional information or code samples that I can provide for context?

**Comment by dpz3579** [comment]
+1 noticed the same issue even if you just switch between theme on a click.

**Comment by alexandrepalagem** [comment]
Here's an example with Animated.View



![Aug-08-2020 16-55-23](https://user-images.githubusercontent.com/5439929/89718772-0deb4400-d998-11ea-9e05-5ada5bd07598.gif)



```js
import React, {useEffect, useRef} from 'react';
import {Animated} from 'react-native';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';

import {mapStyle} from './style.js';

export const Map = (props) => {
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 300,
      delay: 200,
      useNativeDriver: true,
    }).start();
  }, [fadeAnim]);

  return (
    <Animated.View
      style={{flex: 1, backgroundColor: '#000', opacity: fadeAnim}}>
      <MapView
        provider={PROVIDER_GOOGLE}
        style={{flex: 1}}
        customMapStyle={mapStyle}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
    </Animated.View>
  );
};

```

**Comment by juergengunz** [comment]
any workarounds?

**Comment by jamesholcomb** [comment]
I think the issue stems from the default background color (off-white) of the tile in Google Maps.

https://stackoverflow.com/questions/44472433/how-to-set-google-map-loading-tiles-color

The initial render shows all tiles with the default background color.  When panning/zooming to regions where the tile has not been loaded, it's the same effect.  But how do you change this?

**Comment by RobTS** [comment]
Had this problem since mid last year when implementing dark mode and had hoped that if some time passed, there would be a solution available. But this seems not the case here, maybe the maintainers could at least point us to whether this is an issue of the Google Maps Android SDK in general or a background set in the library, so we could simply fix the issue and submit a PR?

**Comment by zholmes1** [comment]
Was anyone ever able to find a fix for this? I don't think this issue should be closed as it's a UX detractor with no clear solution/workaround.

**Comment by zholmes1** [comment]
Here's a decent solution. Some pseudocode below

```
const [loaded, setLoaded] = useState(false)

return (
  <View style={{height: 250, position: 'relative'}}>
    <MapView style={{...StyleSheet.absoluteFillObject}} onMapLoaded={() => setLoaded(true)} />
    {!loaded && (
      <View style={{...StyleSheet.absoluteFillObject, justifyContent: 'center', alignItems: 'center', backgroundColor: 'black'>
        <ActivityIndicator/>
      </View>
    )}
  </View>
)
```

The idea is to cover the map up with a loading area until the `onMapLoaded` callback is fired. It appears like this is after the custom theme is successfully loaded.

**Comment by princefishthrower** [comment]
@alexandrepalagem - I think your example should be starting at `1`, i.e. `const fadeAnim = useRef(new Animated.Value(1)).current;`, and then you want to go to `0` since it's for opacity right? Anyway, here's my TypeScript component version that's working, kind of a blend of @alexandrepalagem and @zholmes1 - I couldn't use the solution by @alexandrepalagem because `MapView` was complaining it had a size of 0...

```tsx
import React, {useEffect, useRef} from 'react';
import {Animated, StyleSheet} from 'react-native';

interface IFadeInOverlayProps {
  reveal: boolean;
}

export default function FadeInOverlay(props: IFadeInOverlayProps) {
  const {reveal} = props;
  const fadeAnim = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    if (reveal) {
      Animated.timing(fadeAnim, {
        toValue: 0,
        duration: 300,
        delay: 200,
        useNativeDriver: true,
      }).start();
    }
  }, [reveal]);

  return (
    <Animated.View
      style={{
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black',
        opacity: fadeAnim,
      }}></Animated.View>
  );
}
```

and usage:

```tsx
 const [mapReady, setMapReady] = useState(false);

...

return (
<View testID={TestIDConstants.MAP_SCREEN_VIEW} style={styles.container}>
        <MapView
          onMapReady={() => setMapReady(true)} ...otherpropshere
        </MapView>
        <FadeInOverlay reveal={mapReady} />
</View>
)
```

just make sure for this type of solution that MapView also has absolute positioning and the `<View>` wrapper has relative positioning.

Smooth as 🧈

**Comment by MarcHbb** [comment]
> 

Nice and smooth animation, it's working perfectly, I have no flickering issue while the map is loading. 
But the overlay is over the map, event though it has opacity value of 0. So I can't interact with the map.

I added few lines to fix it. 

In overlay comp : 

`    const [hideOverlay, setHideOverlay] = useState(false);
`

Use callback after animation to set the state

`.start(() => {
                setHideOverlay(true);
            });
        }
    }, [reveal]);
    `
    
    <Animated.View
            style={{
                ...StyleSheet.absoluteFillObject,
                justifyContent: "center",
                alignItems: "center",
                backgroundColor: theme.base,
                opacity: fadeAnim,
                display: hideOverlay ? "none" : "flex",
            }}
        >
        .
        .
        .

**Comment by MarcHbb** [comment]
@jamesholcomb You can"t have tiles still loading because the fade animation trigger when `onMapReady` is true so no matter what the `duration` you have set, you should not have flashes

**Comment by hansemannn** [comment]
Please excuse if it's an unpopular opinion, but let's face it: Google has to provide a proper fix here to prevent the default map to flash before the custom style is loaded. Every workaround has it pro's and con's (performance vs stability), so it's really up to Google to fix that behavior.

**Comment by majirosstefan** [comment]
@MarcHbb onMapReady is fired before tiles are loaded

**Comment by PedroBern** [comment]
The fade in animation solves the initial loading, but you still get white flashes when programmatically setting the region.

> Google has to provide a proper fix here to prevent the default map to flash before the custom style is loaded

👆

**Comment by jocoders** [comment]
Guys I have the same problem. Any workaround solution?

**Comment by jamesholcomb** [comment]
Even this very popular and mature app that has been downloaded _billions_ of times flashes

https://user-images.githubusercontent.com/362729/200075835-9de396c9-1070-4fce-b835-d3c115f90791.mp4

**Comment by jamesholcomb** [comment]
Sorry for the chatter, but i was pleasantly surprised to see that the white tile flashes during load and also during pan/zoom is fixed in Google Maps for Android 11.60.0703.  Maybe there is hope for us yet.

**Comment by pfcodes** [comment]
This issue should not be closed

**Comment by MariuzM** [comment]
@pfcodes if this is coming from Official Google Maps SDK nothing much but a workaround needs to be done here. 
Above suggestions solves this

**Comment by ThisisDC** [comment]
Do you have any update about it? Trying to build an app and I'm forced to switch to KT for Android for just this annoying glitch.

**Comment by ryskin** [comment]
Problem still exist

**Comment by vestaxpdx** [comment]
Just experiencing this issue too.

**Comment by kkx64** [comment]
Still flashing

**Comment by finnholland** [comment]
here's what i did to solve it for me a bit temporarily at least
```
  const offsetStyle: ViewStyle = {
    position: 'absolute',
    left: -1000,
  };
```
```
<MapView
  style={[{ width: '100%', height: '100%' }, !mapLoaded ? offsetStyle : undefined]}
  ...
  onMapLoaded={() => setMapLoaded(true)}/>
```
just note that if you toggle between the map and the other screen remember to set loaded back to false!
