### ISSUE TITLE
Overlay image disappears when Zoomed in iOS 

### ISSUE THREAD

**Issue by m-tbox** [react-native-maps/react-native-maps#3417]
**Installation**
I am not using pods and have installed the library manually 

**Environment**
```
react-native: 0.59.9
react: 16.8.3
react-native-maps: 0.25.0
```

**Question**
When I zoom in on iOS the Overlay image disappears, it should be visible all the time and not be effected by zoom. Please guide me how can I fix this issue.

**Comment by aravi365** [comment]
Facing the same issue like overlay image flickers when zooming in or out in iOS. Any workaround or fixes?
