### ISSUE TITLE
Default red pins appear when using ‘icon’ prop

### ISSUE THREAD

**Issue by TruffleClock** [react-native-maps/react-native-maps#3418]
# Bug

When setting the `icon` prop of Marker to a PNG on a MapView with `provider={PROVIDER_GOOGLE}` on iOS, the red default pins flicker for a moment before the icon appears.

## Environment info

react: 16.11.0
react-native: 0.62.2
react-native-maps: 0.27.1

Platform: iPhone 11 Pro, iOS 13.4

## Steps To Reproduce

1. Set icon prop
2. Run on iOS
3. See flicker

**Comment by ostaron** [comment]
FWIW, I also noticed this, but using the `image` instead prop worked for me.

**Comment by StebanDev** [comment]
any update on this?

**Comment by valeriik** [comment]
The same + video example - https://github.com/react-native-maps/react-native-maps/issues/3657

**Comment by tharakanwn2014** [comment]
> mage

Using an image is using like 4x more CPU than using icon
