### ISSUE TITLE
Circle and Polygon containsLocation

### ISSUE THREAD

**Issue by strdr4605** [react-native-maps/react-native-maps#3420]
# Feature Request

Would be nice to have a helper function similar to web:

```js
google.maps.geometry.poly.containsLocation(
                    location,
                    new google.maps.Polygon({ paths: [{latitude, longitude}, ...],
                );
            }

new google.maps.Circle({
                    center: {latitude, longitude},
                    radius,
                })
                    .getBounds()
                    .contains({ lat: location.lat(), lng: location.lng() });
```

## Why it is needed

To show only a polygon or circle that contains location, or to change Marker icon if it is a specific polygon.

## Possible implementation

I don't know yet, but it can be discussed in this issue.

### Code sample

I don't see a clear API. Should be discussed

**Comment by abhayciitizen** [comment]
Any update on this?

**Comment by strdr4605** [comment]
> Any update on this?

It's closed, so probably no updates. Maybe create another issue, or make a PR 😅
