### ISSUE TITLE
Change circle radius - method?

### ISSUE THREAD

**Issue by krisidmisso** [react-native-maps/react-native-maps#3422]
# Question

Is there any method to change the radius of a Circle (by reference)?

**Comment by richardbumm** [comment]
radius is a property, so you can change it via any method you create.  I use state to manage the radius:
radius={this.state.radiusInMeters}

**Comment by krisidmisso** [comment]
> radius is a property, so you can change it via any method you create. I use state to manage the radius:
> radius={this.state.radiusInMeters}

The issue is that i have a list/array of circles that are loaded dynamically inside the map. they already have the radius, i want to be able to change the radius via a method using the reference. 

i.e.: `this.circleRef.setRadius(200)` _<- this is a method available on web api i think but its not working on react-native in this library_

**Comment by richardbumm** [comment]
We're talking about different circles then. I assumed from your title you meant the singleton circle for the user.

**Comment by krisidmisso** [comment]
@richardbumm I think we are talking about the same: https://github.com/react-native-community/react-native-maps/blob/master/docs/circle.md.

What I want to do is change the radius property of a circle already present on the map(without deleting and recreating it).
Im guessing there isn't any method to do that but it could be useful to have it in the future. (Also changing the radius with animation could be cool)
