### ISSUE TITLE
Can this be used in a function component?

### ISSUE THREAD

**Issue by peterzernia** [react-native-maps/react-native-maps#3425]
# Question

I'm trying to use this within a function component, using the react useState hook, but it's causing poor behaviour when scrolling the map

```
function Map () {
  const [region, setRegion] = React.useState({
        latitude:  52.520008,
        longitude: 13.404954,
        latitudeDelta: 0.01,
        longitudeDelta: 0.1,
  })

  return (
        <MapView
          region={region}
          style={styles.map}
          onRegionChange={setRegion}
          rotateEnabled={false}
          scrollEnabled
          zoomEnabled
      >
  )
}
```

It seems like the onRegionChange isn't setting the region into the state quick enough, so the map scrolls and then gets jerked back. Is there anyway to make this useable with hooks or should I use a react component?

**Comment by rborn** [comment]
Please udpate your issue following the template or I'll delete it. You already put a lot of effort in giving details :)

**Comment by peterzernia** [comment]
Like this ☝️ ? 😬

**Comment by rborn** [comment]
`onRegionChange` triggers A LOT and crossing the bridge is costly, maybe you can use `onRegionChangeComplete`?

**Comment by peterzernia** [comment]
I'm rendering a Circle around the region of the MapView, and I'd like the circle to move along as the map moves, which means `onRegionChangeComplete` won't work for me 😢 . I should use a React class component or is there a way to get `onRegionChange` to work?

**Comment by rborn** [comment]
You can try, but I don't know :(

**Comment by peterzernia** [comment]
I can't get it to work with a class component either 😭, it ends up too laggy. The best I can do is update the circle location with `onRegionChangeComplete`. It's not the exact behavior I want, but it's usable at least. If anyone has any other ideas let me know!

**Comment by rborn** [comment]
@peterzernia another thing you could try is to limit the number of decimals in the region to 6 (or less?) and  use useMemo to limit the rendering? 
I don't use this module since a long time ago but I remember the change event has a lot of decimals in the coordinates

**Comment by VehpuS** [comment]
Do you need this to be in state? Do you need to pass the region back to the component? Consider using a ref instead and / or let the map save it's internal state and not manage it from outside if this isn't necessary.
