### ISSUE TITLE
AIRMap was not found in UIManager.

### ISSUE THREAD

**Issue by ArjunKarki** [react-native-maps/react-native-maps#3427]
AIRMap was not found in UIManager. 
RN version 0.62.2
react-native-map 0.27.1

**Comment by jdegger** [comment]
Same issue here, did you manage to solve it?

**Comment by jdegger** [comment]
@rborn We understand that the issue template is missing and that's why you closed this issue. However, just letting you know that autolinking seems to be broken. We manually linked it now to solve the issue.

For others encountering this issue, by manually linking and disabling autolinking  you can resolve the problem. If others know how to solve the autolinking problem, let me know.

```diff
From f64ad6d750f6c669d480f90ff7038e0af8f5df34 Mon Sep 17 00:00:00 2001
From: anonymous <example@domain.com>
Date: Mon, 11 May 2020 11:33:51 +0200
Subject: [PATCH] manual link maps

---
 android/app/build.gradle                                     | 2 ++
 .../replace/to/android/folder/MainApplication.java   | 3 +++
 android/settings.gradle                                      | 3 +++
 react-native.config.js                                       | 5 +++++
 4 files changed, 13 insertions(+)

diff --git a/android/app/build.gradle b/android/app/build.gradle
index 0123bbcb0..67e94b11a 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -240,6 +240,8 @@ dependencies {
     debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
         exclude group:'com.facebook.flipper'
     }
+
+    implementation project(':react-native-maps')
     
     if (enableHermes) {
         def hermesPath = "../../node_modules/hermes-engine/android/";
diff --git a/android/replace/to/android/folder/MainApplication.java b/android/replace/to/android/folder/MainApplication.java
index 8e2b5bdf1..d584ea6c5 100644
--- a/android/replace/to/android/folder/MainApplication.java
+++ b/android/replace/to/android/folder/MainApplication.java
@@ -21,6 +21,8 @@ import java.util.List;
 
 import nl.xguard.flic2.Flic2;
 
+import com.airbnb.android.react.maps.MapsPackage;
+
 public class MainApplication extends NavigationApplication {
   public static final String LOG_TAG = "XGMainApplication";
 
@@ -38,6 +40,7 @@ public class MainApplication extends NavigationApplication {
       List<ReactPackage> packages = new PackageList(this).getPackages();
       // Packages that cannot be autolinked yet can be added manually here, for example:
       // packages.add(new MyReactNativePackage());
+      packages.add(new MapsPackage());
       return packages;
     }
 
diff --git a/android/settings.gradle b/android/settings.gradle
index 507a02793..a977ee20b 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -3,4 +3,7 @@ rootProject.name = 'appProject'
 apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
 applyNativeModulesSettingsGradle(settings)
 
+include ':react-native-maps'
+project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android');
+
 include ':app'
\ No newline at end of file
diff --git a/react-native.config.js b/react-native.config.js
index 0712287cc..75c8b8b3d 100644
--- a/react-native.config.js
+++ b/react-native.config.js
@@ -6,5 +6,10 @@ module.exports = {
           ios: null, // disable iOS
       },
     },
+    'react-native-maps': {
+      platforms: {
+        android: null, // disable Android platform, other platforms will still autolink if provided
+      },
+    },
   },
 };
\ No newline at end of file
-- 
2.24.2 (Apple Git-127)
```

**Comment by jdegger** [comment]
@rborn Missing info in template:

# Bug report

## Summary
React Native Maps is not auto-linking correctly on Android. You get the following error in RN:

`AIRMap was not found in UIManager.`

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.03 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.1 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.2, 28.0.3, 29.0.0, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.8.0 => 4.8.0
    react: ^16.12.0 => 16.12.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.25.0

## Steps to reproduce

1. Use version 0.25.0
2. Use react native 0.62.2
3. Not linking

Describe what you expected to happen:

1. correctly auto-linking

**Comment by rborn** [comment]
@jdegger  It looks like @ArjunKarki uses 0.27.1 ?

**Comment by jdegger** [comment]
We will try to update to the newest version, this PR (https://github.com/react-native-community/react-native-maps/pull/3103/files) might solve our issue. However that does not explain the issue encoutnered by @ArjunKarki.

**Comment by rborn** [comment]
True. There are few ways to try to fix this like gradle clean or upgrade gradle in the project, etc.
Gradle versions are pretty sensitive.

**Comment by jdegger** [comment]
I'm certain that upgrading to the new version will solve our issue. However, as we also use react-native-google-places we are stuck on 0.25.0 for now as this is the latest version which is also compitable with react-native-google places as per this issue: https://github.com/tolu360/react-native-google-places/issues/258

We will use patch-package to solve the issue in their repo and then update.

**Comment by rborn** [comment]
@jdegger there's a PR for that issue it seems: https://github.com/tolu360/react-native-google-places/pull/257

**Comment by jinguohao1991** [comment]
add `provider={PROVIDER_GOOGLE}` in MapView

**Comment by jdegger** [comment]
@jinguohao1991 It's a linking problem, not related to the react configuration.

**Comment by zirmax** [comment]
> ```diff
>     List<ReactPackage> packages = new PackageList(this).getPackages();
>        // Packages that cannot be autolinked yet can be added manually here, for example:
>        // packages.add(new MyReactNativePackage());
> +      packages.add(new MapsPackage());
>        return packages;
> ```

Even with manual linking I still get the same error :/

My code: https://github.com/zirmax/RtkGps

**Comment by markmoomoo** [comment]
@jinguohao1991 after you pod install, don't forget to clean the build folder and rebuild your project, this is truely a linking issue not a bug
