### ISSUE TITLE
Unable to get rid of Marker/MapView onPress delay on Android

### ISSUE THREAD

**Issue by the-habu** [react-native-maps/react-native-maps#3429]
# Bug

I've been working on a product for quite some time now, utilizing this great library as a base for extensive mapping. About 50% of the user interactions in my app will be pressing markers and pressing the map background for marker selection and deselection. I've noticed a marker press delay on both platforms (iOS and Android), but until now I was confident that it is my implemetation slowing it down.

Yesterday night, I checked a whole lot on my application and ended up suspecting a delay in the onPress callback. Then I discovered #833 and all it's related issue tickets in this repository. I don't understand why @alvelig recommendation of opening a new ticket according to the template has never been followed by anyone.

In contrary to what some comments might suggest, it has nothing to do with number of markers or other things that might impact the performance of the map library. All other map interactions are totally snappy.

I gave disabling tap to zoom (`zoomTapEnabled={false}`, which only has an effect on iOS though) a shot and voila, iOS magically got an unbelievable boost, making pressing markers a very pleasent experience.

This issue is quite hard to debug and verify, as testing on the emulator (maybe even in debug mode) is slower by nature. Nonetheless since I can work around iOS by disabling tap zoom, I also suspect that something is waiting to see if a second tap is incoming to determine whether a double tap or a single tap will be applied.

I had no great success in Android yet. I tried for a few more hours to disable the `gestureDetector` in `AirMapView.js` and gestures via `UiSettings` on `map`, which gave me no apparent and obvious improvement as on iOS. 

As my app is pretty much all about marker pressing/selection, I'd rather sacrifice some gesture control which slows it down, than having the obvious delay applied. Personally I don't really see why such a delay is necessary at all (I know, it's not your implementation but still). A double tap that happens to land on a marker might trigger marker press and a double tap to zoom without delaying anything, and it would still be totally fine for user experience. If the user wants no other interaction, he/she can double tap in an empty area to achieve the same without marker interaction.

For my (and many others, as noticable by tickets like #833) use cases, improving onPress timing would vastly improve user experience.

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
    Memory: 18.28 GB / 31.95 GB
  Binaries:
    Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```
Tested on OS: Android 8.1 and 9
Library version: 0.27.1

## Steps To Reproduce

The behaviour is actually also noticeable on the `React Maps Native Example` App [from the Play store](https://play.google.com/store/apps/details?id=com.reactnativemapsexample). It indeed uses an old library version and has not seen an update for a long time, but the behaviour is still the same. Imho it seems also noticeable on GoogleMaps App itself.

1. Run rn maps app on iOS without `zoomTapEnabled={false}` 
2. Put console.log in onPress handler of marker
3. Press marker and watch console log output timing
4. Not add `zoomTapEnabled={false}` to MapView
5. Press marker again and watch improved and instant console log timing

Describe what you expected to happen:

I expect no noticeable delay from pressing an UI element (which a map marker ultimately is for the user). Seeing this interaction timing happen on Google Maps makes me feel negative about finding a fix. But seeing this beeing possible on iOS, makes me feel more positive about it again.

## Reproducible sample code

I'd add one if necessary, but this problem should be apparent on any maps app that supports pressing markers, so I'd spare the time for now. Please maintainers let me know if a sample is necessary for the issue being picked up soon.

**Comment by edi** [comment]
I honestly don't get why you closed such a descriptive issue. The other thread was closed already by a member who doesn't seem to have any understanding of the explained issue.

Now this has been closed without explanation. Seems like the issue can be sorted, at least for Android, since for iOS, there is a workaround.

**Comment by rborn** [comment]
@edi this issue is still opened, and #833 was closed when I closes all the tasks that are very old.

**Comment by edi** [comment]
Oh, you’re right. I was on mobile, and only noticed the closed tag (of the referenced issue).

**Comment by doylemark** [comment]
I also experience this behaviour when not using Google as provider on iOS. The effect seems less noticeable in the simulator compared to the physical device..
