### ISSUE TITLE
Overlay image - wrong position on map

### ISSUE THREAD

**Issue by shukiAnavi** [react-native-maps/react-native-maps#3431]
## Summary
Hello!
I'm trying to display an image over the map.
The image appears but not in the right position.

## Environment info

System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 336.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 0.27.1

## Steps to reproduce

1. Add 'Overlay' component that displays a local image.
2. Set the bounds to [[topLeftCoordinate], [bottomRightCoordinate]] 

Describe what you expected to happen:

The image should appear inside the position of the bounds

## Reproducible sample code

This is the how I set the bounds of the image (topLeft & bottomRight coordinates)
> <MapView.Overlay
                            image={require("app/assets/images/masked.png")}
                            bounds={[
                                [38.2684076484853, -98.9585169076067],
                                [38.2613963515147, -98.9495870923933]
                            ]}
                        />

And here is the result:
![image](https://user-images.githubusercontent.com/10337876/81677586-c10bd600-9459-11ea-9f8c-bed186bd6972.png)

The image appears beneath the bounds. 
The black and white circles on the map are the bounds that I've used in the Overlay component.

>  <MapView.Circle
                            key = { 'circle' }
                            center = { {latitude: 38.2684076484853 , longitude: -98.9585169076067} }
                            radius = { 55 }
                            zIndex = {3}
                            strokeWidth = { 3 }
                            strokeColor = { '#3FA2F7' }
                            fillColor = { 'black' }
                        />
                        <MapView.Circle
                            key = { 'circle' }
                            center = { {latitude: 38.2613963515147 , longitude: -98.9495870923933} }
                            radius = { 55 }
                            zIndex = {3}
                            strokeWidth = { 3 }
                            strokeColor = { '#3FA2F7' }
                            fillColor = { '#fff' }
                        />

What am I doing wrong?

**Comment by rborn** [comment]
Please update your issue following the template, you already put a lot of effort with all the details you added  😊

**Comment by shukiAnavi** [comment]
I can solve it by doing something like that:



> const topLeftLatitude = 38.2684076484853
const bottomRightLatitude = 38.2613963515147
const difference = topLeftLatitude - bottomRightLatitude



><MapView.Overlay
                            image={require("app/assets/images/masked.png")}
                            bounds={[
                                [topLeftLatitude + difference , -98.9585169076067],
                                [bottomRightLatitude + difference, -98.9495870923933],
                            ]}
                        />

But it will be weird :)
