### ISSUE TITLE
iOS urlTemplate highest zoom level not rendering tiles

### ISSUE THREAD

**Issue by maartenvandillen** [react-native-maps/react-native-maps#3434]
# Bug report

## Summary
When using urlTemplate with a custom tile server, the highest zoom level (street level) is not rendering on iOS. It is showing the underlying Apple Maps roads, without the tiles (because the shouldReplaceMapContent prop is set), but not the custom tiles. All other zoom levels are rendering ok. The same code is running fine on Android, including the highest zoom level. The tile server is serving tiles of size 512. I am using tileSize={256 * PixelRatio.get()} in the urlTemplate prop to compensate for retina displays. I have also tried hardcoded values 256 and 512.

## Environment info
```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 74.41 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2
```

Library version: 0.27.1

## Steps to reproduce
```
        <MapView
          ref={this.map}
          style={{ flex: 1 }}
          provider={PROVIDER_DEFAULT}
          mapType={MAP_TYPES.NONE}
          initialRegion={regionNL}
          rotateEnabled={false}
          maxZoomLevel={18}
          minZoomLevel={4}
          onRegionChange={region => {
            let zoom = Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2)
            console.log("Zoomlevel", zoom)
          }}
        >
          <UrlTile
            urlTemplate={"https://url.and.apikey.to.custom.tile.server/{z}/{x}/{y}.png"}
            shouldReplaceMapContent={true}
            maximumZ={18}
            minimumZ={4}
            maxZoomLevel={18}
            minZoomLevel={4}
            tileSize={256 * PixelRatio.get()}
            zIndex={-3}
          />
      ...
      />
```

I have looked at all the existing issues concerning tile size and iOS but haven't found a solution. I have also tried a fork with merged https://github.com/react-native-community/react-native-maps/pull/2694 but that didn't seem to change anything.

Please advise how to proceed.

**Comment by JoniVR** [comment]
Hi @maartenvandillen, Did you manage to fix this?

**Comment by JoniVR** [comment]
I'll update this in case anyone else runs into it. I've discovered that latest versions of `UrlTile` support a `maximumNativeZ` property. Playing around with this combined with `maxZoomLevel` on the map itself allows you to work around it. Apparently, from my reading, osm limits around 18, so I'd recommend that as a `maximumNativeZ`.
