### ISSUE TITLE
Markers looks way more bigger in some phones (android)

### ISSUE THREAD

**Issue by alaminopu** [react-native-maps/react-native-maps#3436]
## Summary
Markers looks way more bigger in some phones Ex. Samsung galaxy S10, Huawei y6. I already tried with 1x, 2x, 3x, 4x pngs but it didn’t help. 

## Environment info

```bash

System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.81 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.27.1

Looks bigger Huawei y6 and Samsung galaxy S10
![Screenshot from Huawei y6](https://user-images.githubusercontent.com/1296554/82211164-b5fcee00-9910-11ea-8d5d-2cc7f6c4619d.jpg)

Describe what you expected to happen:
1. It should looks nice like other android phones. 
![Screenshot from Pixel 3](https://user-images.githubusercontent.com/1296554/82211254-dfb61500-9910-11ea-8f69-4bbefea07670.png)

**Comment by WeZinc** [comment]
same here... in iOS

**Comment by yonureker** [comment]
Are you setting marker sizes relative to device screen width & height?

**Comment by francesco-clementi-92** [comment]
Same problem here. Any news?

**Comment by andraantariksa** [comment]
Same problem here
