### ISSUE TITLE
Navigation compass to a location

### ISSUE THREAD

**Issue by xn3cr0nx** [react-native-maps/react-native-maps#3437]
# Question

Hi, I'm trying to implement a sort of compass pointing to a marker. I'm able to use Animated API to animate a big arrow that should indicate the direction. 
My first approach was basically calculating the angle between user's coordinates and marker's coordinates. But this approach is weak, because it doesn't take into consideration rotation... I sought a lot for something like this, but I think some feature is missing to determine the angle correctly. Could heading be used to find out the rotation? Do somebody have some example for this or which feature is missing?

**Comment by neiker** [comment]
I'm solving a similar issue, this is what I learned so far:

You can listen region change event and get the heading there:
```mapRef.current?.getCamera().then(camera => {
					dispatch({ type: 'SET_HEADING', payload: Math.round(camera.heading) });
				});
```

But this have some problems:
- Region change event is not always triggered. I'm not sure but seems it's only triggered when you pan a little and not just rotate
- Only fires when gesture ends.

**Comment by xn3cr0nx** [comment]
Thank you @neiker, it's a starting. The problems you're highlighting suggest it's not enough to implement a fully functional solution. The pointer should turn based on phone rotation, not just as result of a gesture.

**Comment by ahmedtehseen** [comment]
Hi @xn3cr0nx, did you find any solution to this, I have to implement this kind of compass in my application as well.
Thanks

**Comment by xn3cr0nx** [comment]
@ahmedtehseen nope, working on other features at the moment. I didn't find the correct manner to proceed

**Comment by empireofryan** [comment]
I can't believe this hasn't come up earlier. Seems like an essential feature to have live navigation components for the primary React Native Maps repo.
Closest available solution I could find is this: https://github.com/flyandi/react-native-maps-navigation-example (also referenced here: https://github.com/react-native-community/react-native-maps/issues/3229).
Although with 17 stars and no updates in 2 years, it doesn't give me a great feeling.

Do our users really have to navigate from one point to the next using an overhead view?
