### ISSUE TITLE
Open all callouts at once when zooming in to street level

### ISSUE THREAD

**Issue by aravi365** [react-native-maps/react-native-maps#3441]
# Question 
Please help me to make all the callouts open at once when i zoomed in to a particular level or street level. 

Tried this, but didn't worked. Refer https://github.com/react-native-community/react-native-maps/issues/1041#issuecomment-291469326

**Comment by praveenkumar66** [comment]
@aravi365 Hi Do you able to find the fix for this issue. I am also facing the issue when loading all markers in the map, the callout is displayed only for the last marker in the list.

**Comment by rosnaib11** [comment]
+1

**Comment by MoronovArt** [comment]
+1
