### ISSUE TITLE
Google Maps on not working on iOS with React 0.62.2

### ISSUE THREAD

**Issue by joaom182** [react-native-maps/react-native-maps#3442]
iOS build throws this error on file AirMapCallout.h on line 7:

```
React/RCTView.h' file not found
```

i'm trying to use Google Maps on iOS, and followed the steps to intsall `AirMap` on project to support Google Maps on iOS.

**Comment by slavikdenis** [comment]
@joaom182 Suggest you to change the title to `Google Maps on not working on iOS` rather than the actual one.

**Comment by fooshi69** [comment]
Hi, I have the same problem

**Comment by neXorianus** [comment]
having this issue, too,
but in my case it cannot find `#import "RCTView.h"` in `node_modules/react-native-maps/lib/ios/AirMaps/AIRMapCallout.h`
