### ISSUE TITLE
cat center cooprdinates

### ISSUE THREAD

**Issue by lukasa1993** [react-native-maps/react-native-maps#3443]
```
this.map.animateCamera({
      center: {
        longitude: this.location.coordinates[0],
        latitude:  this.location.coordinates[1],
      },
      zoom:   12,
    });
```

doesn't' center always on top left coordinate…

it doesn't even show on region of map, its lightly top left of map.

this only happens when map is not fullscreen currently i use height:200 for map when this happens

**Comment by lukasa1993** [comment]
`this.map.setCamera`
with same parameters works correctly every times… sets coordinates in center but animation seems buggy…

**Comment by geroale** [comment]
Same issue here

**Comment by OguzEkinci** [comment]
still have the same problem
