### ISSUE TITLE
Can't show full world?

### ISSUE THREAD

**Issue by pROFESOR11** [react-native-maps/react-native-maps#3444]
# Question
Hi all,
I would like to show full word in a view, but the zoom level is restricted between 0 and 20. That will not allow to show world completely in a single view. I read nearly whole documentation, but couldn't find a way to do this. Could you please help me?

Edit: `fitToCoordinates` method doesn't work properly, if all coordinates can't be shown in a single view.

**Comment by Yamini07** [comment]
Any update on this ?

**Comment by Yamini07** [comment]
@pROFESOR11 - Were you able to achieve it ?

**Comment by ronnaf** [comment]
@Yamini07 @pROFESOR11 have you found any solution?
