### ISSUE TITLE
 my application cannot find the key

### ISSUE THREAD

**Issue by josileudo** [react-native-maps/react-native-maps#3446]
I have a problem.
I have already done all the procedures with my api key, but my map does not redisplay the map. How do I fix this?
<img width="297" alt="Captura de Tela 2020-05-25 às 14 14 17" src="https://user-images.githubusercontent.com/48743781/82936129-811e1600-9f64-11ea-8754-08a8ea84600d.png">
Here is my code

> > 
> import React, {Component} from 'react';
> import {View, Text} from 'react-native';
> import mapStyle  from './SRC/Styles/MapStyle' 
> import MapView, {PROVIDER_GOOGLE} from 'react-native-maps'
> 
> 
> export default class App extends Component {
>   render(){
>     return (
>       <View style= {mapStyle.conteiner}>
>         <MapView style={mapStyle.map}
>         loadingEnabled={true}
>         region={{
>         latitude: 37.78825,
>         longitude: -122.4324,
>         latitudeDelta: 0.015,
>         longitudeDelta: 0.0121,
>         }}>
>         </MapView>
>         
>       </View>
>     )
>   }
> }

**Comment by anlramirezs11** [comment]
I have the same problem!!

**Comment by anlramirezs11** [comment]
Hi!! @josileudo, I had the same problem. 

I solved this problem by following the recommendations in issue #3352 and following the section "Generate the API Key to Integration of Google map"  in this article: https://aboutreact.com/react-native-map-example/

I hope It will resolve you problem. :+1:

**Comment by leaderruvuna** [comment]
I am facing the same issue.
