### ISSUE TITLE
Google maps not working on RN 0.62.2

### ISSUE THREAD

**Issue by kenobi91** [react-native-maps/react-native-maps#3447]
# Bug report

## Summary

I m using react maps with RN 0.62.2, i created clean project and installed everything like in Installation guide. After running my app it crashes when i load map i would get black screen and then crash, but this only hapends if i user provider='google' and in my AppDelegate file i see 'GoogleMaps/GoogleMaps.h' file not found and build is failing. I did go through instalation and add:

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

## Environment info

`react-native info` output:

System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 645.02 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```bash
# paste it here
```

Library version: 0.27.1

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

**Comment by policeman16** [comment]
Yep, I have the same issue. How to fix it?

**Comment by policeman16** [comment]
I have the same. Same environment and MapView doesn't show anything. 
```
<Text>aa</Text>
            <MapView
                initialRegion={{
                    latitude: 37.78825,
                    longitude: -122.4324,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                }}
            />
            <Text>aa2</Text>
```
Gives me only screen with 'aaa' and 'aa2' texts. No errors, no warnings

**Comment by suretarget** [comment]
Hi @kenobi91 , I have fresh installed RN 0.62.2 and it's working fine.
Have you added Google API key to AppDelegate.m file?

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
+  [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; // add this line using the api key obtained from Google Console
...
```

**Comment by kenobi91** [comment]
Hi @suretarget yes i did, i found what is issue my pods were not installed ok, once i removed it and restarted project form base line it worked. @policeman16  add style={{ flex: 1 }} to your map

**Comment by policeman16** [comment]
Yes, I found it too yesterday. Thank you very much for your help btw. :)

**Comment by hoanghuy27297** [comment]
> Hi @suretarget yes i did, i found what is issue my pods were not installed ok, once i removed it and restarted project form base line it worked. @policeman16 add style={{ flex: 1 }} to your map

How did you solve it? I'm getting the same problem with RN 0.63.0. Tried to remove Pods and Podfile.lock and reinstalled but still not work
