### ISSUE TITLE
When open map modal app will crash I have upgrade target API level 27 to 28

### ISSUE THREAD

**Issue by virendra702** [react-native-maps/react-native-maps#3451]
![image_2020_05_29T11_41_33_994Z](https://user-images.githubusercontent.com/47003593/83325886-7da0cc80-a28d-11ea-9e5c-78c8cf68141f.png)
![image](https://user-images.githubusercontent.com/47003593/83325963-218a7800-a28e-11ea-9957-58761c3e1711.png)
![image](https://user-images.githubusercontent.com/47003593/83325965-2c450d00-a28e-11ea-83c9-887e4ee32fa7.png)
![image](https://user-images.githubusercontent.com/47003593/83325971-3d8e1980-a28e-11ea-8ddd-44a04aefa41d.png)

react-native : 0.58.1
react: 16.6.3
react-native-maps: 0.26.0

**Comment by christopherdro** [comment]
Do you have a crash report?
