### ISSUE TITLE
Huawei MapKit support

### ISSUE THREAD

**Issue by Kladislav** [react-native-maps/react-native-maps#3461]
# Feature request
Add Huawei MapKit support for Huawei phones.

## Why it is needed
Google Maps has no more working on Huawei phones.

**Comment by filipef101** [comment]
This should be a top priority

**Comment by DaNiELChIoRo** [comment]
Is there any work around? Has anybody overcome this?

**Comment by DaNiELChIoRo** [comment]
Well, actually it seems they are looking for help. So I will try to give it a try in order to satisfy this necessity

**Comment by yasserzubair** [comment]
Hello, Any update on this?

**Comment by DaNiELChIoRo** [comment]
not yet, need to update the Android project because as long as I see. It does not uses gradlew. Which is a blocker for new Android Studio's IDE
