### ISSUE TITLE
Broken link in installation.md

### ISSUE THREAD

**Issue by qualitymanifest** [react-native-maps/react-native-maps#3464]
The link in [this section](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#build-issues-with-google-maps-ios-utils-ios) is broken, and the file that it references (swift.md) doesn't seem to exist anymore

**Comment by fendorio** [comment]
Stumbled across this today. Located the link in the documentation of google maps and have opened a PR with the readme updated with the new link.
