### ISSUE TITLE
Marker onDragEnd causing issues on iOS

### ISSUE THREAD

**Issue by RazaShehryar** [react-native-maps/react-native-maps#3465]
👋 Hi!

I am having an issue with onDragEnd for a single Marker on iOS (On Android it is working fine). I am getting the coordinates from onDragEnd. However, as soon as the event finishes, all other components don't work. I have to tap on the map to make all components work again. I have tested the code for both the platforms on Expo production.

Here's my code:

`<MapView
        provider={PROVIDER_GOOGLE}
        customMapStyle={NightStyle}
        style={styles.mapStyle}
        zoomTapEnabled={false}
        region={location}
        onRegionChangeComplete={(r) => regionComplete(r)}
      >
        <Marker
          coordinate={location}
          onDragEnd={(e) => onDragEnd(e)}
          draggable={true}
        />
      </MapView>`

Library version: 0.26.1

**Comment by azhararmar** [comment]
I am facing the same issue, what is causing this?

**Comment by murilo-campaner** [comment]
Same here...

**Comment by tuchidoghostmaster** [comment]
any luck ??

**Comment by akashdeepsharma1991** [comment]
any update

**Comment by RazaShehryar** [comment]
I have no idea why this issue hasn't been resolved yet. I am still facing the issue.

**Comment by the-habu** [comment]
Still occurs on 0.28.0

**Comment by navarrofracisco** [comment]
Still happening on 0.30
