### ISSUE TITLE
AnimatedMarkers.js example doesn`t work

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [react-native-maps/react-native-maps#3467]
<img width="330" alt="截屏2020-06-19 上午11 22 49" src="https://user-images.githubusercontent.com/46700201/85093763-b514f000-b21f-11ea-9c69-e651af5b70c1.png">

**Comment by ZHEQIUSHUI** [comment]
it is work when i remove 
```
           <Marker.Animated
              ref={marker => {
                this.marker = marker;
              }}
              coordinate={this.state.coordinate}
            /> 
```
i use apple map.

**Comment by cicconewk** [comment]
> it is work when i remove
> 
> ```
>            <Marker.Animated
>               ref={marker => {
>                 this.marker = marker;
>               }}
>               coordinate={this.state.coordinate}
>             /> 
> ```
> 
> i use apple map.

If you're using Marker.Animated you should pass `{ latitude, longitude, latitudeDelta, longitudeDelta }`. It is required because you're might be using AnimatedRegion as coordinates.
