### ISSUE TITLE
React-native-google-maps _ "_OBJC_CLASS_$_AIRGoogleMapHeatmap", referenced from:       objc-class-ref in AIRGoogleMap.o ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [react-native-maps/react-native-maps#3472]
**I am using** 
 "react-native-maps": "0.27.1",
 "react-native": "^0.62.2",

**Error:**
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AIRGoogleMapHeatmap", referenced from:
      objc-class-ref in AIRGoogleMap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**My pod file includes**
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

and I am also using **use_native_modules!** 

I was using  "react-native-maps": "0.25.0" everything was working fine on iOS but not on android, now the lastest version is working on android but not on iOS.

**Comment by MuhammadAhmed1994** [comment]
Just reverted back to the version 0.25.0
and linked the library properly for android and iOS. everything started working now.
for android make sure to link the google maps properly

In mainApplication.java file

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
       packages.add(new RNFirebaseNotificationsPackage());
       **packages.add(new RNFirebaseMessagingPackage());
       packages.add(new MapsPackage()); // <-- Add this line
      // packages.add(new RNPermissionsPackage());
      // Packages that cannot be autolinked yet can be added manually here, for example:
      return packages;
    }

**Comment by williamswebworks** [comment]
I am also experiencing this issue with RN 63.2 and RN Maps 27.1

**Comment by Balasnest** [comment]
Facing same issue in react native 0.63.2 and react-native-maps: 0.26.1 (I took this version bcz it support androidX). It works in ios if I choose `0.25.0` @rborn Need your help here.

**Comment by Balasnest** [comment]
works if we do this: `build Phases -> compile sources - Add AIRGoogleMapHeatmap.m`. If it's not there, directly go to lib inside the AIRGoogleMap folder, then drag and drop it.
