### ISSUE TITLE
Why keep showing unlink error message when running `react-native run-android`

### ISSUE THREAD

**Issue by cxrod** [react-native-maps/react-native-maps#3476]
# Question
Hi,
The library is working fine on Android and iOS with RN 0.62.5 but when I ran `react-native run-android` always appears this error
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-maps (to unlink run: "react-native unlink react-native-maps")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag. 
```

and when I ran `react-native unlink react-native-maps` it finish successfully but nothing happens, none file are changed
```
info iOS module "react-native-maps" is not installed
info Unlinking "react-native-maps" Android dependency
info Android module "react-native-maps" has been successfully unlinked
```

**Comment by allan-simon** [comment]
I think it's important not to close this bug

**Comment by allan-simon** [comment]
bumping it to avoid closing :)

**Comment by allan-simon** [comment]
bump

**Comment by allan-simon** [comment]
that's a pity

**Comment by mjstelly** [comment]
Wow! No love for this issue whatsoever. What's up folks? Lack of resources? I have the same issue for ios. The error clearly states `If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.` So, here we are.

**Comment by udayaprakashjayaraman** [comment]
Im too facing the same in iOS
<img width="1286" alt="Screenshot 2021-11-16 at 8 51 49 AM" src="https://user-images.githubusercontent.com/22929591/141890100-9ebedde6-2c2d-4248-abc6-48db4e5d1c96.png">
 
anyone got it solved?

**Comment by Zhou-Bill** [comment]
how to solve?

**Comment by ggerminiani** [comment]
same problem
