### ISSUE TITLE
fitToElements not accounting the marker size

### ISSUE THREAD

**Issue by hugoassisj** [react-native-maps/react-native-maps#3479]
# Bug report

## Summary

I have a bunch of <Marker> components set on a <MapView> component. Using the prop 'onLayout' I call the method 'fitToElements(true)'. It works as it zooms into the markers, but the marker on the top of the screen Is being chopped.

![actual](https://user-images.githubusercontent.com/45035051/85636989-5a80f700-b658-11ea-84a4-fbfe83fa49eb.png)

## Environment info

react-native: "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz"
react: "~16.9.0",
expo: "~37.0.3",
Target Platform Android (using google maps)

Library version: "^0.26.1",

## Steps to reproduce

1. Create a MapView component
2. Add Marker components vertically ( different Longs)
3. Call 'fitToElements '

Describe what you expected to happen:

![expected](https://user-images.githubusercontent.com/45035051/85634864-e3952f80-b652-11ea-8275-e77824694a46.png)

**Comment by yamifr07** [comment]
something similar happen to me with fitToSuppliedMarkers

**Comment by hugoassisj** [comment]
I saw in the code for the function that it uses a default padding. It would be useful to have this padding as a parameter as it could solve this kind of problem

**Comment by iamir4g** [comment]
please, write an example for **fitToSuppliedMarkers**, how to use it?
