### ISSUE TITLE
fitToSuppliedMarkers zoom level

### ISSUE THREAD

**Issue by yamifr07** [react-native-maps/react-native-maps#3481]
I have a map inside a view with height equals to 156. When I use fitToSuppliedMarkers passing 2 markers for example one in Argentina and the other in Spain, it shows the right region but markers are not visible. How can I fit region to include pins in it?

**Comment by franciscailleAstus** [comment]
I have the same issue.
I know I can use EdgePadding to try fitting the marker, but a "Zoom" option would better fit my case.

![image](https://user-images.githubusercontent.com/44379473/86961164-c4a49c00-c12e-11ea-9763-c8a11de63874.png)
Nothing in the doc also, https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md

**Comment by ahmedam55** [comment]
Is there a way to fit to supplied markers with zoom level?
