### ISSUE TITLE
Maps get stucked

### ISSUE THREAD

**Issue by mahecode** [react-native-maps/react-native-maps#3489]
# Bug report

## Summary

When we enable cacheEnabled prop in mapview component and if we try to search then map get stucked and if i remove the cacheEnabled prop then map works fine.

## Environment info

`react-native info` output:

```bash
# paste it here
 "react": "16.9.0",
 "react-native": "0.61.5",
 "react-native-maps": "0.27.1",

```

`export default class App extends React.Component {`
  `render() {`
   ` return (`
    `  <View style={styles.container}>`
        `<View style={{width: Dimensions.get('window').width, position: 'absolute', top: 0, zIndex: 2, height: 70, backgroundColor: '#fff', borderBottomLeftRadius: 12, borderBottomRightRadius: 12, justifyContent: 'center', alignItems: 'center'}}>`
         ` <TextInput style={{width: 200, height: 40, backgroundColor: '#BFBFBF'}} placeholder="search" />`
      `  </View>`
  `      <MapView `
         ` mapType="satellite"`
        `  cacheEnabled`
         ` style={styles.mapStyle} `
      `  />`
      `</View>`
  `  );`
 ` }`
`}`

**Comment by erennyuksell** [comment]
same issue
