### ISSUE TITLE
App is getting crashed on release mode with animateMarkerToCoordinate

### ISSUE THREAD

**Issue by Sumit2406** [react-native-maps/react-native-maps#3490]
When I use below code and generate release version, my app is getting crash.

```
this.marker._component.animateMarkerToCoordinate(
            newCoordinate,
            duration
          );
```
and when I use

`userCoordinate.timing({newUserCoordinate, duration}).start();`

the marker movement is not smooth, it jumps from one coordinate to another.
I have followed the solution provided in #2195 but the solution did not help in release mode. The error is same as mentioned in #2195 screenshot.

The animation is happening smoothly in debug mode but crashed the app in release mode.

Please provide me solution.

The version we are using
Node version - v10.12.0
NPM - 6.4.1
ReactNative - 0.60.4
react-native-maps - 0.26.1

**Comment by konstantinmv** [comment]
If your marker is passed as a ref (using a useRef hook or React.createRef()), you don't need _component anymore and could just do this.marker.current.animateMarkerToCoordinate(...).

**Comment by islamouzou** [comment]
> If your marker is passed as a ref (using a useRef hook or React.createRef()), you don't need _component anymore and could just do this.marker.current.animateMarkerToCoordinate(...).

Can you show an example how to use this ? i always get an error when i use useRef hook

**Comment by konstantinmv** [comment]
what exactly are you doing @islamouzou, maybe you can show your code and why it crashes?

**Comment by EhsanSarshar** [comment]
@rborn there is a property inside MapMarker.js line 311 which is undefined

```
 _runCommand(name, args) {
    switch (Platform.OS) {
      case 'android':
        NativeModules.UIManager.dispatchViewManagerCommand(
          this._getHandle(),
          this.getUIManagerCommand(name),
          args
        );
        break;

      case 'ios':
      // this property is undefined
        this.getMapManagerCommand(name)(this._getHandle(), ...args);
        break;

      default:
        break;
    }
  }
```

would you mind to fix it @rborn
