### ISSUE TITLE
How to draw the curve polyline for given coordinates

### ISSUE THREAD

**Issue by renishdeveloper** [react-native-maps/react-native-maps#3497]
How to draw the curve polyline for given coordinates ?

![image](https://user-images.githubusercontent.com/40269099/87004718-831dfa80-c1db-11ea-89a6-644efbe8416e.png)

Here is my output of polylline, I want curve line that joins to every coordinates.

Here, are the coordinates, I'm using to draw the Polyline.
21.189079, 72.789719
21.190639, 72.788689
21.193490, 72.787005
21.198341, 72.783808
21.197791, 72.780739
21.197841, 72.779012
21.200952, 72.778529
21.203482, 72.776083
21.204243, 72.775514
21.207833, 72.776641

Thanks in advance.!

**Comment by luisgurmendez** [comment]
@renishdeveloper did you find a way to accomplish this?
