### ISSUE TITLE
For android, accessibility properties on <Marker /> and <Callout /> are ignored by screen reader

### ISSUE THREAD

**Issue by ui-ninja** [react-native-maps/react-native-maps#3500]
# Bug report

## Summary

In **Android device** when screen reader is turned "ON", the accessibility properties on `<Marker />` are ignored by screen reader and nothing is announced when user taps on a marker. 
Also, the `<Callout />` is not accessible. I am unable to tap and access `<Callout />` descendants. Instead the focus automatically goes to parent `<MapView />`

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 47.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.20.1 - ~/projects/*/mobileapp/react-native/node_modules/.bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
```

Library version: 0.60.6

## Steps to reproduce

```
<MapView
  region={this.state.region}
  onRegionChange={this.onRegionChange}
>
  {this.state.markers.map(marker => (
    <Marker
      coordinate={marker.latlng}
      title={marker.title}
      description={marker.description}
      accessible
      accessibilityLabel={`Some useful label`}
    >
      <MyCustomMarkerView {...marker} />
     <Callout accessible>
        <MyCustomCalloutView {...marker} {...accessibleProps} />
     </Callout>
   </Marker />
  ))}
</MapView>
```
1. Turn on screen reader (Talkback).
2. Navigate to screen where `<MapView />` is shown.
3. Now, with talkback on, try to tap on custom `<Marker />` shown and notice if screen reader announce it. **Nothing is announced, accessibility props are ignored by screen reader.**
4. Double tap on `<Marker />`, it displays `<Callout />`, try to tap on it. **Unable to tap on `<Callout />`, focus shift to parent `<MapView />` component**

Describe what you expected to happen:

1. Screen reader should readout the accessibility labels passed.

**Comment by kevinrodriguez-io** [comment]
Why was it closed? This is something important, not because it is `accessibility` it should be closed.

This demonstrates why this kind of bot is a bad idea, minorities are ignored by this kind of behavior.

**Comment by kevinrodriguez-io** [comment]
A blind person couldn't even know what's on the screen because markers are just not read. They will just know there's a map and that's all, that's not accessible at all.

**Comment by ganeelz** [comment]
This issue is still happening.
Anyone have any solutions?
This is the Map.Working Fine in iOS.
In Android, it doesn't announce anything on selecting the marker.

  <MapView
        accessible={true}
        ref={this.map}
        initialRegion={region}
        style={styles.map}
        showsMyLocationButton={false}
        showsCompass={false}
        showsScale={false}
        showsUserLocation={isLocationGranted}
        onPanDrag={this.setMapDragging}
        onRegionChangeComplete={this.onRegionChange}>
        <MapView.Marker
          accessible={true}
          accessibilityLabel={marker.store_name}
          coordinate={{
            latitude: marker?.latitude,
            longitude: marker?.longitude,
          }}
          onPress={(e) => !isListView && this.onMarkerPress(e)}>
          <View style={styles.markerWrap} accessible={false}>
            <Animated.Image
              accessible={true}
              source={screenImages.images.markers}
              style={[styles.marker, scaleStyle]}
              resizeMode="contain"
            />
          </View>
        </MapView.Marker>
      </MapView>

**Comment by ganeelz** [comment]
This issue is still happening.
Anyone have any solutions?
This is the Map.Working Fine in iOS.
In Android, it doesn't announce anything on selecting the marker.

        <MapView
        accessible={true}
        ref={this.map}
        initialRegion={region}
        style={styles.map}
        showsMyLocationButton={false}
        showsCompass={false}
        showsScale={false}
        showsUserLocation={isLocationGranted}
        onPanDrag={this.setMapDragging}
        onRegionChangeComplete={this.onRegionChange}>
        <MapView.Marker
          accessible={true}
          accessibilityLabel={marker.store_name}
          coordinate={{
            latitude: marker?.latitude,
            longitude: marker?.longitude,
          }}
          onPress={(e) => this.onMarkerPress(e)}>
          <View style={styles.markerWrap} accessible={false}>
            <Animated.Image
              accessible={true}
              source={screenImages.images.markers}
              style={[styles.marker, scaleStyle]}
              resizeMode="contain"
            />
          </View>
        </MapView.Marker>
        </MapView>

**Comment by nschild** [comment]
bump

**Comment by nschild** [comment]
I stumbled across this
https://stackoverflow.com/questions/18990030/how-to-add-contentdesctiption-to-infowindow-or-marker-in-android-googlemaps-v2-f

Android, at least, works when setting the title or description prop to whatever you want the screen reader to say.

**Comment by xtendch** [comment]
Thank you @nschild for this hint! Adding title prop to the marker helped.
What your doing regarding accessibility of the Callout? We couldn't find any solution for making it accessible to TalkBack on Android and pressable. This is really a must in today's world to have accessible components!
(I've tried putting the custom callout inside a pressable, but nothing helped.) Any ideas?
