### ISSUE TITLE
Map markers not announcing accessibility label when tapped

### ISSUE THREAD

**Issue by andrewTaylor2** [react-native-maps/react-native-maps#3507]
# Question

When using VoiceOver on iOS, tapping on a map marker has no effect.

```
<Marker {...props} accessibilityLabel="Gym name: Crossfit ..." >
```
Is there something I am doing wrong, or it is not supported in library?

**Comment by andrewTaylor2** [comment]
Any update ??

**Comment by trungledangAxonActive** [comment]
I cannot even tap on the Marker when the Voice Over is on. It happens on the iPhone XR, IOS version: 17.6.1, for other iPhone devices, it's working
