### ISSUE TITLE
[Android] Marker onPress not fired

### ISSUE THREAD

**Issue by dangkhoa2708** [react-native-maps/react-native-maps#3509]
I'm experience the issue only on Android. I tried some solutions but none working. I put a log inside onPress function at react-native-maps/lib/components/MapMarker.js. It doesn't fire anything. Any idea what problem guys ?

react-native: 0.61.5
react-native-maps: 0.27.0
Emulator: Pixel XL API R

<img width="453" alt="Screen Shot 2020-07-22 at 00 33 41" src="https://user-images.githubusercontent.com/20517762/88087598-5abad680-cbb3-11ea-97cd-d64b0bf53d19.png">

**Comment by daltonmenezes** [comment]
Same here, MapView -> onPress and onMarkerPress not working on emulator by clicking, but on real device works. Seems the emulator or this lib are not recognizing the click as a tap.

**Comment by daltonmenezes** [comment]
Ok, I tried to use another AVD and it works.

Success case: **Nexus 5X API 29**
Failure case: **Pixel 2 API 30**

**Comment by andrewTaylor2** [comment]
@daltonmenezes is `onAccessibilityTap` working for you?

**Comment by aman-technyx** [comment]
also happening with me !! any solution found ?
