### ISSUE TITLE
Feature Request: Street View Coverage Layer

### ISSUE THREAD

**Issue by MichaelTaylor3D** [react-native-maps/react-native-maps#3510]
# Feature request

The javascript api for google maps allows you to view the street view coverage on the map with the following code:
```
var streetViewLayer = new google.maps.StreetViewCoverageLayer();
streetViewLayer.setMap(map);
```
It views the street view coverage as such
![image](https://user-images.githubusercontent.com/5665004/88096270-616e2d00-cb64-11ea-8541-97f4be5e74dc.png)

## Why it is needed

Would add more value to the module

## Possible implementation

I'm not sure if the Android and IOS apis support this, but if they do this would be really great to add. Possible Implementation may be a simple `showStreetviewCoverage` prop.

**Comment by MichaelTaylor3D** [comment]
any feedback?

**Comment by BrodaNoel** [comment]
Does anyone here found an alternative for this?
