### ISSUE TITLE
similar to panTo method in react native

### ISSUE THREAD

**Issue by js08** [react-native-maps/react-native-maps#3511]
# Question

Hi,

I am trying to implement a search functionality similar to the below video. I got it working on my web using this package @react-google-maps/api, it provides panTo method, using which we can search the cities easily, by moving map to that location.

Does react-native-maps also provide similar functionality, since I need to do search functionality in my mobile too

https://www.youtube.com/watch?v=WZcxJGmLbSo

**Comment by selven** [comment]
```map.animateCamera({
            center: {
              latitude,
              longitude,
            },
            zoom: 14,
          });```

**Comment by js08** [comment]
@selven hey do you have any sample prototype
