### ISSUE TITLE
Android: OnRegionChangeComplete occurs multiple times

### ISSUE THREAD

**Issue by ddave09** [react-native-maps/react-native-maps#3523]
## Summary

```
<MapView
    style={styles.map}
    region={this.state.region}
    onRegionChangeComplete={this.onRegionChange}
    showsUserLocation={true}
>
```
`this.onRegionChange` event occurs multiple times at once. This only happens on Android, iOS triggers the event only once.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 25.05 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 24.0.2, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 28.0.3, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom_64, android-26 | Android TV Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-P | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.27.1

## Steps to reproduce

1. Assign `onRegionChangeComplete` event with MapView as shown above
2. print region when event is called
3. Notice that even though region has not changed event is called multiple times.
4. Also notice that each following region change will trigger the even multiple times again.

Describe what you expected to happen:

`onRegionChangeComplete` event should be called only once when region changes. This behavior is intact on iOS but on Android, it's not.

## Reproducible sample code

```
<MapView
    style={styles.map}
    region={this.state.region}
    onRegionChangeComplete={this.onRegionChange}
    showsUserLocation={true}
>
```

```
onRegionChange = (region) => {
    console.log(region)
}
```

**Comment by christopher-18** [comment]
@ddave09 Did you got any workaround?

**Comment by ddave09** [comment]
@christopher-18 I have followed below steps:

1.) No op on defined actions that ends up with `onRegionChangeComplete` using a flag when you wish not to take any actions.
2.) Take actions in `onRegionChangeComplete` only when `region` change threshold is met with `toFixed` function. I have noticed that when flood of calls occur, usually the region changes are negligible.

Unfortunately, I haven't found a way to stop the calls to `onRegionChangeComplete`. I hope this helps.

**Comment by christopher-18** [comment]
@ddave09 Can you look into this https://github.com/react-native-community/react-native-maps/issues/3545, suggest some workaround?

**Comment by hugoh59** [comment]
This issue is happening to a lot of people and no one is taking actions to fix it, it' been going on for over 5 years that I've used this library.

**Comment by KrifaYounes** [comment]
This issue is happening happening also on iOS.
There is a way to have a method onPressIn and onPressOut the map ? 
also when we use method animateToRegion , OnRegionChangeComplete is called twice.

**Comment by spideyinf** [comment]
Yeah  `onRegionChangeComplete` has been called many times during the pan

**Comment by adnanirfan** [comment]
`onRegionChangeComplete` provides `isGesture` in second parameter of a callback, to identify if the move was from the **user** or an **animation**. 

https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#events

**Comment by KrifaYounes** [comment]
> `onRegionChangeComplete` provides `isGesture` in second parameter of a callback, to identify if the move was from the **user** or an **animation**.
> 
> https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#events

IsGesture is only availabble on android

**Comment by adnanirfan** [comment]
@KrifaYounes it works in both Android and iOS. But this is mentioned in the docs that `isGesture` is supported by **Google Maps** only.

**Comment by KrifaYounes** [comment]
> @KrifaYounes it works in both Android and iOS. But this is mentioned in the docs that `isGesture` is supported by **Google Maps** only.

In ios I get : isgesture:undefined
