### ISSUE TITLE
Change marker image size dynamically

### ISSUE THREAD

**Issue by dardinier** [react-native-maps/react-native-maps#3539]
# Bug report

## Summary

I have a custom image as marker pin. I also have a zoom mode feature in my app. I would like to have bigger markers when zoom mode is enabled.

## Environment info

`react-native info` output:

```bash
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 5.53 GB / 23.54 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 20200802.200524.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: `0.27.1`

## Steps to reproduce

1. Create a map with custom image marker and precise a size for this image.
2. Change dynamically the size of the marker image.

### Expectation :

The image size is `50:50` :

![image](https://user-images.githubusercontent.com/24563898/91544954-be59c180-e920-11ea-879e-fa39a50739cd.png)

When i toggle the zoom mode, the image is `100:100` and centered :

![image](https://user-images.githubusercontent.com/24563898/91545093-eba66f80-e920-11ea-9570-ffb6543491b9.png)

### Reality :

The image size is `50:50` :

![image](https://user-images.githubusercontent.com/24563898/91544954-be59c180-e920-11ea-879e-fa39a50739cd.png)

When i toggle the zoom mode, the image is `100:100` but contained in a `50:50` block :

![image](https://user-images.githubusercontent.com/24563898/91545158-04168a00-e921-11ea-90f3-a03eb60a996f.png)

## Reproducible sample code

You can see the code here :

https://snack.expo.io/@alexis.ouvrages/marker-image-dynamic-size

**Comment by ehynds** [comment]
I achieved this by forcing the marker to re-render via `key` when the size dynamically changes.

```js
const size = zoomLevel <= 10 ? 40 : 80;

<Marker
  key={size}
  ...
/>
```
