### ISSUE TITLE
Add AnimatedMapView type (and rename it)

### ISSUE THREAD

**Issue by mrousavy** [react-native-maps/react-native-maps#3541]
# Bug report

## Summary

The types (`index.d.ts`) currently don't have a type definition for the `Animated` export (which is a MapView with Animated API support, exported in [index.js#L24](https://github.com/react-native-community/react-native-maps/blob/master/index.js#L24)). It currently exports the [MapViewAnimated](https://github.com/react-native-community/react-native-maps/blob/master/index.d.ts#L300) class, which doesn't exist and throws an error while trying to render.

## Solution 1

1. Rename the `Animated` export to `AnimatedMapView` (or `MapViewAnimated`) - source: [MapView.js#L1058](https://github.com/react-native-community/react-native-maps/blob/master/lib/components/MapView.js#L1058)
2. Export the `AnimatedMapView`/`MapViewAnimated` type in `index.d.ts`

## Solution 2

Don't export the `AnimatedMapView` at all. Instead, tell users to create their animated component themselves:

```js
const AnimatedMapView = Animated.createAnimatedComponent(MapView);
```

## Why

It is a _really_ bad idea to name something `Animated`. I mean how does that look? 

```jsx
<Animated ...>
```

Who reads this and knows that this renders a Map?

**Comment by bluntbrain** [comment]
@mrousavy thanks for the suggestion. This may reflect in upcoming releases :)
