### ISSUE TITLE
Changed provider and UrlTile but "App won't run without Google Play services"

### ISSUE THREAD

**Issue by nbastoWM** [react-native-maps/react-native-maps#3542]
# Question

I'm trying to get this to work on a Huawei phone.
I changed provider to {null} and set UrlTile to urlTemplate={'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png'} but even then the map won't show and presents this error:

```App won't run without Google Play services, which are not supported by your device```

Does this package needs google play services even with a custom Tile Overlay?

**Comment by melvinchng** [comment]
I am in the same boat.

Apparently, Huawei created a port on this. You may want to checkout [their repository](https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-map) as I came across this [Medium](https://medium.com/huawei-developers/hms-map-kit-react-native-f7213ad697e2) article on how to have maps working on react-native with HMS.  However, the package is having [issue](https://github.com/HMS-Core/hms-react-native-plugin/issues/14) with vue native and I am unable to verify if it is working.

**Comment by interhub** [comment]
The problem is actual, still no solution, help please
