### ISSUE TITLE
Location not getting updated after fetching data in an API

### ISSUE THREAD

**Issue by Manfrin92** [react-native-maps/react-native-maps#3543]
# Bug report

## Summary

I'm using this library to show a location received by an API. When the page is rendered it should show the map using it. I tried to start the map using a static location because using a null value throws an error, however even before the fetching is completed (which I tested printing the received information) the map does not get updated with the new latitude and longitude. 

In order to wait for the fetch I created a loading state, after the fetch it is set to false and the map should show the correct location.

I created a repository to show the problem. The static location is in the US and before the fetch it should render someplace in Brazil, but that never happens. The API is just a test to show the problem. In this repository that I created it is necessary to add the google map api key in two different places in order to be able to run the code.

Example repository with the problem: 

https://github.com/Manfrin92/ExampleRepository

Folders that need the api key to run the project:

android/app/src/main/AndroidManifest.xml 
android/app/src/main/res/values/strings.xml

## Environment info

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 6.24 GB / 15.63 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

This problem also occurred in Windows.

Library version: 0.27.1

## Steps to reproduce

clone the repo
put the api key in those two folders
react-native start
react-native run-android

Describe what you expected to happen:

I expect the map to render some place different from the previous state. The map should show a place in Brazil.

**Comment by christopherdro** [comment]
You’re missing the region prop on Mapview. You are only using initial region

**Comment by abhatia-lix** [comment]
You can use mapRef and use one of the api functions provided by MapRef. User animateToRegion or setCamera:
https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#methods
