### ISSUE TITLE
on max zoom, marker is moving slowly

### ISSUE THREAD

**Issue by christopher-18** [react-native-maps/react-native-maps#3545]
I wanted to drag my map around the marker, so I created one fake marker at the centre. Now when I am doing the max zoom, in my android device, the marker is drifting slowly. 

```
<MapView
        provider={PROVIDER_GOOGLE}
        style={{ height: mapHeight }}
        region={this.state.region}
        ref={_map}
        zoomEnabled={true}
        minZoomLevel={9}
        onRegionChangeComplete={(region) => _onRegionChangeComplete(region)}>

 _onRegionChangeComplete (region) {
   this.setState({
     region: region,
    latitude: region.latitude,
    longitude: region.longitude
    })
    console.log(region.latitude, region.longitude);
  };
```

My _onRegionChangeComplete function is getting called infinitely after achieving max zoom in android. It is working fine in iOS. Help required.

**Comment by ddave09** [comment]
@christopher-18 

Only take actions in `_onRegionChangeComplete` if region change threshold is met.

Something like below:

do `this.setState` in `_onRegionChangeComplete` only if below condition is met. Or simply return when reverse of the below condition is met.

```
if (this.state.region.latitude.toFixed(<threshold_number>) !== region.latitude.toFixed(<threshold_number>)
        || this.state.region.longitude.toFixed(<threshold_number>) !== region.longitude.toFixed(<threshold_number>))
```

Include latitude/longitude deltas in the condition above as you mentioned about the zoom level in #3523
