### ISSUE TITLE
Marker.Animated is lagging too much on IOS

### ISSUE THREAD

**Issue by TheEhsanSarshar** [react-native-maps/react-native-maps#3553]
I have a car marker animating on map.
it have bearing and position animation.
everything work fine in Android but as IOS it's too lagging when starting the animation.

There are the codes for animating the marker
```

if (Platform.OS === 'android') {
        marker?.current?.animateMarkerToCoordinate?.(
          {
            latitude: 38.3368456,
            longitude: -122.0299002,
            latitudeDelta: 0.0043,
            longitudeDelta: 0.0041,
            ...(props.origin || []),
          },
          10000,
        )
      } else {
        markerOrigin?.current?.region
          ?.timing({
            latitude: 38.3368456,
            longitude: -122.0299002,
            latitudeDelta: 0.0043,
            longitudeDelta: 0.0041,
            ...(props.origin || []),
            duration: 10000,
          })
          .start()
      }

// Bearing Animation

    const rotation = new Animated.Value(0)
    const bearingDegree =
      rotation.interpolate({
        inputRange: [0, 360],
        outputRange: ['0deg', '360deg'],
      }),

Animated.timing(rotation, {
          toValue: props.bearing,
          useNativeDriver: true,
          duration: 10000,
        }).start()
```

This is the car marker

```
<Marker.Animated
        coordinate={markerOrigin.current.region}
        ref={marker}
        tracksViewChanges={track}
        flat
        anchor={anchor}
      >
        <AnimatedImage
          source={require('../../assets/images/motor-map.png')}
          style={allStyles}
          resizeMode="contain"
          onLoad={onLoad}
        />
      </Marker.Animated>



```

I am using 
react-native@0.63.2
react-native-map@^0.27.1

**Comment by EhsanSarshar** [comment]
the only real issue is that animateMarkerToCoordinate is not supporting in ios

**Comment by EhsanSarshar** [comment]
@pvinis sorry if I bother you :) .
would you mind to help the community to solve this issue in IOS. 
the issue is in here [Marker.js](https://github.com/react-native-community/react-native-maps/blob/master/lib/components/MapMarker.js) in line 311.
it suppose to return a function but it return undefined.

here are the code portion

```Javascript
_runCommand(name, args) {
    switch (Platform.OS) {
      case 'android':
        NativeModules.UIManager.dispatchViewManagerCommand(
          this._getHandle(),
          this.getUIManagerCommand(name),
          args
        );
        break;

      case 'ios':
        this.getMapManagerCommand(name)(this._getHandle(), ...args);
        break;

      default:
        break;
    }
  }
```

**Comment by pvinis** [comment]
No idea why I was pinged here, but if you know what the problem is, maybe do a PR?

**Comment by EhsanSarshar** [comment]
@pvinis I don't know that much about ObjectiveC. but hope you help to solve it. this issue exist since 2018 and it seems that there is no one to solve it

**Comment by EhsanSarshar** [comment]
@gabrielmoncea is there any progress on this issue.

**Comment by gabrielmoncea** [comment]
Hey @EhsanSarshar I haven't seen any PR that might solve this issue. And I only label issues for now.
And please don't spam other community members. People do open source for different reasons and no one is obligated to solve any issues.

**Comment by EhsanSarshar** [comment]
@gabrielmoncea thanks for the response. I am very sorry if I bothered anyone. I must use mapbox-gl or webview until this issue will fix.

**Comment by Dakuan** [comment]
yep, still a thing

**Comment by EhsanSarshar** [comment]
this issue is still active don't stale it

**Comment by Dakuan** [comment]
still a thing

**Comment by TheEhsanSarshar** [comment]
@stale hold on

**Comment by realfelixyu** [comment]
Still a problem
