### ISSUE TITLE
Android vs iOS Marker Placement

### ISSUE THREAD

**Issue by mofmn** [react-native-maps/react-native-maps#3554]
# Bug report

Edit : After more thought it seems that this is an issue with the difference in marker placement between the two OS, iOS seems to place centre of marker at the coordinate provided, and android places at bottom and centre. I do not see a way to align this behaviour at this point. 
On iOS, the marker renders as expected - Over the top of a polyline, with the line visible underneath through the transparent parts of the png given to the Marker component. In Android the polyline is not at all visible underneath the Marker PNG as is shown in the following images 
In Android : 
<img width="483" alt="Screenshot 2020-09-22 at 4 30 55 PM" src="https://user-images.githubusercontent.com/9949335/93854963-a263f880-fcf1-11ea-8b80-adb448c80d06.png">
In iOS
<img width="425" alt="Screenshot 2020-09-22 at 4 39 45 PM" src="https://user-images.githubusercontent.com/9949335/93855342-4baaee80-fcf2-11ea-94cf-8fcb360846ed.png">

The expectation is for the android build to behave as the iOS build is doing

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 46.72 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: react-native-maps@0.27.1

## Steps to reproduce

```
<Marker.Animated
              ref={(marker) => {
                this.marker = marker;
              }}
              image={Icons.LocationCircle}
              coordinate={this.state.coordinate}
              style={{ width: 72, height: 72 }}
              opacity={0.9}

            />`

`<Polyline
             coordinates={this.state.gpsData}
             strokeColor="rgba(18, 72, 87, 0.9)"
             strokeWidth={7}
              />
```

I listed this as a bug, i could understand if it's considered more of a feature request. I figured a bug as the two environments do not behave the same so this leads to unexpected behaviour. I imagine the easiest way to reproduce this is to draw a PNG with transparency over any Polyline on the same coordinates.

**Comment by mofmn** [comment]
Actually, this isn't an issue with transparency as when the route overlaps/turns back on itself it you can see the previous route underneath the PNG. So this is actually an issue with drawing the Polyline, it does not draw the last bits of the line underneath the Marker.

**Comment by mofmn** [comment]
So it seems that the reality is that android and iOS place their markers with different philosophies, iOS puts the centre of the marker on the point provided, and i am guessing Android puts the bottom and centre at the point provided. As far as i can tell theres no prop for aligning this behaviour. Any help on this front?

**Comment by mclima123** [comment]
You can use the centerOffset prop on iOS and anchor prop on Android [as seen here](https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md).
For Android, if you wanna have the marker centered on a position, pass the prop _anchor={{ x: 0.5, y: 0.5 }}_

**Comment by grantbartone** [comment]
+1

In my own testing, I ended up with conditionally setting the `anchor` prop on Android to `{ x: 0.2, y: 0.2 }` to get the most accurate marker placement. Would be great to incorporate this in the library so it behaves the same across platforms out of the box.
