### ISSUE TITLE
App crash when render <Mapview></Mapview>

### ISSUE THREAD

**Issue by shrimallamanoj** [react-native-maps/react-native-maps#3555]
App crash when render <Mapview></Mapview>

working fine in android

Here are the deatils:
		"react-native-maps": "^0.26.1",
		"react": "16.9.0",
		"react-native": "^0.61.5",

Xcode: 10.3 version?
Before its working suddenly stopped working... any solution?

**Comment by eacanalg** [comment]
Can you please give more info? what do you mean by crash? Any error code? which platform? my first guess is that you are trying to use this on web and it is not supported for web.

**Comment by coolprinze** [comment]
I'm having same issue after updating RN to 0.63.3

**Comment by coolprinze** [comment]
MapView works fine on android and shuts down(crash without error) the app on IOS. Please help

**Comment by antonioreyna** [comment]
Same problem here on android, but when adding markers, it starts to slow and show lot of log messages on android studio about garbage collector then crashes with no error
