### ISSUE TITLE
Move repo from react-native-community

### ISSUE THREAD

**Issue by rborn** [react-native-maps/react-native-maps#3556]
We need to move the repo to our own org or to somebody that's an "oficial" maintainer as per

https://github.com/react-native-community/discussions-and-proposals/blob/master/partners/0002-apply-organization-repository-policy.md

**Comment by rborn** [comment]
@christopherdro I think we should tackle this with an org maybe?
Also there different levels of "access" that should be unified?  (for example I cannot publish to npm 😅)

Let me know your thoughts 😄

**Comment by EhsanSarshar** [comment]
I think we should work on this library to make it better. it have too many bugs. and the only thing annoying in my app is maps. marker onPress are very slow. marker animation on ios are very laggy and many other things.

**Comment by rborn** [comment]
@EhsanSarshar any help is more than welcome: https://github.com/react-native-maps/react-native-maps/issues/3564

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-maps/react-native-maps/issues/3563
