### ISSUE TITLE
TouchableHighlight is not working after marker(react-native-map) drag-drop happen in iOS

### ISSUE THREAD

**Issue by rahulagg10** [react-native-maps/react-native-maps#3559]
# Question

Hi Team,

I'm getting a problem while drag drop a pin on google map then TouchableHighlight(imported from 'react-native') present on screen is not taking any action(like onPress). **This happening in only iOS**.

When I import **TouchableHighlight** from **'react-native-gesture-handler'** then it works fine.
But the problem is I'm using the **GooglePlacesAutocomplete**(react-native-google-places-autocomplete) on Map screen and **GooglePlacesAutocomplete** is using **TouchableHighlight** from **'react-native'.** 
So could you help me by giving the idea how can I over come from this problem?

Thanks,
Rahul

**Comment by vuonghvat** [comment]
Same :(

**Comment by vuonghvat** [comment]
Do you fixed?

**Comment by vuonghvat** [comment]
Please tell me solution :(

**Comment by rahulagg10** [comment]
@vuonghvat I don't have fix for now. If you find any pls post here.

**Comment by disrae** [comment]
Same issue but we're using TouchableOpacity 👍 I'll edit if I find another Touchable that works.
