### ISSUE TITLE
Update package for the new home repo

### ISSUE THREAD

**Issue by rborn** [react-native-maps/react-native-maps#3563]
The repo was moved to a new home repo, and we need to update it to reflect this

- [ ]  update any link that leads to the old repo (readme, package, etc)
- [x] add "looking for maintainers/help" announcement - https://github.com/react-native-maps/react-native-maps/issues/3564
- [x] fix/setup Travis -  https://github.com/react-native-maps/react-native-maps/pull/3566

**Comment by gabrielmoncea** [comment]
@rborn which is the new repo?

**Comment by rborn** [comment]
@gabrielmoncea  you are already in it :) and npm should take the new url anyway https://github.com/react-native-maps/react-native-maps.git
We just transferred the repo, we didn't create a new one

**Comment by gabrielmoncea** [comment]
I was asking because the last release was in March and there are 29 ongoing PR :)
I thought the project was unmaintained

**Comment by rborn** [comment]
well... https://github.com/react-native-maps/react-native-maps/issues/3564
