### ISSUE TITLE
Update position even though showsUserLocation=false?

### ISSUE THREAD

**Issue by freakadunse** [react-native-maps/react-native-maps#3574]
Hey there,

im currently developing an app and the main focus lies on the mapview.
I'd like to change the blue dot of the user's current location and display a circle instead.
Works fine, i draw circle with the circle component which gets updated which the location in the state i get by onUserLocationChange.

But as soon as i set showsUserLocation=false the event won't get triggered.

Is there a property/handler to get the current location without displaying the blue dot + GPS radius? 
Or at least deactivate the gps circle around the users current position?

i'd like to avoid having my own timers to retrieve the current location because it works quite well with the mapview events.

Thanks.

BR
Pascal

**Comment by hgvo9** [comment]
@freakadunse

Hey I was wondering if you found a way to get around this ? I have exactly the same issue

**Comment by freakadunse** [comment]
Hi mate,

sorry for that late response.

I have implemented a new class component.
This class component renders a circle around the current position.
That is dependent on a location property in my state.

To refresh the position is use the Location.watchPositionAsync which triggers a refresh function as callback.

```
<MapView style={{ height: '100%', width: '100%' }}
                ref={mapView}
                showsPointsOfInterest={true}
                showsBuildings={false}
                showsMyLocationButton={false}
                initialRegion={location}
                toolbarEnabled={false}
                onRegionChangeComplete={onRegionChangeComplete}
                customMapStyle={Colors[colorScheme].map}>
                       <UserLocation location={location} delta={delta} />
            </MapView>

```

as soon as the location gets changed, the UserLocation will automatically rerender.

Hope this helps :-)

BR
Pascal

**Comment by hgvo9** [comment]
> Hi mate,
> 
> sorry for that late response.
> 
> I have implemented a new class component.
> This class component renders a circle around the current position.
> That is dependent on a location property in my state.
> 
> To refresh the position is use the Location.watchPositionAsync which triggers a refresh function as callback.
> 
> ```
> <MapView style={{ height: '100%', width: '100%' }}
>                 ref={mapView}
>                 showsPointsOfInterest={true}
>                 showsBuildings={false}
>                 showsMyLocationButton={false}
>                 initialRegion={location}
>                 toolbarEnabled={false}
>                 onRegionChangeComplete={onRegionChangeComplete}
>                 customMapStyle={Colors[colorScheme].map}>
>                        <UserLocation location={location} delta={delta} />
>             </MapView>
> ```
> 
> as soon as the location gets changed, the UserLocation will automatically rerender.
> 
> Hope this helps :-)
> 
> BR
> Pascal

Hi Pascal,

Thank you a lot for your answer, and no worries for the late response. Unfortunately, I don't use expo so I don't have Location.watchPositionAsync method available in my project.

Have a good day!
hgv9

**Comment by hgvo9** [comment]
> > Hi mate,
> > sorry for that late response.
> > I have implemented a new class component.
> > This class component renders a circle around the current position.
> > That is dependent on a location property in my state.
> > To refresh the position is use the Location.watchPositionAsync which triggers a refresh function as callback.
> > ```
> > <MapView style={{ height: '100%', width: '100%' }}
> >                 ref={mapView}
> >                 showsPointsOfInterest={true}
> >                 showsBuildings={false}
> >                 showsMyLocationButton={false}
> >                 initialRegion={location}
> >                 toolbarEnabled={false}
> >                 onRegionChangeComplete={onRegionChangeComplete}
> >                 customMapStyle={Colors[colorScheme].map}>
> >                        <UserLocation location={location} delta={delta} />
> >             </MapView>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as soon as the location gets changed, the UserLocation will automatically rerender.
> > Hope this helps :-)
> > BR
> > Pascal
> 
> Hi Pascal,
> 
> Thank you a lot for your answer, and no worries for the late response. Unfortunately, I don't use expo so I don't have Location.watchPositionAsync method available in my project.
> 
> Have a good day!
> hgv9

Nevermind, I got expo modules working on my react-native project by installing 'react-native-unimodules' package (https://docs.expo.dev/bare/installing-unimodules/), and indeed the method 'watchPositionAsync' of 'expo-location' package does work very well without setting the prop 'showsUserLocation' to true.

I don't know if that's the best solution but this is the only thing that is working so far, so thanks a lot Pascal for the tip.

Thank you,
hgv9
