### ISSUE TITLE
can't install google map pod 

### ISSUE THREAD

**Issue by waterflower124** [react-native-maps/react-native-maps#3575]
Hi everyone
I have an issue to install google map.
I have no any issues when I use this module without google map. But when I add google map to iOS project, I have an error in pod install.

Follow is my pod file:
![Screenshot at Oct 03 23-08-49](https://user-images.githubusercontent.com/39854665/95006028-7ab44080-05cd-11eb-92ed-369392cf2828.png)

when I enter `pod install', there is following error
![Screenshot at Oct 03 23-11-14](https://user-images.githubusercontent.com/39854665/95006053-d67ec980-05cd-11eb-98a5-b28fd931871d.png)

![Screenshot_9](https://user-images.githubusercontent.com/39854665/95005937-34121680-05cc-11eb-8aac-b9d3578f0a9c.png)

Following is my os environment.
````
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
````

Hope your help. Thanks

**Comment by kwaimind** [comment]
Hey @waterflower124 it looks like you're installing the package wrong and you've removed react native from your pod file. 

If you're using RN 0.60+ then you can typically just run

```
cd ios
pod install
```

Try that and see if it fixes the error. There is more detailed iOS installation instructions in the README 👻

**Comment by waterflower124** [comment]
> Hey @waterflower124 it looks like you're installing the package wrong and you've removed react native from your pod file.
> 
> If you're using RN 0.60+ then you can typically just run
> 
> ```
> cd ios
> pod install
> ```
> 
> Try that and see if it fixes the error. There is more detailed iOS installation instructions in the README 👻

**Comment by waterflower124** [comment]
Hi @kwaimind Thanks for your reply. As I described. all packages are latest: RN 0.63.3. and map is working but have error when I add google map on iOS. when I add google map pod and pod install then shows error.

**Comment by SharfMohiuddin** [comment]
I'm facing the same issue. Can anybody has the solution for it?
