### ISSUE TITLE
MapView's onLayout event is not documented

### ISSUE THREAD

**Issue by lucasriondel** [react-native-maps/react-native-maps#3576]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Expected Behavior

https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md

I expected to find documentation on `onLayout` event but did not find anything :(

### Actual Behavior

![image](https://user-images.githubusercontent.com/7773454/95102656-ed3f3080-0733-11eb-803d-e03ea332aa27.png)

### Reproducible Demo

**Comment by MichaelHettmer** [comment]
The `onLayout` event of react-native-map's MapView is the same as the `onLayout` of the default react-native View.
You can find the documentation here https://reactnative.dev/docs/view#onlayout
