### ISSUE TITLE
Create .github templates for issues

### ISSUE THREAD

**Issue by rborn** [react-native-maps/react-native-maps#3578]
We need to add back issues templates.

This is a good example (actually it was using this before it was moved): https://github.com/react-native-community/.github)

**Comment by kwaimind** [comment]
Totally agree 💯 

Do you want to take this task or should I?

**Comment by rborn** [comment]
@kwaimind if you could would be amazing ❤️

**Comment by kwaimind** [comment]
I'm on it 💪
