### ISSUE TITLE
Map does not show up in either browser or phone throughExpo: Cannot read property 'style' of undefined when running web version

### ISSUE THREAD

**Issue by jshrt** [react-native-maps/react-native-maps#3580]
## Is this a bug report?

Yes

Bug reproduction:

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
    "react-native": "~0.63.2",
    "react": "16.13.1",
    "react-native-maps": "0.27.1",
```

### Steps to Reproduce

1. create a new react native project
2. install react-native-maps (_Please read through installation instructions_)
3. create a map component like the following:
```
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, Text, View, Dimensions } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <MapView
              initialRegion={{
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421
              }}
             style={styles.mapStyle} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapStyle: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});

```

### Expected Behavior

A map should show up in both the web version on my browser

### Actual Behavior

In the browser, I received the error that you can see in the bug reproduction
### Reproducible Demo

1. Go to this [link](https://snack.expo.io/@jshrt/mapview)
2. Select web in the right side (_on top of the phone component in there_)
3. Voila, error appears.

**Comment by christopherdro** [comment]
This library doesn't provide support for web.

**Comment by jshrt** [comment]
@christopherdro Is this pointed it out to in the docs?

**Comment by jshrt** [comment]
Thank you!

**Comment by actuallymentor** [comment]
This error persists, but the docs say `Web is experimental! You may need to add the web target to your Expo app.` which seems to indicate this should work.
