### ISSUE TITLE
UrlTile on map with google provider on IOS not transparent

### ISSUE THREAD

**Issue by andrew-sushko-es** [react-native-maps/react-native-maps#3582]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native": "0.63.2",
"react": "16.13.1",
"react-native-maps": "^0.27.1",

### Steps to Reproduce

`
const MapScreen = () => {
...
return ( 

     <MapView
          ref={mapRef}
          style={{flex: 1}}
          provider={PROVIDER_GOOGLE}
          initialRegion={currentRegion}>
             <UrlTile
                key="weatherTile"
                urlTemplate= 
                  {`http://maps.openweathermap.org/maps/2.0/weather/PR0/{z}/{x}/{y}?appid=${OWMAP_TOKEN}`}
                maximumZ={19}
                flipY={false}
                shouldReplaceMapContent={false}
          />
        </MapView>
   )
}
`

### Expected Behavior

On Android all works good:
[Android Image](https://ibb.co/Zm1VxW5)

### Actual Behavior
On IOS it looks like:
[IOS image with Google Maps](https://ibb.co/ZGG8NPL)

And if pass prop provider={null} it turns to IOS maps and all works good:
[IOS image with IOS maps](https://ibb.co/fMqPhwP)

**Comment by rohitkum28** [comment]
@andrew-sushko-es Did you find any fix for this issue? I am facing the same issue. It should be reopened again.

**Comment by andrew-sushko-es** [comment]
@rohitkum28 Hey, yeah I found the way how to resolve this issue. But it works only with services whitch provides possibility to adjust pallette of weather map in url, and your url should looks like: 
`https://maps.openweathermap.org/maps/2.0/weather/PA0/{z}/{x}/{y}?&palette=0.5:000000;1.8:00fa64;2.4:00e600;3:00d300;4.5:00ba00;6:00a000;9:008c00;10.5:007800;11.1:006400;12:005a00;15:005000;18:004600;21:eff800;24:f3eb00;27:fadc00;30:ffcd00;36:ff9600;42:ff5b00;48:ff0000;72:ff0064;96:ff0092;192:aa2bc3;300:7609a4&opacity=0.7&appid=${WEATHER_API_KEY}`

It is only way i found to fix this issue without modification of lib code. As I get for some reasons 
inversion of gray, non-bright colors to white occurs and palette helps to avoid this colors. Hope it helps you!
