### ISSUE TITLE
Issue with zooming MapView with google provider

### ISSUE THREAD

**Issue by AlexanderKaplunsky** [react-native-maps/react-native-maps#3588]
Hi, mates. I'm using react-native-maps v0.27.1 for IOS (only) app. After updating react-native from 0.59.x to 0.63.3 I started to get crashes while zooming map ( with Google provider ). It was so strange, Google Maps SDK tried to get data from random cell of memory, that causes error:

> com.google.Maps.LabelingBehavior (48): EXC_BAD_ACCESS (code=1, address=0xe)  e.t.c

So, I found solution for this issue.

Try to downgrade GoogleMaps pod in 

> node_modules/react-native-maps/react-native-google-maps.podspec

Set

> s.dependency 'GoogleMaps', '3.2.0'

This version works fine for me

If this solution fixed your issue, you have to create patch for react-native-maps. Use this to create patch

> [patch-package](https://www.npmjs.com/package/patch-package)

My react-native info

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 54.09 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by ragozin-n** [comment]
Same issue here, thanks for your solution

**Comment by fdobre** [comment]
A similar crash is still present in 27.0.1 showing up on device rotation related to GoogleMaps 3.5.0:

```
OS Version: iOS 14.4 (18D52)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x0000000000000008
Crashed Thread: 0

Application Specific Information:
countByEnumeratingWithState:objects:count: > XTUM >
Attempted to dereference garbage pointer 0x8.

Thread 0 Crashed:
0   upmesh                          0x200695378         gmscore::vector::Vector2fWithOffsetAndOrigin<T>
1   upmesh                          0x20068f74c         gmscore::vector::Vector2fWithOffsetAndOrigin<T>
2   upmesh                          0x2006896ec         gmscore::vector::Vector2fWithOffsetAndOrigin<T>
3   upmesh                          0x200688ffc         gmscore::vector::Vector2fWithOffsetAndOrigin<T>
4   upmesh                          0x200565f18         gmscore::renderer::Behavior::HasHigherPriority
5   upmesh                          0x200609bac         gmscore::renderer::ProxySortedRenderBin<T>::OrderingWrapper
6   upmesh                          0x2005eaeac         gmscore::renderer::RenderBin::PerformDraw<T>
7   upmesh                          0x20063f088         gmscore::renderer::ProxySortedRenderBin<T>::OrderingWrapper
8   upmesh                          0x2005e9478         gmscore::renderer::RenderBin::PerformDraw<T>
9   upmesh                          0x2005e8058         gmscore::renderer::RenderBin::PerformDraw<T>
10  QuartzCore                      0x330fce6f8         CA::Display::DisplayLink::dispatch_items
11  QuartzCore                      0x3310a7a7c         display_timer_callback
12  CoreFoundation                  0x32a870dcc         __CFMachPortPerform
13  CoreFoundation                  0x32a895fe4         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_F
```

Any idea if upgrading GoogleMaps sdk in the podspec could fix the issue?

Has anybody tried an upgrade of GoogleMaps to 4.2.0?

**Comment by shahin963** [comment]
@AlexanderKaplunsky that worked thanks
