### ISSUE TITLE
Overlays are not deleted in native once destroyed in React Native

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [react-native-maps/react-native-maps#3598]
# Bug report

## Summary

Currently when you update the map with components such as overlay from the state and add and remove them many times, such as when moving the map, these elements are unmounted in react but persist on the map, which makes the application start to consume RAM until it fails.

## Environment info

`react-native info` output:

```bash
      react-native: 0.63.3
      react: 16.13.1
      react-native-maps: 0.27.1
```

## Steps to reproduce

1. Have a map and inside an array (what will come from the state) that will be filled with overlays
2. I create the overlay in a different component, for test if is unmounted.
3. Add many overlays to the array, for example 15 per second, and clean, add, clean, add, clean

Describe what you expected to happen:

1. React Native unmount components
2. Java/Ios remove the native component from the map

Describe what you actually happens:

1. React Native unmount components
2. Java/Ios does not remove the native component from the map and acumulate

## Reproducible sample code

<img width="595" alt="Captura de pantalla 2020-10-31 a las 0 15 41" src="https://user-images.githubusercontent.com/16174918/97764822-348cc700-1b10-11eb-8efa-2b4ed6638938.png">

**Comment by DavidGonzalezGutierrez** [comment]
I found it.
There is a small bug in the Java code, probably the same bug will be in Objective C.
I will upload a PR to solve this bug.

**Comment by ParagonVirtuoso** [comment]
Can you tell me if this problem has been fixed? I have a case here that is happening this same problem!
