### ISSUE TITLE
Possible to use Coordinate system other than Lat/Long for custom map?

### ISSUE THREAD

**Issue by CDBridger** [react-native-maps/react-native-maps#3599]
As title says, Have a custom tiled map that want to place markers over, but the coordinates of the markers are given in (X,Y) meters from the top left (0,0). Does this library accommodate for this ability or do I have to figure out the appropriate conversion (or is there another library which will accommodate this ability?)

Cheers!

**Comment by christopherdro** [comment]
Use `coordinateForPoint` method on <Mapview />. https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md
