### ISSUE TITLE
Unable to get URLTile working

### ISSUE THREAD

**Issue by CDBridger** [react-native-maps/react-native-maps#3601]
Trying to get URLTile example working using 'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png' but instead I get an invisible tile with the apple maps in the background. I've added the NSAppSecurityTransport allow arbitrary loads to my info.plist. 

Here is my code

```
const ProjectMap: React.FC<ProjectMapProps> = ({ route, navigation }: ProjectMapProps) => {

    const MapRef = useRef<MapView>(null);
    const [region, setRegion] = useState(INITIAL_REGION);
    const [urlTemplate, setUrlTemplate] = useState<string>('http://c.tile.openstreetmap.org/{z}/{x}/{y}.png')

    const onRegionChange = (region: any) => {
        setRegion(region);
    }

    return (
            <MapView
                ref={MapRef}
                style={styles.mapStyle}
                region={region}
                onRegionChange={onRegionChange}
                mapType={Platform.OS == "android" ? "none" : "standard"}
            >
                <UrlTile
                    maximumZ={4}
                    flipY={false}
                    style={styles.tileStyle}
                    zIndex={1}
                    urlTemplate={urlTemplate}
                />
            </MapView>
    )
}

export default ProjectMap

const styles = StyleSheet.create({
    mapStyle:{
        flex: 1,
    },
    tileStyle:{
        flex: 1,
    }
})
```

Can someone explain what I'm doing wrong?

**Comment by CDBridger** [comment]
Turns out it was an issue with the template I was using. Issue I still have is that the world map is coming up behind which I do not want.

**Comment by douglaslondrina** [comment]
It's stated in MapView comp. documentation that "none" mapType is not supported for MapKit (iOS map engine). Try setting props mapType to "none" and provider to "google".

**Comment by IPWright83** [comment]
@CDBridger what was wrong with your template? I've got the same problem, just trying to experiment using the example from the README.

**Comment by IPWright83** [comment]
Ok, I found swapping the template to use `https` instead worked :)
