### ISSUE TITLE
MapPadding doesn't work on Android

### ISSUE THREAD

**Issue by questionablequestion** [react-native-maps/react-native-maps#3603]
# Bug report

## Summary

MapPadding prop doesn't work properly on Android while on iOS works great. I'm using Google as map provider. I have tried using `PixelRatio.getPixelSizeForLayoutSize` specifically for Android but it doesn't make difference. If I give it some crazy value like `5000` it seems like kinda works but still doesn't make sense.

## Environment info

`react-native info` output:

```bash
react: 16.13.1
react-native: 0.63.2 
react-native-maps: 0.27.1
```

## Steps to reproduce

1. Add mapPadding prop
```
<MapView
...
mapPadding={{
    top: 120,
    right: 0,
    bottom: 160,
    left: 0,
}}
```

Describe what you expected to happen:

1. Using `getMapBoundaries` should return visible boundary coordinates
2. Based on boundary, I fetch markers and show them

Describe what you actually happens:

1. Currently I'm getting markers that are behind cards that are hovering at the bottom of the map (height is 160, same as bottom padding)

## Reproducible sample code

Add `mapPadding` prop with top/right/bottom/left values.

**Comment by ChielBruin** [comment]
(Variations of) this bug have/has been discussed in other issues as well:
- #2108
- #3340

For some people it worked to update the width of the map in the `onMapReady` handler to force an update of the component (see the comment by LukePenkava in #2108)

In my case this solution did only work some of the time, making it both an ugly and a non-working fix. Furthermore, the `mapPadding` seems to randomly reset if I perform enough React navigation screen transitions that trigger layout changes of the mapview.

I have only seen the bug on Android, but all Android phones I tried have shown the issue.

**Comment by questionablequestion** [comment]
Thanks. I have tried hacks with changing width onMapReady but nothing changed. Google logo is in correct position for me it's just that `getMapBoundaries` isn't respecting padding on Android.

**Comment by spacesuitdiver** [comment]
Yea I have to setWidth awkwardly to get this to work. I also am not able to get `fitToCoordinates` to work properly, it doesn't seem to abide by the mapPadding like iOS does.

**Comment by bemaverick** [comment]
Any updates here?
@questionablequestion

**Comment by questionablequestion** [comment]
@bemaverick Nothing, I'm still stuck with this problem and I don't have any other alternative beside changing screen design so cards aren't positioned absolute over the map but below it.

**Comment by mausv** [comment]
I was having a similar issue using fitToCoordinates, found a workaround.

https://github.com/react-native-maps/react-native-maps/issues/2629#issuecomment-765001139

**Comment by hosle** [comment]
The `map.setMapPadding` method works well when you run the `lib/Android/` implementation in native page. 
However, the `RootReactView` that contains `AirMapView` doesn't get re-rendered after we set the padding to it. That's why the google watermark gets overlapped or gone. 
To fix this is just to add a post in `requestLayout` in `AirMapView.java` as below

```
//AirMapView.java
  @Override
  public void requestLayout() {
    super.requestLayout();
    post(measureAndLayout);
  }

  private final Runnable measureAndLayout = new Runnable() {
    @Override
    public void run() {
      measure(MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
              MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
      layout(getLeft(), getTop(), getRight(), getBottom());
    }
  };
```
After fixed :
<img src="https://user-images.githubusercontent.com/6284688/109627911-1649dd00-7b7d-11eb-8914-c40bd49a4eaf.jpg" width="270" height="562">


Have created PR #3730 as well.

**Comment by christopherdro** [comment]
Fixed via 4741b607fe06b82b24a7b04fc28441dc592944ce

**Comment by adabaed** [comment]
This should be reopened.

**Comment by mrakus-sofomo** [comment]
Still does not work

**Comment by gcmazzardo** [comment]
It looks like this is a problem again.

**Comment by shoamano83** [comment]
Hi, I recently noticed some issues related to `mapPadding` property on Android (https://github.com/react-native-maps/react-native-maps/issues/5150, https://github.com/react-native-maps/react-native-maps/issues/5152, https://github.com/react-native-maps/react-native-maps/issues/5153 and https://github.com/react-native-maps/react-native-maps/issues/5154) and fixed them with this PR: https://github.com/react-native-maps/react-native-maps/pull/5151.

You can find a patch there which can be applied using `patch-package`. If you're interested, please try it out and let me know your feedback. Thanks!

**Comment by markerclusterer** [comment]
> I have to setWidth in onMapReady as mention to get the attribution to show up at the bottom but I also am not able to get `fitToCoordinates` to work properly, it doesn't seem to abide by the mapPadding like iOS does.





https://stackdev.space/questions/is-the-getmap-function-malfunctioning
