### ISSUE TITLE
Map jumps around when scrolling is released

### ISSUE THREAD

**Issue by luistoxic** [react-native-maps/react-native-maps#3605]
# Bug report

## Summary

When i scroll on the map it often jumps around a bit when scroll is released. 
I started a whole new project with nothing inside and no plugins except react-native-maps and get the same behaviour.
I get the same error with the version thats on npm 0.27.1 and by installing the latest version from GitHub. 
The strange thing is that it does not always do this sometimes it works right and when i release the scroll it calls onRegionChangeComplete immediately. But when it bugs it calls onRegionChange like 20 times before onRegionChangeComplete is called.

If you need more information i would be happy to provide it.

## Environment info

`react-native info` output:
IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    Visual Studio: 16.7.30413.136 (Visual Studio Community 2019), 15.9.28307.1234 (Visual Studio Community 2017)
  Languages:
    Java: 1.8.0_251 - C:\Program Files\Java\jdk1.8.0_251\bin\javac.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.3 => 0.63.3
    react-native-windows: Not Found

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. Start new project with create-react-native-app
2. Install react-native-maps
3. Create a screen with only MapView
4. Scroll around the map and on release it jumps around a little bit

Describe what you expected to happen:

1. That on release the map does not jump.

Describe what you actually happens:

## Reproducible sample code

`import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapView, {PROVIDER_GOOGLE,} from 'react-native-maps';

export default function App() {
    return (
        < View style={styles.container}>
            < MapView
                provider={PROVIDER_GOOGLE}
                style={styles.map}
                pitchEnabled={false}
                rotateEnabled={false}
                showsCompass={false}
            >
            < /MapView>
        < /View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    map: {
        bottom: 0,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
    }
});
`

**Comment by hugoh59** [comment]
I'm stil having this issue.

**Comment by AlexMachin1997** [comment]
I've just come across this issue after upgrading my app.

I'm currently using version 0.28, when I scroll away it just takes me back to my position. Am I missing a property or something ?

Just a note, I'm watching the users location and updating it via "expo-location" watchAsync which updates the postion so that might be causing the issue.

Would appreciate any comments 😄

**Comment by lekzd** [comment]
Looks like it's m1 chipset related issue and can be fixed using "run with Rosetta" option in simulator application info modal in Mac OS

**Comment by dansimau** [comment]
> Looks like it's m1 chipset related issue and can be fixed using "run with Rosetta" option in simulator application info modal in Mac OS

The M1 was announced on November 10 2020[[1](https://en.wikichip.org/wiki/apple/mx/m1)] and this bug report was filed on November 5 2020.

**Comment by lekzd** [comment]
> > Looks like it's m1 chipset related issue and can be fixed using "run with Rosetta" option in simulator application info modal in Mac OS
> 
> The M1 was announced on November 10 2020[[1](https://en.wikichip.org/wiki/apple/mx/m1)] and this bug report was filed on November 5 2020.

I found this issue similar to mine, related with M1 and hope "run with Rosetta" solution helps others who read issues like me

**Comment by MotionbyFabi** [comment]
I came across this issue while building my app with react-native-maps version "0.31.1", I already tried the run with rosetta solution and that didn't seem to solve my problem. This is what my code looks like.

`<MapView
                onPress={onSelect}
                style={{
                  flex: 1,
                  width: "100%",
                  zIndex: -1,
                }}
                customMapStyle={
                  ThemeStatus === "Dark" ? DarkModeMapStyle : LightModeMapStyle
                }
                loadingBackgroundColor={Theme.gray[200]}
                pitchEnabled={!mapIsLocked}
                rotateEnabled={!mapIsLocked}
                scrollEnabled={!mapIsLocked}
                minZoomLevel={Zoom}
                scrollDuringRotateOrZoomEnabled
                zoomEnabled={!mapIsLocked}
                showsUserLocation={true}
                provider={PROVIDER_GOOGLE}
                region={{
                  latitude: location?.latitude!,
                  longitude: location?.longitude!,
                  latitudeDelta: 0.092,
                  longitudeDelta: 0.0421,
                }}
              >
                {selectedLocation && (
                  <Marker
                    draggable
                    coordinate={selectedLocation!}
                    onDragEnd={onSelect}
                  />
                )}
              </MapView>`

I have tried to make a new project with only react native maps in it like the original problem and I exhausted all of my solutions. Would be much appreciated if someone can help.
