### ISSUE TITLE
Maps text is scaling when user changes text size from phone settings

### ISSUE THREAD

**Issue by mak12** [react-native-maps/react-native-maps#3606]
**Summary**
Font scaling issue.
Although i have been able to stop Apps text font scaling through

`    Text.defaultProps.allowFontScaling = false; `

But maps text sizes are same as from phone settings.
**Environment info**

    System:  
 
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 54.01 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
    Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
    npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-i18n: 2.0.15`

**Steps to reproduce**

1. Install library
2. Change font size from phone settings

![image](https://user-images.githubusercontent.com/30626811/98246325-fa9a4580-1f93-11eb-8f07-81e3974e2fe6.png)

**Comment by YeshanJay** [comment]
I'm having the same issue. Please reopen this issue ticket.

**Comment by arundevkv** [comment]
Same issue here

**Comment by arundevkv** [comment]
Any update on this issue. Please reopen this issue.

**Comment by codal-mpawar** [comment]
@arundevkv @mak12 @YeshanJay Any update on this? we are getting same issue.

**Comment by arundevkv** [comment]
@codal-mpawar Nope. Living with this issue
