### ISSUE TITLE
Add WMS layer capability

### ISSUE THREAD

**Issue by iliastsergoulas** [react-native-maps/react-native-maps#3609]
# Question

Is WMS layer going to be available in the near future? I believe that it should be offered as part of the Component Api, maybe in the same way as Overlay.
WMStile is offering tiled display, something not so useful when all you want is to show the returned polygon on the map, just like Openlayers in simple Javascript.

**Comment by Bulva** [comment]
+1

**Comment by ombogdan** [comment]
+1

**Comment by ombogdan** [comment]
+1

**Comment by ombogdan** [comment]
+1

**Comment by ankitsharma07** [comment]
Are there methods to load/overlay openlayer maps or geoserver shapefiles?
