### ISSUE TITLE
Trying to change the mapType using setState does not work on the latest version

### ISSUE THREAD

**Issue by federicomiralles** [react-native-maps/react-native-maps#3614]
## Summary

Trying to change the **mapType** using **setState** does not work on the latest version.
Indeed the issue I'm reporting looks quite similar to this one: https://github.com/react-native-maps/react-native-maps/issues/2178

## Environment info

      react-native: 0.63.2
      react: 16.13.1
      react-native-maps: 0.27.1

## Reproducible sample code

```
import React, { useRef, useState } from 'react';
import { StyleSheet, Button } from 'react-native';
import MapView from 'react-native-maps';

const CHANGE_MAPTYPE_TO = 'Change mapType to ';

const Map = () => {
  const mapRef = useRef<MapView>(null!);
  const [buttonTitle, setButtonTitle] = useState(CHANGE_MAPTYPE_TO + 'satellite');

  const toggleMapType = () => {
    let mapType;
    mapType = mapRef.current?.state.mapType === 'satellite' ? 'standard' : 'satellite';
    const buttonNewTitle = CHANGE_MAPTYPE_TO + (mapType === 'satellite' ? 'standard' : 'satellite');
    console.log('UPDATE MAP TYPE TO =', mapType);
    console.log('PREVIOUS STATE =', mapRef.current?.state);
    mapRef.current?.setState(
      {
        ...mapRef.current?.state,
        mapType,
      },
      () => {
        console.log('NEW SATE =', mapRef.current?.state);
        setButtonTitle(buttonNewTitle);
      },
    );
  };

  return (
    <>
      <MapView ref={mapRef} provider="google" style={styles.container} />
      <Button title={buttonTitle} onPress={() => toggleMapType()} />
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default Map;
```
Upon pressing the button you'll get the following logs:
```
[Wed Nov 11 2020 10:32:46.914]  LOG      UPDATE MAP TYPE TO = satellite
[Wed Nov 11 2020 10:32:46.915]  LOG      PREVIOUS STATE = {"isReady": true}
[Wed Nov 11 2020 10:32:46.915]  LOG      NEW SATE = {"isReady": true, "mapType": "satellite"}
[Wed Nov 11 2020 10:32:56.273]  LOG      UPDATE MAP TYPE TO = standard
[Wed Nov 11 2020 10:32:56.274]  LOG      PREVIOUS STATE = {"isReady": true, "mapType": "satellite"}
[Wed Nov 11 2020 10:32:56.275]  LOG      NEW SATE = {"isReady": true, "mapType": "standard"}
```
Unfortunately changing the mapType on the state does not take effect on the MapView.

Any idea what I might have missed or doing wrong here?

**Comment by abhatia1994** [comment]
Have you tried providing the prop directly to MapView? Why are you using ref?

**Comment by Saqib92** [comment]
Still same Error

**Comment by Simon-TechForm** [comment]
I think your approach is overcomplicating things a bit.

The following works for me on both iOS and Android:
```ts
import React, {useState} from 'react';
import {StyleSheet} from 'react-native';
import MapView, {MapTypes} from 'react-native-maps';

export default function App() {
  const [mapType, setMapType] = useState<MapTypes>('standard');
  const toggleMapType = () =>
    setMapType(mapType === 'standard' ? 'satellite' : 'standard');

  return (
    <MapView style={styles.mapView} mapType={mapType} onPress={toggleMapType} />
  );
}

const styles = StyleSheet.create({
  mapView: {
    flex: 1,
  },
});

```

I'm going to close this for now, but if you believe that there's still a bug regarding this, feel free to open a new issue following the issue template.

**Comment by Saliheen** [comment]
> I think your approach is overcomplicating things a bit.
> 
> The following works for me on both iOS and Android:
> 
> ```ts
> import React, {useState} from 'react';
> import {StyleSheet} from 'react-native';
> import MapView, {MapTypes} from 'react-native-maps';
> 
> export default function App() {
>   const [mapType, setMapType] = useState<MapTypes>('standard');
>   const toggleMapType = () =>
>     setMapType(mapType === 'standard' ? 'satellite' : 'standard');
> 
>   return (
>     <MapView style={styles.mapView} mapType={mapType} onPress={toggleMapType} />
>   );
> }
> 
> const styles = StyleSheet.create({
>   mapView: {
>     flex: 1,
>   },
> });
> ```
> 
> I'm going to close this for now, but if you believe that there's still a bug regarding this, feel free to open a new issue following the issue template.

**this works but it re renders the map**

**Comment by Niranjan-A-S** [comment]
Hi... I am having an issue where map is rendering hybrid for the first time but when navigated back and coming to the same screen is not showing the hybrid map. In my case I always need the map to be hybrid. This is observed is physical android devices (Not in emulator or simulator).

    "react-native": "0.76.6",
    "react-native-maps": "1.18.0",
