### ISSUE TITLE
Sliding map up on opening keyboard.

### ISSUE THREAD

**Issue by padas2** [react-native-maps/react-native-maps#3618]
I have a screen where I am rendering the following components:
1. Mapview
2. TextInput 
3. Text                                                                   -- all of them placed in column-wise fashion.

The textInput and Text components are enclosed in a `AvoidKeyboardView` style.
All of these components have `StyleSheet.absoluteFillObject` styling attribute set on them.

When I click on the TextInput component, the keyboard pops up but overlaps over the `TextInput` and `Text` component.
I found that this was because of the `StyleSheet.absoluteFillObject` styling attribute which was set to these components.
Once I removed this attribute, both of these components were moving up on clicking on the TextInput component.

But I found out that the map component was not moving up on opening up the keyboard.
So I removed the `StyleSheet.absoluteFillObject` attribute on the `MapView` component and found that the map disappeared completely. Later I came to know that this attribute is needed to render map.

My question now is, how do I get the MapView to move up along with the rest of the components on opening up the keyboard ?

**Comment by Jdiego06** [comment]
Hello, I have the same problem, could you solve it?

**Comment by abdoutech19** [comment]
Hi, did you find a solution to this?

**Comment by kenanallahverdiev** [comment]
Hi, i have the same problem , please help

**Comment by Jdiego06** [comment]
> Hi, i have the same problem , please help

Hi, could you show me your code, I left the project I was working on a few months ago, but I remember the problem was with the styles.

**Comment by karuzo17** [comment]
This is exactly my issue at the moment on Android with react-native-maps 0.28.1. As soon as the keyboard shows up my complete Map is not responding anymore. Working on it since 3 days, still no solution.

**Comment by Vuong-QT** [comment]
+1 same
