### ISSUE TITLE
<GoogleMaps/GoogleMaps.h> file not found XCODE (RN version ~0.61.4")

### ISSUE THREAD

**Issue by dymyll** [react-native-maps/react-native-maps#3620]
# Question
Hello! 

I  am using googleMaps in my "react-native": "~0.61.4" project. The code runs perfectly fine when running on my device and simulator, however when trying to upload my code to testflight, first Archiving the project( Project -> Archive), the code fails... saying it somehow can't find the <GoogleMaps/GoogleMaps.h> all of a sudden. 
I have searched and searched and can't find a solution. I keep seeing something about Airmaps and some linking that has probably changed on this repo's end, but I have no idea what to do in order to get this to work or what to change. 
Can anyone assist me with this? 
Do I need to import something other than <GoogleMaps/GoogleMaps.h>

**My podfile contains:** 
      rn_maps_path = '../node_modules/react-native-maps'
      pod 'react-native-google-maps', :path => rn_maps_path
      pod 'GoogleMaps'
      pod 'Google-Maps-iOS-Utils'

**My AppDelegate.m contains:** 
#import <GoogleMaps/GoogleMaps.h>
@implementation AppDelegate

@synthesize window = _window;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [GMSServices provideAPIKey: @'MyapiKey'];
...
}

Thanks in Advance!

**Comment by anhquan291** [comment]
Same issue here. Hope someone can help. Thanks

**Comment by BaderSerhan** [comment]
Same here, anybody found a solution?
