### ISSUE TITLE
Map animation occasionally results in glitches on iOS

### ISSUE THREAD

**Issue by deermichel** [react-native-maps/react-native-maps#3621]
# Bug report

## Summary

In our iOS app, we occasionally encounter an annoying glitch when animating between map markers. When slowing down the screen capture, it looks like the map initially jumps to the target position, then jumps back to its initial position and starts the animation.

## Environment info

```bash
react-native: 0.63.3
react: 16.13.1
react-native-maps: 0.27.1
Target Platform: iPhone 11, iOS 14.1, GMaps
```

Last known working:
```bash
react-native: 0.60.5
react: 16.8.6
react-native-maps: 0.25.0
```

## Steps to reproduce

Well, that's a bit tricky because the glitches only occur sometimes (yay). [This](https://gist.github.com/deermichel/bbfcc0b73a271d4932e15b49f362e1ce) is roughly how we interact with MapView. We already tried changing `animateCamera` to `animateToRegion` and reverted the custom markers to the stock ones, but the glitches persist. `setCamera` works as expected - however omitting the animation is not an option in our case. On Android and older/slower iOS devices (e.g. iPhone SE 1st gen, iPhone 7, Simulator on Mac), the glitches don't occur.

Here's a screen capture at 5% speed:

![gif](https://user-images.githubusercontent.com/8472721/99259915-ff27ef00-281a-11eb-8b66-8be308306679.gif)

Describe what you expected to happen:

A smooth animation between the current and the target position.

Describe what you actually happens:

After calling `animateCamera`, before the animation starts, the map initially jumps to the target position and then jumps back to the initial position.

## Reproducible sample code

(see Steps to reproduce)

**Comment by donnes** [comment]
You had fit some solution to this problem?

**Comment by deermichel** [comment]
Unfortunately not, it seems somewhat related to state updates in the background, because when deferring them with a timeout, the glitch occurs less often. Though on the iPhone 12 series, this "workaround" stopped working with the glitch happening as frequently as before.

**Comment by pynner** [comment]
Can confirm same issue on iOS 14.4 && GMaps

## My enviro
react-native: 0.63.3
react: 16.14.0
react-native-maps: 0.27.1
Target Platform: iPhone 11, iOS 14.4, GMaps

**Comment by pynner** [comment]
@donnes @deermichel I just stumbled on a potential workaround!

I slapped an `await mapRef.current?.getCamera()` right before the call to animateCamera - with this change, the map no longer glitches on animation!

Hopefully that works for you guys as well :) Let me know!

**Comment by kimkong88** [comment]
> @donnes @deermichel I just stumbled on a potential workaround!
> 
> I slapped an `await mapRef.current?.getCamera()` right before the call to animateCamera - with this change, the map no longer glitches on animation!
> 
> Hopefully that works for you guys as well :) Let me know!
> 
> edit: stumbled on another workaround thanks to [#2629 (comment)](https://github.com/react-native-maps/react-native-maps/issues/2629#issuecomment-765001139), wrap the call in a `requestAnimationFrame` just like in the comment, seems to also prevent the glitch

This solution worked for me.
