### ISSUE TITLE
How to hide markers outside or inside of a polygon?

### ISSUE THREAD

**Issue by KHAELOM** [react-native-maps/react-native-maps#3624]
I want to show markers that only belong to a polygon and hide all markers outside of it (the blue area) using "PROVIDER_GOOGLE" as MapView. I tried to add an inverted geojson  Polygon with the highest zIndex, but the external markers always appear above the geojson.

Her is what i tried:

```
    <MapView
      provider={PROVIDER_GOOGLE}
      style={Map}
      initialRegion={this.state.region}
      onPress={e => this.onPress(e)}
      customMapStyle={mapViewStyle}
      {...mapOptions}>
     
             <Geojson geojson={this.state.distone} 
                      zIndex= {Infinity}
                      strokeColor="rgba(042,242,242,1)"
                      fillColor="rgba(042,242,242,0.8)"/>
   <MapView/>
```

This is what I got:

![Sans titre](https://user-images.githubusercontent.com/39144037/99584496-524d9d80-29e5-11eb-83a7-5e5794a2651a.png)

can I  make the Geojson component have a higher zIndex than his parent MapView?
can I change the visibility of mapView's "stylers" to "visibility": "on", but only inside or outside a Polygon?
can I make the  MapView only retrieve the features(markers, routes...) that exist inside a polygon?

**Comment by Only-IceSoul** [comment]
PolyUtil.containsLocation -> https://developers.google.com/maps/documentation/android-sdk/utility, Try copying the code to javascript

**Comment by KHAELOM** [comment]
@Only-IceSoul I can't show or hide the markers that are above the blue zone, unless I show or hide all markers in the whole mapview through the stylers, because I don't know how to access and hide each marker one by one. these markers are not generated by me, I have trouble accessing the markers one by one and hide the ones inside the blue area, not checking if some location is inside a polygon

**Comment by msadhikari** [comment]
Is there any update on this issue

**Comment by sgarg15** [comment]
Has this issue been updated yet? I was looking for something similar for my application?

**Comment by Tobjoern** [comment]
Hey, I'd also be interested in a feature, which allows hiding labels within a certain region.
