### ISSUE TITLE
Any way to change IOS  and Android 'showsmylocationbutton' s location ?

### ISSUE THREAD

**Issue by lakjeewa-rightapps** [react-native-maps/react-native-maps#3625]
'showsmylocationbutton'  is located on the top right corner in Android but in IOS it's in the bottom left corner... anyone knows a fix?

**Comment by Only-IceSoul** [comment]
u have to create a button.  -> Mapview.animateToRegion(region)

**Comment by lakjeewa-rightapps** [comment]
> u have to create a button. -> Mapview.animateToRegion(region)

Thanks buddy , I did that ! and works fine.
