### ISSUE TITLE
On iOS, GoogleMaps GOOGLE_PROVIDER map jank when switching on its tab

### ISSUE THREAD

**Issue by pierre-fribourg-context** [react-native-maps/react-native-maps#3628]
# Bug report

## Summary

On iOS, when using react-native-maps with GMaps (using provider={GOOGLE_PROVIDER}) in conjugaison with react-navigation/bottom-tabs, map jank / jump when going back to map tab.
This DOES NOT happen when using Apple Map (remove provider={GOOGLE_PROVIDER})

Issue with GMaps here:
![](https://i.ibb.co/crmmSQr/gmap.gif)

No issue with AppleMap here:
![](https://i.ibb.co/4j4pr9H/applemap.gif)

## Environment info
      react-native: 0.63.0
      react: 16.13.1
      react-native-maps: 0.27.1

`react-native info` output:
```bash
info Fetching system and libraries information...
(node:1499) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 210.54 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Open the app
2. Click on "Other" tab
3. Go back to "Map" tab

Describe what you expected to happen:

1. Map should not jump / jank as it does

Describe what you actually happens:

1. Map jump / jank from the iOS header size (50 "notched" iPhone, 20 "classic" iPhone)

## Reproducible sample code

```javascript
import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

function MapTab() {
  return (
    <View style={{ flex: 1 }}>
      <MapView provider={PROVIDER_GOOGLE} style={{ flex: 1 }} />
    </View>
  );
}

function OtherTab() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Hello</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

function MyTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Map" component={MapTab} />
      <Tab.Screen name="Other" component={OtherTab} />
    </Tab.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <MyTabs />
    </NavigationContainer>
  );
}
```

**Comment by fribourgpierre** [comment]
As a workaround, it's possible to re-render map the full map on each tab focus like:

```javascript
import { useFocusEffect } from '@react-navigation/native';

function MapTab() {
  const [showMap, setShowMap] = useState(false);

  useFocusEffect(
    React.useCallback(() => {
      setShowMap(true);
      return () => setShowMap(false);
    }, []),
  );

  return (
    <View
      style={{
        flex: 1,
      }}
    >
      {showMap && <MapView provider={PROVIDER_GOOGLE} style={{ flex: 1 }} />}
    </View>
  );
}
``

**Comment by ourmaninamsterdam** [comment]
I'm using react-navigation and I get the same jump when the map is shown. If the react-navigation `Screen` that holds `MapView` has a header then I don't get this issue.

**Comment by arunpugahz** [comment]
using `PROVIDER_GOOGLE` on iOS is blocking the UI thread, you can check with the performance monitor from your simulator. Because of this, the application feels laggy, moving across the map is slow and makes navigation jank.

Apple Maps
<img width="399" alt="Screenshot 2021-01-15 at 12 41 15 PM" src="https://user-images.githubusercontent.com/53349433/104693115-1d34a180-572f-11eb-81e0-bf6d3da24e1e.png">
Google Maps
<img width="379" alt="Screenshot 2021-01-15 at 12 41 35 PM" src="https://user-images.githubusercontent.com/53349433/104693081-10b04900-572f-11eb-91fd-41cd03b6f0fe.png">

**Comment by iKronyck** [comment]
I have the same problem @arunpugahz you found any solution to resolve the slowly of the map?

**Comment by ourmaninamsterdam** [comment]
> I'm using react-navigation and I get the same jump when the map is shown. If the react-navigation `Screen` that holds `MapView` has a header then I don't get this issue.

We were able to resolve the Google Maps jumping by enabling [react-native-screens](https://github.com/software-mansion/react-native-screens#usage-with-react-navigation) for react-navigation.

**Comment by skulegirl** [comment]
> > I'm using react-navigation and I get the same jump when the map is shown. If the react-navigation `Screen` that holds `MapView` has a header then I don't get this issue.
> 
> We were able to resolve the Google Maps jumping by enabling [react-native-screens](https://github.com/software-mansion/react-native-screens#usage-with-react-navigation) for react-navigation.

I was having a similar but slightly different issue - every time i was on a tab with a map and panned the map, then moving to other tabs would cause the screen to bounce a bunch. Adding the react-native-screen module fixed it, thanks for the great suggestion!

**Comment by arunpugahz** [comment]
@iKronyck I haven't found a solution yet. Have you tried any other method?
Also, I noticed, this happens only when markers are rendered
Adding `react-native-screens` doesn't help with the UI thread hang on google Maps.

**Comment by littleski** [comment]
We also have the same issue. (GOOGLE_PROVIDER + IOS Combo) What's weird is that :
* With a custom marker dynamic Image (like based on props a different image) -> No Hang, No Lag
* With a custom marker with dynamic Image + Custom static Text (like allways a "hello world" -> No Hang, No Lag.
* With a custom marker with dynamic text (like a name based on props (the prop was always in the custom maker in all 3 cases, just a mapper of rendering the text or not) -> Huge Lags.

As of today, i don't have any explanations (and it feels really surprising).

We already use basic optis (memo, trackviews, etc.).

No issue/No lag on  Android, or if using the default provider. (in all 3 cases). It's really the combo ios + GOOGLE_PROVIDER + some weird cases we haven't been able to identify which causes the issue.

**Comment by ngocphucstyle** [comment]
I solved it by set animationEnabled={false} in MapView
