### ISSUE TITLE
MapView onPress does not work on specific areas [Android only]

### ISSUE THREAD

**Issue by valeriik** [react-native-maps/react-native-maps#3629]
# Bug report

## Summary

**MapView**'s **onPress** callback does not work/fired on specific areas [Android only]. 
See the screenshot where highlighted the areas I am talking about.

![image](https://user-images.githubusercontent.com/24571089/99972785-a1118380-2da7-11eb-9fcf-835cbece847a.png)

If user clicks on any other area on the map, even on the text near the icon/image - everything works fine and I see that **onPress** works as expected.

## Environment info

      react-native: 0.61.2
      react: 16.9.0
      react-native-maps: 0.27.1

      Target Platform: Android 10.0.0 Huawei P30 Lite, Android Emulator with Android 11.0

## Steps to reproduce

Click on any kind of icons/images like those which highlighted on the screenshot above.
Please note, this is **not** my custom markers - this images provided by Google and they comes as map layout.
Also this "not clickable" area a little bit bigger then the image, so if user tap very close to the image  **onPress** also will **not** triggered.

Describe what you expected to happen:

**onPress** works even user clicks on image/icon which represents type of object on Google map.

## Code sample

```
<MapView
...
  onPress={(e) => {
    console.log("onPress...");
  }}
/>
```

**Comment by JavyMB** [comment]
Hi  @valeriik 
Thank you for raising this ticket, however, this may not be a bug :
Those places are called "PointOfInterest". MapView Component contains a different Event called "onPoiClick" to handle places.
check here for [more info](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md) doc  🙈

Use this instead:
```
<MapView
...
  onPress={(e) => {
    console.log("onPress...");
  }}
  onPoiClick={(e) => {
    console.log("on Point Of Interest..."); // <------ add this 
  }}
/>
```

**Comment by rushant11** [comment]
@JavyMB 
I can't select these marked places in the React Native Android map. In iOS, all POI places are selectable and get coordinates.
