### ISSUE TITLE
Cloud based styling

### ISSUE THREAD

**Issue by ryansalatti** [react-native-maps/react-native-maps#3630]
# Question

As you may know, you can use the Google cloud console's cloud based styling tool to create a custom map. The difference here is that Google gives you a map id rather than the JSON for the style. I couldn't seem to find anything in the documentation on where to put in the map id in order to use the custom style. Is this possible to do in react-native-maps? Thank you.

[Google Cloud Based Map Styling](https://developers.google.com/maps/documentation/android-sdk/cloud-based-map-styling)

**Comment by kevin-carlson** [comment]
Hi, yeah I am having same issue. Any update on this? I want to use a cloud-based map id but seems that react-native-maps does not support this. Can react-native-maps add this feature?

**Comment by midrizi** [comment]
+

**Comment by sejeeth11** [comment]
+1

**Comment by cizar** [comment]
+1

**Comment by christopherdro** [comment]
duplicate https://github.com/react-native-maps/react-native-maps/issues/3713
