### ISSUE TITLE
Detox - Support tap() on Markers

### ISSUE THREAD

**Issue by clemblanco** [react-native-maps/react-native-maps#3632]
# Feature request

Calling `.tap()` on `<AIRGoogleMapMarker>` element doesn't tap at the correct x/y coordinate on the screen.

It's always ending up tapping at the top-left corner of the MapView, even though my marker is aligned at the centre of the MapView.

![image](https://user-images.githubusercontent.com/668419/100210506-f9a96380-2f02-11eb-87fe-f919119c4265.png)

## Why it is needed

I want to be able to tap a marker when covering my application with end-to-end tests.

## Possible implementation

N/A

### Code sample

Just passing a `testID` prop to the `<Marker>` element and try to use it to call `.tap()`.

```jsx
import MapView from 'react-native-maps';
// ...

render() {
    return (
        <MapView
            // all_the_props
        >
            <MapView.Marker
                key="some-key"
                identifier="some-identifier"
                coordinate={ { latitude: 51.15, longitude: -0.15} }
                testID="some-test-id"
            >
                <View style={ { backgroundColor: '#ff0000', height: 50, width: 50 } }>
                    <Text>Marker</Text>
                </View>
            </MapView.Marker>
        </MapView>
    );
}
```

See https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#tappoint

**Comment by Saranshmalik** [comment]
This still is an issue. I am not able to tap on a marker on the map. Any workaround for this?

**Comment by Saranshmalik** [comment]
@clemblanco Did you find a solution for this?

**Comment by clemblanco** [comment]
> @clemblanco Did you find a solution for this?

Yes. I'll write a blog article about it. 😉

**Comment by Saranshmalik** [comment]
> > @clemblanco Did you find a solution for this?
> 
> Yes. I'll write a blog article about it. 😉

Great. Waiting for it. Need it to get my automated tests complete 😁👍

**Comment by clemblanco** [comment]
@Saranshmalik https://clem.io/articles/2021-05/react-native-maps-detox-support-tap-on-markers

**Comment by lclarkg18** [comment]
Disappointed that this was closed, would make things much easier if you could just tap a marker
