### ISSUE TITLE
React native maps showsMyLocationButton position

### ISSUE THREAD

**Issue by alakdam07** [react-native-maps/react-native-maps#3633]
I am using Expo react-native-app. I have some local data which I want show in maps. For maps I have used [React-native-maps](https://github.com/react-native-maps/react-native-maps). I successfully pull the data and display in maps by using `Marker`. For user location I have used `expo-location` and `expo-permission`. That works fine. I have used React-native-maps one props called ` showsMyLocationButton`, by default props boolean `false`. when I made it true I can able to see in `IOS Emulator` and i think by default position bottom-right. Android emulator I don't see the button at all. This is [ios][1] image and this [android][2] image. I want to display some data under the maps like a Bottom-Sheet, for that I have used this [package](https://github.com/osdnk/react-native-reanimated-bottom-sheet). As a result it hide the ios' ` showsMyLocationButton`. 

I want to display the user current location Button like [Uber][3]. I tried lots of way to do that but could not able to achieve the goal. I want change the button icon as well but also failed. Really appreciate if someone Help me out. 

I shared my code in **[Snack](https://snack.expo.io/@alakdam/user-current-location-button-psotion)** `Ps. it only works in ios and Android, does not work in web View`.

**This is my code**

    import React, { useState, useEffect, useCallback } from 'react';
    import {
      Dimensions, StatusBar, StyleSheet, Text,
      TextInput, TouchableOpacity, View, Button
    } from 'react-native';
    import Constants from 'expo-constants';
    import Mapview, { Marker, Callout, PROVIDER_GOOGLE } from 'react-native-maps'
    import * as Location from 'expo-location';
    import * as Permissions from 'expo-permissions';
    import datas from './datas.json'
    // You can import from local files
    
    import Animated from 'react-native-reanimated';
    import BottomSheet from 'reanimated-bottom-sheet';
    
    // or any pure javascript modules available in npm
    
    
    export default function App() {
      const sheetRef = React.useRef(null);
      const renderContent = () => (
        <View
          style={{
            backgroundColor: 'white',
            padding: 16,
            height: 450,
          }}
        >
          <Text>Swipe down to close</Text>
    
          <Button
            title="Open Bottom Sheet"
            onPress={() => sheetRef.current.snapTo(0)}
          />
    
        </View>
      );
    
    
    
      const [state, setstate] = useState({
        "latitude": 60.1098678,
        "longitude": 24.7385084,
        "latitudeDelta": 1,
        "longitudeDelta": 1
      });
    
      useEffect(() => {
        _onMapReady();
      }, [_onMapReady]);
    
      const _onMapReady = useCallback(async () => {
        const { status } = await Permissions.askAsync(Permissions.LOCATION);
        if (status !== `granted`) {
          // console.log(`Permisson Denied`);
        }
        const location = await Location.getCurrentPositionAsync({ "accuracy": Location.Accuracy.High });
        setstate({
          ...state,
          "latitude": location.coords.latitude,
          "longitude": location.coords.longitude
        });
      }, [state]);
    
    
    
      return (
        <View style={styles.container}>
          <Mapview
            provider={PROVIDER_GOOGLE}
            initialRegion={state}
            showsIndoors={true}
            showsMyLocationButton={true}
            zoomControlEnabled={true}
            zoomEnabled={true}
            zoomTapEnabled={true}
            showsScale={true}
    
            showsBuildings={true}
            showsUserLocation={true}
            showsCompass={true}
            onMapReady={_onMapReady}
    
            style={styles.mapStyle}>
            {
              datas.data?.map((i) => {
                return (
                  <Marker
                    coordinate={{
                      "latitude": i.location.lat,
                      "longitude": i.location.lng
                    }}
                    animation={true}
                    key={i.id}
    
                  >
                    <Callout
                      style={{ "width": 100, "height": 50 }}>
                      <View>
                        <Text>{i.Property}</Text>
                      </View>
                    </Callout>
                  </Marker>
                );
              })
            }
    
          </Mapview>
    
    
          <BottomSheet
            ref={sheetRef}
            snapPoints={[450, 300, 0]}
            borderRadius={10}
            renderContent={renderContent}
          />
    
        </View>
      );
    }
    const styles = StyleSheet.create({
      container: {
        "flex": 1,
        "alignItems": `center`,
        "justifyContent": `center`
        // position: 'absolute',
    
      },
      mapStyle: {
    
        "height": Dimensions.get(`window`).height,
        "width": Dimensions.get(`window`).width
    
      },
    
    });

  [1]: https://i.stack.imgur.com/TxJ3c.jpg
  [2]: https://i.stack.imgur.com/p4hPG.jpg
  [3]: https://i.stack.imgur.com/uONhJ.png

**Comment by alakdam07** [comment]
mapPadding props is the solution

**Comment by gomathisolai16** [comment]
mapPadding={{top: 20, right: 20, bottom: 550, left: 20}}

**Comment by Zolboo05** [comment]
is there another solution beside mapPadding?

**Comment by ChromeQ** [comment]
The problem with mapPadding is that when centering the map on a selected marker, they are also offset by the same amount. This is unacceptable in my opinion

**Comment by Gugarauj07** [comment]
> The problem with mapPadding is that when centering the map on a selected marker, or animate to lat/lng or just setting a region/bounds, they are also offset by the same amount. Now I need to calculate the offset in lat/lng to get it re-centered, and this is affected by zoom level and screen size/density as 200pixels mean different amounts to different screens and devices, so I have not worked out the calculation yet. It is also different for iOS and Android as the default position of the button is not the same corner of the screen.
> 
> This is unacceptable in my opinion, there should be an easy way to position the button, perhaps I will look to open a PR as it must be easier than the calculation I mentioned above.

have u calculated the offset yet? How could i do it?
