### ISSUE TITLE
How to call function every time the map changes its region to more than a 3 km radius?

### ISSUE THREAD

**Issue by aharon-vish** [react-native-maps/react-native-maps#3636]

**Comment by thebiltheory** [comment]
I would suggest running a check every time the current positions move keeping the old current location stored.
Fire your callback every time the distance between `currentLocation` and `PreviousLocation` is greater than `3km`

I found this website that implements a logic to find the distance between two coords.
https://www.nhc.noaa.gov/gccalc.shtml

<img width="284" alt="Screenshot 2020-11-30 at 14 37 39" src="https://user-images.githubusercontent.com/2975322/100616593-9ca21900-3319-11eb-96e9-4539d590534f.png">

Not sure this has something to do with react-native-maps though. 

Cheers.
