### ISSUE TITLE
error while updating property 'image' of a view managed by airmapmarker

### ISSUE THREAD

**Issue by Ritesh175862** [react-native-maps/react-native-maps#3638]
<img width="402" alt="Screenshot 2020-11-30 at 8 50 10 PM" src="https://user-images.githubusercontent.com/51701629/100629759-ac3c5480-334f-11eb-9e38-fba037b7a3ed.png">

**Comment by rborn** [comment]
@Ritesh175862 please stop opening the same issue without following the template. Please update the issue following the template or I'll close this issue too.
