### ISSUE TITLE
maps goes down automatically on iPhone 12

### ISSUE THREAD

**Issue by AhamedEstiak** [react-native-maps/react-native-maps#3642]
# Bug report

## Summary

GoogleMaps In iPhone 12 goes down automatically and infinitely.

## Environment info

      react-native: 0.61.1
      react: 16.9.0
      react-native-maps: 0.27.1

    Target Platform: 
     - iOS - 14.1
     - iPhone 12 and simulator 

   Using GoogleMaps.

`react-native info` output:

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 57.94 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 19, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```bash
# paste your react: 16.9.0, react-native: 0.61.1, react-native-maps: 0.27.1
```

## Steps to reproduce

Describe what you expected to happen:

1. Expected maps working correctly in all iOS devices. 

Describe what you actually happens:

1. I'm using GoogleMaps and maps go down automatically in iPhone 12 and also simulator.
2. All other iPhone models, iOS versions and also the simulator works fine.

![resize_video_map](https://user-images.githubusercontent.com/10617117/100864254-f47a8480-34bf-11eb-9859-cbbb8896cbad.gif)

**Comment by haris523** [comment]
+1
