### ISSUE TITLE
Error when unmounting while animateToRegion() is still executing

### ISSUE THREAD

**Issue by juergengunz** [react-native-maps/react-native-maps#3645]
I encounter an issue when the MapView is in a route (handled by react-navigation) and a function is called like animateToRegion() and while this is executing the user goes back in the navigation stack, which results in an "Argument 0 (NSNumber) of AIRGoogleMapManager.anmiateToRegion must not be null" error, because the route where the map is mounted, is being unmounted.

How can I prevent this error from happening without knowing how long the anmiateToRegion function is executing?

**Comment by Imperyall** [comment]
same here

**Comment by KazakovVS** [comment]
Same here
