### ISSUE TITLE
Yarn add react-native-maps still does a manual linking and produces error for IOS 14.2

### ISSUE THREAD

**Issue by dymyll** [react-native-maps/react-native-maps#3646]
# Bug report

## Environment info

`react-native info` output:

```bash
      react-native: 0.61.4
      react: 16.9.0
      react-native-maps: 0.27.1
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. Yarn add react-native-maps -E
2. cd ios/ 
3. pod install
4 cd..
5. react-native run-ios

After the error was produced I ran 'react-native unlink react-native-maps' and repeated steps 1 - 5 (removing react-native-maps from package.json).... same result.

Describe what you expected to happen:

Describe what actually happens:
The terminal shows a response that 'react-native-maps was installed using manual linking' however, this is not true. 
Below is an attachment of this error. 

FYI this happened after IOS and Xcode made a recent update (IOS 14.2) as this has never happened prior to this. 

## Reproducible sample code

![Screen Shot 2020-12-06 at 9 31 02 PM](https://user-images.githubusercontent.com/31488060/101308118-b908ee80-380e-11eb-9161-a35f4a5a79f7.png)

**Comment by udayaprakashjayaraman** [comment]
is anyone find solution for this.. still getting this issue in my Mac M1 for iOS in my "react-native": "0.62.2" project

**Comment by pinpong** [comment]
see: https://github.com/react-native-maps/react-native-maps/pull/4417
