### ISSUE TITLE
Show tooltip below marker icon

### ISSUE THREAD

**Issue by raulicious** [react-native-maps/react-native-maps#3648]
Is it possible to open tooltip below marker icon on press? By default it opens on top and I don't see any properties in the docs to change that.

**Comment by raulicious** [comment]
Nevermind, I have figured it out. The solution was the **calloutAnchor** property on Marker.

**Comment by DenysMoro** [comment]
@raulgordejev 
What are you using for tooltip? Are you drawing Marker as tooltip?

**Comment by raulgordejev** [comment]
> @raulgordejev
> What are you using for tooltip? Are you drawing Marker as tooltip?

Have a look at this example: https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/Callouts.js

The tooltip component is called Callout, which needs to be inside the marker as a child.
