### ISSUE TITLE
API Key as parameter

### ISSUE THREAD

**Issue by karlgunst** [react-native-maps/react-native-maps#3649]
It should be possible to set the API Key via a property on MapView

We build enterprise applications and each customer will have their own API Key. We have a configuration layer that brings customer settings into our application from our backend.

**Comment by julienR2** [comment]
I don't see anywhere in Google Maps API where you can setup dynamically the API_KEY 🤔 It seems it was possible in v1 to pass an API_KEY when creating a MapView in the Android SDK but I don't any reference of this anymore in the docs..

It would be an interesting feature, but we might be constrained by the SDK here ? To be confirmed though

**Comment by majirosstefan** [comment]
@karlgunst I also think this is not possible for Android, as Google Docs says, that you need to put the API key in app manifest and therefore it must be in the app in compile time.. However, in iOS, you can set up API key in runtime.

See official docs for Android:
https://developers.google.com/maps/documentation/android-sdk/get-api-key

Stackoverflow responses: 
https://stackoverflow.com/questions/27945759/setting-google-maps-v2-api-key-at-runtime
https://stackoverflow.com/questions/51297404/change-google-maps-api-key-at-run-time-in-android

If you are using only iOS version, you can either fork this repo, or patch it how you want using patch-package https://github.com/ds300/patch-package I think patching is probably better for your enterprise use-case.

Hope it helps.
