### ISSUE TITLE
<GoogleMaps/GoogleMaps.h> not found (RN 0.63)

### ISSUE THREAD

**Issue by Flora-Ht** [react-native-maps/react-native-maps#3656]
# Bug report

## Summary

I'm creating a new project and trying to install react-native-maps and GoogleMaps for iOS. 

## Environment info

`react-native info` output:

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 722.99 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```bash
      react-native: 0.63.3
      react: 16.13.1
      react-native-maps: 0.27.1
```

## Steps to reproduce

1. Create new project
2. Add `use_frameworks!` in the Podfile
3. Add in the Podfile:
```
# react-native-maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils', '~> 3.4.2'
```
4. Remove react-native-maps dependencies (in `node_modules/react-native-maps/react-native-google-maps.podspec`) so you can have the latest version of Google-Maps-iOS-Utils (which supports `use_frameworks!`)
5. `pod install`
6. Build in xcode

**Describe what you expected to happen:**

Build successful 

**Describe what actually happens:**

![Capture d’écran 2020-12-17 à 11 31 55](https://user-images.githubusercontent.com/17475009/102476633-9c18ba80-405b-11eb-9b6e-5edeaa9fc474.png)

**Comment by Queeniie** [comment]
I fixed it by removing everything and starting the install again. 
- `rm -rf node_modules` 
- Add only in the Podfile:
```
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
```
- `pod install`
- In XCode, "add files to {project_name} ..." -> `node_modules/react-native-maps/lib/ios/AirGoogleMaps` and `node_modules/react-native-maps/lib/ios/AirMaps`
- Change import in `{project_name}/AirGoogleMaps/AIRGoogleMapHeatmap.h` to `#import "GMUHeatmapTileLayer.h"`
- And don't forget to add the API Key in your AppDelegate

**Comment by Kenny4444** [comment]
I am currently seeing this using react-native-maps 0.27.1

```
System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.54 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

I tried everything Queenie suggested but I am still getting 'GoogleMaps/GoogleMaps.h' file not found in AppDelegate.m

Any help or ideas on what to try would be appreciated.

Thanks

**Comment by aerionprakash** [comment]
> I fixed it by removing everything and starting the install again.
> 
> * `rm -rf node_modules`
> * Add only in the Podfile:
> 
> ```
> pod 'GoogleMaps'
> pod 'Google-Maps-iOS-Utils'
> ```
> 
> * `pod install`
> * In XCode, "add files to {project_name} ..." -> `node_modules/react-native-maps/lib/ios/AirGoogleMaps` and `node_modules/react-native-maps/lib/ios/AirMaps`
> * Change import in `{project_name}/AirGoogleMaps/AIRGoogleMapHeatmap.h` to `#import "GMUHeatmapTileLayer.h"`
> * And don't forget to add the API Key in your AppDelegate

Thanks. This worked while using !use_frameworks.
I had to check `Copy items if needed`, `Create groups` and Target Name while adding AirGoogleMaps and AirMaps.

**Comment by dhayaljaswantgit** [comment]
> ```
> pod 'GoogleMaps'
> pod 'Google-Maps-iOS-Utils'
> ```
> 
> 
>      
>   
> 
> 
> * `pod install`


I just added below lines in my pod file : 

pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

and then pod install

my error was fixed

**Comment by zaidraddad94** [comment]
all done but i get this now 
```Cannot find 'GMUWeightedLatLng' in scope```

**Comment by smanzini** [comment]
> I am currently seeing this using react-native-maps 0.27.1
> 
> ```
> System:
>     OS: macOS 11.2.2
>     CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>     Memory: 1.54 GB / 16.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
>     Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
>     npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.10.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     Android SDK:
>       API Levels: 23, 29, 30
>       Build Tools: 28.0.3, 29.0.2, 30.0.3
>       System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 4.1 AI-201.8743.12.41.7042882
>     Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_282 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.1 => 17.0.1
>     react-native: 0.63.4 => 0.63.4
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> I tried everything Queenie suggested but I am still getting 'GoogleMaps/GoogleMaps.h' file not found in AppDelegate.m
> 
> Any help or ideas on what to try would be appreciated.
> 
> Thanks

Hello @Kenny4444 I'm currently running "react-native-maps": "0.29.4" and having the same issue after build -> 
AppDelegate.m: 'GoogleMaps/GoogleMaps.h' file not found
"react": "17.0.2",
"react-native": "0.66.3"
macOS 12.0.1 
iOS SDK Facebook 9.3.0
iOS 15.1

platform :ios, '15.0'

target 'xxxx' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GooglePlaces'
  pod 'GoogleSignIn' 

 Are you still experiencing it?
Could anyone help me?
Many thanks
Stefano

**Comment by smanzini** [comment]
Hi @christopherdro thanks for reopening.

I've done all the steps above:
Add only in the Podfile:
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
pod install
In XCode, "add files to {project_name} ..." -> node_modules/react-native-maps/lib/ios/AirGoogleMaps and node_modules/react-native-maps/lib/ios/AirMaps
Change import in {project_name}/AirGoogleMaps/AIRGoogleMapHeatmap.h to #import "GMUHeatmapTileLayer.h"

But receiving again the same error:  AppDelegate.m: 'GoogleMaps/GoogleMaps.h' file not found
Thank you for your help.

**Comment by CCB-cerivera** [comment]
> Hi @christopherdro thanks for reopening.
> 
> I've done all the steps above: Add only in the Podfile: pod 'GoogleMaps' pod 'Google-Maps-iOS-Utils' pod install In XCode, "add files to {project_name} ..." -> node_modules/react-native-maps/lib/ios/AirGoogleMaps and node_modules/react-native-maps/lib/ios/AirMaps Change import in {project_name}/AirGoogleMaps/AIRGoogleMapHeatmap.h to #import "GMUHeatmapTileLayer.h"
> 
> But receiving again the same error: AppDelegate.m: 'GoogleMaps/GoogleMaps.h' file not found Thank you for your help.

Test this in your podfile 

 rn_maps_path = '../node_modules/react-native-maps'

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  
  pod 'GoogleMaps' 
  pod 'Google-Maps-iOS-Utils'

**Comment by smanzini** [comment]
> 

hello @CCB-cerivera many thanks, already solved!

**Comment by danieldanielecki** [comment]
```
# React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```

as described in https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps, but `pod install` was missing in the `ios` directory.

**Comment by TongCong** [comment]
> > 
> 
> hello @CCB-cerivera many thanks, already solved!

What is the specific content of the podfile file? May I take a look at it，Thanks

**Comment by virenradadiya** [comment]
To resolve the issue, add the following lines to your Podfile, then run `pod install`:

```
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
```

If this doesn't work, the issue might be that the `min_ios_version_supported` environment variable is set to a value lower than `13.4`. In that case, change `min_ios_version_supported` to `13.4`, then run `pod install` again.
