### ISSUE TITLE
Default red pin appear when using ‘icon’ prop (iOS only) + video example

### ISSUE THREAD

**Issue by valeriik** [react-native-maps/react-native-maps#3657]
# Bug report

The default red pin appears for a second before the image written in the **icon** prop appears.

The same as https://github.com/react-native-maps/react-native-maps/issues/3418 which was closed without any comments/fixes.

## Summary

Watch the video
![Запись экрана 2020-12-17 в 17 29 11](https://user-images.githubusercontent.com/24571089/102509009-b6b85700-408e-11eb-8cf0-8cb82b8c74f7.gif)

## Environment info

```
react-native: 0.61.2
react: 16.9.0
react-native-maps: 0.27.1

Target Platform: eg: iOS Simulators: iPhone 5s(12.4) / iPhone 11(13.5)
```

**Comment by SArham** [comment]
Same problem with the red default pin which flashes for a fraction of a second. 

I use a custom views where the custom component's image is switched to another when clicked on.

**Comment by Hatko** [comment]
+1

**Comment by FadiAboMsalam** [comment]
same issue any update on this ?

**Comment by Simon-TechForm** [comment]
Focusing the discussion here: #4214
