### ISSUE TITLE
Polygon fill disappears when zooming closer (Android/Google Maps)

### ISSUE THREAD

**Issue by 0handersson0** [react-native-maps/react-native-maps#3660]
# Bug report

## Summary

Polygon fill breaks/disappears on some rare use cases when zooming closer. Seems to only affect Android and Google Maps. 

## Environment info
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "0.27.1"

Target Platform: Android, Nexus 4, API 30

## Steps to reproduce

Run sample code below. Try to zoom out and see that polygon is filled. Zoom closer and watch how the fill gets ignored /disappears. 

![image](https://user-images.githubusercontent.com/72985598/102633899-5d652c00-4151-11eb-8c6e-08e961abff5b.png)

![image](https://user-images.githubusercontent.com/72985598/102633951-6fdf6580-4151-11eb-9a3c-fa4a736b0137.png)

Describe what you expected to happen:

Polygon should remain filled when zooming closer.

Describe what actually happens:

Polygon ignores fill on a closer zoom level. When zooming back out the fill comes back.

## Reproducible sample code

`
export default class Map extends Component
{
    constructor(props) {
        super(props);

        this.cords = [
        {latitude: 51.515104128984014, longitude: -0.10724911330413751},
        {latitude: 51.51509360416017, longitude: -0.10724835349528761},
        {latitude: 51.51465057669589, longitude: -0.1071944167403503},
        {latitude: 51.51460907475539, longitude: -0.10720387744435952},
        {latitude: 51.51458119252253, longitude: -0.10720359244086186},
        {latitude: 51.5145659847235, longitude: -0.10720854690997368},
        {latitude: 51.514565841485364, longitude: -0.10717180048492399},
        {latitude: 51.51456491220439, longitude: -0.10708745271098784},
        {latitude: 51.514537965678876, longitude: -0.10708831081260248},
        {latitude: 51.51453744032382, longitude: -0.10703958890470723},
        {latitude: 51.51453703757894, longitude: -0.10700292532867993},
        {latitude: 51.51453743133726, longitude: -0.1070395892777116},
        {latitude: 51.514537965678876, longitude: -0.10708831081260248},
        {latitude: 51.51453347763805, longitude: -0.10708882843286197},
        {latitude: 51.514515504094135, longitude: -0.10708957383268031},
        {latitude: 51.514453046028315, longitude: -0.10709216409085431},
        {latitude: 51.514452100966935, longitude: -0.10700572734583182},
        {latitude: 51.514451717495874, longitude: -0.10698196236649697},
        {latitude: 51.514451513135725, longitude: -0.1069570369466649},
        {latitude: 51.51453591201073, longitude: -0.10695657758347708},
        {latitude: 51.5145368021658, longitude: -0.10695656948982939},
        {latitude: 51.514536329503905, longitude: -0.10686597655334648},
        {latitude: 51.51456302904545, longitude: -0.1068654168185306},
        {latitude: 51.514582527626416, longitude: -0.10686499721777297},
        {latitude: 51.51457908473389, longitude: -0.10645998468441437},
        {latitude: 51.514575499813624, longitude: -0.1063587833253565},
        {latitude: 51.51458188041884, longitude: -0.1063585186059541},
        {latitude: 51.514579100387664, longitude: -0.1062241778846328},
        {latitude: 51.51444631136468, longitude: -0.1062290965070779},
        {latitude: 51.51444531206065, longitude: -0.1061671923738715},
        {latitude: 51.51445383021261, longitude: -0.10616898642358719},
        {latitude: 51.51478270950928, longitude: -0.10620990711212475},
        {latitude: 51.515085564911736, longitude: -0.10625647696798633},
        {latitude: 51.515099661471034, longitude: -0.10624953601310688},
        {latitude: 51.51521419317838, longitude: -0.10626065252690296},
        {latitude: 51.515179917476836, longitude: -0.10644647315186612},
        {latitude: 51.51516471373927, longitude: -0.10651073678805388},
        {latitude: 51.515156633124356, longitude: -0.10656892531788696},
        {latitude: 51.515147539030075, longitude: -0.10667631819243362},
        {latitude: 51.515104128984014, longitude: -0.10724911330413751}
        ];

    }

    render() {
        return (
            <MapView initialRegion={{latitude: 51.515104128984014,longitude: -0.10724911330413751,latitudeDelta: 0.008,longitudeDelta: 0.008}}>
                {
                    <Polygon strokeWidth={2} fillColor={'red'} coordinates={this.cords} />
                }
            </MapView>
        );
    }
}
`

**Comment by PedroViniciusMelo** [comment]
Any ideias about how to solve it?

**Comment by abhatia1994** [comment]
Provide a key to the Polygon component. I think what is happening is that Map is re-drawing the polygons on every zoom. Giving it a constant key will tell react not to re-draw as the key is the same

**Comment by Kotpes** [comment]
Adding `key` to `<Polygon />` does not solve the issue

**Comment by ombogdanJoinToIt** [comment]
same problem

**Comment by Monisankarnath** [comment]
Did anyone find a solution to this. For me it is happening in android and ios both in v1.20.1
