### ISSUE TITLE
pinColor not rendering same in iOS and android

### ISSUE THREAD

**Issue by iOS321** [react-native-maps/react-native-maps#3667]
# Bug report

## Summary

pinColor not rendering same in iOS and android
## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```
"react": "16.11.0",
 "react-native": "0.62.2",
 "react-native-maps": "^0.27.1",

Target Platform:  iOS 14.2 (Using GoogleMaps)

## Steps to reproduce

1. create a mapview with provider Google 
2. create some markers with with setting pinColor as yellow or orange(tried hex code too )

Describe what you expected to happen:

1. the pin color rendered in android was yellow/orange but in iOS the pin color was different (Screenshots attached for both)

**I need to display yellow and orange pins in one of my apps, it works in android but for iOS the pinColor is not rendering correctly.**

## Reproducible sample code

Here is my code for map creation

```
 <MapView
          ref={map => {global.map = map }}
          style={style}
          provider={PROVIDER_GOOGLE}
          initialRegion={region}
          customMapStyle={MapStyles}
          mapType={mapType}
          onRegionChangeComplete={async(region, bounds) => {
              bounds = await this.mapUpdated(bounds)
              onRegionChangeComplete ? onRegionChangeComplete(region, bounds) : ''
            }
          }
          onMapReady={async(bounds) => {
              bounds = await this.mapUpdated(bounds)
              onMapReady ? onMapReady(bounds) : ""
            }
          }
          scrollEnabled={scrollEnabled}
          pitchEnabled={pitchEnabled}
          zoomEnabled={zoomEnabled}
          rotateEnabled={rotateEnabled}
          markerIcon={markerIcon}
          markerLatLng={markerLatLng}
        >
            {this.markers = []}
            {Object.keys(markerList).length > 0 && markerList.sites.map((marker,index) => (
                this.createMarkerList(marker, index)
            ))}
        </MapView>
```

This is the marker creation:
```
<Marker key={index} 
              coordinate={{latitude: marker.Latitude,longitude: marker.Longitude}}
              ref={_marker => {this[`marker${index}`] = _marker}}
              pinColor='yellow'//or 'orange'
              onPress={() => {
                this.handleMarkerPress(marker, index, marker)
              }}
          >
              <Callout onPress={() => {this.handleCalloutPress(index, marker)}}>
              </Callout>
          </Marker>
```

this is orange pinColor in android
<img width="146" alt="android-orange" src="https://user-images.githubusercontent.com/76558987/103088923-6d2db600-4612-11eb-900a-41ca432d9766.png">

this is yellow pinColor in android
<img width="106" alt="android-yellow" src="https://user-images.githubusercontent.com/76558987/103088926-6f901000-4612-11eb-835a-61b07724af2f.png">

this is orange pinColor in iOS
<img width="120" alt="iOS-orange" src="https://user-images.githubusercontent.com/76558987/103088927-7028a680-4612-11eb-885f-f295535bb61d.png">

this is yellow pinColor in android
<img width="119" alt="iOS-yellow" src="https://user-images.githubusercontent.com/76558987/103088928-70c13d00-4612-11eb-9fdb-c89d126b559d.png">

**Comment by christopherdro** [comment]
Take a look at this issue. https://github.com/react-native-maps/react-native-maps/issues/887 if you want identical markers across platforms you will most likely need to go with an icon or image.
