### ISSUE TITLE
Support google static map?

### ISSUE THREAD

**Issue by muratoner** [react-native-maps/react-native-maps#3668]
Hi,

I want to use this library but i need an answer. This library support google static map?

Thanks in advance

**Comment by abhatia1994** [comment]
I dont think it does. But you can disable all the interactions with the map using its props.

**Comment by muratoner** [comment]
@abhatia1994 i'm using now like as your suggestion. But i think will google static map more performance than disabled interactions mapview.

**Comment by christopherdro** [comment]
Using static maps api will definitely be more performant but is not supported through this lib.
