### ISSUE TITLE
how can i prevent markers from sliding across the screen when my data is changed?

### ISSUE THREAD

**Issue by nimrodbens** [react-native-maps/react-native-maps#3672]
what i want to achieve is for them to scale down and then pop back up in the new location. is it possible? thank you.!

**Comment by arunpugahz** [comment]
Add a unique key to the markers. [#3290](https://github.com/react-native-maps/react-native-maps/issues/3290)

**Comment by nimrodbens** [comment]
but then the markers just cut off when changing position. is there any way i can scale and fade them down when disappearing and scale up when appearing in a different location?

**Comment by arunpugahz** [comment]
Then you should make a custom Animated Marker, and do your fade-in fade-out animation using hooks/LifeCycle methods

**Comment by nimrodbens** [comment]
i've tried that. then it becomes a huge mess. i need to keep a state variable a the `MapView` level because if i want the markers to disappear then i can't just change the coordinates data because if a marker is gone then it's gone so i need to toggle that state var at the map view level wait for them to disappear then change the data. also then i need to toggle it back on for them to appear again. am i missing something? is there any simpler way?

it's a shame there isn't a choice for appear animation like in here:

https://developers.google.com/maps/documentation/ios-sdk/reference/group___marker_animation#ga429e924d2dd9a3684169fb4dfe99ab2a

sliding across the map is very not intuitive for the user for what it means and it can misrepresent the data.
