### ISSUE TITLE
Memory leak with custom marker with Image element (with demo)

### ISSUE THREAD

**Issue by chrisregner** [react-native-maps/react-native-maps#3676]
# Bug report

## Summary

I've discovered a memory leak when using Marker to create a custom markup with Image. Rendering it multiple times (for example rendering new pins as you pan,) causes the memory to steadily grow

## Environment info

"react": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "0.27.1"
Target Platform: iOS - iPhone SE 2020, 14.2 (This is the test device, but issue has been tracked from different iOS devices as well such as iPhone 7)

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.19 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/node
    Yarn: 1.22.4 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 6.72s.

```

## Steps to reproduce

1. Render `<Marker>`s with custom JSX markup/children with React Native `<Image>` tag inside (as opposed to using `image` or `icon` props on `<Marker>` directly)
2. Cause the said `<Marker>`s to render multiple times in large number. For example via rendering new Markers as user pans.

Describe what you expected to happen:

1. Marker should render without increasing the memory

Describe what actually happens:

1. Marker renders and as you render lots of them we can observe the unreleasing increase in the memory

## Reproducible sample code

GitHub repo: https://github.com/chrisregner/rnmmarkerleak

This is the `App.js` file for convenience:

```
import React, { memo, useCallback, useState } from 'react'
import { Image, View } from 'react-native'
import MapView, { Marker } from 'react-native-maps'
import circleWhitePng from './circle-white.png'

let pinId = 0
const App = () => {
  const [pins, setPins] = useState([])
  const handleRegionChangeComplete = useCallback(({
    latitude, longitude, latitudeDelta, longitudeDelta
  }) => {
    const newPins = []
    for (let i = 1; i <= 20; i++) {
      for (let j = 1; j <= 20; j++) {
        const newPin = {
          id: pinId++,
          latitude: latitude - (latitudeDelta / 2) + ((latitudeDelta / 21) * i),
          longitude: longitude  - (longitudeDelta / 2) + ((longitudeDelta / 21) * j),
        }

        newPins.push(newPin)
      }
    }
    setPins(newPins)
  }, [])

  return (
    <View style={{ flex: 1, backgroundColor: 'red' }}>
      <MapView
        provider='google'
        style={{ flex: 1 }}
        mapType='satellite'
        initialRegion={{
          latitude: 32.7767,
          longitude: -96.7970,
          latitudeDelta: .001,
          longitudeDelta: .001,
        }}
        onRegionChangeComplete={handleRegionChangeComplete}
      >
        {pins.map(pin => <CustomMarker key={pin.id} {...pin} />)}
      </MapView>
    </View>
  )
}

export default App

const CustomMarker = memo(coord => {
  const [shouldTrackViewChanges, setShouldTrackViewChanges] = useState(true)

  return (
    <Marker
      coordinate={coord}
      tracksViewChanges={shouldTrackViewChanges}
    >
      <Image
        source={circleWhitePng}
        onLoad={() => {setShouldTrackViewChanges(false)}}
        fadeDuration={0}
      />
    </Marker>
  )
})
```

---

Btw. This is a very important library for lots of developers, thanks to everyone who spent/are spending time for this!

**Comment by gavin-rose** [comment]
Hello! There is another active issue mentioning this that dates all the way back to 2018... crazy! Some of the comments in that thread mention trying to use an Icon component instead of an Image component. Sometime here soon I may look into possible optimizations to try and resolve at least some of this.

**Comment by chrisregner** [comment]
@gavin-rose Actually in my later tests, I discovered that even with the most basic pin (the red one), if rerendered in this manner it doesn't release the memory. I'll try to post the reproduction here later

**Comment by gavin-rose** [comment]
Okay, I would be happy to take a look!

**Comment by chrisregner** [comment]
@gavin-rose Sorry for the delay, I've opened new issue in #3715
