### ISSUE TITLE
Error while updating property 'kmlSrc'

### ISSUE THREAD

**Issue by phybriun** [react-native-maps/react-native-maps#3678]
When I try to render a KML on screen using MapView it shows this error:

![WhatsApp Image 2021-01-07 at 17 07 27](https://user-images.githubusercontent.com/73902721/103939794-17c1d080-510b-11eb-8990-1164b54505af.jpeg)

This is my code:

` <MapView
              onMapReady={() => setLoadingMap(false)}
              loadingEnabled={true}
              style={style.map}
              mapType={'satellite'}
              region={position}
              showsCompass={true}
              kmlSrc="https://linkkml.com.br"
              provider={PROVIDER_GOOGLE}
            />`

My KML:

`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<Style id="estiloAzul">
		<LineStyle>
			<color>64f00014</color>
		</LineStyle>
		<PolyStyle>
			<color>64f00014</color>
		</PolyStyle>
	</Style>
	<Style id="estiloVerde">
		<LineStyle>
			<color>6414f0a0</color>
		</LineStyle>
		<PolyStyle>
			<color>6414f0a0</color>
		</PolyStyle>
	</Style>
	<Style id="estiloVermelho">
		<LineStyle>
			<color>641400ff</color>
		</LineStyle>
		<PolyStyle>
			<color>641400ff</color>
		</PolyStyle>
	</Style>
	<Placemark id="0ADAA777C11813D0A850">
		<name>Q11L01</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD --&gt; #estiloVermelho</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31776155166666,-22.81232653166667,0 -47.31778717888889,-22.81231561472222,0 -47.31779282305556,-22.81231342833333,0 -47.31779861777778,-22.81231161194444,0 -47.31780453527778,-22.812310175,0 -47.31781054638889,-22.81230912416666,0 -47.31781662194444,-22.81230846444444,0 -47.3178227325,-22.81230819944444,0 -47.31782884777778,-22.81230833027778,0 -47.31783493861111,-22.81230885611111,0 -47.317840975,-22.81230977444444,0 -47.3178469275,-22.81231108111111,0 -47.31785276722222,-22.81231276944444,0 -47.31785846555555,-22.81231483138889,0 -47.317863995,-22.81231725666667,0 -47.31786932833333,-22.81232003388888,0 -47.31787444,-22.81232314888889,0 -47.31787930444445,-22.81232658722222,0 -47.31788389861111,-22.81233033138889,0 -47.31788819972222,-22.81233436388889,0 -47.31789218694445,-22.81233866444444,0 -47.31789584083332,-22.8123432125,0 -47.31789914388889,-22.81234798555556,0 -47.31790207944444,-22.81235296083333,0 -47.31790291111111,-22.81235453722222,0 -47.31798745888889,-22.81251713805555,0 -47.31788161527777,-22.81256327194444,0 -47.31776155166666,-22.81232653166667,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="1778B82A511813D0A850">
		<name>Q11L02</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD --&gt; #estiloVerde</description>
		<styleUrl>#estiloVerde</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31766864194444,-22.81236611027778,0 -47.31776155166666,-22.81232653166667,0 -47.31788161527777,-22.81256327194444,0 -47.31778908666666,-22.81260360194445,0 -47.31766864194444,-22.81236611027778,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVerde</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="0DD6A5307D1813D0A851">
		<name>Q11L03</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD --&gt; #estiloAzul</description>
		<styleUrl>#estiloAzul</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31757573222223,-22.81240568888889,0 -47.31766864194444,-22.81236611027778,0 -47.31778908666666,-22.81260360194445,0 -47.31769655805556,-22.81264393194444,0 -47.31757573222223,-22.81240568888889,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloAzul</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="1C8BC2B4461813D0A851">
		<name>Q11L04</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD --&gt; estiloVermelho</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31748282249999,-22.81244526722222,0 -47.31757573222223,-22.81240568888889,0 -47.31769655805556,-22.81264393194444,0 -47.31760402916667,-22.81268426194444,0 -47.31748282249999,-22.81244526722222,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="279EF863F81813D0A851">
		<name>Q11L05</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31738991277778,-22.81248484583333,0 -47.31748282249999,-22.81244526722222,0 -47.31760402916667,-22.81268426194444,0 -47.31751150027777,-22.81272459194444,0 -47.31738991277778,-22.81248484583333,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="3807C081931813D0A851">
		<name>Q11L06</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31729700305556,-22.81252442416667,0 -47.31738991277778,-22.81248484583333,0 -47.31751150027777,-22.81272459194444,0 -47.3174189713889,-22.81276492194445,0 -47.31729700305556,-22.81252442416667,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="41CF742AC31813D0A851">
		<name>Q11L07</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31720409305556,-22.8125640025,0 -47.31729700305556,-22.81252442416667,0 -47.3174189713889,-22.81276492194445,0 -47.31732644249999,-22.81280525166667,0 -47.31720409305556,-22.8125640025,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="098A44AAF51813D0A852">
		<name>Q11L08</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31711118305557,-22.81260358055556,0 -47.31720409305556,-22.8125640025,0 -47.31732644249999,-22.81280525166667,0 -47.31723391361111,-22.81284558138889,0 -47.31711118305557,-22.81260358055556,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="1FEA000D201813D0A852">
		<name>Q11L09</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31701827305555,-22.81264315888889,0 -47.31711118305557,-22.81260358055556,0 -47.31723391361111,-22.81284558138889,0 -47.31714138444444,-22.81288591111111,0 -47.31701827305555,-22.81264315888889,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="2C49FBCBDF1813D0A852">
		<name>Q11L10</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31714138444444,-22.81288591111111,0 -47.31723391361111,-22.81284558138889,0 -47.31735664444444,-22.81308758222222,0 -47.31726449638888,-22.81312866333333,0 -47.31714138444444,-22.81288591111111,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="00209F241D1813D0A853">
		<name>Q11L11</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31723391361111,-22.81284558138889,0 -47.31732644249999,-22.81280525166667,0 -47.3174487925,-22.81304650083334,0 -47.31735664444444,-22.81308758222222,0 -47.31723391361111,-22.81284558138889,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="1EF5B2C56E1813D0A853">
		<name>Q11L12</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31732644249999,-22.81280525166667,0 -47.3174189713889,-22.81276492194445,0 -47.31754094055555,-22.81300541944444,0 -47.3174487925,-22.81304650083334,0 -47.31732644249999,-22.81280525166667,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="216E7073F71813D0A853">
		<name>Q11L13</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.3174189713889,-22.81276492194445,0 -47.31751150027777,-22.81272459194444,0 -47.31763308833333,-22.81296433805555,0 -47.31754094055555,-22.81300541944444,0 -47.3174189713889,-22.81276492194445,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="3022E193F51813D0A853">
		<name>Q11L14</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31751150027777,-22.81272459194444,0 -47.31760402916667,-22.81268426194444,0 -47.31772523611111,-22.81292325666667,0 -47.31763308833333,-22.81296433805555,0 -47.31751150027777,-22.81272459194444,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="46993F3FC61813D0A853">
		<name>Q11L15</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31760402916667,-22.81268426194444,0 -47.31769655805556,-22.81264393194444,0 -47.31781738388889,-22.812882175,0 -47.31772523611111,-22.81292325666667,0 -47.31760402916667,-22.81268426194444,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="09E6A7A5C01813D0A854">
		<name>Q11L16</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31769655805556,-22.81264393194444,0 -47.31778908666666,-22.81260360194445,0 -47.31790953166666,-22.81284109361112,0 -47.31781738388889,-22.812882175,0 -47.31769655805556,-22.81264393194444,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="1526E5C0FD1813D0A854">
		<name>Q11L17</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD</description>
		<styleUrl>#estiloVermelho</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31788161527777,-22.81256327194444,0 -47.31800130361112,-22.81279927138889,0 -47.31799308027778,-22.81280370944445,0 -47.3179877275,-22.81280623194445,0 -47.31790953166666,-22.81284109361112,0 -47.31778908666666,-22.81260360194445,0 -47.31788161527777,-22.81256327194444,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloVermelho</styleUrl>
		</Polygon>
	</Placemark>
	<Placemark id="221C795B241813D0A854">
		<name>Q11L18</name>
		<description>Desenho exportado em 15/12/2020 as 14:10
 via Metrica TOPO CAD --&gt; #estiloAzul</description>
		<styleUrl>#estiloAzul</styleUrl>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-47.31788161527777,-22.81256327194444,0 -47.31798745888889,-22.81251713805555,0 -47.31805068722223,-22.81263601611111,0 -47.31805462777778,-22.81264404555555,0 -47.31805795444444,-22.81265231027778,0 -47.31806065111111,-22.81266077,0 -47.31806270472222,-22.81266938333333,0 -47.318064105,-22.81267810888889,0 -47.31806484555555,-22.81268690333333,0 -47.31806492250001,-22.81269572444445,0 -47.31806433555555,-22.81270452916667,0 -47.3180630875,-22.81271327444444,0 -47.31806118444445,-22.8127219175,0 -47.31805863555556,-22.81273041666666,0 -47.31805545333334,-22.81273873,0 -47.31805165361111,-22.8127468175,0 -47.31804725444444,-22.81275463972222,0 -47.31804227722222,-22.81276215805556,0 -47.31803674666666,-22.81276933638889,0 -47.31803068944444,-22.81277613972222,0 -47.31802413500001,-22.81278253444444,0 -47.31801711527778,-22.81278849,0 -47.31800966444445,-22.81279397694445,0 -47.31800181916667,-22.81279896888889,0 -47.31800130361112,-22.81279927138889,0 -47.31788161527777,-22.81256327194444,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
			<styleUrl>#estiloAzul</styleUrl>
		</Polygon>
	</Placemark>
</Document>
</kml>
`

I really don't know why this error, I really need help!

**Comment by zabojad** [comment]
I'm having the same problem. Did you find a way to display kml data @JaiSaro @phybriun ?

**Comment by zabojad** [comment]
[There](https://github.com/react-native-maps/react-native-maps/blob/3338a960c62cc3c364286433ab98e5cf59435ebf/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L1214), if I replace this:

        LatLng latLng = ((LatLng) placemark.getGeometry().getGeometryObject());

by:
 
        LatLng latLng = ((java.util.ArrayList<java.util.ArrayList<LatLng>>) placemark.getGeometry().getGeometryObject()).get(0).get(0);

It will work...

Now I do not understand exactly where does the error comes from? Is it a bug in this lib or is it due to malformed kml files?

Any help would be appreciated...

**Comment by Haseeba393** [comment]
any response on this?
