### ISSUE TITLE
How to get directions and start moving ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [react-native-maps/react-native-maps#3680]
Hi RNMaps community 

Currently I'm working on RN application using react-native maps and react-native-map-directions

My need is how to set the map in mode Tracking when showing the route directions live like in  Google Maps application

**Comment by christopherdro** [comment]
You would use Mapview.Animated and MapView.Marker.Animated and pass the live coordinates as they change to the animated map marker.

**Comment by UmarFarooqCA** [comment]
Hi @mustapha-ghlissi, I want the same behaviour! how do you implement it?
