### ISSUE TITLE
Marker title not shown on iOS

### ISSUE THREAD

**Issue by dy2-X** [react-native-maps/react-native-maps#3682]
Is this a bug report?
Yes

Have you read issues?
Yes

Environment
Please specify the react, react-native, react-native-maps versions, eg:

react-native: 0.62.2
react: 16.11.0
react-native-maps: 0.27.1
Target Platform: eg: iOS - 13.4 Simulator/iPhone 11

***If your target is iOS, please specify if you are using AppleMaps or GoogleMaps

AppleMaps 
GoogleMaps
(Both)

Expected Behavior

It has to show the title simply like that on Android.

Actual Behavior

It shows a text bubble but it is empty.

**Comment by gavin-rose** [comment]
Hello! Could you provide a code snippet or snack?
