### ISSUE TITLE
Display a component on specific coordinates (Latitude and Longitude)

### ISSUE THREAD

**Issue by ehsanali1992** [react-native-maps/react-native-maps#3684]
Is it possible to display a react native component attached to specific region/bounds? Like we can use <Overlay/> to display an image on specific bounds, but what if we need to draw something on that image (X,Y), we definitely need some component so we display the whole component on that region.

**Comment by christopherdro** [comment]
I think `<Overlay />` should work for this case.  https://github.com/react-native-maps/react-native-maps/blob/master/docs/overlay.md
