### ISSUE TITLE
How to get if marker is in view and user see the marker?

### ISSUE THREAD

**Issue by aharon-vish** [react-native-maps/react-native-maps#3685]
Hey,
I'm getting data from the server according to my location, I need to check if the data is present to the user if not I need to show some message to the user,
how to calculate if the marker inside view?

**Comment by gavin-rose** [comment]
Greetings! Could you clear a couple of things up? Are you trying to find the user's position and display a marker, or are you trying to render a marker, and if the user is near, an action is taken?
