### ISSUE TITLE
iOS cocoapods cannot support use_framework

### ISSUE THREAD

**Issue by GengJian** [react-native-maps/react-native-maps#3686]
# Bug report
After cocoapods install , run failed.

Undefined symbols for architecture armv7:
  "_OBJC_METACLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_METACLASS_$_GMUHeatmapTileLayer in GMUHeatmapTileLayer.o
  "_GMSProject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GMUGridBasedClusterAlgorithm.o
      -[GMUClusterItemQuadItem initWithClusterItem:] in GMUNonHierarchicalDistanceBasedAlgorithm.o
      -[GMUNonHierarchicalDistanceBasedAlgorithm clustersAtZoom:] in GMUNonHierarchicalDistanceBasedAlgorithm.o
      -[GMUWeightedLatLng initWithCoordinate:intensity:] in GMUWeightedLatLng.o
  "_GMSUnproject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GMUGridBasedClusterAlgorithm.o
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in GMUDefaultClusterRenderer.o
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSPolygon", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSMutablePath", referenced from:
      objc-class-ref in GMUGeoJSONParser.o
      objc-class-ref in GMUKMLParser.o
  "_OBJC_CLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_CLASS_$_GMUHeatmapTileLayer in GMUHeatmapTileLayer.o
  "_OBJC_CLASS_$_GMSPolyline", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSGroundOverlay", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in GMUDefaultClusterRenderer.o
      objc-class-ref in GMUGeoJSONParser.o
      objc-class-ref in GMUGeometryRenderer.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Summary
This RN Framework, depend to Google-Maps-iOS-Utils 2.7.0 Version
However,  Google-Maps-iOS-Utils can not support "use_frameworks"
When I need use some swift pod, I have to add "use_frameworks" to podfile
Sadly, Google-Maps-iOS-Utils need upgrade to 3.4.0 + ; but react-native-maps have no updated for a long time
I need to know how to change "Google-Maps-iOS-Utils" Version.....

## Environment info

react-native-cli: 2.0.1
react-native-maps: 0.27.1

Xcode 12.3
cocoapods: 1.10.0
GoogleMaps

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

Describe what you expected to happen:

1. …
![image](https://user-images.githubusercontent.com/13254245/104546928-3cb4c700-5668-11eb-8bed-a3d42af2d14f.png)

2. I have tried like this,but it didn't work
![image](https://user-images.githubusercontent.com/13254245/104546972-55bd7800-5668-11eb-9075-26e12789a9d4.png)

Describe what you actually happens:

1. …
2. …

**Comment by GengJian** [comment]
![image](https://user-images.githubusercontent.com/13254245/104547039-83a2bc80-5668-11eb-80a9-025bb849dee4.png)

It's been locked , I want to use latest cocoa frameworks , such as **GoogleMaps & Google-Maps-iOS-Utils**

**Comment by stianjensen** [comment]
This is the trick to install react-native-maps with GoogleMaps support and use_frameworks! in your Podfile: https://github.com/react-native-maps/react-native-maps/issues/3656#issuecomment-749570974
