### ISSUE TITLE
Change the dragging marker offset

### ISSUE THREAD

**Issue by lardissone** [react-native-maps/react-native-maps#3691]
# Question

I'm not sure how this is called, so I don't know if it's already documented, but I haven't found anything in the docs.

When you start dragging a marker the map moves to make the marker point visible under your finger. 

See this example GIF:
![CleanShot 2021-01-21 at 23 19 11](https://user-images.githubusercontent.com/59826/105437243-7032bb00-5c3f-11eb-8236-c4489946d698.gif)

Is there a way to change how much the marker moves from origin point?

**Comment by MacMeDan** [comment]
You will want to look a the the `MarkerProps` check the `anchor` and `centerOffset` I believe those are what you are looking for.

**Comment by christopherdro** [comment]
@lardissone Have you had a chance to try the suggestion posted above?

**Comment by lardissone** [comment]
@MacMeDan thanks will try when I get a chance

@christopherdro not yet, project is on hold for now

**Comment by Cleversou1983** [comment]
Hei @lardissone ! Any progress on this? I'm facing the same issue... Changing `anchor` and `centerOffset` as @MacMeDan told doesn't fixed the problem... The map still moves on start dragging...

**Comment by lardissone** [comment]
@Cleversou1983 didn't had the chance to try that.
