### ISSUE TITLE
Tapping on new house/lot/building number doesn't fire onPress

### ISSUE THREAD

**Issue by chrisregner** [react-native-maps/react-native-maps#3694]
# Bug report

## Summary

When you tap on house/lot/building number on Google Map (that was released "silently" recently), the supplied onPress event handler doesn't fire.

Here's an article about this new feature. I wasn't able to find an official release note:
https://arstechnica.com/gadgets/2020/12/google-maps-new-community-feed-is-like-a-social-network-for-food/

## Environment info

"react": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "0.27.1"
Target Platform: iOS - iPhone SE 2020, 14.2 (This is the test device, but issue has been tracked from different iOS devices as well such as iPhone 7)

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.19 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/node
    Yarn: 1.22.4 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 6.72s.

```

## Steps to reproduce

1. Use 'hybrid' mapType on MapView
2. Find any part of the map with a house/lot/building number
3. Tap right on the house/lot/building number

Describe what you expected to happen:

1. onPress function should fire when tapping even on the house/lot/building number.

Describe what actually happens:

1. onPress doesn't fire when tapping on house/lot/building number.

## Reproducible sample code

```
import React from 'react'
import MapView from 'react-native-maps'

export default () =>
  <MapView
    provider='google'
    style={{ flex: 1 }}
    mapType='hybrid'
    initialRegion={{
      latitude: 32.7767,
      longitude: -96.7970,
      latitudeDelta: .001,
      longitudeDelta: .001,
    }}
    onPress={() => {
      console.log('PRESSED!')
    }}
  />

```

**Comment by christopherdro** [comment]
I think you may want to use `onPoiClick`

**Comment by chrisregner** [comment]
Thanks @christopherdro. Who anyone who's wondering, I simply had to pass the same handler that I have on `onPress` to `onPoiClick`.
