### ISSUE TITLE
WMSTile renders tiles much bigger on android than iOS - why?

### ISSUE THREAD

**Issue by fewtrees** [react-native-maps/react-native-maps#3696]
# Question

On an iOS app using `<WMSTile>` renders images 

<img width="197" alt="iOS map example" src="https://user-images.githubusercontent.com/2836289/106304374-31aa8b00-6253-11eb-883e-5ac4ea2d5aeb.png">

On an Android app the rendered image is much bigger..

<img width="250" alt="Android map with tile graphic" src="https://user-images.githubusercontent.com/2836289/106303818-7d106980-6252-11eb-98a1-888ca2a745c6.png">

There is NO difference in the tile request, both set tile size to 256..

1. Why the size difference?
2. How could you change it?

Cheers

Rob

**Comment by gavin-rose** [comment]
Hi! Can you send a code snippet or snack?

**Comment by MaRaSu** [comment]
@fewtrees I'm not 100% sure however it looks like iOS is showing tile overlays "pixel to pixel" (ref: [https://developer.apple.com/documentation/mapkit/mktileoverlay/1452108-tilesize?language=objc](url)), while Android is scaling low-res (aka "normal" 256x256 pixel tiles) on high-res displays to the intended physical size on display. This is related to open PR #3740.

Compared to web Javascript map libraries like OpenLayers & Leaflet it seems that both iOS & Android tiled map implementations are very basic and lack many expected features like user defined handling of tile sizes & related scale factors. However I'm new to native mobile development so I might be missing something.

**Comment by fewtrees** [comment]
@MaRaSu I have found that requesting a tile size of 768x768 renders the same on Android as 256x256 does on iOS.. This completely messes up a map server but it does look the same.

**Comment by MaRaSu** [comment]
@fewtrees is your Android screen scale factor 3.0x (ref: [https://developer.android.com/training/multiscreen/screendensities.html](url))? That would explain what happens: iOS renders your tile pixel to pixel without caring about the screen pixel density and Android does what I think is the right default i.e. scales the tile.

I assume that when you say "request" you mean requesting a tile from the WMS tile server.

**Comment by fewtrees** [comment]
@MaRaSu 
The android screen isn't scaled - everything untouched and tried on both an emulator plus physical device..

When you include tileSize property on the <WMSTile> obj set to 768, this gets included in the HTTP request back to the tile server..

i.e.

```
<WMSTile
  urlTemplate={resolvedUrl}
  zIndex={0}
  opacity={1}
  tileSize={768}
  epsgSpec={"EPSG:900913"}
/>
```

**Comment by MaRaSu** [comment]
@fewtrees with screen scale factor I actually meant the screen resolution in terms of pixel density (in reference to Android developer url I pasted to my previous comment, however managed to make it non-clickable...). 

And sorry for missing the request & tileSize thing. I have used mostly slippy aka Google aka OSM aka web maps so I had completely forgotten how different the WMS standard is, my bad ;=)
