### ISSUE TITLE
When i draw the polyline on maps by using GPS coordinates , my directions are getting scattered,

### ISSUE THREAD

**Issue by sejeeth11** [react-native-maps/react-native-maps#3697]
# Bug report

## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

Describe what you actually happens:

1. …
2. …

**Comment by gavin-rose** [comment]
Hello! For anyone to be able to rightly help you, can you go more into depth on your issues and provide a code snippet?
