### ISSUE TITLE
When i draw the polyline on maps by using GPS coordinates , my directions are  showing as zig zag.Can anyone please help to resolve it 

### ISSUE THREAD

**Issue by sejeeth11** [react-native-maps/react-native-maps#3698]
[#](
https://user-images.githubusercontent.com/25919764/106363978-d7442400-6351-11eb-9cc2-80b0f28a935b.png

- [url]([url]([url](### url)))

) Bug report

## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

Describe what you actually happens:

1. …
2. …

**Comment by christopherdro** [comment]
This is an issue with coordinates you are using to draw then poly line. You can use an api like googles snap to roads to to improve the output. https://developers.google.com/maps/documentation/roads/snap
