### ISSUE TITLE
Can't update POLYLINE when update array content

### ISSUE THREAD

**Issue by deccosantos** [react-native-maps/react-native-maps#3703]
Hello, can someone help me how to update polyline when array has a new value pushed to it.
In my case, I push a new value to array every 30 seconds and retrieve data from a url. This value makes the marker change its position and I need to create a new line from old position to new position, but when I add a new value to array no new polyline is created and I looked for a way to reset the polyline but I found nothing in documentation.

So, I need to create a line every time marker updates its position... 

Can someone helps me?

**Comment by gavin-rose** [comment]
Hey! Are you using state to render your marker? Every time the state is updated the component will re-render.

**Comment by deccosantos** [comment]
> Hey! Are you using state to render your marker? Every time the state is updated the component will re-render.

My problem is not with marker... I can already update marker position normally. My problem is with the polyline, I can set a new data to array, but no new render is made

**Comment by gavin-rose** [comment]
Are you using values from state to define your polyline? Even if you are, it is possible the polyline module itself will not trigger a re-render, so perhaps to solve this issue you could use an additional value in state, checking to see if a rerender is required. If it is, you can rerender the polyline and set the value back to false once it has re-rendered.

**Comment by deccosantos** [comment]
ok, but how can I re-render the polyline, can you give me an example? what I'm using is a array.map function to get all position to polyline

**Comment by gavin-rose** [comment]
Can you post a code snippet or a snack?

**Comment by deccosantos** [comment]
My code is like this:

```
const coords = [];

<MapView
          mapRef={map}
          ref={map}
          style={{flex:1, minHeight: '107%', maxWidth: '100%'}}
          initialRegion={{
            latitude: lat,
            longitude: long,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,            
          }}
          showsUserLocation={true}
          showsMyLocationButton={true}
          showsTraffic={true}
          followsUserLocation={true}                                 
          >
          <MapView.Marker coordinate={{latitude: lat, longitude: long}}>
            <Image source={icone} style={{ width: 50, height: 50 }} />
            <MapView.Callout tooltip={true} style={styles.popUp}>            
             ...                                    
            </MapView.Callout>            
          </MapView.Marker> 
          <MapView.Polyline
            ref={polylineRef}            
            strokeWidth={3}
            strokeColor="#000"
            coordinates={coords}                    
          />                                                                                                   
        </MapView> 
```

And I have a function called every 30 seconds that has:
coords.push({latitude: newLat, longitude: newLong})

**Comment by gavin-rose** [comment]
class MapComponent extends React.Component {
    constructor() {
        super();
        state = {
            coords: []
        }
    }
    <MapView
        mapRef={map}
        ref={map}
        style={{ flex: 1, minHeight: '107%', maxWidth: '100%' }}
        initialRegion={{
            latitude: lat,
            longitude: long,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        }}
        showsUserLocation={true}
        showsMyLocationButton={true}
        showsTraffic={true}
        followsUserLocation={true}
    >
    <MapView.Marker coordinate={{ latitude: lat, longitude: long }}>
        <Image source={icone} style={{ width: 50, height: 50 }} />
        <MapView.Callout tooltip={true} style={styles.popUp}>
            ...
        </MapView.Callout>
    </MapView.Marker>
    <MapView.Polyline
        ref={polylineRef}
        strokeWidth={3}
        strokeColor="#000"
        coordinates={this.state.coords}
    />
    </MapView> 
}

And for the function that runs every 30 seconds replace the push function with
this.setState({
        coords: this.state.coords.push([latitude: newLat, longitude: newLong])
});

**Comment by gavin-rose** [comment]
`class MapComponent extends React.Component {
    constructor() {
        super();
        state = {
            coords: []
        }
    }
    render(){
        return(
            <MapView
                mapRef={map}
                ref={map}
                style={{ flex: 1, minHeight: '107%', maxWidth: '100%' }}
                initialRegion={{
                    latitude: lat,
                    longitude: long,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                }}
                showsUserLocation={true}
                showsMyLocationButton={true}
                showsTraffic={true}
                followsUserLocation={true}
            >
            <MapView.Marker coordinate={{ latitude: lat, longitude: long }}>
                <Image source={icone} style={{ width: 50, height: 50 }} />
                <MapView.Callout tooltip={true} style={styles.popUp}>
                    ...
                </MapView.Callout>
            </MapView.Marker>
            <MapView.Polyline
                ref={polylineRef}
                strokeWidth={3}
                strokeColor="#000"
                coordinates={this.state.coords}
            />
            </MapView> 
        );
    }
}`

**Comment by gavin-rose** [comment]
Sorry, troubles this morning with sending something pretty.

**Comment by gavin-rose** [comment]
class MapComponent extends React.Component {
    constructor() {
        super();
        state = {
            coords: []
        }
    }
    render(){
        return(
            <MapView
                mapRef={map}
                ref={map}
                style={{ flex: 1, minHeight: '107%', maxWidth: '100%' }}
                initialRegion={{
                    latitude: lat,
                    longitude: long,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                }}
                showsUserLocation={true}
                showsMyLocationButton={true}
                showsTraffic={true}
                followsUserLocation={true}
            >
            <MapView.Marker coordinate={{ latitude: lat, longitude: long }}>
                <Image source={icone} style={{ width: 50, height: 50 }} />
                <MapView.Callout tooltip={true} style={styles.popUp}>
                    ...
                </MapView.Callout>
            </MapView.Marker>
            <MapView.Polyline
                ref={polylineRef}
                strokeWidth={3}
                strokeColor="#000"
                coordinates={this.state.coords}
            />
            </MapView> 
        );
    }
}

//And for the function that runs every 30 seconds replace the push function with
this.setState({
    coords: this.state.coords.push([latitude: newLat, longitude: newLong])
});

**Comment by deccosantos** [comment]
> class MapComponent extends React.Component {
> constructor() {
> super();
> state = {
> coords: []
> }
> }
> render(){
> return(
> <MapView
> mapRef={map}
> ref={map}
> style={{ flex: 1, minHeight: '107%', maxWidth: '100%' }}
> initialRegion={{
> latitude: lat,
> longitude: long,
> latitudeDelta: 0.0922,
> longitudeDelta: 0.0421,
> }}
> showsUserLocation={true}
> showsMyLocationButton={true}
> showsTraffic={true}
> followsUserLocation={true}
> >
> <MapView.Marker coordinate={{ latitude: lat, longitude: long }}>
> <Image source={icone} style={{ width: 50, height: 50 }} />
> <MapView.Callout tooltip={true} style={styles.popUp}>
> ...
> </MapView.Callout>
> </MapView.Marker>
> <MapView.Polyline
> ref={polylineRef}
> strokeWidth={3}
> strokeColor="#000"
> coordinates={this.state.coords}
> />
> 
> );
> }
> }
> 
> //And for the function that runs every 30 seconds replace the push function with
> this.setState({
> coords: this.state.coords.push([latitude: newLat, longitude: newLong])
> });

Not works, map still not re-rendering polilynes...

**Comment by gavin-rose** [comment]
Do you have the source code posted for me to take a look? Or can you paste in a snippet of the whole file that has this code?

**Comment by deccosantos** [comment]
Hi, thanks for helping but I have already solve the problem. My problem was the timeout function that was not calling the function to add a polyline... but now it's working

**Comment by matlabinfo** [comment]
@deccosantos I'm making the polyline when my coordinate updates while moving, the new coordinate will be added to the existing coordinates array but I'm getting the below error so can you please share your code snippet because I'm stuck with the same issue
![issue](https://user-images.githubusercontent.com/90689562/170818368-e596a4b1-0e87-4d28-82aa-838899befa2e.png)
e
