### ISSUE TITLE
I think its right time to release a new version

### ISSUE THREAD

**Issue by ravirajn22** [react-native-maps/react-native-maps#3706]
55 commits to master since last release v0.27.1.

Managing release issues will be easier with frequent releases.

List out the things to do before release, I will try to help.

**Comment by rborn** [comment]
@ravirajn22 perfect, maybe you can open a PR with Wip:Changelog  and there we add sometihng every time we merge a new PR and once we release we pass it to master ?

@christopherdro thoughts?

**Comment by ravirajn22** [comment]
Change log ready #3707

**Comment by christopherdro** [comment]
V0.28.0 published as a pre release
