### ISSUE TITLE
Can't render markers from firebase

### ISSUE THREAD

**Issue by AOSXAP** [react-native-maps/react-native-maps#3709]
# Question

React native maps, can't render markers from firebase. 

I successfully got the data from firebase but i can't render it on map because of an error :"Error while updating property 'coordinate' of a view managed by AIRMapMaker" .

https://snack.expo.io/@lostxap/issue

Above i attached all the code . I tried multiple ways to make it work but i have no idea if its a mistake of mine or a bug

**Comment by MoSanogo** [comment]
Hi AOSXAP!!!
I have looked at your source code .What I have noticed is that you are trying to render yours markers outside of the <<mapView >> component .That won't work because the component Marker must be a child of the <<mapView>> component.
Your code is like this:
****************************************************Bad****************************************************************
`  <>
//Wrong place to put a marker component
    <>
     {datay.map((i,index) => <Marker key={index} coordinate={{ latitude: i.latitude, longitude: i.longitude }}/>)}

    </>
///
    <MapView
        style={{ flex: 1,minHeight:windowHeight }}
        region={region}
        provider={PROVIDER_GOOGLE}
    >
      ////Good place to put a marker component .
    </MapView>
    </>`
************************************************************************************************************************************
and try to write it like as follows :
******************************************************Right**************************************************************************
`  <>
    <MapView
        style={{ flex: 1,minHeight:windowHeight }}
        region={region}
        provider={PROVIDER_GOOGLE}
    >
    
     {datay.map((i,index) => <Marker key={index} coordinate={{ latitude: i.latitude, longitude: i.longitude }}/>)}

        </MapView>
    </>`
I assure that it will work fine.:-)

**Comment by AOSXAP** [comment]
Thanks a lot for your help , i also managed to do this but i encountered another error , my makers aren't visible on the map. The app has no error but it simply won't show the markers

**Comment by MoSanogo** [comment]
Hi AOXAP
I have tried your code  and udnerstood the problem.
The reason you don't see your markers is that your map is far zoomed on your initial region.
So to see all your makers you should play with the <minZoomLevel > and < maxZoomLevel> props on your the<MapView> component.
I mean as follows:
`
<MapView
minZoomeLevel={// Some number your choose 2? }

maxZoomLevel={// Some number you choose.How about 7?}
Be warn that you cannot zoom in or zoom out more than those levels you choose.
>
///Your makers are right herew.

</MapView>

`

**Comment by AOSXAP** [comment]
I think you got me wrong , i cant see any of the markers on the map and that's because they are not rendered there not because ot the zoom

**Comment by MoSanogo** [comment]
Can I see your code base ?

**Comment by AOSXAP** [comment]
Ok so update , i remade the code ans basically i used an useEffect inside the App and put there the code from gData . then i made datay a useState statement ans updated the data from there. The error was that the array i was getting was empty. After that i got the error "error while updating property ..."(the one mentioned at the start of the issue)

**Comment by MoSanogo** [comment]
I was about to write this :
What I have seen in your initial code base is that you are calling gData() ,which is an effet in your <All> component outside of useEffect and depending whether gData returns an promise or not you should adjust your effect accordingly.
Initially you have written your <All> like this:
`  // const datay = gData();

  // const windowHeight = Dimensions.get('window').height;
  //     const [region, setRegion] = useState({
  //     latitude: 47.7823811,
  //     longitude: 22.8647819,
  //     latitudeDelta: 0.009,
  //     longitudeDelta: 0.009,
  //   });
  // console.log(datay);`
I would write my code like this 
` const windowHeight = Dimensions.get('window').height;
      const [region, setRegion] = useState({
      latitude: 47.7823811,
      longitude: 22.8647819,
      latitudeDelta: 0.009,
      longitudeDelta: 0.009,
    });
    const[data,setData]=useState([])
  console.log(datay);
      useEffect(()=>{
   const datay = gData() ;
   setData(data)


             },[])
`

**Comment by AOSXAP** [comment]
That still would give a few errors(i tried) , the main problem is that error i get : " Error while updating property 'coordinate' of a view managed by AIRMapMaker". The array would look like this [{longitude:.., latitude:...,time:... , data: ...},{},{},{}], where all objects have identical data

**Comment by MoSanogo** [comment]
Okay !!
Can you rework  your effect function gData and return only an array of the shape :
let arrData=[{latitude:number,longitude:number},{latitude:number,longitude:number},{latitude:number,longitude:number},{latitude:number,longitude:number}]
I may be wrong but I do believe that your error getting from the effection function gData.

**Comment by MoSanogo** [comment]
you read this docs to retrieve your data.

https://firebase.google.com/docs/database/web/read-and-write

**Comment by AOSXAP** [comment]
Thanks for help , i fixed all the above but issue is still on . Updated the snack : https://snack.expo.io/@lostxap/issue . I still get the error :"Error while updating property 'coordinate' of a view managed by AIRMapMaker"

**Comment by MoSanogo** [comment]
Try this and check again if you are getting the right data from firebase calls.

`return(
    <>
    <MapView
        minZoomeLevel={1}
        maxZoomLevel = {7}
        style={{ flex: 1,minHeight:windowHeight }}
        provider={PROVIDER_GOOGLE}
       //Where is your initialRegion?
    >
   //Let us rewrite your codes in a very defensive manner.
   //Your datay may be empty when the your component first renders on the screen.
   //So we need to check that .
  {(datay.length !==0)?datay.map((i,index) => <Marker key={index} coordinate={{ latitude: i.latitude, longitude: i.longitude }}/>): <Text>Hello wolrd</Text>   }
      
    </MapView>
    </>
  )`

**Comment by AOSXAP** [comment]
It's still not working. Check out https://snack.expo.io/@lostxap/issue , i let there my db auth so it will be easier if you are trying to fix it , but idk i feel like its a bug at this point

**Comment by MoSanogo** [comment]
it is all right now .
I have understood the error.
When you get your data from firebase ,the latitude and longitude are given to you as string and you have convert them to number (float ).

But before all for your security sake ,please change your firebase credentials and I am begging you to do so.
Here are the good code .
`function All(){
  const [datay,setDatay] =useState([]);
  const windowHeight = Dimensions.get('window').height;
      
  useEffect(()=>{
      var data = firebase.database().ref('locations/');
      data.once('value', (snapshot) => {

        const values=Object.values(snapshot.val()).map(value=>{
          return {
            data:value.data,
            latitude:parseFloat(value.latitude),
            longitude:parseFloat(value.longitude),
          }
          
        })
         
  setDatay(datay)

        // setDatay(Object.values(snapshot.val()));

      });

  },[])
`

Please,change your firebase credentials .

**Comment by AOSXAP** [comment]
Ohhhh thx a lot man , you saved my life. ofc i ll change credentials , but i never tought that it would be such a big problem to use a string instead of a float, i tought it had an auto-parser or it would simply allow strings. Anyways thx a lot !

**Comment by MoSanogo** [comment]
You can also add your state <datay> to the dependence array of ` useEffect(()=>{
//your code .................
},[datay])`
you welcome ,man . :-)

**Comment by omartahaineh** [comment]
Hello @MoSanogo 
I have a similar problem, the map is displayed, but its not showing the markers.
here is my code:
```
import React, { useEffect, useState, useRef } from 'react'
import { FlatList, Keyboard, Text, TextInput, TouchableOpacity, View, Dimensions} from 'react-native'
import styles from './styles';
import MapView from 'react-native-maps';
import { Marker } from "react-native-maps";
import { getDatabase, ref, onValue } from 'firebase/database';
import { firebase} from '../../firebase/config'
import { app} from '../../firebase/config'
  
  
  export default function HomeScreen(props) {
  
  const db = getDatabase();
  
  const f1 = ref(db, '/zones');
  
  const [count, setCount] = useState([]);
  
  useEffect(() => {
   return onValue(f1, (snapshot) => {
  let data = Object.values(snapshot.val()).map(value=>{
      return {

        latitude:parseFloat(value.latitude),
        longitude:parseFloat(value.longitude),
      }}
);
  let markers = {...data};
  setCount(markers);
  
  }
  );
  },[]);

  const uniRegion = {
    latitude: 25.2863943,
    longitude: 55.4749801,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }
  const Load = () =>{return <Text>loading</Text>}
console.log(count);

  return (
    <View style={styles.container}>
    <MapView style={styles.map} region={uniRegion}        showsUserLocation={true} >
    {count.length >0?count.map((i, index) => ( <Marker key={index} coordinate={{ latitude: parsFloat(i.latitude), longitude: parsFloat(i.longitude)}}/>)): <Load/> }
      

    </MapView >
    </View>
    );
    }



  
```
