### ISSUE TITLE
Default params at mapview.md for showsTraffic incorrect

### ISSUE THREAD

**Issue by venkatr21** [react-native-maps/react-native-maps#3714]
The default parameter for the `showsTraffic` prop for `<MapView>` in the file [mapview.md](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md) is incorrect. The default is given to be true, but it actually is false.
![image](https://user-images.githubusercontent.com/50309787/107906934-60757080-6f78-11eb-9223-8f6bdba63b52.png)
Is it okay if i create a PR for this issue with updated doc?

**Comment by christopherdro** [comment]
A PR would be great. Can you confirm this is the case across both iOS and Android?

**Comment by venkatr21** [comment]
@christopherdro Yep it is, its the same for iOS and Android. I'll send in a PR on this!
