### ISSUE TITLE
Memory increase when rerendering Markers

### ISSUE THREAD

**Issue by chrisregner** [react-native-maps/react-native-maps#3715]
# Bug report

## Summary

I've discovered a memory leak when using Marker. Rendering it multiple times (for example rendering new pins as you pan) causes the memory to steadily grow

## Environment info

"react": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "0.27.1"
Target Platform: iOS - iPhone SE 2020, 14.2 (This is the test device, but issue has been tracked from different iOS devices as well such as iPhone 7)

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.19 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/node
    Yarn: 1.22.4 - /var/folders/7j/fccclg610xv_zh622pl16xbm0000gn/T/yarn--1609857632570-0.38419182065695345/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 6.72s.

```

## Steps to reproduce

1. Render lots of `<Marker>`s multiple times

Describe what you expected to happen:

1. Markers should render without increasing the memory

Describe what actually happens:

1. As the markers rerender there is a steady increase in the memory

## Reproducible sample code

GitHub repo: https://github.com/chrisregner/rnmmarkerleak

This is the `App.js` file for convenience:

```
import React, { useCallback, useState } from 'react'
import { View } from 'react-native'
import MapView, { Marker } from 'react-native-maps'

let pinId = 0
const App = () => {
  const [pins, setPins] = useState([])
  const handleRegionChangeComplete = useCallback(({
    latitude, longitude, latitudeDelta, longitudeDelta
  }) => {
    const newPins = []
    for (let i = 1; i <= 20; i++) {
      for (let j = 1; j <= 20; j++) {
        const newPin = {
          id: pinId++,
          latitude: latitude - (latitudeDelta / 2) + ((latitudeDelta / 21) * i),
          longitude: longitude  - (longitudeDelta / 2) + ((longitudeDelta / 21) * j),
        }

        newPins.push(newPin)
      }
    }
    setPins(newPins)
  }, [])

  return (
    <View style={{ flex: 1, backgroundColor: 'red', borderColor: '#ffff00', borderWidth: 2 }}>
      <MapView
        provider='google'
        style={{ flex: 1 }}
        mapType='satellite'
        initialRegion={{
          latitude: 32.7767,
          longitude: -96.7970,
          latitudeDelta: .001,
          longitudeDelta: .001,
        }}
        onRegionChangeComplete={handleRegionChangeComplete}
      >
        {pins.map(pin => <Marker key={pin.id} coordinate={pin} />)}
      </MapView>
    </View>
  )
}

export default App
```

---

Btw. This is a very important library for lots of developers, thanks to everyone who spent/are spending time for this!

**Comment by chrisregner** [comment]
For anyone who's having the same issues. I just reused the markers by using the index as ID and always rendering a constant number of markers at a time (using filler invisible markers if necessary. Also had to do a bunch of optimizations to make up for using this index-as-key antipattern).

Optimizations had to do include toggling `trackViewChanges` as updates come and reordering markers data so that the same entities (entities with the same ID) end up in same array index across any 2 subsequent updates.

**Comment by webraptor** [comment]
Closing a serious issue and applying a workaround is not nice and professional at all. 
Have you considered that there's a lot of apps using this in production with heavily optimised code and there's hundreds of app crashes because of this issue?

**Comment by tharakanwn2014** [comment]
I was having the same issue and I was able to stop memory increasing continuously using the same ids as you mentioned. But each rendering markers are not steady and gives like scattering effect. did you able to solve that issue. Please share your code or the steps on how you did that.

**Comment by tharakanwn2014** [comment]
Assigning the **same ID** to the **same point** when each rendering will **prevent memory increase** as well as **markers scattering**.

**Comment by maximantipin** [comment]
Having similar issues with markers & poly lines -- I have > 1000 markers and > 300K poly lines that I need to show/hide depending on the section of the map the user is looking at.

The RAM continues to increase as you pan around the map and markers & poly lines are rendered and removed.

**Comment by tharakanwn2014** [comment]
try to maintain a constant number of markers all the time and assign the same IDs to them.

**Comment by Derewith** [comment]
@tharakanwn2014 can you provide an example to close this issue ?

**Comment by sknutsonsf** [comment]
I'm having a similar issue, but in my test case the number of markers and polylines remains constant after the 4'th re-render (there are separate server calls to get the polylines and markers).

Is there any chance this issue can be fixed?

**Comment by jackimatin** [comment]
same issue...
any solution ?

**Comment by Derewith** [comment]
@chrisregner can you provide an example to close this issue?

**Comment by gregoryharkins** [comment]
This issue is happening without a single pin being rendered.

**Comment by Simon-TechForm** [comment]
I'm struggling to understand how one would expect the ram usage to stay constant with the reproducible code put forth by the author. The code is creating 400 new markers each time the map region changes, with 400 unique id's (not only unique for the 400 new markers, but for each marker ever rendered). This is bound to increase memory usage :) If I'm missing something obvious, please let me know, and I'll re-open :)

**Comment by z0penc0** [comment]
Any news on this? arrived to this report because of excessive battery usage and phone overheating, allocation keeps GC running constantly

**Comment by theonetheycallneo** [comment]
Here's a decent article explaining the technique:

https://itnext.io/performant-custom-map-markers-for-react-native-maps-ddc8d5a1eeb0

**Comment by andyhbg** [comment]
We have the same problem. We have also tried to create new project
`npx create-expo-app my-app`
and only added react-native-maps. The problem still exists, even with a blank map without markers. 
Although the problem is bigger with markers

Has anyone found a working solution?

**Comment by mdghousesaqlain** [comment]
Anyone can provide the sample code or solution to this, as I have encountered this bug is happening.

**Comment by tomas-shar** [comment]
@puelocesar does that fix apply to  Apple Maps too? struggling with exactly the same error on 1.24.2

**Comment by puelocesar** [comment]
> [@puelocesar](https://github.com/puelocesar) does that fix apply to Apple Maps too? struggling with exactly the same error on 1.24.2

Definitely not, but if you look at the patch I wrote, it's fairly easy to apply to the Apple maps code
