### ISSUE TITLE
Specify units for altitude and zoom for animateCamera method

### ISSUE THREAD

**Issue by SKempin** [react-native-maps/react-native-maps#3717]
# Feature request

The units of scale for `altitude` and `zoom` on the `animateCamera` method are notably different but this is not currently covered in the docs. Examples should be provided in the comments, with the min/max units possible for each.

## Why it is needed

It is unclear what these units are, and the min and max of them. It could easily be misinterpreted that they share the same unit scale. I am unsure what the min/max units of `zoom` for Google Maps API are. 

### Code sample

```
   // Only on iOS MapKit, in meters. The property is ignored by Google Maps. Scale min: 0, max: xxx
   altitude: number,

   // Only when using Google Maps. Scale min: 0, max: 30. 
   zoom: number
```

**Comment by marioacero** [comment]
Interested on this solution....
