### ISSUE TITLE
WMSTile is not removed from MapView (iOS, MapKit)

### ISSUE THREAD

**Issue by MaRaSu** [react-native-maps/react-native-maps#3720]
# Bug report

## Summary

WMSTile is not removed from MapView in iOS with AirMap provider, but keeps on rendering after it is removed from React Native "DOM". This issue is possibly the same that was reported in #2866.

I took a look at the code and it looks like the problem is at libs/ios/AirMaps/AIRMap.m: WMSTile is missing in the removeReactSubview-method. Looking elsewhere at the code my understanding is that WMSTile is only a variant of URLTile with a slightly different way of calculating Tile URLs and that's how I found this discrepancy in the codebase between URLTile vs. WMSTile.

I started with react native 2 weeks ago, have never done Objective-C nor native ios development, otherwise I would have rather filed a PR rather than just reported the issue.

## Environment info

react-native: (Expo SDK40)
react: 16.13.1
react-native-maps: 0.27.1

## Steps to reproduce

This is minimal steps and no supporting code. I'm happy to provide more if needed, but rather assume that the possible location of error I commented above is enough to fix this.

1. Instantiate WMSTile inside of MapView: verify it's rendering ok (iOS, MapKit as provider)
2. Remove WMSTile from inside the MapView
3. Test the same code with URLTile instead of WMSTile

Describe what you expected to happen:

1. WMSTile rendering to stop when removed from MapView

Describe what you actually happens:

1. WMSTile keeps on rendering even after removal from MapView
2. Same code tested with URLTile: once removed from MapView the rendering stops as expected

## Reproducible sample code

Happy to provide this if needed. Do not think it adds value unless my guess on the place of error in the code is not correct.

**Comment by christopherdro** [comment]
@MaRaSu I think you're on the right track here. Could you try fixing the discrepancy and submit a pull request for others to review/test?

**Comment by MaRaSu** [comment]
@christopherdro I’m a total noob with react native and have absolutely zero experience with native code, but I guess this is not a bad bug fix to start and convert my complaint to contribution.
