### ISSUE TITLE
AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by softopia-tech** [react-native-maps/react-native-maps#3721]
I am trying to implement animated marker on map but getting **AnimatedValue: Attempting to set value to undefined**
error whenever i use coordinates wrapped in AnimatedRegion like this

`coordinate: new AnimatedRegion({
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: 0,
        longitudeDelta: 0
      })`

to make sure that i am not doing anything wrong i copied this example code 

https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/AnimatedMarkers.js

but the issue still showing in this code too. I haven't found any related issue anywhere in issues section and also not on stackoverflow 

Please check the screenshot here https://ibb.co/bb3Qcdb

Versions:
"react-native": "0.63.2",
"react-native-maps": "0.27.1",

**Comment by jasonmichaels** [comment]
@softopia-tech Do you have an example repo or something to look at? Based on your first example line of code, it's unclear where you're trying to set that.  In the example, this state's `coordinate` property is set as an initial value of `AnimatedRegion`; once `coordinate` is initially set as an `AnimatedRegion`, you shouldn't have to redeclare it as an `AnimatedRegion`. Look at the `animate` method (the button's `onPress` callback) and the `Marker.Animated` JSX. The `Marker.Animated` has a `ref` to `this.marker`, and the coordinate prop should be the state's `AnimatedRegion` values. When the button is pressed, the example modifies the coordinates arbitrarily, and updates differently for iOS and Android.

**Comment by softopia-tech** [comment]
> @softopia-tech Do you have an example repo or something to look at? Based on your first example line of code, it's unclear where you're trying to set that. In the example, this state's `coordinate` property is set as an initial value of `AnimatedRegion`; once `coordinate` is initially set as an `AnimatedRegion`, you shouldn't have to redeclare it as an `AnimatedRegion`. Look at the `animate` method (the button's `onPress` callback) and the `Marker.Animated` JSX. The `Marker.Animated` has a `ref` to `this.marker`, and the coordinate prop should be the state's `AnimatedRegion` values. When the button is pressed, the example modifies the coordinates arbitrarily, and updates differently for iOS and Android.

The issue got fixed after adding `latitudeDelta` and `longitudeDelta` in the `newCoordinates` Object (Check image) 
[https://ibb.co/MBHsjhX](url)

`const newCoordinate = {`
           ` latitude: LATITUDE + (Math.random() - 0.5) * (LATITUDE_DELTA / 2),`
      `longitude: LONGITUDE + (Math.random() - 0.5) * (LONGITUDE_DELTA / 2),`
      `latitudeDelta: LATITUDE_DELTA,`
    `longitudeDelta: LONGITUDE_DELTA,`
   ` };`
