### ISSUE TITLE
Add Huawei MapKit to support Huawei phones

### ISSUE THREAD

**Issue by JithenAnand** [react-native-maps/react-native-maps#3724]
# Feature request

 Add Huawei MapKit to support Huawei phones. Current react-native-maps only supports IOS and ANDROID.

## Why it is needed

Google maps kit is no longer working for newer huawei phone version.

## Possible implementation

 if possible to add implementation of huawei and gms on same repo

**Comment by salah-ghanim** [comment]
@JithenAnand can you do a pull request for this ?

**Comment by liho00** [comment]
why is this issues closed, is huawei mapkit is supported now? but i still not able to use it with huawei phone, could someone reopen this issue please.

**Comment by ionutmiftode** [comment]
any update on this?

**Comment by rosnaib11** [comment]
+1
