### ISSUE TITLE
Polygons rendering

### ISSUE THREAD

**Issue by angeltodorovyara** [react-native-maps/react-native-maps#3734]
A lot of polygons rendering

I'm using React Native with Expo and I currently want to render roughly about 3000 polygons but the app is vary laggy on zoom. Is that normal behaviour that react-native-maps just cannot take the load or there is a way to optimise it? Thank you.
I'm using Google maps for both android and iOS via GOOGLE_PROVIDER
And is there something similar to leaflet-react but for Native apps. I know that I can use it inside a WebView but what's the point of react native then.

**Comment by fattomhk** [comment]
For the number of polygons, I found that the number of coordinates impact on polygons first rendering. If you apply Ramer–Douglas–Peucker line simplification on the coordinates (with lng delta, maybe), it would help a lot on first rendering. I haven't tried the max. num. of polygons, would it be laggy with 3000 squares / triangles (3 or 4 coordinates)?

Maybe it is my bias, most of the time laggy comes from markers.

**Comment by WathikAhmed** [comment]
How do I generate these polygons dynamically?
