### ISSUE TITLE
How to unsubscribe from the onUserLocationChange? It is continuously accumulating when navigate to other screens

### ISSUE THREAD

**Issue by tharakanwn2014** [react-native-maps/react-native-maps#3736]
# Question

onUserLocationChange is continuously calling multiple times and accumulating when navigating to other screens. Is there any way to unsubscribe from onUserLocationChange when navigating to other screens?

[Sat Mar 06 2021 11:08:27.230]  LOG      hit change
[Sat Mar 06 2021 11:08:27.102]  LOG      hit change
[Sat Mar 06 2021 11:08:27.234]  LOG      hit change
[Sat Mar 06 2021 11:08:27.350]  LOG      hit change
[Sat Mar 06 2021 11:08:27.373]  LOG      hit change
[Sat Mar 06 2021 11:08:27.404]  LOG      hit change
[Sat Mar 06 2021 11:08:27.537]  LOG      hit change
[Sat Mar 06 2021 11:08:27.651]  LOG      hit change
[Sat Mar 06 2021 11:08:27.671]  LOG      hit change
[Sat Mar 06 2021 11:08:27.701]  LOG      hit change
[Sat Mar 06 2021 11:08:27.787]  LOG      hit change
[Sat Mar 06 2021 11:08:27.918]  LOG      hit change
[Sat Mar 06 2021 11:08:28.170]  LOG      hit change
[Sat Mar 06 2021 11:08:28.430]  LOG      hit change
[Sat Mar 06 2021 11:08:28.169]  LOG      hit change
[Sat Mar 06 2021 11:08:28.199]  LOG      hit change
[Sat Mar 06 2021 11:08:28.301]  LOG      hit change
[Sat Mar 06 2021 11:08:28.324]  LOG      hit change
[Sat Mar 06 2021 11:08:28.400]  LOG      hit change
[Sat Mar 06 2021 11:08:28.469]  LOG      hit change
[Sat Mar 06 2021 11:08:28.554]  LOG      hit change
[Sat Mar 06 2021 11:08:28.689]  LOG      hit change
[Sat Mar 06 2021 11:08:28.712]  LOG      hit change
[Sat Mar 06 2021 11:08:28.871]  LOG      hit change
[Sat Mar 06 2021 11:08:28.891]  LOG      hit change
[Sat Mar 06 2021 11:08:28.988]  LOG      hit change

**Comment by christopherdro** [comment]
You could try to render the Map only if the screen is focused.

**Comment by tharakanwn2014** [comment]
@christopherdro it didn't work. This happens when I navigate to other screens(except the home screen) from the map screen. When I navigate back to the home screen it stops firing onUserLocationChange. Due to that, I remove all the navigations from the map screen for now.

**Comment by randomprogramming** [comment]
You could use the `useIsFocused` hook to check if your map screen is active or not and remove the `onUserLocationChange` prop based on that.

```
  useEffect(() => {
    if (isFocused) {
      // enable tracking
    } else {
      // disable tracking
    }
  }, [isFocused]);
```
