### ISSUE TITLE
Filter marker those only comes in boundary.

### ISSUE THREAD

**Issue by priyanka-Sadh** [react-native-maps/react-native-maps#3741]
I have an array of markers. I don't want want display all together at same time, rather I want to filter all array marker based on if any comes inside the Bound or not(user display screen), I get the map region bound from here (https://github.com/react-native-maps/react-native-maps/issues/356)

In need of a filter feature now.

**Comment by Priyankamindcrew** [comment]
Any update on above ?

**Comment by christopherdro** [comment]
There is no built-in feature to handle this but you can use `getMapBoundaries` then write some logic to determine whether your marker coordinates inside that boundary. 

https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#methods

**Comment by Priyankamindcrew** [comment]
Hey @christopherdro I am in need of that logic which check if marker location is present inside the boundaries or not, If you can help me on this would be great :)

**Comment by edi** [comment]
> Hey @christopherdro I am in need of that logic which check if marker location is present inside the boundaries or not, If you can help me on this would be great :)

You can simply get the map boundaries with that method, and then filter all markers within that boundary. It's not that hard.
