### ISSUE TITLE
Overaly bearing does not work on iPhone.

### ISSUE THREAD

**Issue by wjjang-jjass** [react-native-maps/react-native-maps#3750]
# Bug report

## Summary
When running the 'ImageOverlayWithBearing' example in ios, the image does not rotate.

## Environment info
 

```bash
#  react-native: 0.63.4, react: 16.13.1, react-native-maps: 0.28.0, Target Platform: IOS: 14.4/ iPhone 7 Plus

## Steps to reproduce
1. Run 'ImageOverlayWithBearing' example in ios.
2. The image is not rotated.

**Comment by tez123z** [comment]
Having the same issue - doesn't seem to work with image overlay

**Comment by dan-os** [comment]
Bump. Our team is also running into this issue. Has anyone investigated into why this may occur? Or managed to fix it?

**Comment by Simon-TechForm** [comment]
The `bearing` prop is for Google Maps only. This is actually already in the docs, but a syntax error causes the information not show.
