### ISSUE TITLE
Display area and distance on polygon and polyline

### ISSUE THREAD

**Issue by nobnisai** [react-native-maps/react-native-maps#3753]
Is there any way we can display the calculated area and distance on polygon and polyline? I am developing the field area measure, but cannot find a way to display the area nor distance.

**Comment by christopherdro** [comment]
You should be able to calculate the distance using the [Haversine Formula](https://en.wikipedia.org/wiki/Haversine_formula). I see a few posts on Stackoverflow for calculating the area of a polygon. Best to take a look there.

**Comment by nobnisai** [comment]
I think you misunderstand what I asked. I would like to know how to show the calculated distance/area on the polygon not how to calculate.

**Comment by nobnisai** [comment]
I think you misunderstand what I asked. I would like to know how to show the calculated distance/area on the polygon not how to calculate.

**Comment by nobnisai** [comment]
> You should be able to calculate the distance using the [Haversine Formula](https://en.wikipedia.org/wiki/Haversine_formula). I see a few posts on Stackoverflow for calculating the area of a polygon. Best to take a look there.

I think you misunderstand what I asked. I would like to know how to show the calculated distance/area on the polygon not how to calculate.

**Comment by christopherdro** [comment]
How about using a custom marker?

**Comment by nobnisai** [comment]
> How about using a custom marker?

I want to display it similar to this one. Is it possible?
![04F5200D-DB6D-442F-BDAE-5911098870D0](https://user-images.githubusercontent.com/24810591/111818186-7c6e8800-8911-11eb-9a63-d56a86e37f2e.jpeg)

**Comment by rodrigoodz** [comment]
> > How about using a custom marker?
> 
> I want to show similar to this one. Is it possible?
> ![04F5200D-DB6D-442F-BDAE-5911098870D0](https://user-images.githubusercontent.com/24810591/111818186-7c6e8800-8911-11eb-9a63-d56a86e37f2e.jpeg)

i could do something like this using custom markers like @christopherdro said.

```
<Marker coordinate={getCenter(markersCoordinates)}>
    <Text>Area:xxx</Text>
</Marker>
```
to show the distance text between two points you can do the same but just using two points instead of four

**Comment by purellarohith** [comment]
Hi @nobnisai 

Am tring to implement same is there any reference to implement it.

**Comment by nobnisai** [comment]
> Hi @nobnisai
> 
> Am tring to implement same is there any reference to implement it.

Well, I used the custom marker to display the distance between each polyline and the center of the polygon. The result is the same as the image above.
