### ISSUE TITLE
Add text label on/over the polyline and in a polygon

### ISSUE THREAD

**Issue by SuuSoJeat** [react-native-maps/react-native-maps#3756]
# Feature request

I would like to request a feature to add a text label on/over the polyline and in the middle of a polygon.

## Why it is needed

It would be convenient and intuitive for displaying the distance of each polyline or the area of each polygon.

## Possible implementation

Add a new text/label prop to polyline and polygon components. 

### Code sample

I could not provide any code sample.

**Comment by christopherdro** [comment]
Duplicate https://github.com/react-native-maps/react-native-maps/issues/3753#issuecomment-802980985
