### ISSUE TITLE
Buildings / Indoors not rendering

### ISSUE THREAD

**Issue by VladimirMoFe** [react-native-maps/react-native-maps#3758]
# Bug report

## Summary

The buildings that have indoors are not rendering when zooming in the map, neither showing the Indoor Level Picker.

## Environment info

`react-native info` output:

```bash
react-native: 0.60.5
react: 16.8.6
react-native-maps: 0.27.1
```

## Steps to reproduce

1. Rendering MapView component with the following propps 
2. Zooming in to a building (happens with all buildings)

![Captura de pantalla 2021-03-22 a las 9 10 59](https://user-images.githubusercontent.com/48053823/111969067-2446aa00-8afa-11eb-8c13-fa3193964f9f.png)

Expected to happen (image from Google Maps): 

![Screenshot_20210322-084904](https://user-images.githubusercontent.com/48053823/111969237-4ccea400-8afa-11eb-8b08-003d0099872d.jpg)

What actually happens:

1. Buildings are not rendering, also indoor level picker not showing. 
![Screenshot_20210322-084831](https://user-images.githubusercontent.com/48053823/111969403-7ab3e880-8afa-11eb-9e5d-e10c93151561.jpg)

## Reproducible sample code

https://snack.expo.io/kFMYjPalP

**Comment by jcmlumacad** [comment]
Is there any solution for this?

**Comment by jcmlumacad** [comment]
Found the solution for this. Setting the map type to `standard` works fine
