### ISSUE TITLE
Downgrade performance on Zoom or Move when use React Hooks.

### ISSUE THREAD

**Issue by abdullaharif789** [react-native-maps/react-native-maps#3759]
![Capture](https://user-images.githubusercontent.com/21336787/111975420-d01dd480-8abd-11eb-9894-077b64c7d82b.PNG)

I have some simple question about react-native-maps that if I used setRegion in the function of onRegionChange, when I zoom the map or move it, it will slow the map or degrade the performance. If I am not set the updated region value,, it will work fine.

**Comment by salah-ghanim** [comment]
@abdullaharif789 I don't see anything specific in your question regarding this library. your question about hooks is more about react-native performance it self.
Please ask on stackoverflow instead... issues usually indicate something that needs to be solved by the repo, this is not the case here.
