### ISSUE TITLE
Very slow performance of onChangeRegion event in GoogleMaps

### ISSUE THREAD

**Issue by scblason** [react-native-maps/react-native-maps#3765]
# Bug report

## Summary
Very slow performance of onChangeRegion event in GoogleMaps. In iOS version (Apple Maps), the performance is perfect and there is no noticeable lagging or delay in event calls.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 114.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 3.8.5 - /usr/local/opt/python@3.8/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Log the result of the call to onReegionChange every time the region changes in Android and IOS
2. Compare speed performance

https://user-images.githubusercontent.com/13370132/112564242-ac0e0c00-8db9-11eb-9fec-b6055ed0aa61.mov

Describe what you expected to happen:

The performance in GMaps shouldn't be so poor!

Describe what you actually happens:

Is there a way to get some sort of performancee boost for that event in GMaps? Configuring the map using other attributes?
Bare in mind that there is no marker being drawn in the map view, just a helper component to show the current location / region when dragging around the map. The setSate event is called every time onChangeRegion is called to update the current location value shown at the top

## Reproducible sample code
See attached file

**Comment by randomprogramming** [comment]
Looks like it's trying to run some form of animation. Please include some code...
