### ISSUE TITLE
Offline react-native-maps usage with google maps

### ISSUE THREAD

**Issue by iromjkee** [react-native-maps/react-native-maps#3774]
Hello, I'm here to ask about react-native-maps working offline with google maps here. Is it possible to download tiles for google when you are currently in the app? For example now I have internet connection, I know, that I will go to place with bad internet and I want to download tiles to my device and use them when have no internet connection. Is it even possible with google api? For real searching the web for a few days, but see only old answers about it and no any examples of how to do that if it's possible.

**Comment by christopherdro** [comment]
This isn't currently possible but hopefully something we can support in the near future. Check #255 for updates.
