### ISSUE TITLE
addressForCoordinate is undefined

### ISSUE THREAD

**Issue by randomprogramming** [react-native-maps/react-native-maps#3775]
I am trying to use the `addressForCoordinate` function as such: 
```
    mapRef.current
      .addressForCoordinate({
        latitude: selectedLatitude,
        longitude: selectedLongitude,
      })
      .then((res) => console.log(res));
```

but I am getting an error that `addressForCoordinate` doesn't exist. When I try to do `console.log("mapref", mapRef.current.addressForCoordinate);`, it prints `undefined`.

I am probably missing something so this is marked as an question, don't think it's a bug. I am using `"react-native-maps": "0.27.1"`.

**Comment by randomprogramming** [comment]
Oh was this method maybe not included in the latest release yet?

**Comment by christopherdro** [comment]
The feature hasn’t been released yet. Will do so in the next coming weeks.

**Comment by randomprogramming** [comment]
@christopherdro Any update on this? Still not in the latest release from what I can tell?

**Comment by wandaomni** [comment]
alguna novedad?

**Comment by danieldanielecki** [comment]
+1, looks like it's still not there

![not_included](https://user-images.githubusercontent.com/12736263/124393824-a438fe80-dcfc-11eb-8e4c-bbfe12e52293.png)

**Comment by danieldanielecki** [comment]
@randomprogramming, I think you can reopen this issue.

**Comment by danieldanielecki** [comment]
> The feature hasn’t been released yet. Will do so in the next coming weeks.

@christopherdro any update on this? as per [3955](https://github.com/react-native-maps/react-native-maps/issues/3955) we badly need this functionality.
