### ISSUE TITLE
MapView.Markers are stuck orphaned in view when they should be removed on Android

### ISSUE THREAD

**Issue by o4oren** [react-native-maps/react-native-maps#3783]
# Bug report

## Summary

I have a MapView component in which I render numerous custom MapView.Markers with a child <Image /> component as custom icon. These represent aircraft, and between 60 seconds api calls change location and heading, some are added, some are removed.
I often have more than 1000 of these on the map. Each API call brings the whole array of objects that are mapped to <MapView.Marker /> components inside the map, and is propagated through a redux store, updating the parent component list of aircraft via a useSelector hook.
All objects have a unique key created from the user id and callsign, and is unique through the system.

Every few cycles, and only on **Android** (on iOS it never happens - using Apple maps. I am not using google maps there because performance is not satisfactory with so many markers), one of the aircraft that disappear from the data (user has disconnected), turn into a red default marker in the last known heading of the aircraft, and stay there forever.

I printed all children keys between updates, by storing the old one in a state. I can see that the ones that stick around are the disconnected ones, but they are no longer children of the map at that stage, and I cannot get rid of them.

## Environment info

`react-native info` output:

```bash
oren@oren-mac vatview % react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 22.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps to reproduce

1. I could not reproduce it with a simple software that just updates and array of markers. I don't know how to reproduce it not on my software.
The code is at: 
https://github.com/o4oren/VatView.git
You can look at the file MapComponent under VatsimMapView.
expo start
And just wait a few cycles.
2. With this code I printed the difference between current and previous keys:
```
    useEffect(() => {
        if(mapRef && mapRef.current)
        {
            const markers = mapRef.current.props.children[0].map(c => c.key).sort();
            console.log('prev', app.prevMarkers);
            console.log('current', markers);

            // find the missing one
            const keys = app.prevMarkers.length > 0 ? app.prevMarkers.filter(m => {
                return !markers.find(e => e === m);
            }) : [];
            console.log('keys', keys);
            dispatch(allActions.appActions.updatePrevMarkers(markers));
        }
    }, [clients]);
```

The result shows that on most cycles all removed items disaapear, but once in a while they don't.

Describe what you expected to happen:

Describe what you actually happens:
1. Sometimes, items remove from the data lose their styling and associated data except for the title.

![Screenshot_20210410-154320_Expo Go](https://user-images.githubusercontent.com/23486326/114607566-613f3000-9ca5-11eb-93db-b1a7bdc85c7d.jpg)

**Comment by Simon-TechForm** [comment]
Focusing discussion here: #4214
