### ISSUE TITLE
requireNativeComponent: "AIRMapCalloutSubview" was not found in the UIManager.

### ISSUE THREAD

**Issue by muskansoni482** [react-native-maps/react-native-maps#3790]
On android following this configuration
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.0.0" 
        mediaCompatVersion = '1.0.1' 
        supportV4Version = '1.0.0'
        androidMapsUtilsVersion = "0.5+"
    }
and using the callout subview as below
```
<Callout
                  alphaHitTest
                  tooltip
                  onPress={(e) => {
                    if (
                      e.nativeEvent.action === "marker-inside-overlay-press" ||
                      e.nativeEvent.action === "callout-inside-press"
                    ) {
                      return;
                    }

                    Alert.alert("callout pressed");
                  }}
                  style={styles.customView}
                >
                  <CustomCallout>
                    <Text>static</Text>
                    <CalloutSubview
                      onPress={() => {
                        console.log("hello");
                      }}
                      style={[styles.calloutButton]}
                    >
                      <Text>Click me</Text>
                    </CalloutSubview>
                  </CustomCallout>
                </Callout> 
```
we are facing this issue
![image](https://user-images.githubusercontent.com/42670480/114981225-463e0d00-9eab-11eb-95b0-e4354e3d525b.png)

**Comment by kmkrtich** [comment]
Same issue for me
Using ReactNative - 0.63.3
react-native-maps - 0.28.0

**Comment by kmkrtich** [comment]
> On android following this configuration
> buildscript {
> ext {
> buildToolsVersion = "28.0.3"
> minSdkVersion = 21
> compileSdkVersion = 28
> targetSdkVersion = 28
> supportLibVersion = "28.0.0"
> googlePlayServicesVersion = "17.0.0"
> mediaCompatVersion = '1.0.1'
> supportV4Version = '1.0.0'
> androidMapsUtilsVersion = "0.5+"
> }
> and using the callout subview as below
> 
> ```
> <Callout
>                   alphaHitTest
>                   tooltip
>                   onPress={(e) => {
>                     if (
>                       e.nativeEvent.action === "marker-inside-overlay-press" ||
>                       e.nativeEvent.action === "callout-inside-press"
>                     ) {
>                       return;
>                     }
> 
>                     Alert.alert("callout pressed");
>                   }}
>                   style={styles.customView}
>                 >
>                   <CustomCallout>
>                     <Text>static</Text>
>                     <CalloutSubview
>                       onPress={() => {
>                         console.log("hello");
>                       }}
>                       style={[styles.calloutButton]}
>                     >
>                       <Text>Click me</Text>
>                     </CalloutSubview>
>                   </CustomCallout>
>                 </Callout> 
> ```
> 
> we are facing this issue
> ![image](https://user-images.githubusercontent.com/42670480/114981225-463e0d00-9eab-11eb-95b0-e4354e3d525b.png)

CalloutSubview is supposed to work for IOS only
