### ISSUE TITLE
GeoJSON type MultiPolygon - onPress get Feature properties

### ISSUE THREAD

**Issue by dmenneck** [react-native-maps/react-native-maps#3791]
# Question

Is there a way to make the individual Features of a MultiLinePolygon GeoJSON Layer clickable? 
I have a GeoJSON dataset with Building geometries and i'd like the user to be able to click on a Building (maybe
change its color) and return it's properties.

**Comment by WrathChaos** [comment]
Hello @dmenneck,
Actually `Polyline` onPress is available and it returns the pressed overlay. 
[Here is the code](https://github.com/react-native-maps/react-native-maps/blob/e6e7b8176ae5d1b0daae354f8ca0b9d4cd5873c8/lib/components/Geojson.js#L195)

Doesn't it suitable for you?

**Comment by dmenneck** [comment]
Hi @WrathChaos,

thanks for your help! This is exactly what i was looking for.

**Comment by dmenneck** [comment]
Now i'm curious if its possible to set a fillColor for a Polyline. `fillColor` is not possible, is it?

**Comment by dmenneck** [comment]
I changed the type to `Polygon` and now it's working. Thanks!
