### ISSUE TITLE
userInterfaceStyle not working

### ISSUE THREAD

**Issue by francesco-clementi-92** [react-native-maps/react-native-maps#3795]
# Bug report

## Summary

I'm trying to set on runtime the prop userInterfaceStyle to dark for an IOS app, but it doesn't work.
I'm also tried to set it by default, but the map continue to be light.

## Environment info

      react-native: 0.64.0
      react: 17.0.1
      react-native-maps: 0.28.0

    Target Platform: iOS - 12.4 Simulator/iPhone X Legal

## Reproducible sample code
https://snack.expo.io/@nordup/react-native-maps-dark-mode

**Comment by boertel** [comment]
I think this PR is fixing it: https://github.com/react-native-maps/react-native-maps/pull/3764 but I'm not sure when is the next release?

**Comment by leolusoli** [comment]
+1
When this feature will be released?

**Comment by christopherdro** [comment]
Duplicate https://github.com/react-native-maps/react-native-maps/issues/3846
