### ISSUE TITLE
Marker.Animated "Jump" in iOS with Google provider

### ISSUE THREAD

**Issue by aguileraps** [react-native-maps/react-native-maps#3804]
# Bug report

## Summary

Marker.Animated "Jump" in iPhone XR iOS 14.4.2 with MapView provider={PROVIDER_GOOGLE}

iPhone XR,  iOS 14.4.2 = Marker Jump
iPhone 6s, iOS 13.3 = Works fine
Android = Works fine

## Environment info

node -v : v10.15.1
expo --version : 4.4.3

## Reproducible sample code

https://snack.expo.io/pE9ldFB64

## Snack  sample in real device

![marker-ios](https://user-images.githubusercontent.com/1988234/116583450-bf4a5500-a8ec-11eb-8095-e2bc59aeb468.gif) ![marker-ios-google](https://user-images.githubusercontent.com/1988234/116583464-c2dddc00-a8ec-11eb-94d7-d5cbc4459010.gif)
 
Thank you!

**Comment by tuanhm93** [comment]
Hello, have you resolve this error?

**Comment by aguileraps** [comment]
> Hello, have you resolve this error?
sadly no, hope someone from the maps team can see it and debug it

**Comment by tuanhm93** [comment]
I figure it that iOS blow 14 is not have this bug
So i decide to use timing animate with iOS blow 14
With iOS greater or equal 14, I still use Marker.Animated with setState to new location only. 
Hope this can help you for now.
Sorry cause my english not good.

**Comment by sonnt612** [comment]
@christopherdro Can you take a look at this bug?

**Comment by Lab3l** [comment]
Hi

Stumbled upon the same issue on our app and ended up figuring a solution which at least for us fixed this problem as we're only rendering a single animated marker on the map (given it might introduce some performance issues if rendering a bunch of markers).
Set a reference to the marker and upon animating the position, set up an interval w/ 10ms execution time which runs markerRef.redraw(). After the animation finishes, naturally clear the interval.

So simple example:

const MARKER_INTERVAL = 10
let redrawInterval = null

animationHandler = () => {
  if (markerRef) {
    // Initial redrawing upon starting
    this.markerRef.redraw()
    redrawInterval = setInterval(() => {
      this.markerRef.redraw()
      },
    MARKER_INTERVAL)
  animatedComponent.timing({
    ...coordinates,
    duration: 500
  })
  .start(() => {
    if (redrawInterval) {
      clearInterval(redrawInterval)
      redrawInterval = null
    })
  }
}

... render map view etc
  <MapView.Marker.Animated
              ref={ref => (this.markerRef = ref)}
              coordinate={coordinates}>
   ...rest
</MapView.Marker.Animated>

Hope this helps you with the issue

**Comment by LightKnight3r** [comment]
> Hi
> 
> Stumbled upon the same issue on our app and ended up figuring a solution which at least for us fixed this problem as we're only rendering a single animated marker on the map (given it might introduce some performance issues if rendering a bunch of markers). Set a reference to the marker and upon animating the position, set up an interval w/ 10ms execution time which runs markerRef.redraw(). After the animation finishes, naturally clear the interval.
> 
> So simple example:
> 
> const MARKER_INTERVAL = 10 let redrawInterval = null
> 
> animationHandler = () => { if (markerRef) { // Initial redrawing upon starting this.markerRef.redraw() redrawInterval = setInterval(() => { this.markerRef.redraw() }, MARKER_INTERVAL) animatedComponent.timing({ ...coordinates, duration: 500 }) .start(() => { if (redrawInterval) { clearInterval(redrawInterval) redrawInterval = null }) } }
> 
> ... render map view etc <MapView.Marker.Animated ref={ref => (this.markerRef = ref)} coordinate={coordinates}> ...rest </MapView.Marker.Animated>
> 
> Hope this helps you with the issue

hi @Lab3l , i tried this but redraw() function does not work on IOS. Which version of this modules did you use? can you send me full solution? thanks alot

**Comment by emehmet** [comment]
I think this is due to both the marker update in the react tree and the update with timing.

I solved this problem with the state that changes with every update in iOS and animate marker in android.

like this;

` if (Platform.OS === 'android') {
        if (marker) {
          marker?.current?.animateMarkerToCoordinate(curPos, 3000);
        }
      }`

`  const [coordinate, set_coordinate] = React.useState<LatLng>({latitude:40;longitue:29}); // constant`

` <Marker coordinate={{
                      latitude: Platform.OS === 'android' ? coordinate?.latitude : AssetData.LAT,
                      longitude: Platform.OS === 'android' ? coordinate?.longitude : AssetData.LON, 
                    }} 
/>`

So on iOS, always update <Marker />. Update with ref and change coordinates once on Android.

**Comment by fgarzonhz** [comment]
This happend also in IOs 15.6.1 in iPhone 12

**Comment by estmau** [comment]
i have same issue in iphone 12 react native 69.5

**Comment by zhenguet** [comment]
I am still looking for a solution
