### ISSUE TITLE
onRegionChangeComplete call multiple time in iOS

### ISSUE THREAD

**Issue by KrifaYounes** [react-native-maps/react-native-maps#3805]
When I use method animateToRegion or when I scrolling the map, the method onRegionChangeComplete is called multiple time. 
There is a way to trigger a method onPressIn and onPressOut the map and call onRegionChangeComplete only one time  when we use animateToRegion ?

**Comment by mattiaefesto** [comment]
Any news about this?

**Comment by KrifaYounes** [comment]
Nothing

**Comment by irmakcosarsahna** [comment]
same issue
