### ISSUE TITLE
Clicking on current location button or toolbar buttons crashes the app

### ISSUE THREAD

**Issue by KrisLau** [react-native-maps/react-native-maps#3808]
# Bug report
## Summary
As described in the title: Whenever I click on the current location button or any of the toolbar buttons (to get directions on Google Maps), the entire app crashes.

## Environment info

`react-native info` output:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 875.48 MB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10 - C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```bash
      react-native: ^0.64.0
      react: ^17.0.2
      react-native-maps: 0.28.0 
```

## Steps to reproduce
1. Follow instructions to install and setup project.
2. Use my code below and click on the toolbar button.
3. Observe the app crash.

_Describe what you expected to happen:_
I was expecting to be redirected to Google Maps and given directions to the map marker location.

_Describe what you actually happens:_
The app just immediately crashes.

## Reproducible sample code
(just for toolbar button not the current location button)

```
<MapView
        onMarkerPress={() => showToolBarHack()}
        toolbarEnabled={true}
        loadingEnabled={true}
        showsUserLocation={true}
        showsMyLocationButton={false}
        showsPointsOfInterest={true}
        region={{
          latitude: 38.7938,
          longitude: -97.5748,
          latitudeDelta: 0.009,
          longitudeDelta: 0.009,
        }}
        style={[styles.map, {height: 200 + toolbarHackHeight}]}>
        <Marker
          identifier={'destination'}
          coordinate={{latitude: 38.7938, longitude: -97.5748}}
        />
</MapView>
```

The following section of code is from: https://github.com/react-native-maps/react-native-maps/issues/549#issuecomment-272815386 which I used to get the toolbar to appear.
```
const [toolbarHackHeight, setToolbarHackHeight] = useState(0);

function showToolBarHack() {
    const heightDiff = 0.5; // we don't want to change the height too much so keep it small. I've noticed 0.5 works best, as opposed to 0.1 doesn't work at all, and 0.5 is barely noticeable to the user.
    // switch the height between 0 and 0.5 and back.
    setToolbarHackHeight(
      toolbarHackHeight === heightDiff
        ? toolbarHackHeight - heightDiff
        : toolbarHackHeight + heightDiff,
    );
}
```

**Comment by francesco-clementi-92** [comment]
Same here

**Comment by sushilbansal** [comment]
Hi @KrisLau / @francesco-clementi-92 : have you guys been able to resolve this issue?

**Comment by KrisLau** [comment]
@sushilbansal Nope I just manually created my own buttons

**Comment by Simon-TechForm** [comment]
I'm struggling to reproduce this. Could one of you try to reproduce this on the latest `react-native-maps`? And if you are able to, provide a sample code, and the stack trace from the crash?

**Comment by KrisLau** [comment]
@Simon-TechForm Unfortunately I stopped trying to use the toolbar and ended up manually creating buttons which perform the same behaviour so i don't have a sample code anymore. However I tried recreating it in a snack and it seems like the problem is coming from when I try to put it in an animated view: https://snack.expo.dev/du_R0LoIe

**Comment by Simon-TechForm** [comment]
@francesco-clementi-92 @sushilbansal able to help out with the above?
