### ISSUE TITLE
onRegionChangeComplete value of isGesture is undefined in version 0.28.0

### ISSUE THREAD

**Issue by dazulu** [react-native-maps/react-native-maps#3818]
# Bug report

## Environment info
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
      react: 16.13.1
      react-native-maps: 0.28.0

## Steps to reproduce

1. Look at the returned values for `onRegionChangeComplete`

Describe what you expected to happen:

1. The value for `isGesture` should be a boolean value

Describe what actually happens:

1. The value for `isGesture`, returned by `onRegionChangeComplete` is `undefined`.

![Screenshot 2021-05-10 at 11 53 35](https://user-images.githubusercontent.com/4543447/117641380-5b464d00-b186-11eb-944f-22589ac0c3d2.png)

**Comment by RyanTG** [comment]
I am seeing this issue, too. 

Anxiously looking forward to this functionality in order to address "map flickering" issues due to onRegionChangeComplete firing over and over without any input from the user.

**Comment by christopherdro** [comment]
Looking through the source it appears the `isGesture` property is only available on google maps. If you are using Apple Maps then the value will be undefined.

**Comment by RyanTG** [comment]
It is undefined with Google Maps in v 0.28.0

**Comment by christopherdro** [comment]
Something might be wrong with your implementation. I see the value but only when the `provider` prop set to `google` on `<Mapview />`.

![Screen Shot 2021-06-17 at 14 13 16 ](https://user-images.githubusercontent.com/3741055/122603589-6fa12380-d029-11eb-8e44-f6963cf3faee.png)

**Comment by RyanTG** [comment]
Ah ok, thanks. Given that some of us are having problems implementing this, a little code snippet can go a long way.

We're essentially doing this: https://stackoverflow.com/questions/47832224/onregionchangecomplete-function-calling-multiple-times-using-react-native-maps/67191495#67191495

````
    onRegionChange = (region, gesture) => {
        if (gesture.isGesture) {
            this.setState({
                ...region,
                showUpdateSearch: this.state.mapCoordinatesUpdated ? false : true,
                mapCoordinatesUpdated: false
            })
        }
    }
````

I am not sure if this is relevant, but we're using Expo (which currently supports 0.27.0). We manually updated to 0.28.0 in package.json, so we assume it's using that version.

**Comment by christopherdro** [comment]
That will only work if you’re on a bare workflow.

**Comment by RyanTG** [comment]
Ah, I thought it was still possible to adjust package versions in managed workflow - as we are currently using a different react-native-screens version due to a regression in 3.0.0. But I guess that's only possible with some packages...

It looks like 0.28.0 is not included (yet!) in the upcoming SDK 42 :(

**Comment by christopherdro** [comment]
If the changes are JS only, then there shouldn't be any issue. However, the changes for this feature included native changes.
