### ISSUE TITLE
Execution failed for task ':app:mergeLibDexDebug'.

### ISSUE THREAD

**Issue by mayankshinkhedkar** [react-native-maps/react-native-maps#3822]
# Bug report

## Summary

Execution failed for task ':app:mergeLibDexDebug'.

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

> Failed to transform classes.jar (project :react-native-maps) to match attributes {artifactType=android-dex, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.api.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

> Execution failed for DexingNoClasspathTransform: 

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 101.10 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

"react-native-maps": "0.27.1"
"react-native-geolocation-service": "^5.2.0"
"react-native-maps-directions": "^1.8.0"

"@react-native-firebase/app": "^11.5.0"
"@react-native-firebase/messaging": "^11.5.0"
```

## Steps to reproduce

1. Setup react-native-maps, react-native-geolocation-service and react-native-maps-directions. Working properly after that Installed firebase for Push Notification.
2. [@react-native-firebase/messaging](https://rnfirebase.io/messaging/usage#installation) setup from given steps

Describe what you expected to happen:

The project must run on Android. In iOS, the project is running without any conflicts.

Describe what you actually happens:

Getting 
Execution failed for task ':app:mergeLibDexDebug'. 
In Android

## Reproducible sample code

![Screenshot 2021-05-15 at 6 05 57 PM](https://user-images.githubusercontent.com/18735292/118361427-0c931b80-b5a9-11eb-9920-5790f4dd31a2.png)

![Screenshot 2021-05-15 at 6 06 42 PM](https://user-images.githubusercontent.com/18735292/118361429-0e5cdf00-b5a9-11eb-8a16-37a3bd439595.png)

![Screenshot 2021-05-15 at 6 10 43 PM](https://user-images.githubusercontent.com/18735292/118361431-0f8e0c00-b5a9-11eb-83a2-d316c398df49.png)

![Screenshot 2021-05-15 at 6 11 16 PM](https://user-images.githubusercontent.com/18735292/118361434-1026a280-b5a9-11eb-8c08-beb96adb694a.png)

**Comment by Simon-TechForm** [comment]
Closing for now. If you believe that this is still relevant, please feel free to open a new issue.
