### ISSUE TITLE
onMapReady not called in testing-library react-native test

### ISSUE THREAD

**Issue by richardwu** [react-native-maps/react-native-maps#3824]
# Bug report

## Summary

I expect `onMapReady` to be called once `MapView` has rendered inside a jest test with `@testing-library/react-native`.

## Environment info

```
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz" (pinned to 0.63.2)
    "react": "16.13.1",
     "react-native-maps": "0.27.1",
```

Target: jest test w/ iOS environment and Apple Maps (default).

## Steps to reproduce

Describe what you expected to happen:

`onMapReady` callback should be called eventually when rendered under a test.

Describe what you actually happens:

The test fails since `onMapReady` callback is never invoked.

## Reproducible sample code

Have the following test component:
```js
import React, { useState } from "react";
import { Text, View } from "react-native";
import MapView from "react-native-maps";

const TestMap = () => {
  const [mapReady, setMapReady] = useState(false);
  return (
    <View>
      <MapView
        onMapReady={() => {
          console.log("map ready");
          setMapReady(true);
        }}
      ></MapView>
      {mapReady && <Text>Test</Text>}
    </View>
  );
};

export default TestMap;
```

Try to run the following jest test:
```js
import { render, waitFor } from "@testing-library/react-native";
import React from "react";
import TestMap from "../TestMap";

describe("TestMap", () => {
  it("works", async () => {
    const { findByText } = render(<TestMap />);
    await waitFor(async () => expect(await findByText("Test")).toBeTruthy());
  });
});
```

**Comment by Simon-TechForm** [comment]
This isn't possible, as react-native-maps relies on native components. Please check out [jest docs](https://jestjs.io/docs/tutorial-react-native#mock-native-modules-using-jestmock) and [react-native docs](https://reactnative.dev/docs/testing-overview#mocking).
