### ISSUE TITLE
How to run example in browser (expo)?

### ISSUE THREAD

**Issue by SeanPedersen** [react-native-maps/react-native-maps#3825]
I am having trouble running the example with expo.

I ran:
`$ npm install`

Followed by:
`$ npm install expo`

Then tried: `$ expo start --web`

But that did not work, am I missing sth obvious? (I am rly inexperienced with React Native / Expo)

**Comment by christopherdro** [comment]
No web support at the moment. See platform compatibility here. https://docs.expo.io/versions/latest/sdk/map-view/
