### ISSUE TITLE
React Native Auto-linking Issue on version 0.61.5

### ISSUE THREAD

**Issue by jaferi512** [react-native-maps/react-native-maps#3826]
I've Installed the react-native-maps according to the official Documentation of React Native Maps Community.
But I'm observing auto-linking issue on react native version 0.61.5.
I hope Community Will Response as soon as possible.
<img width="682" alt="Screenshot 2021-05-25 at 3 17 37 PM" src="https://user-images.githubusercontent.com/57745133/119482105-e91c5d80-bd6c-11eb-9bc0-bed9e54770d9.png">

Thanks in Advance.

**Comment by rborn** [comment]
Usually that error can be ignored ( of course if the app works). Also this repo supports only the latest version of RN, so you are a little behind :)
