### ISSUE TITLE
Region and array of coordinates

### ISSUE THREAD

**Issue by AlexandreMouyen** [react-native-maps/react-native-maps#3828]
Hello there,

I have on array of locations (with coordinates) like companies in a city.

How can I use the "region" props to display these points of interest in the MapView? Maybe how to "clamp" the region?

I really do not know how to use it.

I hope it is clear.

Thanks.

**Comment by christopherdro** [comment]
You won’t use the region prop here. Add the locations as map markers and use fitToElements method. https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#methods

**Comment by AlexandreMouyen** [comment]
Thanks a lot, it is working perfectly.
