### ISSUE TITLE
Overlay rotation

### ISSUE THREAD

**Issue by KaviduAloka** [react-native-maps/react-native-maps#3832]
Hi, I am using the `Overlay `component and I want to rotate this. I see that `bearing` prop is not there anymore. And I tried adding the style and change the props to `transform: [{rotate: '50deg'}]`. It doesn't work either. Any suggestion?

**Comment by nkulic** [comment]
@KaviduAloka bearing property does work for Overlay component (tested on Android physical device), but you must manually clone library and select master branch, and then put that cloned folder (react-native-maps) inside your node_modules folder (you can rename your current react-native-maps to keep it as a backup). But this is not appropriate way, i'm curious why updates on library are not included when simply installing it (e.g. `npm install react-native-maps --save`)

**Comment by KaviduAloka** [comment]
@nkulic thank you very much. It was in the documentation too. But it didn't make any sense. I will have a look and let you know..
