### ISSUE TITLE
MapView - onMapLoaded is not called when initialRegion is set to specific values

### ISSUE THREAD

**Issue by nkulic** [react-native-maps/react-native-maps#3835]
# Bug report

## Summary

When region is set to specific values, `onMapLoaded` property does not execute.

## Environment info

`react-native info` output:

```bash
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "^0.28.0",

Using GoogleMaps provider.
Tested on Physical device (samsung galaxy s9+) and emulators
```

## Steps to reproduce

- Create MapView component and add `onMapLoaded` and `initialRegion` properties

- Set initial region to values (I noticed it acts differently based on different places/coordinates on map), e.g. with values from example below `onMapLoaded` wont execute, yet tiles will be loaded and displayed

```
onMapLoaded={() => console.log('MAP IS LOADED')}
region={{
  latitude: 43.28607,
  latitudeDelta: 0.01,
  longitude: 16.07485,
  longitudeDelta: 0.01,
}}
```

- But if `latitudeDelta` value is changed to `0.03` then `onMapLoaded` will be called.

Describe what you expected to happen:

1. Expecting `onMapLoaded` to be called once tiles are loaded and displayed.

Describe what you actually happens:

1. `onMapLoaded` is not called but map tiles for defined region are fully loaded and clearly seen on device screen

## Reproducible sample code

Online reproduction of bug:
*Make sure to pick Android or IOS and to open LOGS to check outputs
https://snack.expo.io/@nkulic/expo-snac
![Screenshot at Jun 04 20-44-29](https://user-images.githubusercontent.com/63425772/120848977-c4e32c80-c575-11eb-93a5-16c50bd43105.png)

Sample code:
```
<MapView
  onMapLoaded={() => console.log('MAP IS LOADED')}
  region={{
    latitude: 43.28607,
    latitudeDelta: 0.01,
    longitude: 16.07485,
    longitudeDelta: 0.01,
  }}
  mapType={'satellite'}
  style={{ width: '100%', height: '100%' }}
/>
```

**Comment by taylorkline** [comment]
I am experiencing something similar as well since upgrading to React Native v0.64.1. On our previous version of React Native, v0.61.5, an `initialRegion` plus an `onMapReady` that would call `fitToCoordinates` or `animateToRegion` would work fine. Now, the code is called, but it has no effect on Android. As a workaround for the time being, I am manually adding a `setTimeout` for Android of `200` ms. The `fitToCoordinates` and `animateToRegion` work with a timeout in combination with an `initialRegion`.

**Comment by jamesholcomb** [comment]
Thanks @taylorkline, your workaround for `fitToCoordinates` helped me out.   Experiencing this on Android and React Native 0.66.4

**Comment by Simon-TechForm** [comment]
@Simon-TechForm notify me
