### ISSUE TITLE
How to show traffic on the route

### ISSUE THREAD

**Issue by december1990** [react-native-maps/react-native-maps#3843]
I need to show the traffic just on the route that's suggested by google but the problem is that by making the showsTraffic property true on mapView  the traffic data is shown for all the roads and it is mixed up with the polyline that I draw using MapviewDirections so that makes the route hard to recognize, are there anyways to show traffic just for the suggested route and combine traffic polyline with route's polyline ? like the picture below ? thanks

![Untitled](https://user-images.githubusercontent.com/5105855/121688004-396b1d80-cad8-11eb-9792-767546fbc4da.jpg)

**Comment by MehrdadArman** [comment]
Hello. I  have the same issue tooooooo. Please help us. tnx.🥴🥴🥴🥴🥴🥴🥴

**Comment by christopherdro** [comment]
You’d have to create your own polylines.

**Comment by december1990** [comment]
but how can I get the information about the traffic on specific roads ?

**Comment by christopherdro** [comment]
Have you tried searching for exiting APIs? A simple Google search will answer that.
