### ISSUE TITLE
ViewPropTypes undefined when just importing react-native-maps on Web

### ISSUE THREAD

**Issue by richardwu** [react-native-maps/react-native-maps#3844]
# Bug report

## Summary

**NB: Yes, I understand react-native-maps is not supposed to work on web**. That being said, the `import` itself is causing me issues on Web, and you can't dynamically import a module, which means I have to always comment/uncomment out the import whenever I want to run my app on the web, even without the MapView component.

I'm getting the following error when _importing_ `MapView` from `react-native-maps`:
```
TypeError: Cannot read property 'style' of undefined

Module.../../../react-native-maps/lib/components/MapView.js
node_modules/react-native-maps/lib/components/MapView.js:84

  81 |  * Used to style and layout the `MapView`.  See `StyleSheet.js` and
  82 |  * `ViewStylePropTypes.js` for more info.
  83 |  */
> 84 | style: viewPropTypes.style,
     | ^  85 | 
  86 | /**
  87 |  * A json object that describes the style of the map. This is transformed to a string
```

Ideally _importing_ the module in Web should not fail, so perhaps it's better to case statement the reference to `viewPropTypes` if `Platform.OS === "web"`.

## Environment info

```
    react-native: "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz"
    react: 16.13.1
    react-native-maps: 0.27.1
```

## Steps to reproduce

Import `MapView` from `react-native-maps` on Web.

Describe what you expected to happen:

Import should be fine: render of component should fail.

Describe what you actually happens:

Import fails because of an undefined reference on web.

## Reproducible sample code

```
import MapView from "react-native-maps";
```
on web.

**Comment by christopherdro** [comment]
This library is not supported on web.
