### ISSUE TITLE
userInterfaceStyle not working on iOS

### ISSUE THREAD

**Issue by KrifaYounes** [react-native-maps/react-native-maps#3846]
Props userInterfaceStyle not working on iOS
The map style depend on system theme (night/light)
It's possible to manually control map style theme with userInterfaceStyle on iOS (Apple Plan)? 

"react-native": "0.64.0",
"react-native-maps": "^0.29.0",

```
<MapView
    minZoomLevel={3}
    userInterfaceStyle="dark"
    ref={forwardedRef}
    rotateEnabled={false}
    style={styles.map}
    scrollDuringRotateOrZoomEnabled={false}
    onPanDrag={() => setOnPanDrag(true)}
/>

<MapView
    minZoomLevel={3}
    userInterfaceStyle="dark"
    ref={forwardedRef}
    rotateEnabled={false}
    style={styles.map}
    scrollDuringRotateOrZoomEnabled={false}
    onPanDrag={() => setOnPanDrag(true)}
/>
```

**Comment by christopherdro** [comment]
Do you run into the same issue on the example app ? See screenshot posted in  the PR. https://github.com/react-native-maps/react-native-maps/pull/3764

cc @Johan-dutoit

**Comment by Johan-dutoit** [comment]
As far as I can tell it's not part of 0.28, and only landing in [0.29](https://github.com/bpoore/pbm-react/issues/345).

**Comment by leolusoli** [comment]
+1

**Comment by Johan-dutoit** [comment]
It's in 0.29, which isn't marked the latest on NPM (not sure why).
I just tested it in and it works as expected for me.  

I've attached a video just in case.

https://user-images.githubusercontent.com/1611055/122360889-0bae2a80-cf57-11eb-8118-f9165c60e936.mov

**Comment by KrifaYounes** [comment]
> It's in 0.29, which isn't marked the latest on NPM (not sure why).
> I just tested it in and it works as expected for me.
> 
> I've attached a video just in case.
> 
>  Screen.Recording.2021-06-17.at.10.30.20.mov

indeed in npm it's marked 0.28.
when I delete react-native-maps and retry yarn add react-native-maps => yarn install the version 0.28
Maybe, The latest release is not correctly deploy in npm.

**Comment by Johan-dutoit** [comment]
> > It's in 0.29, which isn't marked the latest on NPM (not sure why).
> > I just tested it in and it works as expected for me.
> > I've attached a video just in case.
> > Screen.Recording.2021-06-17.at.10.30.20.mov
> 
> indeed in npm it's marked 0.28.
> when I delete react-native-maps and retry yarn add react-native-maps => yarn install the version 0.28
> Maybe, The latest release is not correctly deploy in npm.

You can still set your package.json to 0.29.0 though (without the `^`) and it should install it just fine.

@christopherdro can you fix npm?

**Comment by Johan-dutoit** [comment]
> > It's in 0.29, which isn't marked the latest on NPM (not sure why).
> > I just tested it in and it works as expected for me.
> > I've attached a video just in case.
> > Screen.Recording.2021-06-17.at.10.30.20.mov
> 
> indeed in npm it's marked 0.28.
> when I delete react-native-maps and retry yarn add react-native-maps => yarn install the version 0.28
> Maybe, The latest release is not correctly deploy in npm.

You can still set your package.json to 0.29.0 though (without the ^) and it should install it just fine.

I believe 0.29.0 is still in 'pre-release' phase, which is why it's not tagged as latest.  @christopherdro can confirm this.

**Comment by christopherdro** [comment]
Correct. 0.29.0 is a pre release. https://github.com/react-native-maps/react-native-maps/releases/tag/v0.29.0
