### ISSUE TITLE
IOS - PROVIDER_GOOGLE Showing empty map

### ISSUE THREAD

**Issue by denisvely** [react-native-maps/react-native-maps#3847]
Hi i am loading Google maps on real IOS Device and it it showing empty map.

Could someone help me?

<MapView
  ref={mapRef}
  style={styles.map}
  showsUserLocation={true}
  scrollEnabled={true}
  zoomEnabled={true}
  showsMyLocationButton={true}
  showsPointsOfInterest={true}
  showsScale={true}
  toolbarEnabled={true}
  showsBuildings={true}
  showsTraffic={true}
  zoomControlEnabled={true}
  provider={PROVIDER_GOOGLE}
  loadingEnabled={true}
 />

Screenshot Attached: 
![telegram-cloud-photo-size-4-5929224098003662266-y](https://user-images.githubusercontent.com/28669083/122049262-e8666c80-cdea-11eb-8def-933ad1af7d42.jpg)

**Comment by christopherdro** [comment]
Make sure your API key is correct. Another option is to see if you can run the example app without any issues. Feel free to open this ticket again if the problem persists and please follow the template.

**Comment by singhtrustcom** [comment]
hi I am also facing the same issue when I tried to implement the map
 IOS - PROVIDER_GOOGLE Showing empty map
 it only showing me the title on the bottom I waste a lot of time to debug that issue but still stuck on it 
 
 I have followed all the step which are mentioned on
  https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md
  
  and I also configured all the setting on the google side as well 
  
  I  also check if IOS Map SDK is enabled or not all other important API like place GEO. etc
  
  also added map style from both and also tried with Custom style option by JSON data 
  
  still not able to load the map ios device on real and as well as simulator 
  
  i and using ***

   "react-native": "0.63.4",

   "react-native-maps": "^0.28.0",
  
  
  I code I also find some warning like 


  Documentation Issue Group
  ...../node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMap.m:29:


same issue on google map  ios -utills 

parameter 'inlineStyle' not found in the function declaration
...../ios/Pods/Google-Maps-iOS-Utils/src/Geometry/Model/GMUPlacemark.m:16:9: In file included from /Users/apple/Documents/GitHub/tfbrandnew/ios/Pods/Google-Maps-iOS-Utils/src/Geometry/Model/GMUPlacemark.m:16:


Parameter 'coordinates:' not found in the function declaration


maybe this will help you to better understand the bug

**Comment by Juliocbr** [comment]
@singhtrustcom @denisvely did you find a solution for this issue?

Greetings.

**Comment by oosunkeye** [comment]
Remove Provider Google for iOS

**Comment by MikhailNarkevich** [comment]
For the future, for those who encountered the same problem.
Be sure to check whether you added the correct **Bundle ID** when adding the **API Key** in the **Google Console**. This is a must, as this may also cause problems if the map is displayed during local debugging, but on real devices it turns white.
