### ISSUE TITLE
Choose the degree of orientation of the map?

### ISSUE THREAD

**Issue by Niiicooo** [react-native-maps/react-native-maps#3849]
Hello

I use the MapView component with custom tiles. Also these tiles being a drawing, the orientation of the drawing is not north.

Is it possible to force the map to be displayed at a certain degree rather than 0° North?

Thanks

**Comment by christopherdro** [comment]
You can probably use Camera to do that. See example here: https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/CameraControl.js
