### ISSUE TITLE
New addressForCoordinate always throws on iOS

### ISSUE THREAD

**Issue by owinter86** [react-native-maps/react-native-maps#3850]
# Bug report

## Summary

I have been testing the recent Pre-release and notice that the new addressForCoordinate will always throw on iOS, I beliebe the conditional here is incorrect

https://github.com/mechazod/react-native-maps/blob/5efd3534e43ba21bffd2e64d946c7a9580b390b7/lib/ios/AirMaps/AIRMapManager.m#L575-L578

as it will throw if `coordinate != nil` which is any time coordinates are correctly added.

Below is a patch package diff solving the issue with what I believe is the correct conditional

```diff
diff --git a/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m b/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m
index 726885f..c5ce4ff 100644
--- a/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m
+++ b/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m
@@ -575,9 +575,9 @@ - (UIView *)view
         if (![view isKindOfClass:[AIRMap class]]) {
             reject(@"Invalid argument", [NSString stringWithFormat:@"Invalid view returned from registry, expecting AIRMap, got: %@", view], NULL);
         } else {
-            if (coordinate != nil ||
-                ![[coordinate allKeys] containsObject:@"latitude"] ||
-                ![[coordinate allKeys] containsObject:@"longitude"]) {
+            if (coordinate != nil &&
+                (![[coordinate allKeys] containsObject:@"latitude"] ||
+                ![[coordinate allKeys] containsObject:@"longitude"])) {
                 reject(@"Invalid argument", [NSString stringWithFormat:@"Invalid coordinate format"], NULL);
             }
             CLLocation *location = [[CLLocation alloc] initWithLatitude:[coordinate[@"latitude"] doubleValue]
```

**Comment by christopherdro** [comment]
Ping @mechazod

**Comment by mechazod** [comment]
@owinter86 I intentionally set that condition to check each statement, because some might pass invalid data for `coordinate`. I don't see any issue here. Can you point out issue will encounter of the existing condition?

**Comment by owinter86** [comment]
@mechazod if coordinate is not nil it will throw, that's the issue. It will never not throw if passing in coordinate data.

**Comment by mechazod** [comment]
@owinter86 if `coordinate` is not nil it will throw due to required property is missing. But if you're saying that user will always pass a valid data that is not `true`. Let's cut the loose here, make the PR if you want to enhance. This is a petty issue.

**Comment by owinter86** [comment]
Im sorry that you see this as a petty issue, but it simply does not work at all on iOS due to this condition. I will make a PR
