### ISSUE TITLE
hi I am also facing the same issue when I tried to implement the map

### ISSUE THREAD

**Issue by singhtrustcom** [react-native-maps/react-native-maps#3851]
hi I am also facing the same issue when I tried to implement the map
 IOS - PROVIDER_GOOGLE Showing empty map
 it only showing me the title on the bottom I waste a lot of time to debug that issue but still stuck on it 
 
 I have followed all the step which are mentioned on
  https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md
  
  and I also configured all the setting on the google side as well 
  
  I  also check if IOS Map SDK is enabled or not all other important API like place GEO. etc
  
  also added map style from both and also tried with Custom style option by JSON data 
  
  still not able to load the map ios device on real and as well as simulator 
  
  i and using ***

   "react-native": "0.63.4",

   "react-native-maps": "^0.28.0",

  
   <MapView
                provider={ PROVIDER_GOOGLE}
                style={styles.container}
                showsUserLocation={true}
            />

  I code I also find some warning like when run the project from Xcode 

  Documentation Issue Group
  ...../node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMap.m:29:

same issue on google map  ios -utills 

parameter 'inlineStyle' not found in the function declaration
...../ios/Pods/Google-Maps-iOS-Utils/src/Geometry/Model/GMUPlacemark.m:16:9: In file included from /Users/apple/Documents/GitHub/tfbrandnew/ios/Pods/Google-Maps-iOS-Utils/src/Geometry/Model/GMUPlacemark.m:16:

Parameter 'coordinates:' not found in the function declaration

maybe this will help you to better understand the bug

_Originally posted by @singhtrustcom in https://github.com/react-native-maps/react-native-maps/issues/3847#issuecomment-862168118_

**Comment by christopherdro** [comment]
Please refrain from opening up new issues if you already posted your comment in a related ticket.
