### ISSUE TITLE
[0.29.0] - Android crashes when addressForCoordinate returns empty list

### ISSUE THREAD

**Issue by owinter86** [react-native-maps/react-native-maps#3854]
# Bug report

## Summary

The new addressForCoordinate will crash on android with `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`
when moving the map to coordinates that tigger an empty list result from the geocoder.

## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. Using the new RN pre-release (0.29.0) and the new `addressForCoordinate` method, zoom all the way out and move around near the bearing sea on android

Describe what you expected to happen:

1. Invalid coordiantes or empty results should not hard crash the app but return throw and get caught in the JS code.

Describe what you actually happens:

1. The app will crash with java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by christopherdro** [comment]
Related https://github.com/react-native-maps/react-native-maps/issues/3850
