### ISSUE TITLE
userInterfaceStyle not working at all on IOS

### ISSUE THREAD

**Issue by Elowarp** [react-native-maps/react-native-maps#3858]
# Bug report

## Summary
userInterfaceStyle is not working on IOS, when I set it to "dark", it won't change and if I let the system choose, it always choose light too. I'm targeting AppleMaps.

## Environment info
(according to package.json)
react: 16.13.1
react-native: sdk 41.0.0
react-native-maps: 0.29.0

Ubuntu 20.04.2 LTS

`react-native info` output:

```bash
react-native : command not found
```

## Steps to reproduce
Insert MapView with the following code : 
```jsx 
<MapView 
    ref={(map) => { this.map = map; }}
    style={styles.mapView}
    initialRegion={this.state.region}
    showsCompass={false}
    initialCamera={this._initCamera()}
    userInterfaceStyle="dark"
/>
```
Describe what you expected to happen:

1. Using the dark mode of the AppleMaps

Describe what you actually happens:

1. The MapView use the light mode of the AppleMaps

**Comment by christopherdro** [comment]
Duplicate https://github.com/react-native-maps/react-native-maps/issues/3846

**Comment by Elowarp** [comment]
I already checked the “duplicate” thread and all informations like the example code etc but none of this are working properly, I always got the light map even after I removed the ^ before 0.29.0.

**Comment by bmovement** [comment]
@Elowarp I had the same experience... but then I remembered to `pod install`... and it worked!

**Comment by Elowarp** [comment]
Ah shit, I thought this module could be used with expo because everything else worked well... Thank you for the response !

**Comment by RichardLindhout** [comment]
Not working for me (I'm on iOS) with dark mode on and userInterfaceStyle="dark" it still shows up as dark

**Comment by RichardLindhout** [comment]
Oh I'm using Google Maps it'll only work with the native apple maps
