### ISSUE TITLE
[Marker] Width + Height  props

### ISSUE THREAD

**Issue by willparsons** [react-native-maps/react-native-maps#3860]
# Feature request
Giving width and height to a marker for the image/icon it is displaying.

## Why it is needed
Currently, there is no simple way to give the image/icon prop then declare its width/height. I know there are workarounds but they can pose more issues, like the makers not sticking to coordinates properly.

## Possible implementation
Not sure about implementation but I'm hoping it's a simple as passing those props down to be used as a styling for the image.

### Code sample
```ts
<Marker
image={require("...")}
width={50}
height={50}
/>
```

**Comment by hungdev** [comment]
+1
