### ISSUE TITLE
GeoJson polyline only tapping.

### ISSUE THREAD

**Issue by rxng8** [react-native-maps/react-native-maps#3862]
# Bug report

## Summary

The geojson layer is tappable everywhere in the layer, but I want it to be only tappable in the polyline in the Geojson layer.

## Environment info

react-native: 0.64.2
react: 17.0.1
react-native-maps: "git+ssh://git@github.com/react-native-maps/react-native-maps.git" (0.29.0 - pre-release)
Target Platform: iOS - 14.0 - iphone xs max - provider: Google Maps.

Describe what you expected to happen:

1. I expect to tap only on the polyline of the geojson.

Describe what you actually happens:

1. the tap is triggered everywhere in the geojson layer.

## Reproducible sample code

Code:
```
<Geojson 
       key={index}
       geojson={GeoJsonPath[key]} 
       strokeColor={GeoJsonColor[key]}
       fillColor={GeoJsonColor[key]}
       strokeWidth={GeoJsonWidth[key]}
       tappable={true}
       onPress={(overlay) => {
             Alert.alert("Ranh giới", GeoJsonDisplay[key])
       }}
 />
```

**Comment by Simon-TechForm** [comment]
@rxng8 if you could please provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) I would be happy to look into whether this is a bug or intended behaviour.

**Comment by rxng8** [comment]
I think I should put it like this:
- When I use the tappable feature on the GeoJson tag, it might look like an intended behavior to be tappable on anywhere inside the GeoJson region (which is the current function in `react-native-maps`).
- However, the GeoJson consists of multiple polylines and polygons, only those objects can be tappable, not the other unmarked places (even places inside the GeoJson region)

So that's the reason why I think that is a bug. Please let me know if you have any comments!

**Comment by Simon-TechForm** [comment]
Thank you for your explanation. Would you be able to provide a sample code that reproduces this, where you include everything needed to to run the example? I can't tell what geojson features are in the sample code you currently provided :)
