### ISSUE TITLE
Issue with docs regarding controlling region as state 

### ISSUE THREAD

**Issue by IPWright83** [react-native-maps/react-native-maps#3863]
# Bug report

## Summary
The docs suggest that if you want to [control the region as state](https://github.com/react-native-maps/react-native-maps#using-a-mapview-while-controlling-the-region-as-state) that you should use the `onRegionChange` event to record the `region` and set this in state. I think this should say use `onRegionChangeComplete` instead but I want to verify this before issuing a PR.

I have tried this, and essentially it doesn't allow you to interact with the map anymore - I believe because `onRegionChange` fires multiple times during a pan/zoom, causing the component to re-render after the first part, which interrupts the operation changing the region.

## Environment info

```
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.81 GB / 15.33 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /home/ian/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

```bash
"react": "17.0.2",
"react-native": "0.64.0",
"react-native-maps": "0.28.0",
```

## Steps to reproduce

1. Double click the map to zoom...

Describe what you expected to happen:

1. I expected the control to still allow zooming/panning

Describe what you actually happens:

1. The map zoomed a fraction compared to how it operated before moving the region into state.
2. Switching to `onRegionChangeComplete={onRegionChange}` however works correctly.

## Reproducible sample code

```
const MapScreen = () => {
   const [region, setRegion] = useState({
        latitude: 53.945,
        longitude: -1.0539,
        latitudeDelta: 0.015,
        longitudeDelta: 0.0121,
    });

   const onRegionChange = (region) => {
        setRegion(region);
    };

    return (

            <MapView
                style={styles.map}
                provider={PROVIDER_GOOGLE}
                region={region}
                onRegionChange={onRegionChange}
            />
    );
};
```

**Comment by adamf59** [comment]
I'm noticing the same effects you've described. Fixed using `onRegionChangeComplete` instead of `onRegionChange`.

**Comment by adamf59** [comment]
Unfortunately, I'm continuing to get "stuttering" problems where dragging will prematurely stop, even using `onRegionChangeComplete`. It's **_certainly_** less pronounced than using  `onRegionChange` though. I've attached a GIF presenting the behavior.

Are you getting the similar effects? If not it may just be my implementation... 

Either way, this may be out of scope of this issue. I'll keep playing around this afternoon.


![Screen Recording 2021-06-23 at 2 56 21 PM](https://user-images.githubusercontent.com/20647102/123153256-77026b80-d433-11eb-972f-76980b0ac80c.gif)

**Comment by bmovement** [comment]
I can confirm that the problem was worse with `onRegionChange` but still problematic with `onRegionChangeComplete`. I wonder if a recent change broke this?

**Comment by adamf59** [comment]
> I can confirm that the problem was worse with `onRegionChange` but still problematic with `onRegionChangeComplete`. I wonder if a recent change broke this?

Thanks for confirming. Since this issue refers to the docs, I've added a new issue to address the problem we're experiencing.

**Comment by bmovement** [comment]
@adamf59 FYI I was able to work around this in my scenario using an `AnimatedRegion` and the `onRegionChange` callback. I couldn't get `addListener` to work, but I guess since I'm made aware of changes through `onRegionChange`, that's not really an issue?

**Comment by adamf59** [comment]
@bmovement I'll give that a shot in a bit. Will report back. You just setting the region prop in `MapView` to an Animated Region? I haven't had to mess with Animated Region before, so I'm unaware of it's implementation.

**Comment by bmovement** [comment]
Basically, but you have to use the Animated MapView.

`import { Marker, Animated as MapView, AnimatedRegion } from 'react-native-maps';`

And instead of storing the region in state, I'm memoizing it, and calling `setValue` on it.

I also noticed the issue that we had problems with seems to occur anytime you cause a rerender. For example, I want a "Search This Area" button to appear if the user pans too far from their original search. Updating this button's visibility in state was causing a rerender and killing the pan, just as before.
