### ISSUE TITLE
Dragging prematurely stops when using onRegionChangeComplete to update region state

### ISSUE THREAD

**Issue by adamf59** [react-native-maps/react-native-maps#3864]
# Bug report

## Summary

When dragging the map, the expected behavior is for the map to move smoothly with the user's finger throughout the whole movement. However, when using `onRegionChangeComplete` to update a state for the maps `region`, the map will randomly stop moving, despite the user's drag/pinch to zoom motion not yet being complete. The attached GIF presents the behavior. This effect was observed only on iOS.

![Screen Recording 2021-06-23 at 2 56 21 PM](https://user-images.githubusercontent.com/20647102/123153256-77026b80-d433-11eb-972f-76980b0ac80c.gif)

## Environment info

`react-native info` output:

```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 381.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```bash
react-native@0.64.2
react@16.13.1
react-native-maps@0.29.0
```

## Steps to reproduce

1. Implement the MapView according to the docs, with a change to account for the issue reported in #3863 
2. Attempt to drag the map or zoom in and out.

Describe what you expected to happen:

1. User begins dragging the map or pinching inward and outward to zoom the map
2. The map smoothly zooms in and out while pinching. The map translates smoothly when dragged. The map moves throughout the user's entire motion.

Describe what you actually happens:

Observe that the map will stop moving before the user's motion is complete. This is coupled with a "stuttering" effect of the map occasionally. 

## Reproducible sample code
```js

const styles = StyleSheet.create({
  map: {
    ...StyleSheet.absoluteFillObject,
    height: '100%',
}
});

const ClubLocationMap = () => {
   const [mapRegion, setMapRegion] = useState({
        latitude: 42.794295,
        longitude: -72.2781,
        latitudeDelta: 0.01,
        longitudeDelta: 0.1,
    });

   const onMapRegionChanged = (new_region) => {
        setMapRegion(new_region);
    };

    return (

            <MapView
                style={styles.map}
                region={mapRegion}
                onRegionChangeComplete={onMapRegionChanged}
            />
    );
};
```

**Comment by ayhoung** [comment]
I'm getting this issue as well! not just with dragging - zooming in and out also prematurely stops as well, giving a glitchy experience

**Comment by ayhoung** [comment]
i realized it has something to do with setting state within the function call - if setState is removed, it doesn't stop anymore

**Comment by elsurudo** [comment]
Same issue here, I wasn't yet able to find a resolution, given that I still want to store the region in react's state.

**Comment by BaderSerhan** [comment]
Same, I'm having multiple issues using this library on iOS!

**Comment by adamf59** [comment]
Any update here?

**Comment by israelidanny** [comment]
Having the same issue. It makes for a quite terrible user experience.

**Comment by mattiaefesto** [comment]
Same here :(

**Comment by mattiaefesto** [comment]
I've fixed this behavior by removing region={region} from the `MapView` tag and showing the map only when I have all the info I need:

```

const [region, setRegion] = useState(undefined);
const [gotUserLocation, setGotUserLocation] = useState(false);

useEffect(() => {
    setTimeout(checkUserLocation, 400);
  }, []);

const checkUserLocation = async () => {
    const l = await LocationService.getUserLocation();
    if (l) {
      setGotUserLocation(true);
      // this needed to be, to zoom on the user
      const r = {
        latitude: l.latitude,
        longitude: l.longitude,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      };
      setRegion(r);
    }
  };

{gotUserLocation && region && (
        <MapView
          ref={mapRef}
          style={styles.map}
          showsUserLocation={true}
          userLocationPriority="high"
          showsPointsOfInterest={true}
          showsMyLocationButton={true}
          toolbarEnabled={false}
          initialRegion={region}
          onRegionChangeComplete={onRegionChange}
          mapType="satellite"
        />
      )}
```

**Comment by elsurudo** [comment]
@mattiaefesto since you are setting `initialRegion` attr and not `region`, this mean you can't change the region after the fact, right?

**Comment by mattiaefesto** [comment]
Yep, but you can get the new region from `onRegionChangeComplete` method and do your stuff with the region passed to the function, without the need to set the region.
For me, this is working.

**Comment by elsurudo** [comment]
Yes, but then are you able to _change_ the region that the map is showing afterwards?

**Comment by mattiaefesto** [comment]
The region is changed without the need to re-set the region
