### ISSUE TITLE
Map view doesn't appear on the screen (GRAY SCREEN)

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [react-native-maps/react-native-maps#3868]
Dear There,

I am trying you use Map in my application, but it doesn't appear

**app.json**
```
{
  "name": "myapp",
  "version": "1.0.7",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    ....
    "react": "^17.0.1",
    "react-native": "^0.64.2",
    "react-native-webview": "^11.6.4",
   ...
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "jetifier": "^1.6.8",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Note: I did all the steps in documentation even that it still not working, what should I do ?

**Comment by javierdac** [comment]
I have the same problem

**Comment by javierdac** [comment]
i fixed the same issue with this:

[Google Maps SDK Android](https://console.developers.google.com/apis/library/maps-android-backend.googleapis.com/)
[Google Maps SDK iOS (if required)](https://console.developers.google.com/apis/library/maps-ios-backend.googleapis.com)

**Comment by MedNabilEssefaihi** [comment]
Dear @javierdac ,

First of all, thank you so much for your answer. The problem in my case was the SHA-1, I used a wrong for R**estrict usage to Android apps**.

**Comment by jboteros** [comment]
> i fixed the same issue with this:
> 
> [Google Maps SDK Android](https://console.developers.google.com/apis/library/maps-android-backend.googleapis.com/)
> [Google Maps SDK iOS (if required)](https://console.developers.google.com/apis/library/maps-ios-backend.googleapis.com)

Thank you 👍
