### ISSUE TITLE
onRegionChangeComplete repeatedly called at max zoom

### ISSUE THREAD

**Issue by IPWright83** [react-native-maps/react-native-maps#3869]
## Summary

When controlling the region using state using the `onRegionChangeComplete` at maximum zoom there appears to be a cycle where `onRegionChangeComplete` is called continuously causing a slight panning affect. This doesn't happen at any other zoom level. It looks like maybe due to a round issue based on the panning affect?

## Environment info
```bash
"react": "17.0.2",
"react-native": "0.64.0",
"react-native-maps": "^0.28.0",
```

`react-native info` output:
```
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.38 GB / 15.33 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /home/ian/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps to reproduce

1. Add a `<MapView>` and subscribe to the `onRegionChangeComplete` callback
2. Call a `setState` like function in the `onRegionChangeComplete` callback and set the `region` prop on the `MapView` based off this
3. Zoom the map in to the highest zoom

Describe what you expected to happen:

1. The `onRegionChangeComplete` callback gets called one at each zoom level

Describe what you actually happens:

1. The `onRegionChangeComplete` callback is called one at each zoom level until the last
2. On the last level, `onRegionChangeComplete` is called continuously causing a slight panning affect.

![MapScroll3](https://user-images.githubusercontent.com/1374775/123630991-1f3a7a80-d80e-11eb-8fe5-c2324a906144.gif)

## Reproducible sample code

https://snack.expo.io/MyhM3pbAJ

**Comment by raulghm** [comment]
The same problem here :(

**Comment by gurpreetsingh2808** [comment]
Same problem.

**Comment by gurpreetsingh2808** [comment]
Same problem. I used custom logic here.

<MapView minZoomLevel={10} maxZoomLevel={30} showsUserLocation={true} region={markerCoordinate} animateToCoordinate showsMyLocationButton onRegionChangeComplete={shouldUpdateLocation} > </MapView>


` 
  const {
    markerCoordinate,
    changeMarker
  } = props;

 const shouldUpdateLocation = (mapData) => {
    // To prevent unnecessary calls to location apis
    if (Math.abs(mapData.latitude - markerCoordinate.latitude) * 100000 > 2) {
      console.log('[shouldUpdateLocation] update mapData ', mapData);
      if (changeMarker) {
        changeMarker(mapData)
      }
    }
  }`

**Comment by mattiaefesto** [comment]
Any update?

**Comment by AliuDardan** [comment]
Still the same problem :(
