### ISSUE TITLE
Please advise when will v0.29.0 tag be released? Currently it's labeled prerelease for 23 days.

### ISSUE THREAD

**Issue by Shahriar87** [react-native-maps/react-native-maps#3872]
# Feature request
Please advise when will v0.29.0 tag be released? Currently it's labeled prerelease for 23 days.

## Why it is needed

We are looking forward to upgrade to v0.29.0 to have fixes for some current bugs. Currently, we see this being published in NPM but are not sure why it is hanging with a Prerelease tag? 

Is this just an overlook or is there a valid reason for the tag v0.29.0 to be not labeled as Latest Release?

Thanks in advanced for an update on this.

**Comment by christopherdro** [comment]
You can still install the pre release. It’ll be published as the latest versions once properly tested.
