### ISSUE TITLE
loadingEnabled is not working for me 

### ISSUE THREAD

**Issue by Kaung-Htet-Naing** [react-native-maps/react-native-maps#3873]
# Bug report

## Environment info

`react-native info` output:

```bash
 "react": "16.13.1",
 "react-native": "~0.63.4",
 "react-native-maps": "0.27.1",
```
## Reproducible sample code

 <MapView
        ref={mapRef}
        onMapReady={() => {
          setMapLoading(false);
        }}
        showsUserLocation
        showsMyLocationButton
        loadingEnabled
        zoomEnabled
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        followsUserLocation
        initialRegion={{
          latitude: userLocation.latitude,
          longitude: userLocation.longitude,
          latitudeDelta: 1,
          longitudeDelta: 1
        }}
      >

**Comment by Punksmurf** [comment]
Not a maintainer, but could you maybe explain what it's doing and what you were expecting it to do? And, while you're at it, place the code in a code block? Cheers!
