### ISSUE TITLE
Change default appcompat to androidx instead android support

### ISSUE THREAD

**Issue by doniwinata0309** [react-native-maps/react-native-maps#3875]
# Feature request

## Why it is needed

Hi currently the default version for android support is 28.0.0 --> https://github.com/react-native-maps/react-native-maps/blob/master/lib/android/build.gradle#L20

`def appCompatLibName =  (supportLibMajorVersion < 20) ? "androidx.appcompat:appcompat" : "com.android.support:appcompat-v7"` this code will return com.android.support as default.

Since we are using androidX and want to disable Jetifier, we need to use androidx.appcompat:appcompat instead com.android.support:appcompat-v7 as default. This can be fix if we change the version to
`def supportLibVersion = safeExtGet('supportLibVersion', '1.2.0') `.

Do you want to consider change into that version instead ? sooner or later all will use android instead android support. 
Thanks.

**Comment by aliraza-noon** [comment]
also this will no longer build in the future because jetifier is being sunset and being removed from cli.

https://github.com/react-native-community/cli/issues/1409

**Comment by aliraza-noon** [comment]
not stale

**Comment by Simon-TechForm** [comment]
Closed by #4146.
