### ISSUE TITLE
Blurry satellite tiles on iOS

### ISSUE THREAD

**Issue by MalinKildal** [react-native-maps/react-native-maps#3876]
# Bug report

## Summary

When using the google map on several screens the tiles get more and more blurry when navigating back and forth. 

## Environment info

```bash
react-native: 0.63.4
react: 16.13.1
react-native-maps: 0.27.1
@react-navigation/native: 5.8.9
```

## Steps to reproduce

1. Have one main screen with a map.
2. Hva another screen, a modal screen, or something also with a map. The maps should be centered to the same place.
3. When navigating back and forth between the screens the map tiles on the secondary screen will get more and more blurry.

Notes: 
- It only happens one some phones, and some simulators. I have not found it to be version specific og phone specific. 
- It does not help to make the main map unmountOnBlur.
- It does not have anything to do with the polygon in the map. The result is the same for empty maps.
- Only fix is to restart the app.

![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 10 59 52](https://user-images.githubusercontent.com/10546246/124446270-8f9e4a00-dd80-11eb-8dd3-3cfa31eab4b1.png)
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 11 00 00](https://user-images.githubusercontent.com/10546246/124446288-94fb9480-dd80-11eb-96e9-f2654180f4c2.png)
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 11 00 08](https://user-images.githubusercontent.com/10546246/124446291-95942b00-dd80-11eb-8420-22803f0da883.png)
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 11 00 11](https://user-images.githubusercontent.com/10546246/124446293-95942b00-dd80-11eb-89a2-e49f3c3c4475.png)

**Comment by JimTeva** [comment]
@Simon-TechForm, @lelandrichardson, any ideas how to fix this?
