### ISSUE TITLE
fitToCoordinates() does not work correctly with a MapView in a Modal if it does not have 100% height on iOS

### ISSUE THREAD

**Issue by robert-nash** [react-native-maps/react-native-maps#3882]
# Bug report

## Summary

This seems like a strange bug to me so it would be helpful to get some insight. I have tried to reduce the reproduceable demo as much as possible but due to the strange circumstances there is a bit of surrounding code.

I have noticed that fitToCoordinates was not working on iOS in my app but it was on Android. I am using fitToCoordinates to ensure that a circle drawn on the map fits within the map. However, on iOS the map is being centred a moderate distance away from the centre point of the circle.  After a lot of investigation, I found that the problem only occurred when my MapView did not take up the full height of the Modal within which it is contained. This does not seem to be a problem if the Modal is excluded.

## Environment info
"react-native": "0.63.4",
"react": "16.13.1",
"react-native-maps": "0.27.1",

Target Platform iOS 14.6 - GoogleMaps
## Steps to reproduce

Place an absolutely positioned MapView inside a Modal and set its height using top and bottom.

Describe what you expected to happen:

This snack shows what should happen with the circle centred on screen after pressing "Fit map to circle".

https://snack.expo.io/@staxy/react-native-maps-fittocoordinates-demo---works

![image0](https://user-images.githubusercontent.com/1884158/124759220-5227f100-df27-11eb-9638-c1859694b0c2.png)

Describe what you actually happens:

This snack shows what happens if the height of the MapView is not set but top and bottom positions are used instead. The map is centred a distance from the center of the circle

https://snack.expo.io/@staxy/react-native-maps-fittocoordinates-demo---does-not-work

![image1](https://user-images.githubusercontent.com/1884158/124759395-7f749f00-df27-11eb-9b83-a420b507f130.png)
## Reproducible sample code

https://snack.expo.io/@staxy/react-native-maps-fittocoordinates-demo---does-not-work

**Comment by ArturoTorresMartinez** [comment]
I got the same issue, anyone solved this?

**Comment by Simon-TechForm** [comment]
I wanted to look into this, but I'm struggling to reproduce the issue. Are you reproducing the issue consistently? I just ran the does-not-work snack 3 times and they all gave the desired result 🤔

**Comment by Simon-TechForm** [comment]
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Comment by ApluUalberta** [comment]
> I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

This is reproducible if you adjust the height styling prop in the snack example, here.

Initial:
![image](https://github.com/react-native-maps/react-native-maps/assets/39037565/abe419fb-1fb8-41e1-973e-0e9c76e0131f)

This works fine as it encompasses the entire modal content. Here is the result:

![image](https://github.com/react-native-maps/react-native-maps/assets/39037565/1eb24622-1958-41f3-a8a1-ba9ce489f553)



Let's try to edit the component height:
![image](https://github.com/react-native-maps/react-native-maps/assets/39037565/f9da929e-b014-48f6-b282-d7da2192a370)

This yields this:
![image](https://github.com/react-native-maps/react-native-maps/assets/39037565/251fd118-d398-4250-83ae-2e25416907b3)

**Comment by ApluUalberta** [comment]
I'll create another issue that references this one
