### ISSUE TITLE
Getting an error while generating a polyline in a mapview

### ISSUE THREAD

**Issue by meghaboggaram** [react-native-maps/react-native-maps#3883]
# Bug report

## Summary
I'm getting this error:

Error while updating property 'lineCap' of a view managed by: AIRMapPolyline

null

Attempt to invoke virtual method 'void com.google.android.gms.maps.model.u.g(java.util.List)' on a null object reference

## Environment info

      react-native: 0.63.2
      react: 16.9.35
      react-native-maps: tried with both 0.28.0 and 0.29.2

## Steps to reproduce
Here is my code:

if (loadMap) {
    return (
      <MapView
        region={{
          latitude: 13.0036939,
          latitudeDelta: 0.01339980000000196,
          longitude: 77.5622523,
          longitudeDelta: 0.028350600000010218,
        }}
        style={[mapStyle, { marginBottom: marginBottom }]}
        showsCompass={true}
        showsMyLocationButton={true}
        showsUserLocation={true}
      >
        <Marker
          coordinate={currentLocation}
          image={require('../assets/car-sideview-green.png')}
        />
        <Marker coordinate={destLocation} />

        <Polyline
          coordinates={[
            {
              latitude: 13.0033584,
              longitude: 77.5716715,
            },
            {
              latitude: 13.0033367,
              longitude: 77.5712459,
            },
            {
              latitude: 13.0072072,
              longitude: 77.57116169999999,
            },
            {
              latitude: 13.0081605,
              longitude: 77.5545045,
            },
            {
              latitude: 13.0000863,
              longitude: 77.5528021,
            },
            {
              latitude: 12.9999731,
              longitude: 77.5532415,
            },
            {
              latitude: 12.9992273,
              longitude: 77.55309450000001,
            },
          ]}
          strokeColor={colorPalettes.greenPalette.medium}
          strokeWidth={4}
        />
      </MapView>
    );
  } else {
    return (
      <View
        style={[mapStyle, { alignItems: 'center', justifyContent: 'center' }]}
      >
        <LoadingCircle />
      </View>
    );
  }

The code was working perfectly fine with SDK version 40 and react-native-maps@0.27.1
When I updated SDK to version 42 and the corresponding packages and react-native-maps, I started to get the following error:

If I use <Polygon> instead of <Polyline>, with the rest of the props and code same, the map is displayed with the markers and polygon without any error. I'm having problem only with Polyline

I have attached screenshot of the error thrown and the stacktrace.
![Screenshot_20210707-184743](https://user-images.githubusercontent.com/67511600/124770394-eca02880-df57-11eb-85ae-77d1145f6ed1.jpg)
![Screenshot_20210707-184755](https://user-images.githubusercontent.com/67511600/124770443-f6299080-df57-11eb-8bd0-f21916baf140.jpg)

**Comment by meghaboggaram** [comment]
This code works fine when using Polygon instead of Polyline, rest being the same..

**Comment by douglaslondrina** [comment]
I'm having this problem too, just updated to Expo 42 and react-native-maps 0.28.0 (current version shipped in Expo).
Any Polyline on Android will pop this error and crash.

**Comment by christopherdro** [comment]
duplicate https://github.com/react-native-maps/react-native-maps/issues/3823

**Comment by Jamsanz** [comment]
`<MapViewDirections
      lineDashPattern={[0]}
      origin={origin}
      destination={destination}
      apikey={GOOGLE_MAPS_APIKEY}
      
    />`
Try this. It solved my own problem but the line would dash.

**Comment by Jamsanz** [comment]
<MapViewDirections
      lineDashPattern={[0]}
      origin={origin}
      destination={destination}
      apikey={GOOGLE_MAPS_APIKEY}
    />

Try this. It solved my problem but the line would dash.
