### ISSUE TITLE
Publish new release 0.29 -> 0.29.2

### ISSUE THREAD

**Issue by SergeySlutskiyGowombat** [react-native-maps/react-native-maps#3885]
On the npm registry stored old version dated by february. but on the repo I see tags 0,29 and further, is there a way to publish updated package to npm registry?

**Comment by Quentinb** [comment]
I'm also patiently waiting for the npm version to update so that the package can be installed with react > 7.x

**Comment by christopherdro** [comment]
You can install the pre-release using `npm install react-native-maps@next` or `yarn add react-native-maps@next`, or simply specify the version in your package.json.
