### ISSUE TITLE
GeoJSON + onPress + Zoom. onPress event sometimes not fires

### ISSUE THREAD

**Issue by DenysMoro** [react-native-maps/react-native-maps#3887]
# Bug report

## Summary
I've noticed interesting behaviour with GeoJSON component + onPress and Zoom. (I've created reproducible repo and attached it below)
Sometimes onPress event not fires at all. For example:
1. We have map with zoom, let's say, 1. `onPress` event fires
2. User zoom in a little bit (x2-3-4-...) and `onPress` event not fires when he is trying to tap in the middle of a polygon
3. User trying to press/tap closer to `stroke` - `onPress` event fires

I've noticed that if user zoomed a lot, then he need to click/press/tap as closer as possible to the stroke. Is it okay? I thought that user should be able to click everywhere inside polygon

## Environment info
`react-native info` output:
```bash
"react": "16.13.1",
"expo": "41.0.1",
"react-native": "~0.63.2",
"react-native-maps": "0.29.2",
```

## Steps to reproduce
Please clone my reproducible example and play with it. I've attached video to the issue

Describe what you expected to happen:
`onPress` fires every time when I'm pressing inside polygon, no matter - closer to stroke or not

Describe what you actually happens:
`onPress` event is unstable and fires only closer to Polygon stroke

## Reproducible sample code
https://github.com/DenysMoro/rnmaps-expo-geojson-onpress

https://user-images.githubusercontent.com/77282657/125452651-a85621ac-9b70-460d-8e36-961c3657c572.mov

**Comment by DenysMoro** [comment]
Okay. I converted LineString geometry type to Polygon and onPress event started to work as expected.

**Comment by marexv** [comment]
> Okay. I converted LineString geometry type to Polygon and onPress event started to work as expected.

How did you covert it?
