### ISSUE TITLE
rounded corners

### ISSUE THREAD

**Issue by avlonder** [react-native-maps/react-native-maps#3888]
# Bug report

## Summary

Previously, if you wanted to get a MapView with rounded corners, you could wrap it inside a View component with borderRadius and hidden overflow, e.g. 
```
<View style={{ borderRadius: 20, overflow: 'hidden' }}>
  <MapView
     style={{ width: '90%', aspectRatio: 1 }}
     provider={PROVIDER_GOOGLE}/>
</View>
```
However, since Android API level 30, the map still shows the "Google" label, but the map itself is blank.

## Environment info
```
react-native: 0.63.4
react: 16.13.1
react-native-maps: 0.28.0
```

**Comment by KrisLau** [comment]
@losthakkun `borderRadius` works but specifying the corner doesn't weirdly enough

**Comment by Simon-TechForm** [comment]
I don't think that the map being blank has anything to do with the borderRadius. Your code sample is working as expected on my end.

I'm going to close this for now, but if you think this is still relevant and releated to react-native-maps, please feel free to open a new issue.
