### ISSUE TITLE
<MapView /> doesn't works in Modal Component [Android]

### ISSUE THREAD

**Issue by Shair17** [react-native-maps/react-native-maps#3890]
# Bug report

## Summary
I'm using <MapView /> component from react-native-maps 0.28.0, So I decided to draw that component into a <Modal /> for get user location and so on, I'm using <Modal /> component that comes from -> react-native-magnus (https://magnus-ui.com/docs/modal/) but I don't think that's the problem, because that magnus modal component it's based on react-native-modal. I try to set `flex: 1` to <MapView /> Component, I've checked the permissions, but it doesn't works for me.

## Environment info
OS: Windows 10
Platform: Android (Real Phone Xiaomi Redmi Note 8 Pro)
React: 17.0.1
React Native: 0.64.1
React Native Maps: 0.28.0
React Native Magnus: 1.0.62
React Native Modal: 12.0.2

`System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
    Memory: 2.81 GB / 7.92 GB
Binaries:
    Node: 14.17.3 - ~\AppData\Local\Temp\yarn--1626544554660-0.5613243802934613\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1626544554660-0.5613243802934613\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Intel x86 Atom_64
    Android NDK: Not Found
    Windows SDK: Not Found
IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_262 - C:\Program Files\OpenJDK\openjdk-8u262-b10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by Shair17** [comment]
It should be clarified that it works perfectly is a <View /> component or within a React Navigation Tab and so on, but within a <Modal /> it does not work.

**Comment by Simon-TechForm** [comment]
I just did a quick test, the following works perfectly fine for me:
```ts
import React from 'react';
import {StyleSheet, Modal, View} from 'react-native';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <View style={styles.container}>
      <Modal visible={true}>
        <MapView style={styles.mapView} />
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mapView: {
    flex: 1,
  },
});
```

I'm going to close this for now, as I don't think it's related to react-native-maps. If you believe that this is still relevant and related to react-native-maps, please feel free to open a new issue.
