### ISSUE TITLE
Error to use polylines with new Expo SDK (Android Only)

### ISSUE THREAD

**Issue by gustrigoni** [react-native-maps/react-native-maps#3892]
I upgrade my React Native and Expo SDK to 42.0 and I still having this error:
![error](https://user-images.githubusercontent.com/50127691/126208738-b07e5863-2ca7-4b98-b0ec-3bac79db3e2c.png)

My react-native-maps version in app.json is ^0.29.2, can you guys fix it? I need it urgently.

**Comment by christopherdro** [comment]
Duplicate https://github.com/react-native-maps/react-native-maps/issues/3823
