### ISSUE TITLE
Package doesn't work with Google-Maps-iOS-Utils (~> 3.0.0)

### ISSUE THREAD

**Issue by n3rd253** [react-native-maps/react-native-maps#3893]
# Bug report

Ran into this issue http://5.9.10.113/66966465/react-native-maps-ios-build-issues-when-using-use-frameworks-linkage-stati when installing https://github.com/prscX/react-native-app-tour.

Found a fix which involves updating to use Google-Maps-iOS-Utils 3.0.0 https://github.com/googlemaps/google-maps-ios-utils/issues/23#issuecomment-579467769, however when I go to utilize as prescribed, I receive this issue running pod install

[!] CocoaPods could not find compatible versions for pod "Google-Maps-iOS-Utils":
  In Podfile:
    Google-Maps-iOS-Utils (~> 3.0.0)

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.28.0, which depends on
      Google-Maps-iOS-Utils (= 2.1.0)

Specs satisfying the `Google-Maps-iOS-Utils (~> 3.0.0), Google-Maps-iOS-Utils (= 2.1.0)` dependency were found, but they required a higher minimum deployment target.

## Environment info

<!--
  Please specify the react, react-native, react-native-maps versions, eg:

    "react": "16.11.0",
    "react-native": "0.62.2",
      "react-native-maps": "github:react-native-community/react-native-maps",

  

    Target Platform: --simulator="iPhone 11 Pro Max (13.7)"

    Using GoogleMaps

**Comment by christopherdro** [comment]
We should probably update the podspec file [here](https://github.com/react-native-maps/react-native-maps/blob/master/react-native-google-maps.podspec#L21) but will need to test for any breaking changes.

**Comment by n3rd253** [comment]
@christopherdro yeah would be GoogleMaps 3.7.0 and iOS-Utils 3.0.0

**Comment by christopherdro** [comment]
@n3rd253 can you submit a pull request with those updated?

**Comment by Miyagee** [comment]
Any activity on this one @christopherdro? Ran into aa similar problem as OP.

**Comment by Miyagee** [comment]
It seems like the only breaking change listed in [v3.0.0.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v3.0.0) is `update GMUFeature interface to conform to spec #rfc7946`. Not sure if that breaks anything in react-native-maps? The rest seems to be bugfixes and new features.
