### ISSUE TITLE
MapView onPress Delay on iOS and Android 

### ISSUE THREAD

**Issue by chipmunkcode** [react-native-maps/react-native-maps#3897]
I don't understand why #833 the issues still exist and is closed for years and there is no workaround?
When I onPress the MapView event, the callback takes about half a second until it fires.
Why is this happening? Is this because it waits for a doublePress to recognize? Is there a way to turn it off?

Issue is on Apple maps and Google maps on iOS and Android equally.
I expect it to be immediately to trigger the callback when I press/tap on the map....

Any ideas?

**Comment by jstnwang0** [comment]
I just found a workaround. You can wrap the <MapView> in a <Pressable>. The <Pressable> forwards all of the touches to the <MapView> still, but has its own prop for onPressIn.

**Comment by cheynewallace** [comment]
@jstnwang0 got an example of this?  When I try this, the map is still on top, so the press events are sent to the map, not the pressable (it works though if I press on the very outer edges where the pressable is overlapping)

**Comment by saransh-malik** [comment]
Yup, this issue still is existing and there seems to be no good workaround for this.

**Comment by laurens-lamberts** [comment]
We are encountering this delay with our implementation as well.
Unfortunately the suggested pressable-around-mapview workaround won't be feasible for us, as we need the exact coordinates of the location tapped. Deriving that from a pressable event based on the region would be a last resort, but quite a nasty solution.

Any chance that there will be a fix for this in the future?
We find the react-native-maps package very useful. Thanks for all the hard work!

**Comment by mikescott** [comment]
I'm having tihs issue and wrapping the MapView in Pressable doesn't make a difference

**Comment by EthanDM** [comment]
Wrapping in a Pressable works if you need logic that isn't exposed by the MapView onPress event. Otherwise, I'm still seeing a delay.
