### ISSUE TITLE
ld: library not found for -lDoubleConversion - iOS

### ISSUE THREAD

**Issue by Vaishnavi0630** [react-native-maps/react-native-maps#3898]
Hi,

After integrating maps into expo project I am getting below error for another library in iOS 

ld: library not found for -lDoubleConversion
<img width="891" alt="Screenshot 2021-07-27 at 4 27 46 PM" src="https://user-images.githubusercontent.com/33316110/127142898-93209a82-c133-4788-96f4-b5ed36f66359.png">

**Comment by norflin321** [comment]
I solved by running Xcode using Rosetta
