### ISSUE TITLE
MapView onPress not precise when clicking next to Marker

### ISSUE THREAD

**Issue by chipmunkcode** [react-native-maps/react-native-maps#3899]
I am setting the marker and changing its position when onPressing on the `MapView`.
However when I am close to a marker and want to change the position right next to it, the MapView onPress doesn't give me the right latitude and longitude. Only when I onPress a few more inches next to the Marker it works. (see the attached video)

This is quite annoying, because I can't really set the marker position properly when I want to change my position just slightly.

Is there a way to deactivate the "invisible radius" around the Marker? 

```js
const Home = () => {
  const [location, setLocation] = useState({ lat: 48, lng: 10 });

  const newPosition = ({ nativeEvent }) => {
    if (nativeEvent.coordinate) {
      const { latitude, longitude } = nativeEvent.coordinate;
      alert(`pressed: lat:${latitude}, lng:${longitude}`);
      setLocation({
        lat: latitude,
        lng: longitude,
      });
    }
  };


  return (
    <View style={styles.container}>
      <MapView style={styles.map} onPress={newPosition}>
        <Marker
          coordinate={{ latitude: location.lat, longitude: location.lng }}
        ></Marker>
      </MapView>
    </View>
  );
};
```

https://user-images.githubusercontent.com/86783532/127149349-dcc85e43-9c1d-4412-832f-68d875822534.mov

**Comment by ftaibi** [comment]
same, any solution mate?

**Comment by Simon-TechForm** [comment]
Unfortunately this is the native behaviour of Apple Maps. And there's a simular "issue" on google maps. See (https://issuetracker.google.com/issues/35823783). I'm going to close this for now, as there's not a lot to do.
