### ISSUE TITLE
Index: 2, Size: 0 error when Marker component is mounted on android.

### ISSUE THREAD

**Issue by SocialAnxty** [react-native-maps/react-native-maps#3902]
## Summary

Whenever the marker component is mounted, the app gives me the error here: https://i.imgur.com/Awhqn20.png

It gives very little details on the issue, it just says index: 2, size: 0.

I have narrowed it down to being caused by the marker component itself, no matter what props I pass to it or how I pass those props to it, if the marker component is loaded in any way with any data, this error happens.

## Environment info

"react-native": "0.64.1",
"react": "17.0.1",
"react-native-maps": "^0.28.0",

Only happens on Android, does not seem to matter which version it happens on every android version I tried so far.

## Steps to reproduce

```
 <MapView
              //showsUserLocation={true}
              //userLocationUpdateInterval={60000}
              style={{width: '100%', height: '100%'}}
              initialRegion={{
                latitude: markers[0] ? markers[0].location.lat : 37.78825,
                longitude: markers[0] ? markers[0].location.lng : -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}>   {currentActiveWorkers.map((worker, index) => (
                <View
                  key={worker.location.latitude + worker.location.longitude}>
                  <MapView.Marker
                    key={worker.location.latitude + worker.location.longitude}
                    onCalloutPress={() => console.log(worker.location)}
                    coordinate={{
                      latitude: worker.location.latitude,
                      longitude: worker.location.longitude,
                    }}
                    title={worker.name}
                    description={'Currently on route!'}>
                    <View
                      style={{
                        width: 50,
                        height: 50,
                        borderWidth: 2,
                        borderColor:
                          worker.workerUid == route.params.value.uid
                            ? 'blue'
                            : 'green',
                        borderRadius: 50,
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}>
                      <View
                        style={{
                          width: 20,
                          height: 20,
                          borderWidth: 2,
                          borderColor:
                            worker.workerUid == route.params.value.uid
                              ? 'blue'
                              : 'green',
                          borderRadius: 50,
                          alignItems: 'center',
                          justifyContent: 'center',
                          backgroundColor:
                            worker.workerUid == route.params.value.uid
                              ? 'blue'
                              : 'green',
                        }}>
                        <Text style={{color: 'white'}}>
                          {worker.name.substring(0, 1)}
                        </Text>
                      </View>
                    </View>
                  </MapView.Marker>
                </View>
              ))}
      </MapView>
```

I just have a basic setup, I am calling MapView and inside of it the MapView.Marker;

I also have tried just using the Marker component via importing it on its own and doing <Marker> but that also causes the same issue so its not that.

I have tried everything, even removing the marker from the map and just adding a single marker just to test it out. If any marker is loaded, the error happens. Even if I add the coordinate stuff from the example it happens. No matter what if the marker is mounted it gives the error.  Only on android too, on iOS everything works perfectly. Does anyone have any ideas on how I can fix this? Its driving me mad I have already spent abunch of hours trying to figure it out. Thanks!

**Comment by mangkoran** [comment]
Currently encountering this issue too.

**Comment by Simon-TechForm** [comment]
I'm struggling to reproduce this. Can any of you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? There's quite a bit going on in the example provided currenly.

**Comment by Gaurang-786** [comment]
@Simon-TechForm  you found any solution ?

**Comment by Triggs125** [comment]
@Simon-TechForm @SocialAnxty Was a solution found to this? I'm seeing this error as well.

**Comment by andersoncaramos** [comment]
@Triggs125 this is it! thanks a lot
