### ISSUE TITLE
Slow performance using markers's children

### ISSUE THREAD

**Issue by gustrigoni** [react-native-maps/react-native-maps#3904]
# Bug report
## Summary
I am working in a project that I need to use markers with SVG, for that I am using the SVG as a marker child, but that has implied on a slow perfomance when many markers are displayed on the map. Is there a better way to solve this? I got an example from the docs and the problem is not only with SVG, even a simple View can reproduce it.

## Environment info

    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
    react: 16.13.1
    react-native-maps: ^0.28.0
    expo: ~42.0.1
     
    # device
    Samsung Galaxy A71 (SM-A715F)

## Steps to reproduce
1. Clone the repository from https://github.com/gustrigoni/react-native-maps-report
2. Choose how many markers do you want to add in the map 
![image](https://i.imgur.com/YvzAQS2.jpg)
3. Press GO to add the markers on the map
4. Press in the marker icon to change the marker component
![normal](https://imgur.com/W9RLIup.jpg))
![view child](https://imgur.com/2g9rBde.jpg))
![svg child](https://i.imgur.com/GizrnPk.jpg)

## Conclusion
After 5000 makers with children in the map the app crashes.
**Important: I'm using React Memo in the components**

**Comment by yoann84** [comment]
You might want to use react native map clustering if you have to display a lot of markers : https://github.com/venits/react-native-map-clustering#props

**Comment by gustrigoni** [comment]
> You might want to use react native map clustering if you have to display a lot of markers : https://github.com/venits/react-native-map-clustering#props

I've made my use case on the example, on our application, we need a svg on the marker, you can see that with 20 markers the performance is already affected, so there is not really much that clustered markers could do. It looks like a rendering issue on the map.

**Comment by CristyTarantino** [comment]
We are facing exactly the same issue. It used to work fine in version `0.27.1`.

**Comment by maullerz** [comment]
Try making `tracksViewChanges={false}` prop for Marker component.
It helps in my case - also have custom View as children.

**Comment by danieldanielecki** [comment]
Tip: use https://github.com/venits/react-native-map-clustering for clustering your markers. It has improved my app significantly, I'm handling thousands of markers.

**Comment by 0xcD3v** [comment]
> 

I set this to false after that some UI Markers doesn't fully render
