### ISSUE TITLE
Not able to visualize direction user is currently facing

### ISSUE THREAD

**Issue by js1998** [react-native-maps/react-native-maps#3905]
# Bug report

## Summary
When showing a users location, the direction a user is facing is not shown in appleMaps. It's currently only showing the default marker without the direction of where a user is facing.
<img width="51" alt="Screen Shot 2021-07-30 at 5 25 29 PM" src="https://user-images.githubusercontent.com/32103379/127723008-f8e1df56-8361-4fa5-944f-71b658dee240.png">

Should look similar to what's already seen in Apple Maps here:
![IMG_3356](https://user-images.githubusercontent.com/32103379/127723021-5955b587-fa63-42b3-93bc-51971338e699.jpg)

## Environment info
      react-native: 0.63.4
      react: 16.9.0
      react-native-maps: 0.29.2

## Steps to reproduce
https://snack.expo.dev/q7B7UXSV-

1. Zoom in to your current location to see app
2. Marker for current location does not include user bearing

Describe what you expected to happen:
1. User location marker should have direction of where user is looking at

## Reproducible sample code
https://snack.expo.dev/q7B7UXSV-

**Comment by krakz999** [comment]
@js1998 found a solution, is this unimplemented or a bug?

**Comment by Simon-TechForm** [comment]
Apple haven't included the heading annotation in MapKit, meaning `react-native-maps` cannot show it either, unfortunately :)

**Comment by georgibakken** [comment]
[It seems ](https://developer.apple.com/documentation/mapkit/mkuserlocation/1452721-heading) it has been added now?

**Comment by gediminastub** [comment]
Heya! Could this be reopened as feature is "implementable"? I think this would be beneficial to map users. Thanks!

**Comment by gediminastub** [comment]
Heya, this would be outstanding to have! Pretty please.. 🙏

**Comment by jeffinhk** [comment]
@monholm  Can we have this re-opened or change the tag?

**Comment by WayneKim92** [comment]
If you need this, use [it](https://www.npmjs.com/package/react-native-maps-my-location-direction).

**Comment by nekiro** [comment]
Still needed, is anyone planning on adding that?

**Comment by omarsdev** [comment]
Any update ?
