### ISSUE TITLE
A MapViewProps interface attribute is out of date

### ISSUE THREAD

**Issue by hmartiins** [react-native-maps/react-native-maps#3906]
# Bug report

## Summary

A MapViewProps interface attribute is out of date

## Environment info

```
expo: ~41.0.1
react: 16.13.1
react-native-maps: 0.27.1
```

## Steps to reproduce

1. create a reference variable and assign the MapViewProps to its type (example: ```const refMap = useRef<MapViewProps>(null);```;
2. when trying to access the current.region.latitude attribute value it returns undefined;
3. however, when I try to access the attribute value using .current .__lastRegion.latitude, then yes it returns the correct value.

```tsx
console.log(refMap.current.region.latitude) // Return undefined
console.log(refMap.current.__lastRegion.latitude) // Return latitude
```

#### Describe what you expected to happen:

I was expecting the refMap.current.region.latitude attribute to return the MapView's latitude to me, but it returned undefined, and when I logged in refMap.current, then yes I realized that inside it the right attribute would be refMap. .current__lastRegion.latitude

#### Describe what you actually happens:

When using refMap.current.__lastRegion.latitude, my Eslint returns a typing error, because in the index.d.ts file _lastRegion is not defined, only region that is defined there. As you understand it, the __lastRegion attribute should be region according to the MapViewProps type file

![2021-07-30-225342_1366x768_scrot](https://user-images.githubusercontent.com/51277667/127725783-d42a1b0a-5015-4767-95c6-2d85e3d3d257.png)

## Reproducible sample code

Excerpt from where the error is in the code:

```tsx
import React, { ReactElement, useRef, useState } from 'react';
import { View } from 'react-native';

import MapView, { Marker, MapViewProps } from 'react-native-maps';

export function App(): ReactElement {
const refMap = useRef<MapViewProps>(null);
const [viewHeight, setViewHeight] = useState<number>();
const [viewWidth, setViewWidth] = useState<number>();

async function onMapChange() {
  // Here the object is undefined
  const latitude = refMap.current.region.latitude;
  // This correct code would be below, however, I get the error "Property '__lastRegion' does not exist on type 'MapViewProps'."
  // const zoom = refMap.current.__lastRegion.latitude;
}
```

Snack link: [https://snack.expo.dev/taj_4vzbV](https://snack.expo.dev/taj_4vzbV)

**Comment by Simon-TechForm** [comment]
A couple of comments on this:

`__lastRegion` **is** actually missing from the declaration file, but not from `MapViewProps`. As suggested by the name, `MapViewProps` is a type meant for declaring the props that you are able to pass along to the `MapView` component, and shouldn't be used for `refs`. Use `MapView` instead. Isn't TypeScript going crazy when you try to use `MapViewProps`?

I made a pull request that adds `__lastRegion` to the `MapView` class declaration, even though I'm not really sure that it was ever meant to be exposed direcly like that. Instead, maybe consider getting the latest region from the `region` parameter of `onRegionChange`, so your code becomes:

```
async function onMapChange(region: Region) {
    console.log(region.latitude);
};
```

**Comment by christopherdro** [comment]
@Simon-TechForm I don't think `__lastRegion` was meant to be exposed directly. Maybe best way to move forward here is to remove it from the next release and recommend users to use  `onRegionChange` or `onRegionChangeComplete` to track the last region locally. Thoughts?

**Comment by Simon-TechForm** [comment]
> @Simon-TechForm I don't think `__lastRegion` was meant to be exposed directly. Maybe best way to move forward here is to remove it from the next release and recommend users to use `onRegionChange` or `onRegionChangeComplete` to track the last region locally. Thoughts?

That depends on what you mean by removing it :) 

I think it is totally reasonable not to merge my pull request, and instead advise users to track it locally.

We probably shouldn't be removing it from the source code, as it is used for comparison, to make sure `setNativeProps` isn't called unnecessarily.

**Comment by hmartiins** [comment]
It would be nice if it were recommended to use ```onMapChange``` to capture the latitude or region, for me the most logical would be to use the ```lastRegion``` or ```region.latitude``` for such an act. I apologize if I rushed to open this issue

**Comment by Simon-TechForm** [comment]
> It would be nice if it were recommended to use `onMapChange` to capture the latitude or region, for me the most logical would be to use the `lastRegion` or `region.latitude` for such an act. I apologize if I rushed to open this issue

I get why you could get confused by `__lastRegion`. Trying to use `Region` comes down to using the wrong type for your ref. `Region` isn't a property on the MapView class.

@christopherdro how about we actually do add `__lastRegion` to index.d.ts, but add is as a private member? That way, consumers will see it's there, but be notified that it shouldn't be accessed?

**Comment by MatrixFrog** [comment]
@Simon-TechForm Is this what you mean? https://github.com/react-native-maps/react-native-maps/pull/4058

@hmartiins does it work as expected?

**Comment by Simon-TechForm** [comment]
Yes, that was what I imagined. But since it isn't initialized in the contructor, I suggest making it optional.

**Comment by MatrixFrog** [comment]
good idea, done
