### ISSUE TITLE
ZoomLevel Explanation

### ISSUE THREAD

**Issue by falay26** [react-native-maps/react-native-maps#3907]
<MapView /> has the props minZoomLevel and maxZoomLevel, but they are not explained anywhere. What I am trying to achieve (and I think this might be the use case for lots of people) is limit the users so that they can not see more than 100 kilometers in width (the number is representative) but it changes when the device's width changes. So how does this props work exactly?

**Comment by christopherdro** [comment]
Check the docs. https://github.com/react-native-maps/react-native-maps/blob/ebb13b55e63a25dd5f306f309d1752b939296115/docs/mapview.md
