### ISSUE TITLE
Setting scrollDuringRotateOrZoomEnabled to false doesn't prevent map center change on Android

### ISSUE THREAD

**Issue by kHorozhanov** [react-native-maps/react-native-maps#3910]
# Bug report

## Summary

I'm setting scrollDuringRotateOrZoomEnabled to false, and in IOS it works as expected.
When I zoom in/out map center is still the same.
But on Android devices, the map center was changed.

## Environment info

"react": "16.13.1",
"react-native": "~0.63.4",
"react-native-maps": "0.29.2",

## Steps to reproduce

1. Create a simple MapView with initialRegion

```
<MapView
  provider={PROVIDER_GOOGLE}
  initialRegion={initialRegion}
  onRegionChange={onRegionChange}
  scrollDuringRotateOrZoomEnabled={false}
/>
```
2. Run application on android emulator/device
3. Try to change zoom from the bottom of the map

Describe what you actually happens:

The Map center was changed.

I'm expecting a property ```scrollDuringRotateOrZoomEnabled={false}``` will save the map center while zooming (IOS works as expected).

https://user-images.githubusercontent.com/15924598/128214404-91393e0b-1b27-4a03-89b2-507d2ca36c54.mov

**Comment by znanick** [comment]
+1

**Comment by znanick** [comment]
If you have found how to fix this problem, please write

**Comment by amserhii11** [comment]
Any solutions @kHorozhanov  ?

**Comment by Simon-TechForm** [comment]
I'm unable to reproduce this on the latest version of react-native-maps. Can you please test out the latest version and report back?

**Comment by fuelkoy** [comment]
This is still happening to me on Android real device (haven not tested emulator
`
"expo": "^44.0.6",
"react": "17.0.1",
"react-native": "0.64.3",
"react-native-maps": "^0.31.0",
`

**Comment by tkyr-hh** [comment]
The same here

**Comment by tkyr-hh** [comment]
@Simon-TechForm Why did you close this bug? I faced the issue on my Huawei Y9 2019 and  Xiaomi Redmi 9C devices.. the property `scrollDuringRotateOrZoomEnabled` is not working on android it works only on IOS.
The first video recording is with an IOS simulator, and the second is with my android phone, please observe the difference.

https://user-images.githubusercontent.com/96578305/169834168-664a5001-690a-48e4-b8ae-0ec9a7731774.mp4

https://user-images.githubusercontent.com/96578305/169835378-c82295fe-e2d6-4e97-ba11-b3f534fb5360.mp4

This is my code: 

` 
           
           <MapView

            ref={mapViewRef}
            provider={PROVIDER_GOOGLE}
            scrollDuringRotateOrZoomEnabled={false}
            style={styles.map}
            onRegionChangeComplete={_onRegionChangeComplete}
            initialRegion={{
              latitude: initialLocation?.latitude,
              longitude: initialLocation?.longitude,
              latitudeDelta: latLongDelta,
              longitudeDelta: latLongDelta,
            }}
            userInterfaceStyle={systemColorSchema}
            showsMyLocationButton={!!currentAddress}
            showsUserLocation={!!currentAddress}
            scrollEnabled={!scrollDisabled}
            onTouchStart={_onTouchStart}
            showsCompass
          />
`

**Comment by celian-rib** [comment]
Hi, is there any solution for this? Still having the issue on rn-maps latest version

**Comment by fuelkoy** [comment]
Added discussion related to this as there is actually build in mechanism to this on Android also.
https://github.com/react-native-maps/react-native-maps/discussions/4489

**Comment by fuelkoy** [comment]
Solved by pretty simple workaround: https://github.com/react-native-maps/react-native-maps/issues/4247#issuecomment-1283569058
