### ISSUE TITLE
Unable to load finer detail on maps in Native simulators/emulators while zooming

### ISSUE THREAD

**Issue by Eli-Nathan** [react-native-maps/react-native-maps#3916]
# Bug report
## Summary
**When zooming, finer detail on maps in Native simulators/emulators doesn't show**

When rendering a `<MapView />` on ios and Android simulators, I am able to pan North/South/East/West and the map updates no problem.

However, if I try to zoom in, it seems to not load the finer detail that you'd expect.

When running on my physical device, it behaves as expected.

Is there something on my end that needs to be done so that the library is supported by device simulators? Or is it a bug?

## Environment info
```bash
react-native: 0.64.1
react: 16.0.0
react-native-maps: 0.28.0

Target Platform: iOS - 14.3 Simulator - iPhone 12
Target Platform: iOS - Android 9 - Pixel 4
```

## Steps to reproduce

1. Add basic MapView
2. Run app on native sims
3. Zoom into a location

Expected:
The map updates the finer details of the place you are zooming into

Describe what you actually happens:
It acts as though it is an image that is scaled up. No new places are added and it becomes somewhat blurry.

https://user-images.githubusercontent.com/32842898/129257360-0d584045-0b4c-4522-ab34-1883f1fbf759.mov

## Reproducible sample code

[Snack code example](https://snack.expo.dev/v8A-bTEum)
**Please note** The Expo sim on that Snack example works as expected. It's when it's run on actual native sims from Xcode or Android Studio that it doesn't work.

----
Edit: I just tried on an iPhone 8 sim and it works as expected.
So it's just specific sims that seem to have the problem

**Comment by Simon-TechForm** [comment]
@Eli-Nathan what was the outcome of this? Was it a glitch? Or is it continuing to happen?
