### ISSUE TITLE
There is no way to get overlay details using geojson

### ISSUE THREAD

**Issue by alichampion** [react-native-maps/react-native-maps#3921]
# Only able to get overlay/polygon coordinates when using geojson but i need other information as well which is along with the feature properties of geojson.

👉 Hi everyone I have been trying to get overlay data onPress, Both on Android and iOS there is no way to get overlay/polygon details however we can get coordinates and position but I need other information as well which is along with the feature properties.

- react-native-maps v0.28.0

This is how I'm doing.

import React from "react";
import { Dimensions } from "react-native";
import MapView, { Geojson, UrlTile } from "react-native-maps";

const geoJsonFile = require("components/ui/map/components/germany.geo");
let { width, height } = Dimensions.get("window");
const ASPECT_RATIO = width / height;
const LATITUDE_DELTA = 10; //Very high zoom level
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
const GeojsonMap = (props) => {
  return (
    <MapView
      style={{
        flex: 1,
        backgroundColor: "transparent",
      }}
      initialRegion={{
        latitude: 51.1657,
        longitude: 10.4515,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      }}
    >
      <Geojson
        strokeColor="blue"
        strokeWidth={0.5}
        fillColor="red"
        geojson={geoJsonFile}
      />
      <UrlTile
        /**
         * The url template of the tile server. The patterns {x} {y} {z} will be replaced at runtime
         * For example, http://c.tile.openstreetmap.org/{z}/{x}/{y}.png
         */
        urlTemplate={"http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"}
        /**
         * The maximum zoom level for this tile overlay. Corresponds to the maximumZ setting in
         * MKTileOverlay. iOS only.
         */
        maximumZ={19}
        /**
         * flipY allows tiles with inverted y coordinates (origin at bottom left of map)
         * to be used. Its default value is false.
         */
        flipY={false}
      />
    </MapView>
  );
};
export default GeojsonMap;

Geojson file is here [https://filebin.net/bho8uuj8z49ytw0e](url)

**Comment by alichampion** [comment]
<img width="1680" alt="Screenshot 2021-08-17 at 3 27 19 AM" src="https://user-images.githubusercontent.com/38204661/129636997-2a829a64-3709-4309-bdb6-76d7521dcfe1.png">

I actually need overlay details as you can see in the screenshot this helped me.

But as you know it's temporary is there any way it can be fixed permanently.

**Comment by christopherdro** [comment]
Can you try the current prerelease v0.29.2? That includes the following changes that I think solve your issue.

https://github.com/react-native-maps/react-native-maps/pull/3728/files

**Comment by alichampion** [comment]
> Can you try the current prerelease v0.29.2? That includes the following changes that I think solve your issue.
> 
> https://github.com/react-native-maps/react-native-maps/pull/3728/files

Hi, @christopherdro thanks for your time and great work.

One thing more can you also add onPress to GeojsonProps props interface?

**Comment by christopherdro** [comment]
Isn’t that what the changes in the linked pull request does?

**Comment by alichampion** [comment]
> Isn’t that what the changes in the linked pull request does?

Hi, @christopherdro I think you added onPress to the geojson.md but I don't see it in the GeojsonProps interface in index.d.ts

**Comment by christopherdro** [comment]
Ok yea I see that missing. @WrathChaos can you make tia update in the other PR you have open right now?

**Comment by christopherdro** [comment]
Related https://github.com/react-native-maps/react-native-maps/pull/3920

**Comment by christopherdro** [comment]
Updates included in https://github.com/react-native-maps/react-native-maps/releases/tag/v0.29.3
