### ISSUE TITLE
react-native-web peer dependency

### ISSUE THREAD

**Issue by Borduhh** [react-native-maps/react-native-maps#3922]
## Summary

`react-native-maps` has a peer dependency conflict with the latest `expo init` package.

```
npm ERR! Found: react-native-web@0.13.18
npm ERR! node_modules/react-native-web
npm ERR!   react-native-web@"~0.13.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-web@"^0.11" from react-native-maps@0.28.0
npm ERR! node_modules/react-native-maps
npm ERR!   react-native-maps@"^0.28.0" from the root project
```

Is there any issue with updating the `react-native-web`?

**Comment by brunabursi** [comment]
having the same error here 👎

**Comment by salah-ghanim** [comment]
@Borduhh @brunabursi have you guys tried simply to increase the version of react-native-web inside the package.json locally to see if the build passes then ?

I see on their github that the last version is 0.17.0
https://github.com/necolas/react-native-web/releases/tag/0.17.0

if that works you can create a pull request of that change, we'll review it and merge

**Comment by stdavis** [comment]
> have you guys tried simply to increase the version of react-native-web inside the package.json locally to see if the build passes then ?

What do you mean by "build"? I don't see any build or test scripts other than linting in this project.

**Comment by Borduhh** [comment]
> > have you guys tried simply to increase the version of react-native-web inside the package.json locally to see if the build passes then ?
> 
> What do you mean by "build"? I don't see any build or test scripts other than linting in this project.

I believe he means builds in expo. @salah-ghanim I went ahead and updated one of our packages with a peer dep of `^0.13` and everything is working. I'll shoot up a PR momentarily for it.
