### ISSUE TITLE
Map crash on eas build product in android

### ISSUE THREAD

**Issue by vrinch** [react-native-maps/react-native-maps#3924]
Hi,

We have been using this package for a while now both in development and production with expo build and it has worked as expected.

Recently we migrated to eas, for the sole purpose of cutting down the size of the app. 

After eas build and submit are implemented without any errors.

The map functions as should in iOS, but on android, it lags for a few seconds and crashes.

Sentry does not log any errors for this crash.

We have use the expo run:android command and there’s no error message being displayed and the crash still happens.

Has any one experienced this in the past?

**Comment by diazdell91** [comment]
I am having the same problem, any solution?

**Comment by christopherdro** [comment]
Can you try using `adb logcat` while trying to reproduce the crash and see if we get any hints on what is causing the crash?

**Comment by Holler-Jason** [comment]
We are experiencing the same issue with Android and EAS Build. Are there any current solutions?

**Comment by vrinch** [comment]
@diazdell91 and @Holler-Jason no fix or solution currently, we had to revert back to using expo build, this was after wasting a whole month trying to figure the problem.

**Comment by vrinch** [comment]
@christopherdro has the issue been fixed?

**Comment by christopherdro** [comment]
Oops, looks like I linked this ticket accidentally in an unrelated PR.

**Comment by vrinch** [comment]
okay
have you been able to reproduce this?
it happens only on android when built with EAS

**Comment by christopherdro** [comment]
I haven't had a chance yet. Can you try using [`adb logcat` ](https://developer.android.com/studio/command-line/logcat) to see if we can get some more info about the crash?

**Comment by christopherdro** [comment]
@vrinch  Have you already seen this ticket? https://github.com/expo/expo/issues/14135

**Comment by vrinch** [comment]
yes I have and all files have been configured properly
running `adb logcat` doesn't point to anything specifically

**Comment by christopherdro** [comment]
@vrinch There must be a report of the crash. Search for the word `FATAL` and see if something comes up.

**Comment by brentvatne** [comment]
@vrinch - you are not being helpful. https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question

**Comment by jvgaeta** [comment]
This is happening to me. adb says

03-15 19:55:26.756 27585 27585 E AndroidRuntime: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml

It seems like an issue with eas. They are ignoring the android.config key

**Comment by AmigoDeluxe** [comment]
Yup... same here. Works with "expo build", fails with "eas build".

**Comment by blitzve0** [comment]
i added google api key and it was fixed for me

**Comment by hanamurayuki** [comment]
I also face same problem. 
IOS is ok, but blank map on android with `eas build`.
Reason is google map api authorization. (logo exists, but map is brank)

Document was updated on Fri Nov 25 2022.
https://docs.expo.dev/versions/latest/sdk/map-view/

> # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> 
> 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> For development builds
> - If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> - After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> - `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`

Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, 
but we need to upload  `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials >  Application Identifiers > click your project's package name and under Android Keystore), 

After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.
