### ISSUE TITLE
<GoogleMaps/GoogleMaps.h> not found in AppDelegate.m 

### ISSUE THREAD

**Issue by Bayramito** [react-native-maps/react-native-maps#3925]
In my project Im getting this error after upgrading my react-native from `0.63.4` to `0.64.2` 

<img width="493" alt="Ekran Resmi 2021-08-21 15 09 10" src="https://user-images.githubusercontent.com/44513402/130322976-ef472f91-ff59-4f23-ae7f-3a3cc36989aa.png">

**Comment by christopherdro** [comment]
That’s an issue with your one signal service extension and not this lib. Also please follow the issue template next time creating an issue. It’s there for a reason.
