### ISSUE TITLE
How to use OpenStreetMap tiles on android and ios.

### ISSUE THREAD

**Issue by FranciscoMendes10866** [react-native-maps/react-native-maps#3932]
I was currently trying to add a map to my ios application, however Apple Maps tiles persists.

This is my code:

```js
import React from 'react';
import { Platform, SafeAreaView } from 'react-native';
import MapView, { UrlTile } from 'react-native-maps';

import styles from './styles';

const index = () => {
  return (
    <SafeAreaView style={styles.container}>
      <MapView
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 12,
          longitudeDelta: 12,
        }}
        style={styles.mapView}
        mapType={Platform.OS === 'android' ? 'none' : 'standard'}
        provider={null}
        rotateEnabled={false}
        zoomEnabled={false}>
        <UrlTile
          urlTemplate="https://c.tile.openstreetmap.org/${z}/${x}/${y}.png"
          shouldReplaceMapContent={true}
          maximumZ={19}
          flipY={false}
        />
      </MapView>
    </SafeAreaView>
  );
};

export default index;
```

In my `Info.plist` I already added the following:

```html
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

However if I add the `shouldReplaceMapContent={true}` in the `<UrlTile />` component, it looks like this:

![map](https://res.cloudinary.com/dj5iihhqv/image/upload/v1630074479/issues/Screenshot_2021-08-27_at_15.23.19_r0fnuh.png)

What should I do? I am quite confused.
What I wanted was to have the OSM tiles.

**Comment by MaRaSu** [comment]
@FranciscoMendes10866 couple of things:
- `shouldReplaceMapContent` work exactly as defined, it removes the iOS map from the background
- Your `urlTemplate`is incorrect format. If you check the prop types info and examples you notice there is no "$" used for templating
- OpenStreetMap free servers are not meant for "at scale" use. As of today they will work with RNM on iOS, but not on Android. Anyways, if you intend to distribute your app to more than a few people please check OSM free server terms of use first.

**Comment by FranciscoMendes10866** [comment]
@MaRaSu Thanks for the answer, I'm just doing a personal project, but just a question. Do OSM tiles work on android?

**Comment by MaRaSu** [comment]
@FranciscoMendes10866 OSM tileserver you were planning to use works for iOS, but not on Android. Apparently that tileserver is doing blocking based on client (http) user agent and too many developers on Android have misused that free server using React Native Maps thus RNM standard user agent is blocked.

OSM tiles naturally work on Android, issue is about the tileserver serving those tiles. As you probably know OSM database, map tiles rendered (with a specific map style and rendering engine) from OSM database and tileserver are all separate concepts.
