### ISSUE TITLE
onUserLocationChange callback heading undefined on iOS AppleMaps

### ISSUE THREAD

**Issue by EyadAlghamdi** [react-native-maps/react-native-maps#3934]
# Bug report

## Summary

`onUserLocationChange` callback in iOS MapKit is not returning the heading (its always undefined).
I went through the code and I believe the issue is [in this line of code here](https://github.com/react-native-maps/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L1021)

I am not sure how to change it tho I'm not very experiences with iOS development. (maybe we can add development manual to this repo on how to setup and contribute to it and i'd be happy to assist?)

## Environment info

`react-native info` output:

```bash
      react-native: 0.65.1
      react: 17.0.2
      react-native-maps: 0.28.0 
     target: iOS (AppleMaps)
```

## Steps to reproduce

1. Setup a plain MapView
2. Ensure you have `showUserLocation ={true}`
3. pass a function to `onUserLocationChange` and inspect the callback to get the heading

Describe what you expected to happen:

The heading in the `onUserLocationChange` callback should NOT return `undefined` 

## Reproducible sample code

simple EXPO example here https://snack.expo.dev/@eyadal/react-native-maps-heading-undefined (run on iPhone of course)

**Comment by kalebheitzman** [comment]
Same issue.

**Comment by christopherdro** [comment]
@kalebheitzman Can you adding ` @"heading": [RCTConvert NSData:location.heading]` to the event payload and see what shows up in your logs?

**Comment by kalebheitzman** [comment]
@christopherdro I'm not sure where to do that... Do you have a quick code sample and I'll reply with the output

**Comment by kalebheitzman** [comment]
@christopherdro I solved this issue using the ```expo-location``` package. It does return a heading (not that that's useful information, but maybe?)

**Comment by christopherdro** [comment]
Add `@"heading": [RCTConvert NSData:location.heading]` to the event payload below `speed` [here](https://github.com/react-native-maps/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L1020) and rebuild through Xcode.

**Comment by kalebheitzman** [comment]
Didn't work.

```
[Tue Sep 07 2021 17:50:44.422]  WARN     RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks
```

```
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[7]'
terminating with uncaught exception of type NSException
```

**Comment by christopherdro** [comment]
@kalebheitzman Can you test this PR? https://github.com/react-native-maps/react-native-maps/pull/3944

**Comment by EyadAlghamdi** [comment]
It needs to have location.course instead of location.heading, and no need for RCT convert you can find my fork here, ill make a PR to merge it in https://github.com/EyadAlghamdi/react-native-maps

**Comment by EyadAlghamdi** [comment]
never mind, looks like @christopherdro beat me to it 👍  ill remove my fork then

**Comment by christopherdro** [comment]
@EyadAlghamdi Thanks for confirming the solution! :)
