### ISSUE TITLE
Update the documentation for the latest version of the plugin and the latest version of react native

### ISSUE THREAD

**Issue by TeodorStoyanov17** [react-native-maps/react-native-maps#3935]
# Feature request

Update the documentation.

## Why it is needed

After two days of struggling to setup the Google map on iOS I found out that the documentation link for installation in the README.md file is much older(from 2016). For faster setup and no missunderstanding of the documentation and the guidelines it will be a great idea to update the README.md of the latest version with the links to the docks to the latest version.

## Possible implementation

This is not related to the code base, rather to the documentation. Any links to it, could be updated to the latest version for them.

### Code sample

Not a code feature.

**Comment by christopherdro** [comment]
What specifically needs to be updated? Could you submit a pull request with those changes?
