### ISSUE TITLE
OSM Tile Server not working

### ISSUE THREAD

**Issue by galdinoramon** [react-native-maps/react-native-maps#3941]
## Summary

UrlTile is not working with openstreetmap url on Android (emulator / real device). According to the [#3747](https://github.com/react-native-maps/react-native-maps/issues/3747), this appears to be a permissions problem relatade to the http user agent and the new usage policy presented on [OSM Tile Usage Policy
](https://operations.osmfoundation.org/policies/tiles/#:~:text=OpenStreetMap%20data%20is%20free%20for,Our%20tile%20servers%20are%20not.&text=If%20your%20project%20doesn't,the%20OSMF%20Terms%20of%20Use.) , 

No solution has been presented so far and there are many others users with that problem. 

Please if someone know how to fix the problem and can give some tips.

## Environment info

```
"expo": "42.0.0",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "0.63.4",
"react-native-maps": "0.28.0"

```

## Steps to reproduce

UrlTile works fine with this url 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg' but not working with osm url 'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png'.

Describe what you expected to happen:

Visible OSM tiles

Describe what you actually happens:

Blank map on android device

## Reproducible sample code

    const urlTemplate = 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg';

    return (
        <View style={styles.container}>
            <MapView
                provider={null}
                style={{
                    position: 'absolute',
                    top: 0,
                    left: 0,
                    right: 0,
                    bottom: 0,
                }}
                mapType={'none'}
                initialRegion={region}
            >
                <UrlTile urlTemplate={urlTemplate} maximumZ={19} flipY={false} />
            </MapView>
        </View>
    );

**Comment by christopherdro** [comment]
@MaRaSu Put together some docs recently around Tiles that might be helpful. https://github.com/react-native-maps/react-native-maps/blob/master/docs/tiles.md

**Comment by galdinoramon** [comment]
Thanks for the feedback @christopherdro , apparently OSM free tile servers do not work on Android anymore due to the overuse. Do you know another way? maybe with a webview implementation... is it possible?

**Comment by MaRaSu** [comment]
@galdinoramon @christopherdro I think the right way to solve this is to use either a commercial tile service provider or setup your own tile server (relatively simple, see [https://switch2osm.org/serving-tiles/](https://switch2osm.org/serving-tiles/)), or if you find one, use a free tileserver for which Terms of Use are aligned with the actual usage. Trying to abuse openstreetmap.org tileservers, against their stated Usage Policy, with whatever workaround or hack, is not the right way in my opinion.

Some people probably misunderstand React Native Maps functionality: it's not a full map application for OSM-maps, it's just the client, and you need to organise for the service (server) yourself.

**Comment by galdinoramon** [comment]
Thanks @MaRaSu and @christopherdro , it was really helpful

**Comment by richcrad** [comment]
I know this issue is closed, but I've run into the same problem using the tile server from NOAA, i.e.:

      <UrlTile urlTemplate='http://tileservice.charts.noaa.gov/tiles/50000_1/{z}/{x}/{y}.png/>

This works perfectly on iOS but doesn't load the tiles at all on Android.

Does anyone know if there is a generic issue with tile servers on Android? Thanks!
