### ISSUE TITLE
takeSnapshot not capturing markers

### ISSUE THREAD

**Issue by msaqlain** [react-native-maps/react-native-maps#3942]
react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
react: 16.13.1
react-native-maps: 0.28.0

I want to get markers as a part of snapshot. When we use takeSnapshot method all markers are ignored. 

Please let me know the possibility of this

**Comment by christopherdro** [comment]
Feel to reopen with the issue template fully filled out. fwiw, I can see markers in the snapshots when testing with the example app on iOS.

**Comment by msaqlain** [comment]
```
const snapshot = this.viewRefTest.takeSnapshot({
    format: 'png',   // image formats: 'png', 'jpg' (default: 'png')
    quality: 0.5,    // image quality: 0..1 (only relevant for jpg, default: 1)
    result: 'file'   // result types: 'file', 'base64' (default: 'file')
});


<MapView
    ref={viewRefTest => {
        this.viewRefTest = viewRefTest;
    }}
    showsUserLocation={true}
    followUserLocation={true}
>
</MapView>
```

@christopherdro try using this code

**Comment by msaqlain** [comment]
Follow this issue on github as it needs resolution.

**Comment by msaqlain** [comment]
@christopherdro Please reopen this issue.
