### ISSUE TITLE
Property 'Animated' does not exist on type 'typeof Marker'.

### ISSUE THREAD

**Issue by pablogdcr** [react-native-maps/react-native-maps#3943]
# Bug report

## Summary

I'm trying to use animated markers with typescript, but it says that the property "Animated" does not exist on type Marker.

```javascript
    <Marker.Animated>
         // ~~~~~~~~
         // Property 'Animated' does not exist on type 'typeof Marker'.
         // ...
    </Marker.Animated>
```

## Environment info

      react-native: 0.64.2
      react: 17.0.1
      react-native-maps: 0.29.3

`react-native info` output:

```bash
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.19 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Using vscode, eslint 7.31.0, typescript 4.4.2
2. Create a .tsx component
3. import Marker from 'react-native-maps'
4. render `Marker.Animated` and you will get the error

Describe what you expected to happen:

No error displayed, as it's a normal use of the maker, shown in the examples.
(https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/AnimatedMarkers.js)
`Animated` should be a Property of `Marker`

Describe what you actually happens:

Property 'Animated' does not exist on type 'typeof Marker'.

## Reproducible sample code

AnimatedMarker.tsx
```javascript
import React, { useRef } from 'react';
import { Marker, AnimatedRegion } from 'react-native-maps';

const AnimatedMarker: React.FC = () => {
   const coordinate = useRef(new AnimatedRegion({
      latitude: 0,
      longitude: 0,
      latitudeDelta: 0,
      longitudeDelta: 0,
   })).current;
   
   return (
      <Marker.Animated
         coordinate={coordinate}
      />
   );
};

export default AnimatedMarker;
```

**Comment by rodrigo2392** [comment]
+1

**Comment by asit-panda** [comment]
Property 'Animated' does not exist on type 'typeof Marker'.

Same issue. Please look into this. Thanks in advance.

**Comment by Simon-TechForm** [comment]
Yeah, this seems to be a mistake in the TS declaration. In the meantime, you could:
```ts
import { MarkerAnimated } from 'react-native-maps';
```

which is the same as `Marker.Animated` and should work with TS.

**Comment by Simon-TechForm** [comment]
I'm going to close this, as I need to narrow down the open issues. I hope that the workaround I provided above will suffice for now. I will merge a TS rewrite soon, that will fix the issue itself.
