### ISSUE TITLE
2 pins on same lat long

### ISSUE THREAD

**Issue by saurabhnemade** [react-native-maps/react-native-maps#3947]
# Bug report

Rendering two custom pins at same lat long gives flashing effect on ios while on android it correctly overlaps another pin.

Android on left, iOS on right.

https://user-images.githubusercontent.com/17445338/132657674-d0698e6e-298d-41f4-8c5a-c5394d3e08f3.mp4

## Environment info

```
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 105.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /opt/homebrew/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.3 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps to reproduce

Just render custom markers on same lat long.

Describe what you expected to happen:
Behaviour needs to be consistent. It either need to flash or does not.

Describe what you actually happens:
Currently it is flashing on ios and overlapping on android.

**Comment by dusanspasojevic** [comment]
Try to adjust your markers zIndex

**Comment by Simon-TechForm** [comment]
As suggested by @dusanspasojevic specifying the zIndex should fix this. Closing for now, but feel free to open a new issue if specifying zIndex doens't fix the issue.

**Comment by AhmedHF** [comment]
after setting zIndex, it still did not work
