### ISSUE TITLE
Android - upgrade to API level 30

### ISSUE THREAD

**Issue by costel21d** [react-native-maps/react-native-maps#3949]
I updated the targetSdkVersion and compileSdkVersion to 30 in build.gradle and after rebuild I have this message on MapView.

Using on emulator Pixel_4_XL_API_30(AVD) - 11

**App won't run without Google Play services, which are not supported by your device.**

```
      ...
        compileSdkVersion = 30
        targetSdkVersion = 30
```

**Comment by christopherdro** [comment]
Please read the documentation and follow the issue template next time when opening an issue. 

https://github.com/react-native-maps/react-native-maps/blob/2236ad9ffc18a3e273e6d302ef738c1ecb1f6322/docs/installation.md#android-emulator-issues
