### ISSUE TITLE
Invariant Violation: requireNativeComponent: "AIRMapHeatmap" was not found in the UIManager.

### ISSUE THREAD

**Issue by SJImobility** [react-native-maps/react-native-maps#3958]
# Bug report

## Environment info

Code sample

`<Heatmap points={this.props.coordinateArray}
                gradient={{
                  colors: ["blue", "yellow", "orange", "red", "darkred"],
                  startPoints: [0.05, 0.1, 0.15, 0.2, 0.3],
                  colorMapSize: 2000,
                  radius: 25,
                  opacity: 1
                }}>
              </Heatmap>`

Error:

Invariant Violation: requireNativeComponent: "AIRMapHeatmap" was not found in the UIManager.
This error is located at:
    in AIRMapHeatmap (at MapHeatmap.js:79)
    in MapHeatmap (at MapScreen.js:119)
    in AIRMap (at MapView.js:993)
    in MapView (at MapScreen.js:87)
    in RCTView (at MapScreen.js:86)
    in MapScreen (created by ConnectFunction)
    in ConnectFunction (created by SceneView)
    in SceneView (created by TabNavigationView)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by ResourceSavingScene)
    in ResourceSavingScene (created by TabNavigationView)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by TabNavigationView)
    in RCTView (created by TabNavigationView)
    in TabNavigationView (created by NavigationView)
    in NavigationView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by Card)
    in RCTView (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by Card)
    in RCTView (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (at src/index.tsx:78)
    in RCTView (at Transitioning.js:138)
    in Wrapped (at src/index.tsx:73)
    in AnimatedSwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.js:19)
    in Provider (at App.js:18)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)
getNativeComponentAttributes
    getNativeComponentAttributes.js:30:4
exports.get
    ReactNativeViewConfigRegistry.js:102:25
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0

Same code is working for Android
https://play.google.com/store/apps/details?id=com.barglance.barglance&hl=en_ZA&gl=US

**Comment by Simon-TechForm** [comment]
Could you please provide an example of how you are using Heatmap? Please provide a Minimal, Reproducible Example.

**Comment by suhaillilac** [comment]
am getting same issue , Anyone find any workaround

**Comment by briang123** [comment]
Same issue. Anyone find a solution?

Running on RN 0.66.4 and react-native-maps v0.30.1

`<MapView
        style={styles.map}
        region={{
          latitude: currentRegion.coords.latitude,
          longitude: currentRegion.coords.longitude,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}>
        {Object.keys(items).map((item) => (
          <Marker
            key={item}
            coordinate={items[item].coords}
            title={item}
            description="Address"
          />
        ))}
      </MapView>
`

**Comment by suhaillilac** [comment]
> Same issue. Anyone find a solution?
> 
> Running on RN 0.66.4 and react-native-maps v0.30.1
> 
> `<MapView style={styles.map} region={{ latitude: currentRegion.coords.latitude, longitude: currentRegion.coords.longitude, latitudeDelta: 0.0922, longitudeDelta: 0.0421, }}> {Object.keys(items).map((item) => ( <Marker key={item} coordinate={items[item].coords} title={item} description="Address" /> ))} </MapView> `

try adding as  provider={"google"}

**Comment by bhomaramgtsinfo** [comment]
Hey @suhaillilac 
i am getting the same issue still on iOS. can you please help to resolve this issue

**Comment by 4RGUS** [comment]
Same issue for me on:

react-native - v0.66.4
react-native-maps - v0.30.1

**Comment by suhail135** [comment]
> 

try adding as provider={"google"}

**Comment by eduardoborges** [comment]
Same problem here.

react-native 0.67.3

**Comment by Simon-TechForm** [comment]
Heatmap isn't implemented for Apple Maps, which is why it's only working with `provider={"google"}`

It would be extremely helpful if one of you could open a PR to update the docs to clearly state that heatmap is google maps only.
Also if one of you could open a new issue following the feature request template, there's a much better chance that this will be picked up by someone.
