### ISSUE TITLE
iOS15 tile overlay flickering when marker updated

### ISSUE THREAD

**Issue by MaRaSu** [react-native-maps/react-native-maps#3969]
# Bug report

## Summary

With iOS 15 something has changed in tile overlay (URLTile, WMSTile, LocalTile) rendering when other elements are drawn on top e.g. markers, this results in flickering of tile overlay's tiles when those on top elements change. This is visible both in simulator and in devices running iOS 15. Does not happen in iOS 14.5 or other older versions.

Since this is impacting my RNM app I will be debugging this to find a root cause or at least a workaround. Would be great to hear if anyone else is suffering from the same, also if some apps have not seen any issues, this would help to narrow down the root cause.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 173.88 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 3.8.5 - /Users/suomimar/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Create tile overlay e.g. URLTile on top of Apple Maps / standard on iOS15
2. Create a marker on top of tile overlay
3. Toggle on & off marker rapidly --> tiles flicker

Describe what you expected to happen:

1. No flickering of tiles

Describe what you actually happens:

1. Tiles flicker, but not always - seems to be dependent on what is updated on top of tile overlay e.g. updating some graphical elements in marker do not cause flicker while some others do

## Reproducible sample code

Minimum viable code to reproduce the problem: [https://github.com/MaRaSu/mapflicker](https://github.com/MaRaSu/mapflicker).

Snippet of code from my app on the marker that is drawn on the map. NB! only a sample of the LocationMarker.tsx component.

```
	return (
		<>
			<Marker anchor={ANCHOR} style={styles.mapMarker} coordinate={coordinate}>
				<View style={styles.container}>
					<View style={styles.markerHalo} />
					{rotate && (
						<View style={[styles.headingHalo, { transform: [{ rotate }] }]}>
							<View style={styles.headingPointerHalo} />
						</View>
					)}
					{rotate && (
						<View style={[styles.heading, { transform: [{ rotate }] }]}>
							<View style={styles.headingPointer} />
						</View>
					)}
					<View style={styles.marker}>
						<Text style={styles.markerText}>{props.enableHack && rotate}</Text>
					</View>
				</View>
				{props.children}
			</Marker>
			{accuracy && (
				<Circle
					center={coordinate}
					radius={accuracy}
					fillColor={CIRCLE_FILL_COLOR}
					strokeWidth={CIRCLE_STROKE_WIDTH}
					zIndex={2}
				></Circle>
			)}
		</>
	);



// Styling of marker
const SIZE = 15;
const HALO_RADIUS = 8;
const ARROW_SIZE = 18;
const ARROW_DISTANCE = 19;
const ARROW_HALO_SIZE_REDUCTION = 5;
const ARROW_HALO_DISTANCE = ARROW_HALO_SIZE_REDUCTION * 2;
const HALO_SIZE = SIZE + HALO_RADIUS;
const HEADING_BOX_SIZE = HALO_SIZE + ARROW_SIZE + ARROW_DISTANCE;

const CIRCLE_FILL_COLOR = 'rgba(0, 0, 255, 0.08)';
const CIRCLE_STROKE_WIDTH = 0.1;

const styles = StyleSheet.create({
	mapMarker: {
		zIndex: 1000
	},
	// The container is necessary to protect the markerHalo shadow from clipping
	container: {
		width: HEADING_BOX_SIZE,
		height: HEADING_BOX_SIZE
	},
	heading: {
		position: 'absolute',
		top: ARROW_HALO_DISTANCE / 2,
		left: ARROW_HALO_DISTANCE / 2,
		width: HEADING_BOX_SIZE - ARROW_HALO_DISTANCE,
		height: HEADING_BOX_SIZE - ARROW_HALO_DISTANCE,
		alignItems: 'center'
	},
	headingPointer: {
		width: 0,
		height: 0,
		backgroundColor: 'transparent',
		borderStyle: 'solid',
		borderTopWidth: 0,
		borderRightWidth: (ARROW_SIZE - ARROW_HALO_SIZE_REDUCTION) * 0.75,
		borderBottomWidth: ARROW_SIZE - ARROW_HALO_SIZE_REDUCTION,
		borderLeftWidth: (ARROW_SIZE - ARROW_HALO_SIZE_REDUCTION) * 0.75,
		borderTopColor: 'transparent',
		borderRightColor: 'transparent',
		borderBottomColor: colorOfmyLocationMapMarker,
		borderLeftColor: 'transparent'
	},
	headingHalo: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: HEADING_BOX_SIZE,
		height: HEADING_BOX_SIZE,
		alignItems: 'center'
	},
	headingPointerHalo: {
		width: 0,
		height: 0,
		backgroundColor: 'transparent',
		borderStyle: 'solid',
		borderTopWidth: 0,
		borderRightWidth: ARROW_SIZE * 0.75,
		borderBottomWidth: ARROW_SIZE,
		borderLeftWidth: ARROW_SIZE * 0.75,
		borderTopColor: 'transparent',
		borderRightColor: 'transparent',
		borderBottomColor: 'white',
		borderLeftColor: 'transparent'
	},
	markerHalo: {
		position: 'absolute',
		backgroundColor: 'white',
		top: 0,
		left: 0,
		width: HALO_SIZE,
		height: HALO_SIZE,
		borderRadius: Math.ceil(HALO_SIZE / 2),
		margin: (HEADING_BOX_SIZE - HALO_SIZE) / 2,
		shadowColor: 'black',
		shadowOpacity: 0.25,
		shadowRadius: 2,
		shadowOffset: {
			height: 0,
			width: 0
		}
	},
	marker: {
		justifyContent: 'center',
		backgroundColor: colorOfmyLocationMapMarker,
		width: SIZE,
		height: SIZE,
		borderRadius: Math.ceil(SIZE / 2),
		margin: (HEADING_BOX_SIZE - SIZE) / 2
	},
	markerText: { width: 0, height: 0 }
});

```

**Comment by MaRaSu** [comment]
For additional explanation for the code snippet above ("LocationMarker"): it is child of RNM MapView.

Initial debugging of the problem points to `<Circle>` component which is used in the LocationMarker to indicate GPS accuracy. If I remove the `<Circle>` component then the map tile flickering stops.

Will continue investigations and creating minimum reproducible code.

**Comment by MaRaSu** [comment]
Minimum viable code created to reproduce flickering issue: [https://github.com/MaRaSu/mapflicker](https://github.com/MaRaSu/mapflicker).

**Comment by mmubeennisar** [comment]
Any update on this issue ?

**Comment by stdavis** [comment]
I have the same issue when I use background location tracking to draw a polyline on the map. @MaRaSu Did you ever find a workaround?

**Comment by MaRaSu** [comment]
@stdavis & @mmubeennisar Unfortunately I have been too busy with other things in life to investigate this any further. Since it appeared with iOS 15 I was a bit hoping it would be a broader issue that Apple would fix with iOS 15.x releases. But apparently that has not been the case.

When I investigated this it was not readily apparent that something in RNM was causing it and a Google search for others reporting this kind of problem with TileOverlays in iOS did not find anything at that point of time (might be different now).

**Comment by dorthwein** [comment]
I'm running into this as well :(

**Comment by lklepner** [comment]
I'm having this problem as well. I'd like to use OpenStreetMap (via UrlTile) but the flickering is very distracting. Has anyone found a way to solve this?

**Comment by MaRaSu** [comment]
@stdavis if you are still willing to put in the effort to debug this issue I can provide some support & pointers. Please ping back here and I can connect via your contact details.

**Comment by stdavis** [comment]
> @stdavis if you are still willing to put in the effort to debug this issue I can provide some support & pointers. Please ping back here and I can connect via your contact details.

Yes! It may not be for another few weeks, but I'm going to be back into this project at some point and would love to tips on where to start. I was going to start by seeing how iOS 16 looks.

**Comment by ashuvssut** [comment]
@lklepner @stdavis can you try removing the enableLatestRenderer();

I was using maps in my android app. using the legacy rendrer solves this (I think)
Plz do reply if you are going to test this out

**Comment by stdavis** [comment]
Yes, I do plan on hitting this at some point but this project keeps getting pushed back for me. It will likely be another few weeks. I have not yet tried the newly released version of this project.

**Comment by ashuvssut** [comment]
@stdavis Please do tell if newer version works for you WITH the Latest Rendrer enabled

For now I am still using the Legacy Rendrer coz it fixed that flickering for me + some other issues as well (like #4161 )

**Comment by mishkeTz** [comment]
I have the problem when using UrlTile with openstreetmaps templte. When trying to zoom-in/out or move the map it first shows the default map and then it loads openstreetmap on top of it.

It flickers and is not really nice.

**Comment by stdavis** [comment]
This appears to be fixed for me at v1.3.1 with the latest renderer enabled! At least in a development build using a custom expo dev client.

**Comment by diffent** [comment]
FYI we found a different flickering issue of the main google map and have a workaround (older version of react-native-maps though).  not sure it will fix your case, but for what it's worth, code snippets are in here.  caution:  you have to mod the ObjC:

https://github.com/react-native-maps/react-native-maps/issues/4459

**Comment by bhishaksanyal** [comment]
Thank you @MaRaSu for sharing the code to reproduce, I would like to suggest you try this for a smoother experience.
<img width="680" alt="replace" src="https://user-images.githubusercontent.com/26772694/192085871-5c185f47-763c-44b9-8f4e-50a30c54f2d4.png">

**Comment by stdavis** [comment]
This still appears to be an issue to me at iOS < 16. 16+ is fine.

**Comment by stdavis** [comment]
Still an issue at iOS < 16...
