### ISSUE TITLE
iOS MapKit Balloon Annotations

### ISSUE THREAD

**Issue by Nokoa** [react-native-maps/react-native-maps#3976]
Apple MapKit allows to create a marker by default in the shape of a balloon, the balloon is animated nicely into the map, becomes bigger and smaller when selected. An icon inside the balloon "glyphImage" can be changed, as well as the color of the balloon, "markerTintColor". Is this something that you support already, if not I would love to have this feature.

**Comment by antonjlin** [comment]
would also like this feature!

**Comment by jxxe** [comment]
+1 — Stale but unaddressed!

**Comment by peterjskaltsis** [comment]
Hi, was this ever added to this library? We'd love this, including the little native iOS animation & SFSymbol glyph that was mentioned^
