### ISSUE TITLE
iOS/Android - MapMarker accessibility issue

### ISSUE THREAD

**Issue by sspaceworld** [react-native-maps/react-native-maps#3981]
# Bug report

## Summary

Android - talkback does not recognize markers accessibility features (label/hint, etc)
iOS - voiceover does not recognize markers either. I saw a merged issue for `isAccessibilityElement` for iOS which should help with this however after merging in the latest react-native-map module, there was NO said prop. 

## Environment info

    "react-native": "0.64.2",
    "react": "17.0.1",
      react-native-maps: 0.29.3

## Steps to reproduce

1. Create mapview
2. Add mapmarkers
3. turn on talk back or voice over
4. see that the map markers are ignored

Describe what you expected to happen:

I expect the mapmarkers to be read by the screen reader

**Comment by salierg** [comment]
Same here. Any solution ?

**Comment by nschild** [comment]
I stumbled across this
https://stackoverflow.com/questions/18990030/how-to-add-contentdesctiption-to-infowindow-or-marker-in-android-googlemaps-v2-f

Android, at least, works when setting the title or description prop to whatever you want the screen reader to say.
