### ISSUE TITLE
fitToElements edgePadding does not work with ios native map

### ISSUE THREAD

**Issue by fakelag** [react-native-maps/react-native-maps#3984]
# Bug report

## Summary

edgePadding variable is not applied when using Apple Maps. This is likely due to the fact that unlike in [fitToCoordinates](https://github.com/react-native-maps/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L429-L459), where padding works perfectly, [fitToElements](https://github.com/react-native-maps/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L384-L400) does not refer to the `edgePadding` argument in any way.

The installation [document](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md) states that the default apple maps implementation is "missing some of the features supported by the Google Maps backend." Could this be a missing feature? Are there other missing features, and are they documented somewhere? Could support for edgePadding be added, as right now the react-native API works inconsistently depending on the platform/map backend? 

## Environment info

```bash
      react-native: 0.64.1
      react: 17.0.1
      react-native-maps: 0.29.3
```

## Steps to reproduce
1. Make a react native application for iOS, using react-native-maps with the default Apple Maps backend
2. Create a map component and receive its instance via a ref
3. Create few marker elements on the map
4. Call fitToElements like so:
```
        mapView.current?.fitToElements({
            edgePadding: {
                bottom: 200,
                left: 0,
                right: 0,
                top: 0,
            },
        });
```

## Describe what you expected to happen:

The map centers around the markers, adding 200 pixels of space at the bottom

## Describe what you actually happens:

The map centers around the markers, without padding at the bottom

**Comment by DanDance** [comment]
MapView API says `Note edgePadding is Google Maps only`

**Comment by fakelag** [comment]
> MapView API says `Note edgePadding is Google Maps only`

it would be epic if that could be changed

**Comment by Simon-TechForm** [comment]
Closing this for now. Feel free to open a new issue as a feature request.
