### ISSUE TITLE
New Google Maps SDK Renderer

### ISSUE THREAD

**Issue by Borduhh** [react-native-maps/react-native-maps#3991]
# Feature request

## Why it is needed

All devices on Android 5.0 (Lollipop) or later with 2 GB or more of data storage will use the new renderer. All other devices will continue to use the legacy renderer until further notice. SDK Progressive Rollout beginning March 2022.

## Possible implementation

Upgrade Maps SDK to the new renderer (https://developers.google.com/maps/documentation/android-sdk/renderer)

**Comment by anirudhabhurke** [comment]
+1 👍

**Comment by salah-ghanim** [comment]
I will take this issue, it looks simple to implement and for now I would just expose a prop to choose the renderer type.

the only issue I see is that the SDK demo shows initialization on application create, so it might be too late if we do it via prop (when view is loaded).

**Comment by pke** [comment]
Is there any action required at all here? This repo still uses Maps SDK 5.1 so its not affected by Google's changes.
Or am I missing something here?

**Comment by SuhilMohammad-rogers** [comment]
Everytime i add a new marker on the MapView, the MapView seems to rerender, it looks like its zooming in and out. i wonder if thats happening because this package is currently using the legacy renderer

**Comment by mak12** [comment]
Any timeline for this implementation ? current implementation isn't accepting `playServicesVersion:18.0.0` from project level configurations.

**Comment by siddharth-kt** [comment]
any update on this ?

**Comment by christopherdro** [comment]
@Borduhh @siddharth-kt @pke @mak12 @dishantwalia Please take a look at this open PR #4055. 
It would be very helpful if you can test the proposed changes with your app and report back with any issues you come across.

**Comment by Simon-TechForm** [comment]
The new renderer can be now be enabled starting from [v0.31.0-beta.2](https://github.com/react-native-maps/react-native-maps/releases/tag/v0.31.0-beta.2) which is released on the beta channel of npm. Props to @isidoro98.
