### ISSUE TITLE
Could we display the transit layer to show subway lines ?

### ISSUE THREAD

**Issue by StintouchDev** [react-native-maps/react-native-maps#3993]
# Feature request

Could we display the **transit layer** that you can find on Google Maps web site?

_Example:_ 
- https://www.google.com/maps/@40.7274935,-73.9144633,12z/data=!5m1!1e2  (New York City)
- https://www.google.com/maps/@51.5220982,-0.2207309,11.25z/data=!5m1!1e2  (London)
- https://www.google.com/maps/@48.8589466,2.2769955,12z/data=!5m1!1e2  (Paris)

## Why it is needed

This layer shows the **subway lines** and this is very useful in big cities like NYC, London, Paris... For apps which are related to transport or directions, this could be a plus.

## Possible implementation

I do not have a huge experience but I think the implementation of **transit layer** should be close to the **traffic layer** one.

### Code sample

```
import MapView from 'react-native-maps';


<MapView
    showsTransit={true}>
        ...
</MapView>
```

**Comment by christopherdro** [comment]
I took a quick look at it doesn't look like there is an API available that shows transit layers. However, you should be able to achieve this yourself by either using the `<Polyline />` or `< Geojson /> component if you can get the paths for the transit lines through another resource. e.g https://github.com/Esri/geojson-layer-js/blob/master/data/dc-metro-lines.json
