### ISSUE TITLE
Android soft-keyboard push the map resize 

### ISSUE THREAD

**Issue by alakdam07** [react-native-maps/react-native-maps#3995]
# Bug report

My React native Android-Manifest file keyboard input mood is:

` android:windowSoftInputMode="adjustResize">` //adjustPan or adjustNothing is not an option

## Summary
Under the React native maps I have Search input. When Search input is focus, Android soft-keyboard appeared and make map resize. Did not find any right solution.  

## Environment info

  Please specify the react, react-native, react-native-maps versions, eg:

      react-native: 0.66.0
      react: 17.0.2
      react-native-maps: ^0.29.3 

`react-native info` output:

```bash
    react-native: 0.66.0
    react: 17.0.2
    react-native-maps: ^0.29.3 
```

## Demo 

[Expo-snacks](https://snack.expo.dev/@alakdam/3fcbaa)

## Expected behavior:

- Maps should not react anything when Input focus

## Current behavior:

- It push the maps to resize

## Reproducible sample code

```
import React, { useState, useEffect } from "react";
import { StyleSheet, Button } from "react-native";
import MapView from "react-native-maps";
import styled from "styled-components";

const initialRegion = {
  latitudeDelta: 5,
  longitudeDelta: 5,
  latitude: 64.1098678,
  longitude: 24.7385084,
};

export default function App() {
  return (
    <>
      <MapView style={styles.mapStyle} initialRegion={initialRegion} />
      <SearchContainer>
        <SearchInput />
      </SearchContainer>
    </>
  );
}

const styles = StyleSheet.create({
  mapStyle: {
    flex: 1,
  },
});

const SearchContainer = styled.View`
  padding: 10px;
  flex: 0.2;
`;

const SearchInput = styled.TextInput`
  padding-right: 16px;
  color: #fff;
  font-size: 16px;
  line-height: 20px;
  height: 44px;
  background-color: green;
`;

```

**Comment by alakdam07** [comment]
> # Bug report
> My React native Android-Manifest file keyboard input mood is:
> 
> ` android:windowSoftInputMode="adjustResize">` //adjustPan or adjustNothing is not an option
> 
> ## Summary
> Under the React native maps I have Search input. When Search input is focus, Android soft-keyboard appeared and make map resize. Did not find any right solution.
> 
> ## Environment info
> Please specify the react, react-native, react-native-maps versions, eg:
> 
> ```
>   react-native: 0.66.0
>   react: 17.0.2
>   react-native-maps: ^0.29.3 
> ```
> 
> `react-native info` output:
> 
> ```shell
>     react-native: 0.66.0
>     react: 17.0.2
>     react-native-maps: ^0.29.3 
> ```
> 
> ## Demo
> [Expo-snacks](https://snack.expo.dev/@alakdam/3fcbaa)
> 
> ## Expected behavior:
> * Maps should not react anything when Input focus
> 
> ## Current behavior:
> * It push the maps to resize
> 
> ## Reproducible sample code
> ```
> import React, { useState, useEffect } from "react";
> import { StyleSheet, Button } from "react-native";
> import MapView from "react-native-maps";
> import styled from "styled-components";
> 
> const initialRegion = {
>   latitudeDelta: 5,
>   longitudeDelta: 5,
>   latitude: 64.1098678,
>   longitude: 24.7385084,
> };
> 
> export default function App() {
>   return (
>     <>
>       <MapView style={styles.mapStyle} initialRegion={initialRegion} />
>       <SearchContainer>
>         <SearchInput />
>       </SearchContainer>
>     </>
>   );
> }
> 
> const styles = StyleSheet.create({
>   mapStyle: {
>     flex: 1,
>   },
> });
> 
> const SearchContainer = styled.View`
>   padding: 10px;
>   flex: 0.2;
> `;
> 
> const SearchInput = styled.TextInput`
>   padding-right: 16px;
>   color: #fff;
>   font-size: 16px;
>   line-height: 20px;
>   height: 44px;
>   background-color: green;
> `;
> ```

**Comment by Willham12** [comment]
@alakdam07 do you found an solution?

**Comment by alakdam07** [comment]
https://stackoverflow.com/questions/17410499/difference-between-adjustresize-and-adjustpan-in-android
