### ISSUE TITLE
OnZoom event property

### ISSUE THREAD

**Issue by BlackBearFTW** [react-native-maps/react-native-maps#4000]
# Feature request

I would like the MapView to have a property that takes a function when the user zooms on the map, the function argument would be the level that was zoomed to. 

## Why it is needed

Currently there is no way to hide a marker when the user is zoomed out a certain level, with this function you could implement something like that yourself. 

### Code sample

```
<MapView
   onZoom={zoomLevel => (
      showMarker(zoomLevel < 5); 
   )}
 >
</MapView>
```

**Comment by BlackBearFTW** [comment]
There are ofcourse other use cases as well

**Comment by adamwlev** [comment]
I think onRegionChange/onRegionChangeComplete plus state that stores the zoom so you can tell if it changed solves for this usecase.

**Comment by Simon-TechForm** [comment]
Closing as this should be doable by using the solution proposed by @adamwlev.
