### ISSUE TITLE
com.facebook.react.common.JavascriptException: IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)

### ISSUE THREAD

**Issue by krishna11124** [react-native-maps/react-native-maps#4003]
# Bug report

## Environment info

`react-native info` output:

```bash
      react-native: 0.61.5
      react: 16.9.0
      react-native-maps: ^0.25.0
```

## Steps to reproduce

Use Polygon Component API
While Draw A Polygon

Describe what you expected to happen:

I am using react-native maps 0.25.0 for draw a polygon on map and i am getting this crash in crash analytics on android 11

Describe what you actually happens:

1.It will Throw IllegalArgumentException 
2.Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)

**Comment by Simon-TechForm** [comment]
You should probably not expect a whole lot of attention to this, as you are running a version that's almost 2.5 years old. Granted, the issue might still persist, but you should test for yourself if it is fixed in the latest version (as pointed out in the issue template).

**Comment by krishna11124** [comment]
Okey.thanks
