### ISSUE TITLE
MapView doesn't zoom out all the way to show the full world map

### ISSUE THREAD

**Issue by ronnaf** [react-native-maps/react-native-maps#4004]
# Bug report

## Summary

Basically, I'm trying to make the MapView zoom out all the way to show the full world map like the behaviour in [Angular Google Maps](https://angular-maps.com/guides/getting-started/) or [Google Maps' Styling Wizard](https://mapstyle.withgoogle.com/). It seems to be bounded by the current size of the map. How does one bypass this boundary in zooming out? Am I missing something?

Thanks!

## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
react: 17.0.2 => 17.0.2
react-native: 0.65.1 => 0.65.1
```

## Steps to reproduce

1. Install react-native-maps in a react-native project
2. Add a sample react-native-maps usage code.
3. Zoom out the map

Describe what you expected to happen:

1. The map zooms all the way out to display the full world map

Describe what you actually happens:

1. The map does not zoom all the way out and is bounded based on the current width of the device.

## Reproducible sample code

Any snack that has react-native-maps code.

**Comment by Simon-TechForm** [comment]
`react-native-maps` doesn't add any boundary for how far you can zoom out, this is decided by the native SDK, and should be the same (or close to) what you would expierence when opening the Google Maps/Apple Maps app on your phone :)
