### ISSUE TITLE
new AnimatedRegion not returning correct coordinates

### ISSUE THREAD

**Issue by zoolle** [react-native-maps/react-native-maps#4010]
I am using the last version 0.30.0 and since I've updated the following is no longer working

```
const newCoordinate = new AnimatedRegion({
      latitude: coordinate.latitude,
      longitude: coordinate.longitude,
      latitudeDelta: LATITUDE_DELTA,
      longitudeDelta: LONGITUDE_DELTA,
    });
```

is returning `{"latitude": 0, "latitudeDelta": 0, "longitude": 0, "longitudeDelta": 0}` while data is never 0 for any of them

**Comment by christopherdro** [comment]
@jasonmichaels Can you help out here?

**Comment by jasonmichaels** [comment]
@christopherdro Got a fix [here](https://github.com/react-native-maps/react-native-maps/pull/4011). That was my oversight, admittedly. I've also added preliminary dev-only tests to confirm the changes return the expected values.

**Comment by zoolle** [comment]
@jasonmichaels @christopherdro problem solved now thank you very much. I will close this now

**Comment by christopherdro** [comment]
@zoolle what changed? Did you test the changes in https://github.com/react-native-maps/react-native-maps/pull/4011?

**Comment by zoolle** [comment]
@christopherdro yes I've installed the package from branch and now everything seem fine
