### ISSUE TITLE
Don't crash when Android API key is not set

### ISSUE THREAD

**Issue by pke** [react-native-maps/react-native-maps#4015]
# Feature request

This package should prevent the app from hard crashing when the Google Maps SDK API Key is not set in the manifest.

## Why it is needed

This always causes great confusion among developers, when they don't have their `.env` file properly set up.

## Possible implementation

The android plugin here could check, if the `com.google.android.geo.API_KEY` is set in the manifest otherwise render a view that simply states that the key is missing.

This problem does not occur on ios, where the Google SDK wisely does not crash but render an empty map (with google attribution).

**Comment by Simon-TechForm** [comment]
What developers are you representing? ;)

Joking aside, can you elaborate on how this would improve the dev experience?

Android throws with a message saying: `API key not found. Check that <meta-data-android:name:="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml`.

How is that more confusing than an empty map? Or is that not the message you are seing?

**Comment by pke** [comment]
It might print the message but still crashes the app. 
When in React native one rarely monitors the  native log stream and won't see that log entry.

**Comment by Simon-TechForm** [comment]
So to narrow down the issue/feature request, this is only a problem when running on a psysical device through the react native cli, correct? Running through Android Studio would provide the native log, and running on an emulator would show the native error in the logbox?

I see how the feature would provide value in the case of cli + psysical device.

**Comment by pke** [comment]
I can check again if it happens in the emulator as well.

**Comment by Simon-TechForm** [comment]
Closing for now. If you believe that this is still relevant, feel free to open a new issue following the feature request template.
