### ISSUE TITLE
Update google-maps dependency to version 5.x

### ISSUE THREAD

**Issue by hesan-aminiloo** [react-native-maps/react-native-maps#4016]
I'm trying to upgrade the `GoogleMaps` Podfile dependency to version 5.x but it keeps telling me that `react-native-maps` depends on version `3.5`. Is there any way to upgrade the dependency?

**Comment by Simon-TechForm** [comment]
Seems to be done in https://github.com/react-native-maps/react-native-maps/releases/tag/v0.30.0 (See: https://github.com/react-native-maps/react-native-maps/pull/3973)

**Comment by Simon-TechForm** [comment]
I'm not really sure myself what releases gets picked out as being pre-releases, and thus not released on npmjs.com. Maybe @christopherdro can shed some light on this?

**Comment by alexqhj** [comment]
I think this needs to be bumped even further, to 6.0 to be compatible with M1 macs.

**Comment by bhishaksanyal** [comment]
@hesan-aminiloo Can you please try testing from the master branch? Probably we can close this issue if all is good
