### ISSUE TITLE
Is supportLibVersion required for react-native-maps?

### ISSUE THREAD

**Issue by CostachescuCristinel** [react-native-maps/react-native-maps#4018]
The Android installation instructions specify to add some keys to the `buildscript`.
However, it is not clear from the docs wether the key `supportLibVersion` is an actual required key for `react-native-maps` to function properly or not.

Is it required?

The default `react-native` android project does not include this key (expo bare workflow also does not).  
If this key is not required (as far as I can tell, this is the case), please remove it from the installation instructions. Alternativelty, please specify which keys are exactly required to be added. The example code there makes it confusing.

**Comment by Simon-TechForm** [comment]
supportLibVersion should no longer be required since #3106, and we are running successfully without specifying it.

Feel free to submit a pr. to improve the documentation.

**Comment by Simon-TechForm** [comment]
Closing for now. If you believe that this is still relevant, please feel free to open a new issue following the feature request template.
