### ISSUE TITLE
<Marker /> does not have property isPreselected

### ISSUE THREAD

**Issue by riancz** [react-native-maps/react-native-maps#4021]
# Bug report

## Summary

It is mentioned in [docs for <Marker /> ](https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md), that <Marker /> has prop `isPreselected` and `tappable`.  However in code it does not. I checked just these two props but maybe there are inconsistencies with more props. I need to be able to move the marker without any tapping and these props could help at least a little bit.

## Environment info

"react-native": "~0.63.4",
"react-native-maps": "^0.29.3",

**Comment by Simon-TechForm** [comment]
The `tappable` prop is iOS Google Maps only (as stated in the docs), and is included in v0.30.0.

`isPreselected` is Apple Maps only (as stated in the docs), and should be included in the source code, but is missing from the typescript declaration file. This should be fixed when #3985 is merged at some point.

**Comment by riancz** [comment]
Hmmm okay I found a reference to the isPreselected in MapMarker.js in propTypes. When I put it on the Marker it still didn't work. But that might be caused by the bug that makes other props (on <Map />) not working. (Controls not showing up).

**Comment by Simon-TechForm** [comment]
Closing for now. See: #4084. If you believe that this is still an issue, please feel free to open a new issue following the issue template.

**Comment by NavigilOMantere** [comment]
@Simon-TechForm Speaking of, any chance we could have that #4084 reviewed? It's a small change and easy to test.
