### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by riancz** [react-native-maps/react-native-maps#4024]
# Feature request

One of the very important feature for a map library is clustering, that's showing multiple markers that tare close by (depending on map zoom) as one marker. Could help performance and map readability.

## Why it is needed

As mentioned above in case of many markers such feature could help with performance, design and readability of the map underneath.

## Possible implementation

Found [this library](https://developer.apple.com/documentation/mapkitjs/mapkit/annotations/about_annotation_clustering) that is build on top of react-native-maps, however seems to be abandoned. Might be better to include it in the library since it is basic functionality.

**Comment by AlexMachin1997** [comment]
This would be really great to have as a standard feature, it's kind of expected for most map libaries.

I remember a few years ago trying this library out for the first time, I tried rendering the markes with no luck as i tried to render a few thoustand.

I've searched for a solution for this for a while, everyone who has created the solution is either out of date or overly complcated and difficult to actually understand.

@riancz Have you found any solutions for a temporarty workaround outside of the core react-native-maps library ?

**Comment by danieldanielecki** [comment]
I feel, [#2992](https://github.com/react-native-maps/react-native-maps/issues/2992) should've been opened.

**Comment by JiriHoffmann** [comment]
I created a clustering library [react-native-clusterer](https://github.com/JiriHoffmann/react-native-clusterer). It uses the c++ version of supercluster to make it even faster and with the `useClusterer` hook you can cluster points with literally one line of code.

**Comment by gen1lee** [comment]
@JiriHoffmann you can also add answer with your lib here https://stackoverflow.com/questions/39815649/react-native-maps-clustering
