### ISSUE TITLE
Execution failed for task ':app:mergeDebugAssets'. > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    > Could not find :react-native-maps':.      Required by:          project :app

### ISSUE THREAD

**Issue by Fiyaz6772** [react-native-maps/react-native-maps#4025]
## Summary

👋 Hi!

I am running react-native run-android and getting this error,

- [ ] report: FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :react-native-maps':.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s

## Environment info

`react-native info` output:

```bash
      react-native: 0.66.1
      react: 17.0.2
      react-native-maps: ^0.29.4
```

## Steps to reproduce

1. Follow instructions for android
2. … try run npm react-native run-android

Describe what you expected to happen:

1. Should work fine

Describe what you actually happens:

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :react-native-maps':.
     Required by:
         project :app

**Comment by Fiyaz6772** [comment]
I have sort it out. Thank You.

**Comment by KianSalehi** [comment]
How did you fix this? I'm having the same error, it seems to be from jCenter

**Comment by Thumendes** [comment]
@KianSalehi Me too.
```
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
```

**Comment by 32godev** [comment]
same here:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.flipper:flipper:0.54.0.
     Searched in the following locations:
       - file:/C:/Users/JD/.m2/repository/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
       - file:/C:/Users/JD/Documents/GitHub/RDUListingApp/node_modules/react-native/android/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
       - file:/C:/Users/JD/Documents/GitHub/RDUListingApp/node_modules/jsc-android/dist/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
       - https://www.jitpack.io/com/facebook/flipper/flipper/0.54.0/flipper-0.54.0.pom
     Required by:
         project :app
         project :app > project :react-native-flipper
   > Could not find com.facebook.flipper:flipper-network-plugin:0.54.0.
     Searched in the following locations:

**Comment by xAirx** [comment]
HOW DID YOU SOLVE IT

**Comment by tvpriyad** [comment]
ANY SOLUTION PLEASE

**Comment by raviSussol** [comment]
For those who are looking for fixes - upgrade the flipper version in the `android/gradle.properties` to your`react-native` compatible version. Mine is `FLIPPER_VERSION=0.99.0` for `react-native": "0.64.2"`.
