### ISSUE TITLE
Default zoom 

### ISSUE THREAD

**Issue by tb42** [react-native-maps/react-native-maps#4026]
# Feature request

Having a default zoom prop that can be applied when map is initially opened. The Google Maps API has this feature already. 

## Why it is needed

Customizing the zoom level for users is effective for tailoring to each dev's use case that they're building for. e.g. an app for a specific city will have a default zoom level that's focused on that 1 city, versus an app for a region will have a more zoomed out default. 
Right now, imo, the zoom level is way too zoomed in. 

I believe in Google Maps they take this prop to the extreme and the most zoomed out level is planet earth. react-native-maps should have something equivalent. 

### Code sample

      <MapView
        region={{
             initialZoom: 9
        }}
      />

**Comment by OrLevy23** [comment]
would also glad to have this

**Comment by isidoro98** [comment]
Hey @tb42 you can already specify the area of the map that is first shown on the screen using `latitudeDelta` and `longitudeDelta`.

This SO post explains it very good: https://stackoverflow.com/questions/36685372/how-to-zoom-in-out-in-react-native-map/36688156#36688156

**Comment by Simon-TechForm** [comment]
Closing for now as the answer provided by @isidoro98 should solve this. If you find that this is not the case, please feel free to open a new issue following the feature request template.
