### ISSUE TITLE
3D buildings for Android

### ISSUE THREAD

**Issue by atsushisuzuki0001** [react-native-maps/react-native-maps#4028]
Would you fix Android map for 3D buildings?
iOS map is displayed for 3D, but Android one isn't.
If you have some solutions, we'd like to know them.

Left picture is for Web. Right one is for Android.
<img width="696" alt="スクリーンショット 2021-12-03 11 23 47" src="https://user-images.githubusercontent.com/93562244/144536068-68b93739-458a-41b7-83f4-400163107840.png">

We'd appreciate your cooperation. 

Regards,

**Comment by isidoro98** [comment]
Using the new maps renderer seems to show 3D building in Japan. You should probably keep an eye on #3991. Once the update is done you should be able to see the building in the devices that can use the new renderer.

**Comment by WRiferreiro** [comment]
@atsushisuzuki0001 feel free to try #4055 and use the new renderer calling `useLatestsRenderer`, 3d buildings are working fine now.

**Comment by isidoro98** [comment]
@atsushisuzuki0001 feel free to try #4055 and use the new renderer calling useLatestsRenderer, 3d buildings are working fine now.
