### ISSUE TITLE
Example project maps are blank

### ISSUE THREAD

**Issue by Astronaut750** [react-native-maps/react-native-maps#4030]
# Bug report

## Summary

All of the maps in the examples project are blank, despite having followed the Examples Setup very thoroughly 😉. It doesn't work either after following the installation instructions again and filling in the missing??? lines in AndroidManifest.xml and build.gradle.
I also replaced the API key with my personal one.

## Environment info

OS: Windows 11
Target Platform: Android Virtual Device, Android 10 (Q), API 29

`react-native info` output:

```bash
 react-native: 0.65.1
 react: 17.0.2
 react-native-maps: 0.29.4
```

## Steps to reproduce

1. clone repo
2. cd example
3. npm install
4. npx react-native run-android

Describe what you expected to happen:

1. Maps are not blank

Describe what you actually happens:

1. Maps are blank

Most maps are blank
![image](https://user-images.githubusercontent.com/38164738/144910943-5db875ec-3532-4db6-a59d-e80812cba98c.png)

Polygon creator is grey
![image](https://user-images.githubusercontent.com/38164738/144911031-cbe15a39-4021-46b1-96a7-c86767f80d82.png)

Animating with MapViews is broken
![image](https://user-images.githubusercontent.com/38164738/144911496-e85abfa2-01de-4002-a0dd-2d9f8c299e72.png)

Cached Map has a ListView
![image](https://user-images.githubusercontent.com/38164738/144911885-9370a787-7a0f-4e13-9aaa-d79446d99165.png)

Image Overlay Component with Assets has a weird error
![image](https://user-images.githubusercontent.com/38164738/144912408-2212b852-1f68-48f9-83e9-ad257da6c7f6.png)

That's enough for today.

**Comment by mariomurrent-softwaresolutions** [comment]
Same here on Android. iOS is working fine

**Comment by christopherdro** [comment]
In almost all cases the issue with a blank map rendering on Android is related to the API key. Please take a look at some of the other related issues that have been opened in the past. https://github.com/react-native-maps/react-native-maps/search?q=blank+map&type=issues

**Comment by Astronaut750** [comment]
@christopherdro So does the example project work for you? If so, where did you insert your API key?

**Comment by palatshq** [comment]
I have the same problem with my live app. The maps are working fine on Expo Go and on iOS phones, however, on Android phones (the playstore app, works fine on Expo Go) the map is returned blank.

I double checked the API-key, and I even replaced it with a new one and pushed through playstore again, without any result.

I have tried reverting to older published releases, none of them work either now. Anyone knows whats up?

**Comment by mariomurrent-softwaresolutions** [comment]
> I have the same problem with my live app. The maps are working fine on Expo Go and on iOS phones, however, on Android phones (the playstore app, works fine on Expo Go) the map is returned blank.
> 
> 
> 
> I double checked the API-key, and I even replaced it with a new one and pushed through playstore again, without any result.
> 
> 
> 
> I have tried reverting to older published releases, none of them work either now. Anyone knows whats up?

Can you log the errors? Or do you see any errors in the log?

**Comment by christopherdro** [comment]
Please make sure that Maps SDK for Android is enabled. 

<img width="906" alt="Screen Shot 2021-12-20 at 3 16 38 PM" src="https://user-images.githubusercontent.com/3741055/146845197-11b8f171-27dd-4232-bc59-bd8a3703983d.png">

**Comment by Astronaut750** [comment]
I am currently working on my diploma project and am already using the MapView Component there and everything is working fine. Just the example project is completely bugged. So did you just clone the repo and start it and eveything worked fine?

**Comment by christopherdro** [comment]
I haven’t ran through all the examples but I wouldn’t be surprised if there are various bugs since the example app isn’t updated often. Pull requests are welcome.

**Comment by palatshq** [comment]
> Please make sure that Maps SDK for Android is enabled.
> 
> <img alt="Screen Shot 2021-12-20 at 3 16 38 PM" width="906" src="https://user-images.githubusercontent.com/3741055/146845197-11b8f171-27dd-4232-bc59-bd8a3703983d.png">

Yep, this was the issue. Thank you.

I find it strange that it worked for several months before, but oh well, at least it is working now.
