### ISSUE TITLE
Apple Maps on iOS emits spurious `onRegionChange` upon mount

### ISSUE THREAD

**Issue by alis0nc** [react-native-maps/react-native-maps#4031]
# Bug report

## Summary

Apple Maps emits two spurious `onRegionChange` events upon component mount. The first one has the coordinates of an intersection in Saratoga, CA (37.275419, -122.009200)*, and the second one has the coordinates of the `MapView`'s `InitialRegion`. 

\* In our actual app, we're getting the coordinates of [Apple Park](https://en.wikipedia.org/wiki/Apple_Park) (37.3346, -122.0092), but we're getting the coordinates in Saratoga when attempting to reproduce the problem with the example app. Not sure why the difference (viewport extents?), but either way it's a location that has nothing to do with the `InitialRegion`.

## Environment info

Our actual app: React 17.0.1, React Native 0.64.1, `react-native-maps` 0.26.1

Example app: React 17.0.2, React Native 0.65.1, `react-native-maps` master @ 6803510

`react-native info` output:

<details>
<summary>Our actual app:</summary>
<pre>
% npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 347.61 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/alisonc/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</pre>
</details>

<details>
<summary>Example app:</summary>
<pre>
% npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 138.10 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/alisonc/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</pre>
</details>

## Steps to reproduce

1. Start up the example app on iOS.
2. Visit the `Events` example
3. Observe that there are two `Map::onRegionChange` events before interacting with the map at all -- one of them in Saratoga, and the next at the lat/lon in `EventListener.js`.
4. Go back and toggle the Google Maps switch on.
5. Visit the Events example
6. Observe that there are no `Map::onRegionChange` events before interacting with the map

I expected that the behaviour of each map provider with `onRegionChange` events is consistent and doesn't emit any `onRegionChange` events before the map view scrolls.

## Reproducible sample code
This is reproducible on `master` branch at 6803510.

https://user-images.githubusercontent.com/4296609/144927986-ae831fc5-6997-4f2f-b5ff-dc8681d62ec4.mp4

**Comment by alis0nc** [comment]
Our use case is dismissing some help text when the user interacts with the map, so for our purposes `onPanDrag` is close enough. It doesn't fire when you perfectly pinch zoom without panning at all, but you're gonna need a hell of a lot of practice to do that on a real touchscreen.

**Comment by isidoro98** [comment]
Hey @alis0nc raised a PR that fixes the issue #4037, feel free to check it out!
