### ISSUE TITLE
Google released a major update of Maps SDK for Android (version 18.0.0)

### ISSUE THREAD

**Issue by auliakbarh** [react-native-maps/react-native-maps#4034]
I got an email from Google regarding Google releasing a major update of Maps SDK for Android (version 18.0.0).

Is it necessary to upgrade the Google Play Services version in `app/build.gradle`?

Reference:
https://developers.google.com/maps/documentation/android-sdk/renderer

**Comment by mak12** [comment]
waiting for this release.

**Comment by christopherdro** [comment]
Duplicate https://github.com/react-native-maps/react-native-maps/issues/3991
