### ISSUE TITLE
New Google Play requirements SDK 18.0.0

### ISSUE THREAD

**Issue by cedced19** [react-native-maps/react-native-maps#4035]
# Feature request

Is `react-native-maps` compilant with the [new Google Play requirements](https://developers.google.com/maps/documentation/android-sdk/renderer)?

If it is not the case, I suggest updating `com.google.android.gms:play-services-maps` to `18.0.0`.

(I searched into `react-native-maps` code and I found that `com.google.android.gms:play-services-maps` was set at `17.0.0`)

## Why it is needed

[New Google Play requirements](https://developers.google.com/maps/documentation/android-sdk/renderer)

## Possible implementation

Update to the new SDK (version 18.0.0).

Thank you all!

**Comment by christopherdro** [comment]
Duplicate #3991
