### ISSUE TITLE
Icons appear on google maps

### ISSUE THREAD

**Issue by riancz** [react-native-maps/react-native-maps#4044]
# Bug report

## Summary

After pressing on marker using google maps on android these two buttons appear in the lower right corner:
<img width="101" alt="image" src="https://user-images.githubusercontent.com/47085300/146750264-a9d667be-86a7-4f25-b6c2-20f18f641040.png">

Since there isn't any option to remove it as far as I know I think this must be bug that appeared because perhaps google added it in newer maps.

## Environment info

      "react": "16.13.1",
      "react-native": "~0.63.4",
      "react-native-maps": "^0.29.3",

    Target Platform: eg: Android - Pixel 4, API 30

**Comment by isidoro98** [comment]
Hey @riancz those icons can be turned on/off on Android Google maps using the MapView prop `toolbarEnabled`. Set it to false and they won't show anymore.

**Comment by riancz** [comment]
Oh thanks so much man! You are right!

**Comment by serdarcevher** [comment]
This is weird, since this toolbar is already disabled for iOS by default but it's only appearing in Android in my case. This makes it difficult to notice that it's a feature rather than a bug.
