### ISSUE TITLE
KML markers not showing on iOS

### ISSUE THREAD

**Issue by japaaak** [react-native-maps/react-native-maps#4051]
# Bug report
I'm trying to import the KML folder and show the markers.

On android it is working fine, but on iOS it is not showing the markers.

I did all the configuration of ios that is in the instruction, but it's not working.

I tested to put the "showsIndoorLevelPicker" in MapView to check if it is configured with the PROVIDER_GOOGLE, and the showsIndoorLevelPicker worked correctly. 

## Environment info
`react-native info` output:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
    Memory: 5.44 GB / 15.94 GB
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\yarn--1640762738272-0.9723123105369802\node.CMD
    Yarn: 1.22.17 - ~\AppData\Local\Temp\yarn--1640762738272-0.9723123105369802\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211 - C:\Program Files\Java\jdk1.8.0_211\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Packages:
    "expo": "~44.0.0"
    "expo-app-loading": "~1.3.0"
    "expo-cli": "^5.0.3"
    "react": "17.0.1"
    "react-native": "0.64.3"
    "react-native-maps": "0.29.4"

**Comment by zabojad** [comment]
https://github.com/react-native-maps/react-native-maps/issues/3190

**Comment by salah-ghanim** [comment]
@japaaak please try @zabojad fix .. if it doesn't work out please submit another ticket with more details.
