### ISSUE TITLE
Initial load of map will show world first and jump to initialRegion

### ISSUE THREAD

**Issue by manufunk** [react-native-maps/react-native-maps#4060]
# Bug report

## Summary

I'm using the google maps provider with expo. If I test my map on Android, the map will first be displayed with a 0 zoom of the whole world. After a second or less, the `initialRegion` (or initialCamera - I tried both) is used and it will display my defined location. However I would expect the map to respect the initial coordinates right from the beginning without showing the zoomed out world first. I also tried the `loadingEnabled` flag to see if this changes anything. Sadly this will just add the loading spinner between the firstly showed zoomed out map and the initial coordinates. On iOS it works as expected.

Is someone else having the same issues?

## Environment info

react-native: 0.64.3
react-native-maps: 0.30.1
expo: 44.0.4

Target Platform: Android 12

## Reproducible sample code

```

const Test = () => {
  return (
    <View flex={1}>
      <MapView
        style={{ flex: 1 }}
        initialRegion={ConfigLimits.defaultLocation}
        loadingEnabled
        provider={PROVIDER_GOOGLE}
      ></MapView>
    </View>
  );
};

export default Test;
```

**Comment by dlombardi** [comment]
Same issue

**Comment by chrismerino** [comment]
I'm having the same issue on RN 0.63.3

**Comment by margabit** [comment]
Same issue

**Comment by jamesjara** [comment]
Same issue
