### ISSUE TITLE
Not working properly with RN 0.67 (RC 6)

### ISSUE THREAD

**Issue by harensarma** [react-native-maps/react-native-maps#4062]
May be my mistake, but it was working fine till RN 0.66 (stable) but not working with RN 0.67 (RC 6). The complete issue is here: [https://stackoverflow.com/questions/70657797/react-native-maps-issue-in-ios-app-undefined-symbols-for-architecture-x86-64](https://stackoverflow.com/questions/70657797/react-native-maps-issue-in-ios-app-undefined-symbols-for-architecture-x86-64)

Please help me to resolve.

**Comment by christopherdro** [comment]
Just merged the following PR that might resolve your issue. https://github.com/react-native-maps/react-native-maps/pull/4061

Can you try testing from the master branch?

**Comment by harensarma** [comment]
> Just merged the following PR that might resolve your issue. #4061
> 
> Can you try testing from the master branch?

I have tested from master branch, getting this : https://pastebin.com/aMBYDH61

**Comment by Parlegrandpa** [comment]
@harensarma I'm also having a similar issue. Are you able to fix it?

**Comment by harensarma** [comment]
> @harensarma I'm also having a similar issue. Are you able to fix it?

I have reverted back to RN 0.66.4 .. now working fine..

**Comment by rodrigodiasf1984** [comment]
I've spent the entire day trying to find a solution and finally, i did compile the ios project right now following this: 
https://gist.github.com/badsyntax/72c5c965fcaefe66d049a8c2cdf34198 

I hope this can help!

**Comment by Simon-TechForm** [comment]
Closing in favour of #3527 and #4097.
