### ISSUE TITLE
Circle in ios with Provider_Google

### ISSUE THREAD

**Issue by claudiarsl** [react-native-maps/react-native-maps#4064]
# Bug report
Circle in ios with Provider_Google

## Summary
When I use PROVIDER_GOOGLE in MapView and test on iPhone, the circle just has a black line and doesn't assume the fill color and stroke color. If I remove the provider or use PROVIDER_DEFAULT, the circle takes on all the props I defined with all the correct colors.

## Environment info

```
  "expo": "~42.0.1",
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-maps": "0.28.0",
```
    Target Platform: iOS - 15.1 iPhone XS

My Code:
` <MapView
            onPress={onMapPress}
            ref={mapRef}
            provider={PROVIDER_GOOGLE} 
            style={styles.map}
            initialRegion={location}
            onMapReady={getZoomLevel}
          >
 <Circle
              ref={circleRef}
              center={location}
              radius={Number(selectedRadius)} // radius is in meters
              strokeWidth={1}
              fillColor="rgba(0,69,255,0.1)"
              strokeColor="rgba(0,69,255,0.6)"
            />
</MapView>`

If I remove the provider on MapView, the circle appears with the right fill and stroke Color. But I would like to use Google Maps in both platforms (iOS and android).

**Comment by Simon-TechForm** [comment]
Hi @claudiarsl. Yeah, this seems to be an issue in the Google Maps SDK for iOS. Closing in favour of #3057.
