### ISSUE TITLE
Zoom messes with map boundaries?

### ISSUE THREAD

**Issue by Rc85** [react-native-maps/react-native-maps#4071]
# Bug report

## Summary

Not sure if this is intended but it seems like the coordinates supplied to setMapBoundaries is setting the size of the view port rather than the how far north/south/west/east your view port can go.

![Screenshot_20220118-122204_MT Drivers](https://user-images.githubusercontent.com/22307591/150013620-6854df19-8b22-4165-80cc-a98869f6fe5f.jpg)

Notice the boundary shown by the arrow and notice where Pitt Meadows is.

![Screenshot_20220118-122242_MT Drivers](https://user-images.githubusercontent.com/22307591/150013695-00992fd0-1377-47d8-b02a-38246bbbf3b9.jpg)

The red arrow here is the most I can scroll to, which is not the boundary that I have set. It's way far left than the one shown in the first picture. Notice where Pitt Meadows is in this picture. I should be able to scroll to the right more to see Golden Ears Provincial Park.

## Environment info

`react-native info` output:

  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.66.1 => 0.66.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
"react-native-maps": "^0.27.1",

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. Set map boundaries
2. Scroll map to edge of any boundary.
3. Zoom in.

Describe what you expected to happen:

You should always be able to reach the specified boundary no matter how zoomed in you are.

Describe what you actually happens:

You cannot scroll to the specified boundaries if you zoom in past a point.

**Comment by Simon-TechForm** [comment]
@Rc85 I'm going to close this for now, as I'm gonna have to have you test this on the latest version of react-native-maps and also provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Granted, the issue might still persist, but you are running a 2 year old version of the library.

Please feel free to open a new issue following the issue template if you find out that this is still an issue :)
