### ISSUE TITLE
[Android] Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by sainteye** [react-native-maps/react-native-maps#4074]
[This is an Android Issue]

Hi, our team use react-native-maps in our production. After we upgrade to RN 0.63, we notice some our users get **"Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference"** error when they leave app for a long time and get back to app again.

<img width="770" alt="screenshot" src="https://user-images.githubusercontent.com/573936/150510358-379117b3-ca6b-4708-9f3a-a7adf09cc48c.png">
<img width="857" alt="error log" src="https://user-images.githubusercontent.com/573936/150510436-fb0dd3ca-1d56-4d62-a788-72f98130ea32.png">

After some research, we find out it might be caused by AirMapView.java "onMyLocationChange", "onHostResume" or "dispatchTouchEvent". We check is the map null by:
`if (map==null) {return;}`
in these three functions. (As the figure shown, we fixed this issue in v5.1.3)

Since we patch these three functions, we never see the react native error happen again.

Can react-native-maps dev team please add these patch to the master release? Thanks!

**Comment by jineshmistry1312** [comment]
Still facing the same issue in latest version 1.3.1
![image](https://user-images.githubusercontent.com/47143115/189650143-6c9894f0-a8cc-4ec8-952b-5f620e0cf1ca.png)

**Comment by ilya-raevskiy** [comment]
> Still facing the same issue in latest version 1.3.1 ![image](https://user-images.githubusercontent.com/47143115/189650143-6c9894f0-a8cc-4ec8-952b-5f620e0cf1ca.png)

Same

**Comment by saransh-malik** [comment]
@Simon-TechForm I guess this issue is still existing even in latest versions, can we get this issue reopened?

**Comment by hsource** [comment]
Just a note - for us, the fix was adding this line to the react-native-maps MapMarker.js file

```ts
     _runCommand(name, args) {
        const handle = this._getHandle();
        if (!handle) return;
        // .. Rest of code
```

The issue was because sometimes, the handle wouldn't exist because the marker or map would've already unmounted.

**Comment by simongt** [comment]
> Just a note - for us, the fix was adding this line to the react-native-maps MapMarker.js file
> 
> ```ts
>      _runCommand(name, args) {
>         const handle = this._getHandle();
>         if (!handle) return;
>         // .. Rest of code
> ```
> 
> The issue was because sometimes, the handle wouldn't exist because the marker or map would've already unmounted.

Thank you @hsource, good to know. Curious, which version of `react-native-maps` are you using for this? I don't see a `_runCommand` function in `MapMarker.js`. Maybe it's intended for a version before/after the `this.marker` ref was introduced? I'm using 1.3.2 myself and seeing this error.
