### ISSUE TITLE
AirMapCoordinate.h file not found

### ISSUE THREAD

**Issue by teodorusluo** [react-native-maps/react-native-maps#4075]
Hi,

I got an error "AirMapCoordinate.h file not found" while build the code with XCODE 13.1.

Here is my system:
1. XCODE -> 13.1
2. REACT-NATIVE -> 0.64.2
3. REACT-NATIVE-MAPS -> 0.30.1

Here is my PodFile
`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

use_frameworks! :linkage => :static

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        # Uncomment the line corresponding to your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end

def appodeal
    pod 'APDAdColonyAdapter'
    pod 'APDAmazonAdsAdapter'
    pod 'APDAppLovinAdapter'
    pod 'APDBidMachineAdapter'
    pod 'APDFacebookAudienceAdapter'
    pod 'APDGoogleAdMobAdapter'
    pod 'APDIronSourceAdapter'
    pod 'APDMyTargetAdapter'
    pod 'APDOguryAdapter'
    pod 'APDSmaatoAdapter'
    pod 'APDStartAppAdapter'
    pod 'APDUnityAdapter'
    pod 'APDVungleAdapter'
    pod 'APDYandexAdapter'
end

target 'testapplication' do
  permissions_path = "../node_modules/react-native-permissions/ios"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'testapplicationTests' do
    inherit! :complete
    # Pods for testing
  end
  
  appodeal
  
  post_install do |installer|
    react_native_post_install(installer)
  end
end
`
Here is my AppDelegate.m
<img width="555" alt="Screen Shot 2022-01-22 at 13 51 54" src="https://user-images.githubusercontent.com/16112468/150628379-42668b02-0229-4267-bf51-662078573914.png">

Here is my Header Search Path
<img width="534" alt="Screen Shot 2022-01-22 at 13 52 49" src="https://user-images.githubusercontent.com/16112468/150628403-c41165eb-699d-49e5-a52d-11222180c45a.png">

I already look at another issue reports about it, I already tried everything but still not works.
<img width="377" alt="Screen Shot 2022-01-22 at 13 54 21" src="https://user-images.githubusercontent.com/16112468/150628432-949933ea-fe46-4120-9c84-0ade9d8d0d33.png">

Please help

**Comment by agupta-avenir** [comment]
I am also facing the same issue suddenly. This has been working earlier.
Project Config:
XCODE -> 13.1
REACT-NATIVE -> 0.65.1
REACT-NATIVE-MAPS -> 0.28.0

**Comment by thorfinnko** [comment]
same here was working fine until a week ago

**Comment by agupta-avenir** [comment]
It got automatically fixed. Try clearing cache and pod repo update might help.

**Comment by devlooppro** [comment]
Same issue!

**Comment by Simon-TechForm** [comment]
Closing for now. If you keep experiencing this issue, please feel free to open a new issue following the bug issue template.

**Comment by dlombardi** [comment]
I'm experiencing this issue! It's after upgrade to Expo SDK 46

**Comment by caferyukseloglu** [comment]
https://github.com/react-native-maps/react-native-maps/issues/3597#issuecomment-1168582636

**Comment by zoobibackups** [comment]
same its issue

**Comment by virgiliosolano** [comment]
Fixed here: https://github.com/react-native-maps/react-native-maps/issues/3597
