### ISSUE TITLE
Web Support for React Native Maps

### ISSUE THREAD

**Issue by Josefpa** [react-native-maps/react-native-maps#4078]
Hey

Please add support for React Native Web

**Comment by lekzd** [comment]
@Josefpa you can use `react-native-web-maps` as well. Just add it as alias to your webpack config

**Comment by Josefpa** [comment]
Yes But it is missing a lot of features

**Comment by oliverloops** [comment]
Google Maps web SDK has some similarities to mobile native maps, but it is possible to share code between these platforms?

**Comment by Simon-TechForm** [comment]
Closing for now. If this is still relevant, please feel free to open a new issue following the feature-request issue template.

**Comment by NilsBaumgartner1994** [comment]
Still relevant

**Comment by guplem** [comment]
Yeah, still relevant. 
Do you think this package would work without issues with [solito](https://solito.dev/)?

**Comment by JupiterXiaoxiaoYu** [comment]
> Yeah, still relevant. Do you think this package would work without issues with [solito](https://solito.dev/)?

Have you figured it out? I'm also wondering
