### ISSUE TITLE
Android device crash instantly - no logs.

### ISSUE THREAD

**Issue by Oriole-Alex** [react-native-maps/react-native-maps#4079]
# Bug report

Adding react-native-maps with following values:

playServicesVersion = "18.0.0"
androidMapsUtilsVersion = "2.3.0"

will immediately crash the app on android device at launch. However launches on a emulator. That said, the map is greyed out on the emulator (havent looked for solution to this yet until I had solved physical device launch).

The difficulty I'm facing is there are no crash logs and otherwise nothing to indicate the app shouldnt be running correctly and so no direction to look in for why it's failing. I've tried gradlew clean. I've tried adding the following instead 

implementation(project(':react-native-maps')){
       exclude group: 'com.google.android.gms', module: 'play-services-base'
       exclude group: 'com.google.android.gms', module: 'play-services-maps'
   }
   implementation 'com.google.android.gms:play-services-base:17.2.1'
   implementation 'com.google.android.gms:play-services-maps:17.0.0'

but to no avail. Sorry if I'm doing something stupid - I've read every possible issue listed on here that seems vaguely related but no solution has come up.

## Environment info

react-native: 0.66.3
react: 17.0.2
react-native-maps: 0.30.1

## Steps to reproduce

1. Add react-native-maps dependency.
2. Add playServicesVersion = "18.0.0" and androidMapsUtilsVersion = "2.3.0" to /android/build.gradle
3. Add <meta-data android:name="com.google.android.geo.API_KEY" android:value="XXX"/> and <uses-library android:name="org.apache.http.legacy" android:required="false"/> to android/app/src/main/androidmanifest.xml.
4. I've been clicking 'sync projects with gradle files' button in android studio as well before running npx react-native run-android.
5. App will build successfully and briefly show a white screen on the device before crashing without any logs/error message.

**Comment by renchap** [comment]
I dont know if this is related, but I just submitted #4080 for a similar issue. Do you have `compileSdkVersion = 31` in your `android/build.gradle`?

If yes, this is the issue and you can add `implementation "androidx.work:work-runtime:2.7.1"` to the `dependencies` block in `android/app/build.gradle`.

If you want to troubleshoot this further, you need to use `adb logcat -T 20` after having [paired your device with `adb`](https://developer.android.com/studio/command-line/adb), you will get all the device debug logs and should be able to see why it does not start.

**Comment by Oriole-Alex** [comment]
Thanks very much! This is perfect!
