### ISSUE TITLE
addressForCoordinate - TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Oriole-Alex** [react-native-maps/react-native-maps#4081]
# Bug report
## Summary

Trying to use addressForCoordinate  method returns [TypeError: undefined is not a function].
Apologies if I've imported something wrongly but I can't find any code examples to copy from. The code I'm using is from the issue https://stackoverflow.com/questions/67490594/react-native-maps-convert-coordinates-to-address and I'm using onRegionChangeComplete as per (https://github.com/react-native-maps/react-native-maps/issues/3955) but nothing seems to work.

## Environment info

      react-native: 0.66.3
      react: 17.0.2
      react-native-maps: 0.30.1 using GoogleMaps on android device

## Steps to reproduce

1. use onRegionChange to grab the address of the new coordinates

Describe what you expected to happen:

Expected an output of a physical address correlating to the selected coordinates

Describe what you actually happens:

Received the following error message: [TypeError: undefined is not a function]

## Reproducible sample code

import React from 'react'
import MapView, { addressForCoordinate } from 'react-native-maps'
import styles from './styles'

function Map() {

    async function ConvertToAddress(coordinates) {
        console.log(coordinates)
        try {
            addressForCoordinate(coordinates).then(address => console.log(address))
        } catch(e) {
            console.log(e)
        }
        
    }

    return (
        <MapView
        style={styles.map}
        initialRegion={{
            latitude: 51.5098,
            longitude: -0.1180,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        }}
        onRegionChangeComplete={event => ConvertToAddress({"latitude": event.latitude, "longitude": event.longitude})}
        />
    )
}

export default Map;

**Comment by Simon-TechForm** [comment]
Hi @Oriole-Alex :)

`addressForCoordinate` is a member of MapView. Try something like this:

```ts
import React, {useRef} from 'react';
import {StyleSheet} from 'react-native';
import MapView, {Region} from 'react-native-maps';

export default function App() {
  const mapViewRef = useRef<MapView>(null);

  const regionChangeCompleteHandler = async (region: Region) => {
    console.log(
      await mapViewRef.current?.addressForCoordinate({
        latitude: region.latitude,
        longitude: region.longitude,
      }),
    );
  };
  return (
    <MapView
      ref={mapViewRef}
      style={styles.mapView}
      onRegionChangeComplete={regionChangeCompleteHandler}
    />
  );
}

const styles = StyleSheet.create({
  mapView: {
    flex: 1,
  },
});

```
