### ISSUE TITLE
Custom Marker gets bigger when zoom out

### ISSUE THREAD

**Issue by khaledtag98** [react-native-maps/react-native-maps#4086]
Hello there ,

When I zoom out the markers get bigger. How to make it fixed size

**Comment by khaledtag98** [comment]
Original 
![B9E8BEC0-1055-4B6C-A9E3-162C72A5D728](https://user-images.githubusercontent.com/55442919/151899316-d399d1c5-db0c-4f66-9188-61219b0a1b62.jpeg)

**Comment by khaledtag98** [comment]
Zoom out ( makers scales up and get bigger)
![E60AB7BE-FE68-4742-8369-8B51C283F53E](https://user-images.githubusercontent.com/55442919/151899385-6c8f8097-e9af-46ad-8362-183ecba0f4c3.jpeg)

**Comment by alunparanggi** [comment]
I don't think those markers get bigger, the size is still same it just the map is getting smaller because you zoomed it out

**Comment by jaskp** [comment]
And is there a way around it?

**Comment by Simon-TechForm** [comment]
There's no build in way to do this. I assume you could work something out by tracking the latitude/longitude-delta in `onRegionChange` and changing your custom view size based on this. I haven't tried this though.

I'm going to close this for now.

**Comment by rossjcooper** [comment]
I'm also having this issue, the docs have been updated about how to generate different resolution images to make them scale better but I'm still a bit stuck on how to do this https://github.com/react-native-maps/react-native-maps/pull/3771
