### ISSUE TITLE
Google Maps SDKs 

### ISSUE THREAD

**Issue by fristyr** [react-native-maps/react-native-maps#4087]
# Bug report
Hi all!
I received a message from Google about Maps that Google Maps SDK beta will be disabled and new supported versions available now.
What this should mean??

A bit of text from email bellow

What do I need to know?
App versions built with the mobile Maps SDKs (Android & iOS) beta (versions 3.0.0, 3.1.0, and 3.10.0) will not work once the beta versions are decommissioned, no earlier than November 2022.

## Environment info

Expo SDK 43
react-native: 0.64.3
react: 17.0.1
 eact-native-maps: 0.28.1

**Comment by flavrwebdev** [comment]
+1

**Comment by jsjexpert** [comment]
+1

**Comment by oliuradu** [comment]
+1

**Comment by brianmharding13** [comment]
+1

**Comment by arunpugahz** [comment]
++1

**Comment by mgsesq** [comment]
+1

**Comment by brianmharding13** [comment]
According to line 31 of the [build.gradle](https://github.com/react-native-maps/react-native-maps/blob/master/lib/android/build.gradle) file, this repo uses SDK version [0.5](https://github.com/googlemaps/android-maps-utils/releases/tag/0.5.0).

**Comment by marcelmedina** [comment]
The [build.gradle]([build.gradle](https://github.com/react-native-maps/react-native-maps/blob/master/lib/android/build.gradle)) file needs updating as per latest release [Android-SDK Releases](https://developers.google.com/maps/documentation/android-sdk/releases) to com.google.android.gms:play-services-maps:18.0.2

**Comment by oliverloops** [comment]
+1

**Comment by Simon-TechForm** [comment]
Closing this in favour of #3991.
