### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by 12944qwerty** [react-native-maps/react-native-maps#4091]
# Bug report

## Summary

I copied the example folder onto my computer and followed the instructions at the [setup](https://github.com/react-native-maps/react-native-maps/blob/master/docs/examples-setup.md). I still get an error (screenshot at bottom)

## Environment info

![image](https://user-images.githubusercontent.com/45984786/152468554-fcff4b9a-9bb7-4cb2-9df0-d25bc85554c5.png)

## Steps to reproduce

Download the example folder and follow the setup instructions

## Describe what you expected to happen:

Work? The app should work like example was supposed to.

## Describe what you actually happens:

![image](https://user-images.githubusercontent.com/45984786/152468417-5240cf68-fcbb-43fd-b76c-12f867e489c8.png)

**Comment by 12944qwerty** [comment]
After a bit of debugging, I noticed that it's returning this error from files that aren't even in the directory I'm using. Why is this happening? How to fix without moving files?

**Comment by Simon-TechForm** [comment]
Hello @12944qwerty. The example folder relies on being placed in the path that it is in, as it uses relative paths to resolve files. So you will have to download the entire repo, and keep the example folder as is :)

I'm going to close this for now, put please feel free to get back to me if this doesn't fix the issue.
