### ISSUE TITLE
How to show directions between two markers or points on Map

### ISSUE THREAD

**Issue by AhmedSarhan** [react-native-maps/react-native-maps#4092]
this is either a feature request or an inquiry about a feature

I would like to show my user on a React Native application the directions of a ride between two markers like in google maps, 
it would also be super helpful if I can show the estimated distance in KM / time in minutes or hours
is this available with this package or is there another way to do it?

**Comment by thomasviaud** [comment]
Hello, you can use : https://github.com/bramus/react-native-maps-directions

**Comment by AhmedSarhan** [comment]
thank you a lot this was really super helpful

**Comment by Simon-TechForm** [comment]
Hi @AhmedSarhan. I'm going to close this for now, but feel free to open a new issue following the feature request template if this is still relevant :)
