### ISSUE TITLE
Polyline is not working for array of two coordiantes.

### ISSUE THREAD

**Issue by rravithejareddy** [react-native-maps/react-native-maps#4094]
I am not able to draw line between two location, I am using Polyline for it, but it's not working with two objects, I need to provide at least three location object for it. So how can I draw line between two location?

**Comment by gustavohcastro** [comment]
provide at least three location works for me!!

**Comment by rravithejareddy** [comment]
I have used Polygon for two locations, but polyline is not working for two locations.

**Comment by gustavohcastro** [comment]
you can duplicate last point of location array, to give three points to a Polygon Component.

**Comment by Simon-TechForm** [comment]
I'm going to close this. Please feel free to create a new issue following the issue template if you think that there's a bug in react-native-maps.
