### ISSUE TITLE
Map without Google or Apple's maps.

### ISSUE THREAD

**Issue by hchen98** [react-native-maps/react-native-maps#4098]
I have a project where it requires me to form a map, the Native American Tribe's map. Is there a way I can use this lib to form my map that's not from Google or Apple? 

I found one API that I could use (URL: https://native-land.ca/our-wonderful-wily-api/). The simplest way could be having a webview component that displays that `<iframe>` map from the site's API. However, that's not ideal as I will have pinpoints feature like what `react-native-maps` lib has.

Anyone has ever done it before?

**Comment by hchen98** [comment]
@ziggear  that's not what I'm asking for.

**Comment by Simon-TechForm** [comment]
Hi @hchen98. This library currently only supports Apple Maps and Google Maps. If you would like, please open an issue with a feature request for this :)
