### ISSUE TITLE
Android crash due to missing existence check in AirMapView.java

### ISSUE THREAD

**Issue by mcapocaccia** [react-native-maps/react-native-maps#4099]
react-native-maps v.0.30.1

Crash:
NullPointerException
Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference

Reason:
AirMapView.java:1014 (function dispatchTouchEvent is:

tapLocation = map.getProjection().fromScreenLocation(new Point(X,Y));

Should be:

if (map != null) {
tapLocation = map.getProjection().fromScreenLocation(new Point(X,Y));
}

**Comment by Simon-TechForm** [comment]
Hi @mcapocaccia.

Could you fill out the issue template and describe when this issue happens? I see that there's no existence for `map` but when does this exception occur?

**Comment by WheelerLee** [comment]
@Simon-TechForm 
When the map show "Google Play services are updating"

**Comment by Simon-TechForm** [comment]
So this is happening on devices that doesn't already have play services installed? This should definitely be a part of the issue, to allow anyone to help you out/fix the issue. Closing for now, but please feel free to open a new issue following the issue template :)

**Comment by AskaHD** [comment]
Updating this issue, just got the crash on a Redmi Note 8 Pro, wich has Google Play Services.

![image](https://user-images.githubusercontent.com/11071186/160996607-aa221286-8916-4cce-9ccd-50104f3d7db8.png)

I can't really confirm when this is happening. A user has open the app, went on a page with the map and got the crash. When going again on the map it was all fine, so the crash doesn't always happen.

**Comment by rajanbalana** [comment]
Were you able to solve it?

**Comment by nes123** [comment]
Happened after upgrading com.google.android.gms package. More specifically:

'com.google.android.gms:play-services-measurement-base:20.0.0'

was upgraded to

 'com.google.android.gms:play-services-measurement-base:20.1.0'

**Comment by andvalsol** [comment]
> react-native-maps v.0.30.1
> 
> Crash: NullPointerException Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference
> 
> Reason: AirMapView.java:1014 (function dispatchTouchEvent is:
> 
> tapLocation = map.getProjection().fromScreenLocation(new Point(X,Y));
> 
> Should be:
> 
> if (map != null) { tapLocation = map.getProjection().fromScreenLocation(new Point(X,Y)); }

I would also add a an if statement if the `tapLocation` variable is not null, since it's being used as a parameter for the `makeClickEventData` function.

**Comment by RomanSytnyk** [comment]
Any status update yet on this issue?

**Comment by mcapocaccia** [comment]
Apparently the fix has been applied to the 0.31.x releases. It is not in 0.30.2, which is the most recent update but a fix on the older release. @andvalsol @RomanSytnyk

**Comment by andvalsol** [comment]
thanks for the update @mcapocaccia

**Comment by tkyr-hh** [comment]
@mcapocaccia Thanks for your suggestion, but from 0.31.x the minimum target IOS platform should be 13, which will not work on iPhone devices such as 6s, 6s Plus and 1st generation SE.
Is there a fix for this issue so we can patch the library with it ??

**Comment by mcapocaccia** [comment]
> from 0.31.x the minimum target IOS platform should be 13, which will not work on iPhone devices such as 6s, 6s Plus and 1st generation SE.
> Is there a fix for this issue so we can patch the library with it ??

@tkyr-hh I believe the iOS 13 restriction is only if you need Google Maps for iOS enabled, is that your use case?
Anyway, you could replace the line of code like I suggested, by creating a patch file and adding "yarn patch-package" to your postinstall script

**Comment by Simon-TechForm** [comment]
@tkyr-hh just a friendly heads-up that the iOS 13 requirements was added in 1.0.0, not 0.31.x :)

**Comment by tkyr-hh** [comment]
@Simon-TechForm Thanks you
