### ISSUE TITLE
Markers not being removed from MapView  [ios]

### ISSUE THREAD

**Issue by MatthewLamperski** [react-native-maps/react-native-maps#4102]
# Bug report

## Summary

In my MapView, I have an array of Markers maintained by a state variable `markerObjs`. In my actual application, I have implemented a simple custom Marker (just a green circle). My problem comes when I try to filter the `markerObjs` array. When a specific `markerObj` is filtered out (removed from the state array), the Marker is still left on the MapView. While I am unable to replicate this bug using Snack (the react-native-maps package does not seem to play nice with Expo's Snack), I have been able to reproduce the issue in a very simplified way: When I tap on the MapView, a `markerObj` is added to the state array, and when I press another button, the array is cleared (therefore removing all markers from the array). Except, when the array is cleared, the Marker is still on the MapView. I am testing this on an iOS device. I have been working at this problem for days now. I have seen that Markers are managed by MapView's children, but even when the MapView's children is an empty array (double checked with using a ref), the Marker remains on the screen. This is my first time reporting a bug, and I tried to exhaust all other options, but I genuinely cannot figure out what is going wrong. Please excuse me if this is a simple fix, I am reaching out for any help at all. Thank you.

## Video

Here is a video example of my problem. When the marker array is cleared, as evidenced in the bottom panel, the marker remains on the screen, even if another marker is added after the first is removed. If there is any more information needed, I would be happy to provide it, just let me know. Thank you!

https://user-images.githubusercontent.com/43217788/155035970-44e43b9b-2dae-4a2e-9844-b7398c213b15.mp4

## Environment info

      react-native: 0.67.2
      react: 17.0.2
      react-native-maps: 0.30.1

      Target Platform: iOS - 15.2.1 iPhone 12 Pro (using Apple Maps)

`react-native info` output:

```bash
 System:
    OS: macOS 11.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 90.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Follow instruction steps for this package
2. Add a marker by tapping anywhere in the MapView
3. Tap 'clear markers' to set the marker array to empty

Describe what you expected to happen:

1. Once the marker state array was emptied, the markers would disappear from the screen

Describe what you actually happens:

1. Once the marker state array was emptied, the markers remain visible on the screen
2. If you are using a custom marker (like I am in my actual application), then the filtered out markers will change into the default markers,  but still show on the screen

## Reproducible sample code

```bash

const Discover = (props) => {
const [markerObjs, setMarkerObjs] = useState([])
const [distance, setDistance] = useState(60)
const [user, setUser] = useState({location: {lat: xxx, lng: xxx}})
const mapRef = useRef(null)

return (
    <View>
      <MapView
        ref={mapRef}
        minZoomLevel={4}
        minDelta={0.1}
        style={{ height: '100%', width: '100%' }}
        initialRegion={{
          latitude: user.location.lat,
          longitude: user.location.lng,
          latitudeDelta: distance / 54.6,
          longitudeDelta: distance / 54.6,
        }}
        onPress={e => {
          setMarkerObjs([
            {
              lat: e.nativeEvent.coordinate.latitude,
              lng: e.nativeEvent.coordinate.longitude,
            }
          ])
        }}
      >
        {
          markerObjs.map((marker, idx) => (
            <Marker
              key={idx}
              coordinate={{latitude: marker.lat, longitude: marker.lng}}
            />
          ))
        }
      </MapView>
     <Box
        p={5}
        position="absolute"
        top={insets.top}
        left={0}
        >
          <Pressable
              p={3}
              onPress={() => {
                setMarkerObjs([])
              }}>
              {({isPressed}) => (
                <Box
                  rounded={20}
                  opacity={isPressed ? 0.5 : 1}
                  p={3}
                  shadow={4}
                  bg="black"
                >
                  <Text color="white" fontWeight={300} fontSize={12}>CLEAR MARKERS</Text>
                </Box>
              )}
            </Pressable>
      </Box>
      <Box
        position="absolute"
        bottom={0}
        bg="white"
        w="100%"
        h="15%"
      >
        <Text>markerObjs: {JSON.stringify(markerObjs, null, 3)}</Text>
      </Box>
     </View>
  )
}

```

**Comment by Simon-TechForm** [comment]
First of all, thank you for taking the time to write a thorough issue description, following the issue template. 👍

I tried looking into this, but I'm struggling to reproduce the bug. Could you try to provide a minimal, reproducible example? I'm aware that your example is fairly minimal, but can you strip away all unnecesarry props, states and third party components, and try to reproduce this in a clean project?

What I did trying to reproduce:

- `npx react-native init MyApp --template react-native-template-typescript`
- `yarn add react-native-maps`
- `cd ios & pod install`
- `yarn ios`

And ran the following in App.tsx:
```ts
import React, {useEffect, useRef, useState} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import MapView, {LatLng, MapEvent, Marker, Region} from 'react-native-maps';

const initialRegion: Region = {
  latitude: 55.676098,
  longitude: 12.568337,
  latitudeDelta: 1.2,
  longitudeDelta: 1.2,
};

export default function App() {
  const mapViewRef = useRef<MapView>(null);
  const [markers, setMarkers] = useState<LatLng[]>([]);

  const setMarker = ({nativeEvent}: MapEvent) =>
    setMarkers([
      {
        latitude: nativeEvent.coordinate.latitude,
        longitude: nativeEvent.coordinate.longitude,
      },
    ]);

  const clearMarkers = () => {
    setMarkers([]);
  };

  useEffect(() => console.log(markers), [markers]);

  return (
    <View style={styles.containerView}>
      <MapView
        style={styles.mapView}
        ref={mapViewRef}
        initialRegion={initialRegion}
        onPress={setMarker}>
        {markers.map((marker, idx) => (
          <Marker
            key={idx}
            coordinate={{
              latitude: marker.latitude,
              longitude: marker.longitude,
            }}
          />
        ))}
      </MapView>
      <Pressable style={styles.clearMarkersPressable} onPress={clearMarkers}>
        <Text>Remove marker</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  containerView: {
    flex: 1,
  },
  mapView: {
    flex: 1,
  },
  clearMarkersPressable: {
    height: 50,
    backgroundColor: 'red',
  },
});

```

**Comment by MatthewLamperski** [comment]
> First of all, thank you for taking the time to write a thorough issue description, following the issue template. 👍
> 
> I tried looking into this, but I'm struggling to reproduce the bug. Could you try to provide a minimal, reproducible example? I'm aware that your example is fairly minimal, but can you strip away all unnecesarry props, states and third party components, and try to reproduce this in a clean project?
> 
> What I did trying to reproduce:
> 
> * `npx react-native init MyApp --template react-native-template-typescript`
> * `yarn add react-native-maps`
> * `cd ios & pod install`
> * `yarn ios`
> 
> And ran the following in App.tsx:
> 
> ```ts
> import React, {useEffect, useRef, useState} from 'react';
> import {Pressable, StyleSheet, Text, View} from 'react-native';
> import MapView, {LatLng, MapEvent, Marker, Region} from 'react-native-maps';
> 
> const initialRegion: Region = {
>   latitude: 55.676098,
>   longitude: 12.568337,
>   latitudeDelta: 1.2,
>   longitudeDelta: 1.2,
> };
> 
> export default function App() {
>   const mapViewRef = useRef<MapView>(null);
>   const [markers, setMarkers] = useState<LatLng[]>([]);
> 
>   const setMarker = ({nativeEvent}: MapEvent) =>
>     setMarkers([
>       {
>         latitude: nativeEvent.coordinate.latitude,
>         longitude: nativeEvent.coordinate.longitude,
>       },
>     ]);
> 
>   const clearMarkers = () => {
>     setMarkers([]);
>   };
> 
>   useEffect(() => console.log(markers), [markers]);
> 
>   return (
>     <View style={styles.containerView}>
>       <MapView
>         style={styles.mapView}
>         ref={mapViewRef}
>         initialRegion={initialRegion}
>         onPress={setMarker}>
>         {markers.map((marker, idx) => (
>           <Marker
>             key={idx}
>             coordinate={{
>               latitude: marker.latitude,
>               longitude: marker.longitude,
>             }}
>           />
>         ))}
>       </MapView>
>       <Pressable style={styles.clearMarkersPressable} onPress={clearMarkers}>
>         <Text>Remove marker</Text>
>       </Pressable>
>     </View>
>   );
> }
> 
> const styles = StyleSheet.create({
>   containerView: {
>     flex: 1,
>   },
>   mapView: {
>     flex: 1,
>   },
>   clearMarkersPressable: {
>     height: 50,
>     backgroundColor: 'red',
>   },
> });
> ```

Interesting... I created an entirely new project to test out the minimal version you gave me, and it worked just fine. So I tried replacing everything on the specific file I had in my project with the version you gave me, and it is not working again. I assume this means something went wrong in my project, so I will figure out where the problem is stemming from. If you have any ideas I'd love to hear them, but I'm sure it will be specific to my project. I will update when I figure out what went wrong. Thank you very much for the help!

**Comment by Simon-TechForm** [comment]
@MatthewLamperski nothing off the top of my head, unfortunately. And I don't see anything obvious in your example either. But please do give an update when you track it down :)

**Comment by MatthewLamperski** [comment]
So, after searching for the issue for a couple days, I decided to give up because the time spent was not worth the benefit. Luckily, the project I am working on is still in its relatively early stages, so I have decided to make a fresh project and copy my files over. 

In short, **the map is working fantastically now**. I'm still not sure where the original issue stemmed from, but if I figure out, I will follow up. Thank you @Simon-TechForm for your help! I'm going to close this issue as I am not experiencing it anymore.

**Comment by VictorPulzz** [comment]
I got same issue @Simon-TechForm , how we can clear markers manually?

**Comment by l-barbosa** [comment]
@MatthewLamperski I've been trying to find the source of a very similar issue [here](https://github.com/react-native-maps/react-native-maps/issues/4214) and also wasn't able to initially create a demo repo where the issue occurred.
After investigation, the issue seems to be connected with [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated).

Do you remember if you happened to use that library on your original project?

**Comment by MatthewLamperski** [comment]
> @MatthewLamperski I've been trying to find the source of a very similar issue [here](https://github.com/react-native-maps/react-native-maps/issues/4214) and also wasn't able to initially create a demo repo where the issue occurred. After investigation, the issue seems to be connected with [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated).
> 
> Do you remember if you happened to use that library on your original project?

Hey, so sorry for the very late response. This was a while ago, but yes I definitely used reanimated in that same project at the time. I didn't use it extensively, opting for React Native's Animated library (my animations were few and far between), but I definitely used that library in that project. I restarted and the bug was fixed in my case, but great find!

**Comment by Snoeprol** [comment]
Hi. I have `react-native-reanimated` version `2.14.4` and I applied the patch. 

I went to folder `/node_modules/` and added the necessary lines. This + rerunning the project using `npx expo start` should do the job right? Am I missing something? My markers are still not being removed. Did anyone find other workarounds?

Best, Mario
