### ISSUE TITLE
[Documentation] Google Maps API Usage 

### ISSUE THREAD

**Issue by iway1** [react-native-maps/react-native-maps#4104]
# Feature request
Add documentation that makes it clear when / how many Google maps API requests will be sent. (Is it one per render, is it one per MapView component mount, is it when the user scrolls the map? I have no idea). It would also be useful to have tips to reduce the number of these requests that will be sent. Again, these costs can blow up if you accidentally create an app that sends a bunch of requests and haven't configured a quota in the Google dev console..

## Why it is needed
There isn't any documentation of when a google Maps map load is triggered, and the API is not free. In my app I'm experience 5 map loads being sent on a single app load / component mount, and since there's no documentation as to what triggers it within `react-native-maps`. Without this documentation it isn't clear how we're supposed to reduce the number of API requests.

**Comment by Simon-TechForm** [comment]
Last time I checked (admittedly it's been quite a while), the Google Maps SDK for both iOS and Android was free for the functionally provided by `react-native-maps`. Looking at [iOS billing](https://developers.google.com/maps/documentation/ios-sdk/usage-and-billing) and [Android billing](https://developers.google.com/maps/documentation/android-sdk/usage-and-billing) this seems to be the case to this day.

Did you get billed for the usage of the lib, or find any information indicating that this would occur?

**Comment by Simon-TechForm** [comment]
Closing for now. Please comment and re-open if you find any further information regarding my comment above.
