### ISSUE TITLE
detail of places

### ISSUE THREAD

**Issue by jackimatin** [react-native-maps/react-native-maps#4105]
hi
thanks for develop this library...

I have a question:

can I get detail of a place like google map?(for example picture, stars and ...)

**Comment by linzof** [comment]
Seen you post this in a few different repositories.

Google Developer Console

You need to create an account and create an api key.

[placeID](https://developers.google.com/maps/documentation/places/web-service/place-id)

For something open source, try [leaflet](https://leafletjs.com/SlavaUkraini/examples.html) or [openstreetmaps](https://www.openstreetmap.org/#map=4/38.01/-95.84)

**Comment by Simon-TechForm** [comment]
Hello @jackimatin. We would like to keep the issue section related to the development of the library. I suggest taking this question to stackoverflow :)

If you believe that this is a bug or a feature request, please fill out the appropiate template and re-open.
