### ISSUE TITLE
[question] how to dynamically fit a polygon on the visible map

### ISSUE THREAD

**Issue by tsvetann** [react-native-maps/react-native-maps#4106]
I would like to display a polygon on the map. It works but with bigger polygons they are not always displayed within the map hence my questions is how to calculate my delta so that I can ensure polygons are always fit within the viewable map?

Thanks

**Comment by Simon-TechForm** [comment]
Hello @tsvetann. We would like to keep the issue section related to the development of the library. I suggest taking this question to stackoverflow :)

If you believe that this is a bug or a feature request, please fill out the appropiate template and re-open.

**Comment by tsvetann** [comment]
@Simon-TechForm thx for your feedback. Do you think discussions should be enabled on this repo for this purpose? Thanks again

**Comment by Simon-TechForm** [comment]
@tsvetann I'm not opposed to the idea. @christopherdro thoughts?
