### ISSUE TITLE
iOS Standard Flyover MapType

### ISSUE THREAD

**Issue by kevin-carlson** [react-native-maps/react-native-maps#4107]
# Feature request

I was looking through the different map types available for MapKit with iOS. I noticed that the standard map has 3d buildings, but the buildings are all extruded from a flat plane. With hybridFlyover map type, it appears that elevation is accounted for and visible in the 3d view. On Apple Maps, elevation is used to extrude the buildings in the standard map, which would be useful to include in react-native-maps. I imagine the mapType could be called 'standardFlyover'.

## Why it is needed

Elevation is very important when viewing maps in 3d. The elevation helps users orient themselves within the map to the terrain. While this is somewhat available through the hybridFlyover map type, creating a standardFlyover map type would allow a user to view the elevation changes in a standard map. This would be useful over the hybridFlyover type because the standard map is much easier to read since it isn't satellite imagery. It also reduces the processing strain relative to the hybrid map type.

## Possible implementation

I imagine this could be added easily if the way react-native-maps interfaces with MapKit offers a map type that I am requesting. I am not familiar with the inner workings of react-native-maps, so I do not have a specific implementation recommendation.

**Comment by EasonHeee** [comment]
+1 on this request. Could some one help take a look?
