### ISSUE TITLE
Android shows white color instead of map.

### ISSUE THREAD

**Issue by MUZAFFAR-PURELOGICS** [react-native-maps/react-native-maps#4109]
This is showing a white color page on android. API key is purchased and services is enable from google console. All integration is successfully done. I also use position absolute etc.
I have created an empty project its behaviour is same on newly project also.
Kindly make a look into this bug thanks.

**Comment by Simon-TechForm** [comment]
Please fill out the issue template and re-open if you keep experiencing this :)

**Comment by bumjin1013** [comment]
+1

**Comment by darimuhittinhey** [comment]
+1
