### ISSUE TITLE
[iOS] - add details.isGesture prop to onRegionChangeComplete callback

### ISSUE THREAD

**Issue by 9r4ik** [react-native-maps/react-native-maps#4112]
# Feature request

## Why it is needed

**onRegionChangeComplete** note from [mapview doc](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md)
```
 isGesture property indicates if the move was from the user (true) or an animation (false). Note: isGesture is supported by Google Maps only. 
 ```
Now iOS MapView with MapKit provider  trigger **onRegionChangeComplete** multiple times while user pan/zoom/pinch map.

iOS MapView with google provide trigger **onRegionChangeComplete** ones when user remove fingers from screen

Without this feature developers could not detect end of user interaction

---
#3805 #3818 
## Possible implementation

With this feature developers could detect end of user interaction

### Code sample

```js
onRegionChangeComplete={(new_region, details) => {
          if (details?.isGesture) {
            console.log('fetch new data with new region');
          }
        }}
```

**Comment by aliwaqar981** [comment]
It would be great if this can be implemented for iOS MapView. Eagerly looking for this

**Comment by RyanTG** [comment]
I don't think this should be marked stale just yet. There's an open PR with a (potential) solution.

**Comment by eduardorfreitas93** [comment]
PR https://github.com/react-native-maps/react-native-maps/pull/4272 with a solution
