### ISSUE TITLE
animateToRegion & fitToCoordinate methods are not present in the MapView reference.

### ISSUE THREAD

**Issue by 100sarthak100** [react-native-maps/react-native-maps#4118]
# Bug report

MapView Reference object
  context: Object
  forceUpdate: ƒ ()
  isReactComponent: Object
  map: Object
  props: Object
  refs: Object
  setState: ƒ ()
  state: Object
  updater: Object
  __lastRegion: Object
  __layoutCalled: true
  __reactInternalMemoizedMergedChildContext: Object
  __reactInternalSnapshotBeforeUpdate: Object
  _onChange: ƒ ()
  _onLayout: ƒ ()
  _onMapReady: ƒ ()
  _onMarkerPress: ƒ ()
  _reactInternalInstance: Object
  _reactInternals: Object
  __proto__: Object

## Environment info
      react-native: 0.66.4
      react: 17.0.2
      react-native-maps: 0.30.1

## Steps to reproduce
const mapRef = useRef(null)
<MapView
     provider={PROVIDER_GOOGLE} /
     region={{region}}
     ref={mapRef}
/>

Describe what you expected to happen:
Not able to get animateToRegion & fitToCoordinate method from the mapRef

**Comment by Simon-TechForm** [comment]
I'm having no issues calling e.g. animateToRegion using the ref. See:
```ts
import React, {useRef} from 'react';
import {StyleSheet} from 'react-native';
import MapView from 'react-native-maps';

export default function App() {
  const mapViewRef = useRef<MapView>(null);

  return (
    <MapView
      ref={mapViewRef}
      style={styles.mapView}
      onRegionChangeComplete={() =>
        mapViewRef.current?.animateToRegion({
          latitude: 52.342,
          longitude: 32.4234,
          latitudeDelta: 1,
          longitudeDelta: 1,
        })
      }
    />
  );
}

const styles = StyleSheet.create({
  mapView: {
    flex: 1,
  },
});

```
Closing for now as you didn't fill out the issue template. If you continue experiencing problems regarding this, feel free to edit your issue including the sections mentioned in the issue template and re-open.

**Comment by akash-unibuddy** [comment]
> I'm having no issues calling e.g. animateToRegion using the ref. See:
> 
> ```ts
> import React, {useRef} from 'react';
> import {StyleSheet} from 'react-native';
> import MapView from 'react-native-maps';
> 
> export default function App() {
>   const mapViewRef = useRef<MapView>(null);
> 
>   return (
>     <MapView
>       ref={mapViewRef}
>       style={styles.mapView}
>       onRegionChangeComplete={() =>
>         mapViewRef.current?.animateToRegion({
>           latitude: 52.342,
>           longitude: 32.4234,
>           latitudeDelta: 1,
>           longitudeDelta: 1,
>         })
>       }
>     />
>   );
> }
> 
> const styles = StyleSheet.create({
>   mapView: {
>     flex: 1,
>   },
> });
> ```
> 
> Closing for now as you didn't fill out the issue template. If you continue experiencing problems regarding this, feel free to edit your issue including the sections mentioned in the issue template and re-open.

Thank you so much for the clear explanation via a snippet.

**Comment by kris1803** [comment]
Having same issue, some times it animates, some times it does nothing, event not throwing or logging errror

**Comment by ashadnasim52** [comment]
> Having same issue, some times it animates, some times it does nothing, even not throwing or logging errror

I am still facing this issue, for the first time user when they grant permission
