### ISSUE TITLE
React Native on Apple Silicon M1 - The linked library 'libPods-ProjectName.a' is missing one or more architectures.

### ISSUE THREAD

**Issue by muhammadqazi** [react-native-maps/react-native-maps#4120]
# Bug report

I'm trying to use react-native-maps in my project, but after several attempts, I am still getting the same issue. I followed all the steps mentioned at https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md .

Is anyone with a similar issue? how to fix it?

**Comment by Simon-TechForm** [comment]
Please check out #4097 and/or #3527.
