### ISSUE TITLE
Warning: Failed prop type: The prop `coordinate` is marked as required in `MapMarker`, but its value is `null`.

### ISSUE THREAD

**Issue by muhammadqazi** [react-native-maps/react-native-maps#4135]
react-native-maps, it's working fine but when I remove PROVIDER_GOOGLE it gave me this error, The error is located somewhere is Callout without Callout component it works fine with apple maps but when I add this it gave me this Warning: Failed prop type: The prop `coordinate` is marked as required in `MapMarker`, but its value is `null`.

 <Callout onPress={() => showModalChargeInfo()} tooltip>
<View style={{
              height: 70,
              width: 250,
              flexDirection: 'row',
              marginBottom:10,
              ...styles.shadow,
            }}>
<Text>Banner</Text>
</View>
</Callout>

Does anyone have a solution?

**Comment by Simon-TechForm** [comment]
Hi @muhammadqazi. I'm gonna have to ask you to take the time it takes to fill out the issue template. There's not nearly enough information in the issue to provided, to sort out if this is a bug. Please feel free to open a new issue following the issue template, and make sure to take a look at how to provide [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) :)

**Comment by muhammadqazi** [comment]
Aight, I'm gonna follow it in the next issue.
