### ISSUE TITLE
Warning: Failed prop type: The prop `coordinate` is marked as required in `MapMarker`, but its value is `null`.

### ISSUE THREAD

**Issue by muhammadqazi** [react-native-maps/react-native-maps#4136]
# Bug report

👋 Hi!

## Environment info

      react-native: 0.67.3
      react: 17.0.2
      react-native-maps: 0.30.1

   
`react-native info` output:

System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 133.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
      react-native: 0.67.3
      react: 17.0.2
      react-native-maps: 0.30.1

```

I am using [react-native-maps](https://github.com/react-native-maps/react-native-maps) it works fine, I add the marker still working with provider google and without google, BUT when I add the Callout component in Marker I gave me an error 
Warning: Failed prop type: The prop `coordinate` is marked as required in `MapMarker`, but its value is `null`.

The expected outcome was to see apple maps on-screen instead of google maps, but It doesn't work.

Describe what you actually happens:

I faced an error and the maps don't render.
Warning: Failed prop type: The prop `coordinate` is marked as required in `MapMarker`, but its value is `null`.

## Reproducible sample code

```javascript

 <MapView
        style={{ flex: 1 }}
        provider={PROVIDER_GOOGLE}
        initialRegion={region}

      >
             <Marker
                    coordinate={fromLocation}>

                         <Callout onPress={() => showModalChargeInfo()} tooltip>

                               <View style={{
                                        height: 70,
                                        width: 250,
                                         flexDirection: 'row',
                                         marginBottom: 10,
                                           ...styles.shadow,
                                   }}>
                                           <Text>Banner</Text>
                                 </View>
                         </Callout>
            </Marker>
</MapView>

```

**Comment by Simon-TechForm** [comment]
I can't run the reproducible sample code you provided, as you didn't provide `region, fromLocation, showModalChargeInfo and styles.shadow`.

Looking at the error message and the code you provided, I guess that you are trying to access the location of the user on iOS, which is somehow failing. This might be caused by a lack of permissions or something else. I suggest taking this question to stackoverflow as we would like to keep the issue section related to code issues :)

**Comment by SohelIslamImran** [comment]
Same Issue on Android @Simon-TechForm

![image](https://user-images.githubusercontent.com/76745339/161315809-ff8b757a-9d45-4783-9557-a5a520e865d3.png)

**Comment by muhammadqazi** [comment]
@Simon-TechForm you need to open this issue again.

**Comment by 06pranto** [comment]
@SohelIslamImran can you solve it?

**Comment by 06pranto** [comment]
i am facing the same error

**Comment by SohelIslamImran** [comment]
@06pranto 
Actually, in my case, I'm using expo SDK 44. And it only supports `react-native-maps version 0.29.4`, But I mistakenly installed version  0.30.1. So when I again downgrade to version 0.29.4 the problem is solved.

**Comment by SohelIslamImran** [comment]
Reopened #4235

**Comment by muhammadqazi** [comment]
Any update on the issue?

**Comment by KinzaShaikh** [comment]
I am facing same issue

**Comment by AravindNandhu** [comment]
I am also facing same issue

**Comment by chanphiromsok** [comment]
I am also facing same issue(3)

**Comment by chanphiromsok** [comment]
temporary solution for me set useNativeDriver: false

**Comment by germanmb23** [comment]
> useNativeDriver

Were did you set this?

**Comment by chanphiromsok** [comment]
> > useNativeDriver
> 
> Were did you set this?

Hi if you are using reaniamted v2 here you go https://github.com/react-native-maps/react-native-maps/issues/4371#issuecomment-1344148890
