### ISSUE TITLE
mapref.current.animateToRegion function doesn't zoom directly to the desired point in IOS

### ISSUE THREAD

**Issue by burakkbilginn** [react-native-maps/react-native-maps#4143]
When I use react-native-maps on Android, mapref.current.animateToRegion works perfectly, zooming to the desired region directly. But with the same code and with required additions, when I use it in IOS, map starts zooming to  a not-intended region, to a far away point at the north of the desired region, and at last stops at the desired point. I mean it doesn't zoom directly to the desired region, but it travels to the north first while zooming, and then to the south and at last the desired region. Is this a bug?

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
    Memory: 4.91 GB / 12.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3 
    react: 17.0.2 => 17.0.2 
    react-native: ^0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

Since it is a working code on Android, I think no need to reproduce it

  How did you expect your project to behave?
  Expected behaviour is zooming directly to the desired point.

Describe what you actually happens:

  The zoom is travelling at first, at last it ends up at the desired point.

## Reproducible sample code

  mapRef.current.animateToRegion({
                latitude: 30,
                longitude: 30,
                latitudeDelta: 0.005,
                longitudeDelta: 0.005,
            }, 2000)

**Comment by Simon-TechForm** [comment]
Is this Google Maps or Apple Maps on iOS?

**Comment by burakkbilginn** [comment]
> Is this Google Maps or Apple Maps on iOS?

Google maps of course

**Comment by Simon-TechForm** [comment]
This is unfornately not something that `react-native-maps` has control over. The library calls `animateToCameraPosition` from the Google Maps iOS SDK natively, which creates the animation. See the [Google Maps iOS SDK documentation](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view#a56e54408e70f1b3e469a2b58ed1b5e93).
