### ISSUE TITLE
Android 12 app crash with 0.31.0-beta.3 version - cannot find symbol variable Renderer

### ISSUE THREAD

**Issue by vkozinec** [react-native-maps/react-native-maps#4149]
Currently trying to run maps on android 12 and getting this error. Using standard Idk 11 from android studio. Does anyone have luck with building the app on android 12?

```
error: cannot find symbol
        MapsInitializer.initialize(context, MapsInitializer.Renderer.LATEST, (MapsInitializer.Renderer renderer) -> {
                                                           ^
  symbol:   variable Renderer
  location: class MapsInitializer
```

![Screenshot 2022-03-28 at 16 51 31](https://user-images.githubusercontent.com/570613/160425434-d2b23e24-384d-4888-a5b1-6767c3bc62d0.png)

## system info

```
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## build.gradle
```
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "2.3.0"
```

## react native

```
"react-native": "0.67.2",
"react-native-maps": "0.31.0-beta.3",
```

**Comment by Simon-TechForm** [comment]
Hi @vkozinec.

I'm quite sure that this is caused by specifying a `playServicesVersion < 18.0.0` in your build.gradle. If you don't need to pin the version, I would suggest just removing it from your build.gradle and let the library use the default versions.

This should definitely be in the docs, so I will leave the issue open until we sort them out.

**Comment by vkozinec** [comment]
Hi @Simon-TechForm 

I will try to remove it now. We are also using OneSignal and I have read that there can be some issues also while using both libraries, so I will test things not and let you know.

Thank you for fast response!

**Comment by vkozinec** [comment]
Just an update, I have tested this on both Android 12 and 10 versions and I can confirm that removing explicit version of `playServicesVersion` from `build.gradle` works.

Also, using it side by side with OneSignal works, tested it on both android versions.

I am really thankful for your help. You can close this issue and update the docs.

**Comment by Simon-TechForm** [comment]
@salah-ghanim are you preparing a PR to update the docs? If not I would prefer that we keep this open or open another issue describing the lacking documentation :)

**Comment by salah-ghanim** [comment]
@Simon-TechForm done
https://github.com/react-native-maps/react-native-maps/pull/4155

fyi ... it seems like GoogleMaps dependencies could be significantly simplified / cleaned up based on the latest version of the google maps SDK

I will try to update the following
 1. GoogleMaps SDK
 2. the sample app
 3. all related documentations

**Comment by Neutrinookoye** [comment]
@Simon-TechForm Thank you so much, removing it from my build.gradle worked for me.
