### ISSUE TITLE
React Native Maps still uses the Google API Maps even I use  my own urlTemplate from my server

### ISSUE THREAD

**Issue by mickael-bdias** [react-native-maps/react-native-maps#4159]
# Bug report

## Summary

React Native Maps still uses the Google API Maps even I use  my own urlTemplate from my server.

## Environment info

`react-native info` output:

```bash
# react": "17.0.2", "react-native": "0.67.3", "react-native-maps": "^0.30.1"
```

## Steps to reproduce

1. Build my own tile server using the tips from [Switch2OSM](https://switch2osm.org/serving-tiles/using-a-docker-container/)
2. Test from my Internet browser
3. Follow the guide to use my urlTemplate
4. Check the number of Google API requests from my Google Cloud Platform

Describe what you expected to happen:

1. After using the urlTemplate, the API requests should be stopped.

Describe what you actually happens:

1. Even using the own tiles, the requests increase +1 at each time

## Reproducible sample code
```

render() {
  const {t} = this.props;
  return (
    <View style={styles.container}>
      <MapView
        // provider={PROVIDER_GOOGLE}
        provider={PROVIDER_DEFAULT}
        style={styles.map}
        region={this.state.region}
        mapType={MAP_TYPES.NONE}
          shouldReplaceMapContent={true}
          onRegionChangeComplete={region => {
            this.setState({region});
          }}>
          <UrlTile urlTemplate={urlTemplate} maximumZ={19} flipY={false} />
          <MapView.Marker
            coordinate={{
              latitude: 39.81594,
              longitude: -7.51088,
            }}
            title={'Localização'}
            description={'Descrição'}
          />
        </MapView>
        <View />
```

**Comment by JoniVR** [comment]
Hi, fyi, for me using:

```tsx
mapType={Platform.select({android: MAP_TYPES.STANDARD})}
```

resolves the issue.

**Comment by mickael-bdias** [comment]
Hi @JoniVR !
Thanks but it did not solve the counter of the Google Cloud Platform API.
I did 4 requests and I saw them on the GCP.

**Comment by JoniVR** [comment]
Oh okay, wasn't aware of this, sorry!

**Comment by mickael-bdias** [comment]
@JoniVR that's OK.
Thanks for helping.
I will use a Web-view or something. 
Google maps is very expensive.

**Comment by ThomasGoatITMedia** [comment]
Hi! this is still an actual problem is there any way to mitigate this?
