### ISSUE TITLE
Out of memory [Android] Custom Marker - new Google maps renderer

### ISSUE THREAD

**Issue by AxelHgt** [react-native-maps/react-native-maps#4161]
# Bug report

## Summary

Out of memory crash, using the new Google renderer on a old Android device.
The app works fine with the LEGACY renderer.

## Environment info

Device: 
Samsung Galaxy S5 SM-G900F
Android 6.0.1

`react-native info` output:

```bash
    "react": "17.0.2",
    "react-native": "^0.66.4",
    "react-native-maps": "^0.31.0-beta.3",
```

## Steps to reproduce

1. Enable the new rendered -> add "enableLatestRenderer();" on index.js file

2. Display the map with a custom marker and specially the parameter "tracksViewChanges={true}"

3. Wait for the crash

Describe what you expected to happen:

1. No Out of Memory error

Describe what you actually happens:

1. Looking at the profiler:
  *   **Using the legacy renderer**, the memory goes up (< 10mb) then the garbage collector does its job and release the memory
  No problem
  *  **Using the latest renderer**, the memory goes up and never goes down, leading to a Out of memory crash
  
  Log from ADB:
  
> E/System: Uncaught exception thrown by finalizer  

> E/art: invalid stream - problem with parameter iterator in /data/data/com.google.android.gms/app_chimera/m/00000197/dl-MapsCoreDynamite.integ_214639020308.apk for method void dsx.<init>(long, dsw[], byte[], android.util.SparseIntArray, boolean)  

> E/art: invalid stream - problem with parameter iterator in /data/data/com.google.android.gms/app_chimera/m/00000197/dl-MapsCoreDynamite.integ_214639020308.apk for method dsx dte.g(glu, java.util.concurrent.atomic.AtomicLong)   

> E/System: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available  

> E/File: fail readDirectory() errno=2 

## Reproducible sample code

I use the parameter "tracksViewChanges" because my custom view is an Animated.View. 
However the result is the same with a simple view. The other parameters seem to have no impact

`
<Marker tracksViewChanges={true} coordinate={{ latitude : latitude , longitude : longitude }}>  
  <CustomMarkerView {...marker} />  
</Marker>
`

**Comment by anton-shokut** [comment]
I am experiencing the similar "out of memory" issue with the new renderer.

**Comment by ashuvssut** [comment]
Looks like the Legacy Rendrer is the only option for now. this issue #3969 also disappeared when using Legacy Rendrer.

I hope the Lastest Rendrer becomes stable soon

**Comment by MarkCSmith** [comment]
I experienced this same problem or a very similar one with a map that has 250 Markers.  Each Marker has a custom view that contains an image with some overlaid text, e.g.,
```
const pinIconSource = ...
const customPinView =
  <View style={styles.numberedPinContainer}>
    <Image source={pinIconSource}/>
    <Text style={styles.numberedPinLabel}>12</Text>
  </View>
```
Styles (probably not important):
```
const styles = StyleSheet.create({
  ...
  numberedPinContainer: {
    alignItems: "center",
  },
  numberedPinLabel: {
    top: 1,
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
    position: "absolute",
  },
   ...
});

```
And later using the customPinView to define a Marker:
```
<Marker key={...} coordinate={...}
  ...
  {customPinView}
</Marker>
```
Adding `tracksViewChanges={false}` fixed the problem or at least made it take much, much longer to occur.  When tracksViewChanges is on, the code in ViewChangesTracker.java repaints each custom Marker's child views into a Bitmap object every 40 milliseconds.  This seems to overwhelm Android's memory allocator / garbage collector.

The disadvantage of turning off tracksViewChanges is that I had to add code to track changes to the views and force a specific Marker to be updated.  I ended up using a unique key each time a Marker's contents changed because I could not get Marker.redraw() to work (that might be a timing issue with my code).

**Comment by chakafasano88** [comment]
This is still an issue! I am currently running Adroid 13. I am rendering only ONE custom MapMarker and my application seems to freeze after 15 seconds and then a native Android prompt appears saying "App is not responding". If I remove the custom marker and use the default google maps pin, the application runs perfectlly. Here is my code: 

```    
<MapView
      initialRegion={{
        latitude: center.latitude,
        longitude: center.longitude,
        latitudeDelta: 0.002,
        longitudeDelta: 0.002,
      }}
      onPress={handleOnPress}
      scrollEnabled={false}
      style={[styles.map, style]}
      zoomEnabled={false}>
      {locations.map(({ coords: { latitude, longitude }, markerUrl }, index) => (
        <Marker key={`marker-${index}`} coordinate={{ latitude, longitude }}>
          <MaterialCommunityIcons
            name={iconDisplay(markerUrl).name}
            size={34}
            color={iconDisplay(markerUrl).color}
          />
        </Marker>
      ))}
    </MapView>
```

I did try adding `tracksViewChanges={false}` which sort of works... The app no longer crashes the performance is awful. the application is extremely slow and unusable. 

Thanks for all the hard work!!

**Comment by alainib** [comment]
any fix ? i have very slow maps few seconds and app crash totally

**Comment by ashuvssut** [comment]
> Looks like the Legacy Rendrer is the only option for now. this issue #3969 also disappeared when using Legacy Rendrer.
> 
> I hope the Latest Rendrer becomes stable soon

I just commented out `enableLatestRenderer();`. And it didnt crash like that
