### ISSUE TITLE
Marker onPress updating state in android but not in ios

### ISSUE THREAD

**Issue by ravis-farooq** [react-native-maps/react-native-maps#4165]
Hey there , I am using React native map, In that I use Marker onPress which sets my  **const [ind,setInd]=React.useState()** , The onPress just works fine in android but in ios it is not updating my **const [ind,setInd]=React.useState()**
<Marker
    coordinate={{...coordinate}}
    flat={true}
    onPress={i => {
      setInd(i);

      mapView?.current?.animateToRegion(
        {
          ...coordinate,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA,
        },
        1000,
      );
    }}>
although map is animating to region

**Comment by Simon-TechForm** [comment]
hi @ravis-farooq. We need to keep the issue section related to bugs and feature requests. I suggest taking this question to stackoverflow or the likes :)
