### ISSUE TITLE
overflow: visible in Marker style is not working

### ISSUE THREAD

**Issue by brianbscho** [react-native-maps/react-native-maps#4169]
## Summary

I'm trying to show `<Image />` above the `coordinate` and `<Text />` below the `coordinate` in map, using Marker, like below:

```
    <Marker
      coordinate={{longitude: poi.longitude, latitude: poi.latitude}}
      style={{overflow: 'visible'}}>
      <View style={{overflow: 'visible'}}>
        <Image
          source={icon.source}
          style={{
            width: 50,
            height: 70,
          }}
        />
        <View
          style={{
            width: 30,
            height: 20,
            position: 'absolute',
            left: 20,
            bottom: -20,
          }}>
          <Text
            numberOfLines={1}
            ellipsizeMode="tail">
            {poi.name}
          </Text>
        </View>
      </View>
    </Marker>
```

But <Text> component is not visible. I tried to use negative `marginBottom` and it didn't either. Is it expected behavior? Is there any way I could show component below the `coordinate` prop in map?

## Environment info

      react-native: 0.64.0
      react: 17.0.1
      react-native-maps: ^0.29.4

`react-native info` output:

```bash
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 55.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. Try to show component below `<Marker />` with `overflow: 'visible'` or trying to move `<Marker />` positioning down the `coordinate` like code snippet in summary.

Describe what you expected to happen:

1. Show component below the `coordinate`.

Describe what you actually happens:

1. Nothing is shown.

**Comment by go-sean-go** [comment]
Experiencing the same with the same exact use case as above. Also messes up things like shadows.

**Comment by alainib** [comment]
still getting this issu in end of 2023
do you fixed it ?

no way to display a text with absolute position and overflow visible with marker

https://github.com/react-native-maps/react-native-maps/issues/4863

**Comment by brianbscho** [comment]
> still getting this issu in end of 2023 do you fixed it ?
> 
> no way to display a text with absolute position and overflow visible with marker
> 
> #4863

No, I couldn’t find fix and had to change the design.

**Comment by alainib** [comment]
> > still getting this issu in end of 2023 do you fixed it ?
> > no way to display a text with absolute position and overflow visible with marker
> > #4863
> 
> No, I couldn’t find fix and had to change the design.

DAMN, big issue.

thanks   to avoid me loosing more time to try to fix it

**Comment by brianbscho** [comment]
I don't have screenshot because I don't work for the project anymore. But I remember that I simply placed the text on top of the location, not icon image.

In my original code snippet, I tried to put image on top of the location and text below it. Instead of the original design, I placed text on top of the location and image on top of the text. The icon is bit dislocated but I didn't have other solution.

**Comment by brianbscho** [comment]
> > > still getting this issu in end of 2023 do you fixed it ?
> > > no way to display a text with absolute position and overflow visible with marker
> > > #4863
> > 
> > 
> > No, I couldn’t find fix and had to change the design.
> 
> do you have screenshot of the new design you are actually using please ? (and maybe some code ) what i'am actually doing is this : but yellow marker should be at blue dot position
> 
> <img alt="Capture d’écran 2023-10-17 à 10 09 26" width="247" src="https://user-images.githubusercontent.com/7910081/275759068-c8b9b73a-7cf5-4140-8f14-eb02b75c6ed1.png">

I don't have screenshot because I don't work for the project anymore. But I remember that I simply placed the text on top of the location, not icon image.

In my original code snippet, I tried to put image on top of the location and text below it. Instead of the original design, I placed text on top of the location and image on top of the text. The icon is bit dislocated but I didn't have other solution.

**Comment by go-sean-go** [comment]
Hey y'all - check out my comments in this issue: https://github.com/react-native-maps/react-native-maps/issues/4384

If you're only worried about positioning the pin, and not touch areas, the `anchor` prop can provide a solution. :)
