### ISSUE TITLE
Is it possible to rotate custom marker?

### ISSUE THREAD

**Issue by Lian39** [react-native-maps/react-native-maps#4171]
I've added a custom arrow marker to user's position instead of default one. Now I'm interested if it's possible to rotate my marker depending on the user's direction of movement.

**Comment by alexdarh** [comment]
<Image style={{transform: [{ rotate: `${myCurrentPosition.heading}deg` }]}}

**Comment by Lian39** [comment]
But if I'm rendering my marker as a <Marker />
```
 <Marker
     coordinate={currentPosition}
    image={ARROW_MARKER}
 />
```

**Comment by Simon-TechForm** [comment]
hi @Lian39 . We need to keep the issue section related to bugs and feature requests. I suggest taking this question to stackoverflow or the likes :)
