### ISSUE TITLE
Map pins are too large on build #2016

### ISSUE THREAD

**Issue by abtfulmind** [react-native-maps/react-native-maps#4173]
# Bug report
Please see "Map pins are too large on build #2016"

this was closed for some arbitrary reason. THe issue persists: we're having it right now. Perhaps admin can re-open since there was no reason for closing it in the first place.

## Environment info

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

Describe what you actually happens:

1. …
2. …

**Comment by eprice122** [comment]
+1
