### ISSUE TITLE
I Am Facing Issue In Installing it in my Latest Project

### ISSUE THREAD

**Issue by BishesSaha** [react-native-maps/react-native-maps#4175]
# Bug report

# npm resolution error report

2022-04-11T09:47:02.079Z

While resolving: demoproject@0.0.1
Found: react@17.0.2
node_modules/react
  react@"17.0.2" from the root project
  peer react@">= 16.0 || < 18.0" from react-native-maps@0.30.1
  node_modules/react-native-maps
    react-native-maps@"*" from the root project
  peer react@"17.0.2" from react-native@0.68.0
  node_modules/react-native
    react-native@"0.68.0" from the root project
    peer react-native@">= 0.51" from react-native-maps@0.30.1
    node_modules/react-native-maps
      react-native-maps@"*" from the root project
  peer react@">=17.0.1" from react-native-web@0.17.7
  node_modules/react-native-web
    peer react-native-web@">= 0.11" from react-native-maps@0.30.1
    node_modules/react-native-maps
      react-native-maps@"*" from the root project

Could not resolve dependency:
peer react@"^18.0.0" from react-dom@18.0.0
node_modules/react-dom
  peer react-dom@">=17.0.1" from react-native-web@0.17.7
  node_modules/react-native-web
    peer react-native-web@">= 0.11" from react-native-maps@0.30.1
    node_modules/react-native-maps
      react-native-maps@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "17.0.2",
    "whileInstalling": {
      "name": "demoproject",
      "version": "0.0.1",
      "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
    },
    "location": "node_modules/react",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "17.0.2",
        "from": {
          "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
        }
      },
      {
        "type": "peer",
        "name": "react",
        "spec": ">= 16.0 || < 18.0",
        "from": {
          "name": "react-native-maps",
          "version": "0.30.1",
          "whileInstalling": {
            "name": "demoproject",
            "version": "0.0.1",
            "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
          },
          "location": "node_modules/react-native-maps",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "react-native-maps",
              "spec": "*",
              "from": {
                "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "react",
        "spec": "17.0.2",
        "from": {
          "name": "react-native",
          "version": "0.68.0",
          "whileInstalling": {
            "name": "demoproject",
            "version": "0.0.1",
            "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
          },
          "location": "node_modules/react-native",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "react-native",
              "spec": "0.68.0",
              "from": {
                "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
              }
            },
            {
              "type": "peer",
              "name": "react-native",
              "spec": ">= 0.51",
              "from": {
                "name": "react-native-maps",
                "version": "0.30.1",
                "whileInstalling": {
                  "name": "demoproject",
                  "version": "0.0.1",
                  "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                },
                "location": "node_modules/react-native-maps",
                "isWorkspace": false,
                "dependents": [
                  {
                    "type": "prod",
                    "name": "react-native-maps",
                    "spec": "*",
                    "from": {
                      "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "react",
        "spec": ">=17.0.1",
        "from": {
          "name": "react-native-web",
          "version": "0.17.7",
          "whileInstalling": {
            "name": "demoproject",
            "version": "0.0.1",
            "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
          },
          "location": "node_modules/react-native-web",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "peer",
              "name": "react-native-web",
              "spec": ">= 0.11",
              "from": {
                "name": "react-native-maps",
                "version": "0.30.1",
                "whileInstalling": {
                  "name": "demoproject",
                  "version": "0.0.1",
                  "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                },
                "location": "node_modules/react-native-maps",
                "isWorkspace": false,
                "dependents": [
                  {
                    "type": "prod",
                    "name": "react-native-maps",
                    "spec": "*",
                    "from": {
                      "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react",
    "spec": "17.0.2",
    "from": {
      "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": "^18.0.0",
    "error": "INVALID",
    "from": {
      "name": "react-dom",
      "version": "18.0.0",
      "whileInstalling": {
        "name": "demoproject",
        "version": "0.0.1",
        "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
      },
      "location": "node_modules/react-dom",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "react-dom",
          "spec": ">=17.0.1",
          "from": {
            "name": "react-native-web",
            "version": "0.17.7",
            "whileInstalling": {
              "name": "demoproject",
              "version": "0.0.1",
              "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
            },
            "location": "node_modules/react-native-web",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "peer",
                "name": "react-native-web",
                "spec": ">= 0.11",
                "from": {
                  "name": "react-native-maps",
                  "version": "0.30.1",
                  "whileInstalling": {
                    "name": "demoproject",
                    "version": "0.0.1",
                    "path": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                  },
                  "location": "node_modules/react-native-maps",
                  "isWorkspace": false,
                  "dependents": [
                    {
                      "type": "prod",
                      "name": "react-native-maps",
                      "spec": "*",
                      "from": {
                        "location": "C:\\Users\\BishesSaha\\Desktop\\DemoProject"
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}

**Comment by salah-ghanim** [comment]
duplicate https://github.com/react-native-maps/react-native-maps/issues/4167
