### ISSUE TITLE
App wont build using Google Map iOS

### ISSUE THREAD

**Issue by russmenum** [react-native-maps/react-native-maps#4183]
# Bug report

## Summary

After following the install instructions for iOS attempted to run the app in the XCODE simulator. If the install instruction code is present the app will not build.

## Environment info
      react-native: "~0.63.4"
      react: "16.13.1"
      react-native-maps: "0.30.1"
      Target Platform: eg: iOS - 15.2 Simulator/iPhone 11 (trying to use googleMaps)
      XCODE: Version 13.2.1 (13C100)

`react-native info` output:

```bash
# paste your react, react-native, react-native-maps versions here
"_swift_willThrow", referenced from:
      GoogleMapsUtils.HeatMapInterpolationPoints.generatePoints(influence: Swift.Double, granularity: Swift.Double) throws -> [__C.GMUWeightedLatLng] in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
  "Swift.Array.init() -> [A]", referenced from:
      variable initialization expression of GoogleMapsUtils.HeatMapInterpolationPoints.(data in _085340145A7263942932318178DB6148) : [__C.GMUWeightedLatLng] in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
      variable initialization expression of GoogleMapsUtils.HeatMapInterpolationPoints.(heatMapPoints in _085340145A7263942932318178DB6148) : [__C.GMUWeightedLatLng] in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
      GoogleMapsUtils.HeatMapInterpolationPoints.init(givenClusterIterations: Swift.Int) -> GoogleMapsUtils.HeatMapInterpolationPoints in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
      GoogleMapsUtils.HeatMapInterpolationPoints.(kcluster in _085340145A7263942932318178DB6148)() -> [[__C.CLLocationCoordinate2D]] in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **
```

## Steps to reproduce

1) set up pod file per instructions
```require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'app' do
  use_unimodules!
  config = use_native_modules!

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
end
```

2) add lines to ```AppDelegate.m``` resulting:
```
#import "RNNotifications.h"
#import "AppDelegate.h"

// ADD THIS
#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif
// TILL HERE

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import <TSBackgroundFetch/TSBackgroundFetch.h>

#import <GoogleMaps/GoogleMaps.h>// react-native-maps

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
#import <EXSplashScreen/EXSplashScreenService.h>
#import <UMCore/UMModuleRegistryProvider.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;
@property (nonatomic, strong) NSDictionary *launchOptions;

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [GMSServices provideAPIKey:@"KEY"]; // add this line using the api key obtained from Google Console //react-native-maps//OUR KEY
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  
  
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  self.launchOptions = launchOptions;
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  #ifdef DEBUG
    [self initializeReactNativeApp];
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #endif

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  // [REQUIRED] Register BackgroundFetch
  [[TSBackgroundFetch sharedInstance] didFinishLaunching];

  // for react-native-notifications
  [RNNotifications startMonitorNotifications]; // -> Add this line
  
  return YES;
}

- (RCTBridge *)initializeReactNativeApp
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
  // THIS CONDITION
  #if RCT_DEV
    [bridge moduleForClass:[RCTDevLoadingView class]];
  #endif
  // TILL HERE
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return bridge;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
  return extraModules;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[EXUpdatesAppController sharedInstance] launchAssetUrl];
 #endif
}

- (void)appController:(EXUpdatesAppController *)appController didStartWithSuccess:(BOOL)success {
  appController.bridge = [self initializeReactNativeApp];
  EXSplashScreenService *splashScreenService = (EXSplashScreenService *)[UMModuleRegistryProvider getSingletonModuleForClass:[EXSplashScreenService class]];
  [splashScreenService showSplashScreenFor:self.window.rootViewController];
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

// for react-native-notifications
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}

@end

```

Describe what you expected to happen:

1. I expected to project to build and run in the simulator so I could try and make use of this package

Describe what you actually happens:

1. if the podfile and and AppDelegate.m code from the install staeps is present the app will not build
2. Tried both npm run ios and running from XCODE

## Reproducible sample code

The issue is the app can not run once you add the code from the instructions, either something in the instructions is unclear, and the Prdfile or AppDelegate.m are wrong, or somthing is broken. My guess is something is unclear, but I am at a loss as to what line is wanted to be moved? Or why I need to change in XCODE for this to build

**Comment by Simon-TechForm** [comment]
hi @kapil21. We need to keep the issue section related to bugs and feature requests. I suggest taking this question to stackoverflow or the likes :) The install instructions haven't changed for a while, so it's unlikely that this is caused by react-native-maps. If you manage to track down the issue further, feel free to open a new issue :)

**Comment by russmenum** [comment]
Who is @kapil21? @Simon-TechForm And so this repo just ignores critical install wholes?

**Comment by Simon-TechForm** [comment]
@russmenum my apologies, too quick on the paste. Edited my comment :)

We don't ignore issues if bug reports indicates that there's an error in the library, but your issue doesn't indicate any issue in the library. As I said, if you manage to track down the issue, please feel free to open another issue :)

**Comment by russmenum** [comment]
Then what is the error?

If I remove this library app builds, if I install it, the Google-Maps-iOS-Utils ver it requires prevents the app building

**Comment by russmenum** [comment]
@Simon-TechForm  this is a bug with respect to fresh installs, I am not sure what changed but at this time you cant use Google Maps on iOS following the current directions. It could be anything from a ver change of who knows... I am willing to provide whatever info is needed to track this down, as I am sure it is affecting a lot of iOS builds... But I am very confused why instead of prob the ticket is just forced closed completely unresolved or addressed?

**Comment by Simon-TechForm** [comment]
@russmenum Lets make sure I wasn't too quick on this :)

I just tried to reproduce your issue, but I can't. I even tried to reproduce it in a `react-native@0.63.4` project to be sure. It builds and runs successfully on my end.

If you are able to provide a [minimal reproducible example project](https://stackoverflow.com/help/minimal-reproducible-example) in a repo, I will be happy to revisit the issue :) Please make sure to provide steps for how you set up the example project.

**Comment by russmenum** [comment]
> @russmenum Lets make sure I wasn't too quick on this :)
> 
> I just tried to reproduce your issue, but I can't. I even tried to reproduce it in a `react-native@0.63.4` project to be sure. It builds and runs successfully on my end.
> 
> If you are able to provide a [minimal reproducible example project](https://stackoverflow.com/help/minimal-reproducible-example) in a repo, I will be happy to revisit the issue :) Please make sure to provide steps for how you set up the example project.

@Simon-TechForm  cloned the project, still cant build when using Google Maps on iOS

striping out all keys and screens other than the ```Map.js``` in its most min form for a [minimal reproducible example project](https://stackoverflow.com/help/minimal-reproducible-example)

If this repo will build for you that would mean there is just something beyond odd in the node, xcode, or pod files that are in the ```.gitignore``` standard to an RN project. But beyond comparing between a working system set up which I do not have, and this broken one how would you even troubleshoot that? And with this being a copy from a fresh git clone that would basically rule that out anyways.

you can clone ```git@github.com:russmenum/mrep.git```

The ``README``` documents steps I took here; and the error snip I get before it fails.

As noted this is related to Google Maps, but I am following the installation instructions and this is supposed to be supported use.

**Comment by Simon-TechForm** [comment]
@russmenum your example repo builds and runs successfully for me as well.

> If this repo will build for you that would mean there is just something beyond odd in the node, xcode, or pod files that are in the .gitignore standard to an RN project.

Yeah it definitely seems like there's something odd going on in your local env. I would suggest creating a new RN project from scratch and installing react-native-maps in that and check whether that works as expected, eg.:

- `npx react-native init MapsTest`
- Follow the installation instructions of react-native-maps

**Comment by russmenum** [comment]
@Simon-TechForm respectfully having to restart a project from scratch just to use a library is itself a bug. 

How did you build the project? Directly in XCODE or using "npm run ios"? If in XCODE what target?

What ver of XCODE? and so on? Whatever this X ingredient is, that or a lack of it is the bug...

**Comment by Simon-TechForm** [comment]
@russmenum I'm not talking about restarting a project, I'm asking you to check whether it works in a fresh project, since the bug is only reproducible on your computer :)

**Comment by russmenum** [comment]
@Simon-TechForm the clean test you recommend won't even let me npm install 

```
[user_name]@iMac MapsTest %  npm install react-native-maps --save-exact
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mapstest@0.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">= 16.0 || < 18.0" from react-native-maps@0.30.1
npm ERR!   node_modules/react-native-maps
npm ERR!     react-native-maps@"*" from the root project
npm ERR!   2 more (react-native, react-native-web)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from react-dom@18.0.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=17.0.1" from react-native-web@0.17.7
npm ERR!   node_modules/react-native-web
npm ERR!     peer react-native-web@">= 0.11" from react-native-maps@0.30.1
npm ERR!     node_modules/react-native-maps
npm ERR!       react-native-maps@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/[user_name]/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[user_name]/.npm/_logs/2022-04-14T18_41_45_442Z-debug.log
[user_name]@iMac MapsTest % 
```


```17.0.2``` seems to be in the target range so very confused? And it at least completed this step on the project that was ```16.13.1```

I literally only done:
- ```npx react-native init MapsTest```
- ```cd MapsTest```
- ```npm run ios``` to test that it built right
- closed the app
- and now ```npm install react-native-maps --save-exact```

So this is as clean fresh start as you can get

**Comment by Simon-TechForm** [comment]
@russmenum yeah, this is caused by https://github.com/react-native-maps/react-native-maps/issues/4167. You should be able to install with the --force flag without issues :)

**Comment by russmenum** [comment]
Not sure why but it builds, but it is still using Apple Maps, not Google

**Comment by Simon-TechForm** [comment]
@russmenum  Make sure to apply the `provider="google"` prop.

**Comment by russmenum** [comment]
@Simon-TechForm any idea where to look for what is different? While this runs, it does not really fix the problem, unless this app is completely rebuilt on this new base from scratch. 

There is clearly some change here that needs to be spliced over, but nothing obvious. And it is still beyond odd that the same code will run on your system, but not this one. I would also expect a core system config issue to persist even on a fresh build like this.

That it is not doing so makes it even more strange that you can DL the same repo as me but it runs for you and not me?

**Comment by Simon-TechForm** [comment]
@russmenum since you're able to build in a fresh install, you've most likely ruled out system settings, xcode version etc, and probably narrowed it down to something project specific. Since I'm able to build and run the exact same code, I would suspect that cleaning out the project completely, reinstalling everything might fix it. The easiest way to test that is probably to clone your own repo into a new folder and install/build/run in the new folder.

**Comment by russmenum** [comment]
@Simon-TechForm that is basically how I made the MREP

- Fresh clone of this app repo to a separate dir
- copied everything but ```.git``` to the MREP
- ```npm install```
- ```cd ios```
- ```pod install```
- ```cd ..```
- ```npm run ios```

Before I committed the change to MREP I removed all the things listed above, so the keys and what not would not be on that GIT. But I am at a complete loss how a "something project specific" error would carry overdoing that where it would not run here, but run for you there?

I even fresh cloned the ```git@github.com:russmenum/mrep.git``` to a separate dir and did nothing but:
- ```npm install```
- ```cd ios```
- ```pod install```
- ```cd ..```
- ```npm run ios```

And this link error on ```npm run ios``` presisited.

**Comment by Simon-TechForm** [comment]
@russmenum are you currenly on an Intel or M1 mac?

**Comment by russmenum** [comment]
@Simon-TechForm I have both. Today am on an Intel one.

**Comment by Simon-TechForm** [comment]
@russmenum Okay. I'm also currently on an Intel one, so that doesn't explain why it doesn't build on your end.

**Comment by russmenum** [comment]
@Simon-TechForm 

While I still get 
```
      GoogleMapsUtils.HeatMapInterpolationPoints.(kcluster in _085340145A7263942932318178DB6148)() -> [[__C.CLLocationCoordinate2D]] in libGoogle-Maps-iOS-Utils.a(HeatMapInterpolationPoints.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It looks like the build may keep running past that? It goes on to 

```

/Users/[user_name]/github/test-mrep/FRD-Clone/fr-driver-track-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'boost-for-react-native' from project 'Pods')
/Users/[user_name]/github/test-mrep/FRD-Clone/fr-driver-track-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'react-native-notifications' from project 'Pods')
/Users/[user_name]/github/test-mrep/FRD-Clone/fr-driver-track-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'react-native-maps' from project 'Pods')
/Users/[user_name]/github/test-mrep/FRD-Clone/fr-driver-track-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'RNBackgroundFetch' from project 'Pods')
/Users/[user_name]/github/test-mrep/FRD-Clone/fr-driver-track-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'react-native-google-maps' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
	Ld /Users/[user_name]/Library/Developer/Xcode/DerivedData/frdrivertrackapp-gimfqgdjlxeiqvczvobjuesndnse/Build/Products/Debug-iphonesimulator/frdrivertrackapp.app/frdrivertrackapp normal (in target 'frdrivertrackapp' from project 'frdrivertrackapp')
(1 failure)


```

no idea where it is even getting 8 from because ```IPHONEOS_DEPLOYMENT_TARGET = 11.0```; but that does not seem to be what is crashing this. Any idea on the next bit ?

**Comment by russmenum** [comment]
@Simon-TechForm In case anyone else encounters this posting here. I have never encunted this issue before.

As noted above was getting a lot of ```Could not find or use auto-linked library 'swift*'``` and then errors for not finding them.

Finaly found [this](https://stackoverflow.com/questions/52536380/why-do-i-get-ios-linker-errors-with-my-static-libraries)

Apparently, in weird cases, XCODE needs you to manually add an empty Swift file and bridge. No clue why, or how this worked for you can not me with out you doing this, but if anyone else gets traped in this, it is a fix.

Not sure if it is common enough to add to the how to insall page or not.

**Comment by Simon-TechForm** [comment]
@russmenum I'm glad you worked it out :)

If we get more people reporting the issue, I will make sure to add a note about it in the installation instructions. I think this will happen on any library that relies on swift libraries, so it isn't specific to `react-native-maps` :) But yeah, very strange that it worked fine on my end.
