### ISSUE TITLE
`showPointsOfInterest` has no effect on Android

### ISSUE THREAD

**Issue by adamsoutar** [react-native-maps/react-native-maps#4187]
# Bug report

## Summary

`showPointsOfInterest={false}` doesn't seem to have any effect on Android.

When supplying this prop, nothing happens, the POI are still visible (it _does_ work on iOS MapKit - I have not tried iOS Google Maps as I don't have that set up for this project).

You can work around this by providing a custom style to hide POI on Android's `standard` map:

```js
<MapView
  mapType='standard'
  // Has no effect on Android, but supplied for iOS
  showsPointsOfInterest={false}
  // POI workaround for Android
  customMapStyle={{
    featureType: 'poi',
    elementType: 'labels',
    stylers: [{ visibility: 'off' }],
  }}
>
  {children}
</MapView>
```

However, `customMapStyle` doesn't seem to work for the `satellite`, `hybrid` or `terrain` map styles - it only works on `standard`. So far, I have not been able to find a way to hide Points of Interest on Satellite Google Maps.

Maybe this prop was always meant to be MapKit-specific, but that's just not mentioned in the docs?

## Environment info

`react-native info` output:

```
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 28.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - ~/n/bin/node
    Yarn: Not Found
    npm: 8.1.4 - ~/n/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```bash
react: 17.0.2
react-native: 0.66.2
react-native-maps: 0.30.1 (also tried 0.31.0-beta.5 - no difference)
```

## Steps to reproduce

1. Mount a `<MapView showPointsOfInterest={false} />`

Describe what you expected to happen:

1. Points of Interest such as local shops, restaurants, etc. should be hidden

Describe what you actually happens:

1. They are still visible on Android, even though they disappear on iOS MapKit.

**Comment by Simon-TechForm** [comment]
@adamsoutar first of all, thank you for taking the time to write a thorough issue.

> Maybe this prop was always meant to be MapKit-specific, but that's just not mentioned in the docs?

You are absolutely correct. It's simply only implemented for iOS Mapkit, which should be stated in the docs. I've just opened a PR that adds a note about it.

If you would like to see it implemented on Google Maps as well, feel free to open a feature request (most of it should be a copy/paste of this issue) :)

**Comment by adamsoutar** [comment]
Awesome, that makes sense. 

Thanks for updating the docs, I'll open a Feature Request when I'm at my machine tomorrow 👍

**Comment by adamsoutar** [comment]
Closing in favour of #4192 .
Thanks for the help @Simon-TechForm :)
