### ISSUE TITLE
iOS/Android Timing animation crash app with useNativeDriver

### ISSUE THREAD

**Issue by SergioAN007** [react-native-maps/react-native-maps#4188]
# Bug report
Using timing animation with useNativeDriver: true app crashes in ios and android
react-native-maps version 0.30.0+ include last 0.31.0-beta.5

## Summary
Using timing animation with useNativeDriver: true app crash in ios and android

disconnectAnimatedNodeFromView: Animated node with tagp[176] does not exist
Error: This JS animated node type cannot be used as native animated node

## Environment info

"react-native": "0.68.0",
"react-native-maps": 0.30.0+

## Reproducible sample code

this.state = {
    coordinate: new AnimatedRegion({
        latitude: this.props.Marker.Latitude,
        longitude: this.props.Marker.Longitude,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA
    }),
}

let markerMove = { ...newCoordinate, duration: animateDuration, useNativeDriver: true };
this.state.coordinate.timing(markerMove).start();

**Comment by CHETANECINFOSOLUTIONS** [comment]
Were you able to solve this problem
Issue I am facing is when I keep screen which has code of animateMarker open for long time then app automatically crashes

I have followed this approach
https://github.com/react-native-maps/react-native-maps/blob/master/example/src/examples/AnimatedMarkers.tsx

**Comment by SergioAN007** [comment]
This issue is not your case. 
Using timing animation with useNativeDriver: true app crashes in ios and android. The error occurs immediately, on the first attempt to animate.
This problem is not solved in the current version (v1.1.0) of the library. Therefore, in iOS I use timing animation with useNativeDriver: false, and in Android - animateMarkerToCoordinate


"react-native": "0.69.2",
"react-native-maps": 1.1.0

**Comment by CHETANECINFOSOLUTIONS** [comment]
Yes, I follow the same approach
But what I have noticed is even though we use timing without nativeDriver
and we are updating location per second app crashes after some time if we
are on that screen which has location update and animate marker code

And it only happens in release mode it won't crash on emulator it only
crash when you send ipa file and install it
