### ISSUE TITLE
Custom IOS native module 'GoogleMaps/GoogleMaps.h' file not found

### ISSUE THREAD

**Issue by zarkoden** [react-native-maps/react-native-maps#4191]
# Bug report

## Summary

When `#import <GoogleMaps/GoogleMaps.h>` is used in custom IOS native module it fails. But it's being imported in AppDelegate.m without any problems.

## Environment info

`react-native info` output:

System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2021.12.06.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 31
      Build Tools: 29.0.3, 32.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 3.0.0 => 3.0.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```bash
# paste your react, react-native, react-native-maps versions here
```

## Steps to reproduce

1. create native module file, for example, CustomCode.m:

```
#import "CustomCode.h"
#import <React/RCTRootView.h>
#import <GoogleMaps/GoogleMaps.h>
//#import "Firebase.h"

@implementation CustomCode

// Lifecycle methods (DO NOT DELETE)
// These methods will be called in the BuddyBoss app's AppDelegate.m
// You can hook into them to initiate your native libraries or run any custom side-effects

// Called inside AppDelegate.m didFinishLaunchingWithOptions method. This should be used to init most native libraries.
+ (void)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // [GMSServices provideAPIKey:@"KEY"]; // add this line using the api key obtained from Google Console
}

// Called inside AppDelegate.m didFinishLaunchingWithOptions method when rootView is attached to window
+ (void)rootViewVisible:(RCTRootView *)rootView
{}

// Here you can write your own custom native modules to use in your custom repo
// Below is an example of a simple method to multiply two numbers
// See https://reactnative.dev/docs/native-modules-ios for more information

RCT_EXPORT_MODULE()

// This example method can be deleted
RCT_REMAP_METHOD(multiply,
                 multiplyWithA:(nonnull NSNumber*)a withB:(nonnull NSNumber*)b
                 withResolver:(RCTPromiseResolveBlock)resolve
                 withRejecter:(RCTPromiseRejectBlock)reject)
{
  NSNumber *result = @([a floatValue] * [b floatValue]);
  resolve(result);
}

@end
```
and CustomCode.h

```
#import <React/RCTBridgeModule.h>
#import <React/RCTRootView.h>

@interface CustomCode : NSObject <RCTBridgeModule>

+ (void)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions;
+ (void)rootViewVisible:(RCTRootView *)rootView;

@end
```
2. try to build the app

Describe what you expected to happen:

Expected is imports to work in custom module as it works with  #import "Firebase.h" or as it works on  AppDelegate.m

Describe what you actually happens:

1. …
2. …

**Comment by salah-ghanim** [comment]
@zarkoden this is not a bug in this repository, this completely depends on how you setup your native environment, this lib on its own doesn't define native dependencies for iOS instead it just gives instructions where those dependencies to be expected your project's (Podfile).


don't assume GoogleMaps is part of react-native-maps and you should be able to phrase your question properly for stackoverflow not here

**Comment by sesm** [comment]
>  instead it just gives instructions where those dependencies to be expected your project's (Podfile)

@salah-ghanim Can you give a link to those instructions please? Do you mean that iOS users who want to use Google Maps should copy this dependencies to Podfile? https://github.com/react-native-maps/react-native-maps/blob/master/example/ios/Podfile.lock#L14
