### ISSUE TITLE
Build input file cannot be found: '/my-app/ios/AirMaps/Callout/SMCalloutView.m'

### ISSUE THREAD

**Issue by tdranv** [react-native-maps/react-native-maps#4193]
# Bug report

## Summary

I've started using the library in a project but I cannot build it. I get the following error when trying to build the iOS project.
```
Build input file cannot be found: '/my-app/ios/AirMaps/Callout/SMCalloutView.m'
```

I'm not sure why xCode looks for the files in the ios folder. The files are present in `node_modules/react-native-maps/lib/ios`, but I do not know how to tell xCode to look for them there. I tried modifying the build configuration and include the path to the files there but still nothing.

Here is how the project structure looks in xCode:
![Screenshot 2022-04-14 at 15 37 19](https://user-images.githubusercontent.com/45210624/163392384-07c0f3b5-e796-499f-8d81-40eb6c7dc5f7.png)

Not sure why these two are in red.

Here are the folders that it needs (in node_modules):
![Screenshot 2022-04-14 at 15 41 06](https://user-images.githubusercontent.com/45210624/163392540-8ea128ea-7ea8-4880-b9d1-f82ec2a370bf.png)

## Environment info
react-native-maps: 0.30.1

`react-native info` output:

```bash
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 467.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
```

Podfile:
```ruby
platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'my-app' do
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  use_unimodules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

## Steps to reproduce

1. npm install react-native-maps
2. npx pod-install
3. in xCode -> Product -> Build

Describe what you expected to happen:

1. Have the project build successfully.

Describe what you actually happens:

1. I get an error

## Reproducible sample code

Not applicable.

**Comment by salah-ghanim** [comment]
@tdranv there is nothing special here, most likely you didn't link the library correctly given the fact that you're trying to link the files manually in xcode

Please follow the instructions here: https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md
