### ISSUE TITLE
Android 12

### ISSUE THREAD

**Issue by iraniancat** [react-native-maps/react-native-maps#4194]
# Bug report

## Summary

Hello
I want to develop this component for my application but not compatible for android 12 and Crash on Android 12

**Comment by CVHOANG-coder** [comment]
same problem

**Comment by salah-ghanim** [comment]
@iraniancat @CVHOANG-coder there is a format to submitting tickets that are missing. which is necessary info to support you here.

I'm closing this bug, please submit it again with all info you have including
1. environment info
2. which devices did you test on.
3. the crash's stacktrace
