### ISSUE TITLE
Getting error after installing pods in iOS Simulator React Native 0.68.1

### ISSUE THREAD

**Issue by dhruvparmar1** [react-native-maps/react-native-maps#4197]
# Bug report

## Summary

Getting an error after installing react-native-google-maps pods for iOS:

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

## Environment info

`react-native info` output:

```bash
System: mac M1
react-native: 0.68.1  
react: 17.0.2  
react-native-maps: 0.30.1
Target Platform: iOS - 15.4 Simulator/iPhone 13
Using GoogleMaps
```

## Steps to reproduce

1. In AppDelegate.mm added #import <GoogleMaps/GoogleMaps.h> & [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; 
2. Added React Native Maps dependencies rn_maps_path = '../node_modules/react-native-maps' pod 'react-native-google-maps', :path => rn_maps_path in pod file above use_native_modules!3. 
3. After running the application from vs code and xcode getting an error as Undefined symbol: _OBJC_CLASS_$_RCTBundleURLProvider, Undefined symbol: _OBJC_CLASS_$_RCTBridge,  Undefined symbol: _RTCAppSetupPrepareApp, Undefined symbol: _RTCAppSetupDefaultRootView

Describe what you expected to happen:

1. The iOS app sould get installed and run in iOS simulator without getting any erro
<img width="388" alt="err" src="https://user-images.githubusercontent.com/35068228/164782582-68fdba99-63d3-4e35-8d99-75db0c00bcee.png">
r

**Comment by salah-ghanim** [comment]
@dhruvparmar1 duplicate
https://github.com/react-native-maps/react-native-maps/issues/3527

**Comment by togenius1** [comment]
I got the same issues on M1.
