### ISSUE TITLE
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by bumjin1013** [react-native-maps/react-native-maps#4210]
Hi, when i put playServicesVersion = "17.0.0" on build script, Excution failed for task error occur and build is fail.
With out playServicesVersion, build is success but app is crashed when MapView is called.

environment
rn : 0.68.0
react : 17.0.2

```
buildToolsVersion = "31.0.0"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        kotlinVersion = '1.5.0'
        supportLibVersion   = "23.1.1" // default: 23.1.1
        playServicesVersion = "17.0.0" // or find latest version
        androidMapsUtilsVersion = "2.3.0"
```

**Comment by caglardurmus** [comment]
Same here i can't build too.

**Comment by DuongVuongUTE** [comment]
+1

**Comment by siddharthanelango** [comment]
same issue facing here  Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.


buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        supportLibVersion   = "30.0.2"

        playServicesVersion = "17.0.0" // or find latest version      
        googlePlayServicesVisionVersion = "19.0.0"
        androidMapsUtilsVersion = "2.3.0"
    }

**Comment by JordaoViktor** [comment]
I'm also having this error

**Comment by memon07** [comment]
I am still facing this issue on react-native-maps version 1.4.0

environment : 
`react-native : 0.71.2,
react-native-maps : 1.4.0, react : 18.2.0 `


gradle settings : 
        
        buildToolsVersion` = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "20.1.5948944"
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "2.3.0"
        androidXCore = "1.7.0"

**Comment by kpatticake** [comment]
Still facing this issues, fresh install. Any word?

**Comment by Priyanshu2117** [comment]
is this issue resolved? if yes then how?

**Comment by Ashishkanojia2** [comment]
solution kaha hai iska
