### ISSUE TITLE
liteMode makes maps unusable on older android devices

### ISSUE THREAD

**Issue by mahcloud** [react-native-maps/react-native-maps#4221]
# Bug report

## Summary

Using the prop liteMode on an android device that is old enough that it does not support light/dark mode results in a map that will not interact. The user cannot zoom or move.

## Environment info

      react-native: 0.67.2
      react: 17.0.2
      react-native-maps: 0.31.1

    Target Platform: eg: android

## Steps to reproduce

Opening a map on a pixel 2 or pixel 3 results in the map no longer being intractable if liteMode is set to true.

Describe what you expected to happen:

I expect to be able to set liteMode={true} or liteMode={false} to support modern android devices without it crashing the map on older android devices. 😄 

Describe what actually happens:

liteMode={true/false} on pixel2 android phone results in a map that cannot be used.

## Reproducible sample code

```js
<MapView
  liteMode={true}
/>
```

**Comment by arslanafzal-entertainer** [comment]
+1

**Comment by Simon-TechForm** [comment]
hi @mahcloud 👋 I suggest having a look at Google's docs for [lite mode](https://developers.google.com/maps/documentation/android-sdk/lite#overview_of_lite_mode) - the non-interactive map is how it's supposed to work :)
