### ISSUE TITLE
Check if longitude and latitude is within the region

### ISSUE THREAD

**Issue by arelstone** [react-native-maps/react-native-maps#4222]
# Feature request

## Why it is needed
When dealing with a lot of markers the performance of the map is slow and sluggish. A performance optimisation is to check if a marker is within the region of the map before rendering it.

## Possible implementation

You can use the region to see if the point is within the given region

### Code sample

I've been using this for a long time in the app I am working on and think that some could benefit for it too

```js
isLatLngInRegion({latitude, longitude}) {
    const {region, initialRegion} = this.props
    // We cannot determinate if the coords is within the viewport
    if (!region || !initialRegion) return true

    const { latitude: regLat, latitudeDelta, longitude: regLon, longitudeDelta } = region
    const latMin = regLat - (latitudeDelta / 2)
    const latMax = regLat + (latitudeDelta / 2)
    const lonMin = regLon - (longitudeDelta / 2)
    const lonMax = regLon + (longitudeDelta / 2)

    let long = longitude

    if (lonMin < -180 && longitude > 0) {
      long = longitude - 360
    }

    if (lonMax > 180 && longitude < 0) {
      long = longitude + 360
    }

    return (latitude >= latMin && latitude <= latMax) && (long >= lonMin && long <= lonMax)
  }
  ```

**Comment by ravirajn22** [comment]
Hi thanks for the code snippet, this lib is just a bridge to native layer. All custom logics which can be implemented in JS even if used by many should not be included in the library. Keeping it this way will make it easier to maintain the library.
