### ISSUE TITLE
Google-Maps-iOS-Utils/GoogleMapsUtils.modulemap' not found

### ISSUE THREAD

**Issue by parmarravi** [react-native-maps/react-native-maps#4223]
I am getting this error when I try to build the app in Xcode

> fatal error: module map file '/Users/raviparmar/Library/Developer/Xcode/DerivedData/AppName-fzfidluhroyaqbftlvcalahizjbe/Build/Products/Release-iphoneos/Google-Maps-iOS-Utils/GoogleMapsUtils.modulemap' not found

Package .json

```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@react-native-community/datetimepicker": "^6.1.2",
    "@react-native-firebase/app": "^14.9.1",
    "@react-native-firebase/crashlytics": "^14.9.1",
    "@react-native-firebase/messaging": "^14.9.1",
    "@react-native-picker/picker": "^2.4.1",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "add": "^2.0.6",
    "axios": "^0.27.2",
    "dayjs": "^1.10.6",
    "decode-google-map-polyline": "^1.0.1",
    "install": "^0.13.0",
    "js-base64": "^3.7.2",
    "metro-react-native-babel-transformer": "^0.70.2",
    "react": "^18.0.0",
    "react-native": "^0.68.1",
    "react-native-calendars": "^1.1283.0",
    "react-native-confirmation-code-field": "^7.2.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "2.4.1",
    "react-native-maps": "^0.31.1",
    "react-native-maps-animated-polyline": "^1.0.6",
    "react-native-marquee": "^0.3.2",
    "react-native-material-menu": "^2.0.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-dropdown": "^1.0.2",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-paper": "^4.12.1",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-reanimated": "2.8.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-shimmer": "^0.6.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.3.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-vector-icons": "^9.1.0",
    "react-native-webview": "^11.18.2",
    "validate.js": "^0.13.1",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@babel/core": "^7.17.10",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/cli-platform-android": "^7.0.1",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^28.0.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "eslint": "8.14.0",
    "eslint-plugin-detect-hard-code": "^0.1.0",
    "jest": "^28.0.3",
    "metro-config": "^0.70.2",
    "metro-react-native-babel-preset": "^0.70.2",
    "react-native-asset": "^2.0.1",
    "react-native-svg-transformer": "^1.0.0",
    "react-test-renderer": "18.0.0"
  },
```

POD FILE

```

# $FirebaseSDKVersion = '8.10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

install! 'cocoapods', :deterministic_uuids => false

target 'appname' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # react-native-maps dependencies
  rn_maps_path = '../node_modules/react-native-maps' # This path is likely to be `../node_modules/react-native-maps` in your own project.

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS

  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'


  target 'appnameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

Error on vs code

> 
> e-webview/libreact-native-webview.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_RNSplashScreen", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_RCTRootView", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_RCTBridge", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_FIRApp", referenced from:
>       objc-class-ref in AppDelegate.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 
> objc[13118]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x207301eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c4f8). One of the two will be used. Which one is undefined.
> objc[13118]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x207301f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c548). One of the two will be used. Which one is undefined.
> objc[13118]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x207301f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c598). One of the two will be used. Which one is undefined.
> objc[13118]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x207301fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c5e8). One of the two will be used. Which one is undefined.
> objc[13118]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x207301ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c638). One of the two will be used. Which one is undefined.
> objc[13118]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x207302040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105d3c688). One of the two will be used. Which one is undefined.
> 2022-05-05 07:36:17.711 xcodebuild[13118:108102] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> 2022-05-05 07:36:17.711 xcodebuild[13118:108102] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         Ld /Users/raviparmar/Library/Developer/Xcode/DerivedData/appname-dqbblgoqsdixldesibgybnuqwdtn/Build/Products/Debug-iphonesimulator/appname.app/appname normal (in target 'appname' from project 'appname')
> (1 failure)

**Comment by jayliang701** [comment]
@parmarravi I meet this error. Have you resolved it? What is your solution? Thank you!

**Comment by parmarravi** [comment]
@jayliang701  need to recompile the  xcworkspace file in Xcode and do pod update. It will fix the issue

**Comment by pratikdonda** [comment]
module map file '/Users/prateek/Library/Developer/Xcode/DerivedData/thrive-fuerrfgjufxddewdefergteoxji/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.modulemap' not found

Getting this error while update Xcode 14 to 15

can anybody help me here?

**Comment by julihabif** [comment]
Same here, I tried everything and I still get the error.

**Comment by cgandiaf** [comment]
Same here, is there anything new to fix it?
Also happened when updating from Xcode14 to 15.

Can anybody help me? Thanks!!

**Comment by GirrajS** [comment]
add "arm64" in Excluded architectures for debug and release, go to Project->Build Settings. And also check Node version, make sure to use Node 18.

**Comment by sahilkashyap64** [comment]
make sure to remove from both [project and pods section.](https://github.com/react-native-maps/react-native-maps/issues/4258#issuecomment-1780343283)

i had problem with m1 chip, set the terminal to use rosetta.
and also did [this](https://stackoverflow.com/a/77843156/8769785), I'm using xcode 15,RN version 66.4

```
if installer.respond_to?(:__apply_Xcode_12_5_M1_post_install_workaround)
      installer.__apply_Xcode_12_5_M1_post_install_workaround
    end
    ```
