### ISSUE TITLE
Fix tooltip width

### ISSUE THREAD

**Issue by DoneDeal0** [react-native-maps/react-native-maps#4230]
# Bug report
Custom tooltip's width are very narrow. Each character fills a line. 

There are currently 3 ways to fix it: 
1)  apply a fixed width (ex: `width: 200`), but it creates a weird ui depending of the text (too large or too small, rarely well adjusted)
2) apply a `position: relative` property to the `Callout` element (as child of the `Marker`), but the `Marker` is not properly positioned on the map anymore (this is particularly true when zooming on a map with a circle. We clearly see that the Marker is out of range).
3) stop using a custom tooltip and simply give `title` and/or `description` props to the marker, but the tooltip is ugly and can't be styled.

Suggested fixes:
a) give a `width: "100%` to the `Callout`'s tooltip, so the problem is gone. 
b) allow a `tooltipStyle` prop on the Marker so we can use the default tooltip with ease (relevant props would be: `backgroundColor`, `borderRadius`, `titleColor`, `descriptionColor`)

## Environment info
      react-native: 0.64.3
      react: 17.0.1
      react-native-maps: 0.29.4
 
I'm using Expo.

For the moment, the best option I came up with is:

```
   <Callout style={getToolipStyle(title, description)} tooltip>
              <Tooltip title={title} description={description} />
    </Callout>

export const getToolipStyle = (title: string, description: string) => {
  const _width = title.length > titles.length ? description.length : description.length;
  return {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: _width * 9,
    borderRadius: 8,
  };
};
```

**Comment by jagthedrummer** [comment]
This is still a bug and should not have been closed.
