### ISSUE TITLE
fitToCoordinates does not work properly on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by satyaranjan-evince** [react-native-maps/react-native-maps#4232]
### Summary
fitToCoordinates does not work as expected in iPhone 11 Pro Max

### Environment info
  react-native: 0.63.4
  react: 16.13.1
  react-native-maps: 0.31.1

**Target Platform**:  iOS

**Device in which issue is reproduced** : iPhone 11 Pro Max, iOS 15.4

**Steps to reproduce**
Call fitToCoordinates once when screen is mounted using a set of coordinates, works fine
Navigate to another screen, return back to the first screen and call fitToCoordinates  using the same set of coordinates, we will get the bug.

**Describe what you expected to happen:**

Map should be show correct area

**Describe what actually happens:**

Map does not stays within the required coordinates

**Reproducible sample code**
```js
fitAllMarkers = (coords = []) => {
       

        let edgePadding =
            Platform.OS == "android" ?
                {
                    top: PixelRatio.getPixelSizeForLayoutSize(80), right: PixelRatio.getPixelSizeForLayoutSize(20), bottom: PixelRatio.getPixelSizeForLayoutSize(80), left: PixelRatio.getPixelSizeForLayoutSize(Metrics.screenWidth * .45)
                } :
                {
                    top: initialWindowSafeAreaInsets.top + 80 + getStatusBarHeight(), right: 20, bottom: 80, left: Metrics.screenWidth * .45
                }

        let coordinates = [
            {
                latitude: parseFloat(this.props.currentLocation.latitude),
                longitude: parseFloat(this.props.currentLocation.longitude),
            },
            {
                latitude: parseFloat(this.props.objStoreDetails.latitude),
                longitude: parseFloat(this.props.objStoreDetails.longitude)
            }
        ]

        if (coords.length !== 0)
            coordinates = coordinates.concat(coords)


        if (this.mapView !== undefined && this.mapView !== null) {
         
            this.mapView.fitToCoordinates(coordinates, {
                 edgePadding: edgePadding,
                 animated: true
            })
        }

    }
```
.......
```js
 <MapView
                    ref={ref => this.mapView = ref}
                   
                    provider={PROVIDER_GOOGLE}
                    zoomControlEnabled={false}
                    zoomEnabled={false}
                    pitchEnabled={false}
                    scrollEnabled={false}
                    zoomTapEnabled={false}
                    showsUserLocation={false}
                    zoom={100}
                    customMapStyle={myMapStyle}
                    style={[styleMapView.mapView, { height: this.props.mapHeight + (Platform.OS == "ios" ? initialWindowSafeAreaInsets.top : 0), marginTop: Platform.OS == "ios" ? -initialWindowSafeAreaInsets.top : 0 }]}
                    moveOnMarkerPress={false}

                >

```

**Comment by danidaryaweesh** [comment]
Having the same issue described here

**Comment by nes123** [comment]
It seems that the ref callback does not work. 

<MapView
ref={ref => console.log(ref}

does not result in any output

**Comment by satyaranjan-evince** [comment]
> It seems that the ref callback does not work.
> 
> <MapView ref={ref => console.log(ref}
> 
> does not result in any output

It certainly works, wait till map is ready

**Comment by satyaranjan-evince** [comment]
Just some clarification for the bug, it malfunctions only while using Google maps on iOS, in default apples map it works as expected.

**Comment by XeeshanAnsari** [comment]
I am getting the same issue with GOOGLE maps but, It's working perfectly with apple maps. Any suggestions please for google maps.

**Comment by danidaryaweesh** [comment]
Thanks for the suggestion @XeeshanAnsari! will try it and hopefully it will work!

**Comment by socheat-leang** [comment]
Same issue here

**Comment by Simon-TechForm** [comment]
When are you calling the fitAllMarkers function?

**Comment by Simon-TechForm** [comment]
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Comment by estmau** [comment]
I have same issue. I use ani iphone 12 emulator with ios 16 in xcode 14 and props provider: google. If i change to apple maps, y dont have this issue.
