### ISSUE TITLE
LongLogTag issue

### ISSUE THREAD

**Issue by CuHeng** [react-native-maps/react-native-maps#4233]
> Task :react-native-maps:lintDebug FAILED
Lint found 5 errors, 19 warnings. First failure:

...\node_modules\react-native-maps\android\src\main\java\com\airbnb\android\react\maps\AirMapTileProvider.java:174: Error: The logging tag can be at most 23 characters, was 28 (urlTile: tile cache HIT for ) [LongLogTag]
    Log.d("urlTile: tile cache HIT for ", Integer.toString(zoom) +
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



/app/build.grade 
add source
`
   lintOptions {
        disable 'LongLogTag'
    }
`

**Comment by VladyslavMartynov** [comment]
I have also the same lint error when i am trying to build react-native application for Android? Somebody know how to solve this problem? Adding lintOptions { disable 'LongLogTag' } did not help and break good practice rules , maybe it`s better to make some changes  in source code ...\node_modules\react-native-maps\android\src\main\java\com\airbnb\android\react\maps\AirMapTileProvider.java:?

**Comment by Simon-TechForm** [comment]
Thank you for reporting this. I've pushed a commit that will fix this in the next release :)

**Comment by VladyslavMartynov** [comment]
Thanks for solving the problem!)
