### ISSUE TITLE
initialRegion not working on Android on version 0.31.0 or 0.31.1

### ISSUE THREAD

**Issue by MGD-GLS** [react-native-maps/react-native-maps#4234]
![image](https://user-images.githubusercontent.com/97229362/167765922-9d227b27-ffb5-4376-a888-3c52604e77b2.png)
error while updating property 'initialRegion' of a view managed by airmap

but on version 16.1 working correct

**Comment by MGD-GLS** [comment]
^0.30.0 working too

**Comment by SohelIslamImran** [comment]
Didnt you facing this issue? https://github.com/react-native-maps/react-native-maps/issues/4235

**Comment by mpn7** [comment]
Why was this closed? I still have this issue using the most basic of your examples.

`<MapView
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421
    }}
  />`

This is my package.json:
"@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-picker/picker": "2.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "create-react-class": "^15.6.2",
    "expo": "^44.0.0",
    "expo-analytics": "^1.0.18",
    "expo-app-loading": "^1.3.0",
    "expo-asset": "^8.4.6",
    "expo-file-system": "~13.1.4",
    "expo-localization": "^12.0.1",
    "expo-location": "^14.0.2",
    "expo-sqlite": "^10.1.1",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-image-slider-box": "^1.1.23",
    "react-native-map-link": "^2.9.3",
    "react-native-maps": "^0.31.1",
    "react-native-pager-view": "^5.4.15",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-side-menu-updated": "^1.3.2",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-tab-view": "latest",
    "react-translated": "latest",

Can anyone help with this?

Thank you, 
Miguel Neves

**Comment by kersa901** [comment]
> Why was this closed? I still have this issue using the most basic of your examples.
> 
> `<MapView initialRegion={{ latitude: 37.78825, longitude: -122.4324, latitudeDelta: 0.0922, longitudeDelta: 0.0421 }} />`
> 
> This is my package.json: "@react-native-async-storage/async-storage": "~1.15.0", "@react-native-community/netinfo": "7.1.3", "@react-native-picker/picker": "2.2.1", "@react-navigation/native": "^6.0.10", "@react-navigation/native-stack": "^6.6.2", "create-react-class": "^15.6.2", "expo": "^44.0.0", "expo-analytics": "^1.0.18", "expo-app-loading": "^1.3.0", "expo-asset": "^8.4.6", "expo-file-system": "~13.1.4", "expo-localization": "^12.0.1", "expo-location": "^14.0.2", "expo-sqlite": "^10.1.1", "react": "17.0.1", "react-native": "0.64.3", "react-native-image-slider-box": "^1.1.23", "react-native-map-link": "^2.9.3", "react-native-maps": "^0.31.1", "react-native-pager-view": "^5.4.15", "react-native-safe-area-context": "^4.2.5", "react-native-screens": "^3.13.1", "react-native-side-menu-updated": "^1.3.2", "react-native-swiper": "^1.6.0-rc.3", "react-native-tab-view": "latest", "react-translated": "latest",
> 
> Can anyone help with this?
> 
> Thank you, Miguel Neves

I may have been closed because no bug template was used. Might be worth creating a new bug for this and following the issue template

**Comment by mpn7** [comment]
For anyone interested I created a new issue with this error. #4256
