### ISSUE TITLE
Error: This JS animated node type cannot be used as native animated node

### ISSUE THREAD

**Issue by SohelIslamImran** [react-native-maps/react-native-maps#4235]
# Bug report
Getting this error,
`Error: This JS animated node type cannot be used as native animated node`
and also this

```Warning: Failed %s type: %s%s, prop, The prop `coordinate` is marked as required in `MapMarker`, but its value is `undefined`., 
MapMarker```

When using `AnimatedRegion` and `MarkerAnimated`

![image](https://user-images.githubusercontent.com/76745339/167872256-4f04e676-3da5-4654-b0ae-0dee7d057b9e.png)

## Environment info
google map
android emulator expo go

`react-native info` output:

```bash
    "expo": "^45.0.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1",
    "react-native-maps": "0.30.1",
```

Related issue with details #4136

**Comment by SohelIslamImran** [comment]
Related issue with details #4136

**Comment by Simon-TechForm** [comment]
Can you please include a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? :)
