### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by chetanparmar95** [react-native-maps/react-native-maps#4238]
# Bug report

## Summary

After installation when I run the iOS project from xcode, it gives following error
`
Undefined symbols for architecture x86_64:
  "_CTRadioAccessTechnologyNRNSA", referenced from:
      ___GMSCellNetworkTypeForRadioType_block_invoke in GoogleMaps
  "_CTRadioAccessTechnologyNR", referenced from:
      ___GMSCellNetworkTypeForRadioType_block_invoke in GoogleMaps
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

## Environment info

`react-native info` output:

```bash
react-native: 0.68.1
react: 17.0.2
react-native-maps: 0.31.1

Target Platform: eg: iOS(GoogleMap) - 14 Simulator/iPhone 11 pro max

```

## Steps to reproduce

1. Installing the specified version
2. Add following in pod file
```
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'GoogleMaps' 
```
3. Run the project from xcode

Describe what you expected to happen:

1. Build the project successfully

Describe what actually happens:

1. Failed with errors

**Comment by NipperInShorts** [comment]
I can't speak to the specifics around the bug itself, but setting NO to **Build Active Architecture Only** for debug might be a good workaround to get your app building.
You'll need to do this for both the project and pods.

**Comment by togenius1** [comment]
Same issues on Mac mini M1

**Comment by chetanparmar95** [comment]
@NipperInShorts this did not solve the problem.

**Comment by TereshchenkoVlad** [comment]
> I can't speak to the specifics around the bug itself, but setting NO to **Build Active Architecture Only** for debug might be a good workaround to get your app building. You'll need to do this for both the project and pods.

It helps me, (Mac Pro M1 )

**Comment by Simon-TechForm** [comment]
Thank you @TereshchenkoVlad 👍  Closing for now :)
