### ISSUE TITLE
[Apple Map]Polygon holes will not be updated.

### ISSUE THREAD

**Issue by jb9229** [react-native-maps/react-native-maps#4243]
# Bug report
👋 Hi!

## Summary
Polygon holes will not be updated.
This is the same for GeoJson.

We are temporarily forcing the key value to update the polygon holes.
provider="google" works fine.

When re-rendering, is there any way to update polygon holes in apple map?

## Environment info

react-native: 0.64.3
react: 17.0.1
react-native-maps: 0.30.1
Target Platform: iOS - 15.2 Simulator/iPhone 13,
map type: AppleMaps

```bash
`react-native info` output:
OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 21.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce
1. GeoJson or Polygon Rendering
````
<Geojson  geojson={serviceZoneGeoData} strokeColor="#~" fillColor="#~" strokeWidth={2} />
````
2. when "onRegionChangeComplete" change "serviceZoneGeoData"
````
<MapView
   onRegionChangeComplete={() => {
      ~~~~~
   setServiceZoneGeoData(newServiceZoneData);
}}
````
3. but not change servicezon(but re-rendering and servicezoneData is changed)
Describe what you expected to happen:
1. when change th servciezoneData and change polygon holes data

Describe what actually happens:

but not change servicezon(but re-rendering and servicezoneData is changed)

**Comment by Simon-TechForm** [comment]
Could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I can't run the code you provided, as I need `serviceZoneGeoData` and `newServiceZoneData`.
