### ISSUE TITLE
Animated Marker Flickering/Shivering

### ISSUE THREAD

**Issue by justinantony** [react-native-maps/react-native-maps#4246]
# Bug report

## Environment info

 react-native: 0.67.0
      react: 17.0.2
      react-native-maps: 0.30.1 
     iOS Phone
    GoogleMaps

https://user-images.githubusercontent.com/4530426/169762448-9fdbdc86-fae5-4b49-b8be-d81d4de66103.mp4

```js
Insert sample code here
```

**Comment by Jhonte** [comment]
+1 Works fine in simulator, but not on a real iPhone.

**Comment by hoaibkdn** [comment]
+1 hi @justinantony, how did you solve this issue?

**Comment by sen46Sko** [comment]
+1 same issue
