### ISSUE TITLE
onRegionChange fired multiple times after drag release

### ISSUE THREAD

**Issue by Foskas** [react-native-maps/react-native-maps#4248]
## Description

After dragging the map (not the marker),  the method onDrag is fired multiple times, change the selected location in the map.

After dragging the map (not the marker),  the method onDrag is called as soon as I release the touch/mouse but onRegionChange is called lots of times before onRegionChangeComplete is called.  Every one of this onRegionChange calls is returning different coordinates from the ones select while dragging. 

This does not happen all the time, but when it does, the location changes complety from the selected one. Sometimes it triggers the onRegionChange once (as it should), sometimes 4, sometimes 6....not consistent at all.

## Environment info

react-native: 0.64.2
react: 17.0.2
react-native-maps: 0.31.1

## Target 
Platform: iOS
Device: IPhone 13 Pro Max Simulator

## Steps to reproduce

To reproduct the isso all we need is just drag the map until this happens.

Here is an example of logs when the problem happens. As you can see, the coordinates changes a bit since the drag was released (last onDrag).
![Screenshot 2022-05-26 at 10 43 51](https://user-images.githubusercontent.com/39563017/170462992-fea35056-ed6a-42a3-9cd0-b925d326b4ee.png)

## Code example
```
<MapStyled
          height={height}
          ref={mapRef}
          provider={PROVIDER_GOOGLE}
          minZoomLevel={10}
          maxZoomLevel={18}
          showsCompass={false}
          initialRegion={INITIAL_LOCATION}
          onRegionChangeComplete={(coords: CoordinatesType, details?: { isGesture: boolean }): void => {
            if (details?.isGesture) console.log('DRAG END', coords);
          }}
          onPress={onMapClick}
          onRegionChange={(coords: CoordinatesType, details?: { isGesture: boolean }): void => {
            if (details?.isGesture) console.log('ON REGION CHANGE', coords, details);
          }}
          onPanDrag={(evt): void => {
            console.log('ON DRAG', evt.nativeEvent);
          }}
  >
```

**Comment by Simon-TechForm** [comment]
I need to make sure that I understand this correctly. When you drag the map, it's very likely that the region will change after you release the drag. Unless your drag is close to steady as you release it, the region will change after you release the drag, as the map will keep scrolling in the direction that the drag was released. This is expected behaviour.

Are you experiencing something else?
