### ISSUE TITLE
Bug with building app on a simulator on arm64 architecture

### ISSUE THREAD

**Issue by AvelisGit** [react-native-maps/react-native-maps#4249]
# Bug report

## Summary

Cannot build an app on a simulator after installing the library (using Xcode with rosetta on macbook M1 pro). Getting  an error: The linked library 'libPods-project.a' is missing one or more architectures required by this target: x86_64. (in target 'project' from project 'project')

<img width="420" alt="Снимок экрана 2022-05-27 в 10 25 26" src="https://user-images.githubusercontent.com/105357634/170662531-f2f88db7-6112-4eec-8273-8ad55300288d.png">

## Environment info

      react-native: 0.68.2
      react: 17.0.2
      react-native-maps: 0.31.1"

     Target Platform: iOS - 15.5 Simulator

## Steps to reproduce
followed installation guide in https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md

**Comment by orel-asper** [comment]
waiting for an answer too.

**Comment by XFAISAL** [comment]
Updates guys?

**Comment by Ziao** [comment]
Any news or workarounds :)?

**Comment by chriswiggins** [comment]
You need to make sure you set the arm64 build to be disabled on both your project, as well as the pods project. You’ll need to make sure you’re opening the XCWorkspce and not the Project file

**Comment by ChrisLFieldsII** [comment]
> Try adding
> 
> ```
>     installer.pods_project.build_configurations.each do |config|
>       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
> ```
> 
> into your Podfile, like this.
> 
> ```
>   post_install do |installer|
>     installer.pods_project.build_configurations.each do |config|
>       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> ```
> 
> run `npx pod-install` and make sure to open the project through Rosetta, this helped me.

This saved me and the team! We ran into this issue after integrating this project with bare expo also integrated.

Previously before this, I could at least run ios simulator on M1 with Rosetta enabled for XCode 13.4.

However after adding `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` in the `config` iteration, we no longer have to enable Rosetta.

**Comment by fukemy** [comment]
im using visual code, how to do it? Thanks
