### ISSUE TITLE
nativeEvent doesnt work inside onDragEnd

### ISSUE THREAD

**Issue by Qwardly** [react-native-maps/react-native-maps#4255]
### Summary

When I try to return coordinates via onDragEnd, event.nativeEvent does not work, as if nativeEvent does not exist for event. In other parts of the code, for example inside TouchableOpacity, it works.
![image](https://user-images.githubusercontent.com/81578967/170887515-780f1204-79be-47ef-bf7e-76a917612558.png)

### Reproducible sample code

```TSX
<Marker
                    coordinate={{
                        latitude: initialRegion.latitude,
                        longitude: initialRegion.longitude
                    }}
                    draggable={true}
                    onDrag={(e) => console.log('onDrag')}
                    onDragEnd={(event)=> event.nativeEvent}
                >
```

### Steps to reproduce

.

### Expected result

nativeEvent work inside onDragEnd

### Actual result

nativeEvent doesnt work

### React Native Maps Version

0.29.4

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.64.3

### Are you using Expo?

Yes

### Device(s)

iPhone 7

**Comment by Simon-TechForm** [comment]
Hi. 0.29.4 is getting old at this point. Please try using the latest version of react-native-maps. If you still experience the issue, feel free to open a new issue :)
