### ISSUE TITLE
Latest release has a smaller version than the one before it

### ISSUE THREAD

**Issue by fiteroc** [react-native-maps/react-native-maps#4257]
### Summary

The latest released version is v0.30.2 and the one before it is v0.31.1. Is this a mistake? With npm install we get the latest version as being v0.31.1, is this correct though? Please check it up!

### Reproducible sample code

```TSX
-
```

### Steps to reproduce

Check the version

### Expected result

Check the version

### Actual result

Check the version

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### Are you using Expo?

No

### Device(s)

-

**Comment by Simon-TechForm** [comment]
That's just how Github shows releases. v0.30.2 is the "latest" in the sence that it was the latest to be released, but 0.30.2 is just a maintenance release for Expo and contains nothing that v0.31.1 doesn't :)

**Comment by sudeepto-dutta** [comment]
@Simon-TechForm  So we should consider `0.31.1` as the latest version instead of `0.30.2` right?
