### ISSUE TITLE
Markers are not interactable when scrollEnabled = false

### ISSUE THREAD

**Issue by PaulMetley** [react-native-maps/react-native-maps#4263]
### Summary

Hello,

First of all, thanks for this amazing library.

I am trying to implement a simple map behavior still I am facing some issues to achieve it.

- **Objective** : Display a **fixed** map with **iteractable** markers.

The obvious way of doing that seems to set "scrollEnabled" parameter to "false" then to implement markers.

- **Behavior** : Markers became unpressable when "scrollEnabled" = true

Do you guys know a way to achieve wanted behavior properly ?

Sincerely,

Paul

### Reproducible sample code

```TSX
return (
    <MapView
        style={{
          flex: 1
        }}
        onPress={() => console.log("MAP PRESS")}
        moveOnMarkerPress={true}
        scrollEnabled={false}
          initialRegion={{
            latitude: 9.9169618,
            longitude: 78.1376334,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        tracksViewChanges={false}
        zoomEnabled={false}
      >
        <Marker
            coordinate={{
                latitude: 9.9169618,
                longitude: 78.1376334
            }}
            onPress={() => console.log("MARKER PRESS")}/>
    </MapView>
)
```

### Steps to reproduce

Just implement markers in a <MapView> with scrollEnabled = false

### Expected result

MapView should be unscrollable and markers should still be interactable

### Actual result

MapView should be unscrollable and markers **are not** interactable

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.67.2

### Are you using Expo?

No

### Device(s)

Google Pixel 3A

**Comment by Simon-TechForm** [comment]
Hi @PaulMetley 👋 

I'm having no issues setting `scrollEnabled={false}` and getting Marker onPress events with the sample you provided. One error I'm seeing is that you are setting `tracksViewChanges={false}` on the mapView and not the marker. I've just opened the discussion section, so if you continue experiencing problems, feel free to open a discussion in there :)
