### ISSUE TITLE
onRegionChangeComplete is executed multiple times when I change the region

### ISSUE THREAD

**Issue by cflorez10** [react-native-maps/react-native-maps#4265]
### Summary

when I make a significant region change the `onRegionChangeComplete` method is executed more than once, I am not clear if this behavior is expected or how I would listen only for the final region change which is actually what I need.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet } from 'react-native';

export default function App {
  const handleRegionChangeComplete = (region: Region) => {
    console.log('Current Region:', region);
  };

  return (
    <MapView 
      style={styles.map}
      initialRegion={map.region}
      region={map.region}
      onRegionChangeComplete={handleRegionChangeComplete}
    />
  )
}

const styles = StyleSheet.create({
  map: {
    flex: 1,
  }
});
```

### Steps to reproduce

make a change of region that involves a long journey, e.g. change from one continent to another or even change from one country to another with a drag movement, the idea is to swipe up or swipe down with a long movement.

### Expected result

the result that I expect and understand should happen is that a change of region should only be painted when the map reaches its destination by ending the drag event. if this is not the case, then understand how to listen only to the final region change.

### Actual result

when a change of region involving a significant displacement I get several changes of region at once, it is executed once in the middle of the movement and once more when the movement ends.

### React Native Maps Version

0.30.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.67.2

### Are you using Expo?

No

### Device(s)

iPhone 13 (iOS 15.2)

**Comment by ShawnRoller** [comment]
I'm seeing this as well.  `onRegionChangeComplete` is called while the Apple Maps is scrolling from a swipe.  I would expect it to only be called when the map stops scrolling and lands on a final region.

**Comment by BhuwaneshSisodia** [comment]
Hope this works for you

` const callAPI = (item) => {
    setTimeout(() => {
      dispatch(getData(item));
    }, 500);
  };

  const onRegionChange = async (item) => {
    setTimeout(() => {
      setLocation({
        latitude: parseFloat(item.latitude.toFixed(6)),
        longitude: parseFloat(item.longitude.toFixed(6)),
        latitudeDelta: parseFloat(item.latitudeDelta).toFixed(4),
        longitudeDelta: parseFloat(item.longitudeDelta).toFixed(4),
      });
    }, 1000);
    callAPI();
  };`
  
  _// MapView prop_
`onRegionChangeComplete={(item) => {
          onRegionChange(item);
}}`

**Comment by BhuwaneshSisodia** [comment]
Hope this works for you...

```
const onRegionChange = async (region, details) => {
    if (details.isGesture === true) {
      setLocation(region);
      return;
    }
    // await callAPI();
};
```
  // In MapView props
`onRegionChangeComplete={(region, details) => onRegionChange(region, details)}
`

**Comment by Dildar-Khan** [comment]
@BhuwaneshSisodia  details.isGesture is undefined, even passing provider={PROVIDER_GOOGLE}.

**Comment by Dildar-Khan** [comment]
Hello @BhuwaneshSisodia details.isGesture is always undefined.

import MapView from 'react-native-map-clustering';
import {PROVIDER_GOOGLE} from 'react-native-maps';

<MapView
provider={PROVIDER_GOOGLE}
onRegionChangeComplete={(mapRegion, {isGesture}) =>
 console.log(mapRegion, isGesture)
  }
......
/>

**Comment by cflorez10** [comment]
@BhuwaneshSisodia is only available for android, it is not an applicable solution for iOS, in iOS will always throw `undefined`.

**Comment by eduardorfreitas93** [comment]
@cflorez10 PR https://github.com/react-native-maps/react-native-maps/pull/4272 with a solution

**Comment by cflorez10** [comment]
@eduardorfreitas93 thanks for the contribution, I have a doubt, this is a workaround or a solution to the main problem which is the double execution of the `onRegionChangeComplete` event.

**Comment by eduardorfreitas93** [comment]
No, it's a solution for isGesture to work on IOS, you can try to solve it with the solution from @BhuwaneshSisodia

**Comment by kickbk** [comment]
Thanks @eduardorfreitas93 for the brilliant solution. Instead of waiting for your PR to get merged (which might never get merged for no good reason), it's super easy to use patch-package to apply the change. For those interested, here you go: https://gist.github.com/kickbk/eb2e5cf464dae86943c1067027a2226c

**Comment by kickbk** [comment]
@Simon-TechForm I am noticing a delay from the moment the map seem to have stopped moving (visually) to the time `onRegionChangeComplete` fires, which is a problem. I depend on knowing when the map finished moving, so I can pull up a search results carousel. I need to wait for the map to finish moving to avoid lag (clash) in the animation. So your recent update helps to solve it, but now the carousel appears slightly after it already finished moving, for no apparent reason.
I can think of two reasons this happens:
1. There is a deliberate delay between the moment the map actually stopped moving and `onRegionChangeComplete` firing
2. Although it looks like the map finished moving, programmatically, it's isn't yet.
Which is it?
If it's the first case, then is there a way to avoid the delay?

**Comment by SirCameron** [comment]
isGesture is always undefined on iOS using v1.3.1.

**Comment by cflorez10** [comment]
@eduardorfreitas93 do u have any solution for the newest version(1.3.1), I just tried to update the library but `isGesture` is not available there

**Comment by mattlewer** [comment]
@monholm Has this regressed since? Experiencing this on v1.10.0

**Comment by nfmshow** [comment]
I'm still experiencing this same issue on iOS, v1.24.5 (Google Maps).
isGesture is always undefined and updating the region from onRegionChangeComplete causes an infinite loop.
