### ISSUE TITLE
I get crash when using Google Maps

### ISSUE THREAD

**Issue by billnbell** [react-native-maps/react-native-maps#4288]
### Summary

I am not sure. But if I add Google Maps on IOS I get a crash. If I remove provider={PROVIDER_GOOGLE} the Apple maps show fine on IOS Simulator. Trying to see what it could be. React Native 0.68.2 and React 17.0.2. Followed all directions and got API key from Google.

```
 <MapView
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          region={{
            latitude: data?.destination.latitude ?? 0,
            longitude: data?.destination.longitude ?? 0,
            latitudeDelta: DEFAULT_LATITUDE_DELTA,
            longitudeDelta: DEFAULT_LATITUDE_DELTA + width / height,
          }}
        >
          {data && data.residences.length > 1 ? (
            data.residences.map((marker) => (
              <Marker key={`residence-${marker.title}`} coordinate={marker.latlng} title={marker.address1} />
            ))
          ) : (
            <Marker
              coordinate={{ latitude: data?.destination.latitude ?? 0, longitude: data?.destination.longitude ?? 0 }}
              title={data?.destination.address}
            />
          )}
        </MapView>
```

### Reproducible sample code

```TSX
provider={PROVIDER_GOOGLE}
```

### Steps to reproduce

DO I need Google Maps App installed for it to work?

### Expected result

No crash.

### Actual result

Crash

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.2

### Are you using Expo?

No

### Device(s)

15.5 IOS 13 Max

**Comment by shunki-github** [comment]
me too

**Comment by billnbell** [comment]
I rebooted, and cleaned and set the API Token, and it comes up on IOS, but Android is just a blue box for the map.

I also had to put at top. Even before NsLog.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSString *mapsApiKey = [ReactNativeConfig envFor:@"IOS_GOOGLE_MAPS_API_KEY"];
  [GMSServices provideAPIKey: mapsApiKey];
  NSLog(@"didFinishLaunchingWithOptions");
```

**Comment by Simon-TechForm** [comment]
If I get you right, you are no longer seeing the crash on iOS after doing a cleanup? In that case, I will close the issue. If you are having difficulties setting up the library, have a look at the discussions section 👍
