### ISSUE TITLE
React native new architecture(Fabric) support

### ISSUE THREAD

**Issue by michbil** [react-native-maps/react-native-maps#4289]
# Feature request

React-native new architecture have became pretty stable now, but library support is lacking, which slows down Fabric adoption. 

## Why it is needed

This library is critical for many users, so it should support new architecture. Here is link to the thread https://github.com/reactwg/react-native-new-architecture/discussions/6 with current status of Fabric adoption for open source libraries. 

## Possible implementation

Library is pretty massive, so i think we need to divide transition to several steps.
1. Migration to typescript. react-native-codegen(part of new architecture) requires type definitions for the native components and modules. These definitions can be written in Flowtype or typescript. Given that Flowtype doesn't have much support in open source community, typescript will be best solution.
2. Implement [prerequisites](https://reactnative.dev/docs/new-architecture-library-intro) for new architecture adoption. It's critical to not break functionality for apps running on old architecture.
3. Gradual implementation of Map Providers on different platforms. That way we can ship at least partial functionality of the application on new architecture, with full support on later stages.

### Code sample

For the sake of learning new architecture in details i have created experimental [branch](https://github.com/michbil/react-native-maps/commits/feature/new-architecture-exp) of the react-native-maps. I did partial conversion to typescript(some JS parts are still broken). Then generated specs for iOS AirMap and AirMapMarker and partially implemented native code for these two components. What's working now: on iOS: map display, default marker display, some event handlers, some camera control commands.
This is by no means ready to become PR at this stage, but can be used as demo and sandbox for implementing new architecture.

[![Watch the video](https://img.youtube.com/vi/Myze0hRJ7VU/maxresdefault.jpg)](https://youtu.be/Myze0hRJ7VU)

Question to maintainers: what are you thoughts on typescript conversion and later adoption Fabric?

**Comment by Simon-TechForm** [comment]
hi @michbil 👋 I appreciate you taking the time to put this together. Would you mind commenting on #4156 instead? :)

PS. I recently migrated the entire library to TS, which will be released soon. Check out the beta branch.
