### ISSUE TITLE
Overflow from marker in Android.

### ISSUE THREAD

**Issue by marcoburrometo** [react-native-maps/react-native-maps#4315]
### Summary

Hello all!
I'm trying to do a “pulsating” effect inside a custom marker, so I created an animation with react-native-reanimated-2 for this bubble and put an animated view inside of it.

On iOS, it's working superb, but in Android I have the problem that this “bubble” is not going outside the marker. I also tried to put overflow visible style but with no luck.

Here's the code, but I don't think it's related to the animation, even if I put a single position absolute view it's not overflowing in Android.

Can you help me?

### Reproducible sample code

```TSX
const ring = useSharedValue(0);

useEffect(() => {
    ring.value = withDelay( 
      1,
      withRepeat(
        withTiming(1, {
          duration: 4000,
        }),
        -1,
        false,
      ),
    );
  }, []);
  const ringStyle = useAnimatedStyle(() => {
    return {
      opacity: 0.8 - ring.value,
      transform: [
        {
          // TODO: interpolate value based on distance
          scale: interpolate(ring.value, [0, 1], [0, 10]),
        },
      ],
    };
  });
  
  <Marker
      tracksViewChanges={!loaded}
      coordinate={{
        latitude: user.location._latitude,
        longitude: user.location._longitude,
      }}>
      <Image
        source={....}
      />
      <View style={styles.markerDot} />
      <Animated.View style={ringStyle} />
    </Marker>
```

### Steps to reproduce

Try with android

### Expected result

Same as ios

### Actual result

Not overflowing

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.67.2

### What version of Expo are you using?

Not using Expo

### Device(s)

All the devices

**Comment by Simon-TechForm** [comment]
hi @marcoburrometo 👋 Since you already tried doing this without the animation, could you trim down your sample code to be as minimal as possible, and make sure to include your styles and entire render tree? That will make it quite a bit easier to troubleshoot and determine whether this is caused by `react-native-maps` or not :)

**Comment by marcoburrometo** [comment]
> hi @marcoburrometo 👋 Since you already tried doing this without the animation, could you trim down your sample code to be as minimal as possible, and make sure to include your styles and entire render tree? That will make it quite a bit easier to troubleshoot and determine whether this is caused by `react-native-maps` or not :)

Sure, here's a minimum example:
```

import React from 'react';
import { Image, View } from 'react-native';
import MapView, { Marker } from 'react-native-maps';

function MapScreen() {
  return (
    <MapView
      initialRegion={{
        latitude: 45,
        longitude: 45,
        latitudeDelta: 0.08,
        longitudeDelta: 0.075,
      }}
      onRegionChangeComplete={region => {
        console.log('region changed', region);
      }}
      style={{ flex: 1 }}>
      <Marker
        coordinate={{
          latitude: 45,
          longitude: 45,
        }}>
        {/* Marker image */}
        <Image
          source={{
            uri: 'https://www.studiofrancesconi.com/wp-content/uploads/2019/03/placeholder-profile-sq.jpg',
          }}
          style={{
            height: 30,
            width: 30,
            borderWidth: 2,
            borderColor: '#fff',
            borderRadius: 15,
          }}
        />
        <View
          style={{
            position: 'absolute',
            width: 300,
            height: 300,
            borderRadius: 150,
            backgroundColor: '#fffc',
            zIndex: 10000,
          }}
        />
      </Marker>
    </MapView>
  );
}

export default MapScreen;

```

**Comment by Simon-TechForm** [comment]
Did you test that the performance drops are caused by moving your custom marker into a single parent, or are you experiencing bad performance in general when adding many markers on Android? If it's the latter I believe that it is out of the scope of this issue :)
