### ISSUE TITLE
(Expo) Ram memory increased after reload metro

### ISSUE THREAD

**Issue by 1997roylee** [react-native-maps/react-native-maps#4318]
### Summary

The ram is significantly increased when I reload the expo app, I dont know reason. I think the mapview doesnt unmount after refreshed.

### Reproducible sample code

1. First, the ram is 300MB

![螢幕截圖 2022-07-17 上午2 56 45](https://user-images.githubusercontent.com/53046899/179368549-28d6bbf6-c4ee-41f4-95ef-a90fc0d652fd.png)

2. After I reload the metro, the ram is increased to 400MB

![螢幕截圖 2022-07-17 上午2 57 16](https://user-images.githubusercontent.com/53046899/179368578-aaecffbf-003c-4381-8a79-2169724475f4.png)

### Steps to reproduce

Reload the map on expo app

### Expected result

Ram is same

### Actual result

Ram is increased

### React Native Maps Version

1.0.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

iPhone 11 Pro simulator

### Additional information

**Comment by Simon-TechForm** [comment]
What does "reload" mean in this context? Are you hot reloading from JS. Are you conditionally rendering the component? Are you navigation back and forth in your react-navigation navigators? :)

Your reproducible sample code doesn't contain anything regarding "reloading", so any change you could provide a specific code snippet or snack reproducing the issue? Also, how are you tracking the ram usage? :)

**Comment by 1997roylee** [comment]
Sure man. The app is hot reloading from JS. I track the ram with perofrmance monitor. I toggle reload via expo cli each time, the number of ram is increased.

**Comment by 1997roylee** [comment]
> What does "reload" mean in this context? Are you hot reloading from JS. Are you conditionally rendering the component? Are you navigation back and forth in your react-navigation navigators? :)
> 
> Your reproducible sample code doesn't contain anything regarding "reloading", so any change you could provide a specific code snippet or snack reproducing the issue? Also, how are you tracking the ram usage? :)

I updated the reproduce, how could I solve this issue?

**Comment by Simon-TechForm** [comment]
Unfortunately I'm unable to reproduce this - tried with both the react-native-maps that expo installs and with the latest version. Ram usage stays at ~220mb even after multiple reloads done as you described.

Are you reproducing this in a clean project?

**Comment by Simon-TechForm** [comment]
I didn't since your reproducible sample code indicated that the issue is reproducible in a clean project.

**Comment by FadiAboMsalam** [comment]
@1997roylee @Simon-TechForm  I am facing same issue in stack navigator once i enter the stack with only map view the memory increase when i go out and come back again it increases more as well.
 there is an issue for sure with stack navigator

**Comment by FadiAboMsalam** [comment]
am using "react-native-maps": "^1.3.1", and  "react-native-screens": "3.13.1",  "@react-navigation/bottom-tabs": "^6.3.1", "@react-navigation/native": "^6.0.10", "@react-navigation/native-stack": "^6.6.1",

am not using expo

**Comment by FadiAboMsalam** [comment]
why was this closed 🤔
