### ISSUE TITLE
Missing action typing for MapPressEvent

### ISSUE THREAD

**Issue by felix4321** [react-native-maps/react-native-maps#4320]
### Summary

The action attribute of type MapPressEvent can have the value 'marker-press' if using the google provider for iOS. If you press a marker in iOS with google provider, both functions (onPress and onMarkerPress) are called. If you press a marker, onPress is called with the action argument 'marker-press'.

```
export declare type MapPressEvent = ClickEvent<{
    /**
     * @platform Android
     */
    action?: 'press';
}>;
```

### Reproducible sample code

```TSX
<MapView
    onPress={onMapPress}
    onMarkerPress={onMarkerPress}
    ...
/>
```

### Steps to reproduce

Add a marker to MapView while using google provider for iOS. If you press the marker, you see an MapPressEvent with 'marker-press' as action argument.

### Expected result

I don't know, if more action types are possible. At least you should add the type 'marker-press'.

```
export declare type MapPressEvent = ClickEvent<{
    /**
     * @platform Android
     */
    action?: 'press' | 'marker-press';
}>;
```

### Actual result

I get a typescript error, when I check the MapPressEvent for the 'marker-press' action, because it's not part of the type.

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone SE

**Comment by Simon-TechForm** [comment]
Hi @felix4321 👋.
Thank you for bringing this up. Would you be up for opening a PR? :)

**Comment by felix4321** [comment]
@BasBuur I think you know already the (hacky, but working) quick fix for the problem. But if not:

```
const onMapPress = (event: MapEvent) => {
    if (event.nativeEvent.action !== 'marker-press') {
      ...
    }
  };
```

Of course it would be great, if onMapPress is not called, if pressing a marker. But I have no idea, how to fix this...

**Comment by felix4321** [comment]
@Simon-TechForm I can create a PR for adding the 'marker-press' action to the typings. But I can't fix the issue, that onMapPress should not be called.

**Comment by Simon-TechForm** [comment]
@felix4321 that would be great :) Fixing the typings is a good place to start, and then hopefully at some point, someone has the time to look into the onPress behaviour in general :)

**Comment by SannUA** [comment]
The same problem seems to be with 'polyline-press'. We need to add this action to the typings as well.
