### ISSUE TITLE
initialCamera crashes iOS with google provider [__NSMallocBlock__ zoom]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by felix4321** [react-native-maps/react-native-maps#4321]
### Summary

With react-native-maps@0.31.0 initialCamera works in iOS and google provider.
With react-native-maps@1.0.0 the app crashes in iOS and google provider.
Using android and google provider works without any problems.

Error:
`[__NSMallocBlock__ zoom]: unrecognized selector sent to instance 0x280881bc0`

Further logs can be found in the end.

### Reproducible sample code

```TSX
<MapView
    provider={PROVIDER_GOOGLE}
    initialCamera={{
        altitude: 0,
        center: { latitude: 52.509266, longitude: 13.397118 },
        heading: 0,
        pitch: 0,
        zoom: 11,
    }}
/>
```

### Steps to reproduce

Use sample code above on an iOS device.

### Expected result

App should not crash when using initialCamera für iOS (google maps).

### Actual result

App crashes.

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone SE

### Additional information

```
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSMallocBlock__ zoom]: unrecognized selector sent to instance 0x280881bc0'
2022-07-13 13:42:47.925296+0200 appname[90119:1491728] -[__NSMallocBlock__ zoom]: unrecognized selector sent to instance 0x280881bc0
2022-07-13 13:42:47.925930+0200 appname[90119:1491728] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSMallocBlock__ zoom]: unrecognized selector sent to instance 0x280881bc0'
*** First throw call stack:
(0x18148bd0c 0x198c7cee4 0x18155c750 0x18142560c 0x18142481c 0x104eafae8 0x104eb3cb8 0x104da2a94 0x1838adebc 0x184f2c9f4 0x184f1f768 0x184f33190 0x184f3bc64 0x184f1ee94 0x18143782c 0x181408a64 0x181403fec 0x181417240 0x1a1ee7988 0x183c1741c 0x1839b0b88 0x10439104c 0x1087843d0)
libc++abi: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by Simon-TechForm** [comment]
I'm able to reproduce this. I will look into it and get back to you :)

**Comment by Simon-TechForm** [comment]
Quick status report and notes for myself and others who might look into this:

`_initialCamera` is being deallocated before being accessed in `layoutSubviews`.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/73996878/179281778-99c1056e-29fa-48cf-b3d9-5b321c38004d.png">

This is happening in `v1.0.0-beta.1`, so should be introduced here https://github.com/react-native-maps/react-native-maps/compare/v0.31.1...v1.0.0-beta.1
I haven't had the time to figure out why this is happening yet.

**Comment by Simon-TechForm** [comment]
Hi guys. I've just released `v1.0.1` that should fix the issue. Could you test it out and report back to me?

**Comment by felix4321** [comment]
@Simon-TechForm Yeah, thx! :) Works perfectly now.

**Comment by lukeinage** [comment]
Yes all good, thanks for the quick fix!
