### ISSUE TITLE
Geojson Should allow for `tracksViewChanges` to be set on custom markers

### ISSUE THREAD

**Issue by jcuffney** [react-native-maps/react-native-maps#4337]
### Summary

With data in a GeoJSON format, if you have thousands of markers performance degrades very quickly.  Allowing for setting the `tracksViewChanges` property via the `Geojson` component might help improve the overall performance while using the GeoJSON component.

### Reproducible sample code

```TSX
<Geojson
  geojson={GEOJSON}
  onPress={handleMarkerSelect}
  markerComponent={
    <Image source={require("../../assets/imgs/marker.png")} />
  } />
```

### Steps to reproduce

Render a `Geojson` component with many "points"

### Expected result

The map should work without severe performance degredation.

### Actual result

the map is rendered unusable and freezes indefinitely (tested on android)

### React Native Maps Version

0.32.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

Google Pixel 6

### Additional information

Are there any other things that can be done short of removing some markers to improve performance with many markers? Seems like this might be a fairly common use case.

**Comment by Simon-TechForm** [comment]
Hi @jcuffney 👋. Sounds reasonable. How would you expect this to behave? A single prop that controls `tracksViewChanges` for all markers?

**Comment by jcuffney** [comment]
@Simon-TechForm  I think the single prop on `<Geojson />` would solve the performance related issues for most cases...but I think a better solution would be to have a combination of the single prop as the "default" value to be used for all markers, but allow that value to be overridden by the value of `properties.tracksViewChange` within the geoJSON so it can also be driven by the data.  That way if for some reason someone needed to track view changes for some markers but not others - it would be possible to do so.

**Comment by Simon-TechForm** [comment]
@jcuffney I agree that being able to specify the prop for each individual marker would be optimal.

Would you be up for taking on the task of a PR? If so, I'll be happy to review and merge once it's done. Implemeting the default prop for all markers should be quite simple, while doing it for each individual marker might be as well, but would at least require extending the type we use from `@types/geojson.`

**Comment by jcuffney** [comment]
@Simon-TechForm sure I can have a go at a PR - I just opened a, initial pass #4347  but might need a little more info on how you'd expect to extend the geojson types to work.

Would this just extend the `FeatureCollection` type to include `tracksViewChanges`?

**Comment by Simon-TechForm** [comment]
@jcuffney Exactly. I was under the impression that data like this would normally be added as a foreign member, which would also allow us to type it, instead of relying on the any type in `properties`. But having had a look at other implementations, using the `properties` member seems totally viable, so I'm happy with the solution in your PR. Besides, since we are dealing with JSON, the geojson prop is most likely to be passed an any type either way.

Lets continue the discussion in the PR 👍
