### ISSUE TITLE
Map always shows Africa for a second before going to my initial region

### ISSUE THREAD

**Issue by vadimluminous** [react-native-maps/react-native-maps#4343]
### Summary

As the title says, my map always shows Africa before it goes to my initial location.

### Reproducible sample code

```TSX
<MapView
	initialRegion={region}
	provider={PROVIDER_GOOGLE}
	showsUserLocation
	style={styles.map}></MapView>`


const region = {
    "latitude": 34.0522,
    "longitude": -118.2437,
    "latitudeDelta": 0.009,
    "longitudeDelta": 0.01
}
```

### Steps to reproduce

Code shows steps

### Expected result

My map should go directly to my initialRegion

### Actual result

It instead goes to Africa

### React Native Maps Version

0.30.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

Android 11

**Comment by Simon-TechForm** [comment]
hi @vadimluminous 👋.

This issue was fixed in [v0.31.0](https://github.com/react-native-maps/react-native-maps/releases/tag/v0.31.0) :)
