### ISSUE TITLE
App crash when rerender:  Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

### ISSUE THREAD

**Issue by schriker** [react-native-maps/react-native-maps#4351]
### Summary

I'm trying to build a map with clustering. At first, render everything works fine, but as soon as a user tries to move map or zoom, I'm recalculating markers/clusters postions, and app breaks on iOS with error: Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

![Simulator Screen Shot - iPhone 13 - 2022-07-24 at 14 28 39](https://user-images.githubusercontent.com/28902144/180647938-2b1b1f63-a78c-4159-9cbe-db58e9e7174a.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-24 at 14 29 10](https://user-images.githubusercontent.com/28902144/180647948-1c848a9e-a74e-44c2-8841-ada3f2193291.png)

### Reproducible sample code

```TSX
export const Map: React.FunctionComponent = () => {
    const { styles } = useStyles(stylesheet)
    const mapData = useMapData()
    const [region, setRegion] = useState<Region>(INITIAL_REGION)
    const [, setZoomLevel] = useState(0)
    const [points] = useClusterer(mapData, MAP_DIMENSIONS, region, {
        maxZoom: 15,
        radius: 20,
        minPoints: 5,
    })

    const handleRegionChange = async (newRegion: Region) => {
        setRegion(newRegion)
        setZoomLevel(Math.log2(360 * ((Measurements.WindowWidth / 256) / region.longitudeDelta)) + 1)
    }

    return (
        <MapView
            style={styles.map}
            provider={PROVIDER_GOOGLE}
            initialRegion={INITIAL_REGION}
            onRegionChangeComplete={handleRegionChange}
        >
            {points.map(item => (
                <Point
                    key={item.properties?.cluster_id ?? `point-${item.properties?.id}`}
                    item={item}
                />
            ))}
        </MapView>
    )
}
```

### Steps to reproduce

1. View map
2. Zoom in and move

### Expected result

I would expect to rerender map markers without crashing.

### Actual result

App crash

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 (15.5)

**Comment by schriker** [comment]
Uploading Simulator Screen Recording - iPhone 13 - 2022-07-24 at 16.08.55.mp4…

**Comment by schriker** [comment]
https://user-images.githubusercontent.com/28902144/180651000-5fc80507-7ba5-45e8-a89f-0625de96af23.mp4

**Comment by Simon-TechForm** [comment]
Hi @schriker 👋. Thank you for reporting this. Can I have you trim down the sample code to exclude anything not related to reproducing the issue, and include everything needed to run it as is? :) I can't run your custom hooks etc. :)

**Comment by hi-kuldeep** [comment]
same issue here

**Comment by schriker** [comment]
I use Markers with childrens for this cluster markers with numbers, if I change them to regular markers the App doesn't crash. It looks like iOS have some problems with rendering markers with childrens?

**Comment by schriker** [comment]
Ok, it looks like in my case using Animated.View with layout animation caused this issue, after removing it everything works fine.

Code that caused this problem:

    return (
        <Animated.View
            style={{
                ...styles.wrapper,
                ...containerStyles
            }}
            exiting={FadeOut.duration(200)}
        >
            {children}
        </Animated.View>
    )

**Comment by Simon-TechForm** [comment]
I'm glad you got it working 👍

**Comment by Akash-Hubspire** [comment]
I have the same issue, when Marker has children in it. 
I want to render a custom marker with Text and icon in it.

This is how my code looks like:
```
<MapView
        initialRegion={INITIAL_REGION}
        style={{ flex: 1 }}
        provider={PROVIDER_GOOGLE}>
        {eventLocations?.map((item, index) => {
          const [longitude, latitude] = item.location.coordinates;
          return (
            <Marker coordinate={{ latitude, longitude }}>
              <RenderSvg
                xml={svg.currentLocationMarker}
                width={42}
                height={42}
              />
              <Text>{item?.category}</Text>
            </Marker>
          );
        })}
      </MapView>
```
The issue happens when i switch to another component in the same screen after the map is loaded.

When i remove the children from the marker, it works fine. 
When i remove `provider={PROVIDER_GOOGLE}` it works fine, even if there is children in the Marker.
I'm not using `Animated` anywhere in the screen.

**Comment by hi-kuldeep** [comment]
i got the same problem and i did not find any solution so i used apple map
in ios instead google map

**Comment by Akash-Hubspire** [comment]
> 

I also had to use apple map in my project

**Comment by ravindraguptacapgemini** [comment]
@Akash-Hubspire have you found a fix for the issue, getting exactly the same issue.

**Comment by ravindraguptacapgemini** [comment]
@Simon-TechForm Please reopen the issue, please
