### ISSUE TITLE
Tslint issues with the latest version 1.1.0

### ISSUE THREAD

**Issue by Nehal-Sanklecha** [react-native-maps/react-native-maps#4355]
### Summary

The app throws tslint issues on the update of the package to the latest version. 
Error: for all the built-in and user-defined components it shows **JSX tag can't be used.**
It happens across all the files of the project.

### Reproducible sample code

```TSX
<MapView
                moveOnMarkerPress={true}
                showsIndoors={false}
                cacheEnabled={true}
                testID={"map_component.map_view"}
                provider={PROVIDER_GOOGLE}
                style={styles.map}
                mapPadding={this.props.mapPadding}
                initialRegion={this.getInitialRegion()}
                ref={(ref) => this.mapRef = ref}
                onMapReady={this.onMapLayout}
            >
                {this.renderMarkers()}
            </MapView>

private renderMarkers = () => {
        return this.props.markers.map((marker, index) => {
            return (
                <CustomMarker
                    id={marker.id}
                    coordinate={marker.coordinate}
                    key={`${marker.label}${marker.coordinate.longitude}${marker.coordinate.latitude}`}
                    variant={marker.variant}
                    label={marker.label}
                    isActive={true}
                    zIndex={index}
                />
            );
        });
    }
```

### Steps to reproduce

   
I'm able to render Map but tslint gets fail

### Expected result

Tslint script should work without giving any error

### Actual result

Tslint fails

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.67.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 (15.2)

### Additional information

"react-native-maps": "^1.1.0",
    "tslint": "^5.11.0",
    "typescript": "^4.7.2"
    "react-native": "0.67.4",
    "react": "17.0.2",

**Comment by Simon-TechForm** [comment]
hi @Nehal-Sanklecha 👋

tslint was [deprecated](https://github.com/palantir/tslint/issues/4534) in 2019, so I would recommend migrating to eslint + typescript-eslint which works very nicely with `react-native-maps` 👍
