### ISSUE TITLE
@react-native-community/blur not work on Android

### ISSUE THREAD

**Issue by nicolasdevienne** [react-native-maps/react-native-maps#4356]
### Summary

@react-native-community/blur not works on Android :

![Screenshot_1658939028](https://user-images.githubusercontent.com/65358122/181299309-1688489a-519f-4e9d-ab6b-e486cd6099eb.png)

Whereas it works on iOS :

![Simulator Screen Shot - iPhone 13 mini - 2022-07-27 at 18 23 46](https://user-images.githubusercontent.com/65358122/181299323-498f5f4c-3551-4fd5-b5ba-f1bf4cc8b9d1.png)

### Reproducible sample code

```TSX
<View style={{ flex: 1 }}>
<MapView style={StyleSheet.absoluteFill} />
<BlurView style={StyleSheet.absoluteFill} />
</View>
```

### Steps to reproduce

Simple copy/past the code and run in emulator

### Expected result

Map blurred like on iOS

### Actual result

Map is not blurred

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.66.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 5

### Additional information

Version of @react-native-community/blur is the last : 4.1.0

**Comment by Simon-TechForm** [comment]
hi @nicolasdevienne 👋

I believe this issue should be opened in the @react-native-community/blur repo instead :)

**Comment by karel-suchomel-ed** [comment]
@nicolasdevienne Did you find a solution? Experiencing the same issue. @react-native-community/blur
