### ISSUE TITLE
No support for modern Google Maps Platform styling

### ISSUE THREAD

**Issue by go-sean-go** [react-native-maps/react-native-maps#4361]
### Summary

This is a dupe of https://github.com/react-native-maps/react-native-maps/issues/3713 - which was closed by a bot, but should really be re-opened.

In summary, for custom map styling, this library only supports JSON styling - but Google appears to have deprecated this entirely. Now, Google wants styling done via its cloud console & Map IDs.

Per https://github.com/react-native-maps/react-native-maps/issues/3713, this appears to be fully exposed by their client SDKs (for a couple years now), so it should just be a matter of passing the props around?

Also I see no reason to remove JSON support on the client; this would just be an additive, new param/prop, a la `MapView.customMapStyleId()` or similar (leaving `MapView.customMapStyle()` in-place as-is?).

The Readme itself points to the Google page that explains the deprecation, here: https://mapstyle.withgoogle.com/

<img width="1557" alt="Screen Shot 2022-07-29 at 2 00 24 PM" src="https://user-images.githubusercontent.com/55253273/181842412-12ce3e9f-0112-4fe3-a46d-8a12f16d8a33.png">

More info from Google on why this is important (2-year-old blog post): https://cloud.google.com/blog/products/maps-platform/introducing-new-maps-customization-features

### Reproducible sample code

```TSX
return (
    <MapView
      provider={PROVIDER_GOOGLE}
      customMapStyle={GoogleMapsPlatformMapId}
    </MapView>
  );

// Type 'string' is not assignable to type 'MapStyleElement[]'.ts(2322)
```

### Steps to reproduce

Try to create a modern Map style with Google's supported & current tools, and then try to load that style on `react-native-maps`.

### Expected result

`react-native-maps` should support modern Google map styles.

### Actual result

`react-native-maps` does not support modern Google map styles.

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.2

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 Pro

### Additional information

Again, this is effectively a dupe of: https://github.com/react-native-maps/react-native-maps/issues/3713

More useful info could be in that thread.

**Comment by Simon-TechForm** [comment]
Reopened #3713 :)
