### ISSUE TITLE
Apple Maps doesn't show directional indicator

### ISSUE THREAD

**Issue by JackFord18** [react-native-maps/react-native-maps#4362]
### Summary

When using Expo and Apple Maps on iOS, the directional indicator for the current location dot is not displayed in the MapView. This is inconsistent from the Google Maps MapView variant and regular Apple Maps app, which does show the directional indicator.

Apple Maps in React Native Maps MapView (does not indicate direction to user):
![appleMapsReactNativeMaps](https://user-images.githubusercontent.com/47796906/182075252-1ce6440f-2e84-4536-8ab3-f9ff1dd36036.jpg)

Apple Maps regularly (i.e. just opening the Apple Maps app on my phone, indicates direction to user as shown via red circle)
![appleMapsRegular](https://user-images.githubusercontent.com/47796906/182075254-751a4043-b6f2-4b12-8168-eadb8eb38249.jpg)

### Reproducible sample code

```TSX
import { StyleSheet, Text, View, Dimensions } from "react-native";
import { useEffect, useState } from "react";
import MapView from "react-native-maps";
import * as Location from "expo-location";
import { Magnetometer } from "expo-sensors";

import ActivityIndicator from "../components/common/ActivityIndicator";
import AnimatedLottieView from "lottie-react-native";

export default function HomeScreen(props) {
  const [markers, setMarkers] = useState([]);
  const [location, setLocation] = useState(null);
  const [showLocation, setShowLocation] = useState(false);

  useEffect(() => {
    requestPermissions();
  }, []);

  const requestPermissions = async () => {
    let { status } = await Location.requestForegroundPermissionsAsync();

    if (status !== "granted") {
      setErrorMsg("Permission to access location was denied");
      return;
    }

    let location = await Location.getCurrentPositionAsync();
    if (!location) {
      return;
    }
    setLocation(location);
    setShowLocation(true);
  };
  return (
    <View style={styles.container}>
      <MapView
      provider
        region={{
          latitude: location ? location.coords.latitude : 0,
          longitude: location ? location.coords.longitude : 0,
          latitudeDelta: location ? 0.1 : 5,
          longitudeDelta: location ? 0.1 : 5,
        }}
        showsCompass={true}
        showsUserLocation={showLocation}
        followsUserLocation={false}
        style={styles.map}
      />
      {!location && (
        <ActivityIndicator
          source={require("../assets/animations/location-animation.json")}
          message={"Finding location..."}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {height: "100%",backgroundColor: "#fff",alignItems: "center",justifyContent: "center",},
  map: {width: "100%",height: "100%",
  },
});
```

### Steps to reproduce

Start the expo app with the provided MapView configuration

### Expected result

I expected the project to behave with the standard Apple Maps behavior and look- including displaying a directional cone/indicator to show the user which direction their phone is facing/they are moving (circled in red).
![appleMapsRegular](https://user-images.githubusercontent.com/47796906/182075770-061992f7-29df-4dcb-b6f1-ff3bcbb36a6a.jpg)

### Actual result

The current location point only shows an accuracy ring and no indicator of which direction the user is facing.
![appleMapsReactNativeMaps](https://user-images.githubusercontent.com/47796906/182075802-ca48ef41-a7f7-4f9f-86eb-abc2747d924f.jpg)

### React Native Maps Version

0.30.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

iPhone 12 Pro Max

### Additional information

A directional indicator is shown when using Google Maps instead of Apple Maps, shown here:  
![thumbnail_Image](https://user-images.githubusercontent.com/47796906/182076475-ced9836c-63b5-4f5e-9a3f-0f01ff01de47.jpg)

**Comment by Simon-TechForm** [comment]
The state of this is unfortunately unchanged since #3905.

**Comment by WayneKim92** [comment]
If you need this, use [it](https://www.npmjs.com/package/react-native-maps-my-location-direction).
