### ISSUE TITLE
Blank map on Android, only on some screens, after upgrading to 1.0.0

### ISSUE THREAD

**Issue by gabriellend** [react-native-maps/react-native-maps#4364]
### Summary
**2/2/2023 EDIT**
I opened another issue [here](https://github.com/react-native-maps/react-native-maps/issues/4593#issue-1553983932) about the Android zooming misbehavior and I believe I found a fix. All that is left are the flashing icons and bold text of the map (both only on Android). I will finish updating my react-native/react versions to see if that helps and for now I will close this issue. I know it's a monster. For anyone just seeing this experiencing the same issue(s), my suggestions would be to read the documentation thoroughly, with a fine tune comb, triple check you are using everything they recommend (especially the new renderer), update to Ventura if you are using a mac, and check if you have any Android specific `edgePadding`. Signing off for now!

**1/19/23 EDIT**
The slow loading and crashing on an iOS simulator was fixed by upgrading to macOS Ventura 13.1 (but I bet 13 would also work, I was running Monterrey 12.5 before). Also can try updating XCode to 14.2 but I don't really think that had anything to do with it(but can't be sure). The weird Android behavior is still happening where it doesn't initially zoom to fit the coordinates (except sometimes it does, ha), and the icons are still flashing. So, still working on that.

**12/22/22 EDIT:**
@Simon-TechForm It's a Christmas miracle! :D I stumbled upon the `edgePadding` option in `fitToCoordinates` and I'm optimistic this is the key to this issue! We had some specific `edgePadding` for Android and when I took that away, the maps seems to be centering properly on all devices/emulators/simulators. Don't close yet as I still need to do some testing because the map on an iOS simulator is still very slow/some icons flash on Android/sometimes it doesn't center properly in certain edge cases. But all in all, a MAJOR step forward. In all my combing of the docs/releases, I didn't see any changes to `edgePadding` so I'm curious what happened there. I found [this](https://github.com/react-native-maps/react-native-maps/issues/3308#issue-571612776) issue that mentions it but it was a bit over my head so didn't quite glean if that was it. I'm going to sign off for the holiday for now but wanted to post this in case it could help anyone. I'm cautiously ecstatic as this has been a thorn in my side for almost 5 months!

**11/7/22 EDIT:**
After updating my Kotlin version to 1.6.0 in my build.gradle file (needed to do it to solve an error coming from another dependency), we are now back to where we were on an emulator, with 1/3 screens working on Android. On a physical device, all screens work but are zoomed out to Africa. I have some luck setting initialRegion on 2/3 of those screens but I didn't need to set that before in order for the maps to work(I'm calling fitToCoordinates) and I can't get it to work on the one that matters the most, where real-time tracking is happening.

**11/3/22 EDIT:**
I have upgraded to 1.3.2 and updated Google Play Services (I didn't understand what that was before and thought because I had the Google Play app I was fine). Results were the same. Then I tried enabling the new Google Maps renderer and progress! All maps are showing up now in Android but they are way zoomed out on Africa. Everything works awesome on a physical ios device. An ios simulator takes a really long time to display the map, like 15-20 seconds, and sometimes crashes.

**8/23/22 EDIT:**
Without changing anything, I tried again today with 1.0.0 and the map showed up on 2/3 of the screens, up from 1/3. So, progress. I then upgraded to 1.3.0 with the same results. However, the third screen is still blank.

Hello!

I don't know that this is a bug report, it was the only option though. No one else seems to be having this issue so I bet it's something small I've overlooked. I'm upgrading an app from 0.28.0 to 1.0.0. It worked fine before but now on Android the map is blank (with a google logo) on 2/3 of the screens I use it on. On the screen it is rendering on, it isn't showing the correct region. I read through the changelogs and the installation process and I did see that some things have changed for 0.31.0 and above. I tried the suggestions and also the troubleshooting, but nothing has helped. It's working on iOS okay, though it does take like 10-15 seconds to load, which is atypical. Here is the result when I `adb logcat` "Google Maps Android API":

<img width="833" alt="Screen Shot 2022-08-02 at 4 09 02 PM" src="https://user-images.githubusercontent.com/81834841/182707289-d5c6bebd-48bc-44b6-aa49-82986f8ae13e.png">

I am importing like this:
`import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';`

**8/23/22 EDIT: This screen is now rendering. The view is a little far away but at least I can see it.**
Here are the MapView props and a screenshot for one of the screens not rendering:
```
<MapView
  ref={(ref) => { this.mapRef = ref; }}
  moveOnMarkerPress={false}
  onMapReady={() => this.onMapLayout()}
  style={{ ...Layouts.container, width: StyleConfig.width, height: StyleConfig.height }}
  customMapStyle={MAP_STYLES}
  provider={PROVIDER_GOOGLE}
  showsIndoors={false}
  >
  {markers}
</MapView>
```
<img width="232" alt="Screen Shot 2022-08-03 at 12 03 03 PM" src="https://user-images.githubusercontent.com/81834841/182720622-2febe76e-1623-4a1b-83ca-abd50a13a759.png">

Here is what it should look like:
<img width="292" alt="Screen Shot 2022-08-03 at 12 19 35 PM" src="https://user-images.githubusercontent.com/81834841/182722452-439f281d-bd51-4df6-8ae2-691abe30c0d5.png">

**8/23/22 EDIT: This screen is now rendering better, at least in the right geographical region, the points are still somewhat offscreen, but it's better.**
Here is the code and screenshot for the screen that is rendering, with wrong view (the user location and drop point is working, it's just offscreen):
```
<MapView
  ref={(ref) => { this.mapRef = ref; }}
  onLayout={() => {
    this.mapRef.fitToCoordinates(
      [userCoordinates,
        dropPointLocation],
      {
        edgePadding: this.generateEdgePadding(styles.edgePadding),
        animated: false,
      },
    );
  }}
  style={[styles.map, { ...Layouts.container }]}
  customMapStyle={MAP_STYLES}
  provider={PROVIDER_GOOGLE}
  showsIndoors={false}
  mapPadding={{ bottom: 50, left: 15 }}
>
```
<img width="268" alt="Screen Shot 2022-08-03 at 1 03 03 PM" src="https://user-images.githubusercontent.com/81834841/182727266-0594b886-08d3-4241-a608-c5b925a29f12.png">

Here is what it should look like:
<img width="305" alt="Screen Shot 2022-08-03 at 12 23 40 PM" src="https://user-images.githubusercontent.com/81834841/182723319-e02c4f46-19a3-4281-b60a-3c9b7c282e5f.png">

I tried using `onLayout` instead of `onMapReady` in the first instance, but that just led to a never-ending loading screen.

### Reproducible sample code

```TSX
Other than the above, I can't provide a reproducible example in this case, I'm sorry, the codebase is just so large, not even sure where to start.
```

### Steps to reproduce

Same as above, I know this is not helpful. It is working 1/3 times so not sure what needs to be tweaked in order for it to work/not work.

### Expected result

The map should be rendered with user location and drop points on the first screen.

### Actual result

The map is blank, except for the google logo.

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.67.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Galaxy S9 physical device, Android 12, and Galaxy S21 emulator, Android 12

### Additional information

Just that I'm grateful for anyone's time and help with this. It's not my best GitHub issue, not sure what else would be helpful to include.

**Comment by BrodaNoel** [comment]
That's kind of weird. I'm having the same problem.

My problem is that `onMapReady` is not being called on `iOS`. Not even once.

I'm having this problem after upgrading from Expo SDK 44 to SDK 46 (I made 2 jumps in 1 day).

**Comment by gabriellend** [comment]
@BrodaNoel I was having that issue with react-native-maps 0.31.0 (not sure if that correlates to one of the SDKs you mentioned) and saw there was a fix in one of the 1.0.0 betas, so that's why I upgraded to 1.0.0.

**Comment by BrodaNoel** [comment]
I'm using `0.31.1`, because I'm using `Expo`, and that's the compatible version :(

**Comment by BrodaNoel** [comment]
Related: https://github.com/react-native-maps/react-native-maps/issues/4066

**Comment by Simon-TechForm** [comment]
> That's kind of weird. I'm having the same problem.
> 
> My problem is that `onMapReady` is not being called on `iOS`. Not even once.
> 
> I'm having this problem after upgrading from Expo SDK 44 to SDK 46 (I made 2 jumps in 1 day).
> 
> Related: https://github.com/react-native-maps/react-native-maps/issues/4066

@BrodaNoel `onMapReady` not being called is unrelated to this issue and was caused by the js prop being bridged too late :)

@gabriellend we use the Github Discussions section for anything not related to bugs, but until we determine whether this is a bug or not, I'm fine keeping this as an issue.

First of all, I appreciate you taking the time to fill out the issue template thoroughly.

`Other than the above, I can't provide a reproducible example in this case, I'm sorry, the codebase is just so large, not even sure where to start.` describes how I'm left after going through this issue 😄 Joking aside, would you be able to share the project code privately with me? (Since you painted over parts of the app, I assume that it isn't suitable for public sharing).

**Comment by gabriellend** [comment]
@Simon-TechForm Thank you so much for your response! Ok, noted about the GitHub Discussions, thank you, I'm still somewhat new at this stuff and haven't used that yet. Yes, this is for my job so I didn't think it prudent to share any identifying information publicly. I have asked my boss if it would be ok to share. I doubt he will be ok with sharing the whole project, as it's the intellectual property of the company (maybe I will be surprised), but maybe pertinent parts are okay. Will get back to you!

**Comment by gabriellend** [comment]
@Simon-TechForm I was given permission to share the parts of the code related to react-native-maps. I created a private repo with just those parts and shared it with you. A new development has happened. On iOS, if I make a small change in my editor, revert it back, and save, everything works fine. I have to do that each time I build it though so that's not feasible. This doesn't happen on Android though. Appreciate your time.

**Comment by SammonBabu** [comment]
> ### Summary
> Hello!
> 
> I don't know that this is a bug report, it was the only option though. No one else seems to be having this issue so I bet it's something small I've overlooked. I'm upgrading an app from 0.28.0 to 1.0.0. It worked fine before but now on Android the map is blank (with a google logo) on 2/3 of the screens I use it on. On the screen it is rendering on, it isn't showing the correct region. I read through the changelogs and the installation process and I did see that some things have changed for 0.31.0 and above. I tried the suggestions and also the troubleshooting, but nothing has helped. It's working on iOS okay, though it does take like 10-15 seconds to load, which is atypical. Here is the result when I `adb logcat` "Google Maps Android API":
> 
> <img alt="Screen Shot 2022-08-02 at 4 09 02 PM" width="833" src="https://user-images.githubusercontent.com/81834841/182707289-d5c6bebd-48bc-44b6-aa49-82986f8ae13e.png">
> 
> I am importing like this: `import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';`
> 
> Here are the MapView props and a screenshot for one of the screens not rendering:
> 
> ```
> <MapView
>   ref={(ref) => { this.mapRef = ref; }}
>   moveOnMarkerPress={false}
>   onMapReady={() => this.onMapLayout()}
>   style={{ ...Layouts.container, width: StyleConfig.width, height: StyleConfig.height }}
>   customMapStyle={MAP_STYLES}
>   provider={PROVIDER_GOOGLE}
>   showsIndoors={false}
>   >
>   {markers}
> </MapView>
> ```
> 
> <img alt="Screen Shot 2022-08-03 at 12 03 03 PM" width="232" src="https://user-images.githubusercontent.com/81834841/182720622-2febe76e-1623-4a1b-83ca-abd50a13a759.png">
> 
> Here is what it should look like: <img alt="Screen Shot 2022-08-03 at 12 19 35 PM" width="292" src="https://user-images.githubusercontent.com/81834841/182722452-439f281d-bd51-4df6-8ae2-691abe30c0d5.png">
> 
> Here is the code and screenshot for the screen that is rendering, with wrong view (the user location and drop point is working, it's just offscreen):
> 
> ```
> <MapView
>   ref={(ref) => { this.mapRef = ref; }}
>   onLayout={() => {
>     this.mapRef.fitToCoordinates(
>       [userCoordinates,
>         dropPointLocation],
>       {
>         edgePadding: this.generateEdgePadding(styles.edgePadding),
>         animated: false,
>       },
>     );
>   }}
>   style={[styles.map, { ...Layouts.container }]}
>   customMapStyle={MAP_STYLES}
>   provider={PROVIDER_GOOGLE}
>   showsIndoors={false}
>   mapPadding={{ bottom: 50, left: 15 }}
> >
> ```
> 
> <img alt="Screen Shot 2022-08-03 at 1 03 03 PM" width="268" src="https://user-images.githubusercontent.com/81834841/182727266-0594b886-08d3-4241-a608-c5b925a29f12.png">
> 
> Here is what it should look like: <img alt="Screen Shot 2022-08-03 at 12 23 40 PM" width="305" src="https://user-images.githubusercontent.com/81834841/182723319-e02c4f46-19a3-4281-b60a-3c9b7c282e5f.png">
> 
> I tried using `onLayout` instead of `onMapReady` in the first instance, but that just led to a never-ending loading screen.
> 
> ### Reproducible sample code
> ```tsx
> Other than the above, I can't provide a reproducible example in this case, I'm sorry, the codebase is just so large, not even sure where to start.
> ```
> 
> ### Steps to reproduce
> Same as above, I know this is not helpful. It is working 1/3 times so not sure what needs to be tweaked in order for it to work/not work.
> 
> ### Expected result
> The map should be rendered with user location and drop points on the first screen.
> 
> ### Actual result
> The map is blank, except for the google logo.
> 
> ### React Native Maps Version
> 1.0.0
> 
> ### What platforms are you seeing the problem on?
> Android
> 
> ### React Native Version
> 0.67.4
> 
> ### What version of Expo are you using?
> Not using Expo
> 
> ### Device(s)
> Galaxy S9 physical device, Android 12, and Galaxy S21 emulator, Android 12
> 
> ### Additional information
> Just that I'm grateful for anyone's time and help with this. It's not my best GitHub issue, not sure what else would be helpful to include.

I am having the same issue! It was loading before on android but its not working! Is there any solution?

**Comment by gabriellend** [comment]
@SammonBabu Is it working on any screens, or none? There is no solution yet. I just reverted back to 0.28.0 in the meantime.

**Comment by gabriellend** [comment]
@Simon-TechForm Update: I tried again today with the same version(1.0.0) and 2/3 of the screens worked, up from 1/3. I then upgraded to 1.3.0 with same results.

**Comment by Willham12** [comment]
The map rendering because you have the google logo.
try 
```js
style={StyleSheet.absoluteFill}

**Comment by pinpong** [comment]
I don't think that's an package related issue.
Log if u are using the new renderer.

**Comment by gabriellend** [comment]
@Willham12 Hey, thank you for your input. I will try that.
@pinpong Thank you as well, what do you mean by "Log if u are using the new renderer"?

**Comment by gabriellend** [comment]
> The map rendering because you have the google logo. try
> 
> ```js
> style={StyleSheet.absoluteFill}
> ```

I tried that on `MapView` in place of my styles but it didn't work. This is what my styles are in case it jogs anything:

```
{
  flex: 1
  width: 100%
}
```
And it is inside a View with `flex: 1`

My styles didn't change and the map was working before so it doesn't seem to me that it would be a style issue but I could be wrong.

**Comment by gabriellend** [comment]
Commenting to keep this open. I will try again this week and see what the status of things is.

**Comment by putuoka** [comment]
i think i got similar issue when try running example folder https://github.com/react-native-maps/react-native-maps/discussions/4534

**Comment by TheSilentHorizon** [comment]
So I thought i share my experience with that issue:

In my case the problem was indeed not using onMapReady - I called animateMapTo on componentDidMount which caused the Map weirdly only at expo 47 (in expo 45 it was working with componentDidMount fine) not to load - while the other one did.

**Comment by gabriellend** [comment]
@putuoka That does look like what's happening with mine. Is this happening on Android only?

**Comment by gabriellend** [comment]
@TheSilentHorizon Thanks for your comment! I am using `onMapReady` on one of the screens, I can't remember at this point if it's a working one or not. I will go back and try using it on all of the screens. I'm not using Expo but it's worth a try. Were you having the same issue of it working on some screens and not others? What about emulator verses physical device?

**Comment by putuoka** [comment]
> @putuoka That does look like what's happening with mine. Is this happening on Android only?

yes happen in android. i think the repo is outdate because i just copy from example folder and can't make it work also try to simple install and not working as well. that's make me to try rnmapsbox with openstreetmap free map without google api key

**Comment by TheSilentHorizon** [comment]
> @TheSilentHorizon Thanks for your comment! I am using `onMapReady` on one of the screens, I can't remember at this point if it's a working one or not. I will go back and try using it on all of the screens. I'm not using Expo but it's worth a try. Were you having the same issue of it working on some screens and not others? What about emulator verses physical device?

I had a screen where it was working and one that didnt, tested only on android, but same result on emulator and device.

**Comment by pierroo** [comment]
I am also facing that full grey map issue, on react-native 0.69.7, latest react-native-maps version.
The "onMapReady" event is triggered although nothing shows, I am clueless.

**Comment by vinaciotm** [comment]
🎉 SOLUTION: (USING EXPO SDK 47.0.8) 🎉 

UNDERSTADING THE PROBLEM:
- Development environment use debug SHA1
- Production environment use appSigning SHA1
- Your API KEY in CLOUD have permission for Production, but not for Debug.

##

STEP 1: in your expo project, run `npx expo run:android`
STEP 2: run `cd android`
STEP 3: run `gradle signingReport`
STEP 4: Look for `> Task :app:signingReport` with text `/android/app/debug.keystore` you will see your debug keystore, look for `SHA1` (this is the debug SHA1 that you need to insert on cloud)

-----------------------------------------
* POSSIBLE PROBLEM AND HOW TO FIX:
** Look for `> Task :expo:signingReport` with text `Error: Missing keystore` if is missing, do this:
--STEP A: COPY the `debug.keystore` file in `YOUR_ROOT_PROJECT/android/app/debug.keystore`
--STEP B: run `open /Users/inaciopires/.android/` and PASTE the `debug.keystore` file
--STEP C: lets, check, run again `gradle signingReport` and check if your keystore is not missing anymore.
-----------------------------------------

STEP 5: create a new API KEY for dev debug in https://console.cloud.google.com/google/maps-apis/credentials
and add your `SHA1` that you find in `STEP 4`.


##

🎉  CONGRATULATIONS 🎉 
Now your development debug environment will works again

##

IF YOUR PRODUCTION OR INTERNAL TEST NOT WORKING
- STEP A: open the console https://play.google.com/console/u/1/developers/ and select your App
- STEP B: Search for `App Integrity` and select the tab `App sign`
- STEP C:  copy the `SHA-1 certification` 
- STEP D: follow the `STEP 5` and create your API KEY for this SHA1

##

🎉  CONGRATULATIONS 🎉 
Now your production environment will works


🇧🇷 Thanks, I hope I helped 😉

**Comment by gabriellend** [comment]
@vinaciotm Thanks for your comment, I appreciate your time. I'm not using Expo so I don't think this was my issue but maybe it will help someone else. I think my issue had to do with having Android-specific `edgePadding` (see the most recent update to my original post).

**Comment by gabriellend** [comment]
@Simon-TechForm You can go ahead and close this issue if you'd like. I'm still facing challenges but the initial issue has been resolved. The problem seemed to be that I had custom `edgePadding` for Android. I didn't see anything about the behavior changing in the docs (possible I could have missed it) so would still like to know more about this if you can shed any light.
