### ISSUE TITLE
Using PROVIDER_GOOGLE with react-native-maps crashes Simulator

### ISSUE THREAD

**Issue by iM-GeeKy** [react-native-maps/react-native-maps#4379]
### Summary

Using the provider={PROVIDER_GOOGLE} with a valid Google Maps API key in the MapView component causes the iOS simulator to crash. Running the code on a physical device however, does in fact render the map properly.

_Note: I'm not sure if this is `expo` or `react-native-maps` specific, so this issues is posted on both repos for visibility._  

### Reproducible sample code

```TSX
https://github.com/iM-GeeKy/my-app/tree/master
```

### Steps to reproduce

1. Run `expo start`.
2. `Press i │ open iOS simulator`
3. Add your Google API key to app.json.
4. Uncomment provider in app.js.

### Expected result

The Simulator does not crash.

### Actual result

The Simulator crashes.

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.3

### What version of Expo are you using?

SDK 46

### Device(s)

iPhone 13 Pro Simulator iOS 15.5

### Additional information

Issue opened with Expo team https://github.com/expo/expo/issues/18530

_This happens on amd and apple silicon._

**Comment by Simon-TechForm** [comment]
Your `reproducible sample code` is unavailable.

Besides from that, this looks like a misconfiguration withing expo.

**Comment by iM-GeeKy** [comment]
The visibility of the repo should be public now if that helps although you said it’s Expo related.

**Comment by gkpo** [comment]
did you find the root of the issue in the end ?
