### ISSUE TITLE
Custom markers not resizing on Android

### ISSUE THREAD

**Issue by treykapfer** [react-native-maps/react-native-maps#4382]
### Summary

On android, dynamically rendering marker height/width causes strange behavior. On our application, we want to increase the size of the marker if it's currently selected on the map. The marker behaves as expected on iOS, but the container does not increase in size on Android, the container appears to be locked into the initial width it renders.

### Reproducible sample code

```TSX
import React from "react";
import { View } from "react-native";
import useMap from "./useMap";
import MapView, { Marker, PROVIDER_GOOGLE } from "react-native-maps";
import Pin from "../../assets/pin.svg";

const MapExample = () => {
  const {
    mapRef,
    markerRefs,
    region,
    nearbyServices,
    updateSelected,
    selectedLocation,
  } = useMap();

  return (
    <>
      <View>
        <MapView provider={PROVIDER_GOOGLE} ref={mapRef} initialRegion={region}>
          {!!nearbyServices &&
            nearbyServices.map((loc) => (
              <Marker
                identifier={loc.place_id}
                coordinate={{
                  latitude: loc.geometry.location.lat,
                  longitude: loc.geometry.location.lng,
                }}
                title={loc.name}
                onPress={() => updateSelected(loc)}
                ref={(ref) => (markerRefs.current[loc.place_id] = ref)}
              >
                <View
                  style={
                    !!selectedLocation &&
                    selectedLocation.place_id === loc.place_id
                      ? { width: 60, height: 60 }
                      : { width: 40, height: 40 }
                  }
                >
                  <Pin />
                </View>
              </Marker>
            ))}
        </MapView>
      </View>
    </>
  );
};

export default MapExample;
```

### Steps to reproduce

You can use the code above to reproduce. Within a custom marker, attempt to change the width/height of the container based on any conditions. It will not properly re-render on android. The pin within the container may expand, but the container will not expand, despite the code being on the container itself and not on the pin at all.

### Expected result

We expect the marker to behave the same on android as it does on iOS. Currently the marker only expands "on focus" on iOS. 

### Actual result

When you select the pin on android, the pin itself expands in size (despite the code only being on the container), but the container keeps its width of 40px, causing the pin svg to be cut off.

### React Native Maps Version

0.29.4

### What platforms are you seeing the problem on?

Android

### React Native Version

0.64.3

### What version of Expo are you using?

SDK 44

### Device(s)

Nexus 10, Nexus 6, Nexus 7, Pixel 5, Pixel 4

**Comment by sunny-mittal** [comment]
I've had this issue as well. We had to resort to accepting that we can't change marker size on android :( I've tried all kinds of things but nothing works. If you find a solution, please tag me!

**Comment by abielg** [comment]
Also having this issue

**Comment by sunny-mittal** [comment]
I know this isn't useful information but I've done a lot of exploration of the Google Maps SDK and most issues people are reporting with react-native-maps are actually part of the Google Maps SDK. I know none of us wanna hear this but it's just how it is.

**Comment by daniel-xyz** [comment]
I still have this issue with version 1.14.0 that comes with Expo SDK 51. The marker withs on iOS (Apple Maps) are dynamic while the Google Map on Android isn't. If I change the with via styles it only changes after I refresh manually.
