### ISSUE TITLE
`overflow: 'visible'` style attribute does not work on custom Marker elements

### ISSUE THREAD

**Issue by go-sean-go** [react-native-maps/react-native-maps#4384]
### Summary

Custom Marker elements 'clip' outside of their bounds - regardless of (or ignoring) the `overflow: 'visible'` style attribute being set.

This can occur with full elements (like a `Text` element being positioned `absolute` 'below' the bounds/anchor point), but is maybe more easily shown by setting shadow attributes.

<img width="383" alt="map pins clipping" src="https://user-images.githubusercontent.com/55253273/183736499-4e664ad4-dcf0-4db1-b4fa-4ad1a1fae459.png">

### Reproducible sample code

```TSX
import {View} from 'react-native';
import {MapMarker} from 'react-native-maps';

<MapMarker
  {...props}
  style={{
    overflow: 'visible',
  }}
>
  <View
    style={{
      height: 50,
      width: 50,
      backgroundColor: 'red',
      borderRadius: 25,
      shadowColor: 'green',
      shadowOffset: {width: 1, height: 1},
      shadowOpacity: 1.0,
      shadowRadius: 10,
      overflow: 'visible',
    }}
  />
</MapMarker>
```

### Steps to reproduce

Add a shadow to an element (e.g. `View`) that would exceed its bounds, and then set `overflow: 'visible'` on its parent.

(Also occurs with full views, e.g. add a `Text` element that goes outside of the parents' bounds, e.g. using `position: 'absolute'`.

### Expected result

Shadow is visible outside of `<MapMarker>` bounds.

### Actual result

Shadow is not visible outside of `<MapMarker>` bounds.

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.3

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 Simulator (iOS 15.2)

### Additional information

NOTE: This was also reported here: https://github.com/react-native-maps/react-native-maps/issues/4169 - but was closed by the stale bot. So I am opening this new issue, here.

**Comment by go-sean-go** [comment]
Issue still exists on RN 0.70.1 and `react-native-maps` version 1.3.2.

**Comment by go-sean-go** [comment]
Note that I believe this is a problem (feature?) in the Google Library.

I found this documentation on Google's `GMSMarker` object: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker#aa16a89bd5187e64e71c57c31c150a44d

> Note that the view behaves as if `clipsToBounds` is set to `YES`, regardless of its actual value.

Of course, it provides no reason why. I would love any additional info if anyone can provide any insight, or workaround. This is REALLY jamming me up and forcing all kinds of design sacrifices.

**Comment by alainib** [comment]
did you found a fix ? 
i'm trying to put text in absolute position next to marker 

putting text and icon in a flex view move marker from original position

**Comment by go-sean-go** [comment]
As mentioned, I _believe_ this is a Google Maps SDK limitation (not `react-native-maps`), so I don't think there is anything to be done about it--meaning you will need to make whatever design sacrifices are required. Sadly.

Make sure you check out the `anchor` prop on `MapMarker` - that can help you get things positioned correctly over the GPS coordinate, at least.
