### ISSUE TITLE
Marker's `onPress` fires occasionally for the previously-clicked marker

### ISSUE THREAD

**Issue by sunny-mittal** [react-native-maps/react-native-maps#4386]
### Summary

I've had an issue in my work app that I thought might have something to do with the architecture but as I added some breakpoints and logging, I realized it's an issue at the library level. It primarily presents on Android for me though I have had it occur on iOS, just not reproducibly so I'm considering this an Android issue. Basically, when I tap between markers that are in close proximity (but not overlapping), the callback for the previously-clicked one seems to fire instead of the new one. For example, if I click marker with ID `a` and then slightly next to it tap marker with ID `b`, the `onPress` for `a` fires and then when I tap a second time, the `onPress` for `b` fires. Attached is also a video demoing this in the stripped-down app I created for the issue. You can see in the video that when I tap a pin, it alerts the ID of the _previous_ pin and on the second tap, it alerts its own correct ID. 

https://user-images.githubusercontent.com/8553227/183807309-b961360d-24d9-458c-b776-bce39bb4e8d9.mov

 

### Reproducible sample code

```TSX
https://github.com/sunny-mittal/map-demo
```

### Steps to reproduce

I've included sample data in my github repo that fully repro's the issue but the basic steps are to render some markers (on google maps on Android) at coordinates that are close to each other (no need to be overlapping or anything, though) and attach `onPress` handlers to them. Tap between two pins that are close to each other and observe that the handler for the previously-clicked pin fires unexpectedly before the correct handler fires on subsequent press.

### Expected result

The `onPress` handler for the pin that was pressed should fire correctly.

### Actual result

The `onPress` handler for a previously-clicked pin that's nearby will fire instead of the correct one until the desired pin is pressed again.

### React Native Maps Version

0.31.1 and 1.2.0.beta1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.66.4 and 0.69.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung Galaxy S21 5G, Android 12

### Additional information

This can also be consistently reproduced using `onMarkerPress` at the `<MapView ... />` level.

**Comment by sunny-mittal** [comment]
Here's one more video with an ugly background on the `<Marker .../>` component to show that the pins are absolutely not overlapping in any way, as in my first video they seem like they could be slightly.

https://user-images.githubusercontent.com/8553227/183808772-80731598-9032-43c5-8537-26ffe31a1603.mp4

**Comment by Simon-TechForm** [comment]
Hi @sunny-mittal 👋 Thank you for taking the time to fill out the issue form.

Unfortunately this is an issue in the Google Maps SDK, and has been for a very long time. Google expands the clickable area beyond the marker dimensions, and the behaviour isn't customizable. Check out #2552 and [googles issue tracker](https://issuetracker.google.com/issues/35823783).

**Comment by GoktuqCan** [comment]
Hi, I've created a repository based on the solution I'm using in my current project. I hope you'd find it useful:
[https://github.com/GoktuqCan/react-native-maps-touchables](https://github.com/GoktuqCan/react-native-maps-touchables)

**Comment by tvn19113** [comment]
Hi @sunny-mittal , have you found a solution for this issue?
