### ISSUE TITLE
Blank Map on Android with Expo Go (even on the official example)

### ISSUE THREAD

**Issue by Pitouli** [react-native-maps/react-native-maps#4393]
### Summary

The Google Maps tiles are not loading (but the markers and everything else I could add is indeed working fine), in an Expo Go environment.

You can observe the bug by going to the official page and run the snack on android: https://docs.expo.dev/versions/latest/sdk/map-view/#usage

I haven't tested on iOS.
It was working ~1 week ago, and I do not know exactly when it stopped working because the cache has "hidden" the bug for a while before I noticed it.

### Reproducible sample code

```TSX
import * as React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, Text, View, Dimensions } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});
```

### Steps to reproduce

Open the app and look at the map

### Expected result

The user should see the map

### Actual result

The user only see a light brown background
![image](https://user-images.githubusercontent.com/542778/184631278-96434b34-7616-43f8-a31d-3226e41957b6.png)

### React Native Maps Version

0.30.2 (my project), 1.2.0 (another test project), 0.31.1 (expo example)

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2 (my project), 0.69.4 (another test project), unknown (expo example)

### What version of Expo are you using?

45.0.8 (my project), 46..0.7 (another test project), 46.0.0 (expo example)

### Device(s)

Samsung Galaxy S12FE, Expo Online Android Emulator

**Comment by Pitouli** [comment]
Seems to be a Expo Go issue more than a react-nativ-maps issue:
https://github.com/expo/expo/issues/18618

**Comment by vinaciotm** [comment]
🎉 SOLUTION: (USING EXPO SDK 47.0.8) 🎉 

UNDERSTADING THE PROBLEM:
- Development environment use debug SHA1
- Production environment use appSigning SHA1
- Your API KEY in CLOUD have permission for Production, but not for Debug.

##

STEP 1: in your expo project, run `npx expo run:android`
STEP 2: run `cd android`
STEP 3: run `gradle signingReport`
STEP 4: Look for `> Task :app:signingReport` with text `/android/app/debug.keystore` you will see your debug keystore, look for `SHA1` (this is the debug SHA1 that you need to insert on cloud)

-----------------------------------------
* POSSIBLE PROBLEM AND HOW TO FIX:
** Look for `> Task :expo:signingReport` with text `Error: Missing keystore` if is missing, do this:
--STEP A: COPY the `debug.keystore` file in `YOUR_ROOT_PROJECT/android/app/debug.keystore`
--STEP B: run `open /Users/inaciopires/.android/` and PASTE the `debug.keystore` file
--STEP C: lets, check, run again `gradle signingReport` and check if your keystore is not missing anymore.
-----------------------------------------

STEP 5: create a new API KEY for dev debug in https://console.cloud.google.com/google/maps-apis/credentials
and add your `SHA1` that you find in `STEP 4`.


##

🎉  CONGRATULATIONS 🎉 
Now your development debug environment will works again

##

IF YOUR PRODUCTION OR INTERNAL TEST NOT WORKING
- STEP A: open the console https://play.google.com/console/u/1/developers/ and select your App
- STEP B: Search for `App Integrity` and select the tab `App sign`
- STEP C:  copy the `SHA-1 certification` 
- STEP D: follow the `STEP 5` and create your API KEY for this SHA1

##

🎉  CONGRATULATIONS 🎉 
Now your production environment will works


🇧🇷 Thanks, I hope I helped 😉

**Comment by hanamurayuki** [comment]
I also face same problem. 
IOS is ok, but blank map on android with eas build.

Document was updated on Fri Nov 25 17:54:16 2022 +0530.
https://docs.expo.dev/versions/latest/sdk/map-view/

[Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
[Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)

[Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
For development builds
If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.

**Comment by karimdakroury** [comment]
> I also face same problem. IOS is ok, but blank map on android with `eas build`. Reason is google map api authorization. (logo exists, but map is brank)
> 
> Document was updated on Fri Nov 25 2022. https://docs.expo.dev/versions/latest/sdk/map-view/
> 
> > # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> > ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> > 
> > 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> >    For development builds
> > 
> > 
> > * If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> > * After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> > * `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`
> 
> Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, but we need to upload `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials > Application Identifiers > click your project's package name and under Android Keystore),
> 
> After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.

@hanamurayuki If i am deploying to play store shouldnt i be using the SHA-1 from my play console instead of expo?
