### ISSUE TITLE
react native maps is not working

### ISSUE THREAD

**Issue by Venance5** [react-native-maps/react-native-maps#4394]
### Summary

Since a week I have tried to solve this white map screen. 
The map is not displayed. Only the "google logo" is 
![react native white screen](https://user-images.githubusercontent.com/82992501/184757075-78dc6dfe-e146-42d2-9277-3032ff4c74c4.jpeg)
visible.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (

    <MapView
    style={{flex:1}}
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}
  />
  );
}
```

### Steps to reproduce

Init react native project
install react-native-maps
import MapView
etc.

### Expected result

The map should be displayed

### Actual result

White screen: only the google logo is  visible

### React Native Maps Version

0.30.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

Samsung Galaxy A12 (Android 11)

**Comment by blue86321** [comment]
I have had the same issue before. Have you activated your Google Maps SDK for iOS?
<img width="346" alt="image" src="https://user-images.githubusercontent.com/50546951/184785708-7834f54f-3376-440f-8a20-5d11cb1fe7a4.png">

**Comment by Venance5** [comment]
Sure, And I am using Android Emulator,  so I think it may not be a problem.

**Comment by RyanTG** [comment]
Are you including your google maps api key?

**Comment by benjgorman** [comment]
Having the same issue, Expo's example snack has the same problem: https://docs.expo.dev/versions/latest/sdk/map-view/

**Comment by Venance5** [comment]
I saw where the problem is from. There is an update of react-native-maps.

I am using the version 0.30.2
New version is 0.31.1

I have updated through example on Snack and it works fine.

Thanks
