### ISSUE TITLE
Cant run project on iOS M1

### ISSUE THREAD

**Issue by kamdobrz** [react-native-maps/react-native-maps#4395]
### Summary

I've done all the steps to run the package, but still can't run the project.

### Reproducible sample code

```TSX
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'MyApp' do
  config = use_native_modules!

# React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

### Steps to reproduce

Try to run a project with sample Podfile

### Expected result

Run the project without errors.

### Actual result

Showing All Messages
Undefined symbol: _OBJC_CLASS_$_RCTBundleURLProvider

Undefined symbol: _OBJC_CLASS_$_RCTBridge

Undefined symbol: _RCTAppSetupPrepareApp

Undefined symbol: _OBJC_CLASS_$_RCTLinkingManager

Undefined symbol: _RCTAppSetupDefaultRootView

### React Native Maps Version

1.2.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

simulator

**Comment by qobaid-bunnyrents** [comment]
The solution here worked for me (only step #1 actually) https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9 

Beside step #1, I've also enabled Rosseta.

**Comment by Simon-TechForm** [comment]
Please make sure to search for simular issues before opening a new one. See #4249, #4238, #3527, #4097 and the [Note for Mac M1 users](https://reactnative.dev/docs/environment-setup#cocoapods). :)

**Comment by kamil-floqsta** [comment]
> The solution here worked for me (only step #1 actually) https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9
> 
> Beside step #1, I've also enabled Rosseta.

Thank you @qobaid-bunnyrents! Ive tried many solutions from other threads but only yours works for me!
