### ISSUE TITLE
Maximum image overlay size on iOS with Google Maps?

### ISSUE THREAD

**Issue by stevie-g** [react-native-maps/react-native-maps#4401]
### Summary

We have recently upgraded from react-native-maps version 0.29.3 to 1.3.0-beta.2, and some overlay images that previously rendered on the map without any issues are no longer appearing. The images appear correctly on an Android device using Google Maps, and when using native Apple maps on an iOS simulator - the bug seems to only occur when using Google Maps on an iOS device.

We upgraded to this version because the fix for [issue 3057](https://github.com/react-native-maps/react-native-maps/issues/3057) regarding polygon colour was fairly critical to our app (thank you for solving it!!), so can't really downgrade.

### Reproducible sample code

```TSX
import React from 'react'
import MapView, { Overlay, PROVIDER_GOOGLE } from 'react-native-maps'

interface OverlayData {
	uri: string;
	bounds: [[number, number], [number, number]];
}

const overlayData: OverlayData[] = [{
	// working image - 236 KB (808 × 768 pixels)
	uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Compass_Barnstar_Hires.png/1078px-Compass_Barnstar_Hires.png',
	bounds: [
		[-34.112934054091504, 148.08047732607287],
		[-34.13863400940858, 148.11233244797933]
	]
}, {
	// non working image - 363 KB (1,078 × 1,024 pixels)
	uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Compass_Barnstar_Hires.png/808px-Compass_Barnstar_Hires.png',
	bounds: [
		[-34.111022858153866, 148.02569210529327],
		[-34.13731262869155, 148.06579917669296]
	]
}]

const region = {
	latitude: -34.123348117057915,
	latitudeDelta: 0.09114369672222011,
	longitude: 148.06839019060135,
	longitudeDelta: 0.14679931104183197
}

const App = () => {
	return (
		<MapView
			style={{ flex: 1 }}
			provider={PROVIDER_GOOGLE}
			region={region}
		>
			{overlayData.map((data, index) => (
				<Overlay
					key={index}
					image={{ uri: data.uri }}
					bounds={data.bounds}
				/>
			))}
		</MapView>
	)
}

export default App
```

### Steps to reproduce

- Run the above code in iOS simulator or device and only one image will appear (the smaller)
- Remove `provider={PROVIDER_GOOGLE}` and reload
- Both images will appear

### Expected result

Both images should appear whether using native Apple maps or Google Maps.

### Actual result

Larger image does not appear when using Google Maps on iOS.

### React Native Maps Version

1.3.0-beta.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.64.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Simulators: iPhone 8 + iPad 9th generation (iOS 15.4); Device:  iPad 6th generation (iOS 14.7.1)

### Additional information

The theory I currently have is that there is a maximum size of image overlays enforced somewhere, although I haven't been able to find any information on that for this library or for Google Maps.

In addition to the two images I've used in the reproducible example above, I tested the following sized images (all .pngs) which previously worked before upgrading:
- 234 KB / 1000 × 1000 pixels (works)
- 315 KB / 1070 × 956 pixels (does not work)
- 449 KB / 739 × 648 pixels (works)
- 663 KB / 775 × 1034 pixels (does not work)

Because of this, at the moment I think the problem is related to dimension, not the size of the image in bytes.

Lastly - many many thanks for this library, it's fantastic!

**Comment by stevie-g** [comment]
Just an update based on further testing: it seems as though the limit in dimensions is a maximum of 1024 pixels in either width or height. I guess I'm curious as to whether this is a recent limit imposed by this library, or by Google Maps, or an actual bug?

**Comment by Simon-TechForm** [comment]
hi @stevie-g. Thank you for taking the time to put together a thorough issue.

This is not a limit imposed by `react-native-maps`, nor did I read about it in the Maps SDK release notes. I did some quick testing however, and it seems like it is caused by using the "new" metal renderer on iOS. You can test this out quite easily by going to your node_modules > react-native-maps > iOS > AirGoogleMaps > AirGoogleMapManager.m and at line 48 change `[GMSServices setMetalRendererEnabled:YES];` to `[GMSServices setMetalRendererEnabled:NO];` and doing `react-native run ios` after making the change.

Patching this line could be a temporary solution if you rely on large images. I will try to investigate further when I have the time to do so, and will leave this open until we figure out how to move forward :)

**Comment by stevie-g** [comment]
Hi Simon,

Thanks for your reply and for the solution - I can confirm that that change has fixed the issue. Patching that line seems to be the best solution for us, at least in the short term - I would rather hold off on making changes to how we generate images and their dimensions until we know if it's definitely necessary or not.

Thanks again!

**Comment by chuece** [comment]
Hi all! I see same issue in my 0.69.4 RN project with 1.2.0 react-native-maps. I was investigating on this and threshold for image dimension seems to be 1024px (same image, squared, changing from 1024px to 1025px and it disappears). Turning off metal renderer helps to fix this

**Comment by Simon-TechForm** [comment]
I've been able to reproduce the issue in a native project, so I've opened an issue on google's issue tracker: https://issuetracker.google.com/issues/247339055
