### ISSUE TITLE
onLayout not getting called on Android on latest versions

### ISSUE THREAD

**Issue by JoniVR** [react-native-maps/react-native-maps#4402]
### Summary

On Android, the `onLayout` function of the mapview is not getting called.

### Reproducible sample code

```TSX
<MapView
   onLayout={event => {
     console.log(event.nativeEvent.layout);
   }}
>
```

### Steps to reproduce

1. Run the project on an android phone or tablet.
2. log the `onLayout` method.		

### Expected result

The method should get triggered initially.	

### Actual result

It's not getting triggered.

### React Native Maps Version

1.2.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Android 12 (API 31)

### Additional information

I'm guessing this may have been introduced in:
https://github.com/react-native-maps/react-native-maps/commit/0554cdcc666f8ace40b5e94de17598c2f1b5d528

The problem doesn't seem to exist in earlier versions.

**Comment by Simon-TechForm** [comment]
@JoniVR Your guess is correct. I've just published a new beta release that should fix the issue. Can you try it out and check whether it works out for you? :)

**Comment by JoniVR** [comment]
Hi @Simon-TechForm!

Thanks for the quick response and fix, I'll set a reminder to test this on Monday! Have a nice weekend!

**Comment by JoniVR** [comment]
Seems to work now, thanks for the quick fix! I'll leave this open so you can close it when the fix is released to  stable or whenever you feel like it :)
