### ISSUE TITLE
Google Maps toolbar not able to find Google maps app

### ISSUE THREAD

**Issue by Cleymi** [react-native-maps/react-native-maps#4403]
### Summary

The problem only occurs when I build with the **eas build** command (using the expo manager),
the next:
when I press a marker, the option to navigate to those coordinates is activated, as indicated in the image with the arrow,

![app](https://user-images.githubusercontent.com/45864853/185409613-fec82b84-c5fb-495b-a1ec-5e8599650288.jpg)

then when i press any of those options i get the error shown in the message
I clarify that I have google maps installed on my Android phone v.12 with all the required permissions activated

### Reproducible sample code

```TSX
import MapView, { Polygon, Marker, Callout } from 'react-native-maps';

...

<MapView
          style={styMap.map}
          region={{
            ...customers.center,
            latitudeDelta: 0.09,
            longitudeDelta: 0.04,
          }}
          userInterfaceStyle="dark"
          showsUserLocation={true}
          showsTraffic={options.trafic}
          mapType={options.satellite ? 'satellite' : 'standard'}
        >
          {routes.map((item) => (
            <Polygon
              key={item.id}
              coordinates={item.geometry}
              strokeColor={pinkRed}
              strokeWidth={3}
              fillColor="#fb00ff1f"
            />
          ))}

          {customers.list.map((item) => (
            <MarkerCustomer key={item.id} item={item} />
          ))}
        </MapView>

...
```

### Steps to reproduce

press the marker, and with the native events of the marker the options that I indicate with the arrow in the image are activated
![app](https://user-images.githubusercontent.com/45864853/185413672-ddd0ebbb-4f0d-4a8b-9635-caf50f81015d.jpg)
when I press one of those options, I get the message shown in the image
-> this only happens when the application is built with the **eas build** command

### Expected result

I expected it to work naturally without problems since when compiled with expo build this error is not reproduced

### Actual result

**google maps is not installed or is disabled**

### React Native Maps Version

^1.2.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

xiaomi poco x3 pro, samsung s20 fe

### Additional information

![image](https://user-images.githubusercontent.com/45864853/185451333-8d2a98bc-9297-41cc-944e-3e2fa43d827c.png)

if someone can help me, thanks

**Comment by Simon-TechForm** [comment]
Yeah, I noticed a while back that this wasn't documented in `react-native-maps`, but haven't gotten around to adding it...

This should be fixed by adding
```xml
<queries>
    <package android:name="com.google.android.apps.maps" />
</queries>
```
to the `AndroidManifest.xml` file directly under the `<manifest>` tag, e.g.:
```xml
<manifest package="com.example.app">
    <queries>
        <package android:name="com.google.android.apps.maps" />
    </queries>
    ...
</manifest>
```

**Comment by Cleymi** [comment]
The administrator is expo, therefore theAndroidManifest.xml file does not exist, if you would be kind to explain to me an example of how you could do it in this case, thanks you.

**Comment by Simon-TechForm** [comment]
I'm afraid I can't help you with that, as I'm not an expo user myself. I'd recommend having a look at the expo documentation, or maybe ask the question in expo's discussion section? :)

**Comment by miiguellssantos** [comment]
> The administrator is expo, therefore the AndroidManifest.xml file does not exist, if you would be kind to explain to me an example of how you could do it in this case, thanks you.

You just have to run the command ``` npx expo prebuild ``` to create the .android folder.
