### ISSUE TITLE
fitToElements properties not working - Android

### ISSUE THREAD

**Issue by RandomToni** [react-native-maps/react-native-maps#4411]
### Summary

Only in Android:

mapRef?.current?.fitToElements({edgePadding: {left: 10}) will not work
mapRef?.current?.fitToElements() does work

Method is not able to get the properties properly.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {

  const onMapReady = () => mapRef?.current?.fitToElements({animated: true, edgePadding: {left: 10}})

  return (
    <MapView
      style={{flex: 1}}
      onMapReady={onMapReady}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

call fitToElements with options.edgePadding in order to reproduce issue.

### Expected result

fitToElements will not happen if options.edgePadding is passed.

### Actual result

map remains at initial coordinates.

### React Native Maps Version

1.2.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.65.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung galaxy S8

**Comment by pinpong** [comment]
try:
```js
  const onMapReady = () => mapRef?.current?.fitToElements({animated: true, edgePadding: {left: 10, top:0, right:0, bottom: 0}})

**Comment by tomasmozeris** [comment]
For quick temporal workaround wrapping in `4ms setTimeout` for android seems to work

**Comment by RandomToni** [comment]
Holly guacamole! That did the trick, edgePadding must be completely defined in order for the method to work properly. Thank you.
