### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [react-native-maps/react-native-maps#4412]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@dwisiswant0) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Simon-TechForm** [comment]
Hi @JamieSlome 👋

I've just added a security policy including a contact email. If you reach out on there, I will respond as soon as possible :)
