### ISSUE TITLE
 Exception in HostFunction: Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by Willham12** [react-native-maps/react-native-maps#4415]
### Summary

 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

### Reproducible sample code

```TSX
Example app "Get visible map boundaries
```

### Steps to reproduce

Example app "Get visible map boundaries

### Expected result

no error

### Actual result

error

### React Native Maps Version

1.3.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.67.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13

**Comment by Willham12** [comment]
@Simon-TechForm

**Comment by avakin** [comment]
Receiving the same error after upgrading from 0.31.1 to 1.3.0 on macOS for iPhone simulator.

**Comment by Willham12** [comment]
The Problem is:

https://github.com/react-native-maps/react-native-maps/blob/master/src/MapView.tsx#L1027

**Comment by avakin** [comment]
@Willham12 @Simon-TechForm 

is there is any solution or fix for this for now? maybe reverting to some older release?

**Comment by Willham12** [comment]
@avakin 
```patch
diff --git a/node_modules/react-native-maps/lib/MapView.js b/node_modules/react-native-maps/lib/MapView.js
index 12fc6fa..79668cd 100644
--- a/node_modules/react-native-maps/lib/MapView.js
+++ b/node_modules/react-native-maps/lib/MapView.js
@@ -292,7 +292,7 @@ class MapView extends React.Component {
     }
     _runCommand(name, args) {
         if (react_native_1.Platform.OS === 'ios') {
-            return this._mapManagerCommand(name)(this.map.current, ...args);
+            return this._mapManagerCommand(name)(react_native_1.findNodeHandle(this.map.current), ...args);
         }
         else {
             return Promise.reject(`Invalid platform was passed: ${react_native_1.Platform.OS}`);

**Comment by numine777** [comment]
I still get the same error with the patch applied.  Reverting to 1.2.0, but please let me know if I can help at all

**Comment by avakin** [comment]
also have reverted to 1.2.0, all functionality working as expected. Will try to patch with your fix later, then will respond. Thanks @Willham12

**Comment by Willham12** [comment]
Got the error with Android too

**Comment by dcosmin2003** [comment]
The patch is only for iOS, but I have this error on Android too.

**Comment by Simon-TechForm** [comment]
Hi all. Yeah 1.3.0 is broken. I'd recommend staying on 1.2.0 for now, until I issue a fix. Not really sure yet what went wrong when I tested the changes... My apologies for the inconvenience.

**Comment by manasbatchservice** [comment]
Hi @Simon-TechForm 
Checked with 1.2.0 version also, still facing issue when invoking map.current.getCamera method.

**Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.**

**Comment by Willham12** [comment]
@manasbatchservice clear node_modules and refresh pods, no issues with 1.2.0

**Comment by AqibCybery** [comment]
passing a null string ,or null object causing the issue in my case

**Comment by mousaormoses** [comment]
I have react-native-maps@1.7.1
and still this happens with iOS only

**Comment by DamianUS** [comment]
Still happens in Android as well if the whole region object is passed as reference. I need to unpack de values to make it work:

For example:
@injectable()
class SpotsMapViewModel {
    areasOfInterestPolygons: LatLongPolygon[] = []
    detectionsPolygons: LatLongPolygon[] = []
    areaOfInterestRepository: AreaOfInterestRepository
    detectionRepository: DetectionRepository
    globalState: GlobalState
    isQueryingParkingService: boolean = false
    _region = {
        latitude: 37.3886,
        longitude: -5.9823,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    }
    
// DOES NOT WORK
<View style={styles.container}>
            <MapView
                style={styles.map}
                onRegionChangeComplete={(region) => {spotsMapViewModel.region = region}}
                /*mapType="satellite"*/
                pitchEnabled={false}
                mapType="terrain"
                region={spotsMapViewModel.region}
            >
                {renderAreaOfInterestPolygons()}
                {renderDetectionPolygons()}
            </MapView>
        </View>

// WORKS

 <View style={styles.container}>
            <MapView
                style={styles.map}
                onRegionChangeComplete={(region) => {spotsMapViewModel.region = region}}
                /*mapType="satellite"*/
                pitchEnabled={false}
                mapType="terrain"
                region={
                    {
                        latitude: spotsMapViewModel.region.latitude,
                        longitude: spotsMapViewModel.region.longitude,
                        latitudeDelta: spotsMapViewModel.region.latitudeDelta,
                        longitudeDelta: spotsMapViewModel.region.longitudeDelta,
                    }
                }
            >
                {renderAreaOfInterestPolygons()}
                {renderDetectionPolygons()}
            </MapView>
        </View>
