### ISSUE TITLE
Repost of initialRegion does not work correctly on IOS #4244 [with workaround]

### ISSUE THREAD

**Issue by nschild** [react-native-maps/react-native-maps#4420]
### Summary

Upgraded to 1.0.0 and saw this bug, Still occuring on 1.3.0
RN: 0.66.4

### Reproducible sample code

```TSX
region {"latitude": 35.96, "latitudeDelta": 0.5, "longitude": -83.92, "longitudeDelta": 0.5}

<ClusteredMapView
                    initialRegion={this.region}
                    onRegionChangeComplete={this.handleRegionChange}
                    data={displayMarkers}
                    ref={this.handleClusterMapRef}
                    renderMarker={this.renderPin}
                    renderCluster={this.renderCluster}
                    edgePadding={edgePadding}
                    mapPadding={mapPadding}
                    provider='google'
                    showsUserLocation={this.isLocationAllowed}
                    showsMyLocationButton={false}
                    showsPointsOfInterest={false}
                    showsCompass={false}
                    showsScale={false}
                    showsBuildings={false}
                    showsTraffic={false}
                    showsIndoors={false}
                    zoomControlEnabled={false}
                    rotateEnabled={false}
                    pitchEnabled={false}
                    toolbarEnabled={false}
                    minZoomLevel={5}
                    maxZoomLevel={16}
                    onPress={this.handleMapPress}
                    radius={65}
                    style={style.map}
                    width={width}
                    zoomEnabled={!preventInteraction}
                    zoomTapEnabled={!preventInteraction}
                    scrollEnabled={!preventInteraction}
                    moveOnMarkerPress={!preventInteraction}
                >
                </ClusteredMapView>
```

### Steps to reproduce

open app on ios

### Expected result

zooms to the correct zoom level

### Actual result

correct on andriod, zoomed out to entire united states on ios

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.66.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iphone xr

### Additional information

fixed by setting the prop
`onMapReady={Platform.OS === 'ios' ? this.resetToInitialZoomLevelFixForIOS : undefined}`
where
`    resetToInitialZoomLevelFixForIOS = () => {
        this.map?.animateToRegion(this.initialRegion, 100);
    }
`

**Comment by flexbox** [comment]
Confirmed on iOS with Expo.

I have no issue with 
```json
"dependencies": {
  "react-native": "0.69.4",
  "react-native-maps": "0.31.1",
}
```

```
const initialRegion = {
  latitude: 37.78825,
  longitude: -122.4324,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
};


```
<img width="442" alt="image" src="https://user-images.githubusercontent.com/360936/186668835-df5c3829-7b60-48cf-8d79-c335e7f91b4b.png">


```
const initialRegion = {
  latitude: 48.856614
  latitudeDelta: 0.0922
  longitude: 2.3522219
  longitudeDelta: 0.0426042654028436
}
```
<img width="434" alt="image" src="https://user-images.githubusercontent.com/360936/186669165-ae81a85e-5093-4b94-ad16-b8e75cab8740.png">

Same screenshots with 

```json
"dependencies": {
  "react-native": "0.69.4",
  "react-native-maps": "1.31.1",
}
```

<img width="571" alt="image" src="https://user-images.githubusercontent.com/360936/186670523-8f8bd9e3-0670-41ff-a0a1-83d122407cad.png">


<img width="523" alt="image" src="https://user-images.githubusercontent.com/360936/186670480-b37f1c83-97cc-4156-ae0a-e2c023ec92da.png">

**Comment by RobertTucker1999** [comment]
I've only experienced `initialRegion` prop not working on the built version of a physical device running iOS. Running it on the iOS simulator does not reproduce this issue.

This is still an issue on more recent versions of react-native and react-native-maps:
RN=0.69.5
RNMaps=1.3.1

**Comment by Simon-TechForm** [comment]
Hi @RobertTucker1999 👋 

Are you reproducing the issue consistently? Also, can you elaborate on what the "built version" means? Are you refering to builds on physical devices in general or an archived app, or..? It would be extremely helpful if you could provide the steps needed to reproduce the issue, as I've been having a hard time reproducing it at all... 😕

**Comment by guillaumegaluz** [comment]
I'm experiencing the same situation as @RobertTucker1999 described above: when i run my app in the simulator, the map is properly zoomed using the `initialRegion` props data. But when i build it and open it on Testflight it's zoomed out on the entire world (although still correctly _centered_ on the proper lat/long).

Those are the versions of the packages I'm running:

```
"react-native": "0.69.5",
"react-native-maps": "0.31.1",
```

If i downgrade to

```
"react-native": "0.68.2",
"react-native-maps": "0.30.2",
```

this is not an issue anymore: the map is properly zoomed when built.

Happy to provide any other info!

**Comment by Simon-TechForm** [comment]
Thank you for offering your help @guillaumegaluz :)

This post is specific to >= v1.0.0 as that version included a commit for initialRegion that I assumed fixed the issue.

I just tried archiving an app and installing it ad-hoc, and initialRegion is still working on my end.

@flexbox @nschild are you experiencing this in debug builds?

**Comment by danidaryaweesh** [comment]
I can confirm that I'm also having the same issue on version 1.3.2 on IOS real devices only

**Comment by flexbox** [comment]
This thing is weird 

I updated Xcode on my laptop, and got iOS 16+ now

bumped to
```
    "react-native": "0.69.5",
    "react-native-maps": "^1.3.2",
```

I created a small project and it's working perfectly
https://github.com/flexbox/react-native-bootcamp/tree/main/hackathon/atm-locator

**Comment by mHvNG** [comment]
Are there some updates on this issue? Expo recently updated react-native-maps to 1.3.2, which means I'm stuck on this breaking issue.

**Comment by flexbox** [comment]
@mHvNG 
> It only happens when the value is .1 or higher for latitudeDelta

Can you provide an example of the data to create a reproducible example?
