### ISSUE TITLE
OnRegionChange doesn't work properly

### ISSUE THREAD

**Issue by arthurysong** [react-native-maps/react-native-maps#4427]
### Summary

I'm trying to control the region of the map using a state. I have followed the exact example in the documentation only using functional components instead of class components. When I try to change the location of the map in my android device (in dev env), the map will snap back to where it was originally and then struggle to move to the place I moved it to.

### Reproducible sample code

```TSX
export default function App() {
  const [region, setRegion] = useState({
    latitude: 34.204268,
    longitude: -118.254088,
    latitudeDelta: 0.02,
    longitudeDelta: 0.02,
  });

  const testRegionChange = (region) => {
    console.log(region);
    setRegion(region);
  };
  return (
    <View style={styles.container}>
      <MapView
        style={styles.map}
        region={region}
        provider={PROVIDER_GOOGLE}
        onRegionChange={testRegionChange}
      >
        
      </MapView>
    </View>
  );
}
```

### Steps to reproduce

Create map with region controlled by state

### Expected result

Map should move around smoothly when testing in development.

### Actual result

Map is very glitchy when trying to navigate.

### React Native Maps Version

1.3.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.69.5

### What version of Expo are you using?

SDK 46

### Device(s)

Samsung Galaxy A71 5G

**Comment by arelstone** [comment]
As far as I understood the `region` prop is for "locking" the map to a region.

For my implementation I want to be able to initialize the map with a region but still want to allow the user to move around on the map. For this i use the `initialRegion`

```jsx
const [region, setRegion] = useState<Region>(Utils.HQ)

// ....

<MapView
        {...MapDefaultProps}
        ref={ref}
        initialRegion={regionFrom(region, RADIUS)}
        style={styles.map}
        customMapStyle={R.styles.map}
        onMarkerPress={({ nativeEvent: { id } }) => onMarkerPress(markers.find(m => m.id === id)!)}
        onRegionChangeComplete={setRegion}
        onMapLoaded={() => setIsReady(true)}
/>
```

I hope this will help you @arthurysong

**Comment by youf-olivier** [comment]
I was searching about a bug with onRegionChangeComplete, but I thing it can be a similar probleme here.

About the glitchy map, if I have a map like 

```javascript

const [region, setRegion] = useState<Region>(Utils.HQ)

// ....

<MapView
        {...MapDefaultProps}
        ref={ref}
        onRegionChangeComplete={(region)=>{
           console.log("We change for", region);
           setRegion(region);
        }}
        onMapLoaded={() => setIsReady(true)}
/>

```

When I zoom out 2/3 times i have a infinite loop =>

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/40664502/188487804-62e13da1-2a8e-46f7-a12f-4c89d4f4aef3.png">

**Comment by arthurysong** [comment]
@youf-olivier hey, just took a look at the #4265. That did it for me. Thanks!!
