### ISSUE TITLE
[iOS] App crashes when a Google Map with satellite map type and no markers is removed from the view hierarchy.

### ISSUE THREAD

**Issue by lucaslt89** [react-native-maps/react-native-maps#4432]
### Summary

We identified a crash in the following conditions:
* Google Maps on iOS (Using Metal renderer)
* Map with `satellite` map type
* No markers added and no user location shown in the map (map is completely clean)
* When the map is removed from the view hierarchy, it crashes (it might get hidden after a screen refresh or removed from memory after the user moves back in the stack navigation).

### Reproducible sample code

```TSX
import React, { useEffect, useState } from 'react';
import { View } from 'react-native';
import MapView from 'react-native-maps';

const TestScreen = () => {
  const [showTestMap, setShowTestMap] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setShowTestMap(true);
      setTimeout(() => {
        setShowTestMap(false);
      }, 3000);
    }, 2000);
  }, []);

  return (
    <View style={{ flex: 1 }}>
      {showTestMap && <MapView style={{ flex: 1 }} provider="google" mapType="satellite" />}
    </View>
  );
};

export default TestScreen;
```

### Steps to reproduce

Showing the provided `TestScreen` will generate the crash. The crash happens when the app shows a map with no visible markers at all (not even user location) and then it's removed from the view hierarchy (either by hiding it, or by removing the screen from a navigation stack).

There are 2 ways to reproduce the crash:
Way 1: Remove a clean map from the view hierarchy.
* Add a map to the screen with `provider="google" mapType='satellite"` and no markers, not even user location marker.
* Remove that map from the view hierarchy
* The provided code is doing this (add the map after 2 seconds the screen appears, and then removing it 3 seconds later).

Way 2: Move the map to a place with no markers and then remove it from the view hierarchy.
* Add a map to the screen with `provider="google" mapType='satellite"` which can have markers (for example user location, points of interest or any other marker).
* Move the map to a region that doesn't have any markers (you need to move far away from the markers locations, like in the middle of the ocean, so that markers are removed from memory).
* Remove the map from the view hierarchy.

### Expected result

The app doesn't crash

### Actual result

The app crashes  with the following stack trace:

```
SIGSEGV: Attempted to dereference garbage pointer 0x530038bc8aa0.

0  Our App       std::__1::less<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> >::operator()(std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> const&, std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> const&) const (Our App)
1  Our App       std::__1::__tree_iterator<std::__1::__value_type<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::vector<std::__1::shared_ptr<gmscore::renderer::MetalTexture>, std::__1::allocator<std::__1::shared_ptr<gmscore::renderer::MetalTexture> > > >, std::__1::__tree_node<std::__1::__value_type<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::vector<std::__1::shared_ptr<gmscore::renderer::MetalTexture>, std::__1::allocator<std::__1::shared_ptr<gmscore::renderer::MetalTexture> > > >, void*>*, long> std::__1::__tree<std::__1::__value_type<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::vector<std::__1::shared_ptr<gmscore::renderer::MetalTexture>, std::__1::allocator<std::__1::shared_ptr<gmscore::renderer::MetalTexture> > > >, std::__1::__map_value_compare<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::__value_type<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::vector<std::__1::shared_ptr<gmscore::renderer::MetalTexture>, std::__1::allocator<std::__1::shared_ptr<gmscore::renderer::MetalTexture> > > >, std::__1::less<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool>, std::__1::vector<std::__1::shared_ptr<gmscore::renderer::MetalTexture>, std::__1::allocator<std::__1::shared_ptr<gmscore::renderer::MetalTexture> > > > > >::find<std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> >(std::__1::tuple<MTLTextureType, MTLPixelFormat, int, int, bool> const&) (Our App)
2  Our App       gmscore::renderer::MetalTexturePool::CleanupIfNeeded() (Our App)
3  Our App       gmscore::renderer::MetalTexturePool::ReturnTextureToPool(std::__1::shared_ptr<gmscore::renderer::MetalTexture> const&) (Our App)
4  Our App       gmscore::renderer::MetalPooledTexture::~MetalPooledTexture() (Our App)
5  Our App       std::__1::shared_ptr<reanimated::NativeReanimatedModule>::~shared_ptr() (shared_ptr.h:177:9)
6  Our App       std::__1::shared_ptr<facebook::jsi::Function>::~shared_ptr() (shared_ptr.h:957:1)
7  Our App       std::__1::__hash_table<std::__1::__hash_value_type<long long, std::__1::shared_ptr<facebook::jsi::Function> >, std::__1::__unordered_map_hasher<long long, std::__1::__hash_value_type<long long, std::__1::shared_ptr<facebook::jsi::Function> >, std::__1::hash<long long>, std::__1::equal_to<long long>, true>, std::__1::__unordered_map_equal<long long, std::__1::__hash_value_type<long long, std::__1::shared_ptr<facebook::jsi::Function> >, std::__1::equal_to<long long>, std::__1::hash<long long>, true>, std::__1::allocator<std::__1::__hash_value_type<long long, std::__1::shared_ptr<facebook::jsi::Function> > > >::~__hash_table() (__hash_table:1519:5)
8  Our App       std::__1::unique_ptr<gmscore::renderer::MetalRenderStateController, std::__1::default_delete<gmscore::renderer::MetalRenderStateController> >::reset(gmscore::renderer::MetalRenderStateController*) (Our App)
9  Our App       gmscore::renderer::MetalRenderTarget::~MetalRenderTarget() (Our App)
10 Our App       gmscore::renderer::MetalRenderTarget::~MetalRenderTarget() (Our App)
11 Our App       gmscore::base::ReferenceCounted::GMSx_Unref() (Our App)
12 Our App       gmscore::base::reffed_ptr<gmscore::renderer::RenderTarget>::~reffed_ptr() (Our App)
13 Our App       -[GMSPhoenixRenderer .cxx_destruct] (Our App)
14 libobjc.A.dylib        object_cxxDestructFromClass(objc_object*, objc_class*)
15 libobjc.A.dylib        _objc_destructInstance
16 libobjc.A.dylib        __objc_rootDealloc
17 libsystem_blocks.dylib __Block_release
18 libobjc.A.dylib        AutoreleasePoolPage::releaseUntil(objc_object**)
19 libobjc.A.dylib        _objc_autoreleasePoolPop
20 UIKitCore              -[UIViewController dealloc]
21 libsystem_blocks.dylib __Block_release
22 CoreFoundation         ___RELEASE_OBJECTS_IN_THE_ARRAY__
23 CoreFoundation         -[__NSArrayM dealloc]
24 UIKitCore              -[_UIViewControllerTransitionContext _runAlongsideCompletions]
25 UIKitCore              -[_UIViewControllerTransitionContext completeTransition:]
26 UIKitCore              -[UITransitionView notifyDidCompleteTransition:]
27 UIKitCore              -[UITransitionView _didCompleteTransition:]
28 UIKitCore              ___UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__
29 UIKitCore              -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
30 UIKitCore              -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
31 UIKitCore              -[UIViewAnimationState animationDidStop:finished:]
32 UIKitCore              -[UIViewAnimationState animationDidStop:finished:]
33 QuartzCore             CA::Layer::run_animation_callbacks(void*)
34 libdispatch.dylib      __dispatch_client_callout
35 libdispatch.dylib      __dispatch_main_queue_drain
36 libdispatch.dylib      __dispatch_main_queue_callback_4CF
37 CoreFoundation         ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
38 CoreFoundation         ___CFRunLoopRun
39 CoreFoundation         _CFRunLoopRunSpecific
40 GraphicsServices       _GSEventRunModal
41 UIKitCore              -[UIApplication _run]
42 UIKitCore              _UIApplicationMain
43 Our App       main (main.m:8:12)
44 dyld                   start
```

### React Native Maps Version

1.2.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

All iOS devices

### Additional information

There's a workaround, not elegant though:

To avoid this crash, add an invisible marker that is always in the visible region. We achieved this the following way:
1. Track the visible region in a state:
2. Handle the `onRegionChangeComplete` event to update the region
3. Add a placeholder marker in the visible region

The code should look like this:
```TSX
...
const [visibleRegion, setVisibleRegion] = useState<Region>();
...
<MapView
  ...
  onRegionChangeComplete={region => {
    setVisibleRegion(region);
  }}
>
  {/* This is a placeholder marker required in iOS because if the map doesn't have any markers, it crashes when closing the modal */}
  {Platform.OS === 'ios' && visibleRegion && (
    <Marker coordinate={visibleRegion}>
      <View />
    </Marker>
  )}
</MapView>
```

**Comment by lucaslt89** [comment]
I was able to reproduce this issue with the native Google Maps SDK in a native iOS app. This only happens with the Metal renderer, so if we can include a flag to disable it in `react-native-maps` it'd be great

**Comment by Simon-TechForm** [comment]
Hi @lucaslt89. Thank you for your thorough report.

I noticed that you've opened an issue on google issue tracker as well, which is great. I'll keep an eye on that.

If possible, I would prefer not adding another variable that needs testing/triage etc. If Google doesn't provide a solution, I will of course reconsider :)

**Comment by lucaslt89** [comment]
sounds good. Let's wait for Google to fix it! I did try a fork using OpenGL renderer but other crashes also happen, so I rather stay with Metal which works much better, and only has this crash.

Thanks!

**Comment by isaacparsons-dw** [comment]
I'm not using markers yet `mapType={'satellite'}` still causes a crash with a similar stack trace on my end. I'm not across the details but could it be a satellite view issue rather than an issue with markers too? 

for me the issue seems to be a hybrid with [this issue](https://github.com/react-native-maps/react-native-maps/issues/4130) as I am using both satellite view with provider google

**Comment by lucaslt89** [comment]
@isaacparsons-dw it actually happens when you don't use markers. If the map has a `satellite` type and is completely clean (no markers), when the map is removed from the view hierarchy, then the app crashes. I also found that this is reproducible with a `hybrid` map, if there are no points of interest or streets nearby, and you don't add any markers.

As I mentioned this is an issue on Google Maps SDK and it's [reported there](https://issuetracker.google.com/issues/245716313) so I guess we can close this one.

**Comment by pduggi-olg** [comment]
This seems to have come back in with ios 17 :(

**Comment by natmet** [comment]
Its back in iOs 17
