### ISSUE TITLE
Library not compatibile with use_frameworks! firebase condition

### ISSUE THREAD

**Issue by CiprianS** [react-native-maps/react-native-maps#4434]
### Summary

I am working on a project with React Native 0.69.5. I've tried to install Firebase SDK v6 and, as you know, their requirement is to use use_frameworks! into Podfile of the iOS project.  Doing that, will make the iOS build to fail because
'Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h' file not found

There is a similar issue posted here (https://github.com/react-native-maps/react-native-maps/issues/4380) but it does not help....

### Reproducible sample code

```TSX
Here is the Podfile used in the project
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

project 'TestApp',
  'Debug' => :debug,
  'Release' => :release,
  'Prod.Debug' => :debug,
  'Prod.Release' => :release,
  'Dev.Debug' => :debug,
  'Dev.Release' => :release

target 'TestApp' do
  # use_frameworks!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  pod 'ZendeskChatSDK'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          paths = Array["\"$(inherited)\"", "\"$(SRCROOT)/Google-Maps-iOS-Utils/src/Heatmap\""]
          config.build_settings['HEADER_SEARCH_PATHS'] = paths.uniq
          puts config.build_settings['HEADER_SEARCH_PATHS']
        end
      end
      target.build_configurations.each do |config|
        # config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Steps to reproduce

1. Install a project with React Native 0.69.5
2. Install react-native-maps
3. Install latest version of firebase

### Expected result

Project should build successfully

### Actual result

Build fails because of the error
'Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h' file not found

![Screenshot 2022-09-08 at 17 14 56](https://user-images.githubusercontent.com/10684648/189146010-29c8959a-39f5-48d7-b2ff-145211884f50.png)

If I remove the below code from Podfile.
`

> if target.name == 'react-native-google-maps'
>         target.build_configurations.each do |config|
>           config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
>           paths = Array["\"$(inherited)\"", "\"$(SRCROOT)/Google-Maps-iOS-Utils/src/Heatmap\""]
>           config.build_settings['HEADER_SEARCH_PATHS'] = paths.uniq
>           puts config.build_settings['HEADER_SEARCH_PATHS']
>         end
>       end
>       target.build_configurations.each do |config|
>         # config.build_settings['ENABLE_BITCODE'] = 'NO'
>         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>       end

`

I ran into this issue when trying to run 'pod install'

![Screenshot 2022-09-08 at 19 20 36](https://user-images.githubusercontent.com/10684648/189174927-5538c31b-40d2-4b02-bf61-ca2ad200e4e8.png)

### React Native Maps Version

1.3.1

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.69.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13

**Comment by MarcoBrugali255** [comment]
Same problem

**Comment by Willham12** [comment]
https://github.com/react-native-maps/react-native-maps/discussions/4389
https://github.com/react-native-maps/react-native-maps/discussions/4301

**Comment by billnbell** [comment]
See my work around as @Willham12 linked to.

**Comment by Simon-TechForm** [comment]
Closing in favour of the linked issues/discussion :)
