### ISSUE TITLE
Initial load of map will show Africa first then jump to initialCamera

### ISSUE THREAD

**Issue by KaisSalha** [react-native-maps/react-native-maps#4442]
### Summary

Similar to https://github.com/react-native-maps/react-native-maps/issues/4343, the map renders in Africa then jumps to initialCamera location. `initialRegion` is fixed but not `initialCamera`.

The issue is that `initialCamera` is not in the props before the map is ready as can be seen in the lines below:
[https://github.com/react-native-maps/react-native-maps/blob/2c2fef70b8d529b740db353985c3e9320a8e7762/src/MapView.tsx#L1041-L1077]( https://github.com/react-native-maps/react-native-maps/blob/2c2fef70b8d529b740db353985c3e9320a8e7762/src/MapView.tsx#L1041-L1077)

### Reproducible sample code

```TSX
<MapView
        ref={mapRef}
        provider={PROVIDER_GOOGLE}
        mapType={MAP_TYPES.STANDARD}
        style={StyleSheet.absoluteFillObject}
        showsIndoors={false}
        rotateEnabled={false}
        pitchEnabled={false}
        showsPointsOfInterest={false}
        initialCamera={{
          center: geoLocToLatLng(center),
          zoom: startingZoom,
          pitch: 0,
          heading: 0,
          altitude: 0,
        }}
        region={undefined}
        onRegionChangeComplete={handleRegionChangeComplete}
        onMapLoaded={handleRegionChangeComplete}
        customMapStyle={MAP_STYLE}
        maxZoomLevel={MAX_ZOOM}
        minZoomLevel={MIN_ZOOM}
        onLayout={(event) => {
          const { height } = event.nativeEvent.layout;

          setMapHeight(height);
        }}
>
...
</MapView>
```

### Steps to reproduce

Code shows steps

### Expected result

My map should go directly to my initialCamera

### Actual result

It instead goes to Africa

### React Native Maps Version

^1.1.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.67.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 4 (Android 13)

**Comment by Simon-TechForm** [comment]
Hello @KaisSalha 👋 

I've just released a beta version that should fix the issue - could you try it out and report back to me? :)
