### ISSUE TITLE
Missing inertia / momentum when zooming on Google Map

### ISSUE THREAD

**Issue by Pitouli** [react-native-maps/react-native-maps#4450]
### Summary

In the standard Google Maps App, when you zoom in or out quickly, there is inertia before the zoom stop, which makes the map feel more natural. It works well with react-native-maps on iOS with Apple Maps, but it does not work on Android with Google Maps (not yet tested on iOS with Google Maps)

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

Quickly zoom in or out

### Expected result

The zoom should continue with inertia

### Actual result

The zoom immediately stop, but since you often pan a bit the map at the same time and that panning HAS inertia, the map is not completely frozen either, which makes it feel even weirder.

### React Native Maps Version

1.2.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.3

### What version of Expo are you using?

SDK 46

### Device(s)

Samsung Galaxy S12FE

### Additional information

Another ticket has been opened few years ago about the same issue (but using the term "momentum" instead of "inertia", that's why I did not found it first): https://github.com/react-native-maps/react-native-maps/issues/2579 So I suppose there is few hopes to find a solution ^^

**Comment by Simon-TechForm** [comment]
Hi @Pitouli 👋

This is not a bug in `react-native-maps`, but how the Google Maps SDK behaves on Android. I don't know why Google decided not to match the behaviour in their Maps app vs the Maps SDK, but it's quite easy to reproduce this in a native project, following Google's [quick start guide](https://developers.google.com/maps/documentation/android-sdk/start).

If you would like to see this changed, I'd recommend opening an issue on Google's public issue tracker :)

**Comment by Pitouli** [comment]
Aw ! 😮 I did not knew that, thank you for the information! 🙂
And I will open a ticket at Google then 😛
