### ISSUE TITLE
react-native-maps crash undefined is not a function

### ISSUE THREAD

**Issue by matan-atiya** [react-native-maps/react-native-maps#4467]
### Summary

Updated to the latest version (from 0.31.0) and now each time I try to render child (Polygon, Marker, etc) the app is crashing with "this.getNativeComponent undefined"

![Screen Shot 2022-09-29 at 10 30 39](https://user-images.githubusercontent.com/92845991/192969778-2411e05f-a74f-4f22-b6d1-6f70ae1ec021.png)

### Reproducible sample code

```TSX
import React from 'react';
import {
  Platform,
} from 'react-native';
import MapView, {Polygon, PROVIDER_DEFAULT, PROVIDER_GOOGLE} from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      provider={Platform.OS === 'ios' ? PROVIDER_DEFAULT : PROVIDER_GOOGLE} 
      mapType={'hybrid'}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    >
<Polygon key={'polygon'} coordinates={[{
        latitude: 42,
        longitude: 30}]} />
</MapView>
  );
}
```

### Steps to reproduce

* update to latest version react native and react native maps
* use the snippet above 
* app crash with the error "this.getNativeComponent undefined"

### Expected result

the app renders a map 

### Actual result

app  crashing

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.70.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 (iOS 16) | Android Pixel 5 (API 31)

**Comment by idanplannter** [comment]
same problem

**Comment by matan-atiya** [comment]
Hi, it seems this bug isn't so much related to the react-native-maps package, I found the problem and fix it.

It seems that the Babel plugins I added to my project in the old react native version in the bable.confing.js file cause the problem. Although adding them to that file worked fine in the old version, in the new one it seems to cause the metro bundler to link only parts of the packages to the application, and that caused the map view to be loaded in the app, and for the other components that are imported from the package like Marker, Polygon, etc to be undefined. And that caused the app to crash when using them.

Moving the Babel plugins to .babelrc file fix my issue - hope it will help others who encountered the same problem.

![Screen Shot 2022-10-02 at 0 41 42](https://user-images.githubusercontent.com/92845991/193429390-07354c69-da1e-4cf8-96a8-289ddf359b0e.png)

**Comment by ivandova** [comment]
I had the same issue and thanks to @matan-atiya's advise I found out that in my case I have to remove '@babel/plugin-proposal-class-properties' plugin from babel.config.js (moving it to .babelrc didn't work for me).

However, "mobx" package requires that plugin so I have to keep it. Eventually I had to use "overrides" to bypass the plugin for the files in "node_modules" to make it work.
```

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
  ],
  overrides: [
    {
      test: fileName => !fileName.includes('node_modules'),
      plugins: [[require('@babel/plugin-proposal-class-properties'), { loose: true }]],
    },
  ],
};

```
Hope this helps somebody.

**Comment by NikMsh** [comment]
Facing this issue, tried all methods above and it doesn't help
`TypeError: this.getNativeComponent is not a function (it is undefined) This error is located at:
    in MapPolyline (created by MapViewDirections)` the same for Markers

**Comment by matan-atiya** [comment]
Hi, I upgraded to the last React Native version currently available - 0.72.4, and the last React Native Maps and mobx that are currently available. the plugin that case for me the bug in the first place is not needed in those versions anymore so try to update your project and remove the plugin if it is not necessary, maybe that will help.

**Comment by NikMsh** [comment]
Hi, thanks for your answer it helped me to find the place of a problem! I'm using the latest react-native - 0.72.4 with expo, react-native-maps - 1.7.1, and @reduxjs/toolkit - 1.9.5 in my project. I've used private js methods in some of the classes and needed `@babel/plugin-transform-private-methods` to support them. After removing all `#` before methods and fields deleted `@babel/plugin-transform-private-methods` from config and the problem disappeared.
If someone is facing the similar problem, just check all your plugins at first and try to remove them if you can.

**Comment by SwhiteMHC** [comment]
I am having the same issue. I am not using the plugins mentioned.

React Native Maps Version
1.7.1

What platforms are you seeing the problem on?
Android

React Native Version
0.72.4

What version of Expo are you using?
SDK 49

Device(s)
Samsung Galaxy A14

My babel.config.js:
```
module.exports = {
  presets: ['babel-preset-expo'],
};
```

My .babelrc.json:
```
{
  "plugins": ["nativewind/babel", "module:react-native-dotenv"]
}
```

**Comment by SwhiteMHC** [comment]
#4901

**Comment by lslima91** [comment]
for people landing here:
in my example I had to avoid transpiling **react native** maps with the **transform-private-methods** (you most likely will have a different plugin here)

```
  overrides: [
    // this plugins crashes react native maps markers
    {
      test: (fileName) => !fileName.includes('node_modules/react-native-maps'),
      plugins: [
        [require('@babel/plugin-transform-private-methods'), { loose: true }],
      ],
    },
  ],
}
```

**Comment by lid3rs** [comment]
> for people landing here: in my example I had to avoid transpiling **react native** maps with the **transform-private-methods** (you most likely will have a different plugin here)
> 
> ```
>   overrides: [
>     // this plugins crashes react native maps markers
>     {
>       test: (fileName) => !fileName.includes('node_modules/react-native-maps'),
>       plugins: [
>         [require('@babel/plugin-transform-private-methods'), { loose: true }],
>       ],
>     },
>   ],
> }
> ```

Still valid w/ latest react-native and maps to date

**Comment by jaalvarez2818** [comment]
I have updated to `"react-native": "0.74.3"` and` "react-native-maps": "^1.15.6"`

My .babelrc
`{
  "presets": [
    "module:metro-react-native-babel-preset"
  ],
  "plugins": [
    "react-native-reanimated/plugin",
    "module:react-native-dotenv",
    "react-native-paper/babel",
     ["@babel/plugin-proposal-class-properties", { "loose": false }]
     ["@babel/plugin-transform-private-methods", { "loose": false }]
  ],
}`

` ERROR  TypeError: this.getNativeComponent is not a function (it is undefined)

This error is located at:
    in MapCircle (created by Maps)
    in AIRMap (created by MapView)
    in MapView (created by Maps)
    in RCTView (created by View)
    in View (created by Maps)
    in Maps (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by Drawer)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by Drawer)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by Drawer)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by Drawer)
    in RCTView (created by View)
    in View (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Drawer)
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by Root)
    in PersistGate (created by Root)
    in Provider (created by Root)
    in Root
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
`

What I can do?

**Comment by DMRam** [comment]
> @jaalvarez2818 In my case, I accessed node_modules -> react-native-maps -> lib -> MapMarker.js (commented "getNativeComponent") and MapPolyline.js (commented "getNativeComponent").

It works for me, but how could impact later...?

thx in advance!

**Comment by myBlazingsun** [comment]
> for people landing here: in my example I had to avoid transpiling **react native** maps with the **transform-private-methods** (you most likely will have a different plugin here)
> 
> ```
>   overrides: [
>     // this plugins crashes react native maps markers
>     {
>       test: (fileName) => !fileName.includes('node_modules/react-native-maps'),
>       plugins: [
>         [require('@babel/plugin-transform-private-methods'), { loose: true }],
>       ],
>     },
>   ],
> }
> ```

There are some problems in your answer, the following is my modification:
```
    overrides: [
      {
        test: (fileName) => {
          return !fileName.includes("node_modules\\react-native-maps");
        },
        plugins: [
          ["@babel/plugin-transform-class-properties", { loose: true }],
          ["@babel/plugin-transform-private-methods", { loose: true }],
          [
            "@babel/plugin-transform-private-property-in-object",
            { loose: true },
          ],
        ],
      },
    ],

```

**Comment by ashishneomenta** [comment]
> for people landing here: in my example I had to avoid transpiling **react native** maps with the **transform-private-methods** (you most likely will have a different plugin here)
> 
> ```
>   overrides: [
>     // this plugins crashes react native maps markers
>     {
>       test: (fileName) => !fileName.includes('node_modules/react-native-maps'),
>       plugins: [
>         [require('@babel/plugin-transform-private-methods'), { loose: true }],
>       ],
>     },
>   ],
> }
> ```

This solution 100% worked for me. Thank you you made my day

**Comment by meemalif** [comment]
I have been facing the same issue, and I have tried all the possible iterations in babel.config.js mentioned above. I tried removing/commenting node_modules -> react-native-maps -> lib -> MapMarker.js (commented "getNativeComponent"), which worked but as expected crashed my application in production. Everything was working perfectly fine 1 week ago, then out of nowhere this issue arises, now whenever I open maps screen in my app, it just crashes. 
       "react": "18.2.0",
        "react-native": "0.74.3",
        "react-native-maps": "^1.18.0",
        "expo": "^51.0.24",

**Comment by ashishneomenta** [comment]
@meemalif use "react-native-maps": "1.15.2",

One thing never use ^ in package json version like "^1.18.0"

**Comment by myBlazingsun** [comment]
> @meemalif use "react-native-maps": "1.15.2",
> 
> One thing never use ^ in package json version like "^1.18.0"

why?

**Comment by ashishneomenta** [comment]
we are not sure what changes will be in new Package. so safer side should not use ^ sign. some time it suddenly started issue due to some package and dependency auto update.
