### ISSUE TITLE
Do we have to ask for permission or does this library handle it?

### ISSUE THREAD

**Issue by miladdev85** [react-native-maps/react-native-maps#4469]
### Summary

In an older RN version where we use react-native-map version 0.30.1 - we don't have to manually ask for permission. We only have the prop `showsUserLocation`. But do we have to ask for location permission in the latest version of react-native-maps?

Thank you! 

### Reproducible sample code

```TSX
<MapView
        showsUserLocation
        initialRegion={{
          latitude: locations[0]?.lat,
          longitude: locations[0]?.lng,
          latitudeDelta: 0.3,
          longitudeDelta: 0.4,
        }}
        style={styles.map}>
        {locations.map((marker, index) => (
          <Marker
            key={index}
            coordinate={{ latitude: marker.lat, longitude: marker.lng }}
            title={marker.name}
            description={marker.streetAddress}
          />
        ))}
      </MapView>
```

### Steps to reproduce

`showsUserLocation` does not trigger location permission question. Don't know if this is expected or not. 

### Expected result

Not sure...

### Actual result

No permission question.

### React Native Maps Version

1.3.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.69.3

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 Pro

**Comment by Simon-TechForm** [comment]
Hi @miladdev85 👋 

Please check out [releases](https://github.com/react-native-maps/react-native-maps/releases) or the [changelog file](https://github.com/react-native-maps/react-native-maps/blob/master/CHANGELOG.md). [Hint: v1.0.0] :)
