### ISSUE TITLE
Passing custom Google Maps styles throws error on Android

### ISSUE THREAD

**Issue by dimitarspassov** [react-native-maps/react-native-maps#4473]
### Summary

I'm trying to set some custom styles to the `MapView`, which uses Google Maps, but for some reason I get an error on Android. There are no issues on iOS, where the custom styles I get from [the Styling Wizard](https://mapstyle.withgoogle.com/) are applied correctly. The problem happens on my Android emulator and on real Android device as well.

There is a strange case: If the app is running without me setting the `customMapStyle` prop initially, the map renders with default styles as expected. Then, if I add the styles and the Expo hot reload refreshes the page, the map styles get updated and no errors are thrown.

Even an empty array for `customMapStyle` does not work and causes the same error.

### Reproducible sample code

```TSX
<MapView
	// customMapStyle={[]} This is also problematic

        // The array with custom style object is simplified for the demo
	customMapStyle={[
		{
			elementType: 'geometry',
			stylers: [
				{
					color: '#242f3e'
				}
			]
		}
	]}
	provider={PROVIDER_GOOGLE}
	style={{
		width: 300,
		height: 300
	}}
	initialRegion={{
		latitude: 37.78825,
		longitude: -122.4324,
		latitudeDelta: 0.0922,
		longitudeDelta: 0.0421
	}}
/>
```

### Steps to reproduce

1. Generate an Expo project;
2. Create a simple `MapView`;
3. Add some valid value to `customMapStyle`;
4. Open on Android device or emulator - the error will appear.

### Expected result

I expected to see the map working fine with custom styles as it does on iOS.

### Actual result

<img width="365" alt="Screenshot 2022-10-05 at 16 24 06" src="https://user-images.githubusercontent.com/18030506/194074516-19317b24-da47-4859-9729-9a8461d3e0fb.png">

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.69.5

### What version of Expo are you using?

SDK 46

### Device(s)

Samsung Galaxy S21,  Pixel_4_API_33 (Emulator)

**Comment by Airwarfare** [comment]
I also have this problem as well, on both emulator and psychical devices even with an API key set

**Comment by eprice122** [comment]
I have this issue as well
