### ISSUE TITLE
Support for Google Maps' map ID?

### ISSUE THREAD

**Issue by guillaumegaluz** [react-native-maps/react-native-maps#4475]
### Summary

Google Maps Platform has a neat feature that allows to customize the style depending on the zoom level. But It's only on the new editor (through the console) and this editor doesn't allow to export the JSON: you can only assign a style to a [map ID](https://developers.google.com/maps/documentation/get-map-id#javascript)

Is there a way for me to use a map ID with this package?

PS: apologies for submitting this as a bug, i couldn't find a way to just propose a feature.

### Reproducible sample code

```TSX
-
```

### Steps to reproduce

-

### Expected result

-

### Actual result

-

### React Native Maps Version

0.30.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.5

### What version of Expo are you using?

SDK 46

### Device(s)

iPhone

**Comment by Simon-TechForm** [comment]
Hi @guillaumegaluz 👋 

Check out https://github.com/react-native-maps/react-native-maps/discussions/4368 :)
