### ISSUE TITLE
Unable to Change the Position of Google Icon at Left Bottom Corner

### ISSUE THREAD

**Issue by Jocelyn59435** [react-native-maps/react-native-maps#4479]
### Summary

Hi just wondering if there is a way to change the position of the google icon at the left bottom Corner?
Currently, I did not find a way to do this on `<MapView />.`
Thanks in advance.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/63270296/195242882-2c544125-883e-4d4c-a02b-aa88f08f8198.png">

### Reproducible sample code

```TSX
not applicable
```

### Steps to reproduce

not applicable

### Expected result

Able to remove or change the position of the google icon at the left bottom corner.

### Actual result

Unable to remove or change the position of the google icon at the left bottom corner.

### React Native Maps Version

not applicable

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 pro

**Comment by Simon-TechForm** [comment]
You can use `mapPadding` (see [props docs)](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#props) 👍

**Comment by Jocelyn59435** [comment]
Thanks.
