### ISSUE TITLE
Support for XCODE 14 deployment target minimums

### ISSUE THREAD

**Issue by dwkd** [react-native-maps/react-native-maps#4484]
### Summary

Xcode 14 requires [IPHONEOS_DEPLOYMENT_TARGET >= 11](https://developer.apple.com/support/xcode)

Thank you

### Reproducible sample code

```TSX
build on Xcode 14
```

### Steps to reproduce

build on Xcode 14

### Expected result

buld succeed

### Actual result

build fail - deployment target requires >= 11

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

current

### What version of Expo are you using?

Not using Expo

### Device(s)

build

**Comment by danidaryaweesh** [comment]
@dwkd could you provide more information? It is working for me and I'm using RN 0.68.4 and version 0.31.1 of this library with Xcode 14.

**Comment by Simon-TechForm** [comment]
As mentioned by @danidaryaweesh, this is down to your own project settings and not `react-native-maps`.
