### ISSUE TITLE
Infinite Callback Loop when used with expo-location

### ISSUE THREAD

**Issue by tylercallison** [react-native-maps/react-native-maps#4486]
### Summary

When using `react-native-maps` `<MapView />` and `expo-location`, there is an infinite loop on location change within an `expo-location` callback on an iOS simulator.

Specifically here:
```tsx
TaskManager.defineTask(locTaskName, ({ data, error }) => {
  if (error) {
    console.warn("Failed to get location data");
    return;
  }
  const locations = data as LocationObject;

  // This line will loop infinitely
  console.log("Received new locations", locations);
});
```

If the `<MapView />` is commented out within the repo provided, the callback will no longer be called in a loop.

### Reproducible sample code

```TSX
import * as React from "react";
import { View, StyleSheet } from "react-native";
import * as Location from "expo-location";
// You can import from local files
import * as TaskManager from "expo-task-manager";
// or any pure javascript modules available in npm
import { LocationObject } from "expo-location";
import MapView from "react-native-maps";

const locTaskName = "backgroundLocationTask";

TaskManager.defineTask(locTaskName, ({ data, error }) => {
  if (error) {
    console.warn("Failed to get location data");
    return;
  }
  const locations = data as LocationObject;

  // This line will loop infinitely
  console.log("Received new locations", locations);
});

export default function App() {
  async function startLocationTracking() {
    const foreground = await Location.requestForegroundPermissionsAsync();
    if (foreground.status !== "granted") {
      return;
    }

    if (await Location.hasStartedLocationUpdatesAsync(locTaskName)) {
      await Location.stopLocationUpdatesAsync(locTaskName);
    }

    Location.startLocationUpdatesAsync(locTaskName, {
      accuracy: Location.Accuracy.Highest,
      distanceInterval: 5,
    });
  }

  React.useEffect(() => {
    startLocationTracking();
  }, []);

  return (
    <View style={styles.container}>
      <MapView
        style={styles.container}
        followsUserLocation={true}
        showsUserLocation={true}
        showsCompass={false}
        showsMyLocationButton={false}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    position: "absolute",
    height: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
});
```

### Steps to reproduce

Clone the repo: https://github.com/tylercallison/expo-location-infinite-loop

`git clone https://github.com/tylercallison/expo-location-infinite-loop.git`

`cd expo-location-infinite-loop`
`npm install`
`npx expo prebuild`
`npx expo run:ios`

Wait for the simulator to open and then give location access to the application. Once this is given, attempt to change the location of the device in `Features > Location` and watch the console output run an infinite loop

### Expected result

The callback should not be infinite looping and only be called once on location change. 

### Actual result

The callback is infinite looping on location change when `<MapView />` is present. This will not occur when the `<MapView />` is commented out

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.69.6

### What version of Expo are you using?

SDK 46

### Device(s)

iPhone 14 Simulator

**Comment by tylercallison** [comment]
On further review, this is a problem when `showsUserLocation` is set to `true`

**Comment by michaelluzpaulo** [comment]
showsUserLocation definido como **true** ferra e deixa o esquema em looping infinito demorei um final de semana pra achar o problema e entender isso pqp.

**Comment by tylercallison** [comment]
@michaelluzpaulo where in the code did you find the source of this issue?

**Comment by michaelluzpaulo** [comment]
@tylercallison quando se usa expo-location + expo-task-manager + react-native-maps e se aciona no **showsUserLocation={true}** por alguma razão no mapkit acho que também no android maps(vou confirmar) a troca de coordenada aciona a task continua em loop eu penso que isso "meu achismo baseado no que acontece e em meus anos de programação" deve ser porque internamente o react-native-maps dev usa uma task manager por trás e deve estar ocorrendo algum conflito porque mudando para false funciona perfeitamente como deveria e como a documentação nos fala para fazer. 
Solução: deixar como false e fazer manualmente o que o showsUserLocation faz.
-------------
sorry my english is still improving

**Comment by AprilPolubiec** [comment]
Is the solution just to set showsUserLocation={false}? Because I tried that and am still getting the infinite loop :(
