### ISSUE TITLE
Error while updating property 'showUserLocation' of a view managed by: AIRMap

### ISSUE THREAD

**Issue by ombogdanJoinToIt** [react-native-maps/react-native-maps#4487]
### Summary

<img width="345" alt="image" src="https://user-images.githubusercontent.com/109798616/196221303-692e20b0-b522-4f09-9d33-2c0f6e68f923.png">

### Reproducible sample code

```TSX
my code works great. But when i made a build yesterday i got this error.
```

### Steps to reproduce

just make build on android

### Expected result

my location will show on map

### Actual result

<img width="381" alt="image" src="https://user-images.githubusercontent.com/109798616/196222106-01931450-a7f1-4bab-b693-19d7c978b61f.png">

### React Native Maps Version

1.3.1 and 0.29.3

### What platforms are you seeing the problem on?

Android

### React Native Version

0.63

### What version of Expo are you using?

Not using Expo

### Device(s)

all

**Comment by SyedShahbazHussain** [comment]
I'm also facing the same issue for the last 3 days. Before that, it was working fine.

**Comment by ombogdanJoinToIt** [comment]
https://developers.google.com/android/guides/releases
![telegram-cloud-photo-size-2-5366234046767677625-y](https://user-images.githubusercontent.com/109798616/196362318-bc049a60-44d4-4ef0-a25f-c2d35652f723.jpg)

**Comment by romipraveen1** [comment]
Yes, I'm also facing the same issue for the last 3 days.

**Comment by romipraveen1** [comment]
> https://developers.google.com/android/guides/releases ![telegram-cloud-photo-size-2-5366234046767677625-y](https://user-images.githubusercontent.com/109798616/196362318-bc049a60-44d4-4ef0-a25f-c2d35652f723.jpg)

How can I use this on code ?

**Comment by Simon-TechForm** [comment]
If you are experiencing this, make sure that you aren't depending on `com.google.android.gms:play-services-location:21.0.0` (or the `+` range which is discouraged) in your build.gradle. `react-native-maps` haven't been updated to support `21.0.0` yet and thus requires `20.0.0`.

**Comment by Lavanjan** [comment]
Downgrade the Google Play Services version  **googlePlayServicesVersion = "+"**  to  **googlePlayServicesVersion = "17.0.0"** on project level build.gradle file.

**Comment by Lavanjan** [comment]
Downgrade the Google Play Services version googlePlayServicesVersion = "+"  as  googlePlayServicesVersion = "17.0.0" on project level build.gradle file.

**Comment by ombogdanJoinToIt** [comment]
> googlePlayServicesVersion
i am getting an error
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/109798616/196444247-464fc56b-5877-4045-8763-1462bf8d6378.png">

**Comment by ombogdanJoinToIt** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/109798616/196491962-2350325f-6f1c-43c5-bc53-3e9984218321.png">

**Comment by MAliHassn** [comment]
> Downgrade the Google Play Services version, googlePlayServicesVersion = "+" as googlePlayServicesVersion = "17.0.0" on project level build.gradle file.

yup its working

**Comment by ombogdanJoinToIt** [comment]
when you plan to update the library??

**Comment by RobertFOConnor** [comment]
Any plans to update this to support play-services-location:21.0.0 -> and beyond??

**Comment by siemya** [comment]
I am using 21.0.1, which is a must for me and showsUserLocation is crashing due to this. 

@RobertFOConnor Were you able to find a solution?

**Comment by huy-lv** [comment]
Please open this issue and upgrade the library :D

**Comment by guyzmo** [comment]
Hello I'm having a similar issue, using expo managed, [which is using play-services-maps@18.0.0](https://github.com/expo/expo/blob/0746a58be3b2549f5d834816d24efd9853d1c20a/packages/expo-maps/android/build.gradle#LL87C68-L87C68).

According to @Simon-TechForm's [comment](https://github.com/react-native-maps/react-native-maps/issues/4487#issuecomment-1282053134) it should work fine, but according to @Lavanjan it should be 17.0.0.

I'm afraid to break other things up with downgrading play services to v17… So could some clarification be made on what to do?

**Comment by capaj** [comment]
I was able to fix this by adding this line in android/app/build.gradle
```
    implementation 'com.google.android.gms:play-services-location:20.0.0'
```

which had no negative effect on the rest of my app.

**Comment by ChromeQ** [comment]
With expo SDK 49 being released recently this issue has raised up again, shouldn't react-native-maps be updated to work with `com.google.android.gms:play-services-location` v21+ ?

I have opened a couple of issues before I found this one:
https://github.com/expo/expo/issues/23396
https://github.com/react-native-maps/react-native-maps/issues/4788

**Comment by cnhuz** [comment]
same error

**Comment by AzranAzwer** [comment]
add googlePlayServicesVersion = "17.0.0" on project level build.gradle file.

**Comment by Manish88879** [comment]
I can't find this googlePlayServicesVersion

**Comment by Lavanjan** [comment]
> I can't find this googlePlayServicesVersion

@Manish88879 Please locate the following code snippet in your Android project's build.gradle file. If it's not present, kindly add it. 

`ext {
    googlePlayServicesVersion = "17.0.0"
    firebaseVersion = "17.3.4"
    buildToolsVersion = "30.0.2"
    minSdkVersion = 21
    compileSdkVersion = 31
    targetSdkVersion = 31
    ndkVersion = "21.4.7075529"
}
`

**Comment by Manish88879** [comment]
Thanks It Worked
