### ISSUE TITLE
[Regression] 'RCTConvert+AirMap.h' file not found

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-maps/react-native-maps#4492]
### Summary

This issue is quite similar to https://github.com/react-native-maps/react-native-maps/issues/3597

Happening now with Expo Dev Clients

I've updated some libraries in `Expo`. One of those is `expo-firebase-analytics`.
The new version of `expo-firebase-analytics` (https://docs.expo.dev/versions/latest/sdk/firebase-analytics/) implies adding this config:

```
{
  "expo": {
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ]
  }
}
```

As you can see in the last comments in https://github.com/react-native-maps/react-native-maps/issues/3597, some other people are having the same issue after adding that ` "useFrameworks": "static" ` config.

### Reproducible sample code
It is actually a matter of dependencies.

Add these dependencies:

```
"expo-build-properties": "~0.3.0",
"expo-firebase-analytics": "~7.2.0",
"react-native-maps": "0.31.1",
```

RNMaps is on `0.31.1` because it's the last one supported by the current Expo version.

### Steps to reproduce

Just build `eas build -p ios`.

### Expected result

Build go green

### Actual result

Build red.

```
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapWMSTileManager.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapWMSTile.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapUrlTile.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapURLTileManager.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolylineManager.m

❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m:17:9)

  15 | #import <React/RCTViewManager.h>
  16 | #import <React/UIView+React.h>
> 17 | #import "RCTConvert+AirMap.h"
     |         ^ 'RCTConvert+AirMap.h' file not found
  18 | #import "AIRGoogleMapPolyline.h"
  19 | 
  20 | @interface AIRGoogleMapPolylineManager()
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolyline.m

⚠️  (/Users/expo/Library/Developer/Xcode/DerivedData/NoFilter-fjavmkobuxfkzfckwbwnupmjterw/Build/Intermediates.noindex/ArchiveIntermediates/NoFilter/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapPolyline.dia:1:1)

CompileC /Users/expo/Library/Developer/Xcode/DerivedData/NoFilter-fjavmkobuxfkzfckwbwnupmjterw/Build/Intermediates.noindex/ArchiveIntermediates/NoFilter/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapPoly...
^ Could not read serialized diagnostics file: error(in target 'react-native-google-maps' from project 'Pods')
(warning truncated)
▸ ** ARCHIVE FAILED **
```

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.5

### What version of Expo are you using?

SDK 46

### Device(s)

Build time

**Comment by Saujanmgr** [comment]
I had this error but i solve using this [stackflow](https://stackoverflow.com/questions/63261101/rctconvertairmap-h-file-not-found-error-on-react-native-on-ios)

`$(SRCROOT)/../node_modules/react-native-maps/lib/ios/AirMaps` this should add using xcode; xcode > project > build setting > Header Search Path. add this to debug and release.

after this it will create another problem which i just created an issue #4497

**Comment by pinpong** [comment]
https://github.com/react-native-maps/react-native-maps/pull/4417

**Comment by Simon-TechForm** [comment]
Please reference https://github.com/react-native-maps/react-native-maps/discussions/4389

**Comment by MarcHbb** [comment]
I have the exactly same issue with the same dependencies with the same versions, working with an expo managed workflow 
Any solutions ?

**Comment by Bilal-Abdeen** [comment]
Check out my comment on  [#3597](https://github.com/react-native-maps/react-native-maps/issues/3597#issuecomment-1368291121)
