### ISSUE TITLE
library not found for -lreact-native-maps

### ISSUE THREAD

**Issue by naveensaini4u** [react-native-maps/react-native-maps#4496]
### Summary

I am getting error `library not found for -lreact-native-maps` when trying to create an Archive for ios but it is working in the development mod.

I am using RN Version-> 0.64.0
react-native-maps -> 1.3.2

### Reproducible sample code

```TSX
<MapView
                    style={{width:'100%',height:"100%"}}
                    region={{
                        latitude: 37.78825,
                        longitude: -122.4324,
                        latitudeDelta: 0.015,
                        longitudeDelta: 0.0121,
                    }}
                    >
                    </MapView>
```

### Steps to reproduce

just install react-native-map and install pods.
After that start building Archive.

### Expected result

It should generate a BUILD to upload on TestFlight.

### Actual result

![Uploading Screenshot 2022-10-26 at 4.51.15 PM.png…]()

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.64.0

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 12

### Additional information

"react-native": "0.64.0",
 "react-native-maps": "^1.3.2",

**Comment by naveensaini4u** [comment]
<img width="976" alt="Screenshot 2022-10-26 at 4 56 34 PM" src="https://user-images.githubusercontent.com/41486874/198014679-3433445d-984c-4c30-aa89-a45a6cd868f4.png">

**Comment by Simon-TechForm** [comment]
Hi @naveensaini4u 👋 

I'm archiving apps including `react-native-maps` regularly without issues. You'd have to provide a minimal reproducible sample code to move this along. When you do, I'll re-open this 👍
