### ISSUE TITLE
Build error: 'Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h' file not found in iOS

### ISSUE THREAD

**Issue by Saujanmgr** [react-native-maps/react-native-maps#4497]
### Summary

Using static link React-native-map product GMUHeatmapTileLayer.h error. I am trying to create firebase and map app, to use firebase it need `use_frameworks! :linkage => :static` using that, map does not work and produce multiple errors.

I followed this issue [stackoverflow question](https://stackoverflow.com/questions/63261101/rctconvertairmap-h-file-not-found-error-on-react-native-on-ios) to solve airmaps problem. Now i have `GMUHeatmapTile.h` file not found error.

without using `use_frameworks! :linkage => :static` project will build successfylly.

Please look into my podfile below is sample code.

---

I build a simple test project in github please look into it:
1. [Project](https://github.com/Saujanmgr/rn-firebase-ios)
2. [Pod file](https://github.com/Saujanmgr/rn-firebase-ios/blob/main/ios/Podfile)
---
Tools Versions:
1. pod: 1.11.3
2. react-native: 0.70.3
3. React-native Firebase: 16.2.0
4. Ruby: 2.7.5p203 (recommanded by react-native i.e. [.ruby-version])
5. OS: macOS Ventura 13.0
6. System: Macbook Pro with M1 Pro chip

### Reproducible sample code

```TSX
# POD FILE

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'rnmaptest' do
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps/'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps/'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_frameworks! :linkage => :static # Using Static
  config = use_native_modules!
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    #:flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'rnmaptestTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
    end

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Steps to reproduce

1. create new type script project
2. add react-native-map in project using npm `npm install react-native-maps`
3. add my pod file code into the project ios/podfile
4. and run project

### Expected result

1. Successful build using `use_frameworks! :linkage => :static` 

### Actual result

info Found Xcode workspace "rnmaptest.xcworkspace"
info Building (using "xcodebuild -workspace rnmaptest.xcworkspace -configuration Debug -scheme rnmaptest -destination id=DE14F66E-8304-4439-85C5-FCD9D457A08F")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening rnmaptest.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace rnmaptest.xcworkspace -configuration Debug -scheme rnmaptest -destination id=DE14F66E-8304-4439-85C5-FCD9D457A08F

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 4f5c74e2bcfeba64626881744056b867
Build description path: /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/XCBuildData/4f5c74e2bcfeba64626881744056b867-desc.xcbuild
....
....
....

CompileC /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')
    cd /Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios13.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Index.noindex/DataStore -iquote /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-generated-files.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-own-target-headers.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-all-target-headers.hmap -iquote /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-project-headers.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/react-native-google-maps/include -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public/React-callinvoker -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Google-Maps-iOS-Utils/src/Heatmap -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Private/React-bridging/react/bridging -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-bridging/react_bridging.framework/Headers -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources-normal/arm64 -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources/arm64 -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/react-native-google-maps -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/RCT-Folly -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-Core -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-cxxreact -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsiexecutor -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsinspector -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-logger -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-perflogger -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/Yoga -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/fmt -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/glog -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/libevent -F/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/GoogleMaps/Maps/Frameworks -DHAVE_GOOGLE_MAPS\=1 -DHAVE_GOOGLE_MAPS_UTILS\=1 -fno-modules -include /Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Target\ Support\ Files/react-native-google-maps/react-native-google-maps-prefix.pch -MMD -MT dependencies -MF /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.d --serialize-diagnostics /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.dia -c /Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m -o /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o
In file included from /Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m:8:
/Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9: fatal error: 'Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h' file not found
#import <Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

CompileC /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmap.o /Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')
    cd /Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios13.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Index.noindex/DataStore -iquote /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-generated-files.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-own-target-headers.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-all-target-headers.hmap -iquote /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/react_native_google_maps-project-headers.hmap -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/react-native-google-maps/include -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public/React-callinvoker -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Google-Maps-iOS-Utils/src/Heatmap -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Public -I/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Headers/Private/React-bridging/react/bridging -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-bridging/react_bridging.framework/Headers -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources-normal/arm64 -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources/arm64 -I/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/DerivedSources -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/react-native-google-maps -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/RCT-Folly -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-Core -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-cxxreact -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsiexecutor -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-jsinspector -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-logger -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/React-perflogger -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/Yoga -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/fmt -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/glog -F/Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Products/Debug-iphonesimulator/libevent -F/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/GoogleMaps/Maps/Frameworks -DHAVE_GOOGLE_MAPS\=1 -DHAVE_GOOGLE_MAPS_UTILS\=1 -fno-modules -include /Users/macm1/Documents/IosTest/rn-firebase-ios/ios/Pods/Target\ Support\ Files/react-native-google-maps/react-native-google-maps-prefix.pch -MMD -MT dependencies -MF /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmap.d --serialize-diagnostics /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmap.dia -c /Users/macm1/Documents/IosTest/rn-firebase-ios/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.m -o /Users/macm1/Library/Developer/Xcode/DerivedData/rnmaptest-hhwxcsujjwmbotalxyhyktttdrwk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmap.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmap.o

warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'rnmaptest' from project 'rnmaptest')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'rnmaptest' from project 'rnmaptest')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-bridging' from project 'Pods')

** BUILD FAILED **

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.3

### What version of Expo are you using?

Not using Expo

### Device(s)

iphone 13 (simulator), iphone 14 (simulator), iphone 6 (physical)

### Additional information

This bug only happen if we try to use `use_frameworks! :linkage => :static` but we need to use firebase. And this is the only way. I want to have hassle free out of the box solution or pod file solution. I saw different solution but most are them are for old version and not work at all.

**Comment by pinpong** [comment]
https://github.com/react-native-maps/react-native-maps/pull/4417

**Comment by Saujanmgr** [comment]
I solved this issue by following this [guide](https://github.com/react-native-maps/react-native-maps/discussions/4389#discussioncomment-3746174).

**Comment by goyaltradersbrjn99** [comment]
worked for me too the above guide. thanks a lot.
