### ISSUE TITLE
Mapview  showsUserLocation error

### ISSUE THREAD

**Issue by CashCode** [react-native-maps/react-native-maps#4498]
### Summary

Issue occurs when you set ShowsUserLocation true
This code worked before
Google brought me there: https://stackoverflow.com/questions/74085319/class-was-expected-declaration-of-com-google-android-gms-location-fusedlocatio
They wrote that changing googlePlayServicesVersion from "+" to 21 fix an issue, but it didn't work for me.

![image](https://user-images.githubusercontent.com/8258294/198145996-920741d6-68e2-4ee2-b824-b96bc07cde07.png)

### Reproducible sample code

```TSX
<MapView
          region={{
            latitude: LATITUDE,
            longitude: LONGITUDE,
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA,
          }}
          showsUserLocation={true}
          style={styles.map}
          provider={PROVIDER_GOOGLE}
          initialRegion={{
            latitude: LATITUDE,
            longitude: LONGITUDE,
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA,
          }}
```

### Steps to reproduce

googlePlayServicesVersion = "+" and enable showsUserLocation

### Expected result

expected to work, code worked a week ago

### Actual result

error

### React Native Maps Version

react-native-maps@0.31.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

emulator android

**Comment by CashCode** [comment]
Okay, it's known bug, I changed to 17.0.0 and it seems working.

**Comment by Melber17** [comment]
> Okay, it's known bug, I changed to 17.0.0 and it seems working.

what have you changed to avoid this error?

**Comment by evgenyshenets91** [comment]
googlePlayServicesVersion 17 doesn't work for me

**Comment by FadiAboMsalam** [comment]
@CashCode  why was this closed and what is the solution ????

**Comment by kneza23** [comment]
this is not closed, it is still a bug and there is no solution represented in the comments

**Comment by kneza23** [comment]
this happens when you set googlePlayServicesLocationVersion to 21 in build.gradle file, reverting back to 20 is the only solution right now

**Comment by CashCode** [comment]
```
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
    //added
	googlePlayServicesVersion = "17.0.0" // default: "+"
    firebaseMessagingVersion = "21.1.0" // default: "21.1.0"

    // Other settings
    //compileSdkVersion = 23 // default: 23
    //buildToolsVersion = "23.0.1" // default: "23.0.1" 
    //targetSdkVersion = 23 // default: 23
    supportLibVersion = "23.1.1" // default: 23.1.1
```
working config, may be it will help someone

**Comment by phithu** [comment]
Resolved: https://stackoverflow.com/questions/75273823/java-lang-incompatibleclasschangeerror-found-interface-com-google-android-gms-l/75276209
