### ISSUE TITLE
Cannot convert undefined value to object | iOS Crash

### ISSUE THREAD

**Issue by digitalbore** [react-native-maps/react-native-maps#4503]
### Summary

My iOS app crash when I try to add a standard Marker to a map. 
Without the Markers the map is rendered correctly.

Error log:
```
2022-10-29 13:05:23.974064+0200 grups[576:67414] [javascript] TypeError: Cannot convert undefined value to object

This error is located at:
    in MapMarker (created by MapScreen)
    in AIRMap (created by MapView)
```
![IMG_0083](https://user-images.githubusercontent.com/91802817/198829545-9b4b639d-107c-4d0e-8896-6f118735b9ac.PNG)

The error is caused by line 50 in **decorateMapComponent.js**:

`const platformSupport = providerInfo[react_native_1.Platform.OS];`

### Reproducible sample code

```TSX
import React, { useContext, useEffect, useState } from 'react';
import {
  ScrollView,
  View,
  Alert,
  Platform
} from 'react-native';

import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

const MapScreen = ({ navigation }): JSX.Element => {
  const [groups, setGroups] = useState([1,2,3]);
  
    return (
      <View >
        <View>
          <MapView
            provider={Platform.OS === 'android' ? PROVIDER_GOOGLE : null}
            region={{
              latitude: 0,
              longitude: 0,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0221,
            }}
            toolbarEnabled={false}
          >
            {groups.map((group, index) => {
              return (
                <Marker
                  key={index}
                  coordinate={{latitude: 0, longitude: 0}}
                  title={'xxxx'}
                  description={'xxxxx'}
                />
              )
            })}
          </MapView>
  
        </View>
  
      </View>
    );
}

export default MapScreen;
```

### Steps to reproduce

-

### Expected result

Markers are rendered

### Actual result

iOS app crash

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.70.3

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 8

**Comment by digitalbore** [comment]
I temporary solved the bug modify that way:

`const platformSupport = providerInfo && providerInfo[react_native_1.Platform.OS];`

_providerInfo_ was undefined in my case.

Do you know why this can happen?

**Comment by Simon-TechForm** [comment]
Hi @digitalbore 👋

`provider` shouldn't be passed `null` but rather accepts `google` | `undefined`. If you continue experiencing the issue, please provide a minimal reproducible example in a public repo and I'd be more than happy to reopen this 👍

**Comment by Mhd-Emad** [comment]
I have the same issue!

**Comment by webraptor** [comment]
> Hi @digitalbore 👋
> 
> `provider` shouldn't be passed `null` but rather accepts `google` | `undefined`. If you continue experiencing the issue, please provide a minimal reproducible example in a public repo and I'd be more than happy to reopen this 👍

The docs mention **null** or **undefined**, so maybe update the docs accordingly then.

**Comment by ssommelet21** [comment]
> > Hi @digitalbore 👋
> > `provider` shouldn't be passed `null` but rather accepts `google` | `undefined`. If you continue experiencing the issue, please provide a minimal reproducible example in a public repo and I'd be more than happy to reopen this 👍
> 
> The docs mention `null` or `undefined`, so maybe update the docs accordingly then.

Two years later, it's still not fixed in the documentation:

https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md

Pathetic.

**Comment by itsAdil45** [comment]
almost 3 year still not updated in the docs, causing wastage of hours
