### ISSUE TITLE
addressForCoordinate always returns 0 results from geocoder on android

### ISSUE THREAD

**Issue by tristanheilman** [react-native-maps/react-native-maps#4504]
### Summary

The MapView component has the method 'addressForCoordinate' which is correctly returning geocoding results while being used on iOS devices. While using my Galaxy S20 (android device), I'm not experiencing the same results. Anytime the addressForCoordinate method is run from an android device, the geocoder fails to get any results and returns an empty list. Is there more configurations required to allow android devices to utilize this method? At the moment to get around this, I am running a google reverse geocoding api fetch instead of calling the addressForCoordinate method. I'd like to know why this method is not working on android devices. 

### Reproducible sample code

```TSX
import React, { useRef } from "react";
import { StyleSheet } from "react-native";

import MapView from "react-native-maps";

export default function App() {
  const mapRef = useRef();

  const getAddress = (region) => {
    mapRef.current.addressForCoordinate({
        latitude: region.latitude,
        longitude: region.longitude,
      })
      .then((address) => {
        console.log("addy - ", address);
        // never gets hit
      })
      .catch((error) => {
        console.log("error - ", error);
        // always returns [Error: Can not get address location]
        // due to geocoder list always coming back with 0 results...
      });
  };
  return (
    <MapView
      ref={mapRef}
      style={StyleSheet.absoluteFillObject}
      onRegionChangeComplete={getAddress}
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }}
    />
  );
}
```

### Steps to reproduce

Run the app on an android device. Pan around the map to trigger the onRegionChangeComplete handler. The catch block is always hit due to the geocoder always returning 0 results. 

### Expected result

I expect to at least occasionally see at least 1 result in the response of this method.

### Actual result

The addressForCoordinate MapView method always throws an error and never returns geocoding results on android devices.

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 46

### Device(s)

Samsung Galaxy S20

**Comment by Simon-TechForm** [comment]
Is this happening on all android devices or on the Galaxy S20 specifically?

I have no issues running the sample code you provided. Actually I can't trigger the .catch at all. Could you provide a repo reproducing this?

**Comment by tristanheilman** [comment]
I don't have other android devices to test it on, but either way this seemed to be a one off thing. I'm not seeing the issue anymore with the same code I had before. Not sure what changed, but closing this since no longer seeing the error described above.

**Comment by tristanheilman** [comment]
Actually this is happening again. Here is a repo that reproduces this https://github.com/tristanheilman/react-native-maps-geocoder-test

Testing on my android device - Galaxy S20... Whenever I move the map and invoke the onRegionChange handler the UI freezes and then the catch block is hit.

**Comment by tristanheilman** [comment]
I found this notice on the Android Developer docs for Geocoder class. The notice is in regards to the getFromLocation method. I'm seeing on my android a completely blocking promise. When I change the region of the map and invoke react-native-maps addressForCoordinate method, the package utilizes the deprecated geocoder.getFromLocation() method.

This method needs to be upgraded to utilize the Geocoder.GeocodeListener to avoid the blocking thread while waiting for results. I'm not sure if this refactor would solve my original problem, but it would at least solve an annoying UI thread blocking issue.

Regardless, this should be updated if possible. Since the thread is blocking I do not want to use this in production. If the function was non blocking, I could at least attempt to use it and have a just have a fail-safe api call to google.

This method was deprecated in API level 33. 
Use [getFromLocation(double, double, int, android.location.Geocoder.GeocodeListener)] https://developer.android.com/reference/android/location/Geocoder#getFromLocation(double,%20double,%20int,%20android.location.Geocoder.GeocodeListener
instead to avoid blocking a thread waiting for results.

**Comment by sraka1** [comment]
This seems to still be the case.
