### ISSUE TITLE
Google Maps Provider Movement Jank

### ISSUE THREAD

**Issue by localjo** [react-native-maps/react-native-maps#4511]
### Summary

When using `PROVIDER_GOOGLE` on iOS simulator, moving the map is janky and uncontrollable. 

### Reproducible sample code

Just use `PROVIDER_GOOGLE` in the `MapView` component, and open it in iOS Simulator.

```TSX
<MapView provider={PROVIDER_GOOGLE} />
```

Here's a minimal app that reproduces the problem:

https://snack.expo.dev/@localjo/google-map-provider-bug

### Steps to reproduce

1. Clone [the snack repo](https://snack.expo.dev/@localjo/google-map-provider-bug) locally.
2. Run the app in iOS simulator.
3. Try to drag the map to a new location.
4. Map will jump around and it will be very hard to get it to the location you want.

### Expected result

Map should move smoothly.

### Actual result

Trying to drag the map small distances results in rapid movements and jumps around to different map locations. This is an attempt to drag the map to center the equator, and then Florida:

https://user-images.githubusercontent.com/516388/199513147-88cb34f9-2e42-4426-b14c-21298d57bf3b.mp4

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS Simulator (Google Maps)

### React Native Version

0.69.6

### What version of Expo are you using?

SDK 46

### Device(s)

iPhone 14 Simulator with iOS 16

### Additional information

There are many other issues with `GOOGLE_PROVIDER` which appear to possibly be related:

https://github.com/react-native-maps/react-native-maps/issues/3639
https://github.com/react-native-maps/react-native-maps/issues/3804
https://github.com/react-native-maps/react-native-maps/issues/3863
https://github.com/react-native-maps/react-native-maps/issues/4022
https://github.com/react-native-maps/react-native-maps/issues/4050
https://github.com/react-native-maps/react-native-maps/issues/4248
https://github.com/react-native-maps/react-native-maps/issues/4371
https://github.com/react-native-maps/react-native-maps/issues/4427

It seems there is some issue with the `GOOGLE_PROVIDER` on iOS simulator related to movement callbacks. I wonder if it might be related to some kind of rounding error that makes the map behave as if the position changed more than the actual dragged distance. In most cases, the issue seems to go away when using a real device instead of a simulator.

**Comment by CosmicAshriga** [comment]
Did you find a solution ? I got the same issue and it's troublesome to test my markers...

**Comment by Stuartwastaken** [comment]
Same issue here

**Comment by nicolasmelo1** [comment]
same issue here

**Comment by edi** [comment]
Same issue here for months. Even with an empty map. It does look like the map can behave properly when you sometimes zoom in and out, therefore it must be something from the implementation, since the same map in google maps app, works just fine.

It works smoothly on Android, as well as having "apple maps" by default, so literally 120hz on promotion screens.

I've noticed this behaviour in the past 4 SDKs, and it used to work fine before, when I started working with Expo in ... SDK 36/37... up until 42 when native plugins like Stripe have been introduced.

**Comment by localjo** [comment]
Still relevant

**Comment by Simon-TechForm** [comment]
@localjo could you try updating past `v1.1.0`? (Preferably to the latest version). `v1.1.0` enabled google's metal renderer on iOS which resultated in quite a big jump in performance for us.

**Comment by localjo** [comment]
Thank you, yes. It's much better now. There's still a little bit of jank, after I drag or scale the map in the iOS simulator, it still jumps or continues moving slightly from where I actually dragged, but it's totally useable now. Thanks!
