### ISSUE TITLE
Polyline crashes iOS App 

### ISSUE THREAD

**Issue by yeesiang95** [react-native-maps/react-native-maps#4515]
### Summary

When apply lineDashPattern in Polyline, iOS App not responding.

### Reproducible sample code

```TSX
<MapView 
  provider={PROVIDER_GOOGLE}
  style={{
      ...StyleSheet.absoluteFillObject,
  }}
  initialRegion={initialRegion}
  onRegionChangeComplete={handleRegionChange}
  zoomEnabled={true}
  maxZoomLevel={18}
  minZoomLevel={0}
  rotateEnabled={false}
>
    <Polyline
        coordinates={plannedRoutePoints.map((item)=>({longitude:item.lng, latitude:item.lat}))}
        strokeColor={Colors.BRIGHT_BLUE} 
        strokeWidth={2}
        lineDashPattern={[10,10]}
    />  
</MapView>
```

### Steps to reproduce

Add linDashPattern to polyline

### Expected result

Render dash line

### Actual result

iOS App stop responding

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Simulator iPhone 14 Pro

**Comment by christopherldo** [comment]
Same for me

**Comment by harisraza123** [comment]
+1
Same here after user gives the permission.

**Comment by shawarmaz** [comment]
Getting this as well

**Comment by logan0900** [comment]
I am facing the same problem, the App is crashed while using Polyline. is there any solution? @shawarmaz  @harisraza123  @christopherldo @yeesiang95 
<img width="1440" alt="Screenshot 2023-01-14 at 1 01 59 AM" src="https://user-images.githubusercontent.com/58814997/212413330-557f8ae0-52e6-4605-b024-c91e6a8400a0.png">

**Comment by KrithikShailesh** [comment]
Was anyone able to resolve this issue? @logan0900 @shawarmaz @harisraza123 @christopherldo @yeesiang95

**Comment by Simon-TechForm** [comment]
I'm unable to reproduce this with the sample code provided. Can anoyone experiencing this please provide a **minimal** sample repo or expo snack?

**Comment by yeesiang95** [comment]
Hi, here is the example of polyline  https://snack.expo.dev/2lhxoVu-y 
When I set the lineDashPattern property for the Polyline, and the iOS simulator crashed.

> I'm unable to reproduce this with the sample code provided. Can anoyone experiencing this please provide a **minimal** sample repo or expo snack?

**Comment by DesdeJorge** [comment]
I solved removing the parameter `lineDashPattern` from the `<Polyline>` definition

**Comment by SantiagoCor** [comment]
I'm having this exact same issue.

react-native: 0.68.5
react-native-maps: 1.6.0
iPhone: 14 Pro (simulator)
iOS: 16.2

The app freezes when rendering a Polyline with the parameter `lineDashPattern` on **iOS with Google Maps**. It also happens with a 'LineString' Geojson (i assume it works the same as a Polyline).

This is my polyline:

``` jsx
<Polyline
   coordinates={[
     {latitude: -34.992509, longitude: -63.580034},
     {latitude: -36.825394, longitude: -65.824174},
   ]}
   lineDashPattern={[1, 20]}
/>
```

It works perfectly on Android

**Comment by anxheloo** [comment]
SAme problem here, the only solution i am using right now is to remove lineDashPattern prop from polyline
