### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by praveen97rss** [react-native-maps/react-native-maps#4519]
### Summary
Xcode Version : 13.4.1 (13F100)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_RCTAppSetupPrepareApp", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTAppSetupDefaultRootView", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Reproducible sample code

```TSX
<MapView
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        region={{
          latitude: 11.3806,
          longitude: 77.8944,
          latitudeDelta: 0.015,
          longitudeDelta: 0.015,
        }}
      >

        {coordinates.map((coordinate) => (
          <Marker
            coordinate={coordinate}
            // pinColor="blue"
            title={coordinate.placename}
            key={coordinate.id}
          />
        ))}

      </MapView>
```

### Steps to reproduce

After installing the npm package, we need to install the pod.

$ (cd ios && pod install)
# --- or ---
$ npx pod-install
Enabling Google Maps

If you want to enable Google Maps on iOS, obtain the Google API key and edit your AppDelegate.m(m) as follows:

+ #import <GoogleMaps/GoogleMaps.h>

@implementation AppDelegate
...

(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
+  [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; // add this line using the api key obtained from Google Console
...
The [GMSServices provideAPIKey] should be the first call of the method.

Google Maps SDK for iOS requires iOS 13, so make sure that your deployment target is >= 13.0 in your iOS project settings.

Also make sure that your Podfile deployment target is set to >= 13.0 at the top of your Podfile, eg:

platform :ios, '13.0'
Add the following to your Podfile above the use_native_modules! function and run pod install in the ios folder:

# React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
The app's Info.plist file must contain a NSLocationWhenInUseUsageDescription with a user-facing purpose string explaining clearly and completely why your app needs the location, otherwise Apple will reject your app submission. This is required whether or not you are accessing the users location, as Google Maps iOS SDK contains the code required to access the users location.

That's it, you made it! 👍

### Expected result

Need to resolve this issue.

### Actual result

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_RCTAppSetupPrepareApp", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTAppSetupDefaultRootView", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.4

### What version of Expo are you using?

Not using Expo

### Device(s)

All Devices in iOS side

**Comment by lidroider** [comment]
I've faced same problem and I resolved it by the guide in stackoverflow

https://stackoverflow.com/questions/71933392/react-native-ios-undefined-symbols-for-architecture-x86-64

Hope to help you

**Comment by praveen97rss** [comment]
Thank you for your support ji. I solved my issue.
