### ISSUE TITLE
 Overlay Background color on map - make the map unclickable 

### ISSUE THREAD

**Issue by eliyahu-kriel** [react-native-maps/react-native-maps#4526]
### Summary

i am trying to set a dark background color on the map as overlay
the problem is when doing so - the hole map becomes unclickable.

 i need to implement a logic that by default the map is without the dark background, and if the user click on one of the markers/polygons that on the map - a dark overlay will be set on the map, except the selected marker/polygon.

i also tried to play with the **zindex** property, and to set the _`OverlayComponent`_ at the top of the map, or at the bootom, or  after the markers or before - not helped me, the map was still unclickable

any ideas ?

### Reproducible sample code

```TSX
import {
  View,
} from "react-native";
import MapView from "react-native-maps";


const Map = () => {
  const {markers, polygons} = useMapStore()


  const OverlayComponent = () => (
    <View
      style={{
        position: 'absolute',
        top:0,
        right: 0,
       height: '100%',
        width: '100%',
        opacity: 0.5,
        zIndex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
      }}
    >
    </View>
  );

  return (

<MapView
      region={region}
      style={{
zIndex: 1,
flex:1
}}
<MapMarkers markers={markers} />
<MapPolygons polygons={polygons} />

 <OverlayComponent />
)

}
```

### Steps to reproduce

create a simple map with markers or polygons on it, and set a View element with background color an a position absolute property

### Expected result

the expected result will be to set a background color overlay on the map, and still be able to click on item on the map

### Actual result

the map not respond when click on it

### React Native Maps Version

0.30.1

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.66.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iphone, android

**Comment by itayphytech** [comment]
Happens to me too, would like to see a solution
