### ISSUE TITLE
Flurry of setNativeProps deprecation warnings when using markers

### ISSUE THREAD

**Issue by sharvilak11** [react-native-maps/react-native-maps#4536]
### Summary

We are updating plotted markers for drivers frequently and it gives a flurry of warnings stating - setNativeProps is deprecated and will be removed in next major release. This ultimately bloats the console outputs.

`console.warn('setNativeProps is deprecated and will be removed in next major release');`

Please advise how to remove this warning.

### Reproducible sample code

```TSX
import {Animated, Easing, Image, Platform} from 'react-native';
import {useEffect, useRef, useState} from 'react';
import {AnimatedRegion, Marker} from 'react-native-maps';
import driverMarkerImg from '../../../../../assets/driver-marker.png';

const AnimatedImage = Animated.createAnimatedComponent(Image);

function DriverMarker({location, driver, ...rest}) {
  const [marker, setMarker] = useState(null);
  const [coordinate] = useState(
    new AnimatedRegion({
      latitude: location.Latitude,
      longitude: location.Longitude,
      latitudeDelta: 0.025,
      longitudeDelta: 0.025,
    })
  );
  const rotation = useRef(new Animated.Value(0.01)).current;
  const bearingDegree = rotation.interpolate({
    inputRange: [0, 360],
    outputRange: ['0deg', '360deg'],
  });

  function animateMarker(newLocation) {
    const newCoordinate = {
      latitude: newLocation.Latitude,
      longitude: newLocation.Longitude,
      latitudeDelta: 0.025,
      longitudeDelta: 0.025,
    };
    if (newLocation.Bearing !== null) {
      Animated.timing(rotation, {
        toValue: newLocation.Bearing,
        useNativeDriver: Platform.OS !== 'android',
        easing: Easing.linear,
        duration: 250,
      }).start();
      setTimeout(() => {
        smoothNavigation();
      }, 250);
    } else {
      smoothNavigation();
    }

    function smoothNavigation() {
      coordinate.timing(newCoordinate).start();
    }
  }

  useEffect(() => {
    animateMarker(location);
  }, [location]);

  return location.Bearing ? (
    <Marker.Animated
      identifier={driver.Id}
      coordinate={coordinate}
      ref={marker => {
        setMarker(marker);
      }}
      {...rest}
    >
      <AnimatedImage source={driverMarkerImg} className="w-10 h-14" style={{resizeMode: 'contain', transform: [{rotate: bearingDegree}]}} />
    </Marker.Animated>
  ) : null;
}

export default DriverMarker;
```

### Steps to reproduce

Re-render a marker multiple times and this warning will be printed as many times too.

### Expected result

Give an option to turn off this flurry of warnings.

### Actual result

![image](https://user-images.githubusercontent.com/19903825/203979702-4f89055c-ecaf-4f9f-ba86-28600e2e2ea3.png)

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 46

### Device(s)

Any device

**Comment by zhenguet** [comment]
This is really funny.

With me, it just show on IOS, nothing in Android

**Comment by sharvilak11** [comment]
@zhenguet Funny thing is the console.log statements are eating up entire memory and it starts giving memory warnings.

**Comment by zhenguet** [comment]
@sharvilak11 yes. It warns twice but I can not do anything with map -_-
it's so crazy.

**Comment by zhenguet** [comment]
I see you fixed it. can you share you code ?

**Comment by BerkeAras** [comment]
Same issue. Map still works but this warnings are spamming the console.

**Comment by skizzo** [comment]
This still happens on Version 1.8.0 / iOS, please re-open this.

**Comment by km-tr** [comment]
Is this still happening, and will it not reopen?
