### ISSUE TITLE
MapView onCalloutPress event.nativeEvent.id is available on iOS but not on Android

### ISSUE THREAD

**Issue by findhumane** [react-native-maps/react-native-maps#4537]
### Summary

When all `Marker` children have an `identifier` attribute and using `MapView.onCalloutPress`, then `event.nativeEvent.id` returns the `identifier` on iOS but returns `undefined` on Android.

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { Marker } from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

const markers = [
  { id: "1", title: "Test1", description: "Hello World", location: { latitude: 30.270652526064772, longitude: -97.75368988587985 } },
  { id: "2", title: "Test2", description: "Hello World", location: { latitude: 30.265367698173810, longitude: -97.74469483868448 } },
  { id: "3", title: "Test3", description: "Hello World", location: { latitude: 30.261920499918144, longitude: -97.75005925680142 } },
];

export default function App() {
  const renderMarker = (marker) => (
    <Marker
      identifier={marker.id}
      key={marker.id}
      coordinate={marker.location}
      title={marker.title}
      description={marker.description}
      tracksViewChanges={false}
    />
  );

  const onCalloutPress = (event) => {
    if (event && event.nativeEvent) {
      console.log("onCalloutPress id: " + event.nativeEvent.id);
      if (event._targetInst && event._targetInst.return) {
        console.log("onCalloutPress return key: " + event._targetInst.return.key);
      }
    }
  };

  return (
    <View style={styles.container}>
      <MapView
        style={styles.map}
        initialRegion={{
          latitude: 30.26714,
          longitude: -97.74259,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
        onCalloutPress={onCalloutPress}
      >
        {markers.map(renderMarker)}
      </MapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

1. `git clone https://github.com/findhumane/testmapsidentifier`
2. `cd testmapsidentifier`
3. `npm install`
4. `npx expo start --tunnel`
5. Scan the QR code in Expo Go on Android
6. Tap on any marker
7. The console will show:
   ```
    LOG  onCalloutPress id: undefined
   ```
8. Same steps on iOS work:
   ```
    LOG  onCalloutPress id: 1
   ```

### Expected result

`identifier` passed through on all platforms

### Actual result

`identifier` is `undefined` only on Android

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 47

### Device(s)

Blackberry KEY2 (Android 8.1)

### Additional information

* Reproducible example: <https://github.com/findhumane/testmapsidentifier>
* I also tested `event._targetInst.return.key` based on [a comment from 2017](https://github.com/react-native-maps/react-native-maps/issues/218#issuecomment-343298369) but that returns `null` on both platforms.

**Comment by kevgrig** [comment]
Still an issue

**Comment by Simon-TechForm** [comment]
Hi @findhumane 👋

This is expected behaviour/a missing feature. `id` is only returned on iOS which is also stated in the JSDocs (see: https://github.com/react-native-maps/react-native-maps/blob/9944c868306fb7eddcbccc7e43f1279483561ed3/src/sharedTypes.ts#L31). You can open a feature request in the discussion section or even better open a PR implementing the feature. I'll be more than happy to review and merge it 👍
