### ISSUE TITLE
<Overlay component not working in react-native-maps ^1.3.2

### ISSUE THREAD

**Issue by ombogdanJoinToIt** [react-native-maps/react-native-maps#4540]
### Summary

<Overlay component not shoing image in react-native-maps ^1.3.2 but in react-native-maps 0.29.3 it`s it worked fine

### Reproducible sample code

```TSX
{(arrayForRender ? arrayForRender : []).map((item) => (
                        <>
                            {showOverlay === true ? <Overlay
                                identifier={`overlay-${item?.geozone?.id ?? ''}`}
                                image={url}
                                bounds={item['bbox']}
                                zIndex={99999}
                            /> : null}
                        </>
                    ))}
```

### Steps to reproduce

update react-native-maps from 0.29.3 to ^1.3.2

### Expected result

the image should be displayed

### Actual result

the picture is not displayed

### React Native Maps Version

1.3.1 and 0.29.3

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps)

### React Native Version

0.70.3

### What version of Expo are you using?

Not using Expo

### Device(s)

all

**Comment by AlissonEnz** [comment]
Hey, any update on this? Here it's not working on iOS only.

**Comment by hakandemirbilek** [comment]
Remote images still not working on Android with RN 0.71.1 and react-native-maps 1.4.0

**Comment by AlissonEnz** [comment]
It seems an issue with `png` images. It's working here with `jpg` image

**Comment by hakandemirbilek** [comment]
Tried with a jpg image, still doesnt work.

**Comment by AlissonEnz** [comment]
We found out that it's not working with images larger than 1024px (at least here)

**Comment by hakandemirbilek** [comment]
Unfortunately  tested with a 88x115 px JPEG, but still doesnt work. Local images work independent of the size.

I dont understand how a simple feature can be so inconsistent

**Comment by alcidesbsilvaneto** [comment]
Same problem here, downgrading...

**Comment by josemesaso** [comment]
Same here with the latest version, working only for android.

**Comment by josegutierro** [comment]
Any solution?

**Comment by aravi365** [comment]
Making  line:48 `[GMSServices setMetalRendererEnabled:NO];` in the` react-native-maps/ios/AirGoogleMpas/AIRGoogleMapManager.m` makes the overlay display, but still having flickering issue when zooming in or out

**Comment by BenCommet** [comment]
> Making line:48 `[GMSServices setMetalRendererEnabled:NO];` in the` react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m` makes the overlay display, but still having flickering issue when zooming in or out

This worked for me! It does slow everything down a bit though.

**Comment by dannyz61** [comment]
set `GMSServices setMetalRendererEnabled:NO`
I have added this patch and it is working fine 


`diff --git a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
index 2f704de..11e1f53 100644
--- a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
+++ b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
@@ -45,7 +45,7 @@ RCT_EXPORT_MODULE()
 
 - (UIView *)view
 {
-  [GMSServices setMetalRendererEnabled:YES];
+  [GMSServices setMetalRendererEnabled:NO];
   NSString* googleMapId  = nil;
   BOOL zoomTapEnabled = YES;
   if (self.initialProps){`

**Comment by dannyz61** [comment]
set `GMSServices setMetalRendererEnabled:NO`
I have added this patch and it is working fine 

```diff --git a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
index 2f704de..11e1f53 100644
--- a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
+++ b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m
@@ -45,7 +45,7 @@ RCT_EXPORT_MODULE()
 
 - (UIView *)view
 {
-  [GMSServices setMetalRendererEnabled:YES];
+  [GMSServices setMetalRendererEnabled:NO];
   NSString* googleMapId  = nil;
   BOOL zoomTapEnabled = YES;
   if (self.initialProps){```
