### ISSUE TITLE
Add text label under the polyline 

### ISSUE THREAD

**Issue by michal4511** [react-native-maps/react-native-maps#4542]
### Summary

I would like to display polyline above labels on the map. Currently, I have polyline under labels on the map. I tried to use zIndex but it doesn't work. 

### Reproducible sample code

```TSX
<MapView
        toolbarEnabled={false}
        moveOnMarkerPress={false}
        style={styles.maps}
        region={getMapRegion()}
        provider={PROVIDER_GOOGLE}
        customMapStyle={googleMapSkinStyles}
        scrollEnabled={false}
        zoomEnabled={false}
        rotateEnabled={false}
      >
        <Polyline
          coordinates={coordinates}
          strokeColor="#000"
          strokeWidth={3}
          lineDashPattern={[2]}
          zIndex={999}
        />
      </MapView>
```

### Steps to reproduce

Polyline under the label is default setting

### Expected result

Polyline above label

### Actual result

<img width="68" alt="Screenshot 2022-12-01 at 14 48 51" src="https://user-images.githubusercontent.com/69518903/205083151-2404b4e0-11e7-4803-806a-fe5ee889b250.png">

### React Native Maps Version

"react-native-maps": "0.30.2"

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

iPhone 11

**Comment by arnavb** [comment]
Is there any update on this issue? I'm facing similar on the latest version of the package.
