### ISSUE TITLE
Unable to use fork library with latest react-native-maps version - Getting lib/index.js not found

### ISSUE THREAD

**Issue by yousrasd** [react-native-maps/react-native-maps#4546]
### Summary

Our project is using a fork of react-native-maps. Previously, our fork was using react-native-maps 0.30. I updated our fork by synchronizing it with the latest version of react-native-map master branch. So now, it is using react-native-maps v1.3.2. 
Following this update, our app does not start. Im running into the following error:

error: Error: While trying to resolve module react-native-mapsfrom file/path/projectname/folderA/folderB/file.js, the package /path/projectname/node_modules/react-native-maps/package.jsonwas successfully found. However, this package itself specifies a main module field that could not be resolved (/path/projectname/node_modules/react-native-maps/lib/index.js. Indeed, none of these files exist

When I check our node modules, I indeed do not see a lib folder
![205174571-2d844519-fee7-4201-b011-fac89937b361](https://user-images.githubusercontent.com/63681471/205383635-4d150807-4781-4b2a-9f7b-f281550d986a.png)

I tried changing our project to use the main lib instead of the fork (react-native-maps/react-native-maps), and then I reinstalled the packages (yarn install). Then rechecked the node_modules, and Indeed I see a lib folder, and the app starts successfully.
![205174736-8d5c7a1c-0d35-417a-a4da-5f3df15b2d5b](https://user-images.githubusercontent.com/63681471/205383699-2c242be9-3b45-4ffd-8903-2f38402ec40a.png)

I tried forking this lib under my personal account (https://github.com/yousrasd/react-native-maps). When I use the master branch (which is up to date with this lib), same thing happens when I add this fork in the project: I run into 'this package itself specifies a main module field that could not be resolved' error.
I created a [branch test](https://github.com/yousrasd/react-native-maps/tree/test) that points to an old version of this lib (v0.30.1). When I use this branch in our project, the app STARTS! So now I confirm that there is something in one of the latest versions (versions 1.0.0 and up) that is causing me this error. Not sure if our project is missing a config or something. The project seems to be following the guidelines mentioned in https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md.   Now react-native-maps is using typescript, could it be related? Its like the lib folder is only generated when I use directly your lib which is available on npm.

Update: seems like when I try using your librairy directly by specifying a specific target, I get the SAME behavior as with my forked lib. 
![image](https://user-images.githubusercontent.com/63681471/205405625-5d1ab0cc-ff16-42a8-ad63-84e6924ea085.png)
![image](https://user-images.githubusercontent.com/63681471/205405659-6626a70d-3dc4-4d75-b77c-0ffb89ea0a05.png)
**No** lib folder is present. So now, im thinking that there must be a job that is run that generates that lib folder before publishing the package to npm. That's why it works when I use your lib directly from npm, but doesnt, when I specify a github url. I see that you have a [build phase](https://github.com/react-native-maps/react-native-maps/blob/master/package.json#L13) in your package.json that seems to run before you deploy the package to npm (based on the following workflow https://github.com/react-native-maps/react-native-maps/actions/runs/3128916513/workflow#L30). Based on this finding, I guess that this step is generating the **lib** folder. 

### Reproducible sample code
In package.json, put a forked lib (make sure that the fork is up to date with latest version of react-native-maps).
```TSX
  "react-native-maps": "https://github.com/yousrasd/react-native-maps",
```

then import the Marker from react-native-maps

```TSX
import {Marker} from 'react-native-maps';
```

### Steps to reproduce

1. Have a forked lib that is up to date with the master branch
2. Include it in your project
3. Run the app

### Expected result

App should start

### Actual result

App does not start.  An error is returned:

> error: Error: While trying to resolve module react-native-mapsfrom file/path/projectname/folderA/folderB/file.js, the package /path/projectname/node_modules/react-native-maps/package.jsonwas successfully found. However, this package itself specifies amain module field that could not be resolved (/path/projectname/node_modules/react-native-maps/lib/index.js. Indeed, none of these files exist

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro

**Comment by yousrasd** [comment]
I have a proposal for this. We can add a preinstall hook that runs the "tsc" command. This way the lib folder will be generated when forks are installed in projects.

**Comment by WillyRamirez** [comment]
The library as you see it in this repo isn't the same as hosted by Yarn/NPM. Before a developer submits a new release they usually run a couple of scripts to remove all files needed for development, and what you see on yarn is usually the dist/build/lib folder ready for use. [See here](https://yarnpkg.com/package/react-native-maps?files)

Having said that, in your own app add the following line to your scripts

   ` "postinstall": "cd ./node_modules/react-native-maps && yarn install && yarn build"`

This will build the source code and produce the lib folder.

**Comment by WillyRamirez** [comment]
@yousrasd I tried forking this lib y'day and also was not able to get it to work via the `yarn build` command either. The only way I got it to work was by copying the contents of the original `node_modules/react-native-maps` folder and commit those to my fork (and disable the husky script). Which is not the recommended way of getting a fork to work.... 
But then as soon as I apply [my fix ](https://github.com/react-native-maps/react-native-maps/pull/4478) I receive the following error. 

![image](https://user-images.githubusercontent.com/8708591/206741687-7ca2198d-54c6-4bcd-b08b-0dfc617f7221.png)

**Comment by yousrasd** [comment]
@WillyRamirez hmm interesting, I actually got it working with a postinstall script in the fork lib (as you can see in this branch https://github.com/yousrasd/react-native-maps/tree/adding-postinstall-hook). And it worked well in the project.

But the initial reason why I opened this issue is to see if this can be fixed in this lib directly. So that fork libs dont have to add postinstall scripts.

**Comment by WillyRamirez** [comment]
@yousrasd Ok that's smart. I put the postinstall script in my main app's scripts as seen in my [first comment](https://github.com/react-native-maps/react-native-maps/issues/4546#issuecomment-1344477851). I think yours is a better approach.
