### ISSUE TITLE
MarkerAnimated animation doesn't work

### ISSUE THREAD

**Issue by nolina-ilanjourno** [react-native-maps/react-native-maps#4551]
### Summary

Hi !

I'm trying to move a marker from A position to B position with AnimatedRegion as the documentation say, but I have many errors.

NB : All of this errors doesn't appear in react-native-maps 0.31.1 version with Expo 46.

First of all, the MarkerAnimated does not accept AnimatedRegion as coordinate (I have a typescript error who said : "Type 'AnimatedMapRegion' is missing the following properties from type 'WithAnimatedObject<LatLng>': latitude, longitude").

Secondly, when i'm trying to move the marker with AnimatedRegion (coordinates.timing in the example) i need to provide toValue, longitudeDelta and latitudeDelta, I dont understand why ...?

Despite all these errors, the marker move. The problem is i have a BIIIIG warning who said "setNativeProps is deprecated and will be removed in next major release" many many many times. To solve this issue maybe I need to pass useNativeDriver to true but I have an other error who said : " ERROR  Error: This JS animated node type cannot be used as native animated node"

Anyone can help me to resolve my issues ?

Thanks a lot !

### Reproducible sample code

```TSX
import { StatusBar } from "expo-status-bar";
import React, { useEffect, useRef } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AnimatedRegion, Marker, Animated, MarkerAnimated } from "react-native-maps";
import AnimatedMapRegion from "react-native-maps/lib/AnimatedRegion";
import { AnimatedMapView } from "react-native-maps/lib/MapView";

export default function App() {
  const coordinates = new AnimatedRegion({
    latitude: 48.866667,
    longitude: 2.333333
  });

  useEffect(() => {
    const timout = setTimeout(() => {
      coordinates.timing({
        useNativeDriver: true,
        duration: 5000,
        longitude: 2.3562043,
        latitude: 48.8690107,
        toValue: 0,
        longitudeDelta: 0.015,
        latitudeDelta: 0.015
      }).start()
    }, 2000);

    return () => clearTimeout(timout)
  }, []);

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
      <AnimatedMapView
        style={{ width: "100%", height: "100%" }}
        initialRegion={{
          latitude: 48.866667,
          longitude: 2.333333,
          latitudeDelta: 0.015,
          longitudeDelta: 0.015,
        }}
      >
        <MarkerAnimated
          coordinate={coordinates}
        />
      </AnimatedMapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

### Steps to reproduce

Just lunch the app, you will see the Map with the little red marker in Paris who move 2 seconds  after the loading 

### Expected result

Without any typescript error as in react-native-maps 0.31.2 version with Expo 46

### Actual result

![image](https://user-images.githubusercontent.com/109548580/205938960-1e8fd2ae-5a03-497f-a25e-5a7e0ec7b39c.png)

<img width="878" alt="image" src="https://user-images.githubusercontent.com/109548580/205939134-102b076f-2f8a-42f9-9099-b3150a0aa85d.png">

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 46

### Device(s)

iPhone 14 Pro MAX

### Additional information

I'm using Expo SDK 47 not Expo 46

**Comment by hlspablo** [comment]
It's really sad that a lib so important like this have almost nothing working as expected. I can't make a simple market animation works, I'm facing the same problem as you.

**Comment by sharvilak11** [comment]
I was getting the same issue here, this is how I fixed after so many trials and errors

* Set `useNativeDriver` to true only in the case of iOS and not android. Also, don't use child for Android as it slows down the phone. Use icon and rotation properties for android. 

```
<Marker.Animated
      identifier={driver.Id}
      coordinate={coordinate}
      tracksViewChanges={tracking}
      key={driver.Id}
      ref={marker => {
        setMarker(marker);
      }}
      icon={isAndroid && driverMarkerImg}
      rotation={isAndroid && location.Bearing}
      anchor={isAndroid && {x: 0.5, y: 0.5}}
    >
      {!isAndroid && <AnimatedImage source={driverMarkerImg} style={{resizeMode: 'contain', transform: [{rotate: bearingDegree}], ...style}} />}
</Marker.Animated>
```

* Regarding the flurry of warnings, I had to turn it off from LogBox as those warnings used to eat entire memory.
```
LogBox.ignoreLogs(['new NativeEventEmitter']);
```

**Comment by zhenguet** [comment]
@sharvilak11 see you again. can you share your fixed code?

**Comment by RobTS** [comment]
The types in the current version of the library do not match the animated marker example in the docs any more, maybe users struggling to fill newly required properties is part of the issue. Passing this payload used to be sufficient:

```
          ...userLocation,
          duration: 2500,
          useNativeDriver: false,
```

**Comment by zhenguet** [comment]
@xanderdeseyn you can try add 
```
LogBox.ignoreLogs([
  'setNativeProps is deprecated and will be removed in next major release',
])
```
into index.js in the root off the project

**Comment by emachalan-redblox** [comment]
Is there any update to fix this issue means please update here.

**Comment by AnatoleLucet** [comment]
You can get around this issue by creating you own AnimatedMarker component and/or AnimatedRegion (not as complicated as it seems).
See the comment i left in #4371: https://github.com/react-native-maps/react-native-maps/issues/4371#issuecomment-1344148890

**Comment by owaisnizam** [comment]
The duration param doesn't work and its taking default 500ms duration. Any workaround for this?

**Comment by luissandrea** [comment]
Still relevant
