### ISSUE TITLE
Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

### ISSUE THREAD

**Issue by PaulLeymet** [react-native-maps/react-native-maps#4554]
### Summary

Hi,

Crash happens on IOs device when : 

1.  displaying a custom marker (marker with children) 
2.  specifying provider =  'google'

* **Crash log :**

> `Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil`

* **Both following issues relate the same problem (therefore are closed without real solution but workarounds) :**
[https://github.com/react-native-maps/react-native-maps/issues/3983](url)
[https://github.com/react-native-maps/react-native-maps/issues/4351](url)
(Workarounds being etiher not using children in markers or not using google provider).

### Reproducible sample code

```TSX
<MapView
  initialRegion={{
    latitude: -1.395197,
    longitude: -78.423335,
    latitudeDelta: 0.009999,
    longitudeDelta: 0.009999,
  }}
  style={{ width:200, height: 200 }}
  provider={'google'}
>
  <Marker
    coordinate={{
      latitude: -1.395197,
      longitude: -78.423335,
    }}
  >
    <Image
      resizeMode="cover"
      style={{ width: '100%', height: '100%' }}
      source={{
        uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png',
      }}
    />
  </Marker>
</MapView>
```

### Steps to reproduce

Just rerender the component

### Expected result

Nothing should happen

### Actual result

Crash on IOs : 
> `Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil`

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.67.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 12 (simulator)

**Comment by VictorPulzz** [comment]
Same problem, I have toggle account in application. Then I toggle account, I rerender core application, and then I got same error
