### ISSUE TITLE
onDoublePress not working on IOs

### ISSUE THREAD

**Issue by PaulLeymet** [react-native-maps/react-native-maps#4555]
### Summary

Hi,

onDoublePress doesn't seem to fire on IOs (tested on iPhone 12 simulator). Working fine on Android.

### Reproducible sample code

```TSX
<MapView 
  style={{
    flex: 1, 
  }} 
  onPress={() => {console.log("onPress")}}
  onLongPress={() => {console.log("onLongPress")}}
  onDoublePress={() => {console.log("onDoublePress")}}
/>
```

### Steps to reproduce

Double tap on mapView

### Expected result

Console should log `onDoublePress`

### Actual result

Console logs `onPress` twice

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.67.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 12 (simulator)

**Comment by afu-hive** [comment]
it not working for me too. So I work-around by my self. and work very well
here my code

```javascript
const doublePressRef = useRef(0)

const onPress = () => {
    doublePressRef.current = doublePressRef.current + 1
    setTimeout(() => doublePressRef.current = 0, 400)

    if (doublePressRef.current === 2) { // double press
       // do stuff
    }
}

return (
  <MapView {...otherProps} onPress={onPress} />
)
```

**Comment by Simon-TechForm** [comment]
Hello @PaulLeymet 👋

This is expected behaviour and mentioned explicitly in the [docs](https://github.com/react-native-maps/react-native-maps/blob/9944c868306fb7eddcbccc7e43f1279483561ed3/docs/mapview.md?plain=1#L66). PR's or feature requests in the discussion secion are more than welcome 👍
