### ISSUE TITLE
Styling `road.fill` breaks custom styling on Android

### ISSUE THREAD

**Issue by 256hz** [react-native-maps/react-native-maps#4560]
### Summary

Hi there, I'm not sure if this is an issue with this library or Google's code underneath, but passing this style causes all custom styling to not be rendered on Android.  It renders fine on iOS (using `PROVIDER_GOOGLE`), which made me suspect it could be a problem here, but I don't know for sure.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default App() {
  return (
    <MapView
      style={{ flex: 1 }}
      provider={PROVIDER_GOOGLE}
      customMapStyle={[
        {
          elementType: 'geometry.fill',
          stylers: [
            {
              color: '#6d86a9',
            },
          ],
        }, // this style renders fine
        {
          featureType: 'road.fill',
          stylers: [
            {
              weight: 1,
            },
          ],
        }, // this causes the map to ignore the rest of the custom styles on Android only
      ]}
      // ...
    />
  );
};
```

### Steps to reproduce

Run the above map on Android on an emulator or physical device.  Comment out the second style in the array and reload the map to see that the first style works on its own.

### Expected result

`road.fill` width style should apply to the map and not break the rest of the styling.  Google map on iOS with road.fill style:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/46080343/206872976-9f4b23c8-44da-473e-b487-35640a21d71d.png">

### Actual result

Pixel 4 emulator with the rest of my custom style (but not road.fill)

<img width="426" alt="image" src="https://user-images.githubusercontent.com/46080343/206872856-b7fc31c9-630f-430f-8ec1-0af931d0a437.png">

Pixel 4 emulator with the `road.fill` styler also applied

<img width="426" alt="image" src="https://user-images.githubusercontent.com/46080343/206872922-8c571a8e-caca-44b2-bab0-d521c7b354c4.png">

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 3 emulator, Pixel 4 emulator, Samsung S10 physical device

**Comment by mattigrthr** [comment]
@256hz, I also had the issue, that the custom map style was correctly applied on iOS but not on Android. Turns out, I had a faulty styler in my JSON style. I figured out the right way by using the legacy [Styling Wizard for Google Maps](https://mapstyle.withgoogle.com).

I believe your weight should be applied to the geometry of the road like this:

```json
{
    "featureType": "road",
    "elementType": "geometry.fill",
    "stylers": [
      {
        "weight": 5.5
      }
    ]
 }
```

That's what I got when trying your scenario with the Styling Wizard.
