### ISSUE TITLE
Issue on Expo Development Build: requireNativeComponent: 'AIRMap' was not found in the UIManager

### ISSUE THREAD

**Issue by sami246** [react-native-maps/react-native-maps#4561]
### Summary

Hi,

Not sure if this is the correct place for this issue but I have tried so many different avenues to get rid of this error to no avail. I installed the react-native-maps package on my current expo build and was getting this error from the start. My project already is deep into production so I assumed maybe somewhere along the line I had created an error somewhere so I started a new project to test the package and my environment and like I anticipated it worked. However, this made me think about then trying to run my react native app on Expo Go instead of the development build (I've been using this for admob ads) and it actually worked there too.

So from all the I can only theorise that the issue is something to do with the Expo development build, I have attempted react-native-link, npx expo prebuild, and also tried to follow the documentation directly from expo https://docs.expo.dev/versions/latest/sdk/map-view/#deploying-app-with-google-maps focusing on just the android for now, and many other things but at this point, I am really just lost as to what is right and what is wrong.
Any suggestions on help here would be appreciated.

### Reproducible sample code

```TSX
import { StyleSheet, View, } from 'react-native'
import React, { useEffect, useRef } from 'react';
import { colors} from '../constants/theme'
import { auth } from '../firebase';
import { useState } from 'react';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import NavBar from '../components/NavBar';
import { Gooogle_API_Key } from '../config';
import {GooglePlacesAutocomplete} from 'react-native-google-places-autocomplete';
import { collection, query, where, onSnapshot, orderBy, limit, getDoc, doc,  } from "firebase/firestore";
import { firestoreDB } from '../firebase';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'; // remove PROVIDER_GOOGLE import if not using Google Maps


const MapScreen = ({ navigation }) => {
  const [user, setUser] = useState(auth.currentUser)
  const [data, setData] = useState(null)


  return (
    <View style={styles.container}>
    <MapView
      // provider={PROVIDER_GOOGLE} // remove if not using Google Maps
      style={styles.map}
      region={{
        latitude: 51.537430,
        longitude: -0.125250,
        latitudeDelta: 0.015,
        longitudeDelta: 0.0121,
      }}
    >
    </MapView>
  </View>
  )
}

export default MapScreen

const styles = StyleSheet.create({
  // container: {
  //   flex: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  contentContainer : {
    flex: 10
  },
  container: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
})
```

### Steps to reproduce

- create a new expo project
- create a development build
- install react-native-maps
- write code as above to simply display map

### Expected result

Display the map

### Actual result

requireNativeComponent: 'AIRMap' was not found in the UIManager error appears

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 46

### Device(s)

Samusung Galaxy s20+

### Additional information

I believe the SDK version is actually 47

**Comment by sami246** [comment]
Found the issue myself. Apparently, you have to rebuild your development application after installing new native modules. I wish the documentation was clearer on this point but got there in the end

**Comment by amalikmuhd** [comment]
where you able to get it to work

**Comment by sami246** [comment]
Are you sure you configured your app.json files to have the API key for Google maps and if you have ios or android folders, the key needs to be present there too. Those are the only things that come to mind from the information you have given me, try add those and rebuild the app

**Comment by Brrright** [comment]
I've added the API Key and rebuilded, but still getting same error on my android phone. It works on my android emulator but not for my physical android device.

**Comment by EssamCSE** [comment]
> I've added the API Key and rebuilded, but still getting same error on my android phone. It works on my android emulator but not for my physical android device.

I tried to rebuild it again as I used EAS build after installing the package, but the same problem occurred.

**Comment by AKuinkel** [comment]
> I've added the API Key and rebuilded, but still getting same error on my android phone. It works on my android emulator but not for my physical android device.

Did you add the plugin + api key, checked whether or not we're given location permission, set coordinates for the map and then rebuilt the app?
