### ISSUE TITLE
Imperative map handlers dont initially pan map to correct position on iOS Google Maps

### ISSUE THREAD

**Issue by slutske22** [react-native-maps/react-native-maps#4567]
### Summary

When calling several of the imperative handlers on the `MapView` ref instance, the map view does not immediately update.  For example, when calling methods like `animateCamera`, `fitToCoordinates`, `animateToRegion`, or `fitToElements`, the expectation is the map will immediately change its viewport according to the arguments provided to these functions.  On iOS (whether through expo or bare), this does not happen.  

For example, in the following gif, when the user opens the menu and clicks the "go to station" button, I expect the menu to close, and the map to center on the marker with the "7" on it.  That does not happen. Strangely, when I touch and pan, the map "snaps" into the place I expected it to be after pressing the button:

![Dec-11-2022 18-19-57](https://user-images.githubusercontent.com/52637023/208310993-a1a8738b-9ff7-490b-9589-6907c9379d32.gif)

Also, consider the next gif. After calling one of these methods (pressing the button), the map does not move.  But when I then tap on the center of the map (where there is no marker), the map acts as though it has moved, and highlights marker no. 13, and opens the menu.  It is as if the map *thinks* it moved to the right spot, but does not actually display the updated view until you drag:

![Dec-18-2022 07-27-50](https://user-images.githubusercontent.com/52637023/208311191-2b6da908-11c0-4093-afea-743c0e165750.gif)

This is happening for me on iOS with Google Maps, though not on Android. I have not tried this with apple maps.

Snack reproducing the issue: https://snack.expo.dev/@slutske22/react-native-maps-imperative-issue?platform=ios

### Reproducible sample code

```TSX
// There are several major elements at play in my code.  I distilled the issue down to its most basic form, 
// while still containing those elements, but its alot to put in a codeblock.  Please see this snack: 
// https://snack.expo.dev/@slutske22/react-native-maps-imperative-issue?platform=ios. 
// I am able to successfully reproduce the issue on iOS with this snack.  A bit of pseucocode, 
// with a few relevant code snippets:

PSEUDOCODE: 

// App:
//  - React context object used to save ref to MapView and make it available in all screens
//    - React Navigation Stack Navigator
//      - Home screen with map
//      - Favorites Screen with list of locations

CODE SNIPPETS (See snack for full code example):

// Map.tsx ------------------------------------ :

const MapBase = () => {
  const { setMap } = useContext(MapContext);

  return (
    <MapView
      ref={(r) => setMap(r as MapView)}
      style={StyleSheet.absoluteFill}
      provider={PROVIDER_GOOGLE}
      initialRegion={ ... }>
      {locations.map(({ uuid, latitude, longitude }) => (
        <Marker key={uuid} coordinate={{ latitude, longitude }} />
      ))}
    </MapView>
  );
};

// MapContext.tsx ----------------------------- :

export const MapContext = createContext({});

/**
 * Context provider which provides a reference to the central map's
 * underlying MapView imperative handler
 */
export const MapProvider: React.FC<Props> = ({ children }: Props) => {
  const [map, setMap] = useState<MapView>();

  return (
    <MapContext.Provider value={{ map, setMap }}>
      {children}
    </MapContext.Provider>
  );
};


// Favorites.tsx ---------------------------- :

export const Favorites: React.FC = () => {
  const { map } = useContext(MapContext);
  const navigation = useNavigation();

  const goToLocation = useCallback(
    (location) => {
      navigation.navigate('Home');

      if (map) {
        map.animateCamera({  // <---------------- Issue is here, or with similar methods
          center: {
            latitude: location.latitude,
            longitude: location.longitude,
          },
          zoom: 12,
        });
      }
    },
    [map, navigation]
  );

  return (
    <View>
      {locations
        .filter((l) => l.favorite)
        .map((location) => (
          <TouchableOpacity
            onPress={() => goToLocation(location)}
            style={ ... }>
            <Text>{location.name}</Text>
            <Text>Go to station</Text>
          </TouchableOpacity>
        ))}
    </View>
  );
};



// NavStack.tsx --------------------------------:

export const Stack = createNativeStackNavigator();

/**
 * Central navigation stack of the application
 */
export const NavStack = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen
          name="Home"
          options={{ headerShown: false }}
          component={Home}
        />
        <Stack.Screen name="Favorites" component={Favorites} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

### Steps to reproduce

From a user perspective
- Press the button that should pan/animate the map to a new view
- Map does not update its view until you manually try to drag it

From a dev perspective
- Call any of the imperative methods that are meant to change the map's viewport

### Expected result

I expect the map to immediately update its viewport according to the arguments specified in the method

### Actual result

The map does not update its viewport until the user manually drags it

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

Expo 47.0.0 / 47.0.8, or built with bare

### Device(s)

iPhone 13 simulator, iPhone 11 pro (real device)

### Additional information

This bug is also inconsistent - after some restarts, it went away for a moment, but is now back.  Present whether debugging is enabled or not

**Comment by korifey91** [comment]
I have a similar problem. Calling 
```js
mapRef.current?.animateCamera({
    center: {
      latitude: locationInfo.geometry!.location.lat,
      longitude: locationInfo.geometry!.location.lng,
    },
    zoom: 14,
});
```
doesn't center camera to the position

**Comment by korifey91** [comment]
I replaced `animateCamera` with `setCamera` in order to make it work as expected

**Comment by Alta1re** [comment]
> I replaced `animateCamera` with `setCamera` in order to make it work as expected



> I have a similar problem. Calling
> 
> ```js
> mapRef.current?.animateCamera({
>     center: {
>       latitude: locationInfo.geometry!.location.lat,
>       longitude: locationInfo.geometry!.location.lng,
>     },
>     zoom: 14,
> });
> ```
> 
> doesn't center camera to the position. Instead it make the position to be in the top left corner.
> 
> Interesting thing - it works as expected if a map has `width` and `height` defined in pixels
> 
> Update I was wrong. Defining dimensions in pixels fix nothing. It's just not stable behavior.

Exactly the same issue here. When i change the MapView size while running the app, the map centers as expected. But after restart, the center of the map is in the upper left corner.

**Comment by GRenkel** [comment]
I am also facing this problem! It is not possible to move to a desired location. Has anyone managed to get around this limitation?

**Comment by aikewoody** [comment]
@korifey91 @Alta1re I'm having the exact same problem and just created a bug report ticket about it. Let's see what the responses will be: https://github.com/react-native-maps/react-native-maps/issues/4734

**Comment by breakeren** [comment]
Still relevant. Experiencing this with version 1.7.1

**Comment by vanenshi** [comment]
problem still exist

**Comment by vanenshi** [comment]
Still relevant
