### ISSUE TITLE
[iOS] onRegionChangeComplete not firing when zooming in or out on map

### ISSUE THREAD

**Issue by zalouk567** [react-native-maps/react-native-maps#4568]
### Summary

onRegionChangeComplete not firing when zooming in or out on map (google maps for iOS)

### Reproducible sample code

```TSX
import React, { useRef, useState } from "react";
import styled from "styled-components/native";
import Map, { PROVIDER_GOOGLE } from "react-native-maps";
import { MAP_OPTIONS } from "constants";

export const MapContainer = () => {
  const ref = useRef<Map>();
  const [mapRegion, setMapRegion] = useState(MAP_OPTIONS.initialRegion);

  return (
        <MapStyled
          ref={ref}
          provider={PROVIDER_GOOGLE}
          customMapStyle={MAP_OPTIONS.mapPoiStyle}
          initialRegion={mapRegion}
          onRegionChangeComplete={setMapRegion}
          maxZoomLevel={15}
          minZoomLevel={10}
        >
        </MapStyled>
  );
};

const MapStyled = styled(Map)`
  flex: 1;
  width: 100%;
  height: 100%;
`;
```

### Steps to reproduce

Zoom in or out of the map for iOS

### Expected result

onRegionChangeComplete will be called with the updated map region

### Actual result

onRegionChangeComplete is not being called after zoom

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 47

### Device(s)

iPhone 14 Pro Max (16.1)

**Comment by ktroitsky** [comment]
Same issue

**Comment by mksquad87** [comment]
+1

**Comment by mksquad87** [comment]
@zalouk567 or @ktroitsky  have you found any workaround in the meanwhile?

**Comment by Simon-TechForm** [comment]
Are you able to reproduce this on a real device?

The only way for me to reproduce this is on a simulator and even then it only happens if I release the `option` key before releasing the mouse drag, which has always caused weird behaviour in iOS simulators.
