### ISSUE TITLE
[Apple Map] Memory goes up steadily

### ISSUE THREAD

**Issue by jb9229** [react-native-maps/react-native-maps#4580]
### Summary

Memory is released to maintain maximum memory usage when moving regions or looking up new markers

### Reproducible sample code

```TSX
<MapView
  key={"map-view/GlobalMapView/StyledMapView"}
  mapRef={(ref) => {
    mapViewerRef.current = ref;
  }}
  style={[StyleSheet.absoluteFillObject]}
  maxZoom={mapProfile.clusterMaxZoom}
  initialRegion={{ latitude: currentUserLocation.coords.latitude, longitude: currentUserLocation.coords.longitude, latitudeDelta: 0.01, longitudeDelta: 0.01 }}
  mapPadding={{ top: 0, right: 0, bottom: isVehicleFiltering ? 200 : isSelectedMarker ? 300 : 30, left: 0 }}
  mapType={'standard'}
  userInterfaceStyle={'light'}
  onTouchStart={() => {
    inputBoxRef.current?.blur();
  }}
  onMapReady={() => {
    setMapReady(true);
  }}
  onMapLoaded={() => {
    Platform.OS === 'ios' && !isMapReady && setMapReady(true);
  }}
  showsMyLocationButton={false}
  showsTraffic={true}
  showsUserLocation={true}
  followsUserLocation={myLocationType === MyLocationType.Follow}
  onPanDrag={() => {
        myLocationType !== MyLocationType.InActive && setMyLocationType(MyLocationType.InActive);
  }}
  onPress={(event) => {
     myLocationType !== MyLocationType.InActive && setMyLocationType(MyLocationType.InActive);
     ~~~~
  }}
   onRegionChangeComplete={(region) => {
        currentMapRegionRef.current = region;
        ~~~~
        updateMapPolygon(region, nextZoom);
   }}
    </StyledMapView>
```

### Steps to reproduce

Monitor memory usage by dragging the apple map and changing the region -> Memory constantly rises

### Expected result

Like Google Maps, it maintains memory when it goes up to a certain extent

In addition to changing Google Maps regions, maximum memory usage is maintained even if the number of markers is changed
<img width="1000" alt="구글맵, 300을 넘어가지 않음" src="https://user-images.githubusercontent.com/3200647/210295509-3922c180-518c-41ff-bfd3-0d7f4c6d05b3.png">

### Actual result

Apple Maps continuously increases memory usage when changing regions and markers
<img width="1032" alt="스크린샷 2023-01-03 오전 11 50 12" src="https://user-images.githubusercontent.com/3200647/210295575-067936d3-05c7-4deb-92a8-55e9edd93b3d.png">

### React Native Maps Version

0.30.2, 1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.5

### What version of Expo are you using?

SDK 45

### Device(s)

iPhone 8 (15.5), iPhone 14(16.2)

### Additional information

- i did check the ["react-native-reanimated" issue](https://github.com/react-native-maps/react-native-maps/issues/4214)

**Comment by jb9229** [comment]
Still relevant

**Comment by brsaylor2** [comment]
Still relevant
