### ISSUE TITLE
Zoom in and out bug when using minZoomLevel with followUserLocation

### ISSUE THREAD

**Issue by tomhrtly** [react-native-maps/react-native-maps#4585]
### Summary

When using the following two options with MapView, the map is constantly moving in and out as the user's location is being followed and because there is a zoom level that is set.

This only happens on a real iOS device as your location is changing constantly (see attached screen recording).

Here is a snack with the sample code: https://snack.expo.dev/@tomhartley97/mapview-bug

https://user-images.githubusercontent.com/35436443/212147679-731b0038-f464-408d-8c8e-ef3699eafa86.MP4

### Reproducible sample code

```TSX
import { View } from 'react-native';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <View>
      <MapView
        style={{
          width: 700,
          height: 700,
        }}
        showsUserLocation={true}
        minZoomLevel={18}
        followsUserLocation={true}
      />
    </View>
  );
}
```

### Steps to reproduce

Run the sample code on a real iOS device.

### Expected result

I expect the zoom to not change when followsUserLocation is set to true and the location is updated.

### Actual result

The zoom was constantly zooming in and out.

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

SDK 45

### Device(s)

iPhone XR

**Comment by Simon-TechForm** [comment]
Hi @tomhrtly 👋 

As you might have guessed from the above comment, I've just released a new beta version that should fix the issue. Any chance you could try it out and report back with your findings? The new beta shouldn't manipulate the zoom level in any way, when following user location :)
