### ISSUE TITLE
Change the size of marker when use image props

### ISSUE THREAD

**Issue by quannq-comartek** [react-native-maps/react-native-maps#4607]
### Summary

Hello all,
I can not find out how to change the icon size of a marker in this library. I know that you can embed an image in the marker component, however that really slows down the map as a whole, rather I am talking about sizing the icon attribute of the Marker component.

I have tried adding styles to it with changing width and height, but this seems to have no effect.

Any help?

Thanks!

### Reproducible sample code

```TSX
<Marker
              coordinate={{
                latitude: marker.customer?.lat ?? 0,
                longitude: marker.customer?.lng ?? 0,
              }}
              key={marker.customer?.id}
              image={icons.LocationPNG}
              anchor={{ x: 0.5, y: 0.4 }}
              onPress={() => findAgency(marker.customer?.id || '')}>
```

### Steps to reproduce

When click marker, size of marker change

### Expected result

size of marker change when use image props of marker

### Actual result

Dont know how can change

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.7.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Ios and Android

**Comment by selven** [comment]
You can have two marker images of different sizes and switch between the two of them.

**Comment by noumanmoeen** [comment]
@quannq-comartek were you able to find a solution for this issue ?

**Comment by quannq-comartek** [comment]
No, so sad

**Comment by quannq-comartek** [comment]
> @quannq-comartek were you able to find a solution for this issue ?

No any solution helps me fix this

**Comment by Cor4zon** [comment]
Still relevant

**Comment by rayronvictor** [comment]
You con do something like this:

```tsx
const ICON_IMAGE = {
  icon1: require('../../../assets/icon1.png'),
  icon2 require('../../../assets/icon2.png'),
  // ...
};

function IconMarker() {
  const [iconType, setIconType] = useState('icon1')

  return (
    <View>
      <Marker>
        <Image source={ICON_IMAGE[iconType]} style={styles.marker} />
      </Marker>
  
      <Button onPress={() => setIconType((prev) => prev === 'icon1' ? 'icon2' : 'icon1')}>Change icon</Button>
    </View>
}

const styles = StyleSheet.create({
  marker: {
    width: 12,
    height: 20,
  },
});
```

**Comment by NiccoloCase** [comment]
Still relevant
