### ISSUE TITLE
give me wrong reagion 

### ISSUE THREAD

**Issue by yuanyixiaomei** [react-native-maps/react-native-maps#4620]
### Summary

When I use Display: none to quickly switch between showing and hiding the map, the map gives me back the range below, but my range isn't really there

function :getMapBoundaries
call back values:
northEast: {longitude: 90, latitude: 44.99999999999999}
southWest: {longitude: -90, latitude: -45}

### Reproducible sample code

```TSX
mapRef.current?.getMapBoundaries().then((v) => {})
```

### Steps to reproduce

When I use Display: none to quickly switch between showing and hiding the map, 

### Expected result

right value  

### Actual result

northEast: {longitude: 90, latitude: 44.99999999999999}
southWest: {longitude: -90, latitude: -45}

### React Native Maps Version

 "react-native-maps": "0.29.3",

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

  "react-native": "0.67.1",

### What version of Expo are you using?

SDK 45

### Device(s)

13 promax

**Comment by Simon-TechForm** [comment]
You seem to be using a deprecated version of `react-native-maps`. Please try out the latest version and open a new issue if the problem persists. :)
