### ISSUE TITLE
Enabling Google Maps re-introduces build error for iOS simulator on M1 / M2 / arm64

### ISSUE THREAD

**Issue by zaubara** [react-native-maps/react-native-maps#4624]
### Summary

Hi all,

As soon as one enables Google Maps (eg. by adding googleMapsApiKey in expos app.json), which in turn adds Google-Maps-iOS-Utils to the Podfile, building on M1 results in a build error, even after updating react-native-maps to 1.4.0:

>❌  (/Users/me/Library/Developer/Xcode/DerivedData/ZetesCourier-adfrxchcoufnloeyumasivpwddqv/Build/Products/Debug-iphonesimulator/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h:499:2)
>  497 |
>  498 | #else
>\> 499 | #error unsupported Swift architecture
>      |  ^ unsupported Swift architecture
>  500 | #endif
>  501 |

or 

>❌  (/Users/me/Documents/_git/deleteme/my-app/ios/Pods/Target Support Files/Pods-myapp/ExpoModulesProvider.swift:8:8)
>   6 |  */
>   7 |
>\>  8 | import ExpoModulesCore
>     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/me/Library/Developer/Xcode/DerivedData/myapp-bejelwahwnefipebojrtrzbrgycy/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
>   9 | import EXConstants
>  10 | import ExpoKeepAwake
>  11 |

So while the problem was fixed in GoogleMaps 7.3.0, the issue still exists in Google-Maps-iOS-Utils 4.1.0 - which seems to be only added as a dependency when Google Maps is enabled.

The current workarounds all revolve around using Rosetta.

This was thanksfully fixed in https://github.com/googlemaps/google-maps-ios-utils/pull/428, which has already been merged - but not yet released.

One (dirty) way to add the fix quickly would be adding
```pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :branch => 'main'```
in the local Podfile, forcing the use of the most recent library.

Whenever a new version is out, having a new, fixed react-native-maps would be awesome.

Thanks!

### Reproducible sample code

```TSX
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'

"ios": {
  ...
  "config": {
    "googleMapsApiKey": "..."
  }
}
```

### Steps to reproduce

- npx expo init
- npx install react-native-maps
- manually update to react-native-maps@1.4.0
- enable google maps by adding a valid api key
- npx expo prebuild
- npx expo run:ios

### Expected result

A running build

### Actual result

Build error

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.3

### What version of Expo are you using?

SDK 48

### Device(s)

arm64 iOS Simulator

**Comment by marvwhere** [comment]
For the moment, my workaround is to keep working.

    arch -x86_64 npx expo run:ios

**Comment by zaubara** [comment]
Well, obviously you can compile it through Rosetta. My whole point was NOT using Rosetta.

**Comment by Simon-TechForm** [comment]
Hello everyone 👋

Please check out the latest installation instructions to support apple silicon and also the latest beta version to support use_frameworks! 👍

**Comment by zaubara** [comment]
Hi, and thank you.
Quite a few people are patiently waiting for a tagged release on the official repo (https://github.com/googlemaps/google-maps-ios-utils/issues/437).

I mentioned in my first post that using the main branch
pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :branch => 'main'

would work, or alternatively by using the commit directly

pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :commit => '637954e5bcb2a879c11a6f2cead153a6bad5339f'

So I'm not sure if using a fork is the best solution, but it surely would work for most scenarios.

Personally, I'm using expo prebuild and have ios and android in .gitignore, so editing the Podspec manually is suboptimal at best. On the other hand, I'm not sure if there even is a solution for react-native-maps without an update to google-maps-ios-utils.

**Comment by erik-lissen** [comment]
@zaubara 
Thanks for the help, I'm in the exact same situation.

I made a config plugin for myself to bypass this issue. As you said, the problem is that using expo prebuild will regenerate the podfile so we can't just edit it. This config plugin will add the line after the Podfile is generated.


```js

// ./react-native-maps-ios-fix.js
const plugins = require("@expo/config-plugins");
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const fs = require("fs");
const path = require("path");

module.exports = function withFlipper(config) {
  return plugins.withDangerousMod(config, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );
      const contents = fs.readFileSync(filePath, "utf-8");

      const enableFix = mergeContents({
        tag: "react-native-maps ios fix",
        src: contents,
        newSrc: `  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :branch => 'main' `, //adding the line to point Google-Maps-iOS-Utils to the main branch
        anchor: /use_native_modules!/, //we find this line
        offset: -1, //we add it on the line before
        comment: "#",
      });

      if (!enableFix.didMerge) {
        console.log("ERROR: Cannot add react-native-maps-ios-fix to Podfile.");
        return config;
      }

      fs.writeFileSync(filePath, enableFix.contents);

      return config;
    },
  ]);
};

//app.json or app.config.js

plugins: [
     ...,
      "./expoPlugins/react-native-maps-ios-fix",
    ],
```

**Comment by thisYogesh** [comment]
@erik-lissen This ^ worked for me!

**Comment by mjd** [comment]
@erik-lissen I had to update my plugin to use         
newSrc: `  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`,

Which I figured-out by reading the pod details at https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md

Thanks again for the plugin idea. Works great.

**Comment by erik-lissen** [comment]
@mjd 
Thanks for the tip, woke up today to my EAS build failing and you fixed it for me within 5 minutes :) 
I can see that Google-Maps-iOS-Utils had a release 4 days ago, so hopefully we can get this behind us soon

**Comment by enisze** [comment]
I got these errors: 
❌  (/var/folders/d4/vs95y56x7_ddxqkybw1l9l1w0000gn/T/eas-build-local-nodejs/da587945-8535-4b09-9506-3dcc1a523dae/build/apps/proprate-mobile/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:327:2)

  325 |
  326 | #else
> 327 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  328 | #endif
  329 |

[RUN_FASTLANE]
❌  (../../../../../../../../../../private/var/folders/d4/vs95y56x7_ddxqkybw1l9l1w0000gn/T/eas-build-local-nodejs/da587945-8535-4b09-9506-3dcc1a523dae/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 |
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 |
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 |
  
  Any idea? 
  I tried the first suggestion: 
<img width="899" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/15271433/01040061-6595-4915-bd90-fac24e7953f6">

This is now the .js file I am using and get the following erorr
```
// ./react-native-maps-ios-fix.js
const plugins = require('@expo/config-plugins')
const {
  mergeContents,
} = require('@expo/config-plugins/build/utils/generateCode')
const fs = require('fs')
const path = require('path')

module.exports = function withFlipper(config) {
  return plugins.withDangerousMod(config, [
    'ios',
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile',
      )
      const contents = fs.readFileSync(filePath, 'utf-8')

      const enableFix = mergeContents({
        tag: 'react-native-maps ios fix',
        src: contents,
        newSrc: `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon`,
        anchor: /use_native_modules!/, //we find this line
        offset: -1, //we add it on the line before
        comment: '#',
      })

      if (!enableFix.didMerge) {
        console.log('ERROR: Cannot add react-native-maps-ios-fix to Podfile.')
        return config
      }

      fs.writeFileSync(filePath, enableFix.contents)

      return config
    },
  ])
}
```

Now I get this:

<img width="899" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/15271433/c079fea1-51f7-4998-af86-9f9dd49a3e2f">
