### ISSUE TITLE
Custom Markers not rendering completely in React Native IOS when number of marker or marker size increases

### ISSUE THREAD

**Issue by shailzakumari08** [react-native-maps/react-native-maps#4625]
### Summary

I am trying to render custom marker in android and ios and using react-native-maps library. The number of markers is between 16-900. So when the number of marker increases(>60) or the marker size increases the markers are not rendering completely in ios whereas there is no issue observed in android for any number of markers or marker size. Let me elaborate the issue...what is happening is few markers are rendering properly and visible on the screen but few markers are on the screen and not visible and when i click at that place then it becomes visible.

I tried following things:-

1. Tried using icon and image prop of Marker component of react-native-maps library but the issue was same after the number of markers increased from 700.

2. Used svg image instead of Image from react-native library.

3. When used default marker the markers rendered properly in ios as well as android.

4. Used ref in Marker Component to set TrackViewChange to false. Reference Url (https://github.com/react-native- 
maps/react-native-maps/issues/3384)

Whatever above i tried same problem of marker rendering was reproduced. Whatever the number of marker is or whatever the size is we want markers to get rendered properly and visible on the screen.

### Reproducible sample code

```TSX

import React from 'react';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';
class CustomMap extends React.Component {

    constructor(props) {
      super(props);

      this.state = {
        markers: [],`enter code here`
        region: {
          latitude: 34.334653,
          longitude: 134.365288,
          latitudeDelta: 0.45,
          longitudeDelta: 0.45,
        },
      };
     }

     render() {
       const {
         region,
         markers,
       } = this.state;

       return (

        <View style={{flex:1}}>
          <MapView
            provider={PROVIDER_GOOGLE}
            style={styles.map}
            initialRegion={region}
            region={region}
            ref={ref => (this.map = ref)}>
            {markers &&
              markers.map((marker, index) => (
                <CustomMarker
                  marker={marker}
                  key={index}
                />
              ))}
          </MapView>
      </View>
    );
   }
  }
 }


**Below is the CustomMarker class**


import React, {useState} from 'react';
import {Marker} from 'react-native-maps';


const CustomMarker = ({marker}) => {
  const [tracksViewChanges, setTracksViewChanges] = useState(true);

  return (
    <Marker
      key={marker.key}
      coordinate={marker}
    >
      <Image fadeDuration={0} source={getIcon(marker)} />;
    </Marker>
  );
};

const getIcon = marker => {
  switch (marker?.id) {
    case a:
      return require('Assets/Images/img1/a.png');
    case b:
      return require('Assets/Images/img2/b.png');
    case c:
      return require('Assets/Images/img3/c.png');
    default:
  }
};


### Steps to reproduce

1. Please use MapView, Marker from 'react-native-maps'.
2. Try to render list of markers and use custom image for markers because default marker is working fine.
3. In IOS the issue is reproduced with large size png image or with more number of markers like 500-1000 numbers in google map.

### Expected result

In IOS it should render all the markers in google map whatever the marker size or number be. 

### Actual result

<img width="1175" alt="Screenshot 2023-03-02 at 9 30 32 PM" src="https://user-images.githubusercontent.com/98683033/222719832-49dc0ee7-96f1-4394-9120-7b99abe844d8.png">



### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

>= 0.64.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro - iOS 16.1 simulator

### Additional information

_No response_

**Comment by shailzakumari08** [comment]
How the issue looks like in simulator:-
<img width="1175" alt="Screenshot 2023-03-02 at 9 30 32 PM" src="https://user-images.githubusercontent.com/98683033/222720253-5cd83117-34ab-48da-98c1-694fe6a7d6e0.png">

**Comment by InnaZakarzheeva** [comment]
Do you have any updates with it?

**Comment by RyanTG** [comment]
We are experiencing this, as well. Markers mysteriously disappear when using iOS and displaying 200+). Have not checked Android because we are unable to use custom markers with Android due to massive performance issues.

**Comment by pharazon** [comment]
I'm experiencing this on IOS, when zooming out. There are total of 300 custom markers, but some of them disappear when zooming out. I tested that limiting the number of markers to 100 works ok, so there is an issue if there are more than ~200+ markers visible. On Android everything works ok.

**Comment by ml242** [comment]
I am having something related happen. I have a few hundred markers, after clicking on some to open them a handful disappear or turn into default red pin markers that are not clickable. No clue what is going on, the code is very boilerplate.

**Comment by vivianmauer** [comment]
In my case I'm using custom markers with remote images and the markers disappear when trying to set the `tracksViewChanges` of all of them almost simultaneously.

I was able to resolve this by adding the `onLoadEnd` prop to the Image component with the following implementation
```
  const onLoadEnd = useCallback(() => {
    setTimeout(() => {
      ref.current?.setNativeProps({tracksViewChanges: false});
    }, index * 100);
  }, [index]);
```

**Comment by KHadham** [comment]
Still relevant
marker is not shown on maps but still can be pressed

**Comment by yaminichhabra** [comment]
I am also facing this issue, any update on this ?

**Comment by seyedmostafahasani** [comment]
Same here!

**Comment by ChanuPerera** [comment]
I am facing the same issue, The custom marker is not getting the width/height as I gave. Its just rendering in a specific square which has the width/height equals to default marker. any solution?

**Comment by jeppeerixon** [comment]
> In my case I'm using custom markers with remote images and the markers disappear when trying to set the `tracksViewChanges` of all of them almost simultaneously.
> 
> I was able to resolve this by adding the `onLoadEnd` prop to the Image component with the following implementation
> 
> ```
>   const onLoadEnd = useCallback(() => {
>     setTimeout(() => {
>       ref.current?.setNativeProps({tracksViewChanges: false});
>     }, index * 100);
>   }, [index]);
> ```

Same conclusion here. Trying to set and array of markers with {tracksViewChanges: false} makes them invisible. But rendering one at a time with {tracksViewChanges: false} works.
