### ISSUE TITLE
Maps not showing on Android in Expo app after EAS build

### ISSUE THREAD

**Issue by Pcummings** [react-native-maps/react-native-maps#4628]
### Summary

Hey Guys,

I've recently implemented react-native-maps in my EXPO app. Apart from the showsMyLocationButton={true} does not seem to work on IOS, it otherwise works without a hitch in both development build and production for IOS, but for android it only works in the development build, not the production

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
                    provider={(Platform.OS == "android" ? PROVIDER_GOOGLE : PROVIDER_DEFAULT)}
                    initialRegion={{
                        latitude: currentLocation.coords.latitude,
                        longitude: currentLocation.coords.longitude,
                        latitudeDelta: 0.0522,
                        longitudeDelta: 0.0421,
                    }}
                    showsUserLocation={true}
                    showsMyLocationButton={true}
                    style={styles.map} />
  );
}
```

### Steps to reproduce

Build the app and push to google play, then install it.

### Expected result

I expected the map to show

### Actual result

![IMG_3852](https://user-images.githubusercontent.com/6900289/223088189-7db64a3e-9f80-4884-ad35-6956c01797b2.jpg)

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.3

### What version of Expo are you using?

SDK 48

### Device(s)

Xiaomi 9C

### Additional information

I have tried in EXPO SDK 47 too and with version 1.3.2 of react-native-maps.

Additionally I have checked that all api keys are in place.

**Comment by Pcummings** [comment]
So it seemed that I had not checked all the keys properly - the fingerprint for the production app was incorrect.

**Comment by victm1121** [comment]
> So it seemed that I had not checked all the keys properly - the fingerprint for the production app was incorrect.

Hi @Pcummings , could you tell me how you resolved the issue in detail?
I have exactly the same issue as yours.
Expo 48, React Native 0.71.3, and Vivo.

**Comment by GeneCodeFx** [comment]
> So it seemed that I had not checked all the keys properly - the fingerprint for the production app was incorrect.

Aaa Yes, the fingerprint 😴 I was having the same problem and I also used the wrong SHA1 Fingerprint for the api key

**Comment by Pcummings** [comment]
> 

@victm1121 when you build an app, you can find a SHA1 Fingerprint in Expo under credentials - take that SHA1 fingerprint and copy it to your google API credentials that you are using, and then it should work.

**Comment by nsoeth** [comment]
Same problem. Going back to 0.30.2 works again. However, I had a 4k png image before, but after upgrading Expo from 45 to 48 (and react-native from 0.68.2 to 0.71.8) I am only able to show a 1024px image which is kind of blurry now. Any plans to resolve this?

**Comment by karimdakroury** [comment]
> > 
> 
> @victm1121 when you build an app, you can find a SHA1 Fingerprint in Expo under credentials - take that SHA1 fingerprint and copy it to your google API credentials that you are using, and then it should work.

Hi, Should i use the Expo SHA1 fingerprint or my google Maps API fingerprint for production builds?

**Comment by MobinAkhter** [comment]
@Pcummings solution works for me as well. 
Use Expo SHA1 in Api key credentials.
If in case it does not work on development build, try on production build. It worked for me on production build.
(Uploaded build to google play console for internal testing, downloaded app from the link retrieved from there).

**Comment by charankosari** [comment]
for me while buillding the app itself is giving me errors

**Comment by JDFleury** [comment]
I was having the same issue. I was using the SHA1 fingerprint from the Expo Dev console and my Android application had an entirely different SHA1. Adding this fingerprint to the list in Google Cloud Console fixed it for me. You can find the SHA1 fingerprint in the Google Play Console for your application.
