### ISSUE TITLE
maximumNativeZ Tiles auto-scaled not working properly

### ISSUE THREAD

**Issue by lucasartsfr** [react-native-maps/react-native-maps#4630]
### Summary

While using a custom Tile for my Map, the server provides max zoom 6. So, I use `maximumNativeZ={6}` to auto scale images on higher zoom. 

But When Zooming, tiles are not display correctly : 

![7](https://user-images.githubusercontent.com/26819739/223667958-cbe049f5-b55c-4bf5-b7ec-d98e2c9d4f7e.jpg)
![6](https://user-images.githubusercontent.com/26819739/223667963-cf781578-d0be-49fc-bd4c-047a3068de73.jpg)

Here is how it should display (zoom 6) and how it render when zoomed (7).

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    >
<UrlTile 
key={MyKey} 
opacity={0.5} 
urlTemplate={"https://darksitefinder.com/maps/tiles/tile_{z}_{x}_{y}.png"} 
maximumNativeZ={6} 
/>  
</MapView>
  );
}
```

### Steps to reproduce

Juste use the https://darksitefinder.com/maps/tiles/tile_{z}_{x}_{y}.png url in a urlTemplate and check with zoom higher than 6

### Expected result

Tiles should be like this ScreenShot even when zooming : 

![6](https://user-images.githubusercontent.com/26819739/223668899-dc697332-cf7a-47d0-9817-aec1409739db.jpg)

### Actual result

This is the result when zoom higher than 6 : 

![7](https://user-images.githubusercontent.com/26819739/223668966-ec966fe3-c840-4f78-9ab2-45936b079813.jpg)

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.3

### What version of Expo are you using?

SDK 48

### Device(s)

Oppo Reno 6

### Additional information

I tried this on Web with Leaflet and the same URL for tiles. Everything is working

**Comment by donhurickerby** [comment]
@lucasartsfr have you found a solution to this issue? I am facing a similar problem with local tiles (loaded from file://) where beyond the max zoom the image changes to something very odd. This is my UrlTile declaration, my tiles have a min at lvl 6 and max at lvl 15 but I want the zoom to extend down to 18 with auto scaling.

`<UrlTile
          minimumZ={6}
          maximumNativeZ={15}
          maximumZ={18}
          urlTemplate={mapData.url}
        />`

**Comment by mikescott** [comment]
I had this issue. In fact, I faced two problems:

1. The main issue discussed here is that these light pollution tiles are 1024x1024 so you need to add `tileSize={1024}` to make them display correctly
2. When zooming in my, my light pollution tiles disappeared - this is because the autoscaling from `maximumNativeZ` only works when using the native provider, and I was using Google Maps on iOS.
