### ISSUE TITLE
Unimplemented component: <AirGoogleMap>

### ISSUE THREAD

**Issue by shaileed** [react-native-maps/react-native-maps#4635]
### Summary

i followed [this steps](https://github.com/react-native-maps/react-native-maps/issues/693#issuecomment-262656417) but not every step as if i add both AirGoogleMap and AirMaps i got error of "285 Duplicate symbols for architecture x86_64". so i just added AirGoogleMap in my project directory. but now when i run my project, at the place of <MapView/> component i am getting error as "Unimplemented component: <AirGoogleMap>". 

Also please update steps in your instructions so that one won't waste time just to implement it.

### Reproducible sample code

```TSX
<View style={styles.container}>
        <MapView
          provider={PROVIDER_GOOGLE} // remove if not using Google Maps
          style={styles.map}
          region={{
            latitude: coords.latitude,
            longitude: coords.longitude,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}>
          <Marker
            coordinate={{
              latitude: coords.latitude,
              longitude: coords.longitude,
            }}
            pinColor="#0C8CE1">
            <FeatherIcon
              size={35}
              name='navigate'
              color='#0C8CE1'
            />
          </Marker>
        </MapView>
      </View>
```

### Steps to reproduce

i followed [this steps](https://github.com/react-native-maps/react-native-maps/issues/693#issuecomment-262656417) but not every step as if i add both AirGoogleMap and AirMaps i got error of "285 Duplicate symbols for architecture x86_64". so i just added AirGoogleMap in my project directory. but now when i run my project, at the place of <MapView/> component i am getting error as "Unimplemented component: <AirGoogleMap>". 

### Expected result

MapView component should return map.

### Actual result

![Simulator Screen Shot - iPhone 13 Pro Max - 2023-03-14 at 21 12 12](https://user-images.githubusercontent.com/114909614/225067992-1f649c4c-f594-4aa1-8a11-a3492af7ea12.png)

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.1

### What version of Expo are you using?

Not using Expo

### Device(s)

All IOS Devices

**Comment by Simon-TechForm** [comment]
Hello everyone 👋

Make sure to check out the latest installation instructions and beta versions for arm64 support, new architecture support etc. 👍

**Comment by Salmankhan033** [comment]
I have the Same issues on M1 how fix it?
I followed the latest installation instructions

**Comment by affansk** [comment]
@Salmankhan033  you can still use in new architecture by adding support of legacy components
project: {
ios: {
unstable_reactLegacyComponentNames: [],
},
android: {
unstable_reactLegacyComponentNames: [],
}, // grouped into "project"
},

**Comment by rdong25** [comment]
Add 
`pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
`
And remove
`
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
`
from the Podfile solved the problem for me on M1 Mac.

**Comment by Piyush-Ratlani** [comment]
> [@Salmankhan033](https://github.com/Salmankhan033) you can still use in new architecture by adding support of legacy components project: { ios: { unstable_reactLegacyComponentNames: [], }, android: { unstable_reactLegacyComponentNames: [], }, // grouped into "project" },

This solution worked for me, just added all the component AirGoogleMap and related components in ios.unstable_reactLegacyComponentNames array.
