### ISSUE TITLE
UrlTile/Wmstile not showing in android platform

### ISSUE THREAD

**Issue by smartdatamn** [react-native-maps/react-native-maps#4648]
### Summary

Currently, I'm implementing wmstile feature on my react native map. But it is working on iPhone, but not working on Android.

 

### Reproducible sample code

```TSX
<MapView
      style={MAPSTYLES.contentMapEmbed}                
      showsUserLocation={this.state.isShowsUserLocation}
      followsUserLocation={this.state.isFollowUserLocation}                
      onRegionChangeComplete={region => {this.onRegionChangeComplete(region)}}
      ref={(map) => {this.map = map}}                                
      >
      <WMSTile 
        key={index}
        urlTemplate={item.wms_url}
        zIndex={item.zindex}
        opacity={parseFloat(item.opacity)}
        tileSize={item.tile_size}
        epsgSpec={item.epsg_spec}
      />
  </MapView>
```

### Steps to reproduce

1. My item includes:
wms_url: https://geoserver.com/wms?service=WMS&version=1.1.0&request=GetMap&layers=layer:layer1&styles=&bbox={minX},{minY},{maxX},{maxY}&width={width}&height={height}&srs=EPSG:3857&format=image/png&transparent=true
zindex: 10
opacity: 1
tile_size: 512
epsg_spec: EPSG:3857

2. Have INTERNET permission
3. Have google api key

### Expected result

Must work on android

### Actual result

Not working on android. Need help on this case. What other configurations are needed?

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.4

### What version of Expo are you using?

SDK 48

### Device(s)

Android 11

### Additional information

Event I tried following urltile, but no luck:
```
<MapView region={this.state.region}>
  <UrlTile
    urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
    maximumZ={19}
    zIndex={99}
  />
</MapView>
```

**Comment by AzranAzwer** [comment]
Hi Did you find a solution ?
