### ISSUE TITLE
GoogleMaps (= 7.1.0), GoogleMaps (= 7.3.0)

### ISSUE THREAD

**Issue by dulguuned** [react-native-maps/react-native-maps#4650]
### Summary

Pod install dependancy issue

### Reproducible sample code

```TSX
pod install
```

### Steps to reproduce

Podfile
    
    require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'tabici' do
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'tabiciTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

 

### Expected result

pod install should not have failed

### Actual result

[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In snapshot (Podfile.lock):
    GoogleMaps (= 7.1.0)

  In Podfile:
    Google-Maps-iOS-Utils (from `https://github.com/Simon-TechForm/google-maps-ios-utils.git`, branch `feat/support-apple-silicon`) was resolved to 4.1.0, which depends on
      GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 1.4.0, which depends on
      GoogleMaps (= 7.3.0)

Specs satisfying the `GoogleMaps (= 7.1.0), GoogleMaps (= 7.3.0), GoogleMaps` dependency were found, but they required a higher minimum deployment target.

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.6

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 iOS 16.2

### Additional information

<img width="1160" alt="Screenshot 2023-03-28 at 02 45 38" src="https://user-images.githubusercontent.com/10085623/228037196-30b12437-924e-4611-bc2e-5d6ba54abdfc.png">

**Comment by MDG-MMeksasi** [comment]
same issue...

**Comment by AlfreddGco** [comment]
same issue

**Comment by HafizzyAhmad** [comment]
I still face the same issue as but Im using react native 0.71.8. I already try suggestion by @ingvardm but still show same error

in node modules im using 
s.dependency 'React-Core'
  s.dependency 'GoogleMaps', '7.4.0'
  s.dependency 'Google-Maps-iOS-Utils', '4.1.0'
  
 in podfile
 rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps', '7.4.0'
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'

minimum deployment target is
IPHONEOS_DEPLOYMENT_TARGET = 15.0;
  
  
![image](https://github.com/react-native-maps/react-native-maps/assets/11407182/aaabba42-9789-4d3d-b1cc-89f570c12d58)

**Comment by uzaymacar** [comment]
`arch -x86_64 pod install --repo-update` is what worked for me

**Comment by Bilalwarind** [comment]
**rm Podfile.lock** delete Podfile.lock and run **pod install** or **pod install --repo-update** 
if you are using M1 then run **arch -x86_64 pod install --repo-update**
