### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [react-native-maps/react-native-maps#4665]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by Simon-TechForm** [comment]
Hello @igibek.

I appreciate you reaching out regarding the detected vulnerability!

While we haven't yet decided to participate in the beta program of `Private vulnerability reporting`, we do have a security policy which includes an email address to privately disclose possible vulnerabilities. This email address is actively monitored. Please visit the [Security tab](https://github.com/react-native-maps/react-native-maps/security).

Once we receive the report, we will do our best to confirm and patch the vulnerability as quickly as possible!
