### ISSUE TITLE
Custom Markers on Android use high CPU and eventually crash the app

### ISSUE THREAD

**Issue by stjasink** [react-native-maps/react-native-maps#4700]
### Summary

Using custom markers on my map will cause high CPU usage in the emulator and eventually the application crashes.  I have pasted in a simple MapView with Markers.  Passing in "true" for "useCustomMarkers" will display the custom markers, and I can see the CPU usage of the emulator running at over 150%, sometimes over 200%.  Passing in "false" will display simple markers instead and the CPU usage is 60% to 70%.

Zooming in to show fewer markers does seem to lower the CPU used, but it's still much higher than non-custom markers.

In my actual application, I see it crash after running for a while with custom markers.  I have not yet seen the sample below actually crash, but it is certainly using a lot of CPU.  This seems to slow down other actions, e.g. clicking on markers to bring up callouts.

This is on Android - I haven't run it on iOS yet but do hope to do so soon.

### Reproducible sample code

```TSX
import React from 'react';
import {StyleSheet, Text, View} from 'react-native';
import MapView, {Marker, PROVIDER_GOOGLE} from 'react-native-maps';

function App() {
  return <MyMap useCustomMarkers={true} />;
}

function MyMap({useCustomMarkers}) {
  return (
    <View style={styles.container}>
      <MapView
        provider={PROVIDER_GOOGLE}
        style={styles.map}
        region={mapRegion}
        showsBuildings={false}
        loadingEnabled={true}
        showsUserLocation={true}
        userLocationPriority={'high'}
        showsMyLocationButton={false}
        minZoomLevel={16}
        maxZoomLevel={22}>
        <MyMapMarkers useCustomMarkers={useCustomMarkers} />
      </MapView>
    </View>
  );
}

function MyMapMarkers({useCustomMarkers}) {
  return markerLocations.map((location, markerNum) =>
    useCustomMarkers ? <Marker
        key={'marker' + markerNum}
        coordinate={{latitude: location.lat, longitude: location.lng}}
        zIndex={markerNum}
        trackViewChanges={false}>
        <View style={styles.markerContainer}>
          <View style={styles.marker}>
            <Text style={styles.markerText}>{markerNum}</Text>
          </View>
          <View style={styles.markerPin} />
        </View>
      </Marker> :
      <Marker
        key={'marker' + markerNum}
        coordinate={{latitude: location.lat, longitude: location.lng}}
        zIndex={markerNum}
        pinColor={'green'}
        trackViewChanges={false}
      />
  );
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  markerContainer: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  marker: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 5,
    borderWidth: 3,
    borderColor: 'green',
  },
  markerPin: {
    width: 3,
    height: 5,
    backgroundColor: 'green',
  },
  markerText: {
    fontWeight: 'bold',
    color: 'black',
  },
});

const mapRegion = {
  latitude: 51.5827395,
  latitudeDelta: 0.0066319,
  longitude: -0.149409,
  longitudeDelta: 0.0019558,
};

const markerLocations = [
  {
    lat: 51.585737,
    lng: -0.150214,
  },
  {
    lat: 51.585365,
    lng: -0.150182,
  },
  {
    lat: 51.584366,
    lng: -0.14934,
  },
  {
    lat: 51.584112,
    lng: -0.14893,
  },
  {
    lat: 51.583913,
    lng: -0.148976,
  },
  {
    lat: 51.582766,
    lng: -0.148754,
  },
  {
    lat: 51.581715,
    lng: -0.149121,
  },
  {
    lat: 51.58113,
    lng: -0.148623,
  },
  {
    lat: 51.579808,
    lng: -0.149114,
  },
  {
    lat: 51.585623,
    lng: -0.150089,
  },
  {
    lat: 51.585319,
    lng: -0.149529,
  },
  {
    lat: 51.584418,
    lng: -0.14897,
  },
  {
    lat: 51.584068,
    lng: -0.148902,
  },
  {
    lat: 51.583705,
    lng: -0.148558,
  },
  {
    lat: 51.582616,
    lng: -0.148923,
  },
  {
    lat: 51.581435,
    lng: -0.149005,
  },
  {
    lat: 51.580887,
    lng: -0.148784,
  },
  {
    lat: 51.579779,
    lng: -0.149297,
  },
];

export default App;
```

### Steps to reproduce

The code above will run in `App.js` in a newly set up React Native project, with only `react-native-maps` installed and the API key added to `AndroidManifest.xml`

Run with `useCustomMarkers={true}` (i.e. code exactly as it is pasted in) and 18 numbered markers show on the map.  The emulator uses a lot of CPU.

Run again with `useCustomMarkers={false}` for comparison and default markers are used instead.  The emulator uses much less CPU. 

### Expected result

I expected the application with custom markers to use less CPU (more or less in line with the default markers) and not crash.

### Actual result

The application uses a lot of CPU, often over 200%, and eventually crashes.
As mentioned in the initial description, my actual application eventually crashes but I have not yet seen the minimal example crash yet.

### React Native Maps Version

1.6.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.7

### What version of Expo are you using?

Not using Expo

### Device(s)

'Nexus_5X_API_31(AVD) - 12'

**Comment by chanphiromsok** [comment]
you might need             tracksViewChanges={tracksViewChangesState} 
 after MarkerDisplay you can change it to tracksViewChangesState to false
