### ISSUE TITLE
min zoom level on android phone

### ISSUE THREAD

**Issue by yeesiang95** [react-native-maps/react-native-maps#4709]
### Summary

Some Android phones, such as Samsung S23, S22, and S20, are unable to decrease the zoom level to less than 3, whereas it works on iPhone and some other Android phones, such as Samsung S9 and S10."

### Reproducible sample code

```TSX
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{
        flex: 1,
      }}
      zoomEnabled={true}
      maxZoomLevel={20}
      minZoomLevel={0}
      initialRegion={{
        latitude: 2.51724718513902,
        longitude: 50.72586748749017,
        latitudeDelta: 157.83621920206184,
        longitudeDelta: 137.10936695337296,
      }}
    />
  );
}
```

### Steps to reproduce

![pixel6 pro map](https://user-images.githubusercontent.com/96831321/233959884-1e6feed0-c797-4305-b359-b63ce51d65c1.png)

### Expected result

able to decrease zoom level to less than 3

### Actual result

can only decrease zoom level to 3

### React Native Maps Version

1.5.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung S23,S22,S20,Pixel 6 Pro (Emulator)

**Comment by Simon-TechForm** [comment]
Hi @yeesiang95 👋

This is actually to be expected, but is missing in the docs!

Check out the [Google Maps docs for zoom](https://developers.google.com/maps/documentation/android-sdk/views#zoom) where the behaviour is mentioned. I've just updated the docs to include the limitation :)
