### ISSUE TITLE
AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.

### ISSUE THREAD

**Issue by rgroothuis** [react-native-maps/react-native-maps#4710]
### Summary

See discussion item: https://github.com/react-native-maps/react-native-maps/discussions/4661 

I've followed all the instructions to install the react-native-maps for ios. I do get the Apple Maps on the simulator so big part of the installation was successful, at least that is my conclusion. When I add the provider={PROVIDER_GOOGLE} statement I get the following error message:

ERROR  react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS. 
   at MapView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.PerfectPerformance:147564:78)
   at RCTView
   at View (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.PerfectPerformance:45739:43)
.......
Of course I've added added to folder to my project, see screenshot:

<img width="279" alt="230023051-3babaa76-48d3-4090-89b1-30a0b408c44f" src="https://user-images.githubusercontent.com/14161204/234096525-4fbd45ad-7a0b-4d03-a4d3-54e0ef693418.png">

Still I'm getting the error message and I don't know what to do. Who can help? Suggestions?

### Reproducible sample code

```TSX
I don't have example code to reproduce the problem, sorry. Multiple users are having the same problem, see discussion item.
```

### Steps to reproduce

Followed the default installation instructions listed at: https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md

### Expected result

When following the instructions and adding the provider={PROVIDER_GOOGLE} parameter to the MapsView should switcht the map from Apple map to Google Maps.

### Actual result

Error message, see above. 

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

10.2.2

### What version of Expo are you using?

Not using Expo

### Device(s)

all iPhone simulators

**Comment by Simon-TechForm** [comment]
Hi @rgroothuis.

I look at the discussion section once in a while as well, so having this as a discussions should be enough 👍

The information you're providing is a little confusing to be honest. What is version `10.2.2` of react-native? You state that you followed the installation instructions, but aren't able to provide a reproducible samle code. Also, based on the screenshot provided, you seem to have copied the AirGoogleMaps folder into your iOS project? This is not a part of the installation instructions and shouldn't be done.

My advise is to start a new project from scratch, do nothing but follow the installation instructions carefully and hopefully get everything working. If you are still unable to, please provide a repo or expo snack reproducing the issue :)

**Comment by stjasink** [comment]
Hi @rgroothuis have you been following the most recent instructions here? https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#ios

There are some very old instructions around that mention copying the AirGoogleMaps folder, but the new ones are much simpler thankfully.

**Comment by daihieptn97** [comment]
You must add this line to Podfile 

- Also make sure that your Podfile deployment target is set to >= 13.0 at the top of your Podfile, eg:


```
platform :ios, '13.0'
```

After run 

```
pod install
```

it working for me!

**Comment by djnewage** [comment]
This is not working for me as well anyone have any updates?

**Comment by stjasink** [comment]
> This is not working for me as well anyone have any updates?

Working for me as per my comment above.  I simply followed the instructions at https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#ios 

I did it on a newly created react-native project, not one that I had previously been trying other outdated installation instructions on.  Also, make sure you are using a recent version of maps - mine is 1.10.1

**Comment by djnewage** [comment]
are you running expo or react native bare? my issue is with expo

**Comment by stjasink** [comment]
> are you running expo or react native bare? my issue is with expo

I am not using expo.  Sorry, I don't have any expo tips!

**Comment by nikhilpawar151** [comment]
I am facing same issue for the iOS. And solved it with the following changes.

package:-
`"react-native-maps": "1.15.4",`

Pod File

`platform :ios, '13.4'`

`rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'`

After this just run following commands to clear all existing cache.
`npx react-native clean
npm i
cd ios
pod install
cd.. 
npm start`

Above steps worked for me.
