### ISSUE TITLE
Polyline lineDashPattern inconsistent between Google maps on iOS and Android

### ISSUE THREAD

**Issue by stjasink** [react-native-maps/react-native-maps#4718]
### Summary

Drawing a Polyline with a lineDashPattern behaves very differently between iOS and Android, both using PROVIDER_GOOGLE.  My assumption is that Android is "correct" here because it's behaving roughly the same as Leaflet maps do.

Using a pattern of [2, 10] and a stroke width of 30 does this, with iOS on the left and Android on the right.  So iOS is making much longer dashes with more space in between:

<img width="881" alt="Screenshot 2023-04-28 at 10 47 46" src="https://user-images.githubusercontent.com/8123071/235201261-b0a1c036-866f-4531-9e05-a5990a32d055.png">

I tried to reduce the lengths for iOS by dividing by 50 by doing this:

```
  if (Platform.OS === 'ios') {
    return pattern.map(num => num / 50);
  } else {
    return pattern;
  }
```

Which almost worked, but some of the lines on iOS come out weirdly diagonal and out of line:

<img width="881" alt="Screenshot 2023-04-28 at 10 52 27" src="https://user-images.githubusercontent.com/8123071/235201753-0976236e-8148-482f-9665-87d2966c9c2d.png">

For interest, this is the same on iOS with MapKit, which is somewhere between the two extremes:

<img width="444" alt="Screenshot 2023-04-28 at 12 21 18" src="https://user-images.githubusercontent.com/8123071/235201971-7d3e7c80-a82e-4391-9083-c8928717009e.png">

While this is clearly not a _critical_ bug, it's a bit annoying and I thought I'd raise it in case there was an easy fix for it.  If I knew more about how react native works, I would attempt to investigate myself but that's unlikely to happen very soon.

### Reproducible sample code

```TSX
function MyMap() {
  return (
    <View style={styles.container}>
      <MapView
        provider={PROVIDER_GOOGLE}
        style={styles.map}
        region={{
          latitude: 41.877175,
          latitudeDelta: 0.0001562,
          longitude: 1.5717355,
          longitudeDelta: 0.0003003,
        }}
        minZoomLevel={16}
        maxZoomLevel={22}>
        <Polyline
          coordinates={[
            {latitude: 41.877, longitude: 1.5718},
            {latitude: 41.877162, longitude: 1.571836},
          ]}
          strokeWidth={30}
          lineDashPattern={[2, 10]}
          lineCap={'butt'}
          strokeColor={'black'}
        />
      </MapView>
    </View>
  );
}
```

### Steps to reproduce

Run the sample code in iOS and Android to see the difference in the line dash pattern.

### Expected result

I expect the iOS dash pattern to behave the same as Android.  (Above, I pointed out the assumption that Android is correct!)

And if I do need to scale the pattern to work on iOS, I would at least like it to work without some dashes displaying crooked (this could be something inherent and unavoidable in Google maps in iOS though)

### Actual result

The dash pattern on iOS produces much longer dashes and gaps, roughly 50 times longer.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.7

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 12 Pro Max with iOS 16, Nexus_5X_API_31(AVD) - 12

**Comment by stjasink** [comment]
I tried with a circle and polygon also, and it looks like lineDashPattern is ignored for those on Google Maps on both iOS and Android:

<img width="834" alt="Screenshot 2023-05-03 at 10 18 00" src="https://user-images.githubusercontent.com/8123071/235878324-b733129c-ffd4-47b3-91c6-03b51ca1de11.png">

On iOS with MapKit default map provider, it does work:

<img width="406" alt="Screenshot 2023-05-03 at 10 18 16" src="https://user-images.githubusercontent.com/8123071/235878442-77c5e208-c571-4951-9401-149c1ffb39e4.png">

Code for adding the new shapes:

```
function MyMap() {
  enableLatestRenderer();
  const width = 10;
  const dashPattern = [2, 5];
  return (
    <View style={styles.container}>
      <MapView
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        region={{
          latitude: 41.877175,
          latitudeDelta: 0.0005,
          longitude: 1.5717355,
          longitudeDelta: 0.0005,
        }}>
        <MapPolyline
          coordinates={[
            {latitude: 41.877, longitude: 1.5718},
            {latitude: 41.877162, longitude: 1.571836},
          ]}
          strokeWidth={width}
          lineDashPattern={dashPattern}
          lineCap={'butt'}
          strokeColor={'black'}
        />
        <MapPolygon
          coordinates={[
            {latitude: 41.877264, longitude: 1.571732},
            {latitude: 41.877205, longitude: 1.571567},
            {latitude: 41.877041, longitude: 1.57167},
            {latitude: 41.877098, longitude: 1.571833},
          ]}
          strokeWidth={width}
          lineDashPattern={dashPattern}
          lineCap={'butt'}
          strokeColor={'black'}
        />
        <MapCircle
          center={{latitude: 41.877, longitude: 1.5718}}
          radius={15}
          strokeWidth={width}
          strokeColor={'black'}
          lineDashPattern={dashPattern}
        />
      </MapView>
    </View>
  );
}
```

**Comment by leymytel** [comment]
I'm experiencing the same issue on 0.71.7 with Google provider and Hermes enabled.
Also, the app is super laggy when I render a couple of polylines.
I had to remove the `lineDashPattern` from iOS.

**Comment by stjasink** [comment]
I had a look at the underlying implementations of Google maps for iOS and Android.  In both cases, react-native-maps uses the `lineDashPattern` numbers as specified and passes them to the native library, but the libraries are actually very different despite both being Google Maps.

For iOS, the dashes are specified using `spans` (https://developers.google.com/maps/documentation/ios-sdk/shapes#add-a-repeating-color-pattern-to-a-polyline) and the numbers passed in are used to specify the length of the dashes in _metres_ (https://developers.google.com/maps/documentation/ios-sdk/reference/group___length_kind).

For Android, the dashes are specified using `pattern` (https://developers.google.com/maps/documentation/android-sdk/shapes#stroke_pattern) and the numbers passed in are used to specify the length of the dashes in _pixels_.

Given that react-native-maps gives a single interface to both of these, it would be neater for it to do some internal translation so that the effect is the same in both cases.  Someone would need to make a call as to which one is "correct" in this case.

**Comment by stjasink** [comment]
PS the issue with the uneven and skew dashes in iOS in my use case seems to be entirely down to how the Google Maps library for iOS handles fractional lengths and is nothing to do with react-maps-native.

**Comment by stjasink** [comment]
I found another way to achieve what I wanted to, without using the dash patterns.  So I don't need this any more.  Others might still want it though, if maybe just for consistency.

**Comment by trantus** [comment]
Still relevant

**Comment by trantus** [comment]
> PS the issue with the uneven and skew dashes in iOS in my use case seems to be entirely down to how the Google Maps library for iOS handles fractional lengths and is nothing to do with react-maps-native.

Please can you provide some details, what exactly you achieved? might be it could be useful in my case

**Comment by stjasink** [comment]
@trantus to get the line dash lengths to look the same on Google maps in iOS and Android, I had to divide the iOS lengths by 50.  So where I was using a pattern of [2, 10] for Android, I used [0.04, 0.2] for iOS.  This caused some of the lines to look uneven and skew in iOS, which I assume is down to some internal rounding errors in the iOS implementation for Google Maps.  The code in react-maps-native is just passing these values into the Google Maps library and not manipulating them, so any rendering problems must be in that library.  

As I mentioned above, I eventually found another way to get the effect that I wanted and stopped investigating this any further.

**Comment by trantus** [comment]
@stjasink Thank you, works perfect for me

**Comment by Adriano2108** [comment]
I am completely unable to have a dash or dot pattern, (android & ios)

      <Polyline
        key={`${line.line}-${index}`}
        coordinates={line.data.map(station => ({
          latitude: station.latitude,
          longitude: station.longitude,
        }))}
        strokeWidth={5}
        lineDashPattern={[2, 10]}
      />
      
      I've tried putting all types of numbers instead of [2, 10] and the line is still the simple filled line. I am so lost

**Comment by stjasink** [comment]
@Adriano2108 what zoom level are you using?  If you are zoomed far out, it might be that the dashes are too small to see.  In one of the implementations (probably iOS but can't remember), the dash pattern related to metres on the ground.  In my example above, I was zoomed in at zoom level 20 to 22, so the small dash pattern numbers were visible.  If you are zoomed out more than that then you will need much bigger numbers for it to look correct.

**Comment by trantus** [comment]
> I am completely unable to have a dash or dot pattern, (android & ios). I am using expo managed workflow
> 
> ```
>       <Polyline
>         key={`${line.line}-${index}`}
>         coordinates={line.data.map(station => ({
>           latitude: station.latitude,
>           longitude: station.longitude,
>         }))}
>         strokeWidth={5}
>         lineDashPattern={[2, 10]}
>       />
> ```
> 
> I've tried putting all types of numbers instead of [2, 10] and the line is still the simple filled line. I am so lost

 [0.04, 0.2] - did you try that pattern on iOS?
