### ISSUE TITLE
"never" is not paddingAdjustmentBehavior default

### ISSUE THREAD

**Issue by theodoregold** [react-native-maps/react-native-maps#4724]
### Summary

Default value for `paddingAdjustmentBehavior` in docs is `"never"`, however in reality it is `"always"`. 

Here is the link to source:
https://github.com/react-native-maps/react-native-maps/blob/bd9a8c84123d060415a4660498ca30d6f95cb659/ios/AirGoogleMaps/AIRGoogleMap.m#L421

### Reproducible sample code

```TSX
NA
```

### Steps to reproduce

NA

### Expected result

It should not apply any safe inset padding. In my case to Google logo watermark.

### Actual result

It applies magic padding, which turns out to be safe inset padding. 😢 

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.7

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14

**Comment by Simon-TechForm** [comment]
Thank you for reporting this :) I've updated the docs to include the correct default value.
