### ISSUE TITLE
GeoJson is very slow with MultiPolygon

### ISSUE THREAD

**Issue by saransh-malik** [react-native-maps/react-native-maps#4728]
### Summary

When trying to use a GeoJson component even with just 4 MultiPolygon, the maps go frozen. The JS and UI frame rate goes to 0 for a good minute or so before coming back normal. Is there any workaround we can do to achieve a better performance?
I am already using trackViewChanges as false but that has no impact on the rendering performance. 

### Reproducible sample code

```TSX
<Geojson
          key={'territories'}
          tracksViewChanges={false}
          geojson={props.territories}
        />
```

### Steps to reproduce

1. Add GeoJson to your MapView
2. Try to render 3-4 MultiPolygon at US state level
3. Map freezes and won't respond

### Expected result

The performance shouldn't be impacted

### Actual result

The maps freeze and won't respond for a minute or so, once the polygons are rendered then the maps performs smoothly.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.69.0

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13, Galaxy Tab A8

**Comment by tommasoberlose** [comment]
Still relevant
