### ISSUE TITLE
Android app crashed with eas production build

### ISSUE THREAD

**Issue by stefanoScalzo** [react-native-maps/react-native-maps#4746]
### Summary

when trying to build the prod build and test it on my phone by downloading the APK it keeps crashing. Looking at the logcat adb errors it keeps saying 
java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml

I've triple checked the files with my keys, but it keeps crashing

### Reproducible sample code

```TSX
im trying to build my app in prod mode but react-native-maps seems to keep crashing it, 
what ive done: 
1. gotten the api key and put it in the app.json
    "android": {
      "versionCode": 3,
      "config": {
        "googleMaps": {
          "apiKey": "MYKEY"
        }
      },

2. Ive supplied GOOGLE_PROVIDER in the mapview like so
provider={PROVIDER_GOOGLE}

It works perfectly fine with expo go but not with the EAS build , can someone please tell me why?
```

### Steps to reproduce

run: eas build -p android

### Expected result

The app crashes

### Actual result

The app should not crash and the map should be shown

### React Native Maps Version

^1.4.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.8

### What version of Expo are you using?

SDK 47

### Device(s)

Samsung S10

### Additional information

full error log
`FATAL EXCEPTION: main
05-17 17:53:01.436 24918 24918 E AndroidRuntime: Process: com.puggum.pickaplace, PID: 24918
05-17 17:53:01.436 24918 24918 E AndroidRuntime: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.maps.api.android.lib6.drd.p.a(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):6)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.internal.CreatorImpl.b(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):31)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.internal.CreatorImpl.logInitialization(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):3)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.internal.g.bb(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):5)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at ff.onTransact(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):4)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:1100)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.0.0:2)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.internal.zze.zzl(com.google.android.gms:play-services-maps@@18.0.0:4)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.0.0:12)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.0.0:1)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.zzah.zzb(com.google.android.gms:play-services-maps@@18.0.0:2)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.zzah.createDelegate(com.google.android.gms:play-services-maps@@18.0.0:1)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.1.0:6)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.1.0:1)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.0.0:4)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.rnmaps.maps.MapView.<init>(MapView.java:174)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.rnmaps.maps.MapManager.createViewInstance(MapManager.java:71)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.rnmaps.maps.MapManager.createViewInstance(MapManager.java:28)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:183)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:792)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
05-17 17:53:01.436 24918 24918 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
05-17 17:53:01.467   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*launch*[S]
05-17 17:53:01.468   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*launch*[S]
05-17 17:53:01.480  4392  7064 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
05-17 17:53:01.480  2079  2497 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
05-17 17:53:01.481  6754 18084 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
05-17 17:53:01.483  2079  2166 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
05-17 17:53:01.487  4799 14329 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
05-17 17:53:01.583 28402 25093 E DropBoxUtil: [AppErrors] null InputStream [CONTEXT service_id=254 ]
05-17 17:53:01.583 28402 25093 E DropBoxUtil: java.io.IOException: null InputStream
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at ccmk.c(:com.google.android.gms@231613044@23.16.13 (190400-527363516):23)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cckv.m(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cckj.apply(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at ldz.apply(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at len.apply(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvun.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at degh.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmi.d(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmk.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):9)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dknv.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.h(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.gl(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmk.g(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvtz.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at degf.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkob.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkqc.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkpd.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):3)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkqe.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkod.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):7)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dknv.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkod.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):9)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.h(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.gl(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkof.c(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvue.i(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvuo.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at degh.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmi.d(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmk.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):9)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dknv.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.h(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.gl(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmk.g(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvul.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at degf.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkob.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkqc.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkpd.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):3)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkqe.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkod.run(:com.google.android.gms@231613044@23.16.13 (190400-527363516):7)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dknv.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkod.execute(:com.google.android.gms@231613044@23.16.13 (190400-527363516):9)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.h(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkmg.gl(:com.google.android.gms@231613044@23.16.13 (190400-527363516):4)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at dkof.c(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvut.c(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at cvut.b(:com.google.android.gms@231613044@23.16.13 (190400-527363516):2)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):44)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at hdo.handleMessage(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at android.os.Looper.loopOnce(Looper.java:226)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at android.os.Looper.loop(Looper.java:313)
05-17 17:53:01.583 28402 25093 E DropBoxUtil: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: [AppDoctor] null InputStream [CONTEXT service_id=254 ]
05-17 17:53:01.586 28402 25093 E DropBoxUtil: java.io.IOException: null InputStream
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at ccmk.c(:com.google.android.gms@231613044@23.16.13 (190400-527363516):23)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at cckv.m(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at cckn.apply(:com.google.android.gms@231613044@23.16.13 (190400-527363516):5)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@231613044@23.16.13 (190400-527363516):56)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@231613044@23.16.13 (190400-527363516):1)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at hdo.handleMessage(:com.google.android.gms@231613044@23.16.13 (190400-527363516):0)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at android.os.Looper.loopOnce(Looper.java:226)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at android.os.Looper.loop(Looper.java:313)
05-17 17:53:01.586 28402 25093 E DropBoxUtil: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-17 17:53:01.605   961   961 E BpTransactionCompletedListener: Failed to transact (-32)
05-17 17:53:01.618   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*launch*[S]
05-17 17:53:01.618   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*launch*[S]
05-17 17:53:01.642  2705  2705 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-17 17:53:01.648  3322  3322 E pageboostd: Received HALT command code 2
05-17 17:53:01.669   961   961 E SurfaceFlinger: Attempt to update InputPolicyFlags without permission ACCESS_SURFACE_FLINGER
05-17 17:53:01.672   961  3247 E NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
05-17 17:53:01.679  2705  2705 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-17 17:53:01.680  2705  2705 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-17 17:53:01.709  2705  2705 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
05-17 17:53:01.719   961   961 E SurfaceFlinger: Attempt to update InputPolicyFlags without permission ACCESS_SURFACE_FLINGER
05-17 17:53:02.537  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:03.036  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:04.637  1118  4526 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-17 17:53:04.639  1118  4526 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-17 17:53:04.639  1118  4526 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-17 17:53:04.930  1118  1817 E AlarmManager: Attempt to decrement existing alarm count 0 by 1 for uid 1000
05-17 17:53:04.965  1118  1817 E AlarmManager: Attempt to decrement existing alarm count 0 by 1 for uid 1000
05-17 17:53:05.126   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:05.127   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:05.131   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:05.131   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:06.535  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:09.538  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:10.034  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:10.081   771  1904 E TrafficController: FREECESS
05-17 17:53:12.212   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:12.214   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:12.216   770   776 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:12.216   770   776 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10828[I] (10)0x30000->*alarm*[S]
05-17 17:53:12.539  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:13.741   631   657 E vold    : getUsedF2fsFileNode -> Cannot Get Used FileNode Number (errno=25 Inappropriate ioctl for device)
05-17 17:53:14.910  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:14.939   741   741 E audit   : type=1400 audit(1684360394.924:17916): avc:  denied  { kill } for  pid=0 comm="swapper/2" capability=5  scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0 SEPF_SM-G973W_12_0001 audit_filtered
05-17 17:53:14.998  1118  1842 E MotionRecognitionService: handleMessage: event 200 value : 1
05-17 17:53:15.094  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:15.127  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:15.181 25546 26274 E [ND]SurveyMeasurementService: AsyncTask #1 | onError: applyPolicyRestrictions, Failed requirement., disposed=true
05-17 17:53:15.228  2546  2801 E #IMSCR  : 05-17 17:53:15 0x1101000A:0,PDN FAIL:NOT_DEFINED
05-17 17:53:15.234  2546  2801 E #IMSCR  : 05-17 17:53:15 0x1101000A:0,PDN FAIL:NOT_DEFINED
05-17 17:53:16.036  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:17.132  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:19.043  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:19.372  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:21.246  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:21.263  1118  1842 E MotionRecognitionService: handleMessage: event 200 value : 1
05-17 17:53:21.275  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:22.035  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:24.323  1118  1484 E Watchdog: !@Sync: 2549 heap: 110 / 130 [2023-05-17 17:53:24.322] sdogWay: softdog FD: 1014
05-17 17:53:25.542  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:26.288   771  1904 E TrafficController: FREECESS
05-17 17:53:29.537  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:29.912  1118  4595 E PersonaManagerService: DeviceLocked : true, DeviceSecure : true
05-17 17:53:29.917  1118  1118 E PersonaManagerService: DeviceLocked : true, DeviceSecure : true
05-17 17:53:29.973  1225  1978 E bauth_FPQCBAuthSensorControl: BAuthDeviceWaitIPC sys call failed : 4
05-17 17:53:29.987 20841 20841 E ThemeUtils: View class com.airbnb.lottie.LottieAnimationView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
05-17 17:53:29.996 20841 20841 E ThemeUtils: View class com.airbnb.lottie.LottieAnimationView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
05-17 17:53:30.274  1118  4594 E WindowManager: win=Window{d35a9e3 u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5842 com.android.server.wm.ActivityRecord.destroySurfaces:5823 com.android.server.wm.ActivityRecord.notifyAppStopped:5887 com.android.server.wm.ActivityRecord.activityStopped:6513 com.android.server.wm.ActivityClientController.activityStopped:253 android.app.IActivityClientController$Stub.onTransact:596 com.android.server.wm.ActivityClientController.onTransact:129
05-17 17:53:30.280  2079  2213 E CscParser: update(): xml file exist
05-17 17:53:30.292  2079  2213 E CscParser: update(): xml file exist`

 React native map code
import { StyleSheet, View, Text } from 'react-native'
import { loadTranslations } from './i18n/localization'
import { flex_style, margin_styles } from './global/global-styles'
import { useEffect, useState, useRef } from 'react'
import { width } from './global/global-constants'
import Slider from '@react-native-community/slider'
import MapView from 'react-native-maps'
import { Marker, PROVIDER_GOOGLE } from 'react-native-maps'

const LATITUDE_DELTA = 0.015
const LONGITUDE_DELTA = 0.0121

export default function GoogleMap(props) {
  const mapViewRef = useRef()
  const [radius, setRadius] = useState(20)
  const [latitude, setLatitude] = useState(props.location?.lat ? props.location?.lat : 45.645524)
  const [longitude, setLongitude] = useState(props.location.long ? props.location.long : -73.586019)
  const [chosenLatitude, setChosenLatitude] = useState(props.location?.lat ? props.location?.lat : 45.645524)
  const [chosenLongitude, setChosenLongitude] = useState(props.location.long ? props.location.long : -73.586019)

  if (props.location.lat) {
    return (
      <View
        style={[
          flex_style.flex,
          flex_style.column,
          flex_style.center,
          {
            flex: 1,
            width: '100%',
          },
          margin_styles.vertical_space_xl
        ]}
      >
        <View
          style={margin_styles.vertical_space_md}
          width={width}
          height={width}
        >
          <MapView
            provider={PROVIDER_GOOGLE}
            ref={mapViewRef}
            initialRegion={{
              latitude: props?.latitude,
              longitude: props?.longitude,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LONGITUDE_DELTA
            }}
            onRegionChange={(event) => {
              setChosenLatitude(event.latitude)
              setChosenLongitude(event.longitude)
              props.setLocation({ lat: event.latitude, long: event.longitude })
            }}
            style={styles.map}
          >
            {
              chosenLatitude && chosenLongitude ? 
              <Marker
                coordinate={{
                  latitude: chosenLatitude,
                  longitude: chosenLongitude
                }}
                /> : 
                <Marker coordinate={{ latitude: latitude, longitude: longitude }}/>
            }
          </MapView>
        </View>
        <Slider
          width={'75%'}
          maximumValue={100}
          minimumValue={1}
          onValueChange={(event) => {
            if (event) {
              props.setRadius(Math.round(event))
              setRadius(Math.round(event))
            }
          }}
          value={radius}
        />
        <Text>
          {loadTranslations('generalRadius') + ' : ' + radius + ' km'}
        </Text>
      </View>
    )
  } else {
    return <View></View>
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    width: '100%',
    height: '100%',
  },
})

**Comment by spyshower** [comment]
Did you guys find anything? @dallf44  @stefanoScalzo

**Comment by stefanoScalzo** [comment]
@spyshower yea I simply stopped using eas to build my prod builds

**Comment by spyshower** [comment]
@stefanoScalzo looks like eas is the only way to build now though :P

**Comment by stefanoScalzo** [comment]
Its not you need to prebuild your files and then use ios n grade commands
