### ISSUE TITLE
Add apple silion support by updating the google maps ios utils to 4.2.2

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-maps/react-native-maps#4754]
### Summary

Can you please update the lib with new version of google maps ios utils? 

More: https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v4.2.2

### Reproducible sample code

```TSX
Not applicable
```

### Steps to reproduce

Not applicable 

### Expected result

Build with Apple Silicon

### Actual result

Not applicable 

### React Native Maps Version

any

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

any

### What version of Expo are you using?

Not using Expo

### Device(s)

Not applicable

**Comment by Simon-TechForm** [comment]
Thank you for opening the PR - I've commented on it, and we should be able to continue the discussion there :)
