### ISSUE TITLE
only generated aab file have grey screen, apk working good

### ISSUE THREAD

**Issue by skompaniets** [react-native-maps/react-native-maps#4758]
### Summary

1. added api key
2. apk/debug working good

### Reproducible sample code

```TSX
<resources>
  <string name="google_maps_key" templateMergeStrategy="preserve" translatable="false">key</string>
</resources>
```

### Steps to reproduce

map view

### Expected result

map must working

### Actual result

map is grey

### React Native Maps Version

^1.4.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Realme 6

**Comment by ashok3** [comment]
@skompaniets did you find a solution?
