### ISSUE TITLE
Inconsistent docs for Overlay component

### ISSUE THREAD

**Issue by rokamon1997** [react-native-maps/react-native-maps#4759]
### Summary

What is the right way of providing bounds for overlay? I can't seem to get it working.

- comment for bounds in MapOverlay.d.ts says "_**The coordinates for the image (left-top corner, right-bottom corner). ie.**_"
- docs API (note) for overlay component says "_**The coordinates for the image (bottom-left corner, top-right corner). ie.[[lat, long], [lat, long]]**_"

Which one is it?

### Reproducible sample code

```TSX
<Overlay
        bounds={mapStore.overlayBounds}
        image={{ uri: url }}
      />
```

### Steps to reproduce

Docs.

### Expected result

Docs.

### Actual result

Docs.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.6

### What version of Expo are you using?

SDK 48

### Device(s)

Samsung galaxy s10e

**Comment by rakesho-vel** [comment]
@rokamon1997 did you get this working?

**Comment by jan-kozinski** [comment]
still relevant, the example OverlayWithAssets works fine on iOS and crashes on android. Probably the order is swiched between android and ios native implementation. I'll try to make a PR in a few days
![Uploading Screenshot 2023-11-06 at 16.46.31.png…]()

**Comment by rokamon1997** [comment]
This is how I've implemented the bounds for Overlay component:

`[[minLat,minLng], [maxLat,maxLng]]`

`minLat`, `minLng`, `maxLat`, `maxLng` are all of type `number` and should be in the EPSG:4326 format like [[39,13], [47,25]]. This works for me on both IOS and Android with the 1.7.1 version of the library.
