### ISSUE TITLE
Google Maps not showing up with IOS latest version

### ISSUE THREAD

**Issue by vivek091195** [react-native-maps/react-native-maps#4761]
### Summary

We are currently using v0.24.2 in our application, with latest iOS version(16.5) Google Maps isn't showing up/blank. It is showing up fine in older iOS versions. What might be the cause of this issue.

### Reproducible sample code

```TSX
NA
```

### Steps to reproduce

Use react-native-maps version 0.24.2, and iOS version 16.5

### Expected result

Google Maps should show up correctly

### Actual result

Google Maps is not getting displayed

### React Native Maps Version

0.24.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.66.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone13(16.5)

**Comment by stjasink** [comment]
Have you tried using a newer version of React Native Maps?  Version 0.24.2 is 4 years old now!

**Comment by aaort** [comment]
I'm using the latest `1.7.1` version of react-native-maps and facing the same issue.

Code: 
```js
import React from 'react';
import {SafeAreaView, Text} from 'react-native';
import MapView from 'react-native-maps';

function App(): JSX.Element {
  return (
    <SafeAreaView>
      <Text>Hello World</Text>
      <MapView
        style={{flex: 1, height: 400}}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
    </SafeAreaView>
  );
}

export default App;
```
Result: 

<img width="200" alt="Screenshot 2023-06-11 at 12 11 19" src="https://github.com/react-native-maps/react-native-maps/assets/115251394/05130d3d-9da0-42f2-9f89-bc528a35e8b9">

**Comment by aaort** [comment]
Okay, this was my mistake, it worked after I gave `SafeAreaView` component some size.

**Comment by Simon-TechForm** [comment]
Please try using the latest version and open a new issue if the issue persists. As mentioned by @stjasink, `0.24.2` is more than 4 years old and not supported at this point.
