### ISSUE TITLE
There should be `onCameraChange` events or changing the camera should trigger `onRegionChange`

### ISSUE THREAD

**Issue by bfricka** [react-native-maps/react-native-maps#4762]
### Summary

This issue has a few layers.

1. The only way to listen to the movement of the map is via `onRegionChange`. Because of this, if we want to do stuff as the map moves, we need to interact with `Region` objects.
2. `Region` objects are unfriendly, lack some features of `Camera` objects (`heading`, `pitch`, `zoom`, etc.).
3. `animateToCamera` does not trigger `onRegionChange` events. This behavior is explicitly defined. E.g. `AIRMapsManager.m` has: `// don't emit region change events when we are setting the camera`. When setting the camera, it disables region change reporting, and the sets it to the original value when the animation completes. Thus, we must use `animateToRegion` if we want `onRegionChange` to fire events.
4. Converting between a `Region` and a `Camera`, even for the the fields that should overlap, has been impossible for me to do reliably. For example, we _should_ be able to derive the `zoom` or `altitude` from the `Region`, but none of the algorithms I've worked with can do so reliably on both iOS and Android. I have an algorithm that works reliably on iOS, but not on Android. Either way, `react-native-maps` isn't doing any favors here, since it doesn't have utilities to do these conversions. This is expected, since the conversions themselves are done internally by the platform specific maps implementations.

In summary, we're forced to work with `Region` if we want to listen to the map position, but `Region` is missing features, and cannot be converted to `Camera`, even for the fields that should overlap.

The obvious solution would seem to be to add equivalent `onCameraChange` and `onCameraChangeComplete` events to `MapView`, or alternatively, to simply call `onRegionChange` when setting the `Camera`. The latter is less ideal, but at least it allows us to still work the the `Camera`, while responding to `onRegionChange`.

I would like to open a dialog to discuss the feasibility of this. The fact that setting the `Camera` specifically disables reporting on region changes was clearly deliberate, so I'm curious about the rationale.

### Reproducible sample code

```TSX
import { useRef } from 'react'
import { Button, View } from 'react-native'
import type { Camera, LatLng, Region } from 'react-native-maps'
import MapView from 'react-native-maps'

const DEFAULT_CAMERA_ZOOM = 15
const getAltitudeFromGoogleZoom = (zoom: number) => 591_657_550.5 / Math.pow(2, zoom)

const DEFAULT_CAMERA = {
  altitude: getAltitudeFromGoogleZoom(DEFAULT_CAMERA_ZOOM),
  center: {
    latitude: 32.9400337,
    longitude: -117.2416767,
  },
  heading: 0,
  pitch: 0,
  zoom: DEFAULT_CAMERA_ZOOM,
} satisfies Camera

const randCoord = () => {
  const rand = Math.random()
  const randLength = `${rand}`.length - 1
  return Math.min(-1 + rand * (2 + parseFloat(`1e-${randLength}`)), 1)
}

const randLatLngChange = (latLng: LatLng) => {
  const latitude = latLng.latitude + randCoord()
  const longitude = latLng.longitude + randCoord()

  return { latitude, longitude }
}

const Sample = () => {
  const mapView = useRef<MapView>(null)
  const regionRef = useRef<Region | null>(null)

  return (
    <View style={{ height: 400, width: 280 }}>
      <MapView
        ref={mapView}
        initialCamera={DEFAULT_CAMERA}
        onRegionChange={(region) => console.log('Region changed', region)}
        onRegionChangeComplete={(region) => (regionRef.current = region)}
        style={{ flex: 1 }}
      />

      <Button
        title="Random Camera"
        onPress={() => mapView.current?.animateCamera(
          { center: randLatLngChange(regionRef.current || DEFAULT_CAMERA.center) },
          { duration: 200 })}
        />

      <Button
        title="Random Region"
        onPress={() => {
          const region = regionRef.current
          if (!region) return
          mapView.current?.animateToRegion({ ...region, ...randLatLngChange(region) }, 200)
        }}
        />
    </View>
  )
}
```

### Steps to reproduce

I think I explained the issue, and the sample code will reproduce it. Tapping "Random Camera" doesn't cause the logging of `onRegionChange` events, while tapping "Random Region" does.

### Expected result

I should be able to use the `Camera` objects, while maintaining the ability to observe the map.

### Actual result

Can't use `Camera` and observe the map.

### React Native Maps Version

1.3.2, 1.7.1

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps)

### React Native Version

0.67.5

### What version of Expo are you using?

Not using Expo

### Device(s)

Various

**Comment by OMeyer973** [comment]
You can use a ref to access the camera data onRegionChange

(translated to functional component from this answer: https://github.com/react-native-maps/react-native-maps/issues/487)

```jsx
import React, {  useRef } from "react";
import MapView, { PROVIDER_GOOGLE } from "react-native-maps";

export const Map = ({ }) => {

  const mapViewRef = useRef(null);

  return (
    <MapView
      provider={PROVIDER_GOOGLE}
      ref={mapViewRef}
      style={{ width: "100%", height: "100%" }}
      onRegionChange={() => {
        console.log(
          mapViewRef?.current?.getCamera().then((info) => {
            console.log("info", info);
          })
        );
      }}
    />
  );
};
```

**Comment by QuentinGrange** [comment]
@bfricka Did you find something?

I really need to use the camera for navigation purposes.

![Capture d’écran 2024-06-07 à 18 14 33](https://github.com/react-native-maps/react-native-maps/assets/76915170/7c83da60-7941-4c77-8534-0dd1bb92ed54)

However, when I leave the navigation, `onRegionChangeComplete` is not working anymore (only on iOS) since I've used the camera.

When I try to do `mapRef.current.animateCamera(undefined)` to "delete" the camera and go back to the region, nothing is happening.

**Comment by jasperaelvoet** [comment]
Best I've found is something like this but it isn't really stable.

```js
const handleRegionChange = useCallback(
  (_region: any, _details: { isGesture?: boolean }) => {
    if (isGettingCamera.current) return;
    isGettingCamera.current = true;

    mapReference.current?.getCamera().then((camera) => {
      if (camera?.heading !== undefined) {
        mapBearing.value = camera.heading;
      }
      isGettingCamera.current = false;
    });
  },
  [mapReference, mapBearing]
);
```

mapBearing is a reanimated value.
