### ISSUE TITLE
Building with Xcode 14.3.1 causes UI flickering when zooming in and out on maps

### ISSUE THREAD

**Issue by rwcoderman** [react-native-maps/react-native-maps#4765]
### Summary

Hi, 

I am experiencing something rather strange... I hope you can help 👍 

Building with Xcode 14.3 causes UI flickering when zooming in and out on maps.
When building in Xcode 13.4.1 I experience no problems.

I experience lags both when animating and zooming manually.

I have also noticed that Expo SDK48 has this issue while SDK47 is working OK.

As an example I have attached some videos from a fresh react native project demonstrating this on an iPhone SE (3rd generation) - iOS 16.4 device.

**Xcode 14.3.1**

https://github.com/react-native-maps/react-native-maps/assets/48324305/f0eca622-a22b-44dc-8226-c5c9e4be869c

**Xcode 13.4.1**

https://github.com/react-native-maps/react-native-maps/assets/48324305/35f8d22d-dd0f-4720-b8c8-ec179154ecfc

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

Build project in Xcode 14.3 and it starts having flickering when zooming in and out on Denmark - Aarhus as an example.

### Expected result

Expected no flickering.

### Actual result

Flickering when zooming

### React Native Maps Version

1.1.7

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.71.10

### What version of Expo are you using?

Not using Expo

### Device(s)

Simulator and real devices

**Comment by Roc8Trppn** [comment]
Any news on that one? We too experience that since Expo 48...Since we have a custom map style which is dark, the white flickering is super strong...
