### ISSUE TITLE
Map Loads Incredibly Slow

### ISSUE THREAD

**Issue by Jake-Mulhern** [react-native-maps/react-native-maps#4770]
### Summary

We have implemented the map in a react native project and when the screen loads with the map on it it takes a really long time to load.  Is there any way to speed the process up?  We are not using any Overlays and just a current location marker.  It just gets the lat and longitude information and that is all.

### Reproducible sample code

```TSX


  const showLocation = () => {
    return (
      <Marker
        coordinate={{
          latitude: location?.latitude,
          longitude: location?.longitude,
        }}
        style={{ position: 'absolute' }}
        draggable
        onDragEnd={async (e) => {
          const { latitude, longitude } = e.nativeEvent.coordinate;
          setLocation({
            ...location,
            latitude: latitude,
            longitude: longitude,
          });

          getReverseGeocode(longitude, latitude);
        }}
      />
    );
  };



<MapView
    region={{
        latitude: location?.latitude,
        longitude: location?.longitude,
        latitudeDelta: 0.001,
        longitudeDelta: 0.001,
    }}
    loadingEnabled={true}
    style={styles.mapContainer}
    provider={PROVIDER_GOOGLE}
>
    {showLocation()}
</MapView>
```

### Steps to reproduce

Implement MapView on a react-native screen and observe.

### Expected result

Map should appear right away or 1-2 seconds after screen begins rendering.

### Actual result

Map takes up to 20 seconds to load.

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.71.7

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 12 & all android phones

**Comment by mattigrthr** [comment]
I'm also experiencing this when opening the screen with the map for the first time. When closing and re-opening the app it's much faster. Still, ideally this super long loading period doesn't happen as it's usually the first time a user experience the feature.

RN version: `0.71.8`
Expo version: `48.0.6`
RNM version: `1.3.2`

**Comment by akravchukabto** [comment]
I had the same issue when I was using google as provider for IOS at IOS simulator.
When I tried the build on actual device in my case it was IPhone SE2020 it worked fine.

**Comment by StreetGUY32** [comment]
I'm also experiencing same issue, first i thought this was because i didn’t handled the data from the API well, but that is not the issue My Map rendering is too slow when using Google as a Provider its works fine on Apple Maps, I'm facing same issue on IOS and ANDROID,
This is the Version I'm using :  react-native-maps: 1.7.1

**Comment by rahulnikam2002** [comment]
Did anyone found the solution..? I'm still facing the same issue🙃☹️

**Comment by StreetGUY32** [comment]
@rahulnikam2002, I was facing the issues with marker and map being slow, i used two props in the maker and its working for me and i used a timeout in map **its not recommended** but it worked for and its one way to get things done, I'll share with you.

For Map:

```<MapView
  onMapReady={() => {
  setTimeout(() => {
            setMapReady(true);      // initially this state is false
          }, 1000);
      }} 
```     
 And for the Marker:
 
 ```
 tracksInfoWindowChanges={Platform.OS === 'ios' ? true : false}
tracksViewChanges={Platform.OS === 'ios' ? true : false}
```

**Comment by rahulnikam2002** [comment]
> @rahulnikam2002, I was facing the issues with marker and map being slow, i used two props in the maker and its working for me and i used a timeout in map **its not recommended** but it worked for and its one way to get things done, I'll share with you.
> 
> For Map:
> 
> ```
>   onMapReady={() => {
>   setTimeout(() => {
>             setMapReady(true);      // initially this state is false
>           }, 1000);
>       }} 
> ```
> 
> And for the Marker:
> 
> ```
> tracksInfoWindowChanges={Platform.OS === 'ios' ? true : false}
> tracksViewChanges={Platform.OS === 'ios' ? true : false}
> ```

Thanks for this, will try this!! <3

**Comment by 1eokim** [comment]
Having this exact same issue. Initial map loading takes 6-10 seconds for me, which significantly impacts the user experience.
