### ISSUE TITLE
Overlays are not destroyed

### ISSUE THREAD

**Issue by ParagonVirtuoso** [react-native-maps/react-native-maps#4771]
### Summary

Can you tell me if this problem has been fixed? I have a case here that is happening this same problem!
<img width="1135" alt="Captura de Tela 2023-06-21 às 18 16 41" src="https://github.com/react-native-maps/react-native-maps/assets/38758938/44762045-ae91-4c05-b99a-7f004739bf6d">
I made the correct flow to remove the Overlay while updating and making the key settings and even put a delay for it to render the Overlay again, even so it does not destroy the previous one!

linked with : [issue](https://github.com/react-native-maps/react-native-maps/issues/3598)

### Reproducible sample code

```TSX
import React, {Component} from 'react';
import MapView, {Overlay} from 'react-native-maps';
import estilo from './estilo';

class MapContent extends Component {
  mapRefAnalise: any;
  constructor(props) {
    super(props);
    this.mapRefAnalise = null;
    this.state = {
      verOverlay: false,
      bboxCoordinates: null,
      unConvertedBboxCoordinates: {
        northEast: {
          latitude: -10.119143030159039,
          longitude: -48.316573796522434,
        },
        southWest: {
          latitude: -10.20200607727844,
          longitude: -48.37111113871625,
        },
      },
      bond: {
        northEast: {
          latitude: -10.116100033299208,
          longitude: -48.316879031209744,
        },
        southWest: {
          latitude: -10.201336111531191,
          longitude: -48.37297771457272,
        },
      },
    };
  }

  render() {
    return (
      <MapView
        style={estilo.mapView}
        zoomEnabled={true}
        scrollEnabled={true}
        showsTraffic={true}
        ref={ref => {
          this.handleMapRef(ref);
        }}
        region={this.props.region}
        showsIndoors={true}
        showsIndoorLevelPicker={true}
        mapPadding={{
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }}
        onRegionChangeComplete={async region => {
          this.setState({verOverlay: false});
          !this.props.analise &&
            this.props.onRegionChange &&
            this.props.onRegionChange(region);
          await new Promise(resolve => setTimeout(resolve, 150));
          await this.calcBBOX();
        }}
        mapType={'hybrid'}>
        {this.state.verOverlay && (
          <Overlay
            image={{
              uri: `myurl`,
            }}
            bounds={[
              [
                this.state.unConvertedBboxCoordinates.southWest.latitude,
                this.state.unConvertedBboxCoordinates.southWest.longitude,
              ],
              [
                this.state.unConvertedBboxCoordinates.northEast.latitude,
                this.state.unConvertedBboxCoordinates.northEast.longitude,
              ],
            ]}
          />
        )}
      </MapView>
    );
  }
}
export default MapContent;
```

### Steps to reproduce

Have a map and inside an array (what will come from the state) that will be filled with overlays
I create the overlay in a different component, for test if is unmounted.
Add many overlays to the array, for example 15 per second, and clean, add, clean, add, clean

### Expected result

I hope that when moving the map it removes the old overlay and leaves only the new one, but what happens is that it always generates a new one!

### Actual result

generates a new overlay every time I move the map and getting several layers on the map!

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.71.8

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13

**Comment by ParagonVirtuoso** [comment]
Still relevant

**Comment by ParagonVirtuoso** [comment]
Still relevant

**Comment by ParagonVirtuoso** [comment]
Still relevant

**Comment by JohanssonJonathan** [comment]
I have the exact same problem. 

@ParagonVirtuoso is it still relevant for you?

**Comment by ParagonVirtuoso** [comment]
in my case I used another component and another methodology to solve!
