### ISSUE TITLE
MapVIew/Marker/Callout onPress delay

### ISSUE THREAD

**Issue by mikescott** [react-native-maps/react-native-maps#4776]
### Summary

Reopening this as issues #833 #3429 and #3897 have been closed but the problem still exists

### Reproducible sample code

```TSX
<Callout onPress={() => console.log('press')} />
```

### Steps to reproduce

Using Google as the provider

Press the callout

### Expected result

Instant response

### Actual result

Delay of around 500 ms

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.71.8

### What version of Expo are you using?

SDK 48

### Device(s)

All devices

### Additional information

This does not affect Apple Maps on iOS. A previous proposed solution of wrapping the MapView in Pressable does not have any effect.

**Comment by MikeKovarik** [comment]
Still relevant

**Comment by salah-ghanim** [comment]
@mikescott @mikescott there is a pull request to solve this issue, but the solution is not optimal, I'm waiting on a better pull request to solve this.

**Comment by mikescott** [comment]
Still relevant

**Comment by jordiup** [comment]
Still relevant

**Comment by ABertaud** [comment]
Still relevant

**Comment by ABertaud** [comment]
Still relevant

**Comment by kris-devjet** [comment]
Still relevant

**Comment by WeidsonWikaro** [comment]
Still relevant

**Comment by Alssdev** [comment]
Still relevant

**Comment by cubevis** [comment]
Still exists

**Comment by gustavohariel** [comment]
Still relevant

**Comment by JoachimAmoah** [comment]
still relevant
