### ISSUE TITLE
Allow to add custom headers with urlTemplate property

### ISSUE THREAD

**Issue by devWaleed** [react-native-maps/react-native-maps#4777]
### Summary

This is more like a change/feature request.

We have a custom tile server which takes z/x/y values in query params and returns the map tile for it. The issue we are facing with this library is that our server has a JWT based authentication system implemented. So all the tiles request placed by this library are resulting in 401 error.

I am not able to find anyway to add custom headers to the API requests. I want to add the authorization header with bearer token value so it can work.

### Reproducible sample code

```TSX
N/A
```

### Steps to reproduce

N/A

### Expected result

N/A

### Actual result

N/A

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.65

### What version of Expo are you using?

Not using Expo

### Device(s)

N/A

### Additional information

N/A

**Comment by AlixH** [comment]
Up

**Comment by Michota** [comment]
up
