### ISSUE TITLE
MarkerAnimated prop coordinate has wrong TypeScript type

### ISSUE THREAD

**Issue by karatekid430** [react-native-maps/react-native-maps#4778]
### Summary

The README.md for v1.7.1 says that MarkerAnimated will also take an AnimatedRegion in the coordinate prop. And it does. But its type only shows LatLng, meaning that passing AnimatedRegion is flagged as an error when it should not be.

### Reproducible sample code

```TSX
const coord = new AnimatedRegion();

<MarkerAnimated
  coordinate={coord} // ts should not show an error here
/>
```

### Steps to reproduce

Install, pass AnimatedRegion to coordinate prop of MarkerAnimated with TypeScript

### Expected result

It should say that passing an AnimatedRegion to coordinate prop of MarkerAnimated is not an error

### Actual result

It says that passing an AnimatedRegion to coordinate prop of MarkerAnimated is an error

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.70.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Simulator

**Comment by mcoppola** [comment]
➕

**Comment by ackermanGitHub** [comment]
anyone solved how to animate a marker smoothly on the latests versions of expo and react-native?
