### ISSUE TITLE
Markers not rendering in, invisible

### ISSUE THREAD

**Issue by emanuelboros** [react-native-maps/react-native-maps#4780]
### Summary

We have close to 300 of markers to render after a query.

The markers are custom component.

We’ve had an issue that when a marker is pressed our marker component was connected to redux and they rerendered at every onPress. This caused another issue, not all markers would render in an there would be a flash of markers dissapearing and appearing

Now that issue is fixed from out side. But on 1st render not all markers are visible

I will try to provide a repro demo.

At the moment I’m curios if anyone else is experiencing this issue 

### Reproducible sample code

```TSX
-
```

### Steps to reproduce

-

### Expected result

All markers be rendered in

### Actual result

Markers are invisible

### React Native Maps Version

1.5.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.7

### What version of Expo are you using?

Not using Expo

### Device(s)

All devices

**Comment by 0xcD3v** [comment]
Do you have tracksViewChanges prop set to false?

**Comment by emanuelboros** [comment]
@0xcD3v I have it on true. 

I now have a functional demo, Tried both cases
<img width="565" alt="Screenshot 2023-07-04 at 10 14 37 AM" src="https://github.com/react-native-maps/react-native-maps/assets/47521797/58635d2c-a64e-46d7-b02b-6be8c14d8160">

I render 400 custom pins and they should be in a line one after another. But as you can see it's like a barrcode. While original google maps pins render correctly

**Comment by 0xcD3v** [comment]
> @0xcD3v I have it on true.
> 
> I now have a functional demo, Tried both cases
> 
> I render 400 custom pins and they should be in a line one after another. But as you can see it's like a barrcode. While original google maps pins render correctly
> <img alt="Screenshot 2023-07-04 at 10 13 47 AM" width="565" src="https://user-images.githubusercontent.com/47521797/258024979-09d98d9c-3985-409e-b66b-21be3fe0affe.png"> <img alt="Screenshot 2023-07-04 at 10 14 37 AM" width="565" src="https://user-images.githubusercontent.com/47521797/258024475-58635d2c-a64e-46d7-b02b-6be8c14d8160.png">

you should try use clustering, try this one [react-native-map-clustering](https://github.com/venits/react-native-map-clustering) very easy to use.

**Comment by emanuelboros** [comment]
Unfortunately our business model does not allow clustering.
