### ISSUE TITLE
react-native-google-maps requires higher minimum sdk than react-native's min_ios_version_supported

### ISSUE THREAD

**Issue by mgithubmessier** [react-native-maps/react-native-maps#4784]
### Summary

When doing an install of react-native-maps from react-native 0.71.10,  react-native-maps versions ^1.0.0 have the podspec `react-native-google-maps` which requires ios platfrom >= 13. While react-native's default min platform version is 12.4.

Is there a suggested workaround for when the pod install fails for this? Because the README currently indicates that react-native-maps is compatible with react-native versions >=0.64.3. 

If overriding the minimum platform version is the solution (which I believe would expose all of our projects to larger issues anyway), that should be documented, else if it is not the proper solution, the minimum compatible react-native version should likely be incremented to >=0.72

### Reproducible sample code

```TSX
// package.json

{
  "dependencies": {
    "react-native": "0.71.10",
    "react-native-maps": "^1.0.0"
  }
}
```
// Podfile
```
# React Native Maps dependencies
# The following line is only needed if building on an Apple silicon Mac without rosetta.
pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
```
```


### Steps to reproduce

`yarn`
`pod install`

### Expected result

successful install

### Actual result

# Pod Install Error:
Specs satisfying the `react-native-google-maps (from `../node_modules/react-native-maps`)` dependency were found, but they required a higher minimum deployment target.

### React Native Maps Version

^1.0.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.10

### What version of Expo are you using?

Not using Expo

### Device(s)

simulator

### Additional information

_No response_

**Comment by kruyvanna** [comment]
I'm having the same issue

**Comment by Bualaphanh** [comment]
I have the same problem, how do you solve the problem?

Here my **react-native info**

> System:
  OS: macOS 13.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 35.04 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/opt/node@18/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
    System Images:
      - android-28 | Google Play Intel x86 Atom
      - android-29 | Intel x86 Atom_64
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom_64
      - android-30 | Google Play Intel x86 Atom
      - android-31 | Google Play Intel x86 Atom_64
      - android-32 | Google Play Intel x86 Atom_64
      - android-33-ext4 | Google Play Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
  
If anyone knows how to fix this problem please let me know, Thank you

**Comment by mgithubmessier** [comment]
@Bualaphanh for the time being, I've reduced my version down to `^0.31.1` which works, but is still frustrating, would love to leverage newer features.

**Comment by QRCharlie** [comment]
Same here
"react-native": "0.72.3"
"react-native-maps": "^1.7.1"
gives
Specs satisfying the `react-native-google-maps (from `../node_modules/react-native-maps`)` dependency were found, but they required a higher minimum deployment target.

As suggested by [mgithubmessier](https://github.com/mgithubmessier) downgrading to "react-native-maps": "0.31.1" works.

**Comment by umarnsisar021** [comment]
Please follow the steps
https://youtu.be/VOCRBdzHEqM

**Comment by andrei0807** [comment]
You can change min ios version on Podfile.
```
# platform :ios, min_ios_version_supported
platform :ios, '13.0'
```

**Comment by mgithubmessier** [comment]
> You can change min ios version on Podfile.
> 
> ```
> # platform :ios, min_ios_version_supported
> platform :ios, '13.0'
> ```

If this is the solution to this problem, then this should be added to the documentation -- I can open up a PR for that if that's the preferred solution here.

**Comment by ipoogleduck** [comment]
> You can change min ios version on Podfile.
> 
> ```
> # platform :ios, min_ios_version_supported
> platform :ios, '13.0'
> ```

This still doesn't seem to work for me. Just upgraded to React Native v0.72.5 from v0.70.7 and changed all the deployment targets to iOS 13. I still get the same error

**Comment by SafiDS** [comment]
> You can change min ios version on Podfile.
> 
> ```
> # platform :ios, min_ios_version_supported
> platform :ios, '13.0'
> ```

Its Working for me

**Comment by vnanhtuan** [comment]
> You can change min ios version on Podfile.
> 
> ```
> # platform :ios, min_ios_version_supported
> platform :ios, '13.0'
> ```

Also make sure that your Podfile deployment target is set to >= 13.0 at the top of your Podfile

**Comment by Fari056** [comment]
**for Googlemaps (7.4.0)** (ios)
# platform :ios, min_ios_version_supported
platform :ios, '13.4'
and also change the version in
 "node_modules/react-native-maps/react-native-maps.podspec" to   
 s.platform     = :ios, "13.4"

**Comment by outaTiME** [comment]
Hi there, this started to happen again in version `1.9.1` where the iOS platform requirement is changed to `13.4`:

https://github.com/react-native-maps/react-native-maps/blob/608ef5492c8d450f4c75c22e5c9837aab051e0d9/react-native-google-maps.podspec#L12

in my case that I am using expo, I had to make the following tweak inside the plugins:

```
plugins: [
  [
    'expo-build-properties',
    {
      ios: {
        deploymentTarget: '13.4',
      },
    },
  ],
]
```

hope it is useful 🙏

**Comment by taongocson** [comment]
`# platform :ios, min_ios_version_supported
platform :ios, '13.4'`
add: line into Podfile
`pod 'react-native-maps', :path => '../node_modules/react-native-maps' 
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'`
npm install
cd ios pod install

**Comment by neilanthonyte** [comment]
I downgraded the version to 1.4.0 and now it is working

**Comment by tanimak** [comment]
Check the minimum iOS version specified in the .podspec file of the react-native-maps lib. You can find the file in `node_modules/react-native-maps/react-native-google-maps.podspec`. I had to add the in my case for react-native-maps version 1.11.3 I had `s.platform     = :ios, "13.4"` inside the above file. I changed the `platform :ios` value on top of podfile to 13.4 and the everything started to work.

**Comment by shubhext** [comment]
This work for me
 "react-native-maps": "1.7.1",
  "react-native": "0.72.3",
