### ISSUE TITLE
How to Set always trigger event of a marker instead of another when near together?

### ISSUE THREAD

**Issue by caolong24** [react-native-maps/react-native-maps#4785]
### Summary

I have 2 marker has coordinate at same point(or has coordinate near together).

When i press on a point that there are 2 marker override other, at first time event of marker A was triggered, but the seconds marker B will be triggered.
How to set always trigger marker A  when it has same(or nearly) location others?
I tried set zIndex of markerA > zIndex of markerB but it only help marker A trigger first 

### Reproducible sample code

```TSX
this is a question not bug
```

### Steps to reproduce

Setup 2 marker has same coordinate called that A and B
Set MarkerA zIndex = 1
Set MarkerB zIndex = 2

### Expected result

always trigger event when press on position that has 2 marker

### Actual result

the first press: event Marker A is triggered 
the second press: event marker B is triggered 
the third press: event marker A is triggered 
the fourth press: event marker B is triggered 
.....

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

android

**Comment by umarnsisar021** [comment]
Please follow the steps
https://youtu.be/VOCRBdzHEqM
