### ISSUE TITLE
`subThoroughfare` is missing on Address type

### ISSUE THREAD

**Issue by huextrat** [react-native-maps/react-native-maps#4786]
### Summary

The following type does not offer subThoroughfare, even though this is returned on Android and iOS.

```ts
export type Address = {
  administrativeArea: string;
  country: string;
  countryCode: string;
  locality: string;
  name: string;
  postalCode: string;
  subAdministrativeArea: string;
  subLocality: string;
  thoroughfare: string;
};
```

### Reproducible sample code

```TSX
Not needed
```

### Steps to reproduce

Not needed

### Expected result

We should have the following type:

```ts
export type Address = {
  administrativeArea: string;
  country: string;
  countryCode: string;
  locality: string;
  name: string;
  postalCode: string;
  subAdministrativeArea: string;
  subLocality: string;
  thoroughfare: string;
  subThoroughfare: string;
};
```

### Actual result

Currently `subThoroughfare` is missing:

```ts
export type Address = {
  administrativeArea: string;
  country: string;
  countryCode: string;
  locality: string;
  name: string;
  postalCode: string;
  subAdministrativeArea: string;
  subLocality: string;
  thoroughfare: string;
};
```

### React Native Maps Version

All

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.72.1

### What version of Expo are you using?

Not using Expo

### Device(s)

All

**Comment by salah-ghanim** [comment]
@huextrat see: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_address
and https://developer.apple.com/documentation/corelocation/clplacemark

for me it's clear that this is:
1. available only for iOS MapKit and not google maps and not android.
2. optional for iOS to begin with.

I think such optional / platform specific properties should:
1. be optional (?) type.
2. ideally verbously specified as platform specific, for example mkSubThoroughfare

**Comment by huextrat** [comment]
Hi @salah-ghanim !

Android is using [Geocoder class](https://developer.android.com/reference/android/location/Geocoder) which is based on `android.location` and it contains a `subThoroughfare`. 

https://github.com/react-native-maps/react-native-maps/blob/673e9d21212442af9795cc21a17bf477623c458b/android/src/main/java/com/rnmaps/maps/MapModule.java#L190-L242

I've just tested it and can confirm that we do indeed have `subThoroughfare` on Android.

About your second point, this type is already platform specific as it's only used for `addressForCoordinate` method and that method is working only with Apple Plans on iOS and of course only with GMaps on Android. If you are trying to call `addressForCoordinate` method on iOS with GMaps the methods is not working.

**Comment by salah-ghanim** [comment]
Hi @huextrat thanks a lot for taking the time to explain your change, yes I see that subThoroughfare is there for Android, I was looking at a different API not the geocoder. now I see the native code for both android and iOS.

but still please make the type optional and update the pull request or create a new one, since both android and iOS clearly in their documentation mention that the value could be empty / null.

**Comment by huextrat** [comment]
Hi @salah-ghanim,

I have just updated the PR https://github.com/react-native-maps/react-native-maps/pull/4787

**Comment by huextrat** [comment]
Still relevant
