### ISSUE TITLE
IOS Build Error: `unsupported Swift architecture` and `could not build module 'GoogleMapsUtils'`

### ISSUE THREAD

**Issue by SohelIslamImran** [react-native-maps/react-native-maps#4793]
### Summary

When building the App with `"react-native": "0.72.3"`, ` "expo": "^49.0.3",` and `"react-native-maps": "1.7.1",`, the IOS build getting fail with the following errors:

```sh
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmapManager.m


❌  (/Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:310:2)

  308 | 
  309 | #else
> 310 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  311 | #endif
  312 | 


❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 | 
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 | 
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 | 

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmap.m


❌  (/Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:310:2)

  308 | 
  309 | #else
> 310 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  311 | #endif
  312 | 

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapCircleManager.m

    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'TilleliDev' from project 'TilleliDev')

    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'TilleliDev' from project 'TilleliDev')

    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'TilleliDev' from project 'TilleliDev')

    Run script build phase '[CP-User] [RNFB] Crashlytics Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'TilleliDev' from project 'TilleliDev')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

▸ (1 failure)

2023-07-12 14:32:18.575 xcodebuild[5352:16454] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

** BUILD FAILED **



The following build commands failed:

	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

(1 failure)

Exit status: 65


+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.213.0                 |

| sdk         | iPhoneOS16.4.sdk        |

+-------------+-------------------------+
```

### Reproducible sample code

```TSX
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

Build the app

### Expected result

Successful build

### Actual result

Fail IOS build 

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

SDK 49

### Device(s)

null

**Comment by LucasLFurini** [comment]
If you're using a M1, try on your xCode, go to Product -> Destination -> Destination Architectures -> Show Rosetta Destinations
And then select the Simulator (Rosetta)
Then it should work

**Comment by SohelIslamImran** [comment]
@LucasLFurini Can you please provide details with screenshots? Nothing happening "Show Rosetta Destinations". And how can I select the "Simulator (Rosetta)"?

<img width="625" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/76745339/f0bf2d55-4336-4c94-bbba-6c41627a13c3">

**Comment by LucasLFurini** [comment]
To select the version with Rosetta you need to click here: 
![image](https://github.com/react-native-maps/react-native-maps/assets/110385497/2ed1b7f0-307d-4137-bdd4-4562bbdee7aa)
There will be Iphone 14 Pro (Rosetta)

**Comment by rlisperguier** [comment]
Same problem here.

I'm getting this error when I try to build a dev-client with this command:

`npx eas build --profile development-simulator --platform ios`

The development-simulator profile inside `eas.json`:

```javascript
{
  "cli": {
    "version": ">= 0.34.0"
  },
  "build": {
    "development-simulator": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
    "debug": {
      "android": {
        "buildType": "apk",
        "image": "latest"
      }
    },
    "production": {}
  }
}
``` 

Package versions:
```javascript
"react-native-maps": "1.7.1"
"expo": "^49.0.0"
"react-native": "0.72.3"
```

**Comment by Zuxelus** [comment]
Have the same without expo. "react-native-maps": "1.7.1"

```
While building module 'GoogleMapsUtils' imported from /Users/.../Documents/Projects/.../node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:
In file included from <module-includes>:2:
/Users/.../Library/Developer/Xcode/DerivedData/...-gakpmozuyejlgzbcqlqnauqzhrwl/Build/Products/Release-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:310:2: error: unsupported Swift architecture
#error unsupported Swift architecture
 ^
1 error generated.
In file included from /Users/.../Documents/Projects/.../node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m:8:
/Users/.../Documents/Projects/.../node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9: fatal error: could not build module 'GoogleMapsUtils'
#import "GMUHeatmapTileLayer.h"
 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by SohelIslamImran** [comment]
Try this plugin, It may resolve.

```js
// react-native-maps-plugin.js
const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");
const generateCode = require("@expo/config-plugins/build/utils/generateCode");

// https://github.com/react-native-maps/react-native-maps/issues/4793
const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;

/** @type { import('expo/config-plugins').ConfigPlugin } */
const withPlugin = (expoConfig) => {
  return withDangerousMod(expoConfig, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      const contents = fs.readFileSync(filePath, "utf-8");

      const addCode = generateCode.mergeContents({
        newSrc: googleMapsIosSiliconWorkaroundPodCode,
        tag: "withGoogleMapsIOSWorkaroundPlugin",
        anchor: /\s*get_default_flags\(\)/i,
        src: contents,
        comment: "#",
        offset: 2,
      });

      if (!addCode.didMerge) {
        console.warn(
          "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
        );
        return config;
      }

      fs.writeFileSync(filePath, addCode.contents);

      return config;
    },
  ]);
};

module.exports = withPlugin;
```

```json
// app.json
"plugins": [
      "./react-native-maps-plugin",
    ],
```

**Comment by rlisperguier** [comment]
> Try this plugin, It may resolve.
> 
> ```js
> // react-native-maps-plugin.js
> const fs = require("fs");
> const path = require("path");
> const { withDangerousMod } = require("expo/config-plugins");
> const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> 
> // https://github.com/react-native-maps/react-native-maps/issues/4793#issuecomment-1671269814
> const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;
> 
> /** @type { import('expo/config-plugins').ConfigPlugin } */
> const withPlugin = (expoConfig) => {
>   return withDangerousMod(expoConfig, [
>     "ios",
>     async (config) => {
>       const filePath = path.join(
>         config.modRequest.platformProjectRoot,
>         "Podfile"
>       );
> 
>       const contents = fs.readFileSync(filePath, "utf-8");
> 
>       const addCode = generateCode.mergeContents({
>         newSrc: googleMapsIosSiliconWorkaroundPodCode,
>         tag: "withGoogleMapsIOSWorkaroundPlugin",
>         anchor: /\s*get_default_flags\(\)/i,
>         src: contents,
>         comment: "#",
>         offset: 2,
>       });
> 
>       if (!addCode.didMerge) {
>         console.warn(
>           "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
>         );
>         return config;
>       }
> 
>       fs.writeFileSync(filePath, addCode.contents);
> 
>       return config;
>     },
>   ]);
> };
> 
> module.exports = withPlugin;
> ```
> 
> ```json
> // app.json
> "plugins": [
>       "./react-native-maps-plugin",
>     ],
> ```
> 
> As mentioned here : [#4757 (comment)](https://github.com/react-native-maps/react-native-maps/pull/4757#issuecomment-1604959747) https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps

This works for me!, thanks @SohelIslamImran

**Comment by wodin** [comment]
> Looking into figuring out how to get the logs from xcode now.

@ml242, there should be a link at the bottom of the build page to access the Xcode logs

**Comment by cmcWebCode40** [comment]
> Try this plugin, It may resolve.
> 
> ```js
> // react-native-maps-plugin.js
> const fs = require("fs");
> const path = require("path");
> const { withDangerousMod } = require("expo/config-plugins");
> const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> 
> // https://github.com/react-native-maps/react-native-maps/issues/4793#issuecomment-1671269814
> const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;
> 
> /** @type { import('expo/config-plugins').ConfigPlugin } */
> const withPlugin = (expoConfig) => {
>   return withDangerousMod(expoConfig, [
>     "ios",
>     async (config) => {
>       const filePath = path.join(
>         config.modRequest.platformProjectRoot,
>         "Podfile"
>       );
> 
>       const contents = fs.readFileSync(filePath, "utf-8");
> 
>       const addCode = generateCode.mergeContents({
>         newSrc: googleMapsIosSiliconWorkaroundPodCode,
>         tag: "withGoogleMapsIOSWorkaroundPlugin",
>         anchor: /\s*get_default_flags\(\)/i,
>         src: contents,
>         comment: "#",
>         offset: 2,
>       });
> 
>       if (!addCode.didMerge) {
>         console.warn(
>           "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
>         );
>         return config;
>       }
> 
>       fs.writeFileSync(filePath, addCode.contents);
> 
>       return config;
>     },
>   ]);
> };
> 
> module.exports = withPlugin;
> ```
> 
> ```json
> // app.json
> "plugins": [
>       "./react-native-maps-plugin",
>     ],
> ```
> 
> As mentioned here : [#4757 (comment)](https://github.com/react-native-maps/react-native-maps/pull/4757#issuecomment-1604959747) https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps

This worked for me too thanks @SohelIslamImran

**Comment by enisze** [comment]
I got these errors: 
❌  (/var/folders/d4/vs95y56x7_ddxqkybw1l9l1w0000gn/T/eas-build-local-nodejs/da587945-8535-4b09-9506-3dcc1a523dae/build/apps/proprate-mobile/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:327:2)

  325 |
  326 | #else
> 327 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  328 | #endif
  329 |

[RUN_FASTLANE]
❌  (../../../../../../../../../../private/var/folders/d4/vs95y56x7_ddxqkybw1l9l1w0000gn/T/eas-build-local-nodejs/da587945-8535-4b09-9506-3dcc1a523dae/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 |
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 |
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 |
  
  Any idea? 

This is now the .js file I am using and get the following erorr
```
// ./react-native-maps-ios-fix.js
const plugins = require('@expo/config-plugins')
const {
  mergeContents,
} = require('@expo/config-plugins/build/utils/generateCode')
const fs = require('fs')
const path = require('path')

module.exports = function withFlipper(config) {
  return plugins.withDangerousMod(config, [
    'ios',
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile',
      )
      const contents = fs.readFileSync(filePath, 'utf-8')

      const enableFix = mergeContents({
        tag: 'react-native-maps ios fix',
        src: contents,
        newSrc: `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon`,
        anchor: /use_native_modules!/, //we find this line
        offset: -1, //we add it on the line before
        comment: '#',
      })

      if (!enableFix.didMerge) {
        console.log('ERROR: Cannot add react-native-maps-ios-fix to Podfile.')
        return config
      }

      fs.writeFileSync(filePath, enableFix.contents)

      return config
    },
  ])
}
```

Now I get this:

<img width="899" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/15271433/c079fea1-51f7-4998-af86-9f9dd49a3e2f">

**Comment by kubilaytural** [comment]
> ```
> pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
> ```

Thank you so much! Quick solution 🚀

**Comment by ball-hayden** [comment]
Forcing a new version of `Google-Maps-iOS-Utils` worked for me:

```
// app.json
{
  plugins: [
    [
      'expo-build-properties',
      {
        ios: {
          extraPods: [{ name: 'Google-Maps-iOS-Utils', version: '>=4.2.0' }],
        },
      },
    ],
  ],
}
```

**Comment by chanphiromsok** [comment]
### One of my Team tell me to do this for an M1 user and it works and config plugin for me also works
![Screenshot 2024-01-05 at 1 55 23 in the afternoon](https://github.com/react-native-maps/react-native-maps/assets/65760336/4fc4fb44-9fd4-46e7-9084-816963a2eaab)


> Try this plugin, It may resolve.
> 
> ```js
> // react-native-maps-plugin.js
> const fs = require("fs");
> const path = require("path");
> const { withDangerousMod } = require("expo/config-plugins");
> const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> 
> // https://github.com/react-native-maps/react-native-maps/issues/4793#issuecomment-1671269814
> const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;
> 
> /** @type { import('expo/config-plugins').ConfigPlugin } */
> const withPlugin = (expoConfig) => {
>   return withDangerousMod(expoConfig, [
>     "ios",
>     async (config) => {
>       const filePath = path.join(
>         config.modRequest.platformProjectRoot,
>         "Podfile"
>       );
> 
>       const contents = fs.readFileSync(filePath, "utf-8");
> 
>       const addCode = generateCode.mergeContents({
>         newSrc: googleMapsIosSiliconWorkaroundPodCode,
>         tag: "withGoogleMapsIOSWorkaroundPlugin",
>         anchor: /\s*get_default_flags\(\)/i,
>         src: contents,
>         comment: "#",
>         offset: 2,
>       });
> 
>       if (!addCode.didMerge) {
>         console.warn(
>           "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
>         );
>         return config;
>       }
> 
>       fs.writeFileSync(filePath, addCode.contents);
> 
>       return config;
>     },
>   ]);
> };
> 
> module.exports = withPlugin;
> ```
> 
> ```json
> // app.json
> "plugins": [
>       "./react-native-maps-plugin",
>     ],
> ```
> 
> As mentioned here : [#4757 (comment)](https://github.com/react-native-maps/react-native-maps/pull/4757#issuecomment-1604959747) https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps

**Comment by VadymBezsmertnyi** [comment]
@chanphiromsok 

It works great) Thank you and your colleague.

**Comment by kaladivo** [comment]
For folks who use expo sdk 50, it works without any expo plugin - you just need to use these versions: 

```
 "react-native-maps": "1.10.0"
 "expo": "^50.0.0"
```

**Comment by nemvik** [comment]
> For folks who use expo sdk 50, it works without any expo plugin - you just need to use these versions:
> 
> ```
>  "react-native-maps": "1.10.0"
>  "expo": "^50.0.0"
> ```

i can confirm!
expo will update doctor to recommend 1.10.0 for SDK 50

**Comment by nephykoda** [comment]
**Updated Workaround** Adding on to @chanphiromsok's reply 

Was stuck on this for a few hours until I found this thread. This workaround is not specific to `react-native-maps` though. It should ideally be in the `expo`'s repo.

💻 **Machine**: MacBook Pro M1 
🙅 **XCode Version**: 15.3 (since there is a slight difference in XCode UI)
🫛 **Pod Version**: `1.15.2`
📦 **Package Versions**:
```
"expo": "~50.0.14",
"react-native": "0.73.6"
```
---
**Steps**

1. From your project's directory terminal, open up the `ios` folder's xcworkspace in XCode by running the following, replacing `<your_app_name>` to whatever is populate in your `ios folder`. This step will open up XCode at the correct project directory.
```
open ios/<your_app_name>.xcworkspace
```

2. Get all the possible destinations to build to by following this from Menu Bar: `Product` > `Destination` > `Show All Run Destinations`
![1-show-run-destinations](https://github.com/react-native-maps/react-native-maps/assets/93145265/4be03245-1039-4c8d-9691-3d254e5162a0)

3. Now, you should be able to see the iOS Simulators with (Rosetta) support. Select the simulator with Rosetta for your project.
![2-select-rosetta-support](https://github.com/react-native-maps/react-native-maps/assets/93145265/4bfc08cc-dd43-4f48-8795-fb8d0544ef29)

4. Ensure the top of XCode shows that you are building your app for that specific simulator with (Rosetta), then click on the ▶️ button to build.
![3-build](https://github.com/react-native-maps/react-native-maps/assets/93145265/d49ba646-ba06-4f55-97ab-c548aa206924)

5. In your project, run `npm start` from the project root (not `ios` folder) to check your Metro bundler is running of course.

---

Hope this helps! 🍻

**Comment by VadymBezsmertnyi** [comment]
It helped me:

npx react-native-clean-project

npx expo-doctor

npx expo install --fix

npx expo prebuild --clean
Opened Xcode and waited until everything checked out and the first time without warnings.

ran the command from package.json: "ios": "expo run:ios",

**Comment by chanphiromsok** [comment]
> **Updated Workaround** Adding on to @chanphiromsok's reply
> 
> Was stuck on this for a few hours until I found this thread. This workaround is not specific to `react-native-maps` though. It should ideally be in the `expo`'s repo.
> 
> 💻 **Machine**: MacBook Pro M1 🙅 **XCode Version**: 15.3 (since there is a slight difference in XCode UI) 🫛 **Pod Version**: `1.15.2` 📦 **Package Versions**:
> 
> ```
> "expo": "~50.0.14",
> "react-native": "0.73.6"
> ```
> 
> **Steps**
> 
> 1. From your project's directory terminal, open up the `ios` folder's xcworkspace in XCode by running the following, replacing `<your_app_name>` to whatever is populate in your `ios folder`. This step will open up XCode at the correct project directory.
> 
> ```
> open ios/<your_app_name>.xcworkspace
> ```
> 
> 2. Get all the possible destinations to build to by following this from Menu Bar: `Product` > `Destination` > `Show All Run Destinations`
>    ![1-show-run-destinations](https://private-user-images.githubusercontent.com/93145265/320271895-4be03245-1039-4c8d-9691-3d254e5162a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTA3NzUsIm5iZiI6MTcxMjg5MDQ3NSwicGF0aCI6Ii85MzE0NTI2NS8zMjAyNzE4OTUtNGJlMDMyNDUtMTAzOS00YzhkLTk2OTEtM2QyNTRlNTE2MmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjYwM2EyMmJiZDAwOTc1NGI5MjEzZWEyYzNmNGRlMmIzOGY3NjQxMjM1ODI3MGIwMDk5MWM4MGM0N2FmOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bg71usbqHIpmltciN_aCt21NE3nOYYjDNNy-owvxZhE)
> 3. Now, you should be able to see the iOS Simulators with (Rosetta) support. Select the simulator with Rosetta for your project.
>    ![2-select-rosetta-support](https://private-user-images.githubusercontent.com/93145265/320272001-4bfc08cc-dd43-4f48-8795-fb8d0544ef29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTA3NzUsIm5iZiI6MTcxMjg5MDQ3NSwicGF0aCI6Ii85MzE0NTI2NS8zMjAyNzIwMDEtNGJmYzA4Y2MtZGQ0My00ZjQ4LTg3OTUtZmI4ZDA1NDRlZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMjc2ODhhYjBkMTYxOGYzNjNmZWY5MjU2ZmM3MTQzMTJjMDM2NmJjZjY0YWUyYmExOGIxMWI5NmQ3ZTkyNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EIIR_L8NrZxYoOcGXKFr-UxeS-U2Ihh9EGazU0Kdtxs)
> 4. Ensure the top of XCode shows that you are building your app for that specific simulator with (Rosetta), then click on the ▶️ button to build.
>    ![3-build](https://private-user-images.githubusercontent.com/93145265/320272171-d49ba646-ba06-4f55-97ab-c548aa206924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTA3NzUsIm5iZiI6MTcxMjg5MDQ3NSwicGF0aCI6Ii85MzE0NTI2NS8zMjAyNzIxNzEtZDQ5YmE2NDYtYmEwNi00ZjU1LTk3YWItYzU0OGFhMjA2OTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWU4YThlMGE0MGQwZGRhMGVlMGI3MDBiNzE1OTVjMmM3ZjQzODJmN2FkODU4OWE0MWYyNDA5MzM5MzQyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asryk0VPB-fZ-h9GqYfI_uCzYowKeAykVPQn3by7XFc)
> 5. In your project, run `npm start` from the project root (not `ios` folder) to check your expo server is running of course.
> 
> Hope this helps! 🍻

not expo problem that because MacBook chip M1 building needs to use Rosetta architecture for building app

**Comment by Abdulmalick-Dimnang** [comment]
is there plans to have a solution instead of running emulators using rosetta?
