### ISSUE TITLE
Default prop values for maxZoomLevel and minZoomLevel don't match with reality

### ISSUE THREAD

**Issue by aikewoody** [react-native-maps/react-native-maps#4795]
### Summary

According to the docs the default prop value for `maxZoomLevel` is `20` and for `minZoomLevel` it is `0`, while the max and min values from the camera object are `21` and `2.01...`

### Reproducible sample code

```TSX
import React from 'react';
import {SafeAreaView, StyleSheet, Text} from 'react-native';
import MapView, {
  enableLatestRenderer,
  PROVIDER_GOOGLE,
} from 'react-native-maps';

enableLatestRenderer();

export default function App() {
  const [zoomLevel, setZoomLevel] = React.useState(0);
  const mapViewRef = React.useRef<MapView>(null);

  const onRegionChange = React.useCallback(async () => {
    const camera = await mapViewRef.current?.getCamera();
    if (camera?.zoom) {
      setZoomLevel(camera.zoom);
    }
  }, []);

  return (
    <>
      <MapView
        onRegionChange={onRegionChange}
        provider={PROVIDER_GOOGLE}
        ref={mapViewRef}
        showsMyLocationButton={true}
        showsUserLocation={true}
        style={styles.flex}
        zoomEnabled={true}
      />
      <SafeAreaView pointerEvents="box-none" style={StyleSheet.absoluteFill}>
        <Text>{zoomLevel}</Text>
      </SafeAreaView>
    </>
  );
}

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
});
```

### Steps to reproduce

Zoom all the way out and observe that the zoom level is not equal to `0`

Zoom all the way in and observe that the zoom level is not equal to `20`

### Expected result

The maximum and minimum zoom levels match the default prop values described in the documentation

### Actual result

The maximum and minimum zoom levels don't match with the default prop values described in the documentation

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.11

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 mini (16.4) - simulator

### Additional information

A reproducible codebase can be found at: https://github.com/aikewoody/example-react-native-maps-zoom-level
ps: after cloning change _YOUR_API_KEY_ to a valid value

**Comment by umarnsisar021** [comment]
Please follow the steps
https://youtu.be/VOCRBdzHEqM
