### ISSUE TITLE
LocalTile not working

### ISSUE THREAD

**Issue by katsimoto** [react-native-maps/react-native-maps#4799]
### Summary

Example repo: https://github.com/katsimoto/OfflineMapExample

### Reproducible sample code

```TSX
import React from 'react';
import {StyleSheet, View, Text, Dimensions} from 'react-native';
import MapView, {
  MAP_TYPES,
  PROVIDER_DEFAULT,
  LocalTile,
} from 'react-native-maps';

const {width, height} = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

class App extends React.Component<any, any> {
  constructor(props: any, context: any) {
    super(props, context);

    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
    };
  }

  get mapType() {
    // MapKit does not support 'none' as a base map
    return this.props.provider === PROVIDER_DEFAULT
      ? MAP_TYPES.STANDARD
      : MAP_TYPES.NONE;
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          provider={this.props.provider}
          mapType={this.mapType}
          style={styles.map}>
          <LocalTile
            pathTemplate="/storage/emulated/0/Documents/mytiles/{z}/{x}/{y}.png"
            tileSize={256}
            zIndex={-1}
          />
        </MapView>
        <View style={styles.buttonContainer}>
          <View style={styles.bubble}>
            <Text>Custom Tiles Local</Text>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bubble: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 80,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

export default App;
```

### Steps to reproduce

1. `npx react-native@latest init OfflineMapExample`
2. `cd OfflineMapExample`
3. `yarn add react-native-maps`
4. Add `com.google.android.geo.API_KEY` to `android/app/src/main/AndroidManifest.xml`
5. Copy example from https://github.com/react-native-maps/react-native-maps/blob/master/example/src/examples/CustomTilesLocal.tsx to App.tsx
6. Rename class `CustomTiles` to `App`.
7. Change `pathTemplate` to `/storage/emulated/0/Documents/mytiles/{z}/{x}/{y}.png`
8. Remove initialRegion
9. Download https://drive.google.com/file/d/1MWahbfhwI1WQ4MUm6f2NwIiGQn28oK7F/view?usp=sharing
10. Start emulator
11. `adb push mytiles/. /sdcard/Documents/mytiles`
12. `yarn android`
13. Close app after loading
14. Enable airplane mode
15. Open app

### Expected result

Displays the global map according to the 0/0/0 tile.

### Actual result

The global map displays only in the part that managed to be loaded into the cache at the end of step 12.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Android Emulator - Pixel_5_API_30

**Comment by donhurickerby** [comment]
@katsimoto were you able to get offline maps to work?

**Comment by katsimoto** [comment]
> @katsimoto were you able to get offline maps to work?

No.

**Comment by aroshanzamir** [comment]
I have the same problem..... suggestions?

**Comment by milad-hub** [comment]
I have this problem too, any idea?

**Comment by Cdingram** [comment]
I have the same issue with urltile but using file://. Works fine on iOS but not android.

**Comment by tamdvyounetgroup** [comment]
Any solution?

**Comment by singhaman25** [comment]
Did you find any solution for this?

**Comment by munozdaniel** [comment]
Any solution?

**Comment by Curanda** [comment]
Still relevant
