### ISSUE TITLE
Crash on custom marker after enable new architecture IOS

### ISSUE THREAD

**Issue by meghvarse** [react-native-maps/react-native-maps#4802]
### Summary

IOS app crashed if add any view inside <Marker> with error after enable new architecture :-

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTViewComponentView view]: unrecognized selector sent to instance 0x7f8e0e612390'

![Screenshot 2023-07-22 at 3 15 42 PM](https://github.com/react-native-maps/react-native-maps/assets/140066955/fab75d95-a1a1-49e6-9b26-ead9db90439c)

### Reproducible sample code

```TSX
import React from 'react';
import { Marker } from 'react-native-maps';

<Marker
              key={index}
              zIndex={ZIndexValue}
              coordinate={{
                latitude: get(item, 'location.latitude', 0),
                longitude: get(item, 'location.longitude', 0),
              }}
              tracksViewChanges={mapMarkers.trackChanges}
            >
<View style={{
                width: 40,
                height: 40,
                justifyContent: 'center',
                alignItems: 'center',
                borderRadius: 40 / 2,
                backgroundColor: 'red',
              }}></View>
</Marker>
```

### Steps to reproduce

Add View component inside Marker.

### Expected result

Worked with custom marker.

### Actual result

App crashed when add any view inside marker.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

IOS Simulator

**Comment by ravindraguptacapgemini** [comment]
@Simon-TechForm can you please check this issue, this is happening with many switching to new architecture

**Comment by ravindraguptacapgemini** [comment]
@meghvarse found any workaround for this issue?

**Comment by meghvarse** [comment]
> @meghvarse found any workaround for this issue?

@ravindraguptacapgemini Not yet

**Comment by meghvarse** [comment]
Any update on this please?

**Comment by dhanasekarancm** [comment]
I have referenced the example app and modified the API key as follows in `AppDelegate.mm`

`[GMSServices provideAPIKey:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"MAPS_API_KEY"]];`

However, it only functions correctly when added as indicated in the documentation:

`[GMSServices provideAPIKey:@"MAPS_API_KEY"];`

**Comment by janoslc** [comment]
Still relevant

**Comment by Flowwl** [comment]
Still relevant
