### ISSUE TITLE
enableLatestRenderer call flicker children in <Marker /> 

### ISSUE THREAD

**Issue by SlavaC7** [react-native-maps/react-native-maps#4804]
### Summary

when using enableLatestRenderer
child components flicker when nested in <Marker />. I don't know exactly why, but when I removed the function, the flickering stopped

This happens only on the Android platform, no matter on which device, it flickers on all

Svg.WashMarker:React.FC<SvgProps>

if you use Text or View or something else instead of SVG, it still does not work correctly

### Reproducible sample code

```TSX
const renderPlacePin = useCallback(
      ({ location: { coordinates }, id }: TCarWash, index: number) => {
        const activeImage =
          currentIndex === index ? EColors.primary_400 : EColors.black

        return (
          <Marker
            key={id}
            onPress={() =>
              onPressCarWash(index, coordinates[1], coordinates[0])
            }
            coordinate={{
              latitude: coordinates[0],
              longitude: coordinates[1],
            }}>
            <Svg.WashMarker fill={activeImage} />
          </Marker>
        )
      },
      [currentIndex, onPressCarWash],
    )
```

### Steps to reproduce

- Add function enableLatestRenderer to App.tsx as written in documentation

-add marker with child component

### Expected result

the marker renders the child component

### Actual result

marker flickering on android without rerendering function or component

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.0"

### What version of Expo are you using?

Not using Expo

### Device(s)

Readmi 8, 11 lite

**Comment by eltacogrande** [comment]
Seeing the same thing.

**Comment by uzuntonev** [comment]
I am facing the same issue. Any solution or workaround? If I use tracksViewChanges={false} to Marker, flickering stops, it is not a solution for me because I use Animate.Image that scale if it is selected

**Comment by hmust92** [comment]
Yup. Same issue here. If I go and change enableLatestRenderer to use Renderer.LEGACY, the marker stops flickering. On android, when Renderer.LATEST, the marker will randomly flicker.
