### ISSUE TITLE
When the prop "altitude" is not set the MapView does not work on Android

### ISSUE THREAD

**Issue by felipehidra** [react-native-maps/react-native-maps#4807]
### Summary

If you skip the prop "pitch" on the MapView, the following error occurs on opening the app on Android (The app opens and close. I got this error on LogCat of the Android studio):
`FATAL EXCEPTION: main
           Process: com.<package>, PID: 29312
           com.facebook.react.bridge.NoSuchKeyException: pitch
`

The same problem occurs if the prop "heading" is skipped. This should raise an Exception or an Error on the build.

### Reproducible sample code

```TSX
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'

<MapView
    showsCompass={false}
    toolbarEnabled={false}
    showsUserLocation
    provider={PROVIDER_GOOGLE}
    maxZoomLevel={16}
    minZoomLevel={12}
    style={Styles.map}
    ref={mapRef}
    initialCamera={{
        center: {
            latitude: userCoordinate[0],
            longitude: userCoordinate[1],
        },
        pitch: 85, // <- if I remove this prop, the error occurs on the Android
        heading: 30,
        zoom: 14,
    }}
    onRegionChange={handleOnStartChangeArea}
    onRegionChangeComplete={handleChangeArea}
>
    {markers}
</MapView>
```

### Steps to reproduce

1 - Import the MapView component
2 - Set the prop "initialCamera" and remove/skip de camera prop "pitch"
3 - Run the command "yarn android"
4 - The app will open and close in sequence without any error

### Expected result

The expected result should be the map appears on the coordinates specified on the prop "initialCamera.center".

### Actual result

The app opens and close as soon as the MapView Component is called!

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Motorola moto g(30)

**Comment by haiderTkxel** [comment]
@felipehidra Did you find any solution?

**Comment by felipehidra** [comment]
@haiderTkxel No. If the prop "pitch" is required, this should throw an error, no?

**Comment by salah-ghanim** [comment]
@felipehidra  not an issue ... please checkout typing (specifically MapView.types.ts / Camera type where pitch is explicitly required
