### ISSUE TITLE
Extremely slow map custom markers 

### ISSUE THREAD

**Issue by 0xcD3v** [react-native-maps/react-native-maps#4809]
### Summary

I have a custom marker with a Component and Image, am using react-native-map-clustering when the markers and inside the cluster the map runs faster, when zoom in if  have 20+ markers i start the a hunge decrease on the performance.

I already tried to set tracksViewChanges to false but after that the images doesn't load, only the Views and text render.

### Reproducible sample code

```TSX
<MapView
            ref={mapRef}
            mapType={mapType}
            tracksViewChanges={false}
            showsIndoors={false}
            loadingEnabled
            customMapStyle={[
              {
                featureType: 'poi',
                elementType: 'label',
                stylers: [{visibility: 'off'}],
              },
            ]}
            showsPointsOfInterest={false}
            provider={PROVIDER_GOOGLE}
            showsUserLocation={true}
            showsCompass={false}
            showsMyLocationButton
            toolbarEnabled={false}>
            {locals !== null || locals !== undefined
              ? locals?.map(element => {
                  return (
                    <Marker
                      // icon={
                      //   element.isToCollect
                      //     ? require('../assets/marker_1_80x80.png')
                      //     : require('../assets/marker_2_80x80.png')
                      // }
                      key={element?.description}
                      coordinate={{
                        latitude: element.latitude,
                        longitude: element.longitude,
                      }}
                      onPress={() =>
                        handleMarkerClick(element, 'local-1')
                      }>
                      <View
                        style={{
                          justifyContent: 'center',
                          alignItems: 'center',
                          opacity: element.pressed ? 0.7 : 1,
                        }}>
                        {element?.distance &&
                        element?.time &&
                        !showRoute.show ? (
                          <TimeDistanceInfo
                            image={require('../assets/pedestrian.png')}
                            time={element?.time}
                            distance={element?.distance}
                          />
                        ) : null}
                        <Image
                          source={
                            element.isToCollect
                              ? require('../assets/marker_1_80x80.png')
                              : require('../assets/marker_2_80x80.png')
                          }
                          resizeMode={'contain'}
                          style={{height: 60}}
                        />
                      </View>
                    </Marker>
                  );
                })
              : null}
</MapView>
```

### Steps to reproduce

.

### Expected result

The map running fast with custom markers 

### Actual result

The map start freezing , and is almost impossible to zoom out.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.71.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Android and IOS devices

**Comment by felipehidra** [comment]
The prop "tracksViewChanges" you should add to the Marker component and not to the MapView component.

**Comment by 0xcD3v** [comment]
> The prop "tracksViewChanges" you should add to the Marker component and not to the MapView component.

I know, ignore that i did that for testing and i forgot to remove.

**Comment by felipehidra** [comment]
But even after adding this prop to the Marker, this problem happens yet?

**Comment by 0xcD3v** [comment]
> But even after adding this prop to the Marker, this problem happens yet?

If i set tracksViewChanges to false the map runs without problems in terms of speed, but  Images inside the custom marker don't render. After searching i found this link  [https://itnext.io/performant-custom-map-markers-for-react-native-maps-ddc8d5a1eeb0](https://itnext.io/performant-custom-map-markers-for-react-native-maps-ddc8d5a1eeb0). i change that to a function compoment and for every image inside the custom component i check if the other's already loaded if so i change the value  of tracksViewChanges to false, i didn't properly test it but  i will update this after testing.

**Comment by CalNicklin** [comment]
This might be because you are using Marker children to render the marker. Can you use the icon prop instead? I see you have commented it out, but I can say for sure that using the icon prop will help performance!

**Comment by 0xcD3v** [comment]
> 

Yes this happens because am using marker children to render, but in my use case i can't use an icon prop, i need to render a "complex" maker using Image's and React Native components. The above solution seems to work in most of the time, sometimes it doesn't render properly but so far is the best solution i have.

**Comment by CalNicklin** [comment]
How about if you create the markers outside of the return function so you could memoize?

**Comment by stjasink** [comment]
There is an existing bug about custom markers on Android redrawing in a loop:  https://github.com/react-native-maps/react-native-maps/issues/4501

**Comment by umarnsisar021** [comment]
Please follow the steps
https://youtu.be/VOCRBdzHEqM

**Comment by RamonAmaro** [comment]
same problem here

**Comment by kuczi55** [comment]
@0xcD3v instead of dynamically changing `tracksViewChanges` prop you can try to create a ref to `Marker` component and manually redraw the marker after the image is loaded, so you would have something like this:
```js
<Marker
    ref={markerRef}
    ... >
    <Image
        fadeDuration={0}
        onLoad={
            Platform.OS === 'android'
		? markerRef.current?.redraw
		: undefined
	}
        ...
    />
</Marker>
```
I think redraw wasn't implemented on iOS (at least on Apple Maps as it's unnecessary) and can crash the app, so use it only on Android.
It probably won't resolve problems with occasional improper rendering (to resolve it you can try manually redraw marker using `redraw` function after child of `Marker` component was changed - adding some delay/timeout before executing `redraw` also could help), but it should improve performance a bit.

**Comment by stjasink** [comment]
Still relevant

**Comment by ThisisDC** [comment]
I found the solution in another Github issue. The problem is that trackViewChanges={true} re-renders the marker too often and creates performance issues. We only need to render the marker once for render the image. This is the example --> [https://github.com/react-native-maps/react-native-maps/issues/3339#issuecomment-853028829](url)

**Comment by zachgibson** [comment]
I've had success with the `tracksViewChanges` toggling dance. Set to `true` when you need to draw/animate then set to `false` after it's done.

**Comment by kkx64** [comment]
Though `tracksViewChanges` helps tremendously, the animations are super laggy on Android - but work amazing on iOS.
