### ISSUE TITLE
IsGesture on IOS devices

### ISSUE THREAD

**Issue by andrei-dnt** [react-native-maps/react-native-maps#4810]
### Summary

I saw in version 1.0.0 the issue of onRegionChangeComplete props (which has a property named isGesture, unavailable on ios ) was resolved..im  using version "1.3.2" .. and this method returns me undefined on ios devices

### Reproducible sample code

```TSX
const regionChanging = (values: any, details) => {
        console.log("details", details) => on android works, on ios returns only undefined
        if (details.isGesture === true) {
            onRegionChangeComplete(values)
            return
        }

    }

<MapView onRegionChangeComplete={(region, details) => regionChanging(region, details)} />
```

### Steps to reproduce

nothing special :D

### Expected result

to return true or false

### Actual result

undefined

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iphone 8

**Comment by statico** [comment]
This is an ongoing request: https://github.com/react-native-maps/react-native-maps/discussions/4440

The current solution is to use Google Maps on iOS.

**Comment by statico** [comment]
Still relevant

**Comment by statico** [comment]
Still relevant

**Comment by samih-sghier** [comment]
still relevant, however i found a workaround if anyone is looking for a fix this is my MapView ->  `   
   <MapView
        provider={Platform.OS == "android" ? "google" : undefined}
        style={styles.map}
        customMapStyle={customMapTheme}
        ref={mapRef}
        onPress={handleMapPress}
        region={region}
        onPanDrag={() => {
          if (!showSearchAreaButton && Platform.OS == "ios") setShowSearchAreaButton(true);
        }}
        onRegionChangeComplete={(region, isGesture) => {

          if (isGesture?.isGesture || Platform.OS == "ios") {
            if (!showSearchAreaButton && Platform.OS == "android") setShowSearchAreaButton(true);

            const newBoundingBox = [
              region.latitude - region.latitudeDelta / 2,
              region.latitude + region.latitudeDelta / 2,
              region.longitude - region.longitudeDelta / 2,
              region.longitude + region.longitudeDelta / 2,
            ];
            setRegion(region);
            setBoundingBox(newBoundingBox);
          }
        }}
      >`

**Comment by amykunerhouseful** [comment]
Still relevant

**Comment by anahids-ff** [comment]
Yes, it's still relevant...

**Comment by rwmnau** [comment]
Still relevant for me as well

**Comment by yshypat-sii** [comment]
Still relevant for us as well
