### ISSUE TITLE
iOS MapKit : Does not show user heading on default location marker

### ISSUE THREAD

**Issue by SwannPnct** [react-native-maps/react-native-maps#4811]
### Summary

iOS MapKit : Does not show user heading on default location marker, only a blue basic dot.

i am aware of https://github.com/react-native-maps/react-native-maps/issues/3905 and https://github.com/react-native-maps/react-native-maps/issues/4362 .

Although as said recently in 3905, MapKit heading property is available, see https://developer.apple.com/documentation/mapkit/mkuserlocation/1452721-heading?language=objc .

Is there anyway to add this feature? Would have done a Pull Request if i knew Objective-C.

### Reproducible sample code

```TSX
n/a
```

### Steps to reproduce

n/a

### Expected result

n/a

### Actual result

n/a

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 11 Pro ( ios 16)

**Comment by gediminastub** [comment]
Heya! Could this be reopened? I think this would be beneficial to map users. Thanks!

**Comment by WayneKim92** [comment]
If you need this, use [it](https://www.npmjs.com/package/react-native-maps-my-location-direction).
