### ISSUE TITLE
Question: Traffic visibility on Map

### ISSUE THREAD

**Issue by Rohit-Parte** [react-native-maps/react-native-maps#4817]
### Summary

Hi There!,

Is it possible/ or is there any way to show Traffic in MapView?

### Reproducible sample code

```TSX
NA
```

### Steps to reproduce

NA

### Expected result

NA

### Actual result

NA

### React Native Maps Version

NA

### What platforms are you seeing the problem on?

Android

### React Native Version

NA

### What version of Expo are you using?

Not using Expo

### Device(s)

NA

### Additional information

NA

**Comment by salah-ghanim** [comment]
@Rohit-Parte this feature is not supported directly via react-native-maps but I see that with Google Maps it's possible to call setTrafficEnabled on the GoogleMaps object and it should achive the expected bahviour.

see: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view#aba119ffe9f9b0c892027656767e59732
and: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap

I would suggest:
 1. simply have a local patch in your react-native repo that will add this feature, that way you can always keep up to date with this lib and add this feature each time you install your project (yarn install). example: https://anu-thomas.medium.com/patch-package-in-react-native-c7786a15e279
 
  2. create a pull request that add support for displaying of traffic info for google maps.
