### ISSUE TITLE
Android 'elevation' not working on Markers

### ISSUE THREAD

**Issue by PineAppleGrits** [react-native-maps/react-native-maps#4818]
### Summary

(Only tested on Android, i don't have iOS)
Im trying to set shadow to my markers, i didn't find any solution to this or clarification that it doesnt work on Google Maps.
This is what the marker looks like
![image](https://github.com/react-native-maps/react-native-maps/assets/66481194/58451855-a50f-472d-8dd7-5de15867946b)

### Reproducible sample code

```TSX
export const CustomMarker = ({ coordinate, image, onPress }: { image: string; coordinate: LatLng; onPress?: () => void }) => (
  <Marker onPress={onPress} tracksViewChanges={false} coordinate={coordinate}>
    <View
      style={{
        height: 50,
        width: 50,
        backgroundColor: "red",
        borderRadius: 25,
        overflow: "visible",
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 16.0,

        elevation: 24,
      }}
    />
  </Marker>
);
```

### Steps to reproduce

Add elevation style property to the marker

### Expected result

Marker showing shadow

### Actual result

Shadow not working

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

SDK 48

### Device(s)

Pixel 3a

**Comment by salah-ghanim** [comment]
This is not a bug, please take the time to understand how Google Maps work.

Google maps don't use native views so you can't simply use typical react-native props / behaviour to modify map view components (annotations, markers ...) ... instead please use whatever documented in the lib as supported.

good news is that on iOS apple maps does use native views so you can achive such behaviour there with MapKit.
