### ISSUE TITLE
Unable to resolve module ../Utilities/Platform from "global/path/to/node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js"

### ISSUE THREAD

**Issue by BimalPandeyCode** [react-native-maps/react-native-maps#4820]
### Summary

I used react-native-maps to build an app, it worked on expo go but as soon as I created a preview for expo via github actions it gave me the following error:
![image](https://github.com/react-native-maps/react-native-maps/assets/76998974/d11121a8-6483-4371-89a0-c34a95efa10a)

### Reproducible sample code

```TSX
import React from "react";
import MapView, { Marker } from "react-native-maps";
// just having the package installed caused the isue
const Map = ()=>{
    return <MapView
          onPress={(e) => {
            setMarkerCoordinate(e.nativeEvent.coordinate);
          }}
          style={{ width: "100%", height: 168, marginBottom: 5 }}
        >
          {markerCoordinate.latitude != 9999 &&
            markerCoordinate.longitude != 9999 && (
              <Marker coordinate={markerCoordinate} title="Job's Location" />
            )}
        </MapView>
}
```

### Steps to reproduce

1. Create a preview in github actions using https://docs.expo.dev/eas-update/github-actions/#publish-previews-on-pull-requests
2. Create a PR. 
3. It will fail in "Create preview" step

### Expected result

It works in both expo go app and in an emulator but fails to create a preview. 

### Actual result

![image](https://github.com/react-native-maps/react-native-maps/assets/76998974/fe8ea7c2-6ee7-4381-b160-628fb574dfb8)

inside utilities folder there isn't just a "platform" file but ios and android specific files.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

SDK 48

### Device(s)

Github Action's Expo Preview

**Comment by vinodsptharsha** [comment]
I have temporarily fixed with the below script for web

```
// webCompatibility.mjs
import { promises as fsPromises } from 'fs';
import chalk from 'chalk';

const { readFile, writeFile, copyFile } = fsPromises;

async function log(...args) {
  console.log(chalk.yellow('[react-native-maps]'), ...args);
}

// Export the function using CommonJS syntax
export const reactNativeMapsWeb = async function () {
  log('📦 Creating web compatibility of react-native-maps using an empty module loaded on web builds');
  const modulePath = 'node_modules/react-native-maps';
  await writeFile(`${modulePath}/lib/index.web.js`, 'module.exports = {}', 'utf-8');
  await copyFile(`${modulePath}/lib/index.d.ts`, `${modulePath}/lib/index.web.d.ts`);
  const pkg = JSON.parse(await readFile(`${modulePath}/package.json`));
  pkg['react-native'] = 'lib/index.js';
  pkg['main'] = 'lib/index.web.js';
  await writeFile(`${modulePath}/package.json`, JSON.stringify(pkg, null, 2), 'utf-8');
  log('✅ script ran successfully');
};

reactNativeMapsWeb();
```

and registered npm script

```
"create-web-compatibility": "node --experimental-modules webCompatibility.mjs"
```

**Comment by umarnsisar021** [comment]
Please follow the steps
https://youtu.be/VOCRBdzHEqM

**Comment by GoulvenFrs** [comment]
> I have temporarily fixed with the below script for web
> 
> ```
> // webCompatibility.mjs
> import { promises as fsPromises } from 'fs';
> import chalk from 'chalk';
> 
> const { readFile, writeFile, copyFile } = fsPromises;
> 
> async function log(...args) {
>   console.log(chalk.yellow('[react-native-maps]'), ...args);
> }
> 
> // Export the function using CommonJS syntax
> export const reactNativeMapsWeb = async function () {
>   log('📦 Creating web compatibility of react-native-maps using an empty module loaded on web builds');
>   const modulePath = 'node_modules/react-native-maps';
>   await writeFile(`${modulePath}/lib/index.web.js`, 'module.exports = {}', 'utf-8');
>   await copyFile(`${modulePath}/lib/index.d.ts`, `${modulePath}/lib/index.web.d.ts`);
>   const pkg = JSON.parse(await readFile(`${modulePath}/package.json`));
>   pkg['react-native'] = 'lib/index.js';
>   pkg['main'] = 'lib/index.web.js';
>   await writeFile(`${modulePath}/package.json`, JSON.stringify(pkg, null, 2), 'utf-8');
>   log('✅ script ran successfully');
> };
> 
> reactNativeMapsWeb();
> ```
> 
> and registered npm script
> 
> ```
> "create-web-compatibility": "node --experimental-modules webCompatibility.mjs"
> ```

Hi, I encounter the same issue ! Since I'm a newbie, can you provide more details to your solution ? Where do I put this script file ? and where do I put the npm script ? how do I launch the script ? 

I also checked the video https://youtu.be/VOCRBdzHEqM , it doesn't provide any fix. 

Here is my package.json ( Expo SDK49 / metro ) : 

>{
>  "name": "xyz",
>  "version": "1.0.0",
>  "scripts": {
>    "start": "expo start",
>    "android": "expo start --android",
>    "ios": "expo start --ios",
>    "web": "expo start --web"
>  },
>  "dependencies": {
>    "@react-navigation/drawer": "^6.6.3",
>    "@react-navigation/native-stack": "^6.9.13",
>    "expo": "~49.0.8",
>    "expo-constants": "~14.4.2",
>    "expo-font": "~11.4.0",
>    "expo-linear-gradient": "~12.3.0",
>    "expo-linking": "~5.0.2",
>    "expo-router": "2.0.0",
>    "expo-status-bar": "~1.6.0",
>    "react": "18.2.0",
>    "react-dom": "18.2.0",
>    "react-native": "0.72.4",
>    "react-native-gesture-handler": "~2.12.0",
>    "react-native-maps": "^1.7.1",
>    "react-native-reanimated": "~3.3.0",
>    "react-native-safe-area-context": "4.6.3",
>    "react-native-screens": "~3.22.0",
>    "react-native-web": "~0.19.6"
>  },
>  "devDependencies": {
>    "@babel/core": "^7.20.0"
>  },
>  "private": true
>}

**Comment by victorcngo** [comment]
Still relevant
