### ISSUE TITLE
[IOS-NEW-ARCH-BUG] - App crash while react trying to unmount MapView from navigation.

### ISSUE THREAD

**Issue by yardenPhy** [react-native-maps/react-native-maps#4823]
### Summary

in iPhone simulator when i try go back by the navigation the app crash.

the exception throwing is:

the exception is  reason	__NSCFString *	"-[RCTImageComponentView view]: unrecognized selector sent to instance 0x7f779c9202b0"	0x00006000074b1960

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
const [show,setShow] = observable(true);

// just show example code that casing to unmount 
// in my case is back button that trigger from react-navigation

useEffect(() => {
setTimeout(() => {
setShow(false);
},2000)

},[])

  return (
    <View>
{
show && <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
}
</View>
  );
}
```

### Steps to reproduce

show you map with markers and circle and polygons(in my case)
then go back screen that causing to unmount 
and then app crash and exit 

### Expected result

App should back to previous screen complete the back action

### Actual result

App crash and closed

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14pro simulator

**Comment by ravindraguptacapgemini** [comment]
@yardenShacham can you please check the issue with the custom marker as well. when specifying the custom image as child component for Marker, it does not display marker on map with New Architecture. @yardenPhy

**Comment by sagarj-iprogrammer** [comment]
any update for new New Architecture
