### ISSUE TITLE
Place overlay above map labels

### ISSUE THREAD

**Issue by bbbenja** [react-native-maps/react-native-maps#4828]
### Summary

Hello, 

Is there a way to place an `<Overlay>` component above all map labels on iOS and Android ?

Thanks

### Reproducible sample code

```TSX
<MapView style={{ flex: 1 }}>
          <Overlay
            bounds={[…]}
            image={{ uri: 'images/map_overlay.png' }}
          />
</MapView>
```

### Steps to reproduce

Just show this view with an overlay

### Expected result

I don't want to see road labels over my overlay but I want to see them where there is no overlay

### Actual result

![Simulator Screenshot - iPhone 14 Pro - 2023-08-23 at 15 40 28](https://github.com/react-native-maps/react-native-maps/assets/1065693/8f120724-4f93-4bb9-bfea-7d35f84eaa91)

### React Native Maps Version

1.7.1, v2.0.0-beta.14

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.71.8

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro

**Comment by jan-kozinski** [comment]
Hi, unfortunately it is impossible to draw an overlay above road labels, the SDK doesn't allow it. What you can do is disabling labels entirely or use sattelite view. See https://stackoverflow.com/questions/16124230/how-to-i-control-the-z-index-of-a-groundoverlay-versus-map-features and https://stackoverflow.com/questions/16124230/how-to-i-control-the-z-index-of-a-groundoverlay-versus-map-features
