### ISSUE TITLE
onRegionChangeComplete returns latitude 0, while longitude value is valid.

### ISSUE THREAD

**Issue by khushbujilka22** [react-native-maps/react-native-maps#4830]
### Summary

we are facing this issue since last 3 months, onRegionChange randomly returns latitude 0, it generates only with IOS.

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

const onRegionChangeComplete = region => {
    console.log('onRegionChangeComplete', region);
};

return (
    <MapView
        onPress={() => {
            Keyboard.dismiss();
        }}
        ref={MapRef}
        cacheEnabled={false}
        loadingEnabled
        mapType={'standard'}
        provider={PROVIDER_GOOGLE}
        initialRegion={{
            latitude: 22.30418739019426,
            latitudeDelta: 0.006372572778374774,
            longitude: 70.80215971916914,
            longitudeDelta: 0.004216432571411133,
        }}
        userLocationAnnotationTitle={'My Location'}
        onRegionChangeComplete={onRegionChangeComplete}
        showsMyLocationButton={false}
    />
);
```

### Steps to reproduce

 Randomly generated issue.

### Expected result

 `latitude: 22.30418739019426
latitudeDelta: 0.006372572778374774
longitude: 70.80215971916914
longitudeDelta: 0.004216432571411133` 

### Actual result

`latitude: 0
latitudeDelta: 0.006372572778374774
longitude: 70.80215971916914
longitudeDelta: 0.004216432571411133`

### React Native Maps Version

0.29.3

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.67.3

### What version of Expo are you using?

Not using Expo

### Device(s)

IPhone

**Comment by meghvarse** [comment]
@khushbujilka22 , It happens with new architecture enable?

**Comment by khushbujilka22** [comment]
@meghvarse, NO 

it happens with react-native 0.67.3.

**Comment by khushbujilka22** [comment]
plz help here.
