### ISSUE TITLE
AIRMap is not compatible yet

### ISSUE THREAD

**Issue by Akshaybagai52** [react-native-maps/react-native-maps#4833]
### Summary

I'm getting this error whenever i want to create MapView component. I already wrote my code if there is error in my code then anyone can comment that

### Reproducible sample code

```TSX
const initialRegion = {
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  };
<MapView style={styles.map} initialRegion={initialRegion}>
              <Marker
                coordinate={{
                  latitude: 37.78825,
                  longitude: -122.4324,
                }}
                title="Marker Title"
                description="Marker Description"
              />
            </MapView>
```

### Steps to reproduce

Whenever using Mapview getting this error

### Expected result

It needs to show Map in my app

### Actual result

AIRMap is not Fabric compatible yet.

### React Native Maps Version

^1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Google Pixel 4

**Comment by locndipro** [comment]
It's the same problem for me. Can someone help me with this problem? I have it on Android

**Comment by abocoum** [comment]
in your android gradle.properties 
disable new architecture by setting following property to false 
newArchEnabled=false.

#4383 is related

**Comment by HosamCS** [comment]
> in your android gradle.properties disable new architecture by setting following property to false newArchEnabled=false.
> 
> #4383 is related

not working

**Comment by Elidor00** [comment]
I have a [similar issue](https://github.com/react-native-maps/react-native-maps/issues/4888)

**Comment by sagarj-iprogrammer** [comment]
any update ?

**Comment by sverano** [comment]
> Create a file named react-native.config.js in the root directory of your project & paste this
> 
> ```
> module.exports = {
>   project: {
>     android: {
>       unstable_reactLegacyComponentNames: ['AIRMap'],
>     },
>     ios: {
>       unstable_reactLegacyComponentNames: ['AIRMap'],
>     },
>   },
> };
> ```
> 
> this fixed the issue for me

is work for me thanks ❤️

**Comment by hareesh7777** [comment]
in your android gradle.properties
disable new architecture by setting following property to false
newArchEnabled=false.

after doing this uninstall application and reinstall again

**Comment by rogerchang** [comment]
This worked for me by using the legacy components in the new architecture
`module.exports = {
    project: {
        android: {
            unstable_reactLegacyComponentNames: [
                'AIRGoogleMap',
                'AIRMap',
                'AIRMapMarker',
                'PanoramaView'
            ],
        },
        ios: {
            unstable_reactLegacyComponentNames: [
                'AIRGoogleMap',
                'AIRMap',
                'AIRMapMarker',
                'PanoramaView'
            ],
        },
    },
};`

**Comment by sarathshankarr** [comment]
same issue
AIRMap is not compatible yet
import React from 'react';
import {StyleSheet, Text, View} from 'react-native';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';

const CustomerLocation = () => {
  return (
    <View style={styles.container}>
      <MapView
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}></MapView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    height: "100%",
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});
export default CustomerLocation;
 "react-native": "0.73.6",
    "react-native-maps": "^1.14.0",
