### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by haiderTkxel** [react-native-maps/react-native-maps#4835]
### Summary

Android app crashes. If I remove map view code then crash don't happen:

FATAL EXCEPTION: main
    Process: com.signaturepharmacy, PID: 16721
    com.facebook.react.bridge.NoSuchKeyException: pitch
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:117)
        at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:154)
        at com.rnmaps.maps.MapView.moveToCamera(MapView.java:570)
        at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:508)
        at com.rnmaps.maps.MapView.onMapReady(MapView.java:248)
        at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
        at com.google.android.gms.maps.internal.zzaq.zza(com.google.android.gms:play-services-maps@@18.0.0:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
        at android.os.Binder.transact(Binder.java:1084)
        at m.fh.c(:com.google.android.gms.dynamite_mapsdynamite@233217044@23.32.17 (190400-0):8)
        at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@233217044@23.32.17 (190400-0):19)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8249)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### Reproducible sample code

```TSX
<MapView
          style={styles.mapView}
          provider={PROVIDER_GOOGLE}
          initialRegion={currentLocation}
          showsUserLocation={true}
          initialCamera={initialCamera}
          mapType={Platform.OS == "android" ? "none" : "standard"}
        >
          {orders.map((order, index) => (
            <Marker
              key={index}
              // image={icons.marker}
              coordinate={order.coordinate}
              // title={`Waypoint ${index + 1}`}
              onPress={() => {
                (order.status === Strings.new ||
                  order.status === Strings.inProgress) &&
                  handlePressOnMarker(order);
              }}
            >
              <MarkerWithText order={order} />
            </Marker>
          ))}

          {/* Render polyline */}

          <Polyline
            coordinates={routeCoordinates}
            strokeColor={theme.colors.blue4}
            strokeWidth={4}
            lineDashPattern={[15, 15]}
          />
        </MapView>
```

### Steps to reproduce

Before map screen appears, the app crashes.

### Expected result

Android app should not crash.

### Actual result

Google map should be displayed.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.8

### What version of Expo are you using?

Not using Expo

### Device(s)

OPPO

### Additional information

android/build.gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

The dependencies block in android/app/build.gradle:

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }

    implementation project(':react-native-camera')

    implementation(project(':react-native-maps')){
      exclude group: 'com.google.android.gms'
  }
  implementation 'com.google.android.gms:play-services-base:18.0.1'
  implementation 'com.google.android.gms:play-services-location:19.0.1'
  implementation 'com.google.android.gms:play-services-maps:18.0.2'
}

**Comment by stesvis** [comment]
I am using **Expo** and it crashes on me too with

> API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml

I have the API key in my **app.json** like explained in this doc:
https://docs.expo.dev/versions/latest/sdk/map-view/#android

```json
    "android": {
      "config": {
        "googleMaps": {
          "apiKey": "<My API key from Google Cloud Console"
        }
      },
    },
```

Any solution?

**Comment by megaacheyounes** [comment]
The issue happens when you set the property `initialCamera`, the library expect parameters `pitch` and `heading` to aways have values

One way to fix your code is to add default/hardcode the values for `pitch` and `heading` this way:
```jsx
<MapView
          style={styles.mapView}
          provider={PROVIDER_GOOGLE}
          initialRegion={currentLocation}
          showsUserLocation={true}
          initialCamera={{...initialCamera , heading : 1 , pitch: 1 } } // <----
          mapType={Platform.OS == "android" ? "none" : "standard"}
        >
//[...]
</MapView>
```
This will stop the app from crashing, but I would NOT consider it a solution, library maintainers should add default values or safety tests

**Comment by salah-ghanim** [comment]
@haiderTkxel not an issue ... please checkout typing (specifically MapView.types.ts / Camera type where pitch is explicitly required

**Comment by ibrahimbmohammed** [comment]
any update about this issue, currently stuck with this issue, and none of the solutions I discovered thus far worked

**Comment by JuancaOStos** [comment]
I have the same problem. I'm using Expo and where there is a MapView, the app crashes.
The point is I don't use initialCamera in any of them:
```jsx
<View>
  <MapView
      style={{
          width: '100%',
          height: 180
      }}
      region={{
          latitude: 40,
          longitude: 40,
          latitudeDelta: 0.09,
          longitudeDelta: 0.04
      }}
      scrollEnabled={false}
      zoomEnabled={false}
  >
      <Marker
          coordinate={{
              latitude: 36.726989,
              longitude: -4.468369,
              latitudeDelta: 0.09,
              longitudeDelta: 0.04
          }}
      />
  </MapView>
</View>
```

At this point, I don't know what could happens

**Comment by gerryfletch** [comment]
Same for me, only on Android.

```
Error while updating property 'coordinate' of a view managed by: AIRMapMarker
NoSuchKeyException: longitude
```

**Comment by longtimeno-c** [comment]
Any news on this I'm having the same issue... no initial camera used ( I have region used...)

**Comment by Rquaicoo** [comment]
Any solution??

**Comment by joshex150** [comment]
any solution

**Comment by mmsmadi** [comment]
I had similar issue, it seems out that **latitude & longitude** was strings, so I just converted their values into numbers and everything worked as expected

`
initialRegion={{
    latitude: Number(latitude),
    longitude: Number(longitude),
    latitudeDelta: 0.003,
    longitudeDelta: 0.003,
 }}
`
