### ISSUE TITLE
also have the problem,when use polygon component, holes can not  show when debugging off

### ISSUE THREAD

**Issue by leeeGreat** [react-native-maps/react-native-maps#4836]
### Summary

same as https://github.com/react-native-maps/react-native-maps/issues/2845
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-maps": "0.31.1",

### Reproducible sample code

```TSX
import React, {useMemo} from 'react';
import {inject} from 'mobx-react/native';
import {Polygon} from 'react-native-maps';

export const PolygonsView = inject(store => ({
  data: store.panel.home.type5Array,
  zones: store.panel.home.zones,
  isHide: store.panel.home.disabled,
  areaList: store.panel.areaList,
}))(
  ({
    data = [],
    zones = [],
    isHide = false,
    areaList = [],
    onPolygonClicked = () => {},
  }) => {
    const tmpPolygonEles = useMemo(() => {
      const result = data.map((polygon, index) => {
        console.log('polygon.id----', polygon.id);
        const {areatype = 1} = polygon;
        let lineColor = '#fffff';
        let fillColor = '#fffff';
        console.log('areatype---', areatype);
        switch (areatype) {
          case 1:
            lineColor = '#53A0F4';
            fillColor = '#53A0F475'; // 0.46
            break;
          case 2:
            lineColor = '#35D69C';
            fillColor = '#35D69C75';
            break;
          case 3:
            lineColor = '#35D69C';
            fillColor = '#35D69C75';
            break;
        }
        const coordinates = [...polygon.coordinates];
        if (coordinates.length === 0) {
          return null;
        }
        const holes = JSON.parse(JSON.stringify(polygon.holes));
        return (
          <Polygon
            // shouldRasterizeIOS
            tappable
            onPress={() => {
            }}
            // zIndex={99}  // cannot open
            key={polygon.id}
            coordinates={coordinates}
            holes={holes}
            strokeColor={lineColor}
            fillColor={fillColor}
            strokeWidth={1}
          />
        );
      });
      return result;
    }, [data, zones]);
    if (tmpPolygonEles?.length === 0 || isHide) {
      return null;
    }
    return tmpPolygonEles;
  },
);
```

### Steps to reproduce

when debugging on,holes show ok,when after build bundle in app, the holes can not show

### Expected result

when after build bundle in app, the holes can show correct

### Actual result

![holes not show](https://github.com/react-native-maps/react-native-maps/assets/18436097/a2c28874-1801-4793-82b9-28cabe0747ec)
![holes show](https://github.com/react-native-maps/react-native-maps/assets/18436097/fd057f41-7d3c-4d11-a2fb-90bf9ea0b8d9)

holes show
holes can not show

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.63.2

### What version of Expo are you using?

Not using Expo

### Device(s)

12 promax

### Additional information

none

**Comment by leeeGreat** [comment]
when debug is set off,the proper fillColor is not avaliable,when remove the fillColor proper,holes appears,but it is not my wanted result, i want set color as well

**Comment by leeeGreat** [comment]
i have update to latest version 1.7.1，here is sample code，it is funny

return (
          <Polygon
            // shouldRasterizeIOS  // Cannot open, otherwise holes will not be displayed
            // onPress={() => {}}  Cannot open, otherwise holes will not be displayed
            // zIndex={99}  // Cannot open, otherwise holes will not be displayed, regardless of debug on/off. What should I do if I encounter a layer error?
            key={polygon.id}
            coordinates={coordinates}
            holes={holes} // 区域地图？
            strokeColor={lineColor}
            fillColor={fillColor} // 打开会不显示holes，debug off情况下
            strokeWidth={1}
          />
        );

when remove onPress property in Polygon component, holes can show，but onPress action is not working，but i want the onPres action
Both the zIndex property and onPress property cannot be set, otherwise holes will not be displayed

**Comment by christophemenager** [comment]
@leeeGreat I have the exact same issue. 

- I have a `MapPolygon` with an other single polygon as a hole.
- Adding onPress prop to the `MapPolygon` hides the hole, **only on iOS**

I have no idea how to fix this, for now I removed the onPress as it's not critical for my feature
