### ISSUE TITLE
UrlTile doesn't show right away

### ISSUE THREAD

**Issue by eznix86** [react-native-maps/react-native-maps#4839]
### Summary

When placing an UrlTile On Android in the Mapview component, We are supposed to have the loaded right away, it takes 10  (or even more) seconds to show.

on iOS zero issue (nearly instant)

### Reproducible sample code

```TSX
import { Text, SafeAreaView, StyleSheet } from 'react-native';
import MapView, {UrlTile} from "react-native-maps"

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <MapView style={{flex: 1}}>
    

        <UrlTile
          urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
      </MapView>
    </SafeAreaView>
  );
}
```

### Steps to reproduce

Just run this snack on Android:

https://snack.expo.dev/K6ubhFdGl

### Expected result

UrlTile to show instantly or after few seconds

### Actual result

No tile showing up after 30 secs

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.8

### What version of Expo are you using?

SDK 48

### Device(s)

Pixel 4a

**Comment by amiramira22** [comment]
Still relevant
