### ISSUE TITLE
Animating to MapRegion with custom animation, using AnimatedRegion, re-orients map to angle 0

### ISSUE THREAD

**Issue by Robert6321** [react-native-maps/react-native-maps#4841]
### Summary

I am attempting to animate the map's region using `animatedRegion`. However, when the animation runs and the map is tilted at a certain heading, it resets the map to a heading of 0 degrees while updating the map's region. One alternative is to use `animateCamera` to animate the map, which preserves the heading while animating the region. However, this approach restricts me from specifying my own animation specifications, the only thing that can be controlled is the animation's duration. **Ideally, I would like to update the map's region with a custom animation specification while retaining the map's heading.**

### Reproducible sample code

```TSX
import {
  Easing,
  Button,
  View,
} from 'react-native';
import MapView, { AnimatedRegion, Animated } from 'react-native-maps';
import { useRef } from 'react';

export default function App() {
  const animatedRegion = new AnimatedRegion({
    longitude: 81.06946573710633,
    latitude: 25.634236139173908,
    latitudeDelta: 0.6665647557651191,
    longitudeDelta: 0.5834163331793434,
  });

  const mapRef = useRef(null);

  const animateMap = () => {
    animatedRegion
      .timing({
        longitude: 61.06946573710633,
        latitude: 25.634236139173908,
        latitudeDelta: 0.6665647557651191,
        longitudeDelta: 0.5834163331793434,
        easing: Easing.bezier(0.44, 0.66, 0, 0.99),
        timing: 600,
      })
      .start();
  };

  return (
    <View style={{ flex: 1 }}>
      <Animated
        style={{ flex: 1 }}
        ref={mapRef}
        region={animatedRegion}
        rotateEnabled={true}
      />
      <View style={{ bottom: 50 }}>
        <Button
          title="Animate Map"
          onPress={animateMap}
        />
      </View>
    </View>
  );
}
```

### Steps to reproduce

Update the map's region by updating the animatedRegion passed to the region prop

### Expected result

Map's region should update while maintaining map's heading.

### Actual result

Map's region is updated and heading is reset to 0 degrees.

### React Native Maps Version

0.30.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro

**Comment by mateki0** [comment]
I will check that :)

**Comment by mateki0** [comment]
Hi, @Robert6321 I was trying to fix it but I couldn't find a proper solution in the native code, I'm not even sure if it's possible. The only thing that I managed to find is this workaround, but unfortunately it's working only on iOS so I'm not sure if it will be helpful for you.
```tsx
import {Easing, Button, View} from 'react-native';
import {AnimatedRegion, Animated} from 'react-native-maps';
import React, {useRef} from 'react';

export default function AnimatedMarkers() {
  const animatedRegion = new AnimatedRegion({
    longitude: 81.06946573710633,
    latitude: 25.634236139173908,
    latitudeDelta: 0.6665647557651191,
    longitudeDelta: 0.5834163331793434,
  });

  const mapRef = useRef(null);

  const animateMap = async () => {
    const camera = await mapRef?.current?.getCamera();

    animatedRegion
      .timing({
        longitude: 61.06946573710633,
        latitude: 25.634236139173908,
        latitudeDelta: 0.6665647557651191,
        longitudeDelta: 0.5834163331793434,
        easing: Easing.bezier(0.44, 0.66, 0, 0.99),
        timing: 600,
      })
      .start(() => {
        mapRef?.current?.animateCamera({
          heading: camera.heading,
        });
      });
  };

  return (
    <View style={{flex: 1}}>
      <Animated
        style={{flex: 1, width: 400}}
        ref={mapRef}
        region={animatedRegion}
        rotateEnabled={true}
      />
      <View style={{bottom: 50}}>
        <Button title="Animate Map" onPress={animateMap} />
      </View>
    </View>
  );
}

```

**Comment by Robert6321** [comment]
Still relevant

**Comment by Robert6321** [comment]
Still relevant
