### ISSUE TITLE
Android Device Only - Error while updating property 'showsUserLocation' of a view managed by: AIRMap

### ISSUE THREAD

**Issue by izzuddinraffar** [react-native-maps/react-native-maps#4842]
### Summary

Hello,

I'm encountering an issue while using the latest versions of react-native-maps and react-native. Below, you'll find a screenshot of my android/build.gradle file for reference:
![image](https://github.com/react-native-maps/react-native-maps/assets/24266466/19410b13-0752-43e5-9d06-24ce4eb54ee0)

Despite my efforts, I haven't been able to resolve this problem. I've explored various solutions in the issues section, but none of them seem to work for me.

I've attempted the following in my android/app/build.gradle file:
Adding `implementation "com.google.android.gms:play-services-location:20.0.0"`
or `implementation "com.google.android.gms:play-services-location:21.0.1"`

Additionally, I experimented with different playServicesVersion values in android/build.gradle, including:
```
playServicesVersion = "18.0.0"
playServicesVersion = "20.0.0"
playServicesVersion = "21.0.1"
```
Also attempted using the beta version of react-native-maps, and it worked but it caused issues with my existing map code and contained some bugs, such as lacking support for `animated` in `.fitToCoordinates`."

### Reproducible sample code

```TSX
<MapView
      ref={ref}
      provider={PROVIDER_GOOGLE}
      style={{flex: 1}}
      showsUserLocation={true} // show user's current location
      showsMyLocationButton={true} // show button to center on user's location
      initialRegion={{
        latitude: 6.1897,
        longitude: 102.1573,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }}
      {...props.mapProps}
      // region={{
      //   latitude: 6.155625340041729,
      //   latitudeDelta: 0.02002058218781322,
      //   longitude: 102.1837292611599,
      //   longitudeDelta: 0.012100785970673655,
      // }}
      customMapStyle={mapOptions.customMapStyle}>
      {props.children}
    </MapView>
```

### Steps to reproduce

Just run `./gradlew clean`  and  `yarn react-native run-android`

### Expected result

It should be working fine on `showsUserLocation={true}`. But if `showsUserLocation={false}` is ok.

### Actual result

![WhatsApp Image 2023-09-09 at 01 15 16](https://github.com/react-native-maps/react-native-maps/assets/24266466/b50bf8d7-8332-422c-89e5-7e4004351017)

### React Native Maps Version

^1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.4

### What version of Expo are you using?

Not using Expo

### Device(s)

SAMSUNG GALAXY S20 FE (ANDROID 13)

### Additional information

Please assist me in resolving this issue; I am currently stuck at this point. Thanks!

**Comment by izzuddinraffar** [comment]
The map is functioning correctly after I made changes to the dependency in the `node_modules/react-native-maps/build.gradle` file as follows:
```
+ classpath("com.android.tools.build:gradle:7.1.1")
+ implementation "com.google.android.gms:play-services-location:21.0.1"
```
But please assist me in discovering a better and proper solution instead of this.

file `node_modules/react-native-maps/build.gradle`
```
def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

buildscript {
  // The Android Gradle plugin is only required when opening the android folder stand-alone.
  // This avoids unnecessary downloads and potential conflicts when the library is included as a
  // module dependency in an application project.
  if (project == rootProject) {
    repositories {
      google()
      mavenCentral()
    }
    dependencies {
      classpath("com.android.tools.build:gradle:7.1.1")
    }
  }
}

apply plugin: 'com.android.library'

android {
  compileSdkVersion safeExtGet('compileSdkVersion', 31)

  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 21)
    targetSdkVersion safeExtGet('targetSdkVersion', 31)
  }
}

repositories {
  mavenLocal()
  mavenCentral()
  maven {
    // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
    url "$rootDir/../node_modules/react-native/android"
  }
  maven {
    // Android JSC is installed from npm
    url "$rootDir/../node_modules/jsc-android/dist"
  }
  google()
}

dependencies {
  implementation 'com.facebook.react:react-native:+'
  implementation "com.google.android.gms:play-services-base:${safeExtGet('playServicesVersion', '18.1.0')}"
  implementation "com.google.android.gms:play-services-maps:${safeExtGet('playServicesVersion', '18.0.2')}"
  implementation "com.google.android.gms:play-services-location:21.0.1"
  implementation 'com.google.maps.android:android-maps-utils:3.4.0'
  implementation "androidx.work:work-runtime:2.7.1"
}

```

**Comment by Blackfaded** [comment]
Facing the same issue after upgrading react-native from `0.71.10` to `0.72.4`.

**Comment by Blackfaded** [comment]
Hm I cant tell exactly. Maybe you could just install the package as the first step and then go on with all other steps.

But if you have the patchfile and remove node modules and make a fresh install everything should be fine 👌

**Comment by izzuddinraffar** [comment]
> Hm I cant tell exactly. Maybe you could just install the package as the first step and then go on with all other steps.
> 
> But if you have the patchfile and remove node modules and make a fresh install everything should be fine 👌

Now it working fine, maybe that was my mistake. I placed "postinstall": "patch-package" in the wrong location. Thanks.

**Comment by vagnerlandio** [comment]
Patch file for pnpm

```rootProjectFolder/patches/react-native-maps@1.7.1.patch```
```diff
diff --git a/android/build.gradle b/android/build.gradle
index 88b8991180f0c6c44ffba07269fff3c242133701..57265d193aff485be99d1399a8369c7ed899844c 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -46,7 +46,7 @@ dependencies {
   implementation 'com.facebook.react:react-native:+'
   implementation "com.google.android.gms:play-services-base:${safeExtGet('playServicesVersion', '18.1.0')}"
   implementation "com.google.android.gms:play-services-maps:${safeExtGet('playServicesVersion', '18.0.2')}"
-  implementation "com.google.android.gms:play-services-location:20.0.0"
+  implementation "com.google.android.gms:play-services-location:21.0.0"
   implementation 'com.google.maps.android:android-maps-utils:3.4.0'
   implementation "androidx.work:work-runtime:2.7.1"
 }
```

**Comment by galihriski** [comment]
> > > Hm I cant tell exactly. Maybe you could just install the package as the first step and then go on with all other steps.
> > > But if you have the patchfile and remove node modules and make a fresh install everything should be fine 👌
> > 
> > 
> > Now it working fine, maybe that was my mistake. I placed "postinstall": "patch-package" in the wrong location. Thanks.
> 
> its still happens for me
> 
> this is the result in the terminal after trying npx patch-package react-native-maps --include "android/build.gradle"
> 
> $ npx patch-package react-native-maps --include "android/build.gradle" patch-package 8.0.0 patch-package: you have both yarn.lock and package-lock.json Defaulting to using npm You can override this setting by passing --use-yarn or deleting package-lock.json if you don't need it
> 
> • Creating temporary folder • Installing react-native-maps@1.7.1 with npm • Diffing your files with clean files ⁉️ Not creating patch file for package 'react-native-maps' ⁉️ There don't appear to be any changes.
> 
> I already change the google maps implementation to implementation "com.google.android.gms:play-services-location:21.0.0"
> 
> but its revert back to implementation "com.google.android.gms:play-services-location:20.0.0"

oh its worked now,

im trying this instead

npx patch-package react-native-maps --exclude

**Comment by toluasalu** [comment]
Still relevant

**Comment by Nixhazel** [comment]
still relevant

**Comment by k-saparia** [comment]
can be reproduced! still relevant and using RN v0.72.10

**Comment by neingeist** [comment]
For me, updating to `react-native-maps@~1.10.3` fixed the issue.

**Comment by althoff0** [comment]
Still relevant, working through this issue with a react-native app now

**Comment by BogdanRad** [comment]
I have same error in    `"react-native-maps": "1.15.3"` with    `"react-native": "0.74.6"` ... @althoff0 did  you find a solution?
