### ISSUE TITLE
Not able to zoom out MapView below zoom level 2

### ISSUE THREAD

**Issue by AMITHATHAMPY** [react-native-maps/react-native-maps#4849]
### Summary

I'm trying to make the MapView zoom out to level 0 and 1. But it is not working below zoom level 2. Minimum and Maximum zoom level provided is 0 and 20 respectively

### Reproducible sample code

```TSX
Any code with react-native-map
```

### Steps to reproduce

Install react-native-maps in a react-native project
Add a sample react-native-maps usage code.
Zoom out the map to a level below 2

### Expected result

Should zoom out till the specified min zoom level

### Actual result

Not able to zoom out below 2

### React Native Maps Version

1.7.0

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.71.2

### What version of Expo are you using?

Not using Expo

### Device(s)

All

**Comment by mateki0** [comment]
Hi @AMITHATHAMPY this is what I found in Google Maps SDK documentation. I think it's not a bug in react-native-maps itself. The only thing we can do is updating documentation with the link to the documentation to make it clear for everyone
```
"The range of zoom levels permitted by the map depends on a number of factors including target, map type and screen size. Any number out of the range will be converted to the next closest valid value, which can be either the minimum zoom level or the maximum zoom level"
```
https://developers.google.com/maps/documentation/ios-sdk/views#zoom
