### ISSUE TITLE
[NOT A BUG] How to render geojson without the underlying map

### ISSUE THREAD

**Issue by Pareder** [react-native-maps/react-native-maps#4852]
### Summary

I have a custom geojson file with all the countries' borders and so on and I want to render only it without the underlying map. At first I don't want to be billed by Google Maps because I don't need this map at all. At second some borders (especially islands) of Google maps differ from my geojson border and I want to get rid of it. 

The potential fix of second problem is to use `customMapStyle` prop and hide all land using some color, but it will not fix the first problem.

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { Geojson } from 'react-native-maps';

const geojson = {
  type: 'FeatureCollection',
  features: [...],
}

export default function App() {
  return (
    <MapView
      style={{ flex: 1 }}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    >
      <Geojson geojson={geojson} fillColor="#ffffff"/>
    </MapView>
  )
}
```

### Steps to reproduce

Just run the provided sample code.

### Expected result

The expected result is without extra land rendered by Google Maps.

### Actual result

![image](https://github.com/react-native-maps/react-native-maps/assets/28930553/ea2e766f-75a6-4ee7-a5c3-551a52da0a9b)

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.5

### What version of Expo are you using?

Not using Expo

### Device(s)

All Android devices

**Comment by Ahmedhamed77** [comment]
@Pareder 
could you explain more about the problem
as I see you described more than one problem here
I will write some solutions for you as I understand if not please correct me 

**Avoid Google Maps Billing**: If you're using react-native-maps, by default, it uses Apple Maps on iOS and Google Maps on Android. If you want to prevent any Google Maps charges, consider using react-native-maps without any specific provider, which defaults to the native maps of the platform.

**Hide the Underlying Map**: If you still prefer to use Google Maps (or any other provider) but want to hide the map details, you can use the customMapStyle prop to make the entire map a solid color, then render only the borders from your GeoJSON.

```
   <MapView
      style={{ flex: 1 }}
      customMapStyle={[
        {
          featureType: "all",
          elementType: "all",
          stylers: [
            { visibility: "off" } // This hides everything
          ]
        },
        {
          featureType: "landscape",
          stylers: [
            { visibility: "on" }, // This will show the landscape (if you want)
            { color: "#ffffff" }  // This sets the landscape to white
          ]
        }
      ]}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    >
      <Geojson geojson={geojson} fillColor="#ffffff"/>
    </MapView>
   
 ```
 
hope this will help you as I understood from your description

**Comment by Pareder** [comment]
@Ahmedhamed77 Thanks for your answer. You mentioned 
>If you want to prevent any Google Maps charges, consider using react-native-maps without any specific provider

But how can I do it? As I understood it is not possible in the current version of this library.

**Hide the Underlying Map:** `customMapStyle` prop will work only with Google Maps, it is a good trick anyway.

**Comment by Ahmedhamed77** [comment]
@Pareder Yes unfortunately you still need to add a payment method to Google to get an API key however google gives you a free trial with 200$ every month, if you are doing an individual project that will be okay I guess 
https://developers.google.com/maps/documentation/android-sdk/get-api-key
unfortunately, it's Google policy as I understand
