### ISSUE TITLE
error build IOS

### ISSUE THREAD

**Issue by fukemy** [react-native-maps/react-native-maps#4853]
### Summary

I got this erro when build

<img width="1504" alt="Screenshot 2023-09-28 at 09 52 32" src="https://github.com/react-native-maps/react-native-maps/assets/8202437/14441bd1-54d8-4216-8ca3-bb63bae0f7ea">

### Reproducible sample code

```TSX
no code here
```

### Steps to reproduce

no step here

### Expected result

build success

### Actual result

build failed

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.8

### What version of Expo are you using?

Not using Expo

### Device(s)

simulator IOS

### Additional information

RN 0.71.8
React 18.2.0

**Comment by cgandiaf** [comment]
Same here
In my case, It happened when upgrading from Xcode14 to 15.

Can anybody help? Thanks!!

**Comment by migsandia-1984** [comment]
Add the following to your Podfile above the use_native_modules! function and run pod install in the ios folder:

```
# React Native Maps dependencies
# The following line is only needed if building on an Apple silicon Mac without rosetta.
pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
```

**Comment by salah-ghanim** [comment]
this is an issue for google-maps-ios-utils please open a ticket there if the issue persists.
