### ISSUE TITLE
Press on a Marker - fires press event for another marker if exact same position

### ISSUE THREAD

**Issue by DenysMoro** [react-native-maps/react-native-maps#4854]
### Summary

Conditions:
Image marker - white circle
Note marker - green rectangle

We have 400+ Markers on the Map. 200 for Images and 200 for Notes for example. Sometimes, Images and Notes could have exact same coordinates and Press event starts to work incorrectly at this point

Basically I found two bugs:
1. Click on Note Marker (green) - click event for Image Marker fires instead of Note Marker (see video below)
2. Click on Note Marker - event for Note Marker fires -> Alert is displayed (in my example) -> Close Alert -> you will see Image Marker over Note Marker. Feels like `zIndex` was changed, but it is not.

https://github.com/react-native-maps/react-native-maps/assets/77282657/abfa5108-2df7-43e7-9db7-9d20477081b4

### Reproducible sample code

```TSX
I've created small repo - https://github.com/DenysMoro/expo-react-native-maps-marker-press-collision
```

### Steps to reproduce

1. Load reproducible example
2. Try to press different Note markers and pay attention on Alert text

### Expected result

1. Each click on a Note marker - should fire Note marker event without changing `zIndex` for rest markers

### Actual result

1. Click on Note Marker (green) - click event for Image Marker fires instead of Note Marker (see video below)
2. Click on Note Marker - event for Note Marker fires -> Alert is displayed (in my example) -> Close Alert -> you will see Image Marker over Note Marker. Feels like `zIndex` was changed, but it is not.

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.71.13

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 13 Pro, any

### Additional information

Feels like Map component has own logic of `zIndex` for each element while drawing markers on it. Or maybe not logic, but queue. And maybe last items taking more priority for press events then...

**Comment by DenysMoro** [comment]
Still there

**Comment by liamnoroian** [comment]
Facing a similar issue. Attempted to implement debouncing for onPress to no avail. Looking for a solution.

**Comment by incom-app-ru** [comment]
I managed to solve the problem. You need to delete style={{zIndex: }} for <Marker/>
