### ISSUE TITLE
EXC_BAD_ACCESS in iOS simulator when onMapReady receives null

### ISSUE THREAD

**Issue by kueda** [react-native-maps/react-native-maps#4862]
### Summary

When <MapView>'s `onMapReady` prop receives a value or `null` or `undefined`, the app crashes with a `EXC_BAD_ACCESS` error.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{width: "100%", height: "100%"}}
      onMapReady={null}
    />
  );
}
```

### Steps to reproduce

Set `onMapReady={null}` on any `<MapView />` and run it in an iOS simulator.

### Expected result

A component that receives an optional prop with a null value should behave the same as if it didn't receive the prop at all, e.g. `<MapView />` should be the same as <MapView onMapReady={null} />.

### Actual result

<img width="741" alt="Screenshot 2023-10-10 at 5 18 58 PM" src="https://github.com/react-native-maps/react-native-maps/assets/22691/bc1f8634-2576-4085-aab6-3651f7868327">

The app crashes and the simulator shows a popup saying "APP NAME quit unexpectedly".

### React Native Maps Version

1.8.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.70.9

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 (Simulator; iOS 16.4)

**Comment by salah-ghanim** [comment]
@kueda I can't reproduce the issue under the following environment 

```
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /var/folders/9x/9xzxgmhn75q66kr2x3n691hw0000gn/T/yarn--1700253494780-0.7101434196191923/node
    Yarn: 1.22.19 - /var/folders/9x/9xzxgmhn75q66kr2x3n691hw0000gn/T/yarn--1700253494780-0.7101434196191923/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```


this is the App.tsx code
```JSX

import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return <MapView style={{width: '100%', height: '100%'}} />;
}

```

**Comment by kueda** [comment]
@salah-ghanim, try adding `onMapReady={null}`, e.g. change your `App.tsx` to

```tsx

import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return <MapView style={{width: '100%', height: '100%'}} onMapReady={null} />;
}
```

**Comment by salah-ghanim** [comment]
@kueda you're not supposed to pass null as the typing indicates ... if you have typing setup correctly this is the error message you will receive from your IDE

`TS2322: Type 'null' is not assignable to type '((event?: NativeSyntheticEvent<{}> | undefined) => void) | undefined'.`


please check for null before passing the prop instead of expecting the library to handle something it specifically is typed not to handle.
