### ISSUE TITLE
Build fails when use_frameworks! enabled?

### ISSUE THREAD

**Issue by endrits079** [react-native-maps/react-native-maps#4868]
### Summary

I added firebase to my app, firebase requires use_frameworks,
Since I had react-native-maps installed before installing firebase I had installed Google-Maps-IOS-Utils with Cocoapods
`pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`

After adding firebase I removed it from the Podfile and installed it manually as guided in 
https://github.com/googlemaps/google-maps-ios-utils/blob/b721e95a500d0c9a4fd93738e83fc86c2a57ac89/Swift.md

1.I added a new group with the name Google-Maps-iOS-Utils in my project,
2.I downloaded the project locally from the fork https://github.com/monholm/google-maps-ios-utils/tree/feat/support-apple-silicon (I also tried from the main repo.)
3. In the newly created Group, I select Add files to  "MyProjectName"
4. Unchecked Copy items if needed, selected my project name target in add to targets, and selected Create Groups.
And selected all the folders inside the src folder.
5. Edited GMUMarkerClustering.h inside the group that I created Google-Maps-iOS-Utils/Clusters to use relative paths like this:
```
#import "GMUCluster.h"
#import "GMUClusterItem.h"
#import "GMUClusterManager.h"
#import "GMUDefaultClusterIconGenerator.h"
#import "GMUDefaultClusterRenderer.h"
#import "GMUGridBasedClusterAlgorithm.h"
#import "GMUNonHierarchicalDistanceBasedAlgorithm.h"
#import "GMUStaticCluster.h"

#import "GQTPointQuadTree.h"
```

6.I added a Header.h as group I selected the group with my project name and in targets I selected the target with my project name  and  added this content: 
```
#ifndef Header_h
#define Header_h
#import "GMUMarkerClustering.h"
#endif /* Header_h */
```

I did pod deintegrate && pod install in /ios after all these changes.
I tried to change 
CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
I checked for use header maps and it's already YES

I cleaned the project and when I try to build it I still get this error

Showing Recent Errors Only
/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:10:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:11:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h:10:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager_Internal': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h:10:9: Include of non-modular header inside framework module 'React.RCTActionSheetManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAlertManager.h:10:9: Include of non-modular header inside framework module 'React.RCTAlertManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAlertManager.h:11:9: Include of non-modular header inside framework module 'React.RCTAlertManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTInvalidating.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppearance.h:10:9: Include of non-modular header inside framework module 'React.RCTAppearance': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppearance.h:11:9: Include of non-modular header inside framework module 'React.RCTAppearance': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppState.h:8:9: Include of non-modular header inside framework module 'React.RCTAppState': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTClipboard.h:8:9: Include of non-modular header inside framework module 'React.RCTClipboard': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h:10:9: Include of non-modular header inside framework module 'React.RCTDeviceInfo': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h:8:9: Include of non-modular header inside framework module 'React.RCTDevLoadingView': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:10:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:11:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:12:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:8:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:9:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:10:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:11:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTInitializing.h'

too many errors emitted, stopping now

/path/to/project/node_modules/react-native-maps/ios/AirMaps/AIRMapWMSTileManager.m:13:9: Could not build module 'React'

This is my Podfile

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled


rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

target 'ProjectName' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ProjectNameTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

### Reproducible sample code

```TSX
Error is build related
```

### Steps to reproduce

Add    use_frameworks! :linkage => :static in Podfile and reinstall pods

### Expected result

My project builds and runs successfully

### Actual result

I get build errors

Showing Recent Errors Only
/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:10:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:11:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h:10:9: Include of non-modular header inside framework module 'React.RCTAccessibilityManager_Internal': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h:10:9: Include of non-modular header inside framework module 'React.RCTActionSheetManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAlertManager.h:10:9: Include of non-modular header inside framework module 'React.RCTAlertManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAlertManager.h:11:9: Include of non-modular header inside framework module 'React.RCTAlertManager': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTInvalidating.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppearance.h:10:9: Include of non-modular header inside framework module 'React.RCTAppearance': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppearance.h:11:9: Include of non-modular header inside framework module 'React.RCTAppearance': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTAppState.h:8:9: Include of non-modular header inside framework module 'React.RCTAppState': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTClipboard.h:8:9: Include of non-modular header inside framework module 'React.RCTClipboard': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h:10:9: Include of non-modular header inside framework module 'React.RCTDeviceInfo': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h:8:9: Include of non-modular header inside framework module 'React.RCTDevLoadingView': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:10:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:11:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevMenu.h:12:9: Include of non-modular header inside framework module 'React.RCTDevMenu': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:8:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:9:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:10:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/path/to/project/node_modules/react-native/React/CoreModules/RCTDevSettings.h:11:9: Include of non-modular header inside framework module 'React.RCTDevSettings': '/path/to/project/ios/Pods/Headers/Public/React-Core/React/RCTInitializing.h'

too many errors emitted, stopping now

/path/to/project/node_modules/react-native-maps/ios/AirMaps/AIRMapWMSTileManager.m:13:9: Could not build module 'React'

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.71.11

### What version of Expo are you using?

Not using Expo

### Device(s)

Build error not device specific

**Comment by median299** [comment]
I'm facing a similar error with React native map

react-native-maps
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:10:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:11:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h:10:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager_Internal': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h:10:9 Include of non-modular header inside framework module 'React.RCTActionSheetManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h:10:9 Include of non-modular header inside framework module 'React.RCTAlertManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h:11:9 Include of non-modular header inside framework module 'React.RCTAlertManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTInvalidating.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h:10:9 Include of non-modular header inside framework module 'React.RCTAppearance': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h:11:9 Include of non-modular header inside framework module 'React.RCTAppearance': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppState.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppState.h:8:9 Include of non-modular header inside framework module 'React.RCTAppState': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTClipboard.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTClipboard.h:8:9 Include of non-modular header inside framework module 'React.RCTClipboard': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h:10:9 Include of non-modular header inside framework module 'React.RCTDeviceInfo': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h:8:9 Include of non-modular header inside framework module 'React.RCTDevLoadingView': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:10:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:11:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:12:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h
/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:8:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:9:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:10:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'

/Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:11:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTInitializing.h'


did you find any solution?

**Comment by endrits079** [comment]
> I'm facing a similar error with React native map
> 
> react-native-maps /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:10:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:11:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h:10:9 Include of non-modular header inside framework module 'React.RCTAccessibilityManager_Internal': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.h:10:9 Include of non-modular header inside framework module 'React.RCTActionSheetManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h:10:9 Include of non-modular header inside framework module 'React.RCTAlertManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAlertManager.h:11:9 Include of non-modular header inside framework module 'React.RCTAlertManager': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTInvalidating.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h:10:9 Include of non-modular header inside framework module 'React.RCTAppearance': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppearance.h:11:9 Include of non-modular header inside framework module 'React.RCTAppearance': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppState.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTAppState.h:8:9 Include of non-modular header inside framework module 'React.RCTAppState': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTClipboard.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTClipboard.h:8:9 Include of non-modular header inside framework module 'React.RCTClipboard': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDeviceInfo.h:10:9 Include of non-modular header inside framework module 'React.RCTDeviceInfo': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevLoadingView.h:8:9 Include of non-modular header inside framework module 'React.RCTDevLoadingView': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:10:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:11:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevMenu.h:12:9 Include of non-modular header inside framework module 'React.RCTDevMenu': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:8:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTBridge.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:9:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTDefines.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:10:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h'
> 
> /Users/rawandmajeed/HydeProject/MobileApp/node_modules/react-native/React/CoreModules/RCTDevSettings.h:11:9 Include of non-modular header inside framework module 'React.RCTDevSettings': '/Users/rawandmajeed/HydeProject/MobileApp/ios/Pods/Headers/Public/React-Core/React/RCTInitializing.h'
> 
> did you find any solution?

Not yet unfortunately, 
I needed to enable use_frameworks for firebase because I was planning to use it for push notifications, after like 2 days I couldn't find a solution I might just go with Onesignal for now and remove use_frameworks if no solution is provided

**Comment by recallwei** [comment]
Move them below use_native_modules!, that solve my problem.
```
target 'ProjectName' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # React Native Maps dependencies
  # The following line is only needed if building on an Apple silicon Mac without rosetta.
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  target 'ProjectNameTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```
