### ISSUE TITLE
Get Map rotation

### ISSUE THREAD

**Issue by the-simian** [react-native-maps/react-native-maps#487]
When you pinch and rotate, is there a way to read the global map rotation?

**Comment by fmelp** [comment]
having the same issue here. @the-simian did you manage to figure it out? thanks!

**Comment by the-simian** [comment]
Nope. To my understanding this is simply unsupported atm.

**Comment by willdavidow** [comment]
👍 

This, and being able to set the map rotation, are two very-needed features that seem to be getting actively ignored (based on scouring the open and closed issues here on GitHub)...

**Comment by raihanrazi** [comment]
This is a much needed feature

**Comment by the-simian** [comment]
I agree this is very impotant

**Comment by CherryNerd** [comment]
Any updates on this feature?

**Comment by breadadams** [comment]
> and being able to set the map rotation

@willdavidow according to [MapView docs](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods) this is now possible via `animateToBearing`.

Now we just need to be able to **listen** for updates to the canvas' rotation, those made by the user with a 2 finger spin gesture.

**Comment by kenobi91** [comment]
@breadadamscan you explain this in more detail, I also need some way to get an angle of map rotation and at the moment there isn't one. animateToBearing is no use to me because I need to get angle not to set one.

**Comment by cklinx** [comment]
+1 Need it too

**Comment by its-wufu** [comment]
If you have a ref to the map you can read the rotation using the camera:
```
mapRef.current.getCamera().then(camera => {
	if (camera.heading === 0) // is north
});
```
But my problem is that I don't know where to put this. There is no map event that gets triggered on rotation, right? `onRegionChangeComplete` seems to just fire, when the position changes, not when the camera heading changes.

**Comment by edenhean** [comment]
> 
> 
> If you have a ref to the map you can read the rotation using the camera:
> 
> ```
> mapRef.current.getCamera().then(camera => {
> 	if (camera.heading === 0) // is north
> });
> ```
> 
> But my problem is that I don't know where to put this. There is no map event that gets triggered on rotation, right? `onRegionChangeComplete` seems to just fire, when the position changes, not when the camera heading changes.

Does have anyone a solution to set camera of map always to north?

**Comment by zhigang1992** [comment]
I've add a useEffect + setInterval to get the rotation every 3s. Better than nothing

**Comment by juroMin** [comment]
onRegionChange={() => {
            this.refs.mapView.getCamera()
              .then((info) => {
               console.log('info', info.heading);
              });
          }}

`heading` value determines the rotation angle. But be aware there is a lot of iteration going on.

**Comment by OMeyer973** [comment]
functional component version of this answer: https://github.com/react-native-maps/react-native-maps/issues/487#issuecomment-642596531

```jsx
import React, {  useRef } from "react";
import MapView, { PROVIDER_GOOGLE } from "react-native-maps";

export const Map = ({ }) => {

  const mapViewRef = useRef(null);

  return (
    <MapView
      provider={PROVIDER_GOOGLE}
      ref={mapViewRef}
      style={{ width: "100%", height: "100%" }}
      onRegionChange={() => {
        console.log(
          mapViewRef?.current?.getCamera().then((info) => {
            console.log("info", info);
          })
        );
      }}
    />
  );
};
```

**Comment by Lucstay11** [comment]
To finally close the question. If you want to put the map in 3D without moving your 2 fingers on the screen! You need to change the pitch value of the map object. From 65.5 (in 3D) to 0 (more than 3D).

You can view this value each time the map region changes like this:

`onRegionChange={() => {
        console.log(
          map?.current?.getCamera().then((info) => {
            console.log("info", info.pitch);
          })
        );
      }}`
