### ISSUE TITLE
MapView onPress is not firing

### ISSUE THREAD

**Issue by zlobizlobi** [react-native-maps/react-native-maps#4872]
### Summary

Whenever I press anywhere on my MapView, except for my Markers (they work), the onPress handler doesn't fire. I've tried using `onPressIn` but this causes state changes in my application also in case I want to zoom, so this is not very desired. 

Im using expo 49. 

### Reproducible sample code

```TSX
<Map
                provider={PROVIDER_GOOGLE}
                region={{
                    latitudeDelta: searchLocation?.latitudeDelta,
                    longitudeDelta: searchLocation?.longitudeDelta,
                    latitude: searchLocation?.latitude,
                    longitude: searchLocation?.longitude,
                }}
                followsUserLocation
                showsUserLocation
                userLocationUpdateInterval={1500}
                onRegionChangeComplete={(region, { isGesture }) => {
                    if (isGesture) {
                        updateSearchCoordinates(region)
                    }
                }}
                paddingAdjustmentBehavior="never"
                rotateEnabled={false}
                zoomTapEnabled={false}
                onPress={() => setCurrentActivity(undefined)}
            >
                {activities?.map((activity, index) => (
                    <MapMarker
                        key={activity.id}
                        lon={activity.lon}
                        lat={activity.lat}
                        zIndex={index}
                        onPress={() => 
                            setCurrentActivity(activity)
                        }
                    >
                        {activity.id === currentActivity?.id ? (
                            <MarkerSelectedSvg />
                        ) : (
                            <MarkerSvg />
                        )}
                    </MapMarker>
                ))}
            </Map>
```

### Steps to reproduce

1. Copy the above code. 
2. Create a JSX Map component from it in expo 49.
3. Try to log something inside `onPress`.

### Expected result

You'd see a log. 

### Actual result

You don't see a log. 

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

IPhone 14 Pro, Iphone 11 Pro

**Comment by williampd** [comment]
Please check [#1689](https://github.com/react-native-maps/react-native-maps/issues/1689#issuecomment-519252994)

**Comment by zlobizlobi** [comment]
@williampd - The issue was actually on my side. It was wrapped in `tamagui`'s styled function and wasn't passing on the onPress prop to the MapView unfortunately.
