### ISSUE TITLE
Bug: map moves down continuously

### ISSUE THREAD

**Issue by taeh98** [react-native-maps/react-native-maps#4876]
### Summary

When using `region` in state, `onRegionChangeComplete` to set `region`, and with a high zoom level, the map moves down continuously without interaction. `onRegionChangeComplete` is continuously called, in a feedback loop.

https://github.com/react-native-maps/react-native-maps/assets/28008958/8c573f49-1e92-4fd4-bb09-d09847bba65f

### Reproducible sample code

https://snack.expo.dev/E82w-0iV1

### Steps to reproduce

Run the snack. Upon opening, the map will immediately move downwards without user interaction.

### Expected result

Map would remain stationary unless interacted with by the user. The `region` value in state set when user interacted and changed it (drag, zoom, etc) and not otherwise. `onRegionChangeComplete` would be used to detect these changes and update them in state. This would be the same as the region in the `MapView` already, so would just bring the two into sync and not lead to further changes.

### Actual result

At a high zoom level, the map moves downwards continuously. `onRegionChangeComplete` triggers itself in a feedback loop despite there being no user interaction.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

Samsung Galaxy S22

### Additional information

`"expo": "^49.0.16",`

My use case requires users to centre the `MapView` on a position they press on the map with `onPress`. Just using `onPanDrag` and `onPress` to update `region` value in state does not account for the user pressing zoom control buttons, so `onRegionChangeComplete` is needed. For example, if you only used `onPanDrag` and `onPress` and the user changed zoom level with zoom control buttons, the lat long deltas (=> zoom) would not be changed in the `region` in state to reflect the change in the `MapView`. If the user then pressed elsewhere on the map, the lat long deltas and zoom would be reset to the values in state, though with the new lat/long region centrepoint, but this would not reflect the actual region that had beein in the `MapView`.

**Comment by mateki0** [comment]
You can fix it with this short if check, however it will work only on Google Maps:

```jsx
onRegionChangeComplete={(newRegion: Region, gesture): void => {
            if(!gesture.isGesture) {
              return
            }
            setRegion(newRegion)
          }
```

Source: https://github.com/react-native-maps/react-native-maps/issues/846#issuecomment-1210079461

**Comment by chhornponleu** [comment]
Not sure if it the issue I used to face. Try adding this prop might help
```jsx
<MapView
   paddingAdjustmentBehavior="never"
  ...
/>
```

**Comment by alistertb** [comment]
The solution at https://github.com/react-native-maps/react-native-maps/issues/846#issuecomment-1210079461 only works if you're not interested in animating the region since it rejects any region changes that aren't caused by a gesture

For anyone else who runs into this problem when using eg. `animateToRegion()`, I found that this works for me:

```TSX
const mapRef = useRef<MapView>(null);

const handleRegionChangeComplete = async (newRegion: Region) => {
    const boundingBoxOld = mapRef.current!.boundingBoxForRegion(region);
    const positionOld = await mapRef.current!.pointForCoordinate(boundingBoxOld.northEast);

    const boundingBoxNew = mapRef.current!.boundingBoxForRegion(newRegion);
    const positionNew = await mapRef.current!.pointForCoordinate(boundingBoxNew.northEast);

    const epsilon = 5;
    const distance = Math.sqrt(Math.pow(positionNew.x - positionOld.x, 2) + Math.pow(positionNew.y - positionOld.y, 2));
    if (distance < epsilon) {
      return;
    }

    setRegion(newRegion);
  };

// ...

<MapView
  ref={mapRef}
  onRegionChangeComplete={handleRegionChangeComplete}
  // ...
/>
```

Essentially it only commits the new region if it shifted by a relatively large distance (tweak `epsilon` to taste)
