### ISSUE TITLE
onPadDrag event doesnt work on IOS (even with scrollenabled = false)

### ISSUE THREAD

**Issue by mantmartini** [react-native-maps/react-native-maps#4890]
### Summary

The onPanDrag event works as expected on Android, but it doesn't get triggered on iOS. I've set the scrollEnabled property to false as per the documentation. Here's my code:

### Reproducible sample code

```TSX
const handleMapPanDrag = event => {
    console.log("handleMapPanDrag")
}

  <MapView
          {...panResponder.panHandlers}
          ref={mapRef}
          onPress={handleMapPress}
          onPanDrag={handleMapPanDrag}
          onRegionChange={handleMapPanRelease}
          scrollEnabled={false}
          provider={PROVIDER_GOOGLE}
          style={styles.map}
    > {...}
        </MapView>
```

### Steps to reproduce

.

### Expected result

"I expected the onPanDrag event to function similarly on both Android and iOS platforms. With scrollEnabled set to false, I anticipated the map to disable scrolling and trigger the onPanDrag event on iOS, similar to its behavior on Android."

### Actual result

The onPanDrag event doesn't get triggered on iOS.

### React Native Maps Version

1.7,1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Iphone emulator and physical devices. IOS 16.6 and IOS 17

**Comment by jan-kozinski** [comment]
Hi, I used our code sample on physical IP 14 Pro w/ ios17, on IP 15 simulator w/ ios 17 and on IP 14 simulator w/ ios 16. 
The onPanDrag function triggers and fires without issues, regardless of `scrollEnabled` value or wheter I use google maps or apple maps as the provider.

https://github.com/react-native-maps/react-native-maps/assets/68508047/d019e039-76ef-45a5-877d-aa827509b519
