### ISSUE TITLE
Overlaying a modal causes Google Maps on Android to load tiles very slowly

### ISSUE THREAD

**Issue by eeston** [react-native-maps/react-native-maps#4893]
### Summary

Bit of a weird one tbh and I'm totally stumped as to why this issue would occur :/ 

Basically I have a modal that overlays a map view while the map is loading tiles, downloading location points, & rendering pins. On iOS (both Apple Maps & Google Maps) this works pretty well. On Android (with Google Maps), for some reason this setup causes tiles to load _really_ slowly. I have tested this on an emulator and on a device. Same issue on both.

Video attached...
- issue occurs a bunch of times at the begining
- at 54s I comment out the overlay and refresh a bunch of times to show it loading fine without the modal.

https://github.com/react-native-maps/react-native-maps/assets/18663222/a59bb3b9-4de3-448f-9df3-10695a94588a

Link to repo with issue...
https://github.com/eeston/rn-map-issue-reproduction

### Reproducible sample code

```TSX
import { Text, Modal, StyleSheet, View } from "react-native";
import MapView from "react-native-maps";

export default function App() {

  // toggle this to show/hide the modal & reproduce the issue
  const showOverlay = true;

  return (
    <View style={styles.container}>
      <Modal transparent={true} visible={showOverlay}>
        <Text style={styles.loadingOverlay}>
          Modal causing slow map render...
        </Text>
      </Modal>
      <MapView
        initialRegion={{
          latitude: 57,
          longitude: -4,
          latitudeDelta: 4,
          longitudeDelta: 4,
        }}
        mapType="terrain"
        provider="google"
        style={styles.map}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    width: "100%",
    height: "100%",
  },
  loadingOverlay: {
    backgroundColor: "#rgba(0, 0, 0, 0.5)",
    width: 100,
    height: 100,
    zIndex: 100,
  },
});
```

### Steps to reproduce

Reproduction isn't 100% so you may have to refresh a few times. Video attached to demonstrate issue...

- run code from sample or repo
- if issue isn't shown, try refreshing a few times (pressing `r` in the terminal)

### Expected result

Map tiles load properly

### Actual result

Map tiles load extremely slowly

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

Emulated on Pixel3a, Tested on device Pixel 4a

### Additional information

I'm on expo SKD49 (not available from dropdown)

**Comment by eeston** [comment]
Edit: Simplified the reproducible sample code. Diff here... https://github.com/eeston/rn-map-issue-reproduction/commit/95f82005db2da21a6a9ffb5e9cf89cf9695d459c

**Comment by salah-ghanim** [comment]
@eeston thanks for submitting this bug report.

this seems to me to be out of scope for this library, specifically transparent Modal in RN can be problematic in terms of calculating what's underneath it and it's what could be causing the problem (you mentioned that without it the loading works fine).

have you considered using an external modal lib, for example from react-native-navigation ? 
https://wix.github.io/react-native-navigation/docs/modal

**Comment by eeston** [comment]
@salah-ghanim thanks for the info...I did wonder if it was a modal issue but thought I'd double check here.

I'll check out the other libs 🙏
