### ISSUE TITLE
apiKey not found on production build Android

### ISSUE THREAD

**Issue by elenarosso** [react-native-maps/react-native-maps#4895]
### Summary

I have an error in my map on android , once I generated the keys and put them on my app.json, I compiled it and when I try to open it on my expoGo simulator the error returns: apiKey not found

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

My packages :

"react": "18.2.0",
"react-native": "0.71.14",
"expo": "^48.0.0",
"react-native-maps": "1.3.2"

KEY :

I generated a key and as an app limitation I put ANDROID APP. I entered the package name and also the
SHA-1 certified fingerprint (taken from expo credential). In the API restrictions however I left the choice: Do not limit the key

In my app.json :

{
 "expo": {
   "android": {
     "config": {
       "googleMaps": {
         "apiKey": "my-api-key"
        }
      }
    },
  }
}

### Expected result

Map showing correctly

### Actual result

<img width="506" alt="Screenshot 2023-11-21 alle 10 00 47" src="https://github.com/react-native-maps/react-native-maps/assets/112164113/9ed209a5-a5ea-4e0a-8259-2632280c69b1">

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.14

### What version of Expo are you using?

SDK 48

### Device(s)

any android advices

**Comment by salah-ghanim** [comment]
@elenarosso have you followed the expo documentations ? 
https://docs.expo.dev/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android

https://docs.expo.dev/versions/latest/sdk/map-view/

they have specific set of steps you need to follow if you want to publish your app to google play / release apk.

**Comment by haseebnk** [comment]
same issue with me

**Comment by osain-az** [comment]
@salah-ghanim  did you find a solution  ? 

i have the same issue. i have followed all steps from expo

**Comment by haseebnk** [comment]
React-native-svg issue check for this package re install or install this
again

**Comment by osain-az** [comment]
@elenarosso  My issue was that eas was ignoring my .env file so  the  API key was  not build.  I was hard for me to notice because when I build with eas and start it local  and console.log I can see the key. 

The solution is to add your .env variable to your expo dashboard if your are building with eas.

**Comment by maxmh2003** [comment]
@osain-az 
did you use app.json or app.config.js?

**Comment by osain-az** [comment]
> [@osain-az](https://github.com/osain-az) did you use app.json or app.config.js?

I use both of them. I added the  constant to app.json  then variables in app.config.js
`
export default ({ config }) => ({
    ...config,
    android: {
      ...config.android,
      config: {
        ...config.android.config,
        googleMaps: {
          apiKey: process.env.GOOGLE_MAPS_API_KEY ,
        },
      },
      ios: {
        ...config.ios,
        config: {
          ...config.ios.config,
          googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ,
        },
      },
    
  },

    extra: {
      ...config.extra,
      googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ,
    },
  });
`
but if you want to use eas build remotely then is better to login to expo dev account add the environment variable in for the project

**Comment by GeorgeKumoHq** [comment]
Any solution for this issue. Im using expo. I did prebuild and still facing the issue.
