### ISSUE TITLE
Android only: intialRegion with latitude and longitude properties being string triggers crash

### ISSUE THREAD

**Issue by GBlackwell1** [react-native-maps/react-native-maps#4903]
### Summary

When working with MapView recently, I was using JS toString method to convert values because I was using a map with a string key to get pertinent information about regions. I was testing on my iOS device and it was working perfectly, as well as map animations using animateCamera using numbers for longitudes and latitudes and my initialRegion values set using strings instead. Afterwards a coworker tested on an Android device, and it lead to an immediate crash with no stack trace.

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps'

export default function App() {
  return (
    <MapView
      initialRegion={{latitude:'8',latitudeDelta:'8',longitude:'8',longitudeDelta:'8'}} 
    />
  );
}
```

### Steps to reproduce

Copy and paste the above code and run on iOS using expo. Do the same on Android to receive an immediate  crash upon render.

### Expected result

Expected to open roughly to Nigeria as the map's initial region.
<img width="310" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/76234706/cd5de905-9478-43d3-af0d-3ddff47d15cc">

### Actual result

Immediate crash and return to expo's home screen.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

Google Pixel 3 [emulator], Google Pixel 7

### Additional information

**EXPO version is 49.0.21, no option to input SDK 49 so I put 48**. I know you guys have this listed on your documentation via example that initialRegion is supposed to expect an object with 4 fields having a value of number, but it is an easy oversight, perhaps a warning or an additional emphasis made on the potential crash. Thanks!

**Comment by salah-ghanim** [comment]
@GBlackwell1

Thank you for your report. We appreciate your interest in react-native-maps. As an open-source project, our resources are limited, and we rely on adherence to our documentation and IDE type warnings  to efficiently manage genuine issues. We encourage you to review these resources to ensure correct usage of the library. If you find any bugs while following these guidelines, please let us know, and we'll be more than happy to assist.
