### ISSUE TITLE
Timestamp returned from onUserLocationChange isn't relative to Unix Epoch on IOS map (like documentation says)

### ISSUE THREAD

**Issue by thegunner686** [react-native-maps/react-native-maps#4908]
### Summary

The [documentation](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md#types) says the timestamp returned in the `Location` object from the `onUserLocationChange` event is "Milliseconds since Unix epoch", but this isn't the case for the IOS map. The line of code below shows its using [`timeIntervalSinceReferenceDate`](https://developer.apple.com/documentation/foundation/date/1780268-timeintervalsincereferencedate), not [`timeIntervalSince1970`](https://developer.apple.com/documentation/foundation/date/1779963-timeintervalsince1970) which is the UNIX epoch:

[@"timestamp": @(location.location.timestamp.timeIntervalSinceReferenceDate * 1000),](https://github.com/react-native-maps/react-native-maps/blame/edfac8ae89f6f0e80e5c93604df02124b3b844ae/ios/AirMaps/AIRMapManager.m#L918)

### Reproducible sample code

```TSX
import React from "react";
import MapView from "react-native-maps";

export default function App() {
  const onUserLocationChange = ({ nativeEvent }) => {
    const { timestamp } = nativeEvent.coordinate;
    const date = new Date(timestamp);
    console.log(date); // gives back a date in 1992 not 2023
  };

  return (
    <MapView
      style={{ flex: 1 }}
      showsUserLocation
      onUserLocationChange={onUserLocationChange}
    />
  );
}
```

### Steps to reproduce

- setup a blank expo or react-native project
- install react-native-maps and go through the installation instructions
- use the minimal reproducible code from above
- use default IOS map on an iPhone simulator or real device
- when simulating location or walking around with the app & map open, you should see the date printed to the console

### Expected result

Expected the date from `new Date(timestamp)` to be current, i.e. be in the year 2023 because the assumption was that the timestamp was in milli since unix epoch.

### Actual result

The expected date from `new Date(timestamp)` is in 1992, since the actual timestamp returned gives the interval from 2001 until now, which is a 22 year difference, so when when converting to the unix epoch we get 1970+22 = 1992.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 15 Pro Max, ios 17.2

### Additional information

Expo version is actually 49, but there's not an option for that in the template.

**Comment by jan-kozinski** [comment]
Hi @thegunner686 ! Thank you for reporting this. I've put up a PR that fixes the issue https://github.com/react-native-maps/react-native-maps/pull/4911

**Comment by salah-ghanim** [comment]
@thegunner686 thanks for reporting :)

@jan-kozinski awesome job with the quick fix, already merged 🚀
