### ISSUE TITLE
iOS - onTouchStart not always fired for the second finger

### ISSUE THREAD

**Issue by lorenzomilesi** [react-native-maps/react-native-maps#4919]
### Summary

I'm trying to distinguish the case in which the user wants to draw on the map, from the case in which he wants to zoom.
So, onPanDrag is handling the drawing action, which I want to stop/prevent/cancel if the user uses a second finger on the map, catching it with the onTouchStart event. On Android, it seems working fine, on iOS however, **if the two touches are close to each other temporally**, the second event does not trigger onTouchStart and the onPanDrag event contains the coordinates resulting from the average of the position coordinates of the individual fingers, as if there was only one "centered" touch.

### Reproducible sample code

```TSX
import React from 'react';
import { GestureResponderEvent } from 'react-native';
import MapView from 'react-native-maps';

export const PlaygroundScreen = () => {
  const onTouchStart = (event: GestureResponderEvent) => {
    console.log('[debug] onTouchStart:', event?.nativeEvent);
    if (event?.nativeEvent?.touches?.length > 1) {
      // do stuff
    }
  };

  return (
    <MapView
      style={{ flex: 1 }}
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.01,
        longitudeDelta: 0.01,
      }}
      onTouchStart={onTouchStart}
    />
  );
};
```

### Steps to reproduce

Simply touch with two fingers the map and watch the logs

### Expected result

onTouchStart to be fired two times, once per finger, the second one passing the following `event.nativeEvent` example object
`{
  changedTouches: Array(1);
  identifier: 2;
  locationX: 166.3333282470703;
  locationY: 395.3333282470703;
  pageX: 166.3333282470703;
  pageY: 508.3333282470703;
  target: 643;
  timestamp: 11394361.391958334;
  touches: Array(2);
}
`

### Actual result

onTouchStart fired just once with the following `event.nativeEvent` object
`{
  changedTouches: Array(1);
  identifier: 1;
  locationX: 166.3333282470703;
  locationY: 395.3333282470703;
  pageX: 166.3333282470703;
  pageY: 508.3333282470703;
  target: 643;
  timestamp: 11394361.391958334;
  touches: Array(1);
}`

### React Native Maps Version

1.8.4

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.7

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 12

### Additional information

Just one more note: the expected result corresponds to what I get if instead of MapView I use react native's View

**Comment by salah-ghanim** [comment]
@lorenzomilesi I see in AIRMapManager.m in view initialisation there is the code for Gesture recognition.

I can't think of a simple solution for this issue, but I found the following method: shouldRecognizeSimultaneouslyWith

https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer?language=objc

you might be able to have both gestures active at the same time and by doing so receive the tap touch event for both fingers...

but you need to test

**Comment by jan-kozinski** [comment]
There is only one touch event fired on Apple maps. Enabling Google Maps allows us to detect multiple touches. I suppose it might be related to the AIRGoogleMap.m method `overrideGestureRecognizersForView` or `extendedMapGestureHandler`

**Comment by jan-kozinski** [comment]
We're working to find a solution for you @lorenzomilesi , in the mean time you can try adding react-native-gesture-handler and defining the isPinch function as in https://github.com/react-native-maps/react-native-maps/issues/4247#issuecomment-1283569058

**Comment by lorenzomilesi** [comment]
Thanks @jan-kozinski , hopefully I will find a moment the next week to try out something and let you know

**Comment by jan-kozinski** [comment]
As an alternative you can monkey-patch the library to add `                  @"numberOfTouches": @(recognizer.numberOfTouches)` to line 713 in AIRMapManager.m and change `onTouchStart` to `onPanDrag={e =>  && setIsDrawing(e.nativeEvent.numberOfTouches == 1)`
From my testing, it seems that the numberOfTouches will always detect the other finger
<img width="740" alt="Screenshot 2023-12-22 at 16 46 05" src="https://github.com/react-native-maps/react-native-maps/assets/68508047/4281c2d1-6745-437a-ad3d-50adfd1148ca">

**Comment by lorenzomilesi** [comment]
> As an alternative you can monkey-patch the library to add ` @"numberOfTouches": @(recognizer.numberOfTouches)` to line 713 in AIRMapManager.m and change `onTouchStart` in your react component to `onPanDrag={e => && setIsDrawing(e.nativeEvent.numberOfTouches == 1)` From my testing, it seems that the numberOfTouches will always detect the other finger <img alt="Screenshot 2023-12-22 at 16 46 05" width="740" src="https://private-user-images.githubusercontent.com/68508047/292523326-4281c2d1-6745-437a-ad3d-50adfd1148ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjA0MDksIm5iZiI6MTcwMzI2MDEwOSwicGF0aCI6Ii82ODUwODA0Ny8yOTI1MjMzMjYtNDI4MWMyZDEtNjc0NS00MzdhLWFkM2QtNTBhZGZkMTE0OGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE1NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNTk5OWVhZWQwZDBmN2Q0NGVlZjhkYTA4NWU3YWY5Zjc5N2YzNzU0NGY5YTExY2ZkNjlmYWUyOWMyNjBmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_jIifT4fFa0UU78vuenM2siZE7Azb5KndZSFojh0Ig">

I can confirm this could be a possibile workaround. Thank you!

**Comment by salah-ghanim** [comment]
@jan-kozinski can you please create a pull request with numberOfTouches as an extra to the event ? maybe you can do it for all iOS events ?

**Comment by jan-kozinski** [comment]
unfortunately other events described under "Gesture Recognizer Handlers" pragma do not work well with number of touches. Either they don't fire at all when using more figners, or they don't recognize the additional touches. I'll create a PR that adds number of touches to the onPanDrag. Also @salah-ghanim WDYT about me adding onPanDragStart and onPanDragEnd events?

**Comment by Jin-seop** [comment]
In some cases, you can zoom in  or stop moving with just one finger if you touch quickly.
