### ISSUE TITLE
Problems loading MapView.

### ISSUE THREAD

**Issue by maxform-labs** [react-native-maps/react-native-maps#4923]
### Summary

Problems loading MapView.

Error: Unsupported top level event type "topOnMapReady" dispatched, js engine: hermes
Error: Unsupported top level event type "topOnMapLoaded" dispatched, js engine: hermes

"react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-maps": "1.6.0",

When building on Android, the following error occurs. Please tell me the solution.

 Error: Unsupported top level event type "topOnMapLoaded" dispatched, js engine: hermes

### Reproducible sample code

```TSX
<MapView
      provider={
          Platform.OS === 'android'
          ? PROVIDER_GOOGLE
          : undefined
          }
      style={styles.map}
      initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
      }}
      moveOnMarkerPress={false}
/>
```

### Steps to reproduce

After MapView is loaded, If I touch or scroll the screen after the map is loaded, that error occurs.

### Expected result

A map with initialRegion is displayed.

### Actual result

Error: Unsupported top level event type "topOnMapReady" dispatched, js engine: hermes
Error: Unsupported top level event type "topOnMapLoaded" dispatched, js engine: hermes

If you touch or scroll the screen after the map is loaded, that error occurs.

### React Native Maps Version

1.6.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Galaxy note10+

**Comment by Qamar-Ascend** [comment]
Facing the same issue 
any update?

**Comment by BilalPervezAscend** [comment]
facing same issue any update?

**Comment by jsungh88** [comment]
I haven't solved it yet..

**Comment by jan-kozinski** [comment]
Hi, thanks for reporting! I'll look into that

**Comment by salah-ghanim** [comment]
@maxform-labs can you please test again with the latest version of the library ? looks like a react-native initialisation issue and could be that it's solved in the latest version

**Comment by sudo-AndrewSmith** [comment]
have same troubles with this... now my lib version is 1.15.2

**Comment by AliHussein-areeba** [comment]
Still no fix or workaround for this?
