### ISSUE TITLE
<MapView> component does not render when used as a child component of <View>

### ISSUE THREAD

**Issue by 1eokim** [react-native-maps/react-native-maps#4928]
### Summary

I could be making some really stupid mistake, but I've tried this multiple times hence reporting this issue.

When I render `<MapView>` component by itself, it works perfectly. However, if I render it as a child component of React Native `<View>` component (repro below), it doesn't show up on screen. The `<Text>` child component renders fine.

Any thoughts and suggestions on this issue would be really appreciated. Thanks a lot!

### Reproducible sample code

```TSX
import React from "react";
import { View, Text } from "react-native";
import MapView from "react-native-maps";

export default function Map() {
  return (
    <View>
      <MapView style={{ flex: 1 }} />
      <Text>The text shows perfectly!</Text>
    </View>
  )
}
```

### Steps to reproduce

I've provided the minimum amount of repro sample code above.

### Expected result

MapView to be rendered on screen.

### Actual result

MapView does not render.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.4

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone SE 2020

### Additional information

- I'm using Expo SDK 49 (the highest version option for the question above was 48)

Project's dependencies if they help:
```
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "expo": "~49.0.8",
    "expo-application": "~5.3.0",
    "expo-auth-session": "~5.0.2",
    "expo-constants": "~14.4.2",
    "expo-crypto": "~12.4.1",
    "expo-dev-client": "~2.4.8",
    "expo-linking": "~5.0.2",
    "expo-location": "~16.1.0",
    "expo-router": "2.0.0",
    "expo-sms": "~11.4.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-web-browser": "~12.3.2",
    "firebase": "^10.3.1",
    "jotai": "^2.4.1",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-maps": "1.7.1",
    "react-native-permissions": "^3.8.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "socket.io-client": "^4.7.2"
  }
```

**Comment by mateki0** [comment]
Hi @1eokim, thanks for reporting but everything works fine here. You have to add flex: 1 to your parent view

```tsx
import React from "react";
import { View, Text } from "react-native";
import MapView from "react-native-maps";

export default function Map() {
  return (
    <View style={{ flex: 1 }}>/
      <MapView style={{ flex: 1 }}/>
    </View>
  )
}
```

**Comment by 1eokim** [comment]
@mateki0 Ah, my bad. Thanks so much for letting me know! Everything looks fine now. Will close this issue.
