### ISSUE TITLE
Map markers opens multiple pop ups when markers that are close by are tapped

### ISSUE THREAD

**Issue by bwees** [react-native-maps/react-native-maps#4933]
### Summary

Hello I am working on a transit app and I sometimes have multiple stop markers close by. When the user taps on an areas where there are 2 close by, the map opens one marker then closes it and then opens the other one. I would be fine if it opens the wrong one but its annoying when you tap the correct one, it opens, and then closes and opens the wrong one. Is there a way to make it so only one is opened when the user taps? 

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    >
        <Marker
            coordinate={{
                latitude: 42,
                longitude: 30
            }}
            tracksViewChanges={false}
        >
            <View
                style={{
                    width: 16,
                    height: 16,
                    borderRadius: 9999,
                    backgroundColor: "red,
                }}
            />
            <Callout>
                <Text>Stop 1</Text>
            </Callout>
        </Marker>
        <Marker
            coordinate={{
                latitude: 42.00001,
                longitude: 30.00001
            }}
            tracksViewChanges={false}
        >
           <View
                style={{
                    width: 16,
                    height: 16,
                    borderRadius: 9999,
                    backgroundColor: "red,
                }}
            />
            <Callout>
                <Text>Stop 1</Text>
            </Callout>
        </Marker>
    <MapView>
  );
}
```

### Steps to reproduce

Use the above code, zoom so the markers are slightly overlapping, then tap. You will see a callout pop up, then close, and then the other one will open

### Expected result

I tap in the area, if the incorrect one opens, I tap again and then it goes to the other one. 

### Actual result

Opens one of them, closes, then opens the other one

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

All iOS, unsure about behavior on android

### Additional information

https://github.com/react-native-maps/react-native-maps/assets/12686250/d585a3aa-2fbc-44ed-b85f-af0117649b63

**Comment by mateki0** [comment]
I'm able to reproduce this bug. I will take a look at it.

**Comment by mateki0** [comment]
> I'm able to reproduce this bug. I will take a look at it.

Unfortunately I wasn't able to find a fix for it. All I found is that this method pasted below is being called twice even though I'm pressing only once. After adding third marker it didn't increase to 3 calls. And after first didSelect call there's a didDeselect call so it is:
 - didSelect
 - didDeselect
 - didSelect
Maybe it will help in further debugging somehow.

```
// AIRMapManager.m
- (void)mapView:(AIRMap *)mapView didSelectAnnotationView:(MKAnnotationView *)view
{
    if ([view.annotation isKindOfClass:[AIRMapMarker class]]) {
        [(AIRMapMarker *)view.annotation showCalloutView];
        NSLog(@"did select annotation view");
    } else if ([view.annotation isKindOfClass:[MKUserLocation class]] && mapView.userLocationAnnotationTitle != nil && view.annotation.title != mapView.userLocationAnnotationTitle) {
        [(MKUserLocation*)view.annotation setTitle: mapView.userLocationAnnotationTitle];
    }
}

```

**Comment by bwees** [comment]
We were able to fix this behavior by adding the `anchor` and `pointerEvents` props like below:

```
<Marker
            key={bus.key}
            coordinate={{ latitude: bus.location.latitude, longitude: bus.location.longitude }}
            tracksViewChanges={false}
            anchor={{x: 1, y: 1}}
            pointerEvents="auto"
        >
```
