### ISSUE TITLE
Google Maps crashing the app immediately when apk is build with release mode

### ISSUE THREAD

**Issue by naviniitk** [react-native-maps/react-native-maps#4936]
### Summary

I am building an app which has Maps as a home screen, 
When I am developing on local and in debug variant the Map is loading nicely and everything is working.
But when I build the apk with release flag, `yarn android:staging --mode=release`, the app crashes as soon as I open it.
see video

https://github.com/react-native-maps/react-native-maps/assets/40453120/e75a6ef7-ae05-4532-ae6a-0f295bd748a9

At first I thought this may be due to some other reason and tried to debug it but nothing was working. but when the commented the code for <MapsView>...</MapsView>. the release build is working perfectly fine.

https://github.com/react-native-maps/react-native-maps/assets/40453120/8c79606b-b374-440b-b36b-7c3c4ef30576

I tried to create a new project from the latest react native cli and tried using the maps in there and found the same issue

Debug Mode: 

https://github.com/react-native-maps/react-native-maps/assets/40453120/9a25e017-803c-43f3-9318-34f2c0c77cbd

Release Mode: 

https://github.com/react-native-maps/react-native-maps/assets/40453120/5656b348-bab6-4020-be3e-d25a3a3f5da6

I am normally using the code without much additional things. not sure whats wrong as I can not even see some logs becasue its a release apk.

### Reproducible sample code

```TSX
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import type {PropsWithChildren} from 'react';
import {
  Dimensions,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';
import mapStyles from './map-styles.json';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

function App(): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const {width, height} = Dimensions.get('window');

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
    height: height,
    width: width,
  };

  const region = {
    latitude: 27.560932,
    longitude: 76.625015,
    latitudeDelta: 0.02,
    longitudeDelta: 0.02 * (width / height),
  };

  console.log(region);

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <MapView
        customMapStyle={mapStyles}
        mapType={'satellite'}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          bottom: 0,
          right: 0,
        }}
        region={region}
        provider={PROVIDER_GOOGLE}>

        </MapView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```

### Steps to reproduce

Create a react native app from the cli `npx react-native@latest init AwesomeProject`.
Add react-native-maps to it.
Create a release build

### Expected result

I expected Maps to be shown without any crash.

### Actual result

App getting crashed everytime when opening the app.

### React Native Maps Version

1.9.0, 1.9.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.1 and 0.73.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 3A simulator, Motorola Edge 20

**Comment by naviniitk** [comment]
I was able to fix this issue, I had added a new <application> </application> in my `AndroidManifest.xml` file. my apk was properly being generated and gave no error.
I was trying to make a bundle to see if that might fix the issue. and encounterd this error: 
```
A failure occurred while executing com.android.build.gradle.internal.tasks.PackageBundleTask$BundleToolWorkAction
   > At most one element <application> with namespace '' was expected, but 2 were found.
```
So I removed the other application tag and added the maps api key in the existing one.
```
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
    >

      <meta-data
         android:name="com.google.android.geo.API_KEY"
         android:value="${googleMapsApiKey}"/>
      
      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name"
        android:exported="true"
      >
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        android:screenOrientation="portrait" 
      >
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
        </intent-filter>
      </activity>
    </application>
```

**Comment by Stefentjung** [comment]
Hmmm

**Comment by NyuydineBill** [comment]
So in conclusion, did you fix this by adding the API_KEY? I am stuck in this exact bug @naviniitk

**Comment by naviniitk** [comment]
Api key is always needed, I had 2 `<application>` tags in my AndroidManifest file, so I removed one and it was working after that.

**Comment by NyuydineBill** [comment]
Thanks so much it worked, I added the api key and the page didn't crash

**Comment by MrutyunjayaSenapati** [comment]
I am also facing the same issue but in build mode. Can anyone help me to fix this problem?

**Comment by NyuydineBill** [comment]
> I am also facing the same issue but in build mode. Can anyone help me to fix this problem?

Hello @MrutyunjayaSenapati 
I resolved this by adding the maps api key to my configurations

**Comment by MrutyunjayaSenapati** [comment]
I added my key in androidmanifest.xml rather than do I have to change any other part

**Comment by RashedMaaitah** [comment]
For anyone in 2025, use npx expo-doctor and check if the dependecies are correct, that solved the issue for me
