### ISSUE TITLE
react native 0.65 not compatible with version 1.9.1 and up 

### ISSUE THREAD

**Issue by vellvj** [react-native-maps/react-native-maps#4947]
### Summary

version 1.9.1 and up require node >= 18, but react native 0.65 depends on node v16

### Reproducible sample code

```TSX
<MapView
  initialRegion={{
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
/>
```

### Steps to reproduce

npx react-native init MyNewProject --version 0.65
yarn add react-native-maps@1.10.0
yarn react-native start
yarn react-native run-android

### Expected result

successfully build the project

### Actual result

should able to build project with node v16, since react native 0.65 depends on node v16

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.65.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Xiaomi 11T Pro

**Comment by salah-ghanim** [comment]
@vellvj this is not a bug .. the library is constantly being updated to use the latest react-native, backward compatibility is ensured by simply using older versions of the library.
