### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by fexd12** [react-native-maps/react-native-maps#4951]
### Summary

Is there any plan for react-native-maps to support Macos?

### Reproducible sample code

```TSX
N/A
```

### Steps to reproduce

N/A

### Expected result

Support

### Actual result

Not Support

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.6

### What version of Expo are you using?

Not using Expo

### Device(s)

MacOS

**Comment by salah-ghanim** [comment]
@fexd12 I can't see a realistic way of doing that with reasonable effort, I think it's better for you to use a web based map solution instead.

since react-native-windows / mac uses native desktop technology and this library use native mobile technology and those are very far from each other
