### ISSUE TITLE
Dark Mode Callouts

### ISSUE THREAD

**Issue by bwees** [react-native-maps/react-native-maps#4959]
### Summary

I would like to set the background color fo the callout for use in dark mode situations. I cannot seem to find a solution to either setting the background color or just using whatever the default styling is. I cannot use a tooltip because I need the pointer and it has weird behavior when on the edges of the display.
<img width="188" alt="Screenshot 2024-02-05 at 2 11 57 PM" src="https://github.com/react-native-maps/react-native-maps/assets/12686250/65f4135b-9e49-4931-983e-16bc66cc0689">

I cannot set the background color of the view inside because it just has a white border around it.
<img width="187" alt="Screenshot 2024-02-05 at 2 12 52 PM" src="https://github.com/react-native-maps/react-native-maps/assets/12686250/d529c820-d2c7-4639-8559-1b22c35034cb">

### Reproducible sample code

```TSX
<Callout 
            style={{ 
                alignItems: 'center',
                backgroundColor: "black"
            }}
        >
            <Text>Hello</Text>
        </Callout>
```

### Steps to reproduce

Use the callout example but use the above code as your Callout

### Expected result

I expect the whole callouts color to change. I have not tested on android but this needs to look correct on both platforms...

### Actual result

There is a white border or the callout is not centered when at edge of screen.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

All iOS, unsure about behavior on android

**Comment by jan-kozinski** [comment]
Hi, you should add the prop "tooltp" to your callout as in
```
       <Callout 
          tooltip
            style={{ 
                alignItems: 'center',
                backgroundColor: "black"
            }}
        >
            <Text>Hello</Text>
        </Callout>
```
Please read the docs https://github.com/react-native-maps/react-native-maps/blob/master/docs/callout.md

**Comment by jan-kozinski** [comment]
Hi, thanls for reporting this! Unfortunately, there's no other way than to use the tooltip property. But what you can do is nesting a triangle in the Callout to serve as a pointer as in
```
<Callout
          tooltip
          style={{
            width: 140,
            height: 140,
          }}>
          <View
            style={{
              height: '100%',
              width: '100%',
              backgroundColor: '#1b1b1b',
              borderRadius: 20,
              padding: 10,
            }}>
            <Text style={{color: 'white'}}> Hola! </Text>
          </View>
          <View
            style={{
              width: 0,
              height: 0,
              marginLeft: 'auto',
              marginRight: 'auto',
              borderColor: 'transparent',
              borderTopWidth: 20,
              borderTopColor: '#1b1b1b',
              borderLeftWidth: 20,
              borderRightWidth: 20,
              marginBottom: 10,
            }}
          />
        </Callout>
```

**Comment by bwees** [comment]
I have done this but when a marker is tapped on the edge of the screen, the callout is not centered on the point, resulting in a marker that is offset from the actual point. I can’t program the map to center on the point before the fallout appears because it results in the same behavior.

**Comment by bwees** [comment]
Still relevant

**Comment by jahirfiquitiva** [comment]
I am also looking for a way to customize the background color of the callouts, but there is always a padding/margin that we cannot change the color to 😫 

![Image](https://github.com/user-attachments/assets/aedd7bcf-1947-478c-b851-1fcea627ca96)

**Comment by bwees** [comment]
> I am also looking for a way to customize the background color of the callouts, but there is always a padding/margin that we cannot change the color to 😫
> 
> ![Image](https://github.com/user-attachments/assets/04466f72-ff27-495f-a021-00f761989f05)

How were you able to get the callout dark in the first place? Ours just stays white no matter what we try to do

**Comment by jahirfiquitiva** [comment]
@bwees it changes if you change to dark mode, or if you set the `userInterfaceStyle` in the `MapView` to `dark`

**Comment by bwees** [comment]
Oh interesting, I will have to try that. Thanks!

**Comment by benedusi** [comment]
> [@bwees](https://github.com/bwees) it changes if you change to dark mode, or if you set the `userInterfaceStyle` in the `MapView` to `dark`

Would you mind sharing your Mapview and Callout code? Setting userInterfaceStyle to 'dark' makes no difference to me.

**Comment by bwees** [comment]
Same, it also is not dark on my end when adding `userInterfaceStyle="dark"`. @jahirfiquitiva
