### ISSUE TITLE
AIRGoogleMap setOnClick

### ISSUE THREAD

**Issue by xristeas** [react-native-maps/react-native-maps#4962]
### Summary

After upgrading dependencies when going to our test react-native project we get the following error:

Exception thrown while executing UI block: -[AIRGoogleMap setOnClick:]: unrecognized selector sent to instance 0x7f89a915c400

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1205
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.496
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0

### Reproducible sample code

```TSX
<MapView
                    showsMyLocationButton={false}
                    toolbarEnabled={false}
                    provider={PROVIDER_GOOGLE}
                    showsUserLocation={true}
                    ref={mapRef}
                    style={MapComponentStyles.map}
                    initialRegion={initialRegion}
                    customMapStyle={mapStyle}
                    removeClippedSubviews={false}
                    followsUserLocation={false}
                    onRegionChangeComplete={region => onRegionUpdateHandler(region)}
                />
```

### Steps to reproduce

Just pod install with latest dependencies. and run iOS 

### Expected result

Map page to be loaded

### Actual result

the attached error

### React Native Maps Version

1.10.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.2

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14, emulator

**Comment by xristeas** [comment]
It seems that the problem is thrown when map view is nested inside a <TouchableWithoutFeedback style={MapComponentStyles.touchable} onPressOut={() => { setCarouselVisible(false) }}>

**Comment by salah-ghanim** [comment]
@xristeas this bug seems to be outside this library .. closing, you can always wrap the MapView in a container view.
