### ISSUE TITLE
Application crashes on android without any error logged

### ISSUE THREAD

**Issue by Mons-L** [react-native-maps/react-native-maps#4965]
### Summary

When I use MapView in my code, my application crashes only on ANDROID but not on IOS. After some research, the error comes from the initialRegion of the mapView to which I supplied a latitude and longitude string. On IOS there's no problem but on android the application crashes without any log or message to understand the problem.
If this can help someone stuck.

### Reproducible sample code

```TSX
<MapView
    provider={MAP_PROVIDER}
    customMapStyle={customMapStyle}
    style={{width: "100%", height: "100%"}}
    initialRegion={{
        latitude:  48.18,
        longitude: "12.12",
        latitudeDelta: 0.005,
        longitudeDelta: 0.005,
    }}
/>
```

### Steps to reproduce

Initialize a MapView with an initialRegion with a string latitude and/or longitude.

### Expected result

On IOS : everything works fine don't need anything (or it can provide a warning to say the lat and long are given in string format).
On ANDROID : it should work like on IOS and provide a warning or it should at least give an error to understand the issue.

### Actual result

On IOS : everything works fine (without any error or warning).
On ANDROID : application crashes (without any error or warning).

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.6

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 12 Pro, Google Pixel 3a

### Additional information

I use expo 49.0.16.
I've tested on several devices and it's always the same.
I use the google provider for IOS and ANDROID.

**Comment by jan-kozinski** [comment]
docs say that the longtitude is expected to be a number. Please use the library in accordance to the docs if you expect it to be stable.
