### ISSUE TITLE
Poor performance on Android when markers are added incrementally.

### ISSUE THREAD

**Issue by jared-ca** [react-native-maps/react-native-maps#4968]
### Summary

When using custom markers on Android each time you add a new marker a new `ViewChangesTracker` run loop is started. Each loop re-draws every marker to a Bitmap so you end up with an exponential drop in performance.

For example with 20 markers the library is running a 20 loops each rendering every marker to a canvas, resulting in 400 Bitmap renders every 40ms.

If you run the sample code below with the performance monitor visible you can watch the FPS drop from 120 down to 10 by the time you get to about 16 markers.

### Reproducible sample code

```TSX
import { Button, StyleSheet, Text } from 'react-native';
import MapView, { MapMarker } from 'react-native-maps';
import { useState } from 'react';
import { range } from 'lodash';

export const MapPerformance = () => {
    const [count, setCount] = useState(0);

    return (
        <>
            <Button onPress={() => setCount(count + 1)} title={`${count} Markers`} />
            <Button onPress={() => setCount(0)} title='Clear' />
            <MapView style={styles.map}>
                {range(count).map(x => (
                    <MapMarker key={x} coordinate={{ latitude: x / 2, longitude: x / 2 }}>
                        <Text>Custom Marker</Text>
                    </MapMarker>
                ))}
            </MapView>
        </>
    );
};

const styles = StyleSheet.create({
    map: {
        width: '100%',
        height: '100%',
    },
});
```

### Steps to reproduce

Run the sample app and tap the top button a dozen times.

### Expected result

FPS should stay at a reasonable level

### Actual result

FPS drops to 10 and the whole app is sluggish.

### React Native Maps Version

1.8.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 7 Pro

**Comment by chanphiromsok** [comment]
Hi I have faced an issue with MapView too do not use full dimension it will cause perf with MapView
- you should set trackViewChanges in the marker to false if you are rendering a static marker
- mapView should not use  w 100% and h 100% like that
- for my Attempt I downgraded the w and h and scale with the transform in map view style it is a bit ugly and trick

### After and Before
![image](https://github.com/react-native-maps/react-native-maps/assets/65760336/50446cfb-7534-457e-80e2-954613afe5d2)

**Comment by KHadham** [comment]
@chanphiromsok what tools you use to get that screenshoot ?

**Comment by krakowski** [comment]
This could also be linked to my issue https://github.com/react-native-maps/react-native-maps/issues/4891.

> @chanphiromsok what tools you use to get that screenshoot ?

As I was interested as well: a quick Google reverse image search led me to https://flashlight.dev

**Comment by chanphiromsok** [comment]
> @chanphiromsok what tools you use to get that screenshoot ?

I use flashlight

**Comment by chanphiromsok** [comment]
> This could also be linked to my issue https://github.com/react-native-maps/react-native-maps/issues/4891.
> 
> 
> 
> > @chanphiromsok what tools you use to get that screenshoot ?
> 
> 
> 
> As I was interested as well: a quick Google reverse image search led me to https://flashlight.dev

That not related to your issue I have test long running without marker it still the same

**Comment by mateki0** [comment]
Done in https://github.com/react-native-maps/react-native-maps/pull/4969 by author.
