### ISSUE TITLE
provider={PROVIDER_GOOGLE} doesn't allow onSelect and onDeselect on iOS

### ISSUE THREAD

**Issue by rarenatoe** [react-native-maps/react-native-maps#4970]
### Summary

When using provider `google`, the Marker props onSelect and onDeselect do not work on iOS (which supposedly does work). This should either be fixed or specified in the docs that it doesn't for this case.

### Reproducible sample code

```TSX
import React from 'react'
import { Text } from 'react-native'
import MapView, { Marker, Callout, PROVIDER_GOOGLE } from 'react-native-maps'

<MapView
  provider={PROVIDER_GOOGLE}
  customMapStyle={MapStyle}
>
  <Marker coordinate={someCoordinate}
    onSelect={() => console.log('onSelect called')}
    onDeselect={() => console.log('onDeselect called')}
  >
    <Callout>
      <Text>Hola</Text>
    </Callout>
  </Marker>
</MapView>
```

### Steps to reproduce

1. Find the marker on the map.
2. Press the marker.
3. Check that there is **no** log `onSelect called`.
4. Press anywhere else in the map.
5. Check that there is **no** log `onDeselect called`.

### Expected result

onSelect and onDeselect should work.

### Actual result

onSelect and onDeselect do not work.

### React Native Maps Version

1.10.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.9

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro simulator

**Comment by jan-kozinski** [comment]
Hi, the onSelect and onDeselect props are not supported on Google Maps. I'll update the readme accordingly. Thanks for reporting!

**Comment by salah-ghanim** [comment]
@jan-kozinski I will merge your pull request to update the docs, but do you want to create a pull request for implementing marker select / deselect functionality on google maps ? 
see this from chatgpt:

> 
> Detecting marker selection and deselection in the Google Maps SDK for both iOS and Android involves different approaches tailored to each platform. Below, I'll outline how to implement these functionalities for both environments.
> 
> ### For iOS (Google Maps SDK for iOS)
> 
> In Google Maps SDK for iOS, you can detect marker selection (tap) and deselection by implementing the `GMSMapViewDelegate` methods. Specifically, you'll use `mapView:didTapMarker:` to detect when a marker is tapped (selected) and potentially `mapView:didTapAtCoordinate:` to manage deselection, since there isn't a direct method for detecting marker deselection.
> 
> 1. **Detect Marker Selection:**
>    Implement the `mapView:didTapMarker:` delegate method. This method is called when a marker on the map is tapped.
> 
>    ```swift
>    func mapView(_ mapView: GMSMapView, didTap marker: GMSMarker) -> Bool {
>        // Marker was tapped, implement your logic here
>        return false // Return true to prevent the map from further processing the tap (like showing the info window)
>    }
>    ```
> 
> 2. **Detect Marker Deselection:**
>    Since there's no direct method for marker deselection, one common approach is to detect a tap on the map that's not on a marker. Implement the `mapView:didTapAtCoordinate:` method for this purpose.
> 
>    ```swift
>    func mapView(_ mapView: GMSMapView, didTapAt coordinate: CLLocationCoordinate2D) {
>        // A tap occurred on the map (not on a marker), implement your deselection logic here
>    }
>    ```
> 
>    Remember to set your map view's delegate to the class where you implement these methods:
>    ```swift
>    mapView.delegate = self
>    ```
> 
> ### For Android (Google Maps API for Android)
> 
> In the Google Maps API for Android, you can use the `OnMarkerClickListener` and `OnMapClickListener` interfaces to detect marker selection and deselection.
> 
> 1. **Detect Marker Selection:**
>    Implement `OnMarkerClickListener` and set it on your `GoogleMap` object. The `onMarkerClick` method will be called when a marker is clicked.
> 
>    ```java
>    googleMap.setOnMarkerClickListener(new GoogleMap.OnMarkerClickListener() {
>        @Override
>        public boolean onMarkerClick(Marker marker) {
>            // Marker was clicked, implement your logic here
>            return false; // Return true to indicate that you have consumed the event (i.e., you don't want the default behavior like showing the info window)
>        }
>    });
>    ```
> 
> 2. **Detect Marker Deselection:**
>    Implement `OnMapClickListener` to detect taps on the map. This can be used to handle deselection.
> 
>    ```java
>    googleMap.setOnMapClickListener(new GoogleMap.OnMapClickListener() {
>        @Override
>        public void onMapClick(LatLng latLng) {
>            // The map was clicked, implement your deselection logic here
>        }
>    });
>    ```
> 
> In both iOS and Android, the general idea is to leverage the map and marker listeners provided by the SDK to implement custom behavior for marker selection and deselection. Adjust the logic inside these listener methods according to your app's requirements.

**Comment by jan-kozinski** [comment]
yeah I surely do wanna look into that, I just didn't want to leave the docs missleading until I figure it out

**Comment by salah-ghanim** [comment]
closing since this was released recently
