### ISSUE TITLE
Update to latest renderer for Maps SDK for Android in react-native-maps

### ISSUE THREAD

**Issue by LVExMachina** [react-native-maps/react-native-maps#4980]
### Summary

I received an email from Google Maps Platform stating that apps using the legacy renderer for Maps SDK for Android will be automatically updated to the new renderer starting in March 2024. The legacy renderer will be decommissioned in March 2025. I would like to know if the react-native-maps library is already compatible with the new renderer and, if so, which version is recommended.

The Google Maps Platform email specifies that apps built with Maps SDK for Android will be automatically updated to the new renderer on March 4, 2024. However, if the legacy renderer is manually specified in the settings, the update will be delayed until March 2025.

I would like to understand if the react-native-maps library is ready to handle the new renderer and which version I should use to ensure compatibility with the automatic Google update.

<img width="741" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/149154549/3654e567-4400-4a5e-8a5b-fab969e40db3">

### Reproducible sample code

```TSX
I do not currently have sample code to show as the issue is about library compatibility and not a specific bug.
I do not have precise information on the steps to reproduce the issue as this is a preventive notice from Google Maps Platform.
```

### Steps to reproduce

I do not currently have sample code to show as the issue is about library compatibility and not a specific bug.
I do not have precise information on the steps to reproduce the issue as this is a preventive notice from Google Maps Platform.

### Expected result

I do not currently have sample code to show as the issue is about library compatibility and not a specific bug.
I do not have precise information on the steps to reproduce the issue as this is a preventive notice from Google Maps Platform.

### Actual result

I do not currently have sample code to show as the issue is about library compatibility and not a specific bug.
I do not have precise information on the steps to reproduce the issue as this is a preventive notice from Google Maps Platform.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps)

### React Native Version

0.72.10

### What version of Expo are you using?

SDK 48

### Device(s)

Not specific device

**Comment by RobertFOConnor** [comment]
If you check [the docs](https://developers.google.com/maps/documentation/android-sdk/renderer#opt-out) they say from 18.2.0 maps uses the new renderer by default. 

So if you're up-to-date with react-native-maps, you should already be using it, see the [build.gradle](https://github.com/react-native-maps/react-native-maps/blob/master/android/build.gradle).

**Comment by RobertFOConnor** [comment]
From the docs:

react-native-maps added support for the new renderer in v0.31.0.

To opt in to the new renderer add the following code in your entry file (e.g. App.js):

```javascript
import {enableLatestRenderer} from 'react-native-maps';

From the installation docs:

enableLatestRenderer();
```

`enableLatestRenderer` returns a promise (on android) specifying the map renderer being used, either `'LATEST' | 'LEGACY'`. It can be called at any point to get the renderer being used, but it won't change after the first map has been rendered.

Make sure to test your app thoroughly after enabling the new renderer, as it seems to cause some behavioural changes, e.g. [this](https://github.com/react-native-maps/react-native-maps/pull/4055#issuecomment-1063358886).

---

**Comment by Filippo39** [comment]
The email states:

```
No action is recommended if your app already uses Maps SDK for Android v18.2.0 and does not specify a renderer during the initialization process.
```

From what I can see, starting from version v1.9.0, following the modification made in #4921, the Maps SDK for Android has been updated to version v18.2.0. Therefore, from that version onwards, we should be okay.

**Note**: If anyone, like myself, has defined 'playServicesVersion' in their 'android/build.gradle', that value overrides the version used by react-native-maps.

It remains to be understood whether the second part of the sentence in the email `...and does not specify a renderer during the initialization process.` is respected with v1.9.0, and if older versions will receive a patch or if we will all be forced to update to v1.9.0."

**Comment by salah-ghanim** [comment]
@Filippo39 thanks for contributing, yes latest SDK version should have latest renderer enabled out of the box.

for couple of the previous versions calling MapView.enableLatestRenderer() should work as well.

**Comment by LVExMachina** [comment]
Thank you!

**Comment by gijsjager** [comment]
@salah-ghanim 

I haver added the `enableLatestRenderer()` in my App.js but this gives me "LEGACY" within the callback. 
How do I enable it to "LATEST" 

I am running on 
- expo: 50.0.7
- react-native-maps: 1.10.0

**Comment by uzuntonev** [comment]
I am facing issues when calling `enableLatestRenderer()` . Custom Marker ( children warped in <Marker/>) starts flickering. 

Note: Passing prop `tracksViewChanges={false}` is not a solution because markers change dynamically and scale if selected. Passing this prop prevents any image changes

Running on

- "react-native": "0.72.6"
- "react-native-maps": "^1.7.1"

**Comment by GabrieleMazzola** [comment]
> I am facing issues when calling `enableLatestRenderer()` . Custom Marker ( children warped in ) starts flickering.
> 
> Note: Passing prop `tracksViewChanges={false}` is not a solution because markers change dynamically and scale if selected. Passing this prop prevents any image changes
> 
> Running on
> 
> * "react-native": "0.72.6"
> * "react-native-maps": "^1.7.1"

I also experienced the same issue, and having dynamic markers I could not rely on `tracksViewChanges={false}`.

For now, I disabled the new renderer using `googleRenderer={'LEGACY'}` on my `<MapView>`. It should be okay for a year or so, we'll see what happens next.

**Comment by ryskin** [comment]
why it's closed? I'm still having this issue

**Comment by andrecrimb** [comment]
Still facing the same issue, will this issue be reopened?

**Comment by spyshower** [comment]
i see the old map, should we wait a few more years for the fix?

**Comment by StefanWallin** [comment]
I also still have this in `react-native-maps@2.0.0-beta.15`

**Comment by StefanWallin** [comment]
> I also still have this in `react-native-maps@2.0.0-beta.15`

It seems that for `2.0.0-beta.15` version of RN Maps we're still "pegged" at `18.1.0`:
https://github.com/react-native-maps/react-native-maps/blob/v2.0.0-beta.15/android/build.gradle#L59-L64

**`android/build.gradle` lines 59-64 @ `2.0.0-beta.15`**
```gradle
...
  implementation('com.google.android.gms:play-services-maps') {
    version {
      strictly '[18.0.0, 19.0.0['
      prefer '18.1.0'
    }
  }
...
```

**Comment by spyshower** [comment]
@StefanWallin fyi the latest commit on 2 beta is older than the latest stable version
