### ISSUE TITLE
Polygons always rendering behind UrlTile if caching enabled afterwards

### ISSUE THREAD

**Issue by draperunner** [react-native-maps/react-native-maps#4982]
### Summary

Toggling a polygon works fine either if caching is enabled or disabled from the start. But if caching is toggled on/off after first render, polygons will always be rendered behind the UrlTile.

https://github.com/react-native-maps/react-native-maps/assets/4339443/781ddb3d-a5e1-4441-9e7b-a0bb50cfa7cf

### Reproducible sample code

```TSX
A complete reproducible example can be found in this branch: https://github.com/draperunner/react-native-maps/tree/urltile-polygon-bug-repro
```

### Steps to reproduce

Start the example app from this repro branch: A complete reproducible example can be found in this branch: https://github.com/draperunner/react-native-maps/tree/urltile-polygon-bug-repro

See that toggling the polygon is fine, but not after enabling/disabling the cache.

### Expected result

I would expect the polygons to appear on top of the UrlTile, just like they do if caching is never toggled.

### Actual result

Polygons appear below the UrlTile if caching of the UrlTile is enabled after the initial render.

### React Native Maps Version

1.10.3

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.73.0

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 15

### Additional information

A workaround seems to be to set a new `key` on `<UrlTile>` whenever caching is toggled (whenever `tileCachePath` is changed).

**Comment by hussainahmad** [comment]
@draperunner did you got any luck ?
