### ISSUE TITLE
IOS Crash when MapView is inside FlatList Header

### ISSUE THREAD

**Issue by NiccoloCase** [react-native-maps/react-native-maps#4983]
### Summary

When using React Native Maps (react-native-maps) as the header of a FlatList on iOS, the application crashes.

### Reproducible sample code

```TSX
const MyComponent = () => {
  const data = [...]; // Your FlatList data

  return (
    <FlatList
      data={data}
      keyExtractor={(item) => item.id.toString()}
      ListHeaderComponent={() => (
        <MapView
          style={{ height: 200 }}
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        >
          <Marker
            coordinate={{ latitude: 37.78825, longitude: -122.4324 }}
            title="Marker Title"
            description="Marker Description"
          />
        </MapView>
      )}
      renderItem={({ item }) => (
        <View>
          <Text>{item.name}</Text>
          {/* Other item content */}
        </View>
      )}
    />
  );
};
```

### Steps to reproduce

nstall the react-native-maps library.
Create a FlatList with a MapView component as its header.
Run the application on an iOS device or simulator.
Scroll through the FlatList.

### Expected result

to work!!!

### Actual result

<img width="388" alt="Screenshot 2024-02-23 alle 02 55 28" src="https://github.com/react-native-maps/react-native-maps/assets/41541220/72803983-8eb5-44b8-a358-808a91b39dc7">

### React Native Maps Version

1.10.3

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.14

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 14

**Comment by mateki0** [comment]
Hi @NiccoloCase, thanks for reporting this but I'm not able to reproduce the crash. Can you try it in bare expo project? I tried to reproduce it on two different react-native and maps versions and in both cases it works fine. Please try to use this command and let me know if it work there. It will help us identify what's wrong. And on which version of iOS system did you encounter it?

```
npx create-expo-app -t blank@48
```

Other than that, here is the issue with the same error and from what I see it was connected with reanimated library.
https://github.com/react-native-maps/react-native-maps/issues/3983#issuecomment-1405302781
