### ISSUE TITLE
Still using legacy after enableLatestRenderer

### ISSUE THREAD

**Issue by meedodk** [react-native-maps/react-native-maps#4986]
### Summary

In my App.tsx i run

enableLatestRenderer(); 

But i still get 'LEGACY' returned in the Android.  My simulator 

I do not use any other Services that use a lower version of Google Maps. 

`if (Platform.OS === 'ios') {
  enableLatestRenderer();
} else {
  enableLatestRenderer().then(res => console.log(res));
}`

I also tried including specific implementations with successful build: 

`
implementation("com.google.android.gms:play-services-maps:18.2.0")
implementation("com.google.android.gms:play-services-location:21.1.0")
`

I do not know if this is a bug or if I am doing something wrong in my setup. I followed the steps on the Installation guide. 

Hope someone can help me fix this issue. 
Thanks in advance.

### Reproducible sample code

```TSX
<MapView
        provider={PROVIDER_GOOGLE}
        style={[styles.map]}
        ref={mapRef}
        onPress={onMapClick}
        customMapStyle={mapStyles}
        showsUserLocation
        showsMyLocationButton={false}
        showsCompass={false}
        initialRegion={location}
        onRegionChange={handleOnRegionChange}
        onRegionChangeComplete={handleOnRegionComplete}>
        {children}
      </MapView>
```

### Steps to reproduce

`if (Platform.OS === 'ios') {
  enableLatestRenderer();
} else {
  enableLatestRenderer().then(res => console.log(res));
}`

### Expected result

that the promise return 'LATEST' 

### Actual result

promise returns 'LEGACY'

### React Native Maps Version

^1.10.3

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.72.7

### What version of Expo are you using?

Not using Expo

### Device(s)

Android 13.0 ("Tiramisu" Api level 33

**Comment by gijsjager** [comment]
I got the same issue (but using Expo SDK 50)

**Comment by mateki0** [comment]
Thanks for this solution @gijsjager. On my phone and emulators it all works fine so renderer is always "LATEST" but this may be helpful with old issue with black streets on emulators.

**Comment by BuyMyBeard** [comment]
> I got the same issue (but using Expo SDK 50), after updating the Google Play Service in my android emulator it suddenly got changed to "LATEST"
> 
> Maybe this could help?
> 
> Updating Google Play Service:
> 
> * In the emulator press the 3 dots on the side of the emulator
> * Choose Google Play
> * Press the button [Update]

This fixed it for me, thanks
