### ISSUE TITLE
Custom marker start flicking without changing the state.

### ISSUE THREAD

**Issue by Bilal7811** [react-native-maps/react-native-maps#4997]
### Summary

When employing React Native Maps version 1.11.1, a peculiar phenomenon emerges: custom markers begin to flicker inexplicably, even when the location remains unchanged. Curiously, this issue is absent in React Native Maps version 1.7.1, where custom markers maintain stability without exhibiting any flickering behavior. I have not changed anything in the code except for the version number. you may review my reproducible example here.

react-native-maps v(1.11.1) :
https://github.com/react-native-maps/react-native-maps/assets/124868535/2467ba37-6b18-49a5-9d0e-3e33973129d8

react-native-maps v(1.7.1) :
https://github.com/react-native-maps/react-native-maps/assets/124868535/2020a044-128c-4607-a7b8-a8026133e987

### Reproducible sample code

```TSX
import React, {useRef, useEffect} from 'react';
import {View, Image, StatusBar} from 'react-native';
import MapView, {Marker, PROVIDER_GOOGLE} from 'react-native-maps';
import {useDispatch, useSelector} from 'react-redux';

import {appIcons} from '../../../services';
import {styles} from './styles';

const Dashboard = ({navigation}) => {
  // const dispatch = useDispatch();
  const mapRef = useRef(null);
  const user = useSelector(state => state.user.userLocation);


  return (
    <View>
      <MapView
        provider={PROVIDER_GOOGLE}
        ref={mapRef}
        style={styles.mapStyle}
        initialRegion={{
          latitude: user?.position?.lat,
          longitude: user?.position?.lng,
          longitudeDelta: 241.77777099609375,
          latitudeDelta: 353.77777099609375,
        }}>
        <Marker
          draggable={false}
          coordinate={{
            latitude: user?.position?.lat,
            longitude: user?.position?.lng,
            longitudeDelta: 241.77777099609375,
            latitudeDelta: 353.77777099609375,
          }}>
          <Image source={appIcons.mapIcon} style={styles.imageStyle} />
          <Image source={appIcons.profileIcon} style={styles.userImage} />
        </Marker>
      </MapView>
    </View>
  );
};

export default Dashboard;
```

### Steps to reproduce

You need to use react-native-maps v(1.11.1)
Use the same code

### Expected result

https://github.com/react-native-maps/react-native-maps/assets/124868535/2020a044-128c-4607-a7b8-a8026133e987

### Actual result

https://github.com/react-native-maps/react-native-maps/assets/124868535/2467ba37-6b18-49a5-9d0e-3e33973129d8

### React Native Maps Version

1.11.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.4

### What version of Expo are you using?

Not using Expo

### Device(s)

OnePlus 9R

**Comment by kaladivo** [comment]
I am having the same issue.

**Comment by andresvega-sourcetoad** [comment]
The issue when updated to 1.10.3 and the same behavior on 1.11.3

**Comment by kaladivo** [comment]
If I add `tracksViewChanges={false}` on `Marker` component it seems to remove the flickering for me. I am using react-native-maps 1.11.3.

**Comment by andrecrimb** [comment]
Same issue.

**Comment by simonorzel26** [comment]
Same issue for me v1.11.3, tracksViewChanges={false} worked as a temp fix

**Comment by lklima** [comment]
Same here v1.11.3, I'm using animated view (cicle/radio animation) , the animation doesn't work with `tracksViewChanges={false}`  

https://github.com/react-native-maps/react-native-maps/assets/44346970/c4ea8ed6-49c3-40c1-84c3-09cd37b4cc2c

**Comment by gkpo** [comment]
Same issue here: Adding `tracksViewChanges={false}` fixes the flickering, but stops my animation from working. So this is not a solution for me :(

**Comment by jan-kozinski** [comment]
the flickering is caused by the new react maps renderer and was reported here as well https://github.com/react-native-maps/react-native-maps/issues/4980

**Comment by iM-GeeKy** [comment]
Is there any solution to this? Adding `tracksViewChanges={false}` fixes the flickering, but leads to https://github.com/react-native-maps/react-native-maps/issues/4472#issuecomment-2002643096. I've tried the patch as well, but it still leads to bizarre pressing behavior on Android.

**Comment by salah-ghanim** [comment]
In the new release you can use googleRenderer={'LEGACY'} as a MapView property to avoid being forced to use the latestRenderer and deal with this bug.

**Comment by fuelkoy** [comment]
I upgraded from 1.10.0 (recommended by Expo SDK 50) to 1.14.0. As my experience the markers experience yet blinking.

**Comment by geikobogdan** [comment]
@salah-ghanim, after updating library to 1.15.6 it still doesn't work for Android. Also tested with `googleRenderer={'LEGACY'}`

**Comment by yperdimis** [comment]
When you put a <View> under <Marker> with images and/or text it blinks randomly.  A recent update at google map API is breaking custom Markers in react native. At older devices with older version of google map app there is no blinking. I have installed the latest version of maps @1.15.6. The same bug happens and at @1.7.1.

**Comment by geikobogdan** [comment]
@yperdimis so what can I do in this situation, just leave it and hope for fix?

**Comment by geikobogdan** [comment]
<img width="396" alt="Снимок экрана 2024-06-07 в 01 05 05" src="https://github.com/react-native-maps/react-native-maps/assets/56224886/65785d40-723e-4a11-8fc0-7d135afcbef8">
BTW,  I use only custom image for marker without View wrapper

**Comment by yperdimis** [comment]
I have tested with various emulators and i have found that if you set up your google account with your android phone google map api defaults to the new Renderer and causes the flickering problems. There is no work around to use the legacy renderer with react native maps. If you signed in to your google account it will use the new renderer in react native.

**Comment by Steytz** [comment]
I am in expo 50 using react-native-maps version 1.13.0, so i am facing the same flickering issue explained here when rendering custom markers. When i set trackViewChanges={false} in the Marker it solves the issue and the map is also drastically more performant. For more information about my custom markers they render a jpg or png image inside of them and have like a custom badge that changes its label dynamically on top of them.

my concrete questions:

What does trackViewChanges exactly affect/do for a given Marker component?

When should it be definitely turned on and when off?

Would it not be better to just turn it off by default and and use the [redraw()](https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#methods) method each marker provides when the marker really needs to move/change or be re rendered? this is also stated in the docs for trackViewsChanges.

**Comment by andrecrimb** [comment]
Facing the same issue: `"react-native-maps": "1.13.2"`.

**Comment by ssommelet21** [comment]
> googleRenderer={'LEGACY'}

Not possible since "Maps SDK for Android release notes (Release 19.0.0) June 25, 2024" :

https://developers.google.com/maps/documentation/android-sdk/release-notes

**Comment by ssommelet21** [comment]
> In the new release you can use googleRenderer={'LEGACY'} as a MapView property to avoid being forced to use the latestRenderer and deal with this bug.

Not possible since "Maps SDK for Android release notes (Release 19.0.0) June 25, 2024" :

https://developers.google.com/maps/documentation/android-sdk/release-notes

**Comment by szarbartosz** [comment]
Worked with `1.14.0` version in my project and faced the same issue (tried to bump to the newest one, but it didn't help) `tracksViewChanges={false}` doesn't work for me (when this option is set to false, the image which is my custom marker doest not show up on the android physical device) @jan-kozinski is there any update on this one?

**Comment by SzymonGonet** [comment]
> Worked with `1.14.0` version in my project and faced the same issue (tried to bump to the newest one, but it didn't help) `tracksViewChanges={false}` doesn't work for me (when this option is set to false, the image which is my custom marker doest not show up on the android physical device) @jan-kozinski is there any update on this one?

@jan-kozinski any updates?

**Comment by IKTANIM** [comment]
Any update

**Comment by CleverTomatoe** [comment]
Same issue here. Any fix?

**Comment by melyux** [comment]
Still having this issue on 1.17.1. And setting `tracksViewChanges` false makes my custom markers disappear after a while on Android, which is way worse.

**Comment by itallocastro** [comment]
Same issue here. Any update?

**Comment by freddy-eturi** [comment]
Also facing this issue

**Comment by foukas** [comment]
Is there at least any decent workaround for this? I mean, I'm trying to disable tracksViewChanges right after the custom markers have loaded, but since I'm using a clustered map, markers appear and disappear while interacting with the map and I can neither keep it disabled (because the markers don't update) nor keep it enabled (as there's flickering).

**Comment by ssommelet21** [comment]
Since using a custom marker (an image) makes react-native-maps flicking,

I haven’t placed any image inside the marker itself. Instead, I calculate where to place the images outside of the MapView component.

This way, there’s no more flickering, but we still have to wait to know when to redraw the markers.

https://snack.expo.dev/@ssommelet21/customflickingmarkers

Weird result.

**Comment by samvoults** [comment]
> When you put a View under Marker with images and/or text it blinks randomly. A recent update at google map API is breaking custom Markers in react native. At older devices with older version of google map app there is no blinking. I have installed the latest version of maps @1.15.6. The same bug happens and at @1.7.1.

Any chance a fix will appear soon?

**Comment by JKKholmatov** [comment]
Any updates? I guess using SVG is leading to memory leak and crashes, Play Console is reporting about this crash. We need solution

**Comment by aleks-khomenko** [comment]
Same issue here. Any update?

**Comment by shancock884** [comment]
> In the new release you can use googleRenderer={'LEGACY'} as a MapView property to avoid being forced to use the latestRenderer and deal with this bug.

Based on an email from Google Maps Platform this morning, it seems that specifying the 'LEGACY' renderer will no longer work after March 2025 (even for those versions of react-native-maps/Android SDK where it still does today):

> If you specify the legacy renderer (on version 18.0 or later): your application will continue receiving the legacy renderer until March 2025. Starting in March 2025, you will get the new renderer even if you specify the Legacy renderer.

**Comment by benedusi** [comment]
googleRenderer={"LEGACY"} does not seems to have any effect on the issue anymore

**Comment by ssommelet21** [comment]
> googleRenderer={"LEGACY"} does not seems to have any effect on the issue anymore

Thanks, Sherlock Holmes — that's exactly what I said in my comment back on July 3, 2024.

**Comment by richstimson** [comment]
How is this not fixed when it used to work in 1.7.1?

**Comment by karuzo17** [comment]
We are experiencing the same issue with "react-native": "0.79.2" and "react-native-maps": "^1.18.0". Has anyone find a solution yet ?

**Comment by nBalotis** [comment]
have the same problem.  with with "react-native": "0.79.2" and "react-native-maps": "^1.23.8" any solution?

**Comment by kkx64** [comment]
Why is this closed lol it's still very much a problem, I'm getting crash reports as well

**Comment by ssommelet21** [comment]
> Why is this closed lol it's still very much a problem, I'm getting crash reports as well

Maybe using expo & expo-maps is the way to go :

https://docs.expo.dev/versions/latest/sdk/maps/

react-native-maps is dead

**Comment by fuelkoy** [comment]
My working solution was to set a small period (for example 1s) where tracksViewChanges in true and then turn it to false. With this the markers display at the map but don't flicker after the state is false. Caveat is that they can flicker when the state is yet true.

This is at least better than nothing and works in our use case 😊

```
  const [tracksViewChanges, setTracksViewChanges] = React.useState(true);

  React.useEffect(() => {
    setTimeout(() => {
      setTracksViewChanges(false);
    }, TRACK_VIEW_CHANGES_TIMEOUT);
  }, []);
```
