### ISSUE TITLE
download map and save in pdf,png 

### ISSUE THREAD

**Issue by cdci-gsoftconsulting** [react-native-maps/react-native-maps#5002]
### Summary

hi can i download whole save and save in pdf,png...

### Reproducible sample code

```TSX
hi can i download whole save and save in pdf,png...
```

### Steps to reproduce

unable to find any method for this
hi can i download whole save and save in pdf,png...

### Expected result

download whole save and save in pdf,png...

### Actual result

no method found

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.73

### What version of Expo are you using?

Not using Expo

### Device(s)

both android/ios

### Additional information

hi can i download whole save and save in pdf,png...

**Comment by jan-kozinski** [comment]
You can experiment with the "liteMode" prop on MapView component. It will render the map as a bitmap image so if you have access to developer tools you might be able to download it. Just be aware that enabling the liteMode makes the map irresponsive to gestures, so no zooming or moving around.
[liteMode](https://developers.google.com/maps/documentation/android-sdk/lite#overview_of_lite_mode)

**Comment by salah-ghanim** [comment]
@cdci-gsoftconsulting this is out of scope for this project, you should be able to do it on iOS though, check: https://stackoverflow.com/questions/31020608/convert-uiview-to-png-in-swift

android, I'm not so sure, since google doesn't use native views logic
