### ISSUE TITLE
Marker blinking issue

### ISSUE THREAD

**Issue by JoshiGautamB** [react-native-maps/react-native-maps#5008]
### Summary

On Android side, I am currently facing issue when i use marker. Markers are blinking automatically in map

### Reproducible sample code

```TSX
<Marker
          
            onPress={() => {
              console.log("Clicked");
              setselected(spot);
            }}
            key={spot._id}
            // image={selected == spot ? images.MapPathThree : images.GreenMarker}
            coordinate={{
              latitude: parseFloat(spot.latitude),
              longitude: parseFloat(spot.longitude),
            }}
          >
            <View>
              <Image
                source={
                  selected === spot ? images.MapPathThree : images.GreenMarker
                }
                style={{
                  width: 55,
                  height: 55,
                  tintColor: selected === spot ? colors.redFF4F5A : "#004D16",
                }} // Adjust the size of the image as needed
              />
              <Text
                style={{
                  color: selected === spot ? colors.white : colors.white,
                  fontSize: fontSize.size14,
                  fontFamily: fontFamily.bold,
                  position: "absolute",
                  alignSelf: "center",
                  top: "25%",
                }}
              >
                {Currency}
                {spot.charges}
              </Text>
            </View>
          </Marker>
```

### Steps to reproduce

In android using markers

### Expected result

I have to stop that from happening.

### Actual result

Currently, markers are blinking on android side

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.15

### What version of Expo are you using?

Not using Expo

### Device(s)

Android

**Comment by vijaydiyyala842** [comment]
Same issue But not in andorid , in ios I am facing that markers blinking issue

**Comment by gkpo** [comment]
Just realised I created a duplicate, sorry ^^
Also added a video screenshot of the issue.
Referencing it here: https://github.com/react-native-maps/react-native-maps/issues/5009

**Comment by seyedmostafahasani** [comment]
@JoshiGautamB, you can use the tracksViewChanges prop and set it to false. It should work correctly.

**Comment by Saliheen** [comment]
`tracksViewChanges = {false}` 

works for me

**Comment by jan-kozinski** [comment]
Hi, thanks for reporting this. We're aware of the issue and are trying to fix it urgently. As other mentioned, this is a duplicate of https://github.com/react-native-maps/react-native-maps/issues/4997 so I'm closing this issue

**Comment by azlisamshudin** [comment]
> `tracksViewChanges = {false}`
> 
> works for me

thanks, works for me too

**Comment by fatima-elboubakri** [comment]
where should I put it **tracksViewChanges = {false}** ?

**Comment by seyedmostafahasani** [comment]
@fatima-elboubakri you must use it in Marker, as shown below.
```
<Marker
   ....
   tracksViewChanges={false}
   ....
/>
```

**Comment by melyux** [comment]
If I use that, my markers disappear after a while.

**Comment by emaxedon** [comment]
I'm having this same issue. I believe it is causing a memory leak which is leading to an out of memory error... I'm not sure if the blinking markers are related though.

**Comment by konikjoshi3** [comment]
> If I use that, my markers disappear after a while.

i am facing the same issue as soon as i add tracksViewChanges={false} marker disappears

**Comment by JennieCrowel** [comment]
This is basic when you want to use maps and it's not working.......

**Comment by secretdev710** [comment]
Setting tracksViewChanges={false} is not a good solution.
Sometimes we need to update Markers in specific cases and tracksViewChanges must be true.
Thus, flickering issue must be fixed.

**Comment by TonyHamame** [comment]
After hours of searching I found the solution thanks to ChatGPT...
What we have to do is set `tracksViewChanges` of `Marker` to false after the Images have loaded...
```tsx
function MyComponent({props}) {
	const [markersNotReady, setMarkersNotReady] = useState(true);

	return(
		<Marker {...props} tracksViewChanges={markersNotReady}>
			<Image source={"..."} onLoad={() => setMarkersNotReady(false)} />
		</Marker>
	)
}

**Comment by amitpdev** [comment]
With `tracksViewChanges` = `false` marker is not rendering text over the image.
I was able to solved it with:

```js

const MapMarker => {
	const markerRef = useRef(null);
    
	return (
        <Marker
   	    ref={markerRef}
            tracksViewChanges={false}
            image={markerImage}
            onLayout={() => {
			markerRef.current?.redraw();
            }}
	>
	    <Text>MarkerLand</Text>
        </Marker>
    );
});

```

**Comment by msafieddine** [comment]
Had the same issue, couldn't use tracksViewChanges={false} as I was doing some animation in the marker

SOLUTION: Wrap your marker component in React.memo and gg it works

**Comment by iamvinny** [comment]
I'm on version `1.20.1` because it's packed in Expo Go, has this issue been fixed on more recent version or it still exists?

**Comment by iamvinny** [comment]
> After hours of searching I found the solution thanks to ChatGPT... What we have to do is set `tracksViewChanges` of `Marker` to false after the Images have loaded...
> 
> function MyComponent({props}) {
> 	const [markersNotReady, setMarkersNotReady] = useState(true);
> 
> 	return(
> 		<Marker {...props} tracksViewChanges={markersNotReady}>
> 			<Image source={"..."} onLoad={() => setMarkersNotReady(false)} />
> 		</Marker>
> 	)
> }

Nice workaround! For those who use an icon (`View`) instead of an image, you can do as follow:

```tsx
import { useRef, useState } from 'react';

const [markersNotReady, setMarkersNotReady] = useState(true);

<Marker coordinate={{ latitude: deliveryLat, longitude: deliveryLng }} tracksViewChanges={markersNotReady} >
    <View style={[styles.marker, { backgroundColor: '#047857' }]} onLayout={() => setMarkersNotReady(false)}>
        <FontAwesome name="home" color="#fff" size={10} />
    </View>
</Marker>

const styles = StyleSheet.create({
    marker: {
        width: 25,
        height: 25,
        borderRadius: 9999,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#fff',
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
    }
});
```
