### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-google-maps"

### ISSUE THREAD

**Issue by Kowshika-aspire** [react-native-maps/react-native-maps#5011]
### Summary

I'm trying to upgrade react-native-google-maps version from 0.29.3 to 1.11.3. And when I tried to do pod install, I'm getting CocoaPods could not find compatible versions for pod "react-native-google-maps error in Mac M1.

<img width="1275" alt="Screenshot 2024-03-26 at 6 11 29 PM" src="https://github.com/react-native-maps/react-native-maps/assets/96066863/45034636-931a-45e3-9e39-41b29150788d">

### Reproducible sample code

```TSX
My podfile:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
	
 	platform :ios, min_ios_version_supported
  prepare_react_native_project!

  # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
	# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
	#
	# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
	# 
	# module.exports = {
	#   dependencies: {
	#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
	# 
	flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  	use_frameworks! :linkage => linkage.to_sym
  end

target 'MyApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  #  match the build configurations defined in package.json xcodeSchemes
  project 'MyApp', 'QA-Debug' => :debug, 'QA-IAP-Debug' => :debug, 'Staging-Debug' => :debug, 'Production-Debug' => :debug, 'QA-Release' => :release, 'QA-IAP-Release' => :release, 'Staging-Release' => :release, 'Production-Release' => :release

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  dynamic_frameworks = ['Leanplum-iOS-SDK']

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BugsnagReactNative', :path => '../node_modules/@bugsnag/react-native'
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNTestFlight', :path => '../node_modules/react-native-test-flight'

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if dynamic_frameworks.include?(pod.name)
          puts "Setting dynamic linking for #{pod.name}"
          def pod.build_type;
            Pod::BuildType.dynamic_framework
          end
        end
      end
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  #pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec', :modular_headers => false

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  # React Native third party dependencies podspecs
  #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

  #target 'MyApp' do
    #inherit! :complete
    # Pods for testing
  #end

  post_install do |installer|
      react_native_post_install(
       installer,
       :mac_catalyst_enabled => false
     )
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
          config.build_settings['DEVELOPMENT_TEAM'] = '5EWDLEP4Y9'
        end
      end
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
      if target.name == 'yoga'
        target.remove_from_project
        target.build_configurations.each do |config|
            config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
            config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
        end
      end
    end
  end
end
```

### Steps to reproduce

Try upgrading 1.11.3 from 0.29.3 

### Expected result

I should able to do pod install without pod errors.

### Actual result

<img width="1275" alt="Screenshot 2024-03-26 at 6 11 29 PM" src="https://github.com/react-native-maps/react-native-maps/assets/96066863/679b7147-2872-45eb-9034-0ae931904b59">

### React Native Maps Version

1.11.3

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.10

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone

**Comment by vivianmauer** [comment]
Probably the value of the env variable `min_ios_version_supported` is less than 13.4

**Comment by Kowshika-aspire** [comment]
> Probably the value of the env variable `min_ios_version_supported` is less than 13.4

Tried changing `min_ios_version_supported` to 13.4. But still no luck.

**Comment by Kowshika-aspire** [comment]
What's the minimum deployment version to upgrade 1.11.3 ?

**Comment by FaggioniHQ** [comment]
Hello There,

Any workaround to solve this issue?

Thanks in advance

**Comment by ermarin** [comment]
Hello guys, some request about of this bug?
For the moment i used the version number 1.3.2, if compiled fine and i use Expo
I wait for some update...

Regards

**Comment by salah-ghanim** [comment]
@Kowshika-aspire @FaggioniHQ @ermarin please don't assume that the latest version of react-native-maps is backward compatible with previous react-native versions, especially when react-native itself is introducing breaking changes.

please update to react-native 0.73 or ideally 0.74 to use the latest version, since min iOS requirement was increased to 13.4 as of react-native 0.73

**Comment by ermarin** [comment]
Sorry, however this is not a solution for the problem reported and i go use the version past
Thanks for the comment

**Comment by virenradadiya** [comment]
To resolve the issue, add the following lines to your Podfile, then run `pod install`:

```
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
```

If this doesn't work, the issue might be that the `min_ios_version_supported` environment variable is set to a value lower than `13.4`. In that case, change `min_ios_version_supported` to `13.4`, then run `pod install` again.

**Comment by mare95** [comment]
This is happening on new arch
`No podspec found for 'react-native-google-maps' in '../node_modules/react-native-maps'`

I also tried @virenradadiya suggestion but still the same error.


Here are my dependencies
```
react: 19.0.0
react-native: 0.79.2
react-native-maps ^1.23.7
```

And even if i set min_ios_version_supported to 16 still doesn't work
`platform :ios, '16.0'`

**Comment by mare95** [comment]
Just figured out that it's documented in [installation.md](https://github.com/react-native-maps/react-native-maps/blob/HEAD/docs/installation.md)😅 

```
 rn_maps_path = '../node_modules/react-native-maps'
 pod 'react-native-maps/Google', :path => rn_maps_path
```

**Comment by jasimkhan-ariprodesign** [comment]
hi guys i actually missed s when i was installing pls make sure you have right cmd
i resolve my error by installing right package:

my problem was "react-native-map" instead of this "react-native-maps"

this is old method:
$ npm install react-native-maps
# --- or ---
$ yarn add react-native-maps

$ (cd ios && pod install)
# --- or ---
$ npx pod-install

+ #import <GoogleMaps/GoogleMaps.h>

@implementation AppDelegate
...

(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
+  [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; // add this line using the api key obtained from Google Console
...

# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

for latest version i am on :
    "react": "19.1.0",
    "react-native": "0.80.1",

DO THIS:

import GoogleMaps instead of #import <GoogleMaps/GoogleMaps.h> 👈🏻👈🏻👈🏻👈🏻👈🏻 step 1


AppDelegate.swift

  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    GMSServices.provideAPIKey("YOUR_API_KEY") 👈🏻👈🏻👈🏻👈🏻👈🏻 step 2
    let delegate = ReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    window = UIWindow(frame: UIScreen.main.bounds)

    factory.startReactNative(
      withModuleName: "Q3Car",
      in: window,
      launchOptions: launchOptions
    )

    return true
  }

at last  👇🏻 step 3

Add the following to your Podfile above the use_native_modules! function and run pod install in the ios folder:

# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

**Comment by EQua-Dev** [comment]
Run this from your project root:

``` shell
grep -Rni "platform" node_modules/react-native-maps/react-native-maps.podspec
```

It will show the exact line:

```s.platform     = :ios, "XX.X"```

Bump your 
```platform :ios, ``` and 

```config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']``` (if applicable)

to that version and run pod install again.

Hope this helps.
