### ISSUE TITLE
Subview flickering on children index changes

### ISSUE THREAD

**Issue by night** [react-native-maps/react-native-maps#5014]
### Summary

When using react-native-maps with dynamic/changing `Marker` children arrays, memoization appears not enough to prevent render flicker.

I suspect from reading the native source code that this may be caused by annotations being added and removed on the native side, instead of preserving existing annotations added. More specifically, I think on the native side you may be receiving `insertReactSubview` and `removeReactSubview` when indexes change for a subview, even when that subview's reference is not changing.

After trying to debug and work around this issue, I found that explicitly passing an array of children at fixed indices, I can add and remove children without seeing subview flicker.

### Reproducible sample code

```TSX
import React, {useEffect, useState} from 'react';
import MapView, {Marker} from 'react-native-maps';

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

export default function App() {
  const [markers, setMarkers] = useState([
    {latitude: 37.8067698, longitude: -122.4578827},
    {latitude: 37.7735338, longitude: -122.4635475},
    {latitude: 37.7552137, longitude: -122.4405449},
    {latitude: 37.8047354, longitude: -122.4206322},
    {latitude: 37.7858175, longitude: -122.5035452},
  ]);

  useEffect(() => {
    setInterval(() => {
      // if you comment out the following shuffleArray line, the flickering stops.
      shuffleArray(markers);
      setMarkers([...markers]);
    }, 1000);
  }, []);

  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        longitude: -122.4194,
        latitude: 37.7749,
        latitudeDelta: 0.1,
        longitudeDelta: 0.2,
      }}>
      {markers.map((coordinate) => (
        <Marker
          key={`marker_${coordinate.latitude}_${coordinate.longitude}`}
          coordinate={coordinate}
          tracksViewChanges={false}
        />
      ))}
    </MapView>
  );
}
```

https://github.com/react-native-maps/react-native-maps/assets/2942184/a6e7d1a5-9dac-423f-9d47-b9a1ea01cef4

### Steps to reproduce

Load the sample code provided. Notice that the library re-renders Markers with a flicker instead of keeping the existing Markers rendered.

### Expected result

Children should be able to be resorted without subview re-render.

### Actual result

Subviews are re-rendered.

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.73.4

### What version of Expo are you using?

50

### Device(s)

iPhone 15 Pro (17.3.1)

**Comment by iM-GeeKy** [comment]
Possibly related to https://github.com/react-native-maps/react-native-maps/issues/4997#issuecomment-2016608726

**Comment by salah-ghanim** [comment]
@night In the new release you can use googleRenderer={'LEGACY'} as a MapView property to avoid being forced to use the latestRenderer and deal with this bug.

Please reopen if that doesn't solve the issue

**Comment by night** [comment]
@salah-ghanim this is using iOS and Apple Maps though?

**Comment by quentinnippert** [comment]
@night I had the same problem, I had to remove the `^` in front of the version number so that it wouldn't update the library to the most recent minor version. 

For me :

**Before** :
`"react-native-maps": "^1.8.2",`
**After** : 
`"react-native-maps": "1.8.2",`

**Comment by ssommelet21** [comment]
> @night I just tested with a fresh react-native project (latest) and latest library version ... no flickering so closing this issue for now see: https://github.com/salah-ghanim/MapFlickerTest
> 
> and the video attached:
> 
>  RPReplay_Final1712335087_map.mov

Of course you use tracksViewChanges={false}
