### ISSUE TITLE
Invariant Violation: Event cannot be both direct and bubbling: topSelect

### ISSUE THREAD

**Issue by kuldipopenxcell** [react-native-maps/react-native-maps#5030]
### Summary

When I use Marker in MapView component I get error in android: 

Invariant Violation: Event cannot be both direct and bubbling: topSelect

This error is located at:
    in AIRMapMarker (created by MapMarker)
    in MapMarker (created by MapPage)
    in AIRMap (created by MapView)
    in MapView (created by MapPage)
    in RCTView (created by View)
    in View (created by MapPage)
    in MapPage (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by BottomNavigation)
    in BottomNavigation (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by AppNavigation)
    in AppNavigation (created by RootNavigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by RootNavigation)
    in RootNavigation (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Envitely(RootComponent), js engine: hermes

### Reproducible sample code

```TSX
import {Image, View} from 'react-native';
import React from 'react';
import {styles} from './style';
import MapView, {Marker, PROVIDER_GOOGLE} from 'react-native-maps'; 

const MapPage = () => {
  return (
    <View style={styles.container}>
      <MapView
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}>
        <Marker coordinate={{latitude: 37.78825, longitude: -122.4324}}>
          <Image source={images.marker} style={styles.marker} />
        </Marker>
      </MapView>
    </View>
  );
};

export default MapPage;
```

### Steps to reproduce

1. yarn add react-native-maps 
2. Add your API key to your manifest file (android/app/src/main/AndroidManifest.xml)
3. Add Marker component inside MapView.

### Expected result

Map Marker shows without any error. 

### Actual result

It throws error: Invariant Violation: Event cannot be both direct and bubbling: topSelect

![Screenshot 2024-04-12 at 2 35 45 PM](https://github.com/react-native-maps/react-native-maps/assets/166806638/b2c86112-b984-413d-91ba-91f6f9fc848c)

### React Native Maps Version

^1.13.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel_3a_API_34 Emulator

### Additional information

If i don't use Marker then map works fine.

**Comment by salah-ghanim** [comment]
@kuldipopenxcell this was just fixed, thanks for reporting

**Comment by musthafa-pa** [comment]
Hi @salah-ghanim - I'm facing the same issue in react native version 0.79.0 and react-native-maps version 1.21.0. Below is my minimal reproducible example

`import React, { useEffect, useRef } from "react";
import { Platform, StyleSheet, View } from "react-native";
import MapView, { Marker } from "react-native-maps";

export default function SimpleMap() {
  const mapRef = useRef(null);
  const region = {
    latitude: 28.6139,
    longitude: 77.209,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
  };

  const manuallyTriggerMapReady = async () => {
    const mapInstance = mapRef.current as any;
    if (mapInstance && mapInstance._onMapReady) {
      await mapInstance._onMapReady();
      console.log("✅ Manually triggered map ready");
      mapRef.current?.animateToRegion(region, 1000);
    }
  };

  useEffect(() => {
    setTimeout(() => {
      console.log("⏳ Entered map ready fallback effect");
      if (Platform.OS === "android") {
        manuallyTriggerMapReady();
      }
    }, 2000);
  }, []);

  return (
    <View style={styles.container}>
      <MapView
        ref={mapRef}
        style={styles.map}
        provider="google"
        initialRegion={region}
        onMapReady={() => {
          console.log("✅ Map is ready");
        }}>
        <Marker coordinate={{ latitude: 28.6139, longitude: 77.209 }} />
      </MapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});
`
