### ISSUE TITLE
"googleMapId" not working on IOS

### ISSUE THREAD

**Issue by demoox** [react-native-maps/react-native-maps#5038]
### Summary

The **googleMapId** attribute does not seem to have any effect on IOS compared to the **customMapStyle** attribute which works very well.

As you probably know, the JSON personalization system will soon be deprecated to make way for cloud-based card personalization.

### Reproducible sample code

```TSX
<MapView 
style={{ flex: 1 }} 
provider={PROVIDER_GOOGLE}
googleMapId='XXXXXXXXXXX'
initialRegion={{
  latitude: lat,
  longitude: lng,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421
}}
showsUserLocation={true}
showsMyLocationButton={true}
>
```

### Steps to reproduce

Create a map style on the cloud, then get the map id and set it in the "**googleMapId**" attribute

### Expected result

.

### Actual result

The default map style is applied instead of the map with the defined id.

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.2

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone XS Max

**Comment by mateki0** [comment]
Hi @demoox. If I understood correctly it is not possible yet on iOS. We have to wait for new version of Google Maps SDK for iOS.
See description in Salah's PR.
https://github.com/react-native-maps/react-native-maps/pull/4922
```
Unfortunately for iOS without updating to google-maps SDK v 8.2 the style won't be visible .. waiting on google
```

**Comment by demoox** [comment]
Hi @mateki0 thank you for your reply.

Oh yes indeed! Hopefully the update will be done quickly :)

**Comment by raul364** [comment]
Has this been fixed yet?
