### ISSUE TITLE
Error on startup on react-native 0.74 Bridgeless New Architecture

### ISSUE THREAD

**Issue by mHvNG** [react-native-maps/react-native-maps#5042]
### Summary

Hi, 

While testing the Bridgeless New Architecture of react-native 0.74 I got the following error `(NOBRIDGE) ERROR  Error: Exception in HostFunction: <unknown>` and the following in Xcode `SurfaceRegistryBinding::startSurface failed. Global was not installed.`.

I have ran the entire installation process step by step and the error starts when I add the following to my `Podfile`:
```
# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
```

The following screenshot is directly after the bundle was successful.

![Simulator Screenshot - iPhone 15 Pro - 2024-04-25 at 14 29 38](https://github.com/react-native-maps/react-native-maps/assets/39901096/40b21cbe-cfed-4740-a3a3-614ff5bc760f)

If I'm doing something incorrect I wouldn't know where. 

### Reproducible sample code

```TSX
Not necessary. It happens before you can even think about implementing a MapView in the App.
```

### Steps to reproduce

Follow the installation instructions on react-native 0.74 with the Bridgeless New Architecture enabled. Once you're at the following step the error will show itself.

```
# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
```

### Expected result

I would like to see the app actually start. 

### Actual result

Crash on startup

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.74.0

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 15 Pro (Simulator)

**Comment by mateki0** [comment]
Hi, @mHvNG. Can you show me your AppDelegate.mm? I had the same problem and deleting these booleans helped me

```
- (BOOL)turboModuleEnabled {
  return true;
}


- (BOOL)fabricEnabled{
  return true;
}

- (BOOL)bridgelessEnabled
{
    return YES;
}
```

**Comment by mHvNG** [comment]
Sadly I don't have those booleans... My `AppDelegate.mm`:

```
#import "AppDelegate.h"
//#import <GoogleMaps/GoogleMaps.h>

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
//  [GMSServices provideAPIKey:@"API_KEY"]; // add this line using the api key obtained from Google Console
  
  self.moduleName = @"AppName";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self bundleURL];
}

- (NSURL *)bundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by mHvNG** [comment]
@mateki0 I did some further testing to get the cause of the error or at least close enough. When I install react-native-maps with yarn and add the following to the `Podfile` everything is well:

```
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
```

App startup is fine and when using with provider Apple Maps everything works and I can see and interact with the map. However when I add the following to the Podfile I get the error (stated above):

```
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```

You install the following during a `npx pod install`:

```
Installing Google-Maps-iOS-Utils (4.2.2)
Installing GoogleMaps (7.4.0)
Installing react-native-google-maps (1.14.0)
```

My personal conclusion would be that it's an error on the Google Maps side of the library. I hope this helps somewhat.

**Comment by mateki0** [comment]
Thanks for checking. I see one difference between your and ours podfile. Can you try with this code?
```
  rn_maps_path = '../..'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps', :path => rn_maps_path
```

I know that it's missing in documentation, but this line **pod 'react-native-maps', :path => rn_maps_path** was added to our example app 2 months ago so maybe it's needed now and docs should be updated.

Here is whole Podfile of example app with RN 0.74:
https://github.com/TheWidlarzGroup/react-native-maps/blob/chore/bump-example-rn-to-0.74/example/ios/Podfile

**Comment by mHvNG** [comment]
By removing this:

```
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps', :path => rn_maps_path
```

And adding this:

```
  rn_maps_path = '../..'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps', :path => rn_maps_path
```

I get the following error message:

```
[!] There are multiple dependencies with different sources for `react-native-maps` in `Podfile`:

- react-native-maps (from `../node_modules/react-native-maps`)
- react-native-maps (from `../..`)
```

I tried the `pod deintegrate` and `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` again and it still gave the same error. It only seems to take `../node_modules/react-native-maps` as an answer to install.

**Comment by mateki0** [comment]
Sorry for missleading @mHvNG I meant to put there these 3 lines.
```
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'react-native-maps', :path => rn_maps_path
```
But now I saw that it doesn't change anything. And you are right, there's a crash. Deleting code from appDelegate helped me because I turned off new arch which you are turning on with pod install command.

Unfortunately I don't know how to fix it or if we are even able to do it. Maybe @brentvatne or @lukmccall are able to help here?

**Comment by mHvNG** [comment]
> Edit: It's happening on clean rn 0.74 project with turned on new arch, so it's quite easy to reproduce

Yup, it's not difficult to encounter the crash. I saw that version 1.14.0 brought support for the new architecture, however at the moment it's only working without the `pod 'react-native-google-maps', :path => rn_maps_path` within the Podfile. 

It's working fine when I'm working with Apple Maps as the provider.

**Comment by mrousavy** [comment]
Hey - I'm seeing the same issue with react-native-mmkv, not sure what exactly is causing this. 
![image](https://github.com/react-native-maps/react-native-maps/assets/15199031/5b91675c-9dc4-4020-b4e1-5b4dd88c4756)

**Comment by mHvNG** [comment]
@mrousavy The error message itself isn't helpful unfortunately. I'm way too busy developing apps for clients to start and contribute open source libraries for RN at the moment, so my understanding of the migration from old to new architecture isn't up-to-date unfortunately. 

However it's weird that one `Pod` runs perfectly fine, but the `Pod`: `react-native-google-maps` crashes instantly while the bundle process finished just fine. It wouldn't shock me if there's something not 100% right within `react-native` 0.74 itself.

**Comment by mym0404** [comment]
Well, I suffered same. But in my project(app) it doesn't use react-native-maps but mmkv is used. I need to investigate it further.

**Comment by mym0404** [comment]
> Update: it crashes because with Bridgeless mode this function is called in background. The exception that is raised is
> 
> ```
> [AIRGoogleMapManager constantsToExport] threw and exception: The API method must be called from the main thread
> ```
> 
> So we need to fix it in React Native. I don't have a solution right away, but the fix will come.

Can you share how to trace log in this issue? It will be a great help for finding our common issues.

**Comment by cipolleschi** [comment]
@mym0404 sure!

1. I enabled a feature of Xcode breakpoints which is `Exception Breakpoints`

<img width="517" alt="Screenshot_2024-04-30_at_14 36 05" src="https://github.com/react-native-maps/react-native-maps/assets/11162307/221a5103-7188-4f4b-b343-0fc30e456874">

2. I run the app and see that the `constantsToExport` was raising an exception.
At this point, I had few ways to go:

* I tried to replace the `[GMSServices openSourceLicenseInfo];` line with an empty string => no crashes and no redboxes
* I wrapped the `[GMSService openSourceLicenseInfo];` in a try-catch block to see the exception
```
@try {
    license = [GMSServices openSourceLicenseInfo];
  } @catch (NSException *ex) {
    NSLog(@"[GMSServices openSourceLicenseInfo] threw and exception: %@",  ex);
  }
```

**Comment by matt-dalton** [comment]
FWIW I am getting this and don't use react-native-maps. I _do_ use mmkv, and have upgraded to the `3.0.0-beta.4` release to remain compliant with 0.74.

**Comment by cipolleschi** [comment]
@matt-dalton @mrousavy let's move the MMKV discussion to the MMKV repo, so we can close this issue for maps.

**Comment by mateki0** [comment]
@mHvNG It works fine for me on 0.74.1. Can you confirm that so we can close the issue?

**Comment by rodrigodiasf1984** [comment]
i managed to install the pods with these modifications at the PodFile on the react-native 0.74.1 
`rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'react-native-maps', :path => rn_maps_path`

but the build crashes, any idea how to solve it? 
#include <react/debug/react_native_assert.h> 'react/debug/react_native_assert.h' file not found
![image](https://github.com/react-native-maps/react-native-maps/assets/30758309/1768eab1-6337-488b-a673-b26666fe1188)

**Comment by mateki0** [comment]
@rodrigodiasf1984 there was similar issue in the past opened in react-native repository, maybe you will find something helpful there. If not please open separate issue with your package.json and whole Podfile because I don't think it's connected with this one.
https://github.com/facebook/react-native/issues/38283

**Comment by mHvNG** [comment]
> @mHvNG It works fine for me on 0.74.1. Can you confirm that so we can close the issue?
@mateki0 I'll check when I get home from work. I'll close the issue when all is working.

**Comment by RichardLindhout** [comment]
I had this crash en it was fixed after installing expo-dev-client somehow...

**Comment by RohovDmytro** [comment]
Having same an issue with 0.77.0

**Comment by SimranDev** [comment]
Having same issue with 0.78.0

**Comment by gauravhira** [comment]
Same issue in RN `v0.79.2`

**Comment by delphinebugner** [comment]
In my case, I had the issue because I killed too many background process using `kill -9 <PID>` command (I thought I was killing metro, turns out I killed something more)
Restarting the computer did the job 😁

**Comment by krolow** [comment]
have u guys figure it out? facing that today while trying to update the project to latest expo/react native

**Comment by Leo-071100** [comment]
Same issue in ´0.79.5´

**Comment by Sechorda** [comment]
> have u guys figure it out? facing that today while trying to update the project to latest expo/react native

Same, ever resolve?
