### ISSUE TITLE
Rn074 build ios failed

### ISSUE THREAD

**Issue by rodrigodiasf1984** [react-native-maps/react-native-maps#5048]
### Summary

I've just created a new project with react-native 0.74.1 and I'm installing all the libs I need for the project, when I installed this  lib I encountered an error in installing pods, so I saw an issue where I found how to fix the problem, but when I build the app for ios I've got this error: 

![image](https://github.com/react-native-maps/react-native-maps/assets/30758309/eec6b009-dce0-486f-a789-625d9a9485bb)

### Reproducible sample code

```TSX
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator \"IphoneX\"",
    "start": "react-native start",
    "device": "react-native run-android --variant=release",
    "lint": "eslint --ext .tsx --ext .ts src/",
    "typecheck": "tsc --project tsconfig.json --noEmit",
    "clean-project": "react-native-clean-project",
    "clean-android": "cd android && ./gradlew --stop && ./gradlew clean",
    "bundle": "cd android && ./gradlew bundleRelease",
    "build-apk": "cd android && ./gradlew assembleRelease",
    "install-apk": "adb install app-release.apk",
    "pod": "cd ios && pod install && cd ..",
    "test": "jest --passWithNoTests --no-cache --runInBand",
    "test:watch": "jest --watch",
    "clear_jest": "jest --clearCache",
    "clear-branches": "git branch | grep -v \"dev\" | xargs git branch -D && git fetch --prune"
  },
  "dependencies": {
    "@aws-amplify/api": "^5.4.4",
    "@gorhom/bottom-sheet": "^4",
    "@hookform/resolvers": "^3.3.4",
    "@notifee/react-native": "^7.8.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "^8.0.0",
    "@react-native-community/netinfo": "^11.3.1",
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/messaging": "^19.2.2",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@sentry/react-native": "^5.22.1",
    "date-fns": "^2.29.3",
    "lottie-react-native": "^6.7.2",
    "nativewind": "^2.0.11",
    "phosphor-react-native": "^2.0.0",
    "react": "18.2.0",
    "react-hook-form": "^7.51.4",
    "react-native": "0.74.1",
    "react-native-actions-sheet": "^0.9.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-biometrics": "^3.0.1",
    "react-native-confirmation-code-field": "^7.4.0",
    "react-native-contacts": "^7.0.8",
    "react-native-country-codes-picker": "^2.3.5",
    "react-native-credit-card-input-plus": "^0.4.8",
    "react-native-device-info": "^10.13.2",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-flash-message": "^0.4.2",
    "react-native-floating-label-input": "^1.4.3",
    "react-native-gesture-handler": "^2.16.1",
    "react-native-google-places-autocomplete": "^2.5.6",
    "react-native-image-crop-picker": "^0.41.0",
    "react-native-international-phone-number": "^0.7.6",
    "react-native-maps": "^1.15.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-open-maps": "^0.4.3",
    "react-native-permissions": "^4.1.5",
    "react-native-reanimated": "^3.11.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-star-svg-rating": "^1.8.3",
    "react-native-svg": "^15.2.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-version-check": "^3.4.7",
    "react-native-webview": "^13.10.0",
    "rn-swipe-button": "^1.3.8",
    "rn-tooltip": "^3.0.3",
    "rn-tourguide": "^3.3.0",
    "yup": "^1.4.0",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@eslint/js": "^9.2.0",
    "@react-native/babel-preset": "0.74.83",
    "@react-native/eslint-config": "0.74.83",
    "@react-native/metro-config": "0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-native": "^12.5.0",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^9.2.0",
    "eslint-plugin-react": "^7.34.1",
    "jest": "^29.7.0",
    "jest-transform-stub": "^2.0.0",
    "prettier": "3.2.5",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4",
    "typescript-eslint": "^7.8.0"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}
```

### Steps to reproduce

install the package JSON on the react-native 0.74.1, run pod install and try to build 

### Expected result

build without error 

### Actual result

build crashes with the error: #include <react/debug/react_native_assert.h> 'react/debug/react_native_assert.h' file not found

I've followed the instructions on this issue without success: https://github.com/facebook/react-native/issues/38283

### React Native Maps Version

"react-native-maps": "^1.15.1"

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.74.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Iphone x

### Additional information

my pod file: 

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'parksharing' do
  config = use_native_modules!
  
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
     privacy_file_aggregation_enabled: false
  )
  target 'parksharingTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

**Comment by rodrigodiasf1984** [comment]
for those who are facing the same issue, you must to add this to your pod file before the code  "target 'myAppTests' do"

` rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true`

so you runt this command on the ios folder: 
`USE_FRAMEWORKS=static bundle exec pod install`

I'm closing the issue, thanks

**Comment by ororsatti** [comment]
this is still an issue, the solution above didnt fix it. when you try to pod install you still get an error
