### ISSUE TITLE
Are you considering upgrading GoogleMaps to 8.4.0?

### ISSUE THREAD

**Issue by TrustDec** [react-native-maps/react-native-maps#5051]
### Summary

The latest version of GoogleMaps is 8.4.0, but the version used by react-native-maps is 7.4.0

[iOS sdk release notes](https://developers.google.com/maps/documentation/ios-sdk/release-notes)

### Reproducible sample code

```TSX
react-native-google-maps.podspec
 s.dependency 'GoogleMaps', '7.4.0'
 s.dependency 'Google-Maps-iOS-Utils', '4.2.2'
```

### Steps to reproduce

No need to reproduce

### Expected result

s.dependency 'GoogleMaps', 7.4.0'

### Actual result

s.dependency 'GoogleMaps', 8.4.0'

### React Native Maps Version

any

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

any

### What version of Expo are you using?

Not using Expo

### Device(s)

any

**Comment by salah-ghanim** [comment]
@TrustDec the problem is that the google-maps-ios-utils don't support the latest google-maps, so we're blocked since iOS utils are used in our library.
hopefully google team will eventually merge this pull request, in the meantime nothing much we can do.
https://github.com/googlemaps/google-maps-ios-utils/pull/451


of course you can always patch the library yourself to solve this issue which is rather easy to do

**Comment by TrustDec** [comment]
Thank you very much for your reply. If I want to update to the latest version of Google Maps. First, I need to modify google-maps-ios-utils as shown in the picture. Then react-native-maps need to be changed? @salah-ghanim 
<img width="1020" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/20201085/960b45c4-2bb3-4da7-b53a-8999ab0c1dc3">

**Comment by zachgibson** [comment]
@salah-ghanim google-maps-ios-utils was just updated last week supporting Google Maps v9. Is there a PR or issue outlining what React Native Maps needs to do to support this?

**Comment by TrustDec** [comment]
There are many adjustments. Please wait patiently. A total of two versions are needed, one is the minimum support for iOS 14+, and the other is the minimum support for ios 15+. @zachgibson
