### ISSUE TITLE
BUG / Polygons not unmounting

### ISSUE THREAD

**Issue by yonitou** [react-native-maps/react-native-maps#5052]
### Summary

Hi

I have a huge issue that is impacting all my app : when using Google Maps provider on Android, the polygons that should be deleted by a state change are not unmounting (and I already tried to use all the unique keys possible in the world including : timestamp, index, identifier or even uuid ...)

### Reproducible sample code

```TSX
<MapView
						mapType="hybrid"
						moveOnMarkerPress={false}
						onRegionChangeComplete{onRegionChangeComplete}
						ref={mapRefCallback}
						zoomEnabled
						zoomTapEnabled
					>
						{RPGFields?.map((field) => {
							return (
								<Polygon
									coordinates{field.coordinates.map(
										(coordinate) => {
											return {
												latitude: coordinate.lat,
												longitude: coordinate.lon
											};
										}
									)}
									
									key={`${field.id}-${currentPosition}`}
									
									
									
								/>
							);
						})}
</MapView>
```

### Steps to reproduce

Copy pate the code bellow and create a state variable storing the `RPGFields` then try to change the state to new polygons (random ones) with different coordinates

### Expected result

The polygons displayed should be synchronized with the state variable

### Actual result

The polygons are not unmounting even with a key that triggers a rerender (because the new polygons don't include the old ones)

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.4

### What version of Expo are you using?

SDK 48

### Device(s)

Android

**Comment by salah-ghanim** [comment]
@yonitou I just tested the mentioned bug and couldn't reproduce on the latest react-native-map version, see the following code:


import React, { useState } from 'react';
import { View, Button, StyleSheet } from 'react-native';
import MapView, { Polygon } from 'react-native-maps';

```
const App = () => {
  const [showPolygon1, setShowPolygon1] = useState(true);

  const polygon1Coordinates = [
    { latitude: 37.8025259, longitude: -122.4351431 },
    { latitude: 37.7896386, longitude: -122.421646 },
    { latitude: 37.7665248, longitude: -122.4161628 },
    { latitude: 37.7734153, longitude: -122.4577787 },
    { latitude: 37.7948605, longitude: -122.4596065 },
  ];

  const polygon2Coordinates = [
    { latitude: 37.7825259, longitude: -122.4251431 },
    { latitude: 37.7696386, longitude: -122.411646 },
    { latitude: 37.7465248, longitude: -122.4061628 },
    { latitude: 37.7534153, longitude: -122.4477787 },
    { latitude: 37.7748605, longitude: -122.4496065 },
  ];

  return (
    <View style={styles.container}>
      <MapView
        style={styles.map}
        mapType="hybrid"
        moveOnMarkerPress={false}
        zoomEnabled
        zoomTapEnabled
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      >
        {showPolygon1 ? (
          <Polygon coordinates={polygon1Coordinates} fillColor="rgba(0, 200, 0, 0.5)" />
        ) : (
          <Polygon coordinates={polygon2Coordinates} fillColor="rgba(200, 0, 0, 0.5)" />
        )}
      </MapView>
      <View style={styles.buttonContainer}>
        <Button title="Show Polygon 1" onPress={() => setShowPolygon1(true)} />
        <Button title="Show Polygon 2" onPress={() => setShowPolygon1(false)} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  buttonContainer: {
    flexDirection: 'row',
    margin: 20,
  },
});

export default App;
```



https://github.com/react-native-maps/react-native-maps/assets/1613032/e62a98b3-d8b2-42df-94e0-0c3d50facf29

please use chatgpt or similar tools to help you debug your code before reporting bugs for open source projects.

**Comment by yonitou** [comment]
Hi 
Thanks for your answer. 

As I said, I don't use the last react native maps version (currently on 1.10.0) but I will try to update it (I wanted to avoid a new build). 

I'll keep you in touch but FYI, if I create a bug report it's because I already searched on the internet for over one week and I think that open source is also for people to help each other. Not trying to bother anyone here and Chat GPT is not as helpful as GitHub issues is. 
Thanks anyway !

**Comment by bruceferguson3** [comment]
@yonitou I'm using the same version as you I believe I just found a fix for our version. Try passing `liteMode={true}` to your `MapView`. That's how I got my `Polygon`s to toggle on and off the screen using Android / Google Maps

**Comment by robsoden** [comment]
I don't feel like this should have been closed, this seems to be a very real bug.

We're on react-native-maps v. 1.15.3 and having this exact problem on android only.

Lite-mode is a non-starter as it's not scrollable, and forcing a redraw of the entire map view will be rough since we have a lot of markers to render.

I believe the difference between OPs example and @salah-ghanim is the use of `ref` - which is definitely necessary for a host of other functionality.

Could this issue be re-opened?

**Comment by yonitou** [comment]
Thanks @robsoden for pointing it. The issue is completely here but maintainers don't want to hear about it ..

**Comment by ebnersilva** [comment]
Same problem here, but in my case i'm using Geojson

**Comment by yonitou** [comment]
I know it's not a "solution" but I switched for Mapbox. It's 10 times better in terms of performance, features and support

**Comment by supriyoMondal** [comment]
any update on this ? facing this issue

**Comment by jeandanyel** [comment]
Facing the issue on Android only :/ 
I'm on 1.10.0

**Comment by gorkemogut** [comment]
Feel free to use the patch below if you are still facing the same problem

[react-native-maps+1.20.1.patch](https://github.com/user-attachments/files/21211276/react-native-maps%2B1.20.1.patch)

**Comment by msafieddine** [comment]
> Feel free to use the patch below if you are still facing the same problem
> 
> [react-native-maps+1.20.1.patch](https://github.com/user-attachments/files/21211276/react-native-maps%2B1.20.1.patch)

@gorkemogut did the patch work for you?

**Comment by gorkemogut** [comment]
Yes, I created and working well for me. It fixes also some crash issues for polygons having unusual shapes

**Comment by msafieddine** [comment]
> Yes, I created and working well for me. It fixes also some crash issues for polygons having unusual shapes

Can you explain your use case pls? In my case, when pin is above a building, I show a polygon, else I dont want to show polygon. However, the polygon on the building stays, it doesnt get unmounted. 

How are you doing this conditional rendering? Are you passing null to the `coordinates` prop?

**Comment by Gugarauj07** [comment]
Anyone knows how to solve this? Having the same issue!

**Comment by gorkemogut** [comment]
The latest (New Architecture) versions broke everything again, and the solutions I implemented don't work, even if I try to adapt them to the new version, synchronous access creates other issues. Any way as I didn't want to spend more time the best approach was to assign new key to the map upon changes (this re-renders the map). You could try something like this:

```
 // Map key for Android re-rendering

 const [selectedRegion, setSelectedRegion] = useState<Region | undefined>(undefined)
 const mapKey = useMemo(() => {
        if (Platform.OS === 'android') {
            const markerKey = markers?.length || 0
            const polygonKey = polygons.length || 0
            return `android-map-${markerKey}-${polygonKey}-${currentLevel}`
        }
        return 'ios-map-stable'
    }, [markers, polygons, currentLevel]) // <--- Assign any object here to trigger re-render and construct mapKey upon that

 const returnSelectedRegion = useMemo(() => {
        if (Platform.OS === 'android') return selectedRegion
        return undefined
    }, [selectedRegion])


 <MapView
         key={mapKey}
         initialRegion={returnSelectedRegion()}
         onRegionChangeComplete={(region) => {
               setSelectedRegion(region)
         }}>
 </MapView>
```

**Comment by gorkemogut** [comment]
> > Yes, I created and working well for me. It fixes also some crash issues for polygons having unusual shapes
> 
> Can you explain your use case pls? In my case, when pin is above a building, I show a polygon, else I dont want to show polygon. However, the polygon on the building stays, it doesnt get unmounted.
> 
> How are you doing this conditional rendering? Are you passing null to the `coordinates` prop?

sorry I didn't see that message. Actually I've changed that block on the code to do the null check itself for coordinates but it is not working anymore with the new packages (RN 0.76+)

**Comment by Gugarauj07** [comment]
@gorkemogut what versions of maps and RN are u using?

**Comment by ralppppy** [comment]
Any update on this?

**Comment by gentil-kadson** [comment]
I'm still facing the same issue
