### ISSUE TITLE
Heatmap ios not working.  was not found in the UIMna

### ISSUE THREAD

**Issue by feritzcan2** [react-native-maps/react-native-maps#5056]
### Summary

Hello, I have a problem with heatmap on ios real device.
Heatmap is working perfectly on android but not working on IOS build. Its a dev build. 
Its an expo project.

My expo sdk is v51. I didnt see it in the list for bug report.

Render Error:
requireNativeComponent "AIRMapHeatmap" was not found in the UIManager.
Any suggestions?
Thank you
 
![image](https://github.com/react-native-maps/react-native-maps/assets/55948243/0b4b59c5-9c73-4c04-bffa-ceff9a4db5ca)

### Reproducible sample code

```TSX
// HeatMap.tsx
import React from 'react';
import { Heatmap } from 'react-native-maps';
import MapView from 'react-native-maps';
import { StyleSheet } from 'react-native';
import { Location } from '@/context/location/locationContext';

interface HeatMapProps {
  locations: Location[];
}

const aggregateLocations = (locations: Location[]) => {
  const locationMap = new Map<string, { latitude: number; longitude: number; weight: number }>();

  locations.forEach((location) => {
    const key = `${location.latitude},${location.longitude}`;
    if (locationMap.has(key)) {
      locationMap.get(key)!.weight += 1;
    } else {
      locationMap.set(key, {
        latitude: location.latitude,
        longitude: location.longitude,
        weight: 1,
      });
    }
  });

  return Array.from(locationMap.values());
};

const HeatMap: React.FC<HeatMapProps> = ({ locations }) => {
  const heatmapPoints = aggregateLocations(locations);

  return (
    <>
      <Heatmap
        points={heatmapPoints}
        radius={40} // Increased radius to make points more connected
        opacity={0.3} // Adjust the opacity for smoother blending
        gradient={{
          colors: ['#ffcccb', '#ffb6c1', '#ff69b4', '#ba55d3', '#9370db', '#8a2be2'],
          startPoints: [0.01, 0.05, 0.1, 0.15, 0.2, 0.3],
          colorMapSize: 256,
        }}
      />
    </>
  );
};

const styles = StyleSheet.create({
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

export default HeatMap;
```

### Steps to reproduce

Create an expo app and use heatmap on ios

### Expected result

see heatmap

### Actual result

![image](https://github.com/react-native-maps/react-native-maps/assets/55948243/eb2fced2-f525-4d55-ba08-749c2b2ca47b)

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.74.1

### What version of Expo are you using?

Not using Expo

### Device(s)

14 pro max

**Comment by feritzcan2** [comment]
still couldnt figure out..

**Comment by pelixpng** [comment]
Does Google Maps work on iOS in your project?

**Comment by MathiasVoie** [comment]
This issue has yet to be fixed.
