### ISSUE TITLE
OOM gms policy maps core dynamite

### ISSUE THREAD

**Issue by chanphiromsok** [react-native-maps/react-native-maps#5062]
### Summary

I receive crashed report analytics from googleplay everyday cause from out of memory for mapview I use for driver app and long running

here crashed log
[crashed.txt](https://github.com/react-native-maps/react-native-maps/files/15397905/crashed.txt)

### Reproducible sample code

```TSX
<MapView
          initialCamera={initialCamera}
          ref={mapRef}
          showsCompass={false}
          onPanDrag={() => {
            cancelAnimationFrame(animationIdRef.current);
          }}
          paddingAdjustmentBehavior="never"
          style={mapStyle}
          provider={PROVIDER_GOOGLE}
          scrollDuringRotateOrZoomEnabled={false}
          onTouchEnd={() => {
            delayFollowUserLocationUntil.current = Date.now() + 5000;
          }}
          customMapStyle={customMap}>
          <ArrowMarker onLocationChange={onLocationChange} />
        </MapView>
      </Center>
```

### Steps to reproduce

long running map view keep open using internet if you stay in cold weather can not repoduce (I think)

### Expected result

expect not consume hight ram for long running

### Actual result

for long running map will cause the app crashed

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.6

### What version of Expo are you using?

SDK 48

### Device(s)

Galaxy S10 5G,Reno10 5G,Galaxy Note10+,Galaxy A55 5G,Model:Galaxy S22 Ultra

### I use expo 50 (in  selected expo version does not has 50)

**Comment by salah-ghanim** [comment]
@chanphiromsok this can't be accepted as a bug report since there is no way for us to reproduce what you're describing, specifically for OOM issues, you should run an android memory profiler and understand how memory usage change / grow with time, android offers amazing tools for that, check out: 
https://developer.android.com/studio/profile/memory-profiler

you need to understand your app's memory footprint and what is causing the memory leak, once you identify it please submit a bug report with sample project and share your findings.

**Comment by joseestrella89** [comment]
I am having the same issue running in an emulator. 

"react-native": "0.73.1",
"react-native-maps": "1.9.1"


![Captura de pantalla 2024-06-13 a la(s) 4 22 35 p m](https://github.com/react-native-maps/react-native-maps/assets/13951146/5db78b4c-f8dd-47be-872b-49799b0b5296)

**Comment by joseestrella89** [comment]
I am having the same issue. Currently I am running my app in an android emulator.

"react-native": "0.73.1",
"react-native-maps": "1.9.1",

![Captura de pantalla 2024-06-13 a la(s) 4 22 35 p m](https://github.com/react-native-maps/react-native-maps/assets/13951146/6b6669ac-2b5b-4759-80b9-b350709b0428)

**Comment by chanphiromsok** [comment]
> I am having the same issue. Currently I am running my app in an android emulator.
> 
> "react-native": "0.73.1", "react-native-maps": "1.9.1",
> 
> ![Captura de pantalla 2024-06-13 a la(s) 4 27 30 p m](https://private-user-images.githubusercontent.com/13951146/339580360-cb0e086a-d351-4020-bbaa-eed408c290af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjk3MjgsIm5iZiI6MTcxODMyOTQyOCwicGF0aCI6Ii8xMzk1MTE0Ni8zMzk1ODAzNjAtY2IwZTA4NmEtZDM1MS00MDIwLWJiYWEtZWVkNDA4YzI5MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxNDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwOTc5YTI4ZjQ5ZDg4ZGNiYTlkN2Y2NzNkYmFjYzlmZmJmNTZhNDI5Y2IyYWRlMGQzNDE5N2ZiZmI4ZmIwMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.43tN5bsYkt4nRYepOk6EBKhUpyMZVkshRpJT7HoG6bU)

I have found issue that my app is running foreground service for broadcast location and process is alive everytime I close and open the app the MainActivity and ScreenFragment cause memory leak so that when the user open the map screen it will cause app crashed but unfortunately I can not resolve it yet because I using react-native-screens
