### ISSUE TITLE
1.15 fails to pod install on react native 74

### ISSUE THREAD

**Issue by ororsatti** [react-native-maps/react-native-maps#5065]
### Summary

There is not too much in this, Im trying to build a completely new project from scratch and with react native 0.74 and react-native-maps it fails to pod install, tho I followed all steps.

**Here is the error I get:**
![Screenshot 2024-05-23 at 15 38 45](https://github.com/react-native-maps/react-native-maps/assets/109456266/001b9458-1ebd-40b7-b89f-aba060fcb5b1)

BTW, on previous versions of react,  such as 0.73, it works fine.

### Reproducible sample code

```TSX
npx react-native-community@cli@latest init ProjectName
yarn add react-native-maps
cd ios && pod install
```

### Steps to reproduce

npx react-native-community@cli@latest init ProjectName
yarn add react-native-maps
cd ios && pod install

### Expected result

it should have worked I assume

### Actual result

it didnt

### React Native Maps Version

1.15.2

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.74

### What version of Expo are you using?

Not using Expo

### Device(s)

all iphones

**Comment by EduFaks** [comment]
+1

**Comment by rodrigolopezr** [comment]
+1 Same problem same versions

**Comment by EduFaks** [comment]
For any one having a smilar issue I found a quick fix for it!
1. Uninstall/Remove `react-native-maps` (use npm or yarn depending on how you installed it).
2. Run `yarn add react-native-maps@v2.0.0-beta.15`
3. cd ios && pod install
4. OPTIONAL - If running on an M1 or M2 chip Mac, add the following command in your Podfile above `use_native_modules!`

```
# The following line is only needed if building on an Apple silicon Mac without rosetta.
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```

**Comment by ororsatti** [comment]
> For any one having a smilar issue I found a quick fix for it!
> 
> 1. cd into your main project folder
> 2. Uninstall/Remove `react-native-maps` (use npm or yarn depending on how you installed it).
> 3. Run `yarn add react-native-maps@v2.0.0-beta.15`
> 4. OPTIONAL - If running on an M1 or M2 chip Mac, add the following command in your Podfile above `use_native_modules!`
> 
> ```
> # The following line is only needed if building on an Apple silicon Mac without rosetta.
> pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
> ```
> 5. OPTIONAL - If you want to use google maps with IOS (or even if it is still not working add the following code below the previous code
> ```
> # React Native Maps dependencies
> rn_maps_path = '../node_modules/react-native-maps'
> pod 'react-native-google-maps', :path => rn_maps_path
> ```
> 6. cd ios && pod install
> 
> Hope it helps! 👍🏼 

I dont feel comfortable using a beta version of this lib when there is a stable version.
I just moved to the latest .073 version of react native, untill the devs will fix this issue.

**Comment by salah-ghanim** [comment]
@ororsatti I think your bug report is not completely accurate, but please correct me if I'm wrong.

since you use react-native@latest means you're using 0.74.1 which is known for now to break the pod install step due to one of those two issues (I'm not exactly sure which one specific to our library / google-maps).

https://github.com/facebook/react-native/issues/44437
or
https://github.com/facebook/react-native/pull/44628


we're waiting on react-native team to merge them and publish 0.74.2 , we'll merge then and hopefully the example will be back to working as expected with react-native@latest out of the box

**Comment by salah-ghanim** [comment]
fixed in the latest release
