### ISSUE TITLE
Zoom out map and auto scroll infinite

### ISSUE THREAD

**Issue by DoHue97** [react-native-maps/react-native-maps#5069]
### Summary

i'm working map on iphone, when i zoom out to see a country and the map is auto scrolling infinite. Anyone help this?
Here is the video:
https://github.com/react-native-maps/react-native-maps/assets/39371953/5c8b4c4f-81c0-4517-b868-2355e621f349

### Reproducible sample code

```TSX
<MapView
                        showsPointsOfInterest={false}
                        showsMyLocationButton={true}
                        showsBuildings={false}
                        showsTraffic={false}
                        showsUserLocation={true}
                        followsUserLocation={true}
                        style={{ ...StyleSheet.absoluteFillObject }}
                        provider={PROVIDER_GOOGLE}
                        initialRegion={initialRegion}
                        region={region}
                        onRegionChangeComplete={props.onRegionChangeComplete}
                        onRegionChange={props.onRegionChange}
                        ref={currentMap}
                        pitchEnabled={false}
                        rotateEnabled={false}
                    ></MapView>
```

### Steps to reproduce

- zoom out the map few times 

### Expected result

I don't expect that scroll problem to happen, it just moves automatically

### Actual result

i think when i zoom out few times, the map is not auto scroll.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.18

### What version of Expo are you using?

Not using Expo

### Device(s)

emulator iphone 15

**Comment by DoHue97** [comment]
May be i don't need set the new region when zoom out or zoom in?

**Comment by salah-ghanim** [comment]
@DoHue97 please ask chatgpt or stackoverflow, or at least share a full example, in the code you posted you don't even include any zoom handling logic
