### ISSUE TITLE
After installing the package, build creation for the app fails in android and ios

### ISSUE THREAD

**Issue by CodeERAayush** [react-native-maps/react-native-maps#5074]
### Summary

I have installed react-native-maps, it was running good day before yesterday, but from yesterday, when i am creating a debug or release build it is failing and showing some error mentioned below. 

### Reproducible sample code

```TSX
yarn add react-native-maps
```

### Steps to reproduce

  version for react native:  "react-native": "^0.68.0"

### Expected result

build should be successfull

### Actual result

Task :app:compileDebugJavaWithJavac
/Users/codeeraayush/Documents/newakk/NewAK/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:87: error: package undefined does not exist
import undefined.MapsPackage;
                ^
/Users/codeeraayush/Documents/newakk/NewAK/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:217: error: cannot find symbol
      new MapsPackage(),
  symbol:   class MapsPackage
  location: class PackageList

### React Native Maps Version

  "react-native-maps": "^1.15.4",

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.68.0

### What version of Expo are you using?

Not using Expo

### Device(s)

build issue

**Comment by salah-ghanim** [comment]
@jayadelson @CodeERAayush please refine from using the latest version of RN-maps without the latest version of RN, there is often breaking changes between react-native versions and it's simple unmaintainable to keep backward compatibility.
