### ISSUE TITLE
Execution failed for task ':react-native-maps:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by nitesh-habilelabs** [react-native-maps/react-native-maps#5079]
### Summary

hi I am having an issue. i am using react-native 0.72.3 
library is compiling fine when building locally. but when i build for production, i get the following error:
> Task :react-native-maps:compileReleaseJavaWithJavac FAILED
/Users/vagrant/git/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:7: error: cannot find symbol
import com.facebook.react.fabric.interop.UIBlockViewResolver;
                                        ^
  symbol:   class UIBlockViewResolver
  location: package com.facebook.react.fabric.interop
/Users/vagrant/git/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:64: error: cannot find symbol
interface UIBlockInterface extends UIBlock, com.facebook.react.fabric.interop.UIBlock  {}
                                                                             ^
  symbol:   class UIBlock
  location: package com.facebook.react.fabric.interop
/Users/vagrant/git/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:35: error: cannot find symbol
    public void execute(UIBlockViewResolver uiBlockViewResolver) {
                        ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
/Users/vagrant/git/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:39: error: cannot find symbol
    private void executeImpl(NativeViewHierarchyManager nvhm, UIBlockViewResolver uiBlockViewResolver) {
                                                              ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
/Users/vagrant/git/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:56: error: cannot find symbol
            ((FabricUIManager) uiManager).addUIBlock(this);
                                         ^
  symbol:   method addUIBlock(MapUIBlock)
  location: class FabricUIManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-maps:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/8.0/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 3m 32s
289 actionable tasks: 284 executed, 5 up-to-date
Run: build task failed: exit status 1

i tried version .4 to today’s .6. still same error. 
any help will be appreciated.thanks

### Reproducible sample code

```TSX
<MapView
              style={styles.map}
              //specify our coordinates.
              region={{
                latitude: latitude,
                longitude: longitude,
                latitudeDelta: 0.0005,
                longitudeDelta: 0.0005,
              }}
            >
              {/*Make sure the Marker component is a child of MapView. Otherwise it won't render*/}
              <Marker
                coordinate={{
                  latitude: latitude,
                  longitude: longitude,
                }}
                pinColor={COLORS.BLUE}
                onPress={() => {
                  showLocation({
                    latitude: latitude,
                    longitude: longitude,
                  });
                }}
              />
            </MapView>
```

### Steps to reproduce

honestly i don’t know what specific steps, do i need to follow.  i am just using bitrise to build and getting this error. 

### Expected result

suppose to compile the code without error

### Actual result

compiling getting failed with error.

### React Native Maps Version

1.15.4, 1.15.6

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

pixel 4

**Comment by EdzonBolivar11** [comment]
same issue

**Comment by CS-VineetKumar** [comment]
Getting some errors on the MapUIBlock.java

<img width="1074" alt="Screenshot 2024-05-31 at 10 45 36 AM" src="https://github.com/react-native-maps/react-native-maps/assets/162279444/6debe6d9-9384-4071-b982-44e42028dc09">

**Comment by cindyfelicia** [comment]
same issue using react native 0.73.0

**Comment by nitesh-habilelabs** [comment]
> Getting some errors on the MapUIBlock.java
> 
> <img alt="Screenshot 2024-05-31 at 10 45 36 AM" width="1074" src="https://private-user-images.githubusercontent.com/162279444/335452923-6debe6d9-9384-4071-b982-44e42028dc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzI4NzUsIm5iZiI6MTcxNzEzMjU3NSwicGF0aCI6Ii8xNjIyNzk0NDQvMzM1NDUyOTIzLTZkZWJlNmQ5LTkzODQtNDA3MS1iOTgyLTQ0ZTQyMDI4ZGMwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNTE2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjg5MmRlOGQ4N2QwYWVjOGRiMDE4Njk3MjA4Y2Q0MDc1NmYyZWRhYzE5NzZmYmI3MjE3N2VhNzVkOTU3ODFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CX8raJMWYHH18TjSy86V6d0XsW4i4mRrG1QECHWm_rM">

yes, this com.facebook.react.fabric.interlop.UIBlockViewResolver is causing this issue

**Comment by kumVineet** [comment]
I think there's some changes done on the current version that's breaking. 
For now the solution is moving back to the version that was working. 
Before installing the node modules remove the ^ mark in the package.json it will install the version that was working for you in the respective projects.
Confirm once from the package.lock file for the version installed.

**Comment by nitesh-habilelabs** [comment]
> I think there's some changes done on the current version that's breaking. For now the solution is moving back to the version that was working. Before installing the node modules remove the ^ mark in the package.json it will install the version that was working for you in the respective projects. Confirm once from the package.lock file for the version installed.

hi, can you please tell me which version was working for you? i used this library first time with 1.15.4 and that was not working.

**Comment by kumVineet** [comment]
try using 1.11.3. I was using this and it's working well.

**Comment by nitesh-habilelabs** [comment]
> try using 1.11.3. I was using this and it's working well.

thanks. i will try.

**Comment by nitesh-habilelabs** [comment]
> try using 1.11.3. I was using this and it's working well.

i can confirm that i was able to build using 1.15.3. thank you for the help @kumVineet .

**Comment by TheScalion** [comment]
I have same issue with react native 0.73.8, even i have tried 1.15.3 but still i am getting same error

**Comment by TheScalion** [comment]
i have removed ^ sign from version and its works "react-native-maps": "1.15.3",
thank you @cindyfelicia

**Comment by nishadthajudeen001** [comment]
Below version worked "react-native-maps": "1.15.1(for   "react-native": "~0.73.7"), please inform thread when this is fixed in latest version

**Comment by atheck** [comment]
same here

**Comment by lorenzomilesi** [comment]
Looking at [changelog](https://github.com/react-native-maps/react-native-maps/compare/v1.15.4...v1.15.5), 1.15.4 should be ok.
I tried and it works.

**Comment by nitesh-habilelabs** [comment]
> Looking at [changelog](https://github.com/react-native-maps/react-native-maps/compare/v1.15.4...v1.15.5), 1.15.4 should be ok. I tried and it works.

well it’s strange. because i also tried 1.15.4 first and when i got compiling error on bitrise then i switched to 1.15.3. strange part is that locally .4 version is working fine when running on debug mode.

**Comment by salah-ghanim** [comment]
Everyone please don't use the latest version of the library without the latest react-native.

**There is often breaking changes, v1.13.2 and previous should be used if you're not using react-native 0.74**

**Comment by nitin-mbook** [comment]
Facing this issue for android
    
   ```
 "react-native-maps": "^1.7.1",
    "react-native": "0.71.11",
```

**Comment by ngxhuyhoang** [comment]
> Facing this issue for android
> 
> ```
> "react-native-maps": "^1.7.1",
>  "react-native": "0.71.11",
> ```

Same issue and same version

**Comment by kumVineet** [comment]
Remove the ^ mark from the package.json and don't use the latest version. 

"react-native-maps": "1.15.3",

for this version you will find it to be stable for android.

**Comment by UsamaaRao** [comment]
i have removed ^ sign from version and its works "react-native-maps": "1.15.3",
thank you @cindyfelicia

**Comment by karthikeyancontus** [comment]
issue solved using 

"react-native": "0.72.10",
"react-native-maps": "^1.15.4",

**Comment by Hassaan0** [comment]
> > I think there's some changes done on the current version that's breaking. For now the solution is moving back to the version that was working. Before installing the node modules remove the ^ mark in the package.json it will install the version that was working for you in the respective projects. Confirm once from the package.lock file for the version installed.
> 
> hi, can you please tell me which version was working for you? i used this library first time with 1.15.4 and that was not working.


I was using version `^1.14.0` of the `"react-native-maps"` library with the (^), which allows npm to install any minor updates to that version. However, when I ran the `npm install` command, I encountered an error. To fix this, I changed the library version to `1.14.0` without the (^), which prevents npm from installing any updates. This resolved the issue for me. It seems there might be a breaking change in version `1.15.0`, so I decided to stick with version `1.14.0`.

**Comment by nes123** [comment]
> issue solved using
> 
> "react-native": "0.72.10", "react-native-maps": "^1.15.4",

Not really..

**Comment by Harpreet-2002** [comment]
> Remove the ^ mark from the package.json and don't use the latest version.
> 
> "react-native-maps": "1.15.3",
> 
> for this version you will find it to be stable for android.

I try this version but not working i tried this npm version "react-native-maps": "1.10.3", now its working

**Comment by yilmar0309** [comment]
> Remove the ^ mark from the package.json and don't use the latest version.
> 
> "react-native-maps": "1.15.3",
> 
> for this version you will find it to be stable for android.

thanks @kumVineet this work for me

**Comment by sanduluca** [comment]
> Everyone please don't use the latest version of the library without the latest react-native.
> 
> **There is often breaking changes, v1.13.2 and previous should be used if you're not using react-native 0.74**

And how we had to know this ? Why a patch was released when its compatible only with react native 0.74 ?

**Comment by dgreasi** [comment]
> > I have same issue with react native 0.73.8, even i have tried 1.15.3 but still i am getting same error
> 
> yes i use react native 0.73.8 and map 1.15.3 , 1.15.4, but still iam getting same error. how iis it slove

Try `1.13.2`

**Comment by cripttion** [comment]
> i have removed ^ sign from version and its works "react-native-maps": "1.15.3", thank you @cindyfelicia

Yes this will also worked for me Thankyou

**Comment by omerts** [comment]
@salah-ghanim not sure why this was close, a patch release has broken support, 1.15.3 works, 1.15.4 doesn't. This is a true bug. Backward compatability should not be broken in a patch version release.

**Comment by AftabUfaq** [comment]
same issue for me with  "react-native": "^0.73.5",  "react-native-maps": "1.15.6",

**Comment by usmanabid94** [comment]
> try using 1.11.3. I was using this and it's working well.

It worked for me

**Comment by CS-VineetKumar** [comment]
This issue should not close.
Removing ^ is a short term solution. I am not able to upgrade the version beyond 1.15.3, it is breaking the Android Build. Please open this issue.

**Comment by hundredpackabs** [comment]
Changed the react-native-maps version to "react-native-maps": "1.15.3", removed the ^ and it worked.
For me:

`"react-native": "0.72.6",
  "react-native-maps": "1.15.3",`

**Comment by irfankhanktk** [comment]
Please try without caret ^ sign and then install dependencies using 'yarn' or 'npm install'. It fixed my issue.

**Comment by rodcibils** [comment]
> Please try without caret ^ sign and then install dependencies using 'yarn' or 'npm install'. It fixed my issue.

And can you point out which version are you using? Because this is not a caret or not-caret issue, but a breaking change issue that should be addressed at some point by the devs of this library (to which of couse I express my absolute gratitude, but well I'm experiencing this issue too and being forced to downgrade, should be a high priority fix IMO)

**Comment by alexmgriffiths** [comment]
react-native: 0.73.6
react-native-maps: 1.15.3
Worked for me

**Comment by tuan-708** [comment]
thanks so much i'm reseaching so long time =)))

**Comment by spsaucier** [comment]
`1.15.4` works too, which is good, since it includes a fix for an issue which will soon block iOS App Store uploads.

**Comment by rodcibils** [comment]
@spsaucier Thank you for pointing this out! Upgraded to 1.15.4 and can confirm that it works for me too

**Comment by spsaucier** [comment]
We'll soon need at least `1.15.6` due to the privacy issue on iOS: https://github.com/react-native-maps/react-native-maps/pull/5078

**Comment by Shehryar-intellicode** [comment]
react-native: 0.73.6
react-native-maps: 1.15.4
worked for me for both platforms (previously react-native-maps: 1.20.0 was working only for iOS i downgraded to 1.15.4 and it worked for both)

**Comment by PaneruVipin** [comment]
The issue you're facing occurs because react-native-maps requires additional configuration when building for a production APK. It works fine in the development environment (local), but for the APK, you need to configure the Google Maps SDK for Android. Here's a detailed breakdown of the steps you need to follow:

### 1. **Register a Google Cloud API Project**
   - Go to the [Google Cloud Console](https://console.cloud.google.com/).
   - Create a new project or use an existing one.
   - Enable the **Maps SDK for Android** by navigating to **APIs & Services > Library**, searching for **Maps SDK for Android**, and enabling it.

### 2. **Create an API Key**
   - In the [Google Cloud Console](https://console.cloud.google.com/), go to **APIs & Services > Credentials**.
   - Click on **Create Credentials** and select **API Key**.
   - Initially, **do not restrict** the API key (you can restrict it later if needed).
   - Copy the API key that is generated.

### 3. **Add the API Key to Your Project**
   - In your **app.json** (or **app.config.js**) file, add the API key in the appropriate section for Android:
     ```json
     "android": {
       "config": {
         "googleMaps": {
           "apiKey": "YOUR_GOOGLE_MAPS_API_KEY"
         }
       }
     }
     ```
   - Replace `"YOUR_GOOGLE_MAPS_API_KEY"` with the actual API key you generated.

### 4. **Update `react-native-maps` to Use Google Maps**
   - In your code, ensure you import the `PROVIDER_GOOGLE` from `react-native-maps` and pass it to the `MapView` component:
     ```javascript
     import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

     <MapView
       provider={PROVIDER_GOOGLE}
       style={{ flex: 1 }}
       region={mapRegion}
     >
       <Marker coordinate={mapRegion} />
     </MapView>
     ```

### 5. **Rebuild Your APK**
   - After adding the API key and making the necessary configurations, rebuild your APK.
   - If you're using **Expo**, make sure you're using the appropriate build configuration, such as **EAS Build**.
   - For **bare React Native projects**, run the following command to build your APK:
     ```bash
     npx react-native run-android --variant=release
     ```

### 6. **Test the APK**
   - Once the APK is built and installed on a physical device, test the app to ensure the map is loading correctly.
   - If everything works fine, you can now choose to **restrict** the API key for additional security.

### 7. **Restrict the API Key (Optional but Recommended)**
   - If you want to restrict the API key later for security reasons, go back to **Google Cloud Console > APIs & Services > Credentials**.
   - Click on your API key and under **Key restrictions**, choose **Android apps**.
   - Add your **package name** (e.g., `com.yourapp.name`) and the **SHA-1 certificate** (if you plan to restrict it to a specific certificate).
     - To get the **SHA-1 certificate** for development builds, run:
       ```bash
       keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
       ```
     - For **Google Play Store builds**, retrieve the SHA-1 from the **App Integrity** section in the **Google Play Console**.

### 8. **Rebuild and Test Again**
   - After restricting the API key, rebuild your APK and test again to ensure everything is working correctly with the restricted API key.

By following these steps, you can successfully configure Google Maps for your React Native app without restricting the API key initially, and later add the restrictions for security if needed.

**Comment by bradherman** [comment]
@PaneruVipin I don't think that's accurate.  I have all those things configured just fine and have the issues unless I downgrade to 1.15.x.  It feels like maybe you're replying to the wrong thread?

**Comment by Anushka3001** [comment]
i tried 
react-native: 0.73.6
react-native-maps: 1.15.3
it is still the same error
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

with that i'm also getting this error:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

if anyone knows the solution for this, please help me out.

**Comment by Shehryar-intellicode** [comment]
> i tried react-native: 0.73.6 react-native-maps: 1.15.3 it is still the same error Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> with that i'm also getting this error: Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> 
> if anyone knows the solution for this, please help me out.

for 'gesture handler error i did this 'react-native-gesture-handler": "^2.18.0' in my package.json and for maps error this 'react-native: 0.73.6
react-native-maps: 1.15.4' worked for me.
