### ISSUE TITLE
All subviews are not being removed properly when running new architecture

### ISSUE THREAD

**Issue by b-levinger** [react-native-maps/react-native-maps#5080]
### Summary

Polygons, markers, etc are not being removed properly when unmounted due to being wrapped by `RCTLegacyViewManagerInteropComponentView.` when running the new architecture.

The unmounted view comes in as `RCTLegacyViewManagerInteropComponentView` which contains the real view as a child called "paperView"

I was able to get around this with a simple hack in AIRGoogleMap,

```
- (void)removeReactSubview:(id<RCTComponent>)subview {
  // similarly, when the children are being removed we have to do the appropriate
  // underlying mapview action here.

  if ([subview respondsToSelector:NSSelectorFromString(@"paperView")]) {
    subview = [(RCTLegacyViewManagerInteropComponentView*)subview paperView];
  }

```

(I had to just redeclare RCTLegacyViewManagerInteropComponentView, couldn't get it to import properly, this of course is not a proper fix otherwise I would have just submitted a PR instead)

Example: this is a polygon being removed from the view

<img width="724" alt="Screenshot 2024-05-30 at 6 17 03 PM" src="https://github.com/react-native-maps/react-native-maps/assets/625955/8eb8b186-52d5-405a-9335-77e3d8715512">

<img width="549" alt="Screenshot 2024-05-30 at 6 27 02 PM" src="https://github.com/react-native-maps/react-native-maps/assets/625955/40764efc-7300-4abf-a454-3c4bddad93fc">

### Reproducible sample code

```TSX
<MapView><Marker /></MapView>
```
```


### Steps to reproduce

When running with the new architecture (via interop) add a polygon to the map and then remove it, it will not disappear.

### Expected result

Unmounted child views should no longer be present in the view.

### Actual result

Unmounted react elements remain.

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.74.1

### What version of Expo are you using?

Not using Expo

### Device(s)

ios

### Additional information

_No response_

**Comment by salah-ghanim** [comment]
Incorrect bug report, or at least not reproducible I tested on iOS physical device both google and apple maps and both successfully add and remove views


example:

`import React, {useState, useRef} from 'react';
import {View, Button, StyleSheet} from 'react-native';
import MapView, {Marker, Polygon, Circle, Region} from 'react-native-maps';

type MapItem =
  | {type: 'marker'; latitude: number; longitude: number; key: string}
  | {
      type: 'polygon';
      coordinates: {latitude: number; longitude: number}[];
      key: string;
    }
  | {
      type: 'circle';
      center: {latitude: number; longitude: number};
      radius: number;
      key: string;
    };

const App: React.FC = () => {
  const [mapItems, setMapItems] = useState<MapItem[]>([]);
  const mapRef = useRef<MapView>(null);

  const initialRegion: Region = {
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  };

  const getRandomCoordinates = () => {
    const latitude =
      Math.random() * initialRegion.latitudeDelta +
      (initialRegion.latitude - initialRegion.latitudeDelta / 2);
    const longitude =
      Math.random() * initialRegion.longitudeDelta +
      (initialRegion.longitude - initialRegion.longitudeDelta / 2);
    return {latitude, longitude};
  };

  const addMapItem = () => {
    const newCoordinates = getRandomCoordinates();
    const itemType = Math.floor(Math.random() * 3);
    let newItem: MapItem;

    if (itemType === 0) {
      newItem = {
        type: 'marker',
        latitude: newCoordinates.latitude,
        longitude: newCoordinates.longitude,
        key: Math.random().toString(),
      };
    } else if (itemType === 1) {
      const coordinates = [
        newCoordinates,
        getRandomCoordinates(),
        getRandomCoordinates(),
        getRandomCoordinates(),
      ];
      newItem = {type: 'polygon', coordinates, key: Math.random().toString()};
    } else {
      const radius = Math.random() * 1000 + 500;
      newItem = {
        type: 'circle',
        center: newCoordinates,
        radius,
        key: Math.random().toString(),
      };
    }

    setMapItems(currentItems => [...currentItems, newItem]);
  };

  const removeMapItem = () => {
    setMapItems(currentItems => currentItems.slice(0, -1));
  };

  return (
    <View style={styles.container}>
      <MapView
        ref={mapRef}
        style={styles.map}
        initialRegion={initialRegion}
        provider={'google'}>
        {mapItems.map(item => {
          switch (item.type) {
            case 'marker':
              return (
                <Marker
                  key={item.key}
                  coordinate={{
                    latitude: item.latitude,
                    longitude: item.longitude,
                  }}
                />
              );
            case 'polygon':
              return <Polygon key={item.key} coordinates={item.coordinates} />;
            case 'circle':
              return (
                <Circle
                  key={item.key}
                  center={item.center}
                  radius={item.radius}
                />
              );
            default:
              return null;
          }
        })}
      </MapView>
      <View style={styles.buttonContainer}>
        <Button title="Add Item" onPress={addMapItem} />
        <Button title="Remove Item" onPress={removeMapItem} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

export default App;
`
video attached as well

https://github.com/react-native-maps/react-native-maps/assets/1613032/557566e1-b14b-4f8f-a6b9-0174d594f8ee

**Comment by richstimson** [comment]
See potential root cause fix: https://github.com/react/react-native/issues/57872#issuecomment-5400175931
