### ISSUE TITLE
Android build broken from v1.15.5 onwards

### ISSUE THREAD

**Issue by nlindroos** [react-native-maps/react-native-maps#5082]
### Summary

The Android build fails with both of the latest released patch versions (1.15.5 and 1.15.6).

### Reproducible sample code

```TSX
I apologise for not spending time on creating a minimal repro. Feel free to close if this is not a wider issue.
```

### Steps to reproduce

Install + try to run or build Android.

### Expected result

Build works

### Actual result

Build fails

### React Native Maps Version

1.15.5

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Android API 36 (but the API version is likely not pertinent)

### Additional information

This is the relevant error log:
```sh
> Task :react-native-maps:compileDebugJavaWithJavac
/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:7: error: cannot find symbol
import com.facebook.react.fabric.interop.UIBlockViewResolver;
                                        ^
  symbol:   class UIBlockViewResolver
  location: package com.facebook.react.fabric.interop
/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:64: error: cannot find symbol
interface UIBlockInterface extends UIBlock, com.facebook.react.fabric.interop.UIBlock  {}
                                                                             ^
  symbol:   class UIBlock
  location: package com.facebook.react.fabric.interop
/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:35: error: cannot find symbol
    public void execute(UIBlockViewResolver uiBlockViewResolver) {
                        ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:39: error: cannot find symbol
    private void executeImpl(NativeViewHierarchyManager nvhm, UIBlockViewResolver uiBlockViewResolver) {
                                                              ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:56: error: cannot find symbol
            ((FabricUIManager) uiManager).addUIBlock(this);
                                         ^
  symbol:   method addUIBlock(MapUIBlock)
  location: class FabricUIManager

> Task :react-native-maps:compileDebugJavaWithJavac FAILED
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
```

1.15.4 has no build issues, this is introduced in 1.15.5. The [1.15.5 release](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.15.5) lists #5061 as the only change, so that is likely the culprit.

**Comment by salah-ghanim** [comment]
@alejodiloreto @nlindroos the latest version of this library is currently compatible with the latest version of react-native, specifically RN introduced new native code to support libraries not using Fabric while Fabric is enabled. this code wasn't part of react-native before 0.74 so please upgrade react-native or don't update the library

**Comment by williamdes** [comment]
This library could be marked as requiring react native latest in package json

**Comment by nlindroos** [comment]
All right, that makes sense. Such a breaking change without maintaining backwards compatibility even to the second to latest minor version of React Native should require a major version bump though, if semantic versioning is followed. Currently only the patch version of _react-native-maps_ is bumped for a major change.

**Comment by ziga-hvalec** [comment]
this should be a major change. not just a patch

**Comment by williamdes** [comment]
https://github.com/react-native-maps/react-native-maps/blob/cbc2ff39b214040933da9cd7a234d63c69476392/package.json#L49C27-L49C29

Meanwhile `"react-native": ">= 0.64.3",` ...
