### ISSUE TITLE
Simulator build - AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS

### ISSUE THREAD

**Issue by jakobkarlstrand** [react-native-maps/react-native-maps#5087]
### Summary

I'm trying to use React Native Maps with Google as provider for iOS. 
I have followed the instructions here: https://docs.expo.dev/versions/latest/sdk/map-view/ creating API-keys etc.

I get the following error:

<img width="355" alt="Screenshot 2024-06-12 at 10 09 20" src="https://github.com/react-native-maps/react-native-maps/assets/53311520/1de3e58a-f257-4c99-bb8c-f0050aef21c1">

### Reproducible sample code

```TSX
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

<MapView                          
    provider={PROVIDER_GOOGLE}
>
```

### Steps to reproduce

Start an Expo SDK 50 project with managed flow.
Follow the steps listed here:  https://docs.expo.dev/versions/latest/sdk/map-view
Add Google API Key to field `ios.config.googleMapsApiKey` in `app.json`
Run simulator build with `npx expo run:ios`

### Expected result

MapView with Google as the provider

### Actual result

Error message as shown above.

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 14 Pro Max

**Comment by jakobkarlstrand** [comment]
My bad. All I had to do was delet `/ios` folder and run `npx expo run:ios` again.

**Comment by asaduryan** [comment]
Same with react native without expo

**Comment by moneszarrugh** [comment]
I have the same issue with expo sdk 51 and react-native-maps 1.14.0
