### ISSUE TITLE
new architecture not supported

### ISSUE THREAD

**Issue by AliHussein-areeba** [react-native-maps/react-native-maps#5088]
### Summary

When turning my react native project from old to new architecture, rendering the component that contains the MapView is returning these errors in my metro:

Error: Unsupported top level event type "topOnMapReady" dispatched
Error: Unsupported top level event type "topOnMapLoaded" dispatched

### Reproducible sample code

```TSX
import MapView, { Marker } from "react-native-maps";

<MapView
          style={{flex:1}
          showsUserLocation={true}
          initialRegion={{
            latitude: 33.32265,
            longitude: 44.350832,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
>
    <Marker
            coordinate={{
              latitude: 33.32265,
              longitude: 44.350832,
            }}
            title={"Test Marker"}
     />
</MapView>
```

### Steps to reproduce

Add the sample code to whatever component and run the component.

### Expected result

Expected to run normally like when it was running on old architecture, and not having these errors.

### Actual result

Error: Unsupported top level event type "topOnMapReady" dispatched
Error: Unsupported top level event type "topOnMapLoaded" dispatched

![Screenshot_1](https://github.com/react-native-maps/react-native-maps/assets/170405165/c8dc7e50-78d0-4a5e-93b4-53b87855f794)
![Screenshot_2](https://github.com/react-native-maps/react-native-maps/assets/170405165/0bb76029-105f-4d1e-9c8b-87c1d6affdc6)

### React Native Maps Version

1.15.4

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung Galaxy A54 (android 14)

### Additional information

Please to fix it asap as its holding back development.

**Comment by salah-ghanim** [comment]
update to latest react-native first and try again
