### ISSUE TITLE
When zoomed, roads turn black

### ISSUE THREAD

**Issue by lid3rs** [react-native-maps/react-native-maps#5090]
### Summary

I guess images are the best explanation 

<img width="351" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/1872001/17f5420a-eca4-409b-85ec-791cf3413094">
<img width="342" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/1872001/85e08afd-4f4e-4191-ae8c-64632e8e015d">

### Reproducible sample code

```TSX
<MapView
      provider={PROVIDER_GOOGLE}
      ref={mapRef}
      showsMyLocationButton={true}
      customMapStyle={[
        {
          featureType: 'road',
          stylers: [
            {
              visibility: 'on',
            },
          ],
        },
      ]}
      zoomEnabled={true}
      followsUserLocation={true}
      userLocationUpdateInterval={1000}
      zoomControlEnabled={true}
      showsUserLocation
      style={StyleSheet.absoluteFillObject}
      onLayout={() => {
        mapRef.current?.fitToCoordinates(coordinatesArea, {
          edgePadding: { top: gap, right: gap, bottom: gap, left: gap },
          animated: false,
        })
      }}
    />
```

### Steps to reproduce

Start zooming in until you see streets

### Expected result

As default Google Maps

### Actual result

Black, Bold

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel, api 28

**Comment by sideffect263** [comment]
If your roads turn black when zoomed in on your MapView, the issue likely lies with your customMapStyle configuration. maybe this can help:

`<MapView
  provider={PROVIDER_GOOGLE}
  ref={mapRef}
  showsMyLocationButton={true}
  customMapStyle={[
    {
      featureType: 'road',
      elementType: 'geometry',
      stylers: [
        { color: '#ffffff' }, // Set road color to white
        { visibility: 'simplified' },
      ],
    },
  ]}
  zoomEnabled={true}
  followsUserLocation={true}
  userLocationUpdateInterval={1000}
  zoomControlEnabled={true}
  showsUserLocation
  style={StyleSheet.absoluteFillObject}
  onLayout={() => {
    mapRef.current?.fitToCoordinates(coordinatesArea, {
      edgePadding: { top: gap, right: gap, bottom: gap, left: gap },
      animated: false,
    });
  }}
/>
`

**Comment by lid3rs** [comment]
This was my very first attempt and why I even have stylers in my example. Result is exactly the same. No effect at all.

**Comment by salah-ghanim** [comment]
@lid3rs we don't modify any styling to the native maps, you should be able to reproduce this bug by simply using android google maps SDK directly, I would recommend that you setup such a testing app and if you can reproduce it contact google maps team directly, else you need to find out what difference exist between your sample react-native-maps app and google-maps sample app.
