### ISSUE TITLE
Task :react-native-maps:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by remarkablemark** [react-native-maps/react-native-maps#5095]
### Summary

When building React Native 0.70 for Android, it fails with the error:

```
./node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:7: error: package com.facebook.react.fabric.interop does not exist
import com.facebook.react.fabric.interop.UIBlockViewResolver;
                                        ^
./node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:64: error: package com.facebook.react.fabric.interop does not exist
interface UIBlockInterface extends UIBlock, com.facebook.react.fabric.interop.UIBlock  {}
                                                                             ^
./node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:35: error: cannot find symbol
    public void execute(UIBlockViewResolver uiBlockViewResolver) {
                        ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
./node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:39: error: cannot find symbol
    private void executeImpl(NativeViewHierarchyManager nvhm, UIBlockViewResolver uiBlockViewResolver) {
                                                              ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
./node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java:56: error: cannot find symbol
            ((FabricUIManager) uiManager).addUIBlock(this);
                                         ^
  symbol:   method addUIBlock(MapUIBlock)
  location: class FabricUIManager
```

This may be related to #5061, which was released in [v1.15.5](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.15.5). Was this intended to be a breaking change?

### Reproducible sample code

```TSX
N/A
```

### Steps to reproduce

Install deps:

```sh
yarn add react-native-maps react-native@0.70
```

Build for Android:

```sh
react-native run-android --variant=release
```

### Expected result

Android build success

### Actual result

Android build error

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.15

### What version of Expo are you using?

Not using Expo

### Device(s)

Android

**Comment by PankajRanaCapriGLobal** [comment]
Getting Same erorr

**Comment by hussein-khamis** [comment]
Same here

**Comment by hussein-khamis** [comment]
I just have downgraded to 1.10.0 and it works fine now. You could go above and try in which version it broke too!

**Comment by pauloscardoso** [comment]
for me, not work with none of the options mentioned above =(

**Comment by webchun** [comment]
getting the same issue today and none of the options above are working 😔

**Comment by yogeshhack** [comment]
Hello guys there is an something went wrong with Latest Version i change my Maps version 1.15.6 -> 1.14.0 and than clean the build and run again it's works for me. 
<img width="904" alt="Screenshot 2024-06-19 at 3 41 56 PM" src="https://github.com/react-native-maps/react-native-maps/assets/67140580/38aaa4fe-9262-45a3-8fbe-f8a503b21181">

**Comment by SwhiteMHC** [comment]
@yogeshBadgujar7 Downgrading from 1.15.6 to 1.14.0 worked for me.

**Comment by pauloscardoso** [comment]
Exactly. Version 1.14.0 and not ˆ1.14.0 worked for me.

**Comment by correafederico25** [comment]
It worked for me by changing to version **1.10.0** and first completely deleting the **android/app/build** folder. If I don't delete it, it doesn't work and keeps giving me the same error.

**Comment by radeno** [comment]
Sadly, the patch version is as a major version change
https://github.com/react-native-maps/react-native-maps/issues/5082 and project does not use `peerDependencies` properly

**Comment by eber404** [comment]
here's what I did to get this working again:

* Locked the package version to `1.15.4`
* Ran `npm install`
* Navigated to the Android folder and ran `./gradlew clean && ./gradlew bundleRelease`

**Comment by scr1pt** [comment]
if you use nvm, change version to 1.14.0 then before "yarn install" make "nvm cache clear"

**Comment by VSDOT** [comment]
Same error is coming.  My react native version is 0.73.8 and maps version 1.14.0 and 1.15.4 and it doesn't work when ues does it. how is it slove

**Comment by GSSPawanKumarSingh** [comment]
> Same error is coming. My react native version is 0.73.8 and maps version 1.14.0 and 1.15.4 and it doesn't work when ues does it. how is it slove

Same issue with the same definition. How to solve it?

**Comment by Usmanqayyum109** [comment]
**I resolved an issue using the following setup:**

Note:If you are using react-native-reanimated, first check out this link:
_https://github.com/software-mansion/react-native-reanimated/issues/6076#issuecomment-2154224601_

React Native version: 0.72.3
react-native-maps version: 1.15.6

The solution involves replacing the MapUIBlock.java file located at _node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java_

Here's the code to use in MapUIBlock.java:

package com.rnmaps.maps;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.NativeViewHierarchyManager;
import com.facebook.react.uimanager.UIBlock;
import com.facebook.react.uimanager.UIManagerHelper;
import com.facebook.react.uimanager.UIManagerModule;

import java.util.function.Function;

public class MapUIBlock implements UIBlock {
    private int tag;
    private Promise promise;
    private ReactApplicationContext context;
    private Function<MapView, Void> mapOperation;

    public MapUIBlock(int tag, Promise promise, ReactApplicationContext context, Function<MapView, Void> mapOperation) {
        this.tag = tag;
        this.promise = promise;
        this.context = context;
        this.mapOperation = mapOperation;
    }

    @Override
    public void execute(NativeViewHierarchyManager nvhm) {
        MapView view = (MapView) nvhm.resolveView(tag);
        if (view == null) {
            promise.reject("AirMapView not found");
            return;
        }
        if (view.map == null) {
            promise.reject("AirMapView.map is not valid");
            return;
        }

        mapOperation.apply(view);
    }

    public void addToUIManager() {
        UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(this);
    }
}

**Comment by ijs1103** [comment]
@Usmanqayyum109 OMG...👍 👀

**Comment by dhananjayspeed** [comment]
> Same error is coming. My react native version is 0.73.9 any update on this

**Comment by dhananjayspeed** [comment]
Same error is coming. My react native version is 0.73.9 any update on this

**Comment by salah-ghanim** [comment]
I just updated the documentations to make this clear [compatibility](https://github.com/react-native-maps/react-native-maps?tab=readme-ov-file#compatibility)

you need react-native 0.74 and above if you're using any react-native-maps version above 1.4.0

**Comment by adeayobandung** [comment]
> **I resolved an issue using the following setup:**
> 
> Note:If you are using **_react-native-reanimated_**, first check out this link: _[software-mansion/react-native-reanimated#6076 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/6076#issuecomment-2154224601)_
> 
> React Native version: 0.72.3 react-native-maps version: 1.15.6
> 
> The solution involves replacing the **MapUIBlock.java** file located at **_node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java_**
> 
> Here's the code to use in **MapUIBlock.java:**
> 
> ```
> package com.rnmaps.maps;
> 
> import com.facebook.react.bridge.Promise;
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.uimanager.NativeViewHierarchyManager;
> import com.facebook.react.uimanager.UIBlock;
> import com.facebook.react.uimanager.UIManagerHelper;
> import com.facebook.react.uimanager.UIManagerModule;
> 
> import java.util.function.Function;
> 
> public class MapUIBlock implements UIBlock {
>     private int tag;
>     private Promise promise;
>     private ReactApplicationContext context;
>     private Function<MapView, Void> mapOperation;
> 
>     public MapUIBlock(int tag, Promise promise, ReactApplicationContext context, Function<MapView, Void> mapOperation) {
>         this.tag = tag;
>         this.promise = promise;
>         this.context = context;
>         this.mapOperation = mapOperation;
>     }
> 
>     @Override
>     public void execute(NativeViewHierarchyManager nvhm) {
>         MapView view = (MapView) nvhm.resolveView(tag);
>         if (view == null) {
>             promise.reject("AirMapView not found");
>             return;
>         }
>         if (view.map == null) {
>             promise.reject("AirMapView.map is not valid");
>             return;
>         }
> 
>         mapOperation.apply(view);
>     }
> 
>     public void addToUIManager() {
>         UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
>         uiManager.addUIBlock(this);
>     }
> }
> ```

Thanks bro, this code running for my react-native: 0.72.7 - react-native-maps: 1.14.0

**Comment by Ajmal0197** [comment]
Replace in package.json and do `yarn` / `npm i`
```
    "react-native-maps": "1.4.0",
```

**Comment by MathieuVce** [comment]
> **I resolved an issue using the following setup:**
> 
> Note:If you are using **_react-native-reanimated_**, first check out this link: _[software-mansion/react-native-reanimated#6076 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/6076#issuecomment-2154224601)_
> 
> React Native version: 0.72.3 react-native-maps version: 1.15.6
> 
> The solution involves replacing the **MapUIBlock.java** file located at **_node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java_**
> 
> Here's the code to use in **MapUIBlock.java:**
> 
> ```
> package com.rnmaps.maps;
> 
> import com.facebook.react.bridge.Promise;
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.uimanager.NativeViewHierarchyManager;
> import com.facebook.react.uimanager.UIBlock;
> import com.facebook.react.uimanager.UIManagerHelper;
> import com.facebook.react.uimanager.UIManagerModule;
> 
> import java.util.function.Function;
> 
> public class MapUIBlock implements UIBlock {
>     private int tag;
>     private Promise promise;
>     private ReactApplicationContext context;
>     private Function<MapView, Void> mapOperation;
> 
>     public MapUIBlock(int tag, Promise promise, ReactApplicationContext context, Function<MapView, Void> mapOperation) {
>         this.tag = tag;
>         this.promise = promise;
>         this.context = context;
>         this.mapOperation = mapOperation;
>     }
> 
>     @Override
>     public void execute(NativeViewHierarchyManager nvhm) {
>         MapView view = (MapView) nvhm.resolveView(tag);
>         if (view == null) {
>             promise.reject("AirMapView not found");
>             return;
>         }
>         if (view.map == null) {
>             promise.reject("AirMapView.map is not valid");
>             return;
>         }
> 
>         mapOperation.apply(view);
>     }
> 
>     public void addToUIManager() {
>         UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
>         uiManager.addUIBlock(this);
>     }
> }
> ```

I have experienced the same issue

My config is as follow:
"react-native": "^0.71.0",
"react-native-maps": "1.20.0",

I'm aware that in the Readme of [react-native-maps](https://github.com/react-native-maps/react-native-maps) they have suggested this version "react-native": "^0.74.0"

This patch seems to fix this issue the compilation works and my app is launched.

**Comment by hiThilinaW** [comment]
> **I resolved an issue using the following setup:**
> 
> Note:If you are using **_react-native-reanimated_**, first check out this link: _[software-mansion/react-native-reanimated#6076 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/6076#issuecomment-2154224601)_
> 
> React Native version: 0.72.3 react-native-maps version: 1.15.6
> 
> The solution involves replacing the **MapUIBlock.java** file located at **_node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapUIBlock.java_**
> 
> Here's the code to use in **MapUIBlock.java:**
> 
> ```
> package com.rnmaps.maps;
> 
> import com.facebook.react.bridge.Promise;
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.uimanager.NativeViewHierarchyManager;
> import com.facebook.react.uimanager.UIBlock;
> import com.facebook.react.uimanager.UIManagerHelper;
> import com.facebook.react.uimanager.UIManagerModule;
> 
> import java.util.function.Function;
> 
> public class MapUIBlock implements UIBlock {
>     private int tag;
>     private Promise promise;
>     private ReactApplicationContext context;
>     private Function<MapView, Void> mapOperation;
> 
>     public MapUIBlock(int tag, Promise promise, ReactApplicationContext context, Function<MapView, Void> mapOperation) {
>         this.tag = tag;
>         this.promise = promise;
>         this.context = context;
>         this.mapOperation = mapOperation;
>     }
> 
>     @Override
>     public void execute(NativeViewHierarchyManager nvhm) {
>         MapView view = (MapView) nvhm.resolveView(tag);
>         if (view == null) {
>             promise.reject("AirMapView not found");
>             return;
>         }
>         if (view.map == null) {
>             promise.reject("AirMapView.map is not valid");
>             return;
>         }
> 
>         mapOperation.apply(view);
>     }
> 
>     public void addToUIManager() {
>         UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
>         uiManager.addUIBlock(this);
>     }
> }
> ```

Legend <3
