### ISSUE TITLE
compassOffset not working on Apple Maps (iOS)

### ISSUE THREAD

**Issue by noquinn** [react-native-maps/react-native-maps#5097]
### Summary

The compassOffset prop for the MapView is not working on Apple Maps

### Reproducible sample code

```JSX
import React, {useEffect, useRef} from 'react';
import MapView from 'react-native-maps';

export default function App() {
  const mapRef = useRef();

  useEffect(() => {
    const timeout = setTimeout(
      () => mapRef.current.setCamera({heading: 45}),
      0,
    );
    return () => clearTimeout(timeout);
  }, []);

  return (
    <MapView
      ref={mapRef}
      mapType="standard"
      userInterfaceStyle="light"
      compassOffset={{x: -100, y: 50}}
      style={{flex: 1}}
      initialRegion={{
        latitude: 40.689246,
        longitude: -74.044536,
        latitudeDelta: 0.002,
        longitudeDelta: 0.002,
      }}
    />
  );
}
```

### Steps to reproduce

Use sample code above and run on iOS.

### Expected result

The compass should appear down from and to the left of the default position
<img src="https://github.com/react-native-maps/react-native-maps/assets/65325348/62d31204-0403-453b-a8e3-a0df23eb32bc" width="200" alt="Simulator Screenshot - iPhone 15 Pro" >

### Actual result

The compass appears in the default position
<img src="https://github.com/react-native-maps/react-native-maps/assets/65325348/3f7aac91-6a00-4a2c-84c5-adef86d2418f" width="200" alt="Simulator Screenshot - iPhone 15 Pro" >

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

Apple Maps

### React Native Version

0.74.2

### What version of Expo are you using?

SDK 51

### Device(s)

iPhone 15 Pro (17.5 Simulator), iPhone SE (17.5 Simulator)

### Additional information

[This post](https://stackoverflow.com/questions/48343381/how-to-reposition-compass-of-mkmapview/78136924#78136924) makes it seem like the method used [here](https://github.com/react-native-maps/react-native-maps/blob/da11dd647733846dd297a5a4df78bf0edfa0c7b8/ios/AirMaps/AIRMap.m#L712) might not work anymore

**Comment by chiefchief** [comment]
"react-native-maps": "^1.18.0" still exist this issue
