### ISSUE TITLE
Satellite Fly over not available for android

### ISSUE THREAD

**Issue by Espade** [react-native-maps/react-native-maps#5100]
### Summary

For now, satelliteFlyOver map type is only there for apple, not for android. I wonder when the android support for satelliteFlyOver will be available?

### Reproducible sample code

```TSX
N/A
```

### Steps to reproduce

N/A

### Expected result

N/A

### Actual result

N/A

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Pixel 3A(android 14)

**Comment by rizwanzazz** [comment]
@Espade @mlc @pedro @netshade @miracle2k 
Do you know if there is any progress on this issue?
