### ISSUE TITLE
Api key not found 

### ISSUE THREAD

**Issue by Reeta-7** [react-native-maps/react-native-maps#5105]
### Summary

![image](https://github.com/react-native-maps/react-native-maps/assets/49265323/aaf88e4e-f7a5-428f-abd8-99a07336b0b1) i have done this following chnanges in Android  manifest <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="my api key"/>, but issue is still present 

### Reproducible sample code

```TSX
<MapView
            initialRegion={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
          />
```

### Steps to reproduce

<img width="567" alt="Screen Shot 2024-06-29 at 11 34 54 AM" src="https://github.com/react-native-maps/react-native-maps/assets/49265323/cf0d183a-c0b4-4ae2-8e90-76453a5b5024">

### Expected result

i want to get  proper map view functionality

### Actual result

![image](https://github.com/react-native-maps/react-native-maps/assets/49265323/a05a394a-adbd-4436-bc9a-9c95558a09ba)

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.6

### What version of Expo are you using?

Not using Expo

### Device(s)

samsung a7 android 10

**Comment by spravinkumar9952** [comment]
@Reeta-7  in which Android manifest you are changing? debug or main?

**Comment by Reeta-7** [comment]
Main

**Comment by salah-ghanim** [comment]
@Reeta-7 please follow the setup instructions

**Comment by matheuspbmarques** [comment]
I'm with same issue.

- react-native 0.77.0
- react-native-maps 1.20.1

In projects/android/app/src/main/AndroidManifest.xml I insert 

`<meta-data
  android:name="com.google.android.geo.MY_API_KEY"
  android:value="MY_API_KEY"
/>`

This tags are in <application> and I doing it in AndroidManifest.xml debug version too, but not work.
