### ISSUE TITLE
Application crashes when MapView.Circle center longitude is greater than 180

### ISSUE THREAD

**Issue by TierryBr** [react-native-maps/react-native-maps#5109]
### Summary

If you create a very large radius, for example the entire state will have a very large length, and when displaying this on iOS the application crashes, the same does not happen on Android

### Reproducible sample code

```TSX
<MapView
    ref={ref=> {this.map = ref}}
    provider={PROVIDER_GOOGLE}
    style={Styles.map}
    >
        <MapView.Circle
            center={{longitude: 181,latitude: 40}}
            radius={2000}
        />
</MapView>
```

### Steps to reproduce

add a longitude above 180

### Expected result

could display a longitude above 180 like on android

### Actual result

application crashes when displaying a Circle with center having a length greater than 180

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.5

### What version of Expo are you using?

Not using Expo

### Device(s)

Iphone 15 Pro Max

**Comment by clertonf** [comment]
Same problem here too
