### ISSUE TITLE
Map is not working on android

### ISSUE THREAD

**Issue by MichelNassarleb** [react-native-maps/react-native-maps#5110]
### Summary

I tried the same API key on the example project, it worked fine, but it's not working on this project

### Reproducible sample code

```TSX
<meta-data android:name="com.google.android.geo.API_KEY" android:value="****" />
    "react-native": "0.73.4",
     "react-native-maps": "^1.14.0",
```

### Steps to reproduce

 <MapView
                style={{ flex: 1 }}
                userInterfaceStyle={'light'}
                region={position}
                provider={defaultProvider}
                testID="MapView"
                onRegionChange={(data) =>
                    setMarker((prev) => {
                        console.log(data)

                        return {
                            latitude: data.latitude,
                            longitude: data.longitude,
                            longitudeDelta: data.longitudeDelta,
                            latitudeDelta: data.latitudeDelta,
                            text: prev.text
                        }
                    })
                }
                ref={MapRef}>
                <FocusAwareStatusBar barStyle="dark-content" translucent />
                <Marker
                    icon={require('../../assets/icons/LostPet.svg')}
                    coordinate={{ latitude: marker.latitude, longitude: marker.longitude }}>
                    <Icon name={ICONS.LOCATION} size={56} color={colors.primary[100]} />
                </Marker>
            </MapView>

### Expected result

    the map to show

### Actual result

the map is blank

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Android

**Comment by MichelNassarleb** [comment]
guys its a production project and the map is an essential critical feature in it, without it the user can't do anything, please ask to show you anything in the project that might be wrongly configured, gradle version, anything but please help

**Comment by MichelNassarleb** [comment]
i had to add 
android:hardwareAccelerated="true"
to the application tag that contains the api key meta-tag for it to work

**Comment by Hoto-Mocha** [comment]
You Saved My Life
