### ISSUE TITLE
Android app won't run after deleting node_modules folder.  pen_spark

### ISSUE THREAD

**Issue by mobileashvin** [react-native-maps/react-native-maps#5116]
### Summary

I deleted the node_modules folder in my React Native project and tried to run the Android app with maps. I'm getting this error: "Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'. I even tried using different versions of react-native-maps: both ^1.11.1 and ^1.15.6.
I was able to fix the "Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'" error by:
* Restoring the node_modules folder from a backup.
* Updating the react-native-maps package to a compatible version (possibly the original version used).
* Running the Android project again.

### Reproducible sample code

```TSX
Note: Recompile with -Xlint:deprecation for details.
C:\_source\everlights.mobileapp.v4\node_modules\react-native-maps\android\src\main\java\com\rnmaps\maps\MapUIBlock.java:7: error: package com.facebook.react.fabric.interop does not exist
import com.facebook.react.fabric.interop.UIBlockViewResolver;
                                        ^
C:\_source\everlights.mobileapp.v4\node_modules\react-native-maps\android\src\main\java\com\rnmaps\maps\MapUIBlock.java:64: error: package com.facebook.react.fabric.interop does not exist
interface UIBlockInterface extends UIBlock, com.facebook.react.fabric.interop.UIBlock  {}
                                                                             ^
C:\_source\everlights.mobileapp.v4\node_modules\react-native-maps\android\src\main\java\com\rnmaps\maps\MapUIBlock.java:35: error: cannot find symbol
    public void execute(UIBlockViewResolver uiBlockViewResolver) {
                        ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
C:\_source\everlights.mobileapp.v4\node_modules\react-native-maps\android\src\main\java\com\rnmaps\maps\MapUIBlock.java:39: error: cannot find symbol
    private void executeImpl(NativeViewHierarchyManager nvhm, UIBlockViewResolver uiBlockViewResolver) {
                                                              ^
  symbol:   class UIBlockViewResolver
  location: class MapUIBlock
C:\_source\everlights.mobileapp.v4\node_modules\react-native-maps\android\src\main\java\com\rnmaps\maps\MapUIBlock.java:56: error: cannot find symbol
            ((FabricUIManager) uiManager).addUIBlock(this);
                                         ^
  symbol:   method addUIBlock(MapUIBlock)
  location: class FabricUIManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Steps to reproduce

I deleted the node_modules folder in my React Native project and tried to run the Android app with maps. I'm getting this error: "Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'. I even tried using different versions of react-native-maps: both ^1.11.1 and ^1.15.6.
I was able to fix the "Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'" error by:
* Restoring the node_modules folder from a backup.
* Updating the react-native-maps package to a compatible version (possibly the original version used).
* Running the Android project again.

### Expected result

App run sucessfully

### Actual result

we got error
![Screenshot 2024-07-11 at 3 16 35 PM](https://github.com/react-native-maps/react-native-maps/assets/175301466/730214b9-ad1c-4fcd-984a-3749314e3cc9)

### React Native Maps Version

 ^1.11.1 and ^1.15.6.

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.8

### What version of Expo are you using?

Not using Expo

### Device(s)

Any android device

### Additional information

    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8

**Comment by matale** [comment]
I'm confused why would you expect RN to work when you delete the node_modules folder?

**Comment by mobileashvin** [comment]
After deleted then again nam install then try to run in android and get error

On 11 Jul 2024, at 5:57 PM, Roman Mbwasi ***@***.***> wrote:


I'm confused why would you expect RN to work when you delete the node_modules folder?

**Comment by mobileashvin** [comment]
Thanks. It is working on "react-native-maps": "^1.11.3” version

On 11 Jul 2024, at 10:40 PM, Roman Mbwasi ***@***.***> wrote:


I think its the same issue here so one of those solutions should work #5079 <https://github.com/react-native-maps/react-native-maps/issues/5079> I think the main issue is using ^ in you versions it automatically updates to the latest minor version so remove the ^ if that doesn't work read through the thread.

**Comment by mobileashvin** [comment]
Now Not working on 1.11.3

On 12 Jul 2024, at 11:52 AM, Ashvin ***@***.***> wrote:

Thanks. It is working on "react-native-maps": "^1.11.3” version

On 11 Jul 2024, at 10:40 PM, Roman Mbwasi ***@***.***> wrote:


I think its the same issue here so one of those solutions should work #5079 <https://github.com/react-native-maps/react-native-maps/issues/5079> I think the main issue is using ^ in you versions it automatically updates to the latest minor version so remove the ^ if that doesn't work read through the thread.
