### ISSUE TITLE
Flickering of marker icons on iOS

### ISSUE THREAD

**Issue by Hibbem** [react-native-maps/react-native-maps#5118]
### Summary

On some iOS devices, when I render two markers w/ a different icon are rendered on the exact same location, it results in a flickering between the two icons. On Android, only the latest icon is rendered. An approach to fix this is by grouping the markers, but just wanted to check if there is another solution to tackle this problem / bug.
This is also not a rendering loop, I already checked that to make sure 😄 

### Reproducible sample code

```TSX
poisInRange.map((poi) => (
                <Marker
                  key={poi.id}
                  id={`${poi.id}`}
                  image={getMarkerForCategory(poi.poiCategoryName)}
                  coordinate={{ longitude: poi.location.longitude, latitude: poi.location.latitude }}
                />
              );
            ))
```

### Steps to reproduce

render 2 Markers w/ a different image in the same location

### Expected result

The latest rendered image will be visible

### Actual result

There is flickering between both images

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.6

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 15 pro iOS 17

### Additional information

(I checked some other tickets, but they are all referring to flickering on Android, so I opened a new one )

**Comment by Buibui-Technologies** [comment]
You can add tracksViewChanges={false}, but doing this will break any images rendered within the marker (they won't render). You may replace the image with an icon (any library e.g expo/vector-icons), or use an emoji if you'd see fit.

**Comment by itayphytech** [comment]
you should add zIndex. higher zIndex to top marker
