### ISSUE TITLE
Overlay custom markers with Google markers make onPress not working

### ISSUE THREAD

**Issue by ALexandreM75013** [react-native-maps/react-native-maps#5119]
### Summary

Hi,

I am having an issue with react native maps on android (not tested on ios). When I have custom markers overlaying a Google maps interest point (city's text, monument marker/text...) my marker does not respond to onPress unless I insist a lot. If my custom marker is not overlaying anything, the onPress works perfectly.

Here in the below screenshot, the left marker works perfectly when pressing on it, but the one in red does not respond to onPress because it is overlaying the text "Cathedrale Notre-Dame-De-Paris" :

![Capture](https://github.com/user-attachments/assets/11fd1653-3661-4082-af95-8ba53a912f71)

### Reproducible sample code

```TSX
renderMarker = (data) => {
    return (
      <Marker
        key={data.key}
        coordinate={data.coordinates}
        tracksViewChanges={this.state.tracksViewChanges}
        identifier={data.key}
        style={styles.MarkerStyle}
        anchor={{ x: 0.55, y: 1 }}
        //Press events
        onPress={this.onMarkerPress}
      >
        <CustomMarkerView
          //Data
          data={data}
        />
      </Marker>
    );
  }

render() {
   <MapView
          ref={this.mapRef}
          initialCamera={this.returnInitialCamera()}
          onRegionChangeComplete={this.onRegionChangeComplete}
          style={styles.MapStyle}
          customMapStyle={map_style}
          showsScale={false}
          showsTraffic={false}
          showsIndoors={false}
          zoomControlEnabled={false}
          rotateEnabled={false}
          pitchEnabled={false}
          toolbarEnabled={false}
          maxZoomLevel={18}
          mapType={this.state.map_type}
          cacheEnabled={this.props.cacheEnabled}
          onMapReady={this.onMapReady}
          moveOnMarkerPress={false}
          edgePadding={{
            top: 25,
            bottom: 25,
            left: 25,
            right: 25,
          }}
          provider='google'
        >
          {this.state.markers_list.map((marker, id) => {
            return (this.renderMarker(marker));
          })}
        </MapView>
}
```

### Steps to reproduce

Render a custom marker `<Marker />` which is overlaying a Google Maps interest point marker or text.

### Expected result

All custom `<Marker />` should have the `onPress` always working wherever on the map.

### Actual result

`onPress` of `<Marker />` is not responding since it is overlaying a Google Maps interest point. Note: nothing is happening on the map at all.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.5

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung S10

**Comment by ssommelet21** [comment]
Hello.

Tu pourrais étoffer cet exemple ? : https://snack.expo.dev/@ssommelet21/alexandrem75013

Please modify this example.

**Comment by paalprogger** [comment]
Have you found a solution to this? I'm experiencing the same issue
