### ISSUE TITLE
React native maps crashes on specific devices Android

### ISSUE THREAD

**Issue by SciupaCodice** [react-native-maps/react-native-maps#5120]
### Summary

I have added react native maps to my app and on Android It crashes opening the mp for specifica devices like samsung s22, samsung s23, but for other samsung It works

### Reproducible sample code

```TSX
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}

### Expected result

Not crash my app

### Actual result

It crash opening the map

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.3

### What version of Expo are you using?

SDK 48

### Device(s)

samsung s22, samsung s23

**Comment by ssommelet21** [comment]
IMO, you might find the problem in logcat.

    Connect the USB cable.
    Run: adb devices
    If com.xxx.yyy is your bundle name, run: **adb logcat -d com.xxx.yyy > c:\logs.txt**

Then we could see more with your logs.txt.

**Comment by salah-ghanim** [comment]
without a clear stack trace with the cause being react-native-maps this issue can't be handled.

fyi there are many apps using RNM with 100k+ downloads on android devices and no major crash issues.
