### ISSUE TITLE
googleMapId

### ISSUE THREAD

**Issue by demoox** [react-native-maps/react-native-maps#5123]
### Summary

The googleMapId attribute does not seem to have any effect on IOS compared to the customMapStyle attribute which works very well.

Following https://github.com/react-native-maps/react-native-maps/pull/4922, the Google maps SDK is well above version 8.2 as of today, so what is the problem ? 

### Reproducible sample code

```TSX
<MapView 
style={{ flex: 1 }} 
provider={PROVIDER_GOOGLE}
googleMapId='XXXXXXXXXXX'
initialRegion={{
  latitude: lat,
  longitude: lng,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421
}}
showsUserLocation={true}
showsMyLocationButton={true}
>
```

### Steps to reproduce

.

### Expected result

Create a map style on the cloud, then get the map id and set it in the "googleMapId" attribute

### Actual result

The default map style is applied instead of the map with the defined id.

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.6

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone XS Max

### Additional information

EXPO V50

**Comment by salah-ghanim** [comment]
@demoox it shouldn't be possible that you use react-native 0.73.6 and react-native-maps 1.15.6 

you need react-native 0.74 to have that version of react-native-maps working which tells me the problem you're facing is somewhere else.

please test a clean project with latest version of RN-maps and RN itself

**Comment by demoox** [comment]
Thank you for your answer @salah-ghanim 

I updated RN and RN-Maps with the latest versions, however I don't see any changes, do you know where the problem could come from ?

**Comment by salah-ghanim** [comment]
@demoox I would recommend that you run the app on an iOS device in debug mode and try and check the values in

AirGoogleMap.m

- (instancetype)initWithMapId:(NSString *)mapId andZoomTapEnabled:(BOOL)zoomTapEnabled

you should have both the String mapId not being null

and the mapId object         GMSMapID *mapID = [GMSMapID mapIDWithIdentifier:mapId];
also not null.

if both are setup then you might need to try and modify the google maps version to see, maybe there is a bug with the version included in this library.

**Comment by MoFerhat** [comment]
Hi **@salah-ghanim** 
Sorry for the late response.

How can I do this knowing that I only develop with expo and I don't have access to Xcode?

 https://github.com/react-native-maps/react-native-maps/issues/5147 seems to have the same problem but on Android

**Comment by roshan-ship-it** [comment]
@salah-ghanim I tried debugging the xcode and mapID is nill. I'm not much familiar with xcode but to me it looks like googlemapid gets set after the initialization and below code gets called before setting the googlemapid, that might be the part of the problem.

AirGoogleMap.m
  the mapId object GMSMapID *mapID = [GMSMapID mapIDWithIdentifier:mapId];
