### ISSUE TITLE
iOS and Android app carshing on add Marker or Polyline on map

### ISSUE THREAD

**Issue by ashishneomenta** [react-native-maps/react-native-maps#5135]
### Summary

I added sample code. App crashing if I add marker or Polyline on map.

I am using latest SDK, React native and POD.
![Simulator Screenshot - iPhone Xs - 2024-08-06 at 18 55 50](https://github.com/user-attachments/assets/78ece8cb-371b-4cf7-9b64-1cc5efc7044a)

### Reproducible sample code

```TSX
import React from "react";
import {StyleSheet} from "react-native";
import MapView from "react-native-maps";
import {Polyline} from "react-native-maps";

interface MapWithLineProps
{
  // You can add any props you need here
}

const RawMapViewer: React.FC<MapWithLineProps> = () =>
{
  const coordinates = [
    {
      latitude: 37.78825,
      longitude: -122.4324
    },
    {
      latitude: 37.75825,
      longitude: -122.4624
    },
    {
      latitude: 37.76825,
      longitude: -122.4824
    }
  ];

  return (
    <MapView>
      <Polyline
        coordinates={[
          {
            latitude: 37.8025259,
            longitude: -122.4351431
          },
          {
            latitude: 37.7896386,
            longitude: -122.421646
          }
          // ... more coordinates
        ]}
        strokeColor="#000"
        strokeWidth={2}
      />
    </MapView>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    alignItems: "center",
    height: 500
  },
  map: {
    ...StyleSheet.absoluteFillObject
  }
});
export default RawMapViewer;
```

### Steps to reproduce

Add marker or polyline 

### Expected result

It should show marker on map

### Actual result

App Crashing

### React Native Maps Version

Latest

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.74

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone XS 17.4

### Additional information

Can anyone can help here?

**Comment by simonreid** [comment]
see: https://github.com/react-native-maps/react-native-maps/issues/4467#issuecomment-1871400334

`@babel/plugin-transform-private-methods` will cause this crash, unless overridden in babel config
