### ISSUE TITLE
Android crashes with IllegalStateException - Can't take a snapshot while executing in the background error

### ISSUE THREAD

**Issue by Saad-Bashar** [react-native-maps/react-native-maps#5136]
### Summary

We are getting a lot of crash notifications from sentry and the crash has something to do with react-native-maps. This is what we get in sentry,

![Screenshot 2024-08-12 at 4 46 37 PM](https://github.com/user-attachments/assets/85a40347-4bed-47b5-b3f5-304852d38df2)

For more info, we are using react native cli app with expo package. The version is, "react-native-maps": "1.7.1" with expo SDK 49.

### Reproducible sample code

```TSX
<MapView
      onPress={props.onSelectMap}
      onMapReady={() => {
        setTimeout(() => {
          if (defaultMarker?.current && defaultMarker.current !== null) {
            defaultMarker.current.showCallout();
          }
        }, 10);
      }}
      region={region}
      zoomEnabled={false}
      loadingEnabled={true}
      scrollEnabled={false}
      rotateEnabled={false}
      pitchEnabled={false}
      showsCompass={true}
      style={{height: height / 3}}
      showsUserLocation={true}
      cacheEnabled={true}
      showsMyLocationButton={true}
      toolbarEnabled={true}>
      <Marker coordinate={getRegion(props.coordinates)} ref={defaultMarker}>
        <Image source={marker} className="w-12 h-12" />
        <Callout onPress={props.onSelectMap}>
          <View className="w-80">
            <Text className="text-center" numberOfLines={2}>
              {props.address}
            </Text>
          </View>
        </Callout>
      </Marker>
    </MapView>
```

### Steps to reproduce

Can't reproduce so far on our end. But as mentioned, it is very random.

### Expected result

The crash is very random. The app is crashing on app start and in different places.

### Actual result

Should not crash

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.15

### What version of Expo are you using?

SDK 48

### Device(s)

Android

### Additional information

EXPO SDK 49

**Comment by ssommelet21** [comment]
Hi,

Look like this issue here :

https://github.com/googlemaps/android-maps-compose/issues/590

**Comment by Saad-Bashar** [comment]
Yes, I was about to link that. On our app, the map is pretty simple. Just showing a marker and we are not doing anything else with it. Any idea how can I fix this? Thanks!

**Comment by ssommelet21** [comment]
For me, this seems more like a Google Maps problem than an issue with react-native-maps. Your code seems to stress the MapView too much.

First, I would try a simple button (on/off) with:

onPress(){
  if(toggledOn){
    this.marker.showCallout();
  } else {
    this.marker.hideCallout();
  }
}

If it never crashes, then you should call showCallout more gently (perhaps with useState & useEffect?).

What intrigues me are the two events. I have a bad feeling about this:

```
<MapView
      onPress={props.onSelectMap}
```
      
and

`<Callout onPress={props.onSelectMap}>`

I am not an expert.

**Comment by Saad-Bashar** [comment]
Thanks for your kind help! Yes, you are right. This code was done a long time back and we did not have a good look at it after that. Problem is, so far we haven't been able to reproduce it locally. We already see Sentry issues. For more clarity, this is our full code, Please let me know if you see something else off. 

The crashes are also happening randomly, it's not like the crash only happens on the map page. So it may be internal issues.

```

const regionFrom = (lat, lon, distance) => {
  distance = distance / 2;
  const circumference = 40075;
  const oneDegreeOfLatitudeInMeters = 111.32 * 1000;
  const angularDistance = distance / circumference;
  const latitudeDelta = distance / oneDegreeOfLatitudeInMeters;
  const longitudeDelta = Math.abs(
    Math.atan2(
      Math.sin(angularDistance) * Math.cos(lat),
      Math.cos(angularDistance) - Math.sin(lat) * Math.sin(lat),
    ),
  );

  return {
    latitude: lat,
    longitude: lon,
    latitudeDelta,
    longitudeDelta,
  };
};
const getRegion = props => {
  const [latitude, longitude] = split(props, ',');
  try {
    let region = regionFrom(toNumber(latitude), toNumber(longitude), 2000);
    return region;
  } catch {
    return {
      latitude: toNumber(latitude),
      longitude: toNumber(longitude),
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    };
  }
};
const ShiftMap = props => {
  const defaultMarker = useRef(null);
  let region = getRegion(props.coordinates);
  return (
    <MapView
      onPress={props.onSelectMap}
      onMapReady={() => {
        setTimeout(() => {
          if (defaultMarker?.current && defaultMarker.current !== null) {
            defaultMarker.current.showCallout();
          }
        }, 10);
      }}
      region={region}
      zoomEnabled={false}
      loadingEnabled={true}
      scrollEnabled={false}
      rotateEnabled={false}
      pitchEnabled={false}
      showsCompass={true}
      style={{height: height / 3}}
      showsUserLocation={true}
      cacheEnabled={true}
      showsMyLocationButton={true}
      toolbarEnabled={true}>
      <Marker coordinate={getRegion(props.coordinates)} ref={defaultMarker}>
        <Image source={marker} className="w-12 h-12" />
        <Callout onPress={props.onSelectMap}>
          <View className="w-80">
            <Text className="text-center" numberOfLines={2}>
              {props.address}
            </Text>
          </View>
        </Callout>
      </Marker>
    </MapView>
  );
};```

**Comment by ssommelet21** [comment]
you don't need using a timer
more gently (perhaps with useState & useEffect = 

Like this :

```
import React, { useEffect, useRef, useState } from 'react';
import { View, Text, Image } from 'react-native';
import MapView, { Marker, Callout } from 'react-native-maps';

const YourComponent = (props) => {
  const defaultMarker = useRef(null);
  const [mapReady, setMapReady] = useState(false);

  useEffect(() => {
    if (mapReady && defaultMarker.current) {
      defaultMarker.current.showCallout();
    }
  }, [mapReady]);

  return (
    <MapView
      onPress={props.onSelectMap}
      onMapReady={() => setMapReady(true)}
      region={region}
      zoomEnabled={false}
      loadingEnabled={true}
      scrollEnabled={false}
      rotateEnabled={false}
      pitchEnabled={false}
      showsCompass={true}
      style={{ height: height / 3 }}
      showsUserLocation={true}
      cacheEnabled={true}
      showsMyLocationButton={true}
      toolbarEnabled={true}
    >
      <Marker coordinate={getRegion(props.coordinates)} ref={defaultMarker}>
        <Image source={marker} className="w-12 h-12" />
        <Callout onPress={props.onSelectMap}>
          <View className="w-80">
            <Text className="text-center" numberOfLines={2}>
              {props.address}
            </Text>
          </View>
        </Callout>
      </Marker>
    </MapView>
  );
};
```

**Comment by Saad-Bashar** [comment]
Thanks! Will try that. I am afraid if that will solve the crash that we are having in our repo. The crash seems to be an internal thing in google maps.

**Comment by ssommelet21** [comment]
I don't understand the "you cannot take a snapshot while executing in the background" maybe checking if the app is running in the background is only the solution :

https://reactnative.dev/docs/appstate

gl.

**Comment by Saad-Bashar** [comment]
It seems like a built in android google map issue, we may try to update our react-native-maps package but first we need to update expo sdk first.

**Comment by babacarcissedia** [comment]
seeing this on my end too with sentry. Probably going to start checking appstate before rendering maps ?!

**Comment by Kaosc** [comment]
I was experiencing this issue when cacheEnabled was set to true. After removing that prop, the problem randomly disappeared.

**Comment by angelica-snowit** [comment]
I'm experiencing this log also.
