### ISSUE TITLE
Any way to use dynamic google map ids

### ISSUE THREAD

**Issue by saransh-malik** [react-native-maps/react-native-maps#5147]
### Summary

When using googleMapId, google doesn't let you use old styling options and you need to move over to use cloud styling. Now if you want to have different style of maps supported you need to keep changing googleMapId, is there anyway to reflect the map id changes instantly on change, currently you need to redraw the map to get them to change. 

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      googleMapId={'mapID'}
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

1. Create a mapview with googleMapId
2. Try to dynamically change the value of googleMapId

### Expected result

The new styling related to the change mapId should be reflected on the map.

### Actual result

There is no change to the map view

### React Native Maps Version

1.11.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.69.11

### What version of Expo are you using?

Not using Expo

### Device(s)

S23 Ultra

**Comment by MoFerhat** [comment]
https://github.com/react-native-maps/react-native-maps/issues/5123 same problem on IOS

**Comment by chris-ux** [comment]
This should be reopened, this is still a problem and was never addressed or responded to.
