### ISSUE TITLE
The map is red on the iOS 18 simulator

### ISSUE THREAD

**Issue by Nalymoslih** [react-native-maps/react-native-maps#5170]
### Summary

The map shows red when zoomed out, but it’s not red when zoomed in. This happens only on the simulator.

### Reproducible sample code

```TSX
.
```

### Steps to reproduce

.

### Expected result

.

### Actual result

.

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

18.2.0

### What version of Expo are you using?

Not using Expo

### Device(s)

iphoen 16pro ios 18

**Comment by salah-ghanim** [comment]
@Nalymoslih please never feel entitled to submit an issue / bug report and ignore the clear instructions of how to submit one

**Comment by AngelRamirezMetodika** [comment]
Me surgió el mismo problema del mapa en rojo, implementando el mapa básico.

<MapView
      initialRegion={userLocation as Region}
      region={userLocation as Region}
      loadingEnabled={true}
      showsUserLocation={showsUserLocation}
      style={styles.mapStyle}
/>

https://github.com/user-attachments/assets/3b303650-592b-4bca-b37f-b4d43513825c

**Comment by eerojaaskelainen** [comment]
Affirm this. Seems to be an issue with IOS 18 simulator.
https://forums.developer.apple.com/forums/thread/765787
