### ISSUE TITLE
In Android Maps Screen is completely Blank 

### ISSUE THREAD

**Issue by karthikeyancontus** [react-native-maps/react-native-maps#5171]
### Summary

      
        "react": "18.2.0",
        "react-native": "0.72.10",
        "react-native-maps": "1.15.3",
    
      <MapView
            style={styles.map}
            initialRegion={location}
            ref={mapViewRef}
            onRegionChangeComplete={handleRegionChange}
            showsCompass={true}
            showsMyLocationButton={true}
            showsScale={true}
            onPress={handleMapPress}>
            {Boolean(location) && (
               <Marker
                  coordinate={{
                     latitude: location.latitude,
                     longitude: location.longitude,
                  }}
               />
            )}
         </MapView>

Able View in iOS,
<img width="452" alt="image" src="https://github.com/user-attachments/assets/cebaa4d3-a593-4d07-b823-7f1eedfbcc28">

but not in Android 
<img width="406" alt="image" src="https://github.com/user-attachments/assets/cd34286f-742a-4870-9a84-f57a4fe29243">

I tried complete android gradlew clean and node_modules cleaning, pcakage-lock.json clean, and check that api working or not, it's already working in another project 

### Reproducible sample code

```TSX
"react": "18.2.0",
        "react-native": "0.72.10",
        "react-native-maps": "1.15.3",
    
      <MapView
            style={styles.map}
            initialRegion={location}
            ref={mapViewRef}
            onRegionChangeComplete={handleRegionChange}
            showsCompass={true}
            showsMyLocationButton={true}
            showsScale={true}
            onPress={handleMapPress}>
            {Boolean(location) && (
               <Marker
                  coordinate={{
                     latitude: location.latitude,
                     longitude: location.longitude,
                  }}
               />
            )}
         </MapView>
```

### Steps to reproduce

Just installed and run it, ite's not working 

### Expected result

Need to show the map screen

### Actual result

map is not rendering in android only 

### React Native Maps Version

1.15.3

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.10

### What version of Expo are you using?

Not using Expo

### Device(s)

Google Pixel 6

**Comment by suchuanzhong** [comment]
How did you solve the same problem

**Comment by arunpku** [comment]
Same error

**Comment by PhilippPriller** [comment]
Any update on this? Facing the exact same issue using version 1.20.1. It worked just fine a few weeks ago.
