### ISSUE TITLE
Can't get lineDashPattern to work with GeoJson on Android

### ISSUE THREAD

**Issue by mbackonja** [react-native-maps/react-native-maps#5190]
### Summary

Simply, `lineDashPattern={[6, 6]}` does not work on Android. The Polygon line is solid and not dashed. I saw this PR https://github.com/react-native-maps/react-native-maps/pull/5121 but I'm already on a higher version of react-native-maps (1.18.2) and this should be available from 1.17.0...

### Reproducible sample code

```TSX
<Geojson
  geojson={geoJsonData.polygons}
  strokeColor="#66C61C"
  strokeWidth={4}
  lineDashPattern={[6, 6]}
  fillColor="rgba(255, 255, 255, 0.5)"
/>
```

### Steps to reproduce

Open the Android app and observe that the Polygon line is not dashed compared to the iOS app where it is dashed... 

### Expected result

Line to be dashed the same way it is on iOS

### Actual result

The Line is not dashed at all

### React Native Maps Version

1.18.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.5

### What version of Expo are you using?

SDK 48

### Device(s)

Xiaomi 12T Pro (Android 14)

### Additional information

The Expo version is actually `51.0.37` but in the dropdown the highest version I was able to choose is `SDK 48`...

**Comment by perryfaro** [comment]
@mbackonja Maybe the fillColor is the problem, could you check if the remove that prop the dash will be shown?

**Comment by mbackonja** [comment]
I just tried, it doesn't work... On iOS everything is working perfectly...

Attached images of my attempts and the code that is used for each screenshot:

```
            <Geojson
              geojson={geoJsonData.polygons}
              strokeColor="#66C61C"
              strokeWidth={4}
              lineDashPattern={[6, 6]}
              fillColor="rgba(255, 255, 255, 0.5)"
            />
```
![image](https://github.com/user-attachments/assets/5bb5344c-bc18-4e56-a5d9-dc3d48fc96f1)

```
            <Geojson
              geojson={geoJsonData.polygons}
              strokeColor="#66C61C"
              strokeWidth={4}
              lineDashPattern={[6, 6]}
            />
```
![image](https://github.com/user-attachments/assets/076e9b63-4648-4171-96e1-279e1ac13781)

```
            <Geojson
              geojson={geoJsonData.polygons}
              strokeWidth={4}
              lineDashPattern={[6, 6]}
            />
```
![image](https://github.com/user-attachments/assets/fff556d7-e6d9-4ee9-be89-7583a4528cf7)

**Comment by Ayoubdesigner101** [comment]
can any one show this question https://stackoverflow.com/questions/79133414/invariant-violationnew-nativeeventemitter-requires-a-non-null-argument-js-e

**Comment by mbackonja** [comment]
> can any one show this question https://stackoverflow.com/questions/79133414/invariant-violationnew-nativeeventemitter-requires-a-non-null-argument-js-e

I'm pretty confused, are you sure you answered to the correct issue?

**Comment by mbackonja** [comment]
Any updates to this one? Am I the only one experiencing this issue?

**Comment by salah-ghanim** [comment]
@mbackonja yes unfortunately it seems like it's a you thing

this is the screenshot from an android device

![Screenshot_20241109_205739_rnmshowcase](https://github.com/user-attachments/assets/a273ec4d-68b1-4842-ad55-a76563e6e3ae)


this is the code:

`import React from 'react';
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
  TouchableOpacity,
} from 'react-native';
import MapView, {Geojson} from 'react-native-maps';
import {FeatureCollection} from 'geojson';

const {width, height} = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
let id = 0;

function randomColor() {
  return `#${Math.floor(Math.random() * 16777215)
    .toString(16)
    .padStart(6)}`;
}

const PADDING = 0.01; // Adjust padding as needed

const squareOnMap: FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {},
      geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [
              LONGITUDE - (LONGITUDE_DELTA + PADDING) / 2,
              LATITUDE - (LATITUDE_DELTA + PADDING) / 2,
            ], // Bottom-left with padding
            [
              LONGITUDE + (LONGITUDE_DELTA + PADDING) / 2,
              LATITUDE - (LATITUDE_DELTA + PADDING) / 2,
            ], // Bottom-right with padding
            [
              LONGITUDE + (LONGITUDE_DELTA + PADDING) / 2,
              LATITUDE + (LATITUDE_DELTA + PADDING) / 2,
            ], // Top-right with padding
            [
              LONGITUDE - (LONGITUDE_DELTA + PADDING) / 2,
              LATITUDE + (LATITUDE_DELTA + PADDING) / 2,
            ], // Top-left with padding
            [
              LONGITUDE - (LONGITUDE_DELTA + PADDING) / 2,
              LATITUDE - (LATITUDE_DELTA + PADDING) / 2,
            ], // Closing the polygon with padding
          ],
        ],
      },
    },
  ],
};

class DefaultMarkers extends React.Component<any, any> {
  constructor(props: any) {
    super(props);

    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      markers: [],
    };
  }

  onMapPress(e: any) {
    this.setState({
      markers: [
        ...this.state.markers,
        {
          coordinate: e.nativeEvent.coordinate,
          key: id++,
          color: randomColor(),
        },
      ],
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          provider={this.props.provider}
          style={styles.map}
          initialRegion={this.state.region}
          onPress={e => this.onMapPress(e)}>
          <Geojson
            geojson={squareOnMap}
            strokeColor="#66C61C"
            strokeWidth={4}
            lineDashPattern={[6, 6]}
            fillColor="rgba(255, 255, 255, 0.5)"
          />
        </MapView>
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            onPress={() => this.setState({markers: []})}
            style={styles.bubble}>
            <Text>Tap map to create a marker of random color</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  bubble: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 80,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

export default DefaultMarkers;
`


the example project was used from master / latest release
