### ISSUE TITLE
[EXPO SDK 52] Markers randomly do not appear on Android

### ISSUE THREAD

**Issue by eBeyzaG** [react-native-maps/react-native-maps#5221]
### Summary

After updating to expo 52, my working code for showing markers do not work anymore. My markers on android do not appear. If I change coordinates and reload they appear but after restarting the server they are gone again. I tested multiple things but could not find the cause for disappearance. 

### Reproducible sample code

```TSX
import React, { useState } from 'react'
import { View } from 'react-native'
import MapView, { Marker } from 'react-native-maps'

const mapdemo = () => {

    const [location, setLocation] = useState({ lng: 20.3443, ltd: 25.435 })

    return (
        <View >
            <MapView style={{
                width: "100%",
                height: "100%"
            }}

                initialRegion={{
                    latitude: location.ltd,
                    longitude: location.lng,
                    latitudeDelta: 0.00922,
                    longitudeDelta: 0.00421
                }}
            >
                <Marker
                    key={Date.now()}
                    coordinate={{ latitude: location.ltd, longitude: location.lng }}
                ></Marker>


            </MapView>
        </View>
    )
}

export default mapdemo
```

### Steps to reproduce

Start the development server on Expo Go and test on my device with Expo Go.

### Expected result

Markers to appear on Android map view.

### Actual result

No markers appear on map on Android.

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.76.2

### What version of Expo are you using?

SDK 52

### Device(s)

Samsung Galaxy Z Flip6

**Comment by SaadHassanRopstam** [comment]
Any solution guys? Facing same issue

**Comment by eBeyzaG** [comment]
I downgraded back to Expo SDK 51 and it works again. I'll just use development build & wait until it's solved

**Comment by k2pme** [comment]
Is there any solution? I'm going through the same issue

**Comment by nicolas-meunier-97** [comment]
We are having the same issue here

**Comment by brandon-austin-lark** [comment]
disable new arch

**Comment by fynally** [comment]
Even `showsUserLocation` location is not working too

**Comment by brunotalentum** [comment]
using it, it works in the apk version, but it still has problems in expo go:
"newArchEnabled": false,
  "experimental": {
    "enableFabricRenderer": false
  }

**Comment by peefg** [comment]
none of above has helped so far. still stuck with it, any news, please?

**Comment by AlenMartinez** [comment]
I also have the same error, it was working great until I updated expo SDK to 52

**Comment by eBeyzaG** [comment]
I downgraded back to expo sdk 51 and switched to development build. Let me know if the issue gets fixed for sdk 52 so I can close this

**Comment by ilyasassakali** [comment]
Any solution found to this bug ?

**Comment by edgarscr** [comment]
+1 same for me https://github.com/react-native-maps/react-native-maps/issues/5236

**Comment by JaRoMasterDev** [comment]
Same here. Disabling the new architecture didn't do the trick for me

**Comment by brunotalentum** [comment]
If you use it this way, it doesn't work in Expo Go, but it works when you export the apk:
    "android": {
        "newArchEnabled": false,
        "experimental": {
        "enableFabricRenderer": false
        }
    }

**Comment by JaRoMasterDev** [comment]
> If you use it this way, it doesn't work in Expo Go, but it works when you export the apk: "android": { "newArchEnabled": false, "experimental": { "enableFabricRenderer": false } }

I tried this and built my app using EAS, and it still didn't work

**Comment by CrAcKy-glitch** [comment]
works when the app gets built using eas, but does not work on SDK 52 on android, now have to revert back

**Comment by estoilkov** [comment]
How did you downgrade to expo 51?

**Comment by coffeedevsolutions** [comment]
Same issue here, new arch disabled and still not working.

Getting a combination of "Invalid view returned from registry, expecting AIRMap, got: (null)", markers not appearing, or certain markers appears and disappearing randomly on render.

**Comment by CrAcKy-glitch** [comment]
i went throught the changelog doc of expo for SDK 52 and found this 
<img width="923" alt="image" src="https://github.com/user-attachments/assets/c6f2754d-f201-4f4c-9637-77e0ea41be8f">

they are losing support for google maps in SDK52 and are asking to make those changes in the dev build instead

**Comment by JaRoMasterDev** [comment]
@CrAcKy-glitch Where did you find this?

**Comment by edgarscr** [comment]
> i went throught the changelog doc of expo for SDK 52 and found this <img alt="image" width="923" src="https://private-user-images.githubusercontent.com/63924025/392011512-c6f2754d-f201-4f4c-9637-77e0ea41be8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNTE4NTcsIm5iZiI6MTczMzI1MTU1NywicGF0aCI6Ii82MzkyNDAyNS8zOTIwMTE1MTItYzZmMjc1NGQtZjIwMS00ZjRjLTk2MzctNzdlMGVhNDFiZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE4NDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTkwYmE4ZDY0MTg5NjNhY2RjZmQzYWE5ZmRiNjNlNTBmNmI2YWE4YmNiZjAyNzNmNjg2ODcyOTgxZmIwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CFUGDo611Xe4w_PFYyz2xBpPg737rWHfzLX4Qg2MDPc">
> 
> they are losing support for google maps in SDK52 and are asking to make those changes in the dev build instead, maybe that's why they didn't care about the marker prb

But it clearly says 'Expo Go for Android', which we don't use when compiling, and even then the map doesn't work as expected. According to my logic, that shouldn't be related to the cause of the problem.

**Comment by CrAcKy-glitch** [comment]
@edgarscr This has do with SDK's compatibility, although I agree with your point but I feel they didn't care about the backward compatibility, since they are losing support anyway, just like other libraries.

**Comment by TwoflexStudios** [comment]
+1 +1 +1+1 +1 +1+1 +1 +1+1 +1 +1+1 +1 +1

**Comment by peefg** [comment]
Is there any workaround for this at least, please?

I've been trying to setup a local development build, but in 
- Android emulator I still don't see any markers. But if they randomly appear they are cut and not working #5247
- For Expo go, Android doesn't show any markers (as above) and iPhone ends up with some bubble error (maybe there is an issue for this too).

It is crazy that it is being totally ignored by both parties, since (any) maps are probably the most used element in mobile apps.

**Comment by wldevlojaz** [comment]
> Is there any workaround for this at least, please?
> 
> I've been trying to setup a local development build, but in
> 
> * Android emulator I still don't see any markers. But if they randomly appear they are cut and not working [Custom Marker size is limited on Expo 52 (Android) #5247](https://github.com/react-native-maps/react-native-maps/issues/5247)
> * For Expo go, Android doesn't show any markers (as above) and iPhone ends up with some bubble error (maybe there is an issue for this too).
> 
> It is crazy that it is being totally ignored by both parties, since (any) maps are probably the most used component in mobile apps nowadays.

I fixed it by disabling the new architecture on Android and creating the prebuild of my app, instead of using expo-go I used expo run:android

**Comment by TwoflexStudios** [comment]
> Is there any workaround for this at least, please?
> 
> I've been trying to setup a local development build, but in
> 
> * Android emulator I still don't see any markers. But if they randomly appear they are cut and not working [Custom Marker size is limited on Expo 52 (Android) #5247](https://github.com/react-native-maps/react-native-maps/issues/5247)
> * For Expo go, Android doesn't show any markers (as above) and iPhone ends up with some bubble error (maybe there is an issue for this too).
> 
> It is crazy that it is being totally ignored by both parties, since (any) maps are probably the most used component in mobile apps nowadays.

I fixed it by disabling the new architecture on Android and creating the prebuild of my app, instead of using expo-go I used expo run:android

**Comment by coffeedevsolutions** [comment]
> @edgarscr This has do with SDK's compatibility, although I agree with your point but I feel they didn't care about the backward compatibility, since they are losing support anyway, just like other libraries. also I seldom think if expo would release a fix.

This would make sense except for the fact the the error is also happening for me in an almost identical fashion on iPhone using Apple Maps as well, new arch did not fix either.

**Comment by CrAcKy-glitch** [comment]
> > @edgarscr This has do with SDK's compatibility, although I agree with your point but I feel they didn't care about the backward compatibility, since they are losing support anyway, just like other libraries. also I seldom think if expo would release a fix.
> 
> 
> 
> This would make sense except for the fact the the error is also happening for me in an almost identical fashion on iPhone using Apple Maps as well, new arch did not fix either.

This problem should not with apple maps, try running npx expo install --fix , maybe you are having a incomp version of maps

**Comment by coffeedevsolutions** [comment]
> > > @edgarscr This has do with SDK's compatibility, although I agree with your point but I feel they didn't care about the backward compatibility, since they are losing support anyway, just like other libraries. also I seldom think if expo would release a fix.
> > 
> > 
> > This would make sense except for the fact the the error is also happening for me in an almost identical fashion on iPhone using Apple Maps as well, new arch did not fix either.
> 
> This problem should not be with apple maps, try running npx expo install --fix , maybe you are having a incomp version of maps

@CrAcKy-glitch I assumed my marker issues were the same as the original author but after looking into it some more they aren't, I am getting [ Invalid view returned from registry, expecting AIRMap, got: (null) ] - this is something react-native maps has never thrown before but it is causing my markers to not appears, or glitch in and out, whole map stutters.

Not the comment string for it but any helps here is much appreciated.

Also, npx expo install --fix did not work unfortunately, thank you for the suggestion though.

**Comment by limonrojo-nm** [comment]
Same issue here. Also [react-native-maps-clustering](https://www.npmjs.com/package/react-native-map-clustering/v/3.3.0) is not working on Android

**Comment by Kaivosukeltaja** [comment]
We're facing the same problem after upgrading to SDK 52 and the new architecture. Some of the markers with a longer text inside them can be partially seen. Interestingly, the arrows we created using the old borderWidth hack are visible for every marker but have the arrow points southeast instead of south and its location is at the top left of the container instead of bottom middle.

Also, when I navigate to another tab and then return to the one with the MapView, it resets the location to Null Island (0.0 / 0.0), uses the Google default tiles instead of our custom ones, and doesn't show any markers at all. When that happens, only a force quit will bring our own maps back.

**Comment by Abishzada** [comment]
@limonrojo-nm how do you downgrade to expo 51. do i need downgrade other packages too?

**Comment by limonrojo-nm** [comment]
> @limonrojo-nm how do you downgrade to expo 51. do i need downgrade other packages too?

Yes, sadly you need to downgrade also all the other expo related packages :/ 

You can check current SDK corresponding versions using [this](https://docs.expo.dev/more/expo-cli/#version-validation) `npx expo install --check`.

And if you are using expo go, you need to download the corresponding version [here](https://expo.dev/go) (Deprecated eco go version could only be used in Android and iOS simulator, but no iOS real devices)

**Comment by salah-ghanim** [comment]
see https://github.com/react-native-maps/react-native-maps/issues/5206

we will need to solve this among other issues to be able to support new arch fully, (currently in progress)

**Comment by AdeMarq** [comment]
Facing the same issue. Markers works perfectly on AppleMaps.  I don't intend on downgrading, but will my Markers show up in prebuild?

**Comment by stephenlyo** [comment]
I just realised that this issue is tied to Expo 52—really regretting the upgrade now lol

**Comment by soymonitus** [comment]
Same issue here. Using Expo 52, with newArchEnabled=true. No way to turn it off as it crashes with other dependencies I have. Any workaround or patch?

**Comment by UmiVilbig** [comment]
For anyone else stumbling into this issue. There was a recent architecture change and a subsequent migration. `react-native-maps` has since (i think i read this correctly) fixed the issue and you have to update your packages. I ran `npx expo install --check`

I went from `react-native: "0.76.5"` to `0.76.9` and `expo: "^52.0.23"` to `~52.0.46`. I created a new clean local build with `npm run android` which took a while but eventually worked. My Marker now shows on the map on the first render as expected.

**Although not recommended**, if you are still having trouble you can also try changing `newArchEnabled` in `app.json` to `false`

**Comment by bhavesh-trentium** [comment]
@salah-ghanim Hey guys, I noticed that most of the `react native maps marker not showing on Android` issues are just being closed with the patch solution `newArchEnabled=false`.

But that’s not really a fix — it’s just a workaround. In my case, disabling the new architecture actually breaks other packages in the project.

Would be great if we could have a proper fix instead of just closing issues with that temporary solution.

**Comment by abdulmateen-pb** [comment]
**+1**

**Comment by WLTheDev** [comment]
+1
