### ISSUE TITLE
Google Maps doesn't work on Ios outright

### ISSUE THREAD

**Issue by proevilz** [react-native-maps/react-native-maps#5224]
### Summary

When using `provider="google"` on an ios device, the map errors out. 

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} provider="google"/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});

```
##Reproducible on Snack: https://snack.expo.dev/HmvsU5kdanjZ3xj634vGx?platform=ios

### Steps to reproduce

Add in a `MapView` with `provider="google"`.

### Expected result

The map to work

### Actual result

Error screen
```
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in AIRGoogleMap (created by MapView)
    in MapView (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App
    in Unknown (created by Route(explore))
    in Suspense (created by Route(explore))
    in Route (created by Route(explore))
    in Route(explore) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabNavigator)
```

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Iphone 16 pro max (ios 18.1), snack emulator for iphone 16 pro

**Comment by Ghabriel-elias** [comment]
same issue

**Comment by kewang-codes** [comment]
same issue

**Comment by RenanC4** [comment]
Same Issue

**Comment by zju1** [comment]
same issue

**Comment by burakkaraceylan** [comment]
I’m facing the same issue.

**Comment by abhishekvermax** [comment]
getting same issue
![image](https://github.com/user-attachments/assets/dfe2beea-f233-489c-bfb9-48434fea5639)

**Comment by ian** [comment]
I believe this is an expo@52 issue. Happened as soon as I upgraded.

**Comment by dr-farooq** [comment]
same issue

**Comment by paliwal15** [comment]
any update that how can we fixed this issues

**Comment by paliwal15** [comment]
@proevilz did you find any solution for this issue?

provider="google"
(NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

**Comment by saramiap** [comment]
Same here with 52.011

**Comment by salah-ghanim** [comment]
see https://github.com/react-native-maps/react-native-maps/issues/5206


we will need to solve this among other issues to be able to support new arch fully, (currently in progress)
