### ISSUE TITLE
Marker Error: TypeError: this.getNativeComponent is not a function (it is undefined)

### ISSUE THREAD

**Issue by olipda** [react-native-maps/react-native-maps#5233]
### Summary

After installing react-native-maps, I cannot implement markers. The MapView works, but the marker does not.

Error:

ERROR Warning: TypeError: this.getNativeComponent is not a function (it is undefined) 

Here is my babel.config.js file:

```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {
          '@': './src',
        },
      },
    ],
    ['@babel/plugin-transform-class-properties', { loose: true }],
    ['@babel/plugin-transform-private-methods', { loose: true }],
    ['@babel/plugin-transform-private-property-in-object', { loose: true }],
    [
      'module:react-native-dotenv',
      {
        moduleName: 'react-native-dotenv',
        path: '.env',
      },
    ],
  ],
};
```

Running on React Native v0.75.4
React Native Maps version: 1.20.1

### Reproducible sample code

```TSX
<View style={{ flex: 1 }}>
			<MapView
				style={StyleSheet.absoluteFillObject}
				initialRegion={INITIAL_REGION}
				showsUserLocation
				showsMyLocationButton
				ref={mapRef}
				onRegionChangeComplete={onRegionChange}
			>
				{markers.map((marker, index) => (
					<MapMarker
						key={index}
						title={marker.name}
						coordinate={marker}
						onPress={() => onMarkerSelected(marker)}
					>
						<Callout onPress={calloutPressed}>
							<View style={{ padding: 10 }}>
								<Text style={{ fontSize: 24 }}>Hello</Text>
							</View>
						</Callout>
					</MapMarker>
				))}
			</MapView>
		</View>
```

### Steps to reproduce

Just try to call the Marker component 

### Expected result

I expect to display markers on the map

### Actual result

ERROR Warning: TypeError: this.getNativeComponent is not a function (it is undefined) 
![Snímek obrazovky 2024-11-25 v 18 37 14](https://github.com/user-attachments/assets/c64c6742-07b3-4049-b858-96feb46a53a6)

### React Native Maps Version

1.20.1

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.75.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 15 Pro Max

**Comment by VimukthiShohan** [comment]
Same here. @olipda Any solution?

**Comment by BenjaminWatts** [comment]
I have exactly the same issue

**Comment by gallavie** [comment]
I am also get the same error

**Comment by silvun01** [comment]
Me too , this issue

**Comment by sandipsarkar13** [comment]
Facing same issue in RN 0.76.3

**Comment by salah-ghanim** [comment]
@olipda please don't use this lib with the latest version of react-native, for now Fabric is not supported yet (in progress)

see: https://github.com/react-native-maps/react-native-maps/issues/5206#issuecomment-2504728236
and main readme

**Comment by MohanNB** [comment]
i am also facing same issues react-native-maps1.20.1 version ,some one please update correct answer .

**Comment by ombogdan** [comment]
how to fix it in react-native-maps 1.22.5 and     "react-native": "0.79.1",

**Comment by DivyeshPonkiya** [comment]
I am facing the same issues with "react-native": "0.78.2" and "react-native-maps": "1.22.1".

**Comment by Cheizr** [comment]
Experiencing the same. I'm trying to modify the marker to try if it fixes the issue of Marker not being rendered properly on the first component render.

"react-native": "^0.77.2",
"react-native-maps": "^1.23.7",

**Comment by leonardo-weber** [comment]
having the same problem even with new arch enabled

 "react-native": "^0.76.0",
 "react-native-maps": "^1.23.8",

**Comment by Masabrali** [comment]
This fix may help.
I have react-native version 0.79.1 and react-native-maps version 1.21.0 installed.
I have modified the MapMarker.tsx, MapCallout.tsx and decorateMapComponent.ts files to achieve the results. I also created the patch file just incase. I have shared all the files below.

[patch changes.zip](https://github.com/user-attachments/files/20905143/patch.changes.zip)

[react-native-maps+1.21.0.patch](https://github.com/user-attachments/files/20905168/react-native-maps%2B1.21.0.patch)

**Comment by leonaburime-ucla** [comment]
You may need to remove these from babel.config.js

`['@babel/plugin-transform-class-properties', { loose: true }],
      ['@babel/plugin-transform-private-property-in-object', { loose: true }],
      ['@babel/plugin-transform-private-methods', { loose: true }],`

from [this video](https://www.youtube.com/watch?v=AjMV8S59v-Y)

**Comment by TobiasKC** [comment]
> You may need to remove these from babel.config.js
> 
> `['@babel/plugin-transform-class-properties', { loose: true }], ['@babel/plugin-transform-private-property-in-object', { loose: true }], ['@babel/plugin-transform-private-methods', { loose: true }],`
> 
> from [this video](https://www.youtube.com/watch?v=AjMV8S59v-Y)

For anyone finding themselves with this issue still, can 2nd that this video fixed my issues as well.
