### ISSUE TITLE
Google Maps is not working on iOs with <MapView/> component

### ISSUE THREAD

**Issue by ChantalMorales** [react-native-maps/react-native-maps#5240]
### Summary

MapView is working great in Android but in iOs when i tried to use google Maps I got this error 
 ERROR  react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS. [Component Stack]

### Reproducible sample code

```TSX
MapContainer
        provider={PROVIDER_GOOGLE}
        region={region}
        onRegionChangeComplete={handleRegionChangeComplete}
        showsUserLocation
        showsMyLocationButton={false}
        style={{ flex: 1, width: "100%" }}
      >
        {userLocation && <Marker coordinate={userLocation} pinColor="red" />}

        {filteredVisibleRecyclers.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "recycler")}
          >
            <PinIcon source={recyclerPin} />
          </Marker>
        ))}
        {filteredVisibleCenters.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "center")}
          >
            <PinIcon source={centerPin} />
          </Marker>
        ))}
        {filteredVisiblePartners.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "partner")}
          >
            <PinIcon source={partnerPin} />
          </Marker>
        ))}
        {filteredVisibleStations.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "station")}
          >
            <PinIcon source={stationPin} />
          </Marker>
        ))}
        {filteredVisibleStores.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "store")}
          >
            <PinIcon source={storePin} />
          </Marker>
        ))}
        {visibleCleanPoints.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "cleanPoint")}
          >
            <PinIcon source={cleanPointPin} />
          </Marker>
        ))}
        {visiblePichaybots.map((loc) => (
          <Marker
            key={loc.id}
            coordinate={{ latitude: loc.latitude, longitude: loc.longitude }}
            onPress={() => handleMarkerPress(loc, "pichaybot")}
          >
            <PinIcon source={pichaybotPin} />
          </Marker>
        ))}
      </MapContainer>
```

### Steps to reproduce

When I definde the map in Android is working well but in iOs I'm getting this error: 
 ERROR  react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS. [Component Stack], not even loading Apple Maps component

### Expected result

Show the map with some marks here is a picture of how is working in android 
![image](https://github.com/user-attachments/assets/e16ccd11-d014-4986-bd41-01332fe5be09)

### Actual result

<img width="371" alt="image" src="https://github.com/user-attachments/assets/d344cb4e-167e-4132-8f2d-8a7597a90114">

### React Native Maps Version

1.14.0

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.74.5

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone 15 pro, iPhone 15, iPhone 13, iPhone 14, iPhone Xr

**Comment by myousufrtss** [comment]
Same here, Android runs fine. IOS crashes without any reasons whatsoever.

**Comment by myousufrtss** [comment]
@AntonMyr, I am using React Native cli,      "react-native": "0.76.0" and     "react-native-maps": "^1.20.1".  when i try to interact with map and markers, it unexpectedly close the simulator/device connected.

**Comment by FaithfulAudio** [comment]
this is a result of an internal issue with sub view nil I believe, there's a PR up for this, and I am awaiting it.

**Comment by ChantalMorales** [comment]
> @ChantalMorales Are you using Expo go or a development build?

Expo Go

**Comment by AntonMyr** [comment]
@ChantalMorales Okay I see. If you haven't, I would suggest to also try using a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) as Expo removed google maps support from Expo Go in the Expo SDK 51 release.

**Comment by ChantalMorales** [comment]
> @ChantalMorales Okay I see. If you haven't, I would suggest to also try using a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) as Expo removed google maps support from Expo Go in the Expo SDK 51 release.

We just update to SDK 52 and now this is the error 
![image](https://github.com/user-attachments/assets/53545d70-5595-45f5-a58a-25933434ea12)
should we try to use the development build either way ?

**Comment by easmar89** [comment]
![image](https://github.com/user-attachments/assets/ecfccd80-24cf-4d32-9909-7647b7a3e7c0)

As pointed out by @AntonMyr , expo made it clear in the SDK51 update that you can no longer use gogole maps like that. You have to use apple maps on ios if you want to use expo go, or use a dev build if you want google maps.  Details [here](https://expo.dev/changelog/2024/05-07-sdk-51#single-sdk-version-in-expo-go)

**Comment by ChantalMorales** [comment]
> @ChantalMorales Okay I see. If you haven't, I would suggest to also try using a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) as Expo removed google maps support from Expo Go in the Expo SDK 51 release.

@AntonMyr We did the development build but still got the same error

**Comment by AntonMyr** [comment]
> > @ChantalMorales Okay I see. If you haven't, I would suggest to also try using a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) as Expo removed google maps support from Expo Go in the Expo SDK 51 release.
> 
> @AntonMyr We did the development build but still got the same error

I suspect you might have an issue with the API key in that case.

- Make sure to add your google maps API key to your app.json when building the development build.
- Make sure the API key has the correct permissions

**Comment by salah-ghanim** [comment]
I'm closing this issue because it's all related to the same topic updating to support Fabric / latest react native

you can see in the readme that it's not supported yet here:
https://github.com/react-native-maps/react-native-maps/?tab=readme-ov-file#important-notes

and you can follow up here on the progress:
https://github.com/react-native-maps/react-native-maps/issues/5206
