### ISSUE TITLE
Error on startup android app after upgrading react-native version to 0.76.5

### ISSUE THREAD

**Issue by avinash-nimblechapps** [react-native-maps/react-native-maps#5277]
### Summary

app runs fine in android but got the error as open the app 
React-native : 0.76.5
react-native-maps : 1.20.1
newArchEnabled:true

### Reproducible sample code

```TSX
"react-native-maps": "^1.20.1",
```

### Steps to reproduce

upgrading react native version from 0.70.4 to 0.76.5 and also made changes in the other files 

### Expected result

need to run perfectly with new version

### Actual result

getting error

### React Native Maps Version

1.20.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.76.5

### What version of Expo are you using?

Not using Expo

### Device(s)

android emulator

### Additional information

![Screenshot_1733911094](https://github.com/user-attachments/assets/b0e33a6d-c291-4ab1-b33e-92b934a8fc2e)

**Comment by metkm** [comment]
How do you know if this is related to react-native-maps?
