### ISSUE TITLE
Google Map Not Working on IOS

### ISSUE THREAD

**Issue by paliwal15** [react-native-maps/react-native-maps#5287]
### Summary

When using provider="google" on an ios device, the map errors out.

### Reproducible sample code

```TSX

import React from 'react';
import MapView, {  PROVIDER_GOOGLE } from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} provider={PROVIDER_GOOGLE}/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

import MapView, {  PROVIDER_GOOGLE } from 'react-native-maps';

Add in a MapView with provider={PROVIDER_GOOGLE}.

### Expected result

The map to work.

### Actual result

Getting below Error :

 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in AIRGoogleMapMarker (created by MapMarker)
    in MapMarker (created by MapViewSection)
    in AIRGoogleMap (created by MapView)
    in MapView (created by MapViewSection)
    in RCTView (created by View)
    in View (created by MapViewSection)
    in RCTView (created by View)
    in View (created by MapViewSection)
    in MapViewSection (created by MapViewContainer)
    in RCTView (created by View)
    in View (created by MapViewContainer)
    in MapViewContainer (created by MapPage)
    in MapPage
    in Unknown (created by Route(map/index))
    in Suspense (created by Route(map/index))
    in Route (created by Route(map/index))
    in Route(map/index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SlotNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by SlotNavigator)
    in SlotNavigator (created by Slot)
    in Slot (created by LocationFlowLayout)
    in LocationFlowLayout
    in Unknown (created by Route((address)))
    in Suspense (created by Route((address)))
    in Route (created by Route((address)))
    in Route((address)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SlotNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by SlotNavigator)
    in SlotNavigator (created by Slot)
    in Slot (created by MainLayout)
    in RCTSafeAreaView (created by MainLayout)
    in Provider (created by MainLayout)
    in ThemeProvider (created by PaperProvider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by PaperProvider)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by PaperProvider)
    in PaperProvider (created by MainLayout)
    in I18nextProvider (created by MainLayout)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by MainLayout)
    in MainLayout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.5

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone

**Comment by zhenx** [comment]
Having exactly the same issue for iOS.

**Comment by paliwal15** [comment]
@theKashif  If I used "PROVIDER_DEFAULT," then the default map on the iPhone would show up, right? If I want to use a Google map on the iPhone, the provider value must be "PROVIDER_GOOGLE."

**Comment by zhenx** [comment]
@paliwal15 Thanks for the solution. Unfortunately, I still have the same issue. Mine is not about google map but trigged by heatmap.
 ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in AIRMapHeatmap (created by MapHeatmap)
    in MapHeatmap (created by MapWithAddressMarker)
    in AIRMap (created by MapView)
    in MapView (created by MapWithAddressMarker)
    in RCTView (created by View)
    in View (created by MapWithAddressMarker)
    in MapWithAddressMarker (created by Report)
    in RCTView (created by View)
    in View (created by Report)
    in Report
    in Unknown (created by Route(report))
    in Suspense (created by Route(report))
    in Route (created by Route(report))
    in Route(report) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator
    in Unknown (created by TabLayout)
    in TabLayout
    in Unknown (created by Route((tabs)))
    in Suspense (created by Route((tabs)))
    in Route (created by Route((tabs)))
    in Route((tabs)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in Unknown (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by RootLayout)
    in RootLayout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

**Comment by theKashif** [comment]
@paliwal15  in expo 52 you can't use google maps for ios in Expo Go (can be used in Development Build)

https://expo.dev/changelog/2024/11-12-sdk-52#deprecations

**Comment by paliwal15** [comment]
> @paliwal15 in expo 52 you can't use google maps for ios in Expo Go (can be used in Development Build)
> 
> https://expo.dev/changelog/2024/11-12-sdk-52#deprecations

Are you able to see Google Maps in the iOS development build? In my case, the map does not open in the development build, and in Expo Go, I got the above error.

**Comment by theKashif** [comment]
> > @paliwal15 in expo 52 you can't use google maps for ios in Expo Go (can be used in Development Build)
> > https://expo.dev/changelog/2024/11-12-sdk-52#deprecations
> 
> @theKashif Are you able to see Google Maps in the iOS development build? In my case, the map does not open in the development build, and in Expo Go, I got the above error.

Till now I do not try development build may be tomorrow morning i make one, but I was facing the same issue and got resolved by using default provider instead of google.
According to their documentation it should work in development builds.

**Comment by salah-ghanim** [comment]
see https://github.com/react-native-maps/react-native-maps/issues/5206

we will need to solve this among other issues to be able to support new arch fully, (currently in progress)
