### ISSUE TITLE
google map not working on ios

### ISSUE THREAD

**Issue by sbipinkandari02** [react-native-maps/react-native-maps#5288]
### Summary

facing 'error out' while using provider="google" on an ios device, 

### Reproducible sample code

```TSX
import React from 'react';
import MapView, {  PROVIDER_GOOGLE } from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} provider={PROVIDER_GOOGLE}/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

Add in a MapView with provider={PROVIDER_GOOGLE}.The map to work.

### Expected result

map will work

### Actual result

Getting below Error :

(NOBRIDGE) ERROR Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
in AIRGoogleMapMarker (created by MapMarker)
in MapMarker (created by MapViewSection)
in AIRGoogleMap (created by MapView)
in MapView (created by MapViewSection)
in RCTView (created by View)
in View (created by MapViewSection)
in RCTView (created by View)
in View (created by MapViewSection)
in MapViewSection (created by MapViewContainer)
in RCTView (created by View)
in View (created by MapViewContainer)
in MapViewContainer (created by MapPage)
in MapPage
in Unknown (created by Route(map/index))
in Suspense (created by Route(map/index))
in Route (created by Route(map/index))
in Route(map/index) (created by SceneView)
in StaticContainer
in EnsureSingleNavigator (created by SceneView)
in SceneView (created by SlotNavigator)
in PreventRemoveProvider (created by NavigationContent)
in NavigationContent
in Unknown (created by SlotNavigator)
in SlotNavigator (created by Slot)
in Slot (created by LocationFlowLayout)
in LocationFlowLayout
in Unknown (created by Route((address)))
in Suspense (created by Route((address)))
in Route (created by Route((address)))
in Route((address)) (created by SceneView)
in StaticContainer
in EnsureSingleNavigator (created by SceneView)
in SceneView (created by SlotNavigator)
in PreventRemoveProvider (created by NavigationContent)
in NavigationContent
in Unknown (created by SlotNavigator)
in SlotNavigator (created by Slot)
in Slot (created by MainLayout)
in RCTSafeAreaView (created by MainLayout)
in Provider (created by MainLayout)
in ThemeProvider (created by PaperProvider)
in RCTView (created by View)
in View (created by Portal.Host)
in Portal.Host (created by PaperProvider)
in RCTView (created by View)
in View (created by SafeAreaInsetsContext)
in SafeAreaProviderCompat (created by PaperProvider)
in PaperProvider (created by MainLayout)
in I18nextProvider (created by MainLayout)
in RNCSafeAreaProvider (created by SafeAreaProvider)
in SafeAreaProvider (created by MainLayout)
in MainLayout
in Unknown (created by Route())
in Suspense (created by Route())
in Route (created by Route())
in Route() (created by ContextNavigator)
in RNCSafeAreaProvider (created by SafeAreaProvider)
in SafeAreaProvider (created by wrapper)
in wrapper (created by ContextNavigator)
in ThemeProvider
in EnsureSingleNavigator
in BaseNavigationContainer
in NavigationContainerInner (created by ContextNavigator)
in ContextNavigator (created by ExpoRoot)
in ExpoRoot (created by App)
in App (created by ErrorOverlay)
in ErrorToastContainer (created by ErrorOverlay)
in ErrorOverlay (created by withDevTools(ErrorOverlay))
in withDevTools(ErrorOverlay)
in RCTView (created by View)
in View (created by AppContainer)
in RCTView (created by View)
in View (created by AppContainer)
in AppContainer
in main(RootComponent)

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.5

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone

**Comment by theKashif** [comment]
Hi family, I was facing the same issue when i updated my expo from 50 to 52 and on my side the bug got resolved when I changed the provider from "PROVIDER_GOOGLE" to "PROVIDER_DEFAULT". So just import "PROVIDER_DEFAULT" and use "PROVIDER_DEFAULT" instead of "PROVIDER_GOOGLE".

   `<MapView provider={PROVIDER_DEFAULT}></MapView>`

**version**

 1. "expo": "^52.0.18",
 2. "react-native": "0.76.5",
 3. "react-native-maps": "1.18.0",

[![enter image description here][1]][1]
    


  [1]: https://i.sstatic.net/zO2uwZc5.png


cc: @sbipinkandari02

**Comment by RyanTG** [comment]
Is this issue spam? Why are there four issues for the same thing created on the same day?

Also, isn’t this documented? https://expo.dev/changelog/2024/11-12-sdk-52#deprecations

**Comment by salah-ghanim** [comment]
see https://github.com/react-native-maps/react-native-maps/issues/5206

we will need to solve this among other issues to be able to support new arch fully, (currently in progress)
