### ISSUE TITLE
google maps problem on iOS

### ISSUE THREAD

**Issue by Ahmeth4n** [react-native-maps/react-native-maps#5291]
### Summary

there is no problem when you use _PROVIDER_DEFAULT_ as provider or when you do not specify a provider. Apple Maps opens by default on iOS, and Google Maps opens on Android devices. 

but if we want to use PROVIDER_GOOGLE as provider on iOS, we get an error like this;

<img width="1083" alt="Ekran Resmi 2024-12-17 23 34 07" src="https://github.com/user-attachments/assets/e3025749-0cca-4f96-9bf5-3d44ff047324" />

### Reproducible sample code

```TSX
import React from 'react';
import { SafeAreaView, StyleSheet, View } from 'react-native';
import MapView, { MapViewProps, PROVIDER_GOOGLE } from 'react-native-maps';

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <SafeAreaView>
        <MapView style={styles.map as MapViewProps['style']} 
        provider={PROVIDER_GOOGLE} />
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

we got error when we add provider={PROVIDER_GOOGLE} line on iOS

### Expected result

works with google maps

### Actual result

 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in AIRGoogleMap (created by MapView)
    in MapView (created by HomeScreen)
    in RCTSafeAreaView (created by HomeScreen)
    in RCTView (created by View)
    in View (created by HomeScreen)
    in HomeScreen
    in Unknown (created by Route(index))
    in Suspense (created by Route(index))
    in Route (created by Route(index))
    in Route(index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabNavigator)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator
    in Unknown (created by TabLayout)
    in TabLayout
    in Unknown (created by Route((tabs)))
    in Suspense (created by Route((tabs)))
    in Route (created by Route((tabs)))
    in Route((tabs)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by NativeStackNavigator)
    in RNSScreenContentWrapper (created by ScreenContentWrapper)
    in ScreenContentWrapper (created by DebugContainer)
    in DebugContainer
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen
    in ScreenStackItem (created by SceneView)
    in SceneView (created by NativeStackView)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in Unknown (created by ScreenStack)
    in ScreenStack (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by RootLayout)
    in ThemeProvider (created by RootLayout)
    in RootLayout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.5

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone SE Simulator

**Comment by rkuhl** [comment]
Had the same issue when using Expo Go which does not support Google Maps any more. 
What I did (could help you if you are using ExpoGo):
- created an project in Google Api Console and enabled the `Google Maps iOS SDK` for this project
- created an API key (in Google Api Console > Credentials) restricted to use with my app
- placed the API key in my app.json under: ios.config.googleMapsApiKey as described [here](https://docs.expo.dev/versions/latest/sdk/map-view/)
- created and expo developement build to test and work on the app using the iOS Simulator
This worked in my case. Good luck

**Comment by saramiap** [comment]
https://docs.expo.dev/versions/latest/sdk/map-view/

**Comment by salah-ghanim** [comment]
@Ahmeth4n this is a a side effect of you trying to use the current lib which doesn't support new arch with react-native new arch.

see https://github.com/react-native-maps/react-native-maps/issues/5206

we will need to solve this among other issues to be able to support new arch fully, (currently in progress)
