### ISSUE TITLE
New architecture still not supported in React native maps

### ISSUE THREAD

**Issue by Ashutosh-107** [react-native-maps/react-native-maps#5293]
### Summary

I am using expo go. While prebuild the build is successful but the app crashes. In expo doctor it is showing new architecture not supported - React Native Maps

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
});
```

### Steps to reproduce

Run  npx eas build -p android --profile preview

### Expected result

App should run properly without crashing.

### Actual result

App gets crashed after launch.

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.76.2

### What version of Expo are you using?

SDK 52

### Device(s)

Samsung S23, Oneplus Nord 4

### Additional information

Please support

**Comment by contactsimonwilson** [comment]
Yes, it's still not supported and is both mentioned in the readme and the pinned issue.
Refer to #5206

**Comment by salah-ghanim** [comment]
thanks @contactsimonwilson 

closing since no point in duplication

**Comment by serajhhh** [comment]
Have A Same Error
