### ISSUE TITLE
Expo Sdk 49 issue, map version 1.7.1`

### ISSUE THREAD

**Issue by pk-il** [react-native-maps/react-native-maps#5302]
### Summary

While I'm trying to install the app on iso I'm getting towo errors
1. While building module 'GoogleMapsUtils':
In file included from <module-includes>:2:
/Users/prashantkamboj/Library/Developer/Xcode/DerivedData/AppmakerRuntime-drlawrimwauxomdtjvufuqgpakvq/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils-framework/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:331:2: error: unsupported Swift architecture
  331 | #error unsupported Swift architecture
      |  ^

2. The following build commands failed:
    PrecompileModule /Users/prashantkamboj/Library/Developer/Xcode/DerivedData/AppmakerRuntime-drlawrimwauxomdtjvufuqgpakvq/Build/Intermediates.noindex/ExplicitPrecompiledModules/GoogleMapsUtils-8ZHMRVRI3TY3QO9QIGNO6JFWA.scan

Pod File changes

pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

 rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  

Added the changes in AppDelegate.m as well

expo version 

"expo": "^49.0.0",

### Reproducible sample code

```TSX
Nothing Currently
```

### Steps to reproduce

App not installing

### Expected result

Shoud be sucessfuly installed

### Actual result

Not installing the app on ios

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.72.1

### What version of Expo are you using?

SDK 49

### Device(s)

iPhone 16 pro simulator

### Additional information

expo version

"expo": "^49.0.0",

**Comment by salah-ghanim** [comment]
@pk-il you're using wrong version of react-native with the lib

see: https://github.com/react-native-maps/react-native-maps?tab=readme-ov-file#version-requirements

**Comment by pk-il** [comment]
@salah-ghanim  The Other version is not working with the expo sdk 49
