### ISSUE TITLE
[Alpha] Build failure after v1.21.0-alpha.7

### ISSUE THREAD

**Issue by Abdulmalick-Dimnang** [react-native-maps/react-native-maps#5311]
### Summary

v1.21.0-alpha.6 has a fix for codegen path. However, after this version, it's point to an incorrect path

<img width="1263" alt="Screenshot 2024-12-29 at 4 18 00 PM" src="https://github.com/user-attachments/assets/856cc403-5a4a-4637-b3fc-e31ce860df3e" />

### Reproducible sample code

```TSX
import React from 'react';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <MapView
      style={{flex: 1}}
      initialRegion={{
        latitude: 42,
        longitude: 30,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
}
```

### Steps to reproduce

- Install fresh RN project with new arch turned on
- Install react-native-maps using v1.21.0-alpha.9
- Bundle install
- Bundle exec pod install will throw error

### Expected result

pod install is expected to be successfully installed

### Actual result

invalid codegen path using `src/specs` instead of `lib/specs`

### React Native Maps Version

1.21.0-alpha.9

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 15 Pro

**Comment by salah-ghanim** [comment]
@Abdulmalick-Dimnang alpha is alpha for a reason, please keep track in the pinned issue 

https://github.com/react-native-maps/react-native-maps/issues/5206
