### ISSUE TITLE
[help wanted] onPress events for Marker children?

### ISSUE THREAD

**Issue by IamJoseph** [react-native-maps/react-native-maps#987]
```
lostHandler = () => {
  console.log('clickity');
}

{this.props.markers.map((marker, i) => {
  return(
    <Marker coordinate={marker.cordinate}  key={i}>
      <Callout tooltip>
        <TouchableHighlight onPress= {lostHandler} underlayColor='#dddddd'>
          <View>
            <Text>Lost</Text>
          </View>
        </TouchableHighlight>        
      </Callout>
  )
})}
```
I'll create something like the above with/without the Callout component and I cannot get the onPress handler to fire. Ideally I'd like to create a small form with two buttons that will determine the marker's content upon clicking. What is actually happening is the onPress handler only seems to fire for the Marker container but none of it's children (with the exception of Callout if included).

**Comment by IamJoseph** [comment]
I'm hoping to do something similar to Waze here... but with different functionality of course
![Waze](http://i.imgur.com/uG05gxD.png)

**Comment by ilyadoroshin** [comment]
+1 callout children are not clickable.. callout intercepts the press event

**Comment by lulubun** [comment]
Markers and Animated.Views onPress not working on most versions of IOS. I've checked with all simulators and this is the result:
5s - ok
6 - ok
6+ - ok
6s - not working
6s+ - not working
7 - not working
7+ - not working
8 - not working
8+ - not working
SE - ok
x - not working

Android is having it's own set of crazy issues but it seems to work on Android w/o issues. Any suggestions??

**Comment by alvelig** [comment]
#1556

**Comment by lulubun** [comment]
Not callouts - custom animated views.

**Comment by nathmack** [comment]
Having the exact same issue. I require multiple buttons in my callout.

```
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-maps": "^0.19.0"
```

my example code:
```
return (
  <MapView.Callout
    style={ styles.container }
    tooltip={ true }
    onPress={ () => console.log('hello 1') }
  >
    {
      actions.map(action => (
        <TouchableOpacity
          key={ action }
          onPress={ () => console.log('hello 2') }
          style={ styles.buttons }
        >
          <Text style={ styles.buttonText }>
            { action }
          </Text>
        </TouchableOpacity>
      ))
    }
  </MapView.Callout>
)
```

`onPress` from the `Callout` gets triggered fine, but the children's (`TouchableOpacity`) onPress functions are never called

**Comment by hegelstad** [comment]
Did anybody solve this?

I've understood that the custom marker children onPresses will trigger if the part being pressed is within the Markers viewbox. I have been unable to increase the size of the marker viewbox, so still nothing on this issue.

**Comment by filipef101** [comment]
Bump

**Comment by nathmack** [comment]
I explored this issue a bit here: https://github.com/react-community/react-native-maps/issues/2508
It seems to me that the issue only occurs when setting `provider={PROVIDER_GOOGLE}` on the `MapView` component, I get the expected behaviour when `provider` is not set

**Comment by 18clans** [comment]
Any solution to this yet?

**Comment by KaneLabs** [comment]
f

**Comment by swapanil** [comment]
Why is Airbnb not fixing this issue for android?

**Comment by rborn** [comment]
@swapanil because this is a community module so WE should fix it, not them

**Comment by swapanil** [comment]
> @swapanil because this is a community module so WE should fix it, not them

Do you find any workaround?

**Comment by rborn** [comment]
> > @swapanil because this is a community module so WE should fix it, not them
> 
> Do you find any workaround?

nope

**Comment by madhums** [comment]
I am also experiencing this issue and I would like to help solve it. I don't have much experience with ObjectiveC or Java but I could invest some time.Before I go ahead and do that, does anyone know exactly where the problem is and what needs to be done?

**Comment by deluxestriker** [comment]
> > @swapanil because this is a community module so WE should fix it, not them
> 
> Do you find any workaround?

There is a workaround. You can use a CalloutSubview Component in the Callout itself. The CalloutSubview Component has a onPress-Listener which works fine (FOR iOS).
Example:

```
<Callout style={styles.container}>
                    <CalloutSubview style={styles.container}
                    onPress={()=> SOME_EVENTS}>
                        <TouchableOpacity title="X" style = {styles.buttonContainer}>
                            <Text>X</Text>
                        </TouchableOpacity>
                    </CalloutSubview>
</Callout>
```
Now you can have a working Button in a Callout. BUT the CalloutSubview only works for iOS.
So there are two ways I can think of to produce iOS and Android Apps.
1.) As far as I know Button in Callouts work on Android. So you could export two different projects.
2.) DON'T KNOW IF POSSIBLE, but if the CalloutSubview gets rendered on Android you could place a onPress method on the Button and the CalloutSubview. So, on both OS you could perform actions onPress.

I hope this helps someone :)

**Comment by swapanil** [comment]
> > > @swapanil because this is a community module so WE should fix it, not them
> > 
> > 
> > Do you find any workaround?
> 
> There is a workaround. You can use a CalloutSubview Component in the Callout itself. The CalloutSubview Component has a onPress-Listener which works fine (FOR iOS).
> Example:
> 
> ```
> <Callout style={styles.container}>
>                     <CalloutSubview style={styles.container}
>                     onPress={()=> SOME_EVENTS}>
>                         <TouchableOpacity title="X" style = {styles.buttonContainer}>
>                             <Text>X</Text>
>                         </TouchableOpacity>
>                     </CalloutSubview>
> </Callout>
> ```
> 
> Now you can have a working Button in a Callout. BUT the CalloutSubview only works for iOS.
> So there are two ways I can think of to produce iOS and Android Apps.
> 1.) As far as I know Button in Callouts work on Android. So you could export two different projects.
> 2.) DON'T KNOW IF POSSIBLE, but if the CalloutSubview gets rendered on Android you could place a onPress method on the Button and the CalloutSubview. So, on both OS you could perform actions onPress.
> 
> I hope this helps someone :)

Thanks

**Comment by n3rd253** [comment]
@deluxestriker is there any work around for rendering this in Android?

**Comment by valeriik** [comment]
...even if I added a CusomView above the map component and recalculating coordinates via **pointForCoordinate** and **onRegionChange/onRegionChangeComplete** it works really laggy on Android... iOS better but with still bad performance...

**Comment by valeriik** [comment]
"bot added the stale label on 2 Oct 2020" - stale?? really??

**Comment by alvelig** [comment]
@valeriik This is Google Maps restriction. Note:
> Note: The info window that is drawn is not a live view. The view is rendered as an image
https://developers.google.com/maps/documentation/android-sdk/infowindows#custom_info_windows

So, you better leave a comment there. This won't fix until Google Maps for Android change it.
